### ISSUE TITLE
Seeking past ~27 hours in a twitch HLS vod causes playback to get stuck

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#7816]
### Important Information

Provide following Information:
- mpv version: `mpv 0.32.0-545-g7174c063de-dirty`
- Platform and Version: Gentoo Linux
- Source of the mpv binary: live ebuild

### Reproduction steps

Works:
```
$ mpv --no-config https://www.twitch.tv/videos/642000020 -start 26:00:00
```

Doesn't work:
```
$ mpv --no-config https://www.twitch.tv/videos/642000020 -start 27:00:00
```

It's not tied to `-start` specifically, the same bug occurs when attempting to seek past the ~27 hour point in the OSC.

### Log file

- `-start 27:00:00` (broken): http://dpaste.com/2BR34CN.txt
- `-start 26:00:00` (working): http://dpaste.com/3ZQEBVD.txt
- `-start 26:00:00` + seek to 28h (broken): http://dpaste.com/15KTV6R.txt

In the last log you can see that it even causes the seek logic to get permanently 'stuck', I tried re-issuing a seek to an earlier part to the video (something that normally works), which got ignored - while the demuxer kept on spamming the same repetitive log lines from the previous seek request.

### Sample files

https://www.twitch.tv/videos/642000020 triggers the issue for me, but I don't know how specific it is to twitch. Definitely seems to be related to HLS though.

**Comment by haasn** [comment]
I'm guessing this is most likely an upstream ffmpeg issue but I thought you might want to at least take a look at it.

**Comment by haasn** [comment]
Confirming this is an ffmpeg bug, I can reproduce it with `ffplay`:

Works:
```
$ ffplay -ss 26:00:00 https://dqrpb9wgowsf5.cloudfront.net/3807ae2b7e6f9cce86d1_nasamarathon_38494380224_1474802884/chunked/index-dvr.m3u8
```

Doesn't work:
```
$ ffplay -ss 27:00:00 https://dqrpb9wgowsf5.cloudfront.net/3807ae2b7e6f9cce86d1_nasamarathon_38494380224_1474802884/chunked/index-dvr.m3u8
```

**Comment by haasn** [comment]
Looking at it in more depth, it seems like the actual issue here might be a bug in twitch's encoding setup?

Inspecting the raw packets being delivered by ffmpeg, it gets stuck because the packet DTS wraps around at `2^33` (`8589934592`, which under the MPEG timebase of `90000` corresponds to a playback time of around `95443.71` seconds, or `26:30:44`, although experimentally it gets stuck even with some timestamps around a minute before this)

Looking at the [MPEG-PES specification](https://en.wikipedia.org/wiki/Packetized_elementary_stream#Optional_PES_header) it seems as though it's designed to carry timestamps larger than 33 bits by encoding them in a 5-byte (40-bit) format, and indeed ffmpeg parses them correctly - it's just that the actual data contained in the twitch vod's packet encodes a 33-bit wrapped DTS.

Possibly their internal mixing setup has some component that's designed to only handle 33 bit timestamps, which they then wrap around and send out to clients. Side note, this also means that *playback should get stuck at around this duration*, which we can experimentally verify to be the case:

```
$ mpv --no-config https://www.twitch.tv/videos/642000020 -start 26:29:00
```

Playback suddenly gets stuck at around `26:29:40.610`, whereupon the terminal is flooded with error messages.

Reclassifying this as invalid/broken file.

**Comment by haasn** [comment]
If anybody else ever ends up hitting this bug, I wrote a hack patch to work around this garbage, in theory allowing me to at least *watch* twitch VODs.

```diff
From 1cc14241bba00024b7f95ebe512630fde57ba790 Mon Sep 17 00:00:00 2001
From: Niklas Haas <git@haasn.xyz>
Date: Tue, 9 Jun 2020 05:25:47 +0200
Subject: [PATCH] (HACK) avformat/hls: work around buggy twitch VODS

Do this by forcibly wrapping the requested seek timestamp at 2^33,
thereby recreating a bug in twitch's horrible mess of an encoding setup.

This allows seeking into HLS streams longer than 26 hours, although
actually attempting to *play* past the rollover point will most likely
still completely break. (But to be fair, so does the official twitch web
player...)

The actual magic constant we use may be wrong in arbitrary ways, so the
requested seek point might deviate from the place ffmpeg actually ends
up seeking to. YMMV.
---
 libavformat/hls.c | 17 ++++++++++++++---
 1 file changed, 14 insertions(+), 3 deletions(-)

diff --git a/libavformat/hls.c b/libavformat/hls.c
index 3e35d157ad..efc50d256c 100644
--- a/libavformat/hls.c
+++ b/libavformat/hls.c
@@ -2240,7 +2240,8 @@ static int hls_read_seek(AVFormatContext *s, int stream_index,
     int i, seq_no;
     int j;
     int stream_subdemuxer_index;
-    int64_t first_timestamp, seek_timestamp, duration;
+    int64_t first_timestamp, seek_timestamp, seek_timestamp_fixed, duration;
+    const uint64_t ts33 = (UINT64_C(1) << 33) * AV_TIME_BASE / 90000;
 
     if ((flags & AVSEEK_FLAG_BYTE) || (c->ctx->ctx_flags & AVFMTCTX_UNSEEKABLE))
         return AVERROR(ENOSYS);
@@ -2279,6 +2280,16 @@ static int hls_read_seek(AVFormatContext *s, int stream_index,
     seek_pls->cur_seq_no = seq_no;
     seek_pls->seek_stream_index = stream_subdemuxer_index;
 
+    // XXX: Twitch vods contain mangled timestamps that wrap around at 2^33, so
+    // horrifically hack around the bug by recreating the same bug.
+    seek_timestamp_fixed = seek_timestamp % ts33;
+    if (seek_timestamp_fixed != seek_timestamp) {
+        av_log(s, AV_LOG_WARNING, "Requested seek index above 2^33, wrapping "
+               "around to work around twitch bugs!\n"
+               "original seek timestamp = %"PRIu64", wrapped = %"PRIu64"\n",
+               seek_timestamp, seek_timestamp_fixed);
+    }
+
     for (i = 0; i < c->n_playlists; i++) {
         /* Reset reading */
         struct playlist *pls = c->playlists[i];
@@ -2295,7 +2306,7 @@ static int hls_read_seek(AVFormatContext *s, int stream_index,
         /* Flush the packet queue of the subdemuxer. */
         ff_read_frame_flush(pls->ctx);
 
-        pls->seek_timestamp = seek_timestamp;
+        pls->seek_timestamp = seek_timestamp_fixed;
         pls->seek_flags = flags;
 
         if (pls != seek_pls) {
@@ -2309,7 +2320,7 @@ static int hls_read_seek(AVFormatContext *s, int stream_index,
         }
     }
 
-    c->cur_timestamp = seek_timestamp;
+    c->cur_timestamp = seek_timestamp_fixed;
 
     return 0;
 }
-- 
2.27.0

```

Unfortunately, while this makes `ffplay` work, mpv still gets stuck on trying to seek. I'll see if I can figure out why.

**Comment by haasn** [comment]
> Unfortunately, while this makes ffplay work, mpv still gets stuck on trying to seek. I'll see if I can figure out why.

Figured it out. The problem is that HR seeks still don't work, because mpv doesn't like the fact that the timestamps are all wrapped. Can work around it using `--hr-seek=no`.

Finally, I can watch my shitty speedrun VoDs.

**Comment by wm4** [comment]
I would expect ffmpeg to make HLS timestamps linear, so not our problem.
Seeking with timestamps going backwards isn't supported by ffmpeg or mpv; if it were up to mpv, I'd always linearize the incoming timestamps.

**Comment by ZaquL** [comment]
> a playback time of around `95443.71` seconds, or `26:30:44`, **although experimentally it gets stuck even with some timestamps around a minute before this**

This bug about NEAR rollover: https://trac.ffmpeg.org/ticket/7449

> Seeking with timestamps going backwards isn't supported by ffmpeg or mpv; if it were up to mpv, I'd always linearize the incoming timestamps.

AVSEEK_FLAG_BACKWARD is supported now (https://github.com/FFmpeg/FFmpeg/commit/e78d0810d1741535c95e5ae0f198977626b1cdff), but is still broken for fmp4 (https://trac.ffmpeg.org/ticket/7359). Only ts segments work nice (even that only after https://github.com/FFmpeg/FFmpeg/commit/92053aa26053b941a027a4fc56674d7d86ba1e58).
