### ISSUE TITLE
Can't load https files using self-signed certificate

### ISSUE THREAD

**Issue by CogentRedTester** [mpv-player/mpv#7817]
### Important Information

I'm trying to load a file over an https server that I am running on the local network using a self signed certificate. It used to work on an older build, but it has now stopped.

Provide following Information:
```
mpv 0.32.0-547-g12415db3a6 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jun  7 21:26:43 +08 2020
FFmpeg library versions:
   libavutil       56.50.100
   libavcodec      58.90.100
   libavformat     58.44.100
   libswscale      5.6.101
   libavfilter     7.84.100
   libswresample   3.6.100
FFmpeg version: git-2020-06-07-d09c3567
```
Windows 10 Build 19041

mpv binary sourced from the [Shinchiro builds](https://sourceforge.net/projects/mpv-player-windows/files/)

I went back through old Shinchiro binaries, and the problem started somewhere between commits 685bd6a and 102a083

### Reproduction steps

Run a local https server using a self-signed certificate. Try to play a file from it. There may be more to this issue, but I don't have any other servers to test this with.

### Expected behavior
mpv will play the file, like in this older build: 

![old version](https://user-images.githubusercontent.com/57207260/84101505-3e246e00-aa4d-11ea-85e8-bc6845da9d0c.png)

### Actual behavior
mpv prints `[ffmpeg] tls: (null)` and exits:

![broken version](https://user-images.githubusercontent.com/57207260/84101587-73c95700-aa4d-11ea-9971-a91535e799ed.png)

Perhaps this is an issue with a new ffmpeg build?

### Log File

[log.txt](https://github.com/mpv-player/mpv/files/4749705/log.txt)

**Comment by wm4** [comment]
Clearly a ffmpeg thing.
