### ISSUE TITLE
mpv doesn't use intel media driver

### ISSUE THREAD

**Issue by linusheinz** [mpv-player/mpv#7818]
I try to set up hardware acceloration with intel-media driver on a skylake cpu but mpv doesn't seem to find it 
mpv version:

`mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.3`

mpv conf:

`profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
hwdec=auto 
gpu-api=vulkan`

when I play a  video it uses xv:
` (+) Video --vid=1 (*) (h264 1024x768 30.000fps)
 (+) Audio --aid=1 (*) (aac 1ch 44100Hz)
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.
[ffmpeg] AVHWDeviceContext: Cannot load libcuda.so.1
[ffmpeg] AVHWDeviceContext: Could not dynamically load CUDA
Using hardware decoding (vaapi-copy).
[autoconvert] Converting nv12 -> yuv420p
AO: [pulse] 44100Hz mono 1ch float
VO: [xv] 1024x768 yuv420p
[vo/xv] X11 can't keep up! Waiting for XShm completion events...

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

Exiting... (Quit)`

**Comment by wm4** [comment]
Your linux installation is completely broken. Wipe your disk, install Ubuntu (or any other "safe" distro choice), then it'll work.

**Comment by CounterPillow** [comment]
you also didn't actually provide a full log file, which would likely show Vulkan failing to initialise.

**Comment by wm4** [comment]
Probably the least of his problems.
