### ISSUE TITLE
MPV on windows restart playbacks in paused status

### ISSUE THREAD

**Issue by Sa-ghosts** [mpv-player/mpv#7819]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20200607-git-12415db
- Windows Version:  Windows 10 Home 1909
- Source of the mpv binary:  Windows builds by shinchiro https://sourceforge.net/projects/mpv-player-windows/files
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
1- Set mpv to keep open in your mpv.conf: 'keep-open'
2- Create this key binding: '`<key>` seek 0 absolute-percent; set pause no' (mine is set to a) in your input.conf
3- Start a video and move to the end, make sure the video is fully finished.
4- Press your previously set key binding.

### Expected behavior
After pressing the key binding the video will restart. (this is what currently happens in linux)
 
### Actual behavior
Mpv will go back to the begning of the video but the the video won't start and you have to press the space bar or press the keybinding again for the video to restart.

### Additional informations
There was a similar issue to mine #3001 and according to that issue is was fixed with this commit: [fcf0b80](https://github.com/mpv-player/mpv/commit/fcf0b80dc9dd3ed29e45451bda6315ce0c2b4729)

**Comment by wm4** [comment]
Seems like I just "accidentally" reverted the fix.
