### ISSUE TITLE
Option to automatically reload on file change? 

### ISSUE THREAD

**Issue by notevenaperson** [mpv-player/mpv#7820]
Can mpv automatically reload the image/video stream currently playing when the underlying file changes?

**Comment by wm4** [comment]
Seems unlikely. Also directly conflicts with the "playing while downloading" use-case. For external files like subtitles, the ``sub-reload`` command exists. For the main file, a ``reload`` command could be added (it doesn't exist yet), though you could also just use ``write-watch-later-config ; loadfile ${path}`` (unteststed).

**Comment by pbaykalov** [comment]
`write-watch-later-config ; loadfile ${path}` works fine, thanks
