### ISSUE TITLE
Blue background when playing HDR videos with mesa 20.1.0

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#7823]
### Important Information

Provide following Information:
- mpv version: mpv 0.32.0-550-g44ad00ba10 - git
- Linux Distribution and Version: Arch - 5.6.15 - Openbox - Mesa 20.1.0
- Hardware: AMD Ryzen 3 2200g - Vega 3

### Reproduction steps

Play an HDR file with mesa 20.1.0 installed

### Expected behavior
File should play fine (with tone mapping applied)

### Actual behavior
A blue screen will occur, audio is playing fine, OSD is not working either
Log shows shader errors

### Log file
[shader-compile-problem.txt](https://github.com/mpv-player/mpv/files/4758668/shader-compile-problem.txt)

### Sample files
Any HDR file (only h265 encoding tested)

**Comment by Mitzsch01** [comment]
Thanks! :)
