### ISSUE TITLE
segfault when loading m3u8 with particular characters in a title

### ISSUE THREAD

**Issue by tonycpsu** [mpv-player/mpv#7826]
### Important Information

Provide following Information:
- mpv version **c7fe4ae**
- macOS Version **10.15.4**
- Source of the mpv binary or bundle **homebrew**
- If known which version of mpv introduced the problem **not sure**
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Download [this m3u8 file](https://gist.githubusercontent.com/tonycpsu/3d167c573e36dba2df1f130724105c73/raw/02b608a0f4c72071511b3b950caaedd1b0ff6baa/test.m3u8) and try to play it.  I get a seg fault every time.  I've isolated it to the title containing a unicode heart.

### Expected behavior

no segfault

### Actual behavior

segfault

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4762761/output.txt)

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

None needed to reproduce.

**Comment by Akemi** [comment]
works here without problems. the crash report or a backtrace would be nice to have. though my guess, the problem is more likely related to libass. i tested with libass master. what's your version?

**Comment by tonycpsu** [comment]
> what's your version?

``` $ brew info libass                                                                                                                                                                                                          
libass: stable 0.14.0 (bottled), HEAD
Subtitle renderer for the ASS/SSA subtitle format
https://github.com/libass/libass
/usr/local/Cellar/libass/0.14.0_1 (10 files, 522KB) *
  Poured from bottle on 2020-05-19 at 23:46:07
```

Upgrading to master with `brew unlink libass; brew install --HEAD libass` does indeed fix it.  Thanks!

**Comment by Akemi** [comment]
it was probably this PR (https://github.com/libass/libass/pull/359) that fixed your problem. just as reference if anyone stumbles upon this issue too.
