### ISSUE TITLE
(Most) Random Videos freeze early on in Windows when run from CreateProcess()

### ISSUE THREAD

**Issue by time-killer-games** [mpv-player/mpv#7829]
### Important Information

Provide following Information:
- 0.32.0.484-g152b0e2a8c
- verified on Windows 7 and 10

### Reproduction steps
- Create a blank Win32 Desktop app with a single window in main()
- Call CreateProcess() (with proper UTF8 support if needed) on mpv.exe
- Make sure CreateProcess() to run mpv.exe with a video file opened in it
- most videos will freeze when mpv is embedded in your app's window
OR
- download example.zip below under "Sample Files"
- with example.zip i provided, load example2.mp4 which freezes; example1.mp4 doesn't.
- loading mp4 can be done by drag and drop on window created by running example.exe
- you can also load an mp4 by left click on that window which creates an open file dialog 
- note - The example exe doesn't support UTF-8 in the path it is being run from so extract it somewhere like root C:\ if your machine has non-english characters, but loading the video will work from any location because that does support UTF-8. This is a limitation of a software I wrote it in. I have tried this in a number of different software, both with MinGW and MSVC as the compiler. It freezes regardless, even in an empty C++ project with minimum requirements to reproduce.

### Expected behavior
all supported video files and codecs don't freeze randomly

### Actual behavior
most videos supported freeze early on in playback at random. you may also download youtube videos with default format/codecs and in most cases it will freeze using my example exe. 

### Log file
https://pastebin.com/7kJSPvSf

### Sample files
http://0x0.st/iWzW.zip

**Comment by wm4** [comment]
Does this also happen without -wid?

**Comment by time-killer-games** [comment]
No, only with --wid in my experience. Also, sorry for that rude last remark at the bottom of my ticket, I was a little grouchy. I'll see if I can upload it using your preferred method.

**Comment by time-killer-games** [comment]
Turns out this was a problem with how i wrote my test program lel
