### ISSUE TITLE
Parameters per item in .m3u playlist for rtsp:// ?

### ISSUE THREAD

**Issue by ropucyka** [mpv-player/mpv#7830]
```
#EXTM3U
#EXTINF:-1,Cam
rtsp://12.34.56.78:9101/vod/video.sdp -video-aspect-override=4:3
```

Stream working but ignoring option -video-aspect-override=4:3. It's not possible?

Then what about parsing #MPVCONF tag feature in .m3u playlists?
Example:
```
#EXTM3U
#EXTINF:-1,Cam
#MPVCONF --video-aspect-override=4:3 --window_title "Thank you guys for mpv!"
rtsp://12.34.56.78:9101/vod/video.sdp
```

**Comment by wm4** [comment]
Not possible. Setting arbitrary mpv options from playlists wouldn't be safe. You need to find some other way or propose another mechanism.

What you could do as workaround for example: write a script that parses the file title for special directions, and set the m3u entry title accordingly.

**Comment by ropucyka** [comment]
I have another way.
I will tell to 20 people about how to manually set command line parameters.

Spase flights also not safe, but....  Anyway thank you for fast response, really.

**Comment by thebombzen** [comment]
@ropucyka You can provide your own `mpv.conf` file a d use `--include=` to provide it. 

You could also use `auto-profiles.lua` to automatically load certain options for certain files or protocols (like rtsp). If you add auto-profiles.lua, then you could add this to your default config file or something:

```
[protocol.rtsp]
video-aspect-override=4:3
window-title="Sasuga Auto Profiles"
```

**Comment by ropucyka** [comment]
@thebombzen 
mpv can open (read) `.lua` files as input files (like `.mkv`) without command line arguments?
`mpv.exe scrtipt.lua` ?

**Comment by thebombzen** [comment]
@ropucyka no, you add it to `~~/scripts/` where `~~` is the directory containing `mpv.conf`
