### ISSUE TITLE
Not able to reproduce Dolby Vision on (MP4/TS formats) and HDR10 bland image

### ISSUE THREAD

**Issue by CyberPoison** [mpv-player/mpv#7831]
### Important Information

Provide following Information:
- mpv version:v0.32.0
- Platform and Version: Android 
- Source of the mpv binary:libmpv

### Reproduction steps

Compile LibMpv for Android. 

### Expected behavior
Tone maping correction with HDR10 original colors and support for Dolby Vision (MP4 and TS) 

### Actual behavior
I have some issues 
Well at first the MPV on my Huawei P30 Pro and on my Samsung S10+ both with HDR10 have bland image and i need everytime to move to exoplayer because it's only the way where i can get the original quality and good quality without any issues, btw this a comparaison of my image quality of the 

(Plex = exoplayer) & (Emby = MPV)
### HDR

MPV (Emby)
![image](https://user-images.githubusercontent.com/60718477/84534606-8613f100-acea-11ea-8a65-3f08ef9030eb.png)

Exoplayer (Plex)
![image](https://user-images.githubusercontent.com/60718477/84533441-6c71aa00-ace8-11ea-9ad8-ac53bc1ee734.png)

Emby (MPV)
![WhatsApp Image 2020-06-13 at 03 42 03 (1)](https://user-images.githubusercontent.com/60718477/84557112-934fd080-ad28-11ea-9560-c26fa73d13d9.jpeg)
![WhatsApp Image 2020-06-13 at 03 46 29](https://user-images.githubusercontent.com/60718477/84557113-95199400-ad28-11ea-8d11-fb68bbd51211.jpeg)

**_So as you can see there is some image issues on the clouds/Sun bright, projector on the intro etc..._**

### HDR10

![image](https://user-images.githubusercontent.com/60718477/84533573-af338200-ace8-11ea-9b90-bf97d332a69c.png)

**_As you can see the image is Bland, and i'm pretty sure than it's a tone-map issue, because with exoplayer it works well no quality/bland issues._**

### Dolby Vision (MP4 & TS) 

Both (MP4 & TS) Shows me a black screen and looks like it's also from the issue is from MPV because with exoplayer the movie runs well (No black Screen, No bland image, etc...)

I suggest the devs to use exoplayer as a source for the tone maping because the quality is very well and i enjoy it prety sure than many of people here will be enjoy a lots more if the tone map is comparable in better ways than exoplayer. 

### HDR10 Movie Metadata
![image](https://user-images.githubusercontent.com/60718477/84534023-7f38ae80-ace9-11ea-9f08-ae0006b4ac6a.png)

### DV (Dolby Vision MP4) Metadata
![image](https://user-images.githubusercontent.com/60718477/84534084-98d9f600-ace9-11ea-957f-e760ac036b62.png)

Please if needed, tell me for more info.

Equipment (Huawei P30 Pro)
OS:. Android 10
Compatible HDR10:. Yes

### Sample files

Demo for Dolby Vision
[Glass Blowing @59.94fps: Dolby Vision Profile 8.1 UHD – Dolby Atmos](http://media.developer.dolby.com/DolbyVision_Atmos/mp4/P81_GlassBlowing2_3840x2160%4059.94fps_15200kbps_fmp4.mp4)

[Glass Blowing @59.94fps: Dolby Vision Profile 5 UHD for iOS – Dolby Atmos](http://media.developer.dolby.com/DolbyVision_Atmos/mp4/iOS_P5_GlassBlowing2_3840x2160%4059.94fps_15200kbps.mp4
)

### NOTE

Also reported here 

https://github.com/mpv-android/mpv-android/issues/276

**Comment by Akemi** [comment]
this looks a bit like the issue fixed here https://github.com/mpv-player/mpv/pull/7849
if the issue still persists please open a new issue.
