### ISSUE TITLE
ASS subtitle with `YCbCr Matrix: TV.709` header isn't respected on SD video

### ISSUE THREAD

**Issue by fireattack** [mpv-player/mpv#7835]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20200614-git-c7fe4ae
- Windows Version: Win 7 SP1 and Win 10 newest
- Source of the mpv binary https://sourceforge.net/projects/mpv-player-windows/

### Reproduction steps

The test ass file is as following:

601.ass:
```
[Script Info]
ScriptType: v4.00
YCbCr Matrix: TV.601
PlayDepth: 32
Timer: 100.0000
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Big,黑体,60,&H00966432,&H00000000,&H80000000,&H80000000,-1,0,0,0,100,100,0,0,1,0,0,2,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:20.00,Big,,0,0,0,, ■ ■ ■ ■ ■ ■
```
709.ass:
```
[Script Info]
ScriptType: v4.00
YCbCr Matrix: TV.709
PlayDepth: 32
Timer: 100.0000
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Big,黑体,60,&H00966432,&H00000000,&H80000000,&H80000000,-1,0,0,0,100,100,0,0,1,0,0,2,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:20.00,Big,,0,0,0,, ■ ■ ■ ■ ■ ■
```
The only difference is that it uses `YCbCr Matrix: TV.709` instead.

The font color defined is `R,G,B=50,100,150`.

Playing both subtitles with both an SD and an HD video.

### Expected behavior

| Subtitle | Video | Expected   | xy-VSfilter | mpv |
|----------|-------|------------|-------------|-----|
| 601      | HD    | 44,98,152  | ✔️           | ✔️   |
| 709      | HD    | 50,100,150 | ✔️           | ✔️   |
| 601      | SD    | 50,100,150 | ✔️           | ✔️   |
| 709      | SD    | 55,102,148 | ✔️           | ❌   |

### Actual behavior

See above. When using a subtitle with `YCbCr Matrix: TV.709` header and playing an SD video, mpv fails to respect that header. Instead, it still shows the subtitle in `R,G,B=50,100,150` color.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[output.txt](https://github.com/mpv-player/mpv/files/4777663/output.txt)

### Sample files

I can reproduce the bug with any SD resolution videos.

**Comment by Akemi** [comment]
does setting `--sub-ass-vsfilter-color-compat=full` fix it? or possibly a different value.

**Comment by fireattack** [comment]
Yes, this setting fixes it.

**Comment by Akemi** [comment]
i believe it is intended. the default is supposed to be the most backward compatible to version X of vsfilter (even with its bugs). this is the behaviour some/lot of scripts relied upon at that point of time. any change to vsfilter afterwards, in this case xy-VSfilter, fall into the none compat case and should be left in the none default behaviour.

there is still the possibility of a bug, but for now i am going to close it since the current behaviour is the intended one.
