### ISSUE TITLE
Segmentation fault when trying to render Glyph 0x279C using default OSD font on MacOS

### ISSUE THREAD

**Issue by unique-username313** [mpv-player/mpv#7837]
### Important Information
- mpv version: 
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Jun  6 23:26:51 BST 2020
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.3
```
- macOS Version:
macOS Catalina. Version: 10.15.5 (19F101)

- Source of the mpv binary or bundle:
Homebrew. Standard install; `brew install mpv`

- If known which version of mpv introduced the problem
This is the first version of mpv that was installed on this macOS

- Possible screenshot or video of visual glitches
None
### Reproduction steps

1. Open any compatible media file with mpv using default osd-font (sans-serif)
2. - Press F8 to show the playlist **OR**
    - Open console and type `show-text ${chapter-list}` then Enter **OR**
    - Open console and type `show-text ${playlist}` then Enter **OR**
    - Open console and type `show-text ${track-list}` then Enter **OR**
    - Open console and type `show-text ${edition-list}` then Enter **OR**
    - Other commands that display a list with Glyph 0x279, which I assume is the arrow pointing to the currently active element on the list

### Expected behavior

mpv to display a list on the OSD corresponding to the command passed to mpv

### Actual behavior

Crash with segmentation fault

### Log file

[mpv logfile](https://0x0.st/iWpk.txt)
[macOS Crash Report - Backtrace](https://0x0.st/iWpd.txt)

### Sample files

Any compatible file should do

**Comment by ePirat** [comment]
I think this might be what I fixed in https://github.com/libass/libass/commit/517957eb70b757bdc4a51e62feac29095cd667e5

**Comment by unique-username313** [comment]
Yes it looks like it. Was this merged into libass? If yes, why is it still crashing?
Should I close this issue since it’s libass related?

Sorry for these questions but I don’t really know much about github etiquette.

**Comment by CounterPillow** [comment]
>If yes, why is it still crashing?

because you didn't update libass to the latest git commit.

**Comment by unique-username313** [comment]
Oh well then, installing with --HEAD should fix this. Thank you!

**Comment by Akemi** [comment]
duplicate of #7826 and #7257
