### ISSUE TITLE
Command line for play two subtitles at the same time on my videos

### ISSUE THREAD

**Issue by xmha97** [mpv-player/mpv#7842]
Hello,
I am using the least version of MPV on Windows 10.
How I can play two subtitles at the same time on my videos using a command line?
![SMPlayer](https://user-images.githubusercontent.com/23485114/85036340-45f4b880-b199-11ea-97d6-c066e188d6ff.png)
Please help me.

**Comment by Akemi** [comment]
`--secondary-sid=` it's in the manual https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst

**Comment by xmha97** [comment]
Thanks
```
mpv "Inside Out (2015).mkv" -sub-file "Inside Out (2015).en.srt" -sub-file "Inside Out (2015).fa.srt" -secondary-sid 2
```
