### ISSUE TITLE
Playing videos are strange on samsung phones

### ISSUE THREAD

**Issue by fifa87** [mpv-player/mpv#7843]
I have built QT project using your example on android.

I used this recent libraries built by using the following github,
https://github.com/mpv-android/mpv-android
But on all new Samsung phones(Android 9-10) and few phones playing video is strange.
most Other phones are ok.
Please look at this link video.
https://drive.google.com/file/d/1EaVYDEt1_nzC-UjzG1NxWeZPC7CMypzi/view?usp=sharing
https://drive.google.com/file/d/1R5OYsI3rvXPhp0Ppj32Y2K16VCvbe0Ht/view?usp=sharing
are there anyone to help?

I used this options
    mpvSetProperty("hwdec", "auto-safe");

I used Qt.5.14.2. libmpv for android is recent on above github.
This is very urgent. please help me.
Best Regards.

**Comment by wm4** [comment]
The issue template says you shouldn't use google video. You also didn't provide a log.
In general, either the GLES implementation or mediacodec support could be broken either on the phone, or support of it in mpv/ffmpeg - we just don't know. And in general, phones have heavy bugs that are never solved (some software may choose to attempt to work around them).

**Comment by Akemi** [comment]
sry, that is way to vague. if the problem still persists please open a new issue with the infos we ask for.
