### ISSUE TITLE
How to solve the problem of auto pause of fast playback after setting buffer

### ISSUE THREAD

**Issue by levenies** [mpv-player/mpv#7845]
After I set the buffer, I play the HTTP video at multiple speeds. After playing for a while, the player will pause automatically？

Who knows how to set up or solve it?

My environment is: win7 mpv-dev-i686-20200126

Thank you

**Comment by wm4** [comment]
You can use --cache-pause=no to prevent this behavior.
If playback still stops, it's simply because the http connection doesn't provide data fast enough.
