### ISSUE TITLE
[request] option to rewind playback postion to start when playback is finished

### ISSUE THREAD

**Issue by azev** [mpv-player/mpv#7850]
Option to rewind playback postion to start (position 0) when playback is finished.
Something like `rewind-on-finish=yes`

This is a very handy feature when watching a video multiple times. This is **NOT** loop playback, this is different.

**Comment by zhovner** [comment]
Totally agree. This can be default behaviour for `keep-open=yes` or added as new option like `keep-open=restart`.
Here is the old discussion https://github.com/mpv-player/mpv/issues/3666

**Comment by zhovner** [comment]
Seems that we have to do it ourselves. 
@haasn Can you please advice how this feature should be done to be accepted as pull request?

**Comment by oe-d** [comment]
Added a rewind feature to [this script](https://github.com/oe-d/control).

**Comment by Gubith** [comment]
If seek is at end when playback started,  start at the start.  (I want playback to stop at the end,)

So, if playback was saved at 99%,  play plays to the end and stops.  Then, when play pressed, playback starts at the start.

**Comment by Akemi** [comment]
closing since there is a script for this.

**Comment by azev** [comment]
Can someone please post here an script for zoom in/out?
Thanks!
