### ISSUE TITLE
MPV fails to open youtube links from command line

### ISSUE THREAD

**Issue by haydenblair1** [mpv-player/mpv#7851]
### Important Information
MPV fails to open youtube link. I am unsure with with is related to MPV or youtube-dl. I do not know how to interpret the log below. 

- mpv 0.32.0
- PopOS 20.04
- Ubuntu repository 
- i3 with compton
- Nvidia 440.82

### Reproduction steps
Reproduced below with -v and --no-config. 
mpv -v --no-config https://www.youtube.com/watch?v=r3fE6FQT82s

### Expected behavior
MPV to open and play the linked video. 

### Actual behavior
MPV does not open. Need to quit with 'q' to exit prompt. 

### Log file
[cplayer] Command line options: '-v' '--no-config' 'https://www.youtube.com/watch?v=r3fE6FQT82s'
[cplayer] mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.31.100
[cplayer]    libavcodec      58.54.100
[cplayer]    libavformat     58.29.100
[cplayer]    libswscale      5.5.100
[cplayer]    libavfilter     7.57.100
[cplayer]    libswresample   3.5.100
[cplayer] ffmpeg version: 4.2.2-1ubuntu1
[cplayer]
[cplayer] Configuration: ./waf configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --confdir=/etc/mpv --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --enable-dvdnav --enable-libmpv-shared --enable-libsmbclient --enable-sdl2 --enable-sndio --disable-build-date --enable-dvbin
[cplayer] List of enabled features: 52arch aligned_alloc alsa asm atomics caca cdda cplayer cplugins debug-build drm drmprime dvbin dvdnav egl egl-drm egl-helpers egl-x11 fchmod ffmpeg gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack jpeg lcms2 libarchive libass libass-osd libav-any libavcodec libavdevice libavutil libbluray libdl libm libmpv-shared librt libsmbclient linux-fstatfs lua memfd_create optimize oss-audio plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video sndio stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vt.h wayland wayland-protocols x11 xv zlib
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'config' = 'no' (flags = 8)
[cplayer] Waiting for scripts...
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook
[ytdl_hook] not a ytdl:// url
[ffmpeg] Opening https://www.youtube.com/watch?v=r3fE6FQT82s
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[ffmpeg] Mime-type: 'text/html; charset=utf-8'
[demux] Trying demuxers for level=normal.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxers for level=unsafe.
[lavf] No format found, try lowering probescore or forcing the format.
[cplayer] Opening failed or was aborted: https://www.youtube.com/watch?v=r3fE6FQT82s
[cplayer] Running hook: ytdl_hook/on_load_fail
[ytdl_hook] full hook
[cplayer] finished playback, success (reason 3)
[cplayer]
[cplayer]
[cplayer] Exiting... (Quit)
[cplayer] Set property: shared-script-properties -> 1

**Comment by avih** [comment]
This URL works for me.

Please attach a full log. Regardless, I'm guessing you need to update youtibe-dl.

**Comment by haydenblair1** [comment]
> This URL works for me.
> 
> Please attach a full log. Regardless, I'm guessing you need to update youtibe-dl.

Youtube-dl was a few versions behind. Was using version from ubuntu repos. Have updated to the latest version now but the same issue persists. Is this the correct log file below?

` 53 [   0.020][d][global] config path: 'fonts.conf' -/-> '/etc/mpv/fonts.conf'
 52 [   0.020][v][osd/libass] Setting up fonts...
 51 [   0.027][d][ffmpeg] tcp: Starting connection attempt to 2404:6800:4006:80f::200e port 443
 50 [   0.030][v][osd/libass] Using font provider fontconfig
 49 [   0.030][v][osd/libass] Done.
 48 [   0.030][d][cplayer] Run command: define-section, flags=64, args=["input_osc", "", "default"]
 47 [   0.030][d][cplayer] Run command: enable-section, flags=64, args=["input_osc", "allow-hide-cursor+allow-vo-dragging"]
 46 [   0.030][d][cplayer] Run command: define-section, flags=64, args=["input_forced_osc", "", "force"]
 45 [   0.030][d][cplayer] Run command: enable-section, flags=64, args=["input_forced_osc", "allow-hide-cursor+allow-vo-dragging"]
 44 [   0.327][d][ffmpeg] tcp: Starting connection attempt to 142.250.66.238 port 443
 43 [   0.449][d][ffmpeg] tcp: Successfully connected to 142.250.66.238 port 443
 42 [   1.049][d][ffmpeg] resize stream to 131072 bytes
 41 [   1.049][v][ffmpeg] Mime-type: 'text/html; charset=utf-8'
 40 [   1.049][d][ffmpeg] Stream opened successfully.
 39 [   1.049][v][demux] Trying demuxers for level=normal.
 38 [   1.049][d][demux] Trying demuxer: disc (force-level: normal)
 37 [   1.050][d][demux] Trying demuxer: edl (force-level: normal)
 36 [   1.050][d][demux] Trying demuxer: cue (force-level: normal)
 35 [   1.050][d][demux] Trying demuxer: rawaudio (force-level: normal)
 34 [   1.050][d][demux] Trying demuxer: rawvideo (force-level: normal)
 33 [   1.050][d][demux] Trying demuxer: mkv (force-level: normal)
 32 [   1.050][d][demux] Trying demuxer: libarchive (force-level: normal)
 31 [   1.050][d][demux] Trying demuxer: lavf (force-level: normal)
 30 [   1.588][d][ffmpeg] resize stream to 262144 bytes
 29 [   1.771][d][ffmpeg] resize stream to 524288 bytes
 28 [   1.787][d][ffmpeg] resize stream to 1048576 bytes
 27 [   1.797][v][lavf] No format found, try lowering probescore or forcing the format.
 26 [   1.797][d][demux] Trying demuxer: mf (force-level: normal)
 25 [   1.797][d][demux] Trying demuxer: playlist (force-level: normal)
 24 [   1.797][d][demux] Trying demuxer: null (force-level: normal)
 23 [   1.797][v][demux] Trying demuxers for level=unsafe.
 22 [   1.797][d][demux] Trying demuxer: disc (force-level: unsafe)
 21 [   1.797][d][demux] Trying demuxer: edl (force-level: unsafe)
 20 [   1.797][d][demux] Trying demuxer: cue (force-level: unsafe)
 19 [   1.797][d][demux] Trying demuxer: rawaudio (force-level: unsafe)
 18 [   1.797][d][demux] Trying demuxer: rawvideo (force-level: unsafe)
 17 [   1.797][d][demux] Trying demuxer: mkv (force-level: unsafe)
 16 [   1.797][d][demux] Trying demuxer: libarchive (force-level: unsafe)
 15 [   1.797][d][demux] Trying demuxer: lavf (force-level: unsafe)
 14 [   1.816][d][ffmpeg] resize stream to 524288 bytes
 13 [   1.824][d][ffmpeg] resize stream to 1048576 bytes
 12 [   1.832][v][lavf] No format found, try lowering probescore or forcing the format.
 11 [   1.832][d][demux] Trying demuxer: mf (force-level: unsafe)
 10 [   1.832][d][demux] Trying demuxer: playlist (force-level: unsafe)
  9 [   1.832][d][demux] Trying demuxer: null (force-level: unsafe)
  8 [   1.832][d][ffmpeg] AVIOContext: Statistics: 281553 bytes read, 0 seeks
  7 [   1.832][v][cplayer] Opening failed or was aborted: https://www.youtube.com/watch?v=r3fE6FQT82s
  6 [   1.832][v][cplayer] Running hook: ytdl_hook/on_load_fail
  5 [   1.832][v][ytdl_hook] full hook
  4 [   1.832][d][global] config path: 'youtube-dl' -/-> '/home/hayden/.config/mpv/youtube-dl'
  3 [   1.832][d][global] config path: 'youtube-dl' -/-> '/home/hayden/.mpv/youtube-dl'
  2 [   1.832][d][global] config path: 'youtube-dl' -/-> '/etc/mpv/youtube-dl'
  1 [   1.832][d][ytdl_hook] Running: youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo[height<=?1080    ]+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=r3fE6FQT82s
205 [   1.832][d][cplayer] Run command: subprocess, flags=64, args=["youtube-dl,--no-warnings,-J,--flat-playlist,--sub-format,ass/srt/best,-    -format,bestvideo[height<=?1080]+bestaudio/best,--all-subs,--no-playlist,--,https://www.youtube.com/watch?v=r3fE6FQT82s", "yes", "671088    64", "yes", "yes"]`

**Comment by avih** [comment]
No. You see the instructions when you file a new issue: https://github.com/mpv-player/mpv/blob/master/.github/ISSUE_TEMPLATE/3_bug_report.md

**Comment by haydenblair1** [comment]
Sorry I'm not sure how to use the tool listed to share the file. Have linked below.
https://pastebin.com/hSL9BWK8

**Comment by avih** [comment]
Your log is not full. Did you only upload part of the file? Please do the same but with the full log file.

Regardless, please also post the output of the following command: `youtube-dl --version`.

**Comment by haydenblair1** [comment]
Ok I believe this is a complete log. This video successfully played but only have 5+ minutes of waiting.
https://pastebin.com/F9ZNPrxf
The behaviour seems very inconsistent. In this instance after entering the command it returned '[1] 104447' then gave me a new prompt. Then about 5 minutes later the video opened and played. However sometimes nothing is returned and I need to force quit to get a new terminal prompt.

I dont have slow internet. From what I have seen when other people use mpv in this way the video should start playing fairly quickly?

youtube-dl --version 2020.06.16.1

**Comment by haydenblair1** [comment]
Ok so I guess I have been a bit inpatient. In this instance (https://pastebin.com/a5fbD66G) the prompt was left hanging for 5+ minutes and eventually the video opened. 
I guess this is an issue of it being very slow for some reason?

**Comment by avih** [comment]
It seems that youtube-dl ran for more than 4 minutes before returning. From your last log:
```
[   1.887][d][ytdl_hook] Running: youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo[height<=?1080]+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=RG9TMn1FJzc
[   1.887][d][cplayer] Run command: subprocess, flags=64, args=["youtube-dl,--no-warnings,-J,--flat-playlist,--sub-format,ass/srt/best,--format,bestvideo[height<=?1080]+bestaudio/best,--all-subs,--no-playlist,--,https://www.youtube.com/watch?v=RG9TMn1FJzc", "yes", "67108864", "yes", "yes"]
[ 263.607][v][ytdl_hook] youtube-dl succeeded! 
```

What happens when you run this command from your shell?
```
youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --format "bestvideo[height<=?1080]+bestaudio/best" --all-subs --no-playlist -- https://www.youtube.com/watch?v=RG9TMn1FJzc
```

For me it succeeds after about 3 seconds. If for you it takes many seconds, then it's either a youtube-dl issue or something with your internet. On the other hand, if it always completes quickly, then it could be an mpv issue or some weird python issue.

**Comment by haydenblair1** [comment]
That command was slow also. Have just discovered my vpn seems to be contributing to the issue. With my vpn disabled it opens quickly. So I will have to look into why it isn't playing nicely with youtube-dl. 
Thank you very much for taking the time. I really appreciate it. Sorry the issue does not really relate to you.

**Comment by avih** [comment]
Good luck.

**Comment by avih** [comment]
You can try asking at the [youtube-dl](https://github.com/ytdl-org/youtube-dl) project. Maybe they have more info.

**Comment by haydenblair1** [comment]
Enabling Ipv6 in my VPN settings seems to have fixed it. I don't have any understanding of my this was needed I just gave it a try and it worked! 

Thanks for your help.
