### ISSUE TITLE
API to render video output to a buffer in memory

### ISSUE THREAD

**Issue by hjohn** [mpv-player/mpv#7852]
### Expected behavior of the wanted feature

API in libmpv to render the video output to a buffer specified with a memory address, a size (in bytes) and an expected format.  The user would be responsible for allocating memory for the buffer, making sure it is the right size and has the correct alignment.  If the buffer is too small for the video frame, libmpv could either partially fill it or refuse to fill it.

Secondly, a callback or event should be available which informs the user when the buffer contains a new frame.

The use case would be rendering directly to an Image buffer in systems which donot expose details like OpenGL/Direct3d contexts (or even which type is in use), HWND or window id's.  VLC also offers such an option

**Comment by wm4** [comment]
Such a thing could be possibly added as a backend to the render API. Until now, there hasn't been such an API because it's going to be slow, with software CPU color conversion and scaling to RGB and such. Can I ask what the exact use case beyond not wanting to use GL etc. is?

**Comment by hjohn** [comment]
The use case would be putting the video stream into a `PixelBuffer` which is available for JavaFX 13+.  Once it is there, it can be composited into a UI in any way you want (positioning, scaling, rotation, post effects) as well as making it possible to overlay content over the video.  As JavaFX is platform independent, it offers no access to OpenGL or D3D.  With the `PixelBuffer` it does offer however a way to manipulate a memory area directly.

Currently the only way to integrate MPV for JavaFX is to look up a window id or HWND and provide this via the `wid` parameter.  This only works well under Windows, for Linux I ran into multiple problems related to specific window managers.

From my experience with VLC, the additional overhead seems to be reasonable, and certainly better now than it was (before the introduction of the pixel buffer, a full frame copy was also needed).

**Comment by wm4** [comment]
I still doubt the usefulness of this, but it exists now. There's an example in the mpv-examples repository.

**Comment by alexmercerind** [comment]
Thanks for this feature.

**Comment by viqbgrg** [comment]
Hello, do you have any examples of mpv rendering to PixelBuffer? I don’t know C language, I only know Java.
