### ISSUE TITLE
Indeterministic ordering of shared library dependencies

### ISSUE THREAD

**Issue by mbakke** [mpv-player/mpv#7855]
### mpv version and platform versions

mpv 0.32.0, Python 3.8.2, waf 2.0.19, glibc 2.31, binutils 2.34, GCC 7.5.0, GNU/Linux (Guix)

### Reproduction steps

Build the mpv shared library several times, save a copy of `libmpv.so.1.107.0` for each step.

Investigate the binary with `readelf --wide --dynamic libmpv.so.1.107.0`.  Notice that the order of entries differs between the various builds.

### Expected behavior

Building MPV twice in the same environment always produces bit-identical results.

### Actual behavior

The mpv library is not reproducible.

### Log file

N/A

### Workaround

I found that setting `PYTHONHASHSEED` to a fixed value makes the problem disappear.  A better workaround would be to use `sort()` everywhere these dependencies are enumerated (if any).  Not sure if the problem is with the build scripts or waf itself.

**Comment by wm4** [comment]
Link flags can't be randomized, at least because of static libs. So I wonder what the hell waf is doing there.
