### ISSUE TITLE
Asking for a new release

### ISSUE THREAD

**Issue by fre123ber** [mpv-player/mpv#7856]
I believe that judging by the number of open issues and pull requests there is a lot of refactoring that is being done right now. The build system is not entirely working and there are a lot of structural changes to tackle. So is it premature to ask for an official build, considering that the last mpv version 32.0 was released in January? Maybe setting a place to start could help development. You tell me: maybe you're getting there and many issues are still open to discussion, so it could be that my request is out of place.
Thank you all for the excellent job

**Comment by Akemi** [comment]
> So is it premature to ask for an official build,

we don't and won't provide 'official' builds, only releases/tags.

usually a release happens when it happen, eg when someone feels like it. i don't think we have any known blockers for a release though.
