### ISSUE TITLE
mpv on a virtual console, before startx, with unspecified --vo flag (and defaults to --vo=sdl) does not accept keyboard input when playing a video

### ISSUE THREAD

**Issue by shlomif** [mpv-player/mpv#7859]
### Important Information

Provide following Information:
- mpv version : git master : 22a27c6720244dd24c9b704c8a8225ca1665272f
- Linux Distribution and Version : fedora version 32 x86-64
- Source of the mpv binary: git
- If known which version of mpv introduced the problem
- Window Manager and version: virtual console
- GPU driver and version:                        Intel Iris Plus Graphics 655

- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

I built using

```
waf configure --prefix=/opt/`whoami`/mpv \
    --disable-build-date \
    --enable-libmpv-shared \
    --enable-sdl2 \
    --enable-libarchive \
    --enable-dvdnav \
    --enable-cdda \
    --enable-html-build \
    --enable-dvbin

```

and ran using:

```
/opt/shlomif/mpv/bin/mpv --volume=50 Docs/Images/Videos/Screencasts/kpat-with-fc-solve--screencast/kpat-fcs-with-audio.mkv
```

in a virtual console.

With `--vo=drm` I can press `q` to quit fine

### Expected behavior

Can use the keyboard.

### Actual behavior

No keyboard.

### Log file

Here:

[o2.txt](https://github.com/mpv-player/mpv/files/4833359/o2.txt) - the log file.

### Sample files

E.g:

https://www.shlomifish.org/Files/files/video/kpat-fcs-with-audio.mkv

**Comment by shlomif** [comment]
[o2.txt](https://github.com/mpv-player/mpv/files/4833359/o2.txt) - the log file.

**Comment by Akemi** [comment]
what is the actual problem here. that vo=sdl doesn't  recognise keyboard inputs or that it doesn't default to vo=drm?

**Comment by Dudemanguy** [comment]
This should default to `--gpu-context=drm` now. Quitting with `vo=sdl` in tty works for me as well.
