### ISSUE TITLE
Matroska videos with embedded subtitles, fonts load slowly

### ISSUE THREAD

**Issue by mrcstgt** [mpv-player/mpv#7860]
### Important Information

- mpv-x86_64-20200621-git-dc24a43 by shinchiro
- Windows 10 | Version 1909 | Build 18363.900

### Reproduction steps

Play at least two video files with embedded subtitles (in this case .mkv) and click the next button. 

### Expected behavior

The second video should play without delay.

### Actual behavior

(1) mpv freezes for around a minute and then plays the next video. 

It will once again freeze when loading the first subtitle line and play smoothly afterwards until the next video plays and then (1).

### Log file

[Uploading output.txt…]

[Pastebin url ](https://pastebin.com/6FYE87rG) of log contents in case log file attachment fails.

Encountered this issue while playing local files of anime with muxed fonts and subtitles. I suspect that this is a problem with the subtitles but the same video files, when played using other players play smoothly and proceed to the next file without the excruciatingly long delay.

**Comment by mrcstgt** [comment]
Fixed it. Turns out that mpv was having problems loading more than 1000 fonts that I had installed (I sometimes do design) so I just halved the number of fonts I had and it worked flawlessly.

**Comment by shinchiro** [comment]
This is known issue with `directwrite` backend. You can make mpv used fontconfig by setting `--sub-font-provider=fontconfig` next time when having thousands of fonts installed
