### ISSUE TITLE
Aspect ratio calculation in photo format [stats module]

### ISSUE THREAD

**Issue by zhovner** [mpv-player/mpv#7863]
Right now stats module displays aspect ratio in video format. But photo format is much commonly used.  
For example resolution `3840 х 2160` is showing as `1.78` but `16:9` is much more clear.

![image](https://user-images.githubusercontent.com/774290/85945200-d45cfd00-b944-11ea-814b-b8ef6b3dd571.png)

## Expected behavior 

Add photo format aspect ratio, so `3840 х 2160` will be `16:9`

**Comment by avih** [comment]
I don't think there's an issue with the calculation. The value seems correct, you only want to display it differently (16:9 instead of 1.78).

**Comment by Argon-** [comment]
As far as I'm aware that would require a hard-coded list and probably a float to string map. That doesn't sound pleasant to me.

**Comment by paulguy** [comment]
Can't have it do lowest common denominator somehow?  I'm not particularly good at programming but i figure there's an algorithm for that somewhere.

**Comment by Argon-** [comment]
Then you don't get 16:10 but 8:5 instead.

**Comment by paulguy** [comment]
I mean, it isn't not 8:5. :D

**Comment by wm4** [comment]
Also: cropped 16:9 is still called 16:9 often enough.

**Comment by zhovner** [comment]
Looks like never be done.
