### ISSUE TITLE
Incorrect OSD while playing video

### ISSUE THREAD

**Issue by Abh15h3k** [mpv-player/mpv#7864]
### Important Information

Provide following Information:
- mpv version:  0.32.0-570-g22a27c6720
- Linux Distribution and Version : Arch Linux
- Source of the mpv binary : ??
- If known which version of mpv introduced the problem: ??
- Window Manager and version: dwm 6.2
- GPU driver and version : intel i gpu (no driver installed explicitly)
- Possible screenshot or video of visual glitches : https://imgur.com/a/zclG8vN

### Reproduction steps
play any video file

### Expected behavior
supposed to show osd with proper time line and other elements.

### Actual behavior
shows only a few elements jumbled together. no time line

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/4843054/log.txt)

### Sample files
no specific sample files needed.

**Comment by Akemi** [comment]
what lua version does mpv use/do you use?

**Comment by Abh15h3k** [comment]
> what lua version does mpv use/do you use?

Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

**Comment by Akemi** [comment]
mpv doesn't support lua 5.3. only the following versions are supported https://github.com/mpv-player/mpv/blob/22a27c6720244dd24c9b704c8a8225ca1665272f/waftools/checks/custom.py#L61-L71 (5.1, 5.2, luajit).

configure should have failed and your distribution failed to providing a working package, or something along the lines.

**Comment by wm4** [comment]
Did your distro patch this out? https://github.com/mpv-player/mpv/blob/master/player/lua.c#L434

**Comment by Abh15h3k** [comment]
well. after a lot of trial and error turns out. i just needed to install `ttf-linux-libertine`.

also regarding lua. i have `lua52 and luajit` installed
