### ISSUE TITLE
INTEL-MESA: warning: Bay Trail Vulkan support is incomplete

### ISSUE THREAD

**Issue by yaoberh** [mpv-player/mpv#7867]
### Important Information

Provide following Information:
- mpv version = git
- Linux Distribution and Version = Manjaro 20.04
- Source of the mpv binary = git
- If known which version of mpv introduced the problem = all versions are the same
- Window Manager and version = KDE Plasma, 5.19
- GPU driver and version = Intel Bay Trail, i915 chipset, xorg open source driver

Error:
When running MPV player, the error shows and I can't run with vulkan backend.
Is there something I can do to implement it?
These are the two errors I get:
INTEL-MESA: warning: ../mesa-20.1.2/src/intel/vulkan/genX_cmd_buffer.c:5990: FINISHME: Implement events on gen7
INTEL-MESA: warning: Bay Trail Vulkan support is incomplete

[logfile.txt](https://github.com/mpv-player/mpv/files/4853683/logfile.txt)

**Comment by jeeb** [comment]
Unfortunately your driver is incomplete. Older Intel hardware does not have proper Vulkan drivers. According to the log, libplacebo does seem to roll there, but I would guess it wouldn't work properly. I have same on my Ivy X230 laptop :) .

In this case, if you would like to have proper Vulkan support on this hardware, I would recommend becoming a mesa driver developer.

**Comment by haasn** [comment]
Yikes. I think that the proper stopgap measure here would be for mesa to return `VK_ERROR_FEATURE_NOT_PRESENT` until it's implemented. I'll submit a suggestion for that upstream.

**Comment by haasn** [comment]
I added the `--vulkan-disable-events` option as a work-around.
