### ISSUE TITLE
Support `hash -d` entries in argument path

### ISSUE THREAD

**Issue by smhmd** [mpv-player/mpv#7870]
### Expected behavior of the wanted feature
I'm not sure what it's called, but `hash -d dir=/home/user/directory` makes the latter accessible using `~dir`. You can use that with the main file/directory argument (i.e. `mpv ~dir/video.mp4`,) but you can't use it in arguments (i.e. `mpv --playlist=~dir/videos.txt`.)

### Alternative behavior of the wanted feature
Type the whole path `mpv --playlist=~/directory/videos.txt`.

**Comment by qmega** [comment]
The shell does that, not mpv. I don't know what shell you use.

For bash, I'm not aware of a way to get what you want, but it may be possible.

For zsh, you can use the `MAGIC_EQUAL_SUBST` option (set in your .zshrc or such):
```zsh
$ echo ~/foo --bar=~/foo '--bar=~/foo'
/home/qmega/foo --bar=~/foo --bar=~/foo
$ setopt magicequalsubst
$ echo ~/foo --bar=~/foo '--bar=~/foo'
/home/qmega/foo --bar=/home/qmega/foo --bar=~/foo
```

**Comment by CounterPillow** [comment]
For bash you can use the legacy options syntax:

```
mpv -playlist ~dir/videos.txt
```
