### ISSUE TITLE
Wrong color reproduction when playing 10bit video files

### ISSUE THREAD

**Issue by ahizap** [mpv-player/mpv#7871]
### Important Information

Provide following Information:
- mpv version:- mpv-x86_64-20200621-git-dc24a43
- Windows Version 1909

### Reproduction steps

When I play 10 bit files using mpv the colors seems off in 8bit monitor but when i extract the frame of 10bit file using ffmpeg the colors looks identical to source.Screenshot for comparing https://imgur.com/a/84Nz3Kq

### Expected behavior
Colors reproduction should match the source
### Actual behavior
Colors are displaying wrong when playing with mpv

**Comment by jeeb** [comment]
Please post a log file of playing such a clip with `--log-file=mpv_sucks.log`.

**Comment by ahizap** [comment]
[f.txt](https://github.com/mpv-player/mpv/files/4860890/f.txt)

**Comment by haasn** [comment]
I don't see anything surprising about the log but maybe the 8-bit version has different metadata. Missing log for that one.

**Comment by ahizap** [comment]
> I don't see anything surprising about the log but maybe the 8-bit version has different metadata. Missing log for that one.

[8bit encode.txt](https://github.com/mpv-player/mpv/files/4861326/8bit.encode.txt)
[original.txt](https://github.com/mpv-player/mpv/files/4861327/original.txt)

**Comment by haasn** [comment]
Seems both your original and the 8bit version are RGB, but the 10bit encode is YUV. mpv assumes a different colorspace by default for RGB and YUV content. Since your content is untagged, I wouldn't *expect* it to look the same.

**Comment by ahizap** [comment]
The source file was in RGB which was causing the issue i changed the source file to an YUV and the issue now seems to be resolved thanks @haasn for pointing it out
