### ISSUE TITLE
Playback occasionally pauses

### ISSUE THREAD

**Issue by andrew-boyarshin** [mpv-player/mpv#7872]
### Important Information
- mpv 0.32.0-526-g102a083171
- Windows 10 (recent, 19H2 or 20H1)
- shinchiro build
- Occurred both _with_ and _without_ ANGLE DLL files from latest Firefox

Stuck:
![image](https://user-images.githubusercontent.com/3063662/86338091-1e631d00-bc7c-11ea-8f26-36eaf4dc2b78.png)

_Space_ successfully toggles the "pause" to "play" icon and back.

_i_ output when stuck:
![image](https://user-images.githubusercontent.com/3063662/86338328-684c0300-bc7c-11ea-8a69-27db1d56cd1b.png)

After applying the workaround described below, the _~_ output:
![image](https://user-images.githubusercontent.com/3063662/86338519-a2b5a000-bc7c-11ea-89b2-5390b5f0e55a.png)

Note, that I never had this issue, I am merely investigating the issue on a friend's PC.

This happens on various files, so it's not specific to a single file.

### Reproduction steps
Indeterminate, since the stutter is apparently random.

Config:
```
# High quality video rendering for fast computer. 
profile=gpu-hq 
deband=no 
demuxer-readahead-secs=60 
sub-auto=fuzzy
audio-file-auto=fuzzy
alang=en,eng
slang=en,eng
screenshot-jpeg-quality=100
log-file=mpvlog.txt
msg-level=all=trace
msg-module=yes
msg-time=yes
```

### Expected behavior

Smooth playback.

### Actual behavior

Playback sometimes pauses and doesn't continue.
Workaround: rewind back 5 seconds and resume playback. It successfully plays.

### Log file

[0x0 log (28 MiB)](https://0x0.st/iyrU.txt)

This was captured with all tracing enabled (by my request):
1. Watch video as usual until stutter occurs
2. _Left_ to rewind back
3. Continue watching until the moment the stutter occurred and a bit after
4. Exit player

I've already asked for another log when the issue happens again.

**Comment by andrew-boyarshin** [comment]
Oh wait. Probably related to #7811.

**Comment by igv** [comment]
With `video-sync=display-resample` it doesn't stuck, but plays at ~1 fps.
This bug appeared a month ago after changes to audio.

**Comment by andrew-boyarshin** [comment]
Sorry, this bug has just been confirmed to be fixed by updating to the latest version after #7811 was fixed.
@igv I'd open a different issue since this seems unrelated.
