### ISSUE TITLE
Unable to skip track whilst streaming from STDIN.

### ISSUE THREAD

**Issue by nerd190** [mpv-player/mpv#7876]
• mpv version: 

```
$ mpv --version
mpv 0.32.0
 built on Sat Jun 20 20:39:25 UTC 2020
ffmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
ffmpeg version: 4.3.1
```

• Platform and Version:

```aarch64/ARM64```

• Source of the mpv binary:

```Termux```

Reproduction steps

```stream a playlist from STDIN```

Expected behavior

```able to skip tracks in the playlist file```

Actual behavior

```unable to skip tracks in the playlist file```

Log file

```N/A```

----

Hi, first... **THANK YOU!** mpv is awesome!

I stream using `spotdl` ("spotify-downloader" by ritiek), it uses `youtube-dl` to download or stream tracks via mpv, when it does this though (*stream* using `youtube-dl`) I am unable to skip tracks (all other shortcuts work: P, spacebar, etc)
Is it possible to skip songs whilst streaming?
Thank you for your time!

**Comment by 5c0tt-b0t** [comment]
anyone?!? please!
- "can you stream via youtube-dl AND skips songs?"

if so...
- "how?"

because:
-"I cannot. skip button doesnt work."

**Comment by 5c0tt-b0t** [comment]
Seriously... If its not possible to skip while streaming, a simple... "Not possible" would suffice, you can then close this issue.
Thats kinda how it works with issues...
You answer them, then close them.
Any chance that could happen here?

**Comment by Tsubajashi** [comment]
How about you wait until they have the time to check your issue?
Either way, ill look into it, because i got a similar question on my discord where people can talk about my config.

**Comment by Akemi** [comment]
maybe it would have been better if the issue template wasn't ignored. devs tend to ignore issues where the minimum of work wasn't put in.

**Comment by Argon-** [comment]
No idea what spotdl even is. Of course mpv can skip songs in a playlist. Does spotdl even provide/generate one? Nobody know. It's entirely possible that it doesn't. 
Imo this issue is not about mpv, it's about spotdl. Maybe ask them first.

**Comment by ritiek** [comment]
Basically, the problem @5c0tt-b0t mentions is that it isn't possible to skip tracks when they are fed from STDIN.

For example, when passing media files as arguments to mpv with:
```
$ mpv 1.mp3 2.mp3
```
everything is good and it's possible to immediately skip to the next track by hitting <kbd>></kbd> key.

However, this doesn't work when tracks are fed from STDIN:
```
$ cat 1.mp3 2.mp3 | mpv -
```
in this case mpv combines media data from both these files and tends to treat them as a single track which makes it impossible to skip to the next track like we did in the previous case.

So, is it somehow possible to pass multiple media files from STDIN to mpv and have mpv treat them as separate media files?

(I realize that STDIN is a single file but I guess it should be possible for mpv to handle such a case as each media file passed has its own header information)

**Comment by 5c0tt-b0t** [comment]
Apologies @Akemi for not using the template, was using a mobile app and missed it, I was unaware.
I have edited my original post to conform to the template.
As @ritiek kindly stated, in much better words than me! It is indeed when streaming from STDIN.
Would love to be able to skip tracks whilst streaming from STDIN, is this be something that you guys could possibly implement? Using header information, as suggested by @ritiek ?
Thank you for your time & effort.

**Comment by wm4** [comment]
Piping concatenated audio files is generally not supported (i.e. you'll run into random problems), much less seeking in it. Of course they're not represented as track list, and as long as it's some sort of piping to stdin, it'll never be.
Since you linked that spotify thing (?) this is probably a different case, and/or something that could be handled better on one of the sides, but there's not enough information to tell.

**Comment by 5c0tt-b0t** [comment]
Thank you @wm4 for your explanation.
> that spotify thing (?)
https://github.com/Ritiek/Spotify-Downloader
It converts spotify songs/playlists into youtube links, therefore downloading/streaming from a users spotify but never actually using your spotify but youtube instead. Please take a look, its very popular. I feel just like the ytdl integration mpv has, it should also integrate with spotdl somehow to provide spotify streaming too (a very nice feature... Legally streaming spotify without a spotify client! Just as we can do already with youtube) (and one of the reasons i use mpv is the streaming possibilities like this), I understand what you say, that the otherside could possibly change their side too, I did open a issue their side too (the one referenced here by @ritiek ). Either way, would be great if you could either mpv could read the header files when piped from stdin OR spotdl could split a playlist in the same way youtubedl does??

**Comment by garoto** [comment]
`spotdl` DOES NOT stream from spotify library, it streams from Youtube bases on the search criteria passed via CLI. Only the metadata comes from the spotify API.

**Comment by ritiek** [comment]
> Piping concatenated audio files is generally not supported (i.e. you'll run into random problems), much less seeking in it. Of course they're not represented as track list, and as long as it's some sort of piping to stdin, it'll never be.

Alright.

> Since you linked that spotify thing (?) this is probably a different case, and/or something that could be handled better on one of the sides, but there's not enough information to tell.

Yep, I guess so. I've also yet to learn about much of the functionality provided by mpv. I'll first have a better look if something could be done better from our side when writing audio to stdout.

> I feel just like the ytdl integration mpv has, it should also integrate with spotdl somehow to provide spotify streaming too

@5c0tt-b0t I won't go into details but that really isn't a good idea.

**Comment by 5c0tt-b0t** [comment]
@garoto read again....
I stated it streams a users spotify playlist **"USING YOUTUBE-DL"** i.e from youtube.
And as mpv can stream using youtube-dl, so should spotdl, if possible.
Hence, an issue opened on both sides asking if it is possible.
But reading @wm4 's reply of "never have, never will support streaming from STDIN" reply, I take that as "we are not gonna do anything" @ritiek can instead.
Which is fine, I suppose, but the ability to stream from stdin is a great one, I use it to stream radio stations or spot-dl etc to mpv, for a radio station its perfect as you cannot skip tracks, but for spot-dl doesnt work well, no one wants to listen to every track in a bog playlist, without skip its not a great experience. By no way would I suggest "seeking" within a track as I would expect this would be more troublesome, but if reading the header files would allow skipping/going-back to another track possible, why not?
By all means though, do feel free to close this issue if it is something you deem as not valuable to mpv users, or just not willing to explore.
Thank you.

**Comment by wm4** [comment]
What the fuck...

**Comment by garoto** [comment]
god damnit, wm4 spoiling all the fun _again_.

**Comment by avih** [comment]
@5c0tt-b0t please provide a full log file of when the issue happens (like the issue template states). Until you do that it's impossible to tell more.

**Comment by Dudemanguy** [comment]
I don't think it's expected to be able to skip tracks if you pipe them all into STDIN.
