### ISSUE TITLE
mute is not synced with pulseaudio

### ISSUE THREAD

**Issue by 532910** [mpv-player/mpv#7878]
While the volume control is synchronous with pulse's the mute toggle is not.

mpv 0.32.0, debian sid +marillat

**Comment by CounterPillow** [comment]
Don't ignore the issue template.

**Comment by 532910** [comment]
please add `ao:pulse`

**Comment by Akemi** [comment]
there is the `ao-mute` property for this, i believe.

**Comment by 532910** [comment]
Missed it, thank you @Akemi!
