### ISSUE TITLE
lavfi-complex property weird bahavior

### ISSUE THREAD

**Issue by wjtk4444** [mpv-player/mpv#7879]
```
mpv -V
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.3
```

I wrote a lavfi-complex filter not too long ago, I'm toggling it on and off with a script. I am as green as one could be when it comes to filters so it doesn't look exactly as I planned, but that's not the issue here.

```
local lavfi_complex = [[
        [vid1]
                split
            [vid][bg];

        [bg]
                eq=gamma=0
            [bg];

        [vid]
                scale=ih:-1, 
                drawbox=c=black@0
            [box];

        [bg][box]
                overlay=main_w-overlay_w:(main_h-overlay_h)/2
            [vo]
    ]]
```

I am applying the filter using `mp.set_property('lavfi-complex', lavfi_complex)` command. And there are 3 things I'd like to point out:

* mpv drops demuxer cache when the filter is first applied

* `mp.set_property('lavfi-complex', '')` doesn't remove the filter

* audio glitches/pauses for a really short time whenever filter is changed 

I had to resort to (as stupid as it is) `mp.set_property('lavfi-complex', '[vid1]hflip,hflip[vo]')` to remove the effect and also apply it when the script is first loaded to avoid dropping cache. Which results in this abomination: 

```
function filterOn() mp.set_property('lavfi-complex', '[vid1]hflip,hflip[vo]') end
function filterOff() mp.set_property('lavfi-complex', lavfi_complex) end

filterOn()
```

About the last point, I am not touching the audio stream at all so I'd expect it to be more seamless when a video filter changes.

**Comment by wjtk4444** [comment]
One more thing: I'd expect a silent error when trying to apply a filter when there's no video tracks available.

```
Playing: whatever.mp3
Pad vid1 is not connected to anything.
```

This causes mpv to skip the file and go right to the next playlist entry.

**Comment by Dudemanguy** [comment]
lavfi-complex can't act on runtime, so its behavior is a little weird.

`mp.set_property('lavfi-complex', '')` does remove the filter, but just not at runtime. You can get around this by reloading the file again. The pad thing occurs for the same reason. What you can do is register an event handler and catch any errors. So for example something like `mp.register_event("end-file", check_lavfi_complex)` somewhere and

```
function check_lavfi_complex(event)
	if event.file_error or event.error then
		do_stuff()
	end
end
```

In master, the API changed a little bit and the error got moved to `event.file_error`. Technically if you're running 0.32, you only need `event.error` here. But having both won't hurt.

**Comment by wm4** [comment]
Changing at runtime is actually supposed to work, it's just not very smooth. It's probably a bug that setting an empty filter does nothing. Dropping the cache probably comes from the fact that changing the filter first disables all input tracks, and then enables them again. But in this case, you should just use --vf because you don't need the extra features lavfi-complex provides.

**Comment by wjtk4444** [comment]
>`mp.set_property('lavfi-complex', '')` does remove the filter, but just not at runtime.

Wait, how come you can change a filter at runtime, but you can't remove/apply it?

And about the pad thingy yeah, I could just check if there is any video track before applying the filter but I can't wrap my head around why it's not ignored automatically.

>You can get around this by reloading the file again. 

I guessed that, but that's a filter I'm using for online stuff so dropping the cache is not really an option.

**Comment by wm4** [comment]
> And about the pad thingy yeah, I could just check if there is any video track before applying the filter but I can't wrap my head around why it's not ignored automatically.

That you must do. Why would it be ignored? What the hell would it even do with the filter if there's no track to connect to?

**Comment by wjtk4444** [comment]
>you should just use --vf because you don't need the extra features lavfi-complex provides.

Wait, really? I thought that what I wrote is lavfi-complex. Could you please direct me to any examples on how to convert it to a simple filter? The split and merge part in partucilar. [Manual](https://mpv.io/manual/master/#video-filters-vf) doesn't provide an example of that (or I'm just too inexperienced with lavfi and don't understand basic concepts very well)

**Comment by wjtk4444** [comment]
>That you must do. Why would it be ignored? What the hell would it even do with the filter if there's no track to connect to?

Absolutely nothing, that's my point. If I enable a filter and feed mpv with a playlist consisting of random files, I would expect the filter to work on the video files and be ignored on everything without a video track (rather than mpv skipping these tracks completely). It's just my vision of a sane default.

**Comment by wjtk4444** [comment]
I hate to be that guy who asks for spoonfeeding, but 3 days later I still don't have a clue on how to 

>just use --vf 

as @wm4 said.

Main issue is that I don't know how to I apply `[in]whatever[out]` syntax using `--vf`.

--

### Context:

My goal is to split the video in two, darken the original and overlay it with resized copy. Intended to use with my slightly modified osc and "playlist mode" script (which I should really upload, but it's still WIP). 

Orignal:
![image](https://user-images.githubusercontent.com/20820296/86915373-6917e580-c111-11ea-98d7-da7b79a78512.png)
Filter applied (playlist view + osc visible):
![image](https://user-images.githubusercontent.com/20820296/86915429-7fbe3c80-c111-11ea-940c-fd16e3674646.png)

**Comment by wm4** [comment]
Setting lavif-complex to an empty string does what it should here. Changing lavfi-complex to a different graph (when it still uses the same inputs/outputs) also doesn't flush the cache here (that's because there's actually logic to avoid it).

If you had video enabled, and set lavfi-complex to non-empty for the first time, and it uses `[vo]` and/or a video track that was used by normal video playback, it will deselect the video track and then reselect it, which leads to cache dropping. So just don't do that. Use could set a filter that mostly does nothing (like `copy` or maybe better `fifo`, I don't know if there's a true no-OP pass through filter).

But what you really want is using ``--vf``. You can pass an arbitrary libavfilter graph to the ``lavfi`` filter, just that in ``--vf`` and ``--af`` it must have exactly 1 input and 1 output.

**Comment by wjtk4444** [comment]
>closing issue because I can not reproduce.

Which part? As you have stated, it's all expected behavior. Well, expected after reading this thread, because manual doesn't mention it at all. I would consider updating it with a few notes on:

- `--lavfi-complex` setting and resetting requiring a cache drop
- `--lavfi-complex` changing not requiring a cache drop
- `--lavfi-complex=""` not dropping the cache and thus not providing any results unless the file is manually reloaded / changed 
- `--lavfi-complex` set to any value other than empty resulting in skipping files without video tracks (`Pad vid1 is not connected to anything.`)

--

>But what you really want is using --vf. You can pass an arbitrary libavfilter graph to the lavfi filter, just that in --vf and --af it must have exactly 1 input and 1 output.

Could I please get an example on how to split, apply filters and merge using that method? Because that's exactly what my filter does (see pictures in my previous comment). I don't think it is possible to achieve the same effect with only one input and one output available, but I'd be happy to be proven wrong.

Raw ffmpeg can indeed handle my filter as a regular `vf`, but I have no bloody idea on how to apply that to mpv itself.

`ffmpeg -i file.png -vf '[in] split [vid][bg]; [bg] eq=gamma=0 [bg]; [vid] scale=ih:-1, drawbox=c=black@0 [box]; [bg][box] overlay=main_w-overlay_w:(main_h-overlay_h)/2 [out]' -f matroska - | mpv -`

**Comment by wm4** [comment]
Trivial example: `--vf=lavfi=[[in] copy [a] ; [a] fifo [out]]`

**Comment by wjtk4444** [comment]
Thank You, exactly what I needed. Please consider adding this example to the manual.

**Comment by wm4** [comment]
The manual explicitly states that the filter can take lavfi graphs, and even provides an example with several filters, just no example that uses labels.
