### ISSUE TITLE
Support play video from vk.com via youtube-dl

### ISSUE THREAD

**Issue by IlyaIndigo** [mpv-player/mpv#7880]
### Expected behavior of the wanted feature
mpv {URL on any public video on vk.com up to 25 minutes}
mpv https://vk.com/video-100963008_456240006
Play this video.

### Existing behavior of the required function.
mpv {URL on any public video on vk.com up to 25 minutes}
mpv https://vk.com/video-100963008_456240006
[ytdl_hook] ERROR: requested format not available
[ytdl_hook] youtube-dl failed: unexpected error ocurred
Failed to recognize file format.

### Log file
youtube-dl {URL on any public video on vk.com up to 25 minutes}
youtube-dl https://vk.com/video-100963008_456240006
Works great with vk.com.

**Comment by CounterPillow** [comment]
Where's your log file? I'm assuming you put fixed format specifiers in your `ytdl-format` for youtube and now it fails on any other site, i.e. user error.

**Comment by IlyaIndigo** [comment]
> Where's your log file? I'm assuming you put fixed format specifiers in your `ytdl-format` for youtube and now it fails on any other site, i.e. user error.

Oh, yes.
ytdl-format=136+140/135+140/bestvideo+bestaudio
But how can I make one format for vk.com, and another for youtube.com?

**Comment by CounterPillow** [comment]
by now explicitly specifying format numbers but specifying format selection criteria as the youtube-dl manpage suggests.

```
ytdl-format=bestvideo[height<=?720]+bestaudio/best
```

**Comment by IlyaIndigo** [comment]
Thank you!
