### ISSUE TITLE
MPV not using user set conf files (mpv.conf and input.conf)

### ISSUE THREAD

**Issue by Sa-ghosts** [mpv-player/mpv#7881]
### Important Information

Provide following Information:
- mpv version: mpv-git-8fbc4b1.7z
- Windows Version: 1909
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- If known which version of mpv introduced the problem: it was working okay with dc24a43

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
1- Create an mpv.conf file and input.conf file
2- put them in `C:\pathtompv\mpv\` (folder named mpv inside the folder containing the mpv.exe)
2 alt - put them in `C:\pathtompv\` (same folder as the mpv.exe)
3- play a video

### Expected behavior
mpv would use the .conf files

### Actual behavior
mpv uses default settings

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/4876673/mpv.log)

**Comment by WizRay** [comment]
["C:\users\USERNAME\AppData\Roaming\mpv" is the recommended directory for config. ](https://mpv.io/manual/master/#files-on-windows)

**Comment by Sa-ghosts** [comment]
So it seems like `C:\pathtompv\mpv\mpv\` (folder named mpv inside the mpv folder containing the mpv.exe)
and `C:\pathtompv\mpv\` (same folder as the mpv.exe) no longer do the job.
same thing apply to `C:\pathtompv\mpv\scripts\`

this is what works:
`C:\pathtompv\mpv\portable_config\` OR `%APPDATA%/mpv/`
and for scripts they have to be in `%APPDATA%/mpv/scripts/`

thanks WizRay.

**Comment by Doofussy2** [comment]
This maybe why

https://github.com/mpv-player/mpv/commit/c3694f0acb7f71daac7606fafbadcb7b500ca35e

**Comment by avih** [comment]
> This may be why
> 
> [c3694f0](https://github.com/mpv-player/mpv/commit/c3694f0acb7f71daac7606fafbadcb7b500ca35e)

More specifically, a bug - #7889

**Comment by MRACHINI** [comment]
kindly fix it, i need to have my config folder next to .exe and to be used without having to specify it in another parameter

**Comment by WizRay** [comment]
@MRACHINI, while the bug is fixed for next git build, for now you can create portable_config folder next to the executable or in "C:\users\USERNAME\AppData\Roaming\mpv" folder to put your files in. mpv checks for config files in this priority: AppData/mpv> portable_config next to exe> mpv folder to exe. You don't need to specify anything here.

**Comment by sergeevabc** [comment]
Well, 0200705-git-8fbc4b1 is indeed a disappointment for portable Windows users because of this mess.

**Comment by avih** [comment]
> Well, 0200705-git-8fbc4b1 is indeed a disappointment for portable Windows users because of this mess.

In case it wasn't obvious enough:
- It was a bug.
- It's fixed already.
- Wait for the next build or build mpv yourself if it's so urgent to you.

Bugs happen. If you don't want bugs, look elsewhere. This project occasionally has bugs. It is what it is.
