### ISSUE TITLE
How to select subtitle but not display them?

### ISSUE THREAD

**Issue by ZaxonXP** [mpv-player/mpv#7882]
I am using `mpv` player together with the `youtube-viewer` Perl app. For many occasions I am ok not to have a subtitle displayed, but I would like to have them selected. So I am using following settings:
```
--sub-file=*SUB* --sub-auto=no
```
However then I need to press `v` to hide the subtitles. How can do this "hiding" automatically? What is the command line option  for this?

Regards,
Piotr

**Comment by Akemi** [comment]
--sub-visibility=no, read the manual and/or the default input.conf.

**Comment by ZaxonXP** [comment]
@Akemi : Thank you for your answer! I was reading the manual, but it is huge and I could not find this option somehow.
