### ISSUE TITLE
x11/gl errors when using hwdec = auto

### ISSUE THREAD

**Issue by lgbaldoni** [mpv-player/mpv#7884]
### Important Information

Provide following Information:
- mpv version: 0.32.0+git.20200701T004440.8fbc4b1737 
- Linux Distribution and Version: openSUSE Leap 15.2
- Source of the mpv binary: distro-supplied (from May 2020) and current, both built on OBS
- If known which version of mpv introduced the problem: unknown. The problem started after upgrading from Leap 15.1
- Window Manager and version: plasma5 5.18.5
- GPU driver and version: amdgpu coming with the distro kernel
- Possible screenshot or video of visual glitches: N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Obtain an h.264 or h.265 encoded video.
Run mpv with the hwdec=vaapi option.

Note: the error shows with --no-config hwdec=vaapi but not with hwdec=vaapi-copy.

### Expected behavior
No errors on CLI.

### Actual behavior
Several complaints concerning x11/OpenGL/libva

### Log file
[Log here](https://github.com/mpv-player/mpv/files/4877964/mpv_x11.log)

### Sample files
N/A

**Comment by lgbaldoni** [comment]
I've just seen vaapi it's not recommended, but using hwdec = auto makes no difference (see [log](https://github.com/mpv-player/mpv/files/4896290/mpv_x11_auto.log))
hwdec = auto-copy shows no errors instead.

**Comment by Dudemanguy** [comment]
Does this still happen on git master? The way hwdec is checked was changed recently. At the very least, the CUDA message shouldn't happen anymore.

**Comment by lgbaldoni** [comment]
> Does this still happen on git master? The way hwdec is checked was changed recently. At the very least, the CUDA message shouldn't happen anymore.

I can't reproduce it anymore.

**Comment by Dudemanguy** [comment]
Great, seems like this was solved then.
