### ISSUE TITLE
MPV segfaults when trying to play media with Intel Tearfree turned on.

### ISSUE THREAD

**Issue by BridgetX** [mpv-player/mpv#7885]
### Important Information

- mpv 0.32.0
- Linux version: Ubuntu 20.04 LTS
- Source of the mpv binary: the Ubuntu repos
- Window Manager: dwm 6.2
- GPU driver and version: Intel driver supplied by the distro kernel.

### Reproduction steps
Try to play a video with Intel Tearfree turned on in xorg.conf.d.

### Expected behavior
Video plays normally.

### Actual behavior
MPV segfaults, but plays fine if --vo=xv.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/4878893/output.txt)

### Sample files
N/A

**Comment by CounterPillow** [comment]
Post a gdb backtrace please.

```
gdb mpv
run mpv args here
```
once it crashes
```
bt full
```

**Comment by BridgetX** [comment]
[backtrace.txt](https://github.com/mpv-player/mpv/files/4879132/backtrace.txt)

**Comment by CounterPillow** [comment]
Your mpv binary is stripped of all debug symbols, as is your installation of mesa, so the backtrace does not tell us much other than that it crashes 5 stackframes deep into Intel's notoriously buggy Iris driver.

**Comment by CounterPillow** [comment]
Actually since you're on Ubuntu, you can probably get the debug symbols with `apt install mpv-dbg mesa-dbg`

**Comment by BridgetX** [comment]
Heres the output with mpv-dbgsym and mesa-va-drivers-dbgsym installed.
[backtracedbg.txt](https://github.com/mpv-player/mpv/files/4881189/backtracedbg.txt)

**Comment by CounterPillow** [comment]
`mesa-va-drivers-dbgsym` isn't the right package, but it doesn't matter; the bug does not seem to be in mpv but in Intel's drivers. [mpv is calling glClear](https://github.com/mpv-player/mpv/blob/c1a961ad78b6d1da339e622c723d753a80687824/video/out/opengl/ra_gl.c#L684), and Intel's interpretation of that is apparently "let's crash". Please report this bug against mesa for the iris driver.
