### ISSUE TITLE
Who can answer my question about playing speed

### ISSUE THREAD

**Issue by levenies** [mpv-player/mpv#7886]
I use it libmpv.dll Version 2.0.0.0 20200126 dev
Why do I play frame by frame when the download speed of LAN is very fast? I changed to a slower LAN, and the playback speed was normal. I didn't find out the difference. I used the following parameter settings:

            _player.setProp("cache-size", "2000");
            _player.setProp("cache-pause", "no");	

            _player.setProp("demuxer-cache-duration", "1");
            _player.setProp("demuxer-cache-time", "1");
            _player.setProp("demuxer-readahead-secs", "20");
            _player.setProp("demuxer-max-bytes", "102400");
            _player.setProp("demuxer-cache-duration", "0.5");
            _player.setProp("demuxer-max-back-bytes", "102400");

            _player.setProp("ad-lavc-threads", "0");
            _player.setProp("demuxer-thread", "yes");
            _player.setProp("demuxer-rawvideo-fps", "8");

**Comment by levenies** [comment]
I try not to set any parameters, keep all default, the result is still the same play frame by frame

**Comment by Akemi** [comment]
sry, a question is completely inappropriate for this. please open a new proper issue and fill out the complete issue template.
