### ISSUE TITLE
The video is played frame by frame on some computers with only integrated graphics cards

### ISSUE THREAD

**Issue by levenies** [mpv-player/mpv#7888]
### Important Information

Provide following Information:
- mpv version : mpv-dev-i686-20200126
- Windows Version : win 7
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
I play video frame by frame on the computer with integrated graphics card, and play normally on the computer with independent display

This is the computer display driver that I can't display and play normally
1. Standard VGA graphics adapter; 
2. Radmin mirror driver v3
MPV will automatically select a separate graphics card
Is there any way to make the playback normal？

### Expected behavior
Normal speed for playback display

### Actual behavior
Play frame by frame

### Log file
https://github.com/levenies/test/blob/master/log0.txt

### Sample files
Any Video File

**Comment by Akemi** [comment]
please clarify what frame by frame is supposed to mean, since every video is played frame by frame? do you mean it's slowed down?

a date is not a proper version of a build it's either a release tag or a commit hash.

a log would be very helpful do diagnose your problem and is most likely also needed. there surly is a way to get one even if you just output on the terminal with `-v -v` and copy paste it.

**Comment by levenies** [comment]
> please clarify what frame by frame is supposed to mean, since every video is played frame by frame? do you mean it's slowed down?
> 
> a date is not a proper version of a build it's either a release tag or a commit hash.
> 
> a log would be very helpful do diagnose your problem and is most likely also needed. there surly is a way to get one even if you just output on the terminal with `-v -v` and copy paste it.


Yes, it is very slow when playing, with an average frame rate of about 1-2 FPS. I have also repeated this problem in other computers, that is, disable the driver of the independent graphics card, and then play the video. I have compared the VLC player, which still plays normally

I attached the log file

**Comment by rossy** [comment]
It seems like there's no GPU acceleration at all. At least, there's no support for D3D11 or 10Level9 on the default adapter. If you have integrated graphics, are the drivers installed?

I'm not sure how "Radmin mirror driver v3" works, but if it's a display adapter, maybe mpv has to be configured to use the integerated GPU instead? You could try --d3d11-adapter=intel

Debug information from DxDiag might be helpful. Could you run DxDiag (Win+R, dxdiag, Enter), press Save All Information and post the text file here.

**Comment by levenies** [comment]
> It seems like there's no GPU acceleration at all. At least, there's no support for D3D11 or 10Level9 on the default adapter. If you have integrated graphics, are the drivers installed?
> 
> I'm not sure how "Radmin mirror driver v3" works, but if it's a display adapter, maybe mpv has to be configured to use the integerated GPU instead? You could try --d3d11-adapter=intel
> 
> Debug information from DxDiag might be helpful. Could you run DxDiag (Win+R, dxdiag, Enter), press Save All Information and post the text file here.

At present, I can't get the log in the driver environment of the above computer. I have repeated this situation in other computers, that is, the display adapter of the display adapter of the independent display is disabled, and the display adapter of the Intel integrated graphics card is retained. The playback is also very slow frame by frame, and two logs are attached：

https://github.com/levenies/test/blob/master/DxDiag1.txt
https://github.com/levenies/test/blob/master/log1.txt

**Comment by rossy** [comment]
Thanks for the DxDiag log. Going from the log, there's only one display adapter on that machine and it doesn't have 3D acceleration (see D3D Status: Not Available). I don't know why the integrated GPU isn't appearing as a display adapter, but if mpv can't create a hardware accelerated D3D11 device, it will fall back to software rendered D3D11, which can be slow (but shouldn't be too slow with a powerful CPU.)

I don't know what you can do to speed it up other than double-checking that the Intel GPU drivers are installed. Depending on your hardware, you might be able to use the drivers from Intel's website, or you might have to use the ones from HP.

VLC probably works because it has video output modules that use 2D APIs, like GDI, but mpv on Windows only has video output backends that use 3D APIs, like D3D11, D3D9, OpenGL and Vulkan. Without 3D acceleration, mpv will be slow. (We are thinking of adding a GDI backend to remedy this.)

**Comment by levenies** [comment]
> Thanks for the DxDiag log. Going from the log, there's only one display adapter on that machine and it doesn't have 3D acceleration (see D3D Status: Not Available). I don't know why the integrated GPU isn't appearing as a display adapter, but if mpv can't create a hardware accelerated D3D11 device, it will fall back to software rendered D3D11, which can be slow (but shouldn't be too slow with a powerful CPU.)
> 
> I don't know what you can do to speed it up other than double-checking that the Intel GPU drivers are installed. Depending on your hardware, you might be able to use the drivers from Intel's website, or you might have to use the ones from HP.
> 
> VLC probably works because it has video output modules that use 2D APIs, like GDI, but mpv on Windows only has video output backends that use 3D APIs, like D3D11, D3D9, OpenGL and Vulkan. Without 3D acceleration, mpv will be slow. (We are thinking of adding a GDI backend to remedy this.)

Thank you. Apart from the 2D API, you mean that as long as the CPU performance is not too bad, video playback with integrated graphics card should not be too slow, right? I understand it correctly? Sorry, my English is poor. My machine is i7 CPU and win7 64 bit operating system. I disabled the independent graphics card and left the integrated graphics card. But it seems that the integrated graphics card is not really enabled. I'll find out why.

**Comment by rossy** [comment]
> Thank you. Apart from the 2D API, you mean that as long as the CPU performance is not too bad, video playback with integrated graphics card should not be too slow, right?

Yes, at least on my PC (i5-3570K) I can run mpv in a VM without hardware acceleration, and D3D11 in software mode (WARP) is fast enough to play 720p video. I'm not sure why it would be slow on yours.
