### ISSUE TITLE
Missing comma in options/path.c

### ISSUE THREAD

**Issue by qarmin** [mpv-player/mpv#7889]
after - `exe_dir` should be probably a comma, because instead "exe_dir" is created "exe_dirglobal"

```
static const char *const config_dirs[] = {
    "home",
    "old_home",
    "osxbundle",
    "exe_dir"
    "global",
};
```

**Comment by avih** [comment]
To be specific, this refers to commit c3694f0acb at file `options/path.c`, and I can confirm that adding this comma restores mpv ability to read config files from the exe-dir/ and from exe-dir/mpv/ .

**Comment by avih** [comment]
Thanks for identifying the issue.
