### ISSUE TITLE
sub-* options don't work with auto-profiles.lua

### ISSUE THREAD

**Issue by Columbo199X** [mpv-player/mpv#7890]
### Important Information
- mpv version 0.32.0
- Windows Version Windows 10 1909
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps

I use `sub-ass-styles=C:\Program Files\mpv\styles\640x480.ass` to override subtitle styling.
The .ass file needs to be set to the resolution of the video for the subs to scale correctly.
That's why I have multiple .ass files for different resolutions. Until now I've edited the config manually but I wanted to automate this using the auto-profiles.lua script.

`[640x480]`
`profile-desc=cond:(p["video-params/w"]==640 and p["video-params/h"]==480)`
`sub-ass-styles=C:\Program Files\mpv\styles\640x480.ass`
`osd-playing-msg="640x480"`

### Expected behavior
The corosponding .ass file gets loaded and overrides the sub styling when playing a video in the set resolution.
### Actual behavior
The script works as intended by recognizing the set resolution. But somehow none of the --sub options seems to work.

**Comment by wm4** [comment]
The option is applied only when the subtitle state is initialized (basically when first selection a subtitle track). This is inherent due to how libass works, and can't be easily fixed.

**Comment by Columbo199X** [comment]
Well that's unfortunate. But I appreciate the explanation and hope that someday there will be a work around for it.
