### ISSUE TITLE
display osc instead of progress bar on seek

### ISSUE THREAD

**Issue by github-account1111** [mpv-player/mpv#7891]
Whenever I seek the video, progress bar gets displayed. Any way to display the regular OSC instead (one that appears when I move mouse)?

**Comment by hooke007** [comment]
one of the solutions.
https://mpv.io/manual/master/#options-no-osd-bar
https://mpv.io/manual/master/#key-bindings

**Comment by github-account1111** [comment]
I don't see how that's a solution. With the del option I can only cycle through visibility modes. Same with https://mpv.io/manual/master/#on-screen-controller-osc-visibility

I've searched some more and I think this might be a duplicate #2891.

**Comment by jaseg** [comment]
Check out [python-mpv issue #124](https://github.com/jaseg/python-mpv/issues/124). The lua script there is a workaround until this gets solved in mpv.

**Comment by muzzol** [comment]
is there any work being done on this issue?

**Comment by danielb2** [comment]
is this going to be a fix @jaseg ? I think the ticket should be re-opened since the other issue referenced is just a "workaround" as you say

**Comment by danielb2** [comment]
I too am missing this

**Comment by AndydeCleyre** [comment]
FWIW I just learned to love uosc, which makes this easy.

**Comment by Yutsuten** [comment]
> Also it's possible to disable pop-up seek bar.

To save a few minutes of search for those who want to do the same thing, this is the setting you should put into `mpv.conf`:

```
osd-on-seek=no
```

Just to be clear, this just disables OSD on seek, there is no option to show OSC on seek yet.

**Comment by Xiarno** [comment]
> > Also it's possible to disable pop-up seek bar.
> 
> To save a few minutes of search for those who want to do the same thing, this is the setting you should put into `mpv.conf`:
> 
> ```
> osd-on-seek=no
> ```
> 
> Just to be clear, this just disables OSD on seek, there is no option to show OSC on seek yet.

Would love to show OSC on seek.

**Comment by guidocella** [comment]
```lua
local timer = mp.add_timeout(1, function ()
    mp.command('script-message osc-visibility auto ""')
end, true)

mp.register_event('seek', function ()
    mp.command('script-message osc-visibility always ""')
    timer:kill()
    timer:resume()
end)
```

**Comment by kasper93** [comment]
Fixed by: https://github.com/mpv-player/mpv/pull/14358
