### ISSUE TITLE
Replace wm4 with a sane maintainer

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mpv-player/mpv#7898]
This made me question his sanity: https://github.com/mpv-player/mpv/commit/cdaa496314f90412963f2b3211e18df72910066d

**Comment by haasn** [comment]
Can you define 'sane'?

**Comment by CounterPillow** [comment]
@koyuawsmbrtn please seek help, it's not too late. We can teach you how to install KDE today.

**Comment by Nexxkinn** [comment]
What?

**Comment by Argon-** [comment]
No.

**Comment by wm4** [comment]
Who do you suggest instead?

**Comment by richardpl** [comment]
Every second wm4 sentence is fuck, shit or something similar.

**Comment by wm4** [comment]
Yeah, that's very problematic, I should get banned.

Have you fixed your bugs in ffmpeg yet?

**Comment by Akemi** [comment]
let us know if you found someone who can stay sane in such a bullshit loaded and hostile environment, and still wants to mainly waste their personal time on multimedia especially mpv.

**Comment by wm4** [comment]
You had all the chances to do this after I gave away all my access rights to the github org. (and later when I wasn't around at all for a year or so), but nothing happened.

**Comment by koyuawsmbrtn** [comment]
Well I wouldn't do it, I'm just complaining. I don't care anymore, back to Windows.

**Comment by richardpl** [comment]
Im really thankful for wm4 applying my pr after numerous attempts that just failed when he was not arround here.

**Comment by haasn** [comment]
I still want somebody to define 'sane' to me and explain to me by what definition of the word @wm4 isn't.

**Comment by mlindner** [comment]
I'll give my upvote to this idea as well. Someone who doesn't attack users that report bugs would be a definite upgrade.

**Comment by Akemi** [comment]
enough is enough. i am sick of that spam.
