### ISSUE TITLE
--ao=alsa constantly causes delayed frames and stutter with --video-sync=display-resample

### ISSUE THREAD

**Issue by Dudemanguy** [mpv-player/mpv#7899]
### Important Information

Provide following Information:
- mpv version: git master
- Linux Distribution and Version: Arch/Artix (kernel 5.7.6)
- Source of the mpv binary: built
- If known which version of mpv introduced the problem: d27ad96
- Window Manager and version: sway 1.4-eeb90a79
- GPU driver and version: amdgpu 19.1.0-2

### Reproduction steps

Play a video with `--ao=alsa` and `--video-sync=display-resample`.

### Expected behavior

Smooth playback.

### Actual behavior

There's actually a ton of delayed frames. If the video in scene has a panning shot, this is extremely noticeable and has a lot of stutter. The more intensive rendering settings you throw at it; the worse it gets but you can still see the delayed frame count go up with just the two above settings. This only happens with `--ao=alsa`. Pulse is normal.

### Log file
https://0x0.st/itje.txt

This one is weird to me because I'm pretty sure I've used ao=alsa just fine after the audio api rewrite for quite a while. I almost wonder if there's something weird in the alsa drivers for me. I don't think it's an mpv bug (there's no way it would have taken someone this long to notice), but I'm curious if anyone else gets this.

**Comment by mc4man** [comment]
If you have pulseaudio then alsa is likely configured to  run thru pulse. (typically /usr/share/alsa/pulse-alsa.conf 
Try disabling autospawn (/etc/pulse/client.conf, uncomment, change to no), kill pulse (pactl exit) & try again, should be little to no frame issues.

**Comment by Dudemanguy** [comment]
Thanks, that was it. I swear I had my alsa configured to always pick the actual device and not the pulseaudio output. Looks like it doesn't happen anymore for whatever reason. I guess I can curse poettering or something again.

**Comment by rubyFeedback** [comment]
> I guess I can curse poettering or something again.

IMO it is more that pulseaudio is very complex. ALSA is simpler. I have found that without pulseaudio
I run into fewer problems in the long run. Since then I have become sceptical of "new changes" when
they come with higher cost of complexity. It's a trade-off from a user's perspective and for me personally,
I much prefer simplicity and simpler computer systems.
