### ISSUE TITLE
Support for matroska video resolution cropping

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#79]
vlc supports this feature of matroska container, please teach mpv to understand such mkv files.

**Comment by newyear2016happy** [comment]
You may refer to this step by step guide to crop video files at http://www.idealshare.net/video-converter/video-cropper.html

This guide helps to:

    Crop video at the same time keep or change the video size to  720x576, 704x576, 720x480, 640x480, 480x320, etc or enter the video size  as your desire;
    Crop video at the same time keep or change the video aspect  ratio among 16:9, 4:3, 2.35:1, 1.85:1, etc or enter your desired aspect  ratio;
    Crop video at the same time keep or change the video formats  to MP4, AVI, MOV, FLV, ASF, WMV, MPG, OGV, 3GP, MKV, WTV, DV, RM and so  on;
    Crop videos like crop YouTube video, crop MP4, crop AVI, crop  MOV, crop MKV, crop WMV, crop MPG, crop 3GP, AVCHD, MXF, WebM, OGV, WTV,  MOD, FLV, ASF, and more video formats;
