### ISSUE TITLE
Default play all DVD/Bluray tracks.

### ISSUE THREAD

**Issue by zzz0** [mpv-player/mpv#790]
When you play a dvd like this: ```mpv dvd:// --dvd-device=dvd.iso``` it defaults to playing the first track/title and that's it. I think it should take all the tracks and start them as a playlist, or there should be a way to do that. The same thing happens with Blurays except ```bd://``` is equal to ```bd://0```.

I can't seem to find anyway to play all tracks on a DVD as a playlist other than just doing ```dvd://1-<high-number-you-know-probably-exceeds-the-amount-of-tracks-on-the-disc>```. If there is a way to do it please tell me.

https://github.com/mpv-player/mpv/blob/master/stream/stream_dvd.c

This seems to be the file which handles all of this. Is there anyway to somehow just get the amount of tracks on a dvd, and set it so the default is basically ```dvd://1-amount_of_tracks```? It already detects the amount of DVD tracks and spits it out around line 748. I spent some time messing with that and this piece of code:

```
static const dvd_priv_t stream_priv_dflts = {
  .cfg_title = 0,
};
```

But I have no clue what I'm doing.

**Comment by tewe** [comment]
I'd appreciate this as well, especially since ://A-B only works for DVD, not BD.
