### ISSUE TITLE
Adjust Video Height?

### ISSUE THREAD

**Issue by ahizap** [mpv-player/mpv#7903]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Sometimes changing aspect ratio does not remove black bars from some videos so increasing the video height can solve that problem.In mpc be you can can do it by pressing 8 from the numpad so if something similar can be implemented in the mpv it would be great.

**Comment by Akemi** [comment]
changing the aspect ratio doesn't add black bars, neither does it remove black bars in the video itself. there is also panscan on the shortcuts `w` and `e`.

tbh you are very unspecific ("sometimes" is nothing we can work with) what you actually mean and want. for all i know there might be an issue. it's probably best to open a new issue.

**Comment by wm4** [comment]
5f49009849271ecd995f9f41e4eb2a36a0fc024a

**Comment by ahizap** [comment]
Thanks @wm4 this is exactly what i was looking for.
