### ISSUE TITLE
Crash when mpv tries to display an image over remote X over ssh

### ISSUE THREAD

**Issue by shlomif** [mpv-player/mpv#7906]
### Important Information

Provide following Information:
- mpv version
```
[shlomif@localhost ~]$ /opt/shlomif/mpv/bin/mpv --version
mpv 0.32.0-583-g7a7a0a78b5 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.49.100
   libavcodec      58.90.100
   libavformat     58.44.100
   libswscale      5.6.101
   libavfilter     7.84.100
   libswresample   3.6.100

FFmpeg version: git-snapshot-20200531-rpmfusion
```
- Linux Distribution and Version: fedora 32 x86-64 (via ssh from mageia 8 x86-64)
- Source of the mpv binary: self built using git
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: Plasma 5 (but I recall it also happened with jwm)
- GPU driver and version:

```
[shlomif@localhost ~]$ inxi -CSG
System:
  Host: localhost.localdomain Kernel: 5.7.8-200.fc32.x86_64 x86_64 bits: 64
  Desktop: N/A Distro: Fedora release 32 (Thirty Two)
CPU:
  Topology: Quad Core model: Intel Core i5-8259U bits: 64 type: MT MCP
  L2 cache: 6144 KiB
  Speed: 3780 MHz min/max: 400/3800 MHz Core speeds (MHz): 1: 3713 2: 3607
  3: 3653 4: 3756 5: 3756 6: 3599 7: 3607 8: 3634
Graphics:
  Device-1: Intel Iris Plus Graphics 655 driver: i915 v: kernel
  Display: server: Mageia X.org 1.20.8 driver: modesetting
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz
  OpenGL: renderer: llvmpipe (LLVM 10.0.0 256 bits) v: 3.3 Mesa 20.1.3
```
- Possible screenshot or video of visual glitches: it is a crash

### Reproduction steps

`/opt/shlomif/mpv/bin/mpv --no-config https://www.shlomifish.org/Files/files/images/before-and-after-reboot-uptime-uname.png`
when invoked from remote ssh is crashing. I built it using:

```
# Adapted from rpmfusion's mpv.spec . Also see:
# https://github.com/mpv-player/mpv/issues/7859
waf configure --prefix=/opt/`whoami`/mpv \
    --disable-build-date \
    --enable-libmpv-shared \
    --enable-sdl2 \
    --enable-libarchive \
    --enable-dvdnav \
    --enable-cdda \
    --enable-html-build \
    --enable-dvbin
```

VLC and gwenview with the same file (and all other input video and graphics files I tried)
do not crash over ssh.

### Expected behavior

Not crash.

### Actual behavior

Crash.

### Log file

[mpv.txt](https://github.com/mpv-player/mpv/files/4913796/mpv.txt) - the log output.

### Sample files

See https://www.shlomifish.org/Files/files/images/before-and-after-reboot-uptime-uname.png .

**Comment by CounterPillow** [comment]
Where's your log? Where's a gdb backtrace?

**Comment by shlomif** [comment]
[mpv.txt](https://github.com/mpv-player/mpv/files/4913796/mpv.txt) - the log output

**Comment by shlomif** [comment]
[gdb.txt](https://github.com/mpv-player/mpv/files/4913923/gdb.txt) - gdb backtrace @CounterPillow .

**Comment by CounterPillow** [comment]
Crash happens in Intel's Vulkan layer during probing for Vulkan support.

Your system's graphics setup seems messed up in general, presumably you have an Intel integrated GPU but are doing software rendering with llvmpipe, which is a peculiar choice.

**Comment by Akemi** [comment]
seems like an upstream driver issue.
