### ISSUE TITLE
WASAPI breaks after closing music file in exclusive mode on Windows CLI

### ISSUE THREAD

**Issue by RossSmyth** [mpv-player/mpv#7908]
### Important Information
Windows 10 Home Version 10.0.18362 Build 18362
```
mpv 0.32.0-579-g06033df715 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
built on Sat Jul 11 10:01:37 +08 2020
FFmpeg library versions:
libavutil       56.55.100
libavcodec      58.95.100
libavformat     58.48.100
libswscale      5.8.100
libavfilter     7.87.100
libswresample   3.8.100
FFmpeg version: git-2020-07-10-6f84e9217
```
shinchiro's build from Sat Jul 11 2020

### Reproduction steps

1. Open longer music file on Windows CLI with WASAPI in exclusive mode with keep-open set
What I used for testing:
`mpv --audio-exclusive=yes --ao=wasapi --no-config --no-video --keep-open=yes .\test.flac`
2. Let it play to end (possibly not required)
3. Close the PowerShell window (do not quit with "q")
4. Open the same file or another with the same settings as 1.

I used a .flac file for testing.

### Expected behavior
Can play other files after closing.

### Actual behavior
Does not play, error seen is `The device does not recognize the command. (0x80070016)`

Seems to only happen with longer files. I generated a .flac file with ffmpeg that was 10 seconds long and it worked after 10 tries of closing and reopening. I generated one that is 70 seconds long (how long the song is I noticed this on) and it failed the first try. This failure only effects exclusive mode, and it can run in shared mode fine afterwards. To fix exclusive mode the only way I have found is to restart my computer.

Has a different error than #7787 so I do not think it is the same, but what do I know (not much).

### Log file
Log file of successful run before failure:
http://0x0.st/itD_.log

Log file of run right after the previous:
http://0x0.st/itDf.log

### Sample files

I just generated a test file with ffmpeg using 
`ffmpeg -f lavfi -i "sine=frequency=1000:duration=70" -ac 2 test.flac`
may not need to be stereo but I was just replicating the file I noticed on.

---
Thanks for your help.

**Comment by RossSmyth** [comment]
Seems to be fixed.

**Comment by Atronach** [comment]
> Seems to be fixed.

Unfortunately it's broken again. Getting the same error 0x80070016 when _--audio-exclusive=yes_ is used. Tested w/ mpv v0.34.0 otherwise supplied w/ the latest SMPlayer.

[Log file.](https://github.com/mpv-player/mpv/files/11552422/mpv.log)

Exclusive mode works as such on my system as I can verify so w/ MPC-BE.
