### ISSUE TITLE
How to how to go to the beginning of a ab-loop before the end of the loop?

### ISSUE THREAD

**Issue by jpggithub** [mpv-player/mpv#7912]
I use ab-loop a lot to listen some extracts of music files.

I don't find how to go to the beginning of the loop before the end of the loop.

I tried to bind a key to "seek ab-loop-a" but it did not work.

The other solution could be to use the revert-seek functionality but it supposes to know what I want to do before making a loop so it seems useless in this case.

Is there a solution for my problem?

Thanks for your attention

**Comment by wm4** [comment]
"set playback-time ${ab-loop-a}" will probably work.

**Comment by jpggithub** [comment]
Thanks a lot, it works very well!
I used the following line in my `input.conf`:
`b set playback-time ${ab-loop-a}`
