### ISSUE TITLE
Support .netrc file for secure network streaming

### ISSUE THREAD

**Issue by plittlefield** [mpv-player/mpv#7914]
Could you please implement an automatic feature or configurable setting to use the .netrc file for secure network streaming?

https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html

So, instead of having to type the username and password on the command line...

`mpv sftp://username:password@192.168.0.252/home/username/movie.mp4
`

...you would just type the hostname and mpv would automatically match that in the netrc file...

`192.168.0.252 username password`

`mpv sftp://192.168.0.252/home/username/movie.mp4
`

**Comment by wm4** [comment]
To even be able to implement this, we'd probably need ffmpeg support - so good luck.

**Comment by plittlefield** [comment]
Excuse my confusion but why would you need anything from an audio and video transcoder to get network functionality?!

**Comment by CounterPillow** [comment]
Most protocols are done in ffmpeg too, including this one. What it requires is some AVOpts to set the user and password, which I can patch in if need be because I've done it before for the ftp protocol implementation.

**Comment by plittlefield** [comment]
OK. I just thought it would make sense for one neat Linux command line software to make use of another Linux command line idea!

**Comment by plittlefield** [comment]
I think you'd get some votes if it came to it!

**Comment by andreasnuesslein** [comment]
vote

**Comment by plittlefield** [comment]
Yes please!

**Comment by Akemi** [comment]
closing since we would need ffmpeg support for this. if it already has by now or will get support for it please open a new issue.

**Comment by rihaq** [comment]
> closing since we would need ffmpeg support for this. if it already has by now or will get support for it please open a new issue.

Arrogant 🤦‍♂️

**Comment by Akemi** [comment]
> Arrogant 🤦‍♂️

please look up the definition of arrogant. this obviously isn't the right situation for using it. locking the comments for obvious reasons.
