### ISSUE TITLE
[Help] How to get video stream frames for some customized process such as face detection?

### ISSUE THREAD

**Issue by ll1007** [mpv-player/mpv#7916]
I am doing a project want to show face detection and labels on a real-time 4k video stream. Is there a way get video stream frames from mpv inner process?

**Comment by Akemi** [comment]
you could use the screenshot-raw command, though it won't give you the raw decoded frame but the already processed one in RGB. this is probably still applicable https://github.com/mpv-player/mpv/issues/6370.
