### ISSUE TITLE
scaletempo active even when speed=1

### ISSUE THREAD

**Issue by nevubm** [mpv-player/mpv#7917]
### To reproduce
`mpv --af-add="scaletempo=stride=10:overlap=1:search=250" --speed=1 video.mp4`
Playback will be very slow since scaletempo is active, but it should be disabled, since speed=1
(the `search` parameter is purposefully set insanely high for demonstration only)

### Details
In the default config, when `speed` is set to something other than 1, `scaletempo` is automatically inserted into the filterchain. However, there is no way to configure the parameters of this auto-inserted `scaletempo`, so if we want to change a parameter like `stride`, `overlap`, or `search`, we need to `af-add=scaletempo` manually.

But the user-added `scaletempo` is always active, even at `speed=1`, which can be problematic if you've tuned scaletempo to give higher quality playback, making it more computationally intensive. This can be fine for speeding up stereo audio, but when going back to play 6 channel audio even at normal speed, or just if other audio filters are active, the additional load can make mpv drop frames and stutter playback, even though `scaletempo` is really doing nothing.

I would like the user-added scaletempo to behave the same way as the auto-added scaletempo, disabling itself when speed=1. Or alternatively provide a way to configure the parameters of the auto-added scaletempo. (Since the auto-added scaletempo doesn't appear in the user-configurable filterchain, only internally, there is currently no way to interact with it)

**Comment by Akemi** [comment]
you can most likely write a script for that by observing a property.

**Comment by nevubm** [comment]
`mp.observe_property('speed', 'native', fn)` doesn't work for some reason. The function is never called

**Comment by nevubm** [comment]
nvmd, it does work
