### ISSUE TITLE
C headers and pkgconfig not installed with --enable-cplugins

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#7918]
### mpv version and platform versions

mpv-0.32.0-r1 on Gentoo Linux

### Reproduction steps

When building mpv with `--enable-cplugins`, I would expect headers and pkgconfig to be installed, to be able to build C plugins. This does not happen. `--enable-libmpv-shared` does install these however, which for mere plugin-building shouldn't be necessary (verified by copying headers and defining their locations manually) and imo is not immediately clear.

### Expected behavior

Install headers and pkgconfig

### Actual behavior

Doesn't install headers and pkgconfig

### Log file

[config.log without --enable-libmpv-shared](https://0x0.st/ivKP.log)

Also see https://bugs.gentoo.org/703360

Thanks a lot!

**Comment by Dudemanguy** [comment]
I don't think you need pkgconfig for cplugins. I think the only thing you need is the `client.h` which is indeed not installed with only cplugins enabled. It only gets installed if libmpv is enabled.

**Comment by haarp** [comment]
The only C plugin I have experience with is https://github.com/hoyon/mpv-mpris, and it required these headers when I tried to compile it:

```libmpv/{client.h,stream_cb.h}
misc/{bstr.h,mpv_talloc.h}
mpv/client.h
osdep/compiler.h
ta/{ta.h,ta_alloc.h}
```

its Makefile also looked for a pkgconfig:

```Package mpv was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mpv' found
```

I can't speak for other plugins, tho.

**Comment by Dudemanguy** [comment]
What I said earlier was wrong. You don't need any headers or anything to run a plugin at all (my bad). You only need the development files to compile the .so plugin. So it's just a make dependency but not an actual runtime one. After you have the .so file, you can just use it like you use a lua script.

**Comment by Dudemanguy** [comment]
Not sure why I did not close this ages ago, but as explained above the libmpv development files are not needed to simply run cplugins. You only need those if you are actually building some yourself.
