### ISSUE TITLE
Proactive frame skipping

### ISSUE THREAD

**Issue by weedy** [mpv-player/mpv#792]
This is more of a wish list item.

I throttled down my CPU and got a 60fps 10bit as to force software rendering.
Now since hollywood and junk uses 24fps I should almost be able to render every other frame and end up with smooth looking playback of this 60fps file.
I know I'm over simplifying this as I know nothing of how mplayer/mpv works internally and very little in regards to H.264 decoding.

I spent some time screwing around with `autosync` and `mc` set to stupid high values and was able to get to a point where `A-V:` stayed under 0.3 and `Late:` incremented by less then 5 for the most part. Except when the video locked up for what seemed like the full `mc` interval (which was really high at this point). So the file would play acceptably up until mpv "hiccuped" maybe once per minute. It seems like it would mostly work, if only we could be proactive with frame skipping. Again not knowing how mpv decides when to drop frames, if we knew we were at risk of falling behind we could just skip 1 or 2 future frames entirely.

Once we have a slave API this could help get all the embedded guys off mplayer.

**Comment by wm4** [comment]
Whatever this issue was about... but there's actually an IPC protocol now.
