### ISSUE TITLE
Stop playing and just not quit (and I don't want to see last frame of current playing video)

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#7921]
Right now I set like below.

`--keep-open=yes`
`--keep-open-pause=no`

It keeps video file busy and can't delete it by standard method (PC).
So I don't want to quit mpv each time to delete video file, now I regularly quitting mpv to delete video files (that is annoying ).

_(English isn't my native language, hope I explained well enough.)_

**Comment by wm4** [comment]
--idle?

**Comment by Max-Enrik** [comment]
I tried it but nothing changed.

**Comment by thebombzen** [comment]
You need to use `--keep-open=no` and `--idle=yes` at the same time. In pseudo-GUI mode it will return the player to the default state of "drag and drop to play." From the command-line it will close the window but leave the player open outside.
