### ISSUE TITLE
`--prefetch-playlist` for on disk files

### ISSUE THREAD

**Issue by smhmd** [mpv-player/mpv#7926]
Using [btfs](https://github.com/johang/btfs), I mount torrents on disk and can stream them.

### Expected behavior of the wanted feature
`--prefetch` flag to open the next file in directory/playlist (`$ mpv --prefetch  .`,) so btfs can cache it.

### Alternative behavior of the wanted feature
none.

### Log file
n/a

**Comment by thebombzen** [comment]
What happens if you use `file://` prefixed to your locally-mounted files?

**Comment by smhmd** [comment]
@thebombzen. I don't know what you mean. Could you give me a complete command to run? We can use this torrent (educational purposes) for testing:
```fish
mkdir -p /tmp/btfs/understanding_linguistics
btfs 'magnet:?xt=urn:btih:6c0c4654d0c89ffb625ba407367c1ef357071229&dn=TTC%5F-%5FUnderstanding%5FLinguistics%5F-%5FThe%5FScience%5Fof%5FLanguage&tr=udp%3A%2F%2Fopen.stealth.si%3A80&tr=http%3A%2F%2Ftracker.city9x.com%3A2710&tr=http%3A%2F%2Ft.nyaatracker.com%3A80&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Fthetracker.org%3A80' /tmp/btfs/understanding_linguistics
cd /tmp/btfs/understanding_linguistics/TTC_-_Understanding_Linguistics_-_The_Science_of_Language
mpv . # file://??
```

**Comment by bitraid** [comment]
https://mpv.io/manual/master/#protocols

**Comment by smhmd** [comment]
@thebombzen @bitraid I don't think it did anything differently. (command ran: `mpv file://00._Professor_Bio.mp4`.)

**Comment by bitraid** [comment]
You must add more than one file and the `--prefetch-playlist` option.

**Comment by bitraid** [comment]
And you should also try without the protocol, for example: `mpv * --prefetch-playlist` (should also work)

**Comment by Dudemanguy** [comment]
Tried this with some local files and got a `Using prefetched/prefetching URL` in the log so I assume this already works (if not feel free to reopen).
