### ISSUE TITLE
4K HEVC files stopped playing a few days ago. Shader compile error in log.

### ISSUE THREAD

**Issue by philip-han** [mpv-player/mpv#7927]
### Important Information

Provide following Information:
- mpv version:

mpv git-2020-06-09-d5de79d Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Jun 27 23:51:49 UTC 2020
FFmpeg library versions:
   libavutil       56.50.100
   libavcodec      58.90.100
   libavformat     58.44.100
   libswscale      5.6.101
   libavfilter     7.84.100
   libswresample   3.6.100
FFmpeg version: git-2020-06-05-cf28521

- Linux Distribution and Version

    Ubuntu 18.04 Bionic

- Source of the mpv binary

    Ubuntu mpv PPA - https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

- If known which version of mpv introduced the problem

    unknown

- Window Manager and version

    GNOME Shell 3.28.4

- GPU driver and version

    nvidia 440

- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Any 4k hevc encoded files with --hwdec=auto option. My video card is nVidia 1030GT.

### Expected behavior

Play normally

### Actual behavior

Used to play fine until a few days ago. Files play with blank blue screen but sound is ok.

### Log file

[error.log](https://github.com/mpv-player/mpv/files/4935002/error.log)

**Comment by mc4man** [comment]
Similar setup, fully updated, downgraded mpv to build you have, don't use gnome-shell but tried, can't duplicate.
Log if you want to compare.
 Maybe you did something locally in "the last few days" if this particular file previously worked
[mpv.log](https://github.com/mpv-player/mpv/files/4935839/mpv.log)

**Comment by haasn** [comment]
Fixed in c7fe4ae73ad5f073bbffe3e8a3460b728e7d0f46

**Comment by philip-han** [comment]
A new build dropped yesterday on the PPA and it's all good now.

Thanks to all!

**Comment by mc4man** [comment]
That build you got yesterday was older i.e git-2020-06-30-8fbc4b1, it didn't include above 'fix'.
There is new build in ppa now that's current.. (git-2020-07-16-96cdf53

**Comment by philip-han** [comment]
Thanks for the heads up.

FWIW, the 6-30 build was working for me as well as the latest one.
