### ISSUE TITLE
mpv does not display all text from the VobSub subtitles

### ISSUE THREAD

**Issue by ViktoriiaKh** [mpv-player/mpv#7928]
### mpv and macOS version
- mpv version: 0.32.0
- macOS Version: 10.15.5
- source of the mpv binary or bundle: built from https://github.com/mpv-player/mpv/releases/tag/v0.32.0 

### Reproduction steps

Play the video with subtitles enabled.

`$ ./mpv ./THE_ISLAND_chap2.mp4 --sid=1 --log-file=./mpv.log`

### Expected behavior

mpv displays all text from subtitles.

### Actual behavior

mpv displays only part of subtitles (in which the actors are speaking) and does not display other subtitles (translation of the text that appears on the wall).

For example, mpv displays subtitles that appear at **00:00:36**

![mpv 36sec](https://user-images.githubusercontent.com/19269642/87774917-edfbb100-c82d-11ea-8357-94bb48e39a3c.png)

and does not displays subtitles at **00:00:42**

![mpv 42sec](https://user-images.githubusercontent.com/19269642/87774934-f18f3800-c82d-11ea-971b-8439a5db2078.png)

VLC and mplayer display subtitles at **00:00:42**.

![vlc 42sec](https://user-images.githubusercontent.com/19269642/87774945-f3f19200-c82d-11ea-9456-f5d956accdc1.png)

![mplayer 42sec](https://user-images.githubusercontent.com/19269642/87774951-f5bb5580-c82d-11ea-90cc-01b6fc287c75.png)

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/4937085/mpv.log)

### Sample files

[Sample file](https://www.dropbox.com/s/fx2vurelpjsedrs/THE_ISLAND_chap2.mp4?dl=1)

**Comment by wm4** [comment]
This is a ffmpeg problem. We get the sub title packet for that time position, we feed it to the decoder, but we get nothing back.
mplayer and vlc have their own subtitle decoders, so they don't have the problem.
There's nothing we can do, report to ffmpeg.

**Comment by wm4** [comment]
This can be easily confirmed with ffprobe -show_packets and -show_frames, by the way.

**Comment by ViktoriiaKh** [comment]
OK, thank you for your help.

**Comment by jeeb** [comment]
Thanks for the sample, I will attempt to check if there's anything clear in the `dvdsubdec` decoder in FFmpeg. At least by default there should be no limitation of to only non-forced subpictures or so (there is a boolean option to only decode forced subpictures, but that is the other way, and off by default).
