### ISSUE TITLE
BT.2390 tone mapping creates artifacts on Linux

### ISSUE THREAD

**Issue by qyot27** [mpv-player/mpv#7929]
### Important Information

Provide following Information:
- mpv git-cdaa496314
- Ubuntu Budgie 20.04
- mpv, ffmpeg, zimg built from source/git
- Likely 'introduced' with git-c9f6c458, when BT.2390 tone mapping was added/made default
- budgie-wm (budgie-core 10.5.1-6)
- Intel UHD Graphics 630 (Desktop), i915 ; Core i5-9400

### Reproduction steps

`mpv --no-config bt2390-002.mkv`

### Expected behavior

Video plays without any distortion.  All of the other options for --tone-mapping act correctly.  With Mobius, for example:

![all-other-tone-mapping](https://user-images.githubusercontent.com/1296881/87737722-c105ba80-c7a9-11ea-95c0-a7c55d7657d4.png)

### Actual behavior

![bt 2390](https://user-images.githubusercontent.com/1296881/87737723-c236e780-c7a9-11ea-83bf-b66d69b23715.png)

The brightest areas of the image get inverted and seen as an explosion of black pixels when `--tone-mapping=bt.2390` is used.  This lasts for usually only a few frames, but can be persistent throughout any particular shot.  Things like parts of faces or even the sun get blotted out.

### Log file

Log for BT.2390 playback:
[bt2390.txt](https://github.com/mpv-player/mpv/files/4935189/bt2390.txt)

Log for Mobius playback:
[mobius.txt](https://github.com/mpv-player/mpv/files/4935190/mobius.txt)

**Comment by Doofussy2** [comment]
That almost looks like `--gamut-warning` is enabled. I wonder if `--gamut-clipping` is having an undesired effect?

**Comment by haasn** [comment]
Looks like it could be some sort of overflow bug. Seconding the suggestion to try with `--gamut-clipping=no`, just to be sure. But also try `--hdr-compute-peak=no`.

**Comment by qyot27** [comment]
`--no-config --gamut-clipping=no` did nothing, but `--no-config --hdr-compute-peak=no` seems to resolve it.

**Comment by haasn** [comment]
@qyot27 Does this patch fix it?

```glsl
diff --git a/video/out/gpu/video_shaders.c b/video/out/gpu/video_shaders.c
index 19b002170d..062acf2632 100644
--- a/video/out/gpu/video_shaders.c
+++ b/video/out/gpu/video_shaders.c
@@ -771,7 +771,7 @@ static void pass_tone_map(struct gl_shader_cache *sc,
         // Encode both the signal and the target brightness to be relative to
         // the source peak brightness, and figure out the target peak in this space
         GLSLF("float scale = 1.0 / sig_pq.a;                                    \n"
-              "sig_pq.rgb *= vec3(scale);                                       \n"
+              "sig_pq.rgb = min(sig_pq.rgb * vec3(scale), 1.0);                 \n"
               "float maxLum = %f * scale;                                       \n",
               pq_delinearize(dst_peak));
         // Apply piece-wise hermite spline
```

**Comment by qyot27** [comment]
Yes, that seems to have fixed it.
