### ISSUE TITLE
`mp.utils.join_path` not joining paths properly on Windows

### ISSUE THREAD

**Issue by persianpars** [mpv-player/mpv#7935]
### Important Information

Provide following Information:
- mpv 0.32.0-589-g96cdf5315e
- Windows 10
- Source of the mpv binary shinchiro 

### Reproduction steps
Using `mp.utils.join_path` in Lua on Windows:
```python
local utils = require 'mp.utils'
print(utils.join_path("C:\\tmp", "a.jpg"))
```

### Expected behavior
Paths should be joined by `\` in Windows

### Actual behavior
Paths are joined by `/`
Output of the above code:
```
C:\tmp/a.jpg
```
### Issue

I've been having some issues using the [subselect](https://github.com/zenyd/mpv-scripts) Lua script.
After debugging i've traced the issued and  looks like the `mp.utils.join_path` is joining paths with the `/` separator even in windows.

I think if the `\` is changed to `mp_path_separators` in the line below it would fix the issue:
https://github.com/mpv-player/mpv/blob/7c5c05771796468f96c97e03a692b0dbeb484e02/options/path.c#L292

**Comment by avih** [comment]
It's a known behavior, and generally shouldn't matter, because except for rare exception (like windows explorer), all programs should work with `/` the same as they work with `\`. See #6570.

Which progrogram behaves incorrectly due to this?

**Comment by zc62** [comment]
Just replace `/` with `\` in the lua script, like what avih pointed out in the original issue: https://github.com/mpv-player/mpv/issues/6565#issuecomment-473811768

**Comment by Dudemanguy** [comment]
Apparently this is expected.
