### ISSUE TITLE
Video playing black screen, sound playing normal, what's wrong?

### ISSUE THREAD

**Issue by levenies** [mpv-player/mpv#7936]
### Important Information

Provide following Information:
- mpv version : 2.0.0.0  mpv-dev-i686-20200126
- Windows Version  : win10
- Source of the mpv binary 
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Just open the HTTP web video

### Expected behavior
The screen can be displayed

### Actual behavior
The video is not shown, only the sound is playing

### Log file
https://github.com/levenies/test/blob/master/mpv.log

### Sample files
sorry , secrecy

**Comment by CounterPillow** [comment]
>[  59.848][e][vo/gpu/d3d11] Failed to create vertex buffer: GPU 设备实例已经暂停。使用 GetDeviceRemovedReason 以确定相应的措施。 (0x887a0005)

Your GPU is apparently disabled or otherwise broken.

>[   0.181][v][cplayer] mpv 0.31.0-87-gae0520cafc Copyright 漏 2000-2020 mpv/MPlayer/mplayer2 projects

please update

**Comment by levenies** [comment]
> > [  59.848][e][vo/gpu/d3d11] Failed to create vertex buffer: GPU 设备实例已经暂停。使用 GetDeviceRemovedReason 以确定相应的措施。 (0x887a0005)
> 
> Your GPU is apparently disabled or otherwise broken.
> 
> > [   0.181][v][cplayer] mpv 0.31.0-87-gae0520cafc Copyright 漏 2000-2020 mpv/MPlayer/mplayer2 projects
> 
> please update

It happens occasionally, and sometimes it plays normally

Which version is updated to? I'm worried that updating to the latest version will be unstable

**Comment by WizRay** [comment]
Use builds from [here](https://sourceforge.net/projects/mpv-player-windows/files/64bit/) or if you are ok using terminal, use [scoop](https://scoop.sh/) to install and update [mpv-git](https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv-git.json). Git versions are much more stable than point releases. From what I see, releases version are just references for devs imo.

**Comment by levenies** [comment]
Is it caused by full graphics memory? It is found that this problem is easy to occur when 16 times high speed is played

**Comment by EzeKees** [comment]
Same problem here
