### ISSUE TITLE
Event when external file reaches eof

### ISSUE THREAD

**Issue by tomashavlas** [mpv-player/mpv#7938]
Hi,

is there any event / hook, that I could use to capture eof of an external file? I'm trying to run following command:

```
mpv --external-file=extfile1.mkv --external-file=extfile2.mkv --lavfi-complex="[vid1][vid2][vid3] hstack [vo]" video.mkv
```
external files do not have equal length, and both are shorter than main video. I need to trigger an action when an external file reaches it's end. I've tried following script, but it doesn't catch eof of external file:

```
local msg = require 'mp.msg'

function eof_reached_callback(property, eof_reached)
  msg.debug("eof_reached", property, eof_reached)
end

mp.observe_property("eof-reached", "bool", eof_reached_callback)
```

is there a way how to achieve that? I haven't found anything I could use in the documentation.

**Comment by Akemi** [comment]
it might be possible with this https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/player/lua/stats.lua#L686-L718
