### ISSUE TITLE
how undo --opengl-backend=X11?

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#7941]
### Important Information

Provide following Information:
- mpv version
0.32
- macOS Version
10.9.1
- Source of the mpv binary or bundle
macports

### Reproduction steps

started to playback after error with 

mpv --opengl-backend=X11 (after installing XQuartz).

found out that this has several limitations; cannot "open-with-mpv" for example.
now i would like to "undo" this so that the mpv does remember the last setting;

### Expected behavior

playback also withouth opengl-backend=X11

or undo last setting

### Actual behavior

no able to revert to standard settings

no accurate info on --opengl-backends

no idea where --opengl-backend=X11 got "saved" on computer as no .conf file found

### Log file

https://paste.ubuntu.com/p/xDGP6C7s9z/

**Comment by sfan5** [comment]
mpv does not remember previous settings but it may pick X11 if it's available.
If you don't want it do to that you can uninstall/stop XQuartz or use `--vo=libmpv` (or `--gpu-context=cocoa` ?).

**Comment by Akemi** [comment]
mpv was build with --enable-x11, --disable-gl-cocoa and --disable-cocoa. cocoa needs to be enabled for it to work properly. also 10.9.1 ist not supported anymore.

**Comment by mrkapqa** [comment]
Thank you, it used to function previously without --enable-x11 on Mavericks.

when uninstalling XQuartz, i am able to revert the setting (not really elegantly) and 

[vo/libmpv] No render context set.
Error opening/initializing the selected video_out (--vo) device.

is the output on MacMini iwht only Intel HD 3000.

**Comment by mrkapqa** [comment]
Error parsing option gpu-context (option parameter could not be parsed)
Setting commandline option --gpu-context=cocoa failed.

**Comment by Akemi** [comment]
you have to rebuild your mpv, because if it is the same as in the log it's a broken not supported build. you don't have to set any option to make it work on runtime then. also we don't support OSX 10.9 actively anymore, either use an older mpv version or ask macports people how to get a working version.
