### ISSUE TITLE
Crash on taking screenshot with mpv version git-2020-07-16-96cdf53

### ISSUE THREAD

**Issue by Drugwash2** [mpv-player/mpv#7942]
### Important Information

- mpv version: **git-2020-07-16-96cdf53**
- Linux Distribution and Version: **Mint 19.2 Cinnamon x64**
- Source of the mpv binary: **2.0.32.0+git8~bionic**
- Which version of mpv introduced the problem: **2.0.32.0+git6~bionic** worked fine, so something after that one got faulty
- Window Manager and version: **Mutter (Muffin) 4.2.2**
- GPU driver and version: **NVIDIA 340.108-0ubuntu0.18.04.1**
- Possible screenshot or video of visual glitches: none

### Reproduction steps

Only tested in conjunction with SMPlayer, as this was always the setup. Current version: **SMPlayer v20.6.0 (rev9418) with Qt 5.9.5**.
Everything worked fine with mpv up to and including **2.0.32.0+git6~bionic**; issue appeared only after update to **2.0.32.0+git8~bionic** (current **git-2020-07-16-96cdf53**).
- start playing a video file
- pause playback (*optional)
- press **S** for video-only screenshot or **Ctrl+Shift+S** for video+subtitles

### Expected behavior

Screenshot is taken and saved to dedicated folder, OSD message notifies of the operation.

### Actual behavior

About 5 seconds after pressing one of the key combinations crash report messagebox will apear, playback is stopped.
No image file is saved, no OSD message is displayed.

### Log file

Relevant part of the SMPlayer crash log:
```
Starting screenshot: '/media/XXXXX/Data/Downloads/Pictures/Screenshots/smplayer_screenshots/cap_XXXXX.png'
using 3 threads for scaling
Using zimg.
mpv: ../video/zimg.c:241: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
mpv: ../video/zimg.c:241: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
mpv: ../video/zimg.c:241: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
```

### Sample files

None.

**Comment by CounterPillow** [comment]
can you try with `--zimg-threads=1`? See https://github.com/mpv-player/mpv/commit/2a89da0c8548bec624f7f60f0b08d98602c7d394

**Comment by Drugwash2** [comment]
> can you try with `--zimg-threads=1`? See [2a89da0](https://github.com/mpv-player/mpv/commit/2a89da0c8548bec624f7f60f0b08d98602c7d394)

Thank you for replying. If you could please be more specific as to where exactly to operate the change; I'm relatively new to Linux and don't know where configuration files are stored for each application.

**Comment by Akemi** [comment]
since seems to be a zimg problem which is only in master without a release, i will close this. since it's also apparently fixed in a later master only commit i guess you should report that to whoever is maintaining the package(?) or did the build.

**Comment by CounterPillow** [comment]
>Thank you for replying. If you could please be more specific as to where exactly to operate the change; I'm relatively new to Linux and don't know where configuration files are stored for each application.

Please see https://mpv.io/manual/master/#configuration-files for more information.

**Comment by Drugwash2** [comment]
> Please see https://mpv.io/manual/master/#configuration-files for more information.

Thank you again, this will surely be useful for people using mpv as a standalone player.
For those who, like me, use SMPlayer with mpv, the relevant place to add the recommended parameter would be:
**SMPlayer main menu > Options > Preferences > Advanced >> Mplayer/mpv [tab] > Options**.

For now I have downgraded mpv to **2.0.32.0+git7~bionic** which does not exhibit the issue, removed the parameter from SMPlayer and ignored the current update for mpv, so that future updates would remind me if the bug is still present or has been fixed.

**Comment by jeeb** [comment]
@Drugwash2 , for your information it would actually improve the possibility of it getting fixed if the actual specific state where the issue happens could be figured out. Clearly it did not crash for the person who added this feature so if you have setup where it crashes it'd be nice to figure out.

This starts with giving a full `--log-file=mpv_sucks.log` log file for the issue (which would include various information about the clip that made this happen, as well as other details that could be useful). This I think was mentioned in the issue template.

I do not know if the PPA you utilized for your binaries has debug symbols, but if it has, it'd be nice if you could run the crashing case with `gdb` in the following manner:
```bash
gdb --args mpv --your --usual --options

... wait until it says it has loaded symbols for mpv etc ...
... do the r command to run mpv ...
... as it crashes, do the "bt full" command to get the full backtrace, which you can then post here ...
```

**Comment by mc4man** [comment]
Using same mpv build, same smplayer see no issue with screenshots (zimg is used.
So maybe mutter, mint cinnamon, whatever..

As far as ppa's, debug packages aren't produced by default for good reason, will never show in package manager nor apt.
There is a mpv ddeb in ppa, to use it has to be manually downloaded and installed. It depends on exact same mpv package version so mpv needs updating to that ddeb version if not already.

Or build locally.

Don't see any commits  concerning  this after 07/16..
