### ISSUE TITLE
Jump back and forward based on the subtitles?

### ISSUE THREAD

**Issue by camenduru** [mpv-player/mpv#7946]
Hi I am learning english and japanese with double sub and if I can jump back and forward based on the subtitles it will be perfect for language learners. thanks.

**Comment by CounterPillow** [comment]
Please read the manual:

> **Ctrl+LEFT and Ctrl+RIGHT**
>    Seek to the previous/next subtitle. Subject to some restrictions and might not always work; see sub-seek command.

https://mpv.io/manual/master/
