### ISSUE TITLE
audio-stream-silence causes audio device underruns and audio video desyncs

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#7948]
### Important Information

Provide following Information:
- mpv version: master as of 1fe6def066ec9955fb8cbbe18954802655f52a23
- Linux Distribution and Version: Latest arch linux as of July 26th 2020, uname -a: `Linux archHTPC 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux`
- Source of the mpv binary: git self-compiled
- If known which version of mpv introduced the problem: Some version of mpv installed since beginning of 2020. Likely happened with the audio AO API rewrite.
- Window Manager and version: i3 version 4.18.2
- GPU driver and version: NVidia proprietary 450.57
- Possible screenshot or video of visual glitches: None

See: https://github.com/mpv-player/mpv/issues/6109 for additional comments that I added.

### Reproduction steps

Make sure to use latest master and use the option --audio-stream-silence.

Start playing the file for a bit, then pause it, wait a second, then very rapidly unpause and pause the player again.

### Expected behavior

Audio pauses with the video when the video is paused and no errors are output and no audio-video desync upon unpausing.

### Actual behavior

After unpausing and pausing again the video pauses again but the audio does not. The audio places for less than a second up to several seconds. When eventually unpausing again there's a large audio-video desync (demonstrated in log). The maximum length extra audio playing can be generated by waiting until the audio stops playing while paused, and again rapidly unpausing and pausing again which will play audio for several seconds.

Finally, if you seek while paused to a point further in the file, the player completely breaks and unpausing it causes no effect. You become stuck in a semi-permament state. Pausing and unpausing have no effect. If left for around 1 minute in the unpaused state, the player eventually figures out something is wrong and starts playing video again. Nothing is reported in the log when this eventually happened other than a simple "Audio device underrun detected." again. I didn't include this second part in the log. If needed I can provide an additional log of this happening, but there's nothing to see.

### Log file

https://0x0.st/iwF6.log

### Sample files

Any file should work.

**Comment by wm4** [comment]
Get a proper DAC, so you don't need this feature. I originally implemented this only because I was paid a lot to cater towards people with consumer garbage hardware; now I'm paid nothing and I don't give a shit that I broke this "feature".
Maybe I'll restore it after the audio rewrite is done, just to shut up the likes of you.

**Comment by alucard0134** [comment]
well... that escalated quickly

**Comment by mlindner** [comment]
> Get a proper DAC, so you don't need this feature. I originally implemented this only because I was paid a lot to cater towards people with consumer garbage hardware; now I'm paid nothing and I don't give a shit that I broke this "feature".
> Maybe I'll restore it after the audio rewrite is done, just to shut up the likes of you.

You're a disgusting person. You attack everyone in every single one of these damn issues. If you're not interested in being part of mpv then quit the project and go somewhere else.

**Comment by mlindner** [comment]
We go to the effort of finding your bugs for you and then you attack the people who find the bugs. Get a life.

**Comment by nannerpusser** [comment]
> Get a proper DAC, so you don't need this feature. I originally implemented this only because I was paid a lot to cater towards >people with consumer garbage hardware; now I'm paid nothing and I don't give a shit that I broke this "feature".
> Maybe I'll restore it after the audio rewrite is done, just to shut up the likes of you.

Seeing a dev grow a pair and go Joseph fucking Stalin on a public ticket excites my jimmies. As hard as the Soviet hammer and as bent as the sickle.

**Comment by mlindner** [comment]
Now that wm4 is gone, is there any hope of this getting fixed? What happened to the audio rewrite?

**Comment by jeeb** [comment]
Audio rewrite seemingly got done, and most AOs seem stable now. Not sure anyone of the active people right now has the priority for this, but if a patch is posted and doesn't look too bad + doesn't introduce regressions it has relatively good chances of being accepted.

**Comment by DarkHalo117** [comment]
Solved it for me. I went [here](https://mpv.io/manual/master/#audio-output-drivers) and followed instructions for setting the Pulse audio rate. I set it to the max at 2000 and that solved my issue. I was streaming twitch.tv video and was having that issue and now it's resolved.

**Comment by Akemi** [comment]
apparently not a problem anymore. if this issue still persists please open a new issue.
