### ISSUE TITLE
ICC profile & gamma: Possible to keep it untouched for any content?

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#7951]
I've calibrated the display via DisplayCal and set up relative gamma of 2.4 for it. The profile is installed for the display via DisplayCal, so gamma is adjusted gobally via 1D LUT. mpv seems to work well with the profile (no warning about unset contrast etc.), colors look sane.

However: It seems to set gamma to a higher value with BT.1886 content, probably 2.2 to "compensate" the 2.4 of the ICC profile?
When I manually define `--vf=format:gamma=gamma2.4`, gamma looks the same as when mpv is configured to ignore the ICC profile (i.e. right to my eyes in a dimmed environment).

However, setting `--vf=format:gamma=gamma2.4` makes HDR videos look washed out, so I'd rather have a solution that works universally. Is this possible?
I can achieve this by injecting a 3D LUT created by DisplayCal via ReShade/vkbasalt, but of course I'd rather have an unhacky solution with what mpv offers.

Writing this with a different device, can attach a log later if required.

**Comment by Doofussy2** [comment]
@aufkrawall can you attach a picture of what the higher gamma looks like? I'm curious to see if it's the same result I get...

**Comment by aufkrawall** [comment]
No ICC profile:
![noicc](https://user-images.githubusercontent.com/13510490/88913321-f3f78600-d260-11ea-9046-c700f315cf07.png)

icc-profile-auto:
![iccdef](https://user-images.githubusercontent.com/13510490/88913347-040f6580-d261-11ea-9789-66855c24b0fd.png)

icc-profile-auto + vf=format:gamma=gamma2.4:
![iccgamma2 4](https://user-images.githubusercontent.com/13510490/88913383-14bfdb80-d261-11ea-8295-68af23fa9d2e.png)

Images probably should be looked at without color management enabled.
Log file:
[output.txt](https://github.com/mpv-player/mpv/files/5000672/output.txt)

It's also interesting that Chromium doesn't use a brighter gamma with my ICC profile, while Firefox does. Though neither one looks correct compared to mpv gamma 2.4 or DisplayCal 3D LUT. 😆

**Comment by aufkrawall** [comment]
@haasn I noticed that also HDR videos are brighter with my ICC profile and unlike for content that is treated as bt.1886, it seems there is no equivalent workaround like `--vf=format:gamma=gamma2.4`.

Am I missing an option that would serve my purpose? If not: Would it be possible to implement an option that doesn't adjust gamma based on ICC information (if that's the cause)? To my eyes and viewing conditions, the current behavior just unnecessarily reduces contrast by that gamma adjustment. I'd lust like mpv to consider my display's native color space, without doing other adjustments. :)

**Comment by aufkrawall** [comment]
Closing, as I think it might be justified to report it as an actual bug.
