### ISSUE TITLE
Display only the title of the video in the window title

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [mpv-player/mpv#7952]
Hi.
I think the information in the window header is redundant and I want to hide it, leaving only the name of the file being played. So, for example, the standard header is displayed: "MythBusters.mp4 - mpv", I only want to get "MythBusters".

How can I do that?

I use Archlinux, Pantheon and Mpv.

**Comment by avih** [comment]
https://mpv.io/manual/master/#options-title

**Comment by Khomyak-sibiryak** [comment]
@avih, I get "MythBusters.mp4", but as I said earlier, I need to hide the file format from the header as well.

**Comment by avih** [comment]
Well, you first need to read the manual, then tell us what you did, what you expect, and what happened which you didn't expect.

Hint: you should look at the `filename` property at the "Property list" section.

**Comment by CounterPillow** [comment]
`--title='${filename/no-ext}'`

**Comment by Khomyak-sibiryak** [comment]
Thank you very much!

**Comment by Khomyak-sibiryak** [comment]
@CounterPillow This option works well for local files, but videos with YouTube have part of the link instead of the normal name, how to solve this problem?
