### ISSUE TITLE
 Request a new Feature speed control

### ISSUE THREAD

**Issue by tqangxl** [mpv-player/mpv#7953]
add 1.25 1.5 1.75 2x  speed   control

Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by avih** [comment]
There are builtin keys to change the speed, as described at the manual: https://mpv.io/manual/master/#interactive-control

You can also assign your own keys to cycle a fixed set of values https://mpv.io/manual/master/#command-interface-cycle-%3Cname%3E-[%3Cvalue%3E]
