### ISSUE TITLE
Mpv crashes and locks up system when closing window on Linux Ubuntu i3.

### ISSUE THREAD

**Issue by 00krishna** [mpv-player/mpv#7959]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.28.0+git-816d82f Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 23 23:35:50 UTC 2019
ffmpeg library versions:
   libavutil       56.29.100
   libavcodec      58.53.100
   libavformat     58.28.100
   libswscale      5.4.101
   libavfilter     7.55.100
   libswresample   3.4.100
ffmpeg version: git-2019-06-24-c8232e5
```
- Linux Distribution and Version - Ubuntu 18.04 LTS x64
- Source of the mpv binary - ubuntu PPA
- If known which version of mpv introduced the problem NA
- Window Manager and version - i3 window manager - i3 version 4.14.1 (2017-09-24)
- GPU driver and version - nvidia 410.79
- Possible screenshot or video of visual glitches -- I can't get a screenshot since it crashes and freezes computer. 

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

The problem does not happen every time I watch a video. But if I watch a few different videos, inevitably after say 5-6 video, the player will crash and freeze my system. And it seems like the screen tears too, meaning that the i3 windows manager will also show lines through it, etc. I just have to do a hard reset at that point. 

What triggers the crash is when I click the Alt+Shift+q key to close mpv. That is the standard way to close an application in i3. At that point, the screen freezes. 

I am running mpv on my laptop, so only a single screen. But this keeps happening over and over again. 

### Expected behavior
Expected behavior is for the mpv window to close and the rest of the computer will continue. 

### Actual behavior
The actual behavior is that the system freezes and I have to do a hard reset. 

### Log file
I will try and make a log file. Since the problem does not occur each time, it is a bit hard to capture the problem occurring. 

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
>mpv 0.28.0+git-816d82f

ancient and not even a commit that exists in this repository. Also, if something crashes your X server and locks up your system, it's probably the nvidia driver's fault.

**Comment by 00krishna** [comment]
@CounterPillow Hmm, so I downloaded mpv2 from the Ubuntu PPA. I just did `mpv2 --version` but if that is wrong then what would the correct command be. I just installed the latest version from the PPA, so is the PPA out of date? I agree that the nvidia drivers are usually the culprits. Just figured I would check before going through the pain of changing my nvidia driver and potentially corrupting my system. LMK what the correct command is for getting the version number, thanks.

**Comment by mc4man** [comment]
Re: mpv2
That was a requested curiosity when what's his name left for a while. If you had read the page you'd know that.
Was packaged to allow installing/running alongside mpv.
Since been removed as it's value  is nil, you should also do the same..

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
