### ISSUE TITLE
Adding grain AFTER resizing?

### ISSUE THREAD

**Issue by Ryuukishi** [mpv-player/mpv#7960]
I want to use a film grain shader during playback to mask some artifacts and compression noise on low quality videos but the grain always looks very soft and blocky because the grain is added before resize so when I play the video on full screen mpv resizes the grain alonmg with the video. Is there a way to add the grain after resize so that the grain looks sharp?

**Comment by Akemi** [comment]
use a shader that does exactly that oder rewrite the shader (that you didn't even provide) to use the POSTKERNEL, SCALED or OUTPUT hook, which is the texture after scaling. look at the doku for the **glsl-shade**r option.
