### ISSUE TITLE
Video in root windows does not display when a compositor is active (picom)

### ISSUE THREAD

**Issue by AlecsFerra** [mpv-player/mpv#7967]
### Important Information

Provide following Information:
Arch Linux, Xorg

### Reproduction steps
``` bash
picom & # start compositor
mpv --wid=0 --loop=inf /path/to/video
```

### Expected behavior
The video is displayed as the wallpaper

### Actual behavior
Nothing happen, otherwise if the compositor is killed it works

**Comment by mia-0** [comment]
That’s a picom issue. Looks like it stores a pixmap of the root window and only updates it when it sees a root window property notification with a new pixmap (e.g. when changing the wallpaper with something like feh).
