### ISSUE TITLE
Integrate with KDE Plasma media player component

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#7968]
KDE Plasma has a feature that when media player is opened, it can integrate with media controls widget in the system notification area. It works for example with VLC and with audio / video in Firefox when plasma browser integration is enabled.

I noticed that it doesn't happen for mpv. It would be nice for mpv to integrate with it too. I'd need to look into how exactly it's done if you are interested in details.

**Comment by sfan5** [comment]
I believe this functionality is called mpris.
A script that implements this exists here: https://github.com/hoyon/mpv-mpris

**Comment by shmerl** [comment]
Thanks for the pointer! Would it be useful to upstream into mpv itself, to avoid the need for plugin?

**Comment by shmerl** [comment]
Found some details here: https://specifications.freedesktop.org/mpris-spec/latest/

**Comment by Dudemanguy** [comment]
There definitely won't be a dependency on dbus added upstream or in the case of that plugin, glib as well. I believe the plugin does what you want though so I'll close this issue.

**Comment by shmerl** [comment]
No problem, thanks.
