### ISSUE TITLE
Modifying chapter-list at runtime does not redraw OSC chapter nibbles

### ISSUE THREAD

**Issue by danlamanna** [mpv-player/mpv#7969]
When modifying the `chapter-list` property directly from a lua extension, the state of the player correctly navigates between chapters. The seek bar that hovers over the middle of the video has the correct nibbles with the newly added chapters, however the bottom osc bar only retains the nibbles from the chapters that existed on load. Is it expected that the osc bar won't reactively update, or is this a bug?

For instance:
![marker_nibbles](https://user-images.githubusercontent.com/608229/89239256-ab283000-d5c6-11ea-9bb4-3ff004cba2e8.png)

### Log file
[out.txt](https://github.com/mpv-player/mpv/files/5019412/out.txt)

**Comment by thebombzen** [comment]
Chapter nibbles are drawn once with the expectation that chapters cannot change at runtime. Since scripts *can* change chapters at runtime, they should be redrawn if so. Not necessarily every repaint, but at least once upon every chapter list change.

**Comment by danlamanna** [comment]
Thanks! What is the recommended way of triggering a redraw?

**Comment by agreselin** [comment]
Hey! Sorry to pollute the thread but what lua extension allows you to edit the `chapter-list` @danlamanna?

**Comment by danlamanna** [comment]
> Hey! Sorry to pollute the thread but what lua extension allows you to edit the `chapter-list` @danlamanna?

It was an extension that was developed in-house that's still closed-source, unfortunately.

**Comment by avih** [comment]
> however the bottom osc bar only retains the nibbles from the chapters that existed on load. Is it expected that the osc bar won't reactively update

It was expected because the chapters were initialized only once, because typically chapters don't change.

But it was changed in 2021, 6abb7e385f8f2f22511da13fe506a2cbdf7f5584 added re-init when the chapters change, which should re-render the chapter markers.
