### ISSUE TITLE
Request changes to OSC

### ISSUE THREAD

**Issue by azev** [mpv-player/mpv#7971]
Feature request:
1. Put the OSC bars outside the video frame - without overlaying the video.
2. Remove the OSC title since it is useless.
2. Allow customization of OSC controls.

![s20200804114200](https://user-images.githubusercontent.com/6639188/89308242-693fce00-d648-11ea-8293-5de669336f8c.png)

Like this:
![s20200804114222](https://user-images.githubusercontent.com/6639188/89308264-6e9d1880-d648-11ea-8508-37ae6ec1bde7.png)

**Comment by Dudemanguy** [comment]
1. `boxvideo` can do this for you.
2. You can set `title` to be empty if you don't want to see it.
3. Extremely vague. What do you mean?

**Comment by azev** [comment]
All the [options ](https://mpv.io/manual/master/#on-screen-controller-layout) for the osc are not working for me when i put them on `mpv.conf`, including `boxvideo`.

```
mpv 0.32.0-613-gb238897614 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Aug  2 08:33:54 +08 2020
```

**Comment by Dudemanguy** [comment]
The osc is a lua script and you need to configure it like one. Please see the [configuration](https://github.com/mpv-player/mpv/blob/master/DOCS/man/osc.rst#configuration) section in the documentation.

**Comment by azev** [comment]
Thanks! I totally missed that!

`script-opts/osc.conf`
