### ISSUE TITLE
weird osc with no seekbar

### ISSUE THREAD

**Issue by ZerataX** [mpv-player/mpv#7972]
### Important Information

Provide following Information:
- mpv version
  - mpv 0.32.0 
- Linux Distribution and Version
  - system: `"x86_64-linux"`
  - host os: `Linux 5.4.54, NixOS, 20.09pre236721.840c782d507 (Nightingale)`
  - multi-user?: `yes`
  - sandbox: `yes`
  - version: `nix-env (Nix) 2.3.7`
  - channels(root): `"nixos-20.09pre236721.840c782d507"`
  - channels(kaine): `"home-manager-20.03, nixpkgs-unstable-20.09pre236721.840c782d507"`
  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

- Source of the mpv binary
  - nixpkgs stable-20.03 installed via [home-manager](https://github.com/rycee/home-manager)
- If known which version of mpv introduced the problem
I tried a few older versions, but I can't seem to reproduce this by using older versions, so maybe I should rather file this against nixpkgs.
- Window Manager and version
   - xorg (1.20.8)/wayland (1.19): gnome with mutter 3.26.2
   - xorg (1.20.8): plasma with kwin (5.17.5)
- GPU driver and version
  - amdvlk v-2020.Q3.2
- Possible screenshot or video of visual glitches
![Screenshot from 2020-08-04 19-00-38](https://user-images.githubusercontent.com/5024958/89322730-f6087d00-d684-11ea-8055-9f5d72d110e4.png)

### Reproduction steps

I open any video in mpv

### Expected behavior

The usual osc with a seekbar and buttons not weirdly crammed into the sites

### Actual behavior

this seems very similar to #2228 I can even make it look exactly the same by playing around with the `osc.conf`, but with none set and --no-conf this is what it looks like. it seems impossible to recover the default look with `osc.conf` though.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5023471/output.txt)

**Comment by Akemi** [comment]
is this another case of a not supported lua version being used?

**Comment by ZerataX** [comment]
Hmm seems like it's 5.2.4
```console
$ nix-store --query --references $(nix-instantiate '<nixpkgs>' -A mpv) | grep lua
/nix/store/51wpz44l3fwnqplyplyvrqhk17d4llp0-lua-5.2.4-env.drv
```

**Comment by ZerataX** [comment]
Okay the seekbar is back and I am unsure what exactly happened that it works now. I tested multiple different nixpkgs versions, to see what commit introduced this behavior but couldn't really find anything, but I guess if it works now it's fine?
closing this issue for now
