### ISSUE TITLE
inconsistent behaviour for video-add command during on_preloaded hook (audio files only)

### ISSUE THREAD

**Issue by CogentRedTester** [mpv-player/mpv#7979]
### Important Information

Provide following Information:
```
mpv 0.32.0-603-gb5368980a8 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 26 10:11:35 +08 2020
FFmpeg library versions:
   libavutil       56.57.100
   libavcodec      58.97.102
   libavformat     58.49.100
   libswscale      5.8.100
   libavfilter     7.87.100
   libswresample   3.8.100
FFmpeg version: git-2020-07-25-7c8ad72f1
```

Windows 10 Version 2004
OS Build:  19041.388

### Reproduction steps

Play an audio file with album art, either embedded into the file or selected through --external-files, then run `video-add [file] auto` inside of a function called using the `pre_loaded` hook .

I did this using a lua script, and I also ran sub-add and audio-add to see how the behaviour compared. The exact script I used was:

```
mp.add_hook('on_preloaded', 50, function()
    mp.commandv('audio-add', "D:/Danse Macabre.mp3", "auto")
    mp.commandv('video-add', "D:/mpv.png", "auto")
    mp.commandv('video-add', "D:/mpv.png", "auto")
    mp.commandv('sub-add', "D:/Fantastic Children - 01 (R2DVD 768x576 x264 Hi10p AC3 Chap).srt", "auto")
end)
```

I launched mpv with the command: `mpv --no-config --script=scripts/test.lua 'D:\Wagner_ Die Meistersinger von N_rnberg_ Overture.flac' --log-file=log.txt`

### Expected behavior
Since the `on_preloaded` hook runs after the tracks have been loaded, but before being selected, the expected behaviour would be that an extra track is added to the ends of all track lists, and the normal selection rules would apply. With all the default settings intact that would presumably be the first track in the list.

### Actual behavior

![image](https://user-images.githubusercontent.com/57207260/89615338-8cc37c80-d8c5-11ea-8bd7-c4b6d9943d5d.png)

As you can see the audio and subtitle track selection acts as normal, however the video selected is always the first track added during the hook. This does not happen for normal video files or images, just audio files with a cover.

I imagine this is the case on all systems, but I can only test windows.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/5039653/log.txt)

**Comment by wm4** [comment]
The video tracks selection looks normal. The video tracks without "[P]" are preferred over the track 1, which has the "[P]". the "[P]" means that it's an embedded cover art picture. Maybe it'd be useful to detect whether the external video files are pictures too, but due to the way ffmpeg works, we can't easily tell.

**Comment by CogentRedTester** [comment]
It's interesting that the external-file option makes the image count as embedded. Is there some way to make an image added through video-add behave the same way? Or is this only possible while the file is initially being loaded?

**Comment by wm4** [comment]
> It's interesting that the external-file option makes the image count as embedded.

It doesn't. --external-file just doesn't cause its tracks to be selected by default.

**Comment by CogentRedTester** [comment]
You're right, sorry I was misremembering the terminal output. Since this seems to be intentional behaviour I'll close this issue, but it would be nice to have an extra flag for video-add so that it can be treated the same as --external-file, though I understand that might not be possible. In the meantime I'll just work around this manually.

**Comment by CogentRedTester** [comment]
I was going to note that commits 102a4a8b0654396de7a6355adcf2292a277b6595 and 55d7f9ded197d82d172b7baf74b1a07640361ae8 solved this request since video-add now flags images as pictures. But it seems this is a bug because it's happening to all video files I load as well.

When I get the time I'll grab a log and create a full issue request.
