### ISSUE TITLE
bt.2390 needs work

### ISSUE THREAD

**Issue by NSQY** [mpv-player/mpv#7984]
mpv 0.32.0-615-gfb55ee99e3
Arch Linux, compiled via https://aur.archlinux.org/packages/mpv-build-git/
<details>
  <summary>full</summary>

> $ mpv --version
> mpv 0.32.0-615-gfb55ee99e3 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
>  built on UNKNOWN
> FFmpeg library versions:
>    libavutil       56.57.100
>    libavcodec      58.99.100
>    libavformat     58.49.100
>    libswscale      5.8.100
>    libavfilter     7.87.100
>    libswresample   3.8.100
> FFmpeg version: N-98624-g08f60a35b4
</details>

### Reproduction steps
Playback HDR content on a SDR display (HDR displays would be similarly impacted I assume) with --tone-mapping=bt.2390
### Expected behavior
Decent tonemapping
### Actual behavior
Absurd amount of clipping and some noticeable loss of contrast (in comparison to Hable). Some comparisons between hable and bt.2390 with hdr-compute-peak enabled: https://slow.pics/c/uc3Na3fG, most of my media shows a similar story. Brightness overall does seem better than what Hable provides but the current implementation of bt.2390 is far too happy to destroy parts of a scene in this pursuit.

The blindingly bright 'Sol Levante' from Netflix shows some particularly bad overshoot: https://slow.pics/c/d8OJNbEt

**Comment by Doofussy2** [comment]
Is it possible that the peak of your display is below 203 nits, and that lowering the `--target-peak` to 150 or lower would help? Hable is known to slightly darken the image.

**Comment by aufkrawall** [comment]
Did you disable peak detection?

**Comment by ValZapod** [comment]
First of all "difference between this proposal and the black level adjustment per Recommendation ITU-R BT.1886 is the addition of a tapering factor (1 – E_2)^4" is not implemented, right? https://github.com/mpv-player/mpv/commit/c9f6c458ea54f595127684a3bcd94f578ec42b1f

> Note that we ignore the black point adjustment of the tone mapping
> entirely

Second of all there are a crazy amount of traps and a typo in the document of ITU-T. They are obvious to them, but may be not obvious to @haasn. You can look here, they are documented there https://sourceforge.net/p/dispcalgui/code/HEAD/tree/trunk/DisplayCAL/colormath.py#l2920

```
# BT.2390-3 suggests P[E1] if KS <= E1 <=1, but this results in
# division by zero if KS = 1. The correct way is to check for
# KS < E1 <=1
```

```
# BT.2390-3 suggests 0 <= E2 <= 1, but this results in a discontinuity
# if KS < 0 (high LB > Lmin, low Lmax, high LW). To avoid this, check
# for E2 <= 1 instead

```

```
# BT.2390-3 suggests E2 + b * (1 - E2) ** 4, but this clips, if
# minLum > 0.25, due to a 'dip' in the function. The solution is to
# adjust the exponent according to minLum. For minLum <= 0.25
# (< 5.15 cd/m2), this will give the same result as 'pure' BT.2390-3

```

etc

**Comment by laichiaheng** [comment]
bt.2390 kills the highlight details.
![2021-01-03 14-33-01 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/103473180-9dbede00-4dd0-11eb-9348-14058768f3dd.png)
The left hand side is bt.2390, the right hand side is hable.

**Comment by ValZapod** [comment]
It is not fully implemented as of now.

**Comment by ValZapod** [comment]
Hermite spline is implemeneted here by AMD. 

https://patchwork.freedesktop.org/patch/255949/ and fixit https://patchwork.freedesktop.org/patch/396160/

**Comment by laichiaheng** [comment]
@ValZapod Does MPV need to do more work on it? Or it depends on AMD?

**Comment by Doofussy2** [comment]
You can't compare to MadVR, as it has additional brightening. It adjusts the mid tones etc.

**Comment by ValZapod** [comment]
> has additional brightening

And it does not use 2390 anymore.

**Comment by NSQY** [comment]
With #9666, I'm inclined to close this now. Previously there wasn't much of an option but to use bt.2390 or reinhard, but now bt.2446a and spline behave better in the majority of cases.

I don't recommend anyone to use bt.2390 and it boggles the mind as to why it was ever made the default.

**Comment by pillepalle1234** [comment]
I still think bt. 2446a looks weird. While preserving more Details in Highlights it dims the picture and adds a grey fog.
target-prim=dci-p3
hdr-compute-peak=yes
tone-mapping=bt.2446a or bt.2390 or spline (see picture names)
tone-mapping-mode=auto
hwdec=no
gpu-api=vulkan

Some comparison shots from Lucy, Mad Max Fury Road, Dune UHD:
target-peak=auto

Here bt2446a actually looks better (ive thrown in Spline for comparison aswell)
https://ibb.co/5FQrzQh
https://ibb.co/S789n6M
https://ibb.co/WK2PwJk

Here it does not:

https://ibb.co/wd6XdH7
https://ibb.co/BT1xm5f
https://ibb.co/RcwVPtj
https://ibb.co/qx4PF2x
https://ibb.co/94ZRMHx
https://ibb.co/tcGSCrc

Dune:
https://ibb.co/F43hW95
https://ibb.co/LdxRpcy

Here they look identical:
https://ibb.co/s3BqW2G
https://ibb.co/7bBFLfb

Harry Potter (better depth with bt2390)
https://ibb.co/H2Qm3tG
https://ibb.co/F5YsZVW

Shining:
https://ibb.co/xhwMXPq
https://ibb.co/Mnd2MVV

Target peak is somewhat strange with bt.2446a.. While it gets (a little bit) brighter it still looks off...
target-peak= from auto till 10 (!)

https://ibb.co/94ZRMHx
https://ibb.co/7b1JVy0
https://ibb.co/qW67CjZ
https://ibb.co/PTCw8H8
https://ibb.co/470Crk3
https://ibb.co/cTRD96P

Meanwhile bt.2390 target peak auto vs 100:
https://ibb.co/tcGSCrc
https://ibb.co/ng5NBHn

While bt.2390 sometimes crushes details in highlights i prefer it over the dim grey fog of bt.2446a that brings advantages only in some scenes...

Id did not test spline much yet... But on first sight it seems like a good compromise between preserving highlights and overall brightness. At least in some scenes...

**Comment by ValZapod** [comment]
> inclined to close this now

But those only work with gpu-next that does not allow even for HW decoding and was even not decoding YCbCr correctly until 3 days ago, I think we should repoen this. @haasn was black point handling integrated in mpv? I though that it was added in libplacebo, but not in mpv.

**Comment by NSQY** [comment]
Very well, I will re-open this issue. But I stand by what I said earlier.

Regretfully I do not have any actual suggestions as to how exactly clipping could be improved with bt.2390, so ultimately I'm just doing a whole bunch of whinging.

**Comment by haasn** [comment]
I'm not sure what the purpose of this issue is. BT.2390 is implemented as in the spec.

**Comment by ValZapod** [comment]
> BT.2390 is implemented as in the spec.

Black point is all good then? Okay! BTW, Sol Levante JPEG 2000 master uses Display P3 instead of BT.2020 for primaries, just FYI.

**Comment by haasn** [comment]
> I'm not sure what the purpose of this issue is. BT.2390 is implemented as in the spec.

Actually, I just realized this is wrong. You need to set `--tone-mapping=bt.2390 --tone-mapping-param=0.5` to get the exact curve from the spec. We deviate it by defaulting to knee point 1.0.

**Comment by NSQY** [comment]
What games are the ITU playing?
Here is a comparison between BT.2390 using `--vo=gpu` and `--vo=gpu-next`. 203 nits target, tone-mapping-mode=max because hybrid is a bit broken atm #9781 (this is better for comparisons to --vo=gpu anyway I think?)

https://slow.pics/c/uaiSl6dz

**Comment by ValZapod** [comment]
> > I'm not sure what the purpose of this issue is. BT.2390 is implemented as in the spec.
> 
> Actually, I just realized this is wrong. You need to set `--tone-mapping=bt.2390 --tone-mapping-param=0.5` to get the exact curve from the spec. We deviate from it by defaulting to knee point 1.0.

Just nice. Yeah, I forgot that. Indeed you mentioned in the code.

**Comment by ValZapod** [comment]
> What games are the ITU playing?

mind games. That is not even using CRI (color remapping information).

**Comment by damian101** [comment]
> I'm not sure what the purpose of this issue is. BT.2390 is implemented as in the spec.

It is, vo=gpu-next is the issue, it produces inaccurate results with all tone mapping functions (except for bt.2446a probably).

**Comment by NSQY** [comment]
> > I'm not sure what the purpose of this issue is. BT.2390 is implemented as in the spec.
> 
> It is, vo=gpu-next is the issue, it produces inaccurate results with all tone mapping functions (except for bt.2446a probably).

are you going to elaborate? bt.2390 has a different knee between vo=gpu and gpu-next, for instance.

**Comment by damian101** [comment]
> > > I'm not sure what the purpose of this issue is. BT.2390 is implemented as in the spec.
> > 
> > 
> > It is, vo=gpu-next is the issue, it produces inaccurate results with all tone mapping functions (except for bt.2446a probably).
> 
> are you going to elaborate? bt.2390 has a different knee between vo=gpu and gpu-next, for instance.

There is a strong difference even below the knee, in the linear part. vo=gpu-next tonemapping tends to crush blacks, for example. The issue applies to other tonemapping functions as well, like mobius or simple clip. The only tonemapping function that seems to work fine with vo=gpu-next is bt.2446a.

**Comment by kasper93** [comment]
There were significant changes in gpu-next? Can we close this issue?

**Comment by NSQY** [comment]
Sure, tone mapping is better than ever. Thanks for everything @haasn

**Comment by geextahslex** [comment]
Hi @NSQY which tone mapping settings did you end up using?
