### ISSUE TITLE
Very lagging on OSX

### ISSUE THREAD

**Issue by misiekkb** [mpv-player/mpv#7988]
After a dozen or so minutes of playback, lags begin to appear. I have to close the MPV, wait a while and then I can start the player again.

With no-config there is no problem with playing, no lag, I have this same problem all profiles I use.
[Uploading mpv.txt…]()

MPV version a20ae04, from brew. OSX 10.14.6
My config https://drive.google.com/file/d/1aeXEXGn7nbGQTzLhSDNcvWdF6SgY4wd3/view?usp=sharing
Log  https://drive.google.com/file/d/11tz0q_j_hsFoFbpTP8wlYzc_EbNItOSa/view?usp=sharing

**Comment by Akemi** [comment]
if it's not happening with --no-config, find out which option causes the problem for you. that's something we can't do. don't ignore the issue template. that config is a mess, a lot of the options don't make sense, don't have any kind of meaning for macOS, are nonsensical or just might cause problems in that combination.
