### ISSUE TITLE
Photosensitivity filter

### ISSUE THREAD

**Issue by amadeok** [mpv-player/mpv#7990]
Hi,
I'd be interested to know which is the file in the source code responsible for the photosensitivity filter? I'd like to experiment with it

**Comment by CounterPillow** [comment]
If you mean `--vf=photosensitivity`, then that's [a ffmpeg filter](https://ffmpeg.org/ffmpeg-filters.html#photosensitivity), so you'll have to find the source for it e.g. here https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_photosensitivity.c
