### ISSUE TITLE
MPV doesn't appear to post to stdout when run with --idle property, and stdout is PIPE'd

### ISSUE THREAD

**Issue by RichardSeton** [mpv-player/mpv#7992]
### Important Information
pi@KitchenPi:~/code $ mpv --version
mpv 0.29.1 Copyright Â© 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
   ffmpeg version: 4.1.6-1~deb10u1+rpt1

OS: Latest Raspberry PI download- headless version

### Reproduction steps
I am in the process of writing a Python program to control a sound system - streaming audio, playing CD's and acting as a Bluetooth speaker. For streaming / CD, I am using MPV initiated as a subprocess.  The CD player is just a standard ISB DVD drive - many different types available on Amazon.  Everything works so far, except:

One thing that appears to cause MPV a little trouble is attempting to play a CD when there is no CD in the drive. When MPV detects that there is no CD in the drive, it prints a warning onto stdout. The warning doesn't appear through the JSON OPC interface. So, this warning goes to the terminal. But, I want to capture this message so that I can inform my wife that she has forgotten to insert a CD. 

No problem, redirect stdout and stderr to a PIPE, and use communicate() to look for the pertinent string. Except the message never shows up if you run MPV with the --idle option. 

Below is a simple python program to demonstrate the problem. When --idle is not used, I get the stdout. When it is used, I don't. I have tried flushing the buffer, running the subprocess in no buffer mode. 

Any hints? 

Richard

**Sample Code:**

import subprocess

stdout = ""
stderr = ""

proc = subprocess.Popen(["/usr/bin/mpv", "cdda://", "--no-terminal", "--idle"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

while 1:
#    print("exit: {}".format(proc.returncode))
    try:
        stdout, stderr = proc.communicate(timeout=1)
        print("out: '{}'".format(stdout))
        print("err: '{}'".format(stderr))
    except subprocess.TimeoutExpired:
        print("no message")

**Comment by wm4** [comment]
--no-terminal disables all output to stdout or stderr. The JSON interface has a way to enable log messages.

**Comment by RichardSeton** [comment]
Thank you for your response.  But, I have two questions:
i. I figured that --no-terminal is supposed to disable all messages. But, even with it enabled, the "no media loaded' warning still appears on the terminal output. It also appears into a log file if I ship stdout into a file. It doesn't appear when I PIPE --no-terminal is always specified, whichever the three mechanisms I use

2. Re JSON enabling log messages. I get log messages, just not the "No media loaded" message. Is there a granulation for log messages. It appears you just enable it. 

Richard

**Comment by wm4** [comment]
That's not printed by mpv them.

**Comment by RichardSeton** [comment]
OK. That makes sense. Does not MPV have a way to monitor cdda (I don't know how MPV interfaces with the drive) to know it's status?

Richard

**Comment by RichardSeton** [comment]
Also, why would redirecting stdout (using subprocess Popen) to a file get the" no media message", but doing the same thing to PIPE would not?
Richard

**Comment by RichardSeton** [comment]
After some reflection, and some breakfast!
It looks as though MPV doesn't really know when a source has an issue. Streaming data just appears to stop. I noticed similar behavior when a streaming web service goes down. MPV does stop. But, when using the --idle parameter, it doesn't do. 
The issue for redirecting stdout in as described above would be a subprocess issue, not a MPV issue? So, I'll look for some assistance there. 

Richard
