### ISSUE TITLE
Can I change the subtitle style with the --vf=subtitles command

### ISSUE THREAD

**Issue by 9838464** [mpv-player/mpv#7993]
### Important Information

Provide following Information:
-mpv version
0.32.0-589-g96cdf5315e
-Windows Version
Windows 10 LTSC
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

### Expected behavior

![image](https://user-images.githubusercontent.com/69559970/89968779-5734df80-dc87-11ea-85ff-6f3e8ca8d49c.png)

### Actual behavior

It can't really come out

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5060323/output.txt)

**Comment by 9838464** [comment]
同样地命令在ffmpeg能生效却在mpv出现了错误，或者是我地命令格式有问题？

**Comment by 9838464** [comment]
It can only load the subtitles but can't change the subtitle's style.It will give a false alarm when I try to use force_style.

**Comment by thebombzen** [comment]
You can use --sub-file instead of --vf=subtitles to add external subtitle tracks. Is there a reason you need to use --vf=subtitles?
