### ISSUE TITLE
A way to disable save-position-on-quit for current file

### ISSUE THREAD

**Issue by CreamyCookie** [mpv-player/mpv#7999]
I have a plugin that loops short videos, but this means the file will never end and thus the watch_later file will never be removed. 

### Expected behavior of the wanted feature
A way to disable `save-position-on-quit` just for the current file (via plugins etc.)

**Comment by po5** [comment]
Sounds like something that would be trivial to implement in your script, or get rid of it entirely because this can all be done with auto profiles (setting `loop` and `save-position-on-quit=no`).

**Comment by CogentRedTester** [comment]
You can use the following command in a script/plugin, or simply set it to a keybind in input.conf:

`set file-local-options/save-position-on-quit no`

Option changes written to file-local-options/ are reset once the file is ended.

**Comment by CreamyCookie** [comment]
Very cool. Thanks a lot @CogentRedTester
