### ISSUE TITLE
an option to open the last played video

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#8001]
### Expected behavior of the wanted feature
The video path is presumably only saved alongside [the playback position](https://mpv.io/manual/master/#options-save-position-on-quit) -- a hotkey and a configuration setting to open the last played video (disable/enable by default) would complement existing mpv functionality.
### Alternative behavior of the wanted feature
N/A

**Comment by Argon-** [comment]
It probably depends on which demographic you target. If your main user is launching mpv from a terminal/command line, then this is an unnecessary feature because your shell already provides this. 
Naturally, this doesn't help pseudo-gui users (using double click/open with). Is this in scope for mpv though? Or is this a task better suited to a mpv front end?

**Comment by wm4** [comment]
A script could do this by listing the watch later directory, sorting it by date, and using that option that writes the full path into the watch later config file.

**Comment by Eisa01** [comment]
Perhaps this helps?
Wrote a script that has last video feature.
After adding the script press ctrl + l to launch last video
[https://github.com/Eisa01/mpv-scripts#smarthistory-script-152](https://github.com/Eisa01/mpv-scripts#smarthistory-script-152)

**Comment by smhmd** [comment]
As @Argon- said, it depends on your set up. Terminal users get by by using shell history. If you're using Windows, I remember that right clicking programs on the bar or start menu gives a list of recently opened files using that program.
<details><summary>Yep:</summary>
<p>

![image](https://user-images.githubusercontent.com/46059092/90349111-0b3bbf00-e028-11ea-9422-4dc2a4cce55d.png)

![image](https://user-images.githubusercontent.com/46059092/90349119-1393fa00-e028-11ea-85dc-1216990a75da.png)

</p>
</details>

**Comment by 07416** [comment]
I'm closing this issue after realizing the feature seems to be out of scope.
