### ISSUE TITLE
tct and caca rendering glitches in the terminal on *any* terminal emulator

### ISSUE THREAD

**Issue by christianparpart** [mpv-player/mpv#8004]
### Important Information

Provide following Information:
- mpv version: 0.32.0
- Platform and Version: Ubuntu 20.04
- Source of the mpv binary: ubuntu package
- terminal emulators tested: at least (!): xterm, konsole, gnome-terminal, kitty, alacritty, contour.

### Reproduction steps

```
mpv --vo=tct path/to/some.avi
```
I tried AVI as well as WEBM and I tried `tct`  as well as `caca` video output, whereas for `caca` output I made sure that `DISPLAY` env var is unset.

### Expected behavior

Video being played without leaking VT esscape sequences.

### Actual behavior

Video being played WITH leaking VT escape sequences.

It looks like there are some bytes missing in the (stdout) output stream, such as `\033` (ESC) or even `\033[` (ESC CSI) sothat only the remainder is being printed as text instead of being interpreted as VT sequence (actually SGRs).

### Sample files

I literally just googled for some demo webm file from the internet:

https://commons.wikimedia.org/wiki/File:Spring_-_Blender_Open_Movie.webm

as well as for the avi file i the one from the chromium source code repository at

    `chromium/content/test/data/media/bear_mpeg4asp_mp3.avi`.

**Comment by emanuele6** [comment]
If with "rendering glitches" you mean error messages and timestamps, you can just use the `--no-terminal` option to get rid of them:

    DISPLAY= mpv --no-terminal --vo=tct path/to/some.avi

**Comment by christianparpart** [comment]
Actually, no. I meant leaking VT escape sequences that are printed as text instead of being interpreted by the terminal emulator, because it looks like some leading bytes are missing in some SGR VT sequences

**Comment by avih** [comment]
> Actually, no. I meant leaking VT escape sequences that are printed as text instead of being interpreted by the terminal emulator, because it looks like some leading bytes are missing in some SGR VT sequences

This is highly unlikely to be an issue of incomplete or incorrect escape sequences. What's more likely is that there's more output other than just the TCT output, and when these different outputs interleave then some escape sequences can get broken.

These are the used escape sequences, and they're always printed atomically by the TCT vo (i.e. the TCT code itself never interleaves it with anything else) - https://github.com/mpv-player/mpv/blob/master/video/out/vo_tct.c#L40

Try using the `--really-quiet` option which should disable all other output from mpv itself, i.e. the whole output from mpv should be only from the TCT code.

If that's not enough, then we will need some more info, like screenshot, or some capture of the broken sequence, etc to be able to analyze it further.

**Comment by avih** [comment]
Also,missing from your description of the issue (other than the obvious mpv log) is which terminals you tried, and how frequent it happens (once an hour? once a second? every frame? etc).

**Comment by avih** [comment]
Another possible reason is that something outside of mpv is not able to process the TCT output quickly enough - and occasionally simply discards part of the output from mpv. TCT can be very demanding and take the terminal (and possibly, though less likely in general - pty) processing speed to its limits.

So your system details and spec can also shed light.

**Comment by christianparpart** [comment]
Actually, I said "all" terminal emulators (I have tested) break, and the list of TEs tested is in the top message. :-)

Here's a screenshot:

![image](https://user-images.githubusercontent.com/56763/90329349-5f04c480-dfa4-11ea-8f0b-7bf334ef7d1f.png)

I don't think logs would have helped here, that's why I didn't attach them, because of the nature of the problem I have analyzed so far (also, it was quite late for me last night already, if you still need them, I can still provide them :).

I've tested mpv with `--really-quiet` now, I didn't know about that option until now, thanks for that, and it is working around this issue.

I am not sure how the additional info line at the bottom is rendered without looking at the source. Do you use multiple threads? One for (tct) video-output and one for the stats output at the bottom? If so, then there's maybe a conflicting issue in what writes when to the terminal's stdout. I can imagine that the other entities are writing to stdout while (tct) video-output is currently being written, to, too. (remind: it also happened with `caca` video output driver).

Have a nice Sunday,
Christian.

**Comment by christianparpart** [comment]
![image](https://user-images.githubusercontent.com/56763/90329429-20bbd500-dfa5-11ea-9690-dbcd3614e55a.png)
here you see another one leaking the tail of an SGR CSI sequence.

![image](https://user-images.githubusercontent.com/56763/90329461-624c8000-dfa5-11ea-8d17-688993840d31.png)

this one is from another video with a leaking SGR CSI seq and following wrongly rendered line.

**Comment by christianparpart** [comment]
with regards to frequency, it's more like almost every second, sometimes more, sometimes less. You sometimes see severe image displacements which are auto-fixed quickly due to the next frame being rendered on top of it, but on the right/left hand side of the video frame these artifacts are remaining.

**Comment by avih** [comment]
These are mpv playback messages interleaved with the TCT output.

You clearly didn't try the suggested solutions of `--no-terminal` and/or `--really-quiet`, because one or both of them would have solved it.

**Comment by christianparpart** [comment]
Oh. I don't think this problem is actually fixed. I was telling you that I did try `--really-quiet` and that this does not show this behavior. That leads IMHO to the conclusion that th bug is triggered when txt/caca is being rendered along with additional output (hence °no° `--really-quiet`). 

I can reproduce the rendering glitches on all (above mentioned) TEs.

Neither PTY on the kernel side nor the terminal emulators are skipping bytes just because they are under high input load. So that is why I was filing the ticket here, I don't think it can be caused from anywhere else .

Why are you closing this ticket?

**Comment by avih** [comment]
It's a known behavior.

The TCT output uses plain `printf` and does not go through the standard unified mpv terminal output (which also decides what gets into the log file etc).

This is both for performance reasons and also because the unified terminal output probably wouldn't handle it well - it adds a prefix to each line, might process the content, etc.

Anyway, I've added a note about it at the TCT documentation.

**Comment by christianparpart** [comment]
Thanks for the clarification. This problem also happens when using `caca` video output driver.

One way to fix that would be to define a strict order, e.g. only write log output after having completed a video frame render, for example via a callback. Only one thread should write to the terminal. That way, no output will be broken.

**Comment by avih** [comment]
> One way to fix that would be ...

Yes, it's not an impossible problem to solve, though probably requires more than just timing synchronization, e.g. whether the playback messages overwrite the image or appear below it, new image size calculations, etc.

No one cared enough about it to do that, especially when there are options which can make the problem go away.

TCT and caca are considered toys/for-fun by mpv developers. You really should not use them "for production".

**Comment by avih** [comment]
> Why are you closing this ticket?

Because of this:

> If, with "rendering glitches", you mean error messages and timestamps being printed over the video, you can just use the `--no-terminal` option to get rid of them

> Actually, no.

The cause and behavior was described exactly, as well as a working solution, and yet you didn't try it, or tried it but never mentioned it, and kept wasting people's time by replying as if the suggestion was irrelevant, while in fact it was 100% relevant.

**Comment by christianparpart** [comment]
I am very sure I was trying out your suggestions and did say so in the next reply in this thread:

    https://github.com/mpv-player/mpv/issues/8004#issuecomment-674493212

and did also say that this works around the buggy behavior of using code-path A (log output) along with codepath B (tct/caca) because it's not A is disabled. Of course it's not running into that issue then. I was and I am still trying to be really polite, despite the fact that I was already in a multi-hour-long debugging session before I even considered creating a ticket here, because I first assumed buggy terminal emulators. I think this is absolutely not a waste of time to get things clarified. If you feel this is a waste of time, I apologize for that, but please be reasonable in the statements and claims you make, and don't think people are writing here without respect in mind and actively ignore what feedback they are getting. Please keep that in mind. If you still think that is a waste of time, I again deeply apologize.

**Comment by avih** [comment]
> I am very sure I was trying out your suggestions

I did not quote my suggestion. I quoted the first reply you got by @emanuele6 , and to which your "Actually, no" replied referred - before I made another suggestion.
