### ISSUE TITLE
Add subtitles directory

### ISSUE THREAD

**Issue by smhmd** [mpv-player/mpv#8012]
### Expected behavior of the wanted feature
If you have a file `~/video.mkv` and a subtitles file in `/tmp/video.srt`, a flag to invoke mpv to add `/tmp` to the directories mpv looks for subtitles would be great. something like `$ mpv --sub-dir=/tmp ~/video.mkv`

If you're playing multiple files, they'll all look for subs in that directory using their own filenames.
`$ mpv --sub-dir=/tmp ~/video1.mkv ~/video2.mkv` (loads `/tmp/video1.srt` and `/tmp/video2.srt` for the two files respectively.)

### Alternative behavior of the wanted feature
Doing `$ mpv --sub-file=/tmp/video.srt ~/video.mkv`. I don't know how to work around the second use case.

**Comment by Akemi** [comment]
https://mpv.io/manual/master/#options-sub-file-paths

--sub-file-paths=

**Comment by ewtoombs** [comment]
I also had to add `--sub-auto=all` to get it to work as I had expected.
