### ISSUE TITLE
wayland: fullscreen is broken for list of videos/images with different sizes

### ISSUE THREAD

**Issue by bitraid** [mpv-player/mpv#8014]
### Important Information

- mpv version
```
mpv 0.32.0-650-g0216f8c787 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Aug 18 10:22:01 EEST 2020
FFmpeg library versions:
   libavutil       56.58.100
   libavcodec      58.100.100
   libavformat     58.51.100
   libswscale      5.8.100
   libavfilter     7.87.100
   libswresample   3.8.100
FFmpeg version: N-98749-gab384d289d
```
- Linux Distribution and Version
`ArchLinux 5.8.1`
- Source of the mpv binary
`Local compile`
- If known which version of mpv introduced the problem
6573e0a0af1a7ece043b9d94f6a844cfff6b74d3
- Window Manager and version
`sway version 1.5-6991ac8c (Aug 14 2020, branch 'master')`
- GPU driver and version
`OpenGL 4.6, Mesa 20.1.5 (Intel HD Graphics 620)`
- Possible screenshot or video of visual glitches
![20200818_11h21m17s_grim](https://user-images.githubusercontent.com/4866740/90488943-50a1de80-e145-11ea-9a39-3c329b372744.png)
(playlist image in full screen display)

### Reproduction steps

- mpv must be a floating window - add to sway `config`:
`for_window [app_id="mpv"] floating enable`
- Play a list of videos/images with different sizes. For example, playing the different wallpaper sizes of sway:
`$mpv /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_* --no-config --fullscreen --image-display-duration=inf`
- The first image is displayed ok, but cycling through the rest: The new image is not stretched if it's smaller than screen size, and not shrink if larger. Swithing to another workspace and back fixes the display.

### Expected behavior
The video/image should stretch/shrink to fit, when on fullscreen.

### Actual behavior
When running as a wayland folating window in fullscreen mode, the video/image of a list always has it's original size, if the size differs from the size of video/image that entered fullscreen.

It seems to be fixed with:
```diff
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index 94261455af..2391129b71 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -1350,7 +1350,7 @@ int vo_wayland_reconfig(struct vo *vo)
     vo_calc_window_geometry(vo, &screenrc, &geo);
     vo_apply_window_geometry(vo, &geo);
 
-    if (!wl->configured || !wl->vo_opts->window_maximized) {
+    if (!wl->configured || !(wl->vo_opts->window_maximized || wl->vo_opts->fullscreen)) {
         wl->geometry.x0 = 0;
         wl->geometry.y0 = 0;
         wl->geometry.x1 = vo->dwidth  / wl->scaling;
```
Although, when leaving fullscreen, the window has the size of the video/image that first entered fullscreen.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5089571/mpv.log)

### Sample files

Any list of videos/images with different sizes can be used.

**Comment by bitraid** [comment]
@Dudemanguy With that change, it's impossible to exit full screen, if started with `--fullscreen`.

**Comment by Dudemanguy** [comment]
Really sorry about breaking a bunch of crap lately.

**Comment by aufkrawall** [comment]
@Dudemanguy Not sure if this is related to recent changes at all, but have you noticed temporary mpv window content being cut or clinched close the the bottom on Sway when seeking? I don't think this has always been the case. It's just a minor cosmetic thing though.

**Comment by Dudemanguy** [comment]
Can't say I see anything like that.

**Comment by aufkrawall** [comment]
Turns out it happens on Xorg as well. I suspect a regression in Mesa VAAPI driver, as I don't see it without hwdec and just today I've switched from stable to mesa git-master. Nevermind. :)
