### ISSUE TITLE
Why there is no menu option?

### ISSUE THREAD

**Issue by suiahae** [mpv-player/mpv#8017]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

### My question

Why are there no menu options? Although mpv has rich shortcut key support, they are difficult to remember, especially when they are not used frequently. I don't think it is a good decision to cancel the visual menu and rely on pure shortcut keys to manipulate it.

If it is really inconvenient to add a visual menu, you can set "a dedicated shortcut key to show all available shortcut keys" as an alternative.

Best wishes to mpv :)

**Comment by wm4** [comment]
Someone will have to implement it. I consider a menu a good compromise between the current state and a full fledged GUI, so it might eventually happen.
