### ISSUE TITLE
(mpv,mac) change ao to mbox2 pro device (firewire)

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#8019]
Hello,

i have noticed that on OS X Mavericks i cannot playback through mpv videos whenever i would choose as sound output in system settings the "Mbox2 Pro" instead of "Internal Speakers".

Whenever i would do so, playback of the video would stall at 00:00.

When i change Audio playback in System Settings back to internal Audio Speakers, the mpv playback would correctly function and in terminal it would show

`(+) Video --vid=1 (*) (h264 360x480 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
AO: [coreaudio] 44100Hz stereo 2ch floatp
VO: [gpu] 360x480 yuv420p`

My question is how can i change AO setting in mpv.conf i presume to match the desired outcome , eg. playback through the Mbox2 Pro device instead of Internal Speakers?

thank you very much.

**Comment by mrkapqa** [comment]
mpv is configured to playback video through X11 (XQuartz) and built via macports
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Wed Aug  5 18:15:33 CEST 2020
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.4

**Comment by Akemi** [comment]
we don't really support macOS 10.9, neither do we support xquartz output on macOS. also without the necessary information from the issue template we can't even start helping.

**Comment by mrkapqa** [comment]
thank you, it seems an error on my side (driver issue).
