### ISSUE TITLE
Video playback position keeps progressing in background when started with --pause

### ISSUE THREAD

**Issue by fartsniffer104** [mpv-player/mpv#8026]
### Important Information
mpv 0.32.0-668-g74e62ed2d1
Linux 5.7.16-200.fc32.x86_64

### Reproduction steps
mpv --no-config --pause video.mp4
Wait 30 seconds or so
Unpause the video

### Expected behavior
When unpausing the video starts from the beginning of the file.

### Actual behavior
Video appears to be paused but when unpausing the video will skip 30 seconds (or however long you were paused for) into the video.

git bisect first bad commit: https://github.com/mpv-player/mpv/commit/7a7a0a78b518180bfb48a42e23acac6c801ed5cf

**Comment by mia-0** [comment]
Confirmed to happen only with PulseAudio, and only when player is started in paused state without performing HR seeks before playback. Thanks for bisecting.
