### ISSUE TITLE
Stop MPV resizing on each new file

### ISSUE THREAD

**Issue by aeseok** [mpv-player/mpv#8028]
### Important Information

Provide following Information:
- mpv version
Latest
- Windows Version
Windows 10 pro?

### Expected behavior

Attempting to play audio files with album covers that have varying dimensions, expecting for mpv to keep it's window size the same when playing new files with (larger/smaller) album covers.

### Actual behavior

Resizes itself on each new file, instead of keeping it's original size.

Not really an issue, I just need some help in trying to figure out which settings i need to change in the .conf

**Comment by TheAMM** [comment]
https://gist.github.com/TheAMM/5e07ad787dd95d76131b61840f403a79
