### ISSUE TITLE
Keyboard shortcut to toggle --shuffle

### ISSUE THREAD

**Issue by SirCmpwn** [mpv-player/mpv#803]
Bonus points if I can bind it with lirc

**Comment by wm4** [comment]
Seems like there's no actual interest in this, so I don't see any reason to bother either.

**Comment by mikkelsenQ** [comment]
Would it be possible to implement the 'shuffling' without trying to return the list to its original order? I think it would be great to be able to randomize a playlist, even if the original order is lost.
