### ISSUE TITLE
[IDEA] chrlauncher-like updater

### ISSUE THREAD

**Issue by forart** [mpv-player/mpv#8032]
1st of all let me tell that mpv is one of the best video player on the scene.

BTW its commandline .bat updater tastes a bit outdated and quite "hidden" (for common users) too, so I believe that would be great to have something like chrlauncher (the _Small and very fast portable launcher and updater for Chromium_) if you don't won't integrate this feature inside the software:

https://github.com/henrypp/chrlauncher

Hope that inspires !

**Comment by Akemi** [comment]
we don't provide a command line updater as a .bat file. it comes from a third party that provides the binary and you should address your wish to them. since we don't provide any binaries we won't provide an updated either.
