### ISSUE TITLE
Various issues with JSON IPC event notification

### ISSUE THREAD

**Issue by PCigales** [mpv-player/mpv#8033]
### Important Information
Provide following Information:
- mpv version: mpv 0.32.0-666-gb0f0be7678
- Windows Version: 10
- Source of the mpv binary: shinchiro
- If known which version of mpv introduced the problem

### Reproduction steps
1. Run mpv with "mpv.exe  --input-ipc-server=\\.\pipe\mpv --keep-open"
2. In Python, open the named pipe with "f=open(r'\\.\pipe\mpv2','w+b',0)"
3. Drag and drop any video to the mpv window
4. In the mpv window, click on pause
5. In Python, enter "f.seek(0,2)" to check that something has been received from the pipe (to avoid blocking IO read operation as selector mechanism is not authorized with files on Windows), and you will get "243"
6. In Python, enter "f.readline()" seven times to read these events
7. In Python, enter "f.readline()", and you will get "{"event":"pause"}'
8. In Python, enter "f.readline()", and you will get "{"event":"pause"}'
9. In the mpv window, click on play
10. In Python, enter "f.readline()", and you will get "{"event":"unpause"}'
11. In Python, enter "f.readline()", and you will get "{"event":"unpause"}'
12. Close the mpv window
13. In Python, enter "f.readline()" four times to read these events and you will end getting "" as EOF has been reached and the pipe is closed at mpv side

### Expected behavior
"pause" and "unpause" events should be sent only one
when mpv is closed, it should send a "shutdown" event before closing the pipe

### Actual behavior
"pause" and "unpause" events are sent twice
when mpv is closed, no "shutdown" event is sent

By the way, I cannot find a property that would return the current status of the player such as UPnP "TransportState" ( STOPPED, PLAYING, TRANSITIONING, PAUSED_PLAYBACK, NO_MEDIA_PRESENT...), am I missing something, please ?

Thanks in advance.

**Comment by wm4** [comment]
The pause/unpause events are legacy. In the libmpv API they're marked as deprecated. Since the IPC enables these events by default, it's hard/impossible to signal to the IPC user that they're deprecated.

You should use ``observe_property`` on the ``pause`` property instead.

There is no "canonical" playback state. You can derive one from the existing properties according to your preferences.

Yes, the IPC just closes the connection, instead of sending a shutdown event.

**Comment by PCigales** [comment]
Thank you for your answer and your suggestions.

**Comment by Akemi** [comment]
seems like the problem has beens solved.
