### ISSUE TITLE
Is there a built-in way or hotkey to stop at the end of a current track in a playlist?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#8039]
I do frequently use this feature when its available in a player. Selecting individual tracks prior to starting playback isn't viable for me, choosing to stop on demand (but not mid-song) is.

**Comment by thebombzen** [comment]
Are you looking for `--keep-open=always`? This will cause playback to pause whenever the current file is completed, even if it's not the final entry in the current playlist.

**Comment by garoto** [comment]
After re-reading the issue title some 10x, my guess is he is looking for a way to not auto-advance the playlist, and wait for user input?

**Comment by thebombzen** [comment]
If you're looking for a key to do something like "stop after the end of this track" you could always use a hotkey to cycle the value of `keep-open`, so pushing it will enable `keep-open=always`. Which is the option to cause the player to pause at the end of every file.

**Comment by 07416** [comment]
@garoto This is an example playlist. `x` marks my position:

```
    1. Closer - 5:55
    2. Ida Lupino - 7:35
    3. Started (Paul Bley) - 5:21
    4. Open, to Love - 7:14 x
    5. Harlem  - 3:26
    6. Seven - 7:25
    7. Nothing Ever Was, Anyway - 6:02 
```

In this example, I want to stop after the currently playing song, "Open, to Love". I may resume playback later from "Harlem". The playlist should remain active.

**Comment by 07416** [comment]
> If you're looking for a key to do something like "stop after the end of this track" you could always use a hotkey to cycle the value of `keep-open`, so pushing it will enable `keep-open=always`. Which is the option to cause the player to pause at the end of every file.

I understand. Could you quickly show to to bind the command to a key so I can close this issue after verifying?

**Comment by thebombzen** [comment]
Just edit `input.conf` with the desired behavior. So if you want to use the key `F`, you'd add: F cycle-values keep-open no always` to input.conf.

**Comment by 07416** [comment]
> Just edit `input.conf` with the desired behavior. So if you want to use the key `F`, you'd add: `F cycle-values keep-open no always` to input.conf.

@Traneptora Is it possible to always advance to the next track (pausing at 0:00)? As `cycle-values keep-open no always` pauses right at the end of the current song, when presuming normal playback I have to remember to first press the mapped key, followed by play. Since the network streams aren't pre-cached there's also some unwanted delay with those.

```
[file] This is a directory - adding to playlist.

Playing: ~/Music/1957 - Patsy Cline - Patsy Cline (2018 WEB release)/01 - That Wonderful Someone.flac
     Video --vid=1 [P] (png 800x800 1.000fps)
 (+) Audio --aid=1 (flac 2ch 44100Hz)
AO: [pipewire] 44100Hz stereo 2ch s16

(Paused) A: 00:02:30 / 00:02:30 (100%) Cache: 0.0s
```

**Comment by guidocella** [comment]
`set pause yes; set file-local-options/pause no; set reset-on-next-file pause`

**Comment by Hrxn** [comment]
What do you mean?
Why don't you use `Enter`, which is simply `playlist-next` by default?

**Comment by 07416** [comment]
@Hrxn  > What do you mean? Why don't you use `Enter`, which is simply `playlist-next` by default?

I occasionally want mpv to stop playback *after* the currently playing track — when taking a break from listening a lengthy album. Works fine outside of albums with seamless transitions (e.g. Sgt. Pepper's Lonely Hearts Club Band, Dark Side of the Moon). I prefer never manually stopping mid-track.

The Enter key doesn't clear the "paused" state (see the first given suggestion below), the playback stops again after the following track has finished:

    TAB cycle-values keep-open no always

---

>     set pause yes; set file-local-options/pause no; set reset-on-next-file pause

@guidocella  Sadly doesn't clear the "paused" state, when resuming playback all songs appear to be paused at the end.

---

Hopefully this example makes the request clear enough. At this point (00:00:17) I decide to stop the playlist (i.e. album) playback after the current song has finished playing:

```
Playing: ~/Music/1957 - Patsy Cline - Patsy Cline (2018 WEB)/04 - Too Many Secrets.flac
 (+) Audio --aid=1 (flac 2ch 44100Hz)
A: 00:00:17 / 00:02:17 (13%)
```

mpv advances to the subsequent  song:

```
Playing: ~/Music/1957 - Patsy Cline - Patsy Cline (2018 WEB)/05 - Don't Ever Leave Me Again.flac
 (+) Audio --aid=1 (flac 2ch 44100Hz)
(Paused) A: 00:00:00 / 00:02:27 (0%)
```

From this point onward, after pressing play mpv should follow the default playback behavior. Only when using the specified hotkey should ever mpv pause in the middle of a playlist.

Seems challenging to explain; the guidocella's method in any case functions near-perfectly, I just have to remember to press the specified key (Tab in the example), followed by 'play' (Space), when resuming playback:

    TAB cycle-values keep-open no always

**Comment by 07416** [comment]
Sorry for any frustration — at my workplace we use the custom feature daily. I may not reply anymore, unless I find out  flawless a solution.

**Comment by guidocella** [comment]
If you only want to pause the next song you only need `set pause yes; set file-local-options/pause no`. To not save the pause state, set `watch-later-options-remove=pause`.

**Comment by Hrxn** [comment]
@guidocella 
What's the effective difference then between `set reset-on-next-file pause` and `set watch-later-options-remove=pause`?

Also, with `TAB cycle-values keep-open no always`, there's still `keep-open` set to `always`, is this intentional in this case?

**Comment by guidocella** [comment]
I thought that with "resuming playback" he was referring to playing a playlist after `quit-watch-later`, but that doesn't seem to be case, so he doesn't need to change `watch-later-options`. `reset-on-next-file` and `watch-later-options` are completely unrelated. I don't understand why he still tries to change `keep-open`.

**Comment by Hrxn** [comment]
`keep-open` is for stopping playback not immediately like `pause`, but at the end of the currently active file.

**Comment by 07416** [comment]
> I thought that with "resuming playback" he was referring to playing a playlist after `quit-watch-later`, but that doesn't seem to be case

The question is related to the active instance and active playlist only. This question is not about quitting mpv in any way.

See the [Quodlibet's](https://github.com/quodlibet/quodlibet) 'stop after this song' feature ([code search](https://github.com/search?q=repo%3Aquodlibet%2Fquodlibet%20%22Stop%20After%20This%20Song%22&type=code)) for reference. May require installing the program, if not familiar.

Henceforth the question may as well be:

**How to create a keybind (for mpv) which functions identically to the Quodlibet's 'stop after this song' feature?**

**Comment by guidocella** [comment]
Does `set pause yes; set file-local-options/pause no` not do that?

**Comment by 07416** [comment]
>Does `set pause yes; set file-local-options/pause no` not do that?

It does, the question has been perfectly answered. Now there's no toggled state anymore, mpv pauses *once* when current track ends.

to `input.conf` :

    TAB set pause yes; set file-local-options/pause no
