### ISSUE TITLE
Option to keep video settings on next file?

### ISSUE THREAD

**Issue by spacelantern** [mpv-player/mpv#8041]
Is there a code to keep the video saturation, contrast settings for the next movie? At the moment for each film I have to set these up from scratch. Thanks.

**Comment by thebombzen** [comment]
This is default behavior - keep settings between playlist files, even if changed by the user. You do need the files to be part of the same playlist though, either by invoking mpv using both of them, or enqueuing one while the other is playing. If you just exit mpv and start the next file then mpv will have no idea you want to keep the same settings. And if you want the settings to be global then you can edit mpv.conf.

**Comment by spacelantern** [comment]
Aha, makes sense...At present I have individual files in my movie folder and open them separately. How would I create the playlist? Thanks.

**Comment by thebombzen** [comment]
There's a few ways but the simplest way is to just open the folder itself with mpv, which will read the contents and treat them as a playlist

**Comment by spacelantern** [comment]
Thank you very much! I assume I would have to keep the app open in the background when I'm not watching, to keep the settings within the playlist?

**Comment by thebombzen** [comment]
Yes, closing mpv will cause it to use default settings on next launch. You can also just edit `mpv.conf` to make those color adjustments the default. The docs are pretty good at describing how to do that.
