### ISSUE TITLE
How to use Youtube's automatically generated subtitles?

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#8042]
I looked through both mpv's guide and youtube-dl's guide, youtube-dl can download the auto-generated subtitles with ``--write-auto-sub``, but I see no way to display them in mpv when opening Youtube URLs in mpv. Is there a way to do this without downloading the whole video first?

**Comment by thebombzen** [comment]
You can use `--ytdl-raw-options=write-auto-sub=` on the mpv command line. Don't forget the trailing `=` - it's important.

**Comment by naveenjohnsonv** [comment]
Thanks, I was looking for exactly this! Can we specify the subtitle language too?

**Comment by UserNaem** [comment]
Thanks, this works wondrous
@naveenjohnsonv ``ytdl-raw-options=write-auto-sub=,sub-lang=en``

**Comment by naveenjohnsonv** [comment]
Just noticed that somehow this command also writes over any given subtitles in the video, and only the auto generated subtitles is available in mpv. Any way to keep those too?

> Thanks, this works wondrous
> @naveenjohnsonv `ytdl-raw-options=write-auto-sub=,sub-lang=en`
