### ISSUE TITLE
cleanup current issues and properly label them

### ISSUE THREAD

**Issue by Akemi** [mpv-player/mpv#8044]
when i cleaned up the issue tracker, added various new labels, cleaned up all labels, properly labeled and sorted out all opened issue, etc, i hoped we could properly label all newly opened issues, so we won't get in the same kind of mess we had previously. that didn't quite work completely since there are quite a bunch of issues (~120) that only have the default issue template labels or no labels at all.

since there are some people eager to work on the issue tracker and do manual work, i have a list of issues that need to be looked at:
[issues with no label](https://github.com/mpv-player/mpv/issues?q=is%3Aissue+is%3Aopen+no%3Alabel) (13)
[issues with only default labels](https://github.com/mpv-player/mpv/issues?q=is%3Aissue+is%3Aopen+-label%3Aos%3Awin+-label%3Aao%3Aalsa+-label%3Aao%3Acoreaudio+-label%3Aos%3Amac+-label%3Aao%3Ajack+-label%3Aao+-label%3Avo%3Agpu%3Ad3d11+-label%3Acore%3Aosd+-label%3Aao%3Aopenal+-label%3Aao%3Apulse+-label%3Aao%3Awasapi+-label%3Acore%3Aapi+-label%3Acore%3Aaudio+-label%3Acore%3Acdda+-label%3Acore%3Acolor-management+-label%3Acore%3Advd-bluray+-label%3Acore%3Aedl+-label%3Acore%3Aencoding+-label%3Acore%3Afile+-label%3Acore%3Alibmpv+-label%3Acore%3Amkv+-label%3Acore%3Aoption-param-conf+-label%3Acore%3Artsp+-label%3Acore%3Astream+-label%3Acore%3Asubtitle+-label%3Acore%3Aterminal+-label%3Acore%3Atools+-label%3Acore%3Avapoursynth+-label%3Acore%3Avideo+-label%3Acore+-label%3Afilter%3Avaapi+-label%3Afilter%3Avdpau+-label%3Afilter+-label%3Ahwdec%3Acuda+-label%3Ahwdec%3Ad3d11va+-label%3Ahwdec%3Adxva+-label%3Ahwdec%3Amediacodec+-label%3Ahwdec%3Ammal+-label%3Ahwdec%3Anvdec+-label%3Ahwdec%3Avaapi+-label%3Ahwdec%3Avdpau+-label%3Ahwdec%3Avideotoolbox+-label%3Ahwdec+-label%3Ainvalid+-label%3Ameta%3Adeveloper-needed+-label%3Ameta%3Aduplicate+-label%3Ameta%3Ahelp-wanted+-label%3Ameta%3Ainfo-needed+-label%3Ameta%3Anext-release+-label%3Ameta%3Ano-bug+-label%3Ameta%3Arfc+-label%3Ameta%3Aspacebar-heating+-label%3Aos%3Aandroid+-label%3Aos%3Aios+-label%3Aplatform%3Arpi+-label%3Apriority%3Acritical+-label%3Apriority%3Ahigh+-label%3Apriority%3Aignored-issue-template+-label%3Apriority%3Ainvalid%3Abroken+-label%3Apriority%3Ainvalid+-label%3Apriority%3Alow+-label%3Apriority%3Aon-ice+-label%3Apriority%3Astalled+-label%3Apriority%3Awontfix+-label%3Ascripting%3Aautoload+-label%3Ascripting%3Alua+-label%3Ascripting%3Aosc+-label%3Ascripting%3Aosd+-label%3Ascripting%3Astats+-label%3Ascripting%3Aytdl-hook+-label%3Ascripting+-label%3Aupstream%3Aapple+-label%3Aupstream%3Affmpeg+-label%3Aupstream%3Agnome+-label%3Aupstream%3Aintel+-label%3Aupstream%3Alibass+-label%3Aupstream%3Alibav+-label%3Aupstream%3Alibplacebo+-label%3Aupstream%3Amesa+-label%3Aupstream%3Aplasma+-label%3Aupstream%3Awaf+-label%3Aupstream%3Awayland+-label%3Aupstream+-label%3Avo%3Ad3d11+-label%3Avo%3Adrm+-label%3Avo%3Agpu%3Aangle+-label%3Avo%3Agpu%3Adrm+-label%3Avo%3Agpu%3Aopengl+-label%3Avo%3Agpu%3Avulkan+-label%3Avo%3Agpu%3Awayland+-label%3Avo%3Agpu%3Ax11+-label%3Avo%3Agpu+-label%3Avo%3Alibmpv%3Acocoa-cb+-label%3Avo%3Asdl+-label%3Avo%3Avaapi+-label%3Avo%3Avdpau+-label%3Avo%3Axv+-label%3Avo+) (111) the query basically excludes all none default labels, so it isn't completely correct, but there doesn't seem to be a query of "only include that one specific label"

additionally one could look for stale issues, possible duplicate issues, old issues that might not be applicable anymore, issues with missing info, etc.

**Comment by PranavBhattarai** [comment]
Having a **milestone** on these issues is not a bad idea.

**Comment by Akemi** [comment]
i have no idea how adding even more work to the issue tracker would help this issue where we can't even properly tag/label our current issues properly because the manpower is missing?

i opened this issues because people where claiming they would do the work or that it isn't that much work and i wanted to see what happens. what i can see now, we have 27 untagged issues and 191 issues with only default labels. basically the undone work only increased over the past ~6 months. i can also say that most of the original mentioned issues are also still there and weren't really touched since the initial post.

this problem also arose from me wanting to automate some things, like auto closing stale issues or where the issue template was ignored etc and other things, but the argument that we could do it manually anyway was brought up. apparently we can't.

**Comment by Akemi** [comment]
labeled and sorted out the 37 unlabelled issues.

**Comment by Akemi** [comment]
i sorted through all the above mentioned issues.
