### ISSUE TITLE
Docs: --hwdec=vaapi works with --vo=libmpv

### ISSUE THREAD

**Issue by afdw** [mpv-player/mpv#8045]
### Important Information

- mpv version: 478d39c57492107ce8d5a33e80d5624db330ceab
- Platform: Linux

### Description

`DOCS/man/options.rst` [says](https://github.com/mpv-player/mpv/blob/478d39c57492107ce8d5a33e80d5624db330ceab/DOCS/man/options.rst#video):
> #### `--hwdec=<api>`
> `<api>` can be one of the following:
> vaapi: | requires --vo=gpu or --vo=vaapi (Linux only)
> -- | --
But I think this might not be the case, from my experience it looks like it also works when embedding mpv in other application using libmpv (and the `libmpv` video output driver).

**Comment by Akemi** [comment]
please open a PR for this if possible.

**Comment by afdw** [comment]
> please open a PR for this if possible.

#8792.
