### ISSUE TITLE
[E]: Transcoder: mpv failed with code 1

### ISSUE THREAD

**Issue by Yakonche** [mpv-player/mpv#8046]
### Important Information

Provide following Information:
- mpv version : 0.32.0-695-g478d39c574
- Linux Distribution and Version : Ubuntu 20.04
- Source of the mpv binary : https://github.com/mpv-player/mpv-build.git
- GPU driver and version : NVIDIA GTX 1080 450.66

Hi, I just followed this tutorial step by step (https://www.svp-team.com/wiki/SVP:Linux#Building_3rd-party_apps_from_sources#) but I get this error message :

### Log file

Option vf: vapoursynth doesn't exist.
Error parsing option vf (option parameter could not be parsed)
Setting commandline option --vf=vapoursynth:/home/yakonche/.local/share/SVP4/scripts/ffff.py:4:5 failed.
Exiting... (Fatal error)
===== mpv exited with code 1 =====

**Comment by Akemi** [comment]
i guess you built without vapoursynth support. though we can't tell without a log and you ignored the issue template.

**Comment by CounterPillow** [comment]
this also isn't the SVP support hotline
