### ISSUE TITLE
get current audio device if on auto select

### ISSUE THREAD

**Issue by daed-alus** [mpv-player/mpv#8047]
is there a property that holds the current audio device if mpv is set to auto select the device?

what i want to do, is apply a delay only to my bluetooth headset
if i connect my headset it get's automatically the default audio device and reverts if disconnected in windows
so i let mpv to auto select the device
but then the _audio-device_ property always has the value _"Autoselective device"_, no matter what real device is currently selected
without getting the real audio device i badly can't write a profile for it

**Comment by Akemi** [comment]
i don't think there is.
