### ISSUE TITLE
How do I reset window scale to video size dynamically with a command?

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8052]
I want to issue the equivalent of the window-scale=1 command (Alt+1) through a javascript -> ipc interface.

`set_property("window-scale", 1)` does nothing and `get_property("window-scale")` always returns 1, even if I've scaled the window by dragging the edges.

Also, get_property("geometry") returns an empty string.

Any ideas?

**Comment by Akemi** [comment]
there is a property named `current-window-scale`.

there is/was also this https://github.com/mpv-player/mpv/issues/7541.

**Comment by hedgehog90** [comment]
While 'current-window-scale' returns the correct window-scale, setting 'window-scale' = 1 still doesn't work in the latest build.
I've just realised however setting window-scale to any other value besides 1 does work, so setting it to 1.0001 get's more or less the desired the result.
This is clearly a bug though.
