### ISSUE TITLE
[Request] FAudio backend as single solution for all supported platforms!

### ISSUE THREAD

**Issue by mpvOWNZ-maybe** [mpv-player/mpv#8053]
[https://github.com/FNA-XNA/FAudio](https://github.com/FNA-XNA/FAudio)

Ever since @wm4's audio rewrite, PulseAudio output has been completely unusable:

When starting a video, mpv detects audio/video desync and skips several seconds.
Also, audio drops out completely and the video needs to be restarted from the beginning every time!

ALSA somehow works, but changes master volume of the system - which sucks!
I say somehow because with ALSA mpv reports a HUGE number of dropped frames:

`AV: 00:09:00 / 00:09:00 (100%) A-V:  0.000 DS: 1.000/3 Dropped: 696 Cache: 0.0s`

But notice the discrepancy between the number of delayed & dropped frames ... they don't really make any sense and I'm actually not noticing these dropped frames that mpv keeps reporting.

Therefore, I propose looking into implementing FAudio, since I'm using it with great success in RPCS3 (PlayStation 3 Emulator).
Here's the relevant commit:
[https://github.com/RPCS3/rpcs3/pull/6374](https://github.com/RPCS3/rpcs3/pull/6374)

And with FAudio, it might even be possible to have a single audio backend on all platforms that works reliably, so that all the other audio backends could eventually be removed from mpv; which I'm sure would help in the long run!

Hope somebody really looks into this and gives it a shot!

**Comment by thebombzen** [comment]
If PulseAudio is broken, that's a regression bug. We haven't dropped, removed, or deprecated PulseAudio support, so if it doesn't work then it's a bug that needs to be fixed. 

The solution is *not* to pull in a re-implementation of Windows Audio for Linux. Why would that be the solution

**Comment by CounterPillow** [comment]
> When starting a video, mpv detects audio/video desync and skips several seconds.

Then please submit an issue about this with the template filled out properly because it works just fine here.

**Comment by Akemi** [comment]
atm none of the developers are interested in adding another ao. though we would consider PRs for it. it's possible we will reconsider this in the future.
