### ISSUE TITLE
Passing lavfi-complex with semicolons from loadfile/pipe command

### ISSUE THREAD

**Issue by belonesox** [mpv-player/mpv#8054]
Hello. I open MPV with vstack of two video sources like that
```
mpv.com --lavfi-complex="[vid1]scale=320x160[v1];[vid2]scale=320x160[v2];[v1][v2]vstack=inputs=2[vo]" "source1.avs" --external-file="source2.avs"  --input-ipc-server=\\.\pipe\somepipe
```

And then send by pipe command to reload 
```
loadfile 'source1.py.avs' replace start=6,lavfi-complex='[vid1]scale=320x160[v1];[vid2]scale=320x160[v2];[v1][v2]vstack=inputs=2[vo]'
```
then I got 

```
[ipc_1] Client connected
[input] Command '[vid2]scale=320x160[v2]' not found.
[input] Command was defined at ipc_1.
[ipc_1] Client disconnected
[ipc_1] Exiting...
```

When my "lavfi-complex" was simple, without semicolons (no scale subfilter), all works.
Now, obviously MPV somehow split by semicolon input command from pipe.

**Is it possible to somehow change my lavfi-complex filter,
to make MPV got "loadfile" command from pipe?**

----

Actually I just want to force MPV reload AVISynth files,
but found nothing except "loadfile+replace".

I also tried single/double quotes, splitting by ';'/',', excaping by '\', '^' →  no luck:

```
loadfile "source1.avs" replace start=0,lavfi-complex="[vid1]scale=320x160[v1];[vid2]scale=320x160[v2];[v1][v2]vstack=inputs=2[vo]"  
```
↓↓↓
```
[input] Terminating '"' missing for 'loadfile'
[input] Unparseable garbage at end of option value: '"[vid1]scale=320x160[v1]'
[input] Command loadfile: argument 3 can't be parsed: option parameter could not be parsed.
```

```
[ffmpeg] AVFilterGraph: Unable to parse graph description substring: "\;[vid2]scale=320x160[v2]\;[v1][v2]vstack=inputs=2[vo]"
```

```
[ffmpeg] AVFilterGraph: Unable to parse graph description substring: "^;[vid2]scale=320x160[v2]^;[v1][v2]vstack=inputs=2[vo]"      
```

----
I asked in irc/#mpv → no luck.

**Comment by wm4** [comment]
This should work:
```
loadfile 'source1.py.avs' replace "start=6,lavfi-complex=[[vid1]scale=320x160[v1];[vid2]scale=320x160[v2];[v1][v2]vstack=inputs=2[vo]]"
```
Escaping `;` didn't work, because the input command parser splits by `;` before parsing the commands, and without handling escapes. That's why you need to quote the entire parameter with `"`. Additionally, you need to quote the lavi-complex parameter with `[` and `]`, because ironically, the `[vid1]` triggers the same escaping mechanism, and then  complains about the rest of the string that follows.
I guess escape handling could be better. But you can probably avoid much (or all) of this by using JSON instead.

**Comment by belonesox** [comment]
Great, thank you, it works!
