### ISSUE TITLE
Interpolating for 60Hz but disabling for factors of 60 (30fps, 15fps, etc.) or overriding the default display refresh rate

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8056]
I'm currently using this conf:

```
interpolation=yes
blend-subtitles=yes
video-sync=display-resample
tscale=box
tscale-window=sphinx
tscale-clamp=0.0
tscale-radius=0.95
```

With this setup, a 24fps video looks a lot smoother when played in MPV, and if I capture the display at any 30fps I get desirable results. Without interpolation the captured output at 30fps looks jerky and not very smooth (ie, frequent repeated frames).

However, if I play a 30fps video, every other frame is interpolated to make it 60fps, but if I capture the display at 30fps there's a 50% chance I'll be capturing only the interpolated frames in between, which will look blurry on playback of the captured output.

So, is there a way to disable interpolation for video frame rates that don't need it in my scenario (ie, frame rates that neatly factor into the display rate)
Or perhaps by overriding the display rate (which is set to my monitor's refresh rate) to the rate of my display capturer? (this solution probably makes a lot more sense for my purposes)

Bit of an unusual problem I admit! I'm trying to find the ideal setup for playing videos and capturing them with OBS.

**Comment by CogentRedTester** [comment]
You could use [conditional auto profiles](https://mpv.io/manual/master/#conditional-auto-profiles) to deactivate interpolation whenever the [container or estimated fps properties](https://mpv.io/manual/master/#command-interface-container-fps) are a factor of 60.

**Comment by CogentRedTester** [comment]
You can also use the [override-display-fps](https://mpv.io/manual/master/#options-override-display-fps) to change what fps display-resample targets. I don't know if it's a good idea to change it though.

**Comment by hedgehog90** [comment]
> You can also use the [override-display-fps](https://mpv.io/manual/master/#options-override-display-fps) option to change what fps display-resample targets. I don't know if it's a good idea to change it though.

I've just been trying this and it's delivering some really weird results, it seems like the A/V sync is going screwy and the speed is all over the place.
It's a shame as this seemed like my best bet if it worked as expected.

I'll try conditionally setting the interpolation on and off by reading the estimated-vf-fps, worried this might lead to more unexpected results

**Comment by CogentRedTester** [comment]
Honestly the easiest option is just to set a keybind to toggle interpolation or video-sync (whichever is causing the issue):

`cycle-values interpolation "yes" "no"`
`cycle-values video-sync "audio" "display-resample"`

Then just disable them manually.

**Comment by hedgehog90** [comment]
Way ahead of ya :)
I've built a web interface for controlling mpv and I've added a toggle to auto-detect when best appropriate to interpolate by checking the display fps and the estimated vf fps.
To my surprise it works perfectly and there's no stutter when switching it on and off.
Thanks for your help!
