### ISSUE TITLE
32-bit Window build crashes using Vulkan API

### ISSUE THREAD

**Issue by sammoth** [mpv-player/mpv#8057]
### Important Information

Provide following Information:

mpv-i686-20200830-git-bb1f821

W10 1909

Source of the mpv binary: shinchiro build

### Reproduction steps

The 32-bit build of mpv on Windows crashes for me when specifying gpu-api=vulkan, whereas 64-bit works fine.

Running `mpv --no-config --gpu-api=vulkan` I get the following:

![2020-09-04-23:04:21 090072389](https://user-images.githubusercontent.com/3324352/92288127-d07cc680-ef03-11ea-9ba3-f07c0c9122c7.png)

[mpv.log](https://github.com/mpv-player/mpv/files/5177144/mpv.log)

**Comment by sammoth** [comment]
Maybe this just means there is no 32-bit Vulkan driver available? I'm not sure I have any other 32-bit Vulkan applications to test

**Comment by haasn** [comment]
I need a backtrace to debug this.

**Comment by Dudemanguy** [comment]
Still no backtrace so...
