### ISSUE TITLE
tearing after fullscreen

### ISSUE THREAD

**Issue by doleovit** [mpv-player/mpv#8058]
- mpv-0.32.0_3
- kernel: 5.8.6_1 x86_64 bits: 64 desktop: bspwm 0.9.9 distro: void 
- device-1: intel uhd graphics 620 driver: i915 v: kernel
-  display: server: x.org 1.20.9 driver: intel resolution: 1920x1080~60Hz
- openGL: renderer: mesa intel uhd graphics 620 v: 4.6 mesa 20.1.6
-  xorg-7.6_5 ( xf86-video-intel-2.99.917.899_2 )
- intel-video-accel-1_1
- intel tearfree enabled, default sna
- no compositor (like picom or whatever)
- no dbus

1. no tearing in firefox, surf, et cetera.
2. play a video, no fullscreen, no tearing
3. enter fullscreen, no tearing
4. return from fullscreen
→ get tearing on all gl windows from now on

dirty "solutions" :

1. restart the x server, get no tearing on all gl windows ( back to normal ).
2. start mpv with env. v. `vblank_mode=0` or `opengl-swapinterval=0` in mpv config
3. enter fullscreen
4. return from fullscreen
→ no tearing at all  

vsync.

[similar](https://www.linuxquestions.org/questions/linux-newbie-8/xorg-screen-tearing-issue-on-intel-integrated-graphics-4175647941-print/) problem (last post), but in my case completely independent of his "tearfree". 

i guess this behaviour is already known over the years. is there an actual solution.

→ thx for your work.

**Comment by Akemi** [comment]
please don't ignore the issue template.

**Comment by doleovit** [comment]
thx, this solves the issue.

**Comment by Akemi** [comment]
great your issue is solved.

**Comment by wm4** [comment]
You should probably report this to Intel. mpv can't do anything about this.
