### ISSUE TITLE
Add a way to show warnings/errors in the video window, popup mode for console.lua

### ISSUE THREAD

**Issue by Akemi** [mpv-player/mpv#8061]
### Expected behavior of the wanted feature

add an option to make the console popup on warnings or higher for x seconds (not interactive/input). a shortcut to make it shut up (for the current file), in the case of warning spam from broken files for example.

this can be useful for pseudo-gui mode without a terminal, where warning/error can't be seen when they occur.

### Alternative behavior of the wanted feature

an alternate way to show warnings/errors in the video window.

**Comment by wm4** [comment]
Not very feasible. We don't have a way to distinguish actual errors and warnings, because ffmpeg doesn't.

**Comment by avih** [comment]
Maybe it can exclude the "ffmpeg" log module by default? This would still leave many useful warnings visible, like options/config issues and many more.

**Comment by Akemi** [comment]
duplicate of #7631
