### ISSUE TITLE
API Questions: Run, Subprocess, Named Arguments

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#8063]
I'm writing a .NET wrapper around MPV API via JSON IPC.

I wrote the basic controller, and then need to add implementations of every command. It's working fine for basic commands.

    public async Task LoadPlaylist(string path, bool append = false)
    {
        path.CheckNotNullOrEmpty(nameof(path));

        var flag = append ? "append" : "replace";
        await SendMessageAsync("loadlist", path, flag).ConfigureAwait(false);
    }

SendMessageAsync sends the list of arguments in the format that MPV expects, and returns the content of "data" in the response. Pretty simple.

Now, let's look at "run"

```
run <command> [<arg1> [<arg2> [...]]]
Run the given command. Unlike in MPlayer/mplayer2 and earlier versions of mpv (0.2.x and older), this doesn't call the shell. Instead, the command is run directly, with each argument passed separately. Each argument is expanded like in Property Expansion.
```

I don't know how it works, but I can implement as

    public async Task Run(string command, params object[] args)
    {
        command.CheckNotNullOrEmpty(nameof(command));

        args = new[] { command }.Concat(args).ToArray();
        await SendMessageAsync("run", args).ConfigureAwait(false);
    }

**What would be an example of Run command I could use for unit testing to make sure it's doing what it's supposed to do?**

Now, [Subprocess](https://mpv.io/manual/stable/#command-interface-subprocess) is even more confusing.

    This has the following named arguments. The order of them is not guaranteed, so you should always call them with named arguments, see Named arguments.

There is no indication as to what these mean: MPV_FORMAT_NODE_ARRAY, MPV_FORMAT_STRING, MPV_FORMAT_FLAG

**How do these named arguments work, and how do I need to implement that?**

It also returns "named arguments" that must be parsed, whatever that means.

**Comment by wm4** [comment]
The run command just passes the arguments as normal parameter as seen here: https://mpv.io/manual/master/#protocol
So what you have should be correct and work?

Named arguments (as mandated by the subprocess command) uses a JSON object instead of an array. The subprocess command has an example at the bottom, but using the Lua API instead of JSON: https://mpv.io/manual/master/#command-interface-subprocess
But JSON, Lua, and the libmpv API all map to the same concepts. (The JSON and Lua implementations use libmpv under the hood.) `MPV_FORMAT_NODE_ARRAY` for example would map the JSON arrays. This is probably not explicitly explained anywhere in the manual.

**Comment by mysteryx93** [comment]
So essentially, every JSON IPC request calls Run so I don't need to implement that one. It is exactly what SendMessageAsync does.

As for Subprocess, this is the syntax?

    subprocess <command> <args-object>

In which case I simply create an object with named properties that can be encoded as JSON?

Similarly, I create an object with named properties to decode the JSON?

**Comment by wm4** [comment]
See the subprocess example.

**Comment by mysteryx93** [comment]
You know what? I might as well just skip Subprocess. It's complicated and not really useful for IPC remote control.

I'd just leave RunShell

    public async Task RunShell(string command)
    {
        command.CheckNotNullOrEmpty(nameof(command));

        await SendMessageAsync("run", "/bin/sh", "-c", command).ConfigureAwait(false);
    }

**Comment by wm4** [comment]
Uh, and how is "run" any useful for an IPC client?
Anyway, your choice, but there might be other commands that more or less require named arguments.

**Comment by mysteryx93** [comment]
I haven't yet seen any other command with named arguments. Only ones left to implement are "Input Commands that are Possibly Subject to Change".

However some properties contain named arguments. I think I understand how it works, I might revisit it later after implementing some object properties.

**Comment by mysteryx93** [comment]
Oh... I'm seeing something interesting: "Input Command Prefixes"

This also applies to JSON IPC API?

> These prefixes are placed between key name and the actual command. Multiple prefixes can be specified. They are separated by whitespace.

I don't understand this part. How does this translate into practice?

I guess each command could have an options parameter, containing those settings, and whether the caller should wait for MPV's response.

**Comment by avih** [comment]
> I don't understand this part. How does this translate into practice?

That for instance you can run the command `add volume 10` and it will increase the volume and by default also show an OSD indication (in the case of volume both the new volume value as text, and a volume bar), but if you use the command `no-osd add volume 10` then it will have the same effect but without the OSD indication.

**Comment by mysteryx93** [comment]
in JSON, it will not be the same string as command, but a separate value before? Thus

    { command: [ "no-osd", "raw", "addfile", "abc.mp4" ] }

Correct?

**Comment by mysteryx93** [comment]
The prefix syntax above seems to work; at least it's not throwing any errors.

Now I'm looking at the documentation of [osd-overlay](https://mpv.io/manual/stable/#command-interface-osd-overlay) and the documentation is bad.

> format
> String that gives the type of the overlay. Accepts the following values:
> 
> ass-events
> The data parameter is a string. The string is split on the newline character. Every line is turned into the Text part of a Dialogue ASS event. Timing is unused (but behavior of timing dependent ASS tags may change in future mpv versions).
> 
> Note that it's better to put multiple lines into data, instead of adding multiple OSD overlays.
> 
> This provides 2 ASS Styles. OSD contains the text style as defined by the current --osd-... options. Default is similar, and contains style that OSD would have if all options were set to the default.
> 
> In addition, the res_x and res_y options specify the value of the ASS PlayResX and PlayResY header fields. If res_y is set to 0, PlayResY is initialized to an arbitrary default value (but note that the default for this command is 720, not 0). If res_x is set to 0, PlayResX is set based on res_y such that a virtual ASS pixel has a square pixel aspect ratio.

Formats are missing.

ass-events description is very unclear. It talks about lots of other things and I'm still clueless about what values it wants.

res_x however gives a hint: "Used if format is set to ass-events"

Which means that ass-events is one of the values for format arguments? What are the other valid values?

The documentation needs to be improved here.

**Comment by wm4** [comment]
I think your problem is just that the website rendering messed up the formatting/nesting.

**Comment by wm4** [comment]
PS: I don't know how to fix it.

**Comment by mysteryx93** [comment]
I tried with both Firefox and Chrome, and looking at the Master Branch, and it's the same

**Comment by wm4** [comment]
Try something that isn't webshit. Github also does its own even worse html conversion when "viewing" the files in the repo browser.

**Comment by mysteryx93** [comment]
In MPV documentation section, there is only link to doc web pages. How other than with a web browser would I look at the website?

Either way, it will have to be fixed.

**Comment by avih** [comment]
The source itself looks OK and is quite readable, as `rst` is intended to be. So I suggest you use that if you can't find a web view which displays it correctly: https://raw.githubusercontent.com/mpv-player/mpv/master/DOCS/man/input.rst

Also, the github renderer does indent it correctly but I don't think it's too easy to follow: https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst

**Comment by mysteryx93** [comment]
... so basically all this complicated text means that format is always set to "ass-events" unless we set "none" ?? but that could change in the future.

**Comment by mysteryx93** [comment]
I'm seeing one detail in the doc. 

    edition-list/N/id
    Edition ID as integer. Use this to set the edition property. Currently, this is the same as the edition index.

This property is not marked as RW. Is it writable or not?

Overall, I'm very surprised by the quality of the documentation, especially for an open-source project! Very precise with very few mistakes.

**Comment by avih** [comment]
> very few mistakes

If you noticed actual mistakes then please send a PR to fix them, or at least report them.

**Comment by mysteryx93** [comment]
well there's edition-list/N/id where it's not clear whether it's R or RW

**Comment by avih** [comment]
> there's edition-list/N/id where it's not clear whether it's R or RW

OK.
