### ISSUE TITLE
A button to switch the different video track

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8065]
### Expected behavior of the wanted feature
Add a button to switch the different video track in one MKV file which contains two or more video tracks. (on the OSC controller)
### Alternative behavior of the wanted feature
Automatically playing the next video track. (It will just play the first video track in one multi-videos track file)

**Comment by wm4** [comment]
That's a bit obscure. Currently you can just press the `_` key. (Will cycle through no video.)

**Comment by hooke007** [comment]
Yep, I know that shortcut key. I wish it could have a more intuitive option.

**Comment by thebombzen** [comment]
The OSC is designed to provide relatively common player features to make mpv function a little bit more like a GUI player. Cycling video tracks is a relatively unusual and obscure option so adding it to the OSC would clutter it up a bit more. You can still use `_` and if that keyboard shortcut does not satisfy your fancy, you can change it to anything else in `input.conf`.

**Comment by jimmy-1000** [comment]
> 
> 
> Yep, I know that shortcut key. I wish it could have a more intuitive option.

Like thebombzen said, we can change the key. The bad thing is mpv thinks cover.jpg is a video track 🙄

**Comment by vt-idiot** [comment]
> ### Expected behavior of the wanted feature
> Add a button to switch the different video track in one MKV file which contains two or more video tracks. (on the OSC controller)
> 
> ### Alternative behavior of the wanted feature
> Automatically playing the next video track. (It will just play the first video track in one multi-videos track file)

@hooke007 You still looking for this? Found this issue after having the same thought myself.

I'm not clever enough to figure out how to disable the button when there are only embedded images (cover art, MKV attachments, doesn't matter) + 1 video (or to hide those as "video tracks" from the selector) but here you go...

![image](https://github.com/mpv-player/mpv/assets/81622808/85594f75-dabb-4379-ad91-36db6eabbff8)

The button greys itself out when there is only one video track. It will treat embedded images, regardless of container, as video tracks. I have no idea what that icon is for, but its codepoint wasn't being used for anything else in osc.lua, and it looked like an eyeball to me.

<hr>

Grabbed current osc.lua from this repo: [original-osc.lua.txt](https://github.com/mpv-player/mpv/files/12267805/original-osc.lua.txt)

"Monkey see - monkey do"'d a button to change the video track: [osc.lua.txt](https://github.com/mpv-player/mpv/files/12267806/osc.lua.txt) - rename that osc.lua and you're good to go. Change the line endings (LF -> CR LF) if you're on Windows... or just use this: [osc.lua.CRLF.txt](https://github.com/mpv-player/mpv/files/12267832/osc.lua.CRLF.txt)

Made a diff/patch: [nuOSC.patch](https://github.com/mpv-player/mpv/files/12267813/nuOSC.patch)

**Comment by jimmy-1000** [comment]
> > ### Expected behavior of the wanted feature
> > Add a button to switch the different video track in one MKV file which contains two or more video tracks. (on the OSC controller)
> > ### Alternative behavior of the wanted feature
> > Automatically playing the next video track. (It will just play the first video track in one multi-videos track file)
> 
> @hooke007 You still looking for this? Found this issue after having the same thought myself.
> 
> I'm not clever enough to figure out how to disable the button when there are only embedded images (cover art, MKV attachments, doesn't matter) + 1 video (or to hide those as "video tracks" from the selector) but here you go...
> 
> ![image](https://user-images.githubusercontent.com/81622808/258601062-85594f75-dabb-4379-ad91-36db6eabbff8.png)
> 
> The button greys itself out when there is only one video track. It will treat embedded images, regardless of container, as video tracks. I have no idea what that icon is for, but its codepoint wasn't being used for anything else in osc.lua, and it looked like an eyeball to me.
> 
> Grabbed current osc.lua from this repo: [original-osc.lua.txt](https://github.com/mpv-player/mpv/files/12267805/original-osc.lua.txt)
> 
> "Monkey see - monkey do"'d a button to change the video track: [osc.lua.txt](https://github.com/mpv-player/mpv/files/12267806/osc.lua.txt) - rename that osc.lua and you're good to go. Change the line endings (LF -> CR LF) if you're on Windows... or just use this: [osc.lua.CRLF.txt](https://github.com/mpv-player/mpv/files/12267832/osc.lua.CRLF.txt)
> 
> Made a diff/patch: [nuOSC.patch](https://github.com/mpv-player/mpv/files/12267813/nuOSC.patch)

Thanks for this script. You need to add **--no-osc** to mpv.conf.
About the images (videos with cover) the problem is in mpv, not in the lua. I discovered that problem when I used SMplayer (it uses mpv as core). I reported it but the programmers ignore it and closed my issue:
https://github.com/mpv-player/mpv/issues/8561
