### ISSUE TITLE
gpu-api=vulkan broken

### ISSUE THREAD

**Issue by truexfan81** [mpv-player/mpv#8069]
### Important Information

Provide following Information:
- mpv version: latest git master
- Linux Distribution and Version: ubuntu 20.04
- Source of the mpv binary: compiled using mpv-build
- If known which version of mpv introduced the problem: not sure
- Window Manager and version: kwin 5.18.5
- GPU driver and version: amd opensource driver, not sure how to check the version
- Possible screenshot or video of visual glitches: no visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
add the following to mpv.conf:
vo=gpu
gpu-api=vulkan
Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
player starts without error using vulkan
### Actual behavior
player starts but outputs an error:
Error parsing option gpu-api (option parameter could not be parsed)
setting option gpu-api='vulkan' failed.
### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5192934/output.txt)

### Sample files
any video file will work

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
You compiled mpv without vulkan support.

**Comment by Akemi** [comment]
then this can be closed.
