### ISSUE TITLE
Ctrl key not work in terminal

### ISSUE THREAD

**Issue by agguser** [mpv-player/mpv#8072]
mpv 0.32.0 on Arch Linux 5.8.7

<kbd>Ctrl</kbd> key does not work in **terminals** (e.g. xterm, urxvt) playing **audio** files (but it does work on **video** files, pressing keys on the GUI).

For example, when running `mpv --no-config song.m4a`,  pressing <kbd>Ctrl-a</kbd> shows `[input] No key binding found for key '0x1'` (<kbd>Ctrl-b</kbd> shows `0x2`, and so on) instead of `… 'Ctrl+a'`.

Not sure if this is an mpv's bug or my X misconfiguration, but other terminal apps (e.g. zsh, vim) has no problems with <kbd>Ctrl</kbd> key.

**Comment by avih** [comment]
> pressing Ctrl-a shows [input] No key binding found for key '0x1' (Ctrl-b shows 0x2, and so on) instead of … 'Ctrl+a'.

That's literally what the terminal sends - the byte `0x01` for ctrl-a etc, so it's not an issue with the terminal. mpv should probably know to interpret some simple sequences like ctrl+letter and alt+letter. For more complex sequences it becomes more complex and starts to depend on terminal configuration and other factors.
