### ISSUE TITLE
external-file command not opening URL (Twitch stream)

### ISSUE THREAD

**Issue by crackerbear** [mpv-player/mpv#8074]
### Important Information
mpv 0.32.0-713-gf57b90b069 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Sep  6 12:42:55 +08 2020
FFmpeg library versions:
   libavutil       56.58.100
   libavcodec      58.105.100
   libavformat     58.54.100
   libswscale      5.8.100
   libavfilter     7.87.100
   libswresample   3.8.100
FFmpeg version: git-2020-09-05-d182d8f10

On Windows 10 64bit.

### Reproduction steps

`mpv "https://www.twitch.tv/somestreamer1" --external-file="https://www.twitch.tv/somestreamer2" --lavfi-complex="[vid1] scale=960x540:flags=spline [vid1_scale]; [vid2] scale=960x540:flags=spline [vid2_scale]; [vid1_scale][vid2_scale] hstack [vo]"`

Replace somestreamer1 and 2 with a stream that's currently live.

### Expected behavior

2 Twitch streams horizontally stacked playing side by side.

### Actual behavior

I get the error **Can not open external file https://<span></span>www.twitch.tv/somestreamer2.**

Is this an issue with the `external-file` command not being able to parse URLs (youtube-dl problem perhaps)? I can get the it to work if I replace `external-file` with a local video file rather than a URL.

**Comment by wm4** [comment]
These options need an actual media URL. Only the "main" file can go through ytdl_hook, which turns website links to media URLs.

**Comment by garoto** [comment]
For the `--external-file`, feed mpv the actual .m3u8 URL fetched with  `youtube-dl --get-url <URL>`

**Comment by crackerbear** [comment]
> 
> 
> These options need an actual media URL. Only the "main" file can go through ytdl_hook, which turns website links to media URLs.

That's a shame that external-file doesn't also go through the same ytdl_hook.



> 
> 
> For the `--external-file`, feed mpv the actual .m3u8 URL fetched with `youtube-dl --get-url <URL>`.
> 

Makes sense, thanks for showing how to get the .m3u8 URL.
