### ISSUE TITLE
Howto automatically select a profile according to the FQDN of the URL

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#8075]
Hi, I have this specific profile for ok.ru videos :
```bash
$ grep ok.ru -A1 ~/.config/mpv/mpv.conf 
[ok.ru]
ytdl-format=best[height<=480]/bestvideo[height<=?480]+bestaudio/best
```
How can I have `mpv` select this profile automatically when playing `ok.ru` video URLs ?

**Comment by garoto** [comment]
This is for auto-profiles.lua (needs to be adapted to work with the now built-in version):

```
profile-desc=cond:string.match(get("path", ""), "ok.ru") ~= nil
<options>
```

**Comment by sebma** [comment]
@garoto I have no `auto-profiles.lua` file on my machine, how and where shall I create this file ?

**Comment by garoto** [comment]
https://github.com/mpv-player/mpv/wiki/User-Scripts

**Comment by sebma** [comment]
@garoto Thanks and the following needs to be added to my `mpv.conf`, right ? : 
> ```
> [ok.ru]
> profile-desc=cond:string.match(get("path", ""), "ok.ru") ~= nil
> ytdl-format=best[height<=480]/bestvideo[height<=?480]+bestaudio/best
> ```

**Comment by sebma** [comment]
@garoto It works fine, thanks again.

**Comment by sebma** [comment]
@garoto Hi, I'm just trying to find some documentation about this lua call `get("path", "")` but I couldn't find it even in the Lua reference manual : https://www.lua.org/manual/5.4/manual.html

Do you know where I can find it ?

**Comment by guidocella** [comment]
See https://mpv.io/manual/master/#conditional-auto-profiles

**Comment by sebma** [comment]
@guidocella So It's not a Lua method but it comes from the mpv API right ?

**Comment by guidocella** [comment]
That's correct.

**Comment by sebma** [comment]
@guidocella Thanks for the link :+1: 

G-d bless you.
