### ISSUE TITLE
Small Documentation Issues

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#8077]
I'm going through the API doc to write a .NET wrapper over JSON IPC. I'm surprised at the quality of the documentation -- MUCH MUCH better than the last API I went through!

While going through it, I might as well report any errors, inconsistencies, or unclear things I come across.

First, R / RW flags aren't consistent. One example is "edition-list/N/id", where the description says it can be set, yet it doesn't have the RW flag. "cache-speed" has the R flag when all other read-only properties don't.

Bool properties are documented as returning "yes" or "no", but in Json, it's encoding as proper true/false. The documentation is for various types of usages so perhaps the "yes"/"no" is accurate for other contexts.

Now, "demuxer-cache-state"

>Various undocumented or half-documented things.

The actual data it returns is this

    {"cache-end":0.920000,"reader-pts":-0.080000,"cache-duration":1.000000,"eof":false,"underrun":false,"idle":true,
    "total-bytes":30256,"fw-bytes":30256,"raw-input-rate":6571,"debug-low-level-seeks":0,"debug-byte-level-seeks":2,
    "debug-ts-last":0.920000,"bof-cached":false,"eof-cached":false,"seekable-ranges":[]}

**"file-cache-bytes" isn't in the return values, and there are several return values that aren't listed.**

Can you confirm whether seekable-ranges should be in this format?

    "seekable-ranges":[ { "start":0.0, "end":1.0 }, { "start":0.0, "end":1.0 } ]

**Another minor inconsistency. Descriptions starting with "Returns" vs "Return", there should be guidelines as to which one to use.**

> paused-for-cache
> Returns yes when playback is paused because of waiting for the cache.
> cache-buffering-state
> Return the percentage (0-100) of the cache fill status until the player will unpause (related to paused-for-cache).

**video-frame-info sub-properties have no documentation**

> video-frame-info/picture-type
> video-frame-info/interlaced
> video-frame-info/tff
> video-frame-info/repeat

**osd-dimensions: by convention, sub-properties should contain "osd-dimensions/"**

> w
> Size of the VO window in OSD render units (usually pixels, but may be scaled pixels with VOs like xv).
> h
> Size of the VO window in OSD render units,
> par
> Pixel aspect ratio of the OSD (usually 1).

**Inconsistency between "yes" and "true"**

> partially-seekable
> Return yes if the current file is considered seekable, but only because the cache is active. This means small relative seeks may be fine, but larger seeks may fail anyway. Whether a seek will succeed or not is generally not known in advance.
> 
> If this property returns true, seekable will also return true.

**"Read-only" isn't true. Most options can be changed, and "some" are read-only.**

    options/<name> (RW)
    Read-only access to value of option --<name>. Most options can be changed at runtime by writing to this property. Note that many options require reloading the file for changes to take effect. If there is an equivalent property, prefer setting the property instead.

**A more concrete problem now: "profile-list" doesn't return any response. At least not within 10 seconds.**

    {"command":["get_property","profile-list"],"request_id":1}

**[List of Events](https://mpv.io/manual/stable/#list-of-events) is missing event "property-changed"**

I'll report in this thread whenever I see other issues.

**Comment by mysteryx93** [comment]
video-frame-info sub-properties have no documentation

**Comment by mysteryx93** [comment]
Something I'd like to know. Can some properties or command return "data":null when "error":"success" ?

When properties are unavailable, it returns something like

    {"request_id":2,"error":"property unavailable"}

What are the possible error values?

**Comment by avih** [comment]
> Can some properties or command return "data":null when "error":"success"

`null` is a valid value, so if the property value happens to be `null` (no, I don't have an example off hand), then sure, it can happen.

> what are the possible error values?

Anything other than "success" should be considered an error, and you can consider the actual value a diagnostic message. At this point in time these are the possible values https://github.com/mpv-player/mpv/blob/master/options/m_property.h#L104 but I don't think it's guaranteed to stay that way, so you should probably not count on specific values except that 0 is success and negative (if you use libmpv) is failure.

**Comment by mysteryx93** [comment]
osd-dimensions: by convention, sub-properties should contain "osd-dimensions/"

> w
> Size of the VO window in OSD render units (usually pixels, but may be scaled pixels with VOs like xv).
> h
> Size of the VO window in OSD render units,
> par
> Pixel aspect ratio of the OSD (usually 1).

**Comment by avih** [comment]
> At this point in time these are the possible values...

Note that these values are not exposed directly to libmpv clients, so it's just an FYI on what errors properties can have. The official libmpv interface is documented at `client.h`.

**Comment by mysteryx93** [comment]
> `null` is a valid value, so if the property value happens to be `null` (no, I don't have an example off hand), then sure, it can happen.
Is 'null' a valid value for INT and DOUBLE properties? What data types can be null?

**Comment by avih** [comment]
> Is 'null' a valid value for INT and DOUBLE properties?

If it's documented as INT (or DOUBLE) at-all-times but its value is null, then it's a bug and you should report it.

But it's not C, and the type is not necessarily pre-defined at compile time, and not all properties have a meaningful value at all times. For instance the property `time-pos` might have a `null` value before playback begins because there is no actual value at that point in time, but DOUBLE during playback, etc.

**Comment by mysteryx93** [comment]
Talking of 'null'. "vf" property returns "[]" when there is no filter. It's not null; but it's also an invalid value to deserialize.

I'm not sure whether it's the expected behavior, but I have to write an exception before attempting to deserialize

    if (data == "[]" && !typeof(T).IsAssignableFrom(typeof(IEnumerable)))
    {
        return default;
    }

**Comment by mysteryx93** [comment]
Inconsistency between "yes" and "true"

> partially-seekable
> Return yes if the current file is considered seekable, but only because the cache is active. This means small relative seeks may be fine, but larger seeks may fail anyway. Whether a seek will succeed or not is generally not known in advance.
> 
> If this property returns true, seekable will also return true.

**Comment by mysteryx93** [comment]
> options/<name> (RW)
> Read-only access to value of option --<name>. Most options can be changed at runtime by writing to this property. Note that many options require reloading the file for changes to take effect. If there is an equivalent property, prefer setting the property instead.

"Read-only" isn't true. Most options can be changed, and "some" are read-only.

**Comment by avih** [comment]
@mysteryx93 Please try to collect your issues and post them in one go, and then it would be easier for us to refer to them at one go. Otherwise it just adds noise to the email notification every time you add a note.

If you bump into an issue you feel is necessary to understand before proceeding, then please try to procees anyway, and only if you still really get stuck then ask and we'll try to answer.

Thanks for the understanding.

**Comment by mysteryx93** [comment]
Do you get emails each time I edit the main post? I could edit to add them there.

A more concrete problem now: "profile-list" doesn't return any response. At least not within 10 seconds.

    {"command":["get_property","profile-list"],"request_id":1}

**Comment by mysteryx93** [comment]
All properties are written except Options, but I can't get osd-overlay to work

    {"command":["osd-overlay",{"id":0,"format":"ass-events","data":"test message"}],"request_id":2}
    {"command":["osd-overlay",{"id":0,"format":"ass-events","data":"[[{\\an4\\fs40}OSD test]]"}],"request_id":2}
    {"command":["osd-overlay",{"id":0,"format":"none"}],"request_id":2}

All of these return

    {"request_id":2,"error":"invalid parameter"}

What's missing here?

**Comment by avih** [comment]
> Do you get emails each time I edit the main post?

No.

> I could edit to add them there.

Please don't. Use edits only to fix typos and other not-important changes. For actual new info please use new posts.

But just collect all the remarks you have in some file, and then add one post with all of them together.

Thanks.
