### ISSUE TITLE
Resize screenshots

### ISSUE THREAD

**Issue by Geniusssmit** [mpv-player/mpv#8080]
I know there is an option to change quality and format of screenshots, but I can't find any to change screenshot's resolution.
For my purposes, I need 640x360 screenshots because they are ~20 kb each.
Question is - how can I set mpv player so that all of my screenshots are cropped 640x360?

**Comment by wm4** [comment]
Not currently possible, and I'm probably too stingy to add it as a feature.

**Comment by Hrxn** [comment]
Might just be me, but I think that would be totally out of scope.

If you need to process screenshots *automagically*, use a script with ImageMagick or something.

**Comment by EzeKees** [comment]
And any way to capture a screenshot without pipelining the file?
For example, through libmpv, call get_current_frame and its return value is a byte array that corresponds to the current frame.
Is this implemented?
Thanks in advance

**Comment by Akemi** [comment]
there is a `screenshot-raw` command (now).
