### ISSUE TITLE
af=sacletempo2 crashes when the speed is >= 16

### ISSUE THREAD

**Issue by Alkeryn** [mpv-player/mpv#8081]
### Important Information

Provide following Information:
- mpv version : mpv 0.32.0-722-geed8b6d47b
- Linux Distribution and Version : Arch Linux (kernel : 5.8.7-arch1-1)
- Source of the mpv binary : mpv-git package from the AUR
- If known which version of mpv introduced the problem : no
- Window Manager and version : Bspwm 0.9.10 on xorg server 1.20.9-2
- GPU driver and version : nvidia 450.66-18

### Reproduction steps

run 
``` 
mpv --no-config --af=scaletempo2=max-speed=17 <file>
as long as max-speed is > 16 so that you can get to a speed higher than 16
```
increase the speed with ] until it is higher or equal to 16, then on my computer, mpv crashes with that error message : 
```
mpv: ../audio/filter/af_scaletempo2_internals.c:414: mp_scaletempo2_fill_input_buffer: Assertion `total_fill + p->input_buffer_frames <= p->input_buffer_size' failed.
zsh: abort (core dumped)  mpv file.mkv --no-config
```

### Expected behavior
The speed increases over 16
### Actual behavior
Mpv crashes
### Log file

https://pastebin.com/raw/TZ7UNGSG

### Sample files

every file i've tested worked so far, i tried many h264 and H265 mkv and mp4 files.

**Comment by wm4** [comment]
CC @DorianRudolph

**Comment by DorianRudolph** [comment]
I'm quite busy right now, but I will look into this once I have time.

**Comment by Alkeryn** [comment]
@DorianRudolph Thank you, don't worry, take the time you need :)
