### ISSUE TITLE
What's the best way to dynamically display danmaku (scrolling) comments?

### ISSUE THREAD

**Issue by steinuil** [mpv-player/mpv#8086]
I want to display the messages sent on an IRC channel (or some other chat service) overlaid on top of the video like danmaku comments on niconico, so as text scrolling from right to left, but I'm not sure how to achieve that with the APIs exposed by mpv.

Converting them to an .ass file is not an option since they have to be added in real time (unless .ass files can also be streamed somehow?).

Using an ass-events overlay could potentially work, but it doesn't seem like animated tags such as `\move` work right now. I think I've seen an issue on github months ago about this, but I can't find it anymore. The manual says

> but behavior of timing dependent ASS tags may change in future mpv versions

Is supporting `\move` and other similar commands a planned feature?

I could also draw the danmaku comments with an external program to a bitmap file and reload it on every frame with overlay-add, or even use an ass-events overlay and manually keep track of all the positions of the individual comments and again update them every frame, both of which seem doable but feel very awkward...

Are there better options for my use case?

**Comment by occivink** [comment]
You can simply update the ass-events overlay every frame to simulate the movement effect.

**Comment by avih** [comment]
There's no built in support for scroll, and there's no support currently for "move" events in anything other than actual subtitles, so you'll have to implement something yourself.

Some ideas (not tested):
- Add (and maybe remove) subtitles with "move" in real-time with something like `mp.commandv("sub-add", "memory://ass-content-here")`.
- Generate and display your content several times-per-second using `osd-overlay` and timers. Note that every frame is not trivial - in the past the `tick` event could have been used, but it's deprecated now without real alternative.

**Comment by wm4** [comment]
I'm assuming this has to be dynamic. How would you update the overlay correctly without introducing discontinuities in the movement? If overlays were to support timing, they'd probably always use system time.

> Generate and display your content several times-per-second using osd-overlay and timers. Note that every frame is not trivial - in the past the tick event could have been used, but it's deprecated now without real alternative.

That wouldn't be frame-exact.

**Comment by steinuil** [comment]
I've tried out the osd-overlay and timers suggestion with the callback set at 1/60th of a second, which is how I initially thought of implementing it. There is a bit of stuttering due to not being frame-exact but I think it's good enough for my purposes. If there's no better alternative I guess I'll be going with this.

**Comment by occivink** [comment]
If you're talking about a timer, the manual does say that its resolution is only reliable down to 50ms. Observing `time-pos` like so seems to give good results to me
```
local duration = 5
local ov = mp.create_osd_overlay("ass-events")
mp.observe_property("time-pos", "number", function(_, timepos)
    if not timepos or timepos > duration then
        ov.data = ""
        ov:update()
        return
    end
    local ww, wh = mp.get_osd_size();
    local pos = (timepos / duration) * ww
    ov.data = string.format("{\\pos(%i, %i)}%s", pos, 360, "hello")
    ov:update()
end)
```

**Comment by steinuil** [comment]
`time-pos` could work (since this is in the context of a stream and you're not really supposed to pause). Only thing is, it's not very clear to me how often time-pos updates, at least from the docs.

**Comment by po5** [comment]
See [mpv_irc](https://github.com/po5/mpv_irc) for a script that does exactly this.

**Comment by steinuil** [comment]
@po5 nice! I'll be stealing the IRC handling code from that.

Also I'll close this, since it looks like timers or the `time-pos` event are the best ways to handle this.
