### ISSUE TITLE
Can please adding support for Teletext subtitles?

### ISSUE THREAD

**Issue by rocco99222** [mpv-player/mpv#8088]
Shortkey to set page number. (here in Netherlands it is on page 888)

And shortkey to activate.

And if can convert the grapical subtitles to normal tekst (displaying it the same as SRT subtitles)

Thank you!

**Comment by rocco99222** [comment]
@Lypheo

It is not at life TV, but a recording TS file that i want to play with MPV.
That file that is a copy from the broadcast storing teletext data.

**Comment by jeeb** [comment]
I think this is already supported.

You need FFmpeg built with built with libzvbi, and then you can control the page with https://mpv.io/manual/master/#options-teletext-page . This option on FFmpeg's side can nowadays be set to a special value "subtitle" which would output all pages that are flagged as a subtitle page, but that is at this point not supported on mpv's side.

To get text subtitles, you require setting the option `txt_format` to `ass` from the default of `bitmap`.

**Comment by rocco99222** [comment]
Don't understand anything, and have Windows now.

**Comment by Dudemanguy** [comment]
The feature should already be supported as noted.
