### ISSUE TITLE
How to extract mpv.exe file?

### ISSUE THREAD

**Issue by rocco99222** [mpv-player/mpv#8091]
Is FFMPEG featured in that file?

**Comment by wm4** [comment]
objdump -d mpv.exe
Yes.

**Comment by rocco99222** [comment]
I use Windows now and search for Windows tool to extract mpv.exe

**Comment by avih** [comment]
mpv.exe does NOT contain a copy of ffmpeg.exe, so you cannot extract it to use as a program.

mpv.exe does have the ffmpeg library inside it, but you cannot use it as a program.

If you want ffmpeg.exe, you can get it from here https://www.videohelp.com/software/ffmpeg (this is unrelated to mpv).
