### ISSUE TITLE
Howto automatically select a profile according to the power or hostname of the computer running mpv

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#8092]
Hi,
I have downloaded [auto-profiles.lua](https://github.com/wiiaboo/mpv-scripts/blob/master/auto-profiles.lua) into my `~/.config/mpv/scripts/` dir.
How can I write a condition to select a profile according to the power (cpu frequency ?, ram quantity ?) or hostname of the computer running mpv ?

I tried this, but it does not work : 
```
[pc1]
profile-desc=cond:string.match(getenv("HOSTNAME"), "pc1") ~= nil
autofit=100%x92%
```
mpv says : 
`[auto_profiles] Error evaluating: [string "profile pc1 condition"]:1: attempt to call global 'getenv' (a nil value)`

Can you please help me or give some documentation ?

**Comment by sebma** [comment]
I've replaced `getenv` by `os.getenv`, now it says : 
`[auto_profiles] Error evaluating: [string "profile seb-C70D-B-311 condition"]:1: bad argument #1 to 'match' (string expected, got nil)`
I'm new to lua.

**Comment by sebma** [comment]
I've noticed, the `HOSTNAME` variable needed to be exported.

```
$ lua5.2 -e 'print( os.getenv("HOSTNAME") )'
nil
$ export HOSTNAME
$ lua5.2 -e 'print( os.getenv("HOSTNAME") )'
pc1
```
Now, `mpv` give no error but does not select the `[pc1]` although I'm running `mpv` on `pc1`.

**Comment by sebma** [comment]
This works : 
`profile-desc=cond:os.getenv("HOSTNAME") == "pc1"`

**Comment by Akemi** [comment]
you can do something like this for example.

https://github.com/Argon-/mpv-config/blob/e193d8dc1f78fcb17a03df6ea7474787cca050d1/mpv.conf#L31-L37
https://github.com/Argon-/mpv-config/blob/e193d8dc1f78fcb17a03df6ea7474787cca050d1/mpv.conf#L123-L127
https://github.com/Argon-/mpv-config/blob/e193d8dc1f78fcb17a03df6ea7474787cca050d1/lua-modules/auto-profiles-functions.lua

**Comment by sebma** [comment]
@Akemi I don't this piece of code inside [auto-profiles-functions.lua](https://github.com/Argon-/mpv-config/blob/master/lua-modules/auto-profiles-functions.lua) : 

```lua
local function is_level(level)
    return function(width, height, fps)
        local l = determine_level(width, height, fps)
        return l == level
    end
end
```
Seems complicated, why not write something simpler such as this ? : 
```lua
local function is_level(level)
    local l = determine_level(width, height, fps)
    return l == level
end
```

**Comment by Argon-** [comment]
`is_level` returns a function, therefore, `is_high` is a function and not a boolean. Calling it is the same as calling `is_level(HIGH)` but shorter and you don't need to know about the HIGH/MID/... constants.

**Comment by sebma** [comment]
> This works :
> `profile-desc=cond:os.getenv("HOSTNAME") == "pc1"`

This works also :smile: :
`profile-desc=cond:string.find(os.getenv("HOSTNAME"),"PC-NAME",1,true) ~= nil`

**Comment by sebma** [comment]
Calling `mpv` from a freedesktop `.deskop` file fails testing upon the `HOSTNAME` variable because it loads a restricted environment where `HOSTNAME` is not set.

A workaround is to set it in the `Exec` statement of the `.desktop` file : 
```
Exec=HOSTNAME=$(hostname) mpv ...
```

Or if one has a lot a `.desktop` files, a workaroud is to create a `mpv.sh` script, put in a directory in the `PATH` and replace the `Exec` statement by the following : 
```
Exec=mpv.sh ...
```
