### ISSUE TITLE
G-sync is now working in windowed OpenGL and Vulkan since Nvidia 440.97

### ISSUE THREAD

**Issue by ValZapod** [mpv-player/mpv#8094]
Why should you care? Well, first of all 24000/1001 (23.976) and 24.000 are different, and 24.000 is now used in more and more Blu-rays and Netflix Originals as it what DCI uses and what non-American Bu-rays use. You can switch 120000/1001 to 120.000 Hz using alternate clock in AVI infoframe, but of course in Windows it can be buggy or not work at all and even [in linux kernel](https://github.com/torvalds/linux/commit/304a94a2e6debadd55c4e73cbec432dd57832856#diff-f1b0089a97dd0195eb24305ab63a79e3) there were bugs fixed! Now G-sync works everytime. If you want 72.000 Hz on 100 Hz display (my display supports only higher than 62 Hz, and Low Framerate Compensation doubles the framerate) you can have it! Like with latest Fifth Element, for example. Now if you want 72/1001 it can also work.

Where G-sync works now since that driver? In ffplay. In [photoshop](https://photos.app.goo.gl/6uUw4svfkz1FqjJa6). In Audition. In [Blender](https://developer.blender.org/T76511)! And in mpv. 

Now some questions. 1) is 23.976 is G-sync actually good enough for 24000/1001 estimation?
2) Why sometimes using Nvidia overlay you can see that 24 framerate is fluctuating and sometimes it is not?
3) How to turn off all interpolation as if I understand it correctly by default all interpolation IS off in vulkan and opengl frontends?

The commands are used will follow.

**Comment by Akemi** [comment]
1. probably in most cases
2. depending on the case vsyncs may jitter
3. yes interpolation is off by default

**Comment by ValZapod** [comment]
1) Is G-sync able to also switch the actual clock so that 23.976 (and multiples) is actually valid even after 3 decimal places? I heard it can at least in Vulkan as Vulkan has direct access to VRR API family.
2) It does it too often. I had to restart mpv like 3 times to get it not jumping that thing. I use one command that works everytime. That is mpv.com --gpu-api=vulkan --vulkan-async-transfer=yes --vulkan-async-compute=yes --vo=gpu --hwdec=nvdec  **--video-sync=display-resample --interpolation=no** AND --override-display-fps. My proposal is to write the video framerate to --override-display-fps if G-sync is working. That is a good idea, no? On LG C9 works wonders.
3) I think I wanna edit your wiki and add G-sync where display sync is discussed. It is after all the best way to sync display on Windows and linux. Nircmd does not work nowadays and a bad idea, IMHO.

**Comment by Akemi** [comment]
1. asking here about g-sync is probably not the appropriate place. mpv doesn't set anything regarding the monitors refresh rate, if nothing changed recently
2. --override-display-fps= doesn't do anything else than setting the initial display refresh rate, it will estimate a new one while running and will use that instead. it's a bad idea, also we don't know about g-sync in the mpv context
3. i think we had another issue where g-sync and mpv settings were discussed, there might be valuable information there.
