### ISSUE TITLE
Audio doesn't work after monitor goes to sleep

### ISSUE THREAD

**Issue by rocribera** [mpv-player/mpv#8096]
I usually have MPV open for a long time in my second monitor, since I work in between watching things, but if I leave for a while (like having lunch) my monitors turn off. When I return and wake them up, MPV works fine, I can resume the video, but the audio doesn't work doesn't matter what I do, so I have to close the window and open again.

I imagine this is very specific and difficult to fix, since OS, drivers and many other things can be the cause of this, but if not possible to find a fix is there a way to implement a refresh of some kind (think F5 on browsers)? It would help a lot rather than having to go to the path and open again every single time I return to my pc from going anywhere.

Operating System: Windows 10 2004

EDIT: Don't know if it helps knowing this, but changing video while in a playlist doesn't fix the issue. It's the MPV window that loses the audio, doesn't matter what I do I have to open a new one.

**Comment by ValZapod** [comment]
If it is Nvidia there latest driver and previous one fixed this issue (HDMI and DP audio did not work at all), but in some cases it can still lead to crazy problems, I also had this one from time to time, but next time you see that bug try to play for 12 seconds, it can be that just like for me, the sound has a letency of 12 seconds.

**Comment by rocribera** [comment]
Not Nvidia, just updated drivers but so far doesn't look as it solved anything...

**Comment by qmega** [comment]
> a way to implement a refresh of some kind

Binding a key to `set ao null; set ao <whatever your ao usually is>` might do this.

If you provide a log, it might be clearer what is happening from mpv's point of view -- whether it can see something failing or the OS continues to accept audio and just throws it away, for example. In case you didn't notice the label applied to this issue, it means you aren't going to get much useful help if you don't add a log and the other information requested in the issue template.

**Comment by rocribera** [comment]
Here's the log, starting at line 2379 you see that there's no device specified and later at line 2420 there's the errors. I don't understand why the audio device isn't specified when the screen turns back on...
[20200918mpv.log](https://github.com/mpv-player/mpv/files/5245144/20200918mpv.log)

**Comment by wm4** [comment]
So this starts with:
```
[  14.164][v][ao/wasapi] Selecting device '{634babd5-c5a1-4827-a3a9-d2019f75215f}' (5 - 2460G5 (AMD High Definition Audio Device))
```
(Although strangely, it actually opens another device first, which is immediately reloaded or something.)

Then later, presumably at resume or suspend time, this happens:

```
[2057.072][v][ao/wasapi] OnDeviceStateChanged triggered on device {0.0.0.00000000}.{634babd5-c5a1-4827-a3a9-d2019f75215f}: requesting ao reload
```
The device is (probably) going away, so mpv closes it and tries to reinit it:
```
[2057.091][v][ao/wasapi] Selecting device '{19a69880-f0a2-41e8-ba89-12c7db7422b9}' (4 - L1954 (AMD High Definition Audio Device))
...
[2057.109][e][ao/wasapi] Error finding shared mode format: AUDCLNT_E_DEVICE_INVALIDATED (0x88890004)
```
But as you can see, it picks some (?) device, and initializing it is failing. Well, no clue what's happening there.

The easiest workaround is the select the audio track again manually (by default the `#` key). You could write a script that tries to reload the AO if currently none is active and the device list changes or so. One could argue that this should be builtin, but then again it isn't yet because I didn't want such complicated "policy" stuff.

**Comment by rocribera** [comment]
Oh changing the audio track fixes it! That's great! Thank you very much!
