### ISSUE TITLE
drm:amdgpu_cs_ioctl reports "not enough memory for command submission" with i7-8809g CPU

### ISSUE THREAD

**Issue by ChuckPa** [mpv-player/mpv#8098]
### Important Information

Provide following Information:
- mpv version    **0.32.0**
- Linux Distribution and Version  **Ubuntu 20.04.1 LTS**
- Source of the mpv binary **Ubuntu distribution - `apt-get install mpv`**
- If known which version of mpv introduced the problem
- Window Manager and version  **Gnome 3.36**
- GPU driver and version  **libdrm-amdgpu1::amd64  2.4.101-2** &  **libplacebo7:amd64 1.7.0-2**
- Possible screenshot or video of visual glitches

![MPV-fault-AMDGPU](https://user-images.githubusercontent.com/17990272/93555916-658cb000-f945-11ea-8c88-0611c6761483.jpeg)

**Mediainfo**
```
Format                                   : Matroska
Format version                           : Version 4
File size                                : 48.7 GiB
Duration                                 : 2 h 3 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 56.4 Mb/s
Encoded date                             : UTC 2020-05-02 07:12:01
Writing application                      : mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
Writing library                          : libebml v1.3.10 + libmatroska v1.5.2

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 3 min
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Title                                    : English
Writing library                          : ATEME Titan File 3.9.0 (4.9.0.0)        
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0020 cd/m2, max: 1000 cd/m2

```

### Reproduction steps

This problem is not easily reproducible.
Seeking around in the movie file, while actively playing,  'caught' it somehow.
The display manager became largely non-responsive.
Switching to the text console (CTRL-ALT-F3) allowed above photo of output to be captured.  Nothing in system logs (dmesg or journal)

### Expected behavior
Stable operation while seeking randomly through files.

### Actual behavior
Can be 'caught' resulting in condition shown above.

### Log file

_**Will complete ASAP**_
Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

_Am running with logging active now in hope of capturing this event again.   Will post when occurs agin_

The issue will be closed for ignoring the issue template.

### Sample files

Playback was at about 50% through 48 GB file.
Starting playback at that point does not fail. 
Would therefore need to provide entire file (difficult to do at 1.5 Mbps upload)

Additional runtime library info.
```
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.31.100
[cplayer]    libavcodec      58.54.100
[cplayer]    libavformat     58.29.100
[cplayer]    libswscale      5.5.100
[cplayer]    libavfilter     7.57.100
[cplayer]    libswresample   3.5.100
[cplayer] ffmpeg version: 4.2.4-1ubuntu0.1
[cplayer] 
```

Please don't hesitate to contact for more information or to assist gathering more info.

**Comment by CounterPillow** [comment]
Thank you for your report.

> Will complete ASAP

Until you can provide a log file of the problem in action, can you show a log file of you just playing a bit of the movie? That way we at least know whether you're using Vulkan, and perhaps some useful things about the hardware. Additionally it could tell us about the output resolution and whether it contains subtitles; the subtitle atlas is known to grow quite large on 4k outputs.

Additionally, the Linux kernel version you're running might be handy to know. I know my integrated Vega graphics had Vulkan completely busted with kernel 5.8, with a dmesg log entry from amdgpu complaining about something.

**Comment by ChuckPa** [comment]
I started playback `-v -v -l-log-file=output.txt` 

[output.txt](https://github.com/mpv-player/mpv/files/5243632/output.txt)


kernel:
```
[chuck@lizum Captain Marvel (2019).200]$ uname -a
Linux lizum 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[chuck@lizum Captain Marvel (2019).201]$ 
```

This is the only thing in the `dmesg` log.  Hope it helps.
```
[chuck@lizum Captain Marvel (2019).201]$ dmesg | grep amd
[    0.000000] Linux version 5.4.0-47-generic (buildd@lcy01-amd64-014) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 (Ubuntu 5.4.0-47.51-generic 5.4.55)
[    1.238227] [drm] amdgpu kernel modesetting enabled.
[    1.568008] amdgpu 0000:01:00.0: remove_conflicting_pci_framebuffers: bar 0: 0x90000000 -> 0x9fffffff
[    1.568009] amdgpu 0000:01:00.0: remove_conflicting_pci_framebuffers: bar 2: 0xa0000000 -> 0xa01fffff
[    1.568010] amdgpu 0000:01:00.0: remove_conflicting_pci_framebuffers: bar 5: 0xdb500000 -> 0xdb53ffff
[    1.568012] fb0: switching to amdgpudrmfb from EFI VGA
[    1.568070] amdgpu 0000:01:00.0: vgaarb: deactivate vga console
[    1.568084] amdgpu 0000:01:00.0: enabling device (0006 -> 0007)
[    1.568876] amdgpu 0000:01:00.0: BAR 2: releasing [mem 0xa0000000-0xa01fffff 64bit pref]
[    1.568877] amdgpu 0000:01:00.0: BAR 0: releasing [mem 0x90000000-0x9fffffff 64bit pref]
[    1.568930] amdgpu 0000:01:00.0: BAR 0: assigned [mem 0x2000000000-0x20ffffffff 64bit pref]
[    1.568942] amdgpu 0000:01:00.0: BAR 2: assigned [mem 0x2100000000-0x21001fffff 64bit pref]
[    1.568971] amdgpu 0000:01:00.0: VRAM: 4096M 0x000000F400000000 - 0x000000F4FFFFFFFF (4096M used)
[    1.568972] amdgpu 0000:01:00.0: GART: 256M 0x000000FF00000000 - 0x000000FF0FFFFFFF
[    1.569049] [drm] amdgpu: 4096M of VRAM memory ready
[    1.569052] [drm] amdgpu: 4096M of GTT memory ready.
[    1.569925] amdgpu: [powerplay] hwmgr_sw_init smu backed is vegam_smu
[    1.571468] amdgpu 0000:01:00.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=mem
[    1.881523] fbcon: amdgpudrmfb (fb0) is primary device
[    1.881525] amdgpu 0000:01:00.0: fb0: amdgpudrmfb frame buffer device
[    1.906341] [drm] Initialized amdgpu 3.35.0 20150101 for 0000:01:00.0 on minor 1
[    6.617474] snd_hda_intel 0000:01:00.1: bound 0000:01:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])
[chuck@lizum Captain Marvel (2019).202]$ 
```

**Comment by haasn** [comment]
It's possible this is some sort of VRAM OOM, but in any case, this is probably more interesting for the amdgpu developers than the mpv developers.

**Comment by Akemi** [comment]
closing since this is most likely an upstream problem. if the problem still persists please open a new issue.
