### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by mmowchenko** [mpv-player/mpv#8100]
Will there be a new version any time soon? I'd love for the cifs cache fix from #7408 back in March to land officially. Thanks for all the hard work!

**Comment by Akemi** [comment]
nope, nothing planned as of now.

**Comment by wm4** [comment]
Maybe we could do it soon, but not sure if anyone even cares. Just use git master.

**Comment by tsmithe** [comment]
Hey, I would also love to see a new release, if only because that makes it easier for distros to push changes (such as the fix for #7408) to people. I am happy to use master personally, but it seems a shame to restrict such things to those who know to build master.
