### ISSUE TITLE
Playback freezing on a local IPTV cam hevc @ 30fps

### ISSUE THREAD

**Issue by azev** [mpv-player/mpv#8103]
Source is an IPTV cam streaming HEVC 1280x960 @30fps, no audio. (LAN stream, no internet)
i7 8Gb RAM Windows 10 x64
Playback is very smooth on MediaPlayerClassicHC and through I.E. 11 (cam's web interface).

When playing the stream with the params bellow in mpv the playback is ok but it freezes too much, very annoying:

`mpv "rtsp://user:pass@192.168.0.6/cam" --hwdec=auto --no-correct-pts --fps=30 --untimed --profile=low-latency --framedrop=vo --vo=gpu`

I spent some time on the [doc](https://mpv.io/manual/stable/) to come up with those parameters. I wonder if they are correct.
Can someone please help me with those parameters to get a smooth playback?

**Comment by CounterPillow** [comment]
Please do not use the "question" template to report bugs. Use the bug template, and fill it out properly.

**Comment by azev** [comment]
How do you figure it is a bug or a question?

**Comment by Akemi** [comment]
> Don't ask questions about issues, errors or **problems** you have and instead open
> a proper issue with the right template from the previous selection.
> 
> This template is meant for questions about the workings of mpv, to clarify about
> unspecified behaviour of options or command, or anything else that is not well
> described and needs clarification.

the first sentence of the question template is quite clear. you have a problem, so you have an issue. also you were just kindly asked to open an issue. so please do just that instead of questioning our request.

**Comment by azev** [comment]
> 
> 
> > Don't ask questions about issues, errors or **problems** you have and instead open
> > a proper issue with the right template from the previous selection.
> > This template is meant for questions about the workings of mpv, to clarify about
> > unspecified behaviour of options or command, or anything else that is not well
> > described and needs clarification.
> 
> the first sentence of the question template is quite clear. you have a problem, so you have an issue. also you were just kindly asked to open an issue. so please do just that instead of questioning our request.

bite me

**Comment by Akemi** [comment]
sry, i would rather keep my distance in the times of corona.
