### ISSUE TITLE
Temporarily Black screen after changing desktop

### ISSUE THREAD

**Issue by motorto** [mpv-player/mpv#8104]
### Important Information

Provide following Information:
- mpv version  0.32.0
- Void Linux with kernel version 5.8.10_1 (Linux Distribution and Version)
- Packaged by distribution (Source of the mpv binary)
- dwm , 6.2 (Window Manager and version)
- Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (lspci -nnk,output). i915(libva-intel-driver)
Can't precise the integrated graphics card , if someone know how, and if its necessary please tell me how.

### Reproduction steps

Simply open any file with mpv , change to desktop 2  , return back to desktop 1 , and I get temporarily a black screen  and  a warning on the shell saying:
> [   4.503][w][cplayer] Audio/Video desynchronisation detected! Possible reasons include too slow
> [   4.503][w][cplayer] hardware, temporary CPU spikes, broken drivers, and broken files. Audio
> [   4.503][w][cplayer] position will not match to the video (see A-V status field).

### Log file

http://ix.io/2ybW

I have tried adding hwdec=auto to my mpv.conf but that didn't solve the issue. Don't know what I am doing wrong.

Checking the logs I see this error message:

> [ffmpeg/video] hevc: No support for codec hevc profile 1.

and a bit further down the logs it falls back to software decoding , that might be the issue

> [vd] Falling back to software decoding.

**Comment by wm4** [comment]
Does this happen with any other WM?

**Comment by motorto** [comment]
Tried with xfce4 , and couldn't recreate it...

Adding a composer to dwm might help ? 

The interesting part is that on xfce4 mpv didn't fallback to software
decoding ...
