### ISSUE TITLE
(mpv,macos) error > Assertion failed: (group_index >= 0), function m_config_cache_alloc_internal,...

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#8106]
### Important Information

Provide following Information:
- mpv version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 20 12:38:09 CEST 2020
ffmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
ffmpeg version: 4.3.1

- macOS Version

10.11.6

- Source of the mpv binary or bundle

MacPorts

### Reproduction steps

mpv build correctly (am assuming),
but playback would fail with error

`Assertion failed: (group_index >= 0), function m_config_cache_alloc_internal, file ../options/m_config.c, line 1461.
Abort trap: 6`

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior

play normally

### Actual behavior

no play

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5252481/mpv.log)

**Comment by wm4** [comment]
Needs a backtrace. Closing until then, because it's not actionable.

**Comment by mrkapqa** [comment]
what is backtrace?^

**Comment by mrkapqa** [comment]
what is backtrace?^

**Comment by mrkapqa** [comment]
mpv --no-config /Users/rich/Desktop/Hare\ Krishna\ Hare\ Rama\ Maha\ Mantra.mp4 
 (+) Video --vid=1 (*) (h264 480x360 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
Assertion failed: (group_index >= 0), function m_config_cache_alloc_internal, file ../options/m_config.c, line 1461.
Abort trap: 6

**Comment by avih** [comment]
Please post the actual log, i.e. the complete file which mpv writes when you add `--log-file=mylog.txt` .

**Comment by mrkapqa** [comment]
https://pastebin.com/G7StbRU9

**Comment by Akemi** [comment]
the backtrace is the report you get from macOS when clicking the Report Button on the crash dialogue window.

![how-to-read-crash-reports-1](https://user-images.githubusercontent.com/680386/93721106-fbb31700-fb8d-11ea-8cc2-566494f82643.png)

**Comment by mrkapqa** [comment]
Thanks, the app from mpv.io (Stolendata build) has no issue here.
the build i am refering to is from MacPorts and was evoked from terminal;
please see the pastebin, it says something of 

[ 0.040][v][vo/gpu/opengl] Initializing GPU context 'cocoa'

**Comment by mrkapqa** [comment]
Thanks, the app from mpv.io (Stolendata build) has no issue here.
the build i am refering to is from MacPorts and was evoked from terminal;
please see the pastebin, it says something of 

[ 0.040][v][vo/gpu/opengl] Initializing GPU context 'cocoa'

**Comment by Akemi** [comment]
you usually get this with the binary on the terminal too.

**Comment by mrkapqa** [comment]
thanks, that has not been the case.
doublecomment has been corrected (older firefox build was accomplice)
