### ISSUE TITLE
Add support for automatically having OSC visible on pause.

### ISSUE THREAD

**Issue by KarukSophia** [mpv-player/mpv#8107]
Hi, it would be nice for an option that allows the bottom bar to be visible when the video is paused. I think the easiest way to do this would be to add it to the OSC visibility cycle:

### Expected behavior of the wanted feature
Cycling between OSC visibility should include the option of showing it when video is paused.
### Alternative behavior of the wanted feature
Only allows cycling between never / auto (mouse-move) / always
### Log file
None

**Comment by avih** [comment]
> I think the easiest way to do this...

No. The easiest way is that you use a script similar to this one:
```lua
mp.observe_property("pause", "bool", function(name, val)
    mp.commandv("script-message", "osc-visibility", val and "always" or "auto")
end)
```

However, I _think_ there's currently a bug in mpv which sometimes prevents it from becoming visible when pausing.

**Comment by oe-d** [comment]
> However, I _think_ there's currently a bug in mpv which sometimes prevents it from becoming visible when pausing.

Yeah, that happens on windows.
> ```lua
> mp.observe_property("pause", "bool", function(name, val)
>     mp.commandv("script-message", "osc-visibility", val and "always" or "auto", "no-osd")
>     mp.osd_message(" ", 0.001)
> end)
> ```

**Comment by KarukSophia** [comment]
Thanks, both of you, this works great! I was tinkering around with trying to remove the osd message yesterday but it would not work properly. @oe-d I wonder why the `mp.osd_message(" ", 0.001)` is needed? I tried removing it, but the OSC would not always show up on pause without it.

**Comment by KarukSophia** [comment]
To be clear it works perfectly if I include it.

**Comment by oe-d** [comment]
Graphics sometimes doesn't render if the player is paused and there's no mouse movement or osd messages. Clicking the mute icon when paused doesn't update the graphic until you move the mouse or unpause. It can be done though, as [uosc ](https://github.com/darsain/uosc) renders when paused.

**Comment by oe-d** [comment]
This won't block the default osd.
```
mp.observe_property("pause", "bool", function(name, val)
    mp.commandv("script-message", "osc-visibility", val and "always" or "auto", "no-osd")
    overlay = mp.create_osd_overlay("ass-events")
    overlay:update()
    mp.add_timeout(0.05, function() overlay:remove() end)
end)
```

**Comment by KarukSophia** [comment]
Thank you, I'll try using that, I'm closing this now.

**Comment by sdasda7777** [comment]
Hi, I'd like to use this feature. Where should I place the code to achieve this?

**Comment by guidocella** [comment]
In mpv.conf:

```
[pause]
proflle-cond=pause
profile-restore=copy
script-opt=osc-visibility=always
```

**Comment by sdasda7777** [comment]
I'm sorry, but I'm a complete newbie. The `mpv.conf` should be located in `portable_config/`? And where do I put the code that's provided above? The `mpv.conf` by itself doesn't appear to work for me.

**Comment by sdasda7777** [comment]
Oh, I think the config you provided has a slight typo, should be `profile-cond`. Placing that into `portable_config/mpv.conf` does indeed work without any need for scripting. Thank you!
