### ISSUE TITLE
With nvidia proprietary driver wake up from suspend cause to render memory garbage in the video area

### ISSUE THREAD

**Issue by aaronrancsik** [mpv-player/mpv#8110]
### Important Information

_Sorry if duplicate I don't find it anywhere_

With nvidia proprietary driver wake up from suspend cause to render memory garbage in the video area.
This is known in nvidia documentation:
[nvidia doc](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/powermanagement.html)

Update:
If I continue the playing this glitch disappearing, as far as I know a re-render needed to resolve it 

Provide following Information:
- mpv version 
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100 (runtime 56.51.100)
   libavcodec      58.54.100 (runtime 58.91.100)
   libavformat     58.29.100 (runtime 58.45.100)
   libswscale      5.5.100 (runtime 5.7.100)
   libavfilter     7.57.100 (runtime 7.85.100)
   libswresample   3.5.100 (runtime 3.7.100)
ffmpeg version: n4.3.1
```
- Linux Distribution and Version
`5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux`
- Source of the mpv binary
Official repo
- Window Manager and version
GDM 3.36.3
X11
- GPU driver and version
nvidia proprietary 450.66  
- Possible screenshot or video of visual glitches
![image](https://user-images.githubusercontent.com/20153302/93889725-d6d3b680-fce9-11ea-865f-4dc25dcdf75c.png)

### Reproduction steps
1. Start mpv, play some video
2. Pause the video
3. Suspend your computer
4. Wake up from suspend

### Expected behavior
Re-render the video area without memory garbage
### Actual behavior
You get memory garbage in the video area

### Log file
[log after reproduction steps](https://0x0.st/ilw2.txt)

**Comment by Dudemanguy** [comment]
Are you using wayland by any chance? (this is why we ask people to attach a log).

**Comment by aaronrancsik** [comment]
> Are you using wayland by any chance? (this is why we ask people to attach a log).
> 
> Edit: Oh, I guess probably not since there are window manager decorations.

Sorry, yes, it is X11

**Comment by wm4** [comment]
I remember how nvidia corrupted textures for me after suspend/resume, if they were also mapped as PBOs. That was years ago.

**Comment by philipl** [comment]
I know that nvdec doesn't seem to be able to recover after suspend/resume except by completely reinitialising the decoder. They have some sort of texture dump to system ram as part of their suspend handling these days, but I don't know how transparent that is.

**Comment by wm4** [comment]
vdpau had an explicit "preemption" event after which the API could not be used anymore and had to be reinitialized. It happened on VT switching and suspend/resume. It was a fucking PITA.

**Comment by Akemi** [comment]
seems like an upstream nvidia issue.
