### ISSUE TITLE
Questions about BT2390 tone-mapping

### ISSUE THREAD

**Issue by wchen61** [mpv-player/mpv#8111]
Hi, @haasn 
I have questions about BT2390 tone-mapping when I read the glsl code with -v -v -v option with 450nit.

`color.rgb = cms_matrix * color.rgb;
 float cmin = min(min(color.r, color.g), color.b);
 if (cmin < 0.0) { float luma = dot(dst_luma, color.rgb); float coeff = cmin / (cmin - luma); color.rgb = mix(color.rgb, vec3(luma), coeff); }
 float cmax = max(max(color.r, color.g), color.b);
 if (cmax > 1.0) color.rgb /= cmax;

 color.rgb *= vec3(0.451111);
 // delinearize
 color.rgb = clamp(color.rgb, 0.0, 1.0);
 color.rgb *= vec3(1.000000);
 color.rgb = pow(color.rgb, vec3(1.0/2.2));
 out_color = color;`

In the GLSL shader code, the color conversion seems works on linear color space, and then apply gamut clipping directlly?
After gamut clipping and divide by dst_range（450nit）, the value should less than 1 for delinearize?

Am I right to understand that？

### Log file
[BT2390_450nit.txt](https://github.com/mpv-player/mpv/files/5265319/BT2390_450nit.txt)

**Comment by haasn** [comment]
The snippet you're pasting/analyzing happens after BT.2390 tone-mapping is already done. I'm not sure what exactly you're asking. But yes, the processing is done in linear light.

**Comment by Akemi** [comment]
questions was answered.
