### ISSUE TITLE
Duplicate Screenshots Occurring with Option+S

### ISSUE THREAD

**Issue by berrygal38** [mpv-player/mpv#8112]
### Important Information
- mpv version: mpv 0.32.0
- macOS Version: Catalina 10.15.6
- Source of the mpv binary or bundle: GitHub
- Release where issue occurred: Releases after 0.29.0 have this issue

### Reproduction steps
Config file has info specified for screenshot location, compression, format, and filter and has been dropped into the location as instructed by MPV. 
Open any video file (multiple formats attempted) and move scrubber to location to begin screenshots
Hit Option+S and play to begin saving series of consecutive screenshots
Hit Option+S again to stop screenshot process
Folder designated in config file will have all recorded screenshots from session

### Expected behavior
MPV will make consecutive screenshots beginning the first time Option+S is hit and the process will end once user hits Option+S to stop it; Images will save to folder designated in config

### Actual behavior
MPV duplicates every other screenshot throughout process

###Log File
[sharempvlog.txt](https://github.com/mpv-player/mpv/files/5279832/sharempvlog.txt)
https://github.com/mpv-player/mpv/files/5279832/sharempvlog.txt

**Comment by Akemi** [comment]
post a log please. don't ignore that part of the issue template.

**Comment by berrygal38** [comment]
> post a log please. don't ignore that part of the issue template.

I have attached a log file, hopefully the correct way.

**Comment by Akemi** [comment]
seems like you didn't load any file and you didn't attempt to make any screenshots, or you log is incomplete.

**Comment by berrygal38** [comment]
[shareLog.txt](https://github.com/mpv-player/mpv/files/5285873/shareLog.txt)
I've tried it again

**Comment by Akemi** [comment]
i can't reproduce your issue and from you log it looks fine. for testing use `mpv av://lavfi:testsrc --no-config --screenshot-template='mpv_(%wH-%wM-%wS.%wT)_%#02n`. if there are duplicate screenshots ther will be a `_2` at the end of the filename.

**Comment by berrygal38** [comment]
I'm sorry, I don't understand what you mean by using that code for testing. Do I put that in my config file?

**Comment by Akemi** [comment]
you use it on the command line/terminal.

**Comment by Akemi** [comment]
no reply.
