### ISSUE TITLE
--geometry using middle of a video instead of corner?

### ISSUE THREAD

**Issue by desudesune** [mpv-player/mpv#8114]
>x and y set the window position, measured in pixels from the top-left corner of the screen to the top-left corner of the image being displayed.

wouldn't it be easier if you used the middle point of a video as a reference to an xy coordinate instead of the corner of a video? there's so many video resolutions out there that this setting current setting we have is pretty much unusable

**Comment by Akemi** [comment]
i don't think the option should be changes in its behaviour now. also general all windowing system work with the corner of a window and not the centre. also using the centre makes it hard to place a window directly in the corner with a variable sized window.
