### ISSUE TITLE
libmpv d3d9 and d3d11 flicker

### ISSUE THREAD

**Issue by time-killer-games** [mpv-player/mpv#8118]
### Important Information

- latest libmpv at time of writing. I update my msys2 packages frequently.
- windows 10 (doesn't happen on windows 7)
- flickering on d3d9 and d3d11 rendered windows

### Reproduction steps

Unfortunately, I can not provide easy to reproduce instructions because it requires owning GameMaker Studio 1.4 (d3d9) and GameMaker Studio 2.x (d3d11) the former is no longer for sale and the latter I don't expect anyone to buy for this ticket.

I just need to know if there is some special required flag to use in combination with the window id ("wid") when working with a d3d window. I've noticed d3d9 windows from other software such as GameMaker 8.1 do not have flickering. So it really puzzles me what is causing it and i really wish i had more details i could give that would make reporting this issue easier to solve.

I don't have this issue on Linux, so i assume it's a d3d issue.

I'm using libmpv my source code is here - https://github.com/time-killer-games/libvidplayer

**Comment by wm4** [comment]
"wid" and "d3d window" sound like they would conflict indeed. You would probably need to use d3d on windows around the window passed to wid only, so they don't overlap. But I don't know enough about window's internal compositor.
The only other choice is changing your code to use the render API. The render API is currently OpenGL-only, so to integrate with d3d you'd need to write complicated ANGLE glue code. Or maybe you could use the new software rendering render API, then you'd need to write probably less complicated glue code to render into a memory array and upload and display that as texture (will likely still be slower than direct rendering, at least for large resolutions).

**Comment by time-killer-games** [comment]
I'm closing this as there appears to be no easy solution and I will need to try what you recommended, that's good enough. 

Thanks for the info!
