### ISSUE TITLE
youtube-dl failed: not found or not enough permissions

### ISSUE THREAD

**Issue by fifa87** [mpv-player/mpv#8119]
- mpv 0.32.0-603-gb5368980a8
- Android  (9.0),arm64-v8a

### Reproduction steps

I tried to play youtube url.
But it failed.
I copied asset files for youtube-dl correctly

D window player: copied "/data/user/0/com.*/files/.config/mpv/cacert.pem" true
D window player: copied "/data/user/0/com.*/files/.config/mpv/youtube-dl" true
D window player: copied "/data/user/0/com.*/files/.config/mpv/subfont.ttf" true
D window player: copied "/data/user/0/com.*/files/.config/mpv/ytdl/python3" true
D window player: copied "/data/user/0/com.*/files/.config/mpv/ytdl/python38.zip" true
D window player: copied "/data/user/0/com.*/files/.config/mpv/ytdl/youtube-dl" true

and ytdl property was set as "yes"
mpvSetProperty("ytdl", "yes");

I think youtube-dl was found correctly. but it failed to run.

D window player: mpv log: "config path: 'youtube-dl' -> '/data/user/0/com.*/files/.config/mpv/youtube-dl'"
D window player: mpv log: "found youtube-dl at: /data/user/0/com.*/files/.config/mpv/youtube-dl"
D window player: mpv log: "Running: /data/user/0/com.*/files/.config/mpv/youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=inMD4svYnXQ"
D window player: mpv log: "Run command: subprocess, flags=64, args=[args=\"/data/user/0/com.*/files/.config/mpv/youtube-dl,--no-warnings,-J,--flat-playlist,--sub-format,ass/srt/best,--format,bestvideo+bestaudio/best,--all-subs,--no-playlist,--,https://www.youtube.com/watch?v=inMD4svYnXQ\", playback_only=\"yes\", capture_size=\"67108864\", capture_stdout=\"yes\", capture_stderr=\"yes\"]"
D window player: mpv log: ""
D window player: mpv log: "youtube-dl failed: not found or not enough permissions"
D window player: mpv log: "finished playback, unrecognized file format (reason 4)"
D window player: mpv log: "Failed to recognize file format."

I will upload detail log txt file.
[log.txt](https://github.com/mpv-player/mpv/files/5287686/log.txt)

Please help me to fix this issue. It is very urgent.
Best Regards.

**Comment by indcomp07** [comment]
Urgently need solution to same issue.

**Comment by CounterPillow** [comment]
How urgently? Is an airplane about to crash because of it?

**Comment by indcomp07** [comment]
Sorry I never meant that, but client will reject the project. The problem is happening in some devices not all.

**Comment by CounterPillow** [comment]
Since I assume you're getting paid for this it might be a good idea to investigate this yourself, as I doubt any existing mpv contributors run youtube-dl on Android.

**Comment by indcomp07** [comment]
Thanks CounterPillow, i tried my level best 2 months back, i failed. I am currently using web view. But At least someone(fifa87) more is getting same issue.

**Comment by Akemi** [comment]
this doesn't seem like our problem. maybe environment related. also the youtube-dl hook has a config option to set the path (ytdl_path). it's probably worth setting it to a absolute path for testing.
