### ISSUE TITLE
unix-terminal: input buffered after bg; fg

### ISSUE THREAD

**Issue by guidocella** [mpv-player/mpv#8120]
### Important Information

- mpv version: 0.32.0-747-g5e4ec15e6c
- Linux Distribution and Version: Arch Linux, Linux 5.8.10
- Source of the mpv binary: self compiled
- If known which version of mpv introduced the problem: it has been present since at least version 29.1 which is the earliest I used
- Window Manager and version: zsh 5.8 or bash 5.0.018 on the Linux console, X11 and Wayland; I assume it's also on MacOS

### Reproduction steps

- Play something from the terminal
- Press Ctrl-Z
- Execute `bg`
- Execute `fg`
- Press keybindings other than Enter

### Expected behavior

mpv immediately reacts to every keybinding

### Actual behavior

mpv buffers input until you press Enter

This is because `osdep/terminal-unix.c` clears `ICANON` only in the `SIGCONT` handler, but executing `fg` after `bg` doesn't send it:

Ctrl-Z; fg (sends `SIGCONT`)
Ctrl-Z; bg (sends `SIGCONT`); fg (doesn't send `SIGCONT`)

This isn't a big deal since I've worked around it by using
`f() { kill -TSTP %mpv && sleep .01 && fg %mpv }`
instead of `fg`, but I wonder if there's a way to detect `fg` calls or being unable to is just a terminal limitation. I can't think of any similar CLI application accepting keyboard input without using curses to see if they have the same issue.

### Log file

https://0x0.st/iU97.txt this is an example of a foregrounded mpv responding to several seek commands all at once only after pressing enter.

**Comment by wm4** [comment]
Doesn't seem to be a recent regression. I think the problem is that there's no way to be notified of this, and mpv removed terminal polling at some time. (Polling as in actively checking the state after a small timeout, in a loop.)

**Comment by h1z1** [comment]
Can't duplicate this with bash 4.2.46

**Comment by guidocella** [comment]
It's not a window, I'm talking about playing in the terminal.

**Comment by h1z1** [comment]
Do you mean _console_ ? ie outside X entirely?  Still couldn't duplicate it.

**Comment by guidocella** [comment]
It doesn't actually matter if there's a window, the bug is about sending input to mpv through the terminal, not through the window which has nothing to do with `ICANON`. Either open a video and then switch back to the terminal, or play music with `--audio-display=no`.
The only similar CLI application that came to my mind is mplayer, but that behaves even worse since just Ctrl+Z `fg` makes it buffer input.

**Comment by avih** [comment]
mpv probably needs to catch signal SIGTTOU and/or SIGTTIN, and try to init the terminal on every followup write attempt until such init succeeds, or some such. It needs some thinking, but should be possible with some work.

For now mpv doesn't do that. You can send a PR if you feel like working on it.

**Comment by guidocella** [comment]
> mpv probably needs to catch signal SIGTTOU and/or SIGTTIN, and try to init the terminal on every followup write attempt until such init succeeds, or some such. It needs some thinking, but should be possible with some work.
> 
> For now mpv doesn't do that. You can send a PR if you feel like working on it.

I looked up those signals and they are sent when a background process attempts to write to or read from the terminal. How can they help if the issue occurs when mpv is in the foreground?

**Comment by h1z1** [comment]
> It doesn't actually matter if there's a window, the bug is about sending input to mpv through the terminal,

Then it was as I thought originally and I can't duplicate it unless...   For shits, are you using the default bindings?

**Comment by avih** [comment]
> I looked up those signals and they are sent when a background process attempts to write to or read from the terminal. How can they help if the issue occurs when mpv is in the foreground?

That mpv can detect that it's at the background, which means it tries to re-init the terminal (disable input buffering) until it succeeds - which would hopefully happen once it comes to the foreground again.
