### ISSUE TITLE
C-style cast between mpv_handle * and unsigned long long

### ISSUE THREAD

**Issue by time-killer-games** [mpv-player/mpv#8122]
Since pointers are implementation defined, I was wondering if a c-style cast to and from a mpv_handle * and unsigned long long was a safe thing to do? I'm updating my code so that it doesn't do this anymore just in case, but I was just curious.

Edit:

Not sure why this was tagged feature request, i selected "ask a question"...

Thanks!
Samuel

**Comment by paulguy** [comment]
Would intptr_t be a better choice?

**Comment by time-killer-games** [comment]
I wouldn't be the one to answer that, I have no idea.
