### ISSUE TITLE
default-track flag is ignored in case of forced-track flag

### ISSUE THREAD

**Issue by pcroland** [mpv-player/mpv#8123]
### Important Information
`--default-track 0:yes` flag will be ignored in case of `--forced-track 0:yes` flag.

- mpv version: 20200920
- Platform and Version: Win 10 2004
- Source of the mpv binary: updater.bat

### Reproduction steps
Change the file so the subtitle has `forced-flag` enabled:
`mkvpropedit input.mkv -e track:s1 -s flag-forced=1`

### Expected behavior
The track with `default-track=1` should be enabled when starting the file.

Tracks with `forced-track=1` should be enabled when you switch to an audio with the same language (e.g: you change the language from English to Spanish, the Spanish forced subtitle will be enabled)
or just ignore the `forced-track` flag completely (this is what most player does)

### Sample file
https://x0.at/S6T.mkv

**Comment by Dudemanguy** [comment]
As of git master, this is essentially the behavior. If there is a forced sub track and the audio language is the same as the forced sub, by default the forced sub will be selected over the default sub track.
