### ISSUE TITLE
Wayland backend does not set an opaque region

### ISSUE THREAD

**Issue by rmader** [mpv-player/mpv#8125]
### Important Information

Provide following Information:
- mpv version: 0.32.0
- Linux Distribution and Version: Fedora 32
- Source of the mpv binary: rpmfusion-free-updates
- If known which version of mpv introduced the problem: no
- Window Manager and version: Mutter/Gnome-Shell 3.38 (master)
- Possible screenshot or video of visual glitches:

Gnome 3.38 introduced a debug color overlay for opaque regions. Wayland compositors can determine whether a region is opaque either from the texture format (does it have an alpha channel?) or by a client hint (`wl_surface_set_opaque_region`, see [spec](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface)). `mpv` apparently does not yet set a opaque region.
![Screenshot from 2020-09-30 22-50-02](https://user-images.githubusercontent.com/6313774/94752076-751ae880-038a-11eb-9d69-1661c5ac2121.png)
![Screenshot from 2020-09-30 22-49-23](https://user-images.githubusercontent.com/6313774/94752072-73e9bb80-038a-11eb-96c0-088986c8cee5.png)

### Reproduction steps
 - run GS 3.38
 - `alt`+`f2` -> `lg` -> `Meta.add_debug_paint_flag(Meta.DebugPaintFlag.OPAQUE_REGION)`
 - run `mpv`

### Expected behavior
`mpv` should have a green overlay, indicating an opaque surface/buffer

### Actual behavior
`mpv` has a purple overlay, indicating a non-opaque surface/buffer

### Why should you care?
Setting the opaque region allows some major optimizations in Wayland compositors. The obvious one is the rendering pipeline, which often can use fast paths. The other is culling and frame callbacks, i.e. not sending frame callbacks to completely obscured surfaces. Both can, depending on the scenario, have serious impact on system performance.

**Comment by Dudemanguy** [comment]
I didn't even know this part of the spec existed honestly. Looks like a simple enough fix though.

**Comment by CounterPillow** [comment]
Just so nobody forgets this while implementing this: `--alpha=yes` (making mpv create a framebuffer with an alpha component if the input has alpha) should disable setting the hint, because otherwise fun things happen.

**Comment by rmader** [comment]
> **EDIT:** Speaking of which, wouldn't it be fine for compositors to assume that any wl_surface is opaque if it doesn't have an alpha component in the buffer used by it?

That's should already be the case, but apparently mpv does use an alpha channel by default - at least I checked with some weston test apps that Mutter properly detects them as opaque, without setting an opaque region. If you are sure mpv does not do so, I can have another look whether there's some bug in Mutter though.

**Comment by CounterPillow** [comment]
> [vo/gpu] Using FBO format rgba16f.                                                           

Yeah, looks like we apparently do create an RGBA FBO (???), this is also worth investigating on mpv's side.

**Comment by Dudemanguy** [comment]
It's worth noting that alpha is currently broken on wayland egl (and I'm not sure how to fix it other than adding a bunch of disgusting boilerplate that I don't want to do).

**Comment by rmader** [comment]
Ah alright - then setting the opaque region could be a workaround until the right format can be used.

**Comment by wm4** [comment]
You can't not have an RGB FBO without A.

**Comment by Dudemanguy** [comment]
>Just so nobody forgets this while implementing this: --alpha=yes (making mpv create a framebuffer with an alpha component if the input has alpha) should disable setting the hint, because otherwise fun things happen.

I'm not sure this actually even matters. This is just a compositor hint. I'm not sure what exactly a compositor would do with this hint other than send (or not send) frame callback based on whether or not the region is signaled as opaque. It's probably actually safer to just always consider mpv's wl_surface as opaque even if part of the buffer is technically alpha. There's no sane way to set a non-rectangular region. The worst case is that you do some extra rendering but oh well.

**Comment by rmader** [comment]
> I'm not sure what exactly a compositor would do with this hint other than send (or not send) frame callback based on whether or not the region is signaled as opaque.

In Mutter, setting the opaque region allows (additionally to frame callback reduction), to take a fast rendering path and skips rendering surfaces behind the opaque one. As of 3.38, it also enables fullscreen "unredict" automatically (direct buffer flip without compositing).

**Comment by wm4** [comment]
Is Wayland really so hilariously bad that it requires rendering any window assuming transparency by default?

**Comment by rmader** [comment]
> Is Wayland really so hilariously bad that it requires rendering any window assuming transparency by default?

If the buffer has an alpha channel, yes. But the same is true for X11, only worse.

**Comment by Dudemanguy** [comment]
>In Mutter, setting the opaque region allows (additionally to frame callback reduction), to take a fast rendering path and skips rendering surfaces behind the opaque one. As of 3.38, it also enables fullscreen "unredict" automatically (direct buffer flip without compositing).

Shouldn't any fullscreen buffer always use direct scan-out regardless of this hint or not? Well I guess I don't know how mutter works.

Anyways, it sounds like to me it's better to just always set the entire mpv surface as opaque regardless.

**Comment by rmader** [comment]
> Shouldn't any fullscreen buffer always use direct scan-out regardless of this hint or not? Well I guess I don't know how mutter works.

No, and that's true for all compositors that follow the spec (and also X11, when using a compositor). But I guess it shouldn't be such a hassle to use a alpha-less buffer with EGL :/

**Comment by wm4** [comment]
No, on X11 you have to work "hard" to get a configuration with an alpha channel in the first place. I know because I've implemented --alpha for x11.
On the other hand, wayland (at least with EGL) does not seem to have such hints, and you just get a framebuffer config with alpha, which is ?????.
As far as native texture/FBO formats go, RGB only formats are a corner case that is slow and doesn't even exist on Vulkan, while normally you use RGBA to get RGB even if you don't need alpha. That's probably because 3 bytes per pixel is a slow mess on CPUs, and apparently even on GPUs.

**Comment by rmader** [comment]
AFAIK the Wayland spec requires every compositor to support XRGB, which would be opaque.

**Comment by CounterPillow** [comment]
> RGB only formats are a corner case that is slow and doesn't even exist on Vulkan

Yeah, I've just wasted my time writing a patch that only chooses the rgba formats if alpha is enabled and apparently RADV does not like this.

I guess the best solution then is to just set the entire window as opaque unless `--alpha=yes`, so we can continue using rgba FBOs.

**Comment by rmader** [comment]
> I guess the best solution then is to just set the entire window as opaque unless `--alpha=yes`, so we can continue using rgba FBOs.

Sound reasonable - it could be done together with the input region.

FTR, this is the list of currently supported formats in Mutter: https://gitlab.gnome.org/GNOME/mutter/-/blob/9b9b912765f49553849e8c8aca7d2a75692ca9cc/src/wayland/meta-wayland-dma-buf.c#L690-698

**Comment by wm4** [comment]
XRGB isn't a thing in EGL. EGL is confusing and (apparently) doesn't have the concept of alpha channels. So whatever.
(PS: fuck EGL.)

**Comment by rmader** [comment]
> No, on X11 you have to work "hard" to get a configuration with an alpha channel in the first place. I know because I've implemented --alpha for x11.

Apparently using alpha channel becomes more and more common (I'm thinking of Firefox with Webrender, GTK4, probably QT), partly because of CSD etc. So "modern" X11 pretty much works the same as Wayland there, with the main difference of things not being atomic - and, yes, it's more annoying to get the right Xvisual. AFAIK that's also in line with other OS compositors / toolkits.

**Comment by wm4** [comment]
Well, my point is that on X11, you explicitly have to request alpha. Having to use netwm to make this efficient is orthogonal, and not very surprising.
While on wayland, you get alpha even if you didn't want it.
Does wayland at least specify whether alpha is straight or premultiplied?

**Comment by rmader** [comment]
Follow up on the situation on X11 and Wayland in combination with EGL: the relevant discussions apparently happened at https://bugs.freedesktop.org/show_bug.cgi?id=67676 and https://gitlab.freedesktop.org/mesa/mesa/-/issues/149

In short: in the moment there's no way to communicate within EGL whether you need a format that will be transparent or opaque for compositors. So they needed to decide what they give to everyone and ended up going for opaque on X11 transparent on Wayland, with no (reasonable) way to change that. With GLX in turn this worked well. So to conclude: it's not about X11 or Wayland, it's just about EGL being limited here :/

**Comment by wm4** [comment]
wayland is shit

**Comment by christianrauch** [comment]
> Is Wayland really so hilariously bad that it requires rendering any window assuming transparency by default?

Not sure what you mean here. The alpha channel depends on which EGL configuration you request (i.e. if `EGL_ALPHA_SIZE` is set), right? I don't see how you are forced to use an alpha channel. You can easily request an XRGB buffer by not requesting an alpha channel in your EGL configuration.

> No, on X11 you have to work "hard" to get a configuration with an alpha channel in the first place.

Maybe this is because no-one thought of transparency 35 years ago? :-)
