### ISSUE TITLE
what is different: mpv.conf vs input.conf, comparison..?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#8126]
hi

im read manual but im not clear , what is different configuration:
file mpv.conf    input.conf ?

what not work in mpv.conf and input.conf  ?
what is work in mpv.conf  and  input.conf  ?
this mpv is very helpfully

**Comment by emanuele6** [comment]
In `mpv.conf`, you set settings, e.g.
```conf
loop-file=inf
volume=60
```

In `input.conf`, you bind `mpv` command to key combinations, e.g.:
```conf
# press h to know what time it is.
h show-text "hello, it is ${clock}"
# press = to reset the speed
= set speed 1.0
```

**Comment by manuelsongokuh** [comment]
mpv.conf = change the default to modify user, instead input use for keyboard key..?

wow potential MPV
