### ISSUE TITLE
[FR] Add auto-save current position to be able to resume in case of crash

### ISSUE THREAD

**Issue by NightMachinary** [mpv-player/mpv#8128]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

I know about `save-position-on-quit`, but it only works if mpv quits normally, but I sometimes lose my mpv sessions to sudden restarts that don't allow mpv to quit properly. Having an option to save the current position every 30 seconds would solve this. I'm also open to using a Lua plugin for this, but I haven't studied the docs for that, so if someone can help me, that'd be appreciated.

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Akemi** [comment]
from our wiki https://github.com/mpv-player/mpv/wiki/User-Scripts:

https://github.com/AN3223/dotfiles/blob/master/.config/mpv/scripts/auto-save-state.lua
https://gist.github.com/Hakkin/5489e511bd6c8068a0fc09304c9c5a82

**Comment by hell1231** [comment]
> from our wiki https://github.com/mpv-player/mpv/wiki/User-Scripts:
> 
> https://github.com/AN3223/dotfiles/blob/master/.config/mpv/scripts/auto-save-state.lua https://gist.github.com/Hakkin/5489e511bd6c8068a0fc09304c9c5a82

how to add them to mpv palyer?
i'm non programmer...
