### ISSUE TITLE
bug: speed -1.0

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#8129]
### Important Information

Provide following Information:
- mpv version mpv 0.32.0+git.20200525T015437.b83bdd1d17
- Linux Distribution and Version : opensuse 15.2 64bit kde
- Source of the mpv binary mpv 0.32.0+git.20200525T015437.b83bdd1d17
### Reproduction steps

i add command in input.conf:
h add speed 1.0
g add speed -1.0

open mpv and press h ,h ,h (works speed video) but i press g,g,g (works) but until 0.01 video is frozen, i press h result 1.01,2.01 (works)  but why 0.01? maybe is bug 0.01?

**Comment by wm4** [comment]
not bug

**Comment by CounterPillow** [comment]
Why would it be a bug? Did you expect the speed to go 0.0? There's a pause button for that. Playback speed is limited to 0.01 intentionally: https://github.com/mpv-player/mpv/blob/dcec6d9556c6cfca11b865442174479096f55111/options/options.c#L542

**Comment by Akemi** [comment]
there is also backspace to reset the speed.
