### ISSUE TITLE
Use title from PLS playlist format

### ISSUE THREAD

**Issue by smhmd** [mpv-player/mpv#8133]
Using a [PLS file](https://en.wikipedia.org/wiki/PLS_(file_format)) as a playlist, I have something like this:
```yml
[playlist]

File1=https://example.com/file.mp4
Title1=Example video
```
Of 300 videos or so. The URLs themselves have generic titles. Is there a way to force playlist to use `Titles`?
![image](https://user-images.githubusercontent.com/46059092/94885539-6145b400-0468-11eb-8571-733a198bb464.png)

**Comment by Akemi** [comment]
with m3u playlist and the #EXTINF tag it should work, i believe.
