### ISSUE TITLE
HEVC hardware decoding breaks after seeking (only for .ts files)

### ISSUE THREAD

**Issue by jhelgert** [mpv-player/mpv#8143]
### Important Information
- mpv version: 0.32.0 
- ffmpeg version: 4.3.1
- macOS Version: 10.15.7
- Source of the mpv binary or bundle: Installed via homebrew

### Reproduction steps

``` bash
mpv --no-config --hwdec=videotoolbox out.ts
```

### Expected behavior

HEVC hardware decoding should still work for .ts and .mkv files after seeking.

### Actual behavior

Strangely, for *.ts files the hevc hardware decoding breaks after seeking with the OSD or the trackpad gesture and the cpu usage increases drastically.

### Log file

Log file for the ts file: https://0x0.st/i0ah.txt
Log file for the mkv file: https://0x0.st/i0a7.txt

### Sample files

[Here's a HEVC recording from my vdr (.ts file)](https://0x0.st/i0aD.ts). [And here's the same video as mkv](https://0x0.st/i0a5.mkv).

The mkv file was obtained with:
``` bash
ffmpeg -i out.ts -vcodec copy -acodec copy out.mkv
```

If needed, I could provide more samples. It's exactly the same for other recorded 4k channels with hevc codec.

**Comment by Akemi** [comment]
one is using our internal mkv demuxer and the other one uses the lavf. i guess that is the problem and that would make it an upstream problem, eg ffmpeg?

**Comment by Akemi** [comment]
on a side note. it works for me without falling back to th sw decoder. try increasing the size of the **--vd-lavc-software-fallback=** option. default is 3. also see the manual.

**Comment by Akemi** [comment]
did that option solve your problem? if yes, you can close this issue.

**Comment by jhelgert** [comment]
Yes, works fine with `--vd-lavc-software-fallback=120`. Thanks!
