### ISSUE TITLE
Support for language variants, such a regions or countries

### ISSUE THREAD

**Issue by mugiritsu** [mpv-player/mpv#8144]
### Expected behavior of the wanted feature
Being able to set the preferred variant of a certain language. This is useful for pople who follow release groups who have members of many countries and release various alternative tracks of the same language.

**Usage examples:**
Preferring Canadian French over European French:
`slang=fr-CA,fr-FR`

Preferring Simplified Chinese over Traditional Chinese:
`slang=zh-CN,zh-TW`

Preferring Latin-american or Mexican Spanish over European Spanish. If there's no Spanish tracks available, prefer english tracks:
`slang=es-419,es-MX,es,es-ES,en-US,en,en-GB`

Could also work with honorific tracks:
`slang=en-US,en,en-JP,es-AR,es-JP`

And subtitles/audio tracks for people with certain impediments:
`slang=sgn-FSL,sgn-ES,sgn-US` (sign languages)
`slang=en-simple,en-US,en,es-simple,es-MX,es`
`alang=en-simple,en-US,en,es-simple,es-MX,es`

Recent versions of MKVToolNix support these language tags:
![mkvtoolnix-gui_UzqUOoHDyq](https://user-images.githubusercontent.com/53368149/95036739-1a350a00-0686-11eb-8970-1e91cca0387e.png)

![mkvtoolnix-gui_CSp079F2TA](https://user-images.githubusercontent.com/53368149/95036823-549ea700-0686-11eb-89fa-b05200cdf015.png)

**Comment by v-fox** [comment]
But isn't that what it already does ? I've been using smplayer's settings for that and not sure if it's any different than directly configuring mpv. What would be an improvement, however, is if mpv would always match recognized language (or closest language group, like "any dialect of English" or "any dialect of Chinese" if exact one is not found but unless exact matching order is specified: like "en_GB,en_US,ru" would mean "prefer British then US but use any English if those are absent, then search for Russian") despite exact container format based on it own format, system format (like `locale`) or any of container formats. Not sure which way would be better.

**Comment by mugiritsu** [comment]
Seems like the old `language-country` tag is deprecated and never got any support from popular muxing tools. But this new matroska spec supports the IETF BCP 47 standard, wich is much more flexible for the purposes described above.

Also, since the classic language tag and the new IETF language tag are independent from each other, they can coexist without any problem. 

![image](https://user-images.githubusercontent.com/53368149/95304934-907e6b80-0842-11eb-82a5-15a15219ff8a.png)

A nice aproach, that also could solve the issue you commented, could be something like this:

alang=eng,fre
alocale=en-US,fr-CA,en-GB

slang=spa,eng
slocale=es-JP,es-419,es-MX,es-ES,en-JP,en-US,en-GB

**Comment by KucharczykL** [comment]
Would be good to support displaying language variants at least for the most common ones like differenting between traditional and simplified Chinese. There's an English description listed in https://unicode.org/iso15924/iso15924-codes.html but I'm not sure if any libraries and tools have access to that.
