### ISSUE TITLE
mpv cannot play, with default settings, contents from sites that reject range requests

### ISSUE THREAD

**Issue by PCigales** [mpv-player/mpv#8145]
By default, for http or https addresses, mpv sends a request with a range header ('Range': 'bytes=0-') to access the content. The problem is that some servers reject such requests sending a 406 error code rather than just replying with a 200 status code instead of a 206 status code, not complying with HTTP specifications. It is the case of several DLNA servers, among which Microsoft media server for transcoded contents.
The workaround is to test the address before launching mpv to determine whether the site accepts partial requests or not, and if it not the case, add a 'stream-lavf-o' option set at {"seekable":"0"}. This option cannot be used by default as it disables seeking in the content. This solution works, but it adds latency and increases the processing time.
Maybe mpv could fall back to this option automatically by itself when opening an http/https address fails with a 406 error code ?
Thanks.

**Comment by wm4** [comment]
That's not how http works. The rest is up to libavformat, which contains the http code.

**Comment by PCigales** [comment]
I totally agree with you, that is the way things should go.

**Comment by wm4** [comment]
What I'm saying is, the work around should be in libavformat. I don't even know if you can get the http status code from the API. An alternative might be a curl backend for mpv.

**Comment by garoto** [comment]
Not ideal I guess, but probably can be worked around with an `auto-profiles` condition. I used to have a broken httpd that would return an impossible number in response to ffmpeg's `Range: bytes=0-` initial request and I worked that around by setting `stream-lavf-o-set=seekable=1` via profile.
