### ISSUE TITLE
Core dump on Manjaro Unstable branch.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8150]
### Important Information

Provide following Information:
- mpv version
v0.32.0.754.g015b676875-1
- Linux Distribution and Version
Manjaro Unstable Branch
- Source of the mpv binary
AUR
- If known which version of mpv introduced the problem
git version
- Window Manager and version
Mutter 3.38.1-1
- GPU driver and version
Driver version: Mesa Gallium driver 20.2.0 for Radeon RX 580 Series (POLARIS10, DRM 3.38.0, 5.8.13-4-MANJARO, LLVM 10.0.1)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
It plays the video
### Actual behavior
It crashes.
### Log file

https://0x0.st/i03f.txt

### Sample files

Every video.

**Comment by laichiaheng** [comment]
@Akemi By the way, it happens under X11

**Comment by Dudemanguy** [comment]
Is this one of AMD's driver regressions?

**Comment by CounterPillow** [comment]
No, this is one of your regressions, namely https://github.com/mpv-player/mpv/pull/8146#discussion_r500809522 (if we had a backtrace of this, then that would confirm it)

**Comment by Dudemanguy** [comment]
If it happens under X11, then that's not related.

**Comment by CounterPillow** [comment]
Did you even read the log?

```
[   1.812][v][vo/gpu] Probing for best GPU context.
[   1.812][v][vo/gpu/opengl] Initializing GPU context 'wayland'
[   1.812][w][vo/gpu/wayland] Display socket (null) not found/unavailable! Falling back to NULL!
```

**Comment by Dudemanguy** [comment]
`wl_display_connect` already tried to connect to NULL before.

**Comment by CounterPillow** [comment]
But `wl_display_get_fd` didn't try to get the fd of `NULL` before, which it does now because it's done before `if (!wl->display) return false`.

I can reproduce the crash and wow, would you look at that, it's exactly as I described:
```
(gdb) bt
#0  0x00007ffff5d07620 in wl_display_get_fd () at /usr/lib/libwayland-client.so.0
#1  0x000055555568e82c in vo_wayland_init (vo=0x555555817840)
    at ../video/out/wayland_common.c:1146
#2  0x0000555555678015 in wayland_egl_init (ctx=0x7fffac000c60)
    at ../video/out/opengl/context_wayland.c:301
#3  0x000055555565932d in ra_ctx_create
```

**Comment by Dudemanguy** [comment]
Yup my fault. Auto-probing would fail. I'll revert it. It's a pointless feature anyway.

**Comment by laichiaheng** [comment]
https://github.com/mpv-player/mpv/commit/5dc16a4a183d51736cc56b4ef0a6b91a7b56fa09
