### ISSUE TITLE
subprocess: Return the original list of arguments as a result

### ISSUE THREAD

**Issue by archiif** [mpv-player/mpv#8152]
### Expected behavior of the wanted feature
When running the subprocess command, return the original list of arguments used in the subprocess. This would be useful in certain situations where you need to access that information again.
For example, for dealing with temporary files when the subprocess is ran asynchronously:
```lua
local file

function bar(success, result, error)
    if result.status == 0 then
        mp.osd_message('Command succeeded')
    else
        mp.osd_message('Command failed: ' .. result.stderr)
    end
    os.remove(file) -- this variable may have already been overwritten by the time this function is called
end

function foo()
    file = os.tmpname()
    mp.command_native_async({
            name = 'subprocess',
            playback_only = false,
            capture_stdout = false,
            capture_stderr = true,
            args = {command, file},
                            }, bar)
end
```
If you run the `foo` function repeatedly without waiting for each of the subprocesses spawned by them to be completed, the `bar` function that is called after those subprocesses are finished will only be able to access the latest iteration of the `file` variable, leaving all the older temp files undeleted.

### Log file

https://0x0.st/i066.txt

**Comment by wm4** [comment]
You can just make bar a closure and pass the original command yourself.

**Comment by archiif** [comment]
Sorry, I don't quite understand. If I make `bar` a closure how do I pass that function to `mp.command_native_async`?

**Comment by Akemi** [comment]
solved.
