### ISSUE TITLE
OSD-info when video is paused

### ISSUE THREAD

**Issue by Solarunit** [mpv-player/mpv#8155]
Please add an OSD-info when video is paused - a text "Paused" at the top left corner of the video. The duration can be 2 sec or (preferably) until the video is unpaused.

![Screenshot](https://user-images.githubusercontent.com/20891064/95530223-fd7e3680-09e5-11eb-891e-0edc8d569fa7.png)

**Comment by CogentRedTester** [comment]
Add `osd-msg` between the key and command in input.conf:

`SPACE osd-msg cycle pause`

**Comment by Solarunit** [comment]
@CogentRedTester unfortunately it doesn't work reliable

**Comment by oe-d** [comment]
Space no-osd cycle_values osd-msg1 Paused \n; cycle pause

**Comment by CogentRedTester** [comment]
The following lua script should also work. Just replace the pause character with whatever text you want:

```
local ov = mp.create_osd_overlay('ass-events')
ov.data = "⏸️"

mp.observe_property('pause', 'bool', function(_, paused)
    if paused then ov:update()
    else ov:remove() end
end)
```

**Comment by Solarunit** [comment]
@oe-d this is perfect but the problem is - in 50% cases there is no osd-msg at all when I pause the video. 

@CogentRedTester how to apply this lua script?

**Comment by oe-d** [comment]
That's mpv being stupid and sometimes not rendering the osd when the player is paused. Devs should probably look into that.

To use the script, save the text as a lua file and put it in .../mpv/scripts/ (https://mpv.io/manual/stable/#files)

**Comment by Solarunit** [comment]
> To use the script, save the text as a lua file and put it in .../mpv/scripts/ (https://mpv.io/manual/stable/#files)

thanks!

>That's mpv being stupid and sometimes not rendering the osd when the player is paused.

well, for me it happens very often.

>Devs should probably look into that.

I hope they do

**Comment by Akemi** [comment]
if there isn't an open issue for it(?), no one will most likely look at it.

since the initial feature request has been fulfilled, i will close this.

**Comment by CogentRedTester** [comment]
@Solarunit Yes it looks like the OSD tends not to update for a short period of time after a pause. I've modified the script to wait for 0.1 seconds before adding the pause icon, and that seems to have fixed it:
```
local mp = require 'mp'
local ov = mp.create_osd_overlay('ass-events')
ov.data = [[{\fs100\an5}]] .. "⏸"

mp.observe_property('pause', 'bool', function(_, paused)
    mp.add_timeout(0.1, function()
        if paused then ov:update()
        else ov:remove() end
    end)
end)
```

I've also modified the style of the pause icon to be larger and in the center of the screen. Changing the ov.data line back to what it was before will undo the change if you don't like it.

**Comment by Solarunit** [comment]
The script is working fine @CogentRedTester 
Thanks!
