### ISSUE TITLE
Any way to disable OSD volume progress-bar?

### ISSUE THREAD

**Issue by Solarunit** [mpv-player/mpv#8156]
Is there a way to disable OSD volume progress-bar? 
Volume info in % at the top left corner should stay.

![Screenshot2](https://user-images.githubusercontent.com/20891064/95597772-ba5cab80-0a57-11eb-9f90-b5a7f6e57d53.png)

**Comment by garoto** [comment]
Just browse the fricking manual.

**Comment by Solarunit** [comment]
ok, got it

**Comment by sfan5** [comment]
It's not actually that simple so here's more helpful advice:

<pre>
9 no-osd add volume -2; show-text "Volume: ${volume}%"
0 no-osd add volume +2; show-text "Volume: ${volume}%"
</pre>

**Comment by Solarunit** [comment]
@sfan5 yes, I did the same, thanks
