### ISSUE TITLE
Black colors are always out of gamut

### ISSUE THREAD

**Issue by pbasista** [mpv-player/mpv#8161]
### Important Information

- mpv --version
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100 (runtime 56.51.100)
   libavcodec      58.54.100 (runtime 58.91.100)
   libavformat     58.29.100 (runtime 58.45.100)
   libswscale      5.5.100 (runtime 5.7.100)
   libavfilter     7.57.100 (runtime 7.85.100)
   libswresample   3.5.100 (runtime 3.7.100)
ffmpeg version: n4.3.1
```
- Linux Distribution and Version
  - Arch Linux
- Source of the mpv binary
  - Distribution's package: `community/mpv 1:0.32.0-4 [installed]`
- If known which version of mpv introduced the problem
  - unknown to me
- Window Manager and version
  - Sway 1.5 from the distribution's package: `community/sway 1:1.5-1 [installed]`
- GPU driver and version
  - Intel(R) HD Graphics 630 (KBL GT2)
  - Intel open-source Mesa driver (Mesa 20.2.0), conformanceVersion 1.2.0.0
  - VA-API version: 1.9 (libva 2.9.1)
- Possible screenshot or video of visual glitches
  - [https://postimg.cc/RNnhRszH](https://postimg.cc/RNnhRszH)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases
- using the latest release version v0.32.0

### Reproduction steps

1. Get a video which displays a black color. For instance, it is possible to use this video from YouTube: https://www.youtube.com/watch?v=aXHcRiSK_ys and download it to file e.g. via `youtube-dl "https://www.youtube.com/watch?v=aXHcRiSK_ys"`.
1. Play the video with gamut warning enabled: `mpv --no-config --gamut-warning Black\ screen\ for\ Backlight\ Bleeding\ -\ 1\ hour\ 1080p-aXHcRiSK_ys.mp4`.

In the played video, the black color will be replaced with white color. This is caused by the triggering of the gamut warning feature which inverts the out-of-gamut colors to highlight them. It means that `mpv` considers the black color to be out of gamut. I am not sure why.

If I experiment with various tone mapping settings, I can adjust the tone mapping behavior of the bright colors to a great extent. This is useful for playing the HDR videos on a non-HDR display. But I was unable to find a combination of tone mapping options which would be able to completely remove the out-of-gamut highlighting for the black colors with gamut warning enabled.

However, I have found out that the `--video-output-levels=limited` option does remove almost all out-of-gamut highlighting for the black colors. I suppose that the reason is that the color levels are then mapped to a slightly smaller scale which starts at some non-zero value which `mpv` considers to be within the target display's gamut.

I am not sure if my display ([LG 27UD59](https://www.lg.com/uk/monitors/lg-27UD59)) uses full range or limited range color levels. I do not know how to check it. But considering that it is a desktop monitor, I would assume that it uses full range color levels. In such case, the issue might be related to `mpv`'s color conversion algorithm which might incorrectly convert the video colors to values which are out of the target display's gamut. If the display indeed uses limited range colors, then `mpv` might be detecting its capabilities incorrectly. I am not sure.

I have experienced this behavior on several Linux computers with slightly different configurations. It occurs on Wayland and also on X.Org. I have been able to reproduce it in Sway and in Gnome. It occurs on an internal display of MacBook Air (13-inch, Early 2015), as well as the previously mentioned external desktop monitor. And it occurs when the external monitor is connected via HDMI and also when it is connected via DisplayPort. I have only tried it on non-HDR displays.

All the computers that I have tried it on use the Intel Graphics GPU integrated in the CPU. I did not try other operating systems or other GPUs.

### Expected behavior

I would assume that the default tone mapping should map the colors from the video's colorspace to the colors from the display's colorspace in a way where no color would be out of gamut.

### Actual behavior

The default tone mapping does not correctly map the dark colors from the video's colorspace to the target display's colorspace. The black colors are considered to be out of gamut.

### Log file

https://0x0.st/iGaY.txt

### Sample files

* https://youtu.be/aXHcRiSK_ys (with gamut warning `mpv` produces a fully white image)
* https://youtu.be/C82kFD_Yol8?t=36 (screenshot with gamut warning enabled: https://postimg.cc/RNnhRszH)

**Comment by haasn** [comment]
I can't reproduce this issue on my GPU, but does this patch fix it?

```patch
diff --git a/video/out/gpu/video_shaders.c b/video/out/gpu/video_shaders.c
index a85b02ddee..5c1bae1db7 100644
--- a/video/out/gpu/video_shaders.c
+++ b/video/out/gpu/video_shaders.c
@@ -899,7 +899,7 @@ void pass_color_map(struct gl_shader_cache *sc, bool is_linear,
     // Warn for remaining out-of-gamut colors is enabled
     if (opts->gamut_warning) {
         GLSL(if (any(greaterThan(color.rgb, vec3(1.01))) ||
-                 any(lessThan(color.rgb, vec3(0.0)))))
+                 any(lessThan(color.rgb, vec3(-0.01)))))
             GLSL(color.rgb = vec3(1.0) - color.rgb;) // invert
     }
 
```

I'm assuming this error is benign, in any case. The color black probably just ends up as something just barely less than zero, for whatever reasons. Most likely our check is simply too strict.

**Comment by haasn** [comment]
Re-open if the issue persists.

**Comment by pbasista** [comment]
You are right, it resolved the issue, at least in my case. The black colors now do not trigger the gamut warning.

Thank you very much for looking into it.

**Comment by ValZapod** [comment]
> But considering that it is a desktop monitor, I would assume that it uses full range color

Why assume? For Display Port it is automatic as source (nvidia control panel?) says, no option; for HDMI there may be an option, but some normal displays like LG C9 support automatic range. This is called YCC and RGB quantisation range that is done in YQ and Q flag (yes, YCC can also be full range, but not xvYCC or the simplest subsampled mode, it can be like that in sYCC mode for example, see HDMI spec) with some amount of defaults and rules specified in CTA standards and HDMI spec. Works great but is broken from time to time in either the source or device...

> * Intel open-source Mesa driver

You should report that to MESA? What the will say?

**Comment by pbasista** [comment]
> Why assume?

Because I did not have any knowledge about the means that are necessary to in fact check this. In any case, the fact of whether this particular display uses the full range or limited range color levels or whether it can adapt to the source's color levels is irrelevant for the issue that I was experiencing with `mpv`. As was mentioned above, it was caused by the black color levels sometimes being represented as tiny negative values instead of zeros. I am not sure what could potentially cause such a numeric imprecision but the patch proposed by @haasn has at least fixed the gamut warning for me.

> You should report that to MESA? What they will say?

I am not sure what should I report. Do you suggest that the issue with inaccurate level of black color is caused by Mesa? I currently do not see into `mpv` or Mesa well enough to be able to confirm that or act on such a suspicion in any reasonable manner.
