### ISSUE TITLE
[Q] What's the recommended way to share code between mpv scripts?

### ISSUE THREAD

**Issue by NightMachinary** [mpv-player/mpv#8162]
Should I use [`require`](https://stackoverflow.com/questions/2932172/how-to-create-include-files-in-lua-language)?

**Comment by NightMachinary** [comment]
I played around, and the only way I could get this to work was by hardcoding the dir:

```
package.path = os.getenv("HOME") .. "/.config/mpv/scripts-shared/?.lua;" .. package.path
require("mpv_shared")
```

Using relative paths did not work. `mp.get_script_directory()` did not work either (its docs say only for directory scripts).

**Comment by guidocella** [comment]
You can use

```lua
mp.command_native({"expand-path", "~~/scripts"})
```

**Comment by NightMachinary** [comment]
[**@Guido Cella**](https://github.com/guidocella) commented on [Oct 15, 2020, 1:16 PM GMT+3:30](https://github.com/mpv-player/mpv/issues/8162#issuecomment-709051730 "2020-10-15T09:46:48Z - Replied by Github Reply Comments"):
> You can use
> 
> ```lua
> mp.command_native({"expand-path", "~~/scripts"})
> ```

I get

`  log("tagger called" .. mp.command_native({"expand-path", "~~/scripts"}))`

```
[autotag] Command 'expand-path' not found.
[autotag]
[autotag] stack traceback:
[autotag] 	/Users/evar/.config/mpv/scripts/autotag.lua:40: in function 'handler'
[autotag] 	mp.defaults:459: in function 'call_event_handlers'
[autotag] 	mp.defaults:496: in function 'dispatch_events'
[autotag] 	mp.defaults:452: in function <mp.defaults:451>
[autotag] 	[C]: ?
[autotag] 	[C]: ?
[autotag] Lua error: /Users/evar/.config/mpv/scripts/autotag.lua:40: attempt to concatenate a nil value
```

**Comment by guidocella** [comment]
expand-path was added 1 year ago in version 0.30 (https://github.com/mpv-player/mpv/commit/4247a54d98dd386056308d6d275a35a7ad77becb). Are you using a very old version?

**Comment by NightMachinary** [comment]
[**@Guido Cella**](https://github.com/guidocella) commented on [Oct 15, 2020, 8:29 PM GMT+3:30](https://github.com/mpv-player/mpv/issues/8162#issuecomment-709459997 "2020-10-15T16:59:26Z - Replied by Github Reply Comments"):
> expand-path was added 1 year ago in version 0.30 ([4247a54](https://github.com/mpv-player/mpv/commit/4247a54d98dd386056308d6d275a35a7ad77becb)). Are you using a very old version?

You're right. After updating, `package.path = mp.command_native({"expand-path", "~~/"}) .. "/scripts-shared/?.lua;" .. package.path` works. Thanks.
