### ISSUE TITLE
automatically pause

### ISSUE THREAD

**Issue by Geniusssmit** [mpv-player/mpv#8164]
How to automatically pause playback after each subtitle line is said?

**Comment by CounterPillow** [comment]
This is a very specific use case, which means mpv does not have a builtin way of doing this. You best do it by writing yourself a Lua or JS script for mpv which observes the `sub-start` and `sub-end` properties to figure out when the subtitle has changed, and then sets the `pause` property if `time-pos` >= the previously observed `sub-end`.

**Comment by oltodosel** [comment]
You can use https://github.com/oltodosel/interSubs or look how it's done there.
At config:
`auto_pause_min_words = 10`
`auto_pause = 0`

**Comment by Casiyus** [comment]
> 
> 
> How to automatically pause playback after each subtitle line is said?

Did you end up reaching a solution for this ?

**Comment by avih** [comment]
> Did you end up reaching a solution for this ?

I'm sure that if someone writes a script for it and is aware of this issue, then they'll post or link their script here.

Feel free to do that yourself and help others while at it.

**Comment by guidocella** [comment]
```
[sub-pause]
profile-cond=time_pos > sub_end - 0.1 and time_pos < sub_end
pause
```
seems to work.
