### ISSUE TITLE
Occational stuttering playback on wayland

### ISSUE THREAD

**Issue by focus64** [mpv-player/mpv#8169]
Since commit efb0c5c, playback on wayland became unsmooth on both Sway and Gnome. The problem is pronounced when having two playback windows on the same deskotp screen, one playing a 30fps video with mpv, the other playing a 24fps (or 25fps) video with either mpv or Firefox. The 30fps playback becomes unsmooth and stuttering every several minutes.

The problem is also observed in full screen playback on Gnome (3.36 and 3.38), just a lot less.

Full screen playback on Sway looks fine, or unnoticeable.

I am on Arch linux, Intel integrated graphics HD 630.

**Comment by Dudemanguy** [comment]
Log?

**Comment by focus64** [comment]
[30fps.log](http://0x0.st/iGLW.log)
[24fps.log](http://0x0.st/iGL4.log)

**Comment by Dudemanguy** [comment]
I can reproduce this but only with multiple videos playing at once and only on the default audio video-sync mode. So probably vblank occasionally gets missed (no callback from the compositor) which results in stutter. I can easily make the heuristic less strict though.

**Comment by DmitryHetman** [comment]
I also noticed that mpv performs poorly on intel atom (lg x120 netbook, 1gb ram), especially when I enable full-screen or any scaling on wayland, while vlc plays it just fine in any mode. Of course it too slow, but vlc is usable while mpv not, look like problem with hardware acceleration

**Comment by Dudemanguy** [comment]
Completely unrelated to this.
