### ISSUE TITLE
video-sync=display-resample maxes GPU out when moving mpv window to a different virtual desktop on kwinft Wayland

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#8178]
### Important Information

- mpv 0.32.0-766-gf5a094db04
- Arch
- own build
- kwinft 5.20 Wayland
- mesa-git 20.3.0_devel.127495.2da1178bf3e

### Reproduction steps

Open a video with `--video-sync=display-resample` and then move mpv's window to a different virtual desktop.

### Expected behavior

Playback should get metered in such a way that it doesn't put additional load on the GPU vs. playback on the original virtual desktop.

### Actual behavior

mpv maxes out my GPU. Looks like rendering without vsync, i.e. as high frame rate as possible.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/5386306/output.txt)

**Comment by Dudemanguy** [comment]
>Audio/Video desynchronisation detected! Possible reasons include too slow
>hardware, temporary CPU spikes, broken drivers, and broken files. Audio
>position will not match to the video (see A-V status field).

Does that message pop up when you move it to a different desktop? That shouldn't happen. I wonder if something funny is going on with presentation time here.

**Comment by aufkrawall** [comment]
> Does that message pop up when you move it to a different desktop?

Yes.

**Comment by Dudemanguy** [comment]
I had the chance to try this out and for me it instantly behaved badly (i.e. broken playback). I confirmed it has to do with presentation time, but I didn't dig through the details of why.

**Comment by Dudemanguy** [comment]
Does it still happen with 9976c83? I was never able to exactly reproduce your problem, but the commit is probably related.

**Comment by aufkrawall** [comment]
It has gotten better: GPU load still ramps up, but not as much anymore. If you think this is an issue in kwinft, I'll report it there.

**Comment by Dudemanguy** [comment]
Hard to say but it can't hurt. mpv does use presentation time in a slightly strange way though so maybe it's related.

**Comment by aufkrawall** [comment]
Fixed in either mpv git-master or kwinft 5.22
