### ISSUE TITLE
[SUGGESTION] Haiku port

### ISSUE THREAD

**Issue by forart** [mpv-player/mpv#8182]
MPV quickly becomed my favorite player, so it would be great to have it under this cool multimedia operating system too:

https://www.haiku-os.org/

Hope that inspires.

**Comment by Hrxn** [comment]
Hmmmm.. but does it support XDG? 🤔

**Comment by qyot27** [comment]
[Did you even bother to try and look for it in HaikuDepot first?](https://depot.haiku-os.org/#!/?bcguid=bc1-XQDM&repos=haikuports&arch=x86_64&viewcrttyp=FEATURED&srchexpr=mpv)

**Comment by Akemi** [comment]
it apparently already is.
