### ISSUE TITLE
filter_sdh.c joins lines without a space causing bad punctuation.

### ISSUE THREAD

**Issue by hboetes** [mpv-player/mpv#8185]
This is pretty easy to reproduce, with a common srt file which contains something like this

```
9332-01:58:18,365 --> 01:58:22,573
foo bar bla,
yada yada yada
```
The filter_sdh.c joins those two lines like this: "foo bar bla,yada yada yada", which is against common punctuation rules.

Please consider adding a space at the end of each joined line, so they look like this: "foo bar bla, yada yada yada".

Thanks!

**Comment by Akemi** [comment]
i believe this isn't even a valid srt line. usually the number of the line and the timecodes are separated by a newline.

i can't reproduce it, neither with --sub-filter-sdh=yes nor --sub-filter-sdh-harder=yes. also you ignored the issue template. if the problem still persists with the latest master version of mpv please open a proper issue.
