### ISSUE TITLE
[BUG] auto extension profiles are case-sensitive

### ISSUE THREAD

**Issue by NightMachinary** [mpv-player/mpv#8187]
### Important Information

Provide following Information:
- mpv version
```
❯ mpv --version
mpv 0.32.0-750-ge1536193cb Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Sep 28 14:02:04 UTC 2020
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: 4.3.1
```
- macOS Version: 10.15
- Source of the mpv binary or bundle: https://github.com/jnozsc/mpv-nightly-build

### Reproduction steps

If I use
```
[extension.jpg]
input-conf=/Users/evar/Base/_Code/lua/mpv/image_input.conf
```
, mpv does not activate this profile on files ending in `.JPG`. Adding
```
[extension.JPG]
input-conf=/Users/evar/Base/_Code/lua/mpv/image_input.conf
```
works correctly.

**Comment by guidocella** [comment]
extension profiles are deprecated anyway, you should use conditional auto profiles.

```
[img]
profile-cond=estimated_frame_count < 2
```

**Comment by Akemi** [comment]
since the usage of "extension.*" is deprecated and if the current way of detecting images aren't any good, please consider opening a feature request.

**Comment by NightMachinary** [comment]
[**@Akemi**](https://github.com/Akemi) commented on [Oct 17, 2020, 9:12 PM GMT+3:30](https://github.com/mpv-player/mpv/issues/8187#issuecomment-711055347 "2020-10-17T17:42:29Z - Replied by Github Reply Comments"):
> since the usage of "extension.\*" is deprecated and if the current way of detecting images aren't any good, please consider opening a feature request.

Please consider updating the manpage then; It doesn't indicate the deprecation. Thanks!

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst

here at least it says it's "soft-deprecated".
