### ISSUE TITLE
Aspect ratio override "4:3" versus "1.3333"

### ISSUE THREAD

**Issue by JorgeR81** [mpv-player/mpv#8189]
Hi,

I noticed that when I override the aspect ratio to "4:3" the picture is 1 or 2 pixels wider than what it's supposed to be.

If I use "1.3333" instead, the OSD will still show the same message "Aspect ratio override: "4:3" but I can get the exact dimensions. Now I can get screen captures with exact dimensions of 1920 x 1440, and "print screens" showing a picture of 1440 x 1080 (I tested on a 1920 x 1080 monitor).

Just try cycle-values video-aspect-override "1.3333" "4:3" and you will clearly see it.
I'm on windows 10. Tested on mpv 0.32.0 Windows 64-bit (stable release version)

I don't know if this is a bug or a known issue?
(You can feel free to close this issue, since I already found a workaround. I just thought this might help others, also new to MVP, when googling this or something.)

Thanks

**Comment by Akemi** [comment]
this seems to be a rounding bug(?). would you mind opening a proper issue please?

**Comment by JorgeR81** [comment]
OK, I will try to provide all the extra information, mentioned on the template
