### ISSUE TITLE
Aspect ratio override "4:3" versus "1.3333" ( rounding bug? )

### ISSUE THREAD

**Issue by JorgeR81** [mpv-player/mpv#8190]
- mpv 0.32.0 Windows 64-bit (stable release version)

- windows 10 home, version 1909

- Source of the mpv binary: I'm new to MPV. I've just download it from: https://www.videohelp.com/software/mpv-media-player.
(I download most of my video software from there. It always worked fine).

### Reproduction steps

Just try **cycle-values video-aspect-override "1.3333" "4:3"** and you will clearly see it.
I've also tried with "no-config" in the "mpv.conf" file and it has the same behavior.

### Expected behavior

When do **set video-aspect-override "4:3"**, I expect a picture of 1440 x 1080 (I tested on a 1920 x 1080 monitor).
I also expect to be able to take screenshot with the exact dimensions of 1920 x 1440.
I tried on other software (MPC-HC, VLC and Potplayer), and this is the behavior I get.

### Actual behavior

When I override the aspect ratio to "4:3" the picture is 1 or 2 pixels wider than what it's supposed to be.
If it is 1 or 2 to pixels wider, seem to depend on the dimensions of the original Image. But I didn't explored this much deeper.
If I use "1.3333" instead, the OSD will still show the same message "Aspect ratio override: "4:3" but I can get the exact dimensions.

_**EDIT : check the post below to get more objective results.**_

### Log file

Sorry, total newbie here!... I couldn't figure out how to do this yet. (I've also tried "log-file=C:\output.txt", but it didnt work.)
But this bug is so simple to reproduce that perhaps is best to just report now, instead of waiting any longer. I'm glad to provide more information if needed, or to make a log file, if you help me with that.

**Comment by Akemi** [comment]
> ### Expected behavior
> ... I expect a picture of 1440 x 1080...

on a side note, mpv will always upscale and never downscale in such cases. so 1920x1440 would be the right dimension in that case. what the actual window dimension will be depends on you monitor resolution and platform.

**Comment by JorgeR81** [comment]
Yes, when I take a screenshot the expected image size is 1920 x 1440.
So, I guess you can forget about the 1440 x 1080 pictures part, because that's redundant information. Those were produced by making a "Print Screen" (while using a 1920 x 1080 monitor) and then cropping to exact dimensions of the video picture with some photo editing software.
But, just to clarify it, the image is 1 or 2 pixel wider on both cases. You can see it with your "naked eye" on the monitor if you cycle trough "1.3333" and "4:3".

**Comment by JorgeR81** [comment]
I did a couple of extra tests, but now just focusing on screenshots, to get more clear results.
I tested with this in the input.conf file and took screenshots:
 
c   set video-aspect-override "16:9"
v   set video-aspect-override "1.7777"
n   set video-aspect-override "4:3" 
m  set video-aspect-override "1.3333"

------------------------------------------------------------------------

I used a video with **1920 x 1080** native resolution:

- Overriding to "4:3" produces a screenshot of 1920 x 1439

- Overriding to "1.3333" produces a screenshot of 1920 x 1440 (expected behavior of "4:3" ratio)

- Overriding "16:9" produces a screenshot of 1920 x 1080 (the expected behavior)

- Overriding to "1.7777" produces a screenshot of 1920 x 1080

------------------------------------------------------------------------

I also used a video with **1920 x 1038** native resolution. 
The aspect ratio is "correct" in this video (it's an approximation of the 1.85:1 aspect ratio).

- Overriding to "4:3" produces a screenshot of 1920 x 1439

- Overriding to "1.3333" produces a screenshot of 1920 x 1440 (expected behavior of "4:3" ratio)

- Overriding "16:9" produces a screenshot of 1920 x 1079

- Overriding to "1.7777" produces a screenshot of 1920 x 1080 (expected behavior of "16:9" ratio)

------------------------------------------------------------------------

Tried on a video with an even more "cinematographic"" aspect ratio. Native resolution: **1920 x 808**.
Same results as last resolution:

- Overriding to "4:3" produces a screenshot of 1920 x 1439

- Overriding to "1.3333" produces a screenshot of 1920 x 1440 (expected behavior of "4:3" ratio)

- Overriding "16:9" produces a screenshot of 1920 x 1079

- Overriding to "1.7777" produces a screenshot of 1920 x 1080 (expected behavior of "16:9" ratio)
