### ISSUE TITLE
wrong filename

### ISSUE THREAD

**Issue by collstudent** [mpv-player/mpv#8194]
Hi,

I want to see the title as I jump to next file in the playlist. e.g. if file 05.mp4 is being played, I want to go to 06.mp4 and see 06.mp4 as OSD. So I put the following shortcut in input.conf

PGUP  playlist-prev  ;  show-text "${filename}"  ; 

It does jump to file 06.mp4, but shows the text 05.mp4 while jumping. Can someone help me fix this? I even tried putting a dummy shortcut between, like 

PGUP  playlist-prev  ;	set speed 1.0   ; show-text "${filename}"  ; 

but it didn't work either.

**Comment by CogentRedTester** [comment]
Use [--osd-playing-message](https://mpv.io/manual/master/#options-osd-playing-msg) instead.

**Comment by collstudent** [comment]
I modified it to
`PGUP  playlist-prev    ; osd-playing-msg='file: ${filename}'  `

The command line says  `input: Command 'osd-playing-msg='file:' not found.`
and `input: Invalid command for key binding 'PGDWN': 'playlist-next ; osd-playing-msg='file: ${filename}'`

**Comment by collstudent** [comment]
Ok, I fixed it by leaving it to `PGUP playlist-prev ;` and modifying the mpv.conf file by adding a line `osd-playing-msg= 'Now Playing: ${filename}\n \nPlaylist:\n${playlist}'` as suggested by `https://github.com/stax76/mpv.net/issues/171`
