### ISSUE TITLE
[Question] win10 echo loadfile garbled

### ISSUE THREAD

**Issue by skelet8801** [mpv-player/mpv#8197]
[**echo loadfile** fails] : file name **garbled**

**Windows 10** professional 64                
 **mpv-x86_64**-20201011-git-67b4a96 from Official website

Execute thie command :  echo loadfile **D:\abc02中文**.mp4  >\\.\pipe\mpvsocket 
When the file name contains Chinese characters, loadfile fails

this fails:
echo **loadfile** **D:\abc02中文**.mp4  >\\.\pipe\mpvsocket

but these work :
**mpv D:\abc02中文**.mp4 --input-ipc-server=\\.\pipe\mpvsocket
echo loadfile D:\abc02.mp4  >\\.\pipe\mpvsocket

### Expected behavior
Load successfully and play the video
### Actual behavior
[   1.648][e][file] Cannot open file 'D:\abc02֐΄.mp4': No such file or directory

### Log file
[   1.641][v][ipc_0] Client connected
[   1.641][d][cplayer] Run command: loadfile, flags=73, args=[url="**D:\\abc02֐΄.mp4**", flags="replace", options=""]
[   1.642][d][global] config path: 'C:\Users\jly\AppData\Roaming/mpv/watch_later' -> 'C:\Users\jly\AppData\Roaming/mpv/watch_later'
[   1.642][i][cplayer] Saving state.
[   1.643][v][cplayer] EOF code: 3  
[   1.643][v][ipc_0] Client disconnected
[   1.643][d][ao/wasapi] Thread Reset
[   1.643][d][ad] Uninit decoder.
[   1.643][d][ipc_0] Exiting...
[   1.643][d][vd] Uninit decoder.
[   1.645][d][cplayer] Terminating demuxers...
[   1.647][d][cplayer] Done terminating demuxers.
[   1.647][v][cplayer] finished playback, success (reason 2)
[   1.647][i][cplayer] 
[   1.647][v][cplayer] Running hook: ytdl_hook/on_load
[   1.648][v][ytdl_hook] ytdl:// hook 
[   1.648][v][ytdl_hook] not a ytdl:// url 
[   1.648][v][ifo_dvdnav] Opening **D:\abc02֐΄.mp4**
[   1.648][v][bdmv/bluray] Opening D:\abc02֐΄.mp4
[   1.648][v][file] Opening D:\abc02֐΄.mp4
[   1.648][e][file] **Cannot open file 'D:\abc02֐΄.mp4': No such file or directory**
[   1.648][e][stream] Failed to open D:\abc02֐΄.mp4.
[   1.648][v][cplayer] Opening failed or was aborted: D:\abc02֐΄.mp4
[   1.648][v][cplayer] Running hook: ytdl_hook/on_load_fail
[   1.648][v][ytdl_hook] full hook 
[   1.648][d][ao/wasapi] Thread Reset
... ...

### Sample files
The following is **AutoHotKey script**, regardless of whether the first filename contains Chinese or not, the video can be played normally. If there is Chinese characters in filename2, execute **^Numpad2** to report an error.

#SingleInstance, Force

;filename = D:\abc02中文.mp4
filename = D:\abc01.mp4

**filename2** = **D:\abc02中文**.mp4
;filename2 = D:\abc02.mp4

shell := ComObjCreate("WScript.Shell")
socketNmae = mpvsocket
cmd = mpv %filename% --input-ipc-server=\\.\pipe\%socketNmae%
Run, %cmd%,,, pid_get

^Numpad1::
cmd = echo cycle pause   >\\.\pipe\%socketNmae%
shell_exe_cmd(cmd)
return

**^Numpad2**::
cmd = echo **loadfile** %**filename2**%  >\\.\pipe\%socketNmae%
shell_exe_cmd(cmd)
return

shell_exe_cmd(cmd)
{
	global shell
	shell.Exec(ComSpec " /C " cmd)
}

Esc::
exec := shell.Exec(ComSpec " /C " "taskkill /f /im mpv.exe")
ExitApp
return

**Comment by garoto** [comment]
`C:\> chcp 65001`  <kbd>ENTER

**Comment by skelet8801** [comment]
> `C:\> chcp 65001` ENTER


Thank you very much, this does work in the cmd window.

But when I call ComObjCreate("WScript.Shell").EXEC, it doesn't work. 
I tried various methods adding "chcp 65001" to the command, it did not work.

**Comment by skelet8801** [comment]
I can write the command line into a temporary bat script, execute it, 
and then delete the temporary script. But this is slower. 
As follows:
cmd = CHCP 65001 > null `necho loadfile %filename2%  >\\.\pipe\%socketNmae%
FileDelete, aa.bat
FileAppend, %cmd%, aa.bat, UTF-8-RAW
Run %comSpec% /C  aa.bat


Finally, I abandoned loadfile command. 
When I need to open a new file, directly call mpv to open it in the original location. 
Then kill the original MPV window Pid. 
This is faster (because I also need to adjust the video progress. When I open it with mpv, 
it can jump directly To the specified progress. 
If I use loadfile , after executing the command, it need to sleep for 100 milliseconds to adjust the progress).
As follows:
geometry = % p_w "x" p_H "+" pos_X "+" pos_Y
cmd = mpv %filename%  --start=%jump_to% --geometry=%geometry%  --input-ipc-server=\\.\pipe\%socketNmae%
