### ISSUE TITLE
mpv manual page - unable to find how to change 60 seconds seek jump (up/down keys)

### ISSUE THREAD

**Issue by slrslr** [mpv-player/mpv#8200]
The Linux Arch (Manjaro) manual page for mpv 0.32.0-4 does not show any configurable options which i would understand to apply on up/down keys seeking in the video.

mpv --list-options|egrep -i "seek|60"
```--audio-wait-open                Float (0 to 60) (default: 0.000)
 --cache-secs                     Double (0 to any) (default: 36000.000)
 --chapter-seek-threshold         Double (default: 5.000)
 --demuxer-backward-playback-step Double (0 to any) (default: 60.000)
 --demuxer-lavf-analyzeduration   Float (0 to 3600) (default: 0.000)
 --demuxer-lavf-buffersize        Integer (1 to 10485760) (default: 32768)
 --demuxer-seekable-cache         Choices: auto no yes (default: auto)
 --force-seekable                 Flag (default: no)
 --hr-seek                        Choices: no absolute yes always (default: absolute)
 --hr-seek-demuxer-offset         Float (default: 0.000)
 --hr-seek-framedrop              Flag (default: yes)
 --network-timeout                Double (0 to any) (default: 60.000)
 --osd-duration                   Integer (0 to 3600000) (default: 1000)
 --osd-margin-y                   Integer (0 to 600) (default: 22)
 --osd-on-seek                    Choices: no bar msg msg-bar (default: bar)
 --replaygain-fallback            Float (-200 to 60) (default: 0.000)
 --sub-ass-vsfilter-color-compat  Choices: no basic full force-601 (default: basic)
 --sub-clear-on-seek              Flag (default: no)
 --sub-margin-y                   Integer (0 to 600) (default: 22)
 --target-prim                    Choices: auto bt.601-525 bt.601-625 bt.709 bt.2020 bt.470m apple adobe prophoto cie1931 dci-p3 display-p3 v-gamut s-gamut (default: auto)
```

My aim is to change seek from 60s to 30s. I have found config file:
$ locate mpv.conf
/usr/share/doc/mpv/mpv.conf

i tried to add "hr-seek-demuxer-offset=30" to the first line, but that not change the 60s jump in the video.

**Comment by sfan5** [comment]
`mpv --list-options` is not the manual. `man mpv` is the manual, read it.

**Comment by slrslr** [comment]
Yes, i read it too and not found.

**Comment by shabahengam** [comment]
keybindings should be in `input.conf`, **not** `mpv.conf`
put this in input.conf (`~/.config/mpv/input.conf`)
```
UP osd-msg seek 30 exact
DOWN  osd-msg seek -30 exact
```
read the [manual](https://mpv.io/manual/master/) for more info.

**Comment by slrslr** [comment]
That worked, thank you.
Yes this player is user unfriendly, but that is by design to not offer any GUI configuration interface i guess.
The manual contains "seek" 260 times or more ) I would spend my life reading it and when i would be at the end, i would forget the beginning.

**Comment by garoto** [comment]
The html version @ https://mpv.io/manual/master/ has a ToC.
