### ISSUE TITLE
[gpu_next] mpv properties (ex: time) as a shader parameter (was transition shaders)

### ISSUE THREAD

**Issue by butterw** [mpv-player/mpv#8206]
### Expected behavior of the wanted feature
The following example shader displays an orange bloc that moves on screen at mpv first launch (based on frame): 
https://github.com/butterw/bShaders/blob/master/mpv/cs_wkgroups.hook.glsl

**I would like to be able to trigger transition shaders, at each new file played (in a playlist for instance). This would be possible if play time in seconds was available as a parameter to shaders.**  

**Feature request: expand available uniform parameters available to user shaders:**
1) Make time in seconds available as a uniform float parameter to user shaders (like mpc-hc/be). This enables timed effects (independantly of the frame rate which could be 25, 30 or 60fps, etc.). 
It can also be used as a seed for PRNG. The glsl version of this noise shader produces an undesirable pattern using frame or random: https://github.com/butterw/bShaders/blob/master/FilmGrain_Noise/bNoise.hlsl

2) Make play time in seconds (or play frame ?), which resets to zero at each new file available to user shaders. The value 0 could be used to trigger a transition effect.

**Comment by butterw** [comment]
For transition effects specifically, it might be simpler to introduce a !WHEN condition on playtime to enable/disable the shader in the pass header: 
The shader is enabled WHEN a new input file is loaded and for a specified duration. 
   
A time uniform (1.) would still would be useful in shaders: 
- "random" is a fixed sequence ? unless you can change the seed of the PRNG it isn't actually random at all.
- being able to have random effects would be desirable. 
- the logic required for handling timed effects (start, stop, repetition, duration) isn't that simple, as demonstrated by this simple shader for mpc-hc: 
https://github.com/butterw/bShaders/blob/master/bStrobe.hlsl

**Comment by natural-harmonia-gropius** [comment]
> AFAIK what is still missing is the ability to associate a mpv property (such as playback-time) to a shader

Try this.

![image](https://github.com/mpv-player/mpv/assets/50797982/57647e60-01c6-408f-8c6f-8361ff29ae5f)

```lua
mp.observe_property("playback-time", "native", function(_, v)
    -- print(v)
    mp.command("no-osd set glsl-shader-opts p=" .. v)
end)
```

**Comment by butterw** [comment]
Using a script (I'm using javascript as I am not familiar with lua or its syntax) it is possible to associate a property as a vo_gpu_next shader input using mp.observe_property. But there still is a problem here as playback-time is initially undefined when the file loads.
Obviously it is possible to test the value in the function before passing it on to the shader and the script approach can work, but this does end up being more complex than is desirable.

```
//obs.js:
mp.observe_property("playback-time", "number", play_time);
function play_time(name, value) {
	print (value);
	mp.command("no-osd set glsl-shader-opts time_s=" +value);
}
```

**Comment by natural-harmonia-gropius** [comment]
> I'm using javascript as I am not familiar with lua or its syntax

I'm not happy with lua too. but mujs only supports ES5 and the perf much worse than lua-jit.

You can use this: https://typescripttolua.github.io/, to avoid lots of traps of lua.

> more complex than is desirable

These checks was enough I think.

```js
mp.observe_property("playback-time", "native", (name, value) => {
    if (typeof value !== "number" || Number.isNaN(value))
        return;

    // ...
});
```
