### ISSUE TITLE
GLSL Shader (FSRCNNX) fails to hook when video file is opened via double-click

### ISSUE THREAD

**Issue by lextra2** [mpv-player/mpv#8210]
### Important Information

- mpv version
mpv-x86_64-20201011-git-67b4a96

- Windows Version
w10 v2004

- Source of the mpv binary
mpv-x86_64-20201011-git-67b4a96.7z
https://sourceforge.net/projects/mpv-player-windows/files/64bit/

- If known which version of mpv introduced the problem
I will investigate which build started to break the hook.

### Reproduction steps
Double-click on any video file (assign the file container to mpv, e.g. "open with")
Now with the opened video, press "f" for fullscreen, then "shift+i" and then "2" to show the advanced info tab. As you can see, the statistics for FSRCNNX are no where to be seen because it failed to hook.

This does not happen when I open MPV as a blank first, and then manually drag & drop the video onto it. In this case FSRCNNX properly hooks once fullscreen is toggled.

My mpv.conf:
```
profile=gpu-hq
glsl-shader="FSRCNNX_x2_8-0-4-1.glsl"
```
### Log files

[double-click-log.txt](https://github.com/mpv-player/mpv/files/5436664/double-click-log.txt)
[drag-and-drop-log.txt](https://github.com/mpv-player/mpv/files/5436666/drag-and-drop-log.txt)

### Expected behavior
FSRCNNX should hook properly.

### Actual behavior
FSRCNNX does fail to hook when videos aren't dragged & dropped.

### Sample files
Any video will do.
https://github.com/igv/FSRCNN-TensorFlow/releases/tag/1.1

[Video of the issue](https://streamable.com/ovr1wb)

**Comment by CounterPillow** [comment]
Neither logs show it applying any of your config options. Are you sure your config file is named `mpv.conf` and in the right location?

**Comment by lextra2** [comment]
> 
> 
> Neither logs show it applying any of your config options. Are you sure your config file is named `mpv.conf` and in the right location?

Please check out this short video on the issue. As you can see, gpu-hq is properly loaded from my mpv.conf (from the portable_config folder) and only FSRCNNX fails to hook (only when opening a video via double click)

[VIDEO LINK](https://drive.google.com/file/d/18L7wyF-t40Tg2cUapqvQe6ubmnZrlrVt/view?usp=sharing)

**Comment by Doofussy2** [comment]
Doesn't look like the address for the shader is correct. I use that shader, but I specify the directory.

**Comment by lextra2** [comment]
> 
> 
> Doesn't look like the address for the shader is correct. I use that shader, but I specify the directory.

You're right. If I specify the whole filepath, e.g.
`glsl-shader="C:\Users\Admin\Downloads\mpv-x86_64-20201011-git-67b4a96\shaders\FSRCNNX_x2_8-0-4-1.glsl"`
It works again. Still, I remember it working fine with just
`glsl-shader="FSRCNNX_x2_8-0-4-1.glsl"`
in earlier builds.

Anyway, Issues is solved. Closing.

**Comment by hooke007** [comment]
glsl-shader="xxx.glsl" only works when you put the "xxx.glsl" in the same folder of "mpv.exe".
