### ISSUE TITLE
Can't build mpv app bundle 

### ISSUE THREAD

**Issue by shinysuittheory** [mpv-player/mpv#8211]
- mpv version 0.32.0_6
- macOS Version 10.15.7

I've been trying to reinstall mpv from source so as to get the app bundle for macOS, similarly to the closed and now locked "Missing mpv.app bundle #46532", but keep getting an error which I believe has something to do with python but I can't figure out what. Can anyone shed some light?

link to error text from terminal - https://pastebin.pl/view/a5a1e0d0

<img width="675" alt="Screenshot 2020-10-26 at 3 13 37 PM" src="https://user-images.githubusercontent.com/73496105/97219365-4a149080-17a0-11eb-93ba-0fd0cb2e2d04.png">

**Comment by jeeb** [comment]
`Last 15 lines from /Users/blackgold/Library/Logs/Homebrew/mpv/03.python3` mentions that `/Users/blackgold/Library/Logs/Homebrew/mpv/03.python3` probably contains the full log?

**Comment by shinysuittheory** [comment]
> `Last 15 lines from /Users/blackgold/Library/Logs/Homebrew/mpv/03.python3` mentions that `/Users/blackgold/Library/Logs/Homebrew/mpv/03.python3` probably contains the full log?

link to text from full log - https://pastebin.pl/view/7cef94a0

**Comment by jeeb** [comment]
Please test with current master or otherwise bump the utilized waf to a newer one (I recently bumped the utilized version from 2.0.9 to 2.0.20) ? I will test here locally first with the current version of Python 3 I have around, and then attempt with 3.9, which apparently you have already upgraded to.

**Comment by shinysuittheory** [comment]
> Please test with current master or otherwise bump the utilized waf to a newer one (I recently bumped the utilized version from 2.0.9 to 2.0.20) ? I will test here locally first with the current version of Python 3 I have around, and then attempt with 3.9, which apparently you have already upgraded to.

I re-updated brew and tested with the current master and the issue seems to be resolved. I think it was also some weird bug with xcode as I also opened xcode and kept it open, before reinstalling from source
