### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mmowchenko** [mpv-player/mpv#8214]
Is there any hope for a new release? For those of us that don't have the means to build the master it would be really nice to see some of the past year's fixes come to light.

**Comment by jeeb** [comment]
Yes, this is in planning.

Basically a case of:

1. Checking if any open pull requests are quick enough wins.
2. Checking core developers if there's anything they would like to land in the near future
   * new stuff
   * requesting another look at some previously changed thing
   * etc
3. Requesting folk for another look at basic functionality, if there isn't anything too clear that has regressed.

**Comment by nshtg** [comment]
There was a nasty bug that was fixed quite a while back that lead to extremely slow connections from SMB shares (at least in linux). This alone should warrant a new release in my opinion.
