### ISSUE TITLE
libmpv - cuda with x11egl not works

### ISSUE THREAD

**Issue by ua0lnj** [mpv-player/mpv#8215]
### Important Information

Provide following Information:
- mpv version - latest
- Linux Distribution and Version - ubuntu 18.04
- Source of the mpv binary - git
- Window Manager and version - X11 1.19.6
- GPU driver and version - NVIDIA dlloader X Driver  450.80.02

### Reproduction steps
Play hevc 4k mkv video, Nvidia GT-1030 card.
mpv -vo=gpu -hwdec=cuda works fine.

But libmpv with:
mpv_set_option_string(hMpv, "vo", "gpu");
mpv_set_option_string(hMpv, "hwdec", "cuda");
hardware decoder not works and libmpv use soft decoder.

I have:
[   0.718][v][vo/gpu] Loading hwdec driver 'cuda-nvdec'
[   0.718][v][vo/gpu/cuda-nvdec] cu->cuGLGetDevices(&device_count, &display_dev, 1, CU_GL_DEVICE_LIST_ALL) failed -> CUDA_ERROR_INVALID_GRAPHICS_CONTEXT: invalid OpenGL or DirectX context
[   0.718][v][vo/gpu/cuda-nvdec] CUDA hwdec only works with OpenGL or Vulkan backends.
[   0.718][v][vo/gpu] Loading failed.

If I use mpv_set_option_string(hMpv, "gpu-context", "x11");
I have:
API error: error setting option
because GLX disabled by default now.

If I use mpv_set_option_string(hMpv, "gpu-context", "x11egl");
I have too:
[   0.719][v][vo/gpu] Loading hwdec driver 'cuda-nvdec'
[   0.719][v][vo/gpu/cuda-nvdec] cu->cuGLGetDevices(&device_count, &display_dev, 1, CU_GL_DEVICE_LIST_ALL) failed -> CUDA_ERROR_INVALID_GRAPHICS_CONTEXT: invalid OpenGL or DirectX context
[   0.719][v][vo/gpu/cuda-nvdec] CUDA hwdec only works with OpenGL or Vulkan backends.
[   0.719][v][vo/gpu] Loading failed.

I tryed
mpv_set_option_string(hMpv, "gpu-context", "auto");
same result,
mpv_set_option_string(hMpv, "gpu-api", "opengl");
same result.
mpv_set_option_string(hMpv, "hwdec", "nvdec");
same result.

Before the disable GLX it worked with "gpu-context", "x11".
Got this after updating to current git.
What else can I try?

Libmpv configured with EGL support:
Checking for EGL 1.4                                                                      : yes 
Checking for OpenGL X11 EGL Backend                                       : yes 
Checking for OpenGL without platform-specific code (e.g. for libmpv)      : yes 
Checking for OpenGL context support                                       : yes

**Comment by CounterPillow** [comment]
Can you try with `hwdec=nvdec` instead? Both cuda and nvdec will use the same implementation from what I know, just have different interfaces to access them with, with nvdec supporting EGL properly.

**Comment by philipl** [comment]
Where is the GL context coming from? When you use libmpv, doesn't the embedding app need to provide it?

**Comment by ua0lnj** [comment]
libmpv use with Native window embedding.
App suspended when libmpv started.
This is vdr plugin mpv, https://github.com/ua0lnj/vdr-plugin-mpv
If you know what it is.

**Comment by mc4man** [comment]
It would appear? that your plugin needs gpu-context=x11 which has been disabled (but not removed.
You could,
Take it up with the plugin people
Restore gpu-context=x11, atm it's a simple 2 line edit to wscript
Build libmpv separately using an older version

This issue aside the most likely use of gpu-context=x11 was for users whose nvidia hardware and or driver doesn't support  nv-codec-headers or the version available to them or for others who wish to use vdpau for some reason.
The build: disable GLX  commit has made use of vdpau impossible..
I see no reason not to revert that commit.

**Comment by jeeb** [comment]
You **don't** need to edit the wscript if you want to enable glx. `--enable-gl-x11` should be enough for that to get enabled. If it doesn't, then something is wrong (on more than one level).

But I do not think `gpu-context=x11` is the issue here, or at least I see no clear hint about it.

Currently GLX is disabled by default as nothing else than VDPAU without copy-back as far as I understand requires it any more. This is a hint for people to inform that they have use cases where they absolutely require it.

For VDPAU, we need to think about what is the newest nvidia hardware that **only** supports VDPAU. I think at this point there's been quite a few years since last such piece of hardware was released. Nvidia has clearly signaled that nvdec is the future, and while they did make someone work a bit on VDPAU, many of the new additions/fixes seem to actually not work (or at least I recall people failing when actually testing these additions, although I might be incorrect).

**Comment by ua0lnj** [comment]
So that's the question.
Where did I write about vpau?
I am using hwdec cuda.
Why does mpv work with EGL, but mpvlib does not?

**Comment by ua0lnj** [comment]
If I enable glx with --enable-gl-x11, libmpv and hardware decoder works fine with:
mpv_set_option_string(hMpv, "vo", "gpu");
mpv_set_option_string(hMpv, "hwdec", "cuda");
mpv_set_option_string(hMpv, "gpu-context", "x11");

But with mpv_set_option_string(hMpv, "gpu-context", "x11elg") libmpv and hardware decoder not works.

**Comment by ua0lnj** [comment]
It works. If the program that libmpv is running from uses GLX, libmpv cannot get the EGL context. If you use EGL everywhere, then everything works correctly.
