### ISSUE TITLE
Add HDR passthrough support to gpu-context=drm

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#8219]
### Expected behavior of the wanted feature

HDR passthrough while using `--gpu-context=drm`.

### Alternative behavior of the wanted feature

Tonemapping is all that's available on linux right now.

### Log file

N/A, mpv only supports HDR passthrough on windows

This feature request is hopefully self explanatory. Since linux 5.4 HDR metadata has been supported in DRM, and it is possible to set this metadata and send it directly to the display. This functionality already exists on windows so hopefully it can be extended to DRM. I know that (currently) wayland and Xorg do not have any support for HDR passthrough, so this issue is **not** about full HDR support on linux, just for DRM.

Kodi currently has support for this, and it is used on a lot of *elec distros for HTPCs. See this PR: https://github.com/xbmc/xbmc/pull/16103

**Comment by laichiaheng** [comment]
So we can passthrough HDR in KODI now?

**Comment by laichiaheng** [comment]
It's a big big big news!

**Comment by LaserEyess** [comment]
If by "now" you mean "over a year ago", yes. But only if you're using the DRM backend.

**Comment by laichiaheng** [comment]
> If by "now" you mean "over a year ago", yes. But only if you're using the DRM backend.

How to do that?

**Comment by LaserEyess** [comment]
I don't know I've never used Kodi. This is mpv's issue tracker though, so probably not the best place to ask.
