### ISSUE TITLE
MPV window position does not get remembered when exiting fullscreen mode on Gnome Wayland

### ISSUE THREAD

**Issue by focus64** [mpv-player/mpv#8220]
MPV git master version.

MPV options:
gpu-api=opengl
gpu-conext=wayland

When exiting fullscreen mode on Gnome wayland (3.38.1), MPV window position always gets reset to upper left corner of the desktop, rather than back to its original window position before entering fullscreen mode.

I am on Arch Linux, Intel iGPU.

[mpv.log](http://0x0.st/id88.log)

**Comment by Dudemanguy** [comment]
That's the responsibility of the compositor/window manager. mpv has no code for this.

**Comment by focus64** [comment]
But MPV version 0.32 works fine on Gnome wayland 3.38.1.

**Comment by Dudemanguy** [comment]
If that's true, I don't know what that would occur. In wayland, clients have no way of knowing where they are in the global output. It's impossible for mpv to position itself anywhere. It is entirely on the compositor to position windows.

**Comment by focus64** [comment]
Could it be possible that Gnome wayland uses some info exposed by mpv as the key to remember its window position? If git master version of mpv changes the exposed info (the key) when exiting fullscreen mode, then Gnome may miss the lookup of the original mpv window position.

I have no idea what the exposed info can possibly be. But that may be a clue for mpv authors.

Since version 0.32 works fine. I consider it a regression.

**Comment by Dudemanguy** [comment]
>Could it be possible that Gnome wayland uses some info exposed by mpv as the key to remember its window position?

mpv doesn't expose any info that's not already known to the compositor by virtue of mpv being a wayland client.

>Since version 0.32 works fine. I consider it a regression.

Feel free to bisect it, but it's a GNOME bug.

**Comment by focus64** [comment]
Just bisected it. It's commit 30dcfbc that introduced this behavior. Not sure if it is a Gnome bug or a mpv bug though.

**Comment by Dudemanguy** [comment]
Yeah that's unfortunate. That commit is a workaround a sway bug. There's no reason `wl_surface_commit` should affect the window position, but given that the commit in question is a hack, that's a decent argument to revert it. I'll think about it.

**Comment by focus64** [comment]
Thanks.

**Comment by Dudemanguy** [comment]
Ended up reverting it after all.
