### ISSUE TITLE
Selecting specific display for full screen under Wayland?

### ISSUE THREAD

**Issue by arvidjaar** [mpv-player/mpv#8221]
Using Ubuntu 20.04 with MPV from mc3man mpv-tests repository.

```
[cplayer] mpv git-2020-04-17-a09c769 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Apr 19 20:30:24 UTC 2020
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.42.102
[cplayer]    libavcodec      58.80.100
[cplayer]    libavformat     58.42.100
[cplayer]    libswscale      5.6.101
[cplayer]    libavfilter     7.79.100
[cplayer]    libswresample   3.6.100
[cplayer] FFmpeg version: git-2020-04-18-4457f75
```

I have two monitors (builtin LCD and external HDMI TV) and under X11 use --fs-screen 1 to launch video on full screen TV. I am not sure what is proper syntax under Wayland. Looking in logs, I see:

```
[vo/gpu/wayland] Registered output LGD 0x046d (0x4):
[vo/gpu/wayland] 	x: 0px, y: 0px
[vo/gpu/wayland] 	w: 1920px (310mm), h: 1080px (170mm)
[vo/gpu/wayland] 	scale: 1
[vo/gpu/wayland] 	Hz: 60.020000
[vo/gpu/wayland] Registered output SNY SONY TV (0x5):
[vo/gpu/wayland] 	x: 1920px, y: 0px
[vo/gpu/wayland] 	w: 1920px (1600mm), h: 1080px (900mm)
[vo/gpu/wayland] 	scale: 1
[vo/gpu/wayland] 	Hz: 23.976000
```

so I tried `--fs-screen=5` and it appears to work but results in warning:

```
[vo/gpu/wayland] Reconfiguring!
[vo/gpu/wayland] Screen index 5 not found/unavailable! Falling back to screen 0!
...
[vo/gpu/wayland] Surface entered output LGD 0x046d (0x4), scale = 1
[vo/gpu/wayland] Surface entered output SNY SONY TV (0x5), scale = 1
[vo/gpu] Assuming 23.976000 FPS for display sync.
```

and video plays on TV. I do not mind warning as long as it works, I'm just not sure whether it works as intended or just by accident, nor how stable output numbers are.

If it works as designed, it would be helpful if mpv could list available outputs (as there is no xrandr equivalent for Wayland as yet).

Thank you.

**Comment by Dudemanguy** [comment]
The warning message is your hint there. On wayland, your TV's screen index is 0 so `--fs-screen=0` is what you want here.

**Comment by arvidjaar** [comment]
> On wayland, your TV's screen index is 0 

It was 0, and now it became 1. So the question remains - it is possible to refer to specific display? Because "screen number" does not appear to be persistent. I do not know whether I can rely on it in X11, but so far screen number never changed there.

> It's the job of your compositor to replicate xrandr.

I am not sure what you are trying to say. It is job of kernel to handle DRM, still mpv provides option to list DRM outputs (`--drm-connector=help`). It is job of ALSA/PA to handle audio, still mpv provides option to list available outputs (`--audio-device=help`). What exactly is wrong in providing similar option to list available screens?

**Comment by Dudemanguy** [comment]
I don't believe there's any guarantee in the order in which displays are added. xrandr is a complicated tool that is out of mpv's scope and not particularly relevant here.

>What exactly is wrong in providing similar option to list available screens?

It's not impossible. I'm not sure how applicable this option would be to other platforms though.

**Comment by Akemi** [comment]
would be fine on macOS.

**Comment by arvidjaar** [comment]
Diving a bit deeper.

Wayland does not have any notion of "screen number" (nor has any notion of "screen" for this matter). The "screen number" used by mpv is really just current enumeration order of outputs (wl_output). This can change depending on how composer was started. As example:

Start composer when both internal LCD and HDMI are connected:

```
interface: 'wl_output',                                  version:  2, name:  5
        x: 1920, y: 0, scale: 1,
        physical_width: 1600 mm, physical_height: 900 mm,
        make: 'SNY', model: 'SONY TV',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 1920 px, height: 1080 px, refresh: 23.976 Hz,
                flags: current
interface: 'wl_output',                                  version:  2, name: 28
        x: 0, y: 0, scale: 1,
        physical_width: 310 mm, physical_height: 170 mm,
        make: 'LGD', model: '0x046d',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 1920 px, height: 1080 px, refresh: 60.020 Hz,
                flags: current preferred
```

Unplug HDMI

```
interface: 'wl_output',                                  version:  2, name: 28
        x: 0, y: 0, scale: 1,
        physical_width: 310 mm, physical_height: 170 mm,
        make: 'LGD', model: '0x046d',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 1920 px, height: 1080 px, refresh: 60.020 Hz,
                flags: current preferred
```

Plug HDMI again

```
interface: 'wl_output',                                  version:  2, name: 28
        x: 0, y: 0, scale: 1,
        physical_width: 310 mm, physical_height: 170 mm,
        make: 'LGD', model: '0x046d',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 1920 px, height: 1080 px, refresh: 60.020 Hz,
                flags: current preferred
interface: 'wl_output',                                  version:  2, name: 30
        x: 1920, y: 0, scale: 1,
        physical_width: 1600 mm, physical_height: 900 mm,
        make: 'SNY', model: 'SONY TV',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 1920 px, height: 1080 px, refresh: 23.976 Hz,
                flags: current
```

So HDMI output will have "screen" number 1 in the first case, 0 (and the only) in the second case and 0 in the last case (because mpv is using reverse list to enumerate outputs).

Core Wayland does not offer any way to persistently identify outputs. It is suggested to use xdg_output_manager for this which - according to protocol specification - should provide persistent stable names for available outputs:

```
interface: 'zxdg_output_manager_v1',                     version:  3, name:  6
        xdg_output_v1
                output: 30
                name: 'HDMI-1'
                description: 'Sony SONY TV'
                logical_x: 1920, logical_y: 0
                logical_width: 1920, logical_height: 1080
        xdg_output_v1
                output: 28
                name: 'eDP-1'
                description: 'Встроенный дисплей'
                logical_x: 0, logical_y: 0
                logical_width: 1920, logical_height: 1080
```

As far as I can tell, this is the best we can get without trying to probe connected devices ourselves.

What about generalizing `--drm-connector` option or may be extending `--screen` and `--fs-screen` by allowing specify screens by name? Something like `--fs-screen name:HDMI-1`? This of course will need backend support, but looks general enough to apply to other platforms as well.

Comments? If this has chance to be accepted I probably beef up patch.
