### ISSUE TITLE
--deband=no --cscale=spline36 breaks if video is metadata rotated and in nv12 format

### ISSUE THREAD

**Issue by CounterPillow** [mpv-player/mpv#8223]
### Important Information

Provide following Information:
- mpv version
```
$ mpv --version
mpv 0.32.0-786-gc07089a250 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Oct 26 02:26:28 CET 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.100
   libavformat     58.63.100
   libswscale      5.8.100
   libavfilter     7.88.100
   libswresample   3.8.100
FFmpeg version: N-99733-g7b0d179195
```

- Linux Distribution and Version: Arch Linux, kernel 5.9.2
- Source of the mpv binary: mpv-build
- GPU driver and version: mesa 20.2.1, radeonsi
- Possible screenshot or video of visual glitches

![shot-20201003_142220-0001](https://user-images.githubusercontent.com/308818/97812815-57d88300-1c84-11eb-9e02-c404cc462b30.png)

### Reproduction steps
```
mpv --no-config --profile=gpu-hq --deband=no --hwdec=vaapi sample.mp4
```

Compare to 
```
mpv --no-config --profile=gpu-hq --hwdec=vaapi sample.mp4
```

### Expected behavior

Let me disable memes

### Actual behavior

Chroma plane all messed up

### Log file

https://0x0.st/idAF.log

### Sample files

https://0x0.st/idmr.mp4

**Comment by CounterPillow** [comment]
Looks to be related to `cscale=spline36` and `--gpu-api=opengl`, works fine with vulkan or cscale=bilinear (or, as I said, deband=yes)

**Comment by philipl** [comment]
And specifically for `nv12` format. You can repro with `--vf=format=nv12` and software decoding.

**Comment by philipl** [comment]
```
mpv --no-config --cscale=spline36 --deband=no --vf=format=nv12 sample.mp4
```

**Comment by CounterPillow** [comment]
You should've probably kept in the title that the rotation metadata is relevant, I can't reproduce it with videos that aren't rotated.

**Comment by CounterPillow** [comment]
`--cscale=haasnsoft` or ewa also does not fare much better, but has different artefacting:
![mpv-shot0001](https://user-images.githubusercontent.com/308818/97813351-dd116700-1c87-11eb-9410-87d38b03dff4.jpg)

**Comment by hooke007** [comment]
So far, there is no better way than to change the following three parameters.
--hwdec=no
--cscale=bilinear/bicubic_fast/oversample
--deband=yes

**Comment by hooke007** [comment]
I can confirm it still exist in the win10 and auto-copy. The tags are not accurate.

**Comment by haasn** [comment]
Worth pointing out that this is fixed in `gpu-next`

**Comment by madjxatw** [comment]
> Worth pointing out that this is fixed in `gpu-next`

But `cscale` yet cannot be set individually with gpu-next, it simply takes the setting for `scale`.

**Comment by mdmjmsa** [comment]
any update on this issue?

**Comment by okias** [comment]
I can confirm (Linux 6.5.0-5-amd64)
```
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.1
FFmpeg version: 6.1-5
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

mpv -vo vaapi VID_20231220_133642.mp4
 (+) Video --vid=1 (*) (h264 3840x2160 29.916fps)
[vo/vaapi] OSD format not supported. Disabling OSD.
[vo/vaapi] Warning: this compatibility VO is low quality and may have issues with OSD, scaling, screenshots and more.
[vo/vaapi] vo=gpu is the preferred choice in any case and includes VA-API support via hwdec=vaapi or vaapi-copy.
Using hardware decoding (vaapi).
[autorotate] Video rotation with this format not supported
VO: [vaapi] 3840x2160 vaapi[nv12]
[vo/vaapi] Video is flagged as rotated by 90 degrees, but the video output does not support this.
[vo/vaapi] vaPutSurface() failed (invalid parameter)
[vo/vaapi] vaPutSurface() failed (invalid parameter)
```

`mpv -vo gpu VID_20231220_133642.mp4 --deband=no --cscale=spline36` = greyscale video with color crossing lines
`mpv -vo gpu VID_20231220_133642.mp4 --deband=no --cscale=bilinear` = fine
