### ISSUE TITLE
Cannot compose MPV through Brew for lack of Youtube-dl

### ISSUE THREAD

**Issue by Profitter** [mpv-player/mpv#8224]
==> Downloading https://github.com/ytdl-org/youtube-dl/releases/download/2020.09.20/youtube-dl-2020
#=#=-#  #
curl: (22) The requested URL returned error: 451 Unavailable for Legal Reasons
Error: Failed to download resource "youtube-dl"
Download failed: https://github.com/ytdl-org/youtube-dl/releases/download/2020.09.20/youtube-dl-2020.09.20.tar.gz

I tried installing mpv through Brew. However, youtube-dl was banned from downloading as it was believed to violate the DMCA rules. The installation process just stopped after it detected that youtube-dl cannot be downloaded. Can you update the mirror in the brew for a version without the part of youtube-dl.

**Comment by Akemi** [comment]
we don't have anything to do with homebrew, report that to them.

**Comment by RiCONfru** [comment]
Btw, @Profitter, youtube-dl is still releasing in their official site: http://yt-dl.org/
