### ISSUE TITLE
How to play playlist items in reverse order  ?

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#8228]
Hi,

How can I play playlist items in reverse order with `mpv` : from oldest to newly added ?

**Comment by Akemi** [comment]
no option for that as far as i know. you would need to write a script yourself that manipulates the mpv playlist. there are examples of how to manipulate the playlist in our user script section https://github.com/mpv-player/mpv/wiki/User-Scripts

**Comment by sebma** [comment]
On youtube, on can add `?sort=dd` to the URL :)
On a flat playlist, on can type `mpv $(tac flat_plalist)`

**Comment by poslat-pismo** [comment]
please make it possible to use negative indexes like so
```
--input-commands="playlist-play-index -1"
```

**Comment by stacyharper** [comment]
does anyone already glued up a script for that? a simple bind to reverse the current playlist would be perfect

**Comment by stacyharper** [comment]
for the record: https://git.sr.ht/~stacyharper/dotfiles/tree/1828bdea3db4607d297ea7d219f4894a6a6dbb0c/item/.config/mpv/scripts/reverse-playlist.lua
