### ISSUE TITLE
VoiceMeter Audio and mpv

### ISSUE THREAD

**Issue by cooook1e** [mpv-player/mpv#8230]
Hi, I'm new to mpv and I'm wondering if anyone knows how to set my audio-channel to VoiceMeter automatically because every time I open MPV I have to switch it in windows sound settings.

![3095a03b462a15379d29a412b4a8880d](https://user-images.githubusercontent.com/73973363/98185165-b8a8cb00-1ed1-11eb-9277-8270643d5917.png) 
![3c3635a08f849cf7c73d403a4c6affda](https://user-images.githubusercontent.com/73973363/98185237-d4ac6c80-1ed1-11eb-9ade-b9da31c7b697.png)

"audio-channels=CABLE-B Input(VB-Audio Cable A)" doesn't work.

**Comment by Akemi** [comment]
audio-channels sets the channel layout you want and not an audio-device. use --audio-device instead. --audio-device=help will list all possible devices.

**Comment by cooook1e** [comment]
Where do I go to get the devices listed?

**Comment by cooook1e** [comment]
@Akemi Where do I go to get the devices listed?

**Comment by Akemi** [comment]
i just told you how to do that.

**Comment by cooook1e** [comment]
No bro I don't know WHERE to use it at

**Comment by cooook1e** [comment]
the mvp.conf?

**Comment by cooook1e** [comment]
I just don't know how to get to the command line for mpv that's all

**Comment by oe-d** [comment]
You can easily list, set and cycle audio devices with this script.
https://github.com/oe-d/control

**Comment by Akemi** [comment]
mpv is a command line player. just type "mpv ----audio-device=help " and it will output a list. make sure mpv is in your PATH or navigate into mpv binary containing folder beforehand.
