### ISSUE TITLE
"sub-reload" does not work in C#

### ISSUE THREAD

**Issue by Sunddyy** [mpv-player/mpv#8231]
### Important Information
I am using libmpv to develop a kind of player right now. I want to hide the subtitle and show them freely. By far, I can remove the subtitle with "sub-remove" command in C# , however once I want to display it again with "sub-reload" , failed. 

Development info:
- mpv-1.DLL , downloaded from github, the original file is mpv-dev-x86_64-20201101-git-73be201.7z
- Windows7 pack 1
- mpv-dev-x86_64-20201101-git-73be201.7z 
-VS 2017 community version.

### Reproduction steps
some of  the codes listed below

//the key codes are all from the sample in github 
....
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int MpvCommand(IntPtr mpvHandle, IntPtr strings);
        private MpvCommand _mpvCommand;
...
        private void DoMpvCommand(params string[] args)
        {
            IntPtr[] byteArrayPointers;
            var mainPtr = AllocateUtf8IntPtrArrayWithSentinel(args, out byteArrayPointers);
            _mpvCommand(_mpvHandle, mainPtr);
            foreach (var ptr in byteArrayPointers)
            {
                Marshal.FreeHGlobal(ptr);
            }
            Marshal.FreeHGlobal(mainPtr);
        }

.....

      private void btnShowSub_Click(object sender, EventArgs e)
        {
            Control thisCtrl;
            thisCtrl = (Control)sender;
            String mpvStr = "sub-remove";// Work， it removes the subtile 
            if (thisCtrl.Text == "S-")
            {
                mpvStr = "sub-remove";
                thisCtrl.Text = "S+";
            }
            else
            {
                mpvStr = "sub-reload";// !!!!!!!!!!!! does not work !!!!!!!!!!!!!!!!
                thisCtrl.Text = "S-";
            }
            DoMpvCommand(mpvStr,"1");

        }

### Expected behavior
Show subtitle as normal.
### Actual behavior
No subtitles displayed and no error either.

I think it is a simple issue,but why it does not work. Thank you .

**Comment by guidocella** [comment]
If you removed the subtitle track there is nothing to reload. Try using the command `rescan-external-files` or `sub-add <url>`.
