### ISSUE TITLE
mpv detection of two config files  win10 64bit

### ISSUE THREAD

**Issue by omgbox** [mpv-player/mpv#8232]
### Important Information

i extracted to C:\apps\ created environment for binary, and cmd executed mpv,  now mpv spit out, 2 config detected delete C:\apps bogus, mpv wans to delete C:\apps this folder holds mpv and its files  and there is no config file here, mpv wants to use C:\Users\heroku\AppData\Roaming\mpv , this folder roaming\mpv holds nothing . 
 
mpv-x86_64-20201101-git-73be201.7z  

 

- mpv version below
- Windows Version - mpv-x86_64-20201101-git-73be201.7z  
- Source of the mpv binary - https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- If known which version of mpv introduced the problem , 20201101-git-73be20 and 4-20201101-git-73be201

I'm currently using version, without any issues. 
 mpv 0.32.0-752-g34b8adc456

**Comment by Akemi** [comment]
please don't ignore the issue template. i don't think mpv wants to delete that folder.
