### ISSUE TITLE
Subtitle paragraphs with same timestamps displayed in wrong order

### ISSUE THREAD

**Issue by pcroland** [mpv-player/mpv#8235]
Provide following Information:
- mpv: 20201101
- winver: Win 10 20H2

```
39
00:01:11,720 --> 00:01:15,160
How did he survive

40
00:01:11,720 --> 00:01:15,160
his dual with Moriarty?
```
will be displaed as:
```
his dual with Moriarty?
How did he survive
```

**Comment by Akemi** [comment]
that's most likely an invalid srt. also see https://github.com/mpv-player/mpv/issues/7070
if you want a different behaviour. either open an issue on the ffmpeg tracker an their srt demuxer we use, or libass since we pass the ffmpeg returned ass to it.
