### ISSUE TITLE
Question: Project status?

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#8236]
This issue is not about mpv itself (the code and software suite) but the project.

I recently read that there may have been a change in active developers. May be
wrong or right, I don't know, but truth be told, I am also not really interested in
the WHY. I am more interested in the:

a) status quo

and especially

b) future outlook

Just to clarify: I never had any problem with any mpv dev. No exception to that statement. :)

However had, in particular for b), I sort of transitioned from mplayer to mpv. mpv is, hands down,
better than mplayer IMO. More active too. I still keep mplayer (better to have two players than
just one :P ) but by and large I am mostly using mpv for playing everything. And ffmpeg for
transforming multimedia-related data. And imagemagick for image-related conversions.

On Linux this all works really well; the commandline is sort of my ultimate "benchmark" for
getting things done here. GUIs are nice, I use them too, but I am mostly a commandline
user.

Anyway - back to this question.

Can any of you mpv devs, or casual contributors, perhaps comment on this?

Are there any active devs left? Any specific roadblocks or issues for the project?
I am especially interested in the "future outlook". I am aware that nobody has
a working crystal ball, so speculation is also fine (for me) if it is based on current
evaluation of the context. (This may be obvious for mpv devs, but I am just a
casual mpv guy really, not a mpv dev, and actually just a hobbyist programmer
anyway.)

Thanks for anyone being able to give some helpful context about the project
status as a whole! Again, I am less focused on wanting to know the "behind
the scenes" rumours, I just want to know the health of the project really. And
I have no hidden agenda other than this simple question really. :)

(As nobody wants to leave issues open, perhaps this issue could be left
open for a week or two, to allow for people to chime in, before closing
it? I don't know if github allows an auto-closing option ... if so then I would
set it to, say, something reasonable such as two weeks. Makes no sense
to have it run for months admittedly, since it is only the "current snapshot"
of the project status, and "predictions" to the future, which is always hard.)

(PS: Reddit is unfortunately NOT a hugely reliable source of information,
in my opinion ... there are way too many deliberately wrongful links and
comments made/given. Github issue trackers seem MUCH more reliable,
in my opinion, based on past experience in this regard.)

**Comment by garoto** [comment]
Lurk more.

**Comment by Akemi** [comment]
our main dev and biggest contributor is sadly gone. we still have active developers for all crucial parts and platforms. i don't think we have any major roadblocks. contributions might get slower than before.

**Comment by wm4** [comment]
fuck you

**Comment by wm4** [comment]
fuck you.... don't delete my comments.
fuck you
fuck you

**Comment by CounterPillow** [comment]
FYI, the current account "wm4" is not the original wm4. wm4 deleted his GitHub account, and within minutes some troll from 4chan claimed it and is now using it for trolling. Hence why there's a "deleted a comment from wm4" in this issue now.

**Comment by garoto** [comment]
And btw, this was the contents of the comment by the troll account: https://0x0.st/idhZ.png

**Comment by Akemi** [comment]
yeah great. post a screenshot of the comment i deleted for a reason. thanks.

**Comment by Hrxn** [comment]
*"And, listen kids, this is why you never delete your accounts... you simply just don't use them anymore."*
