### ISSUE TITLE
mpv with hw accel loops between 2-3 frames after changing i3 workspace

### ISSUE THREAD

**Issue by asakura42** [mpv-player/mpv#8238]
Latest mpv from Arch Linux repo. Old laptop with Intel Core i3 and ATI Radeon HD 5650M. Latest xf86-video-ati and many related mesa/vdpau/vaapi stuff. i3wm and Xorg (properly configured with the Archwiki help). So...

With vaapi mpv works good. But when I pause video, change workspace and later come back to mpv's workspace, mpv's window shows part of my previous workspace a couple of seconds and later when I start video, it just cycles between 2-3 frames. But audio and subtitles are okay.

Also I hear how my videocard's fan stops making noise when I change workspace, maybe it's related. Maybe it's not the mpv problem, but this behavior is only in mpv, some games (warsow, for example) work fine when I change workspace while playing.

I run mpv with `DRI_PRIME=1` and have `LIBVA_DRIVER_NAME="radeonsi"` variable in .profile

**Comment by Akemi** [comment]
don't ignore the issue template.
