### ISSUE TITLE
Key bindings using modifier + mouse button not recognised in Wayland

### ISSUE THREAD

**Issue by sammoth** [mpv-player/mpv#8239]
- mpv version - v0.32
- Linux Distribution - Arch
- Source of the mpv binary - Arch official repo
- Window Manager and version - sway v1.5
- GPU driver and version - amdgpu mesa 20.2.1

Under wayland, it looks like keybindings like modifier+mousebtn don't work. For example run

    mpv --no-config --input-test --idle --force-window --gpu-context=wayland

then press shift+left mouse. The OSD will say that only left mouse was pressed. Running

    mpv --no-config --input-test --idle --force-window --gpu-context=x11

will show shift+left mouse is picked up.

[Log](https://0x0.st/idnt.txt)

**Comment by Dudemanguy** [comment]
Yup, you're right. Good catch.
