### ISSUE TITLE
Dropped frames when entering fullscreen mode for the first time

### ISSUE THREAD

**Issue by YhenZN** [mpv-player/mpv#8240]
### Important Information

Provide following Information:
- mpv version

```
mpv 0.32.0-791-g73be20143e Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  1 10:19:46 +08 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.100
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.88.100
   libswresample   3.8.100
FFmpeg version: git-2020-10-31-3da35b7c
```
- Windows Version: Windows 10 20H2
- Source of the mpv binary: shinchiro's sourceforge

### Reproduction steps

`mpv --no-config --scale=ewa_lanczossharp D:\File.mp4`

### Expected behavior

mpv should enter fullscreen mode without dropping any frames, just like with only `--no-config`.

### Actual behavior

The first time entering fullscreen mode, mpv will get stuck for a second and drop ~20-30 frames. After that, entering/exiting fullscreen mode won't cause frame drops anymore.

Not sure if this is a problem on my end but it only happens when using ewa_*, jinc and haasnsoft as scaler.

[mpv.log](https://github.com/mpv-player/mpv/files/5502781/mpv.log)

**Comment by Akemi** [comment]
please, also post a log file like the issue template asks for.

**Comment by sammoth** [comment]
Have you tried setting `gpu-shader-cache-dir`

**Comment by Akemi** [comment]
no reply. if the problem still persists with `gpu-shader-cache-dir` please open a new issue.
