### ISSUE TITLE
mpv 0.32.0 stable play tls m3u8 error ,but vlc work

### ISSUE THREAD

**Issue by obama88** [mpv-player/mpv#8242]
C:\Users\XXX\Downloads\PortableApps\PortableApps\SMPlayerPortable\App\SMPlayer\mpv> ./mpv                         

 mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 12:29:32 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.36.100
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-26-5e6210015

C:\Users\XXX\Downloads\PortableApps\PortableApps\SMPlayerPortable\App\SMPlayer\mpv> ./mpv "https://www.nmgxwhz.com:65/20200309/ZAThMRPP/index.m3u8"

[ffmpeg] tls: handshake failed: error:14FFF3E7:SSL routines:(UNKNOWN)SSL_internal:unknown failure occurred
Failed to open https://www.nmgxwhz.com:65/20200309/ZAThMRPP/index.m3u8.
[ytdl_hook]
[ytdl_hook] youtube-dl failed: not found or not enough permissions

**Comment by CounterPillow** [comment]
This is a problem with your build of mpv, specifically the TLS library it links against.
