### ISSUE TITLE
Warning if the binary is not in the config dir

### ISSUE THREAD

**Issue by PalmtopTiger** [mpv-player/mpv#8244]
The directory where the binary is located does not contain portable_config directory or any .conf files: [listing.txt](https://github.com/mpv-player/mpv/files/5504784/listing.txt)

mpv just checks if the binary parent directory exists and prints a warning about it.

https://github.com/mpv-player/mpv/blob/dfa5ae2ad61cba4fab850a41779ce95332c27935/player/configfiles.c#L68-L74
https://github.com/mpv-player/mpv/blob/9a1942ac95484a277239de1068801342754c079a/osdep/path-win.c#L93-L94

### Important Information

Provide following Information:
- mpv version: 0.32.0-791-g73be20143e
- Windows Version: Windows 7 SP1 x64
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- If known which version of mpv introduced the problem: 22a27c6720244dd24c9b704c8a8225ca1665272f

### Reproduction steps

Place the config files in AppData/mpv and the binary somewhere else.

### Expected behavior

No warning if the binary is not in the config dir.

### Actual behavior

> Warning, two config dirs found:
>    C:\Users\Андрей\AppData\Roaming/mpv (main)
>    D:/Tools/mpv (bogus)
> You should merge or delete the second one.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5504736/output.txt)

**Comment by bitraid** [comment]
This started happening with aa18a8e1cde663caeabd93af7d57a745c1a76af6, which reverts c3694f0acb7f71daac7606fafbadcb7b500ca35e.
