### ISSUE TITLE
Subtitle moving up and down does not work after reverting from overriding user style

### ISSUE THREAD

**Issue by ldzhjn** [mpv-player/mpv#8250]
mpv version being used is the latest version by shinchiro available here
OS: Windows 10
Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
Unknown which version introduced the problem, but I can confirm the recent versions all had this issue.

### Reproduction steps

Load an ass subtitle, press "u" to override user style.
Now subtitle position can be moved up and down using "r" and "t".
Press "u" again to revert override user style.
Now subtitle position can not be moved up and down using "r" and "t".

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/5506128/output.txt)

**Comment by Akemi** [comment]
still works for me. if this issue still persists please open a new issue with proper reproduction steps, especially a example file.
