### ISSUE TITLE
Scripts in folders are not loaded

### ISSUE THREAD

**Issue by RicBent** [mpv-player/mpv#8252]
### Environment
- mpv version: 0.32.0
- Linux Distribution and Version: Manjaro 20.2 Nibia
- Source of the mpv binary: Manjaro repositories
- Window Manager and version: kwin 5.20.2 (X11)

### Reproduction steps

Put any functional script (C/LUA/JS) into a folder and rename it to main.so/lua/js.
See: https://mpv.io/manual/master/#script-location

### Expected behavior

Script should be loaded.

### Actual behavior

Script isn't loaded.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5507018/output.txt)

### Sample files

Applies to every input file.

**Comment by avih** [comment]
Well, it looks at the three script locations and doesn't find anything...
```
[   0.430][d][global] config path: 'scripts' -> '/home/bent/.config/mpv/scripts'
[   0.430][d][ytdl_hook] loading mp.defaults
[   0.430][d][global] config path: 'scripts' -/-> '/home/bent/.mpv/scripts'
[   0.430][d][console] loading mp.defaults
[   0.430][d][global] config path: 'scripts' -/-> '/etc/mpv/scripts'
```

Do you have any scripts there?

**Comment by RicBent** [comment]
Yeah I usually got a script called subs2srs.lua there that works. I moved it to /home/bent/.config/mpv/scripts/subs2srs/main.lua to reproduce the issue.

**Comment by avih** [comment]
> I moved it to /home/bent/.config/mpv/scripts/subs2srs/main.lua to reproduce the issue.

Your version (0.32) doesn't support directory scripts.

> See: https://mpv.io/manual/master/#script-location

This is a link to master - towards 0.33. You should look at your manual page which documents 0.32.

**Comment by RicBent** [comment]
Oh, thanks a lot!
