### ISSUE TITLE
MPV does not start with system gamma value

### ISSUE THREAD

**Issue by shag00** [mpv-player/mpv#8255]
### Important Information

Provide following Information:
- mpv version: 4.2.4
- Linux Distribution and Version: Kubuntu 20.04
- Source of the mpv binary: this site
- If known which version of mpv introduced the problem: current version
- Window Manager and version: KDE Plasma Version: 5.18.5, KDE Frameworks Version: 5.68.0
- GPU driver and version: Nvidia 450 meta package
- Possible screenshot or video of visual glitches: not really necessary, in dark scenes cannot see much, with desired gamma you can.

### Reproduction steps

Turn the PC off then turn it on again and open MPV.

### Expected behavior

That the gamma value set in Kubunutu, system settings>display & monitor>gamma would be used.

### Actual behavior
A different gamma value is used, I suspect 1.00.
Just opening system settings>display & monitor>gamma without making any changes and then closing the window
will make MPV use the desired gamma setting.

### Log file
[mpv.txt](https://github.com/mpv-player/mpv/files/5516339/mpv.txt)

**Comment by Akemi** [comment]
if the problem still persists please open a new issue. also the log here doesn't show problem i would say. since it didn't even try to initialise a vo.
