### ISSUE TITLE
What is the CLI option to skip videos in a youtube playlist that return "Failed to recognize file format." ?

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#8256]
Hi,

What is the CLI option to skip videos in a youtube playlist that return `Failed to recognize file format.` ?

**Comment by CounterPillow** [comment]
I'm fairly certain that the default behaviour already is that videos that fail to load are skipped.

**Comment by sebma** [comment]
@CounterPillow I guess you're right, since the `youtube-dl` has now been taken down by YouTube (:sob:), it's no more updated.

I've justiced `youtube-dl` (latest version : 2020.09.20) returns to `mpv` an empty playlist : 
```
$ mpv https://www.youtube.com/playlist?list=PLRv5TPGK6KtxYD43zj1_f3lWKCrMkDZzo
[ytdl_hook] Got empty playlist, nothing to play. 
Failed to recognize file format.


Exiting... (Errors when loading file)
$
```

**Comment by CounterPillow** [comment]
> has now been taken down by YouTube

no, it hasn't been. The legal notice was sent by the RIAA, not by YouTube. And downloads are still up from the official website: http://youtube-dl.org/

**Comment by sebma** [comment]
> > has now been taken down by YouTube
> 
> no, it hasn't been. The legal notice was sent by the RIAA, not by YouTube. And downloads are still up from the official website: http://youtube-dl.org/

Thanks man :+1:  I'm going to download yt-dl v2020.11.12 right-away :smile:

**Comment by sebma** [comment]
@CounterPillow With the latest `youtube-dl`, `mpv` can now play youtube playlists fine just like it used to :smile:
