### ISSUE TITLE
Command 'playlist-play-index' not found.

### ISSUE THREAD

**Issue by enthus1ast** [mpv-player/mpv#8258]
I'm writing a console player that uses mpv as its audio/video backend.
I'm communication with mpv via its c api (through a Nim wrapper).

To choose songs from the internal playlist i send:

```
"playlist-play-index" "1"
```

on windows it works fine with version:

```
mpv 0.29.0-280-gdd83b66652 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sat Mar 16 10:30:45 DST 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.47.103
   libavformat     58.26.101
   libswscale      5.4.100
   libavfilter     7.48.100
   libswresample   3.4.100
ffmpeg version: N-45276-g6cfa173303
```

however on linux (tried with the shipped version of mpv on raspbian and archlinux)
with version:

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.6-1~deb10u1+rpt1
```

"playlist-play-index" is not recognized any more.

I've searched through the issues and changelogs but i cannot find any info about this change.

is "playlist-play-index" gone? If yes, what is the replacement?

Please also see my attached logfile from the raspbian box.

### Log file

[mpv_logfile.txt](https://github.com/mpv-player/mpv/files/5526632/mpv_logfile.txt)

**Comment by sfan5** [comment]
`playlist-play-index` was added after mpv 0.32.0, it is not present in your 0.29.1 build.
You can set `playlist-pos` to achieve the same on older versions.

**Comment by enthus1ast** [comment]
thank you @sfan5 , strange that the windows version is `mpv 0.29.0-280-gdd83b66652`

**Comment by enthus1ast** [comment]
@sfan5 

i tried sending both commands, but both are not valid, any idea?
```
[  43.622][e][main] Command 'playlist-play-index' not found.                                                                                                                                                       [  43.622][e][main] Command 'playlist-pos' not found.    
```

**Comment by enthus1ast** [comment]
ahh `playlist-pos` is a property, not a command.
Got it, works. Thanks again.
