### ISSUE TITLE
mpv/youtube-dl can't play youtube playlists

### ISSUE THREAD

**Issue by Nixie722** [mpv-player/mpv#8259]
### Important Information
- mpv version: 0.32.0-796-g790647314c
- youtube-dl version: 2020.11.01.1
- Windows Version: 10.0.19041 Build 19041
- Source of the mpv binary: mpv.io

### Reproduction steps
`$ mpv https://www.youtube.com/playlist?list=PL9D478540A2B59FF4` results in `Failed to recognize file format` error.

However, playing individual youtube videos and streams work just fine.

### Log file
-`$ mpv -v -v` [pastebin](https://pastebin.com/7Qkqwrq8)
-`$ mpv -msg-level=ytdl_hook=debug` [pastebin](https://pastebin.com/1A7iDzc8)

### What I've tried
- remove mpv completely from system and download it again
- remove youtube-dl.exe and install it via pip
- use `updater.bat`
- run mpv without config via `$ mpv --no-config`
- change location of mpv

**Comment by sfan5** [comment]
You will find that `youtube-dl -J 'https://www.youtube.com/playlist?list=PL9D478540A2B59FF4'` also fails to extract any videos.
Not an mpv bug.

**Comment by Nixie722** [comment]
Thanks for clarification, sucks that youtube-dl repository was taken down. 
And thanks for your time.

**Comment by wiiaboo** [comment]
Nothing to do with youtube-dl either. Youtube was broken for hours yesterday.

**Comment by Nixie722** [comment]
@wiiaboo unrelated, youtube-dl is still unable to download playlists for me. This issue persist and was created before the youtube redirector SSL problem yesterday. I found a workaround by using youtube-dlc.exe from blackjack4494/yt-dlc and renaming it to youtube-dl.exe.
