### ISSUE TITLE
MPV keeps creating a directory in AppData\Roaming and then warns me about two config dirs

### ISSUE THREAD

**Issue by Anton1699** [mpv-player/mpv#8262]
### Important Information

Provide following Information:
mpv version 0.32.0-810-gf85de9e6d6
Windows 8.1 Pro 64-bit
Built using the media-autobuild-suite

### Reproduction steps

Running mpv with the configuration files in the same directory as the binary

### Expected behavior

MPV uses the configuration files

### Actual behavior

MPV uses the configuration files, but also creates a directory in C:\Users\User\AppData\Roaming\ and then complains that it finds two directories and suggests I delete one of them.

### Log file

https://pastebin.com/84abQfVU

**Comment by garoto** [comment]
Can reproduce. I'm assuming it's a side effect of all the recent 'deprecate XDG' and the subsequent 'Revert XDG deprecation' snafu.

**Comment by bitraid** [comment]
This is the same message as in #8244 (and #8232). @jeeb I have confirmed that reverting aa18a8e1cde663caeabd93af7d57a745c1a76af6 (bringing back c3694f0acb7f71daac7606fafbadcb7b500ca35e, 688251bc662c50bc7fe56bb1ec8fef4e1407cdf0) fixes the issue.

**Comment by jeeb** [comment]
@bitraid yup, that was a mistake. Sorry for not noticing this as part of taking that config location switch-back pull request in. :)
