### ISSUE TITLE
Integration with youtube-dlc

### ISSUE THREAD

**Issue by sclel016** [mpv-player/mpv#8264]
### Important Information

Provide following Information:
- mpv version: 0.32
- Linux Distribution and Version: Fedora 33
- Source of the mpv binary: /usr/bin/mpv
- Window Manager and version: Swaywm v1.5

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
`mpv --no-config ytdl_path=/usr/bin/youtube-dl <youtube link>`
`mpv --no-config ytdl_path=/usr/bin/youtube-dlc <youtube link>`

### Expected behavior
Video plays in mpv.

### Actual behavior
```
[file] Cannot open file 'ytdl_path=/usr/bin/youtube-dl': No such file or directory
Failed to open ytdl_path=/usr/bin/youtube-dl.
```

youtube-dl works fine if I don't specify the `ytdl_path`, however I'm migrating to `youtube-dlc` fork and would like to specify the path to the forked version.

**Comment by garoto** [comment]
Only mpv builds starting from [October 28](https://github.com/mpv-player/mpv/commit/ad1ecd4350efe5580d1b1b56ebb8012df0dd93e6) have support to specifying a custom pathname to a `yt-dl` binary, and that should be made via passing an `script-opts` option to `ytdl_hook.lua`, e.g.: `--script-opts=ytdl_hook-ytdl_path=C:/BIN/ytdlc`.

Also, your tentative option syntax would fail regardless.

**Comment by deus0ww** [comment]
ytdl_path is a script option. [https://mpv.io/manual/master/#options-script-opts](https://mpv.io/manual/master/#options-script-opts)

`--script-opts=ytdl_path=...`

**Comment by sclel016** [comment]
Thanks for the info about the syntax, it wasn't clear to me (even after reading the documentation) what the proper syntax would look like for the override. I'll try a fresh build of mpv and see if I can get it working with the proper command.

Would the following syntax be correct in `mpv/mpv.conf`?
`script-opts=ytdl_hook-ytdl_path=<path>`

**Comment by garoto** [comment]
> Would the following syntax be correct in `mpv/mpv.conf`?
> `script-opts=ytdl_hook-ytdl_path=<path>`

Yes, the `mpv.conf` syntax of the option looks correct to me.

**Comment by sclel016** [comment]
Thanks!
