### ISSUE TITLE
Delaying playback

### ISSUE THREAD

**Issue by NullVSNone** [mpv-player/mpv#8269]
I know there's an older question: https://github.com/mpv-player/mpv/issues/4120

That got an answer where you can add `pause=yes` to the config.

Is there any way to do it from the terminal? Like:

```
mpv -delay=1000 test.mp4
```

That delays playback by 1000ms?

**Comment by Akemi** [comment]
it's still exactly like mentioned in that issue. you have to write script for it.

**Comment by NullVSNone** [comment]
@Akemi So there's nothing that can be done like `--audio-delay` and then compounding it with `--video-sync`?

**Comment by Akemi** [comment]
just try it instead of asking. there are not that many combinations.

tldr, no.
