### ISSUE TITLE
windowed mode broken on Ubuntu MATE

### ISSUE THREAD

**Issue by catharanthus** [mpv-player/mpv#8270]
### Important Information

Provide following Information:
- mpv version: current master (f85de9e6d6d2785b0a40af052d245e07e2ae14c5)
- Linux Distribution and Version: Ubuntu MATE 18.04
- Source of the mpv binary: built with mpv-build
- If known which version of mpv introduced the problem: c1d744328e737fe80ecfdc0cbb6260d7699f4328
- Window Manager and version: Marco 1.20.1
- GPU driver and version NVIDIA 450.80.02
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1) Set the display resolution to 1920x1080.
2) Open any video file with 1920x1080 native resolution in mpv.

### Expected behavior

mpv starts in windowed mode, then the F hotkey can be used to switch between windowed and fullscreen modes.

### Actual behavior

mpv starts in fullscreen mode, cannot be switched to windowed mode.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5542093/mpv.log)

### Sample files

Any 1920x1080 video file will work.

**Comment by mc4man** [comment]
With all the ubuntu's I have I usecompiz so that little bit of code doesn't seem to matter on way or the other. 
With all the WM's around I wouldn't know which way is the greater good ..
If you need to mitigate the current behavior in mpv.conf try a autofit-larger option, a value of 96-98 should work.
ex.  autofit-larger=96%

**Comment by catharanthus** [comment]
> With all the ubuntu's I have I use compiz so that little bit of code doesn't seem to matter one way or the other.
> With all the WM's around I wouldn't know which way is the greater good ..
> If you need to mitigate the current behavior in mpv.conf try a autofit-larger option, a value of 96-98 should work.
> ex. autofit-larger=96%

autofit-larger option works, thanks. Still, this behavior seems a bit counterintuitive. Is there any way to add a workaround based on WM detection?

I tried compiz, and the problem doesn't manifest with it. But for some reason compiz is noticeably more buggy than marco on my machine.

**Comment by catharanthus** [comment]
By the way, the commit introducing this problem problem is quite simple: c1d744328e737fe80ecfdc0cbb6260d7699f4328. Unfortunately just reverting it won't work since it will cause some problems with IceWM, apparently.

**Comment by Dudemanguy** [comment]
I tried marco 1.27.0 and couldn't reproduce so I will assume mate fixed this.
