### ISSUE TITLE
Audio clipping with specific files

### ISSUE THREAD

**Issue by HybridDog** [mpv-player/mpv#8271]
I noticed that there exist audio files in mp3 and opus format which after decoding have samples with an amplitude bigger than one. When I open these files in mpv, I can hear clipping even if I reduce the output volume. 
Audacious supports a ReplayGain setting to reduce the amplitude, which helps against hearable clipping.
In mpv I have tried the settings `--af=format=float`, `--replaygain-fallback=-20`, `--replaygain-clip=yes`, `--ad-lavc-downmix=yes` and `--audio-normalize-downmix=yes`, but they did not help.
Is there a setting to avoid clipping which I couldn't find yet?

Here's an example file which causes clipping for me and additional flac files for reference: [opus_file_clipping.zip](https://github.com/mpv-player/mpv/files/5542471/opus_file_clipping.zip)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5542475/output.txt)

**Comment by nemya9066** [comment]
Same issue I would like to add that for me files having this problem play fine with vlc so it definitely have to do with mpv or maybe ffmpeg as I heard vlc use their own decoders.

**Comment by sammoth** [comment]
This might be due to the same reason I noted in [this issue's comments.](https://github.com/mpv-player/mpv/issues/8267) mpv seems to apply replay gain by adjusting the output's volume. If the output doesn't accept floating point input, the audio could be clipped before reaching the replay gain adjustment.

**Comment by richardpl** [comment]
> Same issue I would like to add that for me files having this problem play fine with vlc so it definitely have to do with mpv or maybe ffmpeg as I heard vlc use their own decoders.

Nonsense. VLC uses ffmpeg decoders.
