### ISSUE TITLE
weird behavior after cropping a video in fullscreen mode(wayland)

### ISSUE THREAD

**Issue by shabahengam** [mpv-player/mpv#8274]
### Important Information

Provide following Information:
- mpv version: 
```
mpv fd48f0b Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 10 01:24:46 +0330 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.101
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.89.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-09-d2dcb113
```
- Linux Distribution and Version: `Void Linux, Kernel 5.8.18`
- Window Manager and version: `sway 1.5, wayland 1.18, wlroots 0.11`
- GPU driver and version:  `Intel, i915`
- Possible screenshot or video of visual glitches
1.
![glitch](https://user-images.githubusercontent.com/53096747/99196832-0364f580-27a4-11eb-8cce-aff182d109f4.jpg)

2.

![glitch2](https://user-images.githubusercontent.com/53096747/99196834-065fe600-27a4-11eb-8043-71ee320c6f20.jpg)

### Reproduction steps

1.use [this script ](https://github.com/occivink/mpv-scripts/blob/master/scripts/crop.lua)
2.go to fullscreen mode
3.crop a part of video and return to window mode

### Expected behavior

mpv window size should be the size of the cropped part.
for example if the cropped region is 400x400 then mpv window size should be that size,IMO.

### Actual behavior

1.mpv window get transparent.(look at the picture 1 )
2.and sometime the video get out of the mpv window (look at the picture 2)

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/5543112/log.txt)

**Comment by Dudemanguy** [comment]
Ah, yeah I think this is a sway bug. mpv's window size is correct, but sway's borders still think it should be the size of the video's original dimensons. There used to be a workaround for this actually, but said workaround caused weird behavior in gnome/mutter so it got removed. I'm not really happy with the way it currently is, but I haven't thought of a workaround that doesn't cause breakage somewhere.

Related: https://github.com/swaywm/sway/issues/3029

**Comment by Dudemanguy** [comment]
This is fixed by https://github.com/swaywm/sway/pull/5812 btw.

**Comment by Dudemanguy** [comment]
Just fixed upstream.
