### ISSUE TITLE
Will there be improvement to the Subtitle for MPV?

### ISSUE THREAD

**Issue by AsrielDewitt** [mpv-player/mpv#8276]
https://youtu.be/QvO8kcWFFT0

using the video above as an example, the English subtitle has features such as text alignment, coloring, and text resize. All by the subtitle itself. 

Will MPV have these for it's subtitle in the future?

**Comment by v-fox** [comment]
Not sure where the example part supposed to be… unless you mean [Youtube player's subtitles](https://en.wikipedia.org/wiki/WebVTT). mpv always supported pretty much all subtitle formats there are and there is nothing fancier than "[SubStation Alpha](https://en.wikipedia.org/wiki/SubStation_Alpha)" made with [Aegisub](https://en.wikipedia.org/wiki/Aegisub) which make Youtube subtitles look as pathetic as DVD's & BluRay's trashy, hardcoded, raster bitmaps.

**Comment by wiiaboo** [comment]
This is not up to mpv, open feature requests in ffmpeg's bug tracker to request those WebVTT features.
