### ISSUE TITLE
Can I get the filename from MPV_EVENT_END_FILE?

### ISSUE THREAD

**Issue by btx638** [mpv-player/mpv#8282]
I would like to know the name of the ending file or the file path.

**Comment by Akemi** [comment]
`X show_text "${filename}"` keybindig for example. for the rest read the docs, please.

**Comment by btx638** [comment]
Can add a item called filename to struct mpv_event_end_file ?

like:

typedef struct mpv_event_end_file {
    int reason;
    int error;
    int64_t playlist_entry_id;
    int64_t playlist_insert_id;
    int playlist_insert_num_entries;
   const char *filename;
} mpv_event_end_file;
