### ISSUE TITLE
mpv: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pmuybae** [mpv-player/mpv#8285]
### Important Information

Provide following Information:
- mpv version: mpv-1:0.32.0-5
- Linux Distribution and Version: Manjaro Cinnamon (Rolling)
- Source of the mpv binary: Manjaro repositories
- If known which version of mpv introduced the problem: mpv-1:0.32.0-5 (probably updated before that around 3 months ago)
- Window Manager and version: Mutter **(Muffin)**
- GPU driver and version: 
```
26:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev c7)
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Radeon RX 480
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

### Reproduction steps

Running any mpv command will show this error for me. This includes `mpv --no-config` and `mpv -v`

### Expected behavior
mpv to open

### Actual behavior
`mpv: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory`

### Log file

Crashes before making a log file.

**Comment by sfan5** [comment]
Ask your distributions to recompile mpv or one of its depending packages (off the top of my head libplacebo or shaderc might depend on glslang).

**Comment by pmuybae** [comment]
I've done a full recompile and still have the issue.

**Comment by sfan5** [comment]
Find the dependency that has the missing library and recompile it, `readelf -d` and `ldd` can help.
