### ISSUE TITLE
Digital Rights Management (DRM) content

### ISSUE THREAD

**Issue by jrmzlara** [mpv-player/mpv#8286]
Is there support from mpv to play protected content (DRM E. g. Widevine)?

**Comment by haasn** [comment]
`--demux-lavf-o=decryption_key=<key>` should work. I'm assuming you already have the decryption key. (But if not, [there are browser extensions](https://www.google.com/search?hl=en&q=widevine%20l3%20decryptor) that help you extract them from Widevine-protected websites.)

**Comment by abderrahmanesaad** [comment]
> `--demux-lavf-o=decryption_key=<key>` should work. I'm assuming you already have the decryption key. (But if not, [there are browser extensions](https://www.google.com/search?hl=en&q=widevine%20l3%20decryptor) that help you extract them from Widevine-protected websites.)

i got multiple decryption_key how to us them waiting for answer

**Comment by Akemi** [comment]
the question has been answered. the last question is something that should be asked on ffmpeg support..

**Comment by CounterPillow** [comment]
@Shuggy999 It's `--demuxer-lavf-o`, not `demux`.

**Comment by Shuggy999** [comment]
Thnak you
