### ISSUE TITLE
reset-on-next-file=volume does not reset output volume

### ISSUE THREAD

**Issue by e5150** [mpv-player/mpv#8287]
### Important Information

- mpv version: 0.32.0-819-g24d6961833
- Linux Distribution and Version: slackware 14.2
- Source of the mpv binary: git repo
- If known which version of mpv introduced the problem b74c09efbf7c6969fc053265f72cc0501b840ce1
- Window Manager and version: i3 4.18
- GPU driver and version: N/A
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps
Run: `mpv --no-config --volume=20 --reset-on-next-file=volume <files ...>`, change volume, and skip to next file

### Expected behavior
Volume to be reset to 20 on next file

### Actual behavior
The output volume is stuck at the value set manually during last file. Though it seems to be reset internally since volume changes starts off from 20, but it needs to be adjusted before the actual output volume is affected.

### Log file
[output.txt](https://0x0.st/i5yA.txt)

### Sample files

N/A

**Comment by emanuelserpa** [comment]
Confirm this problem
