### ISSUE TITLE
screenshot get wrong picture when use vo=gpu and rotate

### ISSUE THREAD

**Issue by zhuyuliang045** [mpv-player/mpv#8291]
**Important Information**

- mpv version: 0.29.1

- Linux Distribution and Version: uos 4.19.67-13eagle

- Source of the mpv binary: ubuntu repo

- GPU driver and version: N/A

- Possible screenshot or video of visual glitches: N/A

- Reproduction steps

- Run: mpv --vo=gpu --video-rotate=90 <files ...>, change volume, use the shortcut key 's' to take a screenshot,

- Expected behavior

a distorted image

**Comment by zhuyuliang045** [comment]
mpv version 0.29.1
Open a video with mpv --vo=gpu --video-ratote=90 
When I use the shortcut key s to take a screenshot, I get a distorted image.

**Comment by CounterPillow** [comment]
> mpv version 0.29.1

Please update. And don't ignore the issue template.
