### ISSUE TITLE
Error parsing option ytdl-raw-options (option not found) and no javascript user script support

### ISSUE THREAD

**Issue by Rom888** [mpv-player/mpv#8297]
Hi everybody!
I tried to add javascript user script and got the error: "Can't load unknown script"
After reading this issue: https://github.com/mpv-player/mpv/issues/5348
I realized, that my mpv build (ubuntu focal standart PPA) was not compiled with javascript support.

I tried using this recomended PPA:
https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests?field.series_filter=focal
It has javascript support, but I got  error:
Error parsing option ytdl-raw-options (option not found)

mpv version
mpv 0.33.0-1-gfa7afc3e19

Linux Distribution and Version
ubuntu 20.04 focal

Source of the mpv binary
sudo add-apt-repository ppa:mc3man/mpv-tests
sudo apt install mpv

### Reproduction steps
```mpv --ytdl-raw-options='playlist-end=5' ${url}```

### Expected behavior
no errors

### Actual behavior
Error parsing option ytdl-raw-options (option not found)
Setting commandline option --ytdl-raw-options=playlist-end=5 failed.
Exiting... (Fatal error)

### Log file

https://gist.github.com/Rom888/2628cb4715e805df5d799f31d556d9f7#file-mpv-text

**Comment by sfan5** [comment]
I don't see the error you are mentioning it your log file at all.

**Comment by CounterPillow** [comment]
The ytdl hook requires Lua. You built without Lua support.
