### ISSUE TITLE
The ability to move the video window disappears occasionally

### ISSUE THREAD

**Issue by Argon-** [mpv-player/mpv#83]
Just some minor change I noticed, not a real bug but I doubt it's intentional. :)

I'm using mpv @ bb569b56de1a8abd637772aaa584ade8abfda6ad and in earlier versions I could drag the video window around by clicking (and holding) a random spot inside the video window. In said release, this stops working after switching to fullscreen and back (no OSX native fs) until I resize the window.
It doesn't matter if the video is started from bash or via the app bundle.
Moving the video window through the title bar is not affected.

**Comment by vitorgalvao** [comment]
@pigoz Has this change been reintroduced? I’ve noticed that I also cannot drag the window anymore.

Currently on `mpv` version `0.7.2`, installed via `homebrew` with no specified flags, from [the official repo](https://github.com/mpv-player/homebrew-mpv). OS X Yosemite `10.10.1`.

**Comment by wm4** [comment]
0.7.2 is not supported anymore, for all practical purposes.

Try git master.

**Comment by vitorgalvao** [comment]
@wm4 Alright; will wait for the new release and report back if the problem persists, then. Thank you.

**Comment by pigoz** [comment]
I am using master and it works normally (the only non draggable part is the OSC).

**Comment by vitorgalvao** [comment]
Good to know; thank you.
