### ISSUE TITLE
Possible usage of null pointer in wayland_common.c

### ISSUE THREAD

**Issue by qarmin** [mpv-player/mpv#8302]
`wl->current_output` is chcked if is equal to null

https://github.com/mpv-player/mpv/blob/fa7afc3e19acffd3198fdc8fddb671013a337b05/video/out/wayland_common.c#L1407-L1417

but later is used without checking, which may use invalid memory
https://github.com/mpv-player/mpv/blob/fa7afc3e19acffd3198fdc8fddb671013a337b05/video/out/wayland_common.c#L1420

**Comment by CounterPillow** [comment]
If you read `find_output` you'd realise that this if clause actively sets `wl->current_output`, in fact you'd realise this if you read the code of the if body, which also makes use of `wl->current_output` without any further checks after calling `find_output`. If `find_output` does not find any output, the return within that if body is triggered.

Non-issue, can be closed, reporter should verify output of static analyzers.

**Comment by Dudemanguy** [comment]
Yes, having no `wl->current_output` is a hard error like it should be. I don't believe there's any issue here.
