### ISSUE TITLE
Possible usage of null pointer `mpi` in vo_sixel.c

### ISSUE THREAD

**Issue by qarmin** [mpv-player/mpv#8303]
In line 333 is `mpi` checked if is equal to null, but a little before is used(322,323)
https://github.com/mpv-player/mpv/blob/959097c880d9dcf83cb2edbdf8a2403ae997f713/video/out/vo_sixel.c#L322-L333

**Comment by avih** [comment]
That code is copied from vo_sixel.c where it can indeed be NULL on resize. As far as I know it can't be NULL for sixel, and so this check is redundant, for now.

**Comment by avih** [comment]
However, if you know of an actual condition which can lead to this code used with NULL mpi, then please give an example, at which case - yes, it should be checked elsewhere too.

**Comment by avih** [comment]
The condition was redundant when this issue was opened, but after 9e41102ec5 it's not redundant anymore, e.g. when there's no video frame but we do render the OSD.

Thanks for the report.
