### ISSUE TITLE
Latest MPV buld with javascript and --ytdl-raw-options for ubuntu 20.04 focal

### ISSUE THREAD

**Issue by Rom888** [mpv-player/mpv#8305]
Could anybody suggest a MPV build for Ubuntu 20.04 focal which supports both javascript userscript and --ytdl-raw-options?

I tried:

```
sudo apt install mpv
Installed: 0.32.0-1ubuntu1
http://archive.ubuntu.com/ubuntu focal/universe amd64 Package

RESULT: build without javascript support
Error: Can't load unknown script: /home/rom/.config/mpv/scripts/keybind.js
```

then:

```
sudo add-apt-repository ppa:mc3man/mpv-tests
sudo apt install mpv
Installed: mpv 0.33.0-1-gfa7afc3e19
https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests?field.series_filter=focal

RESULT: built without Lua support
Error parsing option ytdl-raw-options (option not found)
```

**Comment by avih** [comment]
mpv doesn't distribute buids, and the links are by community members.

You should probably report the issue to @mc4man , or you can try to build it yourself.

I believe previous builds at this PPA did include lua, so I'm guessing it's a temporary issue which should be fixed soon.

**Comment by mc4man** [comment]
"Installed: mpv 0.33.0-1-gfa7afc3e19"
Don't know where you got that mpv from but it's not from my ppa (mpv-tests) as last build was 
mpv (2:0.32.0+git7~focal1) , i.e git-2020-10-128-73be201, and lua is certainly enabled

**Comment by Rom888** [comment]
Ou, thanks for the help!
I tried ppa:mc3man/mpv-tests again and it works like a charm!!!
It looks like mpv started from /usr/local/bin/mpv before (where I tried to build myself).

MPV is a really great product!
