### ISSUE TITLE
Don't deprecate --cache-secs

### ISSUE THREAD

**Issue by CrossRoast** [mpv-player/mpv#8306]
Please, don't deprecate the --cache-secs option. When using mpv on files in a NAS --demuxer-max-bytes limits how much memory you're prepared to use on mpv and --cache-secs can set the number of seconds that's enough. The main reason to cache content is to smooth out network latency and latency is measured in units of time. Having an option to limit cache in units of time is preferable.

**Comment by tomty89** [comment]
Couldn't agree more.

> This option is considered useless, since there is no good reason to limit the cache by time

Think about audio-only files v.s. (HD) video. `demuxer-max-bytes` is way more useless / non-sensical, especially when RAM and/or network bandwitch are limited. If I want mpv to buffer enough for a video, I might be prefetching the a full audio track.

**Comment by rolandjon** [comment]
> Couldn't agree more.
> 
> > This option is considered useless, since there is no good reason to limit the cache by time
> 
> Think about audio-only files v.s. (HD) video. `demuxer-max-bytes` is way more useless / non-sensical, especially when RAM and/or network bandwitch are limited. If I want mpv to buffer enough for a video, I might be prefetching the a full audio track (which not only waste resources but also introduce unnecessary delay). It only makes sense when it serves as a ultimate ceiling to avoid accidental OOM or whatsoever.

Totally agree.

**Comment by Dudemanguy** [comment]
Undeprecated by f1d0365a6f72b88f7427814f636863ae1656f72a.
