### ISSUE TITLE
Mouse pointer does not disappear after switching back to mpv

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#8310]
### Important Information

$ brew info mpv
mpv: stable 0.33.0 (bottled), HEAD
$ system_profiler SPSoftwareDataType
System Version: macOS 10.13.6 (17G14033)

### Reproduction steps

1. Play any movie in full screen
2. While playing, Cmd+Tab to another app (out of full screen back into the OS)
3. (You may need to left-click a couple of different apps to provoke the bug)
4. Finally, Cmd+Tab back to full screen mpv

### Expected behavior

Mouse pointer should disappear automatically after a second

### Actual behavior

Mouse pointer stays on screen forever until you move it, which is annoying

**Comment by Akemi** [comment]
i can't reproduce this at all.

**Comment by forthrin** [comment]
The initial report has been updated with the correct macOS version where the problem does happen.

I can't reproduce the problem in 10.15.7. Would a log reveal anything relevant to this issue?

**Comment by avih** [comment]
> Would a log reveal anything relevant to this issue?

We can't know without seeing it first, but it could certainly help, in addition to the fact that it's required for all bug reports.

**Comment by Akemi** [comment]
the log would have told me that you were on a not officially support macOS version (10.13), for example. it works on 10.14 for me and i don't see myself debugging and fixing this.

the reason is probably a not firing event and race condition.

**Comment by forthrin** [comment]
Fully acceptable and sorry about the initial confusion.

I should have prefaced this by saying I am brought to tears by discovering `mpv` after years of suffering in the pits of orange traffic cones. You have done everything right. Every little detail, from the plethora of relevant command line options, fast startup/jumping, to every little design decision, is as if I should have done it myself.

I have some comments about cropping and subtitles, in particular videos with hard-coded black bars, where many things could be said to be a bit askew. Do you welcome reports on this? If so, I'll post a separate issue.

There is also visual flickering when toggling full screen mode, presumably a well known, hard to fix issue?

**Comment by Akemi** [comment]
yeah, feel free to report those problems.

i don't have any visual flickering and it's not a know issue. see the reported open issues here https://github.com/mpv-player/mpv/labels/os%3Amac so if there is something i can reproduce i will fix it or try to suggest a workaround, if possible.

**Comment by forthrin** [comment]
The "mouse pointer staying on the screen forever" did in fact happen with 10.15.7 just now. I can't willingly reproduce it, and it happens quite rarely, but it happens. I'll write again if I have more information.

**Comment by Akemi** [comment]
i think then we should investigate a bit. when i get around i will make a branch with some test outputs.

**Comment by Akemi** [comment]
please try with this branch https://github.com/Akemi/mpv/tree/mac_cursor (commit https://github.com/Akemi/mpv/commit/943327e12a6a68a97f1784ec63059e38e5a35eb6) and paste me the terminal output of when it happens. you can probably also test it in 10.13, it's possible the same problem and if it's easier to reproduce there it will save you some time.

**Comment by forthrin** [comment]
I haven't experienced this for a while, or at least not to the degree that I remember it as an ongoing annoyance, so closing for now.
