### ISSUE TITLE
Internal subtitles are no longer displayed immediately when switching tracks

### ISSUE THREAD

**Issue by Ben-Kerman** [mpv-player/mpv#8311]
I'm running the 0.33.0 build from the official Arch Linux package repos. I also observed this behavior with a fairly recent (iirc 1-2 months old) Windows build of mpv.

### Reproduction steps
Play any video that has internal/embedded subtitles, ideally one with multiple subtitle tracks, and switch to a track that has text visible at the current timestamp.

### Expected behavior
The text from the newly selected track should immediately be rendered (as it was in 0.32), at least if there is no cache.

### Actual behavior
In 0.33, you have to step at least one frame ahead in order for subtitles to be visible again. This doesn't happen with external subtitles as far as I can tell.

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/5593069/mpv.log), from starting mpv with `mpv --no-config -v -v --log-file=mpv.log <file>`. I added `--pause` and `--start` so mpv would start while displaying subtitles, then switched tracks and stepped one frame ahead so the subs from tracks 2 would become visible. After that I quit mpv.

**Comment by Akemi** [comment]
don't ignore the issue template and provide a log.

**Comment by Ben-Kerman** [comment]
Sorry, I added one now. I honestly didn't think that it would be important for an issue that should be so easily reproducible.

**Comment by Akemi** [comment]
we ask for a log for a reason. it baffles me why people think it's okay to ignore our request.

a log file tells us many things, for example what kind of of subtitles, what config you use, what backend is chosen, what renderer is used and many more. all things that can be important to reproduce and understand an issue.

**Comment by LiteracyFanatic** [comment]
I bisected this and it looks like the regression was introduced in commit b56e2efd5f3d2ed5e62fe02acdaedef03b2d2fbc.

**Comment by kooolarpan** [comment]
any updates on this issue?
