### ISSUE TITLE
Question: what are the best settings to playback added files without delay?

### ISSUE THREAD

**Issue by schollz** [mpv-player/mpv#8315]
Thank for you for this brilliant tool.

I am using this tool to essentially stream audio from a websocket connection into a local JACK port. My websocket is continuously providing a 1-second audio clip every second. Each clip is a chunk of a continuous audio source which should be played back as seamlessly as possible. I wrote a program that to enqueues these incoming clips to a mpv server which is outputting to my JACK client. My server command is the following:

```
> mpv --no-video --jack-port="system:playback_(1|2)" --input-file=/dev/shm/mpv --idle &
```

Every time a websocket message comes in, it is decoded and saved to a temp file and appended to the `mpv` playlist:

```
echo "loadfile incomingfileX.mp3 append-play" > /dev/shm/mpv
```

This is working, but sometimes I am getting "pop" sounds which I think are happening when the switchover to the next clip begins. The pop is not due to the delay in websocket incoming audio since I don't start the mpv player until I have a few of the chunks already. 

I have a couple of questions regarding this setup and how `mpv` works in it:

- When I am doing this, does `mpv` automatically start buffering subsequent files to be played immediately after the current file? I.e. is there a lag time between playback of two files, maybe of a few ms?
- Are there optimized settings I could use to make sure the file chunks are played as continuous as possible (avoiding pops from changing to next buffer)?

Any insight into this would be greatly appreciated :) I've searched for awhile and haven't found a specific answer to this kind of question.

**Comment by Akemi** [comment]
there can be a lag between files. see the explanation of the first option below.
there are various options:
--gapless-audio
--merge-files

**Comment by schollz** [comment]
Thanks @Akemi that did the tricky. It works wonderfully.

For anyone else curious here's my new `mpv` command:

```
> mpv --merge-files=yes --gapless-audio=yes --no-video --jack-port="system:playback_(1|2)" --input-file=/dev/shm/norns.online.mpv --idle &
```

The other thing I discovered is that `mp3` and `ogg` files do not do a good job for gapless audio but using `flac` worked perfectly.
