### ISSUE TITLE
Thick text in lxterminal

### ISSUE THREAD

**Issue by HybridDog** [mpv-player/mpv#8319]
In some rare situations, parts of the text shown in my lxterminal window look thick. When I move the mouse above this text, it looks regular; it stays regular when I move away my mouse.
Maybe the thick text is caused by the terminal somehow rendering the text at the same positions twice.

Thick text:
![doubletex](https://user-images.githubusercontent.com/3192173/100264575-4b77db00-2f4f-11eb-8e23-c6962e1e5375.png)

Regular text after moving the mouse over it:
![aftermouse](https://user-images.githubusercontent.com/3192173/100264570-4a46ae00-2f4f-11eb-81da-712f58216b1e.png)

I use lxterminal 0.3.1 and I've only seen this thick text with the mpv output and not other programs.  I've always been wondering about the workings of mpv and lxterminal which cause this thick text.

### Log file

I don't have log files. The situation happens rarely, so I only have a screenshot. I could not yet find a way to reproduce the situation.

**Comment by sfan5** [comment]
mpv does not render the text inside your terminal and it doesn't use any special escape sequences to make that particular line bold either.
This is a bug in your terminal emulator.

**Comment by avih** [comment]
> In some rare situations

How much rare? can you reproduce it with some reasonable frequency, even if not always?

**Comment by HybridDog** [comment]
I have tried to reproduce it intentionally but never succeeded. I think it happens approximately two times in a month when I start mpv once every day; this is a vague guess since I don't keep track of the time when it happens.

**Comment by CounterPillow** [comment]
ask lxterminal devs
