### ISSUE TITLE
profile-cond=demuxer-via-network doesn't work

### ISSUE THREAD

**Issue by kelppo** [mpv-player/mpv#8324]
### Important Information

Provide following Information:
- mpv version
mpv 0.33.0-1-gfa7afc3e19
- Linux Distribution and Version
Arch Linux
- Source of the mpv binary
mpv-git on AUR
- If known which version of mpv introduced the problem
N/A
- Window Manager and version
Openbox 3.6.1
- GPU driver and version
AMDGPU 5.9.10-arch1-1
mesa 20.2.3-1
- Possible screenshot or video of visual glitches
N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

I want to use dynaudnorm only for local files but the auto profiles I came up with doesn't seem to work at all.

### Expected behavior

mpv uses dynaudnorm only for local files

### Actual behavior

mpv doesn't use dynaudnorm at all

### Log file

https://0x0.st/iREv.txt
Specifically:
[   0.009][v][auto_profiles] Re-evaluating auto profile network 
[   0.010][v][auto_profiles] Profile condition error on evaluating: [string "profile network condition"]:1: attempt to perform arithmetic on global 'demuxer' (a string value) 
[   0.010][v][auto_profiles] Re-evaluating auto profile non-network 
[   0.010][v][auto_profiles] Profile condition error on evaluating: [string "profile non-network condition"]:1: attempt to perform arithmetic on a boolean value 
[   0.010][v][auto_profiles] Re-evaluating auto profile network 
[   0.010][v][auto_profiles] Profile condition error on evaluating: [string "profile network condition"]:1: attempt to perform arithmetic on global 'demuxer' (a string value) 
[   0.010][v][auto_profiles] Re-evaluating auto profile non-network 
[   0.010][v][auto_profiles] Profile condition error on evaluating: [string "profile non-network condition"]:1: attempt to perform arithmetic on a boolean value 

### Sample files

My mpv.conf:
https://0x0.st/iREY.conf

**Comment by sfan5** [comment]
From the [documentation](https://mpv.io/manual/master/#conditional-auto-profiles):

> Any variables in condition expressions can reference properties. If an identifier is not already defined by Lua or mpv, it is interpreted as property. For example, `pause` would return the current pause status. If the variable name contains any `_` characters, they are turned into `-`. For example, `playback_time` would return the property `playback-time`.

This means you need `demuxer_via_network`, not `demuxer-via-network` (which is an arithmetic expression).
