### ISSUE TITLE
4K-UHD Blu-ray subtitles darker on MPV

### ISSUE THREAD

**Issue by nehalem501** [mpv-player/mpv#8325]
### Important Information

Provide following Information:
- mpv version: mpv 0.33.0-1-gfa7afc3e19
- Platform and Version: Ubuntu 20.04 - X11 nvidia proprietary driver - Linux 5.4.0-54 x86_64
- Source of the mpv binary: built myself (https://github.com/mpv-player/mpv-build)

### Reproduction steps

Play the 4K UHD blu-ray release of Spiderman 1 (2002), I made the rip myself with makemkv. I'm playing this on a regular SDR 1080p monitor without any custom config.(I've attached a sample file which has the problem below)
I've also tried this with the latest MPV version on macOS and with VLC, the same bug is present (might be an ffmpeg bug)

### Expected behavior
Subtitles should be white. Here is a picture taken on my SDR 1080p TV with a 4K UHD blu-ray player playing the disc where we can see the expected behaviour.
![IMG_4416](https://user-images.githubusercontent.com/4194367/100388548-2d7fa880-302b-11eb-9e9f-9a01da10217a.JPG)

### Actual behavior
Subtitles are grey instead of white. Here is a screenshot.
![mpv-shot0001](https://user-images.githubusercontent.com/4194367/100388397-bc3ff580-302a-11eb-8d1f-72110bc5ca18.jpg)

### Log file

https://0x0.st/iRI2.txt

### Sample files

https://0x0.st/iRI_.mkv

**Comment by sfan5** [comment]
The subtitles in the picture taken from your TV look grey to me, just a lighter shade. In fact the whole picture seems awfully bright so entirely from "feeling" I'd consider mpv's rendering more accurate.

Have you compared the colors of mpv and your Bluray player *both* attached to your TV?

**Comment by nehalem501** [comment]
Ok I've tried to do a better comparison, both pictures are of the same monitor with a DSLR on manual mode to have the exact same exposure.
On the UHD blu-ray drive (Panasonic DP-UB820) the subtitles are a much lighter grey than the MPV output. In person the difference is much more visible than on these pictures.
The text layout difference is because there are 2 different English subtitles tracks and (the color is identical across all subs tracks) and I've selected the wrong one on the player.

The top picture is MPV, the bottom one the dedicated player.
![IMG_4420](https://user-images.githubusercontent.com/4194367/100390524-f90eeb00-3030-11eb-874e-bea5280957fb.JPG)
![IMG_4421](https://user-images.githubusercontent.com/4194367/100390530-fca27200-3030-11eb-86ca-b37fdf00cbe8.JPG)

**Comment by jeeb** [comment]
For the record, this is because the subtitles end up handled as 100 nits, which is the good ol' SDR peak white. Except apparently for HDR you're supposed to bump it to 203 nits. You either handle the bumping, or then you apply the tone mapping before the subtitles are overlaid (since they IIRC are just SDR).

Where the current behavior semi-accidentally ends up working correctly is output to HDR, where the SDR subtitle surface gets bumped to 203 nits. See the difference before/after the recent BT.2390 tone mapping changes, where this bumping got added (the crappy tone mapping is by Windows itself in these images).
![bt2390-01-before](https://user-images.githubusercontent.com/27182/100391193-5c057f80-303b-11eb-9345-f289d170be33.png)
![bt2390-02-after](https://user-images.githubusercontent.com/27182/100391203-6293f700-303b-11eb-85f3-e055c573a221.png)

**Comment by laichiaheng** [comment]
> For the record, this is because the subtitles end up handled as 100 nits, which is the good ol' SDR peak white. Except apparently for HDR you're supposed to bump it to 203 nits. You either handle the bumping, or then you apply the tone mapping before the subtitles are overlaid (since they IIRC are just SDR).
> 
> Where the current behavior semi-accidentally ends up working correctly is output to HDR, where the SDR subtitle surface gets bumped to 203 nits. See the difference before/after the recent BT.2390 tone mapping changes, where this bumping got added (the crappy tone mapping is by Windows itself in these images).
> ![bt2390-01-before](https://user-images.githubusercontent.com/27182/100391193-5c057f80-303b-11eb-9345-f289d170be33.png)
> ![bt2390-02-after](https://user-images.githubusercontent.com/27182/100391203-6293f700-303b-11eb-85f3-e055c573a221.png)

Is there a workaround for it in MPV?

**Comment by nehalem501** [comment]
Ok, I'll try the latest version with `gpu-next`
