### ISSUE TITLE
(aac lc) no sound from youtube-stream 

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#8327]
> Hello , i am having a problem with a certain stream on Ubuntu 20.10 (alsa-only, no pulse)

the video on stream 
https://www.youtube.com/watch?v=nHr4uunJ2q8&t=322s

would play fine, however, no audio.

mpv was built (and rebuilt) with vapoursynth support and following options:

echo --enable-libx264 >> ffmpeg_options
echo --enable-vapoursynth >> mpv_options
echo --enable-libmpv-shared >> mpv_options
echo --enable-libx264 >> ffmpeg_options
echo --enable-libmp3lame >> ffmpeg_options
echo --enable-libfdk-aac >> ffmpeg_options
echo --enable-nonfree >> ffmpeg_options

other streams play just fine.

the audio in the video is labeled as 
"German, 384 kb/s, 32.0 kHz, 6 channels, AAC LC"

other streams play just fine;

what am i missing?

thank you very much.

> mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv 0.33.0-7-g8886f017a1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Nov 27 11:29:32 CET 2020
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.61.100
[cplayer]    libavcodec      58.113.100
[cplayer]    libavformat     58.64.100
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.91.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: N-100070-g659e6e9c88
[cplayer] 
[cplayer] Configuration: ./waf configure --enable-vapoursynth --enable-libmpv-shared
[cplayer] List of enabled features: alsa asm build-date cplayer cplugins debug-build drm egl egl-helpers egl-x11 ffmpeg gl glibc-thread-name glob glob-posix gpl iconv libass libavdevice libdl libm libmpv-shared librt linux-fstatfs linux-input-event-codes lua luajit optimize plain-gl posix posix-or-mingw pthreads pulse stdatomic vapoursynth vt.h x11 xv zimg zlib
[cplayer] Reading config file /usr/local/etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/rich/.config/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv 0.33.0-7-g8886f017a1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Nov 27 11:29:32 CET 2020
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.61.100
[cplayer]    libavcodec      58.113.100
[cplayer]    libavformat     58.64.100
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.91.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: N-100070-g659e6e9c88
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1

**Comment by mc4man** [comment]
I'd suspect that 6 channel audio has pretty much nothing in it...
Use a different audio stream, one of many examples 
mpv --ytdl-format=137+140 https://www.youtube.com/watch?v=nHr4uunJ2q8&t=322s

**Comment by mrkapqa** [comment]
ok, thanks, i dont know why i was being offered this url in the first place,
on another OS the url instead (with greasemonkey) would be 
https://www.youtube.com/watch?v=nHr4uunJ2q8 
and it would play;
thank you very much.

**Comment by Dudemanguy** [comment]
Simply a bad audio stream.

**Comment by jemadux** [comment]
still we have that problem

**Comment by CounterPillow** [comment]
no you don't, you have a different problem.
