### ISSUE TITLE
mpv can not play the url I give, but mplayer can

### ISSUE THREAD

**Issue by widon1104** [mpv-player/mpv#8331]
### Important Information

Provide following Information:
- mpv version 
➜  ~ mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1.6-1+dde
- Linux Distribution and Version deepinV20
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Window Manager and version
- GPU driver and version i5-8350U
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

mpv can not play the url (http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2020/11/25/c9d907b6b69248a5ae253eff407cdc87_h2642000000nero_aac16-1.mp4), but mplayer(1.3.0) and chrome can play the url

### Expected behavior
mpv should play this url

### Actual behavior
mpv hang can not play this url

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
```
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
```

I highly doubt your browser or mplayer can play a zero-byte-length file that's not even an MP4.

**Comment by widon1104** [comment]
> I highly doubt your browser or mplayer can play a zero-byte-length file that's not even an MP4.

You can use chrome play the url I give.

**Comment by CounterPillow** [comment]
Chromium also shows an empty 0 byte page.

Is this geo-restricted?

**Comment by widon1104** [comment]
this url may can not play in some area...
the log is below:

mpv --no-config --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-19f1 --msg-level=ffmpeg/demuxer=error --no-fs --hwdec=no --sub-auto=fuzzy --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=88080522 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=80 --cache=auto --start=25 --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/widon/Pictures/smplayer_screenshots --audio-pitch-correction=yes --volume-max=110 --ytdl=no --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2020/11/25/c9d907b6b69248a5ae253eff407cdc87_h2642000000nero_aac16-1.mp4

Playing: http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2020/11/25/c9d907b6b69248a5ae253eff407cdc87_h2642000000nero_aac16-1.mp4
[ffmpeg] tcp: Failed to resolve hostname cntv.vod.cdn.myqcloud.com: Name or service not known
Failed to open http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2020/11/25/c9d907b6b69248a5ae253eff407cdc87_h2642000000nero_aac16-1.mp4.
Exiting... (Errors when loading file)

**Comment by widon1104** [comment]
mplayer ok, mpv fail log:
[mplayer_ok.txt](https://github.com/mpv-player/mpv/files/5608558/mplayer_ok.txt)
[mpv_fail.txt](https://github.com/mpv-player/mpv/files/5608561/mpv_fail.txt)

**Comment by Akemi** [comment]
that's not a mpv log. also doesn't seem like an mpv issue if ffmpeg can't resolve the url.

**Comment by CounterPillow** [comment]
Check that you're not setting some proxy env vars which mpv or ffmpeg internally will pick up but mplayer or your browser won't.

**Comment by widon1104** [comment]
> Check that you're not setting some proxy env vars which mpv or ffmpeg internally will pick up but mplayer or your browser won't.

But I do not use any proxy in command line.
