### ISSUE TITLE
Option to constrain HLS content by resolution

### ISSUE THREAD

**Issue by rohieb** [mpv-player/mpv#8334]
### Expected behavior of the wanted feature
On my 1280x1024 screen, it doesn't make much sense to play anything larger than 720p or maybe 1080p content. However, when playing HLS URLs, mpv chooses the first stream by default, which for some URLs might be 2160p or larger, which results in a window that is much larger than my screen size, which I would have to resize first, and additionally strains my WiFi. Alternatively, I could switch to the respective video track, but this incurs additional latency due to rebuffering each new stream.
It looks like the video resolution is already part of the .m3u8 playlist, so mpv can know about it before selecting the respective video stream to play.

For anything that is passed to youtube-dl, we already have the `--ytdl-format` option to constrain the video resolution.
Also there was #2116, which led to the creation of `--hls-bitrate=<rate>`; however, bitrate is only a very marginal indicator for the video resolution, and different HLS playlist indicate different bitrate thresholds for the same resolution — as shown below, there are three 720p streams with different bitrates:

```
$ mpv https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8
     Video --vid=1 'bitrate 549960' (h264 1280x720 29.970fps)
     Video --vid=2 'bitrate 812183' (h264 1280x720 29.970fps)
 (+) Video --vid=3 'bitrate 2059041' (h264 1280x720 29.970fps)
     Audio --aid=1 'bitrate 549960' (aac 2ch 32000Hz)
     Audio --aid=2 'bitrate 812183' (aac 2ch 48000Hz)
 (+) Audio --aid=3 'bitrate 2059041' (aac 2ch 48000Hz)
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 vaapi[nv12]
AV: 00:00:24 / 00:00:50 (48%) A-V:  0.000 Cache: 25s/7MB
[…]
```

Another example where the highest resolution (2160p) is selected:

```
$ mpv https://wwmc.video/dovetail-template-sets/dovetail-template-sets.m3u8
 (+) Video --vid=1 'bitrate 48028483' (h264 3840x2160 29.970fps)
     Video --vid=2 'bitrate 3695024' (h264 854x480 29.970fps)
     Video --vid=3 'bitrate 31129510' (h264 1920x1080 29.970fps)
     Video --vid=4 'bitrate 2402141' (h264 640x360 29.970fps)
     Video --vid=5 'bitrate 1341762' (h264 426x240 29.970fps)
     Video --vid=6 'bitrate 8865118' (h264 1280x720 29.970fps)
 (+) Audio --aid=1 'bitrate 48028483' (aac 2ch 44100Hz)
     Audio --aid=2 'bitrate 3695024' (aac 2ch 44100Hz)
     Audio --aid=3 'bitrate 31129510' (aac 2ch 44100Hz)
     Audio --aid=4 'bitrate 2402141' (aac 2ch 44100Hz)
     Audio --aid=5 'bitrate 1341762' (aac 2ch 44100Hz)
     Audio --aid=6 'bitrate 8865118' (aac 2ch 44100Hz)
Using hardware decoding (vaapi).
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 3840x2160 vaapi[nv12]
[…]
```

Therefore I propose the creation of a new option, e.g. `--hls-max-resolution=<width>x<height>` to constrain the maximum chosen resolution for HLS streams. Additionally, the same could be introduced for the minimum resolution. In the above examples, `--hls-max-resolution=1280x1024` would select vid=1, 2 or 3 in the NASA-TV example, and vid=6 in the wwmc example.

**Comment by Akemi** [comment]
i think this can be done with a script.

**Comment by ZhenFTW** [comment]
How would I do that via script?

**Comment by rohieb** [comment]
Yeah, closing an issue without really giving a solution is not really good practise.

**Comment by ZhenFTW** [comment]
How to list the qualities of HLS url via property? I don't wanna requests and parse the m3u8 and get the resolutions. We can select the quality with --vid but is there no option to get or observe the list of resolution of a playing HLS playback.

**Comment by sur5r** [comment]
This can be done by roundtripping through ytdl:
```
mpv --script-opts=ytdl_hook-try_ytdl_first=yes --ytdl-format='bestvideo[width<=960][height<=540]+bestaudio/best'
```

**Comment by rohieb** [comment]
> This can be done by roundtripping through ytdl:
> 
> ```
> mpv --script-opts=ytdl_hook-try_ytdl_first=yes --ytdl-format='bestvideo[width<=960][height<=540]+bestaudio/best'
> ```

Interesting solution, but it doesn't seem to work for all cases. In this case, `youtube-dl` shows me:
```
$ youtube-dl -F https://do.wwmc.cloud/dovetail-template-sets/media-5/media.ts
[generic] media: Requesting header
[info] Available formats for media:
format code  extension  resolution note
mp2t         ts         unknown  
```

whereas with mpv I see all the formats as in the original post.

**Comment by simoniz0r** [comment]
> This can be done by roundtripping through ytdl:
> 
> ```
> mpv --script-opts=ytdl_hook-try_ytdl_first=yes --ytdl-format='bestvideo[width<=960][height<=540]+bestaudio/best'
> ```

While this does kind of work, a dedicated option would be appreciated.  Forcing the HLS stream through youtube-dl makes the `force-media-title` option not work since youtube-dl pretty much always just sets the title to `index`, and I can't find a way to override this.
