### ISSUE TITLE
How to resetting the settings when I use the "profile-cond="

### ISSUE THREAD

**Issue by vvyoko** [mpv-player/mpv#8335]
setting:

[16:9]
profile-cond= p["video-params/aspect"] <=1.8 and p["video-params/aspect"] >=1.7
video-aspect-override=16:9
panscan=1
geometry=100%x100%
no-window-dragging

It can works on the first match in the playlist or first one.
But when it match, it cant  resetting in next file and still keep this setting when mpv exit.
When i have 2 and more setting,it just use the first one match in a playlist

For example I add a profile to resetting ,it l cant work  
[re]
profile-cond= p["video-params/aspect"] <=1
video-aspect-override= -1

And `profile-dec=cond:p.width>1800 and p.height>1000` dont work for me 
I can only use `profile-cond= p["video-params/w"] >1800 and p["video-params/h"] >1000`

like the log 
the second video is 1080x1920  in line 1285
it still Applying profile '16:9'  in line 1428

[log.txt](https://github.com/mpv-player/mpv/files/5610150/log.txt)

**Comment by guidocella** [comment]
Use `profile-restore=copy`
And `profile-cond=width > 1800 and height > 1000` should work

**Comment by vvyoko** [comment]
> 使用`profile-restore=copy`
> 并且`profile-cond=width > 1800 and height > 1000`应该工作

thx.
It seems I didn't read the document carefully enough.

`If you want the profile to be reverted if the condition goes to false again, you can set  profile-restore:`

`profile-cond=`  can work, but in other issues,people use `profile-dec=cond:p`  

`profile-cond=`  can work is  enough
thx very much!
