### ISSUE TITLE
mpv 0.33.0 crashes using the vaapi driver when switching to full screen.

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#8339]
### Important Information

Provide following Information:
- mpv version: 0.33.0
- Linux Distribution and Version: Archlinux 5.9.10-arch1-1
- Source of the mpv binary: [Arch repository](https://www.archlinux.org/packages/community/x86_64/mpv/)
- If known which version of mpv introduced the problem: v0.33.0
- Window Manager and version: i3 version 4.19 (2020-11-15)
- GPU driver and version: Intel Corporation UHD Graphics 605 (rev 03)
- Possible screenshot or video of visual glitches: None

### Reproduction steps

1. Running the following command, using the vaapi driver
```
mpv video.mp4 --no-config --vo=vaapi
```

2. And after switching to full screen a few times, mpv crashes randomly with the following error messages:
```
mpv: ../ta/ta.c:293: ta_dbg_check_header: Assertion `h->canary == CANARY' failed.
```
```
mpv: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
```

### Log file

Link: [log](https://0x0.st/i7s9.txt)

### Sample files

None

**Comment by LaserEyess** [comment]
I can reproduce this only on intel with intel-media-driver as the vaapi driver. Here's a backtrace https://0x0.st/i7zH.txt

I cannot reproduce this on AMD, though while --vo=vaapi "works" in the sense that it doesn't crash, it does not really work at all. This might be a driver issue, but it could also easily be an mpv issue.

**Comment by A1337Xyz** [comment]
> I can reproduce this only on intel with intel-media-driver as the vaapi driver. Here's a backtrace https://0x0.st/i7zH.txt

I'm using libva-intel-driver with the variable LIBVA_DRIVER_NAME=i965 defined.

**Comment by LaserEyess** [comment]
i965 doesn't crash for me, but it gives this error
```
[vaapi] libva: /usr/lib/dri/i965_drv_video.so init failed
```

I'm trying to bisect and it seems all the way back to 0.30.0 that iHD is crashing. This is most likely an intel bug.

**Comment by ZoomRmc** [comment]
Have the same bug with the second assertion fail showing up randomly. mpv crashes on resize, seeking, manipulating subtitles.

Arch, OpenBox, i915, bug persists up to 0.33.1 to latest git build from aur, `vo=vaapi`.

**Comment by Dudemanguy** [comment]
Feel free to make a new issue if this is still an issue.
