### ISSUE TITLE
Multiple video output tracks with lavfi-complex

### ISSUE THREAD

**Issue by wabiloo** [mpv-player/mpv#8340]
The documentation about `--lavfi-complex` states that 
> Other tracks, as long as they're not connected to the filter, and the corresponding output is not connected to the filter, can still be freely changed with the normal methods.

So I understand to mean that it should be possible to have multiple tracks on the input, and that those of which not used in a filter chain should be switchable to (using for example the _ key binding)

Unfortunately that doesn't seem to work...
What I'm trying to do is to have the ability to switch between video 1, video 2, and a blend difference of the 2, just by cycling through the `vid` property.

I tried:
`mpv  video1.mp4 --external-file=video2.mp4 --external-file=video1.mp4 --external-file=video2.mp4 --lavfi-complex="[vid1][vid2]blend=all_mode=difference[vo]" `, and mpv starts playing the output of the filter graph. When trying to use _ (or `cycle vid` in the console), I get 

```
Can't switch away from complex filter output.
Track switched:
 (+) Video --vid=1 (*) (hevc 1920x1080 25.000fps)
 (+) Video --vid=2 (*) 'video2.mp4' (hevc 1920x1080 25.000fps) (external)
     Video --vid=3 (*) 'video1.mp4' (hevc 1920x1080 25.000fps) (external)
     Video --vid=4 (*) 'video2.mp4' (hevc 1920x1080 25.000fps) (external)
```

Log: [output.txt](https://github.com/mpv-player/mpv/files/5611292/output.txt)

Is there something obvious I'm missing?

**Comment by Akemi** [comment]
seems like it's not intended to work to switch away from a complex filter out like the error message suggests.
