### ISSUE TITLE
Option to alter loadfile flags for ytdl

### ISSUE THREAD

**Issue by GreyAsteroid** [mpv-player/mpv#8341]
### Preface
I have set mpv in charge of the ytdl:// uri scheme.
When using it, it does this.
[   0.087][d][cplayer] Run command: loadfile, flags=65, args=[url="ytdl://https://www.youtube.com/watch?v=dQw4w9WgXcQ", flags="replace", options=""]

### Expected behavior of the wanted feature
I would like an option to adjust the loadfile flags for ytdl so that I may change it to no longer replace but instead append. As far as I can tell there is not a way of doing this via config file in general or just for ytdl.

**Comment by wiiaboo** [comment]
What do you mean?

**Comment by GreyAsteroid** [comment]
So, let me explain my use case to shed some light.

I have a Chrome extension that when activated accesses ytdl://(whatever  video is on the page).

I have mpv set as the default handler of ytdl:// links.

The way mpv handles ytdl:// links is by essential running loadfile on it.

The problem I have is that there's no way (that I can tell) to adjust the loadfile behavior to append instead of replace if you're accessing mpv via uri.

Ideally I'd like a --script-opts=ytdl_hook-append or something that way I can queue up multiple videos in mov.

**Comment by wiiaboo** [comment]
That's not ytdl_hook, that's mpv.
You're supposed to use something like [umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv) if you want a single instance mpv to keep accepting links from your browser.

**Comment by GreyAsteroid** [comment]
> That's not ytdl_hook, that's mpv.
> You're supposed to use something like [umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv) if you want a single instance mpv to keep accepting links from your browser.

So I'd like to not do that which is the point of me making this feature request. 

If mpv had an option to change the default loadfile behavior then the functionality of umpv would just be built into mpv for my use case.

**Comment by GreyAsteroid** [comment]
So the general functionality to do this has already been requested in https://github.com/mpv-player/mpv/issues/2166 so this should stay closed since it's a duplicate.
