### ISSUE TITLE
How to check if the strings match in "profile-cond="

### ISSUE THREAD

**Issue by vvyoko** [mpv-player/mpv#8342]
I dont know lua,I searched in Google and wrote that 

`profile-cond=p(string.find(["audio-device-list"],"4d7b106f")) >=1`

I want to match `4d7b106f` in the `audio-device-list` for change audio-device to `4d7b106f` when it  connected

i test `echo show-text ${audio-device-list} 5000 >\\.\pipe\mpvsocket` 
it can show `audio-device-list` value and `4d7b106f` is in that.

How to write the `profile-cond` for that?

**Comment by guidocella** [comment]
`profile-cond=mp.get_property('audio-device-list'):match('4d7b106f') ~= nil`
You need `mp.get_property` to access `audio-device-list` as a string, since the magic identifiers are equivalent to `mp.get_property_native('audio-device-list')` which returns a table. The code to find a value in a table doesn't fit in 1 line and would have to be put in a script:
```lua
for _, audio_device in pairs(mp.get_property_native('audio-device-list')) do
    if audio_device.name == '4d7b106f' then
        mp.set_property('audio-device', '4d7b106f')
    end
end
```

**Comment by vvyoko** [comment]
> `profile-cond=mp.get_property('audio-device-list'):match('4d7b106f') ~= nil`
> You need `mp.get_property` to access `audio-device-list` as a string, since the magic identifiers are equivalent to `mp.get_property_native('audio-device-list')` which returns a table. The code to find a value in a table doesn't fit in 1 line and would have to be put in a script:
> 
> ```lua
> for _, audio_device in pairs(mp.get_property_native('audio-device-list')) do
>     if audio_device.name == '4d7b106f' then
>         mp.set_property('audio-device', '4d7b106f')
>     end
> end
> ```

`profile-cond=mp.get_property('audio-device-list'):match('4d7b106f') ~= nil`  can work for me.

Very fortunate I don't mess with scripts，although this paragraph was only put into one of the scripts
I am not a programmer
In our case, we ordinary people refer to programmers as superpowers!

And I am communicating with you through a translation tool!
I hope you can understand what I'm saying.

Thank you very much for your help!
Have a nice day
