### ISSUE TITLE
Add properties for the start and end time of secondary subtitles

### ISSUE THREAD

**Issue by LiteracyFanatic** [mpv-player/mpv#8343]
### Expected behavior of the wanted feature
I have a script which uses `sub-start` to jump to the beginning of the currently playing line. It also factors in the `sub-delay` but it looks like a separate delay for the secondary subs has already been requested in another issue. I would like to have `secondary-sub-start` and `secondary-sub-end` so that I can do the same thing with the secondary subs. For context, I watch videos with Japanese as the primary subs and English as the secondary subs. There are times when only the English subtitles are showing because they are a translation of text that is already visible on screen. Since there is no point in duplicating that text in the Japanese subtitles, `sub-start` is undefined and I can't use my script.

### Alternative behavior of the wanted feature
NA

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/5612074/log.txt)

**Comment by bitingsock** [comment]
Is combining your subtitles into 1 file viable here?

**Comment by LiteracyFanatic** [comment]
I still want to be able to toggle their visibility separately.
