### ISSUE TITLE
Mpv has a transparent bar on top in all window modes (fullscreen - tiling - float)

### ISSUE THREAD

**Issue by iMaaNor** [mpv-player/mpv#8345]
### Important Information

Provide following Information:
- mpv version:0.33.0
- Linux Distribution and Version:arch 5.9.10
- Source of the mpv binary [Arch  repository](https://www.archlinux.org/packages/community/x86_64/mpv/) 
- If known which version of mpv introduced the problem:idk
- Window Manager and version: i3 v4.16.1
- GPU driver and version:Intel 2nd Generation Core Processor Family
- Possible screenshot or video of visual glitches
https://ibb.co/gMRZTZq
https://ibb.co/1mNskMb

### Reproduction steps

i open a video like this with or with out fs option
`mpv video.mp4 -fs=yes`
or 
`mpv video.mp4`

### Actual behavior
there is a transparent bar like a menubar at the top of all modes of window (fullscreen - float - tiling)

### Log file

[the log file](https://0x0.st/i7Zs.txt)

**Comment by emmatebibyte** [comment]
What was the solution for this?

**Comment by iMaaNor** [comment]
> What was the solution for this?

Comment out "frame-opacity = X" in picom config file

**Comment by avih** [comment]
> there is a transparent bar like a menubar

mpv doesn't have anything resembling a menu bar, so it's unclear what you're referring to. A screenshot could help.

**Comment by CounterPillow** [comment]
> > there is a transparent bar like a menubar
> 
> mpv doesn't have anything resembling a menu bar, so it's unclear what you're referring to. A screenshot could help.

the issue was already resolved by the reporter and they did provide screenshots in the original post.
