### ISSUE TITLE
Where can you download 0.33.0 for Windows?

### ISSUE THREAD

**Issue by desudesune** [mpv-player/mpv#8346]
I'm not seeing it on the Windows builds:

https://sourceforge.net/projects/mpv-player-windows/files/64bit/

https://sourceforge.net/projects/mpv-player-windows/files/stable/

**Comment by CounterPillow** [comment]
shinchiro's builds are whatever is in the master branch of the git repo that week, 11-22 should pretty much be 0.33.

**Comment by Akemi** [comment]
we don't provide official builds.
