### ISSUE TITLE
Some files cannot be hw decoded on apple silicon (videotoolbox)

### ISSUE THREAD

**Issue by pxia** [mpv-player/mpv#8348]
### Important Information

```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 22 11:53:59 PST 2020
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: 4.3.1
```

#### apple silicon, macOS 11.0.1
Tried both the stolendata build (intel) and a custom build I made myself (arm). Some files cannot be hw decoded.
#### Intel, macOS 10.13.5
Only tried the stolendata build. Files failed earlier can be hw decoded here.

### Reproduction steps

`mpv --no-config --hwdec=videotoolbox`

### Expected behavior

Video opened and played

### Actual behavior

No GUI activity. Errors in console.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5614696/output.txt)

### Sample files

[SampleVideo_1280x720_1mb.mp4.zip](https://github.com/mpv-player/mpv/files/5614700/SampleVideo_1280x720_1mb.mp4.zip)

**Comment by Akemi** [comment]
try with ffmpeg and see if it also errors out or post the output. though this is clearly an ffmpeg issue. so please report it there.

```
ffmpeg -hwaccel videotoolbox -i "your_file.MP4" -f null -
```

**Comment by pxia** [comment]
filed https://trac.ffmpeg.org/ticket/9016
