### ISSUE TITLE
No MPV 0.33 for Ubuntu stable version

### ISSUE THREAD

**Issue by AO-LocLab** [mpv-player/mpv#8351]
### Important Information

MPV 0.33 is not being offered as a .deb either from the official Canonical repository for Ubuntu 20.10, nor from the mc3man PPA (no PPA for Groovy)  

One of the possibilities to bring MPV 0.33 to the Ubuntu Community would be to offer a Groovy PPA for ppa:mc3man/mpv-tests
Though I requested it from the PPA manager, my request got ignored.

### Reproduction steps
Install MPV from the official Ubuntu repository or from ppa:mc3man/mpv-tests

### Expected behavior
Users running the latest Ubuntu stable should be able to install MPV 0.33

### Actual behavior
The MPV 0.33 .deb for Ubuntu Focal 20.04 available in ppa:mc3man/mpv-tests doesn’t not install in Ubuntu Groovy 20.10. 

### Log file
No log file

### Sample files
No sample files

**Comment by CounterPillow** [comment]
Hi AO-LocLab,

the mpv project itself does not provide official builds, nor do we have any influence over what distributions choose to package.

Your best bet is to make a build yourself, or wait for someone from the community to provide an unofficial build for you. Alternatively, contact your distribution's maintainer of the package and ask them to package a newer version, though they might not want to do that on purpose.

**Comment by mc4man** [comment]
There is one in ppa shortly (couple hours to publish 
minor changes to make easier build
no zimg as not in repo, don't want to package for 20.10
using gslang for vulkan  as also don't want to package shaderc for 20.10
nv-codec-headers 9.1.23.2, requires 435.21 or newer
Likely a one & done
