### ISSUE TITLE
segmentation fault when trying to loop-file

### ISSUE THREAD

**Issue by indeedwatson** [mpv-player/mpv#8353]
### Important Information

Provide following Information:
- mpv version 0.32.0_779_gcbbdb3fae4 (mpv-git from AUR)
- Linux Distribution and Version: Arch linux kernel 5.9.11
- Source of the mpv binary: AUR and official Arch repo
- If known which version of mpv introduced the problem
- Window Manager and version: bspwm
- GPU driver and version: amdgpu 19.1

In my input.conf I have
```

r cycle_values loop-file inf no
R cycle_values loop-playlist inf no # repeat whole playlist
```

Until recently, it did what it was supposed to, repeat the video once it finishes.

But now it makes mpv crash with segmentation fault. I've commented out all of my config except for those two lines and the issue persists.

### Log file

https://paste.xinu.at/0Xxy2/

**Comment by qmega** [comment]
FYI, your log shows that you're actually running mpv 0.33.0-18-ga74b6619f2 (which is latest master as of this writing). What you posted in the issue template is just the last time the AUR build script was updated.

Your log also shows you have some scripts/plugins loaded. Did you also try disabling those when you commented out your config? Try running with `--no-config` to actually disable everything. You can use use the default keybinding <kbd>Shift</kbd> + <kbd>L</kbd> to toggle loop-file like your <kbd>r</kbd> does, or use `--input-conf` to point to a file with the two input lines you posted.

If I had to guess, I'm suspicious of `/home/yama/.config/mpv/scripts/mpris.so`. It's a binary plugin and MPRIS has a LoopStatus property.

In any case, I can't reproduce with the same version on Arch, so if it's not one of your scripts/plugins, you'll probably have to bisect and/or run in a debugger. If you don't know how, I or someone else can help, but I'm pretty sure it's mpris or another plugin, so please check that first.

**Comment by CounterPillow** [comment]
A backtrace could be useful. run `gdb mpv` then type `run videofilehere` and then once it segfaults do a `bt full` and show us the output.

**Comment by indeedwatson** [comment]
@qmega You're right, it's mpris. Thank you for the pointer.

Output of `gdb`

```Thread 9 "mpv/SO plugin (" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe67fc640 (LWP 375945)]
0x00007fffe4df687b in event_handler () from /home/yama/.config/mpv/scripts/mpris.so
(gdb) bt full
#0  0x00007fffe4df687b in event_handler () at /home/yama/.config/mpv/scripts/mpris.so
#1  0x00007fffef82d914 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffef8817d1 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffef82ce63 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#4  0x00007fffe4df76df in mpv_open_cplugin () at /home/yama/.config/mpv/scripts/mpris.so
#5  0x000055555563cf25 in  ()
#6  0x000055555563d20c in  ()
#7  0x000055555563d28b in  ()
#8  0x00007ffff53f73e9 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff5325293 in clone () at /usr/lib/libc.so.6
```

**Comment by Akemi** [comment]
then you should report is upstream.
