### ISSUE TITLE
Pulse/ALSA play <1s of sound after pause, mute, unpause

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#8356]
### Important Information

Provide following Information:
- mpv version: mpv 0.33.0-1-gfa7afc3e19 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: self compiled
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: sway version 1.5-32b93ef6 (Nov 25 2020, branch 'master')
- GPU driver and version: amdgpu 5.9.11, mesa 20.2.3-1
- Possible screenshot or video of visual glitches: N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

With any video:
```
mpv --no-config --ao=(pulse|alsa) any_video.mkv
```

### Expected behavior
Silence after unpausing

### Actual behavior
A small amount of sound, <1s, probably just 100 or so ms

### Log file
ALSA: https://0x0.st/i7W7.log
PULSE: https://0x0.st/i7Wh.log

### Sample files
N/A, any file I've tried reproduces this.

When I say "pulse or ALSA" I probably only mean pulseaudio, but I'm not sure. Etiher way I can reproduce on both `--ao=pulse` and `--ao=alsa`

**Comment by sfan5** [comment]
This is due to audio buffering and exists since the `softvol=no` removal, if you want instant (un-)muting bind keys to toggle `ao-mute` (same applies to volume changes btw).

**Comment by LaserEyess** [comment]
dupe of https://github.com/mpv-player/mpv/issues/6807
