### ISSUE TITLE
REWIND seek -100% - start video from beginning

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8357]
I'd like to start video from very beginning with hotkey. Is there a chance to do it?

_(I tried to find a solution - unfortunately I didn't found useful information)_

**Comment by skitvandarken** [comment]
which software you want the shortcust to work on?

**Comment by Max-Enrik** [comment]
mpv

**Comment by guidocella** [comment]
Bind a key to `set playlist-pos 0`

**Comment by Max-Enrik** [comment]
Wow! Very nice, thank you.
It also back to first video of the playlist.
Is it possible make it effect only current video file?

**Comment by Akemi** [comment]
`X seek 0 absolute` see seek command and its flags https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst
