### ISSUE TITLE
lua commandv("video-add") displays only a single frame of video

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8358]
### Important Information

mpv 0.32.0-821-g38275338ee

### Description

I have a lua script that adds a generated video stream if the preloaded item only contains audio using the video-add command
With the latest mpv build it only produces 1 frame of video of the input stream.

Complicated setup, check out the sample file below.
Extract the zip archive, cd inside the extracted directory and run the following:

```
mpv --log-file=mpv.log --no-config --script=test.lua --of=nut --ovc=rawvideo --oac=pcm_s16le --oacopts=ac=2 "--af-add=@downmix1:lavfi=[pan=stereo|FL<1.0*FL+0.707*FC+0.707*BL|FR<1.0*FR+0.707*FC+0.707*BR]" "--vf-add=lavfi=[scale=(iw*sar)*min(1280/(iw*sar)\,720/ih):ih*min(1280/(iw*sar)\,720/ih),pad=1280:720:(1280-iw*min(1280/iw\,720/ih))/2:(720-ih*min(1280/iw\,720/ih))/2,format=yuv420p]" --force-window=yes --o=- audio.mp3 | ffmpeg -i - -c copy out.mkv -y
```

ffmpeg generates a video called 'out.mkv' with 1 frame from the piped input.

Issue not present in previous version built June 21st - mpv 0.32.0-563-gdc24a437fb

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5631027/mpv.log)

### Sample files

[mpv-test.zip](https://github.com/mpv-player/mpv/files/5631030/mpv-test.zip)

**Comment by CogentRedTester** [comment]
I believe this was caused by the commits that added external cover art support. All video streams are being tagged as picture files, which leads to only a single frame being processed.

**Comment by hedgehog90** [comment]
That sounds right. Incidentally no matter what I try I can only get a single frame. Tried adding the fps video filter, using the fps argument, nothing works.

**Comment by hedgehog90** [comment]
Sorry for my impatience but I'd appreciate if someone could look into this.

**Comment by hedgehog90** [comment]
Can someone look into this soon?
If CogentRedTester's hunch is correct then it should be very easy to fix.

**Comment by hedgehog90** [comment]
*bump*

The video-add command has been broken for over a month now.

I'll make a simpler example:

```mpv --log-file=mpv.log --no-config --script=test.lua --force-window=yes audio.mp3```

and test.lua contains:

```mp.add_hook("on_preloaded", 10, function () mp.commandv("video-add", "video.mkv", "select") end)```

This still doesn't work!
