### ISSUE TITLE
How to get the audio device/output currently in use by mpv

### ISSUE THREAD

**Issue by enilfodne** [mpv-player/mpv#8361]
Hi,

I recently started playing with SOFA and while it sounded good on my headphones, its a complete mess on any speaker setup. As i have different Audio Outputs for them, i was wondering if there's a way to get the audio output that `mpv` is currently using?

Setup: Linux, PulseAudio, mpv-git

I tried poking around in`audio/out/ao.c`, but AFAICS, by utilizing [` split_ao_device`](https://github.com/mpv-player/mpv/blob/master/audio/out/ao.c#L254), the information about the audio output is being discarded. Is there any reason for this? Keeping this intact, would allow people to use `string.match` in their profiles for example.

And a side-question?

Is there any story behind the terms used in `ao`. As `pulse`/`alsa`/`jack` are back-ends, rather than devices. And the back-end device may not necessarily be a device (as many back-end support virtual device), but rather an output.

**Comment by Akemi** [comment]
same as #8047. don't think this is currently possible.
