### ISSUE TITLE
how to get sart for iOS

### ISSUE THREAD

**Issue by SpectatorNan** [mpv-player/mpv#8362]
I am a newbie and I cannot find any information on how to start development on iOS;

i find build scripts in
[https://github.com/stps/mpv-ios-scripts](https://github.com/stps/mpv-ios-scripts)

but it report error

clang: error: invalid argument '-mmacosx-version-min=10.15' not allowed with '-mios-simulator-version-min=11.0'

i don't know how start in programs

for example ijkplayer, there tell users how to build. 
In the ci folder, I only found the Mac build shell but not the iOS build shell

**Comment by Akemi** [comment]
if you have problems with that script, ask on their issue tracker.

there are already related closed issues:
https://github.com/mpv-player/mpv/issues/5902
https://github.com/mpv-player/mpv/issues/5439
https://github.com/mpv-player/mpv/issues/5331
https://github.com/mpv-player/mpv/issues/4723
https://github.com/mpv-player/mpv/pull/3682#issue-184049753

https://github.com/ldwardx/mpv-build-mac-iOS

https://github.com/mpv-player/mpv/wiki/Compiling-distro-releases-for-OS-X

pass the right targets to our build system clang und swift (--swift-flags="\-target arm-apple-iphoneos14"), or disable swift.

if you want actual help try first and ask about actual problems if you have one. none of us will most likely give you a step by step guide.
