### ISSUE TITLE
How to only load the same extensions files with autoload.lua

### ISSUE THREAD

**Issue by vvyoko** [mpv-player/mpv#8363]
When I open a mp4 file only load all *.mp4 file
Open a mp3 file load all *.mp3 file

Because usually I just need a video playlist or an audio playlist.

I try not to load the script.
Then manually load a modified configuration of the autoload.lua
```
[extension.mp3]
load-scripts=no
script="~~/autoload.lua"
```

But It still load  scripts

**Comment by Tsubajashi** [comment]
You basically told mpv to not load a script, and afterwards, load a script. 
You can move your mp3s to another directory, and mp4s to another one again, so they aren’t in the same folder. Then just use the autoload script.

**Comment by vvyoko** [comment]
I find 
`--script-opts=myscript-optionA=TEST,myscript-optionB=0,myscript-optionC=yes`

and the [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) support autoload.conf
```
--[[
To configure this script use file autoload.conf in directory script-opts (the "script-opts"
directory must be in the mpv configuration directory, typically ~/.config/mpv/).
Example configuration would be:
disabled=no
images=no
videos=yes
audio=yes
--]]
```

i try `script-opts=autoload-audio=yes`
it can work in global setting
but it not work like this
```
[extension.mp3]
script-opts=autoload-audio=yes
```

**Comment by vvyoko** [comment]
use [playlistmanager.lua](https://github.com/jonniek/mpv-playlistmanager/blob/master/playlistmanager.lua)
edit playlistmanager.conf 
`loadfiles_filetypes=["mp3","wav","ogm","flac","m4a","wma","ogg","opus"]`

add to mpv.conf
```
[extension.mp3]
script-opts=playlistmanager-loadfiles_on_start=yes
```

it can be work


I find
 https://github.com/mpv-player/mpv/blob/75acc042628d17414c5fd6da212f30f9ea472213/TOOLS/osxbundle/mpv.app/Contents/Info.plist
and 
https://github.com/mpv-player/mpv/blob/73be20143eea2c0232b63c2617e8604a44217e57/player/external_files.c

it  have some code like `audio_exts[] =`
is there have a option like `[extension.audio]  [extension.video] `to include all audio ext?



I will close this issues after a day for wait someone tell me the answer.
