### ISSUE TITLE
youtube - drag & drop link of youtube video

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8364]
I drag & drop link of youtube video on mpv player it shuts down mpv player and after many tries it starts to play.
How can I fix this issue?

_Thank you!_

**Comment by Akemi** [comment]
no idea. open a proper issue.

**Comment by Max-Enrik** [comment]
I am dropping URLs of youtube video link on mpv player to play, but mpv player close. So after I many times tried8 dropping URLs of youtube video link it start to play, I'd like to know what is a problem that mpv player doesn't play in a first attempt?

_English isn't my native language._

**Comment by CounterPillow** [comment]
You've opened a question template.

If you want to report what you think is a bug, open the proper type of issue for it and fill it out with all the required information.

**Comment by Max-Enrik** [comment]
Ah! Didn't know that.

**Comment by Max-Enrik** [comment]
I just updated youtube-dl windows. And it solved my issue.
