### ISSUE TITLE
Blu-ray audio doesn't work anymore

### ISSUE THREAD

**Issue by Touceire** [mpv-player/mpv#8375]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.33.0-25-ga9aa5a1b1c Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  6 09:48:45 +08 2020
FFmpeg library versions:
   libavutil       56.62.100
   libavcodec      58.114.100
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.92.100
   libswresample   3.8.100
FFmpeg version: git-2020-12-05-89e3f5ab
```
- Windows Version : Windows 10
- Source of the mpv binary :  shinchiro Sourceforge

### Reproduction steps

`mpv --no-config bd:// --bluray-device="E:\"`

### Expected behavior
mpv should play audio.

### Actual behavior
```
mpv --no-config bd:// --bluray-device="E:\"
[bd] List of available titles:
[bd] idx:   0 duration: 02:00:41 (playlist: 00000.mpls)
[bd] idx:   1 duration: 00:10:00 (playlist: 00001.mpls)
[ffmpeg] NULL: Decoder requires channel count but channels not set
[ffmpeg/demuxer] mpegts: Failed to open codec in avformat_find_stream_info
[ffmpeg] NULL: Decoder requires channel count but channels not set
[ffmpeg/demuxer] mpegts: Could not find codec parameters for stream 1 (Audio: pcm_bluray (HDMV / 0x564D4448), 0 channels): unspecified sample rate
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
 (+) Video --vid=1 (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (pcm_bluray)
[ffmpeg/audio] pcm_bluray: Decoder requires channel count but channels not set
Could not open codec.
Decoder init failed for pcm_bluray
Failed to initialize a decoder for codec 'pcm_bluray'.
Audio: no audio
VO: [gpu] 1920x1080 yuv420p
```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/5655740/mpv.log)

### Sample files

Any Blu-ray with pcm audio will do.

**Comment by Isaacx123** [comment]
Can confirm bluray audio does NOT work on Windows 10 anymore.
DTS-HD MA works just fine tho.
Log with bluray audio:
[bluray audio.log](https://github.com/mpv-player/mpv/files/5656004/bluray.audio.log)

Log with DTS audio:
[dts audio.log](https://github.com/mpv-player/mpv/files/5656008/dts.audio.log)

**Comment by mkver** [comment]
Has probably been fixed by [this FFmpeg commit](https://github.com/FFmpeg/FFmpeg/commit/494f868e93d1d671497d0d0884368f015eb7d31e).

**Comment by 44vince44** [comment]
DTS-HD works, but not core DTS (or simple DTS)

**Comment by stax76** [comment]
I don't know if I have a test image with PCM, here it's the other way around, DTS plays fine but DTS XLL isn't found.

A: German, DTS XLL, 2 098 kb/s, 6ch, 48.0 kHz, Default
A: German, DTS, 1 509 kb/s, 6ch, 48.0 kHz
A: English, DTS XLL, 2 224 kb/s, 6ch, 48.0 kHz
A: English, DTS, 1 509 kb/s, 6ch, 48.0 kHz
A: English, DTS, 384 kb/s, 2ch, 48.0 kHz

**Comment by jeeb** [comment]
My current mpv build (based on https://github.com/mpv-player/mpv/commit/fa7afc3e19 , and http://git.videolan.org/?p=ffmpeg.git;a=commit;h=b0a8b40294 as far as FFmpeg goes) does work with BD LPCM and TrueHD. So does a sample I have with DTS.

Will retry later today with current master mpv + FFmpeg.

**Comment by 44vince44** [comment]
I'm just thinking that my problem is slightly different than the others. I should maybe open another thread.
Mine is related to usage of audio-spdif=ac3,dts in mpv.conf.
I use a laptop that I occasionally connect to an amplifier with S/PDIF. So my conf has audio-spdif=ac3,dts which used to work flawlessly ehrn connected with S/PDIF and when disconnected ( = output through speakers). This is how it's supposed to work.
I'm investigating when the regression happened exactly.

**Comment by Isaacx123** [comment]
Bluray LPCM audio works again with the latest shinchiro 0.33.0-46-gdde0189279, the issue can be closed now.
Log:
[mpv.log](https://github.com/mpv-player/mpv/files/5720983/mpv.log)

**Comment by stax76** [comment]
My observation is also another topic, so I deleted the post.

**Comment by jeeb** [comment]
Alright, cheers.
