### ISSUE TITLE
Interpolation turning on and off on 60 FPS YouTube video causing out-of-place frames

### ISSUE THREAD

**Issue by kelppo** [mpv-player/mpv#8378]
### Important Information

Provide following Information:
- mpv version
mpv 0.33.0-31-gb8156a9a86
https://github.com/mpv-player/mpv/commit/b8156a9a86ae4ff087b1b255c68a3ca38ec2d086
- Linux Distribution and Version
Arch Linux
- Source of the mpv binary
https://aur.archlinux.org/packages/mpv-git
- If known which version of mpv introduced the problem
N/A
- Window Manager and version
Openbox 3.6.1-7
- GPU driver and version
linux 5.9.12.arch1-1
mesa 20.3.0-2
vulkan-radeon 20.3.0-2
- Possible screenshot or video of visual glitches
https://0x0.st/ih25.mp4

### Reproduction steps
It's best to see the issue in action linked above. Weirdly enough I tried downloading the video and this doesn't happen when watching it locally.

`$ mpv --no-config --video-sync=display-resample --interpolation --ytdl-format='bestvideo[height<=?720]+bestaudio/best[height<=?720]/best' https://www.youtube.com/watch?v=yH77qX7dqzQ`

```
$ xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
HDMI-A-0 disconnected primary (normal left inverted right x axis y axis)
HDMI-A-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  74.97    50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      59.91  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
   720x400       70.08  
HDMI-A-2 disconnected (normal left inverted right x axis y axis)
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
```

### Expected behavior
mpv plays the video without rendering out-of-place frames

### Actual behavior
As you can see sometimes mpv renders out-of-place frames.

### Log file
https://0x0.st/ih27.log

### Sample files
https://www.youtube.com/watch?v=yH77qX7dqzQ

**Comment by sfan5** [comment]
FYI `--interpolation-threshold=-1` can fix this.

**Comment by alvv-z** [comment]
This also happens to me on Ubuntu 20.10 and `--interpolation-threshold=-1` fixes it.

**Comment by LaserEyess** [comment]
Does setting `--interpolation-threshold=0.01` also work?

**Comment by kelppo** [comment]
Yes but with 0.01 interpolation doesn't show up in stats, whereas with -1 it's there.

**Comment by LaserEyess** [comment]
Yeah it doesn't happen because the display/video are within 1%  so interpolation isn't used. I really think the issue here is that without a fixed container fps, mpv has to make a guess and `--video-sync-max-video-change` and `--interpolation-threshold` are fighting each other.
