### ISSUE TITLE
[client API] Too many logs make ring buffer run out

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#838]
When opening one of my sample mkv file with "-v", I got next logs:
```
[mkv] /---- [ parsing seek head ] ---------
[mkv] Element 0x1f43b675 at 5642.
...
[mkv] Element 0x1f43b675 at 486829844.
[mkv] \---- [ parsing seek head ] ---------
```

The problem is that the number of lines is over 1400.
This causes running out of ring buffer for client API and makes the application crashed.
Since all the parsed head informations are logged at once in demux_mkv_read_seekhead(), it's not a problem of lazy pulling of log events from client side.
Is there any way to avoid runnig out of message buffer in this case? Or, can this be fixed in mpv's client API?

**Comment by xylosper** [comment]
I think it's time to bring up the old issue(#838).

I have a file which produces next logs in a certain point:
```
[ffmpeg/video] mpeg4: ac-tex damaged at 11 1
[ffmpeg/video] mpeg4: Error at MB: 50
[ffmpeg/video] mpeg4: marker does not match f_code
[ffmpeg/video] mpeg4: marker does not match f_code
[ffmpeg/video] mpeg4: marker does not match f_code
[ffmpeg/video] mpeg4: marker does not match f_code
[ffmpeg/video] mpeg4: marker does not match f_code
... (repeat the last line)
```

I guess this is the same issue with #838 because it crashes when creating `mpv_event_log_message` in `mpv_wait_event()`.

This time, the whole number of log lines is over 27000.
If you don't think it's not the issue of long log and you need sample, please let me know.

**Comment by wm4** [comment]
It certainly shouldn't crash. A sample would probably be helpful to reproduce this.

**Comment by xylosper** [comment]
I cut some part of front from original file. The problem occurs around 1m 43s.
https://drive.google.com/file/d/0B7k0IbH_XHW4UWh1YmliTTFIZHc/view?usp=sharing

**Comment by wm4** [comment]
The sample was helpful, thanks. Fixed.

**Comment by xylosper** [comment]
It works. Thank you! (link removed)
