### ISSUE TITLE
term-title doesn't work with git bash

### ISSUE THREAD

**Issue by ChaoticWyrme** [mpv-player/mpv#8380]
### Important Information

Provide following Information:
- mpv version: 0.33
- Windows Version: 10.0.18363 Build 18363
- Source of the mpv binary: scoop
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
- Use git bash rather than cmd.exe or powershell
- Run mpv with a custom --term-title, for example: `mpv https://www.youtube.com/watch?v=UnA7tepsc7s --term-title='${media-name}`

### Expected behavior
It should update the terminal name.

### Actual behavior
It does not change the terminal name at all.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/5662535/output.txt)

**Comment by avih** [comment]
> ### Expected behavior
> 
> It should update the terminal name.

I don't know why you expect it, git-bash runs mintty, which is not a windows console, and on windows term-title sets the window console title.

You might be able to get around that with winpty, which I believe is available for msys2 (on which git-for-windows is based), but I don't know if it's built into git-for-windows, and if not, I don't know if you can install winpty into it.

Either way, mpv terminal output on windows expects a windows console, and git-bash is not a windows console.

**Comment by ChaoticWyrme** [comment]
Thanks for the help, I do in fact have winpty and that worked :)
