### ISSUE TITLE
First second audio crackle on 0.33

### ISSUE THREAD

**Issue by Ambrevar** [mpv-player/mpv#8381]
### Important Information

Provide following Information:
- mpv version: 0.33
- Linux Distribution and Version: Guix (rolling release)
- Source of the mpv binary: (I don't understand the question.)
- If known which version of mpv introduced the problem: 0.33 (0.32 works well)
- Window Manager and version: EXWM 0.24
- GPU driver and version: amdgpu on Mesa 20.1.9

### Reproduction steps

mpv /path/to/audio/file

### Expected behavior

Should play music fine.

### Actual behavior

There is 1 crackle during the first second of each file playback.
It's only audible if the file has sound during the first second.

I can only reproduce this is issue on one of my two Guix machines (with the exact same configuration).

### Log file

https://0x0.st/ihWk.txt

**Comment by Dudemanguy** [comment]
Probably fixed by #9480.
