### ISSUE TITLE
Function to invert phase

### ISSUE THREAD

**Issue by qsniyg** [mpv-player/mpv#8385]
(I have tried to find other issues regarding this, and I looked through the man page, but I couldn't find anything)

### Expected behavior of the wanted feature

Some videos unfortunately come with (accidental?) stereo phase cancelling, which makes it difficult to listen to on stereo speakers. Inverting the phase of one audio channel works, but ripping the audio, opening it in audacity, flipping the phase in one channel, then remuxing is pretty tedious, especially in the case of a playlist that all suffer from this issue.

It would be nice if it was possible to assign a key to flip the phase of one channel.

### Alternative behavior of the wanted feature

Alternatively, perhaps a feature to only play one sound channel for both speakers, which would work around the issue. This isn't necessarily the same as converting to mono (though it does result in this), as most mono conversion algorithms will sum up both the L+R inputs, which in this case would be mostly nulled due to the phase cancelling.

**Comment by haasn** [comment]
`I af toggle lavfi=[pan=stereo|FL=FL|FR=-1*FR]`

**Comment by qsniyg** [comment]
Ah, I didn't even think of that! Thank you!!
