### ISSUE TITLE
How to find the file extension for "Conditional auto profiles" ?

### ISSUE THREAD

**Issue by abactuon** [mpv-player/mpv#8388]
Does not work :
profile-desc=cond:string.match(p.filename, "m4a")~=nil
profile-desc=cond:string.find(get("filename", ""), "m4a") ~= nil

**Comment by abactuon** [comment]
Works, but there are errors in mpv.log.
Ignore, or is there another way?

[   0.071][v][auto_profiles] Re-evaluating auto profile AAC_m4a 
[   0.071][v][console] Opened config file script-opts/console.conf. 
[   0.071][v][auto_profiles] Profile condition error on evaluating: [string "profile AAC_m4a condition"]:1: attempt to index global 'filename' (a nil value)

...

[   0.089][v][auto_profiles] Re-evaluating auto profile AAC_m4a 
[   0.089][i][auto_profiles] Applying auto profile: AAC_m4a 
[   0.089][d][cplayer] Run command: apply-profile, flags=64, args=[name="AAC_m4a", mode="apply"]
[   0.089][v][cplayer] Applying profile 'AAC_m4a'...
[   0.089][v][cplayer] Setting option 'ad' = 'aac' (flags = 4)
[   0.089][v][cplayer] Setting option 'af-add' = 'lavfi=[equalizer=f=64:width_type=o:w=3.3:g=1.8]' (flags = 4)

**Comment by guidocella** [comment]
Profile conditions are supposed to error until the properties in the condition become available. If you really don't want errors logged, you would have to write conditions like `profile-cond=filename and filename:match('%.m4a$') ~= nil`

**Comment by abactuon** [comment]
Thanks, that's better.

**Comment by guidocella** [comment]
A more terse way to avoid errors with profile conditions was to use `get("property-name", default_value)`, e.g.

```
profile-cond=get('filename', ''):match('%.m4a$') ~= nil
```

**Comment by abactuon** [comment]
Thank you, it works .
