### ISSUE TITLE
add VK_KHR_DISPLAY context on Linux

### ISSUE THREAD

**Issue by nrdxp** [mpv-player/mpv#8390]
### Expected behavior of the wanted feature
I'd like to watch movies without the overhead of a display server, which works fine on my Intel integrated machines using `vo=gpu` and `gpu-context=drm`, but with my Nvidia 1060 this is not supported. However I know `VK_KHR_DISPLAY` is supported as I am already using it to play RetroArch without a display server on said Nvidia GPU.

### Alternative behavior of the wanted feature
Currently I can only acheive what I'm after if the GPU supports OpenGL's DRM context, which seems to be everything except for Nvidia (at least the card I have).

### Log file
When launching `mpv` from Linux framebuffer terminal
[log.txt](https://github.com/mpv-player/mpv/files/5682564/log.txt)

**Comment by philipl** [comment]
That's #7268 and it doesn't work in any useful way on nvidia as discussed there.

**Comment by nrdxp** [comment]
my search turned up nothing because I used the _. My bad. Thanks.
