### ISSUE TITLE
can't play UTF-8 Unicode and ISO-8859 encoded subtitle (srt) file with carriage return <CRLF> line terminator 

### ISSUE THREAD

**Issue by charlie39** [mpv-player/mpv#8392]
mpv seems unable to play subtitle files with ISO-8859 and UTF-8 (with BOM) Encoding
these files contain the DOS style CRLF line terminators. 

the sample below shows the <CR> EOL as ' ^M ' in vim text editor in linux 

### Sample files 
(two sample subtitle files are attached as well)
```
1
00:00:00,300 --> 00:00:03,570
So, what do we got?

2
00:00:03,571 --> 00:00:06,213
Terry Colby was involved in the cover-up

3
00:00:06,214 --> 00:00:08,788
of the Washington Township
toxic waste scandal.

4
00:00:08,840 --> 00:00:11,174
What do we need to prove our case?

5
00:00:11,209 --> 00:00:14,010
Someone who was there
when the decision was made

6
00:00:14,045 --> 00:00:16,346
to falsify chemical waste intel.

7
00:00:16,381 --> 00:00:18,848
Get the hell away from my
home. Get away from my home!

8
00:00:18,884 --> 00:00:21,217
Elliot, what is going on with you?

9
00:00:21,269 --> 00:00:23,803
I cannot help you if
you keep me in the dark.

10
00:00:23,855 --> 00:00:25,054
We got problems.

11
00:00:25,107 --> 00:00:26,890
The Dark Army is bailing.

12
00:00:26,942 --> 00:00:28,191
It's not over.

13
00:00:28,226 --> 00:00:30,226
We'll find a way, just not tonight.

14
00:00:30,228 --> 00:00:33,229
How do you not blow your
brains out married to him?

15
00:00:33,231 --> 00:00:34,731
You want to watch me piss too?

16
00:00:34,783 --> 00:00:38,067
- Scott, a misunderstanding...
- Happy to pull my dick out for you.

17
00:00:38,120 --> 00:00:39,819
Elliot!

18
00:00:39,871 --> 00:00:43,740
- Where is she?
- I told you you'd get her back, bro.

19
00:01:50,525 --> 00:01:52,025
Shit!

20
00:02:03,872 --> 00:02:05,788
Shit!

21
00:02:09,494 --> 00:02:11,160
Open up!

22
00:02:11,213 --> 00:02:12,996
I'm bleeding all over the hallway!

23
00:02:14,799 --> 00:02:17,834
It's a life-or-death
situation out here!

24
00:02:17,886 --> 00:02:20,253
Look, I know you're in
there. I just saw you go in.

25
00:02:20,305 --> 00:02:23,506
Open up!

26
00:02:23,558 --> 00:02:25,675
I'm looking...

27
00:02:27,178 --> 00:02:29,512
Well, are you just gonna stand there?

28
00:02:29,564 --> 00:02:31,981
Get me a glass of water, dummy.

29
00:02:32,017 --> 00:02:34,484
Can I use this? Thanks.

30
00:02:36,738 --> 00:02:38,521
My niece gave him to me.

31
00:02:38,573 --> 00:02:41,524
I haven't even named him yet. God.

32
00:02:41,576 --> 00:02:43,826
Do you know the pressure
of an ecstatic six-year-old?

33
00:02:43,862 --> 00:02:47,830
I mean, I kill that thing,
and her whole world collapses.

34
00:02:47,866 --> 00:02:50,617
I like what you did with the place.

35
00:02:50,669 --> 00:02:52,702
Hmm.

36
00:02:52,704 --> 00:02:55,705
Yeah, nice setup. Still
like mine better though.

37
00:03:08,436 --> 00:03:12,388
Yo, let me know if you
want a top-shelf hookup.

38
00:03:12,390 --> 00:03:14,974
Actually, now that I have you...

39
00:03:15,026 --> 00:03:19,562
will you help me move
a dresser... Mr. Muscles?

40
00:03:19,564 --> 00:03:22,565
Okay, come on. Just come on.

41
00:03:32,877 --> 00:03:36,329
Man 'N' Van is getting way too legit.

42
00:03:36,381 --> 00:03:37,747
They used to just be, like, drummers

43
00:03:37,749 --> 00:03:39,248
with their mom's Honda Odysseys.

44
00:03:39,250 --> 00:03:41,584
Now it's an actual company in Queens.

45
00:03:41,586 --> 00:03:45,171
I mean, the guys are literally men in vans.

46
00:03:45,223 --> 00:03:46,589
I'd buy morphine from you,

47
00:03:46,591 --> 00:03:51,594
if you could also get me Suboxone.

48
00:03:51,596 --> 00:03:55,598
Well, it's pretty much
impossible to get Suboxone.

```

[sample.tar.zip](https://github.com/mpv-player/mpv/files/5683897/sample.tar.zip)

### Important Information

Provide following Information:
- mpv version : 
➜  ` mpv --version `
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects 
 built on UNKNOWN 
FFmpeg library versions: 
   libavutil       56.51.100 
   libavcodec      58.91.100 
   libavformat     58.45.100 
   libswscale      5.7.100 
   libavfilter     7.85.100 
   libswresample   3.7.100 
FFmpeg version: n4.3.1 

- Linux Distribution and Version :          arch linux 
- Kernel :                                                clear-linux 5.6.11
- Source of the mpv binary :                   arch community repository
- If known which version of mpv introduced the problem :  checked with with version 0.32.0, same issue.
- Window Manager and version :            dwm-6.2
- GPU driver and version : 
➜ ` trash inxi -G` 
Graphics:  Device-1: Intel HD Graphics 620 driver: i915 v: kernel 
           Device-2: Quanta HP TrueVision HD Camera type: USB driver: uvcvideo 
           Display: server: X.Org 1.20.10 driver: intel resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.2.3 

### Reproduction steps
download the sample files and run with the `--sub-file=`  flag

### Expected behavior
Should be able to run/play the given subtitle files (i guess)

### Actual behavior
Throws error message as mentioned above

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/5683796/log.txt)

same result with the `--no-config` flag

**Comment by thebombzen** [comment]
The samples you provided are not valid SubRip files because they start with this:
```
00:00:00,000 --> 00:00:04,162
<font color="#fffa00"> WWW.MY-SUBS.COM</font>

1
00:00:00,001 --> 00:00:01,994
I will be the youngest executive
```
In particular, the first line is not legal. This prevents ffmpeg from autodetecting the files as SubRip files. If you try running `ffmpeg -i ep3.srt` you'll find the same thing.

**Comment by thebombzen** [comment]
You can reproduce this even after stripping away all CR characters and the BOM, and converting it to simple ASCII text (since there's nothing beyond the ASCII codepoint set, UTF-8 here is just ASCII). If I'm wrong, and these files *should* be legal, then this is an upstream problem with FFmpeg, not with  mpv, since mpv defers format detection to FFmpeg in this case.

**Comment by thebombzen** [comment]
Also, if you copy/paste the above example you provided and save it as `test.srt` with UTF-8 BOM and also CRLF files, it plays fine. So the issue is not related to UTF-8 BOM or CRLF. 
```
leo@gauss ~/Downloads :) $ 
leo@gauss ~/Downloads :) $ file test.srt
test.srt: UTF-8 Unicode (with BOM) text, with CRLF line terminators
leo@gauss ~/Downloads :) $ mpv --no-config input.mkv --sub-file=test.srt
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
     Audio --aid=2 --alang=jpn (aac 6ch 48000Hz)
     Subs  --sid=1 --slang=eng (*) 'eng' (ass)
     Subs  --sid=2 --slang=eng 'enm' (ass)
 (+) Subs  --sid=3 'test.srt' (subrip) (external)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p10
(Paused) AV: 00:00:00 / 01:45:37 (0%) A-V:  0.000
Screenshot: 'mpv-shot0001.jpg'
(Paused) AV: 00:00:00 / 01:45:37 (0%) A-V:  0.000
Exiting... (Quit)
leo@gauss ~/Downloads :) $ 
```
![mpv-shot0001](https://user-images.githubusercontent.com/1342577/102007554-1bbf2600-3cf8-11eb-9077-ca04d2d2bab3.jpg)

**Comment by qyot27** [comment]
The exact problem with the ep3.srt is the lack of a subtitle number at the first position.  All else the same, changing the beginning to:
```
0
00:00:00,000 --> 00:00:04,162
<font color="#fffa00"> WWW.MY-SUBS.COM</font>

1
00:00:00,001 --> 00:00:01,994
I will be the youngest executive
```

should be all that's necessary.  The ep1.srt has a lot of extra junk in that line before the timecodes even start.

**Comment by thebombzen** [comment]
@qyot27 that's because `ep1.srt` is actually a TAR archive with one entry, and it's the actual SRT file. Not sure how that happened, tbh.

**Comment by charlie39** [comment]
@thebombzen   @qyot27 i see, Its working out of the box with mplayer though
