### ISSUE TITLE
Should I adjust the brightness of my LCD to 203nits?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8398]
In the manual, it says the default `--target-peak` value is 203, if I don't want to change the setting of MPV player, should I adjust the brightness of LCD to 203nits? or still 100nits for SDR?

Is it going to lose details for SDR and HDR content if the brightness is below 203nits? For example, the brightness of my LCD is 158nits(40%) now, and I set the `--target-peak=158`.

**Comment by laichiaheng** [comment]
Anyone?

**Comment by Hrxn** [comment]
Whatever feels comfortable for you..

But yes, personally I'd try it with 203 nits (cd/m²), why not?

**Comment by laichiaheng** [comment]
I have a question, why choose 203? Is it a standard or something?

**Comment by Hrxn** [comment]
Well, it's not technically a standard, but an recommendation.

I think you can download the full thing easily here:
https://www.itu.int/pub/R-REP-BT.2408-3-2019

**Comment by haasn** [comment]
1. Use whatever is comfortable for you. The whole point of BT.1886 / SDR response is that it's dependent on the desired brightness and contrast, which involves subjective and situational factors.
2. If you need to follow a specific reference viewing standard, consult that reference standard (typically 100 nits). If you don't, see 1.
3. The 203 nits figure is technically just for interoperability between HDR and SDR, to help us figure out what the 'SDR white level' should be in an absolute luminance space like PQ. Whether that SDR white level actually ends up being shown at 100 nits or 203 nits is, technically, irrelevant. It only matters for the aesthetic quality of the tone mapping. (And it also matters if you plan on displaying SDR signals on a HDR display). See 1.

**Comment by laichiaheng** [comment]
>     1. Use whatever is comfortable for you. The whole point of BT.1886 / SDR response is that it's dependent on the desired brightness and contrast, which involves subjective and situational factors.
> 
>     2. If you need to follow a specific reference viewing standard, consult that reference standard (typically 100 nits). If you don't, see 1.
> 
>     3. The 203 nits figure is technically just for interoperability between HDR and SDR, to help us figure out what the 'SDR white level' should be in an absolute luminance space like PQ. Whether that SDR white level actually ends up being shown at 100 nits or 203 nits is, technically, irrelevant. It only matters for the aesthetic quality of the tone mapping. (And it also matters if you plan on displaying SDR signals on a HDR display). See 1.

Does it matter if I plan on displaying HDR signals on a SDR display?

**Comment by laichiaheng** [comment]
>     1. Use whatever is comfortable for you. The whole point of BT.1886 / SDR response is that it's dependent on the desired brightness and contrast, which involves subjective and situational factors.
> 
>     2. If you need to follow a specific reference viewing standard, consult that reference standard (typically 100 nits). If you don't, see 1.
> 
>     3. The 203 nits figure is technically just for interoperability between HDR and SDR, to help us figure out what the 'SDR white level' should be in an absolute luminance space like PQ. Whether that SDR white level actually ends up being shown at 100 nits or 203 nits is, technically, irrelevant. It only matters for the aesthetic quality of the tone mapping. (And it also matters if you plan on displaying SDR signals on a HDR display). See 1.

@haasn Such as my TV only is 105nits now, should I change the target-peak to 105?

**Comment by ValZapod** [comment]
> but an recommendation

This is a report, not a rec. For example for BT.2035 there is a report AND a recommendation --  different.
