### ISSUE TITLE
Hover buttons can be frustratingly* small

### ISSUE THREAD

**Issue by mike-ward** [mpv-player/mpv#8399]
- The size of the hover controls can be frustratingly small at times. 

- The X button at the top right gets overlapped by the window sizing borders (Windows 10) when the --no-border option is specified making it difficult to click.

![image](https://user-images.githubusercontent.com/567927/102254851-d6088600-3ece-11eb-8f4a-c04376f6efd4.png)

```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  6 10:03:04 +08 2020
FFmpeg library versions:
   libavutil       56.62.100
   libavcodec      58.114.100
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.92.100
   libswresample   3.8.100
FFmpeg version: git-2020-12-05-89e3f5ab
```

Recommendations: 

- Set a minimum height for these controls
- Add margins to move the buttons inwards from the borders 
-  Add more space between the minimize/maximize/close icons in the top right corner

\* I use frustratingly as an adjective to indicate difficulty. No pejorative or divisive sense indicated or implied. 😃

**Comment by garoto** [comment]
Scaling the OSD is an option: https://mpv.io/manual/master/#on-screen-controller-scalewindowed
