### ISSUE TITLE
MPV does not change to fullscreen/exit fullscreen until I quit the app with --vo=gpu parameter

### ISSUE THREAD

**Issue by ToTomTo** [mpv-player/mpv#8400]
-mpv version 32.0, 33.0
- MacOS version Big Sur 11.1 (but was happening also in latest Catalina)

- issue description:
- when I doubleclick on video it doesn't change to fullscreen, and if already in fullscreen, then it doesn;t change to window until I quit the app with CMD+Q
- using Menu -> Toggle fullscreen doesn't do anything
- by removing and adding parameters I found out the issue is with --vo=gpu parameter in config
I have removed it and it works as expected

**Comment by Akemi** [comment]
vo=gpu is deprecated. also don't ignore the issue template if you want help.
