### ISSUE TITLE
Refresh playlist

### ISSUE THREAD

**Issue by veyselolgun** [mpv-player/mpv#8405]
Hello,

I have a playlist and this playlist updated continously. Is it posible to refresh playlist of mpv-player when mpv-player running ? I do not want to restart mpv-player 

I tried this `mpv --playlist=playlist.m3u` but it is not work 

here is the problem:

playlist.m3u has 4 items,
then i runned mpv-player
then playlist.m3u growed up to 6 items
i am monitoring mpv-player from command line and mpv-player finished after the 4th song

Is there any way to refresh the playlist of mpv-player  ?

**Comment by c02y** [comment]
I want this too, when I started to play a local video, there is already a list, then after a while, there is a new file added into the same directory, I need to refresh the playlist, so it can play the next file in the playlist without restarting mpv, haven't find a method so far.

**Comment by veyselolgun** [comment]
Hi,

please run mpv like this;

`
mpv /home/veysel/mp3/ --input-ipc-server=/tmp/mpvsocket

`
and then from another session, run this command;

`echo '{ "command": ["loadfile", "/home/veysel/file.mp3","append"] }' | socat - /tmp/mpvsocket` 

this command will control your mpv player. I mean you can add new files to playlist directory, mpv will recognise that. (I found it from here : https://mpv.io/manual/master/#json-ipc) 

Also there is python library for mpv player, you can view it from here : https://github.com/jaseg/python-mpv 
Also you can use this code, it will update playlist when you append new file to playlist directory

`
#!/usr/bin/env python3
import mpv,os
from time import sleep
from threading import Thread	
from pathlib import Path


mp3_files_path='/home/veysel/mpv/'

player = mpv.MPV(ytdl=True, input_default_bindings=True, input_vo_keyboard=True)
player.playlist_append(mp3_files_path)
player.playlist_pos = 0


def sorted_ls(path):
    ctime = lambda f: os.stat(os.path.join(path, f)).st_ctime
    return list(sorted(os.listdir(path), key=ctime))

def update():
    files=sorted_ls(mp3_files_path)
    while 1:
        new_files=sorted_ls(mp3_files_path)
        if len(new_files)!=len(files):
            files=new_files
            print(new_files[-1]," added to playlist")
            player.playlist_append(mp3_files_path+new_files[-1])   
        sleep(1)
        

Thread(target=update).start()
while True:
    player.wait_for_playback()












`

**Comment by c02y** [comment]
Thanks, but it is too complicated, I would rather not use it.

**Comment by veyselolgun** [comment]
You're welcome, actually all you have to do is install this package https://github.com/jaseg/python-mpv then run the above code. Maybe there is another easy method. You can share here if you find it

**Comment by Akemi** [comment]
the question has been answered.
