### ISSUE TITLE
Support peertube links

### ISSUE THREAD

**Issue by alex-tee** [mpv-player/mpv#8409]
### Expected behavior of the wanted feature

`mpv https://diode.zone/videos/watch/583e7862-f2fe-4d13-9fac-40a93677202a` is expected to play the video

### Alternative behavior of the wanted feature

**Comment by avih** [comment]
mpv doesn't detect links in web pages - it uses [youtube-dl](https://github.com/ytdl-org/youtube-dl) for that. You can request them to support it.

**Comment by alex-tee** [comment]
ok thanks, it looks like it should already work but maybe there's problems with it https://github.com/ytdl-org/youtube-dl/issues/26002

either way, not mpv's issue
