### ISSUE TITLE
Wayland Xcursor not detected

### ISSUE THREAD

**Issue by travankor** [mpv-player/mpv#8410]
### Important Information

Provide following Information:
- mpv version - 0.33.0
- Linux Distribution and Version - Void
- Source of the mpv binary - package
- Window Manager and version - Wayfire 0.6.0 (wlroots) (happens with sway, too)
- GPU driver and version - Mesa 20.2.3

### Reproduction steps

1. Add cursor_theme option to wayfire.ini (or equivalent for sway)
2. Check that `XCURSOR_THEME` environment variable is set after compositor has launched
3. Start mpv with the wayland-native backend (which is the default)

### Expected behavior

Mpv respects `XCURSOR_THEME`.

### Actual behavior

Mpv uses adwaita cursor unlike other wayland-native applications.

### Log file

Wayland debug of the first few seconds of a video.

ix.io/2IO4

**Comment by Dudemanguy** [comment]
I'm not sure what the standard practice is here for wayland applications. Currently, mpv just calls `wl_cursor_theme_load` which loads the cursor theme set in `~/.icons/default/index.theme` (plus some other [paths](https://github.com/wayland-project/wayland/blob/1ab6a81816f52c17be2138ba569256b5afc029f2/cursor/xcursor.c#L620)).

It's probably possible to add more environment checking if we really want to but I'm not sure if `XCURSOR_THEME` is supposed to be a wayland standard. In the above link, it looks like `XCURSOR_PATH` is actually what should be set. In my case, I actually don't have an environment variables set for the cursor theme; I just have it defined in the `~/.icons` directory.

**Comment by travankor** [comment]
Sway/wayfire automatically set `XCURSOR_THEME` if you toggle the respective setting in their config file. I'm not sure if the setting just sets the environment variable or if there's more to it.

I don't think there's a standard for this, mostly because GTK wants to do this through dbus (not wayland). QT applications and several other applications seems to just read `XCURSOR_THEME`, which I assumed was the de-facto standard minus GNOME/GTK.

**Comment by Dudemanguy** [comment]
Yeah thinking over this some more, I don't think we should be reading this extra environment variable unless it's clearly marked as a wayland standard of some sort. This change was rejected before in the past. I know we currently read `XCURSOR_SIZE` but that's because there's no real alternative. IMO, the right solution is to set your theme in a way so that it's picked by `wl_cursor_theme_load`.

A protocol is the best solution for this (it's on [gitlab](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/21)).

**Comment by travankor** [comment]
>This change was rejected before in the past

Is there a link? I can't find it. I can only find the `XCURSOR_SIZE` PR.

>IMO, the right solution is to set your theme in a way so that it's picked by wl_cursor_theme_load.

The first argument to that function is the cursor theme. What's stupid, though is having client-side cursors by default. So clients can choose whatever cursor they want, in theory, instead of the compositor.

The `.icons` thing just changes the default cursor if the client doesn't select a cursor. Mpv just passes `NULL` as the first argument to `wl_cursor_theme_load`, which is the same as default. So this isn't really a "standard" solution at all; it just happens to work for mpv.

Correct me if I made a mistake here.

>A protocol is the best solution for this (it's on gitlab).

Unrelated, but apparently [certain resizing actions with mpv](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/33) is wrong according to the xdg-shell protocol.

**Comment by Dudemanguy** [comment]
>Is there a link? I can't find it. I can only find the XCURSOR_SIZE PR.

It's the same one. It originally included XCURSOR_THEME.

>The .icons thing just changes the default cursor if the client doesn't select a cursor. Mpv just passes NULL as the first argument to wl_cursor_theme_load, which is the same as default. So this isn't really a "standard" solution at all; it just happens to work for mpv.

I don't follow the reasoning. mpv doesn't care about client side cursors. We just want to get the default for the compositor. `wl_cursor_theme_load` is how you get the default. How is `wayland-cursor` in libwayland not a standard?

>Unrelated, but apparently certain resizing actions with mpv is wrong according to the xdg-shell protocol.

This is dated. mpv hasn't behaved like that for almost a year.
