### ISSUE TITLE
Clarification of issues relating to full screen, cropping

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#8413]
Hi!

To save time for all parties involved, I'd like to clarify a list of things I've come across in my first month as an mpv user, before possibly posting bug reports or feature requests. Thanks again for this wonderful piece of software.

Are there — or would you consider — a shortcut key for:

1. (While in full screen) — Zooming the video to fill exactly the screen height, necessarily cropping the sides?
2. (While in full screen) — Showing the video in its exact original size, aligned to the screen center?
3. Cycling through a list of ratios to crop the video by, eg. mpv.conf: `crop-ratios='4:3 16:9 2.21:1'`?

Would you consider:

1. Auto-cropping hard-coded black bars (correct vertical subtitle position being a major perk)?
2. Aligning large videos to the screen center (rather than the top-left corner) when exiting full screen?

Other questions:

1. Why are subtitles shrinking when zooming with `alt plus`?
2. Is DVD image support supposed to be fully functional, or only experimental? In one case, menus could not be navigated, and a 90 minute film only came up as 30 minutes.

**Comment by Akemi** [comment]
1. `w` or `e`
2. `--video-unscaled` but no shortcut, you can set one yourself, we usually don't consider new shortcuts for obscure stuff
3. that should be done with a script, might be a bit too complex for a shortcut

1. https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua
2. it will place the window where it was when not in full screen, at least on macOS. you probably need to be more specific

1. they are not shrinking though, just cut off. i believe if you want zoom without that you need to use crop. https://github.com/aidanholm/mpv-easycrop or others https://github.com/mpv-player/mpv/wiki/User-Scripts
2. no dvd support is not functional. menus completely not. it might just only play the first vob file

**Comment by guidocella** [comment]
You can use A to cycle through aspect ratios. By default it's bound to cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"

**Comment by Akemi** [comment]
that's not for cropping by aspect ratio though, and that's what he is asking for.

**Comment by forthrin** [comment]
Thanks for your fast and concise response.

1. Ah! Pan-Scan does the job. Had some problems with it and thought it had another purpose. Case closed.
2. Orange Traffic Cone has `O` for this. It's actually quite useful sometimes.
3. Orange Traffic Cone has `C` for this. It's actually quite useful sometimes.
4. Built-in auto-crop is decidedly out of scope?
5. Ignore this.
6. See attachment.
7. Copy that.

https://user-images.githubusercontent.com/1167421/102918721-c0273200-4487-11eb-9be9-72d62f92c4f2.mp4

**Comment by Akemi** [comment]
2. like i said just add your own shortcut? or is there a problem with that? `X cycle_values video-unscaled yes no` or `X cycle video-unscaled`
3. if you want keyboard shortcuts you basically need 2:
```
x cycle_values vf "crop=iw:iw/4*3" "crop=iw:iw/16*9" "crop=iw:iw/2.11*1" ""
X  cycle_values vf "crop=ih/3*4:ih" "crop=ih/9*16:ih" "crop=ih/1*2.21:ih" ""
```
the first shortcut works for videos `video_aspect_ratio >= target_aspect_ratio`
the second for `video_aspect_ratio <= target_aspect_ratio`
if you need it on one shortcut, you need to use a script
4. there is a script for it, so the chances are slim. in the end, if it is added, we might just add that exact script to the binary itself. same as console.lua, osc.lua or ytdl.lua
6. maybe vobsubs/imagesubs? this is again a question we can't really answer without more info, the infos we usually request on the issue template. this could be a bug.

**Comment by qmega** [comment]
`crop=[if(lte(iw/16,ih/9),iw,ih/9*16)]:[if(lte(iw/16,ih/9),iw/16*9,ih)]` will crop anything to 16:9. Replace the 16s and 9s for other target aspect ratios, and you can fit a crop-cycle on one key.
