### ISSUE TITLE
What is the best preference of tscale-radius for interpolation?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8414]
```
tscale=box
tscale-window=sphinx
tscale-radius=0.7
tscale-clamp=0.0
```
If the `tscale-radius` is equal to 0.95 or 1.0, the image will be too much blur, it causes my eye strain and hard to focus on the image , 0.7 seems to reduce judder without losing sharpness. I'm not sure if 0.7 is the best, what is everyone's recommendation?

**Comment by Akemi** [comment]
there is no 'best'. just try it and use whatever you like.
