### ISSUE TITLE
Vsync Jitter in Gnome Wayland is not as low as other Wayland compositors

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8416]
### Important Information

Provide following Information:
- mpv 0.33.0-49-gfa903f3eeb
- Manjaro Gnome Unstable Branch
- AUR
- Every version
- Mutter 3.38.2+4+g00e247ed7-1
- Mesa Gallium driver 20.3.1 for Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.10.2-1-MANJARO, LLVM 11.0.0)
- 
![2020-12-22 17-28-35 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/102873271-de873080-447b-11eb-80ca-f4e360ea8f35.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Just play any video.

### Expected behavior

Vsync Jitter get close to 0 and stay stable.

### Actual behavior

It is never 0, sometimes higher, sometimes lower.

### Log file

https://0x0.st/iCee.txt

### Sample files

Any video.

**Comment by CounterPillow** [comment]
why would this be an mpv bug?

**Comment by laichiaheng** [comment]
Oops, it should be reported to Mutter, wrong place.

**Comment by Dudemanguy** [comment]
FWIW, 0.072 isn't actually bad.

**Comment by laichiaheng** [comment]
> FWIW, 0.072 isn't actually bad.

But in Xorg or other Wayland compositors, it is 0.

**Comment by Dudemanguy** [comment]
Well yes that's just because those things implement presentation feedback and mutter on wayland currently doesn't. That's expected.
