### ISSUE TITLE
Build error on macOS Big Sur 11.1

### ISSUE THREAD

**Issue by xanadu6291** [mpv-player/mpv#8417]
### Important Information

Provide following Information:
- mpv version: Current Git Head
- macOS Version: Big SUr 11.1
- Source of the mpv binary or bundle: Current Git Head
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
git pull
./waf configure --prefix=${TARGET} --disable-debug-build --disable-manpage-build CC=/usr/bin/gcc AR=/usr/bin/ar
./waf build

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
Can build correctly
I already confirmed that mpv source dated Nov.6, 2020 can build correctly.  So something happened in the range of date from Nov. 6 to current...

### Actual behavior
waf build fails with the following error...
tougenroushinoMacBook-Pro:mpv roushi$ ./waf build
Waf: Entering directory `/Volumes/mpv_compile/compile/mpv/build'
Traceback (most recent call last):
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 118, in waf_entry_point
    run_commands()
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 178, in run_commands
    ctx=run_command(cmd_name)
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 169, in run_command
    ctx.execute()
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 366, in execute
    return execute_method(self)
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Build.py", line 93, in execute
    self.execute_build()
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Build.py", line 96, in execute_build
    self.recurse([self.run_dir])
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/Volumes/mpv_compile/compile/mpv/wscript", line 1018, in build
    ctx.load('wscript_build')
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 83, in load
    fun(self)
  File "/Volumes/mpv_compile/compile/mpv/wscript_build.py", line 52, in build
    ctx.load('generators.sources')
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 80, in load
    module=load_tool(t,path,with_sys_path=with_sys_path)
  File "/Volumes/mpv_compile/compile/mpv/.waf-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 389, in load_tool
    __import__(x%tool)
  File "/Volumes/mpv_compile/compile/mpv/waftools/generators/sources.py", line 4, in <module>
    from TOOLS.matroska import generate_C_header, generate_C_definitions
  File "/Volumes/mpv_compile/compile/mpv/TOOLS/matroska.py", line 420
    print("    " * depth, '[' + elid + ']', elem.name, 'size:', length, 'value:', end=' ')
                                                                                     ^
SyntaxError: invalid syntax

### Log file

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by jeeb** [comment]
Probably due to that script now requiring Python 3. If you re-bootstrap waf, it should patch the shebang to point towards python3. Otherwise, you may just run waf with python3 manually.

**Comment by xanadu6291** [comment]
$ ./bootstrap.py 
Downloading https://waf.io/waf-2.0.20...
Download failed.
Downloading http://www.freehackers.org/~tnagy/release/waf-2.0.20...
Download failed.
Could not download waf-2.0.20.

bootstrap fails with above.  How should I do?

**Comment by xanadu6291** [comment]
Also, I have tried to download waf manually.  Then there is version of  2.0.21.  In addition version 2.0.21 of waf also fails with same syntax error...

**Comment by Akemi** [comment]
do what jeeb said. try with python3 instead.

also bootstrap not being able to download waf is a problem on your end, most likely. it works as expected here.

**Comment by jeeb** [comment]
Yes, because bootstrap when it is successful in downloading waf will patch it, since waf upstream says that until they release 3.0 they do not want to make the first line of it `#!/usr/bin/env python3`.

Just run waf with `python ./waf OPTIONS`  manually if you cannot make bootstrap work :)

**Comment by jeeb** [comment]
You can also see why your download fails by applying this patch
```diff
diff --git a/bootstrap.py b/bootstrap.py
index 2d9e8b4294..51b81f5e8e 100755
--- a/bootstrap.py
+++ b/bootstrap.py
@@ -27,8 +27,8 @@ for WAFURL in WAFURLS:
         print("Downloading {}...".format(WAFURL))
         waf = urlopen(WAFURL).read()
         break
-    except URLError:
-        print("Download failed.")
+    except URLError as err:
+        print("Download failed! ({})".format(err))
 
 if not waf:
     print("Could not download {}.".format(WAFRELEASE))
```

**Comment by xanadu6291** [comment]
Hello Jeeb-san,

Error of bootstrap is SSL: CERTIFICATE_VERIFY_FAILED.  I don't know why...

$ python3 bootstrap.py 
Downloading https://waf.io/waf-2.0.20...
Download failed! (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>)
Downloading http://www.freehackers.org/~tnagy/release/waf-2.0.20...
Download failed! (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>)
Could not download waf-2.0.20.

**Comment by avih** [comment]
Are you behind some firewall which can mess with HTTPS? because I just tried it, and it does download for me without issues...

**Comment by jeeb** [comment]
@xanadu6291 it could be that your python3 installation lacks certificates authority configuration or so? Are you using homebrew or normal python.org Python3? If homebrew, check if they have any notes regarding this.

**Comment by xanadu6291** [comment]
Tried with waf in my hand using python3

$ python3 waf --version
waf 2.0.9 (8a950e7bca9a3a9b1ae62aae039ef76e2adc4177)

$ python3 waf build

Succeeded to build mpv Thank you!!

**Comment by xanadu6291** [comment]
@jeeb I don't use homebrew.  I downloaded installer package from https://www.python.org/downloads/

**Comment by jeeb** [comment]
@xanadu6291 huh, I just searched for this and apparently this might be a thing you just need to do with recent enough python3 binaries due to Apple saying they are deprecating their openssl libraries...

From https://bugs.python.org/issue17128#msg315341 :
> As of 2.7.15 (finally!) all current python.org macOS installers now provide their own copies of OpenSSL: 1.0.2x for 3.6.x and 2.7.15. 1.1.0x for the upcoming 3.7.0 release.  Until a better solution for root certificates is implemented, all of the installers also now provide a "Install Certificates.command', a script which will download and install the latest third-party `certifi` bundle of certificates from PyPI and configure the ssl module to use them.  Declaring this issue resolved.  Thanks everyone!

So if you have a thing called `Install Certificates.command`, that... might fix it?

**Comment by xanadu6291** [comment]
@jeeb Thank you for your follow-up.  I just ended python3 installation process without installing certificates.  My bad, it's my fault...  So sorry.

Now I can update waf successfully.  Also with current waf(2.0.20), I can build mpv successfully!!

**Comment by xanadu6291** [comment]
@avih Thanks for your comment.  The problem is my fault.

**Comment by xanadu6291** [comment]
@Akemi Thanks for your comment.  All of my problem was solved.  Jeeb-san helped so much!!
