### ISSUE TITLE
The stats overlay's font_color setting is not RGB, but BGR

### ISSUE THREAD

**Issue by matoi974** [mpv-player/mpv#8419]
### Important Information

Provide following Information:
- mpv version 
0.33.0-46-gdde0189279
- Windows Version 
Windows 7 SP1
- Source of the mpv binary 
shinchiro's build

### Reproduction steps

Create %APPDATA%\mpv\script-opts\stats.conf and write the following:
```
font_color=FF0000
```
Run mpv.
Press `i` to toggle stats overlay.
### Expected behavior
Text is red (FF0000)
### Actual behavior
Text is blue (0000FF).
### Log file
https://pastebin.com/C9AgMtiD

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/man/stats.rst

"Note: colors are given as hexadecimal values and use ASS tag order: BBGGRR (blue green red)."

that's how the ass 'standard' works. colors are defined as bbggrr, see http://docs.aegisub.org/3.2/ASS_Tags/
