### ISSUE TITLE
OSD-info while seeking through OSC seekbar or Mpris

### ISSUE THREAD

**Issue by tolgagunok** [mpv-player/mpv#8423]
Can you add OSD info when seeking with OSC seekbar or MPRIS like in the picture (in every seek event like smplayer).
I tried to find a suitable script but i could not.

![Screenshot_20201226_141754](https://user-images.githubusercontent.com/76615463/103150540-47c1b900-4786-11eb-8042-b966fc09c619.png)

**Comment by Akemi** [comment]
i don't think the OSC should trigger this. if you want to show OSD on seek there are input key prefixes like `osd-msg`.
https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst#input-command-prefixes

**Comment by avih** [comment]
> not the first user who prefers temporary OSC popup over OSD popup

Sorry, I misread the issue.

What OP actually wants is that seeks at the OSC (click/drag) show an OSD timestamp.

I guess it's not impossible, and preferably added in some very generic way, but no one has done it for now.
