### ISSUE TITLE
Support h265

### ISSUE THREAD

**Issue by Aphexus** [mpv-player/mpv#8427]
I ended up converting a lot of my files to h265:

Codec: MPEG-H Part2/HEVC (H.265) (hev1)

Can we get this supported or some way to use ffmpeg or vlc indirectly?

(I actually use foobar mpv so I can play videos in foobar because it works better with the way my system is configured. I replaced the libmpv dll to the latest(0.33) but it doesn't support h265 now so I can't actually use my files in the way I'd like. (I have multiple sound systems and have things configured in a convoluted way)

**Comment by Akemi** [comment]
h265 is supported through ffmpeg like any other format. there is nothing stopping (lib)mpv to play back such files. if you have an actual issue please report is as a proper issue with logs.

**Comment by avih** [comment]
(lib)mpv uses ffmpeg as a library, and h265 has been supported for ages by ffmpeg (which mpv uses) and mpv.

If your application uses libmpv and h265 doesn't work, then either the ffmpeg on your system doesn't support it, or, if libmpv was linked statically with ffmpeg - then it was linked with ffmpeg library which was built without h265 support.

To be honest, I don't know if ffmpeg can even be built without h265 decoding support (libx265 is only needed to encode h265), so bottom line, it should work, or you need to rebuilt ffmpeg with the required support.
