### ISSUE TITLE
stutter and heavy frame drop with scale=spline36 and deband=yes

### ISSUE THREAD

**Issue by sponk0** [mpv-player/mpv#8428]
### Important Information

Provide following Information:
- mpv version: mpv 0.32.0
- Linux Distribution and Version: Debian GNU/Linux bullseye/sid
- Source of the mpv binary: Debian "unstable" repository
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: mate-desktop/unstable,now 1.24.1-2 amd64
- GPU driver and version:
[vo/gpu/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/gpu/opengl] GL_RENDERER='Mesa DRI Intel(R) HD Graphics 2500 (IVB GT1)'
- Possible screenshot or video of visual glitches: n.a.

### Reproduction steps
- playing sample file (attached) with --no-config is fine
- adding --scale=spline36 and/or --cscale=spline36 triggers the issue, especially when combined with --deband=yes
- I first noticed that the problem is triggered with --profile=gpu-hq, further analysis showed that the options above give the problems
- I've tried with 50Hz and 60Hz screen refresh rate, problem occurs in both scenarios
- different options for --video-sync=... give similar results

### Expected behavior
smooth playback (no or little frame drop)

### Actual behavior
Using the scaler options "scale=spline36" and/or "cscale=spline36" cause heavy framedrop, especially when used together with "deband=yes"
I've only observed this behavior for 50Hz video files (regardless of the screen refresh), but I can't tell for sure if it's really caused by the video FPS.

I did a quick searched of the bug tracker archive, those two entries describe issues with similar command line options. possibly related?
[https://github.com/mpv-player/mpv/issues/8223](https://github.com/mpv-player/mpv/issues/8223)
[https://github.com/mpv-player/mpv/issues/7707](https://github.com/mpv-player/mpv/issues/7707)

### Log file
various combinations of scaler and deband options:

[logfile_display50Hz_scale_bilinear_deband_no.txt](https://github.com/mpv-player/mpv/files/5751442/logfile_display50Hz_scale_bilinear_deband_no.txt)
[logfile_display50Hz_scale_bilinear_deband_yes.txt](https://github.com/mpv-player/mpv/files/5751443/logfile_display50Hz_scale_bilinear_deband_yes.txt)
[logfile_display50Hz_scale_spline36_deband_no.txt](https://github.com/mpv-player/mpv/files/5751444/logfile_display50Hz_scale_spline36_deband_no.txt)
[logfile_display50Hz_scale_spline36_deband_yes.txt](https://github.com/mpv-player/mpv/files/5751445/logfile_display50Hz_scale_spline36_deband_yes.txt)

### Sample files
video that causes frame drops:
https://user-images.githubusercontent.com/76743841/103299893-e3a92a00-49fd-11eb-9254-8f67b41070b6.mp4

- Possible screenshot or video of visual glitches
n.a.

**Comment by CounterPillow** [comment]
>  [vo/gpu/opengl] GL_RENDERER='Mesa DRI Intel(R) HD Graphics 2500 (IVB GT1)'

your GPU is too weak to handle it at 50fps.

**Comment by sponk0** [comment]
Thanks a lot for the explanation. I guess I can close the "issue" then.
