### ISSUE TITLE
intermittent stutter due to mistimed frames with Wayland backends + interpolation

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#8431]
### Important Information

Provide following Information:
- mpv 0.33.0-51-gbe167c227b
- Arch
- own mpv build
- any Wayland compositor, e.g. Sway or Plasma (with or without presentation timing feedback support)
- mesa-git 21.0.0_devel.132228.574429f9528
- RX 5700 XT

### Reproduction steps

Play a 4k 60fps VP9 video with these settings inside a Wayland session (so mpv's Wayland backend is picked):

```
hwdec=vaapi
#gpu-context=x11egl

cscale=ewa_lanczos
scale=ewa_lanczos
dscale=ewa_lanczossharp

video-sync=display-resample
interpolation
```

### Expected behavior

There should be no mistimed frames.

### Actual behavior

There are intermittent vsync jitter spikes with mistimed frames (visible as stutter). They occur with both VAAPI and software decoding, but usually more often/earlier with VAAPI. They also occur with Vulkan. They don't occur with XWayland, i.e. `--gpu-context=x11egl`. They also don't occur with the native Wayland backends when `--interpolation` isn't used. Seems to be awfully specific, it's sometimes hardly triggered by other videos for me. The chosen Wayland compositor doesn't seem to matter (but I compiled Sway and wlroots from git-master to be sure).

I tried whether forcing CPU/GPU into maximum performance makes a difference, which isn't the case. Also Xorg is free of any reported mistimed frames, display runs at 85Hz.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5756061/output.txt)

### Sample files

https://www.youtube.com/watch?v=aqz-KE-bpKQ

**Comment by Dudemanguy** [comment]
I can reproduce this pretty reliably that Big Buck Bunny sample but only if the video is played over the network. If I download it locally and play it, it works fine.

**Comment by aufkrawall** [comment]
Is it always dropped frames for you? In my case, they mostly (if not solely?) get reported as mistimed. I've got the video stored locally. I played the whole video several times and it really did not report any mistimed/dropped frames during playback with xwayland. I can check once more to be sure. It also seems that using`vaapi-copy` seems to prevent the issue, or at least reduces it to a great amount. Wild guess: Perhaps that indicates some timing issue and some magic number might not be optimal? I'd try patches if you have a suspicion. :)

**Comment by Dudemanguy** [comment]
I get everything: dropped, mistimed, and delayed frames. However, I see it in xwayland basically just as often as wayland and it seems to occur around the same time (the zoom/panning shot in the beginning). I don't think I'm seeing whatever you're seeing. Maybe my GPU is just too bad for 4k at 60fps.

**Comment by aufkrawall** [comment]
I've repeated some tests and it really seems to be as I initially assumed: It's worst with Wayland VAAPI (frequent jitter spikes), better with Wayland software decoding (rares spikes) and best with XWayland (no spikes reported at all, like on Xorg with VAAPI).
Would be interesting what happened if mpv supported VAAPI via dmabuf so that it worked with xwayland. :)

**Comment by accaldwell** [comment]
I have a similar setup (Arch, Wayland, Interpolation) and switching to the 5.4 LTS kernel from 5.10.x fixed stutter/judder issues for me. MIght be worth trying if this is a new issue for you. For me, the problem was noticeable even in 1080p/24 content, so not sure if its the same issue.

**Comment by aufkrawall** [comment]
I've just tested this and the issue exists also with linux-lts 5.4.89. I wonder if both kernel and mesa actually do anything differently with xwayland vs. mpv native wayland (without vaapi). Even on Gnome 3.38.3 there aren't any reported dropped/mistimed frames with xwayland (at least not during the single occasion when I was testing it). :)

**Comment by aufkrawall** [comment]
Doesn't seem to be a regression caused by subsequent commits after display-resample was implemented for the Wayland backend, as I can go back to ea4685b233090bb155cfa4ec6bf87f421a553168 and still have this issue.

**Comment by Dudemanguy** [comment]
Just revisiting this after a while but it seems I'm now able to play this video without any issues (technically, I upgraded my CPU since last time but that shouldn't really matter). My GPU does not have hwdec support for vp9 however so I cannot test what effect that would have if any. With default software decoding, all was fine.

I'm using a lowly RX 560, but my display is only 60hz not 85hz so my setup has much less work to do than yours. This is on kernel 5.11.1 and mesa 20.3.4.

**Comment by aufkrawall** [comment]
I still have the occasional vsync jitter spikes with mistimed frames in the wake of them. :(

The jitter isn't necessarily very high, e.g. 0.04x instead of 0.02x, but that's already enough to make it visibly stutter. With xwayland, the jitter value is generally much higher, e.g. 0.11x, but it's rather stable and no intermittent spikes occur.

I'm now with an RX 6800 isntead of 5700 XT and the issue hasn't changed.

Well,  4k VAAPI is currently broken on the 6800 , so I lost vaapi-copy as a workaround for the stutter issue and mpv xwayland doesn't prevent screen locking... :(

**Comment by aufkrawall** [comment]
I can't reproduce anymore without VAAPI decoding, so maybe it remaining troublesome indicates another issue specifically with (Navi) VAAPI in mpv on Wayland?
There's btw. no difference for me between the old render loop (Plasma 5.21.5) or the new one on sway (latest git-master).

**Comment by damige** [comment]
This is issue still the case for me (Sway), has been bugging me for months. x11egl does indeed provide a workaround, though ideally xwayland should not be neccesary. There seems to be some issue with the later kernels in combination with MPV and Wayland.

**Comment by Dudemanguy** [comment]
Pity, I hoped maybe mesa or the kernel did something that would fix this by now. Does it occur for you with software decoding or do you need `vaapi` enabled to trigger it?

**Comment by damige** [comment]
It occurs for me in software ,vaapi, and nvdec-copy (laptop with intel+nvidia gpu) when gpu-context=wayland, or waylandvk.
latest mpv compiled from git does not fix it. neither does latest libplaceabo and vo=gpu-next. I seem to get acceptable framerates with gpu-context=wayland when i set: 
- hdr-compute-peak=no
- tone-mapping=reinhard
- tone-mapping-desaturate=1
- tone-mapping-desaturate-exponent=0

But after doing this the image quality is way lower. This is while playing a HEVC x265 10bit  video. anything 1080p or lower does not seem to suffer the same drops.

I used to be able to run MPV with interpolate & video-sync=display-resample but this seems to be impossible now.

I have also noticed that Xwayland(context:x11egl) seems to run at 2560x1440 (scaled resolution, viewed with shift+i) while wayland(context:wayland) makes it 5120x2880. My native screen res is 3840x2160. Maybe this is related to the performance difference? I am using Sway & wlroots.

**Comment by damige** [comment]
Alright, now X11EGL also stutters when "output scale 1" is set in sway.conf. Output in xwayland shows native 4K. the x11egl workaround just seemed to "fix" it due to downscaling the resolution.

**Comment by Dudemanguy** [comment]
>I have also noticed that Xwayland(context:x11egl) seems to run at 2560x1440 (scaled resolution, viewed with shift+i) while wayland(context:wayland) makes it 5120x2880

Okay that's really funky. I would think the reported resolution is wrong in this case. Fractional scaling on wayland works weirdly since mpv as a client can only handle integer values. I haven't actually verified what compositors report to us in the fractional case but I'd assume they would pick an integer value lower than the scale (e.g. `1` in the case of a `1.5` scale) so mpv would render at a 1x scale and then the compositor does the upscaling from there. I guess I should verify why exactly `osd-dimensions` is reporting something weird here though. This sounds like a bug.

>edit: sway: " output scale 1.50" seems to effect this. Now i removed that statement xwayland is 1920x1080 and wayland shows native 4k.

Yeah that's correct and expected. xwayland's resolution will be upscaled by the compositor so in reality you would only be rendering at 1920x1080 for this video.

>Alright, now X11EGL also stutters when "output scale 1" is set in sway.conf. Output in xwayland shows native 4K. the x11egl workaround just seemed to "fix" it due to downscaling the resolution.

Are you able to render native 4K on xorg without any issues?

**Comment by damige** [comment]
> Are you able to render native 4K on xorg without any issues?

After logging back into gnome (X11) i have found i now have exactly the same issues there. Unfortionatly i cannot downgrade the LTS kernel to 5.4, as i now believe it probably has nothing to do with wayland vs xorg, and the probem might be there.

> I have a similar setup (Arch, Wayland, Interpolation) and switching to the 5.4 LTS kernel from 5.10.x fixed stutter/judder issues for me. MIght be worth trying if this is a new issue for you. For me, the problem was noticeable even in 1080p/24 content, so not sure if its the same issue.

I remember doing this a year ago and fixing the same sort of issues then. (interpolation suddenly started stuttering)

**Comment by aufkrawall** [comment]
If there is any stutter on Xorg, the issue might be totally unrelated to the initial Wayland report.

I suggest on Xorg,

- try xf86-video-amdgpu (and perhaps also latest git-master)
- try with uncomposited Xorg (e.g. Plasma with compositor suspended)
- try disabling night light feature or similar if enabled (legacy non-atomic gamma ramps API causes stutter)
- set CPU clock governor to performance
- With RDNA2, configure GPU clocking more aggressive: https://gitlab.freedesktop.org/drm/amd/-/issues/1500#note_825883
- In case of multi-monitor, try with only one monitor connected

I was free of any intermittent stutter during playback on Xorg with latest kernel and mesa versions in ~May 2021 when I sold my 6800.

Ironically, I'm now with Nvidia and 144Hz monitor, and I'm not able to achieve stutter free playback either with 100Hz or higher on both Xorg and Wayland (Windows works, at least with broken multi-plane overlay of DWM disabled)...

**Comment by Dudemanguy** [comment]
Yeah I'm fairly certain your issue is unrelated to the OP.

Regarding the scaled resolution value in the 1.5 case. It's actually correct. This is just what the compositor (well sway in this case) reports. For a 1920x1080 video, it will say that its resolution is 2560 x 1440 and then tell mpv that the scale is 2. So mpv renders the video at 5120 x 2880 (more expensive than just rendering at 4k funnily enough). The compositor then downscales that to your actual screen size. It's unfortunately a bit unintuitive but we have no control over whatever weird scaling the compositor wants to do. This example is actually a pretty decent argument why wayland should support fractional scaling in the client api but oh well that ship probably sailed ages ago.

**Comment by Dudemanguy** [comment]
Time for the annual, "is this still a problem" post.

**Comment by aufkrawall** [comment]
I probably won't be owning any AMD GPU for the next decade or two, so I won't be of any use for this.

**Comment by aufkrawall** [comment]
I now think my tests were flawed by amdgpu power saving features, as I've recently stumbled over some stutter oddities with a 6700 XT. Even when forcing 3D clocking profile (`echo 1 > .../pp_power_profile_mode`), there was stutter (on KWin Xorg not even noticed by mpv stats). After setting more aggressive compute clocking behavior  (`echo 5 > .../pp_power_profile_mode`), all issues went away., including KWin Wayland with various mpv settings/video formats.

@Dudemanguy Might be interesting for Wayland video content type protocol? Imho clocks for video should ramp up rather quickly, but clocking down should have some inert hysteresis (or whatever does the trick).

**Comment by damige** [comment]
Problem still exists, hdr-compute-peak=no is still the work around.
