### ISSUE TITLE
Does MPV read the HDR metadata to work with hdr-comput-peak?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8432]
Recently, I saw a scene in Interstellar which brightness increases dramatically, is that normal for hdr-comput-peak?
Does hdr-compute-peak read the metadata to determine how bright the image is, or use its own technology like dynamic tone-mapping like LG TV do?
![2020-12-31 12-02-56 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/103393919-57634800-4b60-11eb-91f2-0ad0286eec53.png)
![2020-12-31 12-06-20 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/103393957-a1e4c480-4b60-11eb-8736-5511c513afa5.png)

It becomes brighter and brighter in the same scene.

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Doofussy2** [comment]
No, it uses the compute shaders of your GPU driver to measure the brightness of each frame. So some drivers will be better than others. But you can tune it.

https://mpv.io/manual/master/#options-hdr-compute-peak

**Comment by laichiaheng** [comment]
@Doofussy2 Is auto equal to yes?

**Comment by CounterPillow** [comment]
> So some drivers will be better than others.

??????????????????
no, that's not how compute shaders work

**Comment by laichiaheng** [comment]
> > So some drivers will be better than others.
> 
> ??????????????????
> no, that's not how compute shaders work

You mean every driver is the same?

**Comment by Doofussy2** [comment]
> > So some drivers will be better than others.
> 
> ??????????????????
> no, that's not how compute shaders work

My understanding is that the compute shaders are part of the OpenGL driver. And depending on the generation of the GPU/driver some will work better than others.

**Comment by Doofussy2** [comment]
> @Doofussy2 Is auto equal to yes?
> Is it possible to get the brightness information from metadata?

If your GPU doesn't support compute shaders, using auto, they won't enable using them. The manual says that compute peak could perform horribly on some drivers.

**Comment by haasn** [comment]
> Is it possible to get the brightness information from metadata?

`--hdr-compute-peak=no`

> My understanding is that the compute shaders are part of the OpenGL driver.

No, it's part of mpv. Specifically, [here](https://github.com/mpv-player/mpv/blob/master/video/out/gpu/video_shaders.c#L596).

**Comment by Doofussy2** [comment]
Ah! My mistake. Thanks @haasn

**Comment by laichiaheng** [comment]
> > Is it possible to get the brightness information from metadata?
> 
> `--hdr-compute-peak=no`
> 
> > My understanding is that the compute shaders are part of the OpenGL driver.
> 
> No, it's part of mpv. Specifically, [here](https://github.com/mpv-player/mpv/blob/master/video/out/gpu/video_shaders.c#L596).

Which one is closest to how Dolby Vision or HDR10+ does?

**Comment by Hrxn** [comment]
Well, if they have HDR metadata, then use the HDR metadata, I guess?
