### ISSUE TITLE
Assertion failure when using image video output

### ISSUE THREAD

**Issue by magsilva** [mpv-player/mpv#8433]
### Important Information

Provide following Information:
- mpv version: 0.33.0
- Linux Distribution and Version: Fedora 33

### Reproduction steps

Play video using image as video output. For instance:
mpv --no-config ""any video file.mp4" --vo=image

### Expected behavior
Several images with the output of the video.

### Actual behavior
No file with image is created. Instead, the execution is aborted due to a failed assertion:

```
[vo/image] Saving 00000001.jpg
mpv: ../video/zimg.c:241: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
Aborted (core dumped)
```

I also tried the master branch of the git repository, but the error is the same.

I also tried to remove the related assertions at  repack_entrypoint() in video/zimg.c and  at repack_line() in video/repack.c. After disabling them, the files were created as expected:
```
mpv "video file.mp4" --vo=image
 (+) Video --vid=1 (*) (h264 1080x720 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
VO: [image] 1080x720 yuv420p
[vo/image] Saving 00000001.jpg
AO: [pulse] 44100Hz stereo 2ch float
AV: 00:00:00 / 01:43:31 (0%) A-V:  0.000
[vo/image] Saving 00000002.jpg
AV: 00:00:00 / 01:43:31 (0%) A-V:  0.000
```

**Comment by CounterPillow** [comment]
What version of zimg? I can't reproduce this with zimg 3.0.1.

**Comment by magsilva** [comment]
Indeed! Fedora 33 ships with zimg 2.9.3. I download and compiled the latest zimg (3.0.1) and it worked fine. Thank you!

I have reported the bug at Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1911947).
