### ISSUE TITLE
How do you match the current audio stream's language for a conditional profile?

### ISSUE THREAD

**Issue by nicewaffles** [mpv-player/mpv#8437]
I am trying to make a conditional profile that activates when the audio stream is marked with a specific language, but I cannot figure out how to do this.
I tried finding the correct property with the command `show-text "${test-property}"`, and found that `aid` shows the number and language of the current audio stream.
Then I put `profile-cond=aid:match"eng" ~= nil` (using English as an example) in my mpv.conf and opened a file with one audio stream that was displaying `(1) eng` with the command `show-text ${aid}`, but the profile that I configured did not activate.
I suspect that I messed up the condition, as I am not that familar with Lua. Most examples of conditional profiles I could find dealt with numbers or file paths, so I'm shooting in the dark with my attempts.
What is the proper way to do this?

**Comment by guidocella** [comment]
`profile-cond=get("current-tracks/audio/lang") == "eng"` works.

**Comment by nicewaffles** [comment]
@guidocella 
That worked, thanks!
I was able to make it work as a regex by using `profile-cond=get("current-tracks/audio/lang"):match("eng?") ~= nil` (matches `en` and `eng`, for example).
