### ISSUE TITLE
Error when I try to use vapoursynth

### ISSUE THREAD

**Issue by AlucardSama04** [mpv-player/mpv#8438]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20210103-git-3e175df
- Windows Version: 20H2 (19042.685)
- Source of the mpv binary; shinchiro build's
- If known which version of mpv introduced the problem: nope
- Possible screenshot or video of visual glitches: https://i.postimg.cc/63VtDtfY/Screenshot-5.png

I am trying to use VapourSynth with MPV but I get this error.

**Comment by Akemi** [comment]
you are not supposed to ignore the issue template like it is said many times. please provide all the info we ask for.
