### ISSUE TITLE
support fd://N in --input-ipc-server

### ISSUE THREAD

**Issue by redneb** [mpv-player/mpv#8439]
I have written a linux script where I use the `--input-file` command line option, which is deprecated. I tried to switch to the newer `--input-ipc-server`, but this option seems to only support paths (where mpv creates & binds to a unix domain socket). While this very reasonable and covers most use cases, I still think that supporting the `fd://N` notation would make sense.

My use case is that my script launches a *private* instance of mpv. I want my script to have *exclusive* control over that mpv instance and I do not want other processes being able to attach to it. So what I currently do is to create a pair of anonymous interconnected sockets (with `socketpair`) and then pass one of them to mpv with `--input-file=fd://N`. This makes the communication channel *private* and has the added benefit that it does not create any file system object (e.g. a unix domain socket) that has to be eventually somehow garbage collected.

So I propose to have `--input-ipc-server` support the `fd://N` notation (and `fdclose://N` for that matter) with the same semantics as `--input-file`, i.e. when specified, mpv should treat `N` as an already open file descriptor that can be used bidirectionally.

**Comment by avih** [comment]
Aren't file descriptors a per-process thing? i.e. an fd number in one process means nothing in another process, and so they can't be used the way you want it to work?

**Comment by oakkitten** [comment]
when you `fork()` or `posix_spawn()`, the child process, even if you `exec()` later, inherits (copies of) parent's file descriptors. you can also send file descriptors via unix domain sockets

**Comment by redneb** [comment]
> Aren't file descriptors a per-process thing? i.e. an fd number in one process means nothing in another process, and so they can't be used the way you want it to work?

Yes, they are a per-process thing, but when an FD is marked as inheritable (i.e. when the close-on-exec flag is clear, which is the default) then all children process inherit it (or rather they receive a copy of it) and it has same number in the children as it has in the parent.

> Also, there's input-ipc-client https://mpv.io/manual/master/#options-input-ipc-client which might do what you want (though I still not sure how an fd can work cross-process).

You are right, I didn't notice it because I had 0.32.0 installed which didn't have that option. With 0.33.0 `--input-ipc-client` works as expected, thanks.

I am closing this as it has already been addressed in 0.33.0.

**Comment by avih** [comment]
Thanks.
