### ISSUE TITLE
Pause video when seeking

### ISSUE THREAD

**Issue by floppyD** [mpv-player/mpv#8441]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

So it's less "stuttery" when you are trying to find a specific scene. Sure you can just pause before seeking, but I see no upsides of the current behavior. Just pause when the left mouse button is pressed and unpause when it's unpressed.

https://user-images.githubusercontent.com/29208110/103693079-7f471700-4f77-11eb-8294-fe55142805b6.mp4

**Comment by Akemi** [comment]
just use a script for this and bin it to a key.

**Comment by floppyD** [comment]
That's what I'm doing currently, but I opened this issue for the sake of improving the UX. I really do not believe the current behavior is good, neither does any other player I know by the looks of it.
