### ISSUE TITLE
Weird OSC behavior

### ISSUE THREAD

**Issue by floppyD** [mpv-player/mpv#8442]
### Important Information

Provide following Information:
- git 3e175df
- Windows 7
- https://sourceforge.net/projects/mpv-player-windows/files/

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Seeking in some videos make the OSC behave weirdly, unlike any other player.

### Expected behavior

It's smooth like this

https://user-images.githubusercontent.com/29208110/103694042-05179200-4f79-11eb-9124-ad898171d394.mp4

https://user-images.githubusercontent.com/29208110/103694094-1eb8d980-4f79-11eb-820a-8b9fa6596c3e.mp4

### Actual behavior

https://user-images.githubusercontent.com/29208110/103693969-ea451d80-4f78-11eb-8535-4d3215842593.mp4

### Sample files

https://user-images.githubusercontent.com/29208110/103694223-5c1d6700-4f79-11eb-8861-80ee008bf591.mp4

**Comment by floppyD** [comment]
Another weird behavior I noticed with `hr-seek=yes,` shouldn't the seek bar follow the cursor no matter what? So the the user is always aware of the current timestamp?

https://user-images.githubusercontent.com/29208110/103695668-cb945600-4f7b-11eb-8abf-58bc0c8ad90f.mp4

**Comment by Akemi** [comment]
use `seekbarkeyframes=no` in the osc conf https://github.com/mpv-player/mpv/blob/master/DOCS/man/osc.rst

**Comment by floppyD** [comment]
Now it's the same thing as `hr-seek=yes`, so seeking on high quality content like 4K HEVC is terrible. Also the same issue as the plane video. Is an approach like the one in the first example I posted not feasible?
