### ISSUE TITLE
[Feature] Add option to select RTSP listening port

### ISSUE THREAD

**Issue by DistantThunder** [mpv-player/mpv#8446]
### Expected behavior of the wanted feature

* MPV could implement an `--rtsp-transport-port` option which would allow to the port of the listening socket for the appropriate transport protocols (lavf,tcp,udp that I know of) and make the implementation compatible with firewalls. As of now, that port is random and if not open at firewall level, the stream will fail to play.

### Alternative behavior of the wanted feature
---
### Log file
```
mpv --rtsp-transport=lavf  "rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=400&flavour=hd"

Warning: option --cache-secs is deprecated and might be removed in the future (will use unlimited time).
[ffmpeg/demuxer] rtsp: UDP timeout, retrying with TCP
[ffmpeg/demuxer] rtsp: method PAUSE failed: 551 Option Not Supported
[lavf] av_find_stream_info() failed
Failed to recognize file format.

Exiting... (Errors when loading file)
```

**Comment by jeeb** [comment]
There are options in the rtp/rtsp module for this in FFmpeg, called `min_port` and `max_port`.

Thus I would guesstimate that `--demuxer-lavf-o=min_port=X,max_port=Y` might work?

**Comment by stephan-t** [comment]
> There are options in the rtp/rtsp module for this in FFmpeg, called `min_port` and `max_port`.
> 
> Thus I would guesstimate that `--demuxer-lavf-o=min_port=X,max_port=Y` might work?

Unfortunately, that does not work and a `Floating point exception(core dumped)` error is produced.

**Comment by stephan-t** [comment]
Sorry, it does actually work. The problem was that the min and max range needs to be greater than 2.

Example: 
- 2870 to 287[0-1] does not work
- 2870 to 2872 works

**Comment by Akemi** [comment]
seems fixed.
