### ISSUE TITLE
Toggling off last Shader causes the display of (error) instead of empty string

### ISSUE THREAD

**Issue by butterw** [mpv-player/mpv#8448]
### Important Information

Provide following Information:
- mpv version: mpv 0.33.0-46-gdde0189279
- Windows Version: Win10
- Source of the mpv binary: main site
- If known which version of mpv introduced the problem: existing issue

### Reproduction steps
mpv --glsl-shaders="test.hook" video.mp4
input.conf: F1 change-list glsl-shaders toggle "test.hook"

### Expected behavior
toggling last shader off "${glsl-shaders}" should eval to "" empty string  

### Actual behavior
toggling last shader off causes display of "(error)".   
adding ; seems to solve the issue: mpv --glsl-shaders="test.hook;" video.mp4

### Log file
[vo/gpu/d3d11] Using cached vertex shader
[vo/gpu/d3d11] Using cached fragment shader

**Comment by butterw** [comment]
**Correction:** the best working workaround seems to be to prefix with ";" 
 mpv --glsl-shaders=";test.hook" video.mp4
it will display as ",test.hook" but it at least avoid  "(error)" when test.hook is toggled off.


This behavior affects every shader. You can use this simple Chroma shader for testing if needed:
https://github.com/butterw/bShaders/blob/master/mpv/NoChroma.hook

**Comment by Dudemanguy** [comment]
I think this is just a quirk of using change-list in this manner. I'll admit I didn't look very closely but you can easily accomplish the same thing using `cycle-values` like so: `F1 cycle-values glsl-shaders "test.hook" ""` and it'll return an empty string.

**Comment by butterw** [comment]
change-list glsl-shaders toggle is used to toggle an individual shader in the shader chain on/off, this isn't possible with cycle-values.
To avoid this toggle-off display issue you have to use a script to override the default osd or ensure glsl-shaders is "" (it isn't by default or when you've used clr, or when the native property value is set to empty list).
