### ISSUE TITLE
Can't move or resize window if --no-border is used (linux)

### ISSUE THREAD

**Issue by lightonflux** [mpv-player/mpv#845]
When i start mpv with `--no-border` then i can't resize, move or maximize the windows with the options given by the window menu (XFWM) or keyboard shortcuts.

**Comment by jpzbkk** [comment]
I just found a work around for this.  In Linux (Linux Mint I am currently using), there can be a keystroke for resizing a window.  In my case it is alt-F8.  This centers the cursor in the movie window and any movement will resize the window.  Works quite well!

**Comment by rhynzler** [comment]
> I just found a work around for this. In Linux (Linux Mint I am currently using), there can be a keystroke for resizing a window. In my case it is alt-F8. This centers the cursor in the movie window and any movement will resize the window. Works quite well!

For KDE Plasma Desktop you can resize the window in any direction by holding ALT + Right Mouse Button and moving the mouse in the direction you want to resize the widow. If ALT doesn't work, try META key or configure it on Settings » Window Managment » Window Behavior » Window Actions » Inner Window, Titlebar and Frame Actions

**Comment by infinite-ram** [comment]
> I just found a work around for this. In Linux (Linux Mint I am currently using), there can be a keystroke for resizing a window. In my case it is alt-F8. This centers the cursor in the movie window and any movement will resize the window. Works quite well!

Thank you!!!!!

**Comment by infinite-ram** [comment]
> I just found a work around for this. In Linux (Linux Mint I am currently using), there can be a keystroke for resizing a window. In my case it is alt-F8. This centers the cursor in the movie window and any movement will resize the window. Works quite well!

@jpzbkk Thank you !!!!

**Comment by nvmnghia** [comment]
> > I just found a work around for this. In Linux (Linux Mint I am currently using), there can be a keystroke for resizing a window. In my case it is alt-F8. This centers the cursor in the movie window and any movement will resize the window. Works quite well!
> 
> For KDE Plasma Desktop you can resize the window in any direction by holding ALT + Right Mouse Button and moving the mouse in the direction you want to resize the widow. If ALT doesn't work, try META key or configure it on Settings » Window Managment » Window Behavior » Window Actions » Inner Window, Titlebar and Frame Actions

Works on Xubuntu.
