### ISSUE TITLE
Small improvement to bootstrap.py ?

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#8457]
Hi guys,

py bootstrap.py

Output:

    Downloading https://waf.io/waf-2.0.20...
    Download failed.
    Downloading http://www.freehackers.org/~tnagy/release/waf-2.0.20...
    Download failed.
    Could not download waf-2.0.20.

I currently have some broken wget + openssl. I will fix that, but I would
like to suggest adding the remote URLs fully; and stating why the 
download failed too. This way users could more easily understand
what is going on.

I looked at the .py file, then was able to copy the URL, then download
it via the browser anyway. So work around it is easy (mpv works fine
now; that was the 0.33 tarball by the way). I assume whoever wrote
that .py file did not invest much time into making it more solid. Then
again my use case may happen only rarely, so I could understand
if no change is made; I just think it would be a small improvement
so people don't have to look into the .py file (I know both ruby and
python, despite my nick here on github, so I have no problem looking
at python code, but ideally the error-messages could be more descriptive
when something goes awry).

**Comment by CounterPillow** [comment]
Those things in the output (after `Downloading `) literally are the full URL it is trying to download, so I'm not sure what you're complaining about.

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/commit/40ea28c6f9f2f62270c1d07e4d79109d0a2d6b7d
