### ISSUE TITLE
May I ask what is the target of version 1.0

### ISSUE THREAD

**Issue by tasty0tomato** [mpv-player/mpv#8458]
I always think that a version 1.0 means that this project is stable.

**Comment by Akemi** [comment]
there is no plan for a version 1.0 (yet). everything that is tagged with a version is stable.

**Comment by tasty0tomato** [comment]
> there is no plan for a version 1.0 (yet). everything that is tagged with a version is considered stable.

[This is Semantic Versioning](https://semver.org/lang/zh-CN/) and I always think that version 1.0.0 is not just a number, but means that the project can be used by anyone and **not unstable**.

I know that this work will be hard and need to be discussed. Hope someday there will be a mpv 1.0.0 in the future.

Thanks.

**Comment by Akemi** [comment]
it's not the case here. tbh 1.0.0 is just an arbitrary number in the end. if it wasn't for distributions and package managers that only distribute tagged releases, we would probably not do any kind of version numbering at all.
