### ISSUE TITLE
With Auto ICC blacks are dark gray

### ISSUE THREAD

**Issue by CrHasher** [mpv-player/mpv#8464]
### Important Information
- mpv 0.33.0 (latest release)
- mpv binary from https://sourceforge.net/projects/mpv-player-windows/files/stable/mpv-0.33.0-x86_64.7z/download
- Windows 10 Pro 20H2 Build 19042.746
- nVidia GTX 1080 with driver 461.09

**1.1 Windows ICC + MPV AutoICC + No Options forced in nVidia driver:**
![ICCWindows_MpvAutoICC_NvidiaNothingForced](https://user-images.githubusercontent.com/834518/104512519-0428d500-55f7-11eb-8d2c-fbe3993d8c09.png)
**1.2 Windows ICC + MPV NoICC + No Options forced in nVidia driver:**
![ICCWindows_MpvNoICC_NvidiaNothingForced](https://user-images.githubusercontent.com/834518/104512527-055a0200-55f7-11eb-9489-2ba02576c05f.png)
**1.3 Windows No ICC + MPV NoICC + All video options forced in nvidia driver (all default + full-range):**
![NoICCWindows_MpvNoICC_AllNvidiaDriverForcedFullDynamicRange](https://user-images.githubusercontent.com/834518/104512532-068b2f00-55f7-11eb-9e2b-81f91217e2b6.png)
**2.1 Windows ICC + MPV AutoICC + No Options forced in nVidia driver:**
![ICCWindows_MpvAutoICC_NvidiaForceResolutionColorSettings_VideoDynamicRangeByMpv](https://user-images.githubusercontent.com/834518/104512970-a3e66300-55f7-11eb-910e-39b9986ae4e1.png)
**2.2 Windows ICC + MPV NoICC + No Options forced in nVidia driver:**
![ICCWindows_MpvNoICC_NvidiaForceResolutionColorSettings_VideoDynamicRangeByMpv](https://user-images.githubusercontent.com/834518/104512975-a5179000-55f7-11eb-8768-6cdeb71e1606.png)
**2.3 Windows No ICC + MPV NoICC + All video options forced in nvidia driver (all default + full-range):**
![NoICCWindows_MpvNoICC_NvidiaForceResolutionColorSettings_VideoDynamicRangeFull](https://user-images.githubusercontent.com/834518/104512962-a2b53600-55f7-11eb-9b05-d0e0848b5b50.png)

**_HDR_**
**3.1 Windows ICC + MPV AutoICC + No Options forced in nVidia driver:**
![ICCManualMpv](https://user-images.githubusercontent.com/834518/104513142-dc863c80-55f7-11eb-94a4-fe0599ac3221.png)
**3.2 Windows ICC + MPV NoICC + No Options forced in nVidia driver:**
![NoICC](https://user-images.githubusercontent.com/834518/104513146-ddb76980-55f7-11eb-8f03-cb6c543060e6.png)

**ICC comparison sRGB and ICM for pg279q:**
![ICCInspector](https://user-images.githubusercontent.com/834518/104513344-2ec75d80-55f8-11eb-9c5b-622247c1958a.png)

### Reproduction steps
_Config, maybe it helps to pinpoint issue (logs might also have the info)_:
https://0x0.st/-z4j.conf

When I play any video with option icc-profile-auto I get crushed black levels compared to no ICC.

**Observations**

1. From testing I can see that in case icc-profile-auto option is not provided no color correction is applied even if windows ICC is applied in Color Management see (**1.2** + **1.3**, **2.2** + **2.3**). Not sure why ICC set in windows is not applied to video, might be something standard allowing all apps to decide to use or ignore ICC.
2. If ICC is set with icc-profile-auto or with icc-profile option, I get blacks that are too bright and overall all colors are a bit bright. Skin tones look ok in some parts but shadows on faces look terrible. See sRGB and my ICC comparison maybe you can point me to what is in the ICC or what is missing from it and is responsible for this behavior.
3. HDR shows improvement in color accuracy and blacks are ok, see the TV screen the "colors" are more accurate in **3.1** (black and white).

### Expected behavior
Better black levels on SDR content.

### Actual behavior
Blacks washed out, contrast really suffers because of this.

### Log file
https://0x0.st/-z4S.txt

### Sample files
Almost any SDR file but bt.1886 looks more affected.

Thank you!

**Comment by CrHasher** [comment]
Just noticed this in the log: Fallback to dither=fruit because there is no enough shared memory, me noob. Never used -v -v option so now I will go back to dither sierra-lite.

**Comment by Akemi** [comment]
though the dither is unrelated. what i would be more concerned about is:

> [   2.841][v][vo/gpu] Detected ICC profile contrast: inf
> [   2.841][w][vo/gpu] ICC profile detected contrast very high (>100000), falling back to contrast 1000 for sanity. Set the icc-contrast option to silence this warning.

it might help to set the actual contrast with `--icc-contrast=`.

**Comment by CrHasher** [comment]
> though the dither is unrelated. what i would be more concerned about is:
> 
> > [   2.841][v][vo/gpu] Detected ICC profile contrast: inf
> > [   2.841][w][vo/gpu] ICC profile detected contrast very high (>100000), falling back to contrast 1000 for sanity. Set the icc-contrast option to silence this warning.
> 
> it might help to set the actual contrast with `--icc-contrast=`.

How do I find out what the actual contrast is? What I do know is that my monitor has a 1000:1 contrast ratio so the default 1000 should be spot on, or am I missing something?
Actual monitor specs:
https://rog.asus.com/monitors/27-to-31-5-inches/rog-swift-pg279q-model/spec/

**Comment by CrHasher** [comment]
I checked TFTCentral and yes the contrast changes based on brightness settings, this table for my monitor:
![ContrastVSBrightness](https://user-images.githubusercontent.com/834518/104568605-f73ccd80-5658-11eb-843f-fcf76658c91c.png)
For 120cd I did set brightness to 26, contrast is set to 50 (recommended). So this means I'm above 1000 contrast, that +130 to +160 difference might result in crushed blacks right? I will test setting this manually from MPV, would need to also get the value from the *.icm if possible, where do I find that value?

**Comment by CrHasher** [comment]
Tested with manually setting:
**icc-contrast=1126 (almost no change)**
![ICCWindows_MPVAutoICCwithContrast1126__NvidiaNothingForced](https://user-images.githubusercontent.com/834518/104572776-c6f72e00-565c-11eb-8621-dab7beca3d1b.png)
**icc-contrast=3000 (black bars dark gray + video more dark):**
![ICCWindows_MPVAutoICCwithContrast3000__NvidiaNothingForced](https://user-images.githubusercontent.com/834518/104572850-dd04ee80-565c-11eb-9c38-c6dde7500db1.png)

**Comment by Akemi** [comment]
> How do I find out what the actual contrast is? What I do know is that my monitor has a 1000:1 contrast ratio so the default 1000 should be spot on, or am I missing something? Calibrating to 120cd instead of 350cd changes the contrast?
> Actual monitor specs:
> https://rog.asus.com/monitors/27-to-31-5-inches/rog-swift-pg279q-model/spec/

when you calibrated your monitor, before you start the actual calibration step with the different colour patches, you usually manually set your display to a target brightness/contrast (additionally to the R, G and B colour values, etc). i assumed you should know because you use a very specific colour profile (ASUS-ROG-PG279Q-1-Calib6500KWhitePoint_Calib120cdBright_CalibGamma2p2.icm). that colour profile even mentions `120cd`.

did you even create this profile yourself? where is that profile from? does it even match your specific unit of that monitor model?

you can't just take values (or colour profiles) from the internet and think that will work. every unit of the same monitor model has specific characteristics and a variance. they never match with their settings exactly. by changing any settings in the menu you will make your colour profile, that was created for the previous settings (assuming that profile was even created for that specific unit and settings), useless. since it doesn't match anymore.

if you just picked a colour profile from somewhere and think it will match your units characteristics, that will not work and colours etc will never be completely correct. changing any monitor settings for this profile is then just a guesstimation.

**Comment by CrHasher** [comment]
> 
> when you calibrated your monitor, before you start the actual calibration step with the different colour patches, you usually manually set your display to a target brightness (additionally to the R, G and B colour values, etc). i assumed you should know because you use a very specific colour profile (ASUS-ROG-PG279Q-1-Calib6500KWhitePoint_Calib120cdBright_CalibGamma2p2.icm).

The monitor was warmed up for 1h, than in a dark room almost pitch black I used the Spyder 4 Pro and tuned Brightness to 120cd manually, RGB sliders to balance them out to the best I could, the white point with manual tuning was 6450k pretty stable. All this over and over until it was pretty ok even without color management.

I made 2 calibrations one with native white point and native brightness and gamma 2.2. Another with all recommended settings 6500k, 120cd, gamma 2.2 the one I use now. For desktop the recommended calibration looks more accurate than the native one as far as I can see, the human eye is not really the best device to make such comparisons. Is calibrating to native better than recommended? I don't know the science behind it to say for sure.

> the contrast should be part of the profile metadata. at least in my case it is. yeah changing the brightness will change the contrast. since luminance/blackpoint = contrast (OSD brightness 20 from that table for example: 116.59/0.10 = 1165.9)
> 

I can't find anything related to contrast in the *.icm file I assume it is missing or I don't know where to search for it. Mpv says value is to high but the actual value does not appear in the log. Assumption is that mpv can't find it and it interprets it as INF, reverts back to default 1000:1.

> did you create this profile yourself? where is that profile from? does it even match your specific unit of that monitor model?
> 
> you can't just take values (or colour profiles) from the internet and think that will work. every unit of the same monitor model has specific characteristics and a variance. they never match with their settings exactly. by changing any settings in the menu you will make your colour profile, that was created for the previous settings (assuming that profile was even created for that specific unit and settings), useless. since it doesn't match anymore.
> 
> if you just picked a colour profile from somewhere and think it will match your units characteristics, that will not work and colours etc will never be completely correct. changing any monitor settings for this profile is then just a guesstimation.
> 

No I did not take a random calibration from the net, those rarely match a random unit from the same make and model. Thing is it is maybe Spyder 4 Pro that is to blame for not adding bkpt and lumi fields to the *.icm, adding those manually if I knew the values would it help?

> [edit]
> i was under the impression that the icc-contrast setting was kinda a misnomer and it meant the target luminance since for me it detects the 120cd/m^2. i will try to clarify this.
> 
> > Detected ICC profile contrast: 120.000000

**Comment by CrHasher** [comment]
**Added also the icm, if anyone has time to check it out:**
https://0x0.st/-zUa.icm

**Comment by Akemi** [comment]
i see then it was just a misunderstanding on my side. thanks for clearing that up.

i have an i1Display pro and i found the provided calibration software a bit lacking and switched to [DisplayCal](https://displaycal.net). i got much better profiles with that. maybe the spyder 4 pro software does something funky (black point correction/compensation?) that raises the black level a bit? though all the specifics go well past my knowledge.

**Comment by CrHasher** [comment]
> i see then it was just a misunderstanding on my side. thanks for clearing that up.
> 
> i have an i1Display pro and i found the provided calibration software a bit lacking and switched to [DisplayCal](https://displaycal.net). i got much better profiles with that. maybe the spyder 4 pro software does something funky (black point correction/compensation?) that raises the black level a bit? though all the specifics go well past my knowledge.

I did turn to DisplayCAL myself, it's most probably best in class in calibration category, I have absolutely no idea how to use it to correctly calibrate my monitor with DisplayCAL. Did read the documentation but it's full of low level terminology and you need to understand all the basics before even attempting to read the documentation. Default settings even the documentation states that they are just a starting points not de-facto standards. When I downloaded DisplayCAL I was hoping for tutorial on desktop calibration than some nice tutorial for video calibration maybe even 3dlut but all such tutorials are mostly one guy doing it he's way and most of it not something standard. Ended up getting worse results than with default Spyder 4 Pro software, even less contrast and gray blacks. Best I managed to do was sRGB calibration no 3dlut, had no ambient sensor so could not set target lux. It turned out ok but I'm at a point that I'm dropping calibration altogether. For actual video content or even worse HDR I don't know how to even start calibrating for that use-case to get good results. DisplayCAL suggests using different gamma for video in the default settings, is it correct? No clue.

My guess is that no matter what I will use to calibrate it's the Spyder 4 Pro that is a very very mediocre colorimeter. For an uncalibrated display it says I have ~600:1 contrast which is most probably not even close to the actual contrast.

**Comment by hooke007** [comment]
Maybe it is not related with contrast. Gamma problem instead.

Try to add `vf=format:gamma=gamma2.2` in `mpv.conf`.

**Comment by CrHasher** [comment]
After adding `vf=format:gamma=gamma2.2` black's look better not gray:
![ICCWindows_MPVICCAutoGammaForcedTo22_NvidiaPassThrough](https://user-images.githubusercontent.com/834518/105034125-bf22f980-5a61-11eb-8fb1-75ab8a8c0677.png)

So is the default gamma not picked up form the ICC? Is this info in the ICC at all?

I did calibrate to a gamma curve of 2.2 so playing it back at any different gamma might explain the odd behavior. Would be nice to know is it some info missing from the ICC that results in MPV guessing gamma, or an MPV bug.

**Comment by CrHasher** [comment]
I see an improvement in also HDR, albeit a bit greenish tint and low contrast:
**ICC before gamma forced to 2.2**
![ICCManual](https://user-images.githubusercontent.com/834518/105037045-0ca16580-5a66-11eb-84b5-f161a76fdb4d.png)

**ICC after gamma forced to 2.2**
![ICCWindows_MPVICCAutoGammaForced22_NvidiaPassThrough](https://user-images.githubusercontent.com/834518/105037071-15923700-5a66-11eb-95ea-f5151bd8a13e.png)

**Comment by hooke007** [comment]
They discuss this problem here:
https://github.com/mpv-player/mpv/issues/8009#issuecomment-713550678
https://github.com/mpv-player/mpv/issues/8082

And I suggest to create the extra profile to handle HDR sources, or you will see the terrible output.

**Comment by Akemi** [comment]
closing this issue then, in favour of the other two.

**Comment by CrHasher** [comment]
> They discuss this problem here:
> [#8009 (comment)](https://github.com/mpv-player/mpv/issues/8009#issuecomment-713550678)
> #8082
> 
> And I suggest to create the extra profile to handle HDR sources, or you will see the terrible output.

I will check the other issues you added in this thread. For me that HDR video, the second one does not look terrible, with some tweak it would be perfect, just look at people's faces actually looks like an SDR master not the over saturated very saturated to much contrast, blown out whites, version all players force on you.
