### ISSUE TITLE
Waf can't find program 'cc'

### ISSUE THREAD

**Issue by mjhymowitz** [mpv-player/mpv#8465]
### mpv version and platform versions

**according to command prompt**:

C:\Users\local\Downloads>mpv --version
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  6 10:03:04 +08 2020
FFmpeg library versions:
   libavutil       56.62.100
   libavcodec      58.114.100
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.92.100
   libswresample   3.8.100
FFmpeg version: git-2020-12-05-89e3f5ab

C:\Users\local\Downloads>git --version
git version 2.30.0.windows.1

C:\Users\local\Downloads>python --version
Python 3.9.1

### Reproduction steps

install latest version of git
install python 3.9 from microsoft store
install mpv using chocolatey

open command prompt as admin
$ cd cd C:\Users\local\Downloads\mpv-0.33.0\mpv-0.33.0
$ python3 bootstrap.py
$ python3 waf configurate
Setting top to                           : C:\Users\local\Downloads\mpv-0.33.0\mpv-0.33.0
Setting out to                           : C:\Users\local\Downloads\mpv-0.33.0\mpv-0.33.0\build
Checking for waf version in 1.8.4-2.1.0  : ok
Checking for program 'cc'                : not found
Could not find the program ['cc']
(complete log in C:\Users\local\Downloads\mpv-0.33.0\mpv-0.33.0\build\config.log)

### Expected behavior
cc to be there

### Actual behavior
can't proceed due to waf failing to locate cc

### Log file

[config.log](https://github.com/mpv-player/mpv/files/5811544/config.log)

**Comment by avih** [comment]
What are you trying to do? run mpv or build mpv?

If you want to run it, then you don't need waf, and if you want to build it then you need a mingw-w64 setup, e.g. with msys2, where `cc` would typically be mapped to `gcc`. Python on its own is not enough to build mpv.

**Comment by mjhymowitz** [comment]
Im trying to get the ff2mpv extention working on firefox. I honestly not sure what I'm doing. I just found instructions saying to install this repo and now I'm stuck.


https://addons.mozilla.org/en-US/firefox/addon/ff2mpv/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by avih** [comment]
You don't need to build mpv. Looking at the instructions at https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows , you need to get a working version of mpv normally (download it or install with Chocolatey or scoop) and then set it up according to the instructions.
