### ISSUE TITLE
HDR not working on iOS

### ISSUE THREAD

**Issue by skrew** [mpv-player/mpv#8467]
Hi,

I'm facing issues with HDR videos

```[ 274.296][v][libmpv_render] Testing FBO format rgba16f
[ 274.296][d][libmpv_render] Resizing texture: 16x16
[ 274.296][v][libmpv_render] Using FBO format rgba16f.
[ 274.296][v][libmpv_render] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[ 274.296][v][libmpv_render] No advanced processing required. Enabling dumb mode.
[ 274.296][v][libmpv_render] Loading hwdec driver 'videotoolbox'
```

This video is working with others players like VLC.

I'm using LIBMPV 0.32 (0.33 not working because of some context problems)

I'm using a GLKView view, initialized with

```
self.drawableColorFormat = .RGBA8888
self.drawableDepthFormat = .formatNone
self.drawableStencilFormat = .formatNone
```
as @Akemi said, it's not a LIBMPV problem but an implementation problem, but after searching a while, i don't see what i can fix on my side. If anyone know, please tell me !

**Comment by Akemi** [comment]
i am not sure what you are asking for here? do you mean `Disabling HDR peak computation`? then no it will never work with apples opengl because their version doesn't support compute shaders. if you want apples tonemapping via a layer you have to do something like https://github.com/mpv-player/mpv/pull/8404.

**Comment by skrew** [comment]
Unfortunaltly, there are not API like `wantsExtendedDynamicRangeContent` on iOS...

Look like i have to move on libvlc, after 3 years in love with LIBMPV... Sad, but i wish you all the best ! :)

**Comment by Akemi** [comment]
that doesn't really answer the question of what you actually wanted or what you expected?

if libvlc doesn't utilise metal you won't get a different outcome than with mpv. just some tone mapping that might be the same as mpv's.

**Comment by skrew** [comment]
I know, libvlc uses opengl too, but with libvlc the videos works (colors are good), but not with my code based on libmpv...
Look the sky on this screenshot, it's with my code...
I don't know how they make HDR videos looking good, but it's not working on my player...

![IMG_0229](https://user-images.githubusercontent.com/738170/104540288-701f3380-561f-11eb-9a90-16137fe2b6e5.png)

**Comment by Akemi** [comment]
find out what kind of tone mapping they use and replicate those settings with the tone mapping setting in mpv.

though this image looks like some wrongly mapped format, eg a 10bit output mapped to 8bit or something. it looks similar to this issue https://github.com/mpv-player/mpv/issues/7846. so it's possible it's related to hwdec and format mapping. though to be really sure you should have opened a proper issue with the issue template filled out and a log. also maybe @tmm1 knows more by now.

**Comment by skrew** [comment]
Hey ! it's working with the patch available on https://github.com/mpv-player/mpv/pull/7849/files ! :)

Thanks ! I don't have to migrate to libvlc ! :)

**Comment by Akemi** [comment]
that's good to know. yeah that change is only in 0.33.

**Comment by skrew** [comment]
Yep i have see that but the 0.33 version doesn't works for me:
```
[vo/libmpv] fatal: No render context set.
[cplayer] fatal: Error opening/initializing the selected video_out (--vo) device.
```
I have see no breaking changes in client changelog, i have to dig into this problem (i will test with master first)

**Comment by Akemi** [comment]
yes, you should use the new API. the old one is deprecated.

**Comment by skrew** [comment]
It's ok with the new API, except on simulator i get a blue screen instead of video (the same video worked before on old api)

BTW, after more tests, and while HDR support is far better, it's still not "perfect", as you can see on the sky.
Tested with mpv 0.33.0 / ffmpeg 4.3.1 on Mac, and on iOS with ffmpeg 4.3.1 too:

**MAC**
![mpv-shot0001](https://user-images.githubusercontent.com/738170/104626934-b663a980-5696-11eb-91b5-0e1c38d1418e.jpg)

**IOS**
![IMG_0234](https://user-images.githubusercontent.com/738170/104626949-b9f73080-5696-11eb-9727-84f3fe14b85d.png)

**Comment by Akemi** [comment]
the blue screen is most likely not because of the new API but a different change. maybe even that commit that fixed the problem.

like i said before if you don't fill out the proper issue template and provide the infos we need, we can't help you. like this it's just poking in the dark and guesstimation. so please open a new issue.
