### ISSUE TITLE
HDR not perfect on iOS

### ISSUE THREAD

**Issue by skrew** [mpv-player/mpv#8469]
### Important Information
- LIBMPV 0.33.0
- iOS 14.3

### Reproduction steps
Play an HDR content on iOS, it's better on libmpv 0.33 which have this patch: https://github.com/mpv-player/mpv/pull/7849/files but not "perfect"

### Expected behavior
HDR fully supported, like MPV on Mac

### Actual behavior
There are still glitches, as you can see on the sky on the screenshot

### Sample files
http://skrobs.com/hdrb.mkv

### Log file
[mpv-log.txt](https://github.com/mpv-player/mpv/files/5816273/mpv-log.txt)
![IMG_0234](https://user-images.githubusercontent.com/738170/104632617-435e3100-569e-11eb-8d4e-f61bada2395a.png)

**Comment by Akemi** [comment]
we will keep the first one.
