### ISSUE TITLE
How Mac XDR renders an RGBE HDR image

### ISSUE THREAD

**Issue by tommywei-cpu** [mpv-player/mpv#8471]
I have HDR images in .hdr (RGBE) format, which are created by combining a series of images captured at different exposures. I can get the RGB values of each pixel, but how can I know what is the XYZ values at each pixel produced by XDR?

**Comment by Akemi** [comment]
i think you should ask you question at the appropriate forum/place and i think the mpv issue tracker isn't the right place for this.
