### ISSUE TITLE
How to disable or toggle the "pl_prev-pl_next-title-cache" on OSC?

### ISSUE THREAD

**Issue by c02y** [mpv-player/mpv#8472]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

```
$ mpv --version
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1

OS: x86_64 Linux 5.9.16-1-MANJARO
```
### Expected behavior of the wanted feature

OSC Interface
```
+---------+----------+------------------------------------------+----------+
| pl prev | pl next  |  title                                   |    cache |
+------+--+---+------+---------+-----------+------+-------+-----+-----+----+
| play | skip | skip | time    |  seekbar  | time | audio | sub | vol | fs |
|      | back | frwd | elapsed |           | left |       |     |     |    |
+------+------+------+---------+-----------+------+-------+-----+-----+----+
```
![Screenshot_2021-01-16_04-46-36](https://user-images.githubusercontent.com/2135996/104777454-a2af6480-57b6-11eb-8153-f784f7ff184d.png)

I needed to completely disable the "pl_prev-pl_next-title-cache" bar on the OSC layout, 
1. pl_prev and pl_next, I can use the mouse or key bindings to access the playlist
2. title, I can use the title in osc-windowcontrols, and if I change osc-title, it affects the title in windowcontrols as well.
3. cache part, I mostly play local video, this part is empty for local video.

I saw multiple people already mentioned this similar request.
I lot of people say that I can set `windowcontrols=no`, but then I won't have the `minimize, maximize, quit` buttons on the windowcontrols. 
This "pl_prev-pl_next-title-cache" is useless and taking extra space on the screen.

So I need the windowcontrols for `minimize, maximize, quit` buttons + title, and I don't need the "pl_prev-pl_next-title-cache" line on the osc, at least for local file.

Is this feature able to be implemented?

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Akemi** [comment]
i am inclined to say that this will probably not be added as an option. the OSC pretty complex already and i feel none wants to add even more complexity. though it's possible to do yourself, eg copy the script from our repo, adjust the script and add it to you script folder. also don't forget to deactivate the internal OSC with --no-osc.

if anyone else from our devs feels this should be kept open, please feel free to reopen this issue.
