### ISSUE TITLE
Would it be feasible to try and use Zig instead of rust?

### ISSUE THREAD

**Issue by appetrosyan** [mpv-player/mpv#8473]
I see that you may not be very comfortable with rust, in that it imposes many unnecessary limitations and will probably be a headache to maintain because of all the "purists" and haters of the `unsafe` keyword. Seeing as we seem to be sufficiently like-minded, have you had a look into `zig`? Unlike Rust, you can map C 1:1 onto zig and have a relatively painless transition, plus it has some of the good meta programming features. Plus you don't have to have a separate build system, because zig handles its own compilation. 

We have managed to do relatively many things with Vulkan in [river](https://github.com/ifreund/river). Plus you don't have to learn a whole new paradigm, you just have to make a relatively simple syntactic translation. Zig was designed as the better C, and not like Rust to be a better Go.

**Comment by Akemi** [comment]
we are not interested at all at the moment to transition to anything. this may or may not change in the future.
