### ISSUE TITLE
Toggle function for frame interpolation in input.conf?

### ISSUE THREAD

**Issue by askasys-code** [mpv-player/mpv#8479]
I know the function on mpv.conf
`interpolation=yes`
But I need a toggle function for this, because not every movie is ok with interpolation, and sometime I need to deactivate it. 

I tried with 

`CTRL+i vf toggle interpolation`

and I get the error "Changing filter failed!"

**Comment by Akemi** [comment]
interpolation isn't a filter (vf = video filter), it's just a property.

`x cycle interpolation`

**Comment by askasys-code** [comment]
> 
> 
> interpolation isn't a filter (vf = video filter), it's just a property.
> 
> `x cycle interpolation`

Ah! I thought it was a filter lol, now it work like a charm. 
Very quickly response. Thank you much!!!
