### ISSUE TITLE
About filters's design doc 

### ISSUE THREAD

**Issue by rolandjon** [mpv-player/mpv#8482]
HI, experts, I am a newbie to mpv. I am currently learning the code of mpv core. I am really happy to have such a good open source project,It's amazing . However, I am currently  blocked by some code related to filters.
I found that filters have its presence everywhere in the core, but I don’t quite understand the details of the work behind it, such as why each work filter has to create a wrapper filter for it ? And the public pin and private pin of the filter, what is the boundary between them? 

Also, the following example in filter.c,
//      f1 <-> <1a|1b> <-> <2a|2b> <-> <3a|3b> <-> f2
// would be a connection from 1a to 3b. 1a could be a private pin of f1 (e.g.
// mp_filter.ppin[0]), and 1b would be the public pin (e.g. mp_filter.pin[0]).
// A user could have called mp_pin_connect(2a, 1b) mp_pin_connect(3a, 2b)
// (assuming 1b has dir==MP_PIN_OUT). The end result are the following values:

Does it mean that 1a/1b belongs to f1, 3a/3b belongs to f2,and should 2a/2b also belong to a certain filter?

Sorry for some stupid questions,is it possible to write a design document on the wiki to describe the design details of filters ?  Because it is so important and the details are also a bit cumbersome )--

**Comment by Akemi** [comment]
sry i am not sure about the details and since no one answered yet i am closing this.

**Comment by rolandjon** [comment]
Who knows about the filter mechanism of mpv-player, if there are some related blog articles, I will be grateful -(
