### ISSUE TITLE
When mpv play a folder , " ${path}" string replace "\" with "/"

### ISSUE THREAD

**Issue by vvyoko** [mpv-player/mpv#8483]
### Important Information

Provide following Information:
- mpv 0.33.0
- Windows10 1909

### Reproduction steps

When mpv play a folder , `${path} `string replace `\ `with `/`

1,
add key bind `F4 show-text ${path} 5000` to `input.conf`

2,
open mpv.exe,then drag a folder(has video in subfolder) into mpv

3,
key `f4`
it will show like that:
`D:\1/1/1/1.mp4`
![1](https://user-images.githubusercontent.com/2145741/105027645-fbb71b00-5a8a-11eb-8e22-b6345cb166b4.jpg)

but when drag a video file into mpv,then key  `f4`
it will show. 
`D:\1\1\1\1.mp4`
![2](https://user-images.githubusercontent.com/2145741/105027716-0d98be00-5a8b-11eb-983a-f79a84f2fb84.jpg)

hope play folder  `${path} ` will give like play video.

**Comment by avih** [comment]
Why is that a problem?

**Comment by vvyoko** [comment]
> Why is that a problem?

Because I used a plus one command to fail in this case
i add a key bind 
`ctrl+A run "explorer" "/select," "${path}"`

I just assumed that most programs of this type could not handle
After testing, it seems that most programs are compatible with this type `D:\1/1/1/1.mp4`.
So maybe it's a problem with that program alone.

Despite this, I wonder why two types are used? The first type is really uncommon, and the vast majority of common paths are of the second type `D:\1\1\1\1.mp4`

**Comment by avih** [comment]
Yes, most programs can handle `/`, but explorer cannot. You can use this solution for now - https://github.com/mpv-player/mpv/issues/6565#issuecomment-473811768
