### ISSUE TITLE
Any way to make HDR look better on SDR display with MPV?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8484]
With default config, it loses hightlight details, it gets even worse without hdr-compute-peak. Here is a compare with default, default without hdr-compute-peak, hable, and MadVR.

- default:
![2021-01-19 21-52-30 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/105043576-a71e9a80-5aa0-11eb-9f37-73adfebb4f3f.png)

- default without hdr-compute-peak:
![2021-01-19 21-52-58 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/105043651-c0274b80-5aa0-11eb-9a67-e9a3ae004bc7.png)

- hable:
![2021-01-19 21-54-00 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/105043761-e3ea9180-5aa0-11eb-9fa0-16ba5e399d98.png)

- MadVR:
![Snipaste_2021-01-13_22-42-49](https://user-images.githubusercontent.com/9532105/105044020-30ce6800-5aa1-11eb-943a-1ab7645e0077.png)

The last one contains most of the details and have a brighter image.

### Log file

[hdr.txt](https://github.com/mpv-player/mpv/files/5836210/hdr.txt)

**Comment by wiiaboo** [comment]
Have you tried different [tone-mapping](https://mpv.io/manual/master/#options-tone-mapping) options?

**Comment by laichiaheng** [comment]
> Have you tried different [tone-mapping](https://mpv.io/manual/master/#options-tone-mapping) options?

Yes, I've tried hable, reinhard, but they also too dark or lose high light details if I raise the brightness.

**Comment by Doofussy2** [comment]
Have you tried turning the params?
https://mpv.io/manual/master/#options-tone-mapping-param

And adjusting the max boost?
https://mpv.io/manual/master/#options-tone-mapping-max-boost

**Comment by avih** [comment]
@Doofussy2 Are you familiar with sets of params to make mpv behave like common other mappers? (vlc/madvr/osx/etc)? if yes, would you be able to post these "presets" here or add them to the wiki someplace?

**Comment by laichiaheng** [comment]
> Have you tried tuning the params?
> https://mpv.io/manual/master/#options-tone-mapping-param
> 
> And adjusting the max boost?
> https://mpv.io/manual/master/#options-tone-mapping-max-boost

Adjusting max boost loses high light details, too.

**Comment by Doofussy2** [comment]
> @Doofussy2 Are you familiar with sets of params to make mpv behave like common other mappers? (vlc/madvr/osx/etc)? if yes, would you be able to post these "presets" here or add them to the wiki someplace?

The problem with that is the results are inconsistent. I've fairly extensively tested the various parameters, and I have found to have varying results from video to video. Madshi appears to have written his algorithms a little differently, so applying the same params will look a little different. bt.2390 is the best at the moment, but isn't tunable. So haasn would need to make any revisions. Presently it does appear to lose detail in the white point. I don't know what other players use as default, but I could possibly research that. Time isn't on my side, these days.

@laichiaheng in your madvr screenshot, what algorithm were you using? Did you use bt.2390? I haven't used madvr in a while. I should probably get caught up.

**Comment by laichiaheng** [comment]
> > @Doofussy2 Are you familiar with sets of params to make mpv behave like common other mappers? (vlc/madvr/osx/etc)? if yes, would you be able to post these "presets" here or add them to the wiki someplace?
> 
> The problem with that is the results are inconsistent. I've fairly extensively tested the various parameters, and I have found to have varying results from video to video. Madshi appears to have written his algorithms a little differently, so applying the same params will look a little different. bt.2390 is the best at the moment, but isn't tunable. So haasn would need to make any revisions. Presently it does appear to lose detail in the white point. I don't know what other players use as default, but I could possibly research that. Time isn't on my side, these days.
> 
> @laichiaheng in your madvr screenshot, what algorithm were you using? Did you use bt.2390? I haven't used madvr in a while. I should probably get caught up.

It's not mine, but the one who uploads it says that he didn't change any setting.

**Comment by Doofussy2** [comment]
OK, I had a quick few minutes for a basic comparison. Let's stick with Tenet for an apples to apples comparison.

First, we need a baseline. The first screenshot is the studio SDR master. This is the goal outcome.

`--no-config`
![Tenet studio SDR no config](https://user-images.githubusercontent.com/15950919/105123023-2e154800-5a8c-11eb-9510-1634b48659f7.jpg)

`--no-config` `--hdr-compute-peak=no` and using default tone-mapping (bt.2390)
![Tenet no-config hdr compute-peak=no](https://user-images.githubusercontent.com/15950919/105123251-8fd5b200-5a8c-11eb-90a9-80024df6e83c.jpg)

We can see that it's slightly darker, but look at the white building in background, center. Clearly there is a color shift and a loss of clarity.

`--no-config` `--hdr-compute-peak=no` `--tone-mapping=reinhard`
![2 Reinhard default](https://user-images.githubusercontent.com/15950919/105123769-88fb6f00-5a8d-11eb-8f0f-30b9251db78f.jpg)

Default reinhard is also a little darker, and that building still has a color shift but it does look a little better than bt.2390, I think.

`--no-config` `--hdr-compute-peak=no` `--tone-mapping=reinhard` `--tone-mapping-param=0.6`
![Reinhard TMP 0 6](https://user-images.githubusercontent.com/15950919/105125765-032df280-5a92-11eb-83a1-c6cfe26d0028.jpg)


So now we see center stage with a brightness comparative to the studio SDR, but a just slightly brighter. The Building in the background is obviously not correct.

Mobius default is also darker and has the same color shift on that building.

The MadVR screenshot should be ignored. It has been shown to me elsewhere, that a filter is being added to make the picture brighter and isn't a result of tone-mapping. If you look at it, there is a general color desaturation. I'm not overly fond of that.

It does seem to me that mpv's white point is a little off the mark.

**Comment by Doofussy2** [comment]
That's great movie btw. If you understand the 2nd law of thermodynamics/entropy, you'll have a deeper appreciation for it.

**Comment by laichiaheng** [comment]
@Doofussy2 If bt.2390 were tunable, would it look better than this?
I only saw some description on the internet or somebody talked about this, I don't really know what it actually is in physics or math.

**Comment by Doofussy2** [comment]
> @Doofussy2 If bt.2390 were tunable, would it look better than this?

That would depend on how it was implemented. @haasn would have to work some magic. But I think a few tweaks to the current implementation would probably be more achievable. 

> I only saw some description of entropy on the internet or somebody talked about it, I don't really know what it actually is in physics or math.

Just look up 2nd law of thermodynamics.

**Comment by laichiaheng** [comment]
> > @Doofussy2 If bt.2390 were tunable, would it look better than this?
> 
> That would depend on how it was implemented. @haasn would have to work some magic. But I think a few tweaks to the current implementation would probably be more achievable.
> 
> > I only saw some description of entropy on the internet or somebody talked about it, I don't really know what it actually is in physics or math.
> 
> Just look up 2nd law of thermodynamics.

I'm amazed that he can put a reverse thing in the same scene at the same time, and it makes sense.

**Comment by Doofussy2** [comment]
Reverse entropy is a complicated topic for a movie. Many people won't understand what they're seeing.

**Comment by hooke007** [comment]
Individually, I see that `tone-mapping` Gamma looks better in the night scenes, while 2390 seems always show the correct (or natural?) hue in the day scenes.

2390
![d hcp 2390](https://user-images.githubusercontent.com/41094733/105145848-3b890b80-5b3a-11eb-99ab-ba4c81c6ba6a.jpg)

gamma
![d hcp gamma 1 8](https://user-images.githubusercontent.com/41094733/105145851-3d52cf00-5b3a-11eb-8424-45629537ae9e.jpg)

2390
![n hcp 2390](https://user-images.githubusercontent.com/41094733/105145854-3deb6580-5b3a-11eb-95ab-a5d0554ad83b.jpg)

gamma
![n hcp gamma 1 8](https://user-images.githubusercontent.com/41094733/105145855-3e83fc00-5b3a-11eb-81f1-5c1f7428646a.jpg)

**Comment by ValZapod** [comment]
BT.2390 EETF is not implemented is full (no black offset). See https://github.com/mpv-player/mpv/issues/7984#issuecomment-694570896

But yes, after that it will be the best.

**Comment by Akemi** [comment]
since we have an issue open for this and the actual question has been discussed. i will close this one.

**Comment by ojab** [comment]
I suppose `an issue` is the https://github.com/mpv-player/mpv/issues/7984?

**Comment by Akemi** [comment]
yeah. i also think it can possibly related to some other open issued labeled with [core:color-management](https://github.com/mpv-player/mpv/labels/core%3Acolor-management).
