### ISSUE TITLE
Unable to use the comma inside option values when using --demuxer-lavf-o

### ISSUE THREAD

**Issue by SebiderSushi** [mpv-player/mpv#8489]
### Important Information

Provide following Information:
- mpv version `0.33.0-65-g51852aad52`
- Platform and Version Manjaro Linux 20.2.1 (based on Arch Linux, still rolling release in some way but also versioned, idk)
- Source of the mpv binary from Manjaro repositories

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
- Dowload an HLS manifest and all files referenced by it or convert a local video to HLS using `ffmpeg -i input.mp4 -profile:v baseline -level 3.0 -s 640x360 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls manifest.m3u8` for example.
- Try playing back with `mpv manifest.m3u8`
- mpv will return errors because lavf applies different rules for allowed HTTP file extensions as opposed to local file extensions (I.E. the exact same manifest works via `mpv http://source.url/manifest.m3u8` or if i set up an http server and run `mpv http://localhost:8000/manifest.m3u8`)
- Try allowing `.key` and `.ts` files or whatever is in your manifest via `mpv --mpv-demuxer-lavf-o=allowed_extensions=ts,key manifest.m3u8`

### Expected behavior
mpv does something equivalent to `ffmpeg -allowed_extensions ts,key -i manifest.m3u8 [...]`

### Actual behavior
mpv returns an error parsing the command line apparently expecting the comma to seperate multiple AVOptions. The only option left seems to be specifying `--mpv-demuxer-lavf-o=allowed_extensions=ALL` which feels unclean or maybe even unsafe idk. quoting arount the comma or escaping it did not help.

### Log file

[mpv-log.txt](https://github.com/mpv-player/mpv/files/5841225/mpv-log.txt)

**Comment by SebiderSushi** [comment]
Okay today i read more [about key-value options](https://mpv.io/manual/master/#list-options) and realized that passing `mpv --demuxer-lavf-o-append=allowed_extensions=ts,key m3u8` works for my case.

Is this desired behavior then? I'm fine with specifying options that contain commata using the `-append` modifier, but is there any way to escape the comma when calling `--demuxer-lavf-o=` without modifiers?

**Comment by SebiderSushi** [comment]
Hm so i wanted to use the `--demuxer-lavf-o-append=allowed_extensions=ts,key` workaround with Celluloid but as it turns out action suffixes are not supported with `libmpv`. https://github.com/celluloid-player/celluloid/issues/635

**Comment by Akemi** [comment]
try something like `mpv --demuxer-lavf-o=allowed_extensions=[ts,key]`. also see https://github.com/mpv-player/mpv/blob/ef0aafbd429792781886a6da9d392ddf76cdc7d6/DOCS/man/mpv.rst#escaping-spaces-and-other-special-characters.

**Comment by SebiderSushi** [comment]
Thank you very much! This solves my use case.
