### ISSUE TITLE
How to get progress bar

### ISSUE THREAD

**Issue by Mavpt** [mpv-player/mpv#8492]
### Important Information
- mpv version:
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1

- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch repository community/mpv (pacman -Syu mpv)
- Window Manager and version: bspwm 0.9.10
- GPU driver and version: nvidia 460.32.03-1
- Possible screenshot or video of visual glitches:

![image](https://user-images.githubusercontent.com/58571526/105243957-adc41500-5b67-11eb-80e2-ea3436308276.png)

![image](https://user-images.githubusercontent.com/58571526/105244233-22974f00-5b68-11eb-9a12-b307413ca964.png)

### Reproduction steps
It's reproducible with no config.

### Expected behavior
Have the text and the progress bar (see first image).

### Actual behavior
No text nor progress bar (see second image).

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/5845505/output.txt)

Edit 1: Rewritten to better follow the report template.

**Comment by avih** [comment]
Please follow the report template, attach a log and the rest of the required info.

The lack of text is probably some font issue, while the lack of progress (position) is weird, unless this is the very begining of the clip and the progress is still at the very start.

**Comment by Mavpt** [comment]
> Please follow the report template, attach a log and the rest of the required info.
> 
> The lack of text is probably some font issue, while the lack of progress (position) is weird, unless this is the very begining of the clip and the progress is still at the very start.

First of all I apologize for not following the report template and especially for not including the log file as the latter is even mentioned in the Ask a Question template which I selected. I edited the original post to better follow it and ask that if it's not yet up to your standards to be informed about it so I can further correct it.

Secondly, if you could inform me what fonts mpv expects to be present (or point me towards where that information can be found) I would promptly install them and update give an update on whether that was the source of the problem.

Finally, I can confirm that the screenshot was taken around the middle of the video as to avoid that exact issue.

**Comment by avih** [comment]
> `Reading config file /home/bruno//.config/mpv/mpv.conf`

You mentioned that it's without a config file, but it seems there is one. Can you please try with `--no-config` added at the command line?

**Comment by Mavpt** [comment]
> > `Reading config file /home/bruno//.config/mpv/mpv.conf`
> 
> You mentioned that it's without a config file, but it seems there is one. Can you please try with `--no-config` added at the command line?

I can confirm that the config file was empty, but either way a log file with the --no-config option is bellow:
[output.txt](https://github.com/mpv-player/mpv/files/5845625/output.txt)

**Comment by avih** [comment]
As far as I can tell there are two issues:
1. The progress area doesn't show at the OSC. It should have lighter background and indicate the progress/position as white at its left side. As far as I know this part doesn't use fonts, so I find it very strange that it doesn't show. I don't think I've seen such issue before. Can you try `--script-opts=osc-layout=box` and then post a screenshot after you seek to the middle of the clip?
2. libass is probably unable to find a font. Does `fc-list` list any fonts? Someone on IRC suggested that the output of `fc-match` (i.e. the font which matches an empty pattern) is the one picked by default, and on my system (Ubuntu) it is the case indeed: `fc-match` prints `DejaVuSans.ttf: "DejaVu Sans" "Book"`, and in the mpv log I see `[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans` when the OSD or OSC displays for the first time. I'd imagine fontconfig needs to have some font which it considers the default, but I don't recall how to set it up (outside of mpv).

**Comment by Mavpt** [comment]
1. Bellow are the log file and a screenshot taken _around_ 4:10/10:34 of mpv when ran using `mpv --script-opts=osc-layout=box --log-file=output.txt`.
[output.txt](https://github.com/mpv-player/mpv/files/5848751/output.txt)
![image](https://user-images.githubusercontent.com/58571526/105341836-7c832d80-5bd7-11eb-9046-25ef166c7755.png)

2. When I run fc-list it outputs 926 fonts. Strangely by runnig both `fc-match` and `fc-match "sans-serif"` I get `Hack Regular Nerd Font Complete Mono Windows Compatible.ttf: "Hack NF" "Regular"`.

**Comment by avih** [comment]
For starters, I'd try to setup fontconfig so that the default and/or "sans-serif" would match a variable width font (not monospace), like dejavu sans or noto sans.

The other issue where lines/rectangles are not drawn (your last screenshot should have shown a rounded frame for the whole OSC with darker semi-transparent background, and a rectangle seek bar) is unclear to me, and I've never seen such issue before. No clue for now, but maybe it's somehow related to libass not finding a font - but if that's the case then I don't understand why...

**Comment by Mavpt** [comment]
Installing dejavu sans fixed the issue as can be seen in the screenshot bellow.
![image](https://user-images.githubusercontent.com/58571526/105347900-72fdc380-5bdf-11eb-92e3-2f8f66b95506.png)

If you there's anything else I can do to help with the latter part of your answer say so. Otherwise I think this issue can be closed.

**Comment by avih** [comment]
Can you please confirm that with layout=box it also renders correctly (rounded frame, etc)?

**Comment by Mavpt** [comment]
I believe so, but the result is in the screenshot bellow.
![image](https://user-images.githubusercontent.com/58571526/105348594-79d90600-5be0-11eb-9704-7e7e2e4915e3.png)

**Comment by avih** [comment]
So we concluded that with missing variable-width font matching "sans-serif", it will not draw the OSD/OSC text, and might also end up not drawing lines and areas. Weird, might be worth looking into it, but good to know regardless.

Yeah, closing for now, though people can stil post here more info.

Thanks.
