### ISSUE TITLE
Ogg Kate support

### ISSUE THREAD

**Issue by nelk114** [mpv-player/mpv#8493]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

Ogg files with [Ogg Kate](https://wiki.xiph.org/OggKate) subtitles streams should have those subtitles available during playback.

This seems to be one of very few ways (the only one I've been able to find) of embedding audio and subtitles in one file without having to have video as well.

### Alternative behavior of the wanted feature

n/a

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by jeeb** [comment]
1. I don't see why (f.ex.) MP4 or Matroska couldn't have audio only + subtitles?
   ```ffmpeg -v verbose -i AUDIO -i SUBS -map 0:a -map 1:s -c:a copy out.mp4```
   (or dot-mkv/a)
2. Subtitle decoding features should go towards FFmpeg. https://trac.ffmpeg.org is FFmpeg's issue tracker.

**Comment by Akemi** [comment]
what jeeb said. sub decoding feature request should go to ffmpeg. a dummy video can be added with lavfi-complex.
