### ISSUE TITLE
Can not build libmpv On Apple M1 Machine

### ISSUE THREAD

**Issue by moonfunjohn** [mpv-player/mpv#8494]
### Important Information

Provide following Information:
- mpv version: 0.33.0
- macOS Version: 11.1
- Source of the mpv binary or bundle
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

### Reproduction steps

1. Download ffmpeg-4.3.1 source and build 
2. Download mpv-0.33.0 source and run the following command:
     ./bootstrap.py
     ./waf configure --enable-libmpv-static
     ./waf

### Expected behavior

Build successfully and libmpv.a will show at build/libmpv.a

### Actual behavior

It show me the following message: 

[257/420] Compiling player/configfiles.c
ld: warning: ld: warning: ignoring file /usr/local/lib/libavfilter.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64

Please help.

**Comment by Akemi** [comment]
your build environment is telling waf to build for for x86. though i can't tell with nearly to no info, maybe provide the full configure and build log. building for arm64 is already confirmed working.

you can try setting CFLAGS="-mmacosx-version-min=10.8" and/or LDFLAGS="-mmacosx-version-min=10.8" for configure and/or setting the right --swift-flags="\-target arm64-apple-macosx10.X".

**Comment by moonfunjohn** [comment]
Please find the attached log files.
[build.log](https://github.com/mpv-player/mpv/files/5853883/build.log)
[config.log](https://github.com/mpv-player/mpv/files/5853884/config.log)

**Comment by Akemi** [comment]
your build log is incomplete. did you properly clean your build folder and environment, seems like you still have build artifacts left from your old build? otherwise it wouldn't start with:

> [224/420] Linking build/mpv
> [225/420] Compiling video/out/filter_kernels.c

**Comment by moonfunjohn** [comment]
[build.log](https://github.com/mpv-player/mpv/files/5859534/build.log)

Please find the complete build.log

**Comment by Akemi** [comment]
what are your full command line invocations?

**Comment by CounterPillow** [comment]
From your config.log:
```
#define __SSE2_MATH__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE_MATH__ 1
#define __SSE__ 1
#define __SSP__ 1
#define __SSSE3__ 1
[...]
#define __amd64 1
#define __amd64__ 1
[...]
#define __x86_64 1
#define __x86_64__ 1
```

You are, somehow, using a x86_64 crosscompilation toolchain (or an x86_64 toolchain running JIT'd on ARM). No explicit x86_64 target is specified, but your /usr/bin/cc is building for x86_64, as evident from this part of your config.log:
```
[1/2] Compiling [32mbuild/.conf_check_8e46d5179a7baee80c5bde3d8e886731/test.c[0m

['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Wall', '-std=c11', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wimplicit-fallthrough', '-fno-math-errno', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-Wno-logical-op-parentheses', '-fcolor-diagnostics', '-Wno-tautological-compare', '-Wno-tautological-constant-out-of-range-compare', '-DDEFAULT_DVD_DEVICE="/dev/rdiskN"', '-DDEFAULT_CDROM_DEVICE="/dev/disk1"', '-DHAVE_GPL=1', '-DHAVE_CPLAYER=1', '-DHAVE_LIBMPV_STATIC=1', '-DHAVE_BUILD_DATE=1', '-DHAVE_OPTIMIZE=1', '-DHAVE_DEBUG_BUILD=1', '-DHAVE_LIBDL=1', '-DHAVE_CPLUGINS=1', '-DHAVE_ASM=1', '-DHAVE_LIBM=1', '-DHAVE_POSIX=1', '-DHAVE_POSIX_OR_MINGW=1', '-DHAVE_SWIFT=1', '-DHAVE_PTHREADS=1', '-DHAVE_STDATOMIC=1', '../test.c', '-c', '-o/Users/john/Documents/workspace/mpv-0.33.0/build/.conf_check_8e46d5179a7baee80c5bde3d8e886731/testbuild/test.c.1.o']
[2/2] Linking [33mbuild/.conf_check_8e46d5179a7baee80c5bde3d8e886731/testbuild/testprog[0m

['/usr/bin/cc', '-L/Library/Developer/CommandLineTools/usr/lib/swift/macosx', '-Xlinker', '-rpath', '-Xlinker', '/usr/lib/swift', '-L/usr/lib/swift', '-Xlinker', '-rpath', '-Xlinker', '/Library/Developer/CommandLineTools/usr/lib/swift/macosx', 'test.c.1.o', '-o/Users/john/Documents/workspace/mpv-0.33.0/build/.conf_check_8e46d5179a7baee80c5bde3d8e886731/testbuild/testprog']
err: Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _main in test.c.1.o
  "_iconv_close", referenced from:
      _main in test.c.1.o
  "_iconv_open", referenced from:
      _main in test.c.1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
