### ISSUE TITLE
Let Stats.lua show the change of window scale when toggle fullscreen

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8495]
### Expected behavior of the wanted feature
When entering the fullscreen,  the number of window scale should change.
![Snipaste_2021-01-21_23-54-44-tuya](https://user-images.githubusercontent.com/41094733/105375905-226c8180-5c44-11eb-8549-ea9f767527e2.jpg)

### Alternative behavior of the wanted feature
To show the extra text like "fs" in the `Stats.lua`

### Log file
Unnecessary

**Comment by Akemi** [comment]
window scale represents the actual scale of the windowed window and not the fullscreen window. so no this value should not change in fullscreen.

i don't see a reason to add an "fs" behind it, though neither do i have a strong argument of not adding it.

**Comment by avih** [comment]
The value of the property window-scale affects/reflects the window size - not when full screen.

You can try changing its value using the console and notice that stats does display the changed value, or, alternatively, display it (using the console) while in full screen and notice that it's the same value which stats.lua displays.

So, not a bug - the current value of the window-scale property is displayed correctly.

**Comment by avih** [comment]
Also, while, like @Akemi, I don't have an argument against it, what's the reason you want it to display an indication that it's currently at full screen?

**Comment by hooke007** [comment]
Well,  I do not have a strong argument of adding that.
Maybe I misunderstood the fullscreen, I always thought it is full-windowed.
Just want to show the actual number especially when I use the (nonstandard-ratio) monitor.

**Comment by avih** [comment]
> Just want to show the actual number

Well, would adding "fullscreen" help with that? If no, what kind of value would you want to see there? the image is just stretched/shrunk (by default) to fit the available fullscreen area...

**Comment by Argon-** [comment]
This property (unfortunately) only gives us 1 when in fullscreen, no way around that. This frequently causes confusion though. Maybe it’s better to not show this value when fullscreened?

**Comment by avih** [comment]
> This property (unfortunately) only gives us 1 when in fullscreen

No, it just doesn't change when going fullscreen because it represents the _window_ scale. You can resize the video manually and observe that it changes to some value, then go fullscreen and observe that it just stays whatever it was when windowed.

**Comment by hooke007** [comment]
> Well, would adding "fullscreen" help with that?

Maybe it sounds stupid, but I sometimes thought that was the actual number :-) , or just hide it when fullscreen (like @Argon- said that)?

**Comment by TooYoungTooSimp** [comment]
Maybe we can change it to something other... like just "display scale" or other words which reflect the ratio of display size and video size. So it has the same meaning when windowed and additional intuitive meaning in full screen mode.
