### ISSUE TITLE
Setting option gpu-api='vulkan' failed.

### ISSUE THREAD

**Issue by zluo01** [mpv-player/mpv#8496]
### mpv version and platform versions

mpv-build with master 

system: Fedora 33 with kernel version 5.10.8

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Build with following options for mpv
```
--enable-vapoursynth
--enable-libmpv-shared
--enable-lua
--enable-libbluray
--enable-uchardet
--enable-rubberband
--enable-libavdevice
--enable-vulkan
--enable-shaderc
--enable-caca
--enable-libplacebo
--enable-cuda-hwaccel
--enable-cuda-interop
--enable-pulse
--enable-alsa
```

and `--enable-libx264` for ffmpeg

### Expected behavior
can use vulkan api

### Actual behavior
```
Error parsing option gpu-api (option parameter could not be parsed)
~/.config/mpv/mpv.conf:6: setting option gpu-api='vulkan' failed.
```

### Log file
[config.log](https://github.com/mpv-player/mpv/files/5850834/config.log)
[log.txt](https://github.com/mpv-player/mpv/files/5852776/log.txt)

The issue will be closed for ignoring the issue template.

**Comment by CounterPillow** [comment]
Post full mpv log, not just the build log.

**Comment by zluo01** [comment]
> Post full mpv log, not just the build log.

Updated. Thank you.

**Comment by CounterPillow** [comment]
You built without x11 or wayland (just wayland-protocols?) so no way to create a vulkan context is available; if you run `mpv --gpu-api=help` I suspect it won't show vulkan for that reason.

Why it was compiled without x11/wayland likely is because you are missing some headers.

**Comment by zluo01** [comment]
> You built without x11 or wayland (just wayland-protocols?) so no way to create a vulkan context is available; if you run `mpv --gpu-api=help` I suspect it won't show vulkan for that reason.
> 
> Why it was compiled without x11/wayland likely is because you are missing some headers.

The required X11 dev headers is not in the default package for fedora. Thank you very much,.
