### ISSUE TITLE
Random replaygain failures with mp3 files

### ISSUE THREAD

**Issue by Vrihub** [mpv-player/mpv#8499]
### Important Information

Provide following Information:
- mpv version: 4b25ec3
- Linux Distribution and Version: debian 10.6
- Source of the mpv binary: debian package mpv 0.29.1-1

### Reproduction steps

Play an mp3 file.

### Expected behavior

The file should play ok.

### Actual behavior

Most of the times mpv works ok, but some times (~20%) the output is silence, and some times (~20%) the output is distorted noise. The problem happens randomly, when playing the _same_ file.

So far I've noticed the problem only with mp3 files: aac files and video files are ok.

I've noticed the problem not just in specific files, but with most of the mp3 files that I created by ripping my CDs, using lame (version 3.100 from debian), command line: `lame -x -r -h -b 128`. I haven't tested other mp3 files yet.

The problem doesn't occur with `--no-config`.

The option causing the problem seems to be `replaygain=track` (see the log file excerpts below)

### Log file

By running mpv with `--msg-level=all=trace` I've noticed that there must be some problem in the replaygain initialisation: please compare the relevant log file parts in the three different cases:

File plays OK:

    [v][cplayer] Replaygain: Track=-0.000000/0.000000 Album=0.000000/0.000000
    [v][cplayer] Applying replay-gain: 1.000000
    [v][cplayer] ...with clipping prevention: 1.000000

File plays silence:

    [v][cplayer] Replaygain: Track=-70136128748912640.000000/0.000000 Album=0.000000/0.000000
    [v][cplayer] Applying replay-gain: 0.000000
    [v][cplayer] ...with clipping prevention: 0.000000

File plays noise:

    [v][cplayer] Replaygain: Track=5184219388910173350784159336395440128.000000/0.000000 Album=0.000000/0.000000
    [v][cplayer] Applying replay-gain: inf
    [v][cplayer] ...with clipping prevention: inf

So it seems that some times mpv fails to set the replaygain value, setting it to 0 or infinity.

Please note that the problem happens both in files that contain a replaygain setting, and also in files that have NO replaygain setting in them.

Sample file: https://0x0.st/-ino.mp3

**Comment by mia-0** [comment]
This was fixed in commit 49d6a1e77d3dba5cf30a2cb9cd05dc6dd6407fb2.
