### ISSUE TITLE
Strange errors when playing video with waylandvk

### ISSUE THREAD

**Issue by jack-javana** [mpv-player/mpv#8501]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.33.0-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
built on UNKNOW
FFmpeg library versions:
    libavutil       56.51.100
    libavcodec      58.91.100
    libavformat     58.45.100
    libswscale      5.7.100
    libavfilter     7.85.100
    libswresample   3.7.100
 FFmpeg version: n4.3.1
```
- Linux Distribution and Version: Arch Linux rolling
- Source of the mpv binary: https://github.com/mpv-player/mpv/tree/v0.33.0 - Arch Linux package 
- If known which version of mpv introduced the problem: 33.0
- Window Manager and version: SwayWM 1.5.1
- GPU driver and version: intel hd 630 kbl gt 2/ i915 / libva intel 2.4.1

### Reproduction steps
Add hwdec=vaapi to config 
Add gpu-context=waylandvk to config 
Play any video 

### Expected behavior
Playing video without any errors 
 
### Actual behavior
Video playing normally but mpv is output errors  
```
[   0.039][e][vo/gpu/vulkan/libplacebo] Imported object requires 69656 bytes, larger than the provided size 65536!
[   0.039][e][vo/gpu/vulkan/libplacebo] Imported object requires 69656 bytes, larger than the provided size 65536!
[   0.039][e][vo/gpu/vulkan/libplacebo] Imported object requires 69656 bytes, larger than the provided size 65536!
[   0.039][e][vo/gpu/vulkan/libplacebo] Imported object requires 69656 bytes, larger than the provided size 65536!
```
### Log file
https://0x0.st/-i7n.txt

**Comment by Dudemanguy** [comment]
I think these libplacebo warnings are harmless (not even sure if they're printed these days).
