### ISSUE TITLE
[Feature Request] Provide content of the --playlist option to the scripting layer

### ISSUE THREAD

**Issue by RivenSkaye** [mpv-player/mpv#8508]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request
Well, can't find it anyways. Feel free to point me somewhere else if I missed it

### Expected behavior of the wanted feature
Some callable or property in the Lua (and possibly JS) scripting layer to request the URI/URL or file (with path given to it) passed to the `--playlist` option. Logically `nil` (JS: `undefined` or `null`) if a selector or otherwise non-file object was used, or if no playlist was passed to mpv.

If a playlist was read as the normal input file rather than explicitly set through `--playlist`, possibly keep the option as `nil` or it's JS equivalent. This would allow a user the choice to make this file available to any script installed.

This might even become an extra sub-property of the already existing table returned with a call to `mp.get_property_native("playlist")`. This currently returns the mpv internal playlist, which could house this property as the very first or very last entry. Printing it when playing local files displays `{"filename":"<mediafile>.<ext>"}`, for the playlist itself this could be `{"playlist":"<content of --playlist>"}`. The content field could be empty if a selector like `*.mkv` was used.

Being able to interact with the playlist file can be useful for scripting purposes. For example parsing it for an unshuffled order, removing viewed entries when watching a series or compiling playlists of frequently played items in it just to name a few examples. There are also scripts to manage and create playlists, this could allow them to expand a previously made playlist without having to create a new file.

### Alternative behavior of the wanted feature
A property or callable that returns the input given to the `--playlist` option as-is, without formatting or transforming it. Scripts can be made plenty capable to check if it's a useful path or URI with a few extra lines of code.

### Log file
Attachment: [logfile.txt](https://github.com/mpv-player/mpv/files/5861374/logfile.txt), generated with `mpv -v -v --playlist=playlist.txt >> logfile.txt`. Playlist made with a simple `ls >> playlist.txt` and removed entries I'd already seen/don't care about. I still had this sitting there, figured I might as well use it

**Comment by CogentRedTester** [comment]
Have you tried using the `options/playlist` property?

**Comment by RivenSkaye** [comment]
Not working from the Lua env, `mp.get_property("options/playlist")`  returns a `nil` value, `get_properties("options")` returns a very long string representation of an ~~array~~ indexed table. Getting it native so I can `pairs` or `ipairs` the keys with it  gives me the string value `playlist` on position 2, but no luck getting the input option's value.

Tried a few others listed there and while `options/script` returns `nil`, `options/scripts` returns a table of scripts loaded with the `--script` option. Naturally I tried `options/playlists` to poke if it exhibits the same behavior, but no luck there. Thanks for the suggestion though!

**Comment by guidocella** [comment]
I get a playlist's path before it is expanded by retrieving the playlist property at the beginning of scripts, rather than in event handlers:
```lua
local first_entry = mp.get_property('playlist/0/filename')
if first_entry:match('%.m3u$') ...
```

**Comment by RivenSkaye** [comment]
guidocella's solution seems to work on the typical playlist file if it's loaded as the input file.
I get it returned when I run `mpv playlist.m3u` and the script runs, but if I pass it as a parameter of the playlist option like `mpv --playlist=playlist.m3u`, it gets the first filename in the playlist instead of the playlist file. So this only works for the common file formats that can be passed as an input file, not for options passed to `--playlist`
