### ISSUE TITLE
Static played after seek when using pulseaudio output with pipewire

### ISSUE THREAD

**Issue by artemist** [mpv-player/mpv#8510]
### Important Information

- mpv 0.33.0
- NixOS unstable (21.03pre265130.f217c0ea7c1)
- Using MPV from distribution
- Does not appear limited to a single MPV version
- Window manager is Sway 1.5.1 with wlroots 0.12.0
- Audio server is pipewire 0.3.18
- GPU driver is Linux 5.10.9 amdgpu with mesa 20.3.2 radeonsi
- Audio output device is a Scarlett Solo connected via USB

### Reproduction steps
Attempt to seek quickly backwards or forwards within a video file by holding left or right with audio output set to pulse and using pipewire as the audio server.
This works with or with or without my only audio-sensitive option in my config, `audio-normalize-downmix=yes`. This does not happen when using the alsa or sdl audio output (I have not tested jack) and is significantly reduced when using `audio-buffer=2`.
I have found this behavior on aac, truehd, and dca tracks (all from separate blu-ray rips).

### Expected behavior
When you seek to a position the audio will be decoded then will play normally

### Actual behavior
Occasionally, the audio will be replaced with a static crackle, as if it is unitialized memory. After several seconds the audio will return to normal with no desync.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/5861647/log.txt)

### Sample files
It appears inconsistently but in several different files so I do not believe a sample file is necessary.

**Comment by artemist** [comment]
I'll test with some other players soon and if it seems this is a pipewire issue I'll report it there

**Comment by eternal-sorrow** [comment]
It is pipewire issue https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/394

**Comment by artemist** [comment]
Okay, thanks! I'll move this up to pipewire then
