### ISSUE TITLE
Saving the value of a property in input.conf to restore it later in the session ?

### ISSUE THREAD

**Issue by butterw** [mpv-player/mpv#8512]
Is there a way to store the value of a property so it can be restored later in the same session ?

I'm trying to implement a command to disable/enable the current shader chain.
Disabling shaders is done via input.conf:
CTRL+p change-list glsl-shaders set ""

When turning the shaders back on, I would need to restore them to their previous ${glsl-shaders} value, which is no longer available. I've tried switching profiles, but I couldn't get it work as desired.
I use many different shaders, typically specified at command line, so the answer provided in the following closed issue isn't applicable: Shader on/off command https://github.com/mpv-player/mpv/issues/7582

**Comment by snylonue** [comment]
try this js script
```js
'use strict';
var shader_status = [];

mp.register_script_message("switch-shader", function() {
    if (shader_status.length) {
        shader_status.forEach(function(shader) {
            mp.commandv("change-list", "glsl-shaders", "append", shader);
        });
        shader_status = [];
    } else {
        shader_status = mp.get_property("glsl-shaders").split(',');
        mp.commandv("change-list", "glsl-shaders", "set", "");
    }
});
```

**Comment by butterw** [comment]
script works fine, thanks.
