### ISSUE TITLE
Please don't remove gl-x11

### ISSUE THREAD

**Issue by duramuss** [mpv-player/mpv#8515]
In commit 7831e52238790bf1742b194e0469cf3db5f59bdd, it is said:
> build: disable GLX
> 
> Nobody needs this anymore. If not too many people complain, we'll remove
> this completely. Many already consider X11 and OpenGL legacy, so we
> don't need TWO X11/OpenGL backends.

I'm still using it. Playback does not work correctly on my system without "--gpu-context=x11" and works perfectly with it.
So please don't remove it.

**Comment by LaserEyess** [comment]
If you can't get `--gpu-context=x11egl` working that sounds like a driver issue. However, that commit doesn't mean GLX was removed, it means that it is not the default. You simply need to do `--enable-gl-x11` when building. I don't think it will be removed any time soon.

**Comment by CounterPillow** [comment]
Thanks for ignoring the issue template.
