### ISSUE TITLE
Last character of the line in colored subtitles is always white

### ISSUE THREAD

**Issue by bok** [mpv-player/mpv#8519]
### Important Information

- mpv version : 0.33.0
- Windows Version : Windows 10 20H2 (v19042)
- Source of the mpv binary : chocolatey package
- If known which version of mpv introduced the problem: not known

mpv 0.33.0 : 
![image](https://user-images.githubusercontent.com/175088/106179324-2c8a0500-619b-11eb-9a99-4655185e1fce.png)

### Reproduction steps

Open a video with colored ASS subtitles.

### Expected behavior

Entire line of subtitles is the same color. For example, this is vlc rendering the same lines: 

same line with vlc :
![image](https://user-images.githubusercontent.com/175088/106179430-53483b80-619b-11eb-8ed4-dd1574dbe799.png)

### Actual behavior

The last character of each line is white instead of the specified color (blue in this case):
![image](https://user-images.githubusercontent.com/175088/106179324-2c8a0500-619b-11eb-9a99-4655185e1fce.png)

### Log file

https://0x0.st/--09.txt

### Sample files

https://0x0.st/--GO.mp4

**Comment by Akemi** [comment]
a sample file or subtitle file would be nice. also this is most likely a ffmpeg or libass issue.

**Comment by bok** [comment]
Added a sample file (20 s extract from the original file exhibiting the problem - the issue is still present).

**Comment by Akemi** [comment]
this is what ffmpeg extracts. either it's like this in the file or ffmpeg fucks it up. i tried to extract the file with mp4box, but there no tags are extracted. btw those tags are also not standard conform for srt subtitles.

anyway this is an ffmpeg issue, if at all. report it to them.

```
1
00:00:01,040 --> 00:00:03,840
<font size="36"><font color="#00ffff">All that money on veterinar</font></font><font size="36">y
<font color="#00ffff">college</font></font><font size="36">.</font>

2
00:00:03,840 --> 00:00:07,040
<font size="36"><font color="#00ffff">It's all these truck</font></font><font size="36">s
<font color="#00ffff">and motorcars now</font></font><font size="36">.</font>

3
00:00:08,080 --> 00:00:11,200
<font size="36"><font color="#00ffff">No-one's got need of vets any more</font></font><font size="36">.</font>

4
00:00:11,200 --> 00:00:14,480
<font size="36">Thanks, Mother.</font><font size="36">
<font color="#ffff00">Och, something'll come along</font></font><font size="36">.</font>

5
00:00:14,480 --> 00:00:17,040
<font size="36"><font color="#00ffff">And what if it doesn't</font></font><font size="36">?
LETTERBOX RATTLE</font><font size="36">S</font>

6
00:00:18,200 --> 00:00:21,840
<font size="36">I'll go, Dad.</font><font size="36"> <font color="#ffff00">No, son. You sit an</font></font><font size="36">d
<font color="#ffff00">eat your breakfast</font></font><font size="36">.</font>

```
