### ISSUE TITLE
Can't seek to absolute milliseconds accurately

### ISSUE THREAD

**Issue by snowman** [mpv-player/mpv#8521]
### The steps to reproduce:

```lua
-- FILE: /tmp/seek-then-report.lua
local msg = require "mp.msg"

function foo()
   mp.set_property("pause", "yes")
   mp.commandv("seek", "12.345", "absolute")
end

function bar()
   msg.error("lua> time-pos: " .. mp.get_property("time-pos"))
end

mp.register_event("file-loaded", foo)
mp.register_event("seek", bar)
```

```conf
## FILE: /tmp/input.conf
i print_text "input.conf> time-pos: ${=time-pos}"
```

```sh
## generate sample video to test
$ \ffmpeg -f lavfi -i color=color=blue -t 30 /tmp/blue.mp4

## test with mpv
$ \mpv --load-scripts=no --script=/tmp/seek-then-report.lua --input-conf=/tmp/input.conf /tmp/blue.mp4

 (+) Video --vid=1 (*) (h264 320x240 25.000fps)
[seek_then_report] lua> time-pos: 12.345000
VO: [gpu] 320x240 yuv420p
(Paused) V: 00:00:12 / 00:00:30 (41%)
input.conf> time-pos: 12.360000
(Paused) V: 00:00:12 / 00:00:30 (41%)

Exiting... (Quit)
```

The current `time-pos` is `12.360000` not `12.345`, how to ensure at least three significant decimals? 🤔

**Comment by butterw** [comment]
@25fps, 1 frame=40ms, so seeking seems to have occured to the nearest frame.
 
You should test with an audio file and higher fps video to confirm.

**Comment by snowman** [comment]
That's where the problem is, it should seek to *both* seen and nearest frame, instead of seeking to the next unseen frame just because it's "nearest" to the given time pos.

In short, it should not seek to position where are greater than the given time pos.

If frames can be described as pairs: `[(start1, end1), (start2, end2), ..., (startN, endN)]`, where `startN` and `endN` are start/end time pos of the corresponding frame, and each pair do not overlap. When seek to the specific time pos, it's valid to seek to any position within the pair that includes the given time pos, ideally, it should seek to that frame and exact time pos. 

But if not possible, how about seek to the start of the frame where `(startN, endN)` includes the given time pos?

This is something like the math function `floor` and `round`, we need `floor` because we don't like `1.8` to become `2.0`, it's okay to seek to any timepos within `[1.0, 1.8)` but not to next frame `[2.0, 2.9)`, and seek to that frame and exact time pos is perfect.

**Comment by snowman** [comment]
I am content with the current situation because the `time-pos` is got by calling `get-property playback-time`, so the `time-pos` is not manually pick up and can seek to position around where has no visual difference.
