### ISSUE TITLE
some command cant run in "input-ipc-serve"?

### ISSUE THREAD

**Issue by vvyoko** [mpv-player/mpv#8525]
### Important Information

Provide following Information:
- mpv 0.33.0
- Windows Version Windows10 1909

### Reproduction steps

1,run mpv with  `--input-ipc-server=\\.\pipe\mpvsocket`

2,run cmd then type
`echo set volume 9>\\.\pipe\mpvsocket`

it dont  happen anything

10+ can run
`echo set volume 15>\\.\pipe\mpvsocket`
`echo set volume 11>\\.\pipe\mpvsocket`
and give the log:
```
[  29.273][v][ipc_2] Client connected
[  29.273][d][cplayer] Run command: set, flags=73, args=[name="volume", value="15"]
[  29.273][v][cplayer] Set property: volume=15 -> 1
[  29.273][v][ipc_2] Client disconnected
[  29.273][d][ipc_2] Exiting...
[  51.697][v][ipc_3] Client connected
[  51.697][v][ipc_3] Client disconnected
[  51.697][d][ipc_3] Exiting...
[  84.244][v][ipc_4] Client connected
[  84.244][d][cplayer] Run command: set, flags=73, args=[name="volume", value="11"]
[  84.244][v][cplayer] Set property: volume=11 -> 1
[  84.244][v][ipc_4] Client disconnected
```

just number 0-9 dont run.

i dont find other command use the same number  type
only find `seek`
it not run in 0-9 and run in 10+ too.

`echo seek 10>\\.\pipe\mpvsocket` can run with log
```
[ 972.755][v][ipc_22] Client connected
[ 972.755][d][cplayer] Run command: seek, flags=73, args=[target="10.000000", flags="relative", legacy="unused"]
[ 972.755][v][ipc_22] Client disconnected
[ 972.755][v][lavf] queuing seek to 45.846000
[ 972.755][d][ipc_22] Exiting...
```
`echo seek 9>\\.\pipe\mpvsocket` cant run

**Comment by rossy** [comment]
This seems to be to do with Command Prompt syntax. The syntax ``command n> file``, where n is 0-9, redirects a specific output stream from _command_ to _file_. ``1>`` redirects standard output and ``2>`` redirects standard error. The other digits are undefined (I think,) but cmd still parses the syntax.

To send these commands, put a space between the digit and the >, like ``echo set volume 9 >\\.\pipe\mpvsocket``
