### ISSUE TITLE
Is it possible to disable specific subtitle tracks?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#8528]
I would prefer disabling everything but English by default -- I often have to switch subtitles due to SDH tags (I don't believe that mpv can [filter](https://mpv.io/manual/master/#options-sub-filter-sdh) picture-based subtitles) and the others add much delay to the browsing when they happen to be placed first.

**Comment by 07416** [comment]
Or alternatively, avoiding [forced subtitles](https://en.wikipedia.org/wiki/Subtitles#Categories) by default would help.

>Forced subtitles are common on movies and only provide subtitles when the characters speak a foreign or alien language, or a sign, flag, or other text in a scene is not translated in the localization and dubbing process.

**Comment by Akemi** [comment]
not possible.
