### ISSUE TITLE
Building x86_64 on M1 fails.

### ISSUE THREAD

**Issue by SubstituteR** [mpv-player/mpv#8533]
### Important Information

Provide following Information:
- mpv version: Latest Master
- macOS Version: 11.0.1 ARM

### Reproduction steps
Attempt to build an x86_64 binary with
`./waf configure --disable-debug-build --swift-flags="-target x86_64-apple-macos10.12"`

Compiling for ARM works fine. I'm not an expert so this could simply be a case of a missing flag, but I'm stumped.

### Expected behavior
x86_64 binary that will run on all macs.
### Actual behavior
throws an error during linking
> [225/225] Linking build/mpv
ld: warning: ignoring file osdep/macOS_swift.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC11macOS_swift19RemoteCommandCenter", referenced from:
      objc-class-ref in macosx_events.m.22.o
  "_OBJC_CLASS_$__TtC11macOS_swift7CocoaCB", referenced from:
      objc-class-ref in macosx_application.m.22.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Akemi** [comment]
if you set the target for the swift code you also need to set the target for the (obj-)c files.

set CFLAGS="-mmacosx-version-min=10.12" and/or LDFLAGS="-mmacosx-version-min=10.12" for configure.

```
CFLAGS="-mmacosx-version-min=10.12" ./waf configure ...
```

**Comment by SubstituteR** [comment]
Almost. On a fresh pull of the repo both,
`CFLAGS="-mmacosx-version-min=10.12 -target x86_64-apple-macos10.12" ./waf configure`
and
`CFLAGS="-mmacosx-version-min=10.12 -target x86_64-apple-macos10.12" ./waf configure --disable-debug-build --swift-flags="-target x86_64-apple-macos10.12"`
throw `Unable to find either POSIX or MinGW-w64 environment, or compiler does not work.`

I am able to build other x86_64 binaries no problem, and ARM still works.

**Comment by Akemi** [comment]
then you have to find out why it can't find your posix environment. that sounds like you dev/build environment is not configured correctly.

it's possible that you need to install the SDK header that are in `/Library/Developer/CommandLineTools/Packages/`, if you use the commandlinetools.

**Comment by SubstituteR** [comment]
It only throws this error when using `-target x86_64-apple-macos10.12` in the CFLAGS.

`gcc -mmacosx-version-min=10.12 -target x86_64-apple-macos10.12 asdf.c` on a test file works without issue and produces a binary.

**Comment by Akemi** [comment]
did you also try to set the appropriate LDFLAGS like i mentioned on my first comment?

**Comment by SubstituteR** [comment]
> did you also try to set the appropriate LDFLAGS like i mentioned on my first comment?

Yes, and checking further the problem is with the WAF configuration. If I write a wrapper around CC that invokes with the target, everything configures correctly. Now building is failing due to it using /opt for homebrew (ARM on the M1). Trying to get it to use the x86_64 homebrew install has been fruitless but I'm still trying.

**Comment by Akemi** [comment]
my guess is that your pkg-config path is set wrongly. you can check with `pkg-config --variable pc_path pkg-config`. it probably attempts to look into `/opt` first.

you can prepend to that path with the $PKG_CONFIG_PATH env variable. maybe it might also make sense to adjust your $PATH variable too, to look into `/usr/local` first.

i never tried to cross compile myself, so my experiences are limited. though many before already tried to cross compile the other way around and it works. so there is most likely something that isn't completely right in your setup.

also on a side note it might not like `-target x86_64-apple-macos10.12` but rather wants `--target=x86_64-apple-macos10.12`. it didn't make a difference here, but who knows.

also if you really need further help it's best to provide the configure log from now on.

**Comment by SubstituteR** [comment]
I was able to eventually get it all worked out with a lot of linking and unlinking in brew, etc.

Now I can build for ARM and x86_64! A few notes though, your script to generate an app bundle needs an update. All apps are required to be signed on Apple silicon and codesign won't allow for a symbolic link as the binary in the plist. My current work around is just naming mpv mpv-bundle. Another note, the bundler only pulls either x86_64 or ARM dynlibs. My workflow for this was to simply build each .app and then run a bash script to call lipo on everything (and outputting the merged results.)

Thanks for the assistance! Once I can confirm all is well on Intel macs, I'll be uploading the universal binary.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/6234332/107134158-8a1a0200-68bd-11eb-8c8b-afb1230e2288.png">

**Comment by Akemi** [comment]
> A few notes though, your script to generate an app bundle needs an update... Another note, the bundler only pulls either x86_64 or ARM dylibs. My workflow for this was to simply build each .app and then run a bash script to call lipo on everything (and outputting the merged results.)

i am aware. though i am not sure i do care enough. thinking the workflow of building two separate mpv binaries, bundle those and merge the two resulting bundles, might be the best workflow anyway. for the last part we could make a separate script.

> All apps are required to be signed on Apple silicon and codesign won't allow for a symbolic link as the binary in the plist. My current work around is just naming mpv mpv-bundle and then signing.

that's pretty unfortunate, since it breaks one part of our code, or we might be able to swap symlink and binary. feel free to open a PR or since i didn't look into signing yet maybe a small command example might be helpful.

**Comment by SubstituteR** [comment]
> > A few notes though, your script to generate an app bundle needs an update... Another note, the bundler only pulls either x86_64 or ARM dylibs. My workflow for this was to simply build each .app and then run a bash script to call lipo on everything (and outputting the merged results.)
> 
> i am aware. though i am not sure i do care enough. thinking the workflow of building two separate mpv binaries, bundle those and merge the two resulting bundles, might be the best workflow anyway. for the last part we could make a separate script.
> 
> > All apps are required to be signed on Apple silicon and codesign won't allow for a symbolic link as the binary in the plist. My current work around is just naming mpv mpv-bundle and then signing.
> 
> that's pretty unfortunate, since it breaks one part of our code, or we might be able to swap symlink and binary. feel free to open a PR or since i didn't look into signing yet maybe a small command example might be helpful.

I've uploaded my basic bundler script into a repo. As for switching the symbolic link/binary, that sounds best.
`codesign --force --deep -s - mpv.app` on the app with the symbolic link results in
![image](https://user-images.githubusercontent.com/6234332/107154253-ec1b4b80-693f-11eb-8a54-29170ca32814.png)
Oh well, like you said, switching the link and the binary is probably best.

**Comment by Coeur** [comment]
Thanks SubstituteR.
I've added your tip to https://github.com/mpv-player/mpv/wiki/Compiling-distro-releases-for-macOS
