### ISSUE TITLE
How to play videos circularly in QT

### ISSUE THREAD

**Issue by IHaveBeenAHero** [mpv-player/mpv#8534]
I played my playlist in a QT app via command "loadlist": 
```
const char* args[] = {"loadlist", "/xxx/xxx/xxx/playlist.txt", NULL};
mpv_command_async(_mpv, 0, args);
```
It works well.
But how can i play the playlist in a loop?
https://mpv.io/manual/master/#list-options is too complex for me.  
Thanks.

**Comment by snylonue** [comment]
[`loop-playlist`](https://mpv.io/manual/master/#options-loop-playlist), which can be used as a property

**Comment by IHaveBeenAHero** [comment]
Great! It works. Thank you so mush!
