### ISSUE TITLE
Option to disable nvidia gsync / adaptive sync

### ISSUE THREAD

**Issue by adolfotregosa** [mpv-player/mpv#8537]
When in fullscreen nvidia gsync engages causing stutters with interpolation and video-sync=display-resample.  Other video-sync=display-* options produces, has documented at mpv.io, av desynchronization, video frame drops or  audible audio frame drops.

I really want to keep using interpolation.

Nvidias __GL_VRR_ALLOWED=0 affects nothing with mpv.

Suggestions?

**Comment by aufkrawall** [comment]
According to this user, that variable only works with OGL: https://forums.developer.nvidia.com/t/gl-vrr-allowed-only-affects-opengl-applications-and-is-ignored-with-vulkan/79594

Seems like a dumb driver limitation. I had a similar issue with Nvidia + mpv on Windows, where globally enabled VRR would make the switch to fullscreen painfully slow without hardware decoding and exception for mpv.exe didn't help.

**Comment by adfolfotregosa** [comment]
Yeah indeed but for linux if I use smplayer front end to control mpv gsync is not engaged so it is possible. Hopefully developers find a little time to see this.

**Comment by Dudemanguy** [comment]
Just FYI, there's nothing mpv can really do about this. It's up to your driver/whatever to provide settings to disable these kinds of things.

**Comment by Dudemanguy** [comment]
Not sure why I didn't close it previously (what I said still applies).
