### ISSUE TITLE
External cover art loader overrides integrated cover art

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#8539]
Hello,

mpv now loads cover art such as `folder.jpg` when it finds it on the same dir as the music file. However, if the music file has embedded cover art, it should be preferred over the `folder.jpg`, which is not happening. The external file always takes preference.

Side note: When loading external cover art, mpv will log `Displaying attached picture. Use --no-audio-display to prevent this.`. This is incorrect, as the pciture is technically not "attached" :)

### Important Information

- mpv version: 0.33.0
- Linux Distribution and Version: Gentoo Linux rolling release
- Source of the mpv binary: Built locally via Portage
- If known which version of mpv introduced the problem: Whatever added https://github.com/mpv-player/mpv/blob/master/player/external_files.c#L45
- Window Manager and version: Irrelevant
- GPU driver and version: Irrelevant
- Possible screenshot or video of visual glitches: No glitch, just buggy behavior

### Reproduction steps

- Have mp3 with attached cover art in a dir
- Add `folder.jpg` with different cover art
- Upon opening the mp3, mpv will display `folder.jpg`

### Expected behavior

Prefer embedded cover art

### Actual behavior

Shows external cover art

### Log file

Nothing relevant

### Sample files

Any file with embedded art will do, really.

Thanks!

**Comment by qazesz1** [comment]
This is exactly what I want to say. https://github.com/mpv-player/mpv/commit/55d7f9ded197d82d172b7baf74b1a07640361ae8 changed the default behavior since 0.33 but didn't offer an option for configuration. An option is needed.
