### ISSUE TITLE
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#8540]
### Important Information

Provide following Information:
```mpv-0.33.0_4,1``` built from the FreeBSD port
```ffmpeg-4.3.1_9,1``` built from the FreeBSD port
FreeBSD 12.2

### Reproduction steps
```
$ youtube-dl https://www.youtube.com/watch?v=QOjmvL3e7Lc
```
Ctrl-C once sufficient amount of video is downloaded
```

$ mpv Tokyo\ Live\ Camera\ Ch1\ \[4K\]\ 東京\ 汐留\ 鉄道\ ライブカメラ\ 2021-02-07\ 15_22-QOjmvL3e7Lc.mp4 
Warning: option --sub-paths was replaced with --sub-file-paths and might be removed in the future.
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
Failed to recognize file format.
```

**Comment by bitraid** [comment]
That's youtube-dl's fault. Use [yt-dlp](https://github.com/pukkandan/yt-dlp) instead.

**Comment by yurivict** [comment]
@bitraid yt-dlp Same problem when the same URL is downloaded with yt-dlp.

**Comment by bitraid** [comment]
Latest version works fine here (Windows and ArchLinux).

**Comment by yurivict** [comment]
I use all latest versions:
yt-dlp-2021.02.04
mpv-0.33.0
ffmpeg-4.3.1

and observe the issue.
