### ISSUE TITLE
New mpv 0.33.0-67-g8121d958ec fail

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8541]
Provide following Information:
- mpv version: 0.33.0-67-g8121d958ec
- Windows Version:  Windows 7 64bits
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- Graphic Card: No.

### Reproduction steps
A lot of my files don't work now, I get a "mpv stopped working, Windows is searching a solution."
Even in streaming mpv freezes (white screen) and doesn't show the video.
Sadly I had to go back to 0.32 version.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/5940317/log.txt)

### Sample files
https://0x0.st/-HST.mp4

**Comment by avih** [comment]
Your CPU is relatively old, and it's possible that new builds by shinchiro now require CPU newer than yours.

I'll upload my own build a bit later for you to try. If it will work for you, then maybe you just need to do your own builds, or find someone which builds mpv suitable for older CPUs. Stay tuned.

**Comment by avih** [comment]
@jimmy-1000 if you try different builds later than 0.32 but earlier than the one which fails, can you figure out which is the latest build which works for you?

**Comment by jimmy-1000** [comment]
> 
> 
> @jimmy-1000 if you try different builds later than 0.32 but earlier than the one which fails, can you figure out which is the latest build which works for you?

You are right, 0.33 requires a better CPU or better graphic card to work properly.

**Comment by avih** [comment]
> 0.33 requires a better CPU or better graphic card to work properly.

Right, but can you figure out what is the latest build which does work for you? (at your link you can find builds going back to 2018) this could provide a hint as for where the limitation comes from.
