### ISSUE TITLE
How to get screen resolution for auto profile?

### ISSUE THREAD

**Issue by qazesz1** [mpv-player/mpv#8542]
I'm looking for a property indicating the screen resolution to make a profile auto switch between monitors.
I have refered manual but didn't found option or property desired. But console shows screen resolution once video loaded.

Anyone have ideas about that?

**Comment by avih** [comment]
I don't think there's a property for the screen, but there is for the video window - which would be tehe same as the screen when in fullscreen mode - `osd-dimensions`.

**Comment by qazesz1** [comment]
That's great! Thanks a lot

**Comment by JohnChristofolakos** [comment]
Maybe these didn't exist in 2021, but when I needed them just now, I found the display-width and display-height properties which seem to be what you're looking for.

Unfortunately, on Windows 10, they don't seem to trigger the observe_property handler if the video window  is moved from one screen to another.
