### ISSUE TITLE
Is it possible to include the file directory in the title?

### ISSUE THREAD

**Issue by crazysword1** [mpv-player/mpv#8543]
My current setup uses title="${filename}" in mpv.conf

E.g.

C:\apple\a.mpg

When I play a.mpg, MPV shows the title as "a.mpg"

What I want is for MPV to show the complete path in the title, i.e. "C:\apple\a.mpg"

Is this possible?

Thanks

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Akemi** [comment]
`path`, see https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst#property-list
