### ISSUE TITLE
mpv no gui with hwdec (v4l2m2m gpu-context=drm)

### ISSUE THREAD

**Issue by rox4d** [mpv-player/mpv#8545]
mpv gui overlapped by movie content (mpv use FFmpeg with Kwiboo's patches for v4l2-request and rkvdec):
mpv --no-config --log-file=mpv_log.txt -vo=gpu -gpu-context=drm -hwdec=drm jellyfish-20-mbps-hd-hevc-10bit.mkv
[mpv_log.txt](https://github.com/mpv-player/mpv/files/5953570/mpv_log.txt)

**Comment by Akemi** [comment]
please don't ignore the issue template and properly fill it.

**Comment by CounterPillow** [comment]
You compiled without lua and without libass.

**Comment by rox4d** [comment]
> You compiled without lua and without libass. Both are required for the OSC.

Thanks for reply, but lua and libass exist in list in list of enabled features (mpv_log.txt) and OSD works fine without -hwdec=drm.

> please don't ignore the issue template and properly fill it.

Not shore what needed info are missed in mpv_log.txt, but:
- mpv version - current git.
- Linux Distribution and Version - ubuntu-18.04 arm64 on rockpro64 sbc (rk3399 based board),mesa from git, kernel 5.10.12 with patches from openelec.
- Source of the mpv binary - compiled from git.
- If known which version of mpv introduced the problem - it is unknown.
- Window Manager and version - marco-compton, but mpv was started from drm console.
- GPU driver and version - panfrost from mesa current git.
- Possible screenshot or video of visual glitches - photo (just after pressing 'i' key) without -hwdec=drm:
![1](https://user-images.githubusercontent.com/34712490/107540594-4550dc80-6bd7-11eb-8b67-59410e0ef06c.jpg)
-hwdec=drm:
![2](https://user-images.githubusercontent.com/34712490/107540586-42ee8280-6bd7-11eb-8171-3b311b28f841.jpg)

**Comment by rox4d** [comment]
p.s. it is a photos because there are only a black rectangle in mpv created screenshot file (by pressing 's' key).

**Comment by avih** [comment]
The GUI shows up when you move the mouse, but I don't know if the mouse works in mpv with drm. You can try pressing DEL to manually make it show up (or invoke with `--script-opts-add=osc-visibility=always`).

**Comment by rox4d** [comment]
> The GUI shows up when you move the mouse, but I don't know if the mouse works in mpv with drm. You can try pressing DEL to manually make it show up (or invoke with `--script-opts-add=osc-visibility=always`).

It works (--script-opts-add=osc-visibility=always), but in case hwdec if movie overlap gui, gui are not visible, behaviour are the same with the second photo - text are visible only in not overlapped part.

**Comment by avih** [comment]
CC @xantoz

**Comment by xantoz** [comment]
Have you tried with `--drm-draw-plane=overlay --drm-drmprime-video-plane=primary`. The default is the opposite way around, which isn't optimal for the hwdec overlay case (and our code is currently too stupid to automatically detect and use what would be the optimal in the hwdec vs swdec case here)

**Comment by rox4d** [comment]
> --drm-draw-plane=overlay --drm-drmprime-video-plane=primary

It works, thanks!

**Comment by rox4d** [comment]
It`s not a much problem to have a couple more options in config.

**Comment by avih** [comment]
Let's wait with closing until we understand whether or not it should be considered a bug. For now, to me it still sounds like a bug that these options are needed in order for the overlay to show actually over the video.

CC @xantoz

**Comment by rox4d** [comment]
It shows black screen without --drm-draw-plane=overlay --drm-drmprime-video-plane=primary with current git
