### ISSUE TITLE
Lua scripts not working 

### ISSUE THREAD

**Issue by ayushjaipuriyar** [mpv-player/mpv#8547]
### Important Information

Provide following Information:
- mpv version ;- 0.33.0-71-g0075b76eeb
- Linux Distribution and Version Manjaro 20.2.1
- Source of the mpv binary 
- If known which version of mpv introduced the problem
- Window Manager and version bspwm 0.9.10-12-g98e9642
- GPU driver and version AMD 4700U
- Possible screenshot or video of visual glitches

### Reproduction steps

As such no reproduction steps cause i do the basic command
``` 
mpv PATH_TO_VIDEO
```
### Expected behavior

To enable lua scripts autoload,autosub and play the video

### Actual behavior

The lua scripts dont work and give errors, but obviously the video works
![2021-02-10_21-37-27_1920x1080](https://user-images.githubusercontent.com/66643292/107536803-3161a680-6be8-11eb-8ea4-21712642c665.png)

### Log file
[output.txt](https://gist.github.com/ayushjaipuriyar/51a933ba90d9d83f419133e81f0a2f43)

**Comment by CounterPillow** [comment]
line 147 of the official autoload.lua is
```
    local pl = mp.get_property_native("playlist", {})
```
not `ge_property_native`.

I recommend that you do not remove random characters from the script file before saving it to your scripts folder.

**Comment by ayushjaipuriyar** [comment]
Yeah I realised that later on , some funky stuff happend with the editor, it was deleting all the 't' from the file and adding it to the end of the file.

So, closing this issue

I am sorry for creating an issue on such on a small mistake
