### ISSUE TITLE
"use-filedir-conf" for "scripts" folder

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [mpv-player/mpv#8549]
There is a .lua script that I want to run on only one folder. I've included "use-filedir-conf" on my main mpv.conf, and have created an "mpv.conf" file and a "scripts" folder on the location. It picks up the secondary "mpv.conf", but not the secondary "scripts" folder. What could I do?

**Comment by avih** [comment]
It's documented to only load a config file - not scripts. Additionally, mpv doesn't unload user scripts, so it wouldn't have worked.

However, you might be able to add to the file-specific config file a value `script=path/to/some-script.lua` which I think should load it. That being said, it will not unload on its own once the file playback ends, so you'll need to do something about it at the script itself.

**Comment by 2V3EvG4LMJFdRe** [comment]
`script=path/to/some-script.lua` doesn't work with mpv.conf. Is it ok if I open an issue asking for it to be supported?

**Comment by avih** [comment]
> script=path/to/some-script.lua doesn't work with mpv.conf

They most definitely do. Do you mean they don't work when set via a file-specific config?

If yes, do provide a full log and all other details as required when reporting an issue.
