### ISSUE TITLE
 srt subtitles fails to be read if auto-numbering not present - OK with VLC or Mplayer

### ISSUE THREAD

**Issue by artofit** [mpv-player/mpv#8553]
Case:
In the same folder:

1/ Take some video: test.mp4

2/ Create a srt text file (utf8) test.srt as such:
```
00:00:03,000 --> 00:00:04,000
Some subtitle 1

00:00:05,000 --> 00:00:06,000
another one

00:00:10,000 --> 00:00:12,000
last one

```
Play again with mpv

no show any subtitles now.

### Expected behavior of the wanted feature
Try VLC or Mplayer, you do see that they show the subtitles

**Comment by Akemi** [comment]
report it to ffmpeg, we use their srt decoder.

**Comment by artofit** [comment]
>report it to ffmpeg, we use their srt decoder. though this is probably not valid srt anyway.
You presume that I know how to.
@Akemi as you rely on ffmpeg, you are in better position to report to them, isn't it?
