### ISSUE TITLE
Totally support 10 bit output?

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8554]
My monitor: `Queried output: \\.\DISPLAY4, 3840x2160 @ 10 bits`
When I test the different `--gpu-api`, I found the differences in the log.

1. `--dither-depth=auto` will select 8 bit for Vulkan&Opengl, while 10 bit for D3d11.
2. swapchain format: `R10G10B10A2` will be chosen when use Opengl&D3d11, no such message for Vulkan.
3. Opengl: `Reported display depth: 8` ; D3d11: `Reported display depth: 10` ; no such message for Vulkan.

So does it mean only the d3d11 support 10 bit output correctly?

### Log file

[d3d11.log](https://github.com/mpv-player/mpv/files/5971344/d3d11.log)
[opengl.log](https://github.com/mpv-player/mpv/files/5971346/opengl.log)
[vulkan.log](https://github.com/mpv-player/mpv/files/5971347/vulkan.log)

**Comment by zc62** [comment]
> So does it mean only the d3d11 support 10 bit output correctly?

In windows, yes. And the suggestion would be, stick to d3d11 if you use windows. Probably see #5237

OpenGL and Vulkan do support 10 bit in principle, but not in mpv+windows. I'm not sure about OpenGL, but for vulkan, I think I heard from haasn that it depends on the implementation provided by your video card vendor. If their implementation does not support 10 bit, there is no way for mpv to utilize 10 bit through vulkan API. You can check by running `vulkaninfo`

**Comment by hooke007** [comment]
[vulkaninfo.txt](https://github.com/mpv-player/mpv/files/5975703/vulkaninfo.txt)
Thanks for your suggestions.
So stupid was I. The format for Vulkan should be `A2B10G10R10`, now I can clearly see that
`[   0.957][d][vo/gpu/vulkan/libplacebo] Picked surface format VK_FORMAT_A2B10G10R10_UNORM_PACK32, space VK_COLOR_SPACE_SRGB_NONLINEAR_KHR`
But at this time, mpv still chose to dither to 8 bit for Vulkan. It's weird.

**Comment by Akemi** [comment]
i don't think it is weird, since it's not implemented for vulkan i believe. at least auto picking it https://github.com/mpv-player/mpv/blob/master/video/out/vulkan/context.c#L223-L226

for comparison:
opengl https://github.com/mpv-player/mpv/blob/master/video/out/opengl/context.c#L212-L237
d3d11 https://github.com/mpv-player/mpv/blob/master/video/out/d3d11/context.c#L187-L195

**Comment by hooke007** [comment]
It seems windows users who cares about the correct output have no other choices except D3d11.

**Comment by haasn** [comment]
You can use `--dither-depth=10` to override the auto-detection.

**Comment by hooke007** [comment]
> You can use `--dither-depth=10` to override the auto-detection.

I know it is useful.
I just wonder if it will have other potential possibility that Vulkan actually output 8 bit.

**Comment by dyphire** [comment]
Fixed by https://github.com/mpv-player/mpv/commit/8b64a5d9378c5ced90c1092aa15602f1575083ca.
