### ISSUE TITLE
Set Refresh Rate

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#8556]
It's a very simple question, but it seems impossible if I search online. I only use mpv for 24hz content on a single display that can only do 48hz or 60hz, so I just want to set mpv to always use 48hz. A simple line for mpv.config will do. Thank you in advance.

**Comment by Akemi** [comment]
you can't set the refresh rate of you display with mpv.

on linux you can most likely use https://gitlab.com/lvml/mpv-plugin-xrandr
