### ISSUE TITLE
Property when the video is "buffering"

### ISSUE THREAD

**Issue by NADESHIKON** [mpv-player/mpv#8559]
Hello, is there any property value that represents whether the mpv player is currently buffering for the data (like loading in case of online video / livestreams). I've been looking for ``paused-for-cache`` and ``cache-buffering-state`` and they are not what I've been looking for.

**Comment by garoto** [comment]
`demuxer-cache-idle` I guess.

**Comment by NADESHIKON** [comment]
> `demuxer-cache-idle` I guess.

Just tested, it doesn't change value when buffering for either only video or live stream.

**Comment by garoto** [comment]
Ugh, I'm pretty sure I tested it before replying, and while retesting it, I confirm the property does indeed seems to work as advertised: local files will report `${demuxer-cache-idle}` as `no`, and anything from a random http stream as `yes`.

**Comment by garoto** [comment]
Unless you have such internet that filling the default 150MB buffer from `--demuxer-max-bytes` is that quick.

**Comment by NADESHIKON** [comment]
> Ugh, I'm pretty sure I tested before replying, and while retesting it, I confirm the property does indeed seems to work as advertised: local files will report `${demuxer-cache-idle}` as `no`, and anything from a random http stream as `yes`.

I think there's a misunderstanding, I'm trying to detect whether the mpv is currently buffering for more video data instead of detecting whether the source comes from a HTTP stream or local file.

**Comment by NADESHIKON** [comment]
> > Ugh, I'm pretty sure I tested before replying, and while retesting it, I confirm the property does indeed seems to work as advertised: local files will report `${demuxer-cache-idle}` as `no`, and anything from a random http stream as `yes`.
> 
> I think there's a misunderstanding, I'm trying to detect whether the mpv is currently buffering for more video data instead of detecting whether the source comes from a HTTP stream or local file.

Just tested again, the variable changes whenever the cache has finished loading the entire file from online source. However, for the on-fly loading this doesn't work as intended (variable never changes).
![image](https://user-images.githubusercontent.com/20222292/107836801-38f18e80-6d53-11eb-88b2-f75371cb9c1d.png)

**Comment by garoto** [comment]
That's all I have. Carry on.

**Comment by Akemi** [comment]
closing since the question has been answered. please open a new issue or feature request if you need something else besides what is actually provided.
