### ISSUE TITLE
mpv thinks cover is a video track

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8561]
- mpv version: 0.33.0-67-g8121d958ec
- Windows Version:  Windows 7 64bits
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- Graphic Card: No.

Actually in not a failure of mpv, but is something that must change.
If I add a cover (for example image jpg) to a video, mpv thinks this embedded picture is a video track and list it that way.
I reported this to SMplayer and the developer told me it was mpv, I checked and it is correct, it is mpv.

If thist is fixed, mpv must show something like this:
Video --vid=1
Audio --aid=2
Cover --cid=3

Or it can be also Picture --pid=3
But by the moment, mpv thinks the picture inside as a cover is a video track, as I said before.

**Comment by ChrisK2** [comment]
Well, it kiiiind of is a video track, just one with one very long frame. How exactly is this a problem? If you just don't want it to be displayed you can disable it with ```--audio-display=no```.

**Comment by hedgehog90** [comment]
if you check the mpv property "track-list" you'll see the cover art video track is marked with albumart=true, so you can distinguish between 'proper' video tracks and cover art. Makes sense, so I think this should remain the default behaviour.

Sorry to piggyback this issue but there's been an resolved issue issue for months whereby any video track added with the video-add command is interpreted as cover art and only shows 1 frame
Reverting commit 55d7f9d (player: add automatic loading of external cover art files) fixes it.
Seems like every issue I've started is ignored:
https://github.com/mpv-player/mpv/issues/8358

**Comment by Akemi** [comment]
please leave your unrelated ranting out of the issue comments. i doubt we explicitly ignore your issues out of the +600.

**Comment by jimmy-1000** [comment]
All of you think the actual behavior is correct?? other players like MPC or VLC  don't think the cover is a video track. Don't forget mpv is the core of many programs.

![1](https://user-images.githubusercontent.com/78575427/107857518-63dfef00-6df4-11eb-94d4-b4c070e63ce5.jpg)
![2](https://user-images.githubusercontent.com/78575427/107857519-64788580-6df4-11eb-93f4-29d2ba0a2840.jpg)

**Comment by Akemi** [comment]
i think that is perfectly fine. it's a video for mpv and it can also be distinguished via the property. players using libmpv as its core should just check for albumart flag to distinguish between normal video tracks and covers.

**Comment by 7nik** [comment]
for me, mpv not just lists the cover in video tracks but plays the cover image as the default video track *facepalm*
