### ISSUE TITLE
Audio Output devices not available?

### ISSUE THREAD

**Issue by AVRider** [mpv-player/mpv#8564]
I need to include both ASIO and WASAPI "extended" audio output options to play DSF files, natively, with my TEAC DAC. Presently, I can do this with both FB2K (with additional components added) and TEAC HR Player which has its own ASIO USB driver (with various plugins included). Evidently these additional components and plugins are key to accomplishing the above objective in these apps.

If I execute **--audio-device=help** it only produces the default devices which are inadequate. On the other hand, FB2K produces a comprehensive list of devices to choose from (TEAC ASIO USB DRIVER and WASAPI devices ). See below:
![FB2K Device Options](https://user-images.githubusercontent.com/19938478/107886738-ebe6f700-6ecf-11eb-94d5-e0e2e523b4e4.jpg)

I choose one of the device options shown (ASIO or WASAPI) in order to play these DSF files natively. The option chosen is not the default which is **Default : Digital Audio Interface (TEAC USB AUDIO DEVICE)**. This default will only output PCM 192kHz.

With both FB2K and the TEAC HR Player the output is 2.8MHz (DSD64) or 5.6MHz (DSD128) depending on the DSF file.

How do I accomplish adding these other audio output devices? Is there a library which much be included at run time? How would I then execute the **--audio-device=help** command to produce the extended list of options in order to get the required syntax to included in the **--audio-device=name/device** command?

Thank you.

**Comment by Akemi** [comment]
there is nothing you can change about the output. if you need something else, please open a new issue or feature request.
