### ISSUE TITLE
How to use seek by sending process string

### ISSUE THREAD

**Issue by SpringHan** [mpv-player/mpv#8571]
I'm developing a emacs package to play the songs, and I want to use `seek` command. But after trying the commands in the docs, I still can't use it. I send `seek 5 relative` to the `mpv` process, it didn't seek but stopped.  
So could you tell me what's the command of seek for sending to the process?

### Log file
none

**Comment by Akemi** [comment]
that's exactly what the command is. it also works here.

https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst
