### ISSUE TITLE
Video-Sync is causing dropped frames on high framerates.

### ISSUE THREAD

**Issue by Battler624** [mpv-player/mpv#8573]
On build 0.33.0-76-g93066ff12f at my default resolution (1440, 240hz) I see huge dropped amounts of dropped frames to the point of being unwatchable (24fps video, dropping 19 frames in 10 seconds or so) weird thing is that sometimes it happens and sometimes it doesn't. 

I am using the mpv-made-easy config by moodkiller and decided to comment out the config file lines one by one and finally found out that 

#video-sync=display-resample

Is the cause of dropped frames, without it I dropped a single frame over a few minutes.

This issue doesn't happen on my other monitor which is a 1440p, 165hz.

Both displays are running on HDR if it matter and my pc specs are 5900X, 3080, 16GB 3800 (but at 3600, cuz fuck my luck with fclk) CL14 ram

**Comment by CounterPillow** [comment]
thanks for completely ignoring the issue template.

**Comment by CounterPillow** [comment]
Anyway the problem likely is that you are on a g-sync/freesync monitor, where display-resample does not work as it cannot measure refresh rate from vblank timings consistently (since the driver tries to match the refresh rate of mpv and mpv tries to match the refresh rate of the ever-changing vsync interval, leading to a race to the bottom). Thankfully, display-resample is absolutely not required at all on such displays.

**Comment by Battler624** [comment]
> thanks for completely ignoring the issue template.

nothing popped up, I was logged out and when I pressed the new issue button it prompted me to login and after that I was immediately on the writing page, sorry about that.



> Anyway the problem likely is that you are on a g-sync/freesync monitor, where display-resample does not work as it cannot measure refresh rate from vblank timings consistently (since the driver tries to match the refresh rate of mpv and mpv tries to match the refresh rate of the ever-changing vsync interval, leading to a race to the bottom). Thankfully, display-resample is absolutely not required at all on such displays.

I disabled it, thanks for the info and easy to understand explanation :)

**Comment by CounterPillow** [comment]
> nothing popped up, I was logged out and when I pressed the new issue button it prompted me to login and after that I was immediately on the writing page, sorry about that.

Good to know that GitHub still hasn't fixed that bug. It's supposed to make you choose from a list of issue templates, but if you click on new issue while not logged in, GitHub just skips that part.
