### ISSUE TITLE
autoload.lua randomly adding new entries/skipping items

### ISSUE THREAD

**Issue by steponmepls** [mpv-player/mpv#8575]
### Important Information

Provide following Information:
- mpv 0.33.0-76-g93066ff12f
- Windows 10  Pro x64 10.0.18363 Build 18363
- https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps

Let [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) add items to the playlist and then use binds to move back or forward in the playlist.

In order to reproduce this I renamed my config and script folder to something else only to use the autoload.lua script from this repo and the following mpv.conf and input.conf files:

```
# mpv.conf
profile=gpu-hq
keep-open
image-display-duration=inf
```

```
# input.conf
LEFT playlist-prev
RIGHT playlist-next
q  quit
```

### Expected behavior

Files should cycle in alphabetical order and loop from first file once end of playlist is reached.

### Actual behavior

Files are all over the place. Sometime they follow the alphabetical order, sometime they appear to cycle randomly.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/5998864/output.txt)

### Sample files

I added the images used for the test: [test.zip](https://github.com/mpv-player/mpv/files/5998853/test.zip)

This is a video example of what is happening:
https://user-images.githubusercontent.com/63500907/108272947-3a67f000-7173-11eb-8bed-ab52bbead279.mp4

**Comment by pcpeasant** [comment]
Yup I'm also facing the same issue and it's really making this otherwise great video player almost unusable.
Seems like it's not limited to windows either:
https://github.com/mpv-player/mpv/issues/8694

**Comment by Jules-A** [comment]
https://github.com/mpv-player/mpv/commit/4bc6686b6a80bbae78febf97652e2f0841ca396a Didn't fix it for me, in fact it seems to be worse: https://i.imgur.com/tgetQ17.png

**Comment by thebombzen** [comment]
@Jules-A  try this, see if it helps: https://0x0.st/oxde.patch

**Comment by Jules-A** [comment]
> @Jules-A try this, see if it helps: https://0x0.st/oxde.patch

@thebombzen even worse... https://i.imgur.com/04GsAmM.png

In this case The Vision of EscaFlowne is missing episodes so ignore that and the index of Fullmetal Panic increases by 2 since there was 2 uncut versions apparently but they weren't downloaded.
The issue now is it's ordering 1, 3, 4, 2, 5, 3 (duplicate).

**Comment by dyphire** [comment]
> @thebombzen [4bc6686](https://github.com/mpv-player/mpv/commit/4bc6686b6a80bbae78febf97652e2f0841ca396a) Didn't fix it for me, in fact it seems to be worse: https://i.imgur.com/tgetQ17.png

I can't reproduce it. Could you make the steps to reproduce? it would helpful a lot.

**Comment by Jules-A** [comment]
> > @thebombzen [4bc6686](https://github.com/mpv-player/mpv/commit/4bc6686b6a80bbae78febf97652e2f0841ca396a) Didn't fix it for me, in fact it seems to be worse: https://i.imgur.com/tgetQ17.png
> 
> I can't reproduce it. Could you make the steps to reproduce? it would helpful a lot.

Maybe my conf has something to do with it?
<details>
  <summary>Config</summary>

```profile=gpu-hq
hwdec=auto-safe
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
tscale=oversample
video-sync=display-resample
interpolation
cursor-autohide=320
#fullscreen
#gpu-api=vulkan
#vo=gpu-next
snap-window
geometry=2560x1400
no-border
cache=yes
cache-pause-initial=yes
cache-pause-wait=2
cache-secs=480
demuxer-max-bytes=120000KiB
demuxer-readahead-secs=480
prefetch-playlist=yes
volume-max=100
deband=yes
deband-iterations=2
deband-threshold=48
deband-range=18
deband-grain=2
sub-auto=fuzzy
slang=en,enUS,en-US,en-ja
sub-scale=0.5
sub-ass-override=no
save-position-on-quit
script="~~/scripts/autoload.lua"
```
</details>

**Comment by dyphire** [comment]
> Maybe my conf has something to do with it?

Not sure if it is caused by this `prefetch-playlist=yes` option, because I still don't know how to reproduce it.

> As for steps, it doesn't matter if I isolate the series to a different folder and play, it's messed up regardless. Usually I skip to the next video before the file ends up playing. 

How do you play files of series in different directories? If you play by droping the folder, this loading behavior is not controlled by autoload.lua.

**Comment by Jules-A** [comment]
> > Maybe my conf has something to do with it?
> 
> Not sure if it is caused by this `prefetch-playlist=yes` option, because I still don't know how to reproduce it.
> 
> > As for steps, it doesn't matter if I isolate the series to a different folder and play, it's messed up regardless. Usually I skip to the next video before the file ends up playing.
> 
> How do you play files of series in different directories? If you play by droping the folder, this loading behavior is not controlled by autoload.lua.

Currently I have 87 files of shows of a few different series in the same folder. I just double click a file I want to play.

**Comment by dyphire** [comment]
Just for curiosity, this script of  [playlistmanager.lua](https://github.com/jonniek/mpv-playlistmanager/blob/master/playlistmanager.lua) uses the same approach to to avoid loading duplicate files and sorting algorithm.
Would you get the same issue if you used playlistmanager.lua to load files instead of autoload.lua?

If so, you may catch a bug that we haven't found before.

**Comment by Jules-A** [comment]
> Just for curiosity, this script of [playlistmanager.lua](https://github.com/jonniek/mpv-playlistmanager/blob/master/playlistmanager.lua) uses the same approach to to avoid loading duplicate files and sorting algorithm. Would you get the same issue if you used playlistmanager.lua to load files instead of autoload.lua?
> 
> If so, you may catch a bug that we haven't found before.

Okay so... I found the problem... I noticed it when I was trying out the playlistmanager, even though I removed the script loading from my config, both were being loaded with autoload reporting the correct number of files and playlistmanager reporting extra.

Basically the scripts were being automatically loaded in %AppData%\Roaming\mpv\scripts and adding it in config was loading it twice... When I configured mpv years ago I don't think that was the case and guides said to add to config.
The autoload.lua file and manual are no help either as it only provides location for Linux locations. I see now it's mentioned in script wiki but doesn't mention that they will be automatically loaded.

After removing entries from config I was able to get correct behavior. So I don't think it's really a bug (maybe duplicate script loading can be ignored), just a documentation issue.

**Comment by dyphire** [comment]
Ah, anyway, it is enough to find the real reason and solve the issue for you.

**Comment by avih** [comment]
> Basically the scripts were being automatically loaded in %AppData%\Roaming\mpv\scripts and adding it in config was loading it twice... When I configured mpv years ago I don't think that was the case and guides said to add to config.

mpv always loaded all scripts from the "scripts" dir (and even before the script dir existed - when it was called "lua"), unless you run with `--no-config`.

So it's definitely not a new thing.
