### ISSUE TITLE
Use mpv to render to named pipe

### ISSUE THREAD

**Issue by DarianAnjuhal** [mpv-player/mpv#8577]
Hi,

is it possible to render a video stream (for example rtsp) to named pipe and consume it with vlc/libvlc?
Do you have other ideas (maybe without named pipe) to solve the problem?

We recognized that mpv can handle streams and hardware decoding better than vlc.

Is there a example out there?

My script is currently not working:
`mkfifo $NAMED_PIPE
mpv ${LINK} > $NAMED_PIPE`

If I start `vlc $NAMED_PIPE` a mpv player is shown and the vlc is empty.

It would be nice if you guys have some hints/ideas for me?

Greetings Darian

**Comment by hedgehog90** [comment]
You should be able to output the decoded stream to the pipe like this:

```mpv --o=$NAMED_PIPE --of=nut --ovc=rawvideo --oac=pcm_s16le <mediafiles>```

**Comment by DarianAnjuhal** [comment]
Hi @hedgehog90 and thanks for your reply.

Your are right, its seems mpv is decoding to the pipe correctly (I could see at least the data stream using `cat /tmp/stream`). 

` mpv --o=/tmp/stream --of=nut --ovc=rawvideo --oac=pcm_s16le rtsp://$IP/axis-media/media.amp`

But unfortunately its still not working consume the stream with ffplay /tmp/stream or vlc /tmp/stream.

I am not sure how its working under the hood. Maybe you still have ideas.

Thanks a lot!
Darian

**Comment by Akemi** [comment]
since there hasn't been a reply till now, i am closing this.
