### ISSUE TITLE
MPV running on Wayland session of KDE Plasma is partially out of the screen if video resolution is higher than screen resolution

### ISSUE THREAD

**Issue by glaubersm** [mpv-player/mpv#8585]
Hi

I use MPV 0.33.0-4 on Arch Linux running Wayland session of KDE Plasma 5.21 desktop environment.
My screen resolution is 1080p and MPV window is partially out of the screen when I open a 4K video.
This behavior does not occur on X11 session of KDE Plasma.

**Comment by CounterPillow** [comment]
AFAIK this is left up to the window manager/wayland compositor to handle, and KWin behaves differently in this regard on X11 vs. Wayland. Report it to them.

**Comment by glaubersm** [comment]
Done

https://bugs.kde.org/show_bug.cgi?id=433334

Thanks.

**Comment by Dudemanguy** [comment]
Yeah not a bug. It is up to the WM manager to decide what to do with windows larger than the desktop resolution. You can always use the --autofit-larger option if necessary.
