### ISSUE TITLE
sound mixer for 2 audio stream

### ISSUE THREAD

**Issue by mrWhopper** [mpv-player/mpv#8588]
can somebody make sound mixer for 2 selected audio stream with slider to control balance between them? or i can make that with scripting?

**Comment by Akemi** [comment]
you can do that with scripting, though it might a bit complex with on screen gui. there are several examples of gui scripts on our wiki https://github.com/mpv-player/mpv/wiki/User-Scripts

otherwise this isn't something that we will incorporated directly in mpv, the gui part.
