### ISSUE TITLE
Cursor doesn't autohide on fullscreen, if cursor is outside of video window

### ISSUE THREAD

**Issue by CIAvash** [mpv-player/mpv#8589]
### Important Information

Provide following Information:
- mpv version
0.33.0-dirty (Archlinux package: 1:0.33.0-4)
- Linux Distribution and Version
Archlinux (Linux 5.10.16-arch1-1)
- Source of the mpv binary
Archlinux community repo
- If known which version of mpv introduced the problem
no
- Window Manager and version
Bspwm 0.9.10
- GPU driver and version
mesa 20.3.4-1
- Possible screenshot or video of visual glitches
no

### Reproduction steps

Open a video with mpv(with --no-config or without), put the mouse cursor outside the video window. Press `f` to go to fullscreen.

### Expected behavior

Mouse cursor should hide.

### Actual behavior

Mouse cursor is visible on top of the video.

### Log file

https://gist.github.com/CIAvash/d48b62ca8b9ce8f36cffe882f61539d6#file-mpv-log-txt
https://gist.github.com/CIAvash/d48b62ca8b9ce8f36cffe882f61539d6#file-mpv-log-fullscreen-txt

### Additional notes

If the mouse cursor is inside the video window when going to fullscreen, cursor gets hidden.

If I go to fullscreen and move the mouse, the cursor disappears.

If I switch to another Bspwm workspace and switch back to the workspace the video is playing in fullscreen, the cursor disappears.

It seems to be similar to #5151.

**Comment by avih** [comment]
FWIW, win32 behaves correctly in such case.

**Comment by Dudemanguy** [comment]
Are you sure you really want to use the xv vo? Anyways, I tried it on i3 and it worked fine so possibly a bspwm issue?

**Comment by CIAvash** [comment]
I've switched to Wayland and Sway, and don't have this problem here. But from what I remember changing vo wouldn't fix the problem. Maybe it is a bspwm issue.

**Comment by Dudemanguy** [comment]
Guess, I'll close for now. I'd assume that if cursor hiding really was broken on xorg, we'd get a lot more complaints.
