### ISSUE TITLE
sub-pos relative to video

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [mpv-player/mpv#8597]
Currently, sub-pos uses a fixed point in the window. When a video is letterboxed, the subtitle may appear at an awkward position, such as in between the video and the bottom black bar. With an option to make sub-pos be relative to the bottom of the video, the subtitles would always keep a neat distance and look cleaner in all cases. 

### Expected behavior of the wanted feature

sub-pos is positioned relative to the y axis of the video, instead of being positioned at a fixed point in the window.

![Wed Feb 24 18:59:49 -03 2021](https://user-images.githubusercontent.com/11010067/109071623-b95cab80-76d2-11eb-9901-db80bad9e1b4.png)
![Wed Feb 24 19:00:01 -03 2021](https://user-images.githubusercontent.com/11010067/109071645-c083b980-76d2-11eb-959f-3790e1249536.png)

**Comment by hooke007** [comment]
Why not use `--blend-subtitles=video` ?

**Comment by 2V3EvG4LMJFdRe** [comment]
Aaaaah, that's perfect! You've made my day, thanks.

**Comment by LeLobster** [comment]
Is there an alternative to this because using  `--blend-subtitles` scales the subs based on the video resolution.     
The font size is smaller when playing 1080p video compared to a 480p DVD.

**Comment by hooke007** [comment]
`sub-use-margins=no`

**Comment by LeLobster** [comment]
> `sub-use-margins=no`

Awesome, that seems to do exactly what I was looking for, the only downside is that this no longer allows the user to lower the subtitles into the black bar margin in case it is big enough to fit 2 rows of text in their preferred sub font size
