### ISSUE TITLE
How to change the default screenshot output directory ?

### ISSUE THREAD

**Issue by forliuyifei** [mpv-player/mpv#8598]
Sorry I didn't find where is the config file of mpv.

I checked https://askubuntu.com/questions/1000376/changing-screenshot-directory-for-mpv-media-player-in-ubuntu-17-10 
https://www.linuxquestions.org/questions/linux-software-2/how-to-make-mpv-save-screenshot-to-desktop-folder-4175644942/

But `~/.config/mpv` is empty.

Hoping that all the screenshots would output to `~/Pictures/mpv` , waiting for your help, thanks.

**Comment by CounterPillow** [comment]
> But ~/.config/mpv is empty.

Yes. It is. So create a `mpv.conf` in it. Where's the problem?

**Comment by hooke007** [comment]
And it is up to you to create the `mpv.conf` in which folder. https://mpv.io/manual/master/#files

**Comment by forliuyifei** [comment]
> > But ~/.config/mpv is empty.
> 
> Yes. It is. So create a `mpv.conf` in it. Where's the problem?

Thx, it works now. :+1: 

Yet another queston, what should I do to generate screenshots from different movies and output them to `~/Pictures/mpv/movie_title1/` 、`~/Pictures/mpv/movie_title2/` , and etc ? 

I think it looks more elegant in this way, could you plz provide me some advices ?

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-screenshot-template

You can easily find the answer if read the manual.
