### ISSUE TITLE
Support for --vf-command/--af-command from the JSON IPC interface

### ISSUE THREAD

**Issue by tonycpsu** [mpv-player/mpv#8600]
### Expected behavior of the wanted feature

The `--vf-command` parameter supports sending a command to a video filter (and likewise `--af-command` for an audio filter), but I can't see a way to do this from the JSON IPC interface.  The manual says the `vf` IPC command supports `set`, `add`, `toggle`, `remove`, `del`, `clr`, but not `command`.

My use case is updating the text displayed via a `drawtext` filter.  Removing and re-adding the filter with different parameters works, but leads to the text disappearing for a half a second or so while the filters update.

**Comment by varenc** [comment]
I've gotten this to work and the command to use is `vf-command`.  Not `vf` with the parameter `command`, but just  `vf-command` as its own command. You can find in mentioned in [this section](https://mpv.io/manual/master/#input-commands-that-are-possibly-subject-to-change).
