### ISSUE TITLE
Keep current size when dropping files into mpv

### ISSUE THREAD

**Issue by madprops** [mpv-player/mpv#8601]
I have a window next  to mpv where it makes sense to drag and drop files/urls into mpv to change the current video.
The problem is doing this modifies the height and width of mpv, which is not desired.
Apart from using fixed width and height when opening mpv, is there a way to avoid this?
If the only way is using tiling features of a tiling wm then I'm ok with it, but if there's a simple flag or something then that would be better.

**Comment by Dudemanguy** [comment]
Does using `--no-keepaspect-window` accomplish what you want?

**Comment by madprops** [comment]
I'm already using `--no-keepaspect-window`. 
The resize still happens.

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-reset-on-next-file
Though the doc describe won't reset any settings, but I found it will always changes to the default --window-scale if I skip to next video.

**Comment by Akemi** [comment]
i believe there was a script for this. otherwise you could write a script to set the geometry to the current window size to make the window size fixed on the fly.
