### ISSUE TITLE
[feature] use youtube-dl sigfuncs cache

### ISSUE THREAD

**Issue by pirate486743186** [mpv-player/mpv#8602]
### Expected behavior of the wanted feature
when youtube-dl is used, it should use the sigfuncs cache of youtube-dl
So mpv can start a little bit faster. #5808

I'm on ubuntu 18.04, i haven't actually tested the latest mpv, but i can't see "sigfuncs" been mentioned anywhere. If this is already implemented, it will at least appear in the issues.

**Comment by Akemi** [comment]
i just tested it on a few youtube videos and it wrote data to ⁨`~/.cache⁩/⁨youtube-dl⁩/⁨youtube-sigfuncs⁩`. so it apparently works. on a side note, it didn't do it for all videos, but that is something youtube-dl is responsible for.

**Comment by pirate486743186** [comment]
beh... -_-
