### ISSUE TITLE
_set_abort_behavior for libmpv

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#8604]
**[request for a function]**
Randomly I get an assertion error in libmpv, mainly when cleaning resources, I am 99% sure it is my error, but due to the design of the application, I cannot modify the code much. So I would like to ask or request, if it can somehow be made to make libmpv fail silently, for example, by calling [_set_abort_behavior](https://docs.microsoft.com/en-us/previous-versions/e631wekh(v=vs.140)) at the start of libmpv. Can this be done? Thanks a lot

**Comment by Akemi** [comment]
if there is a problem within mpv, it should be fixed. same goes for your app. so no, i don't think this should be done nor is it a good idea.
