### ISSUE TITLE
[Sway/Wayland] - Wayland GPU contexts detect the wrong monitor's Display FPS when in floating + fullscreen

### ISSUE THREAD

**Issue by aqxa1** [mpv-player/mpv#8606]
### Important Information
- mpv-0.33.0-r100 and 0.33.0-88-gd1be8bb606
- Gentoo AMD64
- Gentoo Portage
- Sway git/wlroots git
- Mesa git, AMD RX 6800

### Reproduction steps
In a multi-monitor configuration. In my case, one 85hz monitor, and one 144hz monitor. Issue doesn't apply to X11 contexts through XWayland.

1. Set:
`for_window [app_id="mpv"] floating enable` in Sway's config file and reload Sway config
2. Run video with any Wayland GPU context. E.g. `mpv --no-config --vo=gpu --gpu-api=opengl --gpu-context=wayland <video>`
3. Video should be in a floating window. Check "Display FPS (specified)" in OSD and it should match monitor's FPS
4. Switch to fullscreen with 'F' or with Sway itself, and `Display FPS (specified)` will match the other monitor. In my case, it will say `Display FPS 85.0001 (specified)` despite running on the 144hz monitor. This also applies if I move the window to the second (85hz) monitor, just in reverse (`Display FPS 144.000 (specified)`. 
5. Further verify with `display-resample` which will indicate much increased VSync jitter in the OSD.

### Expected behavior
Display FPS matches monitor FPS on both monitors

### Actual behavior
Display FPS matches FPS of other monitor

### Log file
https://pastebin.com/Nj44yu2T

**Comment by Dudemanguy** [comment]
Could you try git master? Some things regarding surface/monitor detection were refactored since 0.33.

**Comment by aqxa1** [comment]
Just checked, and issue still exists with git.

**Comment by Dudemanguy** [comment]
Hmm, there's really no reason why floating or not should make any difference here. That makes me suspect sway is doing something funny. Guess, I'll have to rig up a test case later and see where the bug is.

**Comment by Dudemanguy** [comment]
Finally got around to trying this and I can't reproduce. The display fps changes per monitor exactly as intended. Floating/tiled/etc. doesn't matter. Didn't have any issues with sway 1.5.1 or git master. Could you try posting a wayland debug log (WAYLAND_DEBUG=1 mpv .... 2> wayland.log)? With wayland debugging enabled, open a video on one screen, move it another screen, and then quit and post it here. Maybe somehow the surface listener is behaving funny or something.

**Comment by Dudemanguy** [comment]
This is a sway bug. It doesn't occur in 1.5.1 but it occurs in git master and only with floating windows. I suspect it's probably something simple like reporting the wrong display fps. I'll try to bisect it.

**Comment by Dudemanguy** [comment]
Upstream issue filed here: swaywm/sway#6080.

**Comment by Dudemanguy** [comment]
Fixed upstream now.
