### ISSUE TITLE
Mpv is not shown in search bar of Deepin OS 

### ISSUE THREAD

**Issue by vladimircores** [mpv-player/mpv#8607]
Video and audio works. But program icon can't be found in Deepin main menu search.

### Important Information

Provide following Information:
- mpv version - 0.29.18-2
- Linux Distribution and Version - Deepin 20.1
- Source of the mpv binary - Deepin App Store

### Reproduction steps
- Install on Deepin
- Search for app in main menu
- Observe nothing in there

### Expected behavior
Program shown in search from menu bar

### Actual behavior
![image](https://user-images.githubusercontent.com/442111/109481161-7cefcd80-7a8d-11eb-95eb-20b042ba5ab0.png)

### Log file
No log

**Comment by avih** [comment]
mpv is not responsible for Deepin OS search bar functionality. You should file an issue with Deepin OS.
