### ISSUE TITLE
AV1 hwdec vaapi visual glitches on Intel Tiger Lake Xe Graphics

### ISSUE THREAD

**Issue by rmkimathi** [mpv-player/mpv#8611]
### I am not sure if the problem is from ffmpeg, mpv, or intel-media-va-driver-non-free?

- mpv version: mpv 0.33.0-91-g0888e53fc4
- Linux Distribution and Version: Ubuntu 21.04 / 5.10.0-14-generic
- Source of the mpv binary: mpv-build
- If known which version of mpv introduced the problem
- Window Manager and version: Wayland / GNOME 3.38.3
- GPU driver and version: VA-API version: 1.11 (libva 2.10.0) / iHD driver 21.1.1
- Possible screenshot or video of visual glitches

### Log file
$ mpv av1file.mp4 -v
```
[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).
[vo/gpu/vaapi-egl] failed to retrieve libavutil frame constraints
```

### Sample screenshot

![mpv](https://user-images.githubusercontent.com/13484308/109706894-8cb10400-7baa-11eb-9c85-c4c5e6186444.png)

```

mpv --version
mpv 0.33.0-91-g0888e53fc4 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Mar  2 18:20:22 EAT 2021
FFmpeg library versions:
   libavutil       56.66.100
   libavcodec      58.128.100
   libavformat     58.69.100
   libswscale      5.8.100
   libavfilter     7.107.100
   libswresample   3.8.100
FFmpeg version: N-101368-g2fc309e699
```

```
vainfo
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.11 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```

**Comment by jeeb** [comment]
1. Do you get similar issues with just `ffmpeg.c` with `-hwaccel vaapi` ? ([docs](https://trac.ffmpeg.org/wiki/Hardware/VAAPI))
2. Do you get similar issues if you ´ffmpeg -v verbose -i INPUT.mp4 -map 0:v -c copy out.mkv` and play with the mpv Matroska demuxer?

That version of FFmpeg does seem to contain my fixes for MP4/Matroska handling of AV1 http://git.videolan.org/?p=ffmpeg.git;a=commit;h=4688017d9a1c2633c5888de5a0580d29e7680d54 (and the previous commits in that set).

This change did not yet get merged since people didn't want to change what the exported extradata should look like https://patchwork.ffmpeg.org/project/ffmpeg/patch/20201123191046.28887-6-jeebjp@gmail.com/ . You could check if this makes any difference with MP4 files.

**Comment by rmkimathi** [comment]
>     1. Do you get similar issues with just `ffmpeg.c` with `-hwaccel vaapi` ? ([docs](https://trac.ffmpeg.org/wiki/Hardware/VAAPI))
> 
>     2. Do you get similar issues if you `ffmpeg -v verbose -i INPUT.mp4 -map 0:v -c copy out.mkv` and play with the mpv Matroska demuxer?
> 
> 
> That version of FFmpeg does seem to contain my fixes for MP4/Matroska handling of AV1 http://git.videolan.org/?p=ffmpeg.git;a=commit;h=4688017d9a1c2633c5888de5a0580d29e7680d54 (and the previous commits in that set).
> 
> This change did not yet get merged since people didn't want to change what the exported extradata should look like https://patchwork.ffmpeg.org/project/ffmpeg/patch/20201123191046.28887-6-jeebjp@gmail.com/ . You could check if this makes any difference with MP4 files.

Converting to mkv does not fix. The other pointers do not know how to use them. Thanks

**Comment by jeeb** [comment]
Attempt to apply the patch linked to FFmpeg you are utilzing for mpv, see if you get any difference. that should change the extradata passed on by the MP4 reader, although that is unlikely to change anything if remux to matroska didn't work.

Please check if you're getting similar results from ffmpeg.c with vaapi.

**Comment by rmkimathi** [comment]
> Attempt to apply the patch linked to FFmpeg you are utilzing for mpv, see if you get any difference. that should change the extradata passed on by the MP4 reader, although that is unlikely to change anything if remux to matroska didn't work.
> 
> Please check if you're getting similar results from ffmpeg.c with vaapi.

Compiled ffmpeg with custom commit 4688017d9a1c2633c5888de5a0580d29e7680d54 (N-99987-g4688017d9a) but visual glithes remain with av1 hwdec vaapi both mkv and mp4 containers.

```
mpv 0.33.0-92-g99968e1ce5 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Wed Mar  3 02:31:16 EAT 2021
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: N-99987-g4688017d9a
```

**Comment by rmkimathi** [comment]
## Update:
I converted a video file using libsvtav1 and mpv hwdec vaapi av1 was able to play flawless. ... All test videos downloaded online will only software decode using libdav1d

**Comment by jeeb** [comment]
Can you post the results of one of those test videos with ffprobe?
```
ffprobe -v verbose -i INPUT.mp4
```
And then one of the files you generated?

**Comment by rmkimathi** [comment]
> Can you post the results of one of those test videos with ffprobe?
> 
> ```
> ffprobe -v verbose -i INPUT.mp4
> ```
> 
> And then one of the files you generated?

### libsvtav1
```
[libdav1d @ 0x55e9cfda1300] libdav1d 0.8.2
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Tiger Lake SoC Architecture Explainer Intel Technology (svt).mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomav01iso2mp41
    creation_time   : 2021-03-03T06:47:06.000000Z
    encoder         : Lavf58.69.100
  Duration: 00:04:07.06, start: 0.000000, bitrate: 824 kb/s
  Stream #0:0(und): Video: av1 (Main), 1 reference frame (av01 / 0x31307661), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 630 kb/s, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      creation_time   : 2021-03-03T06:47:06.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

### Netflix sample
```
[libdav1d @ 0x557ebfe4c400] libdav1d 0.8.2
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Chimera-AV1-8bit-1920x1080-6736kbps.mp4':
  Metadata:
    major_brand     : iso4
    minor_version   : 1
    compatible_brands: iso4av01
    creation_time   : 2018-08-31T01:00:56.000000Z
  Duration: 00:06:12.41, start: 0.000000, bitrate: 6734 kb/s
  Stream #0:0(und): Video: av1 (Main), 1 reference frame (av01 / 0x31307661), yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], 6733 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 24k tbc (default)
    Metadata:
      creation_time   : 2018-08-31T01:00:56.000000Z
      handler_name    : ivf@GPAC0.7.2-DEV-rev654-gb6f7409ce-github_master
      vendor_id       : [0][0][0][0]
[libdav1d @ 0x557ebfe52e80] libdav1d 0.8.2
[AVIOContext @ 0x557ebfe53400] Statistics: 98387 bytes read, 2 seeks
```

### YouTube sample
```
[libdav1d @ 0x562995319380] libdav1d 0.8.2
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'AV1 - NORWAY 8K.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomav01iso2mp41
    encoder         : Lavf58.60.100
  Duration: 00:03:33.23, start: 0.000000, bitrate: 1686 kb/s
  Stream #0:0(und): Video: av1 (Main), 1 reference frame (av01 / 0x31307661), yuv420p(tv, smpte170m/bt709/smpte170m), 1920x1080 [SAR 1:1 DAR 16:9], 1552 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
```

**Comment by rmkimathi** [comment]
@jeeb 

The AV1 hwdec vaapi video corruption still exists. Were you able to diagnose the culprit? Is it a driver bug or ffmpeg bug?

**Comment by jeeb** [comment]
@rmkimathi 
Unfortunately, I have no insight into AV1 VAAPI since I have no new enough hardware :)

This could be an issue anywhere between the driver or FFmpeg.

**Comment by rmkimathi** [comment]
@jeeb 

I get you. I hope @intel can be providing developers with hardware in future. I am just an advanced user who likes intel CPUs and purchased the TGL to test out AV1 hw decode.

I also submitted bug report to them ( https://github.com/intel/media-driver/issues/1155 )

**Comment by rmkimathi** [comment]
A fix has been found in ffmpeg.

https://github.com/intel/media-driver/issues/1155

**Comment by Akemi** [comment]
since it's an ffmpeg upstream problem, i will close this issue.
