### ISSUE TITLE
Allow for different cli flags and subsequent behaviors for different videos when creating a playlist

### ISSUE THREAD

**Issue by arikanev** [mpv-player/mpv#8612]
### Expected behavior of the wanted feature

`mpv --fs vid1 --fs --sid=no vid2`

## Vid 1 should have captions enabled, vid 2 should have them disabled. Both should be in a playlist! And both should full screen - how to make that work where flags are enabled on the videofile specified directly after them?

I don't want to keep reopening a video player for videos with different behaviors

**Comment by Akemi** [comment]
look at the per file option https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst#per-file-options
