### ISSUE TITLE
Reset gamma not woking with self-comnpiled mpv

### ISSUE THREAD

**Issue by andysendo** [mpv-player/mpv#8615]
reset gamma none-zero value by command line --gamma  param or gui 5/6 key only show blue window, reset contrast/brightness works fine. older vsersion installed from repository gamma control works fine.

so what hedaer/lib is requilred?

output errors:
[vo/gpu/opengl] fragment shader source:
[vo/gpu/opengl] [  1] #version 440
[vo/gpu/opengl] [  2] #define tex1D texture
[vo/gpu/opengl] [  3] #define tex3D texture
[vo/gpu/opengl] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[vo/gpu/opengl] [  5] out vec4 out_color;
[vo/gpu/opengl] [  6] in vec2 texcoord0;
[vo/gpu/opengl] [  7] in vec2 texcoord1;
[vo/gpu/opengl] [  8] layout(std140, binding=0) uniform UBO {
[vo/gpu/opengl] [  9] layout(offset=0) mat3 colormatrix;
[vo/gpu/opengl] [ 10] layout(offset=48) vec3 colormatrix_c;
[vo/gpu/opengl] [ 11] layout(offset=60) float user_gamma;
[vo/gpu/opengl] [ 12] layout(offset=64) vec3 src_luma;
[vo/gpu/opengl] [ 13] layout(offset=80) vec3 dst_luma;
[vo/gpu/opengl] [ 14] layout(offset=96) vec2 texture_size0;
[vo/gpu/opengl] [ 15] layout(offset=112) mat2 texture_rot0;
[vo/gpu/opengl] [ 16] layout(offset=144) vec2 texture_off0;
[vo/gpu/opengl] [ 17] layout(offset=152) vec2 pixel_size0;
[vo/gpu/opengl] [ 18] layout(offset=160) vec2 texture_size1;
[vo/gpu/opengl] [ 19] layout(offset=176) mat2 texture_rot1;
[vo/gpu/opengl] [ 20] layout(offset=208) vec2 texture_off1;
[vo/gpu/opengl] [ 21] layout(offset=216) vec2 pixel_size1;
[vo/gpu/opengl] [ 22] };
[vo/gpu/opengl] [ 23] uniform sampler2D texture0;
[vo/gpu/opengl] [ 24] uniform sampler2D texture1;
[vo/gpu/opengl] [ 25] void main() {
[vo/gpu/opengl] [ 26] vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
[vo/gpu/opengl] [ 27] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[vo/gpu/opengl] [ 28] color.gb = 1.000000 * vec4(texture(texture1, texcoord1)).rg;
[vo/gpu/opengl] [ 29] color = color.rgbr;
[vo/gpu/opengl] [ 30] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/gpu/opengl] [ 31] color.a = 1.0;
[vo/gpu/opengl] [ 32] color.rgb = clamp(color.rgb, 0.0, 1.0);
[vo/gpu/opengl] [ 33] color.rgb = pow(color.rgb, vec3(user_gamma));
[vo/gpu/opengl] [ 34] // color mapping
[vo/gpu/opengl] [ 35] color.rgb *= vec3(1.000000);
[vo/gpu/opengl] [ 36] color.rgb *= vec3(1.000000);
[vo/gpu/opengl] [ 37] out_color = color;
[vo/gpu/opengl] [ 38] }
[vo/gpu/opengl] fragment shader compile log (status=0):
[vo/gpu/opengl] 0:11(25): error: layout qualifier offset overlaps previous member
[vo/gpu/opengl] 
[vo/gpu/opengl] shader link log (status=0): error: linking with uncompiled/unspecialized shader

**Comment by CounterPillow** [comment]
post a full log file please so we can see more information about your particular opengl implementation

**Comment by andysendo** [comment]
[cplayer] Command line options: '--gamma' '1' '-v' 'test.flv'
[cplayer] mpv 0.31.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sat Jan 18 14:42:16 UTC 2020
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.31.100
[cplayer]    libavcodec      58.54.100
[cplayer]    libavformat     58.29.100
[cplayer]    libswscale      5.5.100
[cplayer]    libavfilter     7.57.100
[cplayer]    libswresample   3.5.100
[cplayer] ffmpeg version: 4.2.2
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --disable-debug-build
[cplayer] List of enabled features: aligned_alloc alsa asm atomics build-date cplayer cplugins drm drmprime egl egl-drm egl-helpers egl-x11 fchmod ffmpeg gbm gbm.h gl gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv lcms2 libass libass-osd libav-any libavcodec libavdevice libavutil libdl libm librt linux-fstatfs memfd_create optimize oss-audio posix posix-or-mingw posix-spawn posix-spawn-native pthreads stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-x-egl vaapi-x11 vt.h x11 xv zlib
[cplayer] Reading config file /usr/etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/jiangyd/.config/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'vo' = 'gpu' (flags = 4)
[cplayer] Setting option 'hwdec' = 'auto' (flags = 4)
[cplayer] Setting option 'geometry' = '50%:0%' (flags = 4)
[cplayer] Setting option 'autofit' = '95%' (flags = 4)
[cplayer] Setting option 'slang' = 'zh,zho,chi' (flags = 4)
[cplayer] Setting option 'alang' = 'en,eng' (flags = 4)
[cplayer] Setting option 'sub-auto' = 'fuzzy' (flags = 4)
[cplayer] Setting option 'contrast' = '25' (flags = 4)
[cplayer] Setting option 'brightness' = '8' (flags = 4)
[cplayer] Setting option 'gamma' = '1' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[file] Opening /home/jiangyd/.config/mpv/input.conf
[input] Parsing input config file /home/jiangyd/.config/mpv/input.conf
[input] Input config file /home/jiangyd/.config/mpv/input.conf parsed: 11 binds
[file] Opening test.flv
[demux] Trying demuxers for level=normal.
[lavf] Found 'flv' at score=100 size=2048.
[lavf] avformat_find_stream_info() finished after 98304 bytes.
[demux] Detected file format: flv (libavformat)
[cplayer] Opening done: test.flv
[find_files] Loading external files in .
[lavf] select track 0
[lavf] select track 1
[cplayer]  (+) Video --vid=1 (h264 736x340 25.000fps)
[cplayer]  (+) Audio --aid=1 (aac 2ch 44100Hz)
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'x11egl'
[vo/gpu/x11] X11 opening display: :0
[vo/gpu/x11] Display 0 (HDMI-2): [0, 0, 1920, 1080] @ 60.000000 FPS
[vo/gpu/x11] Current display FPS: 60.000000
[vo/gpu/opengl] EGL_VERSION=1.4
[vo/gpu/opengl] EGL_VENDOR=Mesa Project
[vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[vo/gpu/opengl] Trying to create Desktop OpenGL context.
[vo/gpu/opengl] Choosing visual EGL config 0x3, visual ID 0x21
[vo/gpu/opengl] GL_VERSION='4.5 (Core Profile) Mesa 18.3.6'
[vo/gpu/opengl] Detected desktop OpenGL 4.5.
[vo/gpu/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/gpu/opengl] GL_RENDERER='Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) '
[vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.50'
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 60.000000 FPS for display sync.
[vd] Container reported FPS: 25.000000
[vd] Codec list:
[vd]     h264 - (null)
[vd]     h264_v4l2m2m (h264) - (null)
[vd] Opening decoder h264
[vd] Looking at hwdec h264-vaapi...
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu/vaapi-egl] using VAAPI EGL interop
[vo/gpu/vaapi-egl] Trying to open a x11 VA display...
[vo/gpu/vaapi-egl/vaapi] libva: VA-API version 1.4.0
[vo/gpu/vaapi-egl/vaapi] libva: va_getDriverName() returns 0
[vo/gpu/vaapi-egl/vaapi] libva: User requested driver 'iHD'
[vo/gpu/vaapi-egl/vaapi] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
[vo/gpu/vaapi-egl/vaapi] libva: Found init function __vaDriverInit_1_4
[vo/gpu/vaapi-egl/vaapi] libva: va_openDriver() returns 0
[vo/gpu/vaapi-egl/vaapi] Initialized VAAPI: version 1.4
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).
[vo/gpu/vaapi-egl] failed to retrieve libavutil frame constraints
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] vaExportSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] Supported formats:
[vo/gpu/vaapi-egl]  nv12
[vo/gpu/vaapi-egl]  yuv420p
[vo/gpu/vaapi-egl]  rgba
[vo/gpu/vaapi-egl]  p010
[vo/gpu/vaapi-egl]  gray
[vo/gpu] Loading hwdec driver 'drmprime-drm'
[vo/gpu/drmprime-drm] Failed to retrieve DRM fd from native display.
[vo/gpu] Loading failed.
[vd] Trying hardware decoding via h264-vaapi.
[vd] Selected codec: h264 ((null))
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     aac - (null)
[ad]     aac_fixed (aac) - (null)
[ad] Opening decoder aac
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: aac ((null))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[af] [in] 44100Hz stereo 2ch floatp
[af] [userspeed] 44100Hz stereo 2ch floatp
[af] [userspeed] (disabled)
[af] [convert] 44100Hz stereo 2ch floatp
[vd] Pixel formats supported by decoder: vaapi_vld yuv420p
[vd] Codec profile: unknown (0x64)
[vd] Requesting pixfmt 'vaapi_vld' from decoder.
[vd] Using hardware decoding (vaapi).
[vd] Decoder format: 736x340 [737:736] vaapi[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264
[vf] [in] 736x340 [737:736] vaapi[nv12] bt.601/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 736x340 [737:736] vaapi[nv12] bt.601/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] (disabled)
[vf] [autorotate] 736x340 [737:736] vaapi[nv12] bt.601/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 736x340 [737:736] vaapi[nv12] bt.601/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 736x340 [737:736] vaapi[nv12] bt.601/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[ao] Trying audio driver 'alsa'
[ao/alsa] requested format: 44100 Hz, stereo channels, floatp
[ao/alsa] using ALSA version: 1.1.8
[ao/alsa] opening device 'default'
[ao/alsa] trying format float/14
[ao/alsa] channel map reported by ALSA: FL FR
[ao/alsa] which we understand as: stereo
[ao/alsa] which is what we requested.
[ao/alsa] hw pausing supported: no
[ao/alsa] buffersize: 5120 samples
[ao/alsa] period size: 1024 samples
[ao/alsa] device buffer: 5120 samples.
[ao/alsa] using soft-buffer of 9600 samples.
[cplayer] AO: [alsa] 48000Hz stereo 2ch float
[cplayer] AO: Description: ALSA audio output
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 44100Hz stereo floatp -> 48000Hz stereo float
[af] [out] 48000Hz stereo 2ch float
[cplayer] VO: [gpu] 736x340 => 737x340 vaapi[nv12]
[cplayer] VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 736x340 [737:736] vaapi[nv12] bt.601/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu/x11] not waiting for MapNotify
[vo/gpu] Resize: 1822x841
[vo/gpu] Window size: 1822x841 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 736x340 (737:736)
[vo/gpu] Video display: (0, 0) 736x340 -> (0, 0) 1822x840
[vo/gpu] Video scale: 2.475543/2.470588
[vo/gpu] OSD borders: l=0 t=0 r=0 b=1
[vo/gpu] Video borders: l=0 t=0 r=0 b=1
[vo/gpu] Reported display depth: 8
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu/opengl] fragment shader source:
[vo/gpu/opengl] [  1] #version 440
[vo/gpu/opengl] [  2] #define tex1D texture
[vo/gpu/opengl] [  3] #define tex3D texture
[vo/gpu/opengl] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[vo/gpu/opengl] [  5] out vec4 out_color;
[vo/gpu/opengl] [  6] in vec2 texcoord0;
[vo/gpu/opengl] [  7] in vec2 texcoord1;
[vo/gpu/opengl] [  8] layout(std140, binding=0) uniform UBO {
[vo/gpu/opengl] [  9] layout(offset=0) mat3 colormatrix;
[vo/gpu/opengl] [ 10] layout(offset=48) vec3 colormatrix_c;
[vo/gpu/opengl] [ 11] layout(offset=60) float user_gamma;
[vo/gpu/opengl] [ 12] layout(offset=64) vec3 src_luma;
[vo/gpu/opengl] [ 13] layout(offset=80) vec3 dst_luma;
[vo/gpu/opengl] [ 14] layout(offset=96) vec2 texture_size0;
[vo/gpu/opengl] [ 15] layout(offset=112) mat2 texture_rot0;
[vo/gpu/opengl] [ 16] layout(offset=144) vec2 texture_off0;
[vo/gpu/opengl] [ 17] layout(offset=152) vec2 pixel_size0;
[vo/gpu/opengl] [ 18] layout(offset=160) vec2 texture_size1;
[vo/gpu/opengl] [ 19] layout(offset=176) mat2 texture_rot1;
[vo/gpu/opengl] [ 20] layout(offset=208) vec2 texture_off1;
[vo/gpu/opengl] [ 21] layout(offset=216) vec2 pixel_size1;
[vo/gpu/opengl] [ 22] };
[vo/gpu/opengl] [ 23] uniform sampler2D texture0;
[vo/gpu/opengl] [ 24] uniform sampler2D texture1;
[vo/gpu/opengl] [ 25] void main() {
[vo/gpu/opengl] [ 26] vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
[vo/gpu/opengl] [ 27] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[vo/gpu/opengl] [ 28] color.gb = 1.000000 * vec4(texture(texture1, texcoord1)).rg;
[vo/gpu/opengl] [ 29] color = color.rgbr;
[vo/gpu/opengl] [ 30] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/gpu/opengl] [ 31] color.a = 1.0;
[vo/gpu/opengl] [ 32] color.rgb = clamp(color.rgb, 0.0, 1.0);
[vo/gpu/opengl] [ 33] color.rgb = pow(color.rgb, vec3(user_gamma));
[vo/gpu/opengl] [ 34] // color mapping
[vo/gpu/opengl] [ 35] color.rgb *= vec3(1.000000);
[vo/gpu/opengl] [ 36] color.rgb *= vec3(1.000000);
[vo/gpu/opengl] [ 37] out_color = color;
[vo/gpu/opengl] [ 38] }
[vo/gpu/opengl] fragment shader compile log (status=0):
[vo/gpu/opengl] 0:11(25): error: layout qualifier offset overlaps previous member
[vo/gpu/opengl] 
[vo/gpu/opengl] shader link log (status=0): error: linking with uncompiled/unspecialized shader
[cplayer] first video frame after restart shown
[cplayer] audio sync: sync_to_video=1, offset=-0.080000
[cplayer] starting audio playback
[cplayer] playback restart complete @ 0.080000
[vo/gpu/x11] Disabling screensaver.
[vo/gpu/x11] Disabling screensaver failed (-1). Make sure the xdg-screensaver script is installed.
[cplayer] EOF code: 5  
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[ao/alsa] draining...
[vo/gpu/x11] Enabling screensaver.

**Comment by Akemi** [comment]
please open a proper issue with all the info we ask for.
