### ISSUE TITLE
No GPU usage when using real-time upscaling shaders.

### ISSUE THREAD

**Issue by RandomAccountt** [mpv-player/mpv#8616]
### Important Information

Provide following Information:
Using latest shinchiro build.
Windows version:
Edition	Windows 10 Home
Version	20H2
Installed on	‎12/‎09/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

Graphics card: GTX 1650
### Reproduction steps

Running a video with GLSL shaders (https://github.com/bloc97/Anime4K) with config:

```profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
 

glsl-shaders="~~/shaders/Anime4K_Upscale_CNN_UL_x2_Denoise.glsl;~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_DarkLines_HQ.glsl;~~/shaders/Anime4K_ThinLines_HQ.glsl;~~/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"
```
### Expected behaviour
Video plays smoothly with GPU being used for upscaling.

### Actual behavior
Video extremely slow, less than 1 fps, GPU usage spikes in task manager every few seconds but is otherwise 0%. CPU usage at around 25%.

### Log file

Not sure how to generate a log file on windows.

Thanks!

**Comment by hooke007** [comment]
In mpv.conf
`log-file="~~desktop/mpv.log"`

**Comment by RandomAccountt** [comment]
[mpv.log](https://github.com/mpv-player/mpv/files/6076766/mpv.log)

Thanks

**Comment by haasn** [comment]
Looks like it's trying to compile the shader every single frame.

**Comment by RandomAccountt** [comment]
Oh no. What's the fix?

**Comment by butterw** [comment]
is --gpu-shader-cache-dir set to a folder with write access ?

**Comment by RandomAccountt** [comment]
This fixed the issue. Thanks, much appreciated.
