### ISSUE TITLE
Feature: add a menu to paste URLs or file paths into

### ISSUE THREAD

**Issue by sauce420** [mpv-player/mpv#8617]
### Expected behavior of the wanted feature
The ability to paste links into a box instead of having to drag them, which is slightly awkward.
I think it would be easier to have a small menu inside mpv when opened without a file to paste links or file paths into, although it could ruin the minimal aesthetic. If this has already been requested, I'll delete this.

**Comment by zc62** [comment]
https://github.com/Eisa01/mpv-scripts#smartcopypaste-script
https://github.com/mpv-player/mpv/wiki/User-Scripts

**Comment by sauce420** [comment]
thanks, I'll try this now.
