### ISSUE TITLE
mpv error in a login shell

### ISSUE THREAD

**Issue by anishmittal2020** [mpv-player/mpv#8618]
### Important Information

Provide following Information:
- mpv version

$ mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.4-1ubuntu0.1

- Linux Distribution and Version: Ubuntu 20.04.2
- Source of the mpv binary: apt
- If known which version of mpv introduced the problem: Version: 0.32.0-1ubuntu1
- Window Manager and version
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

I have created another user called as `secure` and added it to the groups `video` and `audio`. When I am logged into Ubuntu with my main user `Happy`. And I do `su --login secure` and then do ` \mpv --fs --no-resume-playback --shuffle "/home/happy/Documents"`, then I get errors (as shown below). This works fine if I do `su secure` i.e. a non login shell. 

### Expected behavior

Be able to run the video

### Actual behavior

```
$ \mpv --fs --no-resume-playback --shuffle "/home/nikhil/Documents"

[file] This is a directory - adding to playlist.
Playing: /home/happy/Documents/Secure/Stuff.mp4
 (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
File tags:
 Artist: Only
 Album: 
 Comment: Only
 Date: 0
 Genre: 
 Title: Stuff.mp4
 Track: 0
[vo/sdl] SDL_Init failed
Error opening/initializing the selected video_out (--vo) device.
Video: no video
```

## Question

How can I avoid this error which occurs in a login shell but not in a non-login shell?

**Comment by CounterPillow** [comment]
Please post a full log file as generated by `--log-file`, as the issue template asks. That way we can see what context probing fails.

**Comment by avih** [comment]
@anishmittal2020 any chance you could post the actual issue and solution for the benefit of others?

**Comment by anishmittal2020** [comment]
When using a  login shell to switch user, we need to execute 'export DISPLAY=0.0'.

This is not needed for non-login shell as that inherits the environment.
