### ISSUE TITLE
mpv playback video freeze in onedrive

### ISSUE THREAD

**Issue by yubanmeiqin9048** [mpv-player/mpv#8619]
I use rclone to mount onedrive in windows10 and use MPV to play the video in it. It will freeze during playback, but it will not be like this when playing with MPC-BE.

**Comment by yubanmeiqin9048** [comment]
mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv 0.33.0-88-gd1be8bb606 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Feb 28 09:25:17 +08 2021
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.66.100
[cplayer]    libavcodec      58.126.100
[cplayer]    libavformat     58.68.100
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.107.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: git-2021-02-28-85ab9deb
[cplayer]
[cplayer] Configuration: /home/shinchiro/build64/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-sdl2 --enable-libarchive --enable-libbluray --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-spirv-cross --enable-vulkan --enable-vapoursynth --prefix=/home/shinchiro/build64/install/mingw
[cplayer] List of enabled features: asm build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vulkan wasapi win32-desktop win32-internal-pthreads zimg zlib
[cplayer] Reading config file D:/Program Files/mpv/portable_config/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'vo' = 'gpu' (flags = 4)
[cplayer] Setting option 'gpu-api' = 'd3d11' (flags = 4)
[cplayer] Setting option 'hwdec' = 'd3d11va-copy' (flags = 4)
[cplayer] Setting option 'hwdec-codecs' = 'all' (flags = 4)
[cplayer] Setting option 'hidpi-window-scale' = 'no' (flags = 4)
[cplayer] Setting option 'autofit-larger' = '80%x80%' (flags = 4)
[cplayer] Setting option 'autofit-smaller' = '50%x50%' (flags = 4)
[cplayer] Setting option 'keep-open' = 'yes' (flags = 4)
[cplayer] Setting option 'hr-seek-framedrop' = 'no' (flags = 4)
[cplayer] Setting option 'save-position-on-quit' = 'no' (flags = 4)
[cplayer] Setting option 'demuxer-max-bytes' = '100MiB' (flags = 4)
[cplayer] Setting option 'osd-on-seek' = 'msg-bar' (flags = 4)
[cplayer] Setting option 'osd-blur' = '0' (flags = 4)
[cplayer] Setting option 'osd-bar-w' = '100' (flags = 4)
[cplayer] Setting option 'osd-bar-h' = '2' (flags = 4)
[cplayer] Setting option 'osd-bar-align-y' = '-1' (flags = 4)
[cplayer] Setting option 'osd-border-size' = '1' (flags = 4)
[cplayer] Setting option 'osd-fractions' = '' (flags = 4)
[cplayer] Setting option 'osd-playing-msg' = '${filename}' (flags = 4)
[cplayer] Setting option 'osd-duration' = '1000' (flags = 4)
[cplayer] Setting option 'ao' = 'wasapi' (flags = 4)
[cplayer] Setting option 'audio-file-auto' = 'fuzzy' (flags = 4)
[cplayer] Setting option 'volume' = '100' (flags = 4)
[cplayer] Setting option 'icc-profile-auto' = '' (flags = 4)
[cplayer] Setting option 'icc-cache-dir' = '~~/icc_cache' (flags = 4)
[cplayer] Setting option 'video-sync' = 'display-resample' (flags = 4)
[cplayer] Setting option 'video-sync-max-video-change' = '5' (flags = 4)
[cplayer] Setting option 'interpolation' = '' (flags = 4)
[cplayer] Setting option 'tscale' = 'oversample' (flags = 4)
[cplayer] Setting option 'scale' = 'ewa_lanczossharp' (flags = 4)
[cplayer] Setting option 'dscale' = 'mitchell' (flags = 4)
[cplayer] Setting option 'dither-depth' = 'auto' (flags = 4)
[cplayer] Setting option 'deband' = '' (flags = 4)
[cplayer] Setting option 'gpu-shader-cache-dir' = '~~/shaders_cache' (flags = 4)
[cplayer] Setting option 'load-scripts' = 'yes' (flags = 4)
[cplayer] Setting option 'glsl-shaders' = '~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/shaders/Anime4K_DarkLines_HQ.glsl;~~/shaders/Anime4K_ThinLines_HQ.glsl;~~/shaders/FSRCNNX_x2_8-0-4-1_LineArt.glsl' (flags = 4)
[cplayer] Setting option 'glsl-shaders-append' = '~~/shaders/SSimDownscaler.glsl' (flags = 4)
[cplayer] Setting option 'sub-auto' = 'fuzzy' (flags = 4)
[cplayer] Setting option 'sub-file-paths' = 'subs;subtitles;字幕;C:/字幕库' (flags = 4)
[cplayer] Setting option 'slang' = 'chs,sc,zh,chi,zho' (flags = 4)
[cplayer] Setting option 'sub-ass-force-margins' = 'yes' (flags = 4)
[cplayer] Setting option 'screenshot-format' = 'png' (flags = 4)
[cplayer] Setting option 'screenshot-tag-colorspace' = 'yes' (flags = 4)
[cplayer] Setting option 'screenshot-template' = 'MPV-%P-N%n' (flags = 4)
[cplayer] Setting option 'screenshot-directory' = '~~desktop/' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[ifo_dvdnav] Opening D:/Program Files/mpv/portable_config/input.conf
[bdmv/bluray] Opening D:/Program Files/mpv/portable_config/input.conf
[file] Opening D:/Program Files/mpv/portable_config/input.conf
[input] Parsing input config file D:/Program Files/mpv/portable_config/input.conf
[input] Input config file D:/Program Files/mpv/portable_config/input.conf parsed: 16 binds
[cplayer] mpv 0.33.0-88-gd1be8bb606 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Feb 28 09:25:17 +08 2021
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.66.100
[cplayer]    libavcodec      58.126.100
[cplayer]    libavformat     58.68.100
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.107.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: git-2021-02-28-85ab9deb
[cplayer]
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer]
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer]
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer]
[stats] Opened config file script-opts/stats.conf.
[auto_profiles] Re-evaluating auto profile HDR2SDR
[console] Opened config file script-opts/console.conf.
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1

**Comment by Akemi** [comment]
please file a proper issue and not a question, and fill out all the info we request.
