### ISSUE TITLE
Semi-random freeze of several seconds 

### ISSUE THREAD

**Issue by williamAlhant** [mpv-player/mpv#8622]
### Important Information

- mpv version : 0.33.0-56-g3e175dff4a according to log
- Windows Version : Windows 10

### Reproduction steps

Sometimes (once in 30 minutes or so), the playback freezes for several seconds. It seems random and I don't know how to reproduce it other than waiting for it to happen.
I have enabled logging to get more info when it happens. I am attaching the last log of when it happened.
I think the log corresponding to the freeze is this one : 
> [7557.832][v][cplayer] Enter buffering (buffer went from 100% -> 6%) [0.068000s].

It happens on my laptop, I think this has not occurred on my desktop.

### Log file

[http://0x0.st/-PJv.txt](http://0x0.st/-PJv.txt)

**Comment by CounterPillow** [comment]
You're playing a local file, so cache is off by default. If you enable the cache with `--cache=yes`, does the problem disappear? I'm asking because I know this helps in situations where the drive is overloaded and not answering reads. You might also want to check the drive activity in task manager. It's possible your drive is dying.

**Comment by williamAlhant** [comment]
Thought about the drive too, but it is less than 5 years old, and the drive is okay, according to SMART counters (I just checked with crystal disk info). Will try the cache option.

**Comment by williamAlhant** [comment]
Have not seen the problem since enabling the cache.

**Comment by Akemi** [comment]
possibly related to #8517 #8447?

**Comment by williamAlhant** [comment]
It's probably not related to mpv, but it seems I have disk usage spikes that may cause this. I have had some issues in a game too.
I don't know the cause of the disk usage spikes though, or how to find out...

**Comment by williamAlhant** [comment]
Ha, I caught it with Windows's resource monitor. I just got a disk usage spike and it is caused by a process reported as "svchost.exe (defragsvc)". I guess it's Windows's defragmenting service...
