### ISSUE TITLE
amd Vega M gpu not supported by Vulkan api

### ISSUE THREAD

**Issue by 24fpsDaVinci** [mpv-player/mpv#8623]
0.33 - mpv version
Ubuntu 20.10 
ubuntu package install
Polaris 22 XT [Radeon RX Vega M GH] using default kernel drivers

### Reproduction steps
set gpu-api=vulkan
play any file

### Expected behavior
Vega M GH should be recognized by Vulkan api
### Actual behavior
Vega M gpu is not recognized by Vulkan api
### Log file
[vo/gpu/vulkan/libplacebo] Probing for vulkan devices:
[vo/gpu/vulkan/libplacebo]     GPU 0: AMD RADV VEGAM (ACO) (discrete)
[vo/gpu/vulkan/libplacebo]            uuid: 00:00:00:00:01:00:00:00:00:00:00:00:00:00:00:00
[vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
[vo/vdpau/x11] X11 opening display: :0

thank you

**Comment by CounterPillow** [comment]
Does `vkcube` work?

**Comment by 24fpsDaVinci** [comment]
> Does `vkcube` work?

running vkcube gives:
Could not find both graphics and present queues

**Comment by haasn** [comment]
libplacebo will tell you why a GPU is unsuitable if you bump up the verbosity to at least `-v -v`, but in this case I'm assuming the issue is lack of surface support (based on the other error).

This is a driver issue, there is nothing mpv can do about it. File a mesa issue.

**Comment by haasn** [comment]
The relevant excerpt from vulkaninfo:

```
VkQueueFamilyProperties:
========================
	queueProperties[0]:
	-------------------
		minImageTransferGranularity = (1,1,1)
		queueCount                  = 1
		queueFlags                  = QUEUE_GRAPHICS | QUEUE_COMPUTE | QUEUE_TRANSFER | QUEUE_SPARSE_BINDING
		timestampValidBits          = 64
		present support             = false

	queueProperties[1]:
	-------------------
		minImageTransferGranularity = (1,1,1)
		queueCount                  = 4
		queueFlags                  = QUEUE_COMPUTE | QUEUE_TRANSFER | QUEUE_SPARSE_BINDING
		timestampValidBits          = 64
		present support             = false
```

The drivers need to report "present support = true" for at least one queue family.

**Comment by 24fpsDaVinci** [comment]
> libplacebo will tell you why a GPU is unsuitable if you bump up the verbosity to at least `-v -v`, but in this case I'm assuming the issue is lack of surface support (based on the other error).
> 
> This is a driver issue, there is nothing mpv can do about it. File a mesa issue.

using a fresh install i seem to found the root cause, its caused by setting amd gpu to 10bit color

removing xorg conf for display depth 30 and going back to default solves the problem

**Comment by haasn** [comment]
There's an [open mesa issue for this](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3537)
