### ISSUE TITLE
[Question] What options to always stay "LIVE" on a livestream (with streamlink)?

### ISSUE THREAD

**Issue by pihug12** [mpv-player/mpv#8626]
I'm using [_streamlink_](https://github.com/streamlink/streamlink) with _mpv_ to watch some Twitch streams ([related MR](https://github.com/streamlink/streamlink/pull/2513)).
I need to keep the shortest latency with the streamer because there are some quick Q&A for the whole viewers in the chat (1st to anwser get points). I use the current command:
```
streamlink https://www.twitch.tv/### 360p --player mpv --player-args '--profile=low-latency --cache=no' --twitch-low-latency --hls-live-edge 1
```

When I hit pause on _mpv_ and then hit play, the stream continues where it stopped and I'm then behind the "live". I'm not sure if this is _mpv_ or _streamlink_ related, but it seems to me to be on the player side? There seems to be like a cache despite I put the `--cache=no` option?

Can you help me to find the right options to always stay the nearest of the "live" state? I don't mind dropped frames. I already read this part in the doc: https://mpv.io/manual/stable/#low-latency-playback

Thanks!

### Config

* Fedora 32
* mpv 0.32.0
* streamlink 2.0.0

**Comment by Akemi** [comment]
i think it's quite obvious that the video stays where it was before pausing. anything else is unexpected and has nothing to do with disabling the cache. just seeking to the end of stream after unpausing should work.
