### ISSUE TITLE
mpv doesn't play full mpls playlist on bluray correctly and misreports length

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#8627]
### Important Information

- mpv version: 0.32.0
- Linux Distribution and Version: Debian testing
- Source of the mpv binary: Debian repo
- Window Manager and version: KDE Plasma 5.21.2

### Reproduction steps

Try to play a bluray index.

### Expected behavior

Should play all files in the playlist.

### Actual behavior

I'm trying to play one of the mpls on a bluray like this:
```
mpv br://31 --bluray-device=<path_to_bluray>
```
It's picking something, but looks like only the first m2ts file, ignoring all the rest.

For example, I see it showing:

```
[bd] idx:  31 duration: 00:00:02 (playlist: 00208.mpls)
```

Actual `00208.mpls` lists a bunch of m2ts entries, but mpv plays only the first one it seems.

**Comment by Geniusssmit** [comment]
Can confirm, It's a shame I need to use a different player for blurays
