### ISSUE TITLE
linux: re-add `--softvol` option

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#8629]
### Important Information
I want this option back, or similar to [this commit](https://github.com/mpv-player/mpv/commit/7621a028bf555c9ed0430501bc6eac2fa204114c) that changes keybindings to use pulseaudio volume.
This was reported earlier https://github.com/mpv-player/mpv/issues/3322 https://github.com/mpv-player/mpv/issues/3359 https://github.com/mpv-player/mpv/issues/3362.

Provide following Information:
- mpv version 0.32.0
- Kubuntu 20.10
- Ubuntu repos
- If known which version of mpv introduced the problem
- KDE Plasma
- Mesa 20.3.4

### Reproduction steps

1. Open video in mpv.
2. Decrease volume.
3. Close mpv.
4. Open same file.
5. Volume not remembered.

### Expected behavior
Have mpv remember volume when i change it.

### Actual behavior
mpv not remembering volume when i change it.

**Comment by sfan5** [comment]
softvol is much than "mpv remembers the volume between restarts".
If you want the PulseAudio volume control back you can change your keybindings:
<pre>
9 add volume -2
0 add volume 2
VOLUME_UP add volume 2
VOLUME_DOWN add volume -2
</pre>

**Comment by soredake** [comment]
> softvol is much than "mpv remembers the volume between restarts".
> If you want the PulseAudio volume control back you can change your keybindings:
> 
> 9 add ao-volume -2
> 0 add ao-volume 2
> VOLUME_UP add ao-volume 2
> VOLUME_DOWN add ao-volume -2
> 
> Edit: These are all supposed to say ao-volume, sorry about that.

I know about keybindings, yes, i have this in my input.conf:
```
MOUSE_BTN3 add ao-volume 2
MOUSE_BTN4 add ao-volume -2
9 add ao-volume -2
0 add ao-volume +2
/ add ao-volume -2
* add ao-volume +2
m cycle ao-mute
VOLUME_DOWN add ao-volume -2
VOLUME_UP add ao-volume +2
MUTE cycle ao-mute
```

But having ONE option like `i-really-want-to-control-pulseaudio=yes` in mpv.conf instead of  that changes keybindings to this would be much simplier than multiple lines in `input.conf`, sorry, I'm minimalist :(

**Comment by Akemi** [comment]
this seems horribly redundant, sry. the most i could see, what we would do, is something similar to https://github.com/mpv-player/mpv/blob/master/etc/restore-old-bindings.conf, eg adding an example how to get the old behaviour back via keybindings.
