### ISSUE TITLE
mpv occasionally breaks video decoding

### ISSUE THREAD

**Issue by Garbaz** [mpv-player/mpv#8630]
Sometimes, while watching a video with mpv, upon trying to un-pause, nothing happens. All video playback in all programs (e.g. a Youtube video in Firefox) no longer works. But otherwise, all graphical components of the OS still work normally.

This happens rather frequently and the only way get things back into order I've found is to log out and back in.

I'm not entirely sure what is at fault here, this might be a driver or even device issue, but I've only ever had it occur in mpv, so that's my best lead.

One thing to note is that I do a lot of pausing/un-pausing and skipping frame-by-frame back and forth while using mpv. I get the feeling that usually things break after I did a lot of that.

#### mpv --version:
```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 24 01:50:41 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72
```

#### System:
_OS:_ Linux Mint 20
_Processor:_ Intel i7-6500U
_GPU:_ Skylake GT2 [HD Graphics 520]

**Comment by Akemi** [comment]
please provide all the info we ask you for when choosing an issue template. if you didn't get to chose one, please make sure you are logged in beforehand.
