### ISSUE TITLE
MPV & UWP apps

### ISSUE THREAD

**Issue by ericleroy01** [mpv-player/mpv#8631]
Hi,

is there a way to embed mpv in UWP apps?
if yes, is mpv compatible with Xbox devices ?

my goal is to replace libvlcsharp from my 2 xbox projects. 4K videos are not displayed on xbox with vlc libraries :(

**Comment by jeeb** [comment]
I think at least at some point some things were possible to build with UWP, but might have required some additional funkiness (helper libraries written by wm4 or whatever).

I don't think anyone from the development team has looked into how to build and/or test on UWP in a very, very long time :) .

**Comment by Hrxn** [comment]
Isn't there already a WPF/WinForms app embedding libmpv? Therefore, the answer is yes, UWP should be possible.

**Comment by ericleroy01** [comment]
this WPF project https://github.com/stax76/mpv.net embed mpv lib.
but mpv is instantiated by using control handle.

UWP controls do not provide handle... this is my main issue
@jeeb where can I find wm4's helper libraries ?

**Comment by CounterPillow** [comment]
Here's an example of someone using libmpv with uwp: https://github.com/Starz0r/LibMpvCSharp

**Comment by ericleroy01** [comment]
thanks but video is not displayed with latest mpv library.

(I tried with valid url and local files)

I saw some Microsoft documentation about SwapChainPanel control. I will try to use render api to reach my goal :)

if you get some information about uwp & mpv, don't hesitate to contact me.

**Comment by Akemi** [comment]
the question has been answered.
