### ISSUE TITLE
mpv Subtitle ScaledBorderAndShadow :yes?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#8635]
The .ass subtitle doesn't look like it suppose to be without adding **ScaledBorderAndShadow :yes** in the .ass subtitle?

I think that for mpv player **ScaledBorderAndShadow: no** by default? 
Cuz
With android mx player the the subtitle is looking like it suppose to be but with mpv it doesn't. But only when **ScaledBorderAndShadow :yes** is added in .ass subtitle the subtitle looks correct like mx player.

So I don't know if it possible but
I would like to turn on **ScaledBorderAndShadow** to yes
Automatically with a keybind so that I don't have to change .ass subtitle file.

**Comment by hooke007** [comment]
It's not mpv. To ask Libass instead.
https://github.com/libass/libass/issues/287

**Comment by erickyun** [comment]
> It's not mpv. To ask Libass instead.
> [libass/libass#287](https://github.com/libass/libass/issues/287)

Ok thank you. I will try to ask there.

**Comment by erickyun** [comment]
> to answer your initial question. you can cycle (force) the ass subtitle properties with in your input.conf
> 
> ```
> X cycle_values sub-ass-force-style "ScaledBorderAndShadow=yes" "ScaledBorderAndShadow=no"
> ```
> 
> or in your mpv conf set
> 
> ```
> sub-ass-force-style=ScaledBorderAndShadow=yes
> ```

Thank you very much for your answer.
That also solved it.
