### ISSUE TITLE
Shifted colors when applying a Vapoursynth filter

### ISSUE THREAD

**Issue by chainikdn** [mpv-player/mpv#8636]
### Important Information

Window 10

mpv version affected: >= mpv-x86_64-20201206-git-a9aa5a1
mpv 0.33-release and earlier works ok

both plain mpv and Plex via libmpv are affected

### Reproduction steps

test.py:
```
import vapoursynth as vs
core = vs.get_core()
video_in.set_output()
```
> mpv.exe --vf=vapoursynth:test.py video.mkv

### Actual behavior
![bad](https://user-images.githubusercontent.com/9394230/110649567-c5fcfb80-81ca-11eb-8feb-16b8db1d5a86.png)
[bad.log](https://github.com/mpv-player/mpv/files/6116800/bad.log)

### Expected behavior
![good](https://user-images.githubusercontent.com/9394230/110649618-cf866380-81ca-11eb-94f5-966a1eb7b1bf.png)
[good.log](https://github.com/mpv-player/mpv/files/6116801/good.log)

**Comment by hooke007** [comment]
I am using the 20210228, and I cannot reproduce the issue.

**Comment by chainikdn** [comment]
ok. to be more specific it's somehow connected with the auto-copy hwdec.

> mpv.exe --vf=vapoursynth:test.py --no-config --hwdec=auto-copy video.mkv
<= 0.33-release - ok
> 0.33 - shifted colors

> mpv.exe --vf=vapoursynth:test.py --no-config video.mkv
any version - ok

> mpv.exe --no-config --hwdec=auto-copy video.mkv
any version - ok

**Comment by chainikdn** [comment]
sample video: https://drive.google.com/file/d/1YgqGGvIewfZ_z6Oh72uZqtVrgE3OYul5/view?usp=sharing

**Comment by chainikdn** [comment]
Doesn't happen anymore with 0.34.0

**Comment by hooke007** [comment]
@chainikdn can u reopen it? I test two devices, it still could be reproduced.

**Comment by hooke007** [comment]
@haasn if possible cc this issue. It could also be reproduced by `--vo=gpu-next --hwdec=auto-copy`

**Comment by chainikdn** [comment]
indeed, not fixed yet :(

**Comment by Natural-Harmonia-Gropius** [comment]
https://github.com/mpv-player/mpv/issues/9424#issuecomment-985606411 works for me.
https://github.com/mpv-player/mpv/issues/9424#issuecomment-986295070 I think continue discussions in this issue is okay.

@chainikdn @Akemi Could you edit this issue, as it's a zimg issue, also hapens to other `vf` https://github.com/mpv-player/mpv/issues/9424#issuecomment-985604877 and even always https://github.com/mpv-player/mpv/issues/9424#issuecomment-985440106 now.

**Comment by ValZapod** [comment]
So zimg is on by default? In which scenarios?

**Comment by ValZapod** [comment]
Does other --zimg-scaler=<point|bilinear|bicubic|spline16|spline36|lanczos> fix this?
Does --zimg-scaler-param-a=4 for default lanczos fixes this?

Also please give this sample from American dad attached right here in github. Thanks.

**Comment by dyphire** [comment]
It has been fixed by https://github.com/sekrit-twc/zimg/commit/c3b86550eaee9608f3b8d5dc2abf89865758ceca.

mpv builds since 20220319-git no longer have it.

**Comment by ValZapod** [comment]
> has been fixed by

Specidically by that commit? I doubt it. How does it look like now?

**Comment by dyphire** [comment]
> Specifically by that commit? I doubt it. How does it look like now?

As I said, when testing with the build of mpv-git after 20220318, you will see that the issue of chroma shifted by zimg has been fixed when using the vapoursynth filter on hardware decoding of copy mode.

If you don't believe it, please test it yourself.

**Comment by chainikdn** [comment]
Not sure the fix was exactly the one mentioned above, but Windows mpv builds starting from 20220313 doesn't have this issue.
