### ISSUE TITLE
input.conf MBTN_* events only respond to a release. If it is possible to make them respond to a press, how do key events respond?

### ISSUE THREAD

**Issue by IlyaIndigo** [mpv-player/mpv#8640]
MBTN_* events only respond to a release.
If it is possible to make them respond to a press, how do key events respond?
```
LEFT seek -1
RIGHT seek +1
MBTN_BACK seek -1
MBTN_FORWARD seek +1
```
You can press and hold the keys until the desired position is reached and release them.
But you can not hold the mouse buttons, you have to press and release them for a long time to rewind to the desired position.

**Comment by wiiaboo** [comment]
Only through [lua](https://mpv.io/manual/master/#lua-scripting-[,flags]]))/JS scripting, afaik.

**Comment by avih** [comment]
> You can press and hold the keys until the desired position is reached and release them.
> But you can not hold the mouse buttons

That's because KB has autorepeat, but mouse buttons don't autorepeat.

As mentioned, you can bind mouse buttons in lua/js with "complex" mode, where you get notified on both press and release. With some programming you can then increase/decrease some property value periodically as long as the button is held down.

Normal mpv mouse buttons binding only trigger the command on button-release.

**Comment by IlyaIndigo** [comment]
@wiiaboo @avih 
I don't understand where I need to put this script
```
function something_handler()
    print("the key was pressed")
end
mp.add_key_binding("x", "something", something_handler)
```
Could you give me an example for my case, where and with what name should I create the script file and what should I write in conf and input.conf?

**Comment by avih** [comment]
> Could you give me an example for my case

Not really an example, but rather the complete solution.

Save this as `mouse-seek.js` in your scripts/ dir inside your mpv config dir:
```js
var repeat = 5;  // times per second - while the button is held down
var bindings = {
    MBTN_FORWARD: "seek  1",
    MBTN_BACK:    "seek -1",
};

var command;
function do_command() {
    mp.command(command);
}

var id = undefined;
function handler(data) {
    clearInterval(id);
    if (data.event == "down") {
        command = bindings[data.key_name];
        do_command();
        id = setInterval(do_command, 1000/repeat);
    }
}

for (var b in bindings)
    mp.add_key_binding(b, handler, {complex: true});
```

**Comment by IlyaIndigo** [comment]
@avih 
I did as you wrote, but when I start up I get this message.
`Can't load unknown script: ~/.mpv/scripts/mouse-seek.js`
Does this mean a syntax error in the script or something else?

**Comment by avih** [comment]
It probably means your mpv was compiled without javascript support.

You should either compile mpv with js support, or ask the maintainer of the mpv package to add js support, or translate the script to lua (which I'm not going to do).

**Comment by IlyaIndigo** [comment]
@avih Okay, thank you!

**Comment by avih** [comment]
But you wanted an example, so my code should be more than enough to get you going, and translate it to lua yourself.
