### ISSUE TITLE
Time of video and local mouse coordinates with MPV

### ISSUE THREAD

**Issue by Gabrivolea** [mpv-player/mpv#8642]
Hi all, 
This is the information of the mpv version I installed:
- mpv version
mpv 0.33.0-88-gd1be8bb606 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 28 09:25:17 +08 2021
FFmpeg library versions:
   libavutil       56.66.100
   libavcodec      58.126.100
   libavformat     58.68.100
   libswscale      5.8.100
   libavfilter     7.107.100
   libswresample   3.8.100
FFmpeg version: git-2021-02-28-85ab9deb
- Windows Version: Window 10

Hello all,

I want to use MPV player to perform manual tracking of object. I simply want to track the mouse click on a video window while a movie is running and copy to clipboard the video time (in number of frames if possible), the x and y absolute position (respect to the image corner so the value should not be affected by the zoom or the pan of the image).

I see this code to obtain the time and I try to modify to also obtain the x and y position based on another ".lua" script I find in the web but obviously it doesn´t run (I am not programmer):

```
require 'mp'

local function set_clipboard(text)
mp.commandv("run", "powershell", "set-clipboard", text);
end

local function copyTime()
local time_pos = mp.get_property_number("time-pos")
local time_in_seconds = time_pos
local time_seg = time_pos % 60
time_pos = time_pos - time_seg
local time_hours = math.floor(time_pos / 3600)
time_pos = time_pos - (time_hours * 3600)
local time_minutes = time_pos/60
time_seg,time_ms=string.format("%.09f", time_seg):match"([^.]*).(.*)"
time = string.format("%02d:%02d:%02d.%s", time_hours, time_minutes, time_seg, time_ms)
mp.osd_message(string.format("Copied to Clipboard: %s", time))
set_clipboard(time)
end

mp.add_key_binding("c", "copyTime", copyTime)
```

I tried to "merge" this code and this other one code:

```
-[[
usage: place script into $HOME/.mpv/lua/ directory (mpv 0.4 and later)
or run mpv --lua path/to/capture.lua
or add "lua=/absolute/path/to/capture.lua" to ~/.mpv/config
keybindings:
a - capture fragment: at first press script remembers start position, at second outputs command for encoding
c - crop: first press remembers mouse cursor coords, second outputs crop filter parameters.
]]
capture = {}
local gp
if mp.get_property == nil then
gp = mp.property_get
else
gp = mp.get_property
end
function capture.handler()
local c = capture
if c.start then
print(string.format("ffmpeg -ss %s -i '%s' -t %s",
c.start, gp("path"), gp("time-pos")-c.start))
print(string.format("WebMaster -s %s -t %s '%s'",
c.start, gp("time-pos")-c.start, gp("path")))
c.start = nil
else
c.start = gp("time-pos")
end
end
function capture.crop()
local x, y = mp.get_mouse_pos()
local resX, resY = mp.get_osd_resolution()
-- print(x .. ":" .. y .. " " .. resX .. "x" .. resY )
local c = capture
if c.pos then
local pos2 = mp.get_mouse_pos()
local w, h = gp('width'), gp('height')
print(string.format("crop=%d:%d:%d:%d",
(x - c.pos[1]) * w / resX, (y - c.pos[2]) * h / resY,
c.pos[1] * w / resX, c.pos[2] * h / resY))
c.pos = nil
else
c.pos = {x, y}
end
end
--mp.add_key_binding("a", "capture", capture.handler)
mp.set_key_bindings({
{"c", capture.crop},
{"a", capture.handler}
})
mp.enable_key_bindings()
```

So I generate this code:

```
require 'mp'

local function set_clipboard(text)
mp.commandv("run", "powershell", "set-clipboard", text);
end

local function copyTime_and_XY()

local x, y = mp.get_mouse_pos()
local resX, resY = mp.get_osd_resolution()
-- print(x .. ":" .. y .. " " .. resX .. "x" .. resY )
c.pos = {x, y, z}
mp.osd_message(string.format("Copied to Clipboard: c.pos))
local time_pos = mp.get_property_number("time-pos")
local time_in_seconds = time_pos
local time_seg = time_pos % 60
time_pos = time_pos - time_seg
local time_hours = math.floor(time_pos / 3600)
time_pos = time_pos - (time_hours * 3600)
local time_minutes = time_pos/60
time_seg,time_ms=string.format("%.09f", time_seg):match"([^.]*).(.*)"
time = string.format("%02d:%02d:%02d.%s", time_hours, time_minutes, time_seg, time_ms)
mp.osd_message(string.format("Copied to Clipboard: %s", time, x, y))
set_clipboard(time, x, y)

end

mp.add_key_binding("c", "copyTime_and_XY", copyTime_and_XY)
```

I attach the files.

If someone could help me I would appreciate a lot since I am not capable to perform this apparently simple task.

Thanks,

Gabriel
[copyTime_and_XY - copia.txt](https://github.com/mpv-player/mpv/files/6126186/copyTime_and_XY.-.copia.txt)
[Capture.txt](https://github.com/mpv-player/mpv/files/6126187/Capture.txt)

I have one reply in another forum and I have tried the solution but without success:
- start mpv from command-line, it will report any errors there.

1) get video time (in number of frames if possible), the x and y absolute mouse position
try printing the properties to the OSD, console or window title.
standard video time isn't difficult to obtain.

2) copy a string to the Windows clipboard.
certainly there are scripts which can do this.

I'm afraid I am not familiar with .lua, and haven't used the mouse-pos property.

`mpv video.mp4 --title="${time-pos} ${mouse-pos}"`

Thanks!!

**Comment by avih** [comment]
You can't "merge" scripts. You have to know what you're doing, or learn programming (which cannot be done in few minutes or days).

I recomend a simpler approach if you prefer not to use scripts. Just add this to your `input.conf`:
```
MOUSE_BTN2 print-text "${=time-pos} ${mouse-pos}"
```
and run mpv from a terminal (like you were suggested to do in that forum) with the video name. Then whenever you right-click the video it will print to the terminal the time in seconds and the mouse position at the coordinates of the window size.

Then quit mpv, and just copy the output from the terminal into a text editor and arrange it however you like.

Or find somneone who will program for you whatever you need.

**Comment by Gabrivolea** [comment]
Thanks a lot Avih, this is the easiest approach I think... I have use Visual Basic for Applications for years copy and pasting code from the web and I have done moreless good applications. The trial and error is not the best approach but it run well :)
