### ISSUE TITLE
Add URL Inferring

### ISSUE THREAD

**Issue by hl2guide** [mpv-player/mpv#8644]
Please consider adding the ability of supporting inferred URLs.

e.g Currently from the command line:

`mpv twitch.tv/criticalrole`
_fails when live (should work)_

`mpv https://twitch.tv/criticalrole`
_succeeds when live (https protocol prefixed)_

Please auto prefix the protocol (https://) if it is missing depending on the root domain (e.g. twitch.tv).

**Comment by CounterPillow** [comment]
How would it distinguish a file named "twitch.tv/criticalrole" from a URL? How would we ensure that the list of domains we enable this special purpose behaviour for is kept exhaustive enough as to not confuse users with inconsistent behaviour? Who would want to maintain such a list, and is it really worth the effort?

**Comment by hl2guide** [comment]
- I suggest that the vast number sites use the HTTPS protocol prefix (catches most)
- "twitch.tv/criticalrole" would not be a file because it has no file extension
- If a local file exists (no extension) then load it otherwise treat it an external URL (fallback)
- I would expect MPV to already have some "Supported Sites" list internally that would then pick up "twitch.tv" as a recognized stream source, no new list needed

**Comment by Akemi** [comment]
- a file doesn't need an extension. also in that case one could consider ".tv/criticalrole" the extension
- i am not sure but such a fallback doesn't seem like a good idea, it could introduce unexpected behaviour
- sry to betray your expectation, we don't have such a list since we don't need one
