### ISSUE TITLE
How to make mpv read more than one cookie.txt file?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#8645]
I know that with this added in mpv.conf **ytdl-raw-options=cookies="cookies1.txt"** mpv reads text file but
When I do this:
 **ytdl-raw-options=cookies="cookies1.txt"**
 **ytdl-raw-options=cookies="cookies2.txt"**

mpv won't read cookies1.txt only cookies2.txt works?

So My question is
Can I make mpv read multiple cookies.txt files at the same time?

**Comment by Akemi** [comment]
does youtube-dl support several cookie files? if yes, how do you pass it to youtube-dl's cookie option? if it's comma separated something like `ytdl-raw-options=cookies="cookies1.txt,cookies2.txt"` should work. that is entirely up to youtube-dl and not mpv.

**Comment by erickyun** [comment]
> does youtube-dl support several cookie files? if yes, how do you pass it to youtube-dl's cookie option? if it's comma separated something like `ytdl-raw-options=cookies="cookies1.txt,cookies2.txt"` should work. that is entirely up to youtube-dl and not mpv.

I will try asking there ytdl-raw-options=cookies="cookies1.txt,cookies2.txt" doesn't seem to work. :(

**Comment by erickyun** [comment]
I found my solution🙂
İt is really simple😅
Copy and pasting the cookies together in one file will work.👍
