### ISSUE TITLE
[SOVLED] About d3d11 exclusive full-screen mode

### ISSUE THREAD

**Issue by NeilTohno** [mpv-player/mpv#8650]
### Important Information

d3d11-exclusive-fs=yes
When I play videos with d3d11 exclusive full-screen mode, click space key to  pause, the UI will freezing, and showing false frames (first video), until switch to window mode.

- mpv version
mpv-x86_64-20210228-git-d1be8bb
- Windows Version
win10 1909 x64 
2950x, vega 64

### Frequency
Always, irregularity

### Log file

[mpv1.zip](https://github.com/mpv-player/mpv/files/6136406/mpv1.zip)

### conf
[c.zip](https://github.com/mpv-player/mpv/files/6137006/c.zip)

**Comment by CounterPillow** [comment]
thank you for ignoring the issue template, specifically the part asking you expressly to provide a full log file of the issue occurring.

**Comment by NeilTohno** [comment]
> thank you for ignoring the issue template, specifically the part asking you expressly to provide a full log file of the issue occurring.

I will add it.

**Comment by amariami** [comment]
> I will add it.
Could you upload your mpv.conf configuration?

**Comment by NeilTohno** [comment]
> Could you upload your mpv.conf configuration?

Done.  (・ω<)
I don't found any error in them.

**Comment by amariami** [comment]
maybe cache allocation is too small
 
<body> 
    <details> 
        <summary>Spoiler XD🔢 </summary> 
         
![Screenshot_2021-03-15-00-13-49-045_de ah_apps data_unit_converter](https://user-images.githubusercontent.com/79769464/111077484-326b4980-84ae-11eb-99d0-040b1a484fd4.png)
    </details>         
</body> 
</html> 

Ex:
`--cache=yes `
`--cache-pause-initial=yes 			#<yes|no>`
`--demuxer-cache-wait=yes			#<yes|no>`
`--demuxer-max-bytes=500MiB			#KiB or MiB`
`--demuxer-max-back-bytes=200MiB		#KiB or MiB`
#https://mpv.io/manual/master/#options-demuxer-max-bytes

**Comment by NeilTohno** [comment]
> maybe cache allocation is too small

Thanks,
I knew it, I can adjust cache size to make playbcak more smoother.

in this case, "d3d11 exclusive full-screen mode" is the problem, it is not pefect.

**Comment by amariami** [comment]
https://sourceforge.net/projects/mpv-player-windows/files/#player-freezing-when-switching-to-fullscreen

**Comment by NeilTohno** [comment]
> https://sourceforge.net/projects/mpv-player-windows/files/#player-freezing-when-switching-to-fullscreen

Thank you.
