### ISSUE TITLE
hope MPV-android could directly read subs easily and from zip/rar/7z.

### ISSUE THREAD

**Issue by NewUserHa** [mpv-player/mpv#8651]
* currently, mpv-android needs to start from `root(/sdcard)` directory every time when try to open/select an local ass/srt file. and if at in the right path(usually the `download` folder), the users always need to find the ass/srt file in a file list of all(*.*).

* Subtitles usually are inside archive files on disks today.
### Expected behavior of the wanted feature
* hope MPV can remember the last used directory for subtitles and can show the right files only(ass/srt for subtitles here).

* mpv-android does nothing(include tip) after trying to open zip of subtitles from http.
Actually, subtitles are usually inside zip/rar, so hope mpv-android can open zip from http and put all available ass/srt into the subtitles listing window by the button on the On Screen Controller.

* the subtitles window by the button on the On Screen Controller may also be able to open subtitles from local or online.

### Alternative behavior of the wanted feature
none

### Log file
none

**Comment by hooke007** [comment]
https://github.com/mpv-android/mpv-android/issues
Why not write it here?

**Comment by NewUserHa** [comment]
I followed the https://mpv.io/community/ and don't know the exists of that repo.
and I checked there are issues for android in the current issues tracker, so thought that here also collect issues for android.

does the current repo collect issues like this for android? and need this issue post to https://github.com/mpv-android/mpv-android/issues?

**Comment by hooke007** [comment]
I seldom see the issues related android here. I think you'd better post it there.

**Comment by NewUserHa** [comment]
ok.
