### ISSUE TITLE
Gamepad not working?

### ISSUE THREAD

**Issue by wrybread** [mpv-player/mpv#8657]
I'm trying to use a joystick to control mpv under Ubuntu but can't get it working. 

I see I need to enable gamepad at runtime with "--input-gamepad=yes", but that fails at runtime with "Error parsing option input-gamepad (option not found) Setting commandline option --input-gamepad=yes failed."

Is gamepad/joystick control still supported in MPV?

**Comment by Akemi** [comment]
if compiled with sdl i believe. please open a new issue with all the info we ask for.
