### ISSUE TITLE
toggle for osc-visibility

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8658]
I'd like to apply toggle on these lines of code.
So I don't need to use Capitalize for the 2nd line.
I think toggle is the best way to solve the issue.

_(sorry for the poor English)_

`c script-message osc-visibility always`
`C set osd-level 1; script-message osc-visibility auto`

**Comment by avih** [comment]
There's no mpv command which cycles a set of commands.

But a script could do that. This is a generic script which you can use to bind any key to cycle any set of commands:
```js
// at input.conf: KEY script-message cycle-cmd "CMD1" "CMD2" ...
// then pressing KEY cycles CMD1 -> CMD2 ->... CMD1 -> CMD2 ->...
// different keys can be bound to cycle diffrent sets of commands
// by avih

var registry = {};

mp.register_script_message("cycle-cmd", function() {
    var key = [].join.call(arguments);
    if (!(registry[key] >= 0))
        registry[key] = -1;
    
    registry[key] = (registry[key] + 1) % arguments.length;
    mp.command(arguments[registry[key]]);
});
```

Save the text above in a file called `cycle-cmd.js` in your scripts dir, then at input.conf add:
```
c script-message cycle-cmd "script-message osc-visibility always" "set osd-level 1; script-message osc-visibility auto"
```
Or any other key or set of commands to cycle.

You'll need javascript support in mpv for this script to work. Else, you'll need to translate it to lua.

**Comment by Max-Enrik** [comment]
Amazing! Than you a lot!

**Comment by Max-Enrik** [comment]
I'd like to mpv starts off with `osc-visibility never` mode, any ideas?

**Comment by avih** [comment]
Here's an idea: RTFM.

**Comment by Max-Enrik** [comment]
(Look like I annoyed you with mentioned your name. I apologize.)
These are what I tried.
```
no-osd-bar
script-message osc-visibility never
set osd-level 0; script-message osc-visibility never
```

**Comment by avih** [comment]
https://mpv.io/manual/master/#on-screen-controller-visibility

**Comment by Max-Enrik** [comment]
Unfortunately, my poor English doesn't give me that opportunity to fully understand it and implement it.
First I read it and tried to find it the Issue section here. But still can't do it by myself.

**Comment by avih** [comment]
At `mpv.conf`: `script-opts-add=osc-visibility=never`
or
At `script-opts/osc.conf`: `visibility=never`

**Comment by Max-Enrik** [comment]
@avih - Believe or not I spent over 2 hours half on this issue and I tried to do it by myself and needed find an answer to my question but there wasn't an option that I can do it. So I asked here and mentioned you.

I apologize and I thankful to you. Thank you a lot!

**Comment by avih** [comment]
>  So I asked here and mentioned you

I got annoyed because it looked as if you use the issue as replacement for reading the manual. We spend a lot of time trying to make the manual as best as we can make it exactly so that people don't have to ask questions for things which are documented.

Your English looks reasonably good to me, and you didn't mention that you looked at the manual.

I recomment to read the whole manual at least once so that you get familiar with what's possible, and then when you actually need something it will be easier to find things you need.

And if your English is not good enough, then you should improve it first, because that's the only language we have docs for.

**Comment by Max-Enrik** [comment]
I know there are tons of hours you spent for the documented.


> I recomment to read the whole manual at least once so that you get familiar with what's possible, and then when you actually need something it will be easier to find things you need.
> 
> And if your English is not good enough, then you should improve it first, because that's the only language we have docs for.

I partially read the document but never read it whole manual, I will do it before end of September 2021.

Once again thank you a lot.

**Comment by Max-Enrik** [comment]
I tried to switch auto to never/cycle but these doesn't work accurately, look like I didn't correctly understand this.
https://github.com/mpv-player/mpv/issues/4896#issuecomment-330458533
```
.. (is_auto and "never" or "always") .. " no-osd"
or
.. (is_auto and "cycle" or "always") .. " no-osd"
```

My expectation is Shows and Hides OSC. And when mode is Hide no need to be show OSC when mouse around bottom (hover) of the window.
_(Hope I explained well enough.)_

**Comment by guidocella** [comment]
Remove ` .. " no-osd"`, that goes at the beginning of commands not at the end, and has no effect on `script-message` anyway since changing osc-visibility doesn't print anything on the OSD.

**Comment by Max-Enrik** [comment]
I was trying to find another way to achieve what I want. Now I think I found a way to achieve it by changing `deadzonesize=10` and this avoids show up OSC when even mouse move. So I was tried to change `auto` to `never/cycle` to avoid show up OSC when while mouse move.
```

local is_auto = true  -- no way to read the osc mode,
                      -- so we assume it starts in auto mode.
function show_hide_osc ()
  is_auto = not is_auto
  mp.command(
    "script-message osc-visibility "
--  .. (is_auto and "auto" or "always") .. " no-osd"
    .. (is_auto and "never" or "always") .. " no-osd"
  )
end
mp.add_key_binding("b", "osc-show-hide-hotkey", show_hide_osc)

```

**Comment by guidocella** [comment]
You're passing the visibility argument to `script-message` twice. Try
```lua
mp.commandv("script-message", "osc-visibility", is_auto and "auto" or "always", 1)
```

**Comment by Max-Enrik** [comment]
I need to change `auto` to `never` so it still doesn't work with your method.

**Comment by guidocella** [comment]
Then just replace "always" with "never".

**Comment by guidocella** [comment]
I'm guessing you're trying to cycle between all 3 visibility values? Then you need a script like

```lua
local visibility = 'auto'
mp.add_key_binding('b', 'osc-cycle-visibility', function()
    if visibility == 'auto' then
        visibility = 'always'
    elseif visibility == 'always' then
        visibility = 'never'
    else
        visibility = 'auto'
    end

    mp.commandv('script-message', 'osc-visibility', visibility, 1)
end)
```

**Comment by Max-Enrik** [comment]
I think I was not clearly explained what I was looking for. Sorry about that. One more time I need to try explain what I am actually looking for. So osc-visibility `always` mode shows up OSC, this is cool. And I need to switch it off like using osc-visibility `never` that if mouse moving OSC shouldn't show up. So far this toggle script doesn't do this.
_(English isn't my native lanauge.)_

**Comment by Max-Enrik** [comment]
I do it exactly as you mentioned. But unfortunately it doesn't show up.

**Comment by Max-Enrik** [comment]
This problem was solved since I use v0.34.

**Comment by Max-Enrik** [comment]
These are both work fine.
```
a set video-unscaled yes
s set video-unscaled no
```

These are both not doing anything, even not given an error.
```
      H script-message cycle-cmd "script-message video-unscaled yes" "script-message video-unscaled no"
shift+h script-message cycle-cmd "script-message video-unscaled yes" "script-message video-unscaled no"
```

Where am I doing wrong in the method of "**cycle-cmd**"?

**Comment by guidocella** [comment]
`script-message` is for interacting with scripts, not for changing properties. Use `cycle-values video-unscaled yes no`

**Comment by Max-Enrik** [comment]
Thank you a lot.

**Comment by Max-Enrik** [comment]
What have I been trying so far?

```
a script-message cycle-cmd "osc-chapterlist yes" "osc-chapterlist no"
a script-message cycle-cmd "osc-chapterlist never" "osc-chapterlist auto"
a script-message cycle-cmd "set osc-chapterlist" "remove osc-chapterlist"
a script-message cycle osc-chapterlist
a script-message cycle-values osc-chapterlist
a script-message toggle osc-chapterlist
```
I couldn't do it myself. Any ideas or help?
