### ISSUE TITLE
is there a lua script that cuts online videos like youtube?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#8659]
is there a lua script that cuts a youtube at a specific time and downloads only the trimmed part?

**Comment by avih** [comment]
Maybe. Check here https://github.com/mpv-player/mpv/wiki/User-Scripts
Or write your own.

**Comment by erickyun** [comment]
> Maybe. Check here https://github.com/mpv-player/mpv/wiki/User-Scripts


couldn't find any .

> Or write your own.

I hope someone else will cuz I don't know how to make lua script myself.
and thanks for your help. :)
