### ISSUE TITLE
unparseable extra characters

### ISSUE THREAD

**Issue by aphsa** [mpv-player/mpv#8663]
### Important Information
Unable to configure input.conf with "h seek -5"

Provide following Information:
- mpv version
```sh
mpv 0.33.0-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.2
```
- Linux Distribution and Version
```sh
Linux tester 5.11.6-arch1-1 #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000 x86_64 GNU/Linux
```
- Source of the mpv binary
Arch repository
- If known which version of mpv introduced the problem
- Window Manager and version
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
```sh
mpv --version
/home/tester/.config/mpv/config:2: unparseable extra characters: 'seek -5'
mpv 0.33.0-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.2

❯ cat ~/.config/mpv/config
volume=20
h seek -5
```

### Expected behavior
What is the input.conf format to bind seek to an ascii character?

**Comment by Akemi** [comment]
` ~/.config/mpv/config` is not the right place for key bindings. it's `input.conf`.
