### ISSUE TITLE
[Feature Request] Migrate Youtube-DL to yt-dlp

### ISSUE THREAD

**Issue by grravity** [mpv-player/mpv#8665]
Suggesting moving from Youtube-DL to yt-dlp
https://github.com/yt-dlp/yt-dlp

yt-dlp is a fork of Youtube-DLC (https://github.com/blackjack4494/yt-dlc - inactive), which is a fork of Youtube-DL. It brings a bit of a faster feature development, as well as actively listening to the community, where youtube-dl has not been so amazing in that aspect. It comes with some new features as well.

**Comment by CounterPillow** [comment]
if the json dump invocation stayed the same don't need to move from anything to anything, it can just look for either of the two.

**Comment by Dudemanguy** [comment]
The youtube-dl hook is just a lua script. You can already set a custom path for it for whatever executable you want so there's no need for us to do anything. See the `ytdl_path` option in the manual.

**Comment by grravity** [comment]
Thank you for clarifying. Sorry for the bother.

**Comment by avahe-kellenberger** [comment]
Is this not available as an option in `mpv.conf`? I'd prefer to not have to pass a command line flag every time.

**Comment by JohnDDuncanIII** [comment]
@avahe-kellenberger

- ~/.config/mpv.conf

`script-opts=ytdl_hook-ytdl_path="/opt/bin/yt-dlp"`

then you can run a test with `mpv -v <youtube_uri>` to double check that it's using `yt-dlp` over `youtube-dl`

```sh
[ytdl_hook] full hook 
[ytdl_hook] found youtube-dl at: /opt/bin/yt-dlp 
[ytdl_hook] youtube-dl succeeded! 
[ytdl_hook] format selection: youtube-dl (separate) 
```

https://github.com/mpv-player/mpv/issues/8264#issuecomment-726453213

**Comment by avih** [comment]
> `script-opts=ytdl_hook-ytdl_path="/opt/bin/yt-dlp"`

You probably want this instead:
```
script-opts-add=ytdl_hook-ytdl_path="/opt/bin/yt-dlp"
```

Note the additional `-add`, because if you don't use it, it will wipe any prior `script-opts` which were set at `mpv.conf`, but with `script-opts-add=...` it will add this value instead of wiping all prior values.

**Comment by avahe-kellenberger** [comment]
Thanks!

**Comment by sebma** [comment]
> The youtube-dl hook is just a lua script. You can already set a custom path for whatever executable you want so there's no need for us to do anything. See the `ytdl_path` option in the manual.

@Dudemanguy Strange, I see no  `ytdl_path` option in the manual of mpv v0.32 :
 ```bash
$ man mpv | grep ytdl_path
$
```
Was this option introduced later ?
