### ISSUE TITLE
Adding currently used (external) subtitle file to info section (shortcut i)

### ISSUE THREAD

**Issue by spfeifer222** [mpv-player/mpv#8669]
Dear mpv team,

is it possible to add the currently used (external) subtitle file to the info section? Either by configuration or merging that feature into the next version? 

This would be convenient: if there are several subtitle files in the directory, currently this is only possible by cycling through the detected subtitles by shortcut j, but the next subtitle is shown and someone has to be cycle through the subtitle files to get that information. 

Best regards,
Seb

**Comment by guidocella** [comment]
You can view the currently used subtitle with F9.

**Comment by spfeifer222** [comment]
I never realized, even if I use mpv for years. Thank you, Guido.
