### ISSUE TITLE
Error "unparseable extra characters" on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by filcode** [mpv-player/mpv#8671]
### Information:
- mpv version: 0.33 for macOS
- macOS Version: macOS Catalina 10.15.7
- Source of the mpv binary or bundle: https://laboratory.stolendata.net/~djinn/mpv_osx/

### Description

In my mpv.conf I define:
alang: eng, por, en, pt
slang: eng, por, en, pt

and I get the following error on the terminal: 
/Users/filipe/.config/mpv/mpv.conf:5: unparseable extra characters: ': eng, por, en, pt'
/Users/filipe/.config/mpv/mpv.conf:6: unparseable extra characters: ': eng, por, en, pt'

If I comment slang and alang on mpv.conf I don't get any error. Any solution idea to solve this?

Thank you

### Screenshot
Please consider the screenshot in attachment.

![Screen Shot 2021-03-23 at 01 19 49](https://user-images.githubusercontent.com/81129688/112078751-de7bf700-8b76-11eb-9ba4-46178f45eda2.png)

### mpv.conf file

Please consider my "mpv.conf" file attached.
[mpv.conf.zip](https://github.com/mpv-player/mpv/files/6186345/mpv.conf.zip)

**Comment by CounterPillow** [comment]
>In my mpv.conf I define:
> alang: eng, por, en, pt
> slang: eng, por, en, pt

Well there's your problem. That's not mpv config syntax at all. You want:

```
alang=eng,por,en,pt
slang=eng,por,en,pt
```

**Comment by filcode** [comment]
> > In my mpv.conf I define:
> > alang: eng, por, en, pt
> > slang: eng, por, en, pt
> 
> Well there's your problem. That's not mpv config syntax at all. You want:
> 
> ```
> alang=eng,por,en,pt
> slang=eng,por,en,pt
> ```

Thank you. You solve my problem.


https://user-images.githubusercontent.com/81129688/112082190-d0c97000-8b7c-11eb-8e6e-bcdb55ddf41e.mov

**Comment by Akemi** [comment]
if your issue is solved you can also close your issues next time, thanks.

**Comment by Akemi** [comment]
please don't delete your initial post. it might still be helpful for people searching for the same problem.
