### ISSUE TITLE
Setting audio-device through conditional auto profile results in stalled playback

### ISSUE THREAD

**Issue by miltrath** [mpv-player/mpv#8672]
### Important Information

- mpv-0.33.0-dirty
- Arch Linux, rolling release
- official repositories

### Reproduction steps

Load a video file with more than 2 audio channels into mpv with the conditional auto profile set in a similar manner:

```
[auto51]
profile-desc=Use analog for multichannel
profile-cond=p["audio-params/channel-count"] >= 3
audio-device=alsa/surround51:CARD=ICUSBAUDIO7D,DEV=0
profile-restore=copy
```

### Expected behavior

Normal playback of both audio and video to start immediately.

### Actual behavior

File loads and mpv displays as normal but playback is stalled.  Playback does not start unless a seek operation is performed or another audio track is selected.  Everything proceeds as normal afterward. 

### Log file

[mpv.issue.log](https://github.com/mpv-player/mpv/files/6187982/mpv.issue.log)

**Comment by kevinlekiller** [comment]
I was having the same issue, to get around it, I'm doing this (waiting until the file is 1 second in):

    profile-cond=get("time-pos", default_value) >= 1 and get("audio-params/channel-count", default_value) > 2

Although, now I see this warning: `Audio device underrun detected.` ; but the audio still plays fine.

**Comment by garoto** [comment]
> Audio device underrun detected [...]

These msgs all started popping-up for users because wm4 explicitly changed this logging mechanic many years ago. Never really understood the reasons given on the commit msg, but whatever.

**Comment by kevinlekiller** [comment]
I've been testing different solutions, checking `core-idle` seems to work every time:

`profile-cond=not get("core-idle", default_value) and get("audio-params/channel-count", default_value) > 2`

Checking `vo-configured` works most of the time, but it sometimes stalls, I'm guessing it's stalls if the ao thread starts before the vo thread.

I'm guessing `core-idle` is after both ao and vo are configured, which is why it works every time.

**Comment by Dudemanguy** [comment]
Not able to reproduce here (linux and pipewire). If this is still a problem, feel free to reopen.
