### ISSUE TITLE
Shift + Click & Drag to queue URLs not functioning under Chromium-based browsers

### ISSUE THREAD

**Issue by twingofan** [mpv-player/mpv#8673]
### Important Information

Provide following Information:
- mpv version `0.33.0`
- Linux Distribution and Version `Void Linux x86_64 glibc`
- Source of the mpv binary `xbps`
- Window Manager and version `i3-gaps 4.19.1`
- GPU driver and version `Nvidia 460.67`

 ### Reproduction steps
 `mpv -v -v --no-config https://www.youtube.com/watch\?v\=aqz-KE-bpKQ > mpv.log`
Shift drag URL (https://www.youtube.com/watch?v=YE7VzlLtp-4) from Chromium-based browser

Reproduces on my machine with vanilla Chromium 89.0.4389.82 and Vivaldi 3.6.2165.40
mpv works as expected when shift-dragging from Firefox 86.0.1 as well as with local files from Thunar 4.16.5
### Expected behavior
mpv queues URL into playlist without interrupting current playback as per https://github.com/mpv-player/mpv/issues/2166
### Actual behavior
mpv clears the playlist and plays new video immediately
logs show that dragging from Chromium sets "replace" flag while dragging from other sources sets "append-play"
### Log file
[mpv.chrome.log](https://github.com/mpv-player/mpv/files/6191925/mpv.chrome.log)
[mpv.firefox.log](https://github.com/mpv-player/mpv/files/6191927/mpv.firefox.log)

**Comment by brpy** [comment]
I can confirm this issue on Gnome, Kde using Google Chrome and Brave.

There should atleast to be a enqueue option/script.

**Comment by Dudemanguy** [comment]
Just as an FYI, this is mostly Chromium to implement (a quick test shows it's still broken). If they send mpv `replace` instead of `append` via the DnD protocols (works the same way on x11 and wayland in this case), there's nothing we can do about it. In theory, your window manager/compositor could override it though.

**Comment by Dudemanguy** [comment]
>there's nothing we can do about it

Well I guess that was a lie. We have an option to override the behavior now (`--drag-and-drop`). It would still be nicer if Chromium fixed this (no clue if it's still broken or not; didn't check).
