### ISSUE TITLE
mpv pseudo protocol

### ISSUE THREAD

**Issue by gitpubber** [mpv-player/mpv#8675]
1) vlc has its own pseudo protocol `vlc://`
2) `vlc://URI` when clicked upon, streams/plays/opens `URI`  in VLC.
3) I would request same feature in mpv namely `mpv://` protocol.
4) `mpv://URI` when clicked upon , must stream/play/open `URI` in mpv.
5) This feature eases the case of streaming. website would include `mpv://` URI, which when clicked would stream video in mpv.
6) in linux, we can use `xdg-open` , please take look at this [open-in-mpv](https://github.com/Baldomo/open-in-mpv/blob/master/install-protocol.sh) 
7) regarding security issues of playing content behind url, content will only be played when the link  is being clicked/opened.

I hope/wish/request that this feature be implemented.

Thanks

**Comment by CounterPillow** [comment]
1. Duplicate of https://github.com/mpv-player/mpv/issues/7985
2. I still think this is an exceedingly bad idea, security wise
