### ISSUE TITLE
Youtube translated title's dont stick

### ISSUE THREAD

**Issue by mjsir911** [mpv-player/mpv#8676]
### Important Information

```
$ mpv --version
Warning: option --cache-secs is deprecated and might be removed in the future (will use unlimited time).
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: 4.3.2
$ uname -a
Linux Ridl3y 5.4.97-gentoo-x86_64 #3 SMP Thu Feb 18 20:23:00 PST 2021 x86_64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz GenuineIntel GNU/Linux
```
`mpv` compiled by gentoo's ebuild

### Reproduction steps

```
mpv "https://www.youtube.com/channel/UCNElM45JypxqAR73RoUQ10g" --no-config --force-window=immediate
```
Keep a close eye on the title bar while the first video loads

### Expected behavior

The title bar displays "inabakumori - Lagtrain (Vo. Kaai Yuki) / 稲葉曇『ラグトレイン』Vo. 歌愛ユキ"

### Actual behavior

The title bar displays "稲葉曇『ラグトレイン』Vo. 歌愛ユキ"

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/6202395/output.txt)

**Comment by mjsir911** [comment]
Seems to be at least somewhat a youtube-dl problem: 
- ytdl-org/youtube-dl#28421
- ytdl-org/youtube-dl#27499
- #ytdl-org/youtube-dl#10758

Feel free to close, even if the title switching is wierd

**Comment by Akemi** [comment]
seems like an upstream issue. for rapid changing of the title it might be best to open a new issue and describe the problem properly.
