### ISSUE TITLE
Invalid audio PTS (TS+HEVC+Opus)

### ISSUE THREAD

**Issue by jaccc** [mpv-player/mpv#8678]
### Important Information

Provide following Information:
- mpv version 0.33.0
- Linux Distribution and Version Gentoo ~amd64
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Window Manager and version XFCE
- GPU driver and version Intel
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
record ts (hevc+vaapi+opus) using ffmpeg from webcam
Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Log file
$ mpv bak.2c.ts 
 (+) Video --vid=1 (hevc 1280x720 5.000fps)
 (+) Audio --aid=1 (opus 2ch 48000Hz)
Using hardware decoding (vaapi-copy).
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
Invalid audio PTS: 0.100000 -> 0.290100
Invalid audio PTS: 0.390100 -> 0.501333
AV: 00:00:01 / 00:14:58 (0%) A-V:  0.000
Invalid audio PTS: 1.387289 -> 1.576756

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:01 / 00:14:58 (0%) A-V:  0.532 ct:  0.181
Invalid audio PTS: 2.559211 -> 2.685789
AV: 00:00:02 / 00:14:58 (0%) A-V:  0.549 ct:  0.358
Invalid audio PTS: 3.151567 -> 3.254067
AV: 00:00:02 / 00:14:58 (0%) A-V:  0.527 ct:  0.530
Invalid audio PTS: 3.823456 -> 3.933356
AV: 00:00:03 / 00:14:58 (0%) A-V:  0.499 ct:  0.697
Invalid audio PTS: 4.346544 -> 4.453000
AV: 00:00:04 / 00:14:58 (0%) A-V:  0.465 ct:  0.858
Invalid audio PTS: 5.022400 -> 5.133689
AV: 00:00:04 / 00:14:58 (1%) A-V:  0.501 ct:  1.011
Invalid audio PTS: 5.550400 -> 5.652767
AV: 00:00:05 / 00:14:58 (1%) A-V:  0.456 ct:  1.168
Invalid audio PTS: 6.224000 -> 6.341500
AV: 00:00:05 / 00:14:58 (1%) A-V:  0.436 ct:  1.319
Invalid audio PTS: 6.754933 -> 6.858600
AV: 00:00:06 / 00:14:58 (1%) A-V:  0.528 ct:  1.570

Exiting... (Quit)

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
please properly fill out the issue template.

**Comment by jaccc** [comment]
ffmpeg -f alsa -ac 2 -i pulse -vaapi_device /dev/dri/renderD128 -framerate 5 -f v4l2 -video_size 1280x720 -i /dev/video0 -vf 'format=nv12,hwupload' -c:v hevc_vaapi -c:a libopus vlc.ts

[output.txt](https://github.com/mpv-player/mpv/files/6260790/output.txt)

**Comment by jaccc** [comment]
less "Invalid audio PTS" messages with new file, upgraded ffmpeg to 4.4 and mpv 0.33.1

mpv   vlc.ts
 (+) Video --vid=1 (hevc 1280x720 5.000fps)
 (+) Audio --aid=1 (opus 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
Using hardware decoding (vaapi-copy).
VO: [gpu] 1280x720 yuv420p
Invalid audio PTS: 0.100000 -> 0.312900
Invalid audio PTS: 0.412900 -> 0.574733
AV: 00:00:01 / 01:04:59 (0%) A-V:  0.000

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:13 / 01:04:59 (0%) A-V:  0.475 ct:  3.369

**Comment by jeeb** [comment]
I would recommend checking the timestamps of that MPEG-TS mux.

`ffprobe -select_streams a -of json -show_streams -show_packets -show_frames -i INPUT > dump.json`
That should show what FFmpeg thinks of the packets.

If the duration of packets read and the coded audio duration do not match, then either the mux is incorrect, or there is a bug in FFmpeg's reading of opus in MPEG-TS.

As an alternative view the least bad open source solution seems to be [DVB Inspector](https://sourceforge.net/projects/dvbinspector/). It is Java and thus kind of meh, but still - it is a nice 2nd opinion.
