### ISSUE TITLE
[Feature reqeust] Delete file permanently shortkey

### ISSUE THREAD

**Issue by anonymoustly** [mpv-player/mpv#8679]
shortkey to remove video file permanently from disk.

**Comment by anonymoustly** [comment]
Maybe only working in pauze mode to prevent unwanted deletion.

**Comment by Akemi** [comment]
that's something for a script or a shortcut.

see https://github.com/mpv-player/mpv/wiki/User-Scripts and the delete-file script as an example (https://github.com/mpv-player/mpv/wiki/User-Scripts). 

se also duplicate issue #4329 and the example script in there for (l)unix

**Comment by guidocella** [comment]
If you just want to remove files permanently on Unix-like systems, you can use also a keybinding like
`Ctrl+Shift+Alt+r run rm -- ${path}; playlist-remove current`
instead of a script.
