### ISSUE TITLE
Window size becomes smaller when rotate runtime video

### ISSUE THREAD

**Issue by nzm001** [mpv-player/mpv#8680]
Platform: Linux Mint 20

Screen size: 2560*1440

mpv version:

```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 26 06:59:44 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72
```

input.conf

```
r cycle-values video-rotate 270 180 90 0
t cycle-values video-rotate 90 180 270 0
```

While I can rotate video, window size becomes smaller.

Original video (400\*800) -> rotate 90 degrees -> Video (smaller than 800\*400) -> rotate back to normal -> Video (smaller than 400\*800)

If I rotate in fullscreen mode, then exit fullscreen, the window size will be 800\*400 or 400\*800.

If I resize the rotated video (smaller than 800\*400) with Alt+1, nothing happens. Resize with Alt+2 and Alt+1, then the windows size is 400\*800 (with large black bands), not 800\*400.

Is this my own problem?

**Comment by Akemi** [comment]
i can't reproduce this, though i am on macOS and the windowing system is a different one. i think it's the the best to open a proper issue instead of a question.
