### ISSUE TITLE
mpv does not play audio, VLC plays it ([cplayer] Could not open/initialize audio device -> no sound.)

### ISSUE THREAD

**Issue by slrslr** [mpv-player/mpv#8684]
### Important Information

Provide following Information:
- mpv version 0.33.0-dirty
- Linux Distribution and Version 5.10.23-1-MANJARO
- Source of the mpv binary official package of Manjaro Linux
- Window Manager and version: XFCE
- GPU driver and version
- Possible screenshot or video of visual glitches

### Detail

Hello,

for one file, the mpv does not play audio, vlc does - [MediaInfo is here](https://bin.disroot.org/?f280642a2ecef0a1#BJMh6wdyeSq8jXVxRU3Ld8iq33toEbewo5LBvqxfadto). [Verbose mpv log is here](https://bin.disroot.org/?e6e1d72c74ef9242#6PTNrppUSWwx2k4Qiv5rS3UnD1jVLJGHqMZCXxdKykiL). While VLC plays the audio, can mpv be made to play it too by defaulot, if not, can i convert the file metadata using ffmpeg so mpv plays the audio?

**Comment by LaserEyess** [comment]
FYI the issue template is there for a reason, you shouldn't have modified it. In particular the sample file would have been most helpful here, as well as reproduction steps, which you also neglected to provide.

This looks like a configuration issue, so without reproduction steps or a file it's impossible to tell, but it looks like pulse fails for some reason and then it tries to fall back to ALSA/JACK, which I assume you don't have.
```
[ao/alsa] opening device 'default'                                                                                                                                                                                                                                             
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
[ao/alsa] Playback open error: No such file or directory
...
[ao/jack] result: stereo                                                                                                                                                                                                                                                       
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
[ao/jack] cannot open server
```

**Comment by slrslr** [comment]
@LaserEyess Hello, the file can be downloaded [here](https://bin.disroot.org/?7b29566dc1fd5636#4TLsaga5xmqKWF8xpx1mWQhCnSa3bcBPQM3fwQz7RnxQ), and the steps to reproduce? Open the file via file manager (in my case Dolphin).

**Comment by CounterPillow** [comment]
Our ao failure logging seems inadequate, even if this turns out to be a user mistake then there is definite room for improvement in mpv here. Failing AOs shouldn't just be silent in a full verbose log.

**Comment by LaserEyess** [comment]
@slrslr I can't download 2.1 GB at 250 KB/s, can you please upload a smaller sample of the file, assuming that can reproduce the issue?

**Comment by LaserEyess** [comment]
Something like `ffmpeg -i in.mp4 -ss 0 -t 10 -c:v copy -c:a copy out.mp4` should work. Verify that it still reproduces the issue though.

**Comment by slrslr** [comment]
Good command, it created the sample, yet the sample and the original no longer have issue (sound is played ok now). Any ideas how to discover why the playback failed or how mpv can handle it and play it as VLC player was able to play it and mpv not? Or mpv reports some user friendly error notice in gui?

**Comment by LaserEyess** [comment]
If you can't reproduce it with just the clip, it may be something with the container that is making mpv choke on it. Can you try ``mpv --no-config --msg-level=ao=trace,ao/pulse=trace --log-file=mpv_sucks.log` and upload the resulting log file?

**Comment by slrslr** [comment]
[output here please](https://bin.disroot.org/?ef05d1cfcb4e660e#9FoQ3Jc78sLxMzZFRgdr7vEzFrhib3VKaKJ2BYung33H)

**Comment by LaserEyess** [comment]
Sorry, I meant run it with the file:
 ```
mpv --no-config --msg-level=ao=trace,ao/pulse=trace --log-file=mpv_sucks.log the_file_that_doesn't_work.mp4
````
You can also try
 ```
mpv --no-config --msg-level=ao=trace,ao/pulse=trace --log-file=mpv_sucks.log the_file_that_does_work.mp4
````

**Comment by slrslr** [comment]
Thanks, i have just found that when i use some application to launch the Dolphin file manager session, this Dolphin window has different design from the Dolphin launched normally from Linux apps menu. Maybe it is less privilege session or something. I will ask on my Linux distro forum.

And under this "externally launched" Dolphin the audio fails. Fortunately the Dolphin has some terminal (F4 key) and when i run your command, the output is: 

```
 (+) Video --vid=1 (*) (h264 640x360 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
error: XDG_RUNTIME_DIR not set in the environment.
[ao] Trying audio driver 'pulse'
[ao/pulse] requested format: 44100 Hz, stereo channels, floatp                                                                                                                                                                                                                 
[ao/pulse] Library version: 14.2.0                                                                                                                                                                                                                                             
[ao/pulse] Proto: 34                                                                                                                                                                                                                                                           
[ao/pulse] Server proto: 4294967295                                                                                                                                                                                                                                            
[ao] Trying audio driver 'alsa'                                                                                                                                                                                                                                                
[ao/alsa] requested format: 44100 Hz, stereo channels, floatp                                                                                                                                                                                                                  
[ao/alsa] using ALSA version: 1.2.4                                                                                                                                                                                                                                            
[ao/alsa] opening device 'default'                                                                                                                                                                                                                                             
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
[ao/alsa] Playback open error: No such file or directory
[ao] Trying audio driver 'jack'
[ao/jack] requested format: 44100 Hz, stereo channels, floatp                                                                                                                                                                                                                  
[ao/jack] Channel layouts:                                                                                                                                                                                                                                                     
[ao/jack]  - waveext                                                                                                                                                                                                                                                           
[ao/jack] result: stereo                                                                                                                                                                                                                                                       
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
[ao/jack] cannot open server
[ao] Failed to initialize audio driver 'jack'
Could not open/initialize audio device -> no sound.
Audio: no audio
VO: [gpu] 640x360 yuv420p
V: 00:01:05 / 00:01:43 (63%)

Exiting... (Quit)
```
full output [here](https://bin.disroot.org/?709a04dcc8f4cf23#98T8mFj7WiegPQobCC6E2vDwDmuGb7W7CQHDBEYPKSK5) if needed

**Comment by LaserEyess** [comment]
I'm not sure what's happening here, it looks like pulse is just refusing to initialize and falling back on jack/alsa which you don't have.

**Comment by tobiasjakobi** [comment]
The problem here probably is the missing XDG_RUNTIME_DIR. PA needs this to function properly, so slrslr should check first why it isn't set in the shell from where mpv is launched.

**Comment by slrslr** [comment]
> check first why it isn't set in the shell from where mpv is launched.

i would like to know how to discover the reason, at this moment (after reboot) "$ env|grep -i xdg" shows "XDG_RUNTIME_DIR=/run/user/1000" ([full output](https://bin.disroot.org/?a15076f849d84baa#CGEijYPhEQGsMR877BJZDffDxERzbPxbg6NAjpBkMUMN)) and audio works, no longer issue.

**Comment by LaserEyess** [comment]
I think mpv should give a better error in this case, but mpv isn't responsible for this variable, your login/display manager is. If for whatever reason it isn't setting this variable 100% of the time, it's a bug in that software.
