### ISSUE TITLE
Expose Colour Temperature controls to user

### ISSUE THREAD

**Issue by willwrong** [mpv-player/mpv#8686]
### Expected behavior of the wanted feature
Expose colour temperature (warmer/cooler, by degrees or percentage?) of MPV instance so it can be controlled via an option (mpv colour-temperature=xyz, perhaps?)

**Comment by hooke007** [comment]
I use the video filter to solve this kind of problems.
(No support for native hwdec)
To edit your `input.conf` like this:
```
KP1       vf toggle colortemperature=temperature=5500
KP2       vf toggle colortemperature=temperature=6500
KP3       vf toggle colortemperature=temperature=9300
``` 
And you can see the output in the runtime.

@Akemi I tried to use `cycle-values` to make it easier to realise, but I couldn't. How could I write the correct syntax?

**Comment by Akemi** [comment]
```
X cycle-values vf "colortemperature=temperature=5500" "colortemperature=temperature=6500" "colortemperature=temperature=9300" ""
```

**Comment by hooke007** [comment]
Thanks, however this will remove the any other filters (which have been added before). Would you have the better solution?

**Comment by Akemi** [comment]
yes it will. you have to write a script for it otherwise, i believe.

**Comment by hooke007** [comment]
Wow, I will have a try if possible.

**Comment by willwrong** [comment]
Hi Akemi,

Thanks so much for this! This, plus a bit of scripting accomplishes exactly what I am after, and thus I will close the issue as I don't believe it requires a great deal more attention.

**Comment by willwrong** [comment]
@Akemi Sorry to resurrect this matter, but a quick one: is there any method where I would utilize both this and native hwdec, or are the two more or less mutually exclusive?

Thanks!

**Comment by philipl** [comment]
You'd have to write an accelerated version of the filter that can run on the gpu, otherwise it has to download the frames to system memory to run the cpu filter and then reupload to the gpu for display. That isn't always disastrous but it is slower and obviously increases cpu utilization.

**Comment by willwrong** [comment]
Thanks for the insight! Probably beyond my skillset, but maybe in time!

**Comment by haasn** [comment]
> You'd have to write an accelerated version of the filter that can run on the gpu, otherwise it has to download the frames to system memory to run the cpu filter and then reupload to the gpu for display. That isn't always disastrous but it is slower and obviously increases cpu utilization.

This functionality exists in [libplacebo](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/include/libplacebo/colorspace.h#L365), which means that it could be added to mpv via #8799 (or simply copy/pasted over).

**Comment by lavinnyv** [comment]
is there a way to adjust the individual color channels - rgb - instead of full color temperature? i just want to pull a few points of green out. my ideal solution would be putting -5 r, -5 g, -5 b on a key to step down. from there i can figure out how to change that to 10 or 1 or positive if i need.
