### ISSUE TITLE
Display "forced track" flag

### ISSUE THREAD

**Issue by damian101** [mpv-player/mpv#8688]
At the moment it's not possible to see whether a subtitle (or audio) track has the "forced track" flag enabled or not.
This would be pretty useful though as it's otherwise often impossible to distinguish the forced subtitle track from the regular one in the same language without playing back the video.

My proposal would be to just add [forced] to the end of an audio or subtitle track when the "forced track" flag is enabled, so for an unnamed forced English subtitle track it would be displayed as "[eng] [forced]" instead of just "[eng]".

**Comment by garfieldbanks** [comment]
Is there an ini setting or something for this?

I'd like to make mpv follow plex conventions for cc/sdh/forced subtitles:
https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/#toc-3

VideoName.eng.forced.ext
VideoName.eng.sdh.ext
VideoName.eng.cc.ext

**Comment by garfieldbanks** [comment]
OK I found I can add "sub-auto=fuzzy" to mpv.conf and it finds the subtitles but it labels them unknown even though they have .eng as part of the filename. This seems like a definite bug.

**Comment by Dudemanguy** [comment]
As of 5c4852d1730c415fc9311a39c6f7003d9c914792, there's a `sub-forced-only-cur` property which covers this I believe. I think the default OSC also has a toggle now if there are forced subtitles.
