### ISSUE TITLE
Add `secondary-sub-text` property

### ISSUE THREAD

**Issue by fxmarty** [mpv-player/mpv#8689]
Hello,

### Expected behavior of the wanted feature

We have the property `sub-text` https://mpv.io/manual/master/#command-interface-sub-text to observe the text of the current sub. It would be nice to have a similar property for the secondary sid, possibly called `secondary-sub-text`.

**Comment by Dudemanguy** [comment]
Added with #8822.

**Comment by fxmarty** [comment]
@Dudemanguy @zsoltiv Thanks a lot!
