### ISSUE TITLE
Fail to build mpv using mpv-build on Fedora

### ISSUE THREAD

**Issue by zluo01** [mpv-player/mpv#8690]
### mpv version and platform versions

build method: mpv-build
mpv version: master
platform: Fedora 33 (5.11.10)

### Reproduction steps

clone mpv-build
run ./rebuild -j4

### Expected behavior
Successfully Build

### Actual behavior

```
/usr/bin/ld: /home/mike/Documents/SoftwareSettings/mpv/mpv-build/build_libs/lib/libass.a(ass_fontconfig.o): undefined reference to symbol 'FcConfigCreate'
/usr/bin/ld: /usr/lib64/libfontconfig.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
```

### Log file
https://0x0.st/-blj.log
https://0x0.st/-ble.log
https://0x0.st/-bl_.log

Thank you.

**Comment by tlalexander** [comment]
Hmm I am just having this issue. Was there a solution?

**Comment by zluo01** [comment]
> Hmm I am just having this issue. Was there a solution?

https://github.com/mpv-player/mpv-build/issues/152#issuecomment-812191249

**Comment by tlalexander** [comment]
Thank you!
