### ISSUE TITLE
MPV Interface

### ISSUE THREAD

**Issue by kusuoh** [mpv-player/mpv#8699]
Hi, sorry im new to mpv, how do i get this exact same interface from the website.
Thanks

![mpv](https://user-images.githubusercontent.com/82033411/113704777-2e2df700-970f-11eb-8e96-b667ba052e02.png)

**Comment by avih** [comment]
The window interface (border, buttons, decoration) is done by the window manager. Some support configurations and themes, some do not.

You will have to consult the documentation of your window manager and/or the OS.

**Comment by CounterPillow** [comment]
This one in particular is KDE's Breeze Dark theme.
