### ISSUE TITLE
Play looping video during long audio file.

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8703]
Basically I want to treat a short looping video file as cover art to display when playing an audio file.

If I add the video with the command 'video-add' I can only get it to play once, but would it be possible in MPV to make it play repeatedly and still retain the ability to seek within the audio file?

**Comment by Akemi** [comment]
you can do something like `--vf=loop=loop=-1:size=X` where X is the size in number of frames you want to repeat. see ffmpeg loop filter https://ffmpeg.org/ffmpeg-filters.html#loop.

**Comment by hedgehog90** [comment]
@Akemi so I gave this a go and implemented something using the loop filter, but last night while streaming from my server there was an issue. For long(ish) video loops (30 secs+) MPV was consuming more and more memory. After a couple hours running a playlist of normal videos with some audio w/ looped video items, I checked the memory usage and it was around 6GB on my 8GB capacity server.

**Comment by Akemi** [comment]
you should open a new issue. it's hard to say what's going on. it could also be an ffmpeg issue but we need to debug that with an easily reproducible case.
