### ISSUE TITLE
libmpv on windows won't start 

### ISSUE THREAD

**Issue by manfromth3m0oN** [mpv-player/mpv#8706]
### Important Information

Information:
- Version: 20210404-git
- Windows 10
- Precompiled lib from sourceforge 

I've embeded mpv in an opengl context which works perfectly on gnu/linux but when the program is compiled for windows the program does not function. Exiting from this call
```
err = mgl.InitGL()
```
with the response 
```
2021/04/09 16:04:55 main.go:152: -19 operation not implemented
```

### Reproduction steps

This issue should be reproducible by trying to compile my code via mingw/cygwin on windows

### Log file

The only avaliable logs I have been able to extract from the program are as listed above

### Sample files

You can get the source [here](https://github.com/manfromth3m0oN/chanshare) and try building for yourself

**Comment by manfromth3m0oN** [comment]
I think the issue is that the go bindings I am using is using the old rendering method.
I've found a workaround for now so I'll close the issue.

**Comment by Akemi** [comment]
i am closing this then.
