### ISSUE TITLE
How can I see the picture when recording like potplayer?

### ISSUE THREAD

**Issue by RallyQ** [mpv-player/mpv#8707]
### Important Information

Provide following Information:
- mpv version
- mpv --version
mpv 0.33.0-88-gd1be8bb606 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 28 09:25:17 +08 2021
FFmpeg library versions:
   libavutil       56.66.100
   libavcodec      58.126.100
   libavformat     58.68.100
   libswscale      5.8.100
   libavfilter     7.107.100
   libswresample   3.8.100
FFmpeg version: git-2021-02-28-85ab9deb

- Windows Version
- win10 1803
- AMD Ryzen 5 2400G with Radeon Vega Graphics 3.6 GHz
- 32G ram
- 
编码录制dshow设备，文件没有总时长，怎样实时显示画面？
mpv --ovc=hevc_amf --oac=aac --of=matroska --o=test.mkv av://dshow:video="@device_pnp_\\?\usb#------":audio="@device_cm_-----" 
用这个参数可以录制USB采集卡的TV视频音频，按ctrl+c结束录制，能正常播放这个录制的文件，但视频没有总时长，无法拖动进度条播放。
另外录制时没有采集卡画面显示。

两个问题：
1，怎样才能让mpv停止编码后视频时长正常？
2，编码时能否实时显示画面？
谢谢！

machine translation：
Coding recording dshow equipment, the file has no total duration, how to display the picture in real time?
mpv --ovc=hevc_amf --oac=aac --of=matroska --o=test.mkv av://dshow:video="@device_pnp_\\?\usb#------":audio="@device_cm_-----" 
With this parameter, TV video and audio from USB acquisition card can be recorded. Press ctrl+c to finish recording, and the recorded file can be played normally, but the video has no total duration, Unable to drag the progress bar to play.
In addition, there is no image display of acquisition card during recording.
Two questions:
1. how can the video duration be normal after mpv stops encoding?
2. Can the picture be displayed in real time when coding?
thank!

**Comment by RallyQ** [comment]
第一个问题我自己解决了，--ofopts=movflags=frag_every_frame或--ofopts=movflags=frag_keyframe参数，录制的文件即可正常显示总时长
mpv --ovc=hevc_amf --oac=aac --of=mp4 --ofopts=movflags=frag_every_frame --o=xxx.mp4 av://dshow:video="@device_pnp_...":audio="@device_cm_..."

**Comment by RallyQ** [comment]
按q结束录制

**Comment by RallyQ** [comment]
怎样能像potplayer那样有画面的录制呢？

**Comment by Akemi** [comment]
it's impossible for us to help you if you don't speak/write in a language we can understand. with that being said english is our preferred language.

**Comment by RallyQ** [comment]
How can I see the picture when recording like potplayer?

**Comment by Akemi** [comment]
you probably need to set the demuxer options for your input:

```
--demuxer-lavf-o=video_size=1920x1080 
--demuxer-lavf-o=pixel_format=uyvy420
--demuxer-lavf-o=framerate=23.976
```

otherwise i am not sure what you are asking.

**Comment by RallyQ** [comment]
> 
> 
> 您可能需要为输入设置解复用器选项：
> 
> ```
> --demuxer-lavf-o=video_size=1920x1080 
> --demuxer-lavf-o=pixel_format=uyvy420
> --demuxer-lavf-o=framerate=23.976
> ```
> 
> 否则我不确定你在问什么。

Record and play simultaneously
or
I want mpv recording to play dshow devices at the same time

**Comment by Akemi** [comment]
i believe that is not possible. you would need to open the output with a different mpv instance.

**Comment by RallyQ** [comment]
> 
> 
> i believe that is not possible. you would need to open the output or the device with a different mpv instance.
Potplayer can be recorded while watching, and I hope mpv can do the same
