### ISSUE TITLE
Mpv 0.32 , 0.33 does not play m3u files in ubuntu 20.10

### ISSUE THREAD

**Issue by semola** [mpv-player/mpv#8709]
The program smplayer 21.10 use mpv 0.32 or 0.33 version.
The m3u files does not open with this version of mpv.
In windows i resolved  this issue replaced the mpv folder by the mpv folder from splayer 19.10
In linux i didn't fix it yet.
Have you any solution about linux?
Thank you.

**Comment by CounterPillow** [comment]
Follow the issue template or we cannot attempt to reproduce the issue or help you.
