### ISSUE TITLE
YouTube URL makes MPV go sleepy time (crash) on macOS

### ISSUE THREAD

**Issue by StupidRepo** [mpv-player/mpv#8710]
### Important Information

Provide following Information:
- mpv version: The version made on 5th April 2021
- macOS Version: Big Sur (11.1)
- [Source of the mpv binary or bundle](https://laboratory.stolendata.net/~djinn/mpv_osx/)
- If known which version of mpv introduced the problem: I don't know, I just got it.
- Possible screenshot or video of visual glitches: All you gotta know is, Drag YouTube video on MPV window and wait like half a sec and it goes bye bye.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases
**Well there is no .app and I am NOT compiling it. Go shove your head in horse poo if you're gonna ask me to do that.**

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

**u wot?**

### Expected behavior
Supposed to play the YouTube video I guess?

### Actual behavior
Crashes when dragging YouTube URL to MPV.

### Log file

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

In the case of a crash please provide the macOS Crash Report (Backtrace).

**My version of macOS is fu😃ed and so broken that it doesn't show crash logs after like 20 minutes or something so uh... maybe later?**

The issue will be closed for ignoring the issue template.
**Ok, whatever.**

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

[https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/https://laboratory.stolendata.net/~djinn/mpv_osx/](https://laboratory.stolendata.net/~djinn/mpv_osx/)

**Comment by StupidRepo** [comment]
Note: It seems that it's the app quitting itself as Console.app isn't showing anything in crashes.

**Comment by StupidRepo** [comment]
Note 2: Dragging random files (files that it can't play) also seems to crash it but CMD + O and CMD + whatever key it is + O (Open URL) seems to crash it too.

**Comment by StupidRepo** [comment]
Found a fix: Use `path/to/mpv.app/Contents/MacOS/mpv  FILE-YOU-WANNA-OPEN.mp3` in Terminal and boom, you can use any key to play it. I don't think this works with mp4's although this isn't much of a fix.

**Comment by StupidRepo** [comment]
### I found the issue!
```[ytdl_hook]  
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.```

**Comment by Akemi** [comment]
yeah okay then.
