### ISSUE TITLE
Hiding GUI with C Plugin does not allow the use of key bindings

### ISSUE THREAD

**Issue by WeebNetsu** [mpv-player/mpv#8711]
I don't know if this is a bug or a feature, but I'm working on a Background Music Player based off of MPV, I'm building this application with C++ and one of the problems I can't seem to figure out how to fix is still being able to use key bindings without displaying the video. When you run (in the terminal) `mpv video.mp4 --no-video` then you can still use [SPACE] to pause, [>] to skip and all the other keys, even without the video being displayed... How do I achieve this? The below code shows you what I've been working on as a test and using the keys when I don't disable the video works fine, but once the video is removed the keys won't work anymore:
```
#include <iostream>
#include <mpv/client.h>

static inline void check_error(int status)
{
    if (status < 0)
    {
        std::cout << "mpv API error: " << mpv_error_string(status) << std::endl;
        exit(1);
    }
}

int main(int argc, char *argv[])
{
    if (argc != 2)
    {
        std::cout << "pass a single media file as argument" << std::endl;

        return 1;
    }

    mpv_handle *ctx = mpv_create();
    if (!ctx)
    {
        std::cout << "failed creating context" << std::endl;
        return 1;
    }

    // Enable default key bindings, so the user can actually interact with
    // the player (and e.g. close the window).
    check_error(mpv_set_option_string(ctx, "input-default-bindings", "yes"));
    mpv_set_option_string(ctx, "input-vo-keyboard", "yes");
    int val = 1;
    check_error(mpv_set_option(ctx, "osc", MPV_FORMAT_FLAG, &val));

    // Done setting up options.
    check_error(mpv_initialize(ctx));

    // Play the file passed in as an argument when executing program.
    const char *cmd[] = {"loadfile", argv[1], NULL};
    check_error(mpv_command(ctx, cmd));

    // THE BELOW
    // the below code allows you to disable the video (similar to using --no-video in the terminal)
    // when I enable this I can no longer use the keybindings to control what's happening (like space to pause)
    // how do I get around this?
    check_error(mpv_set_option_string(ctx, "vid", "no"));

    // THE ABOVE

    check_error(mpv_set_option_string(ctx, "shuffle", "yes")); // shuffle videos
    check_error(mpv_set_option_string(ctx, "loop-playlist", "yes")); // loop playlists
    // Let it play, and wait until the user quits.
    while (1)
    {
        mpv_event *event = mpv_wait_event(ctx, 10000);
        std::cout << "event: " << mpv_event_name(event->event_id) << std::endl;

        if (event->event_id == MPV_EVENT_SHUTDOWN)
            break;
    }

    mpv_terminate_destroy(ctx);
    return 0;
}
```
The piece of code I use to disable the video showing is `check_error(mpv_set_option_string(ctx, "vid", "no"));` but by using that I can not interact with MPV anymore, it doesn't respond to my key presses anymore. Any help would be highly appreciated!

**Comment by WeebNetsu** [comment]
I did the same by executing a Lua script from the plugin, I received the same result, but when I did `mpv video.mp4 --scripts="test.lua"` key bindings worked fine, but when I did `check_error(mpv_set_property_string(ctx, "scripts", "test.lua"));` (the scripts did the same thing: hide the video), I could not use key bindings again... This is a problem related to the C Plugin it seems, since the script worked fine without the C Plugin, but caused the same problem as before when using the C Plugin...

**Comment by avih** [comment]
> When you run (in the terminal) mpv video.mp4 --no-video then you can still use [SPACE] to pause, [>] to skip and all the other keys, even without the video being displayed... How do I achieve this?

mpv reads the key presses at the terminal (stdin or /dev/tty, I don't quite remember). same as any terminal application reads keypresses.

**Comment by WeebNetsu** [comment]
Yeah, but it doesn't do that anymore when you disable the GUI with the C Plugin

**Comment by avih** [comment]
Right, because libmpv can own the window which it can launch, but it doesn't own the terminal.

Your program is launched from the terminal, so you read the keys and, if you want, send them as ketypress commands to mpv.

**Comment by WeebNetsu** [comment]
I see! That makes sense!
Thank you so much for the help, this will help me a lot! :)
