### ISSUE TITLE
How to get gamepad/joystick support?

### ISSUE THREAD

**Issue by wrybread** [mpv-player/mpv#8714]
I'm trying to get MPV to accept joystick input on Ubuntu. In the [MPV manual](https://mpv.io/manual/stable/#input) there's this option:

```
--input-gamepad=<yes|no>
Enable/disable SDL2 Gamepad support. Disabled by default.
```

However when I run mpv --input-gamepad=yes I get the following error:

```
$ mpv --input-gamepad=yes
Error parsing option input-gamepad (option not found)
Setting commandline option --input-gamepad=yes failed.
Exiting... (Fatal error)
```

My MPV version:

```
$ mpv --version
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 24 01:50:41 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72
```

I know I can use a utility to change the joystick signals to keystrokes, but this is an old arcade cabinet with a lot of game configurations and I'd rather not make any changes to the joystick signals themselves.

On the same machine I have mplayer working with joystick input by compiling it with joystick support ("./configure --enable-joystick"), then these lines in  /etc/mplayer/input.conf configure joystick support:

```
JOY_RIGHT seek 10
JOY_LEFT seek -10
```

Does anyone have any advice for how I can get joystick working with MPV?

Thanks for any help, and please let me know if any other info would help.

### Log file

[log](https://pastebin.pl/view/raw/4cd55d77)

**Comment by Akemi** [comment]
your mpv is not built with `sdl2` (and `sdl2-gamepad`) support.
