### ISSUE TITLE
Mpv 0.32 , 0.33 does not play m3u files in ubuntu 20.10

### ISSUE THREAD

**Issue by semola** [mpv-player/mpv#8715]
The program smplayer 21.10 use mpv 0.32 or 0.33 version.
The m3u files does not open with this version of mpv.
In windows i resolved this issue replaced the mpv folder by the mpv folder from splayer 19.10
In linux i didn't fix it yet.
When i use smplayer i have this error.

C:/Users/semol/Downloads/smplayer-portable-21.1.0.0/mpv/mpv.exe --no-config --no-quiet --terminal --no-msg-color --input-ipc-server=C:/Users/semol/AppData/Local/Temp/smplayer-mpv-22b4 --msg-level=ffmpeg/demuxer=error -v --no-fs --hwdec=no --sub-auto=fuzzy --vo=direct3d, --priority=normal --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=329420 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=50 --cache=auto --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=.\screenshots --audio-pitch-correction=yes --af-add=@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)'] --volume-max=100 --ytdl=no --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
--term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} http://escape-iptv.com:8800/movie/semola/xxxxxx/47718.mp4

Command line options: '--no-config' '--no-quiet' '--terminal' '--no-msg-color' '--input-ipc-server=C:/Users/semol/AppData/Local/Temp/smplayer-mpv-22b4' '--msg-level=ffmpeg/demuxer=error' '-v' '--no-fs' '--hwdec=no' '--sub-auto=fuzzy' '--vo=direct3d,' '--priority=normal' '--no-input-default-bindings' '--input-vo-keyboard=no' '--no-input-cursor' '--cursor-autohide=no' '--no-keepaspect' '--wid=329420' '--monitorpixelaspect=1' '--osd-level=1' '--osd-scale=1' '--osd-bar-align-y=0.6' '--sub-ass' '--embeddedfonts' '--sub-ass-line-spacing=0' '--sub-scale=1' '--sub-font=Arial' '--sub-color=#ffffffff' '--sub-shadow-color=#ff000000' '--sub-border-color=#ff000000' '--sub-border-size=0.75' '--sub-shadow-offset=2.5' '--sub-font-size=50' '--sub-bold=no' '--sub-italic=no' '--sub-margin-y=8' '--sub-margin-x=20' '--sub-codepage=ISO-8859-1' '--sub-pos=100' '--volume=50' '--cache=auto' '--screenshot-template=cap_%F_%p_%02n' '--screenshot-format=jpg' '--screenshot-directory=.\screenshots' '--audio-pitch-correction=yes' '--af-add=@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)']' '--volume-max=100' '--ytdl=no' '--term-playing-msg=MPV_VERSION=${=mpv-version:}
[debug] INFO_VIDEO_WIDTH=${=width}
[debug] INFO_VIDEO_HEIGHT=${=height}
[debug] INFO_VIDEO_ASPECT=${=video-params/aspect}
[debug] INFO_VIDEO_FPS=${=container-fps:${=fps}}
[debug] INFO_VIDEO_FORMAT=${=video-format}
[debug] INFO_VIDEO_CODEC=${=video-codec}
[debug] INFO_AUDIO_FORMAT=${=audio-codec-name}
[debug] INFO_AUDIO_CODEC=${=audio-codec}
[debug] INFO_AUDIO_RATE=${=audio-params/samplerate}
[debug] INFO_AUDIO_NCH=${=audio-params/channel-count}
[debug] INFO_LENGTH=${=duration:${=length}}
[debug] INFO_DEMUXER=${=current-demuxer:${=demuxer}}
[debug] INFO_SEEKABLE=${=seekable}
[debug] INFO_TITLES=${=disc-titles}
[debug] INFO_CHAPTERS=${=chapters}
[debug] INFO_TRACKS_COUNT=${=track-list/count}
[debug] METADATA_TITLE=${metadata/by-key/title:}
[debug] METADATA_ARTIST=${metadata/by-key/artist:}
[debug] METADATA_ALBUM=${metadata/by-key/album:}
[debug] METADATA_GENRE=${metadata/by-key/genre:}
[debug] METADATA_DATE=${metadata/by-key/date:}
[debug] METADATA_TRACK=${metadata/by-key/track:}
[debug] METADATA_COPYRIGHT=${metadata/by-key/copyright:}
[debug] INFO_MEDIA_TITLE=${=media-title:}
[debug] INFO_STREAM_PATH=${stream-path}
' '--term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0}' 'http://escape-iptv.com:8800/movie/semola/xxxxxxx/47718.mp4'
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
built on Mon Jan 27 12:34:40 +08 2020
ffmpeg library versions:
libavutil 56.38.100
libavcodec 58.67.100
libavformat 58.36.100
libswscale 5.6.100
libavfilter 7.71.100
libswresample 3.6.100
ffmpeg version: git-2020-01-26-5e6210015

Configuration: /home/shinchiro/build/build64/packages/mpv-stable-prefix/src/mpv-stable/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-sdl2 --enable-libarchive --enable-libass --enable-libbluray --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-spirv-cross --enable-vulkan --enable-vapoursynth --prefix=/home/shinchiro/build/build64/install/mingw
List of enabled features: asm atomics build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths drmprime dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gnuc gpl iconv javascript jpeg lcms2 libarchive libass libass-osd libav-any libavcodec libavdevice libavutil libbluray libm libmpv-shared libplacebo lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vulkan wasapi win32-desktop win32-internal-pthreads win32-pipes zlib
Setting option 'config' = 'no' (flags = 8)
Setting option 'quiet' = 'no' (flags = 8)
Setting option 'terminal' = '' (flags = 8)
Setting option 'msg-color' = 'no' (flags = 8)
Setting option 'input-ipc-server' = 'C:/Users/semol/AppData/Local/Temp/smplayer-mpv-22b4' (flags = 8)
Setting option 'msg-level' = 'ffmpeg/demuxer=error' (flags = 8)
Setting option 'v' = '' (flags = 8)
Setting option 'fs' = 'no' (flags = 8)
Setting option 'hwdec' = 'no' (flags = 8)
Setting option 'sub-auto' = 'fuzzy' (flags = 8)
Setting option 'vo' = 'direct3d,' (flags = 8)
Setting option 'priority' = 'normal' (flags = 8)
Setting option 'input-default-bindings' = 'no' (flags = 8)
Setting option 'input-vo-keyboard' = 'no' (flags = 8)
Setting option 'input-cursor' = 'no' (flags = 8)
Setting option 'cursor-autohide' = 'no' (flags = 8)
Setting option 'keepaspect' = 'no' (flags = 8)
Setting option 'wid' = '329420' (flags = 8)
Setting option 'monitorpixelaspect' = '1' (flags = 8)
Setting option 'osd-level' = '1' (flags = 8)
Setting option 'osd-scale' = '1' (flags = 8)
Setting option 'osd-bar-align-y' = '0.6' (flags = 8)
Setting option 'sub-ass' = '' (flags = 8)
Setting option 'embeddedfonts' = '' (flags = 8)
Setting option 'sub-ass-line-spacing' = '0' (flags = 8)
Setting option 'sub-scale' = '1' (flags = 8)
Setting option 'sub-font' = 'Arial' (flags = 8)
Setting option 'sub-color' = '#ffffffff' (flags = 8)
Setting option 'sub-shadow-color' = '#ff000000' (flags = 8)
Setting option 'sub-border-color' = '#ff000000' (flags = 8)
Setting option 'sub-border-size' = '0.75' (flags = 8)
Setting option 'sub-shadow-offset' = '2.5' (flags = 8)
Setting option 'sub-font-size' = '50' (flags = 8)
Setting option 'sub-bold' = 'no' (flags = 8)
Setting option 'sub-italic' = 'no' (flags = 8)
Setting option 'sub-margin-y' = '8' (flags = 8)
Setting option 'sub-margin-x' = '20' (flags = 8)
Setting option 'sub-codepage' = 'ISO-8859-1' (flags = 8)
Setting option 'sub-pos' = '100' (flags = 8)
Setting option 'volume' = '50' (flags = 8)
Setting option 'cache' = 'auto' (flags = 8)
Setting option 'screenshot-template' = 'cap_%F_%p_%02n' (flags = 8)
Setting option 'screenshot-format' = 'jpg' (flags = 8)
Setting option 'screenshot-directory' = '.\screenshots' (flags = 8)
Setting option 'audio-pitch-correction' = 'yes' (flags = 8)
Setting option 'af-add' = '@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)']' (flags = 8)
Setting option 'volume-max' = '100' (flags = 8)
Setting option 'ytdl' = 'no' (flags = 8)
Setting option 'term-playing-msg' = 'MPV_VERSION=${=mpv-version:}
[debug] INFO_VIDEO_WIDTH=${=width}
[debug] INFO_VIDEO_HEIGHT=${=height}
[debug] INFO_VIDEO_ASPECT=${=video-params/aspect}
[debug] INFO_VIDEO_FPS=${=container-fps:${=fps}}
[debug] INFO_VIDEO_FORMAT=${=video-format}
[debug] INFO_VIDEO_CODEC=${=video-codec}
[debug] INFO_AUDIO_FORMAT=${=audio-codec-name}
[debug] INFO_AUDIO_CODEC=${=audio-codec}
[debug] INFO_AUDIO_RATE=${=audio-params/samplerate}
[debug] INFO_AUDIO_NCH=${=audio-params/channel-count}
[debug] INFO_LENGTH=${=duration:${=length}}
[debug] INFO_DEMUXER=${=current-demuxer:${=demuxer}}
[debug] INFO_SEEKABLE=${=seekable}
[debug] INFO_TITLES=${=disc-titles}
[debug] INFO_CHAPTERS=${=chapters}
[debug] INFO_TRACKS_COUNT=${=track-list/count}
[debug] METADATA_TITLE=${metadata/by-key/title:}
[debug] METADATA_ARTIST=${metadata/by-key/artist:}
[debug] METADATA_ALBUM=${metadata/by-key/album:}
[debug] METADATA_GENRE=${metadata/by-key/genre:}
[debug] METADATA_DATE=${metadata/by-key/date:}
[debug] METADATA_TRACK=${metadata/by-key/track:}
[debug] METADATA_COPYRIGHT=${metadata/by-key/copyright:}
[debug] INFO_MEDIA_TITLE=${=media-title:}
[debug] INFO_STREAM_PATH=${stream-path}
' (flags = 8)
Setting option 'term-status-msg' = 'STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0}' (flags = 8)
Waiting for scripts...
[ipc] Starting IPC master
[ipc] Listening to IPC pipe.
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1
[osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite
[osd/libass] Done.
Done loading scripts.
[ffmpeg] Opening http://escape-iptv.com:8800/movie/semola/xxxxxx/47718.mp4
[osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite
[osd/libass] Done.
Set property: shared-script-properties -> 1
[stream] Failed to open http://escape-iptv.com:8800/movie/semola/xxxxxxx/47718.mp4.
Opening failed or was aborted: http://escape-iptv.com:8800/movie/semola/xxxxxxxx/47718.mp4
finished playback, loading failed (reason 4)

Exiting... (Errors when loading file)
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1

**Comment by Akemi** [comment]
you kinda ignored the issue template again. we don't give smplayer support. please try to reproduce the issue with mpv alone. please also do as the issue template asked you to do and try with `--no-config`.

it seems like ffmpeg fails to open the url. though the log is not a full log like the issue template asked for.

**Comment by amariami** [comment]
> 
> 
> The program smplayer 21.10 use mpv 0.32 or 0.33 version.

ask  https://github.com/smplayer-dev/smplayer/discussions

**Comment by Dudemanguy** [comment]
Seems like an smplayer issue. If not, feel free to reopen.
