### ISSUE TITLE
mpv

### ISSUE THREAD

**Issue by pjezek62** [mpv-player/mpv#8720]
Mpv still have a dependency for aom2 despite of the latest release of aom3. With the old dependency there is disfunctional as well as all video players using mpv as a core engine. I use Archlinux and I am among severely affected users incapable to play any video file. 
Please, update mpv for aom3 as soon as possible: Thank you.

**Comment by jeeb** [comment]
Sorry, we're not the ones running Arch linux packaging :) . We specifically have no requirement on libaom 2,3 or anything.

Please have a good day.

**Comment by sfan5** [comment]
It's not on Arch either, looking at the [`ffmpeg` package](https://archlinux.org/packages/extra/x86_64/ffmpeg/) it depends on `aom` which is currently at version 3.0.0.
Hence whatever problem you are seeing comes from somewhere else.
