### ISSUE TITLE
Hope to add Spectrum

### ISSUE THREAD

**Issue by linuxmm9** [mpv-player/mpv#8723]
Good friend

Hope to add Spectrum when playing music,like this:

[https://img.vim-cn.com/1f/ce211df53e93eec25868b02ee1ad5c25351efd.png](url)

Please support this feature :)

**Comment by Akemi** [comment]
this is something you should request from ffmpeg. there are already a few audio to video filters. https://ffmpeg.org/ffmpeg-filters.html#drawgraph

example: `mpv FILE --lavfi-complex='[aid1]asplit[ao][a1];[a1]showspectrum[vo]`. possible values include but are not limited to `showspectrum,` `showwaves,` `avectorscope,` `abitscope`, `adrawgraph`, `ahistogram`, `showcqt`, `showspatial`...
