### ISSUE TITLE
Video file recorded from stream without timestamp

### ISSUE THREAD

**Issue by kfirohana** [mpv-player/mpv#8727]
Hi,
I am using mpv to present stream of raw h.264 video - received from udp connection.

I  record the stream into .mp4 file, and when I play the output video file - the video plays very very fast (seems to be the speed of reading the file).

1) If I use mpv to play the recorded file with the flags (--no-correct-pts --fps=23.976) than the output video is playing with reasonably speed. 
2) If I switch the origin source to local .mp4 movie than the output file is played ok.

I think that the video is being record without timestamp (probably the received raw packets is missing them initially). 

There is a way to add local timestamp to the recorded file? I want to be able to play the output video file on any regular player witout any manipulation.

Thanks,
Kfir

**Comment by RallyQ** [comment]
参考我的解决办法
https://github.com/mpv-player/mpv/issues/8707

**Comment by Akemi** [comment]
please open a proper issue with all infos we ask for.

though you potentially want or need something like this:
```
--demuxer-lavf-o=video_size=1920x1080 
--demuxer-lavf-o=pixel_format=uyvy420
--demuxer-lavf-o=framerate=23.976
```
