### ISSUE TITLE
Generate list of supported protocols in desktop-file dynamically

### ISSUE THREAD

**Issue by prettyv** [mpv-player/mpv#8731]
### Important Information

- mpv 0.33.1
- Arch Linux (up-to-date), binary from community repo

### Reproduction steps

1. In Dolphin, under Arch Linux, navigate to a folder on a SMB-share containing multimedia files.
2. Open any video/audio file with mpv
3. mpv fails with error: ```[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open smb://@server.local:445/Videos/example.mkv.```

### Expected behavior

Dolphin should have more accurate information about supported protocols and pass a ```file://``` URL instead if a given protocol, e.g. smb, isn't supported in a given environment.

### Actual behavior

```mpv```s .desktop-file currently statically enumerates all protocols it expects to support in ```X-KDE-Protocols```. Since 0.33, when libsmb-support was dropped with reference to ffmpeg-support, opening files on a smb-share broke in KDE environments on Arch, which compiles ffmpeg without libsmb-support (and won't, see https://bugs.archlinux.org/task/69798). Dolphin trusts the listed protocols though to decide whether to pass a protocol-URL directly or transparently fuse-mount via kio-fuse before.

If that is possible, can the list of support protocols be generated at compile time by querying the ffmpeg being linked against about its supported protocols?

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/6319630/mpv.log)

**Comment by CounterPillow** [comment]
> If that is possible, can the list of support protocols be generated at compile time by querying the ffmpeg being linked against about its supported protocols?

Even simpler, the compiled mpv can be run to get this information, including mpv-supported protocols in addition to just the ffmpeg ones: `mpv --list-protocols | grep '://' | sed 's/^ *//g'`

I guess that just means there's some build system wrangling left to do to generate the .desktop file from that.

**Comment by prettyv** [comment]
> **EDIT**: apparently we can't do it that simply because of cross-compilation, which sucks

Meaning it would be unreasonably difficult to implement or just that it takes more thought?

**Comment by CounterPillow** [comment]
> Meaning it would be unreasonably difficult to implement or just that it takes more thought?

It means there needs to be some fallback in place, which is okay to do. The protocols mpv supports are pretty much queried at runtime as far as I know, as some are dynamically loaded from the ffmpeg libraries.

I've attempted to write a autodetect-with-fallback solution but I can't coerce waf into running that code after the mpv binary has been built to generate a .desktop file, so I'll leave it to someone more knowledgeable with the build system to look into it.

**Comment by urbenlegend** [comment]
If anyone's hurting for an easy workaround on Arch, you can make a copy of `/usr/share/applications/mpv.desktop` to `~/.local/share/applications` and remove the `X-KDE-Protocols` line. This will override the package-installed shortcut and make mpv use kio-fuse.

**Comment by 24fpsDaVinci** [comment]
> If anyone's hurting for an easy workaround on Arch, you can make a copy of /usr/share/applications/mpv.desktop to ~/.local/share/applications and remove the X-KDE-Protocols line. This will override the package-installed shortcut and make mpv use kio-fuse.

does this workaround still work? it does not work for me.

**Comment by urbenlegend** [comment]
Yes it works for me. Instead of removing the entire line I just removed smb from the list.

**Comment by ericswpark** [comment]
@urbenlegend thanks for the comment! Here are the commands to do this automatically. This needs to be run every time mpv gets updated:

```shell
cp /usr/share/applications/mpv.desktop ~/.local/share/applications/
sed -i '/^X-KDE-Protocols/s/,smb//; /^X-KDE-Protocols/s/smb,//; /^X-KDE-Protocols/s/smb//; /^X-KDE-Protocols=$/d' ~/.local/share/applications/
```

If your package manager supports hooks then it might be a good idea to have it run after mpv is upgraded, until this is fixed. Example for Arch pacman:


`/etc/pacman.d/hooks/mpv-fix.hook`
```ini
[Trigger]
Operation = Upgrade
Type = Package
Target = mpv

[Action]
Description = Fix mpv desktop file for KDE Plasma integration
Depends = 
When = PostTransaction
Exec = ./fix.sh
```
