### ISSUE TITLE
Fit in full screen

### ISSUE THREAD

**Issue by jeffjoker** [mpv-player/mpv#8733]
Hello,

With a bigger than 1080p screen, videos are not scaled to fit
Use-case: If I play (fullscreen) a 4k video on my 1440p screen, I will have a 1080p image in the middle, then I have to press "W" several times to have it fit
Could this be automatic ?

Thanks and keep up the good work, best player ever

**Comment by avih** [comment]
Please follow the issue template, including logs and all details that it requested,

**Comment by CounterPillow** [comment]
mpv absolutely does scale video, my guess is that you have something weird in your config file.

**Comment by jeffjoker** [comment]
> 
> 
> mpv absolutely does scale video, my guess is that you have something weird in your config file.

I am on windows, I do not have a config file

**Comment by CounterPillow** [comment]
post a `--log-file` as the issue template demands for reporting bugs

**Comment by CounterPillow** [comment]
Actually scratch that, I know what you want. You're watching a video on your monitor with a different aspect ratio than your monitor has. Instead of telling us this, you think this has something to do with scale, which it doesn't. What pressing w does is change the panscan parameter. You can just set your panscan parameter to `1.0` in your config file if you want it to always crop a video to fit your screen's aspect ratio. You'd do this by:

1. creating a file named `mpv.conf` (important, not `mpv.conf.txt` if you have file extensions hidden in explorer!) in `%APDATA%/mpv/`
2. put `panscan=1.0` into it

**Comment by jeffjoker** [comment]
https://pastebin.com/RV9XKNPm

**Comment by jeffjoker** [comment]
> 
> 
> Actually scratch that, I know what you want. You're watching a video on your monitor with a different aspect ratio than your monitor has. Instead of telling us this, you think this has something to do with scale, which it doesn't. What pressing w does is change the panscan parameter. You can just set your panscan parameter to `1.0` in your config file if you want it to always crop a video to fit your screen's aspect ratio. You'd do this by:
> 
>     1. creating a file named `mpv.conf` (important, not `mpv.conf.txt` if you have file extensions hidden in explorer!) in `%APDATA%/mpv/`
> 
>     2. put `panscan=1.0` into it

Thanks for that, but "pan and scan" does not respect the file's aspect ratio, which is not good

**Comment by CounterPillow** [comment]
Then you need to explain what you mean, because I cannot figure out what you want. pan and scan does precisely what you're doing by pressing W.

**Comment by jeffjoker** [comment]
No, W keeps the aspect ratio
pan and scan removes all black borders
I just want the video fit to the first limiting dimension

for ex a 4/3 video should remain 4/3 with black borders

**Comment by CounterPillow** [comment]
W literally increases the property `panscan`.

mpv will keep a 4/3 video to 4/3 with black borders when it scales. That is the default behaviour. You are pan-and-scanning by pressing W. Unless you're producing a log file I cannot figure out what you mean

**Comment by jeffjoker** [comment]
> 
> 
> W literally increases the property `panscan`.
> 
> mpv will keep a 4/3 video to 4/3 with black borders when it scales. That is the default behaviour. You are pan-and-scanning by pressing W. Unless you're producing a log file I cannot figure out what you mean

I linked one above : https://pastebin.com/RV9XKNPm

I confirm to you that the pan and scan option in the config file removes all borders whether it s a 4/3 or other ration, I never have any black borders on my 21/9 3440*1440 display, it also upscales to fully fill my screen
If I use W until the frist limiting dimension reaches the "border" (sorry double different use of the word) of my screen, the black borders remain

**Comment by CounterPillow** [comment]
> I do not want to lose any content just to remove black borders, just a "fit to screen"

so you want `--no-keepaspect`? This will stretch the image.

**Comment by jeffjoker** [comment]
https://pastebin.com/zfGnnycr

in this log of Tenet, when I play with pan and scan, the top and bottom of the image is cropped out, it shouldn't be the case, I should have black borders on the sides

I definitely do not want to stretch the image

**Comment by CounterPillow** [comment]
so you neither want to crop the image to make it fit your aspect ratio, nor do you want to stretch it to fit your aspect ratio.

Do your sources include baked in black bars or something that you're trying to remove?

**Comment by jeffjoker** [comment]
I do not want to remove the black borders if they are present, unless if that's doable without cropping "filmed images"
basically wanting the most (completely) original image and ratio, but fit to my screen, neither a 1080p in the middle, nor an extra scaled with "filmed image" cropped

I will post links to screenshots to show

**Comment by CounterPillow** [comment]
Looks like what you want in that case is this https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua

Put in your `%APPDATA%/mpv/scripts/`.

Good sources are not supposed to have black bars in them.

**Comment by jeffjoker** [comment]
> Looks like what you want in that case is this https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua
> 
> Put in your `%APPDATA%/mpv/scripts/`.

I'll try that

> Good sources are not supposed to have black bars in them.

I agree !!

**Comment by jeffjoker** [comment]
I added the autocrop.lua file in %APPDATA%/mpv/roaming/scripts/ but it doesn't seem to make a difference, I still get a 1080p in the middle without P&S and cropped image with P&S

**Comment by jeffjoker** [comment]
> 
> 
> Looks like what you want in that case is this https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua
> 
> Put in your `%APPDATA%/mpv/scripts/`.
> 
> Good sources are not supposed to have black bars in them.

**Comment by jeffjoker** [comment]
Wow... I had no mpv.conf and no scripts when I opened this and it wasn't ok in fullscreen
I created both mpv.conf and scripts to try and resolve without success
I removed both to take screenshots and now it works...

Thanks again and sorry \o/

**Comment by jeffjoker** [comment]
> 
> 
> Looks like what you want in that case is this https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua
> 
> Put in your `%APPDATA%/mpv/scripts/`.
> 
> Good sources are not supposed to have black bars in them.

WoW great script to remove the black borders of the "dirty" sources !!! thanks a lot
