### ISSUE TITLE
Fix youtube-dl related exit codes

### ISSUE THREAD

**Issue by CrossRoast** [mpv-player/mpv#8734]
### Important Information

Provide following Information:
- mpv version: 0.33.1
- Platform and Version: MacOS Big Sur 11.2.3
- Source of the mpv binary: homebrew

### Reproduction steps

Play any YouTube video with mpv that is unavailable (geo-restricted, privated or any other reason). mpv returns with code 0, despite not being able to play the video.

### Expected behavior

mpv returns a non-zero exit code.

### Actual behavior

mpv returns with exit code 0.

**Comment by CrossRoast** [comment]
To provide some context, I wrote a tiny wrapper script that reads links stored in file extended attributes and first tries to play the remote content version. If that fails, the script runs mpv on the local copy.

**Comment by dri150030** [comment]
Was not able to reproduce. Tried mpv on a privated video and a removed video and got exit code 2 on both with appropriate error messages.
mpv version 0.33.1
archlinux

**Comment by CrossRoast** [comment]
Interestingly, I can no longer reproduce the issue either. Not sure what changed. The problem might have been in my script, though I believe I tested it by printing the exit code to stdout... It could have been a specific video that I can't find now. I'll keep this issue open for a bit, in case I or someone else stumbles on this problem again. If not, it's probably ok to close it!

**Comment by avih** [comment]
>  I'll keep this issue open for a bit, in case I or someone else stumbles on this problem again

No need. Searching closed issues is as easy s searching open issues.

If you find out something new or have more info in the future, then you can post here, and if it needs to be reopened then we'll reopen it.
