### ISSUE TITLE
MPV Does Not Remember Playback Position

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#8736]
I'm running mpv version 0.29.1 on Windows 10 and I have "save-position-on-quit" in my .conf file, yet mpv never saves the position and always restarts playback from the beginning. This makes it almost unusable, since I can't remember the exact position nor can I start writing it down every time I want to quit a video without completing it.

**Comment by CounterPillow** [comment]
you've ignored the issue template, so we don't have the log file to investigate.

> I'm running mpv version 0.29.1

update

**Comment by george-emerald** [comment]
I updated and it was fixed. The new version had mpv.conf under an "mpv" folder within the "mpv" folder instead of the "docs" folder and that seemed to fix it.

**Comment by butter-fly04** [comment]
I am having the same problem in fedora linux.

**Comment by CounterPillow** [comment]
@butter-fly04 it's unlikely that you do have the same issue. Please open a new issue, filling out the required information in the template.
