### ISSUE TITLE
Midi audio file is broken on mpv

### ISSUE THREAD

**Issue by amariami** [mpv-player/mpv#8738]
### Important Information

Provide following Information:
- mpv version 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72

- DESCRIPTION="Linux Mint 20.1 Ulyssa", DISTRIB_DESCRIPTION="Ubuntu Focal Fossa", Kernel: Linux 5.4.0-71-generic
- PPA repository = ppa:mcman/mpv-test
- Xfm4+Compositing
- Graphics:
  Device-1: AMD Wrestler [Radeon HD 6310] vendor: Dell driver: radeon 
  v: kernel bus ID: 00:01.0 
  Display: x11 server: X.Org 1.20.9 driver: ati,radeon 
  unloaded: fbdev,modesetting,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: AMD PALM (DRM 2.50.0 / 5.4.0-71-generic LLVM 11.0.0) 
  v: 3.3 Mesa 20.2.6 direct render: Yes 
### Reproduction steps
--no-config and change back to default config still not work

### Expected behavior
Play midi properly

### Actual behavior
no sound and distortion

### Log file
[mint_ulyssa_xfce.mpv.log](https://github.com/mpv-player/mpv/files/6323433/mint_ulyssa_xfce.mpv.log)

### Sample files
#8724

**Comment by avih** [comment]
Did you just opened a new issue just to say "me too"? It's enough that you added the comment at #8724, feel free to add more details there if you need.

**Comment by amariami** [comment]
> 
> 
> Did you just opened a new issue just to say "me too"? It's enough that you added the comment at #8724, feel free to add more details there if you need.

sorry my connection is poor caused by traffic, i did not see the complete page just keep buffering
