### ISSUE TITLE
Question about compiling mpv? And frame timing is not showing?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#8739]
Hi,

I did follow this guide [Compiling for Windows](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md)

I Did use MSYS2 for compiling mpv and got mpv.exe , mpv.com and .dll files 
İn /mingw64/bin folder.

So
I'm new in this stuff and I did wanna ask if I move or copy the .exe , .com and all .dll files to desktop inside a new folder is there something I will be missing in the /mingw64/bin folder or did I get everything that was compiled/installed with mingw64.exe?

**Comment by erickyun** [comment]
Also frame timings is not showing?

**Comment by avih** [comment]
This is outside the scope of mpv itself, but for the record, you can create a shortcut to mpv.exe at /mingw64/bin (with the real windows path) and use it normally.

Alternatively, if you want a directory with only the files which mpv uses, run the following commands at the one of the MSYS2 shells:
```sh
cd /mingw64/bin
mkdir -p mpv-dist
ldd mpv.exe | cut -f3 -d' ' | grep mingw | xargs -I{} cp -a {} mpv-dist/
strip mpv-dist/*.exe mpv-dist/*.com mpv-dist/*.dll
explorer .  # opens window explorer at /mingw64/bin, copy the dir mpv-dist to somewhere
```
This will be quite big, probably more than 100M, and with dozens of dlls, but that's how it is.

Don't forget to download a recent copy of youtube-dl from https://ytdl-org.github.io/youtube-dl/download.html  and put youtube-dl.exe inside the same dir.

**Comment by avih** [comment]
> Also frame timings is not showing?

Maybe you didn't install the lua development libs. If you did install lua, and `mpv -v` shows that it's built with lua (at "list of enabled features" near the top), and it still doesn't show text on screen then open an separate issue for that with log and everything else which the issue template requests.

**Comment by erickyun** [comment]
> > Also frame timings is not showing?
> 
> Maybe you didn't install the lua development libs. If you did install lua, and `mpv -v` shows that it's built with lua (at "list of enabled features" near the top), and it still doesn't show text on screen then open a separate issue for that with log and everything else which the issue template requests.

Thank you for your reply. it does show that it installed. I will open separate issue.

```
[cplayer] List of enabled features: 51deb asm build-date caca cplayer d3d-hwaccel d3d9-hwaccel debug-build direct3d dos-paths ffmpeg gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv jpeg lcms2 libarchive libass libavdevice libbluray libm lua mingw noexecstack optimize posix-or-mingw stdatomic wasapi win32-desktop win32-internal-pthreads zlib
```
