### ISSUE TITLE
Frame timing not showing after compiling?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#8740]
Hi,

I did follow this guide [Compiling for Windows](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md)

I Did use MSYS2 for compiling mpv and got mpv.exe , mpv.com and .dll files 
İn /mingw64/bin folder.

mpv video.mkv
getting this error.
(+) Video --vid=1 () (h264 1920x1080 23.976fps)
(+) Audio --aid=1 () (aac 2ch 24000Hz)
[vo/gpu] The OpenGL driver does not support OpenGL 3.x
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu] The OpenGL driver does not support OpenGL 3.x
[vo/gpu] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.

```
[cplayer] List of enabled features: 51deb asm build-date caca cplayer d3d-hwaccel d3d9-hwaccel debug-build direct3d dos-paths ffmpeg gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv jpeg lcms2 libarchive libass libavdevice libbluray libm lua mingw noexecstack optimize posix-or-mingw stdatomic wasapi win32-desktop win32-internal-pthreads zlib
```

[Full Log](https://pastebin.com/raw/D6CP5qN7)

**Comment by CounterPillow** [comment]
you did not post the full log as the issue template asks you to

**Comment by erickyun** [comment]
> you did not post the full log as the issue template asks you to

[Full Log](https://pastebinp.com/raw/lI18eX7LyeaSAoSVPJ2MWQ)

**Comment by CounterPillow** [comment]
That log is useless, as it does not show you actually trying to play a file.

**Comment by erickyun** [comment]
> That log is useless, as it does not show you actually trying to play a file.
> 
> You also did not tell us what the expected behavior is, and what the actual behavior is. "Frame timing not showing" is too vague.

Sorry I'm noob still here my bad.

expected behavior:
Shift+ı and 2
To show frame timings on screen

actual behavior:
Nothing is showing in the screen switching to stats 2 is not showing anything.

**Comment by CounterPillow** [comment]
that's likely because you're falling back to some legacy VO that does not use the shading pipeline

**Comment by CounterPillow** [comment]
FYI it looks like you don't have any GPU drivers installed:
```
[vo/gpu] GL_VENDOR='Microsoft Corporation'
[vo/gpu] GL_RENDERER='GDI Generic'
```

**Comment by erickyun** [comment]
> that's likely because you're falling back to some legacy VO that does not use the shading pipeline. I'd know this for sure if you actually bothered to post a proper log, but you didn't, and are seemingly unable to follow even the simplest instructions.
> 
> EDIT: now that you've edited in a full log (which you should've used `--log-file` for like the issue template requested, but you of course didn't) I can indeed see that you are falling back to the direct3d vo, not the GPU vo.

I'm sorry you're right my English is bad and I didn't read fully the instructions.😅

**Comment by avih** [comment]
> I'm sorry you're right my English is bad and I didn't read fully the instructions.😅

Next time, when someone requests from you explicitly to open an issue with log and everything else requested, and you even quote it - https://github.com/mpv-player/mpv/issues/8739#issuecomment-821362920 then at least try to not waste the time of otehr people.

**Comment by erickyun** [comment]
> > I'm sorry you're right my English is bad and I didn't read fully the instructions.😅
> 
> Next time, when someone requests from you explicitly to open an issue with log and everything else requested, and you even quote it - [#8739 (comment)](https://github.com/mpv-player/mpv/issues/8739#issuecomment-821362920) then at least try to not waste the time of otehr people.

You're right but I'm already excepted that it was my fault I didn't know the instructions were important

**Comment by erickyun** [comment]
> FYI it looks like you don't have any GPU drivers installed:
> 
> ```
> [vo/gpu] GL_VENDOR='Microsoft Corporation'
> [vo/gpu] GL_RENDERER='GDI Generic'
> ```

@CounterPillow 

I'm not sure if ı did it right but
I did try to Install the latest version of my gpu drivers from the [vendor site](https://downloadcenter.intel.com/tr/product/59836) but still the same problem occurred?

Intel® Pentium® B960 2.20 GHz
