### ISSUE TITLE
Allow for opening new files in separate windows instead of opening them into the same, single window (macOS)

### ISSUE THREAD

**Issue by dmattera** [mpv-player/mpv#8742]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

When opening a new media file, mpv would have the ability to open said file in a new window separate from any existing windows that are currently open already.

### Alternative behavior of the wanted feature

i can't think of any real alternative to this request. Either mpv can open new files in separate windows or it can't.

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by avih** [comment]
> When opening a new media file, mpv would have the ability to open said file in a new window separate from any existing windows that are currently open already.

mpv already does that. It can't open more than one window anyway.

Also, the issue template explicitly requests you to state what the current behavior is, not only what is expected. Otherwise we can't know what you mean because your expected behavior should already be happening, and we don't have anything to contrast it to (current behavior) in order to understand what you're actually requesting.

**Comment by Akemi** [comment]
duplicate of #1377, #6865 and probably some more. the app bundle isn't really meant to open several instances of itself. several windows are theoretically possible but are not within the scope of mpv itself (the core doesn't support this) but rather of libmpv users.

if you really want that behaviour you have to writ a wrapper script yourself with the `open` command. there are several examples of that in the first linked issue.
