### ISSUE TITLE
Display last 10 played videos history

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8743]
I use SmartHistory and it opens only latest played video.
But I'd like to see 10 last played videos history, is there a script for that?

_PC Win 10 x64_

**Comment by bitraid** [comment]
Try [this](https://github.com/hacel/mpv-scripts).

**Comment by Max-Enrik** [comment]
@bitraid
Amazing! That is better than I was expecting for. Thank you a lot.
This works fine so far. But I get errors when I changed key bind from ``` ` ``` to `k` or `7`

```
error: can't convert to number!
script-opts/recent.conf:3 error converting value '' for key 'auto_save_skip_past'
```

**Comment by bitraid** [comment]
Did you modify [this line](https://github.com/hacel/mpv-scripts/blob/80640cd961d2e49c22f86cedd27f00df2c9ba1db/recent.lua#L15)?
If you still have problems, open an issue on the plugin's repo.

**Comment by Max-Enrik** [comment]
OK, I jump there and will explain more, thank you.
