### ISSUE TITLE
AVFilterGraph: No such filter: 'sofalizer'

### ISSUE THREAD

**Issue by pitdicker** [mpv-player/mpv#8744]
### Important Information

MPV version:
```
mpv 0.33.0-117-gcd7a7a1de8 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Apr 18 10:21:34 CEST 2021
FFmpeg library versions:
   libavutil       56.73.100
   libavcodec      58.136.101
   libavformat     58.78.100
   libswscale      5.10.100
   libavfilter     7.111.100
   libswresample   3.10.100
FFmpeg version: N-101987-gd43b26b30d
```
Fedora 33, Gnome Wayland with an AMD RX5700 gpu.

### Reproduction steps
For quite I few hours I have been trying to get the sofalizer option to work with no succes.
These are my latest commands for compiling and playing on Fedora:
```
sudo dnf install pulseaudio-libs-devel libvdpau-devel libplacebo-devel libva-devel vapoursynth-devel uchardet-devel compat-lua-devel libbluray-devel python3-docutils libjpeg-turbo-devel libmysofa-devel
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build/
echo --enable-libmysofa >> ffmpegoptions
./rebuild -j16
sudo ./install
```
```
mpv --af=lavfi=[sofalizer=sofa="/home/pitdicker/Downloads/ClubFritz1.sofa"] --no-config video.mkv
```

### Expected behavior

Some form of surround sound through my headphones.

### Actual behavior
The resulting message stays the same:
```
[ffmpeg] AVFilterGraph: No such filter: 'sofalizer'
[lavfi] parsing the filter graph failed
[user_filter_wrapper] Creating filter 'lavfi' failed.
Audio filter initialized failed!
Audio: no audio
```

### Log file

https://0x0.st/-ALt.txt

### Sample files

**Comment by jeeb** [comment]
This is due to (lib)sofalizer is a libavfilter and thus depends on FFmpeg being built with the sofalizer filter. To enable it, you will have to build the FFmpeg that is linked against mpv with libsofalizer enabled.

You can list all (audio) filters built into mpv/libavfilter by doing the following (it lists them separately):
```
mpv --af=help
```

**Comment by pitdicker** [comment]
Thank you for the reply. As I understand it, installing the `libmysofa` and `libmysofa-devel` packages and compiling FFmpeg through mpv-build with `--enable-libmysofa` should be enough to enable the sofalizer filter, but apparently not (see my steps from the first post). Did I miss a step?

**Comment by pitdicker** [comment]
Apologies, finally found the problem: a typo...
