### ISSUE TITLE
ctrl+shift+left/right has the same effect as shift+left/right

### ISSUE THREAD

**Issue by ypsah** [mpv-player/mpv#8746]
### Important Information

Provide following Information:
- mpv version: `mpv 0.33.1-dirty`
- Linux Distribution and Version: `archlinux` / `latest`
- Source of the mpv binary: `community/mpv`
- If known which version of mpv introduced the problem: unknown, but it's been a while (#7411 seems to imply `0.31`)
- Window Manager and version: `sway version 1.6`
- GPU driver and version: `libva-intel-driver` [*]
- ~Possible screenshot or video of visual glitches~

[*] I don't know much about this, but my laptop does not have any fancy GPU, only intel's integrated graphics. The output of mpv mentions `Using hardware decoding (vaapi).` and `pacman -Qi libva` reports `libva-intel-driver` as the only installed optional dependency.

### Reproduction steps

- [x] Try to reproduce your issue with --no-config first.

### Expected behavior

While viewing a video or a movie that has subtitles, pressing ctrl+shift+left/right adjusts the subtitle delay so that the next or previous subtitle is displayed now.

### Actual behavior

It seems to have the exact same effect as shift+left/right, that is to say: seek -/+ 1 exact second, without any effect on the subtitle delay.

### Log file

https://0x0.st/-AVW.txt

### Sample files

I used a blank video/audio file for the log file: `ffmpeg -f lavfi -i color=size=1280x720:rate=25:color=black -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -t 30 blank.mkv` and a dummy subtitles file (`for i in {1..15}; do printf '%i\n00:00:%02i,000 --> 00:00:%02i,000\nThis is a test #%i\n\n' $i $((i * 2 - 1)) $((i * 2)) $i; done > blank.srt`).

**Comment by avih** [comment]
> ... pressing ctrl+shift+left/right ...

Do you press at the terminal or at the video window?

Assuming The issue is at the terminal:

Sepending on the terminal, the terminal might not support this combination, or maybe the terminal encodes this combination in a way which mpv does not recognize.

- Try also at the video window and report the result.
- Tell us which terminal you use.
- At the terminal, at the shell prompt (not when running mpv), press ctrl-v and then press ctrl-shift-right, then copy the output which gets printed, and post it here.

**Comment by avih** [comment]
Also, you can try running `mpv --idle --force-window --input-test` and then press the key combination and observes (and report here) what mpv sees.

If the issue is at the terminal, try also with a different terminal if you can, and report the result.

**Comment by ypsah** [comment]
> Do you press at the terminal or at the video window?

I always pressed at the video window, but pressing at the terminal actually works!

I suppose it does not matter which terminal I use then, but for completeness, I reproduced with `mpv` launched from either `alacritty` or `termite`. (both work when pressing at the terminal rather than the video window itself)
And both of them print `^[[1;6C` for ctrl+v then ctrl+shift+right.

> try running `mpv --idle --force-window --input-test` and then press the key combination and observe

```console
$ mpv --idle --force-window --input-test
[input] Key Shift+RIGHT is bound to:
[input] 1.  'no-osd seek  1 exact' in <builtin>:1 (default)
[input] Key Shift+LEFT is bound to:
[input] 1.  'no-osd seek -1 exact' in <builtin>:1 (default)
```

**Comment by avih** [comment]
Sounds like a Wayland issue, maybe at mpv itself. Thanks for the clarifications.

CC @Dudemanguy

**Comment by Dudemanguy** [comment]
Yeah your mpv version is before the wayland backends supported multiple modifiers (see: 1ba5dc84caa1dfe4ee39e8a9947f863b43a52263).
