### ISSUE TITLE
Can't load unknown script: [PATH TO .PY FILE]

### ISSUE THREAD

**Issue by sbstratos79** [mpv-player/mpv#8755]
### Important Information

Provide following Information:
- mpv version:   mpv 0.33.0-107-gdd86f195a6
- Windows Version:    Windows 10 Home (20H2)
- Source of the mpv binary:   Shinchiro Windows build
- ![WindowsTerminal_SIf8eXfBa0](https://user-images.githubusercontent.com/4395586/115236413-faa09300-a138-11eb-807b-081a14d35f1f.png)

### Reproduction steps

Try to use any user-script that requires python.

### Expected behavior

The script should run.

### Actual behavior

It throws an error in the console along the lines of "Can't load unknown script : [PATH TO .PY FILE]"

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/6336001/log.txt)

The issue will be closed for ignoring the issue template.

### Sample files

[subselect scripts.zip](https://github.com/mpv-player/mpv/files/6336041/subselect.scripts.zip)

**Comment by avih** [comment]
> Can't load unknown script: [PATH TO .PY FILE]
> Expected behavior: The script should run.

That's great expectation, but mpv only supports lua and js script. Not python.

**Comment by sbstratos79** [comment]
Sorry for being a little dumb but there are several user scripts in user scripts wiki page that use python. Is there any way to run them at all?

**Comment by avih** [comment]
First of all, mpv itself could never run python scripts.

However, it's possible that some shells install python scripts and then run them on their own.

In this case, the script expects `python` or `python3` installed system-wide and at the path. On Unix (linux/BSD/OSX) it's usually installed, but on windows it's not.

So the short answer is "you can't use these scripts on windows".

Regardless, there's another issue where the .py script is at a place which mpv tries to run scripts. This was allowed in the past and mpv simply ignored scripts with unknown file extension, but it was modified at some stage to print this error.

So this means the script not only expects python to be installed, but it's also old - from before mpv displayed these errors.

Also, t

**Comment by sbstratos79** [comment]
The script that I am trying to run says it has been tested on windows and linux. [Script github](https://github.com/zenyd/mpv-scripts) . So it worked with windows at some point. Maybe adding python in path environment variable fixed that issue. But I guess I can't place the py file in the same folder as the scripts.

**Comment by avih** [comment]
The best place to ask questions about a specific script is at the repo of this script.

Either way, at no point in time was mpv able to execute python scripts on its own.

**Comment by sbstratos79** [comment]
I had considered that, but after trying out a bunch of python based scripts and failing to run all of them, I assumed it was an issue with mpv itself. (Which it kind of is). That's why I opened the issue here.

**Comment by avih** [comment]
> I assumed it was an issue with mpv itself. (Which it kind of is)

It's not, unless you expect mpv to be able to automatically run any type of script with automatic mpv bindings (that's what mpv lua/js scripts are).

And if that's what you expect, then you're probably not a developer and not aware that generally it's not possible without some very considerable effort.

**Comment by sbstratos79** [comment]
By fault I meant the change you mentioned which may have rendered some older scripts unusable.

And turns out it was completely my own fault for the scripts not working. I had to add the base directory of the MPV installation directory under a variable which I could replace with the default APPDATA variable. This is because I was using a portable_config folder instead of the default APPDATA folder. I had added the folder to the path environment, but had not assigned a variable to it.

And you're right, I am not a developer. 🤣 Sorry for taking your time and thanks for the help again. I'd been struggling with this the whole day.

**Comment by avih** [comment]
> By fault I meant the change you mentioned which may have rendered some older scripts unusable.

It didn't render any scripts unusable. It used to ignore unknown scripts silently and keep running, and now it prints an error and keeps running.

As I said, at no point in time was mpv able ti run python scripts.
