### ISSUE TITLE
ASS subtitle wrong border and shadow

### ISSUE THREAD

**Issue by Scorp48** [mpv-player/mpv#8756]
**Important Information**
- mpv version: mpv-x86_64-20210404-git-dd86f19  mpv 0.33.0-107-gdd86f195a6
- Windows Version: Windows 10 pro
- Source of the mpv: Sourceforge
- If known which version of mpv introduced the problem: The last version

**Reproduction steps**
Just open a mkv file with embedded or external .ass subtitles (BorderStyle, Outline:2, Shadow:1)

**Sample files**
[subtitle.zip](https://github.com/mpv-player/mpv/files/6336998/subtitle.zip) or [anothersubtitle.zip](https://github.com/mpv-player/mpv/files/6337581/anothersubtitle.zip)

**Expected behavior**
The subtitle looks with the correct border and shadow.
_Correct in mpv 0.32.0-796-g790647314c or in vlc player(3.0.12):_
![correct in older version](https://user-images.githubusercontent.com/70067415/115252762-0c2f6e00-a12c-11eb-9af0-4f308daa5d95.jpg)

**Actual behavior**
Wrong border and shadow.
_Wrong in last version mpv 0.33.0-107-gdd86f195a6:_
![wrong in last version](https://user-images.githubusercontent.com/70067415/115252765-0cc80480-a12c-11eb-9734-2b40b8452706.jpg)

**Log files**
[log.txt](https://github.com/mpv-player/mpv/files/6336805/log.txt) mpv 0.33.0-107-gdd86f195a6
_From another pc_
[log without error.txt](https://github.com/mpv-player/mpv/files/6337737/log.without.error.txt) mpv 0.32.0-796-g790647314c
[log with the error.txt](https://github.com/mpv-player/mpv/files/6337738/log.with.the.error.txt) mpv 0.33.0-107-gdd86f195a6

**Comment by sfan5** [comment]
> Correct in older version

And which exact older version is that?

Also you didn't post a sample file (providing an incomplete ASS header excerpt doesn't count).

**Comment by Scorp48** [comment]
> 
> 
> > Correct in older version
> 
> And which exact older version is that?
> 
> Also you didn't post a sample file (providing an incomplete ASS header excerpt doesn't count).

The version without mpv error I do not know exactly the version but at most it would be 1 month ago, I do not know the exact version because I did not realize the error until yesterday that I updated it but in vlc player it looks correctly, sample added

**Comment by hooke007** [comment]
To check → https://mpv.io/manual/master/#options-sub-ass-vsfilter-blur-compat

**Comment by Scorp48** [comment]
> 
> 
> To check → https://mpv.io/manual/master/#options-sub-ass-vsfilter-blur-compat

"--sub-ass-vsfilter-blur-compat=no" fix the problem

**Comment by Akemi** [comment]
first thought it was the ScaledBorderAndShadow problem that was introduced with a legacy compatibility change in libass and then fixed in mpv again, eg adding to the subs [Script Info]  "ScaledBorderAndShadow: yes" would fix it. it was this libass https://github.com/libass/libass/commit/5575d2f727750966cb08502a3381e3441938f38f and this mpv https://github.com/mpv-player/mpv/commit/d086421ca478940b8588e33c9f836472a578b199 commit.

though the actual problem is sub-ass-vsfilter-blur-compat which was defaulted to yes in this commit https://github.com/mpv-player/mpv/commit/4dcaf70b9653cd04c2159fac6545f25f8e1cbcf9

**Comment by Akemi** [comment]
since the default was changed again for a reason, i am closing this. i personally set `sub-ass-vsfilter-blur-compat` to `no` in my config, because for me it caused less problems than `yes`.

**Comment by astiob** [comment]
> first thought it was the ScaledBorderAndShadow problem that was introduced with a legacy compatibility change in libass and then fixed in mpv again, eg adding to the subs [Script Info] "ScaledBorderAndShadow: yes" would fix it.

It is.

The ASS samples provided do not set `ScaledBorderAndShadow: yes`, so the borders are 2px wide at the video resolution, which, based on the screenshots, was something like 1920×1080, exactly as specified.
