### ISSUE TITLE
hwdec=auto problem

### ISSUE THREAD

**Issue by yasinsensoy** [mpv-player/mpv#8761]
mpv-version
mpv 0.33.0-107-gdd86f195a6

I'm using mpv-1.dll 64 bit in c#.

I want to use 'hwdec = auto', but the program is getting stuck. I want to use it because the Cpu is between 1% and 5%. But when using 'hwdec = no' the Cpu is between 15% and 20%.

[hwdec=auto.log](https://github.com/mpv-player/mpv/files/6346757/hwdec.auto.log)
[hwdec=no.log](https://github.com/mpv-player/mpv/files/6346758/hwdec.no.log)

**Comment by CounterPillow** [comment]
Your log files are incomplete.

**Comment by yasinsensoy** [comment]
I cut it, then the file continues to play. Same as the last lines.

**Comment by CounterPillow** [comment]
You cut the start. The start is important.

**Comment by yasinsensoy** [comment]
[hwdec=auto.log](https://github.com/mpv-player/mpv/files/6346942/hwdec.auto.log)
[hwdec=no.log](https://github.com/mpv-player/mpv/files/6346943/hwdec.no.log)

**Comment by yasinsensoy** [comment]
Commands slow down when hwdec=auto. Normally it is 0.01ms, while it is 16ms when hwdec=auto. If I use this async get and set property, will this time decrease?
