### ISSUE TITLE
windows W/H ignored

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8762]
Only windows height ignored. Width of the windows showing correctly `1600` but windows height showing `800`. Even I try 1000 height so result still `800`.

Any help would be appreciated that.

```
geometry=-0+40
autofit=1600x900
```

_PC: Windows 10 x64_

**Comment by Akemi** [comment]
if you have an issue, don't use the question template, like you were asked to many times before.

autofit, like the man page says, fits the window to a max size of keeping the aspect ratio. if you want a static size use the geometry option. if you mean something else open a proper issue. please properly read the manual and don't ignore the issue template.

**Comment by Max-Enrik** [comment]
@Akemi - ouch! I see did that without noticed about it. Thank you for mentioned about it.
I already read about it and tried to do it properly, unfortunately looks like I do/misunderstood it.
