### ISSUE TITLE
Window builds here [updated preview version 2021-04-26]

### ISSUE THREAD

**Issue by tasty0tomato** [mpv-player/mpv#8763]
### Expected behavior of the wanted feature

Here is [my build](https://gitee.com/tasty_0_tomato/mpv-windows-build).
I used to use Windows builds by [shinchiro](https://sourceforge.net/projects/mpv-player-windows/files), but since the stable release of version v0.33.1 came out, there wasn't a new build of it. Because I know how to build a Windows binary, so I decide to build it by myself and share it.
I will have enough time to build it in the future time.

Now there are:
1. latest [0.33.1](https://gitee.com/tasty_0_tomato/mpv-windows-build/releases/v0.33.1)
2.  (preview) [2021-04-26](https://gitee.com/tasty_0_tomato/mpv-windows-build/releases/2021-04-26)

**Comment by Akemi** [comment]
thank you for you effort. if you plan to make this something more regular it might be worth adding it to our page (https://github.com/mpv-player/mpv.io). in that case a PR would be welcome. though we would still need to decide if we would accept the PR.

**Comment by avih** [comment]
Thanks, I suggest that you add a post here whenever you create a new build, so that people could follow, and if we notice you do that regularly, then we could consider linking your builds from the main web site.

It would also help if you posted (at your builds repository) your exact build procedure, dependencies (with versions), and environment so that others could try to reproduce your build. Similar to what shinchiro does at his mpv-cmake repository.

I think it would be OK to keep this issue open as long as you post builds regularly (so let's re-open it the next time you post a new build).

**Comment by tasty0tomato** [comment]
Some tips:
1. my very first build is [here](https://github.com/tasty0tomato/mpv-windows-build/releases/tag/v0.33.1)
    And I also listed some environment I used to build it
    ![msedge_Q21fBsQeHF](https://user-images.githubusercontent.com/48764449/115637857-bd5c2100-a343-11eb-8eec-844f53fee9b2.png)
2. I know that the stable release of mpv definitely deserves to be built, but I do not know what about the other situation because I always saw [shinchiro](https://sourceforge.net/projects/mpv-player-windows/files) who sometimes built the master branch of mpv. I do not know how to choose or just to build the stable release.

**Comment by tasty0tomato** [comment]
I kind of wanted to transfer the repository to [gitee](https://gitee.com/tasty_0_tomato/mpv-windows-build) because it will be more convenient for me.
While this is a better choice for Chinese, I do not know whether the people not from China can access gitee.

**Comment by tasty0tomato** [comment]
I kind of wanted to transfer the repository to [gitee](https://gitee.com/tasty_0_tomato/mpv-windows-build) because it will be more convenient for me.
While this is a better choice for Chinese, I do not know whether the people not from China can access gitee.

**Comment by tasty0tomato** [comment]
New release!
Because mxe has new stable release.
[Here](https://gitee.com/tasty_0_tomato/mpv-windows-build/releases/2021-04-26).

**Comment by avih** [comment]
> Because mxe has new stable release.

Was this announced somewhere? Any release notes or some such?

**Comment by tasty0tomato** [comment]
> Because mxe has new stable release.

https://github.com/mxe/mxe/releases

**Comment by tasty0tomato** [comment]
> https://github.com/mxe/mxe/releases

This may not be a stable release, but I will build a master version since there is a new mxe release.

**Comment by avih** [comment]
@tasty0tomato I think it would be easier to find your builds if you changed the title to something like "Window builds here [updated 2021-04-29]" (or choose something else which will be similarly useful), and update the title accordingly whenever you add a new build.

Maybe also update/edit the first post to link to the latest build whenever you update it.

And if any users want to use it, hopefully they can also give you feedback here.

If you think it would be better to keep this issue open - let us know.

**Comment by tasty0tomato** [comment]
@avih Thanks for your advice, and I think it is time to reopen this.

**Comment by garoto** [comment]
Your build is missing lots of useful features and your ffmpeg (v4.2.3) is a year old already.

```diff
> diff -y -W72 features_tomato features_shinchiro
asm                                     asm
build-date                              build-date
caca                               <
cplayer                                 cplayer
                                   >    cuda-hwaccel
                                   >    cuda-interop
d3d-hwaccel                             d3d-hwaccel
                                   >    d3d11
d3d9-hwaccel                            d3d9-hwaccel
debug-build                             debug-build
direct3d                                direct3d
dos-paths                               dos-paths
                                   >    dvdnav
                                   >    egl-angle
                                   >    egl-angle-win32
                                   >    egl-helpers
ffmpeg                                  ffmpeg
                                   >    ffnvcodec
gl                                      gl
gl-dxinterop                            gl-dxinterop
gl-dxinterop-d3d9                       gl-dxinterop-d3d9
gl-win32                                gl-win32
glob                                    glob
glob-win32                              glob-win32
gpl                                     gpl
iconv                                   iconv
                                   >    javascript
jpeg                                    jpeg
                                   >    lcms2
                                   >    libarchive
libass                                  libass
libavdevice                             libavdevice
libbluray                               libbluray
libdl                              <
libm                                    libm
                                   >    libmpv-shared
                                   >    libplacebo
lua                                     lua
luajit                                  luajit
mingw                                   mingw
noexecstack                             noexecstack
                                   >    openal
optimize                                optimize
                                   >    plain-gl
posix-or-mingw                          posix-or-mingw
                                   >    rubberband
                                   >    sdl2
                                   >    sdl2-audio
                                   >    sdl2-gamepad
                                   >    sdl2-video
                                   >    shaderc
                                   >    shaderc-static
                                   >    spirv-cross
                                   >    spirv-cross-static
                                   >    static-build
stdatomic                               stdatomic
                                   >    uchardet
                                   >    vapoursynth
                                   >    vulkan
wasapi                                  wasapi
win32-desktop                           win32-desktop
win32-internal-pthreads                 win32-internal-pthreads
                                   >    zimg
zlib                                    zlib
