### ISSUE TITLE
Option to disable cuda-nvdec when no CUDA device present

### ISSUE THREAD

**Issue by chaitan3** [mpv-player/mpv#8765]
### Important Information

Provide following Information:
- mpv version: 0.33.1
- Linux Distribution and Version: Archlinux
- Source of the mpv binary: Archlinux repository
- Window Manager and version: sway 0.16 
- GPU driver and version: Intel Tiger Lake, Mesa 21.0

### Reproduction steps

1. Have a device with CUDA installed, but no Nvidia GPU present and a device that supports hwdec=vaapi
2. Launch mpv on any video with hwdec=vaapi.

### Expected behavior
Video plays instantly using the device that supports vaapi. 

### Actual behavior
Video starts playing using the vaapi device after a delay of 10 seconds. Log shows that it gets stuck trying to initialize cuda-nvdec.

### Log file

https://0x0.st/-mPB.txt

**Comment by tantei3** [comment]
I tried similar setup in a VM without CUDA device and installed nvidia-cuda-toolkit, however the initialization failure mentioned above doesn't seem to take 10 seconds, it seems to fast enough in my case.

It is possible to build mpv from source with cuda disabled:
`./waf configure --disable-cuda-hwaccel`

With the above mentioned build configuration, `cu->cuInit` call doesn't appear in the logs when `--hwdec=vaapi` is set.

**Comment by Celmor** [comment]
I have the same issue. To note though that I have an nvidia card installed but the driver blacklisted (I use it to passthrough to a VM and load the vfio-pci driver via kernel command line to it).
I'd prefer the hwdec option in the config file to be honored and the cuda/nvidia driver to attempted at all even if nvidia/cuda software is installed and it might detect an nvidia card (even if no nvidia driver is loaded).
For testing purposes I've deleted all library files from the nvidia-utils package which works around this issue:
# pacman -Ql nvidia-utils| awk '\''/\.so/ {print $2}'\'' | while read -r f; do [ -f "$f" ] && rm "$f"; done
Log file with libraries exposing the issue at `Loading hwdec driver 'cuda-nvdec'`:
https://pastebin.com/raw/yexg42wU
Log file after workaround avoiding the issue:
https://pastebin.com/raw/bAPzcbt0
