### ISSUE TITLE
How to set "touch window from outside"

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8766]
Is there any way to keep the video zoom in touch-window-from-outside like other player such as mpc?

![Snipaste_2021-04-23_18-36-13](https://user-images.githubusercontent.com/41094733/115859528-e6bf9e80-a462-11eb-909a-52641e2edf73.jpg)

### Log file

It is unnecessary.

**Comment by avih** [comment]
> It is unnecessary.

Sure, neither is any reply.

**Comment by avih** [comment]
Also, this seems to be mpv.net, so please ask over there.

**Comment by hooke007** [comment]
No, it is mpc, I want to know how to realize the similar function in mpv.

**Comment by hooke007** [comment]
I do not find something useful in the manual, that is why I ask the question.

**Comment by avih** [comment]
Well, I don't know what "touch window from outside" does. But you can most probably use the `panscan` option to adjust the video inside the window - https://mpv.io/manual/master/#options-panscan

Also, by default E and W presets adjust the pan-and-scan value.

**Comment by hooke007** [comment]
Let me explain. This function will always keep the video zoom in to fill full the window. To be specific, the video (origin) 1000x500 and window 2000x700. By the option "--no-keepaspect-window", the video will be zoom in 1400x700 and margins will be black borders. If there is the way to "touch window from outside",the video will zoom in 2000x1000 and some pictures will be cropped.

**Comment by avih** [comment]
So I presumed you tried the `panscan` option and/or tried pressing E or W and it didn't work?

If that's the case, then now we do need a log to help more.

**Comment by hooke007** [comment]
Sorry, maybe it's the problem of bugwin10, After I restarted the OS and "panscan" will act as my expectation.
