### ISSUE TITLE
API Escaping Inconsistencies

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#8767]
- mpv version 0.33.1
- Windows Version 10 x64

I'm communicating with MPV via JSON IPC API.

For [List Options](https://mpv.io/manual/stable/#list-options), the following methods should interpret escapes but don't: `set, add, pre`

    {"command":["change-list","reset-on-next-file","add","%6%VOLume"],"request_id":1}
    {"data":null,"request_id":1,"error":"success"}
    {"command":["get_property","reset-on-next-file"],"request_id":2}
    {"data":["%6%VOLume"],"request_id":2,"error":"success"}

For [Key/Value Dictionary](https://mpv.io/manual/stable/#key-value-list-options), `append` is supposed to "escapes for the key, no escapes for the value". It is escaping both the key and value, contrary to documentation.

    {"command":["change-list","ytdl-raw-options","add","%4%key1=%6%value1"],"request_id":1}
    {"data":null,"request_id":1,"error":"success"}
    {"command":["get_property","ytdl-raw-options"],"request_id":2}
    {"data":{"key1":"value1"},"request_id":2,"error":"success"}

The best way of escaping from code is using `%n%` syntax, which is buried under Paths yet doesn't only apply to paths.

> For paths passed to suboptions, the situation is further complicated by the need to escape special characters. To work this around, the path can be additionally wrapped in the fixed-length syntax, e.g. %n%string_of_length_n (see above).

It is not "string of length n" but rather, "string encodes as n bytes in UTF8"

Note that fixing this will be a breaking change for the code I just wrote.

**Comment by avih** [comment]
The TL;DR is that yes, the escaping is very complex, and might have bugs which are very hard to fix.

Specifically for the things you raised:

> For List Options, the following methods should interpret escapes but don't: set, add, pre

That seems to be true.




> For [Key/Value Dictionary](https://mpv.io/manual/stable/#key-value-list-options), `append` is supposed to "escapes for the key, no escapes for the value". It is escaping both the key and value, contrary to documentation.
> 
> ```
> {"command":["change-list","ytdl-raw-options","add","%4%key1=%6%value1"],"request_id":1}
> {"data":null,"request_id":1,"error":"success"}
> {"command":["get_property","ytdl-raw-options"],"request_id":2}
> {"data":{"key1":"value1"},"request_id":2,"error":"success"}
> ```

That's because you actually used `add` and not `append`. If you replace it to `append` then the `%6%value1` will be literally the value.

**Comment by avih** [comment]
> It is not "string of length n" but rather, "string encodes as n bytes in UTF8"

That depends on how you define "string of length n". In this case the definition is that of the C function `strlen`.

It might be worth clarifying it at the docs.

**Comment by mysteryx93** [comment]
> That's because you actually used `add` and not `append`. If you replace it to `append` then the `%6%value1` will be literally the value.

Good catch. False alarm :)

    {"command":["change-list","ytdl-raw-options","append","%4%key1=%6%value1"],"request_id":1}
    {"data":null,"request_id":1,"error":"success"}
    {"command":["get_property","ytdl-raw-options"],"request_id":2}
    {"data":{"key1":"%6%value1"},"request_id":2,"error":"success"}

> That depends on how you define "string of length n". In this case the definition is that of the C function strlen.

From an API perspective, I shouldn't need to know the internal C implementation. When I send data as JSON, there is no specific encoding (technically I think it uses UTF8 but only the basic characters?) and byte count only comes into play once we put a specific data encoding. In .NET I need to use `System.Text.Encoding.UTF8.GetByteCount(value)`, whereas the doc suggests `value.Length`

**Comment by avih** [comment]
I think these documentation changes will address the correctness issues you raised (considering the "append" complaint is invalid):
1. For list options (not key-value), change the description of `-set: Set a list of items (using the list separator, interprets escapes)` to `-set: Set a list of items (using the list separator, which can be escaped with backslash)`.
2. At the documentation of %n%, after the format of `%n%string_of_length_n`, add a comment that it refers to the length in bytes of the UTF8 string.

Is this correct? Is there anything else left unanswered?

As per "JSON, there is no specific encoding", you're wrong. Read the JSON spec, UTF-8 is the one and only encoding supported in JSON.

**Comment by avih** [comment]
In general, you should consider the communication protocol (in your case JSON-IPC) as just the transport layer which doesn't perform any interpretation or parsing beyond decoding the JSON data.

mpv options parsing works on the data after the transport layer. That's where the `%n%` is interpreted, and also, for instance, escape a list separator of `set` with backslash - the JSON should encode a backslash before the separator, i.e. the JSON will have two backslashes because that's how JSON encodes a backslash.

mpv will then see `\<separator>` (one backslash after decoding the JSON) and then apply its escape interpretation on it to produce a literal separator char which is taken as part of the value and does not delimit the list item.

**Comment by mysteryx93** [comment]
So you're saying that list-add has a different escaping logic than dictionary-add, using backslash? How would you pass a value containing "\,"? That's kind of awkward, but as long as the documentation is clear and consistent.

**Comment by avih** [comment]
> So you're saying that list-add has a different escaping logic than dictionary-add, using backslash?

I'm reading the code, and that's what it does.

> How would you pass a value containing ","?

I mentioned it both in my suggested correction to the docs and in the following post, by using backslash to escape it. for instance:
```
{"command":["change-list","reset-on-next-file","set","foo\\,bar,baz"]}
```
Will create a list of two items: `foo,bar` and `baz`.

> That's kind of awkward

Yes, but more than awkward it's complex, as I mentioned in my first reply in this issue, and which the docs also mention more than once.

Generally, you can't avoid complex escaping mess when you want to use plain text to comunicate compound values. JSON can remove all the escaping mess, at least in some cases, but it's very verbose and inconvenient to use at the command line.

mpv is primarily a command line player, and the JSON-IPC interface was added on top of the existing code. In some cases it can be used in a way which avoids escaping, and in some cases the internal options parser is still invoked.

In the case of list option, only the list separator needs escaping, so it's easiest for the user if all other escapes are ignored. In the case of key-value list it's more complex, hence it needs to support more escaping, and that's also the reason that the multi-items operations are discouraged, and a more convenient `append`` can be used.
