### ISSUE TITLE
Next video in playlist is stuck on pause if loaded by scrolling to the end of the previous video

### ISSUE THREAD

**Issue by JpegXguy** [mpv-player/mpv#8768]
### Important Information

Provide following Information:
- mpv 0.33.1-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100 (runtime 56.70.100)
   libavcodec      58.91.100 (runtime 58.134.100)
   libavformat     58.45.100 (runtime 58.76.100)
   libswscale      5.7.100 (runtime 5.9.100)
   libavfilter     7.85.100 (runtime 7.110.100)
   libswresample   3.7.100 (runtime 3.9.100)
FFmpeg version: n4.4

- Arch Linux
- https://archlinux.org/packages/community/x86_64/mpv/ (Using 1:0.33.1-1 right now)
- Cinnamon (but it happens using Weston and `--gpu-context wayland` as well)
- amdgpu, Linux 5.11.16
- [Here's a video showing the issue](https://youtu.be/DlB-I6bzB38)

### Reproduction steps

1.  Run mpv either with a playlist of videos, or on a folder, or using autoload.lua which will create a playlist even if one file is loaded
2. Scroll to the end of the video.
3.  Next video loads, but it's paused and Play/Pause does nothing

I can reproduce this with any 2+ videos, even without using the script I normally use, autoload.lua. I moved the scripts folder and ran mpv on a folder with `--no-config`, and it still happens.

### Expected behavior

Next video plays after scrolling to the end of the current one, as happens with music files. I remember this used to be how it was with videos as well

### Actual behavior

Next video loads, but as a still image of the first frame, play/pause don't work until I move the timestamp, e.g. by scrolling or with the right arrow on the keyboard

### Log file

Running `mpv --no-config .` In a folder with the 2 videos seen in the attached explanatory video (at the top of this issue)
[output.txt](https://github.com/mpv-player/mpv/files/6368551/output.txt)

**Comment by Dudemanguy** [comment]
I can't reproduce this on master. Is the bug supposed to happen on local videos too? That's all I tested this on. I was too lazy to try a playlist over the internet.

**Comment by JpegXguy** [comment]
Ah sorry if I wasn't clear. My testing is with local videos. That said, I just tried this with a YT playlist, and the same thing happens.

Also yeah, I kind of expected that it would not be easily reproduced. I wanted to downgrade mpv though the Arch Linux archive but older versions require older versions of other libraries like dvdread and it fails to launch. Maybe I can build mpv-git or sth?

also, I just tried on tty with vo=drm and the same happens

As always, pressing Enter (next video) works, just not scrolling to the end of the current video. Then the issue appears

**Comment by Dudemanguy** [comment]
>Maybe I can build mpv-git

Yeah that would be the master branch.

**Comment by avih** [comment]
> I can reproduce this with any 2+ video
> Also yeah, I kind of expected that it would not be easily reproduced

If you can always reproduce it, why did you expect that it would be hard to reproduce?

Is there something special or unique or rare with your system or your videos which you think affects the issue and therefore it will be hard to reproduce elsewhere?

Knowing why you think it would be hard to reproduce could actually help quite a lot in finding the issue.

**Comment by JpegXguy** [comment]
I thought it would be hard to reproduce because I haven't seen it mentioned anywhere. As such I assume that it is rare or only affects me but I don't know why yet.

I'll try to build an older version of mpv

**Comment by Dudemanguy** [comment]
Could you first confirm if you can reproduce it on the master branch?

**Comment by qmega** [comment]
Can reproduce, including with `--no-config`.
Bisected:
b74c09efbf7c6969fc053265f72cc0501b840ce1 is the first bad commit

When it happens, the OSD (not OSC) shows the buffering icon.

I can also reproduce with a single file and `--loop-file`, so it's not dependent on loading a new file, just... a playback restart after EOF?
I *cannot* reproduce with `--no-aid` *or* `--no-vid`, so perhaps something to do with A/V sync.
...and I cannot reproduce with `--ao=alsa` or `--ao=null`, so **seemingly specific to the pulse ao**.

Working version:
```
[   4.630][v][mkv] EOF reached.
[   4.630][v][af] filter input EOF
[   4.630][v][af] filter output EOF
[   4.630][v][vf] filter input EOF
[   4.630][v][vf] filter output EOF
[   4.630][v][cplayer] video EOF reached
[   4.630][d][cplayer] video EOF (status=5)
[   4.630][v][cplayer] playback restart complete @ -9223372036854775808.000000, audio=eof, video=eof
```
Broken version (and log from @JpegXguy is similar):
```
[   1.672][v][mkv] EOF reached.
[   1.672][v][vf] filter input EOF
[   1.672][v][vf] filter output EOF
[   1.672][v][cplayer] video EOF reached
[   1.672][d][cplayer] video EOF (status=4)
[   1.672][v][af] filter input EOF
[   1.672][v][af] filter output EOF
[   1.672][v][cplayer] audio filter EOF
[   1.672][d][cplayer] video EOF (status=4)
[   1.672][v][cplayer] audio ready (and EOF)
[   1.672][d][cplayer] video EOF (status=4)
[   1.672][v][cplayer] starting audio playback
[   1.672][v][ao/pulse] audio end or underrun
[   1.672][v][cplayer] playback restart complete @ -9223372036854775808.000000, audio=draining, video=eof
```

**Comment by JpegXguy** [comment]
All the workarounds @qmega mentioned work for me. Nice work!
Important information that I just thought of: I switched to using pipewire with its pulse layer, instead of pulseaudio some time ago, and mentally it might actually overlap.

Are you using pipewire,@qmega?

**Comment by qmega** [comment]
> Are you using pipewire,@qmega?

No, I'm using actual pulseaudio (14.2) at the moment, though I have been meaning to try pipewire again.

**Comment by JpegXguy** [comment]
I temporarily reinstated `pulseaudio`, removing `pipewire-pulse`, and I can still reproduce this on the latest version of mpv, so it's indeed not pipewire's emulation of pulse at fault.

I can also confirm that building on b74c09e, I come across this problem, while building on its parent bb1f821, things work fine.
