### ISSUE TITLE
Unable to get fullscreen automatically in Gnome 40 Wayland

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#8773]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.33.0-128-gd3b7732aaa Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.74.100
   libavcodec      58.136.101
   libavformat     58.78.100
   libswscale      5.10.100
   libavfilter     7.111.100
   libswresample   3.10.100
FFmpeg version: N-102031-gd98884be41
```
- Linux Distribution and Version
```
                   -`                    
                  .o+`                   --------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 5.11.16-arch1-1 
               `+oooooo:                 Uptime: 1 hour, 6 mins 
               -+oooooo+:                Packages: 1108 (pacman) 
             `/:-:++oooo+:               Shell: zsh 5.8 
            `/++++/+++++++:              Resolution: 1920x1080 
           `/++++++++++++++:             DE: GNOME 40.1 
          `/+++ooooooooooooo/`           WM: Mutter 
         ./ooosssso++osssssso+`          WM Theme: Adwaita 
        .oossssso-````/ossssss+`         Theme: Adwaita-dark [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: Adwaita [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: gnome-terminal 
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/59 
  `+sso+:-`                 `.-/+oso:    Memory: 2758MiB / 32072MiB 
 `++:.                           `-/+/
 .`                                 `/                           
```
- Source of the mpv binary
mpv-build-git in AUR.
- If known which version of mpv introduced the problem
I don't know.
- Window Manager and version
Mutter 40.0+55+gf4f82bcb9-1
- GPU driver and version
```
vainfo: VA-API version: 1.11 (libva 2.11.1)
vainfo: Driver version: Mesa Gallium driver 21.0.3 for Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.11.16-arch1-1, LLVM 11.1.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```
- Possible screenshot or video of visual glitches
Just like normal but without fullscreen.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Playing the video with `glsl-shaders-append="~~/shaders/KrigBilateral.glsl"` or other glsl stuff.

### Expected behavior
It plays the video in fullscreen.
### Actual behavior
It doesn't.
### Log file
[fullscreen.txt](https://github.com/mpv-player/mpv/files/6371209/fullscreen.txt)
### Sample files
[test.zip](https://github.com/mpv-player/mpv/files/6371268/test.zip)

**Comment by Dudemanguy** [comment]
Can't reproduce here. That said, your log does have some very mysterious `Resizing due to xdg from [. . .]` that happen in rapid succession for some inexplicable reason.

**Comment by laichiaheng** [comment]
> Can't reproduce here. That said, your log does indeed have some very mysterious `Resizing due to xdg from [...]` messages that happen in rapid succession for some inexplicable reason.

It only happens with glsl-shaders, without them, it works fine.

**Comment by Dudemanguy** [comment]
>It only happens with glsl-shaders, without them, it works fine.

Which doesn't make any sense really. That said, I works for me with glsl-shaders. I normally use FSRCNNX 8 as part of my setup anyway. Regardless, something is somehow triggering a resize for you as the log shows.

**Comment by laichiaheng** [comment]
> > It only happens with glsl-shaders, without them, it works fine.
> 
> Which doesn't make any sense really. That said, it works for me with glsl-shaders. I normally use FSRCNNX 8 as part of my setup anyway. Regardless, something is somehow triggering a resize for you as the log shows.

I've found something, It happens when if enable the auto-profile

**Comment by CounterPillow** [comment]
```
[   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 4K condition"]:1: attempt to compare number with nil 
[   0.034][v][auto_profiles] Re-evaluating auto profile 4K60 
[   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 4K60 condition"]:1: attempt to compare number with nil 
[   0.034][v][auto_profiles] Re-evaluating auto profile 8K 
[   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 8K condition"]:1: attempt to compare number with nil 
[   0.034][v][auto_profiles] Re-evaluating auto profile HDR 
[   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile HDR condition"]:1: attempt to index global 'video_params' (a nil value) 
[   0.034][v][auto_profiles] Re-evaluating auto profile VP9 
[   0.034][v][auto_profiles] Re-evaluating auto profile mpeg 
[   0.034][v][auto_profiles] Re-evaluating auto profile 雙聲道 
[   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 雙聲道 condition"]:1: attempt to index global 'audio_params' (a nil value) 
[   0.034][v][auto_profiles] Re-evaluating auto profile 多聲道 
[   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 多聲道 condition"]:1: attempt to index global 'audio_params' (a nil value) 
```
if those broken auto profiles try resizing something, that would explain the 0x0 resizes.

Unlikely to be a bug in mpv if your script does things like this.

**Comment by laichiaheng** [comment]
> ```
> [   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 4K condition"]:1: attempt to compare number with nil 
> [   0.034][v][auto_profiles] Re-evaluating auto profile 4K60 
> [   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 4K60 condition"]:1: attempt to compare number with nil 
> [   0.034][v][auto_profiles] Re-evaluating auto profile 8K 
> [   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 8K condition"]:1: attempt to compare number with nil 
> [   0.034][v][auto_profiles] Re-evaluating auto profile HDR 
> [   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile HDR condition"]:1: attempt to index global 'video_params' (a nil value) 
> [   0.034][v][auto_profiles] Re-evaluating auto profile VP9 
> [   0.034][v][auto_profiles] Re-evaluating auto profile mpeg 
> [   0.034][v][auto_profiles] Re-evaluating auto profile 雙聲道 
> [   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 雙聲道 condition"]:1: attempt to index global 'audio_params' (a nil value) 
> [   0.034][v][auto_profiles] Re-evaluating auto profile 多聲道 
> [   0.034][v][auto_profiles] Profile condition error on evaluating: [string "profile 多聲道 condition"]:1: attempt to index global 'audio_params' (a nil value) 
> ```
> 
> if those broken auto profiles try resizing something, that would explain the 0x0 resizes.
> 
> Unlikely to be a bug in mpv if your script does things like this.

So I can't put the shaders in auto-profiles? It's the main reason I use it for different resolution of videos.

**Comment by CounterPillow** [comment]
I don't know what's causing it, but you should isolate it by starting with `--no-config` and seeing with what minimal combination of things the issue happens because it's impossible to find out what's causing it in a setup like this

**Comment by laichiaheng** [comment]
> I don't know what's causing it, but you should isolate it by starting with `--no-config` and seeing with what minimal combination of things the issue happens because it's impossible to find out what's causing it in a setup like this

I have tried many times with `--no-config`, but it works every time with shaders and other settings, but once I enable the auto-profiles with scaling methods or shaders, it happens.

**Comment by laichiaheng** [comment]
It seems like it only happens to Gnome Wayland, it doesn't happen to weston.

**Comment by Dudemanguy** [comment]
I don't get the behavior you describe with that file at all. Instead I get a `[vo/gpu/opengl] before video texture creation: OpenGL error INVALID_OPERATION.` as a result of trying to use those height/width conditions in the autoprofile. So that sounds like an mpv bug to me at least.

**Comment by laichiaheng** [comment]
> I don't get the behavior you describe with that file at all. Instead I get a `[vo/gpu/opengl] before video texture creation: OpenGL error INVALID_OPERATION.` as a result of trying to use those width/height conditions in the autoprofile. So that sounds like an mpv bug to me at least. It probably tries to get the width/height before the video actually exists.

Which file? If you mean my log file, I just use different resizing methods for different resolutions.

**Comment by Dudemanguy** [comment]
I meant the test file you linked with your sample config. Out of curiosity, what happens if you use `--gpu-api=vulkan`? Do you still get the same bug?

**Comment by laichiaheng** [comment]
> I meant the test file you linked with your sample config. Out of curiosity, what happens if you use `--gpu-api=vulkan`? Do you still get the same bug?

Yes, it still get the same bug with vulkan api.

**Comment by laichiaheng** [comment]
> I meant the test file you linked with your sample config. Out of curiosity, what happens if you use `--gpu-api=vulkan`? Do you still get the same bug?

Yes, it still gets the same bug with vulkan api, and it is even worse, it cant work with vaapi.
![2021-04-25 23-30-36 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/115999470-7b223080-a61e-11eb-8c8d-e2ace1a53886.png)

**Comment by Dudemanguy** [comment]
That's completely unrelated. I don't believe 10bit HEVC supports hwdec. There's something funny going on here with fullscreen states in wayland and that auto-profile condition though. That is definitely a bug (working on it).

**Comment by laichiaheng** [comment]
> That's completely unrelated. I don't believe 10bit HEVC supports hwdec. There's something funny going on here with fullscreen states in wayland and that auto-profile condition though. That is definitely a bug (working on it).

What do you mean? RX580 does support HEVC 10bit vaapi decoding.

**Comment by Dudemanguy** [comment]
>RX580 does support HEVC 10bit vaapi decoding

Ah, maybe my information is outdated then. Whatever it is, it's something else completely.

**Comment by laichiaheng** [comment]
It has been fixed, thanks.
