### ISSUE TITLE
Stats Display Problem After Commit f665149fc8

### ISSUE THREAD

**Issue by CharlesMengCA** [mpv-player/mpv#8775]
### Important Information

Provide following Information:
- mpv version: versions after mpv 0.33.0-121-gf665149fc8
- Windows Version: Windows 10 20H2, 19042.928
- Source of the mpv binary:  custom build using modified Shinchiro's script
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Expected behavior
Stats displayed correctly.
### Actual behavior
![Screenshot 2021-04-25 114842](https://user-images.githubusercontent.com/58993776/115999961-3665ad80-a5bc-11eb-8720-41b0d5e23790.png)

### Log file

D:\LinuxFolder\Mod>mpv d:\samsung-uhd-dive-to-new-world.mkv
 (+) Video --vid=1 (*) (h264 3840x2160 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (ac3 2ch 48000Hz)
Using hardware decoding (nvdec).
AO: [wasapi] 96000Hz stereo 2ch float
VO: [gpu] 3840x2160 cuda[nv12]
AV: 00:00:06 / 00:01:52 (6%) A-V:  0.000
[osd/libass] fontselect: Using default font family: (sans, 400, 0) -> ArialMT, 0, ArialMT
[osd/libass] fontselect: Using default font family: (sans, 700, 0) -> Arial-BoldMT, 0, Arial-BoldMT
AV: 00:00:12 / 00:01:52 (11%) A-V:  0.000

The issue will be closed for ignoring the issue template.

### Sample files
Any 4K demo should produce the prolem.
https://4kmedia.org/samsung-dive-to-the-new-world-uhd-4k-demo/

**Comment by jeeb** [comment]
It would be highly surprising if the commit mentioned actually affects this, so most likely this is just the point to which you recently updated to.

I would recommend checking the basics:

1. Does this happen without hwdec?
2. If you rebuild your previous version with the dependencies that you utilized for this newer build, do you get similar corruption?

Thanks.

**Comment by jeeb** [comment]
Not getting this issue with my current dependencies and d3d11va NV12 output at least, so whatever is your issue is not a general problem with NV12 input at least.

**Comment by CharlesMengCA** [comment]
![No-hwdec](https://user-images.githubusercontent.com/58993776/116322669-7e3a2f80-a78a-11eb-98fe-2dc69a406748.png)
![d3d11va](https://user-images.githubusercontent.com/58993776/116322672-7ed2c600-a78a-11eb-8597-deb92e62c28e.png)
![vulkan](https://user-images.githubusercontent.com/58993776/116322673-7f6b5c80-a78a-11eb-81ce-62a22cc97490.png)

all 3 settings, no-hwdec, d3d11va and vulkan,  are having the problem.

Without changing anythings, just replace the mpv.exe built on April 20 and everything will be fine.

That's where I got the idea that a commit after April 20 is causing the problem.

**Comment by CharlesMengCA** [comment]
downgrade NVIDIA driver from 466.11 to 460.89, still same problem.

**Comment by CharlesMengCA** [comment]
The problem has gone on today's build

**Comment by avih** [comment]
> The problem has gone on today's build

I see that you use shinchiro's build script. Would you mind uploading your latest mpv binary someplace? I'd like to test something - #8667  . Thanks in advance.

**Comment by CharlesMengCA** [comment]
my build has JavaScript disabled. maybe not suit for your need.

**Comment by avih** [comment]
I see. Well, if you can afford and would be kind to enable js and upload a build someplace, I'd appreciate it.

**Comment by CharlesMengCA** [comment]
https://github.com/CharlesMengCA/mpv-player-only/avih.7z.001, avih.7z.002, avih.7z.003

**Comment by avih** [comment]
Highly appreciated. Thank you.

For reference, the js issue exists also in your build. I'll update the other thread too.

**Comment by astiob** [comment]
For reference, this may have been a libass issue fixed by libass/libass@db5813281393e39ea996118fd02ddb9442ad3889.
