### ISSUE TITLE
Unable to Seek on Some Audio CDs

### ISSUE THREAD

**Issue by lazerfloyd** [mpv-player/mpv#8777]
Same exact bug as closed issue #1614 - "cdda:// reports no chapters; cdda://1-99 reports exact number of chapters." According to the comments, the underlying bug was never fixed (might be an issue with libcdio itself) and newer versions of mpv no longer seem to accept track numbers at the command line, e.g. `mpv cdda://1` produces a `can't get file status for 1` error message. As such, there is no more workaround for this issue.

### Important Information

- mpv version: 0.33.0
- Linux Distribution and Version: Lubuntu 20.04 LTS (Focal Fossa)
- Source of the mpv binary: http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu/
- Window Manager and version: Openbox/LXQt

### Reproduction steps

Running `mpv cdda://` with specific CDs (a large proportion plays perfectly fine, but certain older ones produce the issue.)

### Expected behavior

Once the CD begins playing, pressing the chapter back and/or forward keys should seek to the previous/next track.

### Actual behavior

CD plays, but mpv outputs `Chapter: (unavailable)` with every key press.

### Log file

[Here is the log file](https://0x0.st/-mVw.txt)

### Samples

I have a large stash of "bad CDs" I can test against and can try to provide specific editions/pressings if it helps.

**Comment by CounterPillow** [comment]
> but certain older ones produce the issue.

What kind of years are we looking at here? I don't own that many CDs but I can look around the house to see if I can find something of comparable vintage to maximise my chances of reproducing this.

Knowing what version your libcdio is may be of help as well.

**Comment by lazerfloyd** [comment]
I think the most common ones that trigger this error in my collection are the original CD versions of the Beatles' albums (pre-2009 remasters). I can confirm Abbey Road, Sgt. Pepper's Lonely Hearts Club Band, Magical Mystery Tour and Yellow Submarine all cause the issue. Just in case, I'll look on Discogs and see if I can match the numbers on the spine with a more specific pressing date. Also happens with original issues of The Doors' Strange Days, The B-52's self-titled, and Cream's Wheels of Fire. So, at a glance, I'd say early CDs from the late 80's/early 90's? Strangely, though, it also happens with my Joy Division Heart & Soul box set, and that came out in 1997, so maybe it's not that cut-and-dried.

I've got libcdio18 version 2.0.0-2 installed (from the Focal Ubuntu repos.)

**Comment by CounterPillow** [comment]
The time frame of early 90s lines up surprisingly well with the age of CDs before [CD text](https://www.gnu.org/software/libcdio/cd-text-format.html) was introduced in 1996. CD Text, among other things, stores a table of contents with the song titles.

**Comment by lazerfloyd** [comment]
That would make a lot of sense... Would output from cd-info be useful, then? Also, I checked and the Beatles CDs are all original 1987 versions.

**Comment by Dudemanguy** [comment]
I pulled out one of my old Iron Maiden CDs (1984) and lo and behold I can reproduce this. cd-info does give the correct track information so you'd think this would be fixable somehow.

**Comment by mia-0** [comment]
Gonna try figuring this out. The libcdio documentation just says “🖕” but a bunch of stuff in mpv’s stream_cdda.c looks outdated and possibly incorrect, so I’ll give fixing that a try.

**Comment by lazerfloyd** [comment]
Any luck? I tried to find helpful documentation and came up empty as well. The code itself is pretty inscrutable for a near clueless neophyte like myself. Maybe reenabling track selection at the command line (e.g. "cdda://1-99") would be an acceptable workaround considering it's not a simple fix to get this to work as intended?
