### ISSUE TITLE
Playing ISM videos

### ISSUE THREAD

**Issue by selfisekai** [mpv-player/mpv#8778]
### Important Information

Provide following Information:
- mpv version: 0.33.1
- Platform and Version: Void Linux (rolling release; x86_64, glibc)
- Source of the mpv binary: Void's xbps repository (no patches - see [build template](https://github.com/void-linux/void-packages/blob/87b46009d1472ce5928c55aba7153bc7ea363c55/srcpkgs/mpv/template))

### Reproduction steps

Try to play a ISM video, some examples below.

Using [haruhi-dl](https://haruhi.download/) (disclosure: I'm a haruhi-dl maintainer) as the ytdl binary, as I'm having difficulties to test with youtube-dl.

#### TVP

```sh
mpv ytdl://tvp:18793117 --ytdl-format='bestvideo[protocol=ism]+bestaudio[protocol=ism]'`
```
Note: HDL reimplemented this extractor to use their new API, but ISM fragments extracted seem to be the same except just the URL protocol (https vs http).

#### Azure Media Services demo

```
mpv https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest
```

### Expected behavior

mpv should play the video to the user.

### Actual behavior

A lot of URLs in unclear errors (like `No video or audio streams selected.` or `EDL: source file 'edl://[a huge load of URLs skipped]' has unknown duration.`) are thrown.

### Log file

- tvp: https://0x0.st/-mV2.txt
- ams: https://0x0.st/-mV7.txt

**Comment by jeeb** [comment]
Ah, microsoft smooth streaming manifests. Didn't think I'd see these in the modern age any more :) .

I don't think FFmpeg has a wrapper for this this format, which is why it doesn't work. Thus this would be a feature request for FFmpeg. Now that the DASH manifest parser is in there with libxml2, I think the gates are open for xml based manifest reading, so if someone cares enough they could attempt to implement it :) .

Thus, closing.

**Comment by jeeb** [comment]
For the record, the FFmpeg issue tracker where you can add a feature request for this format is https://trac.ffmpeg.org/ .

**Comment by jeeb** [comment]
Uhh, do note if this was about EDL and I can re-open. I just looked at the smooth streaming manifest and based my response on that.
