### ISSUE TITLE
Invalid display FPS detection with mixed refresh rate using Wayland and vo=gpu

### ISSUE THREAD

**Issue by Azenet** [mpv-player/mpv#8780]
### Important Information

- mpv version: latest git (61a387ac95)
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: self-built
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: kwin_wayland 5.21.4-1 (arch)
- GPU driver and version: Mesa 21.0.3-2/AMDGPU 19.1.0-2

### Reproduction steps
1. Have a mixed-refresh rate setup
2. Play a video file with vo=gpu
3. Move the player to the screen with the highest refresh rate and set to fullscreen

### Expected behavior
When using the info menu, Display FPS shows a value matching the refresh rate the player is placed on, as vo=xv does properly (under XWayland).

### Actual behavior
The Display FPS values is either the lowest value of all monitors or the value of the primary monitor set in KWin (unable to test which).

### Log file
[out.txt](https://github.com/mpv-player/mpv/files/6378081/out.txt)

**Comment by Dudemanguy** [comment]
>Move the player to the screen with the highest refresh rate and set to fullscreen

Are you saying that the bug doesn't occur if the mpv window is not in fullscreen?

**Comment by Azenet** [comment]
> > Move the player to the screen with the highest refresh rate and set to fullscreen
> 
> Are you saying that the bug doesn't occur if the mpv window is not in fullscreen?

Sorry if that was unclear, it does occur either way. I meant that it's more likely the window overlaps several screens if not fullscreened, which might make it less easy to reproduce.

**Comment by Dudemanguy** [comment]
I'm going to go out on a limb and say that I think this is a Plasma bug. I can't reproduce it here, but I just realized that your setup is 3 monitors. I've only got the capability to test 2 monitors at most here, and that works as expected. That might be the main difference. Looking at your log, we get surface events in rapid succession (from 0.118s to 0.142s) which is probably bad and shouldn't happen. I really doubt you actually moved the mpv window across 3 monitors that fast (but hey maybe I'm wrong). It seems like to me that Plasma is sending us bogus surface entrance events.

If possible, could you try lowering your setup to just 2 monitors and seeing if you still get bad behavior?

**Comment by Dudemanguy** [comment]
Any updates on this out of curiosity?

**Comment by Azenet** [comment]
@Dudemanguy Sorry for the lack of updates, I forgot about actually testing variations on this issue. Now both gpu and xv show `Display FPS` as the highest refresh rate of all the monitors no matter what the situation, so I am assuming something did change upstream. I am however not running latest KWin/AMD drivers at the moment, so this may not be relevant.

**Comment by Dudemanguy** [comment]
Yeah if you aren't on wayland/kwin it's sadly not relevant.

**Comment by Azenet** [comment]
I meant I'm not running the latest versions, but I am running Wayland/KWin.

**Comment by Dudemanguy** [comment]
Well I would say problem solved in that case if it's working now? If you're on Arch, you should be on the latest major version of Kwin anyway (the last round of updates was a bugfix release).

**Comment by Azenet** [comment]
I didn't expect the Display FPS value to be highest of all screens in all situations, which is why I didn't close straight away, but if this is the expected behavior then this can be closed.

**Comment by Dudemanguy** [comment]
Oh my mistake, I thought you were only on the highest refresh rate monitor not on any screen. Then yeah, it's still a bug somewhere.

**Comment by Azenet** [comment]
Seems like changes to mpv or upstream wayland/plasma changes fixed this at some point, as this no longer happens. Thanks for your help diagnosing this issue!
