### ISSUE TITLE
Limit the number of entries returned by mp.utils.readdir()

### ISSUE THREAD

**Issue by glubsy** [mpv-player/mpv#8783]
### Expected behavior of the wanted feature
The lua function `mp.utils.readdir` (in [player/lua.c](https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/player/lua.c#L1049)) could take some extra arguments to limit the number of files/directories returned. This would be useful for directories holding many thousands of files.

For example: `mp.utils.readdir(path [,filter [,limit [,start_offset]]])`.
The underlying C function would stop reading the opened DIR* (pointed by `path`) after `limit` dirents have been read (by `readdir()`), starting from `start_offset` entries.
There could be 3 returned values: `result_table, error, offset`, where `offset` would be the value returned by `dirent->d_off;`. This value could be reused as `start_offset` in a subsequent call to continue reading the rest of the DIR. 

Currently, the [autoload.lua script](https://github.com/mpv-player/mpv/blob/0d384592c57771a0371399783238c490def1b231/TOOLS/lua/autoload.lua#L152) reads the entire file list into a table, and only then set the playlist to the hard-coded 5000 entry limit. This could be optimized better.

Just an idea, and certainly not a very high priority feature but I thought this could help with some user scripts.

**Comment by avih** [comment]
You didn't quite state what the actual user-facing problem and/or how limiting the read would help, and in what.

Personall I wouldn't consider an issue, but if you feel you can improve the user-facing behavior, then you can open a PR with your suggested solution.

On a hunch though, it's probably not worth your time.

**Comment by glubsy** [comment]
Thanks for the insight. 

The problem is when reading very large directories, it takes a very long time to load all the file entries, and in the case of the autoload script, only a fraction of the returned files are actually loaded into the playlist. Limiting the number of returned files upstream would help drastically reducing loading times, and avoid unnecessary enumerations. 

I'll probably try hacking a small user script in C first by re-implementing that function for myself.

**Comment by avih** [comment]
> it takes a very long time to load all the file entries

That's one issue. It probably depends on how fast the disk is etc, but sure, it can be not nice.

> in the case of the autoload script, only a fraction of the returned files are actually loaded into the playlist

That's a different issue.

However, simply limiting the number does not automatically solve these issues. Well, or maybe it does but immediately introduces other issues.

The real question is how do you use it to create a better user experience. And the answer for that is far from simple IMHO.

But sure, you can have a go. If the solution to the user experience problem (not the modified API) is reasonably clean and not too big, it could be interesting.

**Comment by avih** [comment]
For reference, after discussion on IRC it became clear that the ultimate goal was to make `autoload.lua` load files more granularly to address a suspected slow performance with many files - which was never observed in practice (just as precaution).

However, it soon became clear that limiting the number of files from `utils.readdir` can't help at all here, even with additional code complexity, because `autoload` adds to the playlist files which are alphabeticallty just before/after the target file, however, this always requires enumerating all the files anyway, sorting them, and them picking the ones around the current file.

So at least for the use case which OP had in mind - it just wouldn't help anything.
