### ISSUE TITLE
API MsgLevel Doesn't Support Add/Append

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#8784]
Using MPV v0.33.1 on Windows 10 x64.

Communicating with the player via JSON IPC.

`msg-level` looks like a standard [key/value pair](https://mpv.io/manual/stable/#key-value-list-options). It also returns a dictionary.

Why does it not support standard key-value methods?

    {"command":["change-list","msg-level","add","%3%all=%4%warn"],"request_id":1}
    {"request_id":1,"error":"error running command"}

**Comment by avih** [comment]
> msg-level looks like a standard key/value pair. It also returns a dictionary.
> Why does it not support standard key-value methods?

Because it's not a list option, and it's also not documented as a list option.

Internally, it's a unique option type which is used only for `msg-level`, probably because it couldn't use the list option type due to $reasons.
