### ISSUE TITLE
MPV unable to run video wallpaper on Lively after Voicemeeter installation 

### ISSUE THREAD

**Issue by saenpak-929U** [mpv-player/mpv#8788]
### Important Information

Provide following Information:
- mpv version - MPV from Lively
- Windows Version - 19042
- Source of the mpv binary - MPV from Lively
- If known which version of mpv introduced the problem - MPV from Lively
- Possible screenshot or video of visual glitches
![image](https://user-images.githubusercontent.com/50975246/116468327-b7cc7280-a83e-11eb-9a9a-b5de933189fb.png)

### Reproduction steps
After having installed Lively, I installed Voicemeeter Potato.  After a restart, MPV was unable to decode the video wallpaper I had set in Lively

### Expected behavior
![image](https://user-images.githubusercontent.com/50975246/116468327-b7cc7280-a83e-11eb-9a9a-b5de933189fb.png)
The video should have been set as the wallpaper

### Actual behavior
![image](https://user-images.githubusercontent.com/50975246/116468203-9075a580-a83e-11eb-9640-1c2961457bbe.png)
Error message

### Log file
[210428 error log chunk.txt](https://github.com/mpv-player/mpv/files/6394607/210428.error.log.chunk.txt)
Log file from Lively log file

### Sample files
I have no sample file since it was an upload to the Lively App

**Comment by CounterPillow** [comment]
Why are you reporting an issue for Lively on the mpv bugtracker? What you attached is not an mpv log.

**Comment by saenpak-929U** [comment]
[https://github.com/rocksdanister/lively/issues/465](url)
The Lively Dev told me to report to MPV devs

**Comment by saenpak-929U** [comment]
i fixed the issue
