### ISSUE TITLE
Rear speaker channels will not play in 5.1 or 7.1 audio from MKV file. 

### ISSUE THREAD

**Issue by sskevinm78** [mpv-player/mpv#8793]
### Important Information

Provide following Information:
- mpv version - 0.33-107
- Windows Version - Windows 10 64-bit (20H2)
- Source of the mpv binary - No
- If known which version of mpv introduced the problem -No
- Possible screenshot or video of visual glitches - No

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Play MKV file with 5.1 or 7.1 audio analog output to speakers from sound card

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior

5.1 or 7.1 audio

### Actual behavior
No sound to rear speakers; all other speakers have sound

MKV file plays in full 5.1 or 7.1 with Media Player Classic and VLC.  So the MKV file is tested to be good.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Doofussy2** [comment]
With no log, we have no idea of what you're doing. Are you using bitstreaming? Are you decoding and configuring Windows audio, correctly? I use 7.1 for everything and have no issues. You need to attach a log file.

https://mpv.io/manual/master/#options-log-file

**Comment by amariami** [comment]
> 
> Play MKV file with 5.1 or 7.1 audio analog output to speakers from sound card
> No sound to rear speakers; all other speakers have sound
> MKV file plays in full 5.1 or 7.1 with Media Player Classic and VLC. So the MKV file is tested to be good.

it seems you don't understand how to create a log file.

1. Just edit file " mpv.conf " with Notepad or Notepad++ (run as administrator)
2. Type `--log-file="C:\sskevinm78mpv.log"`
3. Play your Play MKV file with MPV player in few seconds then close it
4. Upload your log file (sskevinm78mpv.log) located in Local Disk C

Reference for a beginner (me too)
`https://iamscum.wordpress.com/guides/videoplayback-guide/`

**Comment by sskevinm78** [comment]
Hello,

Sorry about the long delay in response.  I could not find the mpv.conf file in either "\AppData\Roaming\mpv" or "mpv" folder from the download.  I created the CONFIG file, added "--log-file="C:\sskevinm78mpv.log" and added the file to both directories.  I played the MVK with MPV and it did not create a log file as expected.

But I did something different and discovered the problem.  I opened the MKV file with mpv.com and the output console opened displaying the actions of player.  I noted the audio was playing with 5.1(SIDE).  I tested side analog outputs (right and left) and sure enough the rear channels were playing through the the side analog outputs.

I assume FFMPEG is upmixing and redirecting rear channel to the side.  Please let me know what to do to be able to get the log file working so I can upload.  Or how to direct rear output to rear channels.

Thanks again for all the help.

**Comment by Doofussy2** [comment]
If you're not bitstreaming the audio, and you have Windows audio configured to your 7.1 speaker array. I'd suggest upmixing 5.1 to 7.1. That's what I do with 5.1 AAC. You'll want to configure mpv to your speaker channels then use ffmpeg to upmix.

```
audio-channels=7.1
af=lavfi-surround:chl_out=7.1:lfe_low=80
```

https://mpv.io/manual/master/#options-audio-channels

https://ffmpeg.org/ffmpeg-filters.html#surround

**Comment by Dudemanguy** [comment]
Seems like simply a configuration issue + no follow up from OP so closing.
