### ISSUE TITLE
Frames are being dropped whenever the OSD or Seek bar etc appears

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#8798]
I mean whenever (I for example move the mouse so) the lower part of screen shows up, the frame drop counter visible in it (I believe I enabled one to show up above the seek bar), shows that frames are being dropped.

This happens on different machines and operating systems, and isn't brand new.

I'm using this very nice built-in transparent theme:  https://imgur.com/a/wRKZF7L
(no, the frames dont drop from the high video resoultion, they only do when the seek bar is visible, regardless of the video resolution, machine, operating system, etc).

**Comment by avih** [comment]
Feel free to request to re-open it after you follow the template.
