### ISSUE TITLE
More geometry profiles for many files!

### ISSUE THREAD

**Issue by 921j** [mpv-player/mpv#8800]
I often open multiple video files on the same screen to watch at the same time. The video windows that I open each time will be stacked together by default and need to be dragged and placed manually. I hope that --geometry can have more parameters to specify for multiple files Different locations.
For example: if I define 4 positions, then the window position for opening the file will Cyclic placed in these 4 positions.
If there is any script or command that can achieve this function, please let me know, thank you!

**Comment by avih** [comment]
An mpv instance has at most one window, and mpv does not communicate with other instances of mpv. You can control the positioning of any instance of mpv via command line arguments, but mpv will not implement a mechanism to coordinate positioning with other instances of mpv.

In general, windows arrangements and/or tiling is the task of your OS, desktop environment, or window manager. It's not a task of mpv.
