### ISSUE TITLE
utils.file_info(...).ctime returns wrong timestamp

### ISSUE THREAD

**Issue by CrendKing** [mpv-player/mpv#8801]
### Important Information

Provide following Information:
- mpv version: 20210404 (shinchiro)
- Windows Version: Windows 10 build 19042
- Source of the mpv binary: Scoop
- If known which version of mpv introduced the problem: https://github.com/mpv-player/mpv/commit/257a2b9646e845ef801588e871b9859d30ebf99a
- Possible screenshot or video of visual glitches: n/a

### Reproduction steps

1. Write a LUA script with `utils.file_info(...).ctime` in it. `msg.info()` the returned value.
2. Convert the epoch seconds with something like https://www.epochconverter.com/.
2. Compare the timestamp with right click -> Properties -> "Created".

### Expected behavior
According to the mpv manual, `ctime` should be [time of creation (Windows)](https://mpv.io/manual/master/#lua-scripting-ctime). The two timestamps should match.

### Actual behavior
They don't.

### More info

Problematic line is https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/osdep/io.c#L240

According to https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_basic_info, `ChangeTime` is the "The time the file was changed in FILETIME format." The right one should be `CreationTime`: "The time the file was created in FILETIME format, which is a 64-bit value representing the number of 100-nanosecond intervals since January 1, 1601 (UTC)."

**Comment by avih** [comment]
>     If known which version of mpv introduced the problem: 257a2b9

That's when the internal win32 `stat` support was added, but it's not necessarily wrong. `st_ctime` on linux is "time of last status change", while on Windows it's "The time the file was changed in FILETIME format." (in contrast to `LastWriteTime` which is mroe equivalemt to linux `st_mtime`).

According to this https://devblogs.microsoft.com/oldnewthing/20100709-00/?p=13463 , it's the most correct equivalent to linux:

> What’s the difference between writing to a file and changing it? I’m told that the difference is metadata. The Last­Write­Time covers writes to the file’s data stream (which you accomplish via the Write­File function). On the other hand, the Change­Time also includes changes to the file metadata, such as changing its file attributes (hidden, read-only, etc.) or renaming the file.

So, in fact, to me it seems that the documentation of `file_info` - added at 522bfe5b is simply wrong. I don't know why it states:
```
time of last metadata change (Linux) / time of creation (Windows)`
```

It could probably be changed to something like
```
time of last metadata change (Linux) / time of last metadata change or last write (Windows)
```

@CrendKing @tsaaristo @rossy
Do you agree it's just a documentation issue?

**Comment by CrendKing** [comment]
In Linux, ctime is [time of last status change](https://linux.die.net/man/2/stat), so I agree with you that `ChangeTime` is the closest. There is [`crtime`](https://www.tecmint.com/debugfs-command-show-file-creation-time-in-linux/) for creation time, but not offered by stat. So if the intention is to let Windows impl mimic the behavior of Linux, I agree this is a documentation issue.

However, is there a chance to support `CreationTime` on Windows? I myself need it in lua script. Maybe through a special, separate API in `utils`?

**Comment by avih** [comment]
> So if the intention is to let Windows impl mimic the behavior of Linux, I agree this is a documentation issue.

It's definitely the intent of 257a2b9 (internal stats), and I don't see any reason for 522bfe5 (scripting file_info) to want to change the intent - it's certainly not explained anywhere which I can see.

My guess is that the author of 522bfe5 (scripting file_info) performed some quick tests, noticed that `ctime` returns the creation time in their test (because that's probably the last time the metadata was changed), assumed incorrectly that it's creation time on windows - and documented it incorrectly.

So the documentation simply needs to be fixed.

> However, is there a chance to support CreationTime on Windows? I need it in a lua script. Maybe through a special, separate API in utils?

Well, this would be painful because on unix there won't be `crtime` member (of the internal stats implementation), and it would make more deviation between the unix and windows fields and/or locations which use it, which is even more painful because mpv doesn't actually need this value, and it will only be used by the scripting interface, and only on windows.

You can use `subprocess` with something like this https://www.windows-commandline.com/get-file-creation-date-time/ if it's only going to be used on windows anyway.

In general, file_info itself barely made it into mpv, because we really don't want to start exposing POSIX interfaces to scripts, and we definitely don't want to extend this trend, and even more so with windows-only features.

So the question to this answer, unless there's large disagreement by other devs, is "no".

**Comment by CrendKing** [comment]
Fairly enough. Thanks.

Do you need any info from me for the documentation change?

**Comment by rossy** [comment]
@avih Yeah, I'd agree it's a documentation issue.

> There is crtime for creation time, but not offered by stat. 

This is also known as ``btime`` as returned by ``statx()`` on Linux, but since that's a new and non-standard function, we'd have to detect support for it if we wanted to use it (and find an alternative for macOS, Unix, etc.) which might not be worth the effort if mpv doesn't need it internally.

**Comment by avih** [comment]
> Do you need any info from me for the documentation change?

No, thanks, I think we got it.

I just hope to get a response from @tsaaristo (who added the scripting file_info) to understand better why it was documented like it is, but I'm fairly positive it's just a misinterpretation of local test results as I noted earlier.

> which might not be worth the effort if mpv doesn't need it internally.

Yup. That's my take on it as well.

**Comment by tsaaristo** [comment]
I've no memory if I had any deeper meaning to that. Likely too much Python on my mind and/or only quickly glancing at the windows paths, misreading or misremembering it when I wrote the documentation. Looks like I did mention that it was untested on Windows in #5223.

Fix away, though IMO exposing the actually-available creation time on Windows sounds pretty valuable, documenting (correctly this time) that it is unavailable on Linux for now (maybe instead offering st_ctime in the *time* being). Shame I missed it in the PR, would've been clean extend mp_stat at the same time.

**Comment by avih** [comment]
> Fix away

Thanks.

> would've been clean extend mp_stat at the same time.

I don't think it's clean or simple. See rossy's reply above.

**Comment by tsaaristo** [comment]
> I don't think it's clean or simple. See rossy's reply above.

It would've been clean to add a field for FILE_BASIC_INFO.CreationTime, expose that, and explain that the creation time is not available on Linux. The unclean part is statx/btime, if you wanted to support linux too.

> not needed by mpv

Scripts can make use of it - getpid is not needed by mpv either, but it is useful for scripts that want to be aware of process ids.
Creation times are very prominent on Windows, and also useful, seeing that @CrendKing is in need of it.

**Comment by avih** [comment]
> Creation times are very prominent on Windows, and also useful, seeing that @CrendKing is in need of it.

We don't know what it's needed for, and it wasn't needed by anyone else which we know of in the past 10 years.

Also, the mpv scripting interface is not a generic wrapper for windows APIs, and you recall the objection to expose even file_info itself back then.

So for now we think it's not worth adding.

**Comment by CrendKing** [comment]
> We don't know what it's needed for,

Just FYI, I maintain a modified version of the autoload.lua that instead of sorting files by alphanumerical order, sort them by file time (creation, modified, etc.), by supplying a custom sorting method [here](https://github.com/mpv-player/mpv/blob/39630dc8b6c2241df9e0e6066e1bd858b864f7de/TOOLS/lua/autoload.lua#L167). I tried using `subprocess` to compare file creation times with something like `cmd /c dir /b /o:d /t:c path1 path2`. It works, but since the method is called in O(n^2) fashion, when there are lots of files, this becomes resource intensive. Of course, alternatively I could traverse the `table` to build a hash map from file to creation time, to reduce complexity to O(n), but parsing `dir` output would be nasty. PowerShell output is much cleaner, but spawning PowerShell process is way slower.

**Comment by TheAMM** [comment]
@CrendKing while I'd prefer creation time in file_info myself as well (though why give scripting people the trivial scripting features they ask for), as a workaround it's probably much more preferable to use Powershell over cmd.exe for Windows shenanigans, if you don't need to support, like, Vista or XP. [Here's console.lua using powershell to grab the clipboard](https://github.com/mpv-player/mpv/blob/master/player/lua/console.lua#L623-L643), as an example.

**Comment by CrendKing** [comment]
Appreciate the help. I'll figure out a solution.
