### ISSUE TITLE
Bold on font does not work

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#8802]
### Important Information

Provide following Information:
- mpv version : 0.33.0-138-g39630dc8b6
- Windows Version : Windows 10 1703
- Source of the mpv binary : https://sourceforge.net/projects/mpv-player-windows/

### Reproduction steps

mpv --no-config --sub-font="Segoe UI" --sub-font-size=48 --sub-bold=yes

### Expected behavior
From build 0.33.0-107-gdd86f195a6, sub looks bold
![mpv-shot0002](https://user-images.githubusercontent.com/15969210/116810904-ed43c980-ab78-11eb-836e-3ccdeec91249.jpg)

### Actual behavior
sub does not look bold
![mpv-shot0001](https://user-images.githubusercontent.com/15969210/116810931-119fa600-ab79-11eb-81e1-5dd343932c20.jpg)

### Log file
0.33.0-138-g39630dc8b6 https://pastebin.com/7dXXkAcX
0.33.0-107-gdd86f195a6 https://pastebin.com/yKdgEMAy

**Comment by Akemi** [comment]
two different libass versions. broken 0.15.1-0-g5447214643eacef71776350e779adf4b6c07bb3b, working: 49f116ab1fa4386f6a5191f322ac29872279516e (older)

the related verbose message that comes from libass
https://github.com/libass/libass/blob/aa4c9bfefb3b2d652aeac342fdf9f33987507f72/libass/ass_fontselect.c#L740-L741

```
49f116ab1fa4386f6a5191f322ac29872279516e
[   0.916][v][sub/ass] fontselect: (Segoe UI, 700, 0) -> SegoeUI-Bold, 0, SegoeUI-Bold

0.15.1-0-g5447214643eacef71776350e779adf4b6c07bb3b
[   0.742][v][sub/ass] fontselect: (Segoe UI, 700, 0) -> SegoeUI, 0, SegoeUI

```

i would say this is a libass problem. picking the normal font even though font weight is set to 700, which is bold.

**Comment by ValZapod** [comment]
Upstream was fixed https://github.com/libass/libass/pull/503

**Comment by ValZapod** [comment]
Does this allow for new release 😝😝? Also some memory leaks there https://github.com/mpv-player/mpv/commit/c3ebe7eabdbd41d496169bdcd98efff9d3f0bf87

And if you were to merge that HDR metadata passthrough patch... 🤔🤔

**Comment by Akemi** [comment]
please keep the off topic out of closed issues.

**Comment by avih** [comment]
For reference, there was also another issue where "bold font doesn't work" in mpv - https://github.com/libass/libass/issues/509  which was figured out as @shinchiro builds having a custom `fonts.conf` which prevented system fonts from being used (probably existed before libass moved to DirectWrite by default - where fontconfig startup was very slow when system fonts were enabled), and which could end up with only some of the variants found.

This was fixed today - https://github.com/shinchiro/mpv-packaging/commit/00d1d9457718e63f467b70687f0a8e4c0660ec6b  and will probably show up in future shinchiro builds.
