### ISSUE TITLE
Frames are being dropped whenever the OSD or Seek bar etc appears

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#8803]
### Important Information

Provide following Information:
- mpv version 0.33 and earlier
- Platform and Version: Windows 10 and various GNU/Linux distros.
- Source of the mpv binary: official

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
watch anything and show OSD.

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Actual behavior
Frames are being dropped whenever the OSD or Seek bar etc appears 

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

http://0x0.st/-atd.log

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
How does one reproduce this? If I just hover over the seekbar a few times or show the stats nothing bad happens.

**Comment by Dudemanguy** [comment]
No follow and vague issue so I'll close for now. Feel free to reopen if there are more details.

**Comment by StacktraceException** [comment]
Sorry, I've been having some other things going on in my life, so never got
back to this, though I have been meaning to..

śr., 19 sty 2022, 03:21 użytkownik Dudemanguy ***@***.***>
napisał:
