### ISSUE TITLE
mp.add_key_binding not working

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#8804]
### Important Information

Provide following Information:
- mpv version 0.33
- Windows Version 10 with latest updates. (not sure if on GNU/Linux too).
- Source of the mpv binary official
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Did so.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
Keybindings work.

### Actual behavior
None of keybindings work from any scripts using this code. The scripts load fine apart from that. This occurs no matter the "workflow", and whether run from terminal.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

http://0x0.st/-awr.log

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by avih** [comment]
What language is that? (lua? javascript?)

Why is the error not at the log?

what does "mp.add_key_binding not working" even mean?

How should one reproduce it? hint - a minimal scripe test case to reproduce the issue would be best - including expected and actual behavior.

Until you provide more info - exactly as requested at the issue template, we can't do anything. Please request to reopen it after you add all the details.

**Comment by StacktraceException** [comment]
> What language is that? (lua? javascript?)
> 
> Why is the error not at the log?
> 
> what does "mp.add_key_binding not working" even mean?
> 
> How should one reproduce it? hint - a minimal script test case to reproduce the issue would be best - including expected and actual behavior.
> 
> Until you provide more info - exactly as requested at the issue template, we can't do anything. Please request to reopen this issue after you add all the details.

this is not in the "template". Lua. The error isnt there because the command you specified in template doesnt update nor produce a newer file, so it shows the one from previous issue. Again template..

It means the keybindings are not working, what the hell?

**Comment by StacktraceException** [comment]
[mpv-no-bindings.log](https://github.com/mpv-player/mpv/files/6412374/mpv-no-bindings.log)

**Comment by avih** [comment]
Your new log still doesn't show any script loaded except the builtin scripts. It definitely doesn't include any script which has issues with key bindings.

1. Show us a minimal script (like 3 lines script or some such) which can be used to reproduce the issue.
2. Tell us which key you press.
3. State exactly what you expect to happen after you press it.
4. State what happens instead in practice.

**Comment by Dudemanguy** [comment]
You're running `--no-config` in these logs which means you aren't loading any other scripts besides the builtin ones.

**Comment by StacktraceException** [comment]
This issue is still closed. No one sees except from us.

**Comment by StacktraceException** [comment]
Yes, I am. Did you include in your template to have multiple logs for running without --no-config?
Would I run this --no-config if not for the template's sake? Of course it didn't work before all of this.

I'll add more details now.

**Comment by avih** [comment]
We see it, and it will remain closed until you provide the details we requested. 4 simple things. Now just do that, and then add a new comment and ask to reopen that.

Untill you do that, you won't get any further response from anyone.

**Comment by StacktraceException** [comment]
1. https://pastebin.com/2KxEeXuU

2. Any of keys in the lua files.

3. Really? .. I expect them to work (for example undo the video seeking..)

4.. oh my god. nothing happens. I get error in terminal such as ": No key binding found for key 'Ctrl-z'."

**Comment by StacktraceException** [comment]
[mpv-no-bindings--without-no-script-option.log](https://github.com/mpv-player/mpv/files/6412411/mpv-no-bindings--without-no-script-option.log)

**Comment by StacktraceException** [comment]
"Please keep it in #8804. Opening random issues does nothing constructive for anyone and only wastes time for all parties. If you open another pointless duplicate/meta issue, you will be blocked from the organization." 

you both should be blocked. anti-human behaviour. I'll try to get you blocked if i have to

**Comment by avih** [comment]
>     1. Show us a minimal script (like 3 lines script or some such) which can be used to reproduce the issue.

>     1. https://pastebin.com/2KxEeXuU

How is a 200 lines script matching the request?

Do this exactly:
1. Save this code at the current directory as file `keytest.lua`:
```lua
mp.add_key_binding("ctrl+z", function()
    print("ctrl+z pressed")
end)
```

2. Run `mpv --no-config --idle --force-window --script=keytest.lua --log-file=keytest.log`
3. press ctrl-z
4. press q

Upload the log file and link it here.
```

**Comment by StacktraceException** [comment]
Ok. I'll do this now.

**Comment by StacktraceException** [comment]
[keytest.log](https://github.com/mpv-player/mpv/files/6412433/keytest.log)
Here it is, it worked. :)

**Comment by avih** [comment]
>  Here it is, it worked. :)

So if this worked then `mp.add_key_binding` works, which means that either there's a bug in your script, or more than one script binds the same key, and only one of them gets the callback - because at any point in time only one key handler is active.

Now you should debug the specific script where it doesn't work.

Tip: use --no-config like in the example to prevent other scripts from loading so that it's easier to debug.

Feel free to ask more questions, but do first make an effort to answer them yourself, using the mpv lua docs or lua-language docs in general.

After you figure out what the issue was, you can post it here so that others could avoid the same mistake.

Good luck.

**Comment by StacktraceException** [comment]
Thanks, Ive already been trying to troubleshoot further after discovering this. :) 
Before posting this issue I have tried as much as I could research and troubleshoot already. So I also removed the input.conf file for testing which didn't help. My mpv.conf had no keybindings and never has. So this remains a mystery to solve, I will keep you updated/ share this for others.

**Comment by avih** [comment]
Thanks.

If this does turn out to be a real issue in mpv, you can post it here with a minimal script to reproduce it, similar in size to the script which you tested and works.

**Comment by StacktraceException** [comment]
So when the UndoRedo.lua is run with the settings you've provided, it actually works! :> Yes, even with the original  `mp.add_key_binding("ctrl+z", "undo", undo)`   code.

(some other script doesn't work, but it has some error ` Lua error: [string ".\portable_config\scripts\sponsorblock.lua"]:94: bad argument #1 to 'join_path' (string expected, got nil)` so maybe that's the cause for it.

I'll test more now

**Comment by StacktraceException** [comment]
ok, so haha it works for UndoRedo.lua without those arguments after I've removed the mpv.conf file. This is strange, I'm going to read through it again.

**Comment by avih** [comment]
Good. Do tell us what it was after you figure it out.

In general, when you report an issue, we can't guess what goes wrong. Look at your original report and realize that no one could solve the issue like that.

So your goal is to help the developers reproduce the issue with minimal interference of other factors - like other scripts, or bad config, etc - hence --no-config is recommended at the template. If a developer doesn't have an absolutely correct, accurate, and minimal way to reproduce the issue then they're in the dark - and much less likely to be able or even want to help.

Try to keep that in mind when you report other bugs - in mpv or elsewhere.

**Comment by StacktraceException** [comment]
Ok, so all of this makes me feel a bit sorry for being a human.. 

I think I've solved this at least mostly. #no-input-default-bindings in mpv.conf was the cause, BUT I was also confused, because for example; 360rotate.lua worked fine, (but it turns out that is uses different code for keybindings), and what's also confusing is that running some other file with the arguments you've provided printed an error in console about some specific code.. and that anyway it works after removing that line from mpv.conf.. 

Ok, I'll look back after finishing installing scripts (and apologize if I was wrong).

**Comment by haasn** [comment]
> (you both should be blocked. anti-human behaviour. I'll try to get you blocked if i have to or make it as public/medial as possible)

That sounds like free advertising for mpv. I approve!

**Comment by avih** [comment]
> I think I've solved this at least mostly. #no-input-default-bindings in mpv.conf was the cause

Thanks for the info.

So this is both interesting, and could actually also be considered an issue in mpv or the documentation. The documentation states "--no-input-default-bindings    Disable mpv default (built-in) key bindings."

But in practice it seems to block also binding added by scripts - and I could also reproduce it by adding `--no-input-default-bindings` to the command line of the example above - this indeed makes the keypress ctrl+z get ignored with a message:
```
[input] No key binding found for key 'Ctrl+z'.
```

Not quite sure what to make of that, to be honest.

**Comment by StacktraceException** [comment]
I meant without the hash sign ( # ). sorry. (I copied it after commentig it out).
Yes, I too never saw this in documentation. Maybe I (or someone else?) can somehow add this to the documentation? :>

(You're welcome, I'm happy to contirbute. I'd like others to benefit so they don't need to spend hours like me heh)

**Comment by avih** [comment]
> Yes, I too never saw this in documentation

It does appear at the documentation - https://mpv.io/manual/master/#options-no-input-default-bindings

The problem is that it doesn't do what the documentation says as far as I undersrand. And for now I'm not yet sure what it should do - but it does make more sense to me that the documentation is correct, but the behavior is wrong.

It's probably worth opening a bug specificcally for the behavior-vs-documentation of this option, and we can figure out there which one should be fixed.

**Comment by StacktraceException** [comment]
What I mean is that this line does appear in documentation but that it  *also disables keybindings for scripts* is what I never saw.

I think more human friendly is to have an option to disable only mpv's builtin bindings. So the  `mp.add_key_binding` works as humans expect, and also it is easier to write than the 360rotate.lua's code which works regardless.

Yes, please you (so that it's formatted the way you fancy) do open a bug for this, (or let me write as a human would..).
