### ISSUE TITLE
mp.add_key_binding not working

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#8805]
### Important Information

Provide following Information:
- mpv version 0.33
- Windows Version 10 with latest updates. (not sure if on GNU/Linux too).
- Source of the mpv binary official
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Did so.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
Keybindings work. 

### Actual behavior
None of keybindings work from any scripts using this code. The scripts load fine apart from that. This occurs no matter the "workflow", and whether run from terminal.

(for mod (ab)user avih: This means that the keybindings from scripts are not applied, they have no effect, but they should have an effect, when they have an effect, everything is good, you can use functions by pressing keys binded with this functionality... It;s like binding a light switch to turn on your brain) 

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[mpv-no-bindings.log](https://github.com/mpv-player/mpv/files/6412381/mpv-no-bindings.log)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
Opening duplicates of the same thing just wastes everyone's time.
