### ISSUE TITLE
user avih keeps closing my issues. Ignores my improvements he requests (which  are absurdly unnecessary too.)

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#8807]
user avih keeps closing my issues. Ignores my improvements he requests which even are absurdly unnecessary by the way

avih: stop being such a problem. Ive improved the issue desciprtion already

**Comment by Dudemanguy** [comment]
Please keep it in #8804. Opening random issues does nothing constructive for anyone and only wastes time for all parties. If you open another pointless duplicate/meta issue, you will be blocked from the organization.
