### ISSUE TITLE
mpv won't play srt:// streams even though it has it in the protocol list

### ISSUE THREAD

**Issue by Lyamc** [mpv-player/mpv#8808]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.33.0-138-g39630dc8b6 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun May  2 11:17:23 +08 2021
FFmpeg library versions:
   libavutil       57.0.100
   libavcodec      59.0.100
   libavformat     59.0.100
   libswscale      6.0.100
   libavfilter     8.0.101
   libswresample   4.0.100
FFmpeg version: git-2021-05-01-c7c138e4
```
- Windows Version
```
Windows 10 Pro 20H2 19042.928
```
- Source of the mpv binary
```
Sourceforge
```
- If known which version of mpv introduced the problem
https://github.com/mpv-player/mpv/pull/8139

- Possible screenshot or video of visual glitches
n/a

### Reproduction steps

1) Verify that srt is a protocol supported
```
mpv --list-protocols
```
2) Try to connect to an srt stream with `mpv srt://<address>:<port>`. A stream can be created with OBS, ffmpeg, or gstreamer.
3) Verify that stream is working with ffplay or vlc

### Expected behavior

mpv connects to the stream

### Actual behavior

```
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open srt://192.168.68.55:6000.
```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/6412504/mpv.log)

**Comment by Akemi** [comment]
the ffmpeg mpv links to needs to be build with libsrt

**Comment by CounterPillow** [comment]
> the ffmpeg mpv links to needs to be build with libsrt

If it weren't then it wouldn't be in `--list-protocols`, from what I understand

**Comment by Lyamc** [comment]
There was an issue here: https://github.com/mpv-player/mpv-build/issues/138
The suggestion was to try `mpv av://` but that doesn't work, or at least, I haven't ben able to make it work.

```
mpv av://srt:192.168.68.56:6000
     Subs  --sid=1 (subrip)
No video or audio streams selected.

Exiting... (Errors when loading file)
```

**Comment by Akemi** [comment]
> If it weren't then it wouldn't be in `--list-protocols`, from what I understand

correct me if i am wrong but it's just an hardcoded lists and not generated out of the ffmpeg features available. see:
https://github.com/erdnaxe/mpv/blob/465204cd664b8d63ebf522d5c40ed56288f6e01e/stream/stream_lavf.c#L410-L420
https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/stream/stream.c#L65-L96
https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/stream/stream.c#L851-L886

**Comment by garoto** [comment]
shinchiro's build setup isn't compiling ffmpeg with `libsrt` support: https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/ffmpeg.cmake.

**Comment by tvadi** [comment]
Hi, old topic but I am having problems with this too.  
With MPV player, just trying to play an SRT stream from OBS on the same Linux box (Ubuntu 20.04),  SRT in MPV does work in Windows.. On the same machine I can open srt://127.0.0.1:10000 successfully in VLC..

From apt install mpv, getting:

`No protocol handler found to open URL srt://127.0.0.1:10000 The protocol is either unsupported, or was disabled at compile-time.`

From git master compile, getting:
`[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support. Failed to open srt://127.0.0.1:10000.`
