### ISSUE TITLE
--no-input-default-bindings: docs different than behavior

### ISSUE THREAD

**Issue by avih** [mpv-player/mpv#8809]
mpv version: master - 0.33.0-139-gb6aedaa726
Platform and Version: Windows 10
Source of the mpv binary: Own build

### Steps to reproduce

1. Save the following code as `keytest.lua`:
```lua
print("keytest started")

mp.add_key_binding("x", function()
    print("x pressed")
end)
```
2. Run: `mpv --no-config --no-input-default-bindings --idle --force-window --script=keytest.lua`
3. Press `x`

### Expected behavior

Printed at the console: `keytest started` followed by `x pressed`.

### Actual behavior

The printout at the console is:
```
[keytest] keytest started
[input] No key binding found for key 'x'.
```

If removing the `--no-input-default-bindings` option, then it does print `x pressed`.

### Log file

https://0x0.st/-aYf.txt

Thanks to @StacktraceException for identifying it at https://github.com/mpv-player/mpv/issues/8804#issuecomment-830942213

According to the docs, `--no-input-default-bindings` should "Disable mpv default (built-in) key bindings." and it doesn't say anything about bindings added via scripts at runtime.

It's unclear yet what the intent was - seems it could be useful for applications which use libmpv.

If the intent was indeed to disable key bindings added via scripts, then we should fix the docs, else we might need to consider fixing the behavior to match the docs - so that the default bindings are disabled, but binding added at runtime via scripts would still work.

We need to decide which of those we want to pursue.

@stax76 do you have an opinion on this? I know you use libmpv, do you let mpv use the default bindings?

EDIT: interestingly, adding as the first line of the test script:
```lua
mp.commandv("keybind", "y", 'show-text "y pressed"')
```
Does bind the y key, and the text `y pressed` does show at the OSD when pressing y (while pressing x still prints `No key binding found for key 'x'.`).

**Comment by Akemi** [comment]
i don't think this is an intended behaviour and the docs are right. `--no-input-default-bindings` should only disable the built-in/baked-in shortcuts, but should never disable keybindings from external scripts. arguably it could disable the keybindings from the build-in scripts if they use `add_key_binding`, which could have been the original intended behaviour.

for libmpv users this seems also unintended. if one wants to disable all default keybindings but still wants to add features via scripts, that would not work.

**Comment by avih** [comment]
> for libmpv users this seems also unintended. if one wants to disable all default keybindings but still wants to add features via scripts, that would not work.

Agreed, however, I did not test usage via libmpv, and I don't know if the behavior is the same as in mpv itself. That's also why I asked stax76.

For reference, `--no-input-default-keybindings` seems to disable these bindings:
- Builtin bindings (like space for pause).
- Bindings added via the scripting API `mp.add_key_bindings`.

`--no-input-default-keybindings` seems to have no effect on (i.e. the bindings work):
- Key bindings added via `input.conf` (probably cascaded with other input config files if applicable).
- The mpv command `keybind`.
- The scripting API `mp.add_forced_key_binding`.

So from all these bindings, it seems that only `mp.add_key_bindings` doesn't behave as expected with `--no-input-default-keybindings` .

Internally (both lua and js), `mp.add_key_bindings` and `mp.add_forced_key_binding` use the mpv command `define-section`, where the former uses the mpv command flag `default`, and the latter uses the flag `forced`.

The difference between the flags according to the command docs is that `default` doesn't override bindings at `input.conf`, while `forced` does override `input.conf` bindings.

The miscommunication seems to happen between the `define-section` command handler and the function which it calls internally `mp_input_define_section`: https://github.com/mpv-player/mpv/blob/b6aedaa7262781bdc763cf2886d27c37659f7729/player/command.c#L5556-L5563

Where the command handler wants to speak in terms of "do/don't override input.conf" (`!cmd->args[2].v.i` where `args[2]` is the flag, false is `default`, and true is `forced`), but the callee `mp_input_define_section` interprets the second-to-last argument as "is builtin": https://github.com/mpv-player/mpv/blob/b6aedaa7262781bdc763cf2886d27c37659f7729/input/input.c#L1106-L1107

The intent originally was probably that it's classified as builtin to allow `input.conf` override it, but the fact that it gets ignored by `--no-input-default-keybindings` is probably an unintentional side effect of this classification as builtin.

The mpv command `keybind` is unaffected by this, because it uses the internal function `mp_input_bind_key`, which explicitly marks the binding as not-builtin (line 1475): https://github.com/mpv-player/mpv/blob/b6aedaa7262781bdc763cf2886d27c37659f7729/input/input.c#L1471-L1477

The solution is not obvious, and probably either complex or impossible without breaking backward compatibility of the `define-section` command.

I think the best course of action would be to document the current behavior at `--no-input-default-keybindings`.

Original:
```
Disable mpv default (built-in) key bindings.
```

New:
```
Disable mpv default (built-in) key bindings, and bindings added with
the `define-section` command with the flag `default` - which includes
the scripting API `mp.add_key_binding`.

This has no effect on bindings added via `input.conf`, or binding added
via the mpv command `keybind`, or bindings added with the scripting
API `mp.add_forced_key_binding`.
```

Thoughts?

**Comment by avih** [comment]
In other words, the core issue seems to be that internally mpv has two classifications of bindings:
- Lower priority than `input.conf` - which is classified as "builtin" (and affected by the `--no-input-default-binding` option).
- Same priority as `input.conf` where the precedence is determined according to who specified the binding last (`input.conf` is loaded first, the `keybind` command and `define-section` with flag `forced` are applied later and override prior bindings).

And the binding system is already very complex with multiple layers and priorities, and includes for instance binding over specific regions of the window (that's what the OSC uses), etc.

So I don't think it would be easy to change it from a flag of "is builtin" to something with higher resolution, and that's the reason I think just documenting the current behavior is the best course of action for now.

**Comment by avih** [comment]
> New:
> 
> ```
> Disable mpv default (built-in) key bindings, and bindings added with
> the `define-section` command with the flag `default` - which includes
> the scripting API `mp.add_key_binding`.
> 
> This has no effect on bindings added via `input.conf`, or binding added
> via the mpv command `keybind`, or bindings added with the scripting
> API `mp.add_forced_key_binding`.
> ```

Alternatively, we could document it more closely to how mpv handles it internally, maybe like so:
```
Disable key bindings with lower priority than `input.conf`, which includes:
- Built-in (default) mpv bindings.
- The scripting API `mp.add_key_binding`.
- The command `define-section` with flag `default`.

Unaffected: the command `keybind`, the command `define-section` with
flag `forced`, and the scripting API `mp.add_key_forced_binding`.
```

**Comment by occivink** [comment]
I like being able to disable default bindings from scripts so that I can remap them as I see fit. If this is removed from `no-input-default-binding`, it would be good to introduce a new option to do that.

**Comment by avih** [comment]
> I like being able to disable default bindings from scripts so that I can remap them as I see fit

Can you give an explicit example of what you mean?

Also, note that so far I think the best approach is not to change the behavior, but rather document it more accurately.

**Comment by occivink** [comment]
I mean that most scripts come with default bindings that act as 'entry point'. That's good, it makes it easier to try out a script.
However, as a config gets more complex you run into binding conflicts, so it's good to be able to disable these default bindings and set everything up into a single `input.conf`

**Comment by avih** [comment]
Sorry, I still don't quite understand.

Can you describe it in terms of e.g. "The user has [something specific] at input.conf, a script uses mp.add_keybinding(.. [something specific]), then the user can use --disable-input-key-binding in order for [somethig specific] to happen, but this will not work anymore if you change the behavior", or some such.

I.e. a 100% concrete example of setup and minimal script where the current behavior of the option has value, but will have less value if we change the behavior.

**Comment by occivink** [comment]
Let's put it another way. I like that with this option, _only_ the bindings defined in my `input.conf` matter, making it a single source of truth (please don't bring up forced bindings).

**Comment by avih** [comment]
> I like that with this option, _only_ the bindings defined in my `input.conf` matter, making it a single source of truth

Right, thanks. I can understand this.

But even without this option your `input.conf` still overrides any key which a script adds (without forced), so in fact the only "unwanted" keys are those which scripts add as non-forced, AND which you didn't specify at input.conf.

And you want to disable even those, right?

**Comment by StacktraceException** [comment]
@avih I think @occivink wants to disable mpv's default builtin keybindings so he can have his own keybindings setup for everything inluding external scripts. (I'm guessing also that he also wants to have them all rewritten in one input.conf file to be more logically consistent altogether).

**Comment by stax76** [comment]
@avih 

mpv.net by default adds `input-default-bindings = no` to mpv.conf.

> --no-input-default-bindings should only disable the built-in/baked-in shortcuts, but should never disable keybindings from external scripts.

I agree.

**Comment by hooke007** [comment]
Hmm......It seems that "To add the another option to disble the scripts' defalut shortcuts & make the `input-default-bindings=no` just disable mpv default (built-in) key bindings" would be the better choice to satisfy two demands.

**Comment by avih** [comment]
> @avih
> 
> mpv.net by default adds `input-default-bindings = no` to mpv.conf.
> 
> > --no-input-default-bindings should only disable the built-in/baked-in shortcuts, but should never disable keybindings from external scripts.
> 
> I agree.

Does that mean that by default `mp.add_key_binding` in scripts just doesn't work with mpvnet?

That's what it means with mpv, but I don't know if this also happens with libmpv.

**Comment by avih** [comment]
For now I only updated the documentation to reflect more accurately what gets disabled by this option.

I don't disagree that excluding `mp.add_key_binding` for this option could be useful for libmpv clients (_maybe_ also with a way to preserve the current behavior).

However, changing the behavior is sensitive due to the complexity of the bindings infrastructure - which was designed to handle only two "classes" of bindings: builtin-bindings and user-bindings, and currently `mp.add_key_binding` is classified as builtin - to allow `input.conf` to verride it.

So in the future we might still make this separation between "real builtin" and "soft builtin" (PRs are welcome), but for now we just document the current behavior more accurately.

**Comment by stax76** [comment]
> Does that mean that by default mp.add_key_binding in scripts just doesn't work with mpvnet?
> 
> That's what it means with mpv, but I don't know if this also happens with libmpv.

I just tried, the behavior of libmpv is the same as mpv, `input-default-bindings=no` disables keys added with `mp.add_key_binding`.
