### ISSUE TITLE
To play next video

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8810]
Hi, is it possible some Lua programmer here modify this brief script in order the videos on the playlist don't play automatically?
Sometimes we prefer to press a key 'next video' for to play next video.

https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

**Comment by garoto** [comment]
setting `keep-open` to `always` will stop the player from auto-advancing into the next file. You can set a keybind to toggle the option behavior and invoke only when necessary.

**Comment by jimmy-1000** [comment]
> 
> 
> setting `keep-open` to `always` will stop the player from auto-advancing to the next file in a playlist. You can set a keybind to toggle the option behavior and activate only when necessary.

Thanks a lot!
