### ISSUE TITLE
None of deinterlacing options seem to ever work.

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#8811]
### Important Information

Provide following Information:
- mpv version 0.33 and earlier
- Platform and Version GNU/Linux and Windows
- Source of the mpv binary official

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Watch any interlaced video

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Did so.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

(I also tried watching without hardware acceleration and various other "workflows" )

### Expected behavior
Videos don't have any visible interlacing.
### Actual behavior
Whatever settings and filters are chosen (even --vf=nnedi=weights=nnedi3_weights.bin:pscrn=none [which is acually not as slow as they say, when you enable --hwdec-codecs=all it speeds up by orders of magnitude!]), there is no obvious difference. 
### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[interlace.log](https://github.com/mpv-player/mpv/files/6417109/interlace.log)

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment]
Start with something simpler like `--deinterlace` **and** `--no-config` instead of the bunch of options you have right now, that should certainly work.

**Comment by StacktraceException** [comment]
No, I would not write here if it was so simple. I tried several things, searched for hours.

**Comment by StacktraceException** [comment]
What else are your ideas?

**Comment by sfan5** [comment]
That youtube video from your log doesn't work as an example. It has been telecined, enabling the deinterlacer on it will not work.

**Comment by StacktraceException** [comment]
Oh, so like I expected , it may be something with the video, or that it is not possible for this file for some reason.
Could you please elaborate more?

**Comment by StacktraceException** [comment]
I also tried --vf=detelecine previously and it too had no obvious effect.

**Comment by StacktraceException** [comment]
`mpv https://www.youtube.com/watch?v=LtrrGlqBbn4 --vf=d3d11vpp:mode=ivctc`

autoconvert: HW-uploading to d3d11
autoconvert: can't find video conversion for yuv420p
        vf: Disabling filter d3d11vpp.00 because it has failed.
        
   I'm just guessing/troubleshooting now)

**Comment by hooke007** [comment]
The fact is the nnedi3 was working. It is obvious if you watch closely.
You'd better use `hwdec=no` or `auto-copy` if you wish many of the video filters will work.

![no](https://user-images.githubusercontent.com/41094733/116928224-5c134680-ac8f-11eb-8923-000470e2f251.jpg)
![yes](https://user-images.githubusercontent.com/41094733/116928229-5ddd0a00-ac8f-11eb-812c-3be8a83f0f48.jpg)

**Comment by StacktraceException** [comment]
Ok, so it does work, but not obviously enough. Almost the next frame:

![image](https://user-images.githubusercontent.com/61169664/116933173-79cab680-ac63-11eb-8e4f-c9a450a61540.png)

**Comment by StacktraceException** [comment]
Ok, so even with reportedly the best filters for this, it all looks ugly often like here:

![image](https://user-images.githubusercontent.com/61169664/116933959-93203280-ac64-11eb-9464-c7dd35d44f7a.png)

**Comment by hooke007** [comment]
Apparently, the original video has been incorrectly transcoded many times. I agree that it cannot be as the typical interlaced video sample.

**Comment by StacktraceException** [comment]
Sorry, what do you mean? Is this unfuxable?

**Comment by Doofussy2** [comment]
He's telling you that whomever digitized the video, didn't deinterlace it, and the comb artifacting has been encode into the video. It's a shit video, and there's nothing you can do to fix it. If you look at the video's details, it's progressing and not interlaced.

**Comment by ValZapod** [comment]
Youtube does not support interlaced. See this correclty deinterlcased video that should at the very least be 50 fps but also correct chroma swscale parameters should be used:
https://youtu.be/YVbrF-8k65Y

**Comment by Akemi** [comment]
the initial issues has been resolved, the deinterlace work.
