### ISSUE TITLE
Deleting mpv on github website?

### ISSUE THREAD

**Issue by StacktraceException** [mpv-player/mpv#8813]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

Template not needed here.

What is the purpose of having the delete entire directory button here? :
https://github.com/mpv-player/mpv/tree/master/TOOLS/lua   

It seems strange to me, that it seems I can delete all those files

**Comment by CounterPillow** [comment]
We do not control the github web UI. If you hit that delete button, you do not actually delete anything from the mpv-player/mpv repository; you fork the repository to your own account, create a deletion commit, and possibly send it as a pull request to this repository which would first have to be approved.

The mpv issue tracker is not the place to ask questions about GitHub's user interface.

**Comment by jeeb** [comment]
Yup, it will just ask you create a commit somewhere that you have access to if you click that button.

**Comment by StacktraceException** [comment]
> We do not control the github web UI. If you hit that delete button, you do not actually delete anything from the mpv-player/mpv repository; you fork the repository to your own account, create a deletion commit, and possibly send it as a pull request to this repository which would first have to be approved.
> 
> The mpv issue tracker is not the place to ask questions about GitHub's user interface.

Well, it is an mpv issue, as mpv is hosted on github.
