### ISSUE TITLE
~/.config/mpv is ignored in when XDG_CONFIG_HOME is different (flatpak sanbox)

### ISSUE THREAD

**Issue by fastrizwaan** [mpv-player/mpv#8816]
Problem: Flatpak uses  `~/.var/app/io.mpv.Mpv/config`  `XDG_CONFIG_HOME`, and  mpv won't read `~/.config/mpv/` config directory.

Please install and test: https://flathub.org/apps/details/io.mpv.Mpv

This is causing issue with mpv-mpris plugin included in flatpak sandbox's XDG_CONFIG_HOME and `~/.config/mpv/mpv.conf` and `~/.config/mpv/input.conf`

How to resolve multiple config directories?

here's the output excerpt  of `flatpak run -vvv --command=bash io.mpv.Mpv`
```
 --setenv _ /usr/bin/flatpak --setenv XDG_CONFIG_DIRS /app/etc/xdg:/etc/xdg --setenv ALSA_CONFIG_PATH /usr/share/alsa/alsa-flatpak.conf --setenv GI_TYPELIB_PATH /app/lib/girepository-1.0 --setenv GST_PLUGIN_SYSTEM_PATH /app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0 --setenv ALSA_CONFIG_DIR /usr/share/alsa --setenv LC_NUMERIC C --setenv FLATPAK_ID io.mpv.Mpv --setenv PS1 '[📦 $FLATPAK_ID \W]\$ ' --setenv FLATPAK_SANDBOX_DIR /home/rizvan/.var/app/io.mpv.Mpv/sandbox --setenv XDG_DATA_HOME /home/rizvan/.var/app/io.mpv.Mpv/data --setenv XDG_CONFIG_HOME /home/rizvan/.var/app/io.mpv.Mpv/config --setenv XDG_CACHE_HOME /home/rizvan/.var/app/io.mpv.Mpv/cache --setenv PULSE_SERVER unix:/run/user/1000/pulse/native --setenv PULSE_CLIENTCONFIG /run/user/1000/pulse/config --setenv AT_SPI_BUS_ADDRESS unix:path=/run/user/1000/at-spi-bus
F: Running 'bwrap --args 41 bash'
[📦 io.mpv.Mpv ~]$ exit


```

If we want to use `~/.config/mpv` then we have to `unset XDG_CONFIG_HOME` then we can't use installed plugin at  `~/.var/app/io.mpv.Mpv/config`

**Comment by xscd** [comment]
I think the true way for flatpak apps is to use ~/.var/app/io.mpv.Mpv/config for mpv.conf and input.conf files (also scripts)

**Comment by CounterPillow** [comment]
I'm pretty sure that in a flatpak setup, mpv is not supposed to access `~/.config/mpv` as this directory is explicitly designed to be relative to `XDG_CONFIG_HOME` and not a fixed path.

**Comment by fastrizwaan** [comment]
OK, then let's use flatpak's config directory.
