### ISSUE TITLE
can't set ao-volume-max to 150%

### ISSUE THREAD

**Issue by picarica** [mpv-player/mpv#8819]
### Important Information

Provide following Information:
- mpv version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.4-1ubuntu0.1
- Platform and Version
- Linux Mint 20.1
- Source of the mpv binary
- official repository

### Reproduction steps

after setting keybinds to use ao-volume instead of volume volume-max isnt applied, in my cfg i have 
```
volume=150
ao=wasapi
audio-exclusive=yes
audio-channels=stereo
volume-max=150

```
but my max volume of ao is still 100%
i tried adding ao-volume instead of volume but i get 

```
Error parsing option ao-volume (option not found)
/home/picarica/.mpv/config:68: setting option ao-volume='150' failed.
Error parsing option ao-volume-max (option not found)
/home/picarica/.mpv/config:72: setting option ao-volume-max='150' failed.

```

### Expected behavior

want 150% ao

### Actual behavior

no 150% ao

**Comment by zsoltiv** [comment]
You seem to be using wasapi for audio output, but isn't that for Windows only? Maybe try PulseAudio or ALSA?

**Comment by Akemi** [comment]
`ao-volume-max` does not exists. `ao=wasapi` is not available on linux. please do as the issue templates asked you to do, try with `--no-config` and post a log of the problem.

**Comment by picarica** [comment]
> my guess, since you are using an ao that is not available on linux it fails to initialise any ao and because of that can't set ao-volume. see code here
> 
> https://github.com/mpv-player/mpv/blob/dd4d239bcb151b08eb81b38486515a3e1222e1f5/player/command.c#L1602-L1604

i cant easily set ao volume that isnt a problem i cant add it mute it eveyrthing the problem is i cannot set it to be max 150%, i tried even setting it to ao=pulseaudio but problem persist
