### ISSUE TITLE
dvdnav related meta-bug

### ISSUE THREAD

**Issue by tholin** [mpv-player/mpv#882]
I was encouraged to use dvdnav:// instead of dvdread:// so here is a list of all the problems I have with it. Most of them are probably known already but it's good to have them documented anyway.

When seeking forward I often get corrupted frames. The corruption will remain on screen for 10 sec when seeking 10 sec and 1 min when seeking 1 min. The statusline also shows an a-v desync of the seek amount. After the frame gets fixed the a-v desync remains. It was suggested that the corruptions are caused by bugs in libdvdnav. I tried to seek around in vlc but didn't see any corruptions or other problems. This might be because vlc doesn't seek the same way. It use dvdnav_sector_search instead of dvdnav_time_search, and dvdnav_get_position instead of dvdnav_get_current_time, and dvdnav_get_next_cache_block instead of dvdnav_get_next_block.

Seeking backwards will always cut off sound. The statusline shows an a-v desync of the seek amount. The video still plays and as it progress the desync will decrease. When it reaches 0 the sound comes back and the a-v desync jumps again to negative the seek amount (that's the correct amount of desync at this point).

Seeking past a cell boundary cause a large a-v desync of several minutes and sound cuts off. This is usually followed by messages like `Non-monotonic video pts: 0.247267 <= 602.097978" messages`

Seeking to the next chapter will AltGr+2 will sometimes jump past the next chapter and stop at the one after that. The OSD sometimes doesn't update with the correct position after a seek and instead shows a playtime of 0. It will be correct the next time it redraws itself.

Trying to seek before the start or past the end will fail with `libdvdnav: Error when seeking.` This means it's impossible to seek back to the start by seeking back 15 min when the playtime is less than 15 min.

Most of these bugs also exists in dvdread:// but I prefer it anyway because I can play all disc content with dvdread://1-99. If dvdnav had something like that I would use it instead.

**Comment by wm4** [comment]
Needs a developer who actually cares about DVD playback.
