### ISSUE TITLE
Move mpv controls (e.g. play, progress bar, title) from bottom of player to top?

### ISSUE THREAD

**Issue by chausies** [mpv-player/mpv#8827]
I use my mouse scroll-wheel a lot in mpv (to adjust speed and volume), but moving the mouse will sometimes cause the controls to pop up from the bottom and cover the subtitles all the time.

![image](https://user-images.githubusercontent.com/2512400/118071920-98b10300-b35d-11eb-915b-4a2e027ff9d9.png)

Is there a way to move all those controls to the top of the player, so that they don't cover the subtitles when they pop out?

Preferably, there'd be something I could add to my portable_config's to make this happen.

**Comment by hooke007** [comment]
...\portable_config\script-opts\osc.conf
```
layout=topbar
```

**Comment by chausies** [comment]
Sorry, one more thing in addition. Currently, pop-up text (e.g "Speed: 2.00", "Volume: 110%") is in the top-left by default. But now that I've moved the controller to the top, the controller covers that pop-up text.

How can I move the pop-up text's position? (preferably to the bottom-left)

**Comment by avih** [comment]
> How can I move the pop-up text's position?

I don't think you can.

**Comment by hooke007** [comment]
Hmm...If you are not very busy, you will find the answer in the manual.
https://mpv.io/manual/master/#options-osd-align-y
