### ISSUE TITLE
When I accelerate the video playback speed to 4.18 times, the video has no sound.

### ISSUE THREAD

**Issue by AO2233** [mpv-player/mpv#8828]
I upgrade my mpv to 0.33.0-138-g39630dc8b6 (download from https://sourceforge.net/projects/mpv-player-windows/files/64bit/).
    But I find that when I accelerate the video playback speed to 4.18 times, the video has no sound. 
    And if I slow down the speed, the sound reappeared. 
    In the old version, I haven't met this, even speed up over 8 times, the sound is exist. 
    Is this a new feature? I feel the sound quality is better then before. And how to set mpv.conf to make the sound exist in high speed playing ? 
```
$ mpv
mpv 0.33.0-138-g39630dc8b6 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun May  2 11:17:23 +08 2021
FFmpeg library versions:
   libavutil       57.0.100
   libavcodec      59.0.100
   libavformat     59.0.100
   libswscale      6.0.100
   libavfilter     8.0.101
   libswresample   4.0.100
FFmpeg version: git-2021-05-01-c7c138e4
```

**Comment by avih** [comment]
By default the `scaletempo2` disables itself beyond speec of 4.

There are two things you can do:
1. Use the old `scaletempo` filter: `--af=scaletempo`
2. Or configure the new `scaletempo2` filter to allow higher speed: `--af=scaletempo2=max-speed=16`

**Comment by AO2233** [comment]
Thanks🍺🍺🍺!

**Comment by logiclrd** [comment]
I'm curious to know, why does scaletempo2 impose an upper limit of 4 by default?

**Comment by guidocella** [comment]
> I'm curious to know, why does scaletempo2 impose an upper limit of 4 by default?

It was just copied from chromium's implementation where they later removed it. We kept the limit, though increasing the default to 8, because audio makes the frame rate tank at high speeds with `--video-sync=display-resample`, though this happens with any pitch correction filter and may be fixable.
