### ISSUE TITLE
How to make msys2's mpv building support d3d11?

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8832]
I tried to Natively build the mpv for win10 but I cannot make it support d3d11 output.
I just follow the official doc: [#native-compilation-with-msys2](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2)
When I input the `/usr/bin/python3 waf configure CC=gcc.exe --check-c-compiler=gcc --prefix=$MSYSTEM_PREFIX` and found that `d3d11 output shaderc not found`.

![Snipaste_2021-05-16_20-13-05](https://user-images.githubusercontent.com/41094733/118396913-42590280-b684-11eb-8715-2d2afa3a2e1d.jpg)

### Log file
[msys2.log](https://github.com/mpv-player/mpv/files/6489187/msys2.log)

**Comment by sfan5** [comment]
Like that line says you need both shaderc and spirv-cross to enable d3d11.

**Comment by rossy** [comment]
Yeah, MSYS2 has those packages. You should just have to install the following:

```
pacman -S $MINGW_PACKAGE_PREFIX-{spirv-cross,shaderc}
```

**Comment by hooke007** [comment]
Thanks, that is the answer to my question.
