### ISSUE TITLE
OLD TO NEW SEND COMMAND

### ISSUE THREAD

**Issue by subh-kundu** [mpv-player/mpv#8833]
![Untitled](https://user-images.githubusercontent.com/64629942/118402281-d9bf5500-b686-11eb-94f1-1c7c8a34efc9.png)

OLD Version this command is work
ps.StartInfo.Arguments = " --no-quiet --input-terminal=yes --terminal=yes --no-msg-color --input-file=/dev/stdin --vo=direct3d --input-x11-keyboard=no --input-cursor=no --no-keepaspect --monitorpixelaspect=1 --osd-scale=1 --osd-level=2 --osd-border-color=#fff00000 --osd-blur=5.000 --ytdl=no " + " \"" + Fullpath.Text + "\"";

//Play pause command
ps.StandardInput.WriteLine("pause");

How can i apply New version ? please help me out

**Comment by CounterPillow** [comment]
Use `--input-ipc-client`, `--input-file` has been removed.

Also please reconsider whether you really want to use the direct3d VO.

**Comment by subh-kundu** [comment]
> mpv 0.33.0-150-gea89e813f7 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
>  built on Sun May  9 13:16:59 +08 2021
> FFmpeg library versions:
>    libavutil       57.0.100
>    libavcodec      59.0.100
>    libavformat     59.0.101
>    libswscale      6.0.100
>    libavfilter     8.0.101
>    libswresample   4.0.100
> FFmpeg version: git-2021-05-08-b4e7fc4b

thanks your response but not working `--input-ipc-client`

I use this command 
`ps.StartInfo.Arguments = " --no-quiet --input-terminal=yes --terminal=yes --no-msg-color --input-ipc-server=\\.\\pipe\tmp\\mpv-socket --vo=direct3d --input-x11-keyboard=no --input-cursor=no --no-keepaspect --monitorpixelaspect=1 --osd-scale=1 --osd-level=2 --osd-border-color=#fff00000 --osd-blur=5.000 --ytdl=no " + " \"" + Fullpath.Text + "\"";`

but not send command to pause, stop or any type of

**Comment by CounterPillow** [comment]
You're now listening on `\\.\\pipe\tmp\\mpv-socket` and no longer stdin. That being said, /dev/stdin is not a thing on windows, and it also wouldn't do anything here because mpv listens to key events by default, so just remove both input-ipc-server and input-file

**Comment by subh-kundu** [comment]
sorry I can't use any more without `--input-ipc-server=\\.\\pipe\tmp\\mpv-socket` this line
not run mpv window.
 please sir can you write for me the full command

**Comment by CounterPillow** [comment]
no because I do not know what you are trying to do

**Comment by subh-kundu** [comment]
okay I want to make a player with mpv C# windows form application
I already found a player TRadioPlayer-master but it was old version use mpv.exe
now I want to use new mpv player with video window on pannel controls by the way I do not
use mpv.net

**Comment by subh-kundu** [comment]
```
private void mpVlayerLoad()
        {
            ps = new Process();
            ps.StartInfo.ErrorDialog = false;
            ps.StartInfo.UseShellExecute = false;
            ps.StartInfo.RedirectStandardInput = true;
            ps.StartInfo.RedirectStandardOutput = true;          
            ps.StartInfo.FileName = System.IO.Directory.GetCurrentDirectory() + "\\mpv-x86_64-0.33.0.6\\mpv.exe"; 
        }

public Form1()
        {
            InitializeComponent();
            mpVlayerLoad();
        }

public void mpvlay()
        {
            try
            {
                volumes = " --volume=50";
                colours = " --contrast=0 --brightness=0 --hue=0 --saturation=-100 --gamma=0";
                equalizers = " --af-add=@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,12);entry(125,12);entry(250,12);entry(500,-12);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)']";
               
                var windowId = Mpvpanel1.Handle.ToInt64();

                //OLD
                //ps.StartInfo.Arguments = " --no-quiet --input-terminal=yes --terminal=yes --no-msg-color --input-file=/dev/stdin --vo=direct3d --input-x11-keyboard=no --input-cursor=no --no-keepaspect --monitorpixelaspect=1 --osd-scale=1 --osd-level=2 --osd-border-color=#fff00000 --osd-blur=5.000 --ytdl=no " + " \"" + Fullpath.Text + "\"";

                //NEW
                ps.StartInfo.Arguments = " --no-quiet --input-terminal=yes --terminal=yes --no-msg-color --input-ipc-server=\\.\\pipe\tmp\\mpv-socket --vo=direct3d --input-x11-keyboard=no --input-cursor=no --no-keepaspect --monitorpixelaspect=1 --osd-scale=1 --osd-level=2 --osd-border-color=#fff00000 --osd-blur=5.000 --ytdl=no " + " \"" + Fullpath.Text + "\"";            
                ps.Start();
            }
            catch (Exception)
            {
            }

 private void Button1_Click(object sender, EventArgs e)
        {
            mpvlay();
        }
private void Button2_Click(object sender, EventArgs e)
        {
            ps.StandardInput.WriteLine("pause");            
        }
```
When apply OLD Arguments works perfectly and send paly/pause command then 
apply NEW Arguments play the  video and preview the window but not send the play pause command.
I hope now understand my problem sorry for my bad english

**Comment by Akemi** [comment]
how to send a command to via ipc is explained here https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst

**Comment by subh-kundu** [comment]
> how to send a command to via ipc is explained here https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst

yah, I already check it, I don't understand please tell me more. thanks

**Comment by Akemi** [comment]
all text only commands can be found here https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst

```
echo 'cycle pause' | socat - /tmp/mpvsocket
```

there is nothing more to tell. if you don't understand i can't help you.

**Comment by subh-kundu** [comment]
Hi, yes but how to send this command 
ps.StandardInput.WriteLine("  ");
I'm confused

**Comment by subh-kundu** [comment]
[mympv.zip](https://github.com/mpv-player/mpv/files/6491433/mympv.zip)

**Comment by Akemi** [comment]
we are not a programming support. you should know yourself if you write code in that language. i would guess, it's missing the terminating `\n`, but you don't even give an example. you also ignored the issue template, you didn't provide a log. please don't expect us to help you like that at all.

```
ps.StandardInput.WriteLine("cycle pause\n");
```

**Comment by subh-kundu** [comment]
hmm... sir I try already, I don't understand where I mistaken the code
[mympv.zip](https://github.com/mpv-player/mpv/files/6491486/mympv.zip)

**Comment by Akemi** [comment]
i will repeat myself the last time and CounterPillow already said it too. you have to write to the socket and not the stdin of mpv. the socket is whatever you pass to `--input-ipc-server=`. if you don't know how to do that, please ask in an appropriate forum but the mpv issue tracker isn't the right place for this.

also don't posts walls of commented code, but instead and at least post a minimal example if you expect help.

closing this.
