### ISSUE TITLE
mpv back one frame not work properly on .mpg files

### ISSUE THREAD

**Issue by hikikomori4** [mpv-player/mpv#8834]
- mpv version mpv 0.33.1-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
- Linux Distribution and Version  4.19.189-1-MANJARO KDE  x86_64 GNU/Linux 

During play video in .mpg format not work properly rewind one back frame.  
rewind forward frame by frame work ok. 
Issue only on .mpg. 
Files. avi, mkv - rewinds ok.
The problem appeared after a recent update, I did not notice it before.

**Comment by CounterPillow** [comment]
no log, no fix.

**Comment by Akemi** [comment]
please open a new issue and provide all the info we ask for.

**Comment by hikikomori4** [comment]
**CounterPillow**, I don't know where the mpv log is in Manjaro.
`try holding down the frame back step key. `
- i tried, no effect. 

`Akemi Akemi added the priority:ignored-issue-template label `

Dear friend, I don't know how to fill in the whole template. Therefore, I wrote it as it is. 

`please open a new issue and provide all the info we ask for.`

I'm afraid I don't know how to fill in most of the fields. If you tell me how, I will be grateful.

**Comment by Akemi** [comment]
the issue template tells you how to make a log file for example. please read the template careful and try again.
