### ISSUE TITLE
[LUA] os.rename() and os.remove() lua functions don't work with unicode path.

### ISSUE THREAD

**Issue by chrixxxx** [mpv-player/mpv#8835]
### Important Information

Provide following Information:
- mpv = 20210509-git-ea89e81
- Windows Version: 10
- Source of the mpv binary = https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20210515-git-ded36a4.7z/download

### Reproduction steps

when called from a lua script, those 2 lua functions don't work at all if unicode characters are present in either the path or the filename

Example:

os.remove("C:/なく頃に/filename_Привет.tmp")

Don't know if it's possibile to patch them like it has been done with io.open() here : https://github.com/mpv-player/mpv/issues/7704

**Comment by sfan5** [comment]
This should automatically work since bb231889fdd2ee0f519bdb1c756b61ceefd5584b.
We will not be adding any workarounds or hacks to make this work otherwise.
