### ISSUE TITLE
HTTP/3

### ISSUE THREAD

**Issue by joeky888** [mpv-player/mpv#8836]
Hello there.
Apologies for this question might be irrelevant to `mpv`, but how do you enable experimental HTTP3 with mpv? I could enable QUIC settings in browsers, is there an option for `mpv`/`youtube-dl` too?

**Comment by CounterPillow** [comment]
You'll have to ask FFMpeg and Python, mpv does not contain any HTTP implementation. FFmpeg probably has no HTTP3 implementation, and neither does Python. So the short answer is: you can't.

**Comment by haasn** [comment]
(I also don't expect it to be any better than HTTP/1)

**Comment by KebabLord** [comment]
I didn't try this but you can try the following:
### ffmpeg 
- Manually compile / build libCurl to use http/3 by either using ngtcp2 + nghttp3 (--with-nghttp3) or quiche (--with-quiche)
- Then manually compile / build ffmpeg with libCurl: ./configure --enable-libcurl

### yt-dlp
Ytdlp has support to use curl_cffi, which supports http/3 `pip install "yt-dlp[default,curl-cffi]"`. This package is used to bypass cloudflare fingerprinting detection. But i don't know how you can enforce http3. Maybe slightly modify the source code?
