### ISSUE TITLE
If I drag a video to the MPV.exe it will not autoload scripts (in portable mode).

### ISSUE THREAD

**Issue by chrixxxx** [mpv-player/mpv#8841]
### Important Information

Provide following Information:
- mpv version : 0.33 (latest stable release)
- Windows Version: 10 - 64bit
- Source of the mpv binary : sourceforge binaries here https://sourceforge.net/projects/mpv-player-windows/files/stable/mpv-0.33.0-x86_64.7z/download

### Reproduction steps
In portable mode (not tested otherwise) :
dragging a video/media directly into the MPV.exe will make MPV to load it and start, but without loading any script that should be auto loaded (from the "/portable_config/scripts" directory, path relative to where the executables are)  with "load-scripts=yes" in the config.

I don't know if this is intended as behavior, but it  seems pretty strange to me, since if I create a "shortcut" to the MPV.exe and I drag the media into this shortcut (pointing to the MPV.exe).. it will correctly start and load the media, auto-loading also the scripts, instead.

**Comment by Akemi** [comment]
please add a log of the working and broken case.

**Comment by chrixxxx** [comment]
> please add a log of the working and broken case.

I would be glad too.. but when I drag the media file directly to the MPV.EXE it seems no log file is generated too (like the program was ignoring most setting from the config file or had started with not settings at all - and only input keys from input.conf are set)

While dragging it to the shortcut created from MPV.EXE..  everything works as expected: a log file is created and all the scripts are auto-loaded too.

I'm adding a (ugly) screenshot trying to render visually what I'm trying to explain about this strange behavior I noticed.



[![ugly-Screenshot.png](https://i.postimg.cc/sgwL1smS/ugly-Screenshot.png)](https://postimg.cc/fVSCr46T)

**Comment by avih** [comment]
1. When you right click the shortcut and then click "Properties", please post the content of the fields "Target" and "Start in".
2. Do post a log with the shortcut when everything is OK. It will help us see which config dirs/files exist on your system, which mpv version is used, etc.
3. Try also posting a log of this: open a command prompt, cd to the dir where mpv is, then run `.\mpv.exe --log-file=log.txt some-video.mkv` and then quit/close (replace some-video.mkv with an actual path to an existing video).

**Comment by avih** [comment]
Also, I can't reproduce your issue. Here's my test setup:
1. Downloaded the exact same binary like you - https://sourceforge.net/projects/mpv-player-windows/files/stable/mpv-0.33.0-x86_64.7z/download
2. extracted it to some dir.
3. Next to `mpv.exe` I created a dir `portable_config`
4. Inside `portable_config` I created a file `mpv.conf` with just two lines (note that it doesn't need `load-scripts=yes` because that's the default anyway, but you reported that you set it, and so did I):
```
log-file=d:/mpv-log.txt
load-scripts=yes
```
5. Inside `portable_config` I created a dir `scripts`
6. Inside `scripts` I created a file `ping.js` which contains 1 line (it display a timestamp at the OSD every 500 ms):
```js
setInterval(function() { mp.osd_message(mp.get_time_ms()) }, 500)
```

With the above setup:
1. The file `d:/mpv-log.txt` is recreated correctly when I drag-and-drop a video file over `mpv.exe` in Windows explorer.
2. The `ping.js` is definitely loaded and shows a message at the window every 500 ms.

So I can't reproduce neither the issue that a log file is not created, nor the issue that scripts are not loaded.

Now, please duplicate my setup (if you don't have a `d:` drive then use some other path - but NOT `c:/mpv-log.txt` because C: can be protected for writes) and post the log file after you drag a file onto `mpv.exe` in Windows explorer.

**Comment by chrixxxx** [comment]
This is relative to your first post.. then I'll replicate on my system what you asked in the last one, too

1. target = "K:\[ apps ] Players - Encoders\mpv64\mpv.exe" - start in = "K:\[ apps ] Players - Encoders\mpv64"
2. mpv_log.txt attached
3. MPV.exe called from the command prompt works fine..  log.txt attached too.

[mpv_log.txt](https://github.com/mpv-player/mpv/files/6509803/mpv_log.txt)
[log.txt](https://github.com/mpv-player/mpv/files/6509808/log.txt)

**Comment by chrixxxx** [comment]
Ok. I got what was happening and why.

One of my scripts hanged at some points when I was dragging a media file on the MPV.EXE ..  and that was the reason why it wasn't working anymore in that specific case (while others were; I had simply disabled some functions while trying to locate the problem.. and forgot to re-enable them, so I erroneously  thought NONE of the scripts were working..)

My mistake was due to my misunderstanding of how the support function utils.getcwd() worked.

On the manual there's written: "Returns the directory that mpv was launched from"

So I assumed it was the directory from where MPV.EXE itself was launched.. but it isn't. It's like the "working-directory" property.

Is there any way/function to let the script aware of the directory where the currently running MPV.EXE itself is located/launched from ?

I'm sorry I didn't got this alone before posting here...  
.. thank you very much for your help.

(it may be closed)

**Comment by avih** [comment]
> So I assumed it was the directory from where MPV.EXE itself was launched.. but it isn't. It's like the "working-directory" property.

Yes, it's exactly the `working-directory` property: https://github.com/mpv-player/mpv/blob/master/player/lua/defaults.lua#L746-L748

And it stands for Get Current Working Directory.

> Is there any way/function to let the script aware of the directory where the currently running MPV.EXE itself is located/launched from ?

No, but you can get the config diretory with `mp.command_native({"expand-path", "~~/"})` - https://mpv.io/manual/master/#command-interface-expand-path .

**Comment by avih** [comment]
> Is there any way/function to let the script aware of the directory where the currently running MPV.EXE itself is located/launched from ?

Actually, on Windows there is - `~~exe_dir` (use with `expand-path`). See https://mpv.io/manual/master/#paths
