### ISSUE TITLE
Save A-B Loop

### ISSUE THREAD

**Issue by BitTiamatu** [mpv-player/mpv#8842]
Since MPV can create a loop is there anyway to save this loop to file?

**Comment by Akemi** [comment]
i am not sure, do you want to save the loop data to a file (eg start and end time) or do you want to extract the looped part to a file (eg video, audio, subs, etc)?

both are not part of mpv, but the former can be done via a lua/js script or even a key binding. the latter can also be done via a script and there are already scripts that do exactly that.

docs:
https://github.com/mpv-player/mpv/blob/master/DOCS/man/javascript.rst
https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst
https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst

scripts:
https://github.com/kelciour/mpv-scripts/blob/master/sub-cut.lua
https://github.com/Kagami/mpv_slicing
https://github.com/snylonue/mpv_slicing_copy
https://github.com/pvpscript/mpv-video-splice

**Comment by BitTiamatu** [comment]
That would be fine if scripts actually worked for me which they don't. I tried dumping the ab loop cache command and it says it works in the console but the output file is nowhere to be found.

**Comment by Akemi** [comment]
you are way to vague. if you have troubles with a script try to report it to the script author. if the problem actually lies with mpv please open a proper issue.
