### ISSUE TITLE
MPV for Andoird on NVIDIA Shield: Can't make newline in input.config

### ISSUE THREAD

**Issue by neoborn1337** [mpv-player/mpv#8846]
I have tried to edit the inapp input.config with my Nvidia SHIELD remote but can only input one single command. I can't make a new line and input another command. When I just put all commands that i need after each other they don't work anymore.
I have also tried to connect my PC Keyboard to the Shield and use the ENTER key on that one but there won't ever be a new line on the input.config screen.

I am using the march release of mpv for android.

**Comment by Akemi** [comment]
seems like you are having a problem with mpv android. in that case you should report it to the appropriate place here https://github.com/mpv-android/mpv-android

also make sure to follow the issue template properly. if you didn't get to chose an issue template please make sure to be logged in before creating a new issue.
