### ISSUE TITLE
mpv fails to retrieve geometry values via mp.utils.subprocess

### ISSUE THREAD

**Issue by trappedinspacetime** [mpv-player/mpv#8847]
mpv 0.33.0-128-gd3b7732aaa
Ubuntu 20.04
I made a `js` script to execute a shell script. 
`printwinpos.js`:

          function on_start() {
              var result = mp.utils.subprocess({ args: ['save-position'], cancellable: false });
              dump(result);
          }
          mp.register_event("shutdown", on_start);
          
`save-position`:

          #!/bin/bash
          echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket | jq .data | tr '"' ' ' | cut -d'.' -f 1 > ~/.config/mpv/scripts/last_window_rect2.txt

`save-position` script is at `~/.local.bin` and its path is included in `PATH` environment variable. It executes well as it is but it prints empty values when it is called from `printwinpos.js` script. But if I  change 
       
            echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket | jq .data | tr '"' ' ' | cut -d'.' -f 1 > ~/.config/mpv/scripts/last_window_rect2.txt
            
to 

          echo "hello" > ~/.config/mpv/scripts/last_window_rect2.txt
                   
  it prints `hello` into    `last_window_rect2.txt` 
  I need your guidance to figure out what's going wrong

**Comment by avih** [comment]
I didn't try to follow the dataflow closely, but you're registering the `shutdown` event, which means that things are shutting down when the script is called, it it gets called at all - because the script is shutting down too.

But if it does get called, why so complex? can't you do something like this?
```js
mp.utils.write_file("file://~/.config/mpv/scripts/last_window_rect2.txt", mp.get_property("geometry"))
```

**Comment by avih** [comment]
Also, I don't think you can read the window position. IIRC you can only read its width and height (via the properties `osd-width` and `osd-height`, which are also part of `osd-dimensions`).

**Comment by trappedinspacetime** [comment]
@avih Thank you for responding. 

    mp.utils.write_file("file://~/.config/mpv/scripts/last_window_rect2.txt", mp.get_property("geometry"))

It works but as you mentioned it only saves geometry value. What I need to save window position of the MPV player but it only possible via external shell script using `xdotool` and `pid` of MPV.
As you noticed, it seems that shell script fail to retrieve window geometry since it probably exits window before executing shell script. 

The following script also fails:

                function on_exit() {
              var mpv_pid = mp.utils.getpid();
              var winpos = mp.utils.subprocess({ args: ['xdotool', 'getwindowgeometry', mpv_pid], cancellable: false });
              var result = mp.utils.write_file("file://~/.config/mpv/scripts/last_window_rect5.txt", winpos );
          
              dump(result);
          }
          
          
          mp.register_event("shutdown", on_exit);


with the error message:

          There are no windows in the stack
          Invalid window '%1'
          Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
          --shell      - output shell variables for use with eval
          --prefix STR - use prefix for shell variables names (max 16 chars) 
          If no window is given, %1 is used. See WINDOW STACK in xdotool(1)

**Comment by avih** [comment]
> with the error message:

That's because you use `xdotool` incorrectly. Read its man page first.

Then add this line to the begining of your script:
```js
print("mpv pid:", mp.utils.getpid());
```
Then run mpv and pause it. The pid will be printed to the terminal.
Then learn how to use xdotool correctly, maybe using the pid, to get the mpv window geometry.
Once you figure out how to invoke xdotool correctly, modify the subprocess command accordingly.

**Comment by trappedinspacetime** [comment]
@avih Thank you for your help. That mistake escaped my attention, I attempted to use  the `pid` of the MPV instead of its `window id`. Unfortunately MPV doesn't provide `window id` property. Fortunately I achieved to make it work via `xdotool`.
I tried many combinations from `mp.commandv` to ` mp.subprocess`. Only the following works:
`save-pos` bash script:

        #!/bin/bash
        xdotool search --sync --class mpv getwindowgeometry > ~/.config/mpv/scripts/last_window_coords.txt

`win-pos.js`:
function on_exit() {

    var winpossave = mp.command_native({
        name: "subprocess",
        playback_only: false,
        capture_stdout: true,
        args : ["save-pos"]
    });



}


mp.register_event("shutdown", on_exit);
