### ISSUE TITLE
Playback stutters occasionally on wayland

### ISSUE THREAD

**Issue by focus64** [mpv-player/mpv#8851]
Commit f4e89dd introduces playback stutters on wayland (on both Sway and Gnome 40). 

The stutters are mostly observed in windowed mpv. 

On Gnome 40 and Sway, playback stutters become severe when windowed mpv being placed side by side with firefox and scrolling up and down the web page in firefox.

On Gnome 40, playback stutters become visible when hitting "super" key and entering into "activities overview" mode.

I am on Arch linux with Intel integrated graphics HD 630.

[A sample log](http://0x0.st/-epc.log).

**Comment by Dudemanguy** [comment]
I can't reproduce in GNOME or sway (AMDGPU).

**Comment by LaserEyess** [comment]
I can't reproduce this on the same GPU, I tried both vulkan and openGL, and a variety of setttings.

```
mpv --no-config $video
mpv --no-config --video-sync=display-resample $video
mpv --no-config  --video-sync=display-resample --interpolation $video
```
All of those with both ``--gpu-api=vulkan --gpu-context=waylandvk`` and ``--gpu-api=opengl --gpu-context=wayland``.

I have an iHD 620, using the latest stable mesa release in arch's repos.

**Comment by focus64** [comment]
It's unfortunate if you cannot reproduce it.

My system is Kaby  Lake. And I am also on the latest stable mesa in arch.

`--video-sync=display-resample` seems to help reduce stutters a lot.

**Comment by Dudemanguy** [comment]
Well you may or may not be seeing stutter, but it doesn't really make any sense that screwing around with a totally different application would affect mpv in anyway.

**Comment by LaserEyess** [comment]
Can you try capturing a `WAYLAND_DEBUG=client` log for both mpv and firefox and report that to sway or GNOME? Not that this isn't an mpv bug, but it seems like it has to be something happening via the compositor, so those devs might know more.

**Comment by Dudemanguy** [comment]
You could post WAYLAND_DEBUG logs here too if you want. Maybe there's something interesting.

**Comment by focus64** [comment]
I tried this command:

    WAYLAND_DEBUG=1 mpv https://www.youtube.com/watch?v=XYFLK8gXMRU  2>&1  | tee wayland-debug.log

Here is my log: [wayland-debug.log](http://0x0.st/-eWk.log)

**Comment by focus64** [comment]
After spending more time on it, I found mpv stutters on its own without requiring activities from other applications. I even observed stutters in fullscreen mode.

**Comment by Dudemanguy** [comment]
Could you apply this simple patch, produce a log file (--log-file), and post the results? We should be able to see some stuttering in the measurements there.
```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index 6075b9a34b..86e57840b8 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -1856,6 +1856,7 @@ void wayland_sync_swap(struct vo_wayland_state *wl)
     uint64_t ust_mp_time = mp_time_us() - (now_monotonic - wl->sync[index].ust);
 
     wl->last_queue_display_time = ust_mp_time + wl->vsync_duration;
+    MP_VERBOSE(wl, "Frame display time: %"PRId64"\n", wl->last_queue_display_time);
 }
 
 void vo_wayland_wakeup(struct vo *vo)
```

**Comment by Dudemanguy** [comment]
Actually nevermind, I can actually see it now.
