### ISSUE TITLE
How is it possible to make adaptable aspects? Like for 16*9 and 9*16

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#8855]
I adjusted the initial window position and size like below example. I am satisfied with this.
But when video aspects is `9*16` I'd like to my window position and size adapt to `9*16`.

`geometry=1600x900-0+0`

Can someone help me?
_(English isn't my native language.)_

mpv 0.33
Win 10 Pro x64 20h2

**Comment by Akemi** [comment]
you can probably use auto profiles for that https://github.com/mpv-player/mpv/blob/ef0aafbd429792781886a6da9d392ddf76cdc7d6/DOCS/man/mpv.rst#conditional-auto-profiles

**Comment by Max-Enrik** [comment]
@Akemi Thank you a lot.
I tried below profile it changes but it doesn't fit to whole window and position of the mpv window isn't correct.
How can I correct it?

```
profile-cond=width  <= 800
profile-cond=height >= 1200
geometry=720x1280-0+0
```
