### ISSUE TITLE
ASS subtitles can't display correctly

### ISSUE THREAD

**Issue by eko5624** [mpv-player/mpv#8874]
- mpv version  
mpv-0.33.0-173-029ff10

- macOS Version
bigsur 11.4

- Source of the mpv binary or bundle
https://github.com/NextFire/mpv-macos-git-builds/releases

If the fonts which are asked in the .ass file are not installed, mpv will display blank rectangles rather than default font. 
![9980B2577F01108938CC12B5628E6EF2](https://user-images.githubusercontent.com/84926938/119962956-233e6700-bfda-11eb-9f3d-f3e2a8021a5f.jpg)
 

Reproduction steps

1. play a video with any .ass subtitle which asked fonts didn't be installed.

2. watch the ass's fonts .

 Expected behavior
 
 the asked fonts in the .ass can fallback to the OS default fonts than blank rectangles.
 
 Actual behavior
 
 the asked fonts in the .ass display blank rectangles.

**Comment by Akemi** [comment]
don't ignore the issue template. provide a log and and example file. also libass is responsible for picking a proper fallback font. so you should most likely report it to them.

**Comment by eko5624** [comment]
> don't ignore the issue template. provide a log and and example file. also libass is responsible for picking a proper fallback font. so you should most likely report it to them.

I re-edited it,  please take a look, thanks~

**Comment by eko5624** [comment]
> the font libass picks in your case doesn't seem to work. on my and it picks a different one and works:
> 
> yours:
> 
> ```
> [   9.697][i][sub/ass] fontselect: Using default font family: (方正黑体_GBK, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
> [   9.697][v][sub/ass] fontselect: (方正黑体_GBK, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
> [   9.699][v][sub/ass] fontselect: (微软雅黑, 400, 0) -> /Users/huangjiajia/Library/Fonts/微软雅黑.ttf, -1, MicrosoftYaHei
> ```
> 
> mine:
> 
> ```
> [sub/ass] fontselect: Using default font family: (微软雅黑, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
> [sub/ass] fontselect: (微软雅黑, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
> [sub/ass] fontselect: (方正黑体_GBK, 400, 0) -> /System/Library/Fonts/ヒラギノ角ゴシック W3.ttc, -1, HiraginoSans-W3
> ```

Thanks for your reply . So how I can fix it,  do you have an idea ?

**Comment by Akemi** [comment]
try setting `sub-font` to a font that works. i believe it is used as a fallback font.

**Comment by eko5624** [comment]
> try setting `sub-font` to a font that works. i believe it is used as a fallback font.

Yes,  it works. But 'Sub-font'  also affect other ass subtitles . Like this issue --sub-font will also affect the ASS file if the required fonts are not installed. #8637

**Comment by Akemi** [comment]
then, like mentioned, you have to report that to libass. since they are responsible for picking a fallback font.

**Comment by eko5624** [comment]
OK,  thanks.
