### ISSUE TITLE
mpv lacks high resolution application icons

### ISSUE THREAD

**Issue by charbelnicolas** [mpv-player/mpv#8878]
### Important Information

Provide following Information:
- mpv version: 0.33.1-dirty
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch Community Repo
- If known which version of mpv introduced the problem: N/A
- Window Manager and version: awesome v4.3-1019-ga4572b9b5
- GPU driver and version: NVIDIA Proprietary v. 465.31
- Possible screenshot or video of visual glitches

![blurryicon](https://user-images.githubusercontent.com/14960414/120051440-4707aa00-bfe6-11eb-88d8-4159f257528d.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Open mpv on a big taskbar and the icon will be blurry. 

### Expected behavior

I expect mpv to have a 64 x 64 icon at least and not be blurry.

### Actual behavior

Doing a xprop _NET_WM_ICON on an mpv window results in showing only a 32 x 32 icon and nothing for 64 x 64 or 128 x 128.

My taskbar is 50 pixels high so the icon is blurry.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/6563739/output.txt)

**Comment by Dudemanguy** [comment]
mpv does install 64x64 and 128x128 sized icons. I have no clue what your taskbar is doing, but the icons exist.

**Comment by charbelnicolas** [comment]
Sorry, it was my mistake. I've fixed the issue with the awesome.set_preferred_icon_size(64) option in the rc.lua.
