### ISSUE TITLE
White window background when starting a video

### ISSUE THREAD

**Issue by FCrane** [mpv-player/mpv#8880]
Hi!

When starting a video by double-clicking, a white background flashes in the window for a fraction of a second before video playback starts. Only happens with border = yes (but also when starting with --no_config, so it does not seem to be caused by any config parameter). Without the border, the background starts black, which is fine.

The white flashing is really annoying and it would be great if this could be fixed, so that either the window opens with a black background or it opens only when the first video frame is rendered.

Thanks!

### Important Information

Provide following Information:
- 0.34 (latest)
- Windows 10
- https://sourceforge.net/projects/mpv-player-windows/files/64bit/

### Reproduction steps

Start mpv by double-clicking a video file,

### Expected behavior

Window opening with first video frame or black background

### Actual behavior

Window opening with white background for a fraction of a second and then starting video playback

**Comment by FCrane** [comment]
This also happens when using libmpv and assigning a wid of an existing window! When playback stops, the whole window remains white...

How can I prevent that?

**Comment by fire838** [comment]
Can you explain how to fix for a tech illiterate person?

**Comment by garoto** [comment]
> Can you explain how to fix for a tech illiterate person?

No user-facing fix possible as far as I know. Any rendering "glitches" and whatnot on Windows while using the d3d11 renderer are inherented from flaws from the the renderer implementation code itself. Anything related to "Windows rendering" is in hard maintaince mode for quite some time now since the main contributor is AWOL.

**Comment by garoto** [comment]
>  white background flashes in the window for a fraction of a second before video playback starts. 

Forgot to mention that this is probably "just" mpv compiling shaders when using `gpu-hq` or when tweaking the scalers manually.

**Comment by Dudemanguy** [comment]
>Forgot to mention that this is probably "just" mpv compiling shaders

If true this is fixed by shader cache being on by default possibly? Anyways, if this is still a problem with the latest mpv, please open a new issue.
