### ISSUE TITLE
Fixed margins around video in windows mode

### ISSUE THREAD

**Issue by FCrane** [mpv-player/mpv#8881]
Hi!

I'm creating my own GUI with a LUA script, which works fine. However, the border, controls, timeline, etc. always overlay the video. It would be great if I could define an "extra margin" around the video (without cropping or scaling the video!) so that there is enough space for my GUI. In windowed mode only, of course (not for full screen).

E.g. I'd use a 2 pixel margin at the top, left and right of the video so that I can draw a thin border, and a 20 pixel margin at the bottom for drawing some controls and the timeline. Currently, this doesn't seem to be possible without covering (and therefore effectively loosing) some parts of the video, which is undesirable, of course.

It would be great if I even could dynamically change the margins from e.g. (2, 2, 2, 2) to (2, 2, 2, 20), etc. when some event occurs (like mouse movement within the window, mouse moved to the bottom of the window, or whatever condition I use. When dynamically changing the margins, the video should stay the same size and at the same position, but the window should increase ( decrease its size in all four directions.

Thanks!

### Expected behavior of the wanted feature

add margins (in pixels, separately for all 4 sides) around the video without changing video size, cropping or scaling the video.

**Comment by guidocella** [comment]
There are `--video-margin-ratio-*` options, though they accept a ratio and not pixels.

**Comment by FCrane** [comment]
--video-margin-ratio is unusable, because it's relative (and not absolute pixel values) and also it scales the video! Actually I can't imagine any situation where anybody would use that...

**Comment by avih** [comment]
> It would be great if I could define an "extra margin" around the video (without cropping or scaling the video!) so that there is enough space for my GUI. In windowed mode only, of course (not for full screen).

There's no such feature currently, and also no plans to add it. The video area calculations are already very complex, and the value in such feature is most likely not worth the additional complexity of integrating it with all the other margins/areas calculations.

However, if you do have a simple implementation for it which does not regress other related behavior, then feel free to open a PR.
