### ISSUE TITLE
Rounded window corners option

### ISSUE THREAD

**Issue by DanyGee** [mpv-player/mpv#8882]
### Expected behavior of the wanted feature
I would expect some switch to enable rounded window corners (maybe even specify the radius?) 🤔 
Of course not needed in fullscreen mode, just while windowed and probably when not using system decorations.
It would look a bit more modern 🤩 - especially when rounded corners trend is returning.
Overall rounded corners seem to be more pleasant to the eyes.
(Telegram desktop looks like it when you detach a watched video window)

![image](https://user-images.githubusercontent.com/26818551/120078425-d036e380-c0af-11eb-9eeb-efc2f89ec90a.png)

Zoom 👀 
![image](https://user-images.githubusercontent.com/26818551/120078505-2efc5d00-c0b0-11eb-984c-ea70be53731c.png)

**Comment by avih** [comment]
> especially when rounded corners trend is returning

And when it goes away again? should mpv chanse the hottest trends in UI design? (hint: no)

If you want rounded windows, configure your window manager to do that. It's not mpv's job.

**Comment by DanyGee** [comment]
Wow, that's why I suggested a SWITCH for those, who want it.
But OK.
Cheers.

**Comment by avih** [comment]
It's not about forcing. It's about adding code which adds complexity, for a task which is not mpv's to begin with.
