### ISSUE TITLE
How to remove metadata from drone footage

### ISSUE THREAD

**Issue by dlukas372** [mpv-player/mpv#8883]
I'm new to MPV so this might be a basic question, but how do I get rid of the metadata that shows up when I preview my drone footage on MPV? This footage becomes unusable for projects with metadata all over the screen.

**Comment by LaserEyess** [comment]
mpv is a video *player*, except for some rare circumstances, it cannot edit video metadata. You are looking for a video *editor* (or at least something that can modify containers). Try [ffmpeg](https://ffmpeg.org/).

If you want to edit the video while it is playing, in real time, mpv can do that via ffmpeg. Check out [this option](https://mpv.io/manual/master/#video-filters-vf),[ this option](https://mpv.io/manual/master/#video-filters-lavfi),  and a list of video filters from [ffmpeg's documentation](https://ffmpeg.org/ffmpeg-filters.html).

**Comment by dlukas372** [comment]
Thank you for responding. I'm not looking for use mpv as a video editor. What's happening is that when mpv plays my drone footage it displays active metadata on the screen as it plays the footage. MPV doesn't do this with camera footage, only with drone footage. I don't want to see the metadata appearing on top of the footage and I'm wondering how to turn this off!

**Comment by LaserEyess** [comment]
You'll have to give a log file and a sample, because mpv doesn't display anything to the screen by default. Does this "metadata" show up when using vlc, too?

**Comment by dlukas372** [comment]
This is the first time I've seen the metadata show up in footage. It wasn't happening with my default windows media player but I switched to MPV because I'm now filming 10-bit footage that Windows couldn't process, and now the metadata shows up, but only with drone footage. 

![image](https://user-images.githubusercontent.com/85039548/120124868-2b79dc00-c16b-11eb-9c97-e5111a8de871.png)

**Comment by LaserEyess** [comment]
mpv does not display "metadata" by default, and none of those things are even metadata that mpv parses, so I'm guessing they are subtitles that your drone software has embedded. Try `mpv --no-config --sub=no`. If that doesn't work, you need to give a sample file and a log file made with `mpv --no-config --log-file=log.txt` and upload it to some pastebin site.

**Comment by Dudemanguy** [comment]
Appears to be subtitles. If they really aren't, feel free to reopen.
