### ISSUE TITLE
Segfault while watching YouTube live stream

### ISSUE THREAD

**Issue by kelppo** [mpv-player/mpv#8890]
### Important Information

Provide following Information:
- mpv version
0.33.0-177-gfd8c673cfc
https://github.com/mpv-player/mpv/commit/fd8c673cfc1ee51f0bb05c8247a35d44003366da
- Linux Distribution and Version
Arch Linux
- Source of the mpv binary
https://aur.archlinux.org/packages/mpv-git
- If known which version of mpv introduced the problem
N/A
- Window Manager and version
Openbox 3.6.1-7
- GPU driver and version
amdgpu on kernel 5.12.8.arch1-1
mesa 21.1.1-1
- Possible screenshot or video of visual glitches
N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
N/A

### Expected behavior
No segfault

### Actual behavior
mpv segfaults

### Log file
Not sure if this is useful but here is the core dump:
https://0x0.st/-2Fk.xz

### Sample files
See above.

**Comment by CounterPillow** [comment]
core dump is probably not useful since we don't have your binary. Please give us a backtrace.

**Comment by kelppo** [comment]
Backtrace:
https://0x0.st/-_rU.txt

**Comment by avih** [comment]
> Backtrace:
> #0 0x00007fda0246a587 in () at /usr/lib/libluajit-5.1.so.2
> #1 0x000055957095d89b in load_scripts (L=0x404b3378) at ../player/lua.c:308

Well, it happens in luajit, and that `load_scripts` function in mpv is basically the "container" for the whole script, i.e. this function returns only once the script exits or throws an exception - so there's no hint in that mpv function.

For now, it looks like a luajit issue, but an mpv log (generated with `--log-file=log.txt` - just like the issue template requests) _might_ shed some light on which script causes it, and maybe roughly where in that script.

**Comment by CounterPillow** [comment]
Please build luajit with symbols. In fact, try rebuilding luajit+mpv in general, if you're using a git version or something this may be down to an ABI incompatibility.

**Comment by kelppo** [comment]
Sorry if the OP gives an impression that this is reproducible (it's not), I've since rebuilt mpv with debugging symbols and used it to watch a couple more hours of live stream and it hasn't happened again.

>For now, it looks like a luajit issue, but an mpv log (generated with --log-file=log.txt - just like the issue template requests) might shed some light on which script causes it, and maybe roughly where in that script.

I looked at my journal from the previous boot and didn't find anything interesting (probably because mpv was logging at default verbosity), for now I'll add this to my config.

>Please build luajit with symbols. In fact, try rebuilding luajit+mpv in general, if you're using a git version or something this may be down to an ABI incompatibility.

Ok.

**Comment by avih** [comment]
I'll close the issue for now.

You can still post an mpv log if you can get one, and we can reopen this issue if this ends up to be an mpv problem.

For now though, it doesn't look like an mpv issue.

**Comment by avih** [comment]
> Sorry if the OP gives an impression that this is reproducible (it's not), ...

@kelppo but you can still provide more info regardless of log. For instance:
- You described it as "Segfault while watching YouTube live stream". Did it actually happen _while_ you already watch the video? or maybe while mpv/youtbe-dl is still resolving the video but before it actually starts playing?
- If while playing - did it happen right away after playback started? or maybe some minutes/hours after it's been playing?
- Anything else you can provide. The stack trace was useful to know that it doesn't look like an mpv issue, but it still could be some random mpv script you installed which does something really nasty with lua, for instance, or it could be one of mpv's built in scripts (though normal script failure does not result in segfault - the script simply exits and mpv prints its stack trace and an error message).

**Comment by kelppo** [comment]
>You described it as "Segfault while watching YouTube live stream". Did it actually happen while you already watch the video? or maybe while mpv/youtbe-dl is still resolving the video but before it actually starts playing?
>If while playing - did it happen right away after playback started? or maybe some minutes/hours after it's been playing?

It happened when I've already been watching an hour or so.

>Anything else you can provide. The stack trace was useful to know that it doesn't look like an mpv issue, but it still could be some random mpv script you installed which does something really nasty with lua, for instance, or it could be one of mpv's built in scripts (though normal script failure does not result in segfault - the script simply exits and mpv prints its stack trace and an error message).

I only have autoload.lua, https://github.com/ekisu/mpv-webm, and this script I hacked up together although I've been using it for months now without problems:

```
local overlay = mp.create_osd_overlay("ass-events")
overlay.data = "{\\an9}Buffering.."

function print_buffering(name, value)
    if value == true then
        overlay:update()
    else
        overlay:remove()
    end
end

mp.observe_property("paused-for-cache", "bool", print_buffering)
```

I should note that this happened after I recently updated mpv and I've started enabling LTO when building the package, maybe this could be causing problem?

**Comment by avih** [comment]
> It happened when I've already been watching an hour or so.
> I only have autoload.lua, https://github.com/ekisu/mpv-webm, and this script I hacked up together although I've been using it for months now without problems: ...

Your buffering script looks fine. autoload.loa is both fairly small and is not known to cause issues of the segfault kind.

An hour into the video means that the main script which it could happen at is `osc.lua`, and while it's a complex script, there are no known issues where it can segfault.

I don't think it's related to LTO, but luajit is complex and very low level, but before LTO, I'd think it's maybe the specific version of luajit which you use. Maybe you updated luajit recently, etc.

It still sounds like a luajit bug to me, so if I were you I'd focus on this aspect. Maybe build luajit with debug symbols (but it's a JIT compiler, so I don't know how much that would help).

**Comment by KseniyaKolokolkina** [comment]
Well, after I updated my packages in Gentoo, I've been having a similar problem. Except, the package was build WITHOUT luajit installed (see use flags) and the program segfaults almost immediately after the program starts, before the video even starts playing. 

My USE flags for this package where (see: https://packages.gentoo.org/packages/media-video/mpv): +X, +alsa, -archive, -bluray, -cdda, +cli, -debug, +drm, -dvb, -dvd, +egl, -gamepad, +iconv, -jack, -javascript, -jpeg, -lcms, -libcaca, +libmpv, +libplacebo, +lua, +lua_single_target_lua5-1, -lua_single_target_luajit, -nvenc, -openal, -opengl, -pipewire, +pulseaudio, -python_single_target_python3_10, +python_single_target_python3_11, -python_single_target_python3_12, -rubberband, -sdl, -sixel, -sndio, -test, -tools, +uchardet, -vaapi, -vdpau, -vulkan, -wayland, +xv, -zimg, +zlib. 

+ = enabled. 
- = disabled.

**Comment by CounterPillow** [comment]
@KseniyaKolokolkina you use gentoo so you probably have a billion shitty -Ofast -fbreak-shit in your CFLAGS

**Comment by KseniyaKolokolkina** [comment]
@CounterPillow, well, no: 
```
COMMON_FLAGS="-O2 -pipe -march=native -mtune=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
```
