### ISSUE TITLE
How to patch ao_oss.c for #8768

### ISSUE THREAD

**Issue by ish-org** [mpv-player/mpv#8896]
I'm using mpv 0.33.1 on FreeBSD 14.0-CURRENT.
I want to play with oss driver (this is the default audio driver for FreeBSD) but it has the same issue #8768.
Is there any patches ?

P.S. I can play with alsa driver on FreeBSD 14.0-CURRENT without issue #8768.

**Comment by Akemi** [comment]
not that i know of.
