### ISSUE TITLE
Audio might get paused too early or clipped at the end with --reset-on-next-file=pause

### ISSUE THREAD

**Issue by kelciour** [mpv-player/mpv#8898]
### Important Information

- mpv version

```
mpv 0.33.0-178-g4989ccbe7a Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jun  6 09:58:46 +08 2021
FFmpeg library versions:
   libavutil       57.0.100
   libavcodec      59.1.100
   libavformat     59.2.101
   libswscale      6.0.100
   libavfilter     8.0.101
   libswresample   4.0.100
FFmpeg version: git-2021-06-05-29b244ff
```

- Platform and Version

Windows 10, but was able to reproduce the issue on Ubuntu 21.04 with mpv 0.33.0 built on Tue Dec 8 19:04:35 UTC 2020.

- If known which version of mpv introduced the problem

I could be wrong but after testing a few mpv builds from https://sourceforge.net/projects/mpv-player-windows/

20200830-git-bb1f821 - good
20200906-git-f57b90b - bad

https://git.srsfckn.biz/mpv/log/?qt=range&q=bb1f821..f57b90b

### Reproduction steps

1. Start the player in paused state with two audio files. Maybe use the audio file with no silence at the end to make it more easily noticeable. For example, 0489.mp3 from [mpv-issue-reset-on-next-file-pause-sample-files.zip](https://github.com/mpv-player/mpv/files/6605186/mpv-issue-reset-on-next-file-pause-sample-files.zip)
 
    ```mpv --no-config --pause --reset-on-next-file=pause 0489.mp3 0489.mp3```

2. Press `space` or `p` to unpause the player and start playback.

3. Wait until the end of the first audio file. The audio will be automatically paused a bit too early. If press `space` again, the first audio file will continue to play, then the second audio file starts to play and it will also stop a bit too early.

Strangely, after trying to repeat the same steps using a different audio file, 0486.mp3, I couldn't reproduce the issue on Windows yesterday, but today it fails too and I can't explain it. I had a muted NHL live stream in the background but it doesn't seem to make any difference. Also, my audio volume was low and maybe I just didn't notice it and thought it was good.

### Expected behavior

The first audio file is played until the end and then the player is paused or closed if there no second file to play.

### Actual behavior

The first audio file got paused just 1 second or less before it finished playing.
If there no second file to play next, playback ends a bit too early and audio is cut short.

### Log file

- [489-bad.txt](https://github.com/mpv-player/mpv/files/6605236/489-bad.txt)

- [486-good.txt](https://github.com/mpv-player/mpv/files/6605238/486-good.txt)

### Additional Information

Maybe relevant [Playback issues with --reset-on-next-file=pause #8079](https://github.com/mpv-player/mpv/issues/8079)

After adding `--gapless-audio=no`, everything seems to be fine and the issue couldn't be reproduced anymore.

**Comment by Dudemanguy** [comment]
Just for reference this issue does still exist and unsurprisingly was caused by b74c09efbf7c6969fc053265f72cc0501b840ce1.
