### ISSUE TITLE
save-position-on-quit & sub-forced-only are not working in v0.33.1

### ISSUE THREAD

**Issue by captaingreen82** [mpv-player/mpv#8899]
Here save-position-on-quit & sub-forced-only are not working in the latest version (v0.33.1)
I want to resume playback from where I left.
Do I need to add any log file to make it work like for adding shaders or is there any other reason ?
Please help me with this.

#OS = Windows
#My mpv.conf

profile=gpu-hq
deband=yes
volume-max=200
fs
osc=no
load-scripts=yes
no-hidpi-window-scale
autofit-larger=80%x80%
autofit-smaller=50%x50%
keep-open=yes
osd-on-seek=msg-bar  #<no,bar,msg,msg-bar>
osd-blur=0
osd-bar-w=99.9
osd-bar-h=1.3
osd-bar-align-y=1
osd-color='#00FF00'
osd-border-color='#000000'
osd-border-size=2.5
osd-duration=2000
sub-forced-only
sigmoid-upscaling=no
save-position-on-quit

**Comment by Doofussy2** [comment]
You need to use `save-position-on-quit=yes`

and the subs is possibly this:

https://github.com/mpv-player/mpv/issues/8396

**Comment by captaingreen82** [comment]
> You need to use `save-position-on-quit=yes`
> 
> and the subs is possibly this:
> 
> https://github.com/mpv-player/mpv/issues/8396

Still not working.

**Comment by Doofussy2** [comment]
What doesn't work? You need to attach a log.

**Comment by captaingreen82** [comment]
> What doesn't work? You need to attach a log.

How to attach a log please explain.

**Comment by hooke007** [comment]
you totally ignore the issue template. And the template has told u how to do it.

**Comment by captaingreen82** [comment]
> you totally ignore the issue template. And the template has told u how to do it.

Please send that link

**Comment by hooke007** [comment]
I mean `--log-file`
just click the new issue button to see.
Or https://mpv.io/manual/master/#options-log-file

**Comment by Doofussy2** [comment]
Just for reference, save-position works correctly for me on Windows 10.

**Comment by snylonue** [comment]
Does your mpv have write access to `watch_later` folder?

**Comment by captaingreen82** [comment]
> Does your mpv have write access to `watch_later` folder?
> 

I don't know how to check that ?

**Comment by captaingreen82** [comment]
> Does your mpv have write access to `watch_later` folder?

OK
So, this was the real culprit.
I had installed mpv in C drive, so maybe Admin was not allowing to access the watch_later folder.
But when I reinstalled it in another drive, its working fine.
Thanks

**Comment by Dudemanguy** [comment]
The problem seems solved.
