### ISSUE TITLE
How to add message on screen in autoload.lua

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8900]
Hi. I need some help, I want to add the message "_Last file is loaded"_ or _"This is the last file_" or something like that when the last file is loaded and there is not more in the current folder to the autoload.lua script.

**Comment by avih** [comment]
There's no builtin option for that, if that's what you're asking.

You'll need to edit the file and add (program) it yourself. Teaching how to program in Lua is out of scope for the issue tracker.
