### ISSUE TITLE
Why is Vulkan not recommended for Windows?

### ISSUE THREAD

**Issue by realiti4** [mpv-player/mpv#8902]
I've recently started using mpv, and it is an amazing player, lots of freedom. One question that I have is with Vulkan I get much lower and stable vsync-jitter, but every comment or post that I came across not recommends vulkan on windows. Is there a reason for that? I couldn't find any recent info about it. Thanks.

**Comment by haasn** [comment]
I have no idea. Maybe @rossy knows.

**Comment by CounterPillow** [comment]
because GPU drivers on Windows are a mess and you can trust them to do DX11, but not much beyond that. Especially Intel.

**Comment by Jules-A** [comment]
Weird, for me vsync-jitter is far higher (200ms with Vulkan vs ~20 with DX11).

**Comment by realiti4** [comment]
> Weird, for me vsync-jitter is far higher (200ms with Vulkan vs ~20 with DX11). There's also still a bug with fullscreen (I think it's AMD only) but the main reason I went back to DX11 was the vsync-jitter.

For some reason d3d11 vsync-jitter fluctuates a lot between 0.050-0.200 for me. Vulkan has the lowest which is 0.010, and opengl is around 0.025. I don't see much delayed or mistimed frames for any of them though, judder seems ok too.

**Comment by haasn** [comment]
vsync-jitter is a mostly pointless metric. mpv smooths out the variation.

**Comment by realiti4** [comment]
> vsync-jitter is a mostly pointless metric. mpv smooths out the variation.

Oh ok, good to know thanks, because everything else feels good to my eyes, 72hz display should be helping as well.
