### ISSUE TITLE
Use mpv x86 on win10x64, play MP4 file, program crash

### ISSUE THREAD

**Issue by dbyoung720** [mpv-player/mpv#8906]
Use mpv x86 on win10x64, play MP4 file, program crash

log :  [mpv.log](https://github.com/mpv-player/mpv/files/6621933/mpv.log)

**Comment by CounterPillow** [comment]
I cannot reproduce this at all. Please do not ignore the issue template, knowing what version of mpv you're using and where you got the binary from is critical.

If you can, please also try obtaining a backtrace from a debugger.
