### ISSUE TITLE
Playing larger .rar video archives

### ISSUE THREAD

**Issue by Horuyuki** [mpv-player/mpv#8911]
### Important Information

Provide following Information:
- mpv version
`mpv 1:0.33.1-2`
- Linux Distribution and Version
Arch linux rolling latest
- Source of the mpv binary
Official pacman repo
- If known which version of mpv introduced the problem
This one
- Window Manager and version
Gnome Latest update
- GPU driver and version
-nvidia 465.31

### Expected behavior
I dragged the first .rar file into mpv and it plays the movie in full.
### Actual behavior
It buffers a bit and then just crashes. The rar-ed video file is around 110GN total.
Please note that vlc works alright and plays it if I drag the same file in.
And in the mean while a smaller movie at 30GB loaded fine.

**Comment by CounterPillow** [comment]
provide a log file and a backtrace

**Comment by Horuyuki** [comment]
@CounterPillow 
Here is the command output: https://pastebin.com/nZwSZBV9
It just kept going on after the same lines of caution reappeared, and yes I agree the rar format is not necessary anymore in this century.

But I don't know what you mean by back trace?
And here is the log:
https://pastebin.com/deGssuUZ

**Comment by CounterPillow** [comment]
> But I don't know what you mean by back trace?

If it crashes with e.g. a segmentation fault, a backtrace can tell us where it crashes. You can get one by having mpv with debug symbols (i.e. not the one Arch Linux ships, use mpv-build) and then using gdb to debug it:
```
gdb path/to/your/mpv
run --your --mpv --arguments here
# wait until it crashes
bt full
```

See https://wiki.archlinux.org/title/Debugging/Getting_traces

**Comment by garoto** [comment]
In 2021 and if on a *nix-like OS, it's better to just use [rar2fs](https://github.com/hasse69/rar2fs/) instead of relying on `libarchive`'s well-known poor RAR capabilities.

**Comment by Horuyuki** [comment]
> In 2021 and if on a *nix-like OS, it's better to just use [rar2fs](https://github.com/hasse69/rar2fs/) instead of relying on `libarchive`'s well-known lackluster RAR capabilities.

True, but is it even being maintained still? I just installed it and it works like a charm. Though I don't know if it will break in some future updates if it is not being actively developed. Great solution still

**Comment by Horuyuki** [comment]
> > But I don't know what you mean by back trace?
> 
> If it crashes with e.g. a segmentation fault, a backtrace can tell us where it crashes. You can get one by having mpv with debug symbols (i.e. not the one Arch Linux ships, use mpv-build or see the instructions on the archwiki) and then using gdb to debug it:
> 
> ```
> gdb path/to/your/mpv
> run --your --mpv --arguments here
> # wait until it crashes
> bt full
> ```
> 
> See https://wiki.archlinux.org/title/Debugging/Getting_traces

I think it is safe to assume that `libarchive` is not reliable anymore. Since it is what was shown in the logs and command output. While vlc works fine it could be something to do with mpv.

And sorry I cannot provide you with a back trace, that thing itself ran me into some problems on my Arch OS that I can't solve right now:
```gdb /bin/mpv
gdb: error while loading shared libraries: libboost_regex.so.1.76.0: cannot open shared object file: No such file or directory
```
Can you work with the logs instead?

**Comment by CounterPillow** [comment]
> Can you work with the logs instead?

No, fix your system. Don't do partial upgrades on a distribution that doesn't support them.

**Comment by Horuyuki** [comment]
> > Can you work with the logs instead?
> 
> No, fix your system. Don't do partial upgrades on a distribution that doesn't support them.

I never do a partial upgrade. It is just that I don't want to look into that problem, to get `gdb` to work, and then got a traceback, then hopefully make mpv work when smth like vlc and rar2fs works. Mentioning this problem in hopes of mpv's more all around capabilities.

**Comment by CounterPillow** [comment]
Ok but right now we have no sample file and no traceback so we can neither reproduce the bug nor know where it crashes, and therefore there is no chance of anyone bothering to look into this further
