### ISSUE TITLE
on kde with vulkan api mpv crashes on fullscreen

### ISSUE THREAD

**Issue by ZerataX** [mpv-player/mpv#8912]
### Important Information
- mpv version
```
mpv 0.33.1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4
 ```
- Linux Distribution and Version
  - system: `"x86_64-linux"`
  - host os: `Linux 5.10.42, NixOS, 21.05.906.cedcf2565c6 (Okapi)`
  - multi-user?: `yes`
  - sandbox: `yes`
  - version: `nix-env (Nix) 2.3.12`
  - channels(root): `"nixos-21.05.906.cedcf2565c6, nixos-hardware, nixos-unstable-21.11pre294109.fbfb79400a0"`
  - channels(kaine): `"home-manager-21.05"`
  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
- Source of the mpv binary: nixpkgs
- Window Manager and version
  - DE: Plasma 5.21.5
  - WM: KWin
- GPU driver and version
  - GPU: NVIDIA GeForce RTX 2080 Ti 
  - Driver version: 460.73.01

### Reproduction steps

- `nix-shell -p mpv`
- `mpv video.mkv --no-config --fs --gpu-api=vulkan`

This only happens on KDE  if I use gnome it is fine. If I fullscreen after I opened up mpv in windowed mode it's also fine.
It's also fine as long as I use opengl.

Only when I use KDE with vulkan and start in fullscreen this happens.

vulkainfo seems to behave normally under kde:
[vulkaninfo.log](https://github.com/mpv-player/mpv/files/6641769/vulkaninfo.log)

### Expected behavior
mpv opens in fullscreen

### Actual behavior
mpv crashes
```
[vo/gpu/vulkan/libplacebo] vk->CreateSwapchainKHR(vk->dev, &sinfo, PL_VK_ALLOC, &p->swapchain): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/swapchain.c:540)
[vo/gpu/vulkan/libplacebo] Failed (re)creating swapchain!
Could not initialize video chain.
```

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/6641763/mpv.log)

### Sample files

works for me with anything even images

**Comment by Dudemanguy** [comment]
Not sure if this still occurs but it's unlikely to be an mpv issue in any case. Presumably KDE and/or NVIDIA fixed it by now (wayland on vulkan on nvidia theoretically works).

**Comment by pc00per** [comment]
I'm still getting this issue on --hwcodec=auto-safe with some online .m3u8 streams
```$ mpv 'https://c-4.mzzcloud.life/_v8/560b651f49fce209a60ba33b879a3deb54899ced1b1c689fccacf64b275a47e64505c8bbbd1f5c34bcaab15be51f3c7b1cdccf7a4d35a380d38980af086ccda394b8b355962c92e8ac98983f2265c1aa35f63ab3c108e242fc0edba1e55186deb639cfb92f167056a2c6299bc873f79d65979aedaf9488b9dcde00d1936e0306/360/index.m3u8' --hwdec-codecs=all
 (+) Video --vid=1 (h264 720x360 23.976fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
Using hardware decoding (nvdec).
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 720x360 cuda[nv12]
[vo/gpu/vulkan/libplacebo] vk->CreateSwapchainKHR(vk->dev, &sinfo, PL_VK_ALLOC, &p->swapchain): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/swapchain.c:583)
[vo/gpu/vulkan/libplacebo] Failed (re)creating swapchain!
Could not initialize video chain.
Video: no video
A: 00:00:01 / 02:17:17 (0%)```

**Comment by Dudemanguy** [comment]
If this only happens when passing ``--hwdec``, it's a totally different issue.

**Comment by pc00per** [comment]
Ok I solved the issue, it was `nvdec`. Tried `auto-copy` & hwdec used `nvdec-copy` which kinda fixed everything. xD
