### ISSUE TITLE
--gpu-context=displayvk doesn't work on Intel iGPU

### ISSUE THREAD

**Issue by jbeich** [mpv-player/mpv#8916]
### Important Information

- mpv version: v0.33.0-184-g03b9f8e323
- Linux Distribution and Version: FreeBSD 14.0-CURRENT (from 2021-06-12) amd64
- Source of the mpv binary: self-built [mostly](https://github.com/freebsd/freebsd-ports/blob/main/multimedia/mpv/files/patch-libmpv_mpv.def) unmodified
- If known which version of mpv introduced the problem: new feature
- Window Manager and version: vt(4) console
- GPU driver and version: DRM 5.4.92.g20210526 + Mesa 21.1-branchpoint-2831-g5e4ff4ef1ff
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1. Load KMS drivers
2. Switch to VT console (from X11 or Wayland)
3. Run `mpv --vo=gpu --gpu-api=vulkan --gpu-context=displayvk /path/to/file`

### Expected behavior

Runs fine, like fec7c2c30e0c did on top of 1b8f10f54af1.

```
VO: [gpu] 1920x1080 yuv420p
V: 00:00:00 / 00:00:30 (2%) Cache: 1.5s/610KB
```

### Actual behavior

Aborts after failing to find usable configuration.

```
[vo/gpu/vulkan] Selected plane (0) not available on selected display.
[vo/gpu] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.
```

### Log file

- [good](https://github.com/mpv-player/mpv/files/6642658/displayvk.log.txt)
- [bad](https://github.com/mpv-player/mpv/files/6642647/displayvk.log.txt)

### Sample files

https://jell.yfish.us/media/jellyfish-3-mbps-hd-h264.mkv

**Comment by philipl** [comment]
You need to pick a plane that is available. It defaults to 0 but your 0 plane isn't connected to anything. That's also the case on my hardware, and you probably need to specify plane `1`.
