### ISSUE TITLE
Error parsing option ytdl_path (option not found)

### ISSUE THREAD

**Issue by github-account1111** [mpv-player/mpv#8917]
### Important Information

Provide following Information:
- mpv version 0.33.0-178-g4989ccbe7a
- Windows Version Windows 10 1809
- Source of the mpv binary Sourceforge
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

1. Have yt-dlp installed
2. Add `ytdl_path=yt-dlp` to mpv.conf
3. From Powershell, run `mpv https://www.youtube.com/watch?v=YbJOTdZBX1g`

### Expected behavior

Video opens without any errors

### Actual behavior

Video opens but there's also an error:

```
Error parsing option ytdl_path (option not found)
O:/bin/mpv/portable_config/mpv.conf:37: setting option ytdl_path='yt-dlp' failed.
```

which tells me it's using something other than youtube-dl to view it.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to https://0x0.st/
or attach it to the github issue, and replace this text with a
link to it.

[output.txt](https://github.com/mpv-player/mpv/files/6642804/output.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment]
Since it's a script option you need `script-opts=ytdl_hook-ytdl_path=...`

**Comment by github-account1111** [comment]
Thanks! Follow-up question: how was it still opening the video before even though it couldn't find youtube-dl?

**Comment by hooke007** [comment]
But u were using ytdl.
`[   0.568][d][global] config path: 'youtube-dl.exe' -/-> 'O:/bin/mpv/portable_config/youtube-dl.exe'`

**Comment by github-account1111** [comment]
@hooke007 I think you're right haha. I think it was a youtube-dl from my base conda environment. Forgot I had it there. It's weird though, it's not an exe and it's definitely not in my `portable_config` directory.
