### ISSUE TITLE
Getting the currently running mpv process executable path in lua?

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#8918]
I need to run another instance of mpv within a lua script, instead of supplying the script with a static path, it would be useful to know the path of the currently running mpv process.

**Comment by avih** [comment]
> I need to run another instance of mpv within a lua script, instead of supplying the script with a static path, it would be useful to know the path of the currently running mpv process.

mpv doesn't have this value, and also it might not be called `mpv` (if the user renamed it or for whatever reason). It does have `argv[0]` which is usually how it was invoked but it's not exposed to scripts. Also, it could be relative or a symlink, and also it can be wrong - it's not a problem to call program `foo` which gets an `argv[0]` of `bar`.

However, you can get the process id with `utils.getpid()`, and at least on linux you can get `argv[0]` using this command - which you can execute from lua and capture its output:
```sh
sh -c 'cat /proc/$pid/cmdline | tr \\0 \\n | head -1'
```

**Comment by guidocella** [comment]
On Linux you can also use `/proc/self/cmdline` without getting the PID.

**Comment by avih** [comment]
> On Linux you can also use `/proc/self/cmdline` without getting the PID.

Right, but it's delimited with `\0`, so either you read the file yourself from an mpv script and process it yourself, or you run a `sh` line to process it and use an explicit pid value (because `/proc/self` would be `sh`).

**Comment by guidocella** [comment]
> Right, but it's delimited with `\0`, so either you read the file yourself from an mpv script and process it yourself, or you run a `sh` line to process it and use an explicit pid value (because `/proc/self` would be `sh`).

Yeah, I just realized that wouldn't work if you fork to sh like you did. :) What I did in a script was read that file from Lua directly. To get the first argument you would need:
```lua
local file = io.open('/proc/self/cmdline')
local contents = file:read('*a')
file:close()
local foo = contents:match('[^%z]*')
```
Note that In Lua 5.2 "Character class %z in patterns is deprecated, as now patterns may contain '\0' as a regular character.", so this doesn't work if you test it from the latest Lua's command line interpreter. If you use LuaJIT you have to use %z, while both %z and \0 should work with Lua 5.2.

**Comment by sfan5** [comment]
No need to make it so complicated, just use `readlink /proc/PID/exe`.
