### ISSUE TITLE
Instantly closing after opening a video through URL

### ISSUE THREAD

**Issue by 5271** [mpv-player/mpv#8923]
I've just downloaded mpv player through source forge link on your website. When I opened it for the first time it worked perfectly fine and I tested it by playing a video from an URL from youtube. It worked for the first time but then it started closing when I tried to open a video through URL again. It works with local videos on my computer. I tried installing it again but it still works the same (only local videos).
When I drop an URL on it the thumbnail shows up in a really low resolution and the after a second or two it closes.
What am I supposed to do?

**Comment by CounterPillow** [comment]
You're supposed to drag and drop an URL on it, not an image thumbnail.

**Comment by 5271** [comment]
It also instantly closes after I drop an URL on it, not the thumbnail.

**Comment by CounterPillow** [comment]
Make sure you have youtube-dl downloaded and placed next to mpv.exe. If it still fails, provide a log file, which you can generate by setting "log-file=C:/some/path/somefilename.log" in your mpv.conf or by passing `--log-file` on the command line.

**Comment by 5271** [comment]
I installed youtube-dl and it works now. I did it before and it didn't work. I guess it's just computer magic. Big thanks tho and sorry for trouble with such a silly problem.
