### ISSUE TITLE
how to display chapter names on hover

### ISSUE THREAD

**Issue by horusra** [mpv-player/mpv#8925]
example link: https://youtu.be/f02mOEt11OQ

When you download a youtube video (with yt-dl) that includes timestamped chapters, the chapters are retained.
However, MPV does not seem to display them in any way, only showing notches to indicate chapter positions.
Is there a way to (like on youtube) display the current chapter + the chapter that you hover on?

![2071](https://user-images.githubusercontent.com/17074394/122494523-d3a3f780-cfe9-11eb-8081-884871977584.jpg)
mpv: no chapter names

![2072](https://user-images.githubusercontent.com/17074394/122495434-52993000-cfea-11eb-84d2-2e383c555482.jpg)
on youtube: current and hover chapter names

**Comment by Akemi** [comment]
shift + i, for the stats view to show the current chapter and more infos.
shift + click the chapter jump icons on the bottom left to show all chapters.

**Comment by avih** [comment]
Also, you could add this to your `mpv.conf` to show the current chapter title at the OSC. Note that it might be cropped if there's not enough room:
```
script-opts-add=osc-title=${media-title}${?chapter-metadata/title: [${chapter-metadata/title}]}
```
This uses property-expansion - https://mpv.io/manual/master/#property-expansion

E.g. if the current title is "My title" and the current chapter is "My chapter", then the title at the OSC would be:
```
My title [My chapter]
```

There's no way currently to display the chapter while hovering the seek bar. But it sounds like a useful feature to have, do if you want to work on that then you can send a pull-request with this functionality.

**Comment by avih** [comment]
For future reference, this has been merged in master 2 months ago - https://github.com/mpv-player/mpv/commit/76b1ac57a4f49ff2c7f18b7e46aefa7fb3362984

**Comment by horusra** [comment]
> 
> 
> > There's no way currently to display the chapter while hovering the seek bar. But it sounds like a useful feature to have
> 
> For future reference, support for this behavior has been added in mpv-master 2 months ago - [76b1ac5](https://github.com/mpv-player/mpv/commit/76b1ac57a4f49ff2c7f18b7e46aefa7fb3362984)

Yes, thank you so much!
![2812- 00 01 600-00 06 633](https://user-images.githubusercontent.com/17074394/135491648-07bb852a-d4d8-4450-a1cd-bec1bbc0542b.gif)

**Comment by avih** [comment]
> Can someone explain me how to enable this?

This is enabled by default and cannot be disabled, but it was added in July - 3 months ago, so your mpv needs to be newer than that.

**Comment by jacob-emery** [comment]
The flatpak updated to v0.34 only a couple days ago, therefore now I can view the chapter names! I didn't bother checking because I assumed that it was already 0.34. My fault...

**Comment by elig0n** [comment]
I run `0.34.0 built on Sun Nov  7 20:16:38 +08 2021` under windows (from chocolatey) yet I do not see it

**Comment by avih** [comment]
> I do not see it.

Most probably the chapter names are empty. Or maybe you're not hovering the mouse over the seekbar, or you're not running the version you think you run.

> This is enabled by default and cannot be disabled

It's still enabled by default, but It's now possible to disable it - this was added after 0.34 - https://mpv.io/manual/master/#on-screen-controller-chapter-fmt
