### ISSUE TITLE
issues with hardwaredecoding of h265

### ISSUE THREAD

**Issue by sans-c** [mpv-player/mpv#8928]
### Important Information
- mpv version:  0.33.0-184-g03b9f8e323
- Windows Version: Windows 10 21H1 and pretty much any earlier version of Windows 10
- Source of the mpv binary: shinchiro builds
- Video card and drivers: Intel HD520, all tested drivers since the issue started, also "known good" drivers that worked before
- affected mpv versions: all tested versions since over a year were affected

### Reproduction steps
Play pretty much any h265-encoded video file, enable hardware acceleration and maybe seek around a bit in the video.

### Expected behavior
Videos should play normally, mpv should stay responsive, in case of driver hiccups at least "recover" and allow for a graceful shutdown.

### Actual behavior
I've observed several outcomes without any clear pattern.
- More often than not mpv just straight up freezes. 
- Sometimes a file can be played for a while without any apparent issue. Trying to seek, switch to fullscreen or resize the window often results in a freeze.
- Sometimes audio continues to play in the background, sometimes not. 
- Sometimes there is is a message in the logs, which reads: `[vo/gpu/d3d11] Failed to create Texture2D`, but that does not always happen!
- Sometimes mpv continues to eat up a whole CPU core while playing dead, sometimes it does not.

Disabling hardware decoding via hotkey doesn't work either in this state. The only way to recover is to kill mpv using some sort of task manager on Windows. Ever since the issues started, I disabled hardware decoding for h265 and then everything just works fine. I know you (used to?) advice against hardware decoding, still there seems to be something at fault and worthy to report. h264, vp9 and everything else I threw at mpv work like a charm with (and without, if not available) hardware acceleration.

### Log file

A log can be found here: [https://bin.disroot.org/?50bb3a475c449723#EZTmcxzHVxEPktE95wZWTMNHx3iiFfTaE7cNTBdMeyXg](https://bin.disroot.org/?50bb3a475c449723#EZTmcxzHVxEPktE95wZWTMNHx3iiFfTaE7cNTBdMeyXg)
Note that I tried to resize the mpv window before killing mpv. This was to show that mpv was still somehow "alive" (producing logs) but not responding to any hotkeys or other mouse actions.

If you need any more information, I'll try to provide them. Thank you!

**Comment by amariami** [comment]
I'm not found (maybe I missed it) a clear Intel explanation about h265 decoding for all their hardware.
[http://wp.xin.at/archives/3561](http://wp.xin.at/archives/3561)

**Comment by FinnRaze** [comment]
It's Intel's fault.Full support of hevc needs Kabylake or after iGPU(HD Graphics 6xx)
Same behavior on Haswell&Broadwell iGPUs.

**Comment by sans-c** [comment]
> It's Intel's fault.Full support of hevc needs Kabylake or after iGPU(HD Graphics 6xx) Same behavior on Haswell&Broadwell iGPUs.

Uhm - what do you mean by "full support". Skylake suppots (should support) 8bit h265 decode and encode according to multiple sources. Intel says it does, Wikipedia says it does and even [ffmpeg's wiki](https://trac.ffmpeg.org/wiki/Hardware/QuickSync) says it does.

At any rate if there is no support, I'd expect mpv (or ffmpeg or whatever puzzle piece is to be blamed) to politely say "no" instead of randomly and inconsistently crash and burn. Do not get me wrong - I do not expect hardware acceleration to be a given and I understand it might be iffy at times. Still I'd prefer mpv to gracefully handle hiccups and/or produce some useful log output and not just die or freeze. If h265 on Skylake and prior is officialy broken, which does not seem to be the case, then maybe remove support entirely.

**Comment by FinnRaze** [comment]
https://mpv.io/manual/stable/#video
> As an example for something that still causes problems: certain combinations of HEVC and Intel chips on Windows tend to cause mpv to crash, most likely due to driver bugs.

**Comment by FinnRaze** [comment]
About 7~8years ago,Intel claimed that its HD graphics could decode HEVC through "hybrid decode".But later they deleted relevant statements on their website.Based on my test with Broadwell/Haswell CPUs,mpv works with DXVA2 on HEVC samples.However,using dxva2 can result in wrong color.

![DXVA2vsCPU](https://user-images.githubusercontent.com/84557113/201798171-91be5e30-9f5b-410a-9fcc-6d39247088e7.jpg)

So my conclusion is that Intel found their "hybrid decode"  was a failure,but they didn't fix their drvier but to fix their website description.

**Comment by garoto** [comment]
> dxva2

No one should be ever using that.

**Comment by FinnRaze** [comment]
Recent discovery.
On Windows8.1,mpv hwdec=d3d11va plays hevc samples without crash. GPU:HD grahics 5500

**Comment by Dudemanguy** [comment]
The OP is a bit old and there's been a lot of hardware decoding changes since then. Feel free to make new issues for anything specific here if they still persist.

**Comment by sans-c** [comment]
> The OP is a bit old and there's been a lot of hardware decoding changes since then. Feel free to make new issues for anything specific here if they still persist.

In a quick test, pretty much nothing changed for me. I tested v0.36.0-50-g67292855, built 3 days ago.

I didn't look into details and cannot confirm every single detail I described earlier, but at first glance, the issues persist more or less unchanged. Shall we just reopen this issue or should I indeed create a new one?
