### ISSUE TITLE
MPV crashes when i try to play age restricted videos from YouTube

### ISSUE THREAD

**Issue by IvanHuylo** [mpv-player/mpv#8930]
MPV doesn't open age restricted videos anymore. I'm using mpv 0.33.0-184-g03b9f8e323 on Windows 10 Pro 20H2.
I just tested, all of the age restricted videos don't work anymore on MPV, the player just starts(it shows even the YouTube URL from the video) and closes with not a single frame being played. To confirm, I am 18 and I have my YouTube age confirmed, but its still a bit concerning that I can't watch age restricted videos on MPV anymore. I would be less worried if I find out that it is an issue either with YouTube or MPV and not an issue on my side.

**Comment by sfan5** [comment]
This would likely be an "issue" (more of a "Google changed it and they can't do anything about it") for youtube-dl but since you entirely ignored the issue template nobody can tell.

**Comment by kikuyan** [comment]
You need to extract cookies from browser and pass cookies to youtube-dl. Be sure to use the latest version.
`mpv --ytdl-raw-options=cookies=cookies-youtube-com.txt https://www.youtube.com/watch?v=XgnwCQzjau8`

**Comment by CounterPillow** [comment]
it's also not a crash, it just fails to play the URL.
