### ISSUE TITLE
HWDEC + Window rotation = Video artifacts 

### ISSUE THREAD

**Issue by horusra** [mpv-player/mpv#8931]
`UP cycle-values video-rotate 90 180 0`

Using this in input.conf
When the window rotates, artifacts appear.
Doesn't happen with webms, but does happen with mp4/mkv

https://user-images.githubusercontent.com/17074394/122657427-c6ab1380-d163-11eb-8a30-af6559d9efc2.mp4

happens with:
```
nvdec-copy
nvdec
d3d11va-copy
d3d11va
```
does not happen with:
`hwdec=cuda`

```
mpv 0.33.0-184-g03b9f8e323 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 13 08:59:12 +08 2021
FFmpeg library versions:
   libavutil       57.0.100
   libavcodec      59.1.101
   libavformat     59.3.100
   libswscale      6.0.100
   libavfilter     8.0.102
   libswresample   4.0.100
FFmpeg version: git-2021-06-12-480f11bd
```
Windows: 10 20H2 Build 19042.1052
[log](https://pastebin.com/D4bTD1eE)

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/8223

**Comment by Dudemanguy** [comment]
Duplicate as stated above.
