### ISSUE TITLE
How do you change parameters/send commands to the lavfi-complex filter graph in runtime or from a script?

### ISSUE THREAD

**Issue by monsoonsheep** [mpv-player/mpv#8935]
So I'm trying to overlay a youtube stream over a movie, and I'm writing a Lua script that binds a certain key to resize the overlay. The problem is that loading the movie using the lavfi "movie" source all in the same --vf filter is kind of janky, and loading the movie this way doesn't give enough control over its stream.

I have to use ```lavfi-complex``` to control and filter the two different stream and mix their audio. The only limitation is that I have to set everything at startup, or change the whole filter graph in one go, which might not load fast. 

Right now, I can control the video overlay after adding the filter
```
'@loader:lavfi="movie=my_movie.mkv [vid2]; [vid1] scale=w=200:h=200:[frame]; 
[vid2][frame] overlay [vo] "' 
```
But this way, I can't load the audio of the movie and mix it with the ```lavfi-complex``` graph's ```amix``` filter, because only the video track was loaded in the first filter.

There's got to be a way to do this by loading a file with ```--external-files``` and sending commands like ```vf-command``` to the lavfi-graph. I couldn't dive deep down into how mpv interfaces with libavfilters but I thought maybe someone would know of a way to do this.

**Comment by Dudemanguy** [comment]
Sorry for the late response and I'm not 100% sure what you're trying to do but for lavfi-complex changes, you have to directly modify the property/option again. So if you're looking to add audio later, you would need to load the track in some way (like `--external-files` followed by an `audio-add` command). Then you would have to reconstruct the lavfi-complex command with the correct track assignments for everything.
