### ISSUE TITLE
Support for letting mouse events pass through the application window

### ISSUE THREAD

**Issue by Igetin** [mpv-player/mpv#8938]
### Expected behavior of the wanted feature

There’s already `--no-input-default-bindings` for ignoring all keyboard & mouse events, but I couldn’t find anything that would allow you to click/scroll/etc. through the mpv window so that the input event would be received by whatever application is **below** the mpv window. `--input-cursor=no` also exists, but this only hides the cursor when it’s over the mpv window.

Use case: I’d like to overlay subtitles for audio-only streams and keep them visible all the time. I can already achieve this pretty nicely with `--no-video --force-window=yes --alpha=yes --background="#00000000" --border=no --ontop=yes --osc=no --window-dragging=no` and setting the window geometry to something fitting. This way subtitles are the only thing that’s visible in the mpv window, and they stay visible on top of other windows, but there’s still the annoyance of having an area where I can’t interact with what’s below the mpv window. I’ve tried to optimize the geometry to keep the window as small as possible, but unfortunately there needs to be a decent amount of width and height for all subtitles to fit, and sometimes there are 4+ lines of text visible at the same time.

I’m using Fedora on Gnome 3.36 (both X11 and Wayland available).

If this functionality is already available in mpv, please point me to the right direction and close the issue. And feel free to tell me if there’s another method to make this work (with or without the use of mpv).

**Comment by Dudemanguy** [comment]
Such a feature would be heavily dependent on the windowing backend. I'm familiar with one (wayland), but I'm fairly certain such a thing is impossible client-side in wayland. We receive mouse events from the compositor and respond to it. mpv has zero knowledge of any other existing windows/surfaces. Perhaps there is some way for the compositor to do it however.

I'm unsure how feasible or not this is on other platforms.

**Comment by Igetin** [comment]
I have very little knowledge on display servers and compositors myself, but I found this thread with possibly helpful info: https://github.com/glfw/glfw/issues/1236. It seems like GLFW has implemented this for X11, Wayland, Windows & macOS.

**Comment by Dudemanguy** [comment]
Oh my mistake. I totally forgot about `set_input_region`. So yeah this is possible in wayland.

**Comment by fusir** [comment]
It is also possible in x11.  

See this pull request to pqiv that implemented it.  https://github.com/phillipberndt/pqiv/pull/131

And they have an article that explains it.  https://mortoray.com/creating-a-local-screen-overlay-for-streaming-obs-linux/

**Comment by Dudemanguy** [comment]
The linked PR implements it in X11 as well. I would need to rebase it but it works fine.

**Comment by Dudemanguy** [comment]
OPs request was implemented by #8949. Technically no windows or mac support (presumably it's possible there; dunno), but OP only asked for linux stuff so I'll close this. Someone can make a new feature request if they desire it.
