### ISSUE TITLE
The mpv binary statically links libmpv

### ISSUE THREAD

**Issue by evelikov** [mpv-player/mpv#8940]
The mpv binary does not make use of it's own shared libmpv library.
In the sense that, although the mpv project is build with `--enable-libmpv-shared`, `/usr/bin/mpv` itself still static links libmpv.

As far as I can tell, this happens on Arch and Debian (sid) at the very least, so it seems distro agnostic.

Fwiw I had a quick look at the waf build system ... yet it's no immediately clear how to fix this.

### Important Information

Provide following Information:
- mpv version - 0.33.1
- Linux Distribution and Version - Archlinux
- Source of the mpv binary - https://archlinux.org/packages/community/x86_64/mpv/

### Reproduction steps

Download the Arch package (or Debian one if you prefer)
`obdump -x /usr/bin/mpv` -> observe the `NEEDED` entries

### Expected behavior

The output of `obdump -x /usr/bin/mpv` lists `libmpv.so`, the executable is notably smaller.

### Actual behavior

`libmpv` is linked statically into `mpv`, despite the `--enable-libmpv-shared` configure toggle.

**Comment by ericonr** [comment]
Probably easier to do if `mpv` ever switches build systems.

**Comment by Dudemanguy** [comment]
Someone can correct me if I'm misunderstanding something here, but I don't think this is really related to build systems at all. The mpv binary doesn't use libmpv in any way. Even the libmpv vo is just mpv sources that are compiled in every build. libmpv itself is just the same mpv sources compiled as a library with some extra headers + exported symbols and so on.

**Comment by CounterPillow** [comment]
Dudemanguy is correct, mpv does not use libmpv at all. mpv *is* libmpv.

Personally, I do not see the point in completely rearchitecturing what the mpv binary is to save a few megs of space on systems that install both.

**Comment by evelikov** [comment]
So the mpv project provides a library, but it does not use it itself? This sounds sounds very unusual - cannot think of any other project that does that. The principle of "dogfooding" comes to mind, wrt ensuring the API exposed it flexible yet robust.

If we are to follow Linus' reasoning, the library should be nuked... which I have no objections against :-P

**Comment by Dudemanguy** [comment]
The main purpose of libmpv is for other applications not mpv itself. The library came well after mpv. Sure it's theoretically possible to rewrite all the core code, but that's a gargantuan task with questionable benefit at best. Anyways, I think we're good here.

**Comment by CounterPillow** [comment]
not to forget that parts of mpv do use the client API (`rg` for `client.h`).

If you have objections to any part of the client API, feel free to raise them in a separate issue. It appears to me though that you are not the type to use libmpv in an application though.

**Comment by evelikov** [comment]
@CounterPillow how does such a "type" look, do I need a new haircut or something :-P

**Comment by ReillyBrogan** [comment]
Could this be re-opened? Now that meson is the only supported build system it looks like it would be much easier to do this.
