### ISSUE TITLE
Autoprofiles and gpu-api

### ISSUE THREAD

**Issue by lavilao** [mpv-player/mpv#8941]
Hi, does the auto-profiles.lua can change the gpu-api? Because I made a few profiles and I wanted to change the api depending on the codec and apply the corresponding preescaler but it does not work, it just shows an error about fbo, so I want to ask, can you put this:
```
profile-desc=cond:p["video-params/w"]>=848 and p["video-params/h"]>=480 and p["estimated-vf-fps"]>=25 and p["video-format"]=="vp9"
glsl-shaders-clr
glsl-shader="~~/shaders/noise_static_luma.hook"
gpu-api=vulkan
gpu-context=waylandvk
fbo-format=rgba16hf
glsl-shader="~~/shaders/ravu-lite-r3.hook"
```
and expect to work or it will never change the api? thanks in advise (sorry for any bad use of language, english is not my lang)

**Comment by hooke007** [comment]
Are u using the deprecated Autoprofiles?
`profile-desc=` is not the essential right now.

**Comment by Doofussy2** [comment]
I don't think it can be set at runtime, and you should be using a profile header, like: `[Set GPU API]` or whatever you want to call it.

**Comment by lavilao** [comment]
@hooke007 Sorry I didnot knew that autoprofiles was deprecated, is the function merged in mpv? and I'm on linux
@Doofussy2 thanks for the corrected profile :) my mpv is mpv-full 0.33.1 from aur.
with the new profiles it still gives error
[output.txt](https://github.com/mpv-player/mpv/files/6702249/output.txt)
these are the new ones 
```
[Set GPU API2]
profile-cond=p["video-params/w"]>=848 and p["video-params/h"]>=480 and p["estimated-vf-fps"]>=25 and p["video-format"]~="vp9"
glsl-shaders-clr
glsl-shader="~~/shaders/noise_static_luma.hook"
gpu-api=opengl
gpu-context=wayland
fbo-format=rgba16f
glsl-shader="~~/shaders/ravu-lite-r3-ogl.hook"

[Set GPU API3]
profile-cond=p["video-params/w"]>=848 and p["video-params/h"]>=480 and p["estimated-vf-fps"]>=25 and p["video-format"]=="vp9"
glsl-shaders-clr
glsl-shader="~~/shaders/noise_static_luma.hook"
gpu-api=vulkan
gpu-context=waylandvk
fbo-format=rgba16hf
glsl-shader="~~/shaders/ravu-lite-r3.hook"

[Set GPU API4]
profile-cond=p["video-params/w"]<848 and p["video-params/h"]<480 and p["estimated-vf-fps"]<25 and p["video-format"]=="vp9"
glsl-shaders-clr
glsl-shader="~~/shaders/noise_static_luma.hook"
gpu-api=vulkan
gpu-context=waylandvk
fbo-format=rgba16hf
glsl-shader="~~/shaders/ravu-lite-r4.hook"
```

**Comment by lavilao** [comment]
oh forgot to paste this one
```
[Set GPU API1]
profile-cond=p["video-params/w"]<848 and p["video-params/h"]<480 and p["estimated-vf-fps"]<25 and p["video-format"]~="vp9"
glsl-shaders-clr
glsl-shader="~~/shaders/noise_static_luma.hook"
gpu-api=vulkan
gpu-context=wayland
fbo-format=rgba16f
glsl-shader="~~/shaders/ravu-lite-r4-ogl.hook"
```

**Comment by hooke007** [comment]
>is the function merged in mpv

To check the history in the commit here.
https://github.com/mpv-player/mpv/tree/master/player/lua
And doc.
https://mpv.io/manual/master/#conditional-auto-profiles

**Comment by lavilao** [comment]
thanks, the manual has changed since the las time I downloaded it

**Comment by Dudemanguy** [comment]
Oh wait a second @lavilao, I think your errors are due to a wayland bug I fixed a while ago (https://github.com/mpv-player/mpv/pull/8776). I don't think there's anything wrong with your autoprofiles. Could you give mpv from git master a try instead of 0.33.1?

**Comment by lavilao** [comment]
installing mpv-full from aur right now, although I had to switch from the integrated to the autoprofiles script due to not working on many videos, lets hope it works now

**Comment by lavilao** [comment]
seems like I wont be able to install it, I installed the chaotic aur version on mpv-git nut it does not even open (no wayland support aparently) and the aur version as the generic git + rebuild -j4 require ffmpeg-git wich I also downloaded from chaotic but it breaks a TON of packages so I will have to wait till the next release. Thanks anyway

**Comment by lavilao** [comment]
0.34.0 update fixes the root of my problem (not beign able to use vulkan due to blue screen libplacebo error) so now that I can use vulkan to everything this issue is fixed
