### ISSUE TITLE
time_remaining function always return true after 805 line

### ISSUE THREAD

**Issue by qarmin** [mpv-player/mpv#8944]
https://github.com/mpv-player/mpv/blob/cbd87ddb93fb300c072344d22d17b4f17c8a0889/player/command.c#L798-L809

after 803 line, `len` is always greater than 0, so `len >= 0` can be replaced with true or maybe `*remaining >= 0` should be used here

**Comment by Dudemanguy** [comment]
`get_time_length` can return MP_NOPTS_VALUE which (I think) is a magic value which is (probably) less than 0. This check is needed.
