### ISSUE TITLE
mpv & glslang-git causes symbol lookup error

### ISSUE THREAD

**Issue by andykais** [mpv-player/mpv#8945]
### Important Information

Provide following Information:
- mpv version: `0.33.0-191-ga17d79907a`
- Linux Distribution and Version: arch linux
- Source of the mpv binary: https://aur.archlinux.org/packages/mpv-git
- If known which version of mpv introduced the problem: no
- Window Manager and version: i3-wm
- GPU driver and version: `Intel(R) HD Graphics 520 (SKL GT2)`
- Possible screenshot or video of visual glitches: n/a

### Reproduction steps
1. on arch linux, install mpv (the issue is present on both [mpv](https://archlinux.org/packages/?name=mpv) and [mpv-git](https://aur.archlinux.org/packages/mpv-git).
2. Install the latest glslang: `yay -S glslang-git` (version: `11.4.0.r47.gb38100f6-1`)
3. mpv no longer functions: `mpv: symbol lookup error: /usr/lib/libshaderc_shared.so.1: undefined symbol: _ZN8spvtools9Optimizer18RegisterSizePassesEv`

### Expected behavior
mpv runs without issue. 

### Actual behavior
no mpv command can be run. Only the above error is displayed.

### Log file
N/A. Mpv crashes before a log file can be produced.

### Sample files
N/A

### Additional info
mpv works fine using the stable version of glslang (`11.4.0-1`). The necessity of `glslang-git` is that it is required to install either `mpv-git` or `ffmpeg-git`

**Comment by sfan5** [comment]
If you replace a dependency of `shaderc` (here: `glslang`) with a newer, incompatible version you will have to rebuild `shaderc` too or you end up with symbol lookup errors.
This is nothing to do with mpv.

**Comment by andykais** [comment]
Im not sure the fix is as simple as that

#### rebuilding mpv
- `yay -S glslang-git`
- `yay -S mpv-git`
results in:
```
[278/506] Linking build/mpv
[279/506] Compiling osdep/terminal-unix.c
[280/506] Compiling osdep/polldev.c
[281/506] Compiling video/vdpau.c
[282/506] Compiling audio/filter/af_drop.c
[283/506] Compiling audio/decode/ad_lavc.c
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../lib/libplacebo.so: undefined reference to symbol '_ZN7glslang7TShader10getInfoLogEv'
/usr/bin/ld: /usr/lib/libglslang.so.11: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/andrew/.cache/yay/mpv-git/src/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
==> ERROR: A failure occurred in build().
    Aborting...
```

#### rebuilding shaderc
- `yay -S glslang-git`
- `pacman -S shaderc`
after the above steps, running mpv still results in:
```
mpv: symbol lookup error: /usr/lib/libshaderc_shared.so.1: undefined symbol: _ZN8spvtools9Optimizer18RegisterSizePassesEv
```

**Comment by sfan5** [comment]
> `libplacebo.so: undefined reference to symbol '_ZN7glslang7TShader10getInfoLogEv'`

rebuild that too

**Comment by andykais** [comment]
- `yay -S glslang-git`
- `pacman -S shaderc libplacebo`
- yay -S mpv-git`

seeing the same
```
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../lib/libplacebo.so: undefined reference to symbol '_ZN7glslang7TShader10getInfoLogEv'
/usr/bin/ld: /usr/lib/libglslang.so.11: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
error while building mpv-git. Perhaps I need to also install `shaderc-git` and/or `libplacebo-git`

**Comment by andykais** [comment]
ok that did the trick! Here are the steps I needed to perform:
- `yay -S glslang-git`
- `yay -S shaderc-git libplacebo-git`
- `yay -S mpv-git`

mpv now works correctly

**Comment by ramis-svitla** [comment]
For me this is because chrome provides a broken copy of vulkan which is loaded while it tries to execute mpv. The fix is to make a little wrapper at `/usr/local/bin/mpv` that preloads the system version of vulkan:
`#!/bin/sh
export LD_PRELOAD=/usr/lib/libvulkan.so.1
exec /usr/bin/mpv "$@"`
