### ISSUE TITLE
Got a "[vo/gpu] icc-profile-auto not implemented on this platform." warning.

### ISSUE THREAD

**Issue by JerryZhongJ** [mpv-player/mpv#8947]
## mpv version
```
pv 0.33.1-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4

```
## Linux Distribution and Version
Manjaro Linux x86_64
## Source of the mpv binary
Manjaro Official Repository
## Window Manager and version
KDE Plasma(Wayland)
## GPU driver and version
i915

### Reproduction steps
just open mpv from shell

### Log file
https://0x0.st/-9ET.txt

**Comment by CounterPillow** [comment]
Wayland can't do colour space stuff at the moment; clients are blissfully unaware of the icc profile of the monitor, or even what monitor they're on. Not an mpv bug, but a wayland limitation in the name of "security".

**Comment by JerryZhongJ** [comment]
> Wayland can't do colour space stuff at the moment; clients are blissfully unaware of the icc profile of the monitor, or even what monitor they're on. Not an mpv bug, but a wayland limitation in the name of "security".

Then how can i set icc-profile manually and properly ?

**Comment by CounterPillow** [comment]
`--icc-profile=path-to-your-profile.icc`

**Comment by Dudemanguy** [comment]
>even what monitor they're on

Hey, wayland clients can do that at least. But yeah don't expect any color management stuff anytime soon. It's a work in progress™.
