### ISSUE TITLE
Show output resolution in the overlay

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#8953]
It would be extremely handy if mpv showed the output resolution in the `I` overlay.

Right now only the stream resolution is being shown.

**Comment by avih** [comment]
Assuming "output resolution" is the window size, you can add this to your `input.conf`:
```
alt+i show-text "${osd-width}x${osd-height}"
```

If your use case is more complex, for instance pan-and-scan is used, and/or margins, and/or zoom etc (where "output resolution" is much less well defined), then you can find more values at the property `osd-dimensions` - https://mpv.io/manual/master/#command-interface-osd-dimensions .

**Comment by birdie-github** [comment]
As I said I'd like to see it at all times in the `I` onscreen menu. This shortcut will only show it temporarily and lonely.

The direction this bug tracker has taken is not really inspiring.

**Comment by avih** [comment]
> Looks like I have have to read the source and write a patch.

Why won't you first define what "output resolution" is, exactly, especially when the window is not covered entirely by the video?

**Comment by birdie-github** [comment]
I have a 1440p monitor which could run at any resolution, so whenever I make video fullscreen I want to be reminded what my actual monitor resolution is.

`"${osd-width}x${osd-height}"`

Shows 2560x1440 now which is exactly what I want to see.

So, it's `stats.lua` -> `add_file(s)/add_video(s)/add_audio(s)`, I'm fine with `add_video(s)`.

Now I just wonder how to get the output resolution parameters in Lua.

Could be `video-out-params.dwidth` and `video-out-params.dheight`.

**Comment by avih** [comment]
> what my actual monitor resolution is

Well, at the very least that's not how I initially interpreted "output resolution".

For the monitor resolution, you have `display-width` and `display-height` - https://mpv.io/manual/master/#command-interface-display-width

Also, personally I doubt that many would want to see their monitor resolution at the stats display, but that's just me.

So maybe, if you intend to make a pull request, or even here, first define exactly which values you want this thing to display (display resolution, window size, video size if it were not constrained by the window, etc).

**Comment by birdie-github** [comment]
I want to display the resolution of the window mpv is outputting to. This info is very valuable because it allows to also understand whether mpv is performing any operations on the video (e.g. upscaling or downscaling) or just outputting it the way it is.

There are tons of people who watch videos which don't match their output resolution, i.e. I have a 1440p monitor and I prefer to watch 4K videos because they look a lot sharper and show a lot more details than native 1440p videos. Likewise it's nice to know whether videos below my native resolution are being upscaled. That's the reason I started using `scale=ewa_lanczossharp` which looks a ton better than the default mpv upscaler.

**Comment by birdie-github** [comment]
Not to increase the number of lines in the overlay info, you can simply change:

`Native Resolution : Vx x Vy`
to
`Video / Display Resolution: Vx x Vy / Dx x Dy`

**Comment by avih** [comment]
> I want to display the resolution of the window mpv is outputting to

What if it's zoomed out (with black bars) or zoomed in (the video is cropped by the window boundaries), and/or moved vertically or horizontally?

Still only the window resolution in all these cases? if yes, then that's `osd-width` and `osd-height`. If no, then it needs a better definiton.

**Comment by birdie-github** [comment]
> What if it's zoomed out (with black bars) or zoomed in (the video is cropped by the window boundaries), and/or moved vertically or horizontally?

Good catch.

> Still only the window resolution in all these cases? if yes, then that's osd-width and osd-height. If no, then it needs a better definition.

Looks like it, I've just tested playback and `osd-width` and `osd-height` work the way I intended.

**Comment by avih** [comment]
> Good catch.

Only the 3th time I mentioned it. previously:

> especially when the window is not covered exactly by the video?

> display resolution, window size, video size if it was not constrained by the window, etc



> `osd-width` and `osd-height` work the way I intended.

That's good for you, but if we want to make it useful for others too, then we do need to decide what to display in all the cases which are not trivial.

**Comment by Dudemanguy** [comment]
Having a `Output Resolution` line in the stats window (maybe right under `Native Resolution`) sounds reasonable to me. To account for potential cropping, you would just need to add/subtract the margin values in `osd-dimensions`.

**Comment by garoto** [comment]
Somewhere besides the **Window Scale:**  stat perhaps.

**Comment by birdie-github** [comment]
Thank you!

**Comment by netExtra** [comment]
> Having a `Output Resolution` line in the stats window (maybe right under `Native Resolution`) sounds reasonable to me. To account for potential cropping, you would just need to add/subtract the margin values in `osd-dimensions`.

I know this is a dead issue so appologies in advance. But calling it "Output Resolution" is extremely confusing. I literally had to search through Google and Github to understand why my 1920x2160p video played at 1080p resolution had an output resolution of 4k. I get it now and it's obvious "after the fact" but it should have been called something like monitor or display resolution.

**Comment by netExtra** [comment]
> It's exactly "Output resolution" because your output is not limited to "like monitor or display".
> 
> Why was it difficult to understand for you I've no idea. When you resize the mpv window you can instantly see that the output resolution changes. It cannot be more obvious.

What you've just said doesn't scan for two reasons.
1. When you resize an mpv window the Output Resolution doesn't change and nor should it because it's fixed. Didn't you request this?
2. You are conflating "monitor" with "display"  I agree that calling it a monitor output might be too limiting. But a display can be anything that displays the output. So you can make a similar argument for both "output" and "display".

**Comment by Dudemanguy** [comment]
That comment is old and was never actually implemented as described there (we called it `scaled resolution` I think). The current behavior of status is that `Resolution:` will show under the display section with the actual scaled resolution of the the mpv window. There is an `Output Resolution` that will show under certain circumstances if there's a filter or something that alters the scaled resolution further.

**Comment by netExtra** [comment]
> That comment is old and was never actually implemented as described there (we called it `Scaled Resolution` I think). The current behavior of stats is that `Resolution:` will show under the display section with the actual scaled resolution of the the mpv window. There is an `Output Resolution` that will show under certain circumstances if there's a filter or something that alters the scaled resolution further.

Thanks. But on Windows, I do get 'Output Resolution' behaving exactly as described when I set the resolution below the max resolution of the display.  For example setting the OS resolution at 1920x1080 on a 4K display. 'Output Resolution' disappears once the OS resolution matches the display resolution.
