### ISSUE TITLE
Add support for mpv --vo=gpu --gpu-context=drm with --gpu-api=vulkan (Linux).

### ISSUE THREAD

**Issue by Kawasaki443** [mpv-player/mpv#8958]
mpv now only support  --vo=gpu --gpu-context=drm with --gpu-api=opengl, but recently released vulkan 1.2.182 brings two new extentions "VK_EXT_acquire_drm_display" and "VK_EXT_physical_device_drm". So, could it be possible that mpv play video using drm directly with a vulkan backend in the future?

**Comment by Dudemanguy** [comment]
This already exists in master as `displayvk`.  It was added here: #7268.

**Comment by haasn** [comment]
How do those new extensions meaningfully differentiate from `VK_KHR_display`?

**Comment by philipl** [comment]
The acquire extension let's vulkan take an exclusive lock on the display, removing it from visibility via drm to any other programs. This is for VR use-cases to take control of a headset. There is an equivalent extension for x11 that nvidia implements. Of course.

The physical device extension provides more ways to match a drm device to a vulkan device. I may find that useful as the additional patches I'm working on to support vaapi and mode restoration require using the matching drm device and finding it has proven challenging so far.
