### ISSUE TITLE
Change Pitch with Scaletempo2

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#8968]
In MPV v0.33.1, there is now "scaletempo2" audio filter that seemingly achieves better quality than scaletempo or rubberband. Scaletempo has a bug preventing from changing the pitch without altering the speed. Rubberband works but causes audio distortions IMO.

Now, scaletempo2 would look interesting, but it's designed to "Scales audio tempo without altering pitch". Would there be a way to extend it to allow shifting the pitch without altering audio tempo?

**Comment by cyph84** [comment]
This would be a great feature for https://github.com/marcan/blitzloop

**Comment by cyph84** [comment]
Does an algorithm that subjectively "sounds better" when time-stretching also translate to "sounding better" when used for pitch shifting?

From my unscientific sampling of karaoke friends, all seem to prefer Soundtouch over rubberband. Also, rubberband eats up an entire core on a RPI 2 when increasing pitch.

**Comment by mysteryx93** [comment]
I prefer soundtouch over rubberband. Rubberband is inconsistent, alters bass, and causes artefacts with some audios.

**Comment by mysteryx93** [comment]
There are now many methods to change speed in MPV; and still no feature to change pitch without altering speed besides Rubberband (that doesn't produce good output for all types of audios).

I found that changing pitch with [BASS audio](https://www.un4seen.com/) gives better quality than the algorithm used in scaletempo. The licensing terms of BASS however won't be suitable for this project.

That's wishful thinking, but I'd love to be able to shift pitch in MPV with the same algorithm that BASS is using.

**Comment by kokoko3k** [comment]
Also check the workaround posted here, it works with scaletempo:
https://github.com/mpv-player/mpv/issues/9544

**Comment by mysteryx93** [comment]
ah good to know it's actually possible to make it work!

**Comment by kasper93** [comment]
Fixed by #11214
