### ISSUE TITLE
man mpv grotty error

### ISSUE THREAD

**Issue by shinokada** [mpv-player/mpv#8979]
### Important Information

Provide following Information:
- mpv version: 0.33.1
- macOS Version: 11.4
- Source of the mpv binary or bundle: brew install mpv
- If known which version of mpv introduced the problem: unknown
- Possible screenshot or video of visual glitches

![image](https://user-images.githubusercontent.com/147320/124342926-a5860080-dc02-11eb-947d-9f8d2c2698b1.png)

### Reproduction steps

Run `man mpv`.

### Expected behavior

Shows man page.

### Actual behavior

```
:grotty:<standard input> (/opt/homebrew/share/man/man1/mpv.1):6917: character above first line discarded
grotty:<standard input> (/opt/homebrew/share/man/man1/mpv.1):6921: character above first line discarded
grotty:<standard input> (/opt/homebrew/share/man/man1/mpv.1):6925: character above first line discarded
grotty:<standard input> (/opt/homebrew/share/man/man1/mpv.1):7905: character above first line discarded
grotty:<standard input> (/opt/homebrew/share/man/man1/mpv.1):7909: character above first line discarded
grotty:<standard input> (/opt/homebrew/share/man/man1/mpv.1):7913: character above first line discarded
```

**Comment by CounterPillow** [comment]
How exactly would this be a problem with mpv?

**Comment by mlindner** [comment]
I've always had this problem as well. It's only with mpv man pages.

**Comment by shinokada** [comment]
I wonder it is because I installed it with `brew install mpv`. 
Why mpv has two ways to install it.

```
brew install mpv
brew install --cask mpv
```

**Comment by stolendata** [comment]
> I wonder it is because I installed it with `brew install mpv`.
> Why mpv has two ways to install it.
> 
> ```
> brew install mpv
> brew install --cask mpv
> ```

The first method will in this case compile mpv from source code. The second method ("installing from cask") will download a pre-built application. Casks may differ from "core" versions.

**Comment by Dudemanguy** [comment]
Appears to be a packaging issue not an mpv bug.

**Comment by stolendata** [comment]
> Appears to be a packaging issue not an mpv bug.

I'm not entirely sure. In my particular package (which is provided as the Homebrew mpv cask) I include the generated man page file as-is, without any modifications.
