### ISSUE TITLE
Do all the options have no effect when using encoding mode ?

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#8980]
No specific description about this in the manual so I am confused.
And from the output it seems all the options in mpv.conf didn't affect the output.

For example, `vf=fps=50` in the conf file and output is still 24fps (the same with the source)
Only use `mpv --vf=fps=50 --o=outputv.mkv 1280x720.mp4 --log-file=encoding.log` can change the output's fps.

So, I want to confirm if the mpv.conf file has totally no inflence when using the encoding mode.

### Log file
with the command `--vf=fps=50`
[encoding.log](https://github.com/mpv-player/mpv/files/6759546/encoding.log)

**Comment by garoto** [comment]
I guess you want this: https://github.com/mpv-player/mpv/blob/master/etc/encoding-profiles.conf

**Comment by hooke007** [comment]
From the log I have known that mpv will search for that file and the options in `encoding-profiles.conf` will both affect playback and encoding. (It's weird, should it only be read when using encoding mode?)
I just wonder if the options in `mpv.conf` have influence on the process of transcoding.

**Comment by garoto** [comment]
> [...] the options in encoding-profiles.conf will both affect playback and encoding

Doesn't seem to affect playback at all on my setup at all when explicitly invoking one of the profiles present in `encoding-profiles.conf`.

**Comment by hooke007** [comment]
>when explicitly invoking one of the profiles present in `encoding-profiles.conf`

That's true. I mean the options I write.

**Comment by Dudemanguy** [comment]
By no means am I an expert on the encoding code, but it does appear to use its own separate struct for everything which I assume has no access to the global mpv options. So I think the answer is most likely yes, but I'm not 100% sure.

**Comment by Dudemanguy** [comment]
The answer is probably "yes they have no effect" as noted.
