### ISSUE TITLE
anyway to use -vf toggles set in mpv.conf after using vf set "" keybind?

### ISSUE THREAD

**Issue by junguler** [mpv-player/mpv#8982]
hello, i have a somewhat large collection of -vf toggles i have set in my mpv.conf and always testing new filters with the mpv-live-filters script. 
my question is if there is a way to keep using those toggles after i used the vf set "" keybind?
it's easier to clear everything and start again and i like to have the option to do so without needing to close mpv itself which is possible with the script but not for vf toggles i set in mpv.conf.

[log file](https://github.com/mpv-player/mpv/files/6759883/output.txt)

**Comment by junguler** [comment]
i ended up removing the -vf toggles from mpv.conf and directly used the filters in my input.conf
vf-add=@noisse2:!noise=c0s=5:c0f=t #(in mpv.conf) and a vf toggle @noisse2 #(in input.conf)
became
a vf toggle noise=c0s=5:c0f=t #(in input.conf)
now vf set "" removes all the filters but i can still toggle a filter on again with the keybind

**Comment by jupiter104** [comment]
> 

Thank you for the solution!
