### ISSUE TITLE
Build with clang 12 failed with find dependencies

### ISSUE THREAD

**Issue by h0tc0d3** [mpv-player/mpv#8983]
Linux 5.13
MPV Version 0.33.1

posix no
posix threads no
C++11 atomic no
iconv no
zlib no

With gcc all  finded.

```bash
export CARCH="x86_64"
export CHOST="x86_64-pc-linux-gnu"
export CC=clang
export CXX=clang++
export LD=ld.lld
export CC_LD=lld
export CXX_LD=lld
export AR=llvm-ar
export NM=llvm-nm
export STRIP=llvm-strip
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export RANLIB=llvm-ranlib
export HOSTCC=clang
export HOSTCXX=clang++
export HOSTAR=llvm-ar
export HOSTLD=ld.lld
export LINK=llvm-link

export CPPFLAGS="-D_FORTIFY_SOURCE=2"
export CFLAGS="-fdiagnostics-color=always -pipe -O2 -march=znver2 -fstack-protector-strong"
export CXXFLAGS="-fdiagnostics-color=always -pipe -O2 -march=znver2 -fstack-protector-strong"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
```

**Comment by CounterPillow** [comment]
where's your build log?

**Comment by h0tc0d3** [comment]
@CounterPillow No log. Configure fails with error:

```
posix no
posix threads no
C++11 atomic no
iconv no
zlib no
```

**Comment by CounterPillow** [comment]
Show us `build/config.log`, like the issue template tells you to.

**Comment by h0tc0d3** [comment]
Sorry, it's lto thin bug. ```CFLAGS="${CFLAGS} -flto=thin" CXXFLAGS="${CXXFLAGS} -flto=thin"```
[config.log](https://github.com/mpv-player/mpv/files/6760766/config.log)

**Comment by CounterPillow** [comment]
```
Checking for program 'ar'
llvm-ar
find program=['ar'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/bin', '/usr/lib/jvm/default/bin', '/usr/bin/site_perl', '/usr/bin/vendor_perl', '/usr/bin/core_perl'] var='AR' -> ['llvm-ar']
```
no, waf correctly picks AR.

> because obj files have llvm ir.

object files contain native code.

`CC=clang LD=ld.lld ./waf configure` works correctly for me. Do a `./waf clean` first.

**Comment by CounterPillow** [comment]
I looked into whether we explicitly set the linker anywhere in our waf build scripts and we don't, I think waf itself just doesn't respect the LD var.

You could try out the meson build system PR https://github.com/mpv-player/mpv/pull/8840 and see if that handles it correctly.
