### ISSUE TITLE
Decrypt video file and play without saving in C#.NET (Windows)

### ISSUE THREAD

**Issue by rahigadiya676** [mpv-player/mpv#8984]
Hello Folks,

I'm trying to embed the MPV player in the **WinForms** project in **.NET 5.0** and able to embed it and can play online and offline MP4 video into the project and following is the thing which i need to implement here : 

1. we got one encryed video which we need to decrypt and play into MPV player without saving it to any local place.
2. I have seen this same functionality in Python where there is a method `demuxer_lavf_o` is performing decrytion and playing video without saving it.
3.I'm not able to figure out how i can do the same in c#.NET (Windows)?

Please give me your suggestion so i can achieve the same in .NET also.

Thanks,
Rahi Jain

**Comment by Dudemanguy** [comment]
I think it's safe to say this is well out of the scope of mpv. In theory you could do something clever with ffmpeg I suppose (not sure where .NET comes into play though).
