### ISSUE TITLE
No more audio after playing 00:42:40 of remote vimeo video : [timeline] Too many packets in the demuxer packet queues

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#8986]
### Important Information

Provide following Information:
- mpv version : **0.33.0~bionic3**
- Linux Distribution and Version : **XUbuntu 18.04 LTS**
- Source of the mpv binary : **Launchpad ppa:mc3man/mpv-tests**
- If known which version of mpv introduced the problem
- Window Manager and version : **Kwin v5.12.9**
- GPU driver and version : **radeon for Linux kernel 4.15.0-147-generic**

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

**Comment by Dudemanguy** [comment]
I don't think this is actionable given how little information there is.
