### ISSUE TITLE
segfault with --vo=vaapi on Ubuntu wayland session 

### ISSUE THREAD

**Issue by ambicapramod** [mpv-player/mpv#8987]
### Important Information

Provide following Information:
- mpv version
_hustler@heart:~/Videos$ mpv -version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.4-1ubuntu0.1_

- Linux Distribution and Version
Ubuntu 20.04 with wayland session , kernel v5.8
- Window Manager and version
Wayland
- GPU driver and version
i915 
Device: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (0x3e9b)
Mesa 20.2.6

### Reproduction steps

mpv --vo=vaapi clip.mp4

### Expected behavior
Play video with no issue
### Actual behavior
segfault 
### Log file

https://pastebin.com/igtGfdeE

The issue will be closed for ignoring the issue template.

### Sample files
H264 sample video 
http://www.dvdloc8.com/clip.php?movieid=13599&clipid=4

**Comment by Dudemanguy** [comment]
`vo=vaapi` actually requires xorg. If you are looking for hardware decoding (most likely), you shouldn't be passing the vo option but simply `--hwdec=auto` or `--hwdec=vaapi`. That said, this certainly shouldn't segfault. For me, there's just a fatal error and mpv doesn't start. I'm not sure if that's correct or not since I kind of expected xwayland to start but it's probably that's just a `vo=vaapi` quirk. 0.32 is kind of old though.

**Comment by CounterPillow** [comment]
> mpv 0.32.0

out of date and vulnerable to security issues, as expected of Ubuntu

> segfault

post gdb backtrace please:

```
gdb mpv
(gdb) run --vo=vaapi file.mp4
[...]
(gdb) bt full
```

Also, agreeing with what Dudemanguy said, you should not be using the vaapi VO anyway, but if it segfaults it's still worth looking into.

**Comment by ambicapramod** [comment]
@Dudemanguy I just built latest 0.33.1 and able to reproduce the same.

@CounterPillow  Here is the gdb bt 

https://pastebin.com/pTbvrbT0

**Comment by CounterPillow** [comment]
```
#1  0x00007ffff52ddd7c in va_dri_get_drawable () at /opt/intel/mediasdk/lib64/libva-x11.so.2
#2  0x00007fffca0ff1a8 in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#3  0x00007fffca0e98d7 in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
```
I suspect you have some weird intel media SDK thing installed instead of your distributions intel vaapi implementation. The crash happens within said SDK, so it's unlikely to be an mpv issue.

**Comment by LaserEyess** [comment]
This is indeed the same bug and I can reproduce it 100%. The fix intel did did not work, I'll follow up with them about it. However, this is not an mpv bug so it can be closed.
