### ISSUE TITLE
Folder-based auto profile

### ISSUE THREAD

**Issue by Galathorne** [mpv-player/mpv#8992]
Hi

Besides trial and error by copying examples, I have zero experience with programming/scripting. That said, I finally have an mpv.conf file with glsl shaders working just the way I want when watching anime, with the results just perfect for my taste. For reference, I am on Windows 10 and these are my chosen shaders as I have them in my mpv.conf: `glsl-shaders="~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_Upscale_DTD_x2.glsl;~~/shaders/Anime4K_RA_CNN_M.glsl;~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl"`

Now I need them applied only when watching Anime, as live action movies and series kinda suck with them applied. I suppose auto-profile loading is the answer, but I cannot find a working solution for my setup. As all my anime is stored either directly or in different levels of subfolders under `D:\Anime`, I suppose I have to use a profile and specify that only files in any subfolder under this parent folder should use glsl shaders. The closest to an answer that I could find is this example: `https://github.com/po5/mpv-config/blob/master/mpv.conf`, at lines 188-194. Lines 228-241 does have some filename filters which applies to my anime, but using the first two lines of each (starting with `profile-`), removing the `sub-` option I dont need and adding my `glsl-shaders...` line for some reason doesn't work. But with my knowledge and understanding of scripting, this could just as well be Greek to me, so I really have no idea what I am doing. I would defintely want to have them applied based on their path (containing the word `Anime`) rather than based on some matching part of their filenames, as I believe that this would be the only sure way to future-proof any new or random anime that would not otherwise conform. 

Can anyone kindly assist with the exact lines of text I should add to my own mpv.conf file?

**Comment by guidocella** [comment]
```
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('Anime') ~= nil
```

This concatenates the working directory and the path you pass to mpv so it works with both a relative path, like if your current directory is `D:\Anime\series` and you do `mpv 1.mp4`, or with an absolute path like `mpv D:\Anime\series\1.mp4`

**Comment by Galathorne** [comment]
Thanks @guidocella, I appreciate it. I have tested it and unfortunately the problem persists, where the shaders are still being applied to media even outside of the Anime folder.

I attach my mpv.conf with a txt extension for uploding purposes. 
[mpv.conf.txt](https://github.com/mpv-player/mpv/files/6782454/mpv.conf.txt)

Some screenshots below. Check the popup hint above the folder preview each time to confirm the current file's folder. The anime is shaded nicely, but the live action video is visibly "oilified" with a very unnatural look. In other places textures especially like clothes and hair are also badly affected, but these should suffice. Either way, the info on the screenshots should be proof enough. Any ideas?

![Shaders on anime](https://user-images.githubusercontent.com/87099108/124878663-a20cc380-dfcc-11eb-9e42-355190ffbc03.jpg)
![Shaders on anime (info visible)](https://user-images.githubusercontent.com/87099108/124878702-b224a300-dfcc-11eb-9157-b4773cf79259.jpg)
![Shaders on normal media](https://user-images.githubusercontent.com/87099108/124878723-b8b31a80-dfcc-11eb-8706-a367becf9471.jpg)
![Shaders on normal media (info visible)](https://user-images.githubusercontent.com/87099108/124878744-bd77ce80-dfcc-11eb-921d-7f3cfcd7da5a.jpg)

FYI: I also noticed that all the examples has the profile name as label in square brackets, but when I add it, it in itself causes the shaders not to be applied all round. Feel free to comment if you know why this would be the case, but either way it does not currently pertain to my main issue.

**Comment by guidocella** [comment]
You do need a profile name in brackets to define profiles or the options will always be applied. Try

```
# Anime4k Shader settings
# In SMPlayer, Preferences > Advanced > Options for MPV must have entry "--config=yes --vo=gpu" (without quotes) for shaders to function!
[Anime4k]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('Anime') ~= nil
glsl-shaders="~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/shaders/Anime4K_Upscale_DTD_x2.glsl;~~/shaders/Anime4K_RA_CNN_M.glsl"
```

**Comment by hooke007** [comment]
To be better.
```
[Anime4k]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('Anime') ~= nil
profile-restore=copy
glsl-shaders="~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/shaders/Anime4K_Upscale_DTD_x2.glsl;~~/shaders/Anime4K_RA_CNN_M.glsl"
```

**Comment by Galathorne** [comment]
Thank you for all the effort guys. I tried both and except for `profile-restore=copy` and my comments which differ, they have the same outcome as far as I can tell. The issue persists...

In the screenshots below you'll first see the shaders won't work when the name in brackets is read. It works again when I comment it out (with a single hash the only difference), as can be seen. @guidocella, I confirmed the shaders are then always applied for files both inside and outside the Anime folder. So for whatever reason, it seems that something is perhaps broken on my end when trying to use a profile name. Or, is there some other indication I should add to tell mpv to correctly read the profile?

I did not mention it before, but I actually use SMPlayer as my main player. While it is updated to the latest version, the mpv version packaged with it is 0.32.0 (latest is apparently 0.33.0) though I doubt this is the issue.

![Shaders on anime not working](https://user-images.githubusercontent.com/87099108/124893609-2b2af700-dfdb-11eb-9c98-16902d8f01bd.jpg)
![Shaders on anime working](https://user-images.githubusercontent.com/87099108/124893721-439b1180-dfdb-11eb-969e-8f4a46784322.jpg)

**Comment by guidocella** [comment]
That is the issue. Conditional profiles were added in mpv 0.33.

**Comment by hooke007** [comment]
not difficult to manual update the mpv core for smplayer, just replace the files in `\smplayer\mpv\`
It seems smplayer also use the shinchiro's build.

**Comment by Galathorne** [comment]
Well, now I like an idiot. I should have checked this right from the start!

Thanks so much @guidocella. I updated mpv inside the SMPlayer folder, confirmed it through native mpv and SMPlayer playback and both works fine for all files.

I appreciate all the help guys. I'm marking this as closed. Cheers!
