### ISSUE TITLE
Certain command which I'm not sure exists.

### ISSUE THREAD

**Issue by Gellyboy** [mpv-player/mpv#8994]
Hi. So I'm trying to figure out a command that resizes the window not locked to an aspect ratio like `--no-keepaspect` but doesn't lock the video to the window borders and cause distortion. Kinda like how you can adjust a browser window and it shows more of what's on the window rather than stretching out the browser.

**Comment by hooke007** [comment]
```
video-unscaled=yes
no-keepaspect-window
```

**Comment by Gellyboy** [comment]
@hooke007 
is there any way to do this but without both sides getting wider
also is there a way to set a hotkey to reset it to default?

**Comment by hooke007** [comment]
>

**Comment by Gellyboy** [comment]
One last one and I think that should do it, but is there any way to make pan have smaller increments? Sometimes I want to be really exact but everything I've tried doesn't seem to work.

**Comment by hooke007** [comment]
>The unit is in fractions of the size of the scaled video (the full size, even if parts of the video are not visible due to panscan or other options).

That's why u cannot make it exact.

Just make it smaller is possible.
```
Alt+left  add video-pan-x  0.001
Alt+right add video-pan-x -0.001
Alt+up    add video-pan-y  0.001
Alt+down  add video-pan-y -0.001
```

**Comment by Gellyboy** [comment]
Thank you
