### ISSUE TITLE
Some ASS subtitles are garbled and not legible

### ISSUE THREAD

**Issue by jiangzhenjerry** [mpv-player/mpv#8997]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20210704-git-f2afae5
- Platform and Version: Windows 10 21H1 Enterprise X64
- Source of the mpv binary: [sourceforge](https://sourceforge.net/projects/mpv-player-windows/files/64bit/)
- **Additional Information: I'm using it on a 15'' 4K laptop, and hence the system DPI scaling is 250%.** (Just saying, I'm not sure if this is relevant.)

### Reproduction steps

I used MPV to play an MKV file with an embedded ASS subtitle. I used MKVtoolnix to extract the ASS subtitle and attached it below, so you can test it out yourself.

### Expected behavior

This is what it looks like in MPC-BE.
![Honeyview_sshot-2](https://user-images.githubusercontent.com/9311082/125146606-817f5f00-e0db-11eb-8781-95d06d4d771e.jpg)

### Actual behavior

This is what it looks like in MPV. Garbled and not legible.
![Honeyview_sshot-1](https://user-images.githubusercontent.com/9311082/125146563-3d8c5a00-e0db-11eb-89a3-b133ed18eeb7.jpg)

### Log file

https://0x0.st/-Oqh.txt

### Sample files

https://0x0.st/-OqF.ass

**Comment by TheAMM** [comment]
```
PlayResX: 384
PlayResY: 288
```
mpv & libass are just scaling the outline and shadow to match the video resolution, as told. [One of the vsfilter compact flags might help](https://mpv.io/manual/master/#options-sub-ass-vsfilter-blur-compat) - otherwise, adjust the script's resolution.

**Comment by jiangzhenjerry** [comment]
Thank you for the explanation. Unfortunately 'sub-ass-vsfilter-blur-compat' makes no difference in this case, regardless of yes or no. I guess I will have to live with an edited external subtitle for the moment.

**Comment by hooke007** [comment]
In this situation, try the option `sub-ass-force-style = ScaledBorderAndShadow=no`

**Comment by jiangzhenjerry** [comment]
@hooke007 Yes - this option indeed solves the problem. I have added it to a hotkey. Thanks for the suggestion.  Closed the issue for now.
