### ISSUE TITLE
Drag & drop can not use.

### ISSUE THREAD

**Issue by HillCat** [mpv-player/mpv#9003]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20210711-git-f049acf.7z
- Windows Version: windows10 pro ,64 bit

### Sample files
please see the video:[https://youtu.be/iVKAmJ9tX7o](https://youtu.be/iVKAmJ9tX7o)

all the setting files uploaded to google drive ,you can download :[https://drive.google.com/drive/folders/1e-2OUnDpY5y5v1XCAHN99gc0MEXXfC0z?usp=sharing](https://drive.google.com/drive/folders/1e-2OUnDpY5y5v1XCAHN99gc0MEXXfC0z?usp=sharing)

**Comment by snylonue** [comment]
> Do not use garbage like "cloud storage", especially not Google Drive.

and where's your log

**Comment by snylonue** [comment]
It seems you run mpv as Administrator

**Comment by HillCat** [comment]
Is there any explanation? Since I install the mvp player , I had never been seem the drop function work right.

**Comment by LaserEyess** [comment]
Don't run mpv as administrator, you can't drag and drop as a regular user to a program with administrative rights. It's a security issue. This is not an mpv issue. 

https://social.technet.microsoft.com/Forums/windows/en-US/cba0e9b1-25f8-40e5-a888-1435d604f68d/quotrun-as-administratorquot-prevents-drag-and-drop-working
