### ISSUE TITLE
How to handle the blank(space) of the directory in `input.conf`

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9006]
Unluckily, it's impossible to use the paths of mpv ( such as `~~/` ) for the lavfi filters.
When I used the Absolute path and I met with this problem.

Firstly, I set `vf=lut3d=file="D:/ad ad/3dlut.cube"` in `mpv.conf` and it worked.
But when I tried `CTRL+1 vf toggle lut3d=file="D:/ad ad/3dlut.cube"` in `input.conf` , it seemed parameter was divided by the blank.

![Snipaste_2021-07-13_19-01-14](https://user-images.githubusercontent.com/41094733/125440978-90364bc9-9c14-4a51-8a1e-79d30dc48222.jpg)
So, how could I change its format to avoid the problem?

### Log file
[vf.log](https://github.com/mpv-player/mpv/files/6808332/vf.log)

**Comment by guidocella** [comment]
`CTRL+1 vf toggle "lut3d=file=D:/ad ad/3dlut.cube"` should work.

**Comment by hooke007** [comment]
> `CTRL+1 vf toggle "lut3d=file=D:/ad ad/3dlut.cube"` should work.

I tried before, but `D` will be ignored in that situation.

**Comment by hooke007** [comment]
Well, with the help of custom and double quoted, it solved :-)
```
CTRL+1 vf toggle !^lut3d=file="D:/ad ad/3dlut.cube":interp=trilinear^!
```

**Comment by avih** [comment]
> `CTRL+1 vf toggle !^lut3d=file="D:/ad ad/3dlut.cube":interp=trilinear^!`

Hmm.. in this case, shouldn't this work too?
```
CTRL+1 vf toggle "lut3d=file=\"D:/ad ad/3dlut.cube\":interp=trilinear"
```

**Comment by hooke007** [comment]
>CTRL+1 vf toggle "lut3d=file=\"D:/ad ad/3dlut.cube\":interp=trilinear"

Thanks. Useful, too.
If making `~~/` possible, it would be better...

**Comment by garoto** [comment]
[**@hooke007**](https://github.com/hooke007) commented on [Jul 13, 2021, 9:26 AM GMT-3](https://github.com/mpv-player/mpv/issues/9006#issuecomment-879043502 "2021-07-13T12:26:24Z - Replied by Github Reply Comments"):
> Well, with the help of custom and double quoted, it solved :-)
> 
> ```
> CTRL+1 vf toggle !^lut3d=file="D:/ad ad/3dlut.cube":interp=trilinear^!
> ```

Any explanation where does this exclamation point+caret "escaping" syntax comes from? Never seen this before, looks so bizarre.

**Comment by hooke007** [comment]
> Any explanation where does this exclamation point+caret "escaping" syntax comes from?

https://mpv.io/manual/master/#command-interface-any-unicode

Below.
