### ISSUE TITLE
--loop X in combination with --start and --stop

### ISSUE THREAD

**Issue by thomai-d** [mpv-player/mpv#9010]
### Important Information

Provide following Information:
- mpv version 0.32.0 (0.33.0 does not work because of #8433)
- Ubuntu 20.04.2

### Reproduction steps

```
mpv --start=5 --end=6 --loop=2 --no-config video.mp4 
```

### Expected behavior

The video should play from second 5 to second 6.
The video should play from second 5 to second 6 for a second time.

### Actual behavior

The video plays from second 5 to second 6.
The video plays from second 0 to the end.

### Related

In #7108, it is recommended to use loop-ab, but this won't help here, since loop-ab also ignores the `--loop=N` count.

**Comment by guidocella** [comment]
Use ` --start=5 --ab-loop-a=5 --end=6 --ab-loop-b=6 --ab-loop-count=1`

**Comment by Dudemanguy** [comment]
It was answered.

**Comment by mmoya** [comment]
Reviving this, @guidocella's answer doesn't work for me:

```
$ mpv --version
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100 (runtime 57.28.100)
   libavcodec      59.18.100 (runtime 59.37.100)
   libavformat     59.16.100 (runtime 59.27.100)
   libswscale      6.4.100 (runtime 6.7.100)
   libavfilter     8.24.100 (runtime 8.44.100)
   libswresample   4.3.100 (runtime 4.7.100)
FFmpeg version: n5.1.2

$ grep -E ^ID /etc/os-release 
ID=arch
```

In my case it's from some start to the end. With the following command line:

```
mpv --start=02:00 --ab-loop-a=02:00 --ab-loop-count=inf $URL
```

I get same behavior as OP's.

Also:

- `--start` + `--ab-loop-a` + `--ab-loop-count` + `--loop` doesn't work
- `--start` + `--ab-loop-a` + `--loop` doesn't work
