### ISSUE TITLE
Don't Have MPV folder On Appdata as the manual

### ISSUE THREAD

**Issue by Arghadatta** [mpv-player/mpv#9011]
### Important Information

Provide following Information:
- Latest
- Windows 7 Ultimate SP1
- Windows Build by Shincero
- Now
- Possible screenshot or video of visual glitch

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

I have read the manual and now i can't find the mpv folder in appdata.. 

But i have seen mpv folder in my extracted directory.

**Comment by Arghadatta** [comment]
Please Help Me!!

**Comment by CounterPillow** [comment]
create it

**Comment by hooke007** [comment]
create manually +1

>But i have seen mpv folder in my extracted directory.

```
A third config directory with the lowest priority is the directory named mpv in the same directory as mpv.exe.
This used to be the directory with the highest priority, but is now discouraged to use and might be removed in the future.
```

**Comment by Arghadatta** [comment]
> create manually +1
> 
> > But i have seen mpv folder in my extracted directory.
> 
> ```
> A third config directory with the lowest priority is the directory named mpv in the same directory as mpv.exe.
> This used to be the directory with the highest priority, but is now discouraged to use and might be removed in the future.
> ```

So i should create only mpv folder
Or make fonts and scripts folder inside of mpv folder and put all my. conf files and scripts in them..
Kindly reply me

**Comment by hooke007** [comment]
Of course u should put the files u need into the config folder.
https://mpv.io/manual/master/#files-on-windows
And as recommendation, just use `%APPDATA%/mpv/` or `portable_config` to be the only config folder.

**Comment by Arghadatta** [comment]
> Of course u should put the files u need into the config folder.
> https://mpv.io/manual/master/#files-on-windows
> And as recommendation, just use `%APPDATA%/mpv/` or `portable_config` to be the only config folder.

Then can i use portable config in my extracted mpv folder instead of appdata mpv folder

**Comment by hooke007** [comment]
![Snipaste_2021-07-16_16-08-05](https://user-images.githubusercontent.com/41094733/125914561-23342cab-38fc-444b-b0f7-b34d981ba92f.jpg)
yes, and I think u dont read the link carefully...

**Comment by Arghadatta** [comment]
> ![Snipaste_2021-07-16_16-08-05](https://user-images.githubusercontent.com/41094733/125914561-23342cab-38fc-444b-b0f7-b34d981ba92f.jpg)
> yes, and I think u dont read the link carefully...

And the scripts??

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#script-location

**Comment by Arghadatta** [comment]
> https://mpv.io/manual/master/#script-location
> portable_config/scripts/

Thanks for helping
