### ISSUE TITLE
Exclude certain subfolders in a folder-based auto profile

### ISSUE THREAD

**Issue by Galathorne** [mpv-player/mpv#9017]
Hi

I recently got excellent assistance from the community (https://github.com/mpv-player/mpv/issues/8992).

Continuing somewhat on the topic, I want to know how I can ignore certain subfolders when using a folder-based auto profile. I currently have this in my mpv.conf file:
`[Anime4k]`
`profile-cond=require 'mp.utils'.join_path(working_directory, path):match('Anime') ~= nil`
`profile-restore=copy`
`glsl-shaders="~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/shaders/Anime4K_Upscale_DTD_x2.glsl;~~/shaders/Anime4K_RA_CNN_M.glsl"`

So all files located anywhere within my Anime folder get the perfect shader treatment. Now, how do I ignore files (in my case) under the `Anime\One Piece` subfolder? I can simply create another folder named `Anime (Non-shaded)` and move all Anime I don't want shaded into subfolders under there, but if I can do it neatly within mpv.conf, I'd really be happy. My logic says I need to create another auto profile, but my skills lack severely...

**Comment by guidocella** [comment]
```
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('\Anime\') ~= nil and require 'mp.utils'.join_path(working_directory, path):match('\One Piece\') == nil
```

I also added slashes so it matches only directories and not filenames like Anime_1.mp4. If you don't care about that, you can use the shorter

```
profile-cond=(working_directory .. path):match('Anime') ~= nil
```

**Comment by Galathorne** [comment]
Great, thanks!

If I ever need more folders excluded, which part of that line would I add (replacing '\One Piece\' with '\Whatever\'? If you could put the whole line with the added "Whatever" part in bold I would really appreciate it as it would help me understand the syntax a bit better and also keep me from making mistakes or flooding the forum 😅

I don't currently see the need arising for many such folders, but even so, would it be fine to continue adding another part per folder for many potential exclusions?

**Comment by guidocella** [comment]
```
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('\Anime\') ~= nil and require 'mp.utils'.join_path(working_directory, path):match('\One Piece\') == nil and require 'mp.utils'.join_path(working_directory, path):match('\Whatever\') == nil
```

Add as many as you want.

**Comment by Galathorne** [comment]
Fantastic, thanks for the assist.

**Comment by Dudemanguy** [comment]
Seems like the question was answered.
