### ISSUE TITLE
Seek changes audio play state without changing UI or video play state

### ISSUE THREAD

**Issue by robbie01** [mpv-player/mpv#9018]
### Important Information

Provide following Information:
- mpv version
0.33.0-228-g1e90ec647c
- Windows Version
Windows 11 Home 21H2, build 22000.51
- Source of the mpv binary
updater.ps1
- If known which version of mpv introduced the problem
sometime after 2020-11-22

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

The issue persists with --no-config.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

- Launch MPV
- Drag and drop a video file into the player
- Play for a couple of seconds, but less than 5
- Pause
- Seek backwards using i.e. the left arrow key

### Expected behavior
The playhead should be at zero, and the video should be paused.
### Actual behavior
The playhead returns to zero, but the audio keeps playing. Furthermore, the UI still believes that the video is paused and takes two clicks of the pause/play button or two taps of the spacebar to return to the paused state. After the first user-triggered state change, the playhead seeks to where the audio is and takes the video along with it. Upon the second, it returns to a full pause.

(this appears to happen after running `seek 0 absolute`, too)
### Log file

http://0x0.st/-VAb.txt

### Sample files
Seems to happen with all videos I throw at it.

**Comment by sfan5** [comment]
Already fixed, get a newer build.
