### ISSUE TITLE
HDR Tonemapping: incorrect colors

### ISSUE THREAD

**Issue by horusra** [mpv-player/mpv#9019]
### Important Information

latest MPV version
Windows 10 20H2

### Sample files

https://www.avsforum.com/threads/hdr10-test-patterns-set.2943380/
https://disk.yandex.ru/d/RPrX2C7l3HEjPq/09.%20Test%20Footage/02.%20HDR%20photo
![image](https://user-images.githubusercontent.com/17074394/126092322-443d13e9-6b9b-4fdc-9d0a-610e9889802a.png)

## HDR footage is not properly tonemapped, so the colors do not match reference (while HDR is properly tonemapped using MPC-HC & madVR)
![image](https://user-images.githubusercontent.com/17074394/126092188-ca89a4b5-32ec-4934-9cda-821bce899ff6.png)

**Comment by Doofussy2** [comment]
You haven't followed the template. You haven't provided any usable information, no log, no description...

**Comment by horusra** [comment]
> 
> 
> You haven't followed the template. You haven't provided any usable information, no log, no description...

but this is not something that would show up in the log or anything
I have provided the example files so people can reproduce

**Comment by hooke007** [comment]
The information is not enough.
I cannot reproduce, and from the sample —— your sdr color is incorrect too.

sdr
![sdr](https://user-images.githubusercontent.com/41094733/126108872-92732e75-f7fc-4a0d-a572-2b852ae6fce2.jpg)

madvr
![madvr](https://user-images.githubusercontent.com/41094733/126108879-ccf8bfbe-81f2-4ca4-9f51-39491dcc1b5b.jpg)
mpv default
![mpv](https://user-images.githubusercontent.com/41094733/126108882-25c1d934-30f0-4d8d-89d6-7b5ae042d9c1.jpg)
