### ISSUE TITLE
Improvements - Multilanguage UI (use .ts/.qm QT language files)

### ISSUE THREAD

**Issue by bovirus** [mpv-player/mpv#9021]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

Add other language (like Italian).
The program is based on QT and then should be simple to have external .ts/.qm language files to add new languages.

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by guidocella** [comment]
mpv is not based on Qt.

**Comment by bovirus** [comment]
@guidocella 

You are right. Sorry.
My scope is about MPV Easy Player that is based on mpbv but is not mpv.
Thanks.
