### ISSUE TITLE
`persistent_overlay=yes` cause the `{` missing

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9022]
### Important Information

Provide following Information:
- mpv version
commit 70c9d8d5d704764e35098843d1c9a788ee21beb6
- Windows Version
20h2
- Source of the mpv binary
built by the toolchain of shinchiro
- If known which version of mpv introduced the problem
commit 70c9d8d5d704764e35098843d1c9a788ee21beb6 (or earlier)
- Possible screenshot or video of visual glitches
see below

### Reproduction steps

1. start the mpv with the option: `persistent_overlay=yes` in the stats.conf
2. check stats list 4

The key `{` still works, it is just the display error.

### Expected behavior
![Snipaste_2021-07-20_18-11-43](https://user-images.githubusercontent.com/41094733/126306757-e2bb2711-8117-4108-8640-98c48a3fd15a.jpg)

### Actual behavior
![Snipaste_2021-07-20_18-09-06](https://user-images.githubusercontent.com/41094733/126306648-b210c10f-76f6-42b8-b372-b8fb49ff9249.jpg)

### Log file
[osd.log](https://github.com/mpv-player/mpv/files/6847430/osd.log)

**Comment by avih** [comment]
Huh, interesting. The key-name is explicitly wrapped in no-ass to disable ass parsing - exactly because `{` triggers ass parsing.

And as you can see it does work correctly without persistent (before I added the no-ass for the key it was wrong without persistent).

However, the page 4 code makes no distinction between yes/no persistent (it always wraps it with no-ass), so not sure where the issue comes from yet.

I'll look into that, thanks.

**Comment by avih** [comment]
Huh, `no_Ass` is just ignored with persistent display, not sure why yet: https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua#L138-L148

 What is `persistent_overlay=yes` good for anyway?

**Comment by hooke007** [comment]
>What is `persistent_overlay=yes` good for anyway?

For me, i just hope it will not covered by other OSD messages when I watch the stats lists.
For instance, watch the stats and change the volume will make it flicker, which is quite the poor experience.

**Comment by avih** [comment]
> Huh, `no_Ass` is just ignored with persistent display, not sure why yet: https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua#L138-L148

@Argon looks like you added the "ignore no_ASS" in persistent mode, but it's not 100% obvious to me why, mind helping me understand this?

I _think_ it's somehow related to the fact that `mp.osd_message` starts in no-ass mode (plain text), while `mp.set_osd_ass` is yes-ass by default?

However, if one wants to display arbitrary text like file name or property value, or, like here, a key-binding which includes `{`, then it has to be escaped from libass (what no_Ass does normally), but currently no_Ass just doesn't work in persistent mode.

Ideas?

**Comment by avih** [comment]
Oops, wrong mention, sorry.
@Argon- ^

**Comment by avih** [comment]
Also, as far as I can tell, I'm not the first to think that `no_Ass` should just work.

https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua#L573 also uses `no_Ass` for arbitrary filter names and value strings.

So while the name is unlikely to contain `{`, the value definitely could, and in persistent mode it would break (that's at page 1 if there are filters active).

So, this is an already existing issue which no one noticed so far, and the new page 4 also suffers from it, and now someone did notice.

We need to fix this.
