### ISSUE TITLE
toggle osc-bar at fullscreen

### ISSUE THREAD

**Issue by gajeet11000** [mpv-player/mpv#9028]
I want the osc-bar visibility set to **auto** whenever the mpv is in the fullscreen mode but in any other mode, I want it to be in **always** mode. I just want to toggle the osc-visibility property on switching fullscreen event.

For that I wrote a lua script which goes as follows:

```
mp.observe_property("fullscreen", "bool", function (name, val)
    if val == true then
        mp.set_property("osc-visibility", "auto")
    else
        mp.set_property("osc-visibility", "always")
    end
end
)
```
which isn't working for some reason, please help.

**Comment by guidocella** [comment]
`osc-visibility` isn't a property, you modify it with `script-message`:

```lua
mp.observe_property("fullscreen", "bool", function (_, val)
    mp.commandv("script-message", "osc-visibility", val and "auto" or "always")
end)
```

**Comment by avih** [comment]
Next time please read the docs before asking at the issue tracker why something doesn't work - https://mpv.io/manual/master/#on-screen-controller-osc-visibility

**Comment by gajeet11000** [comment]
Thanks a lot, @guidocella. Sorry, @avih I will make sure to read the docs properly, thanks.
