### ISSUE TITLE
`watch-later-options-remove` won't remove the options I set

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9029]
### Important Information

Provide following Information:
- mpv version
20210721 commit 1d1d1fb
- Windows Version
20h2
- Source of the mpv binary
same toolchain of shinchiro
- If known which version of mpv introduced the problem
commit 1d1d1fb

### Reproduction steps

1. start the mpv with
```
 save-position-on-quit = yes
 watch-later-options-remove = volume,speed
```
2. change the volume and speed at runtime and then exit.
3. check the temp file and what were recorded.

### Expected behavior
only `start` was recorded.
### Actual behavior
`start`, `volume` and `speed` were all recorded.

### Log file

[save.log](https://github.com/mpv-player/mpv/files/6857359/save.log)
![Snipaste_2021-07-22_00-17-51](https://user-images.githubusercontent.com/41094733/126523540-62ab115f-67e1-4be5-8915-186df24942c2.jpg)

### P.S.
Just set the single one option is OK —— `watch-later-options-remove = volume` or `watch-later-options-remove = speed` can work as what I expect.

**Comment by sfan5** [comment]
Use
<pre>
watch-later-options-remove=volume
watch-later-options-remove=speed
</pre>

The example in the documentation is incorrect though, we'll fix that.
