### ISSUE TITLE
10-bit video looks wrong in certain cases

### ISSUE THREAD

**Issue by AstroSnail** [mpv-player/mpv#9038]
### Important Information

Provide following Information:
- mpv version
```txt
mpv 0.33.1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4
```
- Linux Distribution and Version
- - NixOS unstable, as of 2021-07-23
- Source of the mpv binary
- - nixpkgs, on branch nixos-unstable
- If known which version of mpv introduced the problem
- Window Manager and version
```txt
i3 version 4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
```
- GPU driver and version
- - xf86-video-nouveau 1.0.17
- - Mesa 21.1.5
- Possible screenshot or video of visual glitches
Expected:
![mpv-shot0001](https://user-images.githubusercontent.com/15970994/126856097-221c3ba8-35eb-4f55-947e-b8899f0da3da.jpg)
Actual:
![2021-07-24-030442_704x400_scrot](https://user-images.githubusercontent.com/15970994/126856102-1584c6f2-9450-403b-b991-c48d64dc4f5b.png)

### Reproduction steps

Play a yuv420p10 video in mpv. (See sample file)

This only reproduces with `--vo=gpu --gpu-api=opengl --opengl-es=no`. Using OpenGL ES works around the issue. Using a different vo works around the issue. Using a software renderer (eg `LIBGL_ALWAYS_SOFTWARE=true` with `--gpu-sw`) works around the issue.

I understand that it's entirely possible that this is a driver issue, or even an issue of the fact the card is damaged, but I decided to start investigation with opening an mpv issue.

### Expected behavior

The video plays normally, in particular with correct colours.

### Actual behavior

The video plays, but is extremely green.

### Log file

Running mpv as described in reproduction steps: [mpvlog2.txt](https://github.com/mpv-player/mpv/files/6871842/mpvlog2.txt)
Running mpv with `--opengl-es=yes` (a workaround strategy) for comparison: [mpvlog2e.txt](https://github.com/mpv-player/mpv/files/6871843/mpvlog2e.txt)

### Sample files

https://user-images.githubusercontent.com/15970994/126856115-4a272875-2804-4539-a354-1d1a8ddcc07c.mp4

**Comment by CounterPillow** [comment]
I'm gonna almost certainly put this bug on nouveau because:

1. nouveau is known for bugs like these
2. I cannot reproduce this on amdgpu
3. 10-bit playback is generally quite well tested, due to the high amount of contributors with anime avatars

opengl ES seems to be working around the issue by ways of inserting an autoconvert filter to convert from yuv420p10 to yuv420p before rendering, maybe because it doesn't support high bit depth framebuffers or something.

**Comment by AstroSnail** [comment]
Alright, thank you!

**Comment by haasn** [comment]
If you want to report it upstream, this issue very much looks like the driver's "16-bit textures" are actually 8-bit textures in disguise.
