### ISSUE TITLE
Why tf default video color/effect ghosty like and why tf controls at the bottom hidden

### ISSUE THREAD

**Issue by alexpandain** [mpv-player/mpv#9041]
### Important Information

Provide following Information:
- mpv version 0.33.1
- Windows Version 7
- Source of the mpv binary https://sourceforge.net/projects/mpv-player-windows/files
- If known which version of mpv introduced the problem 0.33.1
- Possible screenshot or video of visual glitches
![image](https://user-images.githubusercontent.com/73612338/126877494-71e3ff51-dbc2-4642-809d-ce78200ba40b.png)

![image](https://user-images.githubusercontent.com/73612338/126877519-f36a795c-bacf-4644-b5fe-4cc178a3c5c0.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
Play the video in default color that is normal like mpc-be 
### Actual behavior
Gay color as you can see in screenshot and also why controller black?
### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by LaserEyess** [comment]
You didn't follow the issue template so this could be one of a million things, including you using mpv wrong. Include a log and actual reproduction steps.

**Comment by CounterPillow** [comment]
can be closed, user is running without graphics drivers as confirmed by logs sent on IRC
