### ISSUE TITLE
Losing audio device

### ISSUE THREAD

**Issue by milli260876** [mpv-player/mpv#9056]
I've got an issue which is with mpv, through emby. they suggested raising it here but as it's going through external software it might not get addressed anyway i thought i would post the link to the thread there.
on playback if  i use refresh rate switching mpv loses the audio device (denon amp thus no audio). if i skip back it re-finds it. several different builds of mpv AND different config file used, re-installed emby. then even re-installed windows problem persists.

https://emby.media/community/index.php?/topic/99568-direct-playback/page/5/&tab=comments#comment-1048825

any help would be greatly appreciated!!!

**Comment by Doofussy2** [comment]
Attach the log, from that thread. You can drag n drop it.

**Comment by milli260876** [comment]
https://emby.media/community/applications/core/interface/file/attachment.php?id=102947

**Comment by milli260876** [comment]
then i tried this log-file="C:\Users\themi\AppData\Roaming\mpv\Theater_mpv_log.txt"

opengl-pbo=yes
hdr-compute-peak=no

audio-exclusive=yes
audio-stream-silence=yes
audio-device=wasapi/DENON-AVR (Intel(R) Display Audio)

to see if it helped

**Comment by milli260876** [comment]
and a recompile of the latest mpv from git (this was provided by the emby team)

that didn't work either as below log

**Comment by milli260876** [comment]
https://emby.media/community/applications/core/interface/file/attachment.php?id=103304

**Comment by Dudemanguy** [comment]
Please open a new issue if this still exists on 0.36.
