### ISSUE TITLE
Audio stutters

### ISSUE THREAD

**Issue by Geniusssmit** [mpv-player/mpv#9058]
### Important Information

Provide following Information:
- mpv version Last
- Windows Version 10
- Source of the mpv binary the Updater
- If known which version of mpv introduced the problem No
- Possible screenshot or video of visual glitches

### Reproduction steps
Open m2ts file, set volume higher that 100

### Expected behavior
Audio plays smoothly
### Actual behavior
Severe stuttering on volume >100 just a little bit with <=100 volume
I've uploaded mp3 recording, how can I deal with it?
### Sample files
[seewLWYP2d.zip](https://github.com/mpv-player/mpv/files/6893159/seewLWYP2d.zip)

**Comment by Geniusssmit** [comment]
> ### Important Information
> Provide following Information:
> 
> * mpv version Last
> * Windows Version 10
> * Source of the mpv binary the Updater
> * If known which version of mpv introduced the problem No
> * Possible screenshot or video of visual glitches
> 
> If you're not using git master or the latest release, update.
> Releases are listed here: https://github.com/mpv-player/mpv/releases
> 
> ### Reproduction steps
> Try to reproduce your issue with --no-config first. If it isn't reproducible
> with --no-config try to first find out which option or script causes your issue.
> 
> Describe the reproduction steps as precise as possible. It's very likely that
> the bug you experience wasn't reproduced by the developer because the workflow
> differes from your own.
> 
> ### Expected behavior
> Audio plays smoothly
> 
> ### Actual behavior
> Severe stuttering on volume >100 just a little bit with <=100 volume
> I've uploaded mp3 recording, how can I deal with it?
> 
> ### Log file
> Make a log file made with -v -v or --log-file=output.txt, paste it to
> https://0x0.st/ or attach it to the github issue, and replace this text with a
> link to it.
> 
> The issue will be closed for ignoring the issue template.
> 
> ### Sample files
> [seewLWYP2d.zip](https://github.com/mpv-player/mpv/files/6893159/seewLWYP2d.zip)
> 
> Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
> or similar sites. (Only needed if the issue cannot be reproduced without it.)
> Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
No log file so closing.
