### ISSUE TITLE
bluetooth device multimedia buttons

### ISSUE THREAD

**Issue by hl2guide** [mpv-player/mpv#9063]
### Expected behavior of the wanted feature

Please add support for bluetooth device multimedia buttons like other multimedia players support. Play, pause etc..

**Comment by Akemi** [comment]
for what platform though? on macOS that's already the case and would be a bug if it's not working.

**Comment by LaserEyess** [comment]
This works on linux as well. My bluetooth headphnes have buttons for play, pause, and also next/previous track and they all work OOTB on a stock mpv input.conf. You're going to need to give a lot more information on why your setup isn't working.

**Comment by hl2guide** [comment]
I'm running Windows 10 21H1.

My bluetooth headphones' physical buttons work in MusicBee, all browsers, Windows Media Player, MPC-HC etc.

But not for MPV.

**Comment by Akemi** [comment]
please test of the keys are actually recognised with "mpv --input-test --force-window --idle" and are just unbound. in that case you just need to bing those keys. the command should open a new mpv window and whenever you press a key it will show which key and what command is bound in the upper left corner.

**Comment by hl2guide** [comment]
I tested that out using `mpv --input-test --force-window --idle`.

There's no text shown when I press the pause/play button on my bluetooth headphones.

There is for MOUSE_MOVE, MOUSE_ENTER etc..

**Comment by Akemi** [comment]
then your buttons are not recognised at all. rather than a feature request i would say this is an issue? i would appreciate if you could open a new issue, use the issue template for windows instead and provide all the information we ask for.

**Comment by pc00per** [comment]
I have this issue too. I'm on arch/gnome/wayland. Bluetooth buttons work everywhere (music player, youtube, html5 vids, etc). But not on mpv.

**Comment by foxjaw** [comment]
Try https://github.com/hoyon/mpv-mpris with https://github.com/altdesktop/playerctl
