### ISSUE TITLE
Audio files with .eac3 extension don't open as external audio

### ISSUE THREAD

**Issue by SoloBackup** [mpv-player/mpv#9065]
### Important Information

- mpv version: mpv-x86_64-20210725-git-e2109b6
- Windows Version: Windows 10 Home
- Source of the mpv binary: updated by the updater.bat

### Reproduction steps
(I have the command in mpv.conf to reproduce external audios: audio-file-auto=exact)
So in a folder i have the video file and the audio file and subtitle file too, all with the exact same name, with just the different extension (Movie.mkv,Movie.eac3,Movie.srt).

![my folder with the files](https://user-images.githubusercontent.com/84431888/127579594-73db8ab5-bd08-4c67-850a-500e8ba93831.jpg)

When i try to select external audio, the program doesn't recognize, and the external .eac3 audio doesn't appear to be selected in the player.

![trying to open the  eac3 external](https://user-images.githubusercontent.com/84431888/127579609-3b926ba0-0cdf-4dcf-a64a-448301b7af1c.jpg)

But when i try the exact same procedure but with an .mp3 instead of .eac3 it works normally and the mpv shows the .mp3 external audio.

![if the file is  mp3 it works](https://user-images.githubusercontent.com/84431888/127579620-35972475-2f7b-424e-9d55-991374edf0cd.jpg)

### Expected behavior
The behavior to be expected is that the player plays external audios in .eac3 format.

### Actual behavior
The player does not recognize external .eac3 audios

### Log file
I couldn't do

### Sample files
[Movie.mkv mediainfo.txt](https://github.com/mpv-player/mpv/files/6904264/Movie.mkv.mediainfo.txt)
[Movie.eac3 mediainfo.txt](https://github.com/mpv-player/mpv/files/6904266/Movie.eac3.mediainfo.txt)

**Comment by Dudemanguy** [comment]
The reason for this is quite simple. `eac3` isn't in the whitelist of audio extensions so it isn't picked up.

**Comment by SoloBackup** [comment]
Hi thanks for the answer, the .eac3 standalone could be played normally, and it goes very well. Soi thought it was some kind of issue. Thank you!
