### ISSUE TITLE
Why does "mpv --ytdl URL" works whereas "mpv --no-ytdl $(youtube-dl -gf format URL)" does not ?

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#9070]
Hi,

I wonder why does "mpv --ytdl URL" works whereas "mpv --no-ytdl $(youtube-dl -gf format URL)" does not ?
```
$ mpv --no-config --ytdl --ytdl-format=low https://ok.ru/video/89871682250
 (+) Video --vid=1 (*) (h264 640x356 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 640x356 => 640x357 yuv420p
AV: 00:00:12 / 01:52:42 (0%) A-V:  0.000 Cache: 29s/2MB


Exiting... (Quit)
$ mpv --no-config --no-ytdl $(youtube-dl -gf low https://ok.ru/video/89871682250)
[ffmpeg] https: HTTP error 400 Bad Request
Failed to open https://vd296.mycdn.me/?expires=1627770698189&srcIp=176.143.61.90&srcAg=CHROME&ms=185.226.53.5&type=1&sig=BaPTqRvJYmA&ct=0&urls=45.136.22.4&clientType=0&id=139148528330.


Exiting... (Errors when loading file)
```

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/6910215/output.txt)

**Comment by CounterPillow** [comment]
because it's not using the right cookies or user-agent that way?

**Comment by sebma** [comment]
@CounterPillow You're so fast. You just answered before I had the time to post the log file :smile:

**Comment by sebma** [comment]
@CounterPillow I see no user agent in my logfile, what option can I use on mpv cli to see that kind of information ?

**Comment by sebma** [comment]
@CounterPillow Thanks. Calling `mpv` on direct stream with `--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.53 Safari/537.36"` solves the pb.
