### ISSUE TITLE
mpv has wrong colors with any tone mapping

### ISSUE THREAD

**Issue by alexantr** [mpv-player/mpv#9071]
### Important Information

- mpv version: 0.33.0-217-gf049acfd43 (and previous)
- Windows Version: 21H1 19043.1110
- Source of the mpv binary: https://download.sourceforge.net/mpv-player-windows/mpv-x86_64-20210725-git-e2109b6.7z

I tested on two PCs. One has NVIDIA card with driver 471.41 another has Intel HD Graphics 630. Same result on both machines.

### Reproduction steps

Open HDR movie on SDR display, look for scene with bright saturated red lights. Try to compare picture with picture from another player or on HDR display.

### Expected behavior

mpv must show correct colors without hue shifts. Red must be true red not pinkish red.

### Actual behavior

Base colors like red, green and blue has hue shift. Movie scenes with red lights look wrong.

Here is comparisons madvr vs mpv: https://slow.pics/c/4kcOizzW

Also I took three HDR10 calibration videos (04-Rec2020-Red-100%.mp4, 09-Rec2020-Green-100%.mp4, 14-Rec2020-Blue-100%.mp4) and compare colors on different players. Almost all have correct hues: red - 0°, green - 120°, blue - 240°. And mpv only has 343°, 154° and 224°.

![mpv-wrong-hue](https://user-images.githubusercontent.com/4941848/127720626-00a09711-9cfe-43d8-a56f-c72f561992e6.png)

### Log files

[log with config.txt](https://github.com/mpv-player/mpv/files/6910317/log.with.config.txt)
[log no config.txt](https://github.com/mpv-player/mpv/files/6910319/log.no.config.txt)

### Sample files

Sample video files and screenshots on GD: https://drive.google.com/drive/folders/1RbSEtaZ05THg6K6Tvrd25T5_mPIjwEN5?usp=sharing

**Comment by LaserEyess** [comment]
Please don't use google drive for sample files and screenshots.

Can you reproduce any of the other HDR issues such as #8849, #7892, #7742, etc?

**Comment by alexantr** [comment]
#8849 - I like some clipping. It looks more "natural" like ususal SDR videos.
#7892 - no problems
#7742 - I use tone-mapping-desaturate=1 tone-mapping-desaturate-exponent=0 hdr-compute-peak=no

My story not about clipping, it about wrong colors. Clean red, green and blue colors with any brightness have some hue shift. Red color is more noticeable because it presents quite often in movies. bt.2390, hable, reinhard, mobius and other - the all have same problem. Any other player and ffmpeg don't have problems with tone mapping.

I reuploaded all files to my server: https://tmpfiles.xyz/mpv-tone-mapping/

**Comment by LaserEyess** [comment]
My point about hable, specifically, is because you were using hable with ffmpeg so you could have made an apples to apples comparison between mpv and ffmpeg for the same exact tonempaping algorithm. It looks like you did indeed update your files with the hable case and the issue persists. IMO this looks pretty extreme but I'm not at all familiar with tonemapping options in either mpv or ffmpeg to say what the issue is.

**Comment by Doofussy2** [comment]
I can reproduce this. I only tested with the red. But if I specify the primaries to the same at the test image, the color appears correct. 

`target-prim=bt.709`
![mpv-shot0002](https://user-images.githubusercontent.com/15950919/127755596-992a040a-b823-4154-bb1d-757ea566e70a.jpg)

`target-prim=bt.2020`
![mpv-shot0003](https://user-images.githubusercontent.com/15950919/127755607-2edebf7b-6a34-422e-9249-282f4aea26ba.jpg)

**Comment by hooke007** [comment]
The strange shift made mpv's tone-mapping quite diff from other player.

>But if I specify the primaries to the same as the test image, the color appears correct.

I think it was just a luck. `target-prim=bt.2020` will make any other hdr videos look terrible.

**Comment by Doofussy2** [comment]
It should be oversaturated when using the wider gamut. But it does appear to be incorrect with the primaries. If I get time, I'll try to run more comparisons.

**Comment by alexantr** [comment]
Look at this example with real scene: https://tmpfiles.xyz/mpv-tone-mapping/_test_files/red-umbrellas.mp4

madVR:
![Samsung 4K HDR Demo - This is TV ts madvr](https://user-images.githubusercontent.com/4941848/127779295-257abf41-c43f-4be0-beb9-8d087b657138.jpg)

mpv --no-config red-umbrellas.mp4
![Samsung 4K HDR Demo - This is TV ts mpv no-config](https://user-images.githubusercontent.com/4941848/127779538-e3798fbe-9c16-4df8-95a6-d9c567128439.jpg)

The difference is very noticeable, I can't ignore it while watching

**Comment by Robot-DaneelOlivaw** [comment]
I've tested Quicktime and latest mpv, and they aren't far off. This is what I get:

Quicktime:
<img width="1280" alt="Quicktime Rec2020 Red" src="https://user-images.githubusercontent.com/19835896/127973368-e0056766-e472-4244-a9c4-c252eaa36292.png">

`--no-config --icc-profile-auto`:
<img width="1280" alt="mpv Rec2020 Red" src="https://user-images.githubusercontent.com/19835896/127973455-ac07fd6b-20b8-4658-9938-d2a56e01198c.png">

`--no-config --icc-profile-auto --tone-mapping=hable`:
<img width="1280" alt="mpv Rec2020 Red hable" src="https://user-images.githubusercontent.com/19835896/127975147-a0d9e833-0f3b-4319-a6c3-94811ee9d8d2.png">

I've also tested P3 color in a BT.2020 container with mpv. Sample file: https://0x0.st/-4Sy.mov
I'm using 2017 MacBook Pro which has a P3 screen. P3 Red should be at least close to red but in reality it's far off. Setting `target-peak` to a higher value like 1000 makes the result more reasonable. Don't know if it's intended.

<details>
<summary>Test result</summary>

QuickTime:
<img width="1280" alt="Quicktime P3 Red" src="https://user-images.githubusercontent.com/19835896/127974502-e77f7794-1e51-4ea5-bb2f-48e13a185590.png">

`--no-config --icc-profile-auto`:
<img width="1280" alt="mpv P3 Red" src="https://user-images.githubusercontent.com/19835896/127969476-b5669abe-5694-4f86-9440-3d28beafcd60.png">

`--no-config --icc-profile-auto --tone-mapping=hable`:
<img width="1280" alt="截屏2021-08-03 下午3 30 03" src="https://user-images.githubusercontent.com/19835896/127975636-19021863-8342-42b8-ac6d-4e380e6af1dd.png">

`--no-config --icc-profile-auto --target-peak=1000`:
<img width="1280" alt="mpv P3 Red 1000" src="https://user-images.githubusercontent.com/19835896/127969568-eb038992-d082-4a5a-8a60-f62d37a5680e.png">
</details>

**Comment by alexantr** [comment]
I downloaded some previous versions from [SourceForge](https://sourceforge.net/projects/mpv-player-windows/files/) and found which version mpv got the problem.

<details>
<summary>mpv-x86_64-20200614-git-c7fe4ae has normal colors yet</summary>

![mpv-shot0001](https://user-images.githubusercontent.com/4941848/128016373-d9392906-3835-467d-9fdd-f6bca28039f5.jpg)
![mpv-shot0004](https://user-images.githubusercontent.com/4941848/128016382-b62ce6dc-529e-4221-8627-f7962f868878.jpg)
![mpv-shot0003](https://user-images.githubusercontent.com/4941848/128016391-e7cdd111-3b5a-4c0f-8f81-138f88fdf3b0.jpg)

</details>

<details>
<summary>mpv-x86_64-20200614-git-c7fe4ae has hue shift already</summary>

![mpv-shot0001](https://user-images.githubusercontent.com/4941848/128016409-461807e0-df0c-4df6-9100-39a079d9e9e4.jpg)
![mpv-shot0002](https://user-images.githubusercontent.com/4941848/128016429-0fdd5b4f-7fdd-4d34-8d36-8c781234c71e.jpg)
![mpv-shot0004](https://user-images.githubusercontent.com/4941848/128016441-80f08385-d250-46ad-bb28-9837959722f5.jpg)

</details>

**Comment by alexantr** [comment]
`--icc-profile-auto` resolves my problem, but why mpv has problem without this option after mpv-x86_64-20200614-git-c7fe4ae?

**Comment by hooke007** [comment]
Hmm, I used this version and still can reproduce.
20210502-git-39630dc

**Comment by Doofussy2** [comment]
> Hmm, I used this version and still can reproduce.
> 20210502-git-39630dc

That's a year later. He's using 2020, you're using 2021.

**Comment by alexantr** [comment]
Look at commits near this two builds https://github.com/mpv-player/mpv/commits/master?after=416668d3c8bb5d09ebb3d5e3dbe715856165898b+524&branch=master

I think the problematic commit is https://github.com/mpv-player/mpv/commit/dc24a437fb9ba2485bc8c5866542bd36254410d4

If I add `--gamut-clipping=no` the colors are correct. This new option is enabled by default

**Comment by Doofussy2** [comment]
It may also be peak detection. There was an adjustment around that time. Try using `hdr-compute-peak=no`

**Comment by alexantr** [comment]
@Doofussy2 no. `hdr-compute-peak=no` changes brightness only.

<details>
<summary>mpv --no-config</summary>

![mpv-shot0002](https://user-images.githubusercontent.com/4941848/128042875-48b3102f-f131-4350-b8f7-8c9bda52bd5d.jpg)
![mpv-shot0004](https://user-images.githubusercontent.com/4941848/128043086-46db7495-fd04-4096-96cc-1b56f2bbed56.jpg)

</details>

<details>
<summary>mpv --no-config --hdr-compute-peak=no</summary>

![mpv-shot0003](https://user-images.githubusercontent.com/4941848/128042995-7a7e4373-0549-4726-b364-0812988d7ac1.jpg)
![mpv-shot0005](https://user-images.githubusercontent.com/4941848/128043116-f27fe7e2-fcc6-4447-acf7-53d0d6ad5c4d.jpg)

</details>

<details>
<summary>mpv --no-config --gamut-clipping=no</summary>

![mpv-shot0008](https://user-images.githubusercontent.com/4941848/128043549-d02a8b5d-4234-4872-812d-225226e6f1e7.jpg)
![mpv-shot0006](https://user-images.githubusercontent.com/4941848/128043462-4ebb605a-c64e-482e-8fb2-d2b42503deb9.jpg)

</details>

<details>
<summary>mpv --no-config --hdr-compute-peak=no --gamut-clipping=no</summary>

![mpv-shot0009](https://user-images.githubusercontent.com/4941848/128043703-86022d32-4986-41ad-ab41-572132d5a23c.jpg)
![mpv-shot0007](https://user-images.githubusercontent.com/4941848/128043391-ddb78c84-963e-4fb6-81ec-2d75836185c4.jpg)

</details>

**Comment by alexantr** [comment]
I think `gamut-clipping` must be disabled by default

**Comment by Doofussy2** [comment]
compute-peak should probably be disabled by default, too.

**Comment by ObsessedHacker** [comment]
> I think `gamut-clipping` must be disabled by default.
> Or it can do it's job more accurate to preserve colors.

I'm asking as one who's new to MPV and asking to add new things to my config:
Does this solve your issue? (should I add it to my config?):

> hdr-compute-peak=no
gamut-clipping=no
icc-profile-auto
hdr-compute-peak=no

**Comment by alexantr** [comment]
@ObsessedHacker I'm using `hdr-compute-peak=no` and `gamut-clipping=no` now. All my videos I checked look like they should look from my point of view.

**Comment by alexantr** [comment]
@ObsessedHacker you can also try `tone-mapping-desaturate-exponent=0` and `tone-mapping-desaturate=0.9` to tune oversaturated bright areas.

<details>
<summary>default vs tuned</summary>

Look at the sun.

`tone-mapping-desaturate-exponent` and `tone-mapping-desaturate` with default values:
![Sony 4K HDR Demo - Camping in Nature mp4 00 00 06 223 default](https://user-images.githubusercontent.com/4941848/128174891-5bce3843-503f-4c13-9cfb-64e4b582f8c6.jpg)

`tone-mapping-desaturate-exponent=0` and `tone-mapping-desaturate=0.9`:
![Sony 4K HDR Demo - Camping in Nature mp4 00 00 06 223 tuned](https://user-images.githubusercontent.com/4941848/128174904-097f7c2c-cdec-43e3-9ada-36af288bdf82.jpg)

</details>

**Comment by Natural-Harmonia-Gropius** [comment]
with the following parameters, most scenes look fine. but the yellow highlights become orangeish, is it possible to compensate for the yellow highlights?
```
icc-profile-auto
no-gamut-clipping
hdr-compute-peak
tone-mapping=reinhard
tone-mapping-param=0.6
tone-mapping-max-boost=1.0
tone-mapping-desaturate=1.6
tone-mapping-desaturate-exponent=3.2
```
<details><summary>MPV</summary>
<img src="https://user-images.githubusercontent.com/50797982/132098309-8cab9859-fd21-41ad-bc22-28687a0f2576.png">
</details>
<details><summary>UWP MediaPlayer</summary>
<img src="https://user-images.githubusercontent.com/50797982/132098305-d0199c3f-cedf-49ac-b2c3-1fcbf698a6fa.png">
</details>
<details><summary>MPV</summary>
<img src="https://user-images.githubusercontent.com/50797982/132098233-24938277-008b-4bf7-86f0-36ffd6fa3a02.png">
</details>
<details><summary>UWP MediaPlayer</summary>
<img src="https://user-images.githubusercontent.com/50797982/132098190-6200e8fa-92be-4cfe-90b7-7906552299e1.png">
</details>

**Comment by Doofussy2** [comment]
Disable compute peak

**Comment by Natural-Harmonia-Gropius** [comment]
> Disable compute peak

That doesn't affect the color, only the illumination

**Comment by hooke007** [comment]
>icc-profile-auto

But uwp player (if u mean the Microsoft's) doesn't support the correct icc convert at all.

**Comment by Doofussy2** [comment]
I know, and I think that's what you're seeing. I think it's darkening the yellow. Did you try it?

**Comment by Natural-Harmonia-Gropius** [comment]
> I know, and I think that's what you're seeing. I think it's darkening the yellow. Did you try it?

Still orange

**Comment by Natural-Harmonia-Gropius** [comment]
> > icc-profile-auto
> 
> But uwp player (if u mean the Microsoft's) doesn't support the correct icc convert at all.

not at all

mpv -no-config
![image](https://user-images.githubusercontent.com/50797982/132100175-76201176-5ddc-4d37-b38c-b18803b3e71f.png)

uwp
![image](https://user-images.githubusercontent.com/50797982/132100167-a9e4b1d8-f1c6-4d34-a834-498559ea0bf7.png)

**Comment by Doofussy2** [comment]
> > I know, and I think that's what you're seeing. I think it's darkening the yellow. Did you try it?
> 
> Still orange

Try without the ICC and with compute peak disabled. I don't trust the windows ICC. You should make your own.

**Comment by Natural-Harmonia-Gropius** [comment]
> Try without the ICC and with compute peak disabled. I don't trust the windows ICC. You should make your own.

Orange, still orange，and there's only the yellow highlights will be orange, in the general brightness or the dark scene of the yellow looks well.

**Comment by Natural-Harmonia-Gropius** [comment]
tried to adjust `tone-mapping-desaturate` and `tone-mapping-desaturate-exponent`, gives white or orange, no yellow results.

**Comment by Natural-Harmonia-Gropius** [comment]
mpv
![image](https://user-images.githubusercontent.com/50797982/132101544-d8a57c7b-ebb1-4aaf-803a-a18177776faa.png)
youtube provides the sdr version
![image](https://user-images.githubusercontent.com/50797982/132101554-f20342dc-043e-4654-b8fa-a60a92a68877.png)

All colors are so close, except for the yellow in the flames.

**Comment by alexantr** [comment]
With `no-hdr-compute-peak` the yellow color is yellow.

<details>
  <summary>mpv --no-config</summary>

The yellow is orange:

![mpv-shot0001 --no-config](https://user-images.githubusercontent.com/4941848/132105000-8c39b419-392f-4a94-abca-a2efcecac3b9.jpg)

</details>

<details>
  <summary>mpv --no-config --no-gamut-clipping</summary>

The yellow is yellow-orange:

![mpv-shot0002 --no-config --no-gamut-clipping](https://user-images.githubusercontent.com/4941848/132105032-8c0635d8-f1e0-4fda-bce3-7e72228fc00c.jpg)

</details>

<details>
  <summary>mpv --no-config --no-gamut-clipping --no-hdr-compute-peak</summary>

The yellow is yellow:

![mpv-shot0003 --no-config --no-gamut-clipping --no-hdr-compute-peak](https://user-images.githubusercontent.com/4941848/132105058-b3f743f7-c90c-41de-a12d-9391027902a1.jpg)

</details>

<details>
  <summary>youtube</summary>

![youtube](https://user-images.githubusercontent.com/4941848/132105074-963ebd6a-7fc8-47c2-8b7e-129f9b9f6492.jpg)

</details>

**Comment by Doofussy2** [comment]
That's a good example. Take a look at her forehead. Notice the difference in the peak brightness. Applying that to the flames, alters the color. Compute peak drops too low.

Interestingly, the HLG version of that video has notably different coloring. The skin tone is very different. The HDR10 version looks oversaturated.

**Comment by alexantr** [comment]
> The HDR10 version looks oversaturated.

I checked madVR. It shows colors less saturated.

<details>
  <summary>madVR target 200nits</summary>

![LG 4K HDR Demo - Cymatic Jazz ts_snapshot_01 25 269](https://user-images.githubusercontent.com/4941848/132107270-3868ca21-01d1-4510-b750-6d2775707292.jpg)

</details>

**Comment by alexantr** [comment]
Also I enabled Reinhard tone mapping with desaturation I used before bt.2390 and I saw normal colors like in madVR.

Config:
```
tone-mapping=reinhard
tone-mapping-desaturate=0.9
tone-mapping-desaturate-exponent=0
hdr-compute-peak=no
gamut-clipping=no
```

<details>
  <summary>Result</summary>

![LG 4K HDR Demo - Cymatic Jazz ts 00 01 25 269 reinhard](https://user-images.githubusercontent.com/4941848/132107675-f4d0da0c-c308-4471-977e-46dff4dc7c76.jpg)

</details>

I checked another HDR Demo. Look at red umbrellas. Reinhard saves more details like madVR does.

<details>
  <summary>Reinhard vs bt.2390</summary>

Reinhard with config above:
![Samsung 4K HDR Demo - This is TV ts 00 00 42 125 reinhard](https://user-images.githubusercontent.com/4941848/132108124-0ae4ceca-43ff-4361-8ca7-a16d71410534.jpg)

mpv --no-config --no-gamut-clipping --no-hdr-compute-peak:
![mpv-shot0001 --no-config --no-gamut-clipping --no-hdr-compute-peak](https://user-images.githubusercontent.com/4941848/132108126-dfe7f512-d43b-42b4-bf23-6764830560f3.jpg)

madVR:
![Samsung 4K HDR Demo - This is TV ts madvr](https://user-images.githubusercontent.com/4941848/132108131-f7b60de7-9e31-43a0-9d8e-4589bd1bc08d.jpg)

</details>

Is bt.2390 implementation correct in mpv? Because madVR also uses bt.2390 and has normal, no oversaturated colors. Reinhard in mpv is normal too.

**Comment by Doofussy2** [comment]
> I checked madVR. It shows colors less saturated.

I meant the HDR10 mastering is oversaturated. But from your screenshots, it looks like MadVR compensates when tone-mapping.

I now have multiple versions of that Jazz video, and each has different mastering. So make sure to make comparisons from the exact same video.

**Comment by Natural-Harmonia-Gropius** [comment]
```
hdr-compute-peak
tone-mapping=reinhard
tone-mapping-param=0.6
tone-mapping-desaturate=1.2
tone-mapping-desaturate-exponent=2.4
```
![image](https://user-images.githubusercontent.com/50797982/132117742-3edf0954-2140-4c2f-93b0-0abca506faee.png)

> ```
> tone-mapping=reinhard
> tone-mapping-desaturate=0.9
> tone-mapping-desaturate-exponent=0
> hdr-compute-peak=no
> gamut-clipping=no
> ```
yellow is yellow, less contrast, highlights are slightly whitish.
![image](https://user-images.githubusercontent.com/50797982/132117828-f1d31153-b06a-4b3a-ad08-067be44a3f26.png)

UWP
much more yellow, good contrast, highlights are not white or orange
![image](https://user-images.githubusercontent.com/50797982/132117352-177fb1af-ba2b-4735-8144-e76befd1c9ed.png)

**Comment by alexantr** [comment]
Is UWP Player can be a reference? It loses too much details in bright areas. That's why warm yellow becomes yellow.

**Comment by hooke007** [comment]
Probably not, to keep the balance within details , color accuracy , brightness etc. seems to be impossible.

**Comment by Natural-Harmonia-Gropius** [comment]
here's a edited from uwp screenshot (sdr srgb 8bit) by lightroom (exposure -50, highlight -100), I didn't notice where the details were missing
![132117352-177fb1af-ba2b-4735-8144-e76befd1c9ed_edited](https://user-images.githubusercontent.com/50797982/132123360-850b1325-ea5a-4b83-a4a5-9438c7ec4ac6.jpg)

> Is UWP Player can be a reference? It loses too much details in bright areas. That's why warm yellow becomes yellow.

madvr can't too. i think only take a shot for TV can be.
brighter, darker, these are all acceptable, but the color is unaccuracy can't be accept.

samples (from 12bit raw) with adjusted highlights, orange is orange, yellow is yellow.
![-100](https://user-images.githubusercontent.com/50797982/132124283-364c47fa-add8-489d-9e1d-51f58150fa95.jpg)
![0](https://user-images.githubusercontent.com/50797982/132124276-25fa7f16-3b73-4fde-aad6-b83649fa2212.jpg)
![+100](https://user-images.githubusercontent.com/50797982/132124274-06eab656-38af-4da5-b417-5ad15acdb4c2.jpg)

**Comment by ValZapod** [comment]
> i think only take a shot for TV can be.

Or a screenshot using nvidia's JPEG XR screenshot feature. It is perfect! WCG and HDR.

**Comment by ValZapod** [comment]
Genious file by our russian guy Mehanik has

>Mastering display color primaries :	Display P3

which means that any color in BT.2020 primaries outside that (in specified mastering volume) should not be preserved.

Are you serious right now? 04-Rec2020-Red-100%.mp4 will only show 100% P3-D65.

And now, the patches that allow to hevc_metadata modify this in hevc bitream are not merged yet in ffmpeg.

**Comment by Dudemanguy** [comment]
People might get upset at me closing any HDR/tone mapping related issue... No idea what the state of this is currently but there's gpu-next nowadays and a bazillion new tonemapping options I don't understand so I'll close this. Feel free to open a more concrete issue if something truly is still wrong.
