### ISSUE TITLE
Multipedia Keys on keyboard does not work

### ISSUE THREAD

**Issue by anishmittal2020** [mpv-player/mpv#9072]
### Important Information

Provide following Information:
- mpv version

mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.4-1ubuntu0.1

- Linux Distribution and Version
- Window Manager and version
- GPU driver and version

OS: Ubuntu 20.04.2 LTS x86_64 
Host: X550JX 1.0 
Kernel: 5.4.0-80-generic 
Uptime: 4 hours, 2 mins 
Packages: 3793 (dpkg), 358 (brew), 10 (flatpak), 4 (snap) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Unity 
WM: Mutter 
WM Theme: HighContrast 
Theme: Yaru-light [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: vscode 
CPU: Intel i7-4720HQ (8) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 950M 
GPU: Intel 4th Gen Core Processor 
Memory: 4040MiB / 7850MiB 

- Source of the mpv binary:  Ubuntu (PPA) | https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests
- If known which version of mpv introduced the problem

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Tried with `--no-config` but it did not work

### Log file

[Log File](https://0x0.st/-4s3.txt)

The issue will be closed for ignoring the issue template.

**Comment by LaserEyess** [comment]
Can you do `mpv --input-test --force-window --idle`? Press the multimedia keys and see if they're recognized. If they aren't, try to see if they're recognized in your OS, using something like this https://askubuntu.com/a/1197665. If Ubuntu can't recognize them this is an ubuntu issue.

**Comment by anishmittal2020** [comment]
@LaserEyess According to mpv Multimedia keys are not supported in Linux..

**Comment by LaserEyess** [comment]
Where did you see that? That's not true and I can use multimedia keys on linux.

**Comment by anishmittal2020** [comment]
```
--input-media-keys=&lt;yes|no&gt;[](https://mpv.io/manual/stable/#options-input-media-keys)

(OS X and Windows only) Enable/disable media keys support. Enabled by default (except for libmpv).
```

**Comment by anishmittal2020** [comment]
Multimedia keys work with Firefox and Chrome, VLC.

**Comment by LaserEyess** [comment]
The docs are wrong, mpv has support for these keys on both Xorg ([source](https://github.com/mpv-player/mpv/blob/master/video/out/x11_common.c#L683-L693)) as well as Wayland ([source](https://github.com/mpv-player/mpv/blob/master/video/out/wayland_common.c#L88-L99)). But beyond that, I, a linux user, use multimedia keys on my bluetooth headphones to control mpv, so something must be wrong besides lack of support.

**Comment by anishmittal2020** [comment]
I found this: [hoyon/mpv-mpris: MPRIS plugin for mpv](https://github.com/hoyon/mpv-mpris). Do you mean that MPV has buil in support for MPRIS?

**Comment by Dudemanguy** [comment]
The `input-media-keys` option is just a toggle for OS X/Windows for enabling/disabling media keys for thos platforms (whatever is defined as a "media key" there). That doesn't mean media keys don't work on linux. You just have to specify them in your input.conf like any other key.

**Comment by LaserEyess** [comment]
That's a plugin for MPRIS so, no, mpv does not have built in support but that plugin will give mpv support for MPRIS. However, that is not your issue, I do not use MPRIS and it still works for me. 

Please do `mpv --input-test --force-window --idle --log-file=mpv_input.log`, test your multimedia keys, and upload mpv_input.log and link it here.

**Comment by anishmittal2020** [comment]
@LaserEyess  https://0x0.st/-4qX.log

**Comment by LaserEyess** [comment]
You don't need to play a video with that, you can just run that command as is. Assuming you did the test correctly and actually pressed the multimedia keys, it appears they are completely unmapped. Can you do something like

```bash
xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
```
And then press the multimedia keys and see if they get reported?

**Comment by anishmittal2020** [comment]
No output on bash when I press pause/play multimedia key on my keyboard. But it pauses my Youtube video playing on firefox.

**Comment by LaserEyess** [comment]
I'm not sure how that works. Your desktop is saying it doesn't recognize those keys, there's nothing mpv can do about that. Yet, firefox does? This must be something ubuntu/GNOME is doing and I'm unsure what it could be. For now, you can try the MPRIS plugin, it should work. Otherwise you'd need to talk to someone who knows more about GNOME/Ubuntu.

**Comment by LaserEyess** [comment]
@anishmittal2020 can you provide any more information on this? I think this is almost certainly not an mpv bug if `xev` can't even see these keys. Most likely what is happening is that GNOME is intercepting your media keys and sending them to some dbus protocol that firefox and VLC recognize. mpv does not support this, and likely never will due to the complexity of adding dbus.

That protocol may be MPRIS, in which case you can use the MPRIS plugin https://github.com/hoyon/mpv-mpris.

**Comment by anishmittal2020** [comment]
Now I am using MPRIS, although not reliable. We can close the issue as I don't have any other information that I could provide.
