### ISSUE TITLE
Select GPU device

### ISSUE THREAD

**Issue by zpmmehrdad** [mpv-player/mpv#9076]
Hi everyone,

I have two GPUs,

GPU 0: Intel(R)
GPU 1: NVIDIA GeForce GTX 1650

mpv is using GPU 0 but I would like to use GPU 1. How can I set it?

Thanks

**Comment by CounterPillow** [comment]
For Vulkan, use `--vulkan-device`, see `--vulkan-device=help` for a list of devices.

For d3d11, use `--d3d11-adapter`, see `--d3d11-adapter=help` for a list of adapters.
