### ISSUE TITLE
A new way of encrypting/decrypting videos?

### ISSUE THREAD

**Issue by markg85** [mpv-player/mpv#9077]
Hi,

In HLS and MPEG-DASH you have encryption support. But those formats are more tailored towards the streaming and web point of view.

I can convert my videos to HLS formatted ones and have encrypted playback working. It has other advantages like defining the chunk size. A smaller size means your .ts files get smaller and you get to see something sooner.
It's quite fancy really, but not at all tailored towards just the situation of "i have a video file and just want to have it encrypted".
Also, i really dislike that my video (mp4/mkv) needs to be turned into a ts file and put in a m3u8 file as manifest to tie everything together.

I'm looking for a syntax like:
`mpv my_encrypted_file.mkv.enc --decrypt-key=<key> --decrypt-algo=AES-128-CTR`

And encrypting a video would be done like this:
`openssl enc -aes-128-ctr -K <KEY> -iv <IV> -in my_encrypted_file.mkv -out my_encrypted_file.mkv.enc`

The `mpv` command above is just an idea and doesn't work.
The `openssl` command would work if you provide a key and iv.

Note: I am aware of the `crypto` protocol in ffmpeg. That however only works on streams when it was setup with a command like:
`ffmpeg -i <video> -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key <key> -encryption_kid <key_id> <encrypted_video_output>`

That works too but works a bit weirdly. The file is still a video of the length of the original video. So in other terms, it partially encrypts the video (the content itself) not the headers required to know it's a video and it's length. I don't find that ideal either.

A couple of questions come to mind:
1. With the first example (encryption done via openssl, decryption in the mpv command), where would this be done ideally in ffmpeg? Or would that be a new protocol? Say an "openssl" protocol?
2. Would something like this be a welcome addition?
3. How do you folks encrypt videos?
4. I can't imagine i'm the first one ever with a request like this. Doesn't something like this exist already? Then something that isn't in the above examples obviously.

Best regards,
Mark

**Comment by TheAMM** [comment]
> With the first example (encryption done via openssl, decryption in the mpv command), where would this be done ideally in ffmpeg? Or would that be a new protocol? Say an "openssl" protocol?

The `crypto` protocol should already do what you want. You can probably access it with `lavf://` in mpv, though passing the keys I don't know about. That would be a valid feature request.

> Would something like this be a welcome addition?

Not... really.

> How do you folks encrypt videos?

We don't? You have many options for encrypting arbitrary data already: filesystem-level encryption, truecrypt-like solutions, password protected zip archives, openssl invocations, and everything else.

Why *do* you want to encrypt individual videos? There are much more convenient ways to solve this, and having mpv (alone, of all players) support decrypting files encrypted in a specific manner would be quite niche.
I hope you're not handling anything controversial.

**Comment by markg85** [comment]
> Why _do_ you want to encrypt individual videos? There are much more convenient ways to solve this, and having mpv (alone, of all players) support decrypting files encrypted in a specific manner would be quite niche.
> I hope you're not handling anything controversial.

I want to host some files on an open accessible network (IPFS) and for that reason i want to encrypt them. That kinda allows one to use an open network for private data. A downside of this approach is that any transparent native solutions like an encrypted filesystem level partition isn't going to work. Hence the need to encrypt individual files.

Playing such encrypted files is very much possible with ffmpeg (see #9078 that i just opened for this).
In fact, it seems my whole issue is figuring out which command to use to get mpv to behave (which is #9078) so i'm closing this one.
