### ISSUE TITLE
Play file with crypto protocol?

### ISSUE THREAD

**Issue by markg85** [mpv-player/mpv#9078]
Hi,

Encrypt a video in the following manner:
```
AES_KEY=$(openssl rand -hex 32)
AES_IV=$(openssl rand -hex 16)
openssl enc -aes-128-cbc -K $AES_KEY -iv $AES_IV -in my_video.mkv -out my_video.mkv.enc
```
You now have a `my_video.mkv.enc` with AES128 encryption.
You can play this using:
`ffplay my_video.mkv.enc -decryption_key $AES_KEY -decryption_iv $AES_IV`

But how to play this same file using mpv?
As MPV doesn't appear to have the "crypto" protocol.

Best regards,
Mark

**Comment by markg85** [comment]
If i'm reading the mpv documentation correctly, this "should" work:
`mpv lavf://crypto:my_video.mkv.enc --demuxer-lavf-o=decryption_key=$AES_KEY,decryption_iv=$AES_IV`

But it's throwing me the following error:
```
[ffmpeg] crypto: decryption key not set
Failed to open lavf://crypto:my_video.mkv.enc.
```

Any clue how the command should be properly formatted?

**Comment by garoto** [comment]
`mpv --msg-level=all=no,ffmpeg=trace` and keep looking for hints. Escaping is always an issue regardless of platform.

**Comment by markg85** [comment]
> `mpv --msg-level=all=no,ffmpeg=trace` and keep looking for hints. Escaping is always an issue regardless of platform.

Doesn't help me at all.
It gives me less output then not providing it and the output it does give is exactly the same as i posted above.

**Comment by garoto** [comment]
Damn, so sorry for wasting your time.

**Comment by rubyFeedback** [comment]
> so sorry for wasting your time

It's still not bad actually. For instance, I did not know -msg-level could be combined like that e. g. via the ffmpeg=trace part, so I am sure others learned it. And you gave it a try, so I think it's still a win-win even if the original issue has not been solved (yet).

**Comment by qmega** [comment]
You want to set AVOptions on the stream, not the demuxer.
`mpv lavf://crypto:my_video.mkv.enc --stream-lavf-o=key=$AES_KEY,iv=$AES_IV`

Although, unless I'm missing something, aes-128 is only 16 bytes of key; openssl will truncate a longer one but ffmpeg will reject it. A 32-byte key would be aes-256, but I don't know how to tell ffmpeg to do that, if there even is a way. I'd guess ffmpeg's crypto support was designed to access some particular thing that's found in the wild and not as a flexible encryption solution.

I don't want to go too far answering a question you didn't ask (and isn't relevant to mpv) but based on your other issue, if you want to generally "use an open network for private data" you might be better served by a more generic layer of encryption that doesn't require application suport. Unless videos are the only thing you want to store/transfer and mpv is the only client, getting every individual application to decrypt for you is going to be a losing battle.

**Comment by markg85** [comment]
> You want to set AVOptions on the stream, not the demuxer.
mpv lavf://crypto:my_video.mkv.enc --stream-lavf-o=key=$AES_KEY,iv=$AES_IV

Awesome! That works! 

> I don't want to go too far answering a question you didn't ask (and isn't relevant to mpv) but based on your other issue, if you want to generally "use an open network for private data" you might be better served by a more generic layer of encryption that doesn't require application suport. Unless videos are the only thing you want to store/transfer and mpv is the only client, getting every individual application to decrypt for you is going to be a losing battle.

Thank you for your input on that one!
The only troubling thing for me in the "use an open network for private data" idea is video. Images and other static content can be decrypted on the fly easily and presented that way. Video is more tricky as you have not much control over it in the browser. You just need to adhere to standards (or de-facto standards) to get that part working. In browser land that means i need to convert my videos to HLS ones. The browser just supports [CENC](https://ottverse.com/eme-cenc-cdm-aes-keys-drm-digital-rights-management/#CENC_or_Common_Encryption).

Everything discussed here (to get it working in mpv) isn't going to work in the browser. That troubles me. I do not want to conform a standard that throws out the format i had and picks it's own (HLS), i want to be able to play the file, decrypt it with the key i provide and be done with it.

Anyhow, the initial issue is resolved with your answer :)
