### ISSUE TITLE
Fallback to dither=fruit because there is no enough shared memory

### ISSUE THREAD

**Issue by ObsessedHacker** [mpv-player/mpv#9083]
### Important Information

Provide following Information:
- mpv 0.33.0-268-g416668d3c8
- Windows 10 Pro 64bit 21H1 19043.1110
- Source of the mpv binary [sourceforge](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20210801-git-416668d.7z/download)

### Reproduction steps
1) Download MPV from sourceforge
2) Move folder to "C:\Program Files"
3) Run "mpv-install" as Administrator
4) Create a config (mpv.conf) on %appdata%\mpv
5) Add lines
> log-file=~~/log.txt
dither=error-diffusion
error-diffusion=jarvis-judice-ninke
dither-depth=12

I tried the following actions and got the same error:
1) "dither-depth" to 8
2) Deleting "scripts" and "script-opts" folders
3) Removing my existing config and only using the 4 rows of code I mentioned above
4) Changing my audio on Windows to stereo instead of 7.1

### Expected behavior
Will not fallback to dither=fruit

### Actual behavior

> [   0.611][w][vo/gpu] Fallback to dither=fruit because there is no enough shared memory (36108/32768).

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/6928284/log.txt)

**Comment by ObsessedHacker** [comment]
> I don't understand this bug report. What behavior would you have preferred?

I want to play videos on MPV with these settings - "error-diffusion=jarvis-judice-ninke".
And I have a relatively powerful GPU, GTX 1650, in that case, I'm trying to understand the reason it shows me this error "no enough shared memory".
It has 4GB of GDDR5, so it should have "enough shared memory".

**Comment by haasn** [comment]
> And I have a relatively powerful GPU, GTX 1650

The GTX 1650 has exactly [49 KiB of shared memory](http://vulkan.gpuinfo.org/displayreport.php?id=12059#properties). While not *that* much more, it is more than the 32 KiB reported by the d3d11 API, and more than the 36 KiB needed by the shader. Try using `gpu-api=vulkan` instead?

**Comment by ObsessedHacker** [comment]
@haasn

> gpu-api=vulkan

Does work with

> error-diffusion=jarvis-judice-ninke

Thank you for your help!

Unrelated question:
What is better (even tho Vulkan allows me to use "jarvis-judice-ninke")?
D3D11 or Vulkan?
