### ISSUE TITLE
libmpv on iOS / tvOS fail hw decoding with .TS live stream, working on macOS

### ISSUE THREAD

**Issue by skrew** [mpv-player/mpv#9085]
### Important Information

Provide following Information:
- mpv version 0.33
- iOS 14 / tvOS 14
- mpv on Github

### Reproduction steps
Playing a H264 .TS live stream (not hls or dash)
It's look like hwaccel is giving up too fast.

### Expected behavior
Decoding with videotoolbox
On macOS, it's works:
```
mpv -hwdec=auto-safe https://skrobs.com/test.ts
...
 (+) Video --vid=1 (h264 1920x1080 25.000fps)
 (+) Audio --aid=1 --alang=fra (ac3 2ch 48000Hz)
     Subs  --sid=1 --slang=fra (dvb_subtitle)
     Subs  --sid=2 --slang=fra 'hearing impaired' (dvb_subtitle)
[ffmpeg/video] h264: co located POCs unavailable
[ffmpeg/video] h264: co located POCs unavailable
AO: [coreaudio] 48000Hz stereo 2ch floatp
Using hardware decoding (videotoolbox).
VO: [libmpv] 1920x1080 videotoolbox[nv12]
```

### Actual behavior
Falling back to software decoding

### Log file
https://skrobs.com/mpv-log-ios.txt

### Sample files
https://skrobs.com/test.ts

**Comment by Akemi** [comment]
you can try increasing `--vd-lavc-software-fallback=` to something higher. though this seems more like an ffmpeg problem.

**Comment by skrew** [comment]
Already tested with number like 60000 and `--vd-lavc-software-fallback=no` without success

**Comment by skrew** [comment]
I have tested with multiple versions, with the same result:

-> MPV 0.33, 0.32, 0.31, 0.28.1
-> FFmpeg 4.4, 4.3.1, 4.2.2, 4.1.3 

What is interesting is that while the tvOS version fails 100% of the time, the iOS version works from time to time

**Comment by Akemi** [comment]
ffmpeg is responsible for (hw)decoding so it would be best to test with plain ffmpeg first. if you can reproduce the same error, eg falling back to sw or rather not decoding at all, it's an ffmpeg issue. usually you can test with, though no idea how this works with iOS or tvOS:
```
ffmpeg -hwaccel videotoolbox -i "your_file.MP4" -f null -
```

**Comment by skrew** [comment]
I have traced `videotoolbox.c` from `FFmpeg` and the problem is here. I can close this ticket.

Thanks

**Comment by Akemi** [comment]
thanks for checking. if you open an issue on the ffmpeg issue tracker it would be nice if you could link it here too, for future reference and others that might have the same problem.

**Comment by skrew** [comment]
I'm not sure about opening an issue, generally they don't care about this kind of problem... Lost of time i think... I will try if i can't find a solution by myself.

**Comment by jeeb** [comment]
If the broadcast content is interlaced, Apple have specifically noted that they don't support this any more, even though previously VideoToolbox might have had supported this on desktop systems.

https://patchwork.ffmpeg.org/project/ffmpeg/patch/20170926003631.55571-3-ffmpeg@tmm1.net/

See the response from Apple on the rdar issue:
> Correct and intentional. Please stop using interlaced video.

**Comment by skrew** [comment]
@jeeb Good explanation. And that explain why it never fail with HEVC live (if I'm not mistaken, we can't have an interlace with the HEVC encoder)

Thanks

**Comment by jeeb** [comment]
It is a useful misinterpretation if it keeps people from falling into interlacism :) .

HEVC removed custom coding modes from interlaced content (H.264 had PAFF and MBAFF), but kept the metadata fields ("is this picture a field or a frame, top/bottom field"). I have seen interlaced HEVC in f.ex. German broadcasts.

One of my favourite threads on the jct-vc mailing list was where the cable companies' lobbying for special interlaced coding modes got stopped, as the coding performance with standard tooling was considered good enough.
