### ISSUE TITLE
MPV application (./mpv --vo=vdpau --hwdec=vdpau sample.mkv) exits after VT switch out.

### ISSUE THREAD

**Issue by sumedh105** [mpv-player/mpv#9086]
### Important Information

Provide following Information:
- mpv version: 0.33.0-121-gf665149fc8-dirty.
- Linux Distribution and Version: Ubuntu 20.04.2 LTS.
- Source of the mpv binary: git cloned the code and built it.
- If known which version of mpv introduced the problem: Not sure.
- Window Manager and version
- GPU driver and version: Nvidia-470.00.
- Possible screenshot or video of visual glitches: No glitches in the video.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

1. Make sure you are switched to the terminal on which X is running. In my case, X is runningn on the terminal VT#7. I make sure that I am on this terminal by running the command: sudo chvt 7.
2.  Run the mpv application using the command: ./mpv --vo=vdpau --hwdec=vdpau sample.mkv
3. Switch out from the terminal (VT#7) to the terminal (VT#1). To switch out from the terminal VT#7 to terminal VT#1, the command used is: sudo chvt 1
4. The MPV application exits after switching out from the terminal (VT#7) to terminal (VT#1).

### Expected behavior
1. The MPV application should stay in a loop. It should not exit after VT switch out.

### Actual behavior
1. The MPV application exits after VT switch out.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[log-bug-2.txt](https://github.com/mpv-player/mpv/files/6938182/log-bug-2.txt)
The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by philipl** [comment]
Fixed by #9102
