### ISSUE TITLE
YouTube Video Description

### ISSUE THREAD

**Issue by ObsessedHacker** [mpv-player/mpv#9092]
I'm using MPV to watch YouTube videos and I want to read and click links on the video description but I don't see a way of doing so.
While playing a YouTube video all I see on MPV is the video and the title, not the video description.
Is there any way to view the YouTube video description on MPV?

**Comment by guidocella** [comment]
The youtube video description should be printed if you start mpv from the terminal. Otherwise you can print it on the OSD by binding something to `show-text ${metadata}` or `show-text ${metadata/ytdl_description}`, but it will likely get cropped.

**Comment by ObsessedHacker** [comment]
@guidocella
I'm sorry, I'm still new to MPV, how do I insert this?

> show-text ${metadata/ytdl_description}

But what about links? can I click on them?

**Comment by LaserEyess** [comment]
to display it press backtick and then type that line into the REPL. However, this isn't going to do what you want, the OSD is not a GUI, it cannot parse hyperlinks and make them clickable. What you're asking isn't possible with mpv.

**Comment by ObsessedHacker** [comment]
> to display it press backtick and then type that line into the REPL. However, this isn't going to do what you want, the OSD is not a GUI, it cannot parse hyperlinks and make them clickable. What you're asking isn't possible with mpv.

Ok so on input.conf I added a keybind,
As for hyperlinks - I wish it was working.

**Comment by LaserEyess** [comment]
No, you don't need to add a keybind, you literally press `, and then a command window will show up in mpv. You can then type (verbatim) `show-text ${metadata/ytdl_description}` and it will be printed to the OSD. However, like I said it will not do hyperlinks and there's no real way to do that.

**Comment by Hrxn** [comment]
Yes, you can run arbitrary commands with an input bind to [run](https://mpv.io/manual/master/#command-interface-[-]]])

**Comment by Geremia** [comment]
@guidocella Are `channel_url`, `ytdl_description`, `uploader` the only metadata available? What about upload date, views, etc.?

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/blob/f57c5ca422aa3b30d4a746dbad542667936b07ca/player/lua/ytdl_hook.lua#L39-L66 is the list of the currently parsed metadata.

**Comment by Geremia** [comment]
@guidocella How do I show everything? `show-text ${metadata}` only shows a few things.

**Comment by guidocella** [comment]
By adding them to `--display-tags`.
