### ISSUE TITLE
Lrc file with ID3 tags are not supported

### ISSUE THREAD

**Issue by lamyergeier** [mpv-player/mpv#9096]
### Important Information

Provide following Information:
- mpv version

```
$ /home/linuxbrew/.linuxbrew/bin/mpv --version
mpv 0.33.1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Apr  6 06:14:01 UTC 2021
FFmpeg library versions:
   libavutil       56.51.100 (runtime 56.70.100)
   libavcodec      58.91.100 (runtime 58.134.100)
   libavformat     58.45.100 (runtime 58.76.100)
   libswscale      5.7.100 (runtime 5.9.100)
   libavfilter     7.85.100 (runtime 7.110.100)
   libswresample   3.7.100 (runtime 3.9.100)
FFmpeg version: 4.4
```
- Linux Distribution and Version
- Source of the mpv binary: Brew
- If known which version of mpv introduced the problem
- Window Manager and version
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce the issue with --no-config: Yes reproducible

Play a mp3 file with lrc file of the same name that has ID3 tags like 

```text
[ar:Chubby Checker oppure  Beatles, The]
[al:Hits Of The 60's - Vol. 2 – Oldies]
[ti:Let's Twist Again]
[au:Written by Kal Mann / Dave Appell, 1961]
[length: 2:23]

[00:12.00]Naku Penda Piya-Naku Taka Piya-Mpenziwe
[00:15.30]Some more lyrics ...
```

[Refer: LRC (file format) - Wikipedia](https://en.m.wikipedia.org/wiki/LRC_(file_format)#Simple_format)

### Actual behavior

lyrics are not displayed

### Log file

https://0x0.st/-4Rc.txt

**Comment by guidocella** [comment]
mpv recognizes the LRC file you pasted when I try it, so the whole file is needed to reproduce this. Check the output of `ffprobe` on the LRC file; if it's detected with a low score, mpv won't load it unless you lower `--demuxer-lavf-probescore`, for example with `--demuxer-lavf-probescore=1`. Or you can try correcting what makes the score low. The cases I encountered are:

- The first line is a non-standard tag, like `[id:...]` which MiniLyrics used to add. These can be removed with `sed -i '/\[id:/d' *.lrc` (also these have nothing to do with ID3 which are for mp3)

- LRC files encoded in UTF-16. They can be converted to UTF-8 with:
`for lrc in *.lrc; do if file $lrc | grep -q UTF-16; then iconv -f UTF-16 -t UTF-8 $lrc -o $lrc; fi; done`

- The milliseconds are missing. You can add them with `sed -i '/\[[0-9]/s/]/.00]/' foo.lrc`

**Comment by hooke007** [comment]
mpv could render lrc with video files but not with (only) audio files

**Comment by guidocella** [comment]
mpv displays lrc subtitles with audio files just fine.

**Comment by hooke007** [comment]
> mpv displays lrc subtitles with audio files just fine.

cannot reproduce here, if possible please post a sample lrc.

**Comment by guidocella** [comment]
```
[00:00.00]foo
[00:05.00]bar
```

**Comment by Dudemanguy** [comment]
I tried a random mp3 file with ID3 tags + the lrc text in the OP and this worked for me. I will assume this was fixed (another lrc-related issue was closed recently).
