### ISSUE TITLE
`--keepaspect-window` not working in sway

### ISSUE THREAD

**Issue by dobriy88** [mpv-player/mpv#9098]
### Important Information

Provide following Information:
- mpv 0.33.0-283-g8300830951
- Arch Linux
- mpv-git
- sway 1.6.1

https://user-images.githubusercontent.com/43729752/128640118-25c3198b-6400-4f25-aeb2-d3b0a6bdd199.mp4

https://user-images.githubusercontent.com/43729752/128640320-7ae0a362-4433-463f-9920-5939953b9d07.mp4

### Reproduction steps

Play file, make floating window and resize

### Expected behavior
Window keeps aspect of video

### Log file

[sway.txt](https://github.com/mpv-player/mpv/files/6951191/sway.txt)

[i3.txt](https://github.com/mpv-player/mpv/files/6951198/i3.txt)

**Comment by Dudemanguy** [comment]
Just FYI, you can trigger some funky borders in a few cases if you play with the window enough but that's sway not us. Thanks for reporting.
