### ISSUE TITLE
Warning message "unknown key "keyname", ignoring is not clear enough

### ISSUE THREAD

**Issue by TheBestPessimist** [mpv-player/mpv#9105]
### Important Information

Provide following Information:
- mpv version 0.33.0.247 using mpv.net player
- Platform and Version: Windows 10 x64
- Source of the mpv binary: mpv.net provided

### Reproduction steps

In a script options --`ytdl_hook.conf` in my case-- write a wrong property:

`ytdl_path = ytdl`

This is wrong because there should be no spaces around the `=`.

Run mpv from cli, observe the errors and try to understand what you did wrong.

### Expected behavior

I believe it would be more helpful to show quotes around the property name:

```
[ytdl_hook] script-opts/ytdl_hook.conf:1 unknown key 'ytdl_path ', ignoring
```
because in this way it shows me that the property name (in quotes) contains the space.

### Actual behavior

mpv gives the following error:

```
[ytdl_hook] script-opts/ytdl_hook.conf:1 unknown key ytdl_path , ignoring
```

After reading this error, i ignored the `space comma` portion, thinking that it's some weird formatting issue from powershell. I have checked and rechecked multiple times if/why the property name or the script name or location are not OK.

### Solution

I have created the following PR: https://github.com/mpv-player/mpv/pull/9106

**Comment by avih** [comment]
Thanks. Fixed.
