### ISSUE TITLE
video frame sharing

### ISSUE THREAD

**Issue by GongKuiJun** [mpv-player/mpv#9108]
I want shared video frame,Used "https://github.com/leadedge/Spout2" on Windows， or  “Syphon” for  Mac OS ,What do I need to do

**Comment by Akemi** [comment]
that's a very broad question and can't be answered like that, since this needs knowledge about two other project none probably has here.

if you need some opengl texture out of mpv then libmpv is your best bet. otherwise you are on your own if you don't have a specific problem with mpv.
