### ISSUE TITLE
trouble in persian or arabic subtitles

### ISSUE THREAD

**Issue by parsakashani** [mpv-player/mpv#9113]
Provide following Information:
- mpv version: 0.33.1
- macOS Version: 11.5.2
- Source of the mpv binary or bundle: ?
- If known which version of mpv introduced the problem: 0.33.1

### Expected behavior
 
as normal like other versions

### Actual behavior

check boxes instead of persian subtitle and fps drop

i deleted that version so i dont have any logs or screenshots right now but if you need i can do it later

**Comment by Akemi** [comment]
please provide all the information we ask for in the issue template. also this is most likely a libass or font problem and not an mpv one.

**Comment by Dudemanguy** [comment]
Vague issue (likely libass/font) and no log file or other relevant information so closing.
