### ISSUE TITLE
How to check whether it is a keyframe or not?

### ISSUE THREAD

**Issue by mrlogick** [mpv-player/mpv#9116]
How can I check whether mpv is currently playing a keyframe or not? Is there a property or command, with libmpv or lua or something? (I already know how to get the playback-time or seek between keyframes)

**Comment by TheAMM** [comment]
[The manual is a very useful thing to look at.](https://mpv.io/manual/master/#command-interface-video-frame-info)

**Comment by mrlogick** [comment]
Thanks, I searched for hours, how did I not see it?
