### ISSUE TITLE
HDR is extremely broken

### ISSUE THREAD

**Issue by lextra2** [mpv-player/mpv#9117]
Completely broken when in fullscreen mode (see picture 3) and broken when I move my mouse while the video is paused and mpv is focused (see picture 2). The only time HDR actually works is in windowed mode (see picture 1)

01 (windowed, correct look, also checked with VLC which basically looks identical)
![01-Correct](https://user-images.githubusercontent.com/20690384/129435326-c096ca24-9008-4326-be29-7da1ffd43c34.PNG)

02 (this is also how the video looks at all times while windowed if I use `icc-profile-auto`)
![02-Inccorect](https://user-images.githubusercontent.com/20690384/129435336-1d6656f7-c2ee-4bb5-94bc-723e9e1255b3.PNG)

03 (fullscreen, incorrect look)
![03-Incorrect](https://user-images.githubusercontent.com/20690384/129435349-13d29754-4cfd-4ce8-9240-f121e7eac629.jpg)

For all infos on hardware/software please check my logfile
[log.txt](https://github.com/mpv-player/mpv/files/6985953/log.txt)

**Comment by ValZapod** [comment]
Yes, the same happens with these samples. https://trac.ffmpeg.org/ticket/9255#comment:14 Please use CTRL + I screenshots next time. Thanks.

**Comment by lextra2** [comment]
ctrl+i does not capture the issue I think, but I usedit in the last image. thanks.

**Comment by ValZapod** [comment]
> how relevant the issue you linked is to mine

I linked to my comment (14th).

**Comment by Doofussy2** [comment]
This is probably similar to something I reported a while back. https://github.com/mpv-player/mpv/issues/7406 I found a workaround.

**Comment by Doofussy2** [comment]
And you can't use an icc with HDR passthrough, unless it's precisely calibrated for that environment, because is overrides the `target-prim` and `target-trc`. They need to match the Windows swapchain/presenter. Also, because you're just using the standard Windows color mapping:

from your log

```
[   0.045][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 8 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)
[   0.045][v][vo/gpu/d3d11] Selected swapchain format R8G8B8A8_UNORM (28), attempting to utilize it.
[   0.046][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
[   0.046][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: no
[   0.046][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
```
which is 8bit, switching between a window and fullscreen might have undesirable consequences (depending on how the gpu driver deals with these variables).

I have an Nvidia GPU and I always have it configured to match the HDR colorspace. So when I play that video in a window, it's correct.

from my log

```
[   0.136][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)
[   0.136][v][vo/gpu/d3d11] Selected swapchain format R10G10B10A2_UNORM (24), attempting to utilize it.
[   0.137][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
[   0.137][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: yes
[   0.137][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
```
_Note the difference in the swapchain pixel format, and the overlay yes._

I imaging that when the csp can be set at run time, and when @jeeb gets it tightened up, that this will work more automatically.

https://github.com/mpv-player/mpv/issues/8936#issuecomment-874176422

**Comment by Doofussy2** [comment]
So if I set `target-prim=bt.709` and `target-trc=srgb`, I get the same picture as your 02.

![Untitled 5](https://user-images.githubusercontent.com/15950919/129497172-4a6c4f4e-e0e3-49c3-a5c2-162b73e1cac4.png)

This means that those values are what are in the Windows icc (it's sRGB).

The Windows swapchain is set to `d3d11-output-csp=pq` and should also be `d3d11-output-format=rgb10_a2`. So `target-trc=pq` and `target-prim=bt.2020` must also be used, when viewing HDR media. Or the Windows presenter will screw it up. If you were to take a screenshot with mpv, you'll see that the picture is completely different.

**Comment by Doofussy2** [comment]
And I just discovered that setting `d3d11-exclusive-fs=yes` appears to be broken. When it switches to fullscreen, it's clearly losing the HDR metadata. Setting to no, it plays correctly.

[Switching between FS and window.txt](https://github.com/mpv-player/mpv/files/6989189/Switching.between.FS.and.window.txt)

**Comment by haasn** [comment]
Sounds like the solution here would be for mpv to ignore ICC profiles entirely when in HDR output mode? Or perhaps just auto ICC profiles.

**Comment by Doofussy2** [comment]
> Sounds like the solution here would be for mpv to ignore ICC profiles entirely when in HDR output mode? Or perhaps just auto ICC profiles.

I would agree with that assessment. Unless you know what you're doing, don't use an ICC with HDR passthrough. I took a stab at it, a while back. I didn't spend much time on it, but I couldn't make an ICC that would work.

**Comment by Doofussy2** [comment]
The other option (once the csp can be set at runtime) is to make auto-profiles for HDR and SDR, and apply the ICC only for SDR media.

**Comment by lextra2** [comment]
Thanks for your comments @Doofussy2 . I'll test those settings later when I'm home.

**Comment by Doofussy2** [comment]
So just start with

```
target-prim=bt.2020
target-trc=pq
```
And make sure fullscreen exclusivity is set to 'no', which is the default, and don't use any ICC, not even auto

**Comment by lextra2** [comment]
Yep. I'll let you know how it goes.

**Comment by lextra2** [comment]
Nope. Still broken. With everything removed but the following 3 lines in my mpv.conf:
```
d3d11-exclusive-fs=no
target-prim=bt.2020
target-trc=pq
```
I get the following, incorrect look:
(Same as 03 in OP)
![mpv-shot0001](https://user-images.githubusercontent.com/20690384/129654189-fe9fe868-6ba9-4ed3-82fc-9f89fa52e994.jpg)

Funnily enough, printscreen shows how it should look (but not what I'm seeing)
![Printscreen](https://user-images.githubusercontent.com/20690384/129654262-ecdbd5d4-0e04-4633-be38-59b094766f62.png)

**Comment by Doofussy2** [comment]
No. You can't set your GPU to 8bit 4:4:4. You're overriding the settings. First, using 4:4:4 is meaningless. Your media is most likely only 4:2:0. If you think that will improve the quality of the picture, it won't, especially as you are forcing 8bit with dithering. You either need to leave it at default (RGB 8bit), or do what I've done;

![Screenshot 2021-08-16 194221](https://user-images.githubusercontent.com/15950919/129655634-34d88213-95d2-46a7-abb5-cadb1362a47c.jpg)

![Screenshot 2021-08-16 194051](https://user-images.githubusercontent.com/15950919/129655654-271403df-4577-405b-9dfb-ef60da9adc2d.jpg)

**Comment by lextra2** [comment]
1. YCbCr 444 59.94Hz is the default for my TV
2. I already tried all pixel formats; 444, 422 & 420 including RGB full & RGB limited. Nothing made any difference.
3. Dithering is enabled automatically once HDR is toggled.
4. At 60/59.94Hz, 8 bpc is the only allowed color depth for my TV.
5. Like I said, VLC _just works_

**Comment by Doofussy2** [comment]
For 4:4:4 at 59.94Hz, you need to have HDMI 2.1. And if in fact you have HDMI 2.1, then use RGB10. What TV do you have?

**Comment by lextra2** [comment]
Yes my TV and GPU _only_ support HDMI 2.0. TV is Samsung Q60R (2019) & GPU is AMD RX 5700.

4:4:4 8 Bit with 60Hz @2160p works just fine with HDMI 2.0. Also, the TV automatically changes to "PC" mode (Actually, I use Game Mode, but they are almost the same thing)

Appreciate you trying to help me here, but like I said, VLC works just fine (and Chromium works too).

**Comment by Doofussy2** [comment]
I have a Q80R, and I can tell you that your TV needs to be lower than 4:4:4. You need 10bit not 8bit. You're doing something to force a change, and you need to let Windows do what it needs to. I have my TV in PC mode and set to SMPTE, because I have changed the settings in my GPU to make Windows always run in HDR. You should do the same.

**Comment by lextra2** [comment]
You are right. If I use 4:2:0 + 12 Bit @60Hz MPV works in fullscreen. Or when I use 4:2:2 + 10 Bit @30Hz (For what ever reason 60Hz does not allow me to toggle HDR, even though it works for you? and bandwidth should still be enough)

BUT, why does mpv work with no problems while in windowed mode? And why does VLC work right away? The problem here is still mpv and how it handles things. I don't get why I cannot disable exclusive fullscreen for mpv.

**Comment by Doofussy2** [comment]
That's probably due to your GPU and how it interacts with your TV. Could be a driver thing, some kind of API limitation???? But ultimately, it's about bandwidth. HDMI 2.0 doesn't have enough to support that many frames at that resolution. 4:2:2 at 60Hz is pushing the limit, and my cables cost a lot of money :) But 4:2:0 10bit is how the movie mastered, so you aren't losing any quality.

> BUT, why does mpv work with no problems while in windowed mode? And why does VLC work right away? The problem here is still mpv and how it handles things. I don't get why I cannot disable exclusive fullscreen for mpv. 

Well, that might be down to what I pointed out to you, earlier. jeeb has a few things to tweak. You should be able to disable fs exclusivity. I have it disabled. Where did you get your build from?

**Comment by lextra2** [comment]
> 
> 
> Well, that might be down to what I pointed out to you, earlier. jeeb has a few things to tweak. You should be able to disable fs exclusivity. I have it disabled. Where did you get your build from?

https://sourceforge.net/projects/mpv-player-windows/files/ (shinchiro builds) 

`d3d11-exclusive-fs=no` does not work or else this issues wouldn't exist in the first place.

**Comment by Doofussy2** [comment]
I build my own, so maybe you should run a test with that option and attach the log. There's definitely something wrong with it. I already reported that, earlier. But it's the opposite for me. It causes problems when enabled.

**Comment by lextra2** [comment]
Mhh. Yeah maybe there could be something wrong.

Just to clarify:
`d3d11-exclusive-fs=no`
should be identical to
```
window-maximized
no-border
```
which it certainly is not.

**Comment by ValZapod** [comment]
> You can't set your GPU to 8bit 4:4:4

You can select HDR on both YCbCr 4:4:4 8 bit and RGB 8 bit. RGB 8 bit HDR does not work on Sony, here only YCbCr 4:4:4 works. YOU CANNOT SELECT HDR on 4:2:0 8 bit, Nvidia does allow that, but LG (C9) does not. HDR is thus supported for 8 bit. Even 8 bit files are supported by LG C9 player to have HDR signaled by PQ. 

> especially as you are forcing 8bit with dithering

That means little, Nvidia activates dither on a lot of things, including limited RGB.

**Comment by Doofussy2** [comment]
> Mhh. Yeah maybe there could be something wrong.
> 
> Just to clarify:
> `d3d11-exclusive-fs=no`
> should be identical to
> 
> ```
> window-maximized
> no-border
> ```
> 
> which it certainly is not.

No, those are different things.



> > You can't set your GPU to 8bit 4:4:4
> 
> You can select HDR on both YCbCr 4:4:4 8 bit and RGB 8 bit. RGB 8 bit HDR does not work on Sony, here only YCbCr 4:4:4 works. YOU CANNOT SELECT HDR on 4:2:0 8 bit, Nvidia does allow that, but LG (C9) does not. HDR is thus supported for 8 bit. Even 8 bit files are supported by LG C9 player to have HDR signaled by PQ.
> 

But it clearly doesn't actually work. It's breaking his functionality, and loses the HDR metadata. And in my case, my GPU won't even allow me to use 4:4:4 at 60Hz. You have to use 30Hz, and then you might as well use RGB10. It's the same with 8bit. Why use 4:4:4 when you can leave it in RGB? I change everything to 10bit or higher because there are too many glitches in mpv to leave everything at default.

**Comment by ValZapod** [comment]
> GPU won't even allow me to use 4:4:4 at 60Hz.

Yes, and RTX 3090 allows 12 bit 120 Hz RGB/YCbCr 444 12 bit (HDR or SDR) WITH Atnos in TrueHD on my LG C9 and so what (that is 48 gbit/s, all of it)? It is your problem.

> Why use 4:4:4 when you can leave it in RGB?

RGB is 1/6 of size of YCbCr, that is why. Google xvYCC. Superwhite and extended gamut is comonly present in videostreams. LG C9 support that (or at least Superwhite) since v4 firmware even in internal player. Surprise. Also there is no way to convert RGB 8 bit to YCbCr 8 bit, 10 bit YCbCr is needed to present precision is much bigger YCbCr space.

**Comment by Doofussy2** [comment]
> > GPU won't even allow me to use 4:4:4 at 60Hz.
> 
> Yes, and RTX 3090 allows 12 bit 120 Hz RGB (or YCbCr 444) (HDR or SDR, yeah, SDR 10 bit I did actually test, cool) WITH Atnos in TrueHD on my LG C9 and so what (that is 48 gbit/s, all of it)? It is your problem.

Yeah, the RTX 3000s have HDMI 2.1, neither of us have one, and our TVs also have HDMI 2.0 so we're stuck with the HDMI 2.0 limitations. So no 10bit 4:4:4. 

I agree, as most media is released in 4:2:0 it makes sense to operate with the same parameters, or higher.

**Comment by ValZapod** [comment]
> released in 4:2:0 it makes sense to operate with the same parameters

Or 4:4:4 YCbCr. Conversion from 4:2:0 is lossless (if not count some problems with out-of-gamut pixels DUE to actual subsampling, AND ALSO there is no ANY dumb problem with 6 different types of chroma siting in particular the main problem is top left for BT.2020 and BT.2100 in HEVC vs left for AVC/BT.709). For example Xbox X supports sending PERFECT 4:2:0 10 bit in HDR even in 60 fps (there is a problem with integer and non-integer framerate though, Xbox only support non-integer, what a joke).

**Comment by lextra2** [comment]
> > Mhh. Yeah maybe there could be something wrong.
> > Just to clarify:
> > `d3d11-exclusive-fs=no`
> > should be identical to
> > ```
> > window-maximized
> > no-border
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which it certainly is not.
> 
> No, those are different things.

How are they different? There is only 3 types of windows: 1. Exclusive Fullscreen, 2. Windowed Fullscreen (without borders) and 3. Windowed (with borders) And 2. is only possible via my solution.

**Comment by Doofussy2** [comment]
The d3d11 gives full control of the rendering to mpv, and simply making the window borderless, doesn't. Especially as we're referring to the Windows swapchain.

**Comment by lextra2** [comment]
Exactly. MPV does behave abnormal, when compared to other apps.

`d3d11-exclusive-fs=no`

**should** be the same as 

```
window-maximized
no-border
```
anything else is just missleading, because as I've listed, there are only 3 types of windows.

**Comment by Doofussy2** [comment]
No, they shouldn't. It's specific to d3d11. What would happen if you used vulken? It's an entirely different swapchain.

**Comment by lextra2** [comment]
All vulkan apps are always forced to exclusive (amd driver "bug")

And having a setting that says "exclusive fullscreen = no" do anything but make the window not exclusive is just missleading.

**Comment by Doofussy2** [comment]
> And having a setting that says "exclusive fullscreen = no" do anything but make the window not exclusive is just missleading.

I don't understand this statement. It simply disables it, and it works as it should. At least it does for me.

**Comment by lextra2** [comment]
It does not work for me, because it does not achieve the same behavior as the solution I've spoken about.

**Comment by Doofussy2** [comment]
And I suggested that you recreate the issue and attach the log. Maybe even start a new issue report?

**Comment by lextra2** [comment]
Yeah I might do that later. Been thinking about it. But like I said, might be driver dependend.

**Comment by Doofussy2** [comment]
Well, there is an issue I have with it when enabled, so that could be related. If you don't make a separate report, I'll try to make one when we get home.

**Comment by ValZapod** [comment]
> The d3d11 gives full control of the rendering to mpv, and simply making the window borderless

Do I wanna know whether 3 frame new fullscreen and its turning off via "disable fullscreen optimisation" affects this in any way?

**Comment by lextra2** [comment]
> 
> 
> > The d3d11 gives full control of the rendering to mpv, and simply making the window borderless
> 
> Do I wanna know whether 3 frame new fullscreen and its turning off via "disable fullscreen optimisation" affects this in any way?

Yes. Disabling fullscreen opti fixed it, which is why I closed the other thread. HDR is still broken though.

**Comment by ValZapod** [comment]
> Yes. Disabling fullscreen opti fixed it,

Oh, god.

**Comment by ValZapod** [comment]
Okay, so bad news. gpu-next default vulkan does not support HDR, it only tonemaps to SDR and gpu-next's d3d11 context does support HDR pq swapchain but HAHA, the swapchain that defines the colorspace is not propogated to target-*, so you must use target-trc=pq and target-prim=bt.2020!! This is just a bug in vo gpu-next, does not happen in vo gpu. Bug is on both HDR10 and Dolby Vision.

What I used is 24 fps RGB 12 bit. Yeah, I know. But it works. Including 10 bit SDR in SDR windows.

**Comment by lextra2** [comment]
Good to know. But I'd prefer a way that works without me having to manually change bit depth and refresh rate.

**Comment by lextra2** [comment]
@haasn 
Still broken with `vo=gpu-next`
MPV needs to read "8-bit with dithering" as 10-bit (because it is effectively 10-bit). MPV should automatically assume 10-bit if HDR is enabled. _This is what this issue is about._ It works for VLC because they do exactly that.

See this image for what I mean with 8bit dithering.

![Capture](https://user-images.githubusercontent.com/20690384/156799959-5632335e-86a4-458c-868e-af8daa4da3f0.JPG)

**Comment by Hrxn** [comment]
Is there any official Windows documentation that further explains and confirms these display options and settings?

**Comment by Doofussy2** [comment]
> @haasn Still broken with `vo=gpu-next` MPV needs to read "8-bit with dithering" as 10-bit (because it is effectively 10-bit). MPV should automatically assume at least 10-bit if HDR is enabled. _This is what this issue is about._ It works for VLC because they do exactly that.
> 

So this is with passing the metadata to the display? Have jeeb and rossy finished that implementation for d3d11?

**Comment by lextra2** [comment]
> So this is with passing the metadata to the display? Have jeeb and rossy finished that implementation for d3d11?

A.
Here is what works:
- Manually selecting 30Hz (or lower) inside windows settings and
- Manually selecting 10bit inside amd settings. Now
- Colors work, even when in fullscreen (which is where passthrough matters)

B.
Here is what still doesn't work
- Going fullscreen with 60Hz & 8bit+dithering
- Direct passthrough sees 8bit and reverts to sdr, resulting in a washed out look

B works just fine in windowed view as long as I specify the correct target-prim & target-trc.

Like I said, mpv sees 8bit what in reality is 10bit dithered.

**Comment by Doofussy2** [comment]
Ah, yeah now I understand. That makes sense. I wonder if the swapchain may be being set to srgb?

`--d3d11-output-csp=srgb` instead of `pq`

https://mpv.io/manual/master/#options-d3d11-output-csp

**Comment by lextra2** [comment]
> Ah, yeah now I understand. That makes sense. I wonder if the swapchain may be being set to srgb?
> 
> `--d3d11-output-csp=srgb` instead of `pq`
> 
> https://mpv.io/manual/master/#options-d3d11-output-csp

Well damn. This fixes it. Thank you very much!

**Comment by Doofussy2** [comment]
Groovy! Yeah, that is automatically set, but I find it's less than perfect. So I have it always set to `pq` in the conf.
