### ISSUE TITLE
Segmentation Fault - Wayland - Detection of virtual keyboard 

### ISSUE THREAD

**Issue by Eluminae** [mpv-player/mpv#9119]
### Important Information

```
$ mpv --version
mpv 0.33.1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Apr  5 16:57:51 UTC 2021
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: 4.3.2
$ lsb_release -a
LSB Version:	1.0
Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void
```

### Reproduction steps

In Sway (should be the same in any Wayland WM that support virtual keyboard (everyone?))

- Open two terminal
- In the first terminal type `mpv afile.wathever`
- Do not type Return
- In the second terminal type `wtype -s 1000 -k Return`
- Press enter then focus the first terminal with your mouse or keyboard

```
Segmentation fault
```

I think that mpv rely on the wayland virtual keyboard that wtype created but this keyboard was just temporary.

**Comment by Dudemanguy** [comment]
>I think that mpv rely on the wayland virtual keyboard that wtype created but this keyboard was just temporary.

Yup. That's exactly it. The fix is simple too. Thanks for the report!
