### ISSUE TITLE
lavfi-filter: reliably getting the external-file

### ISSUE THREAD

**Issue by skinkie** [mpv-player/mpv#9121]
I am overlaying a program logo on top of a video. I am using --external-file=/tmp/proglogo.png --lavfi-complex="[vid1][vid2]overlay=main_w-270:50[vo]" for this effort.

Recently I received a video that contains an extra mjpeg frame, a thumbnail. This causes vid2 to be the _thumbnail_, instead of the _external-file_.

How can you reliably get the external-file in lavfi-filter?

[output.txt](https://github.com/mpv-player/mpv/files/6987815/output.txt)

**Comment by skinkie** [comment]
@kasper93 what commit did complete it?

**Comment by kasper93** [comment]
> what commit did complete it?

The issue tracker is not for questions or discussions. Also questions are not generally answered by commits.
