### ISSUE TITLE
Default window frame

### ISSUE THREAD

**Issue by srezasm** [mpv-player/mpv#9127]
Is there any way to configure MPV to use the Linux default windows frame?   
So it will be like this:
![image](https://user-images.githubusercontent.com/45644975/129539837-9643756b-7cfd-448d-933d-32276c4d6498.png)

Not this:
![image](https://user-images.githubusercontent.com/45644975/129540412-392d28d2-e48c-404d-9e74-5b25c77afa16.png)

**Comment by avih** [comment]
No. The window decorations is controlled by the environment, which is Windows itself in your case.

On some versions of Windows you can patch the windows theme - which would affect mpv windows as well, but that's outside the scope or control of mpv itself.
