### ISSUE TITLE
No sound device after pause, play

### ISSUE THREAD

**Issue by TheBestPessimist** [mpv-player/mpv#9128]
### Important Information

Provide following Information:
- mpv version 0.33.0-302 build 2021-08-15 x64 lib from sourceforge
- Windows Version 10 21H1 x64
- Source of the mpv binary  mpv.net player, 
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

### Reproduction steps

1. Play a video. Everything is all right: the mpv plays with correct video, audio and subs 

3. after a few seconds of playback press pause (space in my case) to pause playback
4. after a few seconds press pause (space in my case) again to resume playback

### Expected behavior

After resuming playback, the same audio (or video or subtitle) is still selected, as if "nothing was changed". "Audio: no audio" should not happen.

### Actual behavior

After pressing <kbd>Space</kbd>to resume, the playback resumes only after 5-10 seconds, but the audio track is disabled. I have to manually select again the correct track.

When playback finally starts, if I select the track manually after 1-2 seconds, sound starts playing for about 2 seconds, then resets back to "no audio track". If waiting for more than 5 seconds before selecting the correct audio track, then the playback works correctly and with sound.

This happens with `--no-config` as well.

I think this happens at least since start of August, maybe even sooner.

### Log files

Log file1: 

The issue happens right at the end of the log: i paused for about 1 minute, then resumed and there was no sound.
[mmmmmmmmmmmmmmmmmpv.7z.txt](https://github.com/mpv-player/mpv/files/7021831/mmmmmmmmmmmmmmmmmpv.7z.txt)  (it's a 7z file. i made it txt to please github)

Log file 2:

The issue happens right after i start a youtube video, while the video started buffering. After buffering finishes, there is no sound. The audio track is disabled.

[mmmmmmmmmmmmmmmmmpv - while buffering youtube.7z.txt](https://github.com/mpv-player/mpv/files/7022348/mmmmmmmmmmmmmmmmmpv.-.while.buffering.youtube.7z.txt)

**Comment by hooke007** [comment]
It's not the log file devs want. you can use the option `log-file="~~desktop/mpv.log"` to generate it.

https://mpv.io/manual/master/#options-log-file

**Comment by TheBestPessimist** [comment]
Closing as i am unable to reproduce. will reopen if it happens.

**Comment by TheBestPessimist** [comment]
Reopened as i reproduced the issue and have logs

**Comment by TheBestPessimist** [comment]
Added a second log with a youtube video

**Comment by Dudemanguy** [comment]
Is this still a problem on 0.36?

**Comment by TheBestPessimist** [comment]
Hello, I don't think it's a problem anymore, or maybe i fixed it via one of my scrips. 
Closed!

**Comment by Bazian** [comment]
Started facing this issue recently . Running extra/mpv 1:0.37.0-3  on an arch system
