### ISSUE TITLE
--d3d11-exclusive-fs does not work

### ISSUE THREAD

**Issue by lextra2** [mpv-player/mpv#9132]
### Important Information
OS: Windows 10 21H1
GPU: AMD Radeon RX 5700 & 21.6.2 WHQL Driver

### Reproduction steps
Use `d3d11-exclusive-fs=yes` or `no`

### Expected behavior
MPV should have the same behavior as when using

```
window-maximized
no-border
```

### Actual behavior
Fullscreen always does its own thing.

### Log file
I'll add a logfile soon.

### Additional info
Some talk on the issue can be found here:
https://github.com/mpv-player/mpv/issues/9117#issuecomment-900071462

**Comment by ValZapod** [comment]
BTW, it is even worse here! It activates 120 fps 4:2:0 8 bit mode which is kinda very bad since it is only supported since LG CX and LG C9 has broken picture in that, just noise.
