### ISSUE TITLE
bar doesn't display progress when using `osd-back-color`

### ISSUE THREAD

**Issue by lokesh-krishna** [mpv-player/mpv#9134]
### Important Information

Provide following Information:
- mpv version: 0.33.1-dirty
- Linux Distribution and Version: Arch Linux 
- Source of the mpv binary: Arch Linux Packages
- If known which version of mpv introduced the problem
- Window Manager and version: sway 1.6.1
- GPU driver and version: mesa 21.1.6-1
- Possible screenshot or video of visual glitches:
![grim-18-08-2021-13-31-02](https://user-images.githubusercontent.com/20235646/129861262-fef335aa-9781-45a6-babf-5bb45c6cb92c.png)

### Reproduction steps
Launch mpv with `mpv --no-config --osd-back-color='#<insert-color>' <filename>`

### Expected behavior
Bar shows progress 

### Actual behavior
Bar shows specified background but no progress

### Log file
https://0x0.st/-y9r.log

**Comment by uberRegenbogen** [comment]
Duplicated in mpv 0.30.0.  Additionally, setting an alpha value (e.g. `--osd-back-color='#CC888888')` allows the bar to appear through the colour.  (It's as if the bar is being drawn behind the background.)
