### ISSUE TITLE
Memory leak when set hwdec to auto

### ISSUE THREAD

**Issue by DaZiYuan** [mpv-player/mpv#9138]
I made a demo here:
https://github.com/DaZiYuan/mpv_memory_leak_test

if I call player.stop() before playing video, the memory will increase hugely.

![image](https://user-images.githubusercontent.com/80653/129915025-90f8d925-5165-4e13-a999-931e39308e29.png)

I remove that code, the memory increase will slowly. but it still seems to have a little memory leak.

![image](https://user-images.githubusercontent.com/80653/129915409-60037ad9-cd62-40f1-b72c-6e5cbfb5fdb4.png)
![image](https://user-images.githubusercontent.com/80653/129915773-5a144817-8fd7-4ca8-bcef-6c255c1e7bb4.png)

If I set hwdec to no, the problem disappears

https://github.com/hudec117/Mpv.NET-lib-/issues/27

**Comment by ValZapod** [comment]
Why do you think the bug is in mpv?

**Comment by Dudemanguy** [comment]
Highly unlikely to be an mpv issue. Sounds like an issue with that NET lib.
