### ISSUE TITLE
Can't get the `path` and `time-pos` when `end-file` event happens

### ISSUE THREAD

**Issue by snowman** [mpv-player/mpv#9148]
## steps to reproduce 

```lua
-- FILE: /tmp/record_played_time.lua

mp.register_event('end-file', function()
   local path = mp.get_property('path')      -- always return nil
   local time = mp.get_property('time-pos')  -- always return nil
         time = math.floor(time)             -- error, variable "time" is nil

   local historyLog = io.open("mpvHistory.log", 'a+')
   historyLog:write(('%s%s\n'):format(path, '#time=' .. tostring(time)))
   historyLog:close()
end)
```

```sh
$ cd /tmp

# copy above script into record_played_time.lua

# generate sample video for testing
$ ffmpeg -f lavfi -i testsrc -t 5 sample.mp4

# press q to stop playing and quit
$ mpv --msg-level=all=error --no-config --script=record_played_time.lua sample.mp4
[record_played_time] Lua error: [string "record_played_time.lua"]:4: bad argument #1 to 'floor' (number expected, got nil)
```

## Expected

I want to write script that logging played video with time into file when user quit video or switch video.
But it always return `nil` when `end-file` event happens.

so how to get the property `path` and `time-pos` when quit or switch video file?
maybe a new `before-end-file` event? 
thanks!

**Comment by avih** [comment]
> But it (the properties time-pos, path) always return `nil` when `end-file` event happens.

That's because the `end-file` event is sent AFTER the file was unloaded. These properties no longer refer to the file. Read the docs https://mpv.io/manual/master/#command-interface-mpv-event-end-file

You might want to use the `on_unload` hook instead - https://mpv.io/manual/master/#command-interface-on-unload

**Comment by snowman** [comment]
```lua
mp.add_hook('on_unload', 50, function()
   local path = mp.get_property('path')
   local time = mp.get_property('time-pos')

   local historyLog = io.open("mpvHistory.log", 'a+')
   historyLog:write(('%s%s\n'):format(path, '#time=' .. tostring(math.floor(time))))
   historyLog:close()
end)
```

Thank you!!

now it works perfectly
