### ISSUE TITLE
[Request] reset playing position if quitting when only 5% of playback time left

### ISSUE THREAD

**Issue by kopurando** [mpv-player/mpv#915]
Thanks for such a great player, finally we have a (much) better VLC alternative!

While remembering playback position on quit is very helpful, it becomes an annoyance when one quits mpv near the end of a file, i.e. last seconds (or minutes for long files), when it's clear the clip is over and nothing else left to see... On re-opening, mpv will jump to these last unplayed seconds of the file. Now rewind and play again :)

Would be nice to have some threshold to ignore last unplayed part (5% sounds reasonable for most cases) or simply an on-off setting for such behaviour.

Regardless, thanks for your work!

**Comment by kn666** [comment]
> It _was_ implemented, but then ChrisK2 complained, and it was removed.

could this be added back as an option? Also it'd be nice to autorewind when pressing play at the end.

**Comment by Argon-** [comment]
You can do this using a script. I'm using my own: https://github.com/Argon-/mpv-config/blob/master/scripts/auto-save-state.lua
It will always save the state when it's a playlist. When it's not a playlist it will never save state for a small file (<5 Minutes) and only when your current playback position is > 1 minute and < 3 minutes.
