### ISSUE TITLE
How to start mpv window without specify file?

### ISSUE THREAD

**Issue by snowman** [mpv-player/mpv#9150]
The following command not working:

```sh
$ mpv --keep-open=always
```

But with `vlc` player, you can directly run `vlc` then later drag and drop files to play.

**Comment by guidocella** [comment]
Use `mpv --force-window --idle`.

**Comment by snowman** [comment]
Thank you, it works!!

**Comment by sergiomb2** [comment]
we don't have anything more simpler ? I don't understand why running mpv without parameters doesn't do the same

**Comment by guidocella** [comment]
Because mpv is a command line program and you don't always want to create a window.
