### ISSUE TITLE
opening from jdownloader doesnt work if vo=gpu or hwdec=auto set

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#9151]
### Important Information

Provide following Information:
- mpv version
- mpv 0.33.1
- Linux Distribution and Version
- archlinux rolling release
- Source of the mpv binary
- distro repos

- Window Manager and version
- kwin
- GPU driver and version
- intel mesa 21.2.1-1

### Reproduction steps

use jdownloader to download video (maybe from youtube)
add these line to mpv config
vo=gpu
 hwdec=auto
try to open videos from jdownloader by double clicking on them

### Expected behavior
videos should open with mpv

### Actual behavior
mpv opens in background (shell maybe, no window is shown) 
and closes 

### Log file

[somefilename.log](https://github.com/mpv-player/mpv/files/7036048/somefilename.log)

more info:

if I comment out both of those options (vo=gpu , hwdec=auto) then eveything works.
but if one of them is applied the mpv doesnt work.

I can open the video from file manager directly without commenting out the options.
they only affect this jdownloader app it seems.
I had this issue before and reported it https://github.com/mpv-player/mpv/issues/6916 almost two years ago but at that time I didnt know what caused it (any option) or if even it is the same as this issue that I am reporting now.

**Comment by rezad1393** [comment]
bump:

I have added three logs here.

one is opening from terminal the video file with hwdec=vaapi which works.
one is opening from jdownloader the video file with hwdec=vaapi  which doesnt work.
one is opening from jdownloader the video file with hwdec=vaapi commneted out  which  works.
[from-cmd.log](https://github.com/mpv-player/mpv/files/7248769/from-cmd.log)
[jdownloader-with-hwdec.log](https://github.com/mpv-player/mpv/files/7248770/jdownloader-with-hwdec.log)
[jdownloader-without-hwdec.log](https://github.com/mpv-player/mpv/files/7248772/jdownloader-without-hwdec.log)

when I compare the forst and second I see that they are very similar but in the second one mpv doesnt open. just an icon in task manager opens with is a visual feedback from kde-plasma desktop and not indicator of a windows being used.

can someone help debug this issue?

**Comment by Dudemanguy** [comment]
I'm not really sure what "opening from jdownloader" means, but I would assume it's a jdownloader issue.

**Comment by rezad1393** [comment]
I have added the log for the file opening for both conditions.
mpv opens the video file but doesnt show anything and just as fast the process closes.
if this is not mpv issue I dont know what it is.

**Comment by Dudemanguy** [comment]
If opening the file with mpv from cmd works but not opening from jdownloader (I still have no idea what this means) I don't see how this isn't a jdownloader problem.

**Comment by rezad1393** [comment]
as I explained it only happens with mpv (not vlc ) 
and other apps with open their files when click from jdownloader.
and mpv opens videos too if I dont set none of those two setting ( (vo=gpu , hwdec)
but it doesnt play them if one if set.
as I attacked the log file, jdownloader send the file location on filesystem to mpv, but mpv (with either of those two setting set) doesnt play them.
the log shows that mpv gets the files.
but nothing is played on screen and mpv process closes just after loging the log.

**Comment by pintassilgo** [comment]
I can reproduce this issue.

mpv v0.34.1 and latest JDownloader. I use Manjaro KDE X11, my GPU is Radeon RX 570.

I'm unable to open mpv from JDownloader unless I remove `hwdec=auto`. VLC opens just fine.

Reported in JDownloader forum:
https://board.jdownloader.org/showthread.php?p=500023

**Comment by rezad1393** [comment]
I have tested with mpv-git on archlinux and it doesn't have this issue anymore.
so I was right. this was a mpv issue not a jdownloader issue.

**Comment by Hrxn** [comment]
Or an xdg issue?

**Comment by pintassilgo** [comment]
The issue is restricted to mpv, other default applications like VLC opened from JDownloader run just fine, so I guess it is (or was) mpv fault.

**Comment by rezad1393** [comment]
> I have tested with mpv-git on archlinux and it doesn't have this issue anymore. so I was right. this was a mpv issue not a jdownloader issue because the mpv 0.34.1 still has that issue.

guys, read my last post.
as I have said when I install mpv from git the issue is gone.
so I know this was a mpv issue but maybe we just need to wait for new release.

that guy at the top said "If opening the file with mpv from cmd works but not opening from jdownloader (I still have no idea what this means) I don't see how this isn't a jdownloader problem." so now it seems that was wrong.

but anyway, this issue is seems to be fixed (or removed) in git.

**Comment by avih** [comment]
Most probably you have some env vars set by your shell init script (e.g. `~/.bashrc` if you use bash) which allow mpv to use hwdec, and these vars are not set when launching via some application (because it doesn't run the shell init script).

So you need to figure our env var differ.

It could also help if you posted two logs playing the same file: one where it's launched from the shell and hwdec works, and one where it's launched from the app and hwdec doesn't work.

**Comment by rezad1393** [comment]
> It could also help if you posted two logs playing the same file: one where it's launched from the shell and hwdec works, and one where it's launched from the app and hwdec doesn't work.

I did include logs? 
https://github.com/mpv-player/mpv/issues/9151#issuecomment-929818892

also if it is not mpv issue then which app is it?
vlc works.
picture viewer works.
mpv with mpeg1 video works.
only mpv with hwdec doesnt work.
also mpv with git works (or at least worked I need to test again.)
I think it is maybe a compile flag that differs between mpv-git and mpv from archlinux-repo.
I will test more and report back.

**Comment by avih** [comment]
> I did include logs?
> [#9151 (comment)](https://github.com/mpv-player/mpv/issues/9151#issuecomment-929818892)

These logs are for mpv 0.33, which is from November 2020, so about two years old now, and probably irrelevant at this stage.

New logs could help.

The bottom line is that hwdec does work on your system from CLI, and apparently doesn't work when launched from some applications. So something must be different, but it's your system and we don't know how these invocations differ.

I offered some suggestions: shell init script setup (e.g. maybe it sets up `$PATH` differently, or some vars, etc) and/or different command line options. You need to figure out how the invocations differ, and with up-to-date logs maybe someone could try to find such differences too.

**Comment by rezad1393** [comment]
it works in dolphin file manager (kde file manager).
but please wait for my mpv-git to compile and for me to test. 
I will report back.

**Comment by rezad1393** [comment]
I tested.
mpv-git from  https://aur.archlinux.org/packages/mpv-git works.
mpv from archlinux repos doesn't work.
I need to compre build config files of them to see the issue.

**Comment by avih** [comment]
You can save this as `envlog.lua` in your `scripts/` dir, which will log all the env values, so it could help you figure out what's different:
```lua
local env = require("mp.utils").get_env_list()
table.sort(env)

for _,e in ipairs(env) do
    mp.msg.verbose(e)
end
```

**Comment by rezad1393** [comment]
> 

and where can I see them?

**Comment by avih** [comment]
> and where can I see them?
> the output of the script I mean.

At the log file. You can change `verbose` to `info` to show it also at the terminal, but assuming launching from other applications is without a terminal, I thought log-only would be best. Feel free to change it.

**Comment by avih** [comment]
> how can it be the env var issues if with mpv-git it is gone.

Because maybe different versions of mpv treat env vars differently. For instance, IIRC there were some XDG related changes in mpv in recent years.

**Comment by rezad1393** [comment]
I have dont test with two versions (git from aur-arhclinux and official one from archlinux main repo)
and did both with folders opened from file manager and from qdirstat.


[launched from qdirstat.log](https://github.com/mpv-player/mpv/files/10226053/launched.from.qdirstat.log)
[launched from file manager.log](https://github.com/mpv-player/mpv/files/10226054/launched.from.file.manager.log)
[launched from qdirstat-git.log](https://github.com/mpv-player/mpv/files/10226055/launched.from.qdirstat-git.log)
[launched from file manager-git.log](https://github.com/mpv-player/mpv/files/10226056/launched.from.file.manager-git.log)

**Comment by avih** [comment]
> this one is the one that doesn't work.
> [launched from qdirstat.log](https://github.com/mpv-player/mpv/files/10226053/launched.from.qdirstat.log)

This log seem incomplete. It ends with:
```
...
[   0.072][v][vo/gpu] Loading hwdec drivers for format: 'cuda'
[   0.072][v][vo/gpu] Loading hwdec driver 'cuda'
```

Is this the whole file? If yes, then it looks like a crash, but hard to tell where, maybe at the driver when probing for cuda?

**Comment by avih** [comment]
FWIW, one difference I can see is that the bad/crash launch is with `PWD=/home/me/.var`, while the good one is with `PWD=/home/me`, but I have no idea how this could affect crash during cuda probing.

**Comment by rezad1393** [comment]
> FWIW, one difference I can see is that the bad/crash launch is with `PWD=/home/me/.var`, while the good one is with `PWD=/home/me`, but I have no idea how this could affect crash during cuda probing.

That point is not important.
I just used qdirstat on home directory and then opened a random folder from it, in this case .var,  and then went to home folder in the new opended instance of file manager and opened the same video file.

I think the issue is with compile flags difference between git version and the main version compiled by archlinux team.

When I get back home i will create a test bed and step by step add/remove the flags till I get a working main version or  non-working git version.

Have  a good day.

**Comment by avih** [comment]
> I think the issue is with compile flags difference between git version and the main version

But these two builds are of the same version, right? and still the first crashes and the second works, right?
[launched from qdirstat.log](https://github.com/mpv-player/mpv/files/10226053/launched.from.qdirstat.log)
[launched from file manager.log](https://github.com/mpv-player/mpv/files/10226054/launched.from.file.manager.log)

So even if it's also affected by some build options, you still also have an issue where with the same build some invocations crash and some don't, and I think it would be more beneficial to understand why this happens.

Regardless, if you do identify which build options affects it, then it would be useful info as well.

**Comment by rezad1393** [comment]
> > I think the issue is with compile flags difference between git version and the main version
> 
> But these two logs are from the same build/binary, right? and still the first crashes and the second works, right? [launched from qdirstat.log](https://github.com/mpv-player/mpv/files/10226053/launched.from.qdirstat.log) [launched from file manager.log](https://github.com/mpv-player/mpv/files/10226054/launched.from.file.manager.log)
> 
> So even if it's also affected by some build options, you still also have an issue where with the same build some invocations crash and some don't, and I think it would be more beneficial to understand why this happens.
> 
> Regardless, if you do identify which build options affects it, then it would be useful info as well.

Yes and that is my point.
The same software behaves differently in two situation.
And git version with different build works in those two situation.
So if i can find a build option or git commit that before and after causes this, that would be better.
It may be  a git commit in mpv too because i remmeber commit testing the build and seeing it sometimes work.

Again, I cant test or type on my phone so i will test tomorrow .
