### ISSUE TITLE
macOS window title becomes garbled codes

### ISSUE THREAD

**Issue by qin9125** [mpv-player/mpv#9156]
![image](https://user-images.githubusercontent.com/32502941/130803495-c7aaaae2-e77c-444c-b78f-1f846dcd9f7c.png)
![image](https://user-images.githubusercontent.com/32502941/130803642-6ec76a60-f356-4175-bb60-a84f88e36fb1.png)
HI ,Chinese character file name and title are garbled
what should I do? Thank you.

**Comment by Akemi** [comment]
please don't ignore the issue template and provide als the info we ask for.
