### ISSUE TITLE
--lavfi-complex hstack and loop vid2?

### ISSUE THREAD

**Issue by matteomattei** [mpv-player/mpv#9158]
I am trying to play a rtsp stream together with a static video file side by side and it works fine:

`mpv --lavfi-complex="[vid1][vid2]hstack[vo]" rtsp://admin:xxxxxxx@192.168.1.64:554/h264_stream --external-file=/tmp/1.avi`

vid1 is an infinite stream because it reads from an IP cam over rtsp, but vid2 is a static file.
I want vid2 (1.avi file) to be played in loop.

I tried with `--loop-file=inf` and `--loop-playlist=inf` but it does not work.
I guess there is something to add into --lavfi-complex string...

Is there a way to do it?

**Comment by thebombzen** [comment]
@matteomattei
You're probably better off reading from ffmpeg from a pipe. Something like this:
```
ffmpeg -stream_loop -1 -i /tmp/1.avi -c copy -f mpegts - | mpv mpv --lavfi-complex="[vid1][vid2]hstack[vo]" rtsp://admin:xxxxxxx@192.168.1.64:554/h264_stream --external-file=-
```

**Comment by thebombzen** [comment]
You could also do it entirely from within FFmpeg.
```
ffmpeg -i rtsp://admin:xxxxxxx@192.168.1.64:554/h264_stream -stream_loop -1 -i /tmp/1.avi -map 0 -map 1  -c copy -f mpegts - | mpv -
```

**Comment by matteomattei** [comment]
> @matteomattei
> You're probably better off reading from ffmpeg from a pipe. Something like this:
> 
> ```
> ffmpeg -stream_loop -1 -i /tmp/1.avi -c copy -f mpegts - | mpv --lavfi-complex="[vid1][vid2]hstack[vo]" rtsp://admin:xxxxxxx@192.168.1.64:554/h264_stream --external-file=-
> ```

This works fine!!! Thank you!!!
