### ISSUE TITLE
fail build with ffmpeg master

### ISSUE THREAD

**Issue by sl1pkn07** [mpv-player/mpv#9159]
### mpv version and platform versions

7314253180e7c5d06bec6d1fed79ce92bff4b6be in archlinux
3e24e8108d62eeee5453aee206370a273ab12a24 ffmpeg

### Reproduction steps

build mpv by using mpv-build script with ffmpeg master branch

### Expected behavior

build ok

### Actual behavior

fail build

### Log file

https://0x0.st/-t9V.txt
~~~
[ 59/529] Compiling player/sub.c
../demux/demux_lavf.c: In function 'update_read_stats':
../demux/demux_lavf.c:273:31: error: 'AVIOContext' has no member named 'bytes_read'
  273 |         int64_t cur = nest->id->bytes_read;
      |                               ^~

Waf: Leaving directory `/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
~~~

greetings

**Comment by rmkimathi** [comment]
> A workaround is to use the following configure option:
> 
>     --enable-ffmpeg-strict-abi
>                         enable Disable all known FFmpeg ABI violations

works in mpv_options
