### ISSUE TITLE
Expand "~" to "$HOME" automatically in Linux

### ISSUE THREAD

**Issue by not-null-nil** [mpv-player/mpv#9161]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
`mpv Somewhere.in.Time.1980.1080p.BluRay.x264-HD4U.mkv --sub-file=~/Downloads/Somewhere.in.Time.ass`
gives:
```[file] Cannot open file '~/Downloads/Somewhere.in.Time.ass': No such file or directory
Failed to open ~/Downloads/Somewhere.in.Time.ass.
Can not open external file ~/Downloads/Somewhere.in.Time.ass.
```
But 
```
mpv Somewhere.in.Time.1980.1080p.BluRay.x264-HD4U.mkv --sub-file=$HOME/Downloads/Somewhere.in.Time.ass
```
can work.
Is it possible to expand `~` to `$HOME` automatically in Linux?
### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to [Log](https://0x0.st/-t4Q.txt) or attach it to the github issue, and replace this text
with a link to it.

**Comment by haasn** [comment]
`setopt magicequalsubst`

**Comment by C-Entropy** [comment]
Thank you!
