### ISSUE TITLE
AB-Loop with exact seek

### ISSUE THREAD

**Issue by vommie** [mpv-player/mpv#9169]
Is it possible to use ab-loop with exact seek instead of keyframe based seek?

I've tried it with the "hr-seek=yes" option but this did not change the ab-loop making use of keyframes.

**Comment by Dudemanguy** [comment]
I'm not really sure what ab-loop has to do with seeking. It works by using timestamps as your point a and point b. You can also just modify your input.conf to do exact seeks if you want.

**Comment by gloaming** [comment]
@Dudemanguy I think he was trying to say that the ab-loop start and end points are snapped to the nearest keyframe, even when hr-seek is enabled. ("even when" because this seems to be the only option that might affect it.)

I assume this is true because it's noticable that the loop point is often not exactly at the same point I press the key, and trying multiple times it seems to snap back and forth between the same point too early and the same point too late. I sometimes want to loop very short and precise clips when trying to make out sounds in another language, so this is pretty annoying. Is it fixable?

**Comment by Hrxn** [comment]
Just speaking as a user of mpv here, I haven't done a code search for this yet, so maybe take it with a grain of salt.

But I've never noticed that snapping to the nearest keyframe that you describe here.
I mean, that is something that can vary a lot from file to file, depending on how the actual encode has been done.
But some encodes have pretty spaced out keyframes, so this is something where I am fairly certain that I would have noticed it.

And, as far as I know (again, without having searched through the code yet), what ab-loop does internally is using the timestamps of the two defined points (what you see with the `time-pos` property) for its playback loop by doing absolute time seeks, and absolute seeks in mpv are exact seeks by default.

**Comment by vommie** [comment]
Not sure if it's actually the keyframes (I'm just assuming it, because it would make the most sense), but ab loop definetly is not timestamp-perfect. It occurs with h264, h265 (or x264/265) in MKV or MP4 containers all the time for me. You can easily reproduce it by setting the B point in the very last frame of a video, you'll see it will jump earlier to the A point. Also set the A point on the first frame after a scene change, in most cases you will see some frames of the previous scene. 

The encoding/codecs/keyframe settings cannot be the reason. If I code my own mpv-wrapper and implement ab-loops by using seeking with precision=exact and reference=relative, it works perfectly fine, it's frame perfect. So it must be the way ab-loops are implemented in the original mpv. If I have some time I'll have a look into the source code how they do it.

**Comment by KonoVitoDa** [comment]
> You can also just modify your input.conf to do exact seeks if you want.

You mean the seeks done by ab-loop? I also noticed the ab-loop-b points to be imprecise.

**Comment by vommie** [comment]
I created a lua script for mpv. With it I am able now to get ab-repeat with frame precise loops. See:
[https://github.com/vommie/mpv-scripts/blob/main/ab_repeat.lua](https://github.com/vommie/mpv-scripts/blob/main/ab_repeat.lua)
