### ISSUE TITLE
How to change the size of `bigButtons`

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9170]
I want to customize the box layout.

https://github.com/mpv-player/mpv/blob/8aef22e45debedc107917e674072976c55c07f0d/player/lua/osc.lua#L1273

I tried to rewrite that `{x = posX, y = bigbtnrowY, an = 5, w = 15, h = 15} `
but it didn't make any difference. It always kept the original size.

On the other bigButtons I reproduced the same problem. Did I miss sth important?

https://github.com/mpv-player/mpv/blob/8aef22e45debedc107917e674072976c55c07f0d/player/lua/osc.lua#L1276-L1278

**Comment by avih** [comment]
Not sure what you mean exactly, but I _think_ the geometry only determines the position, while buttons are actually symbols at the builtin font, so you might need to change the font size for this.

**Comment by hooke007** [comment]
I didn't change the position `x = posX, y = bigbtnrowY`

`w = 15, h = 15` should be the size I think.

**Comment by avih** [comment]
w and h typically stand for width and height.

**Comment by hooke007** [comment]
As you can see, these codes seem to be redundant...

![Snipaste_2021-09-01_04-37-34](https://user-images.githubusercontent.com/41094733/131572691-54859081-1a4b-4935-8dfa-cf99b881d04e.jpg)
![Snipaste_2021-09-01_04-38-42](https://user-images.githubusercontent.com/41094733/131572697-61a8e455-8da1-4d14-a135-d1dfc9cf5bcb.jpg)

**Comment by avih** [comment]
https://github.com/mpv-player/mpv/blob/8aef22e45debedc107917e674072976c55c07f0d/player/lua/osc.lua#L69

These are ASS tags, and `\fs` is font-size, which is 50 here. You can change this number to make the buttons bigger or smaller.

**Comment by realroot2185** [comment]
How do I make a conf file that just changes the `bigButtons`?

I copied  [mpv/player/lua/osc.lua](https://github.com/mpv-player/mpv/blob/8aef22e45debedc107917e674072976c55c07f0d/player/lua/osc.lua) as `~/.config/mpv/scripts/osc.lua`.
I have some error: `attempt to index global 'user_opts' (a nil value)`.
