### ISSUE TITLE
build mpv 0.33 tvOS error

### ISSUE THREAD

**Issue by asdsjw** [mpv-player/mpv#9171]
build mpv 0.33 tvOS error

Checking for MinGW                                                        : os-win32 not found 
Checking for POSIX environment                                            : no 
Checking for Android environment                                          : no 
Checking for tvOS environment                                             : no 
Checking for Android EGL support                                          : android not found 
Checking for development environment                                      : posix not found 

Unable to find either POSIX or MinGW-w64 environment, or compiler does not work.

ask for help,thanks

**Comment by Akemi** [comment]
you informations are very vague. what exactly are you doing and how? a config log would probably be helpful. also pinging @tmm1 since he should know the most about this.

**Comment by tmm1** [comment]
```diff
diff --git a/wscript_build.py b/wscript_build.py
index 9fc0d25a51..bb4b22efc0 100644
--- a/wscript_build.py
+++ b/wscript_build.py
@@ -209,7 +209,7 @@ def build(ctx):
     ])

     subprocess_c = ctx.pick_first_matching_dep([
-        ( "osdep/subprocess-posix.c",            "posix" ),
+        ( "osdep/subprocess-posix.c",            "posix && !tvos" ),
         ( "osdep/subprocess-win.c",              "win32-desktop" ),
         ( "osdep/subprocess-dummy.c" ),
     ])
```

or alternatively: https://github.com/plexinc/mpv/commit/0c17d248116fc8647a1638e059f6e07bb238c8fd

**Comment by asdsjw** [comment]
Still the same compilation error
My xcode version is 13.1
My command to compile is

#!/bin/sh


ARCHS="arm64"
DEPLOYMENT_TARGET="13.0"

LIPO="y"

CWD=`pwd`
BUILD_DIR="mpv-tvOS"
SOURCE="mpv"
FAT="fat"
THIN=$CWD/$BUILD_DIR/"thin"
SCRATCH=$CWD/$BUILD_DIR/"scratch"

if [ "$*" ]
then
    ARCHS="$*"
    if [ $# -eq 1 ]
    then
        # skip lipo
        LIPO=
    fi
fi


if [ ! -r $SOURCE ]
then
    echo 'mpv source not found. Trying to download...'
    git clone https://github.com/mpv-player/mpv.git
    cd ./mpv/
    ./bootstrap.py
else
    cd ./mpv/
fi

# hacky way to fix typedef redefinition errors for 32-bit builds
# PATTERN="typedef ptrdiff_t GLsizeiptr;"
# REPLACE="#if defined(__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__) && (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ > 1060)\ntypedef ptrdiff_t GLsizeiptr;\n#else\ntypedef intptr_t GLsizeiptr;\n#endif\n"
# perl -pi -e "s/$PATTERN/$REPLACE/" /Users/Josh/Projects/mpv-demo/contrib/mpv/video/out/opengl/gl_headers.h


#./waf clean
#./waf distclean

for ARCH in $ARCHS
do

    echo "Building $ARCH..."

            PLATFORM="appletvos"

    export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/:$PATH"
    export SDKPATH="$(xcodebuild -sdk $PLATFORM -version Path)"
    export CFLAGS="-isysroot $SDKPATH -arch $ARCH -mtvos-version-min=$DEPLOYMENT_TARGET -fembed-bitcode -stdlib=libc++ -std=gnu++11  \
-I$CWD/FFmpeg-tvOS/thin/$ARCH/include"
    export LDFLAGS="-isysroot $SDKPATH -arch $ARCH -Wl,-tvos_version_min,$DEPLOYMENT_TARGET -lbz2 -stdlib=libc++ -std=gnu++11 \
-L$CWD/FFmpeg-tvOS/thin/$ARCH/lib"

    echo $CFLAGS
    echo $LDFLAGS

#--enable-videotoolbox-gl
    OPTION_FLAGS=" --disable-cplayer --disable-lcms2 --disable-lua --enable-libmpv-static --enable-ios-gl --enable-gl --disable-egl-android --disable-swift --disable-stdatomic --disable-iconv --disable-lua --disable-zlib --disable-uchardet --disable-x11 --disable-macos-10-14-features --disable-macos-media-player --disable-macos-cocoa-cb \
--out=$SCRATCH/$ARCH --prefix=$THIN/$ARCH"

    export PKG_CONFIG_PATH="$CWD/FFmpeg-tvOS/thin/$ARCH/lib/pkgconfig"

    echo "Configuring with options $OPTION_FLAGS"

    ./waf configure $OPTION_FLAGS || exit 1
    ./waf build -j4 || exit 1
    ./waf install || exit 1

done

cd ./..

if [ "$LIPO" ]
then
    echo "building fat binaries..."
    set - $ARCHS
    CWD=`pwd`/$BUILD_DIR
    mkdir -p $CWD/$FAT/lib
    cd $THIN/$1/lib
for LIB in *.a
do
    cd $CWD
    echo lipo -create `find $THIN -name $LIB` -output $CWD/$FAT/lib/$LIB 1>&2
    lipo -create `find $THIN -name $LIB` -output $CWD/$FAT/lib/$LIB || exit 1
done

    cd $CWD
    cp -rf $THIN/$1/include $CWD/$FAT
fi


echo Done
