### ISSUE TITLE
`watch-later-options=start` doesn't work as expectation

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9174]
### Important Information

Provide following Information:
- mpv version
- mpv-x86_64-20210829-git-dffb94f 
- Windows Version
- win10 21h1
- Source of the mpv binary
- shinchiro

### Reproduction steps

1. set `watch-later-options=start` and `save-position-on-quit` in mpv.conf
2. open mpv and drag the file to watch
3. jump to 30s and exit
4. reopen the same file, it recovered at 30s
5. jump to 60s and exit
6. reopen the file again

### Expected behavior

it would start at 60s

### Actual behavior

it started at 30s (same with the 1st time)

### Log file

I checked the watch_later file and posted it. If necessary I would post the log.
[watch_later.txt](https://github.com/mpv-player/mpv/files/7092746/watch_later.txt)

It wrote the "30s" under the "60s", that’s the reason I think why it didn't work properly.

**Comment by guidocella** [comment]
You shouldn't use `--watch-later-options=start` because the playback position is always saved even without it, as documented in the manpage. To save only the playback position, use `--watch-later-options-clr`.

**Comment by hooke007** [comment]
`--watch-later-options=` could also avoid this issue.

**Comment by guidocella** [comment]
> `--watch-later-options=` could also avoid this issue.

Yes, but you will get a `Option  not found.` error with `quit-watch-later`.
