### ISSUE TITLE
Add a `first-subtitle-visibility` option

### ISSUE THREAD

**Issue by fxmarty** [mpv-player/mpv#9175]
Hello, this feature request is related to https://github.com/mpv-player/mpv/issues/8243 and https://github.com/mpv-player/mpv/pull/8462 .

### Expected behavior of the wanted feature

Currently it is possible to toggle the subtitle visibility of both subtitles with `subtitle-visibility` and of the secondary subtitle assuming `subtitle-visibility` is set to `yes`.

For my use case ( https://github.com/fxmarty/rikai-mpv ), I want to make invisible the first subtitle, but to still have the ability to toggle the secondary subtitle visibility. This is currently not possible due to the note in the documentation: https://mpv.io/manual/master/#options-secondary-sub-visibility

Do you think it would be possible to add an option for toggling off/on _only_ the first subtitle while leaving the secondary one untouched?

Many thanks for your hard work!

**Comment by avih** [comment]
> Do you think it would be possible to add an option for toggling off/on _only_ the first subtitle

Technically it would be possible, but it's unlikely to happen. The whole secondary-sid subject is largely a hack, which is not well integrated into mpv, and its options are not really consistent with other options in terms of naming and handling.

There were some discussions about making secondary-sid a sort of equal citizen, but it was concluded that it would take a lot of hard work and will likely be sensitive to bugs, so for now there are no such plans.

> I want to make invisible the first subtitle, but to still have the ability to toggle the secondary subtitle visibility

Why not just use one subtitle in such case? And when you want two, enable secondary-sid ?
