### ISSUE TITLE
autoload videos without extensions

### ISSUE THREAD

**Issue by gelantoo** [mpv-player/mpv#9177]
Linux doesn't need extensions, so I have video files without them. And autoload doesn't work. It doesn't load anything, only current playing video in the playlist. Halp!

**Comment by Argon-** [comment]
I don't think there's a satisfying solution other than indiscriminately loading all files in a given directory and letting mpv error out in case it's an unknown format. And I don't think that's a good approach.
Your world without extensions (which is not restricted to Linux) is based on headers. Other than parsing the header of every file (in a given directory), there's little you can do to identify valid files before you feed them to mpv. Well, except file extensions.

**Comment by occivink** [comment]
The autoload script could be modified to process all files in a directory and pass them to `file` to determine their actual type, but maybe it's a better idea to just do that to fix your extensions. They may not be mandatory, but they're still useful.

**Comment by Argon-** [comment]
> The autoload script could be modified to process all files in a directory and pass them to `file` to determine their actual type, but maybe it's a better idea to just do that to fix your extensions. They may not be mandatory, but they're still useful.

Yeah, that's what I said: parse the header of every file. But that doesn't scale well, especially not for e.g. network storage. Works probably fine on small directory trees on a local hard drive but then... why this effort in the first place, when we already have file extensions?

@gelantoo you could add a dummy file extension `.video` and add it to the extensions of autoload.lua as a quick fix. Other than that, my personal opinion is: it's your conscious decision to go against established practices and there is a price attached to this.

**Comment by gelantoo** [comment]
@Argon- 
> I don't think there's a satisfying solution other than indiscriminately loading all files in a given directory and letting mpv error out in case it's an unknown format. 
YEP! That is totally I want to do! Sorry for didn't mention, there are nothing but video files in my video library directories. I'm OK with adding them (files inside a current directory) all. MPV will be fine and won't go crazy ^_^.
Is this hard for modifying the autoload script?
Thankies, thankies, thankies! 😘

**Comment by Argon-** [comment]
It’s not that hard but an even easier alternative: what about opening the whole directory with mpv?

**Comment by gelantoo** [comment]
@Argon- I'm trying to use terminal programs as much as possible. For file manager "nnn" is my fav.  But can't get how to do this inside that nnn 😂

**Comment by Argon-** [comment]
Not sure where the problem is? Maybe you don’t know but instead of passing a file as argument to mpv (on command line) you can pass a directory to mpv and it will open all files within it.
