### ISSUE TITLE
Switching resolution based on window/monitor size

### ISSUE THREAD

**Issue by gerion0** [mpv-player/mpv#9179]
### Expected behavior of the wanted feature

mpv displays it's video only in a certain resolution (e.g. FullHD wenn fullscreen, 600x400 when in window mode and scaled down etc). Youtube with YoutubeDL offers a lot of different video resolutions. Would it be possible that mpv automatically adjusts it's resolution to the window (or monitor) size? E.g., it doesn't make any sense to download a 4k movie, when to monitor is only FullHD.

Kind of similar to #9074 but the switching decision should be based on another parameter.

**Comment by 0x766F6964** [comment]
You can already set a maximum with [`--ytdl-format`][1].

For example I have the following in my mpv.conf:
``
ytdl-format='(bestvideo[height<=?1440]+bestaudio)/best'
``

[1]: https://mpv.io/manual/master/#options-ytdl-format

**Comment by Dudemanguy** [comment]
As explained, you can use `--ytdl-format`.

**Comment by gerion0** [comment]
Not quite the same. Monitors may change sometimes, especially, if it's played on a laptop with external monitors plugged in. Ideally, it would also dynamically adjust to the current window size. Even without that, an _automatic_ adjustment would be more convenient than a config option.
`ytdl-format` of course provides a workaround.

**Comment by Dudemanguy** [comment]
If you are expecting dynamic monitor changes during runtime, this is still possible if you use a script. You can observe the `display-width` or `display-height` property and change the desired options/properties when that value changes. Whether or not this works depends somewhat on your windowing backend (i.e. win32, x11, wayland, etc.) but mpv has the ability.
