### ISSUE TITLE
Option to Add warning when you press `Stop playing and quit.` button

### ISSUE THREAD

**Issue by barraIhsan** [mpv-player/mpv#9180]
### Expected behavior of the wanted feature
So whenever you press the `Stop playing and quit.` or `q` by default it will warn you if you want to `Do you want to Quit without storing the position?`.
### Alternative behavior of the wanted feature
Only warn you when previously you store the position (Assuming the user accidentally press `q` and not `Q`).

This behaviour is disabled by default and can be enabled by using `--warn-when-save-without-save-position` (or something else, I suck at naming thing)

**Comment by avih** [comment]
No. mpv doesn't use confirmation for anything, and that's unlikely to change.

However, you can use e.g. this lua script to require pressing `q` twice in order to quit:
```lua
local timeout = 1  -- seconds
local quit_command = "quit"  -- or "quit-watch-later"

local waiting = false
mp.add_forced_key_binding("q", function()
    if waiting then
        mp.command(quit_command)
    else
        mp.osd_message("Press q again to quit", timeout)
        waiting = true
        mp.add_timeout(timeout, function() waiting = false end)
    end
end)
```

**Comment by barraIhsan** [comment]
Oh ok! thanks
