### ISSUE TITLE
what does this mean? [ao/wasapi] Under-run: Device delay: -0.4

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9181]
what does this mean? when would mpv show this yellow warning? and can I do something to fix it?

**Comment by amariami** [comment]
I found a similar pop-up notice when playing some videos which containing audio HE-AAC format extension. 
Using Mediainfo to read the metadata I see `Delay relative to video                  : -115 ms` 
Is that the issue?

**Comment by Dudemanguy** [comment]
Basically, this just means that there isn't enough audio samples being read. It can happen for various reasons. Getting one on occasion isn't a big deal. See the [wikipedia article](https://en.wikipedia.org/wiki/Buffer_underrun) for more.
