### ISSUE TITLE
Android sub delay works differently?

### ISSUE THREAD

**Issue by SpectralniyRus** [mpv-player/mpv#9182]
![Screenshot_2021-09-03-22-27-55-364_is xyz mpv](https://user-images.githubusercontent.com/90066356/132057554-d97f0767-13d9-43db-9694-39132809fe3c.jpg)
I entered sub delay in my config just like I did in windows version, but it doesn't work. What should I do?

**Comment by CounterPillow** [comment]
open a proper issue at the proper repository

**Comment by sfan5** [comment]
Naming profiles like that doesn't do anything by itself.
If you want to apply config profiles depending on the filename read the [conditional auto profiles](https://mpv.io/manual/master/#conditional-auto-profiles) section of the manual.
