### ISSUE TITLE
HDR Passthrough?

### ISSUE THREAD

**Issue by ObsessedHacker** [mpv-player/mpv#9191]
I'm using a Windows 10 PC connected to an AV receiver and to my Samsung TV.

Display properties:

```
4K
60Hz
12bit
YCbCr420
```

I have 2 media players,
The first one is MPC-HC with madVR,
The second one is MPV.

When I open HDR movie with MPC-HC - The TV automatically changes to HDR.
( As I understand it - MPC-HC sends HDR Passthrough. )
When I open HDR movie with MPV - The TV doesn't change to HDR.
( As I understand it - MPV doesn't send HDR Passthrough )

MPV doesn't have HDR Passthrough?

Current config:
```
gpu-api=auto
gpu-context=auto
video-sync=display-resample
blend-subtitles=no
scaler-resizes-only
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=ewa_lanczossharp
tscale=lanczos
scale-antiring=0.0
cscale-antiring=0.0
dscale-antiring=0.0
tscale-antiring=0.0
tone-mapping=hable
hdr-compute-peak=no
dither=error-diffusion
error-diffusion=sierra-lite
dither-depth=12
correct-downscaling
linear-downscaling=no
deband=no
gamut-clipping=no
```

**Comment by hooke007** [comment]
HDR Passthrough is WIP

**Comment by ObsessedHacker** [comment]
> HDR Passthrough is WIP
> #5804
> 
> > When I open HDR movie with MPV - The TV doesn't change to HDR.
> > ( As I understand it - MPV doesn't send HDR Passthrough )
> 
> No, check [#7866 (comment)](https://github.com/mpv-player/mpv/issues/7866#issuecomment-651829545)

First of all - thank you for the fast response.

1) What is "WIP"?

2) I checked #5804 - the latest activity is from 2020, 
As it looks like - there's nothing new and there's no ETA when MPV will support it.

**Comment by hooke007** [comment]
WIP - Working In Progress

And you can see it in the todo list "Things to maybe do later"

**Comment by ObsessedHacker** [comment]
Hopefully, it will be added soon, I really love MPV, but that's the only flaw of it so far.
