### ISSUE TITLE
Weird HDR Glitch

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9193]
### Important Information

Provide following Information:
- mpv-x86_64-20210905-git-8aef22e
- Windows 10 Pro 64bit 21H1 19043.1110
- Source of the mpv binary: sourceforge

### Reproduction steps
1) Download MPV from sourceforge
2) Move folder to "C:\Program Files"
3) Run "mpv-install" as Administrator
4) Create a config (mpv.conf) on %appdata%\mpv
5) Add lines
```
target-trc=pq
target-prim=bt.2020
gpu-api=d3d11
video-sync=display-resample
blend-subtitles=no
scaler-resizes-only
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=ewa_lanczossharp
tscale=lanczos
scale-antiring=0.0
cscale-antiring=0.0
dscale-antiring=0.0
tscale-antiring=0.0
dither=error-diffusion
dither-depth=12
correct-downscaling
linear-downscaling=no
deband=no
hdr-compute-peak=no
gamut-clipping=no
opengl-pbo
deinterlace=no
vo=gpu
hwdec=auto
framedrop=vo
```
6) Change WIndows to HDR
7) Open HDR video (example video: https://www.youtube.com/watch?v=1La4QzGeaaQ ) 

### Expected behavior
1) Will show accurate colors, not greyish colors.

2) Will only apply HDR settings to HDR video
( target-trc=pq, target-prim=bt.2020 )
and restore SDR settings with SDR video

### Actual behavior
8) See grey video
![Issue](https://user-images.githubusercontent.com/13978119/132324296-8636fc8f-19ab-4be0-bd9c-aa21309054d7.jpg)
( I had to compress it from 64MB to 806KB for GitHub )

Sometimes it's working fine, but mostly it doesn't work fine.

- GTX 1650, WIndows 10 Pro, HDR Samsung TV

**Comment by ObsessedHacker** [comment]
Uh, This is interesting, I think I found the issue.
I have 2 monitors.
The first monitor is only SDR capable, intended for gaming.
The second monitor is HDR-capable (Samsung TV), intended for movies.

If I open the HDR video on the SDR monitor = it will be grey
If I open the HDR video on the HDR tv = it will work correctly
Apparently, it matters where I open the file from which monitor.
Weird...

**Comment by Doofussy2** [comment]
Windows will only apply HDR to display one, and the swapchain needs to be made for that display. You can't randomly use either display.

**Comment by ObsessedHacker** [comment]
> Windows will only apply HDR to display one, and the swapchain needs to be made for that display. You can't randomly use either display.

I can understand the logic behind it, but as I said, even with
```
fs
screen=1
fs-screen=1
```
it doesn't work properly.
I open the file on the SDR monitor, which will open MPV on the HDR monitor ( using fs-screen=1 ), this logic supposed to work fine, but it doesn't.

Allow me to summarize my findings:

1) MPV doesn't choose the right display swapchain when file opened from a different display.
Example: 2 monitors, one is SDR, second is HDR - Open file from SDR display which will open MPV to HDR display (using fs-screen=1),
Result: MPV opens on HDR display, but with SDR display swapchain.

2) HDR settings ( target-trc=pq, target-prim=bt.2020 ) are applied on SDR content,
Which makes SDR content look grey and inaccurate,
(Temporarily solution to this is to add "#" to the 2 lines when SDR content is being played, time consuming and inconvenient)
Is there any way to apply HDR settings only when HDR content is being played?

3) Is there any way to apply SDR settings (revert back the HDR settings) only when SDR content is being played?

**Comment by Doofussy2** [comment]
I don't think you're understanding. It's WINDOWS, not mpv. Specifying the screen in mpv changes nothing. If Windows says it's display 2 then it won't work. Your HDR display has to be seen by Windows as Display 1, the primary display. If not, then you're applying bt.2020 to a bt.709 colorspace. The necessary swapchain for HDR won't be made and you will lose the metadata, resulting in a pallid picture.

**Comment by ValZapod** [comment]
> applying bt.2020 to a bt.709 colorspace

It is PQ that is doing this, not BT.2020 matrix or BT.2020 primaries, those affect almost nothing.

**Comment by Doofussy2** [comment]
> > applying bt.2020 to a bt.709 colorspace
> 
> It is PQ that is doing this, not BT.2020 matrix or BT.2020 primaries, those affect almost nothing (and matrix is being applied in SDR mode, dunno about primaries). (Almost nothing is still visible of course but nothing compared to PQ instead of SDR curve, like BT.1886.)

His HDR display is not the primary. With Windows in HDR mode, there won't be any tone mapping. The PQ setting would only cause this in an SDR colorspace. It's why he's getting intermittent problems. Once his TV is the primary display and he stops trying to switch back and forth between HDR and SDR, all will be well. 

>Is there any way to apply SDR settings (revert back the HDR settings) only when SDR content is being played?

This keeps coming up. We need to be able to set the d3d csp at runtime, then if it doesn't switch automatically, we can use auto-profiles to set it for the primaries of our choosing. I believe jeeb is working on it.

**Comment by ObsessedHacker** [comment]
> Once his TV is the primary display and he stops trying to switch back and forth between HDR and SDR, all will be well.

It's NOT a requirement to have the HDR display (TV) as the primary display on Windows.
As long as you open the MPV window on that specific display - it will show the right colors.
( As i've seen in the logs: 
`Queried output: \\.\DISPLAY2, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)` )
But it does cause inconvenience when I have to open that window on the HDR display when I have "fs-screen=1" on mpv.conf to do it for me, because this way I **SHOULD** be able to open MPV on the HDR display even tho I was using the SDR display to open it.

> This keeps coming up. We need to be able to set the d3d csp at runtime, then if it doesn't switch automatically, we can use auto-profiles to set it for the primaries of our choosing. I believe jeeb is working on it.

Is there any open issue or pull request regarding this problem?
( I would like to check up on it to see when it gets fixed )
You said, "This keeps coming up.", I'm surprised there isn't a fix for it yet,
because if you want to watch HDR content, you will **HAVE TO USE**
`target-trc=pq` ( without this setting - HDR content won't show up correctly )
**BUT** this will make SDR content inaccurate, therefor this setting needs to be according to the content (dynamic), and not fixed (not changing).

**Comment by Doofussy2** [comment]
>It's NOT a requirement to have the HDR display (TV) as the primary display on Windows.
As long as you open the MPV window on that specific display - it will show the right colors.
( As i've seen in the logs:
Queried output: \\.\DISPLAY2, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G22_NONE_P709 (0) )

Look again. It's Gamma 2.2 with bt.709. I have Gamma 2084 with bt.2020

```
[   0.135][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)
[   0.136][v][vo/gpu/d3d11] Selected swapchain format R10G10B10A2_UNORM (24), attempting to utilize it.
[   0.137][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
[   0.137][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: yes
[   0.137][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
```
Nvidia tech support also told me it needs to be the primary display. 

There's no PR, but we talk about it a little, [here](https://github.com/mpv-player/mpv/issues/8936)

**Comment by ObsessedHacker** [comment]
> > It's NOT a requirement to have the HDR display (TV) as the primary display on Windows.
> > As long as you open the MPV window on that specific display - it will show the right colors.
> > ( As i've seen in the logs:
> > Queried output: \.\DISPLAY2, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G22_NONE_P709 (0) )
> 
> Look again. It's Gamma 2.2 with bt.709. I have Gamma 2084 with bt.2020
> 
> ```
> [   0.135][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)
> [   0.136][v][vo/gpu/d3d11] Selected swapchain format R10G10B10A2_UNORM (24), attempting to utilize it.
> [   0.137][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
> [   0.137][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: yes
> [   0.137][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
> ```
> 
> Nvidia tech support also told me it needs to be the primary display.
> 
> There's no PR, but we talk about it a little, [here](https://github.com/mpv-player/mpv/issues/8936)

Yes, the reason it was gamma 2.2 with bt.709 is that the HDR display was not set to HDR on Windows.
If I do set it to HDR I get the following:
`Queried output: \\.\DISPLAY2, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)`

I guess I'll have to say Nvidia tech support is wrong because as a fact - my primary display is SDR and my secondary is the HDR.
And I can get HDR to work properly on my HDR display, without the need to make it my primary display.
Again, as long as I open MPV on my HDR display - HDR will show correctly.

**Comment by Doofussy2** [comment]
Huh! I guess I stand corrected. I suppose Windows could have updated their idiocy :)

**Comment by Obegg** [comment]
Closing this issue since the only way to resolve it is to open mpv on the HDR display.
