### ISSUE TITLE
Subtitle font depending on subtitle language

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#9196]
Hello everyone!
Wondering if it's possible through scripting or maybe a keyboard shortcut to have different fonts depending on the subtitle language.
If, for example, I watch something which contains multiple subtitle languages (French, Chinese, Portuguese), when I switch the subtitle language I'd like it to change to a specified font for that language.
Thanks for the help!

**Comment by guidocella** [comment]
It's easy with a lua script:
```lua
mp.observe_property('current-tracks/sub/lang', 'native', function (_, lang)
    if lang == 'eng' then
        mp.set_property('sub-font', 'foo')
    elseif lang == 'ja' then
        mp.set_property('sub-font', 'bar')
    end
end)
```

**Comment by yaoberh** [comment]
Awesome!! What are the language codes for Simplified Chinese and Traditional? zh_cmn and zh_tw?

**Comment by guidocella** [comment]
subs don't always use the same exact language codes, just check what is used by your subs when selecting them and update your script.
To get random values, use lua's `math.random`, for example:

```lua
math.randomseed(os.time())
mp.set_property('sub-font', math.random() > .5 and 'foo' or 'bar')
```

**Comment by yaoberh** [comment]
Cool :D Is there any way in lua to make it so that it chooses a random font from the ones I've got installed in my system without having to specify the names of the fonts? For example using QtFontDatabase in a python script works, but I don't know how to implement this in lua. Thanks

**Comment by guidocella** [comment]
You can call system commands with `io.popen` or mpv's `subprocess` command. The manpage has an example with `subprocess`.

**Comment by yaoberh** [comment]
I've got not coding nor scripting expertise, although it may have seemed so...I'll try to check what you've explained and see if I can make it work! Thanks for your help :)

**Comment by rubyFeedback** [comment]
That solution could perhaps be added to the FAQ if it is not yet part of it - people may be more likely to find this than in issues, as the latter may be "phased out" once closed eventually. (Even manpages may not be too useful these days; I am of that generation that prefers to google-for-it or read StackOverflow stuff. :D )

**Comment by Natural-Harmonia-Gropius** [comment]
could get a finer tuning to mixed language content based on unicode range？
