### ISSUE TITLE
dash url playback failed

### ISSUE THREAD

**Issue by rolandjon** [mpv-player/mpv#9199]
### Important Information

Provide following Information:
- mpv version : git master
- Linux Distribution and Version: debian 10
- Source of the mpv binary  : https://github.com/mpv-player
- If known which version of mpv introduced the problem  : no
- Window Manager and version 
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv --msg-level=all=trace --log-file=~/Desktop/mpd_ng.log  http://streaming.dolby.com/ftproot/mitXperts/dash/dash_multi_codec.mpd
Failed to recognize file format.

note:ffplay playback ok.

### Expected behavior
playback ok
### Actual behavior
Failed to recognize file format.
### Log file

[mpd_ng.log](https://github.com/mpv-player/mpv/files/7134649/mpd_ng.log)

### Sample files
http://streaming.dolby.com/ftproot/mitXperts/dash/dash_multi_codec.mpd

**Comment by guidocella** [comment]
Try with `--demuxer-lavf-probescore=1`

**Comment by rolandjon** [comment]
@guidocella still not work with --demuxer-lavf-probescore=1 ,
-----
Failed to recognize file format.

Exiting... (Errors when loading file)

**Comment by sfan5** [comment]
FFmpeg only supports reading DASH manifests if it was built with `libxml2`, check the build configuration of your ffmpeg.

**Comment by avih** [comment]
Do you have `youtibe-dl` installed and available to mpv?

If yes, does it play with this?
```
mpv --ytdl-format= ytdl://http://streaming.dolby.com/ftproot/mitXperts/dash/dash_multi_codec.mpd
```

**Comment by rolandjon** [comment]
> FFmpeg only supports reading DASH manifests if it was built with `libxml2`, check the build configuration of your ffmpeg.


thanks. @sfan5 
I used mpv-build to compile. Obviously, I have installed libxml2-dev, 
--------------
dpkg -l |grep libxml2-dev
+++-=================-=============-============-===========================================
ii  libxml2-dev:amd64 2.9.4.5-1+dde amd64        Development files for the GNOME XML library
--------------
but dash demuxer is still not enabled in config.h. 
----
#define CONFIG_CODEC2RAW_DEMUXER 1
#define CONFIG_CONCAT_DEMUXER 1
**_#define CONFIG_DASH_DEMUXER 0_**
#define CONFIG_DATA_DEMUXER 1
----

I tried to find config.log what happened, but it seems that ffmpeg's  config.log was not generated.
But anyway, it seems that it has nothing to do with MPV, but the compiling system is fighting with the distribution. -(

**Comment by rolandjon** [comment]
> Do you have `youtube-dl` installed and available to mpv?
> 
> If yes, does it play with this?
> 
> ```
> mpv --ytdl-format= ytdl://http://streaming.dolby.com/ftproot/mitXperts/dash/dash_multi_codec.mpd
> ```

yes , "youtube-dl" work. 
I truly appreciate you point out those useful information. @avih  @sfan5
