### ISSUE TITLE
Show TimeTags at the top right of screen

### ISSUE THREAD

**Issue by francwalter** [mpv-player/mpv#9200]
Hello
how can I display the time tags, e.g. 

`00:11:29 / 00:25:56 (44%)`

on the right top side instead of left top?

I tried `--osd-bar-align-x=1` in mpv.conf (without the --) and also as parameter but this doesnt change the position.
Is that command not related to this timetag?
Is the osd-bar not the display of the timetags? I can change fontsize of the timetag though (with --osd-font-size=x).

Another question here, only partly related:

Can I display the timetag in relation to the --end parameter?
The second timetag (in my upper example 00:25:56) is always the same, when I set the --end parameter.
Also the bar at the bottom, where I have the controls, here too the end or remaining time are not different if I set an --end parameter, so when the movie stops (because of --end=x before end of file) the remaining time is not 0.

Thanks for hints.
frank

**Comment by guidocella** [comment]
Use `--osd-align-x=right` to align the text, `osd-bar` is the bar in the center that shows the progress.

The text shown when you seek is determined by `--osd-msg3`, so you want `--osd-msg3='${osd-sym-cc} ${time-pos} / ${end} (${percent-pos}%)'`. This seems to always print `end` in seconds though, so you would need a script to set `osd-msg3` with `end` formatted as `hh:mm:ss`.

To change the properties displayed in the `OSC` you would have to copy `player/lua/osc.lua` to your scripts directory and modify it, then use `osc=no` to disable the built-in script.

**Comment by francwalter** [comment]
`--osd-align-x=right` works perfectly, thanks 😄 

The `--osd-msg3="${osd-sym-cc} ${time-pos} / ${end} (${percent-pos}%)"` works too, but with " instead of " (maybe because of Windows OS). So I will try to modify the osc.lua to get hh:mm:ss (seconds is too unhandy).

Thanks!

**Comment by guidocella** [comment]
Note that `osd-msg3` is unrelated to the OSC which is the bar and controls at the bottom.
