### ISSUE TITLE
ICC Profile

### ISSUE THREAD

**Issue by ObsessedHacker** [mpv-player/mpv#9202]
Logs:
`[   0.191][v][vo/gpu/win32] color-profile: C:\Windows\system32\spool\drivers\color\sRGB Color Space Profile.icm`
I was wondering, I'm using MPV to play SDR and HDR, but since it only gets "sRGB Color Space Profile", does it show the right colors?
I'm using a Samsung HDR TV from 2020, do I need a special ICC file in order to get the full colors?
I did search for ICC profile for my TV but there isn't one, which is weird, TVs don't need ICC profile?
I was hoping to better understand this.

**Comment by Akemi** [comment]
there isn't really "a colour profile for your TV". if you want one that is specific to your TV and settings you need a colorimeter to produce one yourself.

**Comment by ValZapod** [comment]
> TVs don't need ICC profile?

No, HDR does not need an ICC profile. ICC profiles are in TV itself.
