### ISSUE TITLE
How to Exclude a name in mpv Profiles?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9204]
Hi,

I apologize in advance for mine bad english?
and would be appreciated if you could help me :)

so I have set Profile in mine mpv.conf like this example:
```
[Shaman King]
profile-cond=string.match(get("filename", ""), "Shaman King %(2021%)")~=nil
deband=yes
deband-iterations=3
deband-threshold=40
deband-range=20
deband-grain=0
glsl-shader="~~/noise_static_chroma.hook"
glsl-shader="~~/noise_static_luma.hook"
framedrop=no
volume=110

```
and another profile like this:

```
[SOFCJ-Raws Shaman King]
profile-cond=string.match(get("filename", ""), "SOFCJ%-Raws")~=nil
fs
deband=no
volume=110

```

so mine problem is the first profile setting will be used also for the second profile cuz
 I have two videos **video A** name is Shaman King and **video B** name is **[SOFCJ-Raws] Shaman King (2021)** 
so video A doesn't have **[SOFCJ-Raws]** in its name but both have **shaman king** written as file name .

what I want to know is how can I exclude the first profile settings for video B ?
I did try write different profile for video B but it didn't work ? deband is also working for video B?

so how can I exclude the first profile settings for the name SOFCJ?

**Comment by guidocella** [comment]
`profile-cond=get("filename", ""):match("Shaman King %(2021%)") ~= nil and get("filename", ""):match("SOFCJ%-Raws") == nil`

**Comment by erickyun** [comment]
> `profile-cond=get("filename", ""):match("Shaman King %(2021%)") ~= nil and get("filename", ""):match("SOFCJ%-Raws") == nil`

Thank youu that did exactly what I wanted.
