### ISSUE TITLE
Property current-window-scale is always 1.0

### ISSUE THREAD

**Issue by WhitePeter** [mpv-player/mpv#9207]
### Important Information

- mpv version: 0.33.0-336-g62b2c5db98
- Linux Distribution and Version: Ubuntu 20.04.3 LTS
- Source of the mpv binary: locally built from this repo (https://github.com/mpv-player/mpv)
- ~~If known which version of mpv introduced the problem~~
- Window Manager and version: Sway 1.6.1 (Wayland)
- GPU driver and version:  AMD iGPU Raven/Picasso on a Ryzen 3500U, Driver version:
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Mesa Gallium driver 21.0.3 for AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.40.0, 5.11.0-34-generic, LLVM 12.0.0)
(I believe this is not an issue with libva, but couldn't remember where to get the driver info elsewhere and vainfo seems to nicely condense the relevant info)

### Reproduction steps

Play any video file, hit 'I' for the stats and look at "Window Scale", or open the console and issue command 'print-text ${current-window-scale}'.
Change window size: "Window Scale" (current-window-scale) will always stay 1.0. This was not always the case. A while back after an upgrade to the latest git master I noticed that some of my conditional auto profiles did not work anymore, nor does a lua script which relied on current-window-scale (property observed). For the time being I work around the issue in lua by using osd-dimensions, but that is not feasible with autoprofiles. Basically, the profiles in question change the scale parameter (--scale) on the fly based on current-window-scale, since above GPU is a bit on the lean side of power but does manage ewa_lanczos quite well as long as the scale factor is smallish (<=2) - no noticeable difference in computation time compared to plain lanczos.
Sadly though, I did not notice right away and have no info on the old working commit, so bi-secting is not so easy, but I did notice some mention of changes to window-scale in the git log. I will try and bi-sect based on that later, if necessary. But maybe it is not an issue with mpv at all. If nobody can reproduce this, I would like to save myself the trouble of bi-secting. ;)

Try to reproduce your issue with --no-config first: Did that, same outcome.

### Expected behavior
current-window-scale reflecting the actual scaling factor from native video resolution to window resolution.

### Actual behavior
current-window-scale always 1.0

### Log file

[output.log](https://github.com/mpv-player/mpv/files/7150287/output.log)

**Comment by Dudemanguy** [comment]
The window-scale behavior was changed quite a bit a while ago, but I believe this is an oversight on my part. The problem you are having is because the maximized case (which in sway is a tiled/tabbed/stacking window) is not always handled correctly. If you float mpv it should work normally. I'll patch this in a bit. Thanks for the report.

**Comment by WhitePeter** [comment]
Wow, that was one quick reply. :1st_place_medal: 

Thanks for the info. You are right, as soon as I put mpv into float mode and resize the propery changes as expected.

While we're at it: I did notice a slight inaccuracy with the window-scale value, which I think is also specific to tiling window managers, not sure about i.e. i3 but I guess it might be the same. From my observations with the old behaviour, I gathered that current-window-scale (cws from here on, for brevity) seems to be calculated from osd-dimensions. This leads to the situation that, when not floating, the window is bigger than the video, padded with black bars - under the condition that keepaspect is on, which it should be. Now these black bars obviously count towards osd-dimensions and artificially/falsely increase the cws value. In my lua script I can account for that and in the autoprofiles it is not a big deal, but I figured, if there is anything that can be done...

Now that I am looking at it, I think I borrowed that code from stats.lua. ;)
```lua
local function get_video_dim(osd)
        local osd = osd or mp.get_property_native("osd-dimensions")
        local scaled_w, scaled_h = osd.w - osd.ml - osd.mr, osd.h - osd.mt - osd.mb
        return scaled_w, scaled_h
end

true_scale = scaled_w / orig_w * scaled_h / orig_h
cws = true_scale^(1/2)  -- square root
```
The last two lines are just for illustration. I think, technically the scale factor should be calculated in both dimensions and cws only reflects the one-dimensional scale. The number of pixels quadruples with scaling by 2 in x *and* y, after all. But this is mainly academic. Just wanted to let you know my interpretation and show where and how the problem with inaccurate cws values on tiling window managers can arise: osd.m{l, r, t, b} need to be subtracted, which they are not, or at least were not while cws was still working. On the floating layer that cannot happen as it seems since both x and y are changed simultaneously, so this seems specific to tiling window managers. But one case should apply to all kinds of WM: fullscreen, where padding with black bars is to be expected.

**Comment by Dudemanguy** [comment]
Current window scale isn't calculated from osd-dimensions. Every VO/windowing backend has a special call that returns the dimensions of the window for this calculation. You are correct that the window scale calculation does not attempt to take into margins or not. Black bars are included as part of the window size. Maybe this should not be done.

**Comment by avih** [comment]
> Every VO/windowing backend has a special call that returns the dimensions of the window for this calculation

True that each VO is responsible to report the dimensions, but the calculation from the dimensions into the `current-window-scale` value is then unified and the same regardless of the VO.

This value can only guarantee to be accurate when the video content exactly fits the window size. In all other cases (zoom, stretch, black bars, etc) a single value simply can't reflect all the values which are exposed via `osd-dimensions`.

FWIW, I don't think the current-window-scale calculation needs to be modified. It's decent for what it does, it's accurate whenever it can be accurate, and for other cases one would need to use osd-dimensions to read all the relevant values.

**Comment by WhitePeter** [comment]
@avih, thanks for the explanation. Is osd-dimensions safe to use for getting the actual window dimensions then? I am asking because what I really wanted was a way to determine window width/height but could not find other properties for this. It was more of an accident that I discovered the change in stats.lua which relies on osd-dimensions for "Scaled Resolution".

**Comment by avih** [comment]
>  Is osd-dimensions safe to use for getting the actual window dimensions then?

I don't understand what "safe" means, but yes. Nothing will blow, and it should hold meaningful values whenever there's a window.

> what I really wanted was a way to determine window width/height

That would be `osd-width` and `osd-height`, which are also avilable as sub-properties of `osd-dimensions` (`.w` and `.h`).

**Comment by WhitePeter** [comment]
> > Is osd-dimensions safe to use for getting the actual window dimensions then?
> 
> I don't understand what "safe" means, but yes. Nothing will blow, and it should hold meaningful values whenever there's a window.

Guess I should have elaborated a bit more. By "safe" I mean: is it guaranteed to hold the actual window dimensions or are there cases when window dimensions and osd-dimensions differ, i.e. by padding?

 > > what I really wanted was a way to determine window width/height
> 
> That would be `osd-width` and `osd-height`, which are also avilable as sub-properties of `osd-dimensions` (`.w` and `.h`).

Yes, that is what I am using in my script, as mentioned above. But why is this property named **osd**-dimensions? That is what put me off, the first time I found it in the man page. Could it not just as well be named or aliased to window-dimensions? Using osd-dimensions to determine window-dimensions feels like *ab*using it and risking breakage in the longrun.

Oh, just because I am not sure about what you mean, when you say:
> I don't think the current-window-scale calculation needs to be modified.
Does that mean, it should stay as it is now (always 1.0) on tiling Wayland window managers or just my other ramblings about the technicalities. I can live with the latter but I would really like to be able to use cws for my autoprofiles. It is accurate enough for those purposes.

**Comment by avih** [comment]
> But why is this property named osd-dimensions?

Because technically it does refer to OSD things, where some of these values also have to relate to the window size, because that's where the osd is rendered.

> Does that mean, ...

No. I was referring to:

>  Black bars are included as part of the window size. Maybe this should not be done

I.e. however current-window-scale is calculated now (from the values which the VO provides) - it's fine.

**Comment by WhitePeter** [comment]
@Dudemanguy, thanks a bunch for the fix!
@avih, thanks again for your insights. My mind is at ease now. ;)
