### ISSUE TITLE
youtube-dl is dead, add yt-dlp as default

### ISSUE THREAD

**Issue by pirate486743186** [mpv-player/mpv#9208]
It's practically certain at this point that youtube-dl is dead.

- Last release in 6/6/2021
- Last commit 1 July
- There's a partial solution for age restricted youtube videos, that  is still not implemented.
- devs say nothing at all
- declining dev activity over time https://github.com/ytdl-org/youtube-dl/issues/26462

proposed solution: Add a fallback to yt-dlp. It seams to be the new youtube-dl . Remove youtube-dl after some time.

Yes, i know you can configure the youtube-dl path/binary. This is about the default in mpv.

**Comment by garoto** [comment]
Normies hating that dstftw tried his best to keep the codebase lean and mean, while rejecting poor, unmaintainable and hackish PRs.

p.s.: `youtube.com` hosted content seems to be parsed just fine as I write this.

**Comment by haasn** [comment]
My, more modest, proposal: Use `yt-dlp` as a fallback if `youtube-dl` is not available in `$PATH`.

That way users can decide whether to install `yt-dlp` or `youtube-dl` without mpv forcing a particular choice.

**Comment by garoto** [comment]
> [...] its 3x faster than yt-dlp when extracting the same json data.

```
[ R:\ ]
> mpv --no-config --script-opts=ytdl_hook-ytdl_path=youtube-dl --msg-level=all=no,ytdl_hook=trace https://yewtu.be/watch?v=KuwVZkgDkmM --vo=null --end=1 | rg "running time"
[ytdl_hook] script running time: 1.929 seconds

[ R:\ ]
> mpv --no-config --script-opts=ytdl_hook-ytdl_path=youtube-dl --msg-level=all=no,ytdl_hook=trace https://yewtu.be/watch?v=KuwVZkgDkmM --vo=null --end=1 | rg "running time"
[ytdl_hook] script running time: 1.946 seconds

[ R:\ ]
> mpv --no-config --script-opts=ytdl_hook-ytdl_path=youtube-dl --msg-level=all=no,ytdl_hook=trace https://yewtu.be/watch?v=KuwVZkgDkmM --vo=null --end=1 | rg "running time"
[ytdl_hook] script running time: 1.999 seconds

[ R:\ ]
> mpv --no-config --script-opts=ytdl_hook-ytdl_path=yt-dlp --msg-level=all=no,ytdl_hook=trace https://yewtu.be/watch?v=KuwVZkgDkmM --vo=null --end=1 | rg "running time"
[ytdl_hook] script running time: 4.529 seconds

[ R:\ ]
> mpv --no-config --script-opts=ytdl_hook-ytdl_path=yt-dlp --msg-level=all=no,ytdl_hook=trace https://yewtu.be/watch?v=KuwVZkgDkmM --vo=null --end=1 | rg "running time"
[ytdl_hook] script running time: 4.389 seconds

[ R:\ ]
> mpv --no-config --script-opts=ytdl_hook-ytdl_path=yt-dlp --msg-level=all=no,ytdl_hook=trace https://yewtu.be/watch?v=KuwVZkgDkmM --vo=null --end=1 | rg "running time"
[ytdl_hook] script running time: 4.479 seconds

```

**Comment by garoto** [comment]
Way too early for this patch imo. What will happen when guidocella gets a real job after he's out of college and loses interest in media player programming shenanigans?

**Comment by pirate486743186** [comment]
@haasn  
> I support the suggestion to add a fallback to `yt-dlp`. I'm not sure if we should ever remove `youtube-dl`, though. Letting users decide seems like the best way forward.

This type of project get's old like milk. If it's truly dead, it will be useless very fast.
There's also a long term trend of reduced activity from the devs, even if they come back, it's still a red flag for the project.

> Incidentally, having `yt-dlp` ordered _before_ `youtube-dl` is probably the more sensible option, for the sole reason of it being more obscure fork - users who have `yt-dlp` installed are more likely to want to use it rather than `youtube-dl`.

Yea, good idea. This is done by other programs


@garoto 
 I suspect you are actually comparing python2 with python3. python3 is slower.

can you play that? (mmd 18)
https://www.youtube.com/watch?v=mhQBnoj5cvs

youtube-dl is not just for youtube, what about other sites?

**Comment by garoto** [comment]
>  I suspect you are actually comparing python2 with python3. python3 is slower.

lol, did you just assumed my retardation level?

**Comment by johnthecracker** [comment]
Yes my friend, do it 2X faster when/if it doesn't work

**Comment by N-R-K** [comment]
> Yes my friend, do it 3X faster when/if it doesn't work

Given the sad fate countless youtube-dl forks have met, one can say the same about yt-dlp my fren :^)

**Comment by johnthecracker** [comment]
Fine.

While developers procrastinate to implement this change, here is a quick workaround.

Delete youtube-dl.exe.

Copy yt-dlp.exe and rename copy to youtube-dl.exe. 

Now you have yt-dlp.exe with 2 different names and MPV will pick up "youtube-dl.exe".

By the way, why there isn't a new stable release of MPV since mpv-0.33.0-x86_64.7z dated 2020-12-06
or I don't look for one where I should?

https://sourceforge.net/projects/mpv-player-windows/files/stable/

MPV may be dying itself.

**Comment by N-R-K** [comment]
> Delete youtube-dl.exe.
> 
> Copy yt-dlp.exe and rename copy to youtube-dl.exe.
> 
> Now you have yt-dlp.exe with 2 different names and MPV will pick up "youtube-dl.exe".

....
Or you can just use `ytdl_path`
https://mpv.io/manual/master/#options-ytdl-path

> MPV may be dying itself.

The main dev left, came back and left again.

**Comment by johnthecracker** [comment]
What alternative would you use to MPV as your first choice ?

**Comment by richardpl** [comment]
Just leave this pointless discussion at once.

**Comment by johnthecracker** [comment]
This is not the pointless discussion.
I ask somebody who knows more than me to tell me something that I am looking for for 
and I get negative reply. 
If everybody had your attitude that let's all leave forums on the internet and communicate privately via email.

**Comment by johnthecracker** [comment]
Hej, I ja sam hrvat . Mozda sam zato i glup.

**Comment by N-R-K** [comment]
> What alternative would you use to MPV as your first choice ?

MPV just werks ™️ (as of now at least), same with youtube-dl. So I see no reason to seek alternative.

**Comment by Akemi** [comment]
locking the comments (for now).
