### ISSUE TITLE
[Subtitles]: Showing <c.font-style_italic> tags instead of formating text

### ISSUE THREAD

**Issue by gadefox** [mpv-player/mpv#9211]
I'm trying to build the app from the source code.. Which lib do I need to install, so the subtitle formatting is correct? Build [configuration](https://ulozto.net/tamhle/DG3OmDCRYVP0#!ZGR3MGR2AmHlZmpmBTD4BGuwLzEvZGODIyyDK0jjZ05XnGVmBD==)

**Comment by Dudemanguy** [comment]
Not sure what you mean, but subtitles are handled by libass (which isn't optional anyway). Make sure your subtitle files are correctly formatted if you are having issues.
