### ISSUE TITLE
autoload: how to toggle functionality?

### ISSUE THREAD

**Issue by horusra** [mpv-player/mpv#9212]
When using [autoload](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) how do you disable it if you don't want MPV to continue to the next file when the current video is done?

Depending on the file you're viewing, you might not want MPV to continue to the next file, for example in folders where the files are not related or in a series.

**Comment by guidocella** [comment]
That script has a disabled option, you can use it with `--script-opts-append=autoload-disabled=yes`. If you mean after mpv already start, you can use the `playlist-clear` command.

**Comment by horusra** [comment]
@guidocella Awesome! Thank you.
playlist-clear was exactly what I was looking for.
I had searched for something like it in the manual, but somehow hadn't found it.
