### ISSUE TITLE
Having the On Screen Controls show up at all makes mpv segfault

### ISSUE THREAD

**Issue by arb103** [mpv-player/mpv#9213]
### Important Information

- mpv version
mpv 0.33.1-r1::gentoo
mpv 0.33.1 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4
- Linux Distribution and Version
Gentoo Linux amd64 kernel version 5.10.61
- Source of the mpv binary
Compiled through portage package manager
- Window Manager and version
dwm 6.2
- GPU driver and version
Intel i965 driver for Intel(R) Ironlake Mobile - 2.4.1
mesa-21.1.7::gentoo

### Reproduction steps

To reproduce the issue I just try to watch any video, either local or through the ytdl hook

### Expected behavior

No segfaults and being able to interact with the player

### Actual behavior

Video plays fine, but almost any interaction with the on screen controls results in a segfault
The interactions that failed were:
- mousing over
- changing volume, brightness, saturation or playback speed
- moving forwards and backwards on the file

The interactions that succeeded were:
- moving and resizing the window the player is at
- going fullscreen
- taking a screenshot
- pausing and playing the video

using the `--osc=no` option makes it so I can mouse over, but the other interactions still result in segfault

### Log file

log file from running  `mpv --log-file=~/mpv.log --no-config --osc=no ytdl://youtube.com/watch?v=9IvgM6pQkns --ytdl-format="best[height=720]"`
https://0x0.st/-xRA.log
I'll also add the relevant dmesg line:
`[22335.105560] mpv/vo[19347]: segfault at 7f701100c000 ip 00007f703ba0764c sp 00007f7025fcc7e8 error 6 in libass.so.9.1.2[7f703b9e5000+29000]`

### Sample files

I can reproduce the issue with any file, but I'll post a sample one if asked

I searched for similar issues and none of them were similar enough to mine, #7257 was the most similar one and the solution there was for that one doesn't look relevant to mine

**Comment by avih** [comment]
> using the `--osc=no` option makes it so I can mouse over, but the other interactions still result in segfault

If it still segfaults with `--osc-no` then it's unrelated to the on-screen controls.

It could be related to libass. Can you try an older libass version?

Can you provide a stack trace?

**Comment by arb103** [comment]
libass-0.15.1-r2 is the name of the package in portage, the libass.so version that is installed belongs to it
```
equery f libass
 * Searching for libass ...
 * Contents of media-libs/libass-0.15.1-r2:
/usr
/usr/include
/usr/include/ass
/usr/include/ass/ass.h
/usr/include/ass/ass_types.h
/usr/lib64
/usr/lib64/libass.so -> libass.so.9.1.2
/usr/lib64/libass.so.9 -> libass.so.9.1.2
/usr/lib64/libass.so.9.1.2
/usr/lib64/pkgconfig
/usr/lib64/pkgconfig/libass.pc
/usr/share
/usr/share/doc
/usr/share/doc/libass-0.15.1-r2
/usr/share/doc/libass-0.15.1-r2/Changelog.bz2
```
as for the backtrace: https://0x0.st/-x7-.txt
I'll wait for your reply to see if this helps clear up what's going wrong, I'll downgrade libass after that if we still can't figure it out

**Comment by avih** [comment]
Right, it seems to be several calls inside libass, and I don't have an insight what that might be, because there are no debug symbols.

So yeah, you can try an earlier version to get another data point.

**Comment by astiob** [comment]
Can you install libass 0.15.2, which is [already in Portage](https://packages.gentoo.org/packages/media-libs/libass) but currently marked unstable/testing? I don’t think there were any known crash fixes in 0.15.2, but it’s still worth checking. If the crash persists, or if you’re unable to try 0.15.2, can you [make a debug build of libass](https://wiki.gentoo.org/wiki/Debugging) to make the stack trace more useful? You may or may not need to also rebuild mpv (if Portage doesn’t force you to do so).

**Comment by arb103** [comment]
I was about to say I was having trouble downgrading libass, I'll try the unstable version first before going back to that
I couldn't get the 0.15.2 version until I did emerge --sync so now I'm waiting on a whole bunch of packages to be updated along with libass, thanks for the tip
also changed the env for mpv and libass so I get the debug symbols this time, I really messed up that part, sorry

**Comment by arb103** [comment]
Updating libass fixed it!
well... mostly
Everything runs as normal now, with the exception of these messages appearing over and over anytime I do the interactions I previously couldn't (volume control, mouseover, etc)

```
[osd/libass] fontselect: failed to find any fallback with glyph 0x1F989 for font: (sans-serif, 400, 0)
[osd/libass] fontselect: failed to find any fallback with glyph 0x1F423 for font: (sans-serif, 400, 0)
[osd/libass] fontselect: failed to find any fallback with glyph 0x1F43E for font: (sans-serif, 400, 0)
[osd/libass] fontselect: failed to find any fallback with glyph 0x1F985 for font: (sans-serif, 400, 0)
```
I am okay with letting things be like this, as annoying as having a nigh unreadable output might be, it's better than where I started and the issue in the title is now fixed anyways
If you don't mind I'll close this issue and open a new one if I can't google my way into getting those glyphs that are making libass freak out

**Comment by avih** [comment]
> ```
> [osd/libass] fontselect: failed to find any fallback with glyph 0x1F989 for font: (sans-serif, 400, 0)
> [osd/libass] fontselect: failed to find any fallback with glyph 0x1F423 for font: (sans-serif, 400, 0)
> [osd/libass] fontselect: failed to find any fallback with glyph 0x1F43E for font: (sans-serif, 400, 0)
> [osd/libass] fontselect: failed to find any fallback with glyph 0x1F985 for font: (sans-serif, 400, 0)
> ```

These are emojis, which are at the title of your clip, at the log:
```
[   5.346][v][cplayer] Set property: file-local-options/force-media-title="Barn Owls 🦉🐣  Stoats 🐾  Kestrels  Buzzards 🦅 & More | Live From Fotherdale, Yorkshire, UK 2021-09-15 14:22" -> 1
```

So I guess the crash is when libass tries to render them at the OSC or OSD.

I presume it crashes only with this file, right? (or other files with emojis at the title), but most files don't have emojis at the title, so with "normal" titles it doesn't crash, right?

**Comment by arb103** [comment]
The player doesn't crash anymore, sorry if I wasn't clear, it just gets those 4 lines repeatedly spammed at the command line
Also, you are right, the spam only happens with videos that have emojis in the title, but the crash I was having previously happened on all videos, with and without emojis in the title, so I think whatever's happening now is unrelated to my original issue
I have tried playing a file with .ass subtitles and it plays well and renders the subtitles, but spams my command line with
`[sub/ass] [0x558f242bcb30]: Warning: no style named 'ED1' found, using 'Default'`
If you need me to run any more tests to help I'll gladly do it, should I downgrade libass again and see if it the segfault still happens with the previous version I was using?

**Comment by astiob** [comment]
> google my way into getting those glyphs that are making libass freak out

Presumably you just need to install a font that contains monochrome emoji. [Here](https://graphicdesign.stackexchange.com/questions/113388/is-there-a-free-open-source-black-and-white-emoji-font) are some font suggestions.

**Comment by TheOneric** [comment]
> I think whatever's happening now is unrelated to my original issue

Since you mentioned "changing volume" specifically as a crash source, which only uses some ASS drawings, very likely yes.
As for the current warnings, you just need to install a font for the used glyphs and you seem to have had bad luck with your ASS-sample as it appears like it got a used Style-definition removed or renamed; the file is partially broken.

> should I downgrade libass again and see if it the segfault still happens with the previous version I was using?

If you want to go the extra mile and it doesn't cost too much of your time, your certainly welcome to try with debug symbols, but you don't have to.

**Comment by avih** [comment]
> The player doesn't crash anymore, sorry if I wasn't clear ...
>  the crash I was having previously happened on all videos

It was clear. I guessed, apparently incorrectly, that the crash in 0.15.1 was due to these emojis, and in 0.15.2 it printed the warnings without crashing.

Anyway, this:
> If you want to go the extra mile and it doesn't cost too much of your time, your certainly welcome to try with debug symbols, but you don't have to.

FYI, @astiob and @TheOneric are libass maintainers, so if you can afford to help them with stack trace with debug symbols (of 0.15.1), then it would be appreciated and probably of use to them.

If not, feel free to clos this issue.

**Comment by arb103** [comment]
I have downgraded libass back to 0.15.1-r2 and I can't reproduce the segfault issue
I rebuilt mpv again just in case it was still linked to the wrong libass files, but everything's working fine
Whatever the original issue was is gone for good it seems, thanks for all your help and sorry I couldn't give you a useful backtrace
