### ISSUE TITLE
If audio pts and video pts are different, how to synchronize audio and video

### ISSUE THREAD

**Issue by Luh10032** [mpv-player/mpv#9217]
### Important Information

Provide following Information:
- mpv version:0.33.0
- Windows Version:windows10
### Reproduction steps
   I pushed a HEVC RTSP stream to the server, and parsed the audio and video of this stream with ffprobe, and found that the parameters related to the pts and dts of the audio and video are different.
   This leads to the inability to play audio when mpv is streaming (video is played normally). If I set "initial-audio-sync=no", the sound can be played, but doing so will cause the audio to be delayed a few seconds from the video.
   When I use vlcplayer or ffplay to pull this stream, the above problem does not occur, that is, the audio can be played normally and the audio and video are synchronized.
   How should I set up so that the audio and video are synchronized when mvp is pulling this stream?

### Actual behavior
audio-stream:
`  {
            "type": "packet",
            "codec_type": "audio",
            "stream_index": 1,
            "pts": 4303176496,
            "pts_time": "537897.062000",
            "dts": 4303176496,
            "dts_time": "537897.062000",
            "duration": 1024,
            "duration_time": "0.128000",
            "size": "267",
            "flags": "K_"
        },
        {
            "type": "frame",
            "media_type": "audio",
            "stream_index": 1,
            "key_frame": 1,
            "pkt_pts": 4303176496,
            "pkt_pts_time": "537897.062000",
            "pkt_dts": 4303176496,
            "pkt_dts_time": "537897.062000",
            "best_effort_timestamp": 4303176496,
            "best_effort_timestamp_time": "537897.062000",
            "pkt_duration": 1024,
            "pkt_duration_time": "0.128000",
            "pkt_size": "267",
            "sample_fmt": "fltp",
            "nb_samples": 1024,
            "channels": 1,
            "channel_layout": "mono"
        },`
video-stream:
` {
            "type": "packet",
            "codec_type": "video",
            "stream_index": 0,
            "pts": 87569010,
            "pts_time": "972.989000",
            "dts": 87569010,
            "dts_time": "972.989000",
            "size": "24768",
            "flags": "__"
        },
        {
            "type": "frame",
            "media_type": "video",
            "stream_index": 0,
            "key_frame": 0,
            "pkt_pts": 87569010,
            "pkt_pts_time": "972.989000",
            "pkt_dts": 87569010,
            "pkt_dts_time": "972.989000",
            "best_effort_timestamp": 87569010,
            "best_effort_timestamp_time": "972.989000",
            "pkt_size": "24768",
            "width": 1920,
            "height": 1080,
            "pix_fmt": "yuv420p",
            "pict_type": "P",
            "coded_picture_number": 0,
            "display_picture_number": 0,
            "interlaced_frame": 0,
            "top_field_first": 0,
            "repeat_pict": 0,
            "color_range": "tv",
            "color_primaries": "bt470bg",
            "chroma_location": "left"
        },`

mpvconf:
`#initial-audio-sync=no
hwdec=auto
cache=yes
vo=gpu`

### Log file

[log-video-ffprobe.txt](https://github.com/mpv-player/mpv/files/7184413/log-video-ffprobe.txt)
[log-audio-ffprobe.txt](https://github.com/mpv-player/mpv/files/7184423/log-audio-ffprobe.txt)

**Comment by arzeth** [comment]
Try
```
vf-add="setpts=PTS-STARTPTS"
af-add="asetpts=PTS-STARTPTS"
```
`man ffmpeg-filters`: https://ffmpeg.org/ffmpeg-filters.html#setpts_002c-asetpts
Although that's what `initial-audio-sync=no` probably does.

You can have multiple same `*-add` at the same time.

If you still have delays, then also add before `af-add=asetpts...` (or maybe after, or just replace, I don't know):
```
af-add="lavfi=[aresample=async=1:min_hard_comp=0.1:first_pts=0]"
```

If you still have delays, then also add:
```
demuxer-lavf-o-add="fflags=+nobuffer+fastseek+flush_packets"
```

If you still have delays, then also add (note that I am saying `also` again):
```
cache=no
demuxer-readahead-secs=0
# use 0.1 instead of 0 if performance is bad
force-seekable=no
```

If you still have delays, then also add both or either one of:
```
no-correct-pts
untimed
```


If you STILL have delays, then try experimenting (`man ffmpeg-all`: https://ffmpeg.org/ffmpeg-all.html#Format-Options) with these three options (but I suspect MPV doesn't support very big TS generated by `use_wallclock_as_timestamps`):
```
demuxer-lavf-o-add="avoid_negative_ts=make_zero"
demuxer-lavf-o-add="copyts"

demuxer-lavf-o-add="use_wallclock_as_timestamps=1"
```

**Comment by Dudemanguy** [comment]
The question appears to have been answered.

**Comment by TGJek** [comment]
> Try
> 
> ```
> vf-add="setpts=PTS-STARTPTS"
> af-add="asetpts=PTS-STARTPTS"
> ```
> ...
Thank you this did solve another A/V sync. issue related to FFmpeg for me XD
