### ISSUE TITLE
system freeze on linux 

### ISSUE THREAD

**Issue by lynoxy** [mpv-player/mpv#9218]
### Important Information

Provide following Information:
- mpv version: mpv 0.33.1
- OS: EndeavourOS Linux x86_64  Kernel: 5.14.5-zen1-1-zen  DE: Cinnamon 5.0.5 
- Source of the mpv binary: [Arch Community Repository](https://archlinux.org/packages/community/x86_64/mpv/)
- If known which version of mpv introduced the problem: I've been using version 0.33 since I started using linux 
- Window Manager and version: Mutter (Muffin) 5.0.1
- GPU driver and version

           Graphics:  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel
 
                      Device-2: NVIDIA GM108M [GeForce 840M] driver: nvidia v: 470.63.01 

                      Device-3: Chicony HP Truevision HD camera type: USB driver: uvcvideo 

                      Display: x11 server: X.Org 1.20.13 driver: loaded: modesetting,nvidia unloaded: fbdev,vesa 

                      resolution: 1920x1080~60Hz 

                      OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 21.2.1 

### Reproduction steps
Playing a video freezes the entire system for a few seconds. After system freeze is gone, mpv freeze continues for few seconds.

There is no particular order of occurrence, it usually happens randomly. It happens every few plays. 

After messing around with the settings a bit, I realized that there are some settings separately causes same problem . 

1. 

    profile=gpu-hq

2. 

    sharpen=1
    saturation=15

3.

    scale=spline36
    cscale=spline36
    dscale=mitchell
    tscale=oversample
    correct-downscaling=yes
    sigmoid-upscaling=yes
    linear-downscaling=yes
    scaler-resizes-only

4.

    deband=yes
    deband-iterations=4
    deband-threshold=48
    deband-range=16
    deband-grain=48

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/7188573/mpv.log)
.
Sorry for my bad English and Linux knowledge.

**Comment by liziyi-gh** [comment]
You seem to using wayland? Try X11 instead.

**Comment by lynoxy** [comment]
❯ echo $XDG_SESSION_TYPE
    x11

I don't think I'm using wayland. As far as I know, Cinnamon (or muffin) does not support Wayland.

**Comment by Feripe-a** [comment]
yay -S downgrade
downgrade mpv

**Comment by lynoxy** [comment]
After this occurs console print "**[cplayer] audio device underrun detected.**" error. I don't know if it is related to the situation or if it is the result of freezing. Also, freezing problems have become more frequent lately, despite the absence of the settings I mentioned above. I can also say that the problem is not only related to Cinnamon. I'm currently using xfce and the same problem persists.

**Comment by lynoxy** [comment]
"force-window=immediate" solved my problem
