### ISSUE TITLE
Load fonts from external folder? how to customize directory?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9219]
### Expected behavior of the wanted feature
Option like [--sub-file-paths=](https://mpv.io/manual/master/#options-sub-file-paths), but for fonts folders.

**For example:**
 sub-file-paths=
 font-file-paths=

**Comment by hooke007** [comment]
>Option like --sub-file-paths=, but for fonts folders.

No. Same feature request could be found in the previous issues.

>Load fonts from external folder?

https://mpv.io/manual/master/#files-~/-config/mpv/fonts/

>how to customize directory?

For directwrite, it's impossible currently.
