### ISSUE TITLE
Artifacting/flickering on fullscreen mode.

### ISSUE THREAD

**Issue by aemilano** [mpv-player/mpv#9223]
### Important Information

Provide following Information:
- mpv version 
-  mpv 0.33.0-336-g62b2c5db98
- Windows Version 
-  Win10 Home Version 21H1
- Source of the mpv binary 
- https://sourceforge.net/projects/mpv-player-windows/files
- If known which version of mpv introduced the problem 
-  Problem has existed since download and redownload. Throughout multiple versions.
- Possible screenshot or video of visual glitches
- https://youtu.be/Alocf6OSJy4   (Is not visible in screen captures or screenshots)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Open any video with higher file size or resolution.

### Expected behavior
Normal video playback
### Actual behavior
Creates weird thread like artifacting glitches or flickering at the bottom of the screen while full screened throughout the video.
### Log file

https://hastebin.com/afakosekec.csharp

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
Please open a new issue if this is still a problem with 0.36.
