### ISSUE TITLE
Strange LibJack Problem

### ISSUE THREAD

**Issue by spbisc97** [mpv-player/mpv#9226]
- mpv version : 0.32.0-2ubuntu2
- Pop os 21.04

There is a problem with some libraries:
just by typing 
```
$ mpv --version  
mpv: symbol lookup error: /usr/lib/x86_64-linux-gnu/pipewire-0.3/jack/libjack.so.0: undefined symbol: pw_thread_utils_get
```
I have this message and I haven't found any info about this error

**Comment by CounterPillow** [comment]
Not an mpv issue. Your pipewire build is broken. Please contact your distributions packaging team, and file an issue there.

**Comment by spbisc97** [comment]
Thanks, sorry for bothering you!
