### ISSUE TITLE
MPV outputs blue image instead of the video when CSGO is opened in another window, bug does not occur if MPV is opened before launching CSGO, only after, and it is random

### ISSUE THREAD

**Issue by bobafettyyy** [mpv-player/mpv#9229]
*when I say that it is random, I do mean that this bug's occurrence is random

mpv version: mpv-x86_64-20210919-git-560e6c8
Windows Version 
his has been a recurring bug for months now, in every version of MPV
and i've actively updated MPV with the built-in updater

**Comment by Natural-Harmonia-Gropius** [comment]
use issue template
provide log file

I guess the problem is not enough VRAM

**Comment by Dudemanguy** [comment]
Probably a VRAM issue.
