### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [mpv-player/mpv#9230]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by sfan5** [comment]
We do not have a dedicated security contact but you are welcome to join our IRC channel and discuss it directly.

**Comment by JamieSlome** [comment]
@CounterPillow - a report has been submitted to us. You can find it here:

https://huntr.dev/bounties/ae1694fc-86ef-40fb-99c2-149993c5e415
