### ISSUE TITLE
CineForm decoding much slower on macOS than Windows

### ISSUE THREAD

**Issue by smlehbleh** [mpv-player/mpv#9231]
On similar spec'd machines, CineForm decoding is much slower on mpv on macOS than mpv on Windows. 
Windows mpv can playback 4K24p CineForm footage at full speed, on macOS, it's in the order of ~1fps.
Apologies for not including information about the exact version (I don't have access to the macOS machine), suffice to say it occurs on all macOS mpv versions I've used. 
I'm not sure if the CineForm decoding is using the official CineForm decoder (it has been open source for a few years now) or if it using libav's non-official version, but I might hazard a guess that SIMD (SSE2) optimisations are disabled/ignored on the macOS implementation maybe?

**Comment by Akemi** [comment]
if it's a decoding problem it's an ffmpeg issue. so try poking there.

**Comment by ValZapod** [comment]
> CineForm decoding is much slower on mpv on macOS than mpv on Windows.

Same Macbook?
