### ISSUE TITLE
mpv fails to build with --enable-dvbin on linux 5.14+

### ISSUE THREAD

**Issue by decathorpe** [mpv-player/mpv#9233]
### mpv version and platform versions

affects mpv 0.33.1, and the related source files have not been touched since then.

### Reproduction steps

Building mpv with `--enable-dvbin` fails with linux 5.14 kernel headers, because the `/usr/include/linux/dvb/video.h` was (re)moved, which is included in mpv's `stream/dvbin.h`.

Looking at recent linux kernel headers, this file seems to have been removed without replacement. Not sure what the expected action for application developers is.

### Expected behavior

mpv should continue to compile (though I'm not sure how to resolve this issue, since the kernel headers are just gone, without obvious replacement).

### Actual behavior

mpv fails to compile with `--enable-dvbin`.

### Log file

Build logs don't contain anything helpful other than the obvious "file `/usr/include/linux/dvb/video.h` not found".

**Comment by CounterPillow** [comment]
Exists on my 5.14 system, and elixir seems to agree with me here: https://elixir.bootlin.com/linux/v5.14.7/source/include/uapi/linux/dvb/video.h

What seems more likely to me is that your kernel is now built without dvbin support, as staging drivers are disabled by default.

**Comment by decathorpe** [comment]
Well, if those includes aren't needed at all, that's like, the best-case scenario :) Thanks for investigating.
