### ISSUE TITLE
Unable to HW decode HEVC videos on Intel GPU

### ISSUE THREAD

**Issue by Simbe** [mpv-player/mpv#9235]
### Important Information

Provide following Information:
- mpv-x86_64-20210919-git-560e6c8
- Windows 10 21H1 19043.1237

Could I get some help on getting HW decoding to work with Intel's GPU and HEVC videos?

With Windows 10 built-in "Photos" software, HW decoding works fine and I can see it in Task Manager: https://ibb.co/JqhQdGp

However with MPV, no matter what "hwdec" values I try with "mpv.conf", I cannot get this to work.

**Comment by CounterPillow** [comment]
Where's your log file?

**Comment by Simbe** [comment]
Where can I get the log file?

Currently my mpv.conf contains just the following lines:
_profile=gpu-hq
hwdec=auto_

But even with those, it doesn't make a difference. CTRL+H toggles between Hardware decoding _off_ and _d3d11va_, but performance remains the same and CPU usage is 100% while GPU usage is 0%.

**Comment by CounterPillow** [comment]
The issue template (which you've ignored) told you how to generate a log file.

**Comment by Simbe** [comment]
Sorry! Here you go:

C:\Program Files (x86)\mpv>mpv --log-file=log.txt DJI_0001.MP4
 (+) Video --vid=1 (*) (hevc 3840x2160 29.970fps)
**[ffmpeg/video] hevc: Failed setup for format d3d11: hwaccel initialisation returned error.**
VO: [gpu] 3840x2160 yuv420p
V: 00:00:07 / 00:01:06 (11%) Dropped: 47

[log.txt](https://github.com/mpv-player/mpv/files/7216242/log.txt)

**Comment by ValZapod** [comment]
> With Windows 10 built-in "Photos" software, HW decoding works fine

That has nothing to do with mpv. It uses MFF. We do not support MFF.

**Comment by Simbe** [comment]
But is there a way to get HW decoding to work for HEVC videos in Windows 10 for MPV?

**Comment by ValZapod** [comment]
> But is there a way to get HW decoding to work

Either using d3d11va or qsv.

**Comment by Simbe** [comment]
d3d11va I did already try with results above (hwaccel initialisation returned error).
For qsv, I do not see that as an available api key in https://mpv.io/manual/stable/#video ?

**Comment by Doofussy2** [comment]
You're using a Quadro P520

`[   0.249][v][vo/gpu/d3d11] Device Name: NVIDIA Quadro P520`

It doesn't support what you're trying to do

https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by Simbe** [comment]
But the Intel UHD Graphics 620 should be able to HW decode? At least it does with Windows Photos when playing HEVC videos. How can I force MPV to use that instead of Nvidia?

**Comment by jeeb** [comment]
> But the Intel UHD Graphics 620 should be able to HW decode? At least it does with Windows Photos when playing HEVC videos. How can I force MPV to use that instead of Nvidia?

I have implemented this picking for the actual d3d11 video renderer with `d3d11-adapter`, but unfortunately the d3d11va code path seems to utilize separate swap chain creation logic. You may try setting d3d11-adapter, but I don't think it will manage to affect which device will get utilized for the decoding bit.

Example:
```
mpv --d3d11-adapter=help
Available D3D11 adapters:
Adapter 0: vendor: 4318, description: NVIDIA GeForce GTX 1080
Adapter 1: vendor: 5140, description: Microsoft Basic Render Driver
```

**Comment by Simbe** [comment]
> > But the Intel UHD Graphics 620 should be able to HW decode? At least it does with Windows Photos when playing HEVC videos. How can I force MPV to use that instead of Nvidia?
> 
> If I were you, I would remove the Nvidia GPU from the rig.

Unfortunately I can't since it's integrated into my HP ZBook Firefly 15 G7 laptop :( And it does help in certain situations.

**Comment by Simbe** [comment]
> > But the Intel UHD Graphics 620 should be able to HW decode? At least it does with Windows Photos when playing HEVC videos. How can I force MPV to use that instead of Nvidia?
> 
> I have implemented this picking for the actual d3d11 video renderer with `d3d11-adapter`, but unfortunately the d3d11va code path seems to utilize separate swap chain creation logic. You may try setting d3d11-adapter, but I don't think it will manage to affect which device will get utilized for the decoding bit.
> 
> Example:
> 
> ```
> mpv --d3d11-adapter=help
> Available D3D11 adapters:
> Adapter 0: vendor: 4318, description: NVIDIA GeForce GTX 1080
> Adapter 1: vendor: 5140, description: Microsoft Basic Render Driver
> ```
> 
> You can pick it with a substring, so in my case "nvidia" would be enough to pick the nvidia one.

Thanks! I'll try this!

**Comment by ValZapod** [comment]
> Unfortunately I can't since it's integrated into my HP ZBook Firefly 15 G7 laptop

You can still turn it off in Device Manager, will require reboot.

**Comment by Hrxn** [comment]
> I have implemented this picking for the actual d3d11 video renderer with `d3d11-adapter`, but unfortunately the d3d11va code path seems to utilize separate swap chain creation logic. You may try setting d3d11-adapter, but I don't think it will manage to affect which device will get utilized for the decoding bit.
> 

Is this simply a question of implementation? Or is it generally not possible to make any distinction with regard to `d3d11-adapter` when it comes to differentiating between decode and output?

**Comment by jeeb** [comment]
> > I have implemented this picking for the actual d3d11 video renderer with `d3d11-adapter`, but unfortunately the d3d11va code path seems to utilize separate swap chain creation logic. You may try setting d3d11-adapter, but I don't think it will manage to affect which device will get utilized for the decoding bit.
> 
> Is this simply a question of implementation? Or is it generally not possible to make any distinction with regard to `d3d11-adapter` when it comes to differentiating between decode and output?

Implementation and testing. I have successfully kept away from having setups with multiple active GPUs :) (even when I had the 4790K with built-in media processing, I did keep it disabled for simplicity's sake).

The fun bit is that `video/out/d3d11/hwdec_d3d11va.c` does already utilize `ra_d3d11_get_device` at initialization, which should get it the RA's device. And the RA's device creation is done from `video/out/d3d11/context.c` , which is where the device selection is indeed taken into mention through `mp_d3d11_create_present_device`.

So, uh... according to my understanding for one reason or another it doesn't work, but I lack the capability to test/debug it :) .

**Comment by FinnRaze** [comment]
Try
```
hwdec=dxva2
d3d11-adapter=Intel(R) UHD Graphics 620
```
My GPU is HD Graphics 5500.When I put 'hwdec=yes' or 'hwdec=d3d11va',mpv failed with HW decode,whereas 'hwdec=dxva2'could work
