### ISSUE TITLE
how can take png screenshot with one key and take jpg screenshot with different key?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9236]
screenshot-format=png
screenshot-png-compression=7

screenshot-jpeg-quality=100
screenshot-format=jpg

this is setting I want to use. I want do example to take jpg screenshot with "s" key and take png screenshot with "p" screenshot.

what must I write in input.conf ?

**Comment by guidocella** [comment]
```
s set screenshot-format jpg; screenshot
p set screenshot-format png; screenshot
```

**Comment by erickyun** [comment]
> s set screenshot-format jpg

Thank you but

> screenshot-format=png
> screenshot-png-compression=7
>
> screenshot-jpeg-quality=100
> screenshot-format=jpg 

what about this settings?

**Comment by erickyun** [comment]
> Settings you put in mpv.conf are applied at startup and can later be changed with keybindings or scripts.

So if I did change png to jpg with key
**screenshot-jpeg-quality=100**
would be executed cuz it set in the mpv.conf before right
then thanks again for your help I'm closing this

**Comment by ValZapod** [comment]
> screenshot-png-compression=7

Do not forget -pred fixed of ffmpeg for png!

**Comment by erickyun** [comment]
> > screenshot-png-compression=7
> 
> Do not forget -pred fixed of ffmpeg for png!

sorry I am new in this stuff don't know what you mean with -pred?

screenshot-png-compression-pred=7 must I write it like this?
and what was fixed what was the issue before?

**Comment by ValZapod** [comment]
Actually, mixed is already the default, sorry. https://mpv.io/manual/master/
