### ISSUE TITLE
Specifying cache preread duration for streaming

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#9250]
I'm watching live VOD streams and mpv encounters buffer underruns way too often.

I'm reading the manual ( https://mpv.io/manual/master/#cache ) and I'm a bit confused:

`--cache-secs=<seconds>` is deprecated:

`Warning: option --cache-secs is deprecated and might be removed in the future (will use unlimited time).`

So, what's the proper way to increase a network buffer and what's the best way it could be done?

I've settled on `--demuxer-readahead-secs=3` but the manual doesn't make it sound like this option applies to network streams.

It would be great if the manual had a section dealing specifically with network streaming. Thank you!

**Comment by guidocella** [comment]
`cache-secs` was undeprecated with https://github.com/mpv-player/mpv/commit/f1d0365a6f72b88f7427814f636863ae1656f72a. Alternatively you can use `demuxer-max-bytes`.
