### ISSUE TITLE
MPV ruins video quality by default, why?

### ISSUE THREAD

**Issue by mzso** [mpv-player/mpv#9251]
### Important Information

Provide following Information:
- mpv version 0.33
- Windows Version 10
- Source of the mpv binary: https://www.videohelp.com/software/mpv-media-player
- Possible screenshot or video of visual glitches

### Reproduction steps

I recorded the desktop with OBS losslessly, 4:4:4 video, full range.

### Expected behavior
Play the video as it is without converting into a subsambled format.

### Actual behavior
I get this:
```
 (+) Video --vid=1 (utvideo 3840x2160 60.000fps)
 (+) Audio --aid=1 (pcm_s16le 8ch 48000Hz)
AO: [wasapi] 48000Hz 7.1 8ch float
[autoconvert] Converting yuv444p -> yuv420p
VO: [direct3d] 3840x2160 yuv420p
```
For whatever reason the video is converted to 420p. Doesn't make sense to me. It gets converted, most of the color information is trashed and then it gets rendered on a display that could show all the detail that was dumped.

**Comment by CounterPillow** [comment]
>vo: [direct3d]

because you set the direct3d VO

**Comment by mzso** [comment]
[**@CounterPillow**](https://github.com/CounterPillow) commented on [2021. szept. 29. 17:39 CEST](https://github.com/mpv-player/mpv/issues/9251#issuecomment-930295793 "2021-09-29T15:39:33Z - Replied by Github Reply Comments"):
> > vo: \[direct3d\]
> 
> because you set the direct3d VO

The opengl outputs were glitchy, typically they resulted the playback starting being delayed by a second or two.

I don' think anything's wrong with the driver, it's the latest one from AMD anyways.

**Comment by CounterPillow** [comment]
Use the GPU VO and set your gpu-api to `d3d11`. If you change your VO to a bad compatibility-only VO, then it is not "ruined by default", it is "ruined by user".

**Comment by mzso** [comment]
@CounterPillow 
Well, the other renderers always had some immediate issues, as I mentioned.
But I'll try other APIs again with GPU VO.

**Comment by mzso** [comment]
[**@CounterPillow**](https://github.com/CounterPillow) commented on [2021. szept. 29. 18:50 CEST](https://github.com/mpv-player/mpv/issues/9251#issuecomment-930354016 "2021-09-29T16:50:53Z - Replied by Github Reply Comments"):
> Use the GPU VO and set your gpu-api to `d3d11`. If you change your VO to a bad compatibility-only VO, then it is not "ruined by default", it is "ruined by user".

I guess it works decently enough. Though MPV is noticeably slower to start with d3d11.
