### ISSUE TITLE
Replacement for --vf=sub

### ISSUE THREAD

**Issue by ESSEMDEE** [mpv-player/mpv#9254]
I use "sub" in my video filter chain so that I can sharply upscale DVD subtitles. To me, sharp and pixelated looks far better than blurry, so deprecation of this filter without replacement is a concern to me.

Therefore, I ask that the sub filter be removed from the deprecation list, or that an alternative method for sharply upscaling bitmap subtitles be introduced, lest I find myself stuck on an older version of MPV in the indeterminate future.

Addendum: Currently, I use --vf=sub,scale=w=iw\*2:h=ih\*2:flags=neighbor so that the same scaling algorithm is applied to both the subtitles and the video as one. Otherwise, nearest-neighbor scaling is not applied, and the result is blurry subtitles. (--sub-gauss=0 also does not help.)

**Comment by ESSEMDEE** [comment]
The documentation does not appear to mention the depreciation status (https://mpv.io/manual/stable/#video-filters-sub) anywhere that I can see, but when invoking mpv v0.35 with --vf=sub, among the output is a warning, "[sub] This filter is deprecated and will be removed (no replacement)".

I am not sure where this depreciation list is located, but as one who utilizes libmpv, and with the noted future change of "remove all symbols that are marked as deprecated" (https://github.com/mpv-player/mpv/blob/master/libmpv/client.h#L225) in the next major bump of the library, it is from said list that I would like to see the sub filter be removed to ensure that it does not get axed in the near future.

**Comment by Dudemanguy** [comment]
>when invoking mpv v0.35 with --vf=sub, among the output is a warning, "[sub] This filter is deprecated and will be removed (no replacement)".

Yeah it's actually in the code itself heh. It would explain why I didn't see it when grepping through the docs.
