### ISSUE TITLE
Does input.conf have a variable for relative paths?

### ISSUE THREAD

**Issue by vvyoko** [mpv-player/mpv#9255]
In mpv.conf
the relative path can be described like this
`log-file="~~/log.txt"`

I want to know if there is a relative path like "~~" in input.conf
The following will not work
`ctrl+a run "~~/test.exe" "${path}"`

**Comment by guidocella** [comment]
Actually `~~` works depending on the option, not whether it's used in mpv.conf or input.conf, for example you can bind `set log-file ~~/log.txt` in input.conf. `run` does not perform this expansion, and your only alternative is using it in a script that calls `expand-path`.

**Comment by vvyoko** [comment]
> Actually `~~` works depending on the option, not whether it's used in mpv.conf or input.conf, for example you can bind `set log-file ~~/log.txt` in input.conf. `run` does not perform this expansion, and your only alternative is using it in a script that calls `expand-path`.

Does expand-path mean something like` ".. /test.exe"`

I just went to test it and this does work
But the path where the file is located is the working path

file path is 
`F:\Documents\Downloads\test.mp4
`
test.exe path is 
`F:\Documents\Downloads\test.exe
`
can do that
`ctrl+a run "test.exe" "${path}"
`
or
```
F:\Documents\test.exe
ctrl+a run "../test.exe" "${path}"
```

Is there a way to find a directory with mpv.exe as the base?

**Comment by guidocella** [comment]
`expand-path` is an mpv command, documented at https://mpv.io/manual/master/#list-of-input-commands. A script that you can put in `~~/scripts/run.lua` with this code should do what you want:

```lua
mp.add_key_binding('Ctrl+a', function ()
    mp.commandv('run', mp.command_native({'expand-path', '~~/test.exe'}), mp.get_property('path'))
end)
```

**Comment by vvyoko** [comment]
thx is work
