### ISSUE TITLE
Can some explain the Toggle stats? How do I know if my gpu isn't strong enough?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9256]
hi,

![IMG_20210930_135851](https://user-images.githubusercontent.com/71968711/135447521-93cb0476-d956-4c9c-b5f4-cde79ea50111.jpg)

I saw [here](https://wiki.piracy.moe/guides/playback#scaling#:~:text=Dropped%20frames%20or%20high%20frame%20times%20%28above%2025ms%29%20are%20a%20signal%20that%20your%20gpu%20isn%27t%20able%20to%20keep%20up%20and%20you%20should%20switch%20to%20a%20less%20demanding%20shader.) written that when upscale shaders is used
```if I see Dropped frames or high frame times (above 25ms) are a signal that your gpu isn't able to keep up```

so can someone explain where I should look for **high frame times (above 25ms)** should I look for fresh or redraw and **average or peak us**?

and what is vsync ratio and jitter? if it does say something about normal video playback what should the number always be?

is there somewhere else I should look for in the Toggle stats to be sure the video is playing normal without any problem?

**Comment by CounterPillow** [comment]
Press 2 to go to page 2, check the total.

**Comment by erickyun** [comment]
> Press 2 to go to page 2, check the total.

![IMG_20210930_143430](https://user-images.githubusercontent.com/71968711/135447914-b7185d7b-ab3d-445f-b4ae-492ea263581c.jpg)

hi thank you for your quick answer.
so where should I look here?

**Comment by erickyun** [comment]
> Press 2 to go to page 2, check the total.

![IMG_20210930_143643](https://user-images.githubusercontent.com/71968711/135448297-05eed272-4dca-4840-a605-062df5e0276f.jpg)

hi thank you for your quick answer.
so where should I look here?

**Comment by CounterPillow** [comment]
no, 25ms would be 25000 here. Note how it specifies "µs", 1000 µs = 1 ms. You'll want to look at "Fresh", and probably average.

It also shows that you're not using any shaders right now, so if you were trying to use those then you're not using them at the moment.

Realistically, the only number you need to pay attention to is "Dropped Frames". If it's at 0, you're good.

**Comment by erickyun** [comment]
> Realistically, the only number you need to pay attention to is "Dropped Frames". If it's at 0, you're good.

What if the video is playing without frame drops, what number should the average frame time be below?

and another question not with mpv but madvr in the beginning when the video starts it always drops 6-8 frames but then until the end of the video there is none frame drops 
is this a bad thing or isn't it not important that it drops frames only in the beginning?

**Comment by CounterPillow** [comment]
> What if the video is playing without frame drops, what number should the average frame time be below?

Depends on the framerate of the video, so 1 second in µs divided by the framerate.

> and another question not with mpv but madvr

this is not your personal tech support forum.

**Comment by erickyun** [comment]
> > What if the video is playing without frame drops, what number should the average frame time be below?
> 
> Depends on the framerate of the video, so 1 second in µs divided by the framerate.
>

Thank you for your answer

> > and another question not with mpv but madvr
> 
> this is not your personal tech support forum.

I see I couldn't explain myself sorry my bad english what I want to know is the same for mpv actually
is it not important that it drops frames only in the beginning and then none until until the end? 
or if framedrop only occasionally like lets say 20min long video it framedrops in beginning and 12 minute only?
