### ISSUE TITLE
Option to specify "download handler"

### ISSUE THREAD

**Issue by horusra** [mpv-player/mpv#9257]
### Note: This is not a thread for discussing your like/dislike of yt-dl/yt-dlp

**Background:** 
yt-dl gets [throttled and there is no fix in sight (yet), ](https://github.com/ytdl-org/youtube-dl/issues/29326) so some people are switching to [yt-dlp](https://github.com/yt-dlp/yt-dlp) for the time being
Having an option in the MPV config file to specify which one to use would be great.

That is all.
It doesn't matter which one you prefer, or why you want to use one over the other, but I'm just asking for the end-user to have an option to choose one over the other.

### Very easy solution:
It can be as easy as specifying the name of the handler in the MPV config file, since installing yt-dl or any of the flavors via pip install (when configured correctly) means they're in PATH so all you need to tell MPV is if it has to call youtube-dl.exe or yt-dlp.exe or yt-whatever.exe

**Comment by guidocella** [comment]
master already uses yt-dlp by default. For 0.33 you can put `script-opts-append=ytdl_hook-ytdl_path=yt-dlp` in `mpv.conf`.

**Comment by horusra** [comment]
> 
> 
> master already uses yt-dlp by default. For 0.33 you can put `script-opts-append=ytdl_hook-ytdl_path=yt-dlp` in `mpv.conf`.

Oh wow, thank you, I did not know that. I was reading a (now closed) issue that went off the rail and it seemed like there wasn't a solution yet.

**Comment by jeeb** [comment]
Has been implemented for quite a while indeed as the ytdl_path option for the ytdl_hook built-in lua script  :) .
