### ISSUE TITLE
Cycle - Remaining Time and Total Time

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#9258]
My expectations are Cycle Remaining Time and Total Time by using `g` key. And I even tried `7/8` keys if this method can be work. But nothing happens - even I don't see any errors.
(I use `cycle-cmd.js` made by @ avih)
```
g   script-message cycle-cmd "script-message timetotal yes" "script-message timetotal no"

7   script-message timetotal yes
8   script-message timetotal no

7   timetotal yes
8   timetotal no
```

- mpv v0.33 (its hard to find it - I believe it v033)
- Windows 10 Pro 21H1

**Comment by byblo** [comment]
I use this in the input.cfg to cycle remaining time / hide the time:
c cycle-values osd-level 2 1

Then onto the mpv.conf:
osd-msg2='${time-remaining}'


You can adapt it for you own needs by editing those entries. find other osd-level and osd-msg values on the user manual

**Comment by Max-Enrik** [comment]
I try the below one but still doesn't work.

Any ideas/help would be appreciated.
```
a cycle-values timetotal no yes
```
