### ISSUE TITLE
[Linux] Usage of org.freedesktop.ScreenSaver for generic idle inhibit on Wayland?

### ISSUE THREAD

**Issue by Mershl** [mpv-player/mpv#9275]
### Description

Latest mpv is reporting "GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback." while running on GNOME wayland.

https://github.com/mpv-player/mpv/blob/2d348980cbbb8a1d4f547c0cf5b09bd8d9208a0f/video/out/wayland_common.c#L1730

Other apps started using the [org.freedesktop.ScreenSaver](https://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html) interface as an generic way to support idle inhibit. Could this also be a candidate for mpv?

**Comment by CounterPillow** [comment]
mpv will not add support for dbus garbage.

**Comment by ssokolow** [comment]
For the record, I downvoted the "dbus garbage" comment because I'm a KDE+MPV user who refuses to install "GNOME garbage".

**Comment by redhat421** [comment]
I ran into this same issue on KDE under Wayland on Fedora 39. KDE didn't notice a video playing in `mpv` and thus didn't trigger presentation mode.

I forked a version of [mpv-freedesktop-screensaver-plugin.c](https://gist.github.com/redhat421/290843550ab30d8472e0788a648fede9) and added it as an `mpv` plugin. This worked perfectly to inhibit power management and the screensaver / lock.

I thinking of packaging up the plugin and distributing it like [mpv-mpris](https://repology.org/project/mpv-mpris).

P.S. `mpv` is super great! Thanks for the hard (and often thankless) work maintaining such an excellent player. :-D

**Comment by felagund** [comment]
For posteriority, the merge request was merged 8 months ago or so: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3145
Not that there is an easy inMPV solution for KDE...

**Comment by llyyr** [comment]
> Not that there is an easy inMPV solution for KDE...

KDE supports the idle inhibit protocol for years already, you don't need to do anything else for mpv to use it

**Comment by felagund** [comment]
> > Not that there is an easy inMPV solution for KDE...
> 
> KDE supports the idle inhibit protocol for years already, you don't need to do anything else for mpv to use it

Hm, but MPV does not automatically turn of KDE's night mode off, it seems to me. Do I need to set it somewhere?

**Comment by CounterPillow** [comment]
@felagund night mode is a completely different thing to screen locking inhibition
