### ISSUE TITLE
can i the change playlist media names?

### ISSUE THREAD

**Issue by ninthy** [mpv-player/mpv#9288]
i can change title but i can't change this, is it possible? (with cli arguments)

![image](https://user-images.githubusercontent.com/48928106/136675787-6002cf43-905f-485c-9bb6-38f05dd204d1.png)

**Comment by infantlogesh7x** [comment]
I am facing the same issue recently and can't find solution to resolve this, I updated from an earlier build (14 November 2022) build to latest build (23 April 2023) and find this confusing.

I have already made this changes in `mpv.conf` to not show video title in Window and Taskbar title, please give me a solution to do the same with the playlist items.

```
script-opts='osc-title=${filename}' #MPV WINDOW NAME - shows filename instead of the title metadata
title='${filename} - mpv' #MPV TASKBAR NAME - shows filename instead of the title metadata
```

14 November 2022 build
![06 - PUBG Ninja Montage #8  U-9HjO2SsdI _1080p_00_00_40 267-01-min](https://user-images.githubusercontent.com/93128864/233855304-993ea09b-1457-4522-99ec-5705583bc756.png)


23 April 2023 build
![06 - PUBG Ninja Montage #8  U-9HjO2SsdI _1080p_00_00_40 267-03-min](https://user-images.githubusercontent.com/93128864/233855310-bd5eb85a-5dee-4256-aaaf-78311fd4be87.png)

Thank you.

**Comment by Dudemanguy** [comment]
You can't individually set each playlist title, but you could use `--force-media-title` to override everything. Making the `playlist/N/title` property writeable is probably reasonable (not currently possible).
