### ISSUE TITLE
full-range YUV video not properly displayed, strong brightness increase on dark colors

### ISSUE THREAD

**Issue by damian101** [mpv-player/mpv#9289]
mpv version 0.33.1 on Arch Linux, package source https://archlinux.org/packages/community/x86_64/mpv/

Full-range YUV video is currently not displayed properly in mpv, brightness is off, black becomes gray. 
Easily noticeable in this full-range sample, where the left end of the grayscale should be pure black: https://github.com/jursonovicst/gradient/blob/master/test_sequences/1920x1080/gradient_1920-1080_0-25_yuv444p10_x265.mp4

**Comment by haasn** [comment]
That is not a full-range sample, it is a limited-range sample mistagged as full range.
