### ISSUE TITLE
Color correction (--icc-profile) and --blend-subtitles used together on an older GPU results in neither being applied, but color correction alone works normally

### ISSUE THREAD

**Issue by wyatt8740** [mpv-player/mpv#9293]
### Important Information

Provide following Information:
- mpv version

Git master.

- Platform and Version

Debian Sid

- Source of the mpv binary

Built myself from git master using GCC `Debian 10.2.1-6`.

~~If you're not using git master or the latest release, update.~~

### Reproduction steps

Using `--icc-profile` works absolutely fine, but if used alongside `--blend-subtitles=video` or `--blend-subtitles=yes` on a machine with an older GPU, suddenly color correction gets disabled because the GLSL version is apparently "too old."

### Expected behavior

Even if `--blend-subtitles` and `--icc-profile` can't be used together for some real technical reason, color correction probably should not be disabled entirely.

Ideally, both would work together, even on an Ironlake GPU (Westmere i7).

Since color correction (on its own) clearly works, it should not be disabled.

### Actual behavior

Color correction is disabled entirely if used alongside `--blend-subtitles`, making neither subtitles nor the video get any correction. So it would have been better to not pass `--blend-subtitles` to begin with.

Also, for some reason, it's trying to use the "mitchell" scaler, even though I never asked it to and the documentation states bilinear is the default. I cannot find a way to make it not try to apply "mitchell."

### Log file

[mpvb.txt](https://github.com/mpv-player/mpv/files/7326801/mpvb.txt)

### Sample files

Literally any video file that is in an appropriate pixel format.

**Comment by Dudemanguy** [comment]
Is this still an issue on 0.36?

**Comment by Dudemanguy** [comment]
No followup so closing.
