### ISSUE TITLE
Using --vo=libmpv causes no files to open

### ISSUE THREAD

**Issue by hotsno** [mpv-player/mpv#9296]
### Important Information

NOTE: I was told [here](https://github.com/mpv-player/mpv/issues/9232#issuecomment-940682960) that my "build is without swift and cocoa-cb support." I'm not quite sure what this means and how I'm supposed to fix this, but assuming this is true, then the reason for my issue is already identified, I'd just like some help figuring out how to go about doing fixing it.

Provide following Information:
- macOS Version: 11.6
- Source of the mpv binary or bundle: Followed instructions from this issue comment: https://github.com/mpv-player/mpv/issues/9232#issuecomment-925922864

### Reproduction steps

Build app bundle with Homebrew with instructions from comment linked above. Add `--vo=libmpv` to mpv.conf

### Expected behavior

Files open

### Actual behavior

Files don't open

### Log file

https://pastebin.com/kXEX0MMX

**Comment by CounterPillow** [comment]
Since this is a build problem, your `build/config.log` would be very appropriate to include here.

**Comment by Akemi** [comment]
if you installed mpv via `brew install --HEAD` adding a `-v` should at least show the configure output (something like https://github.com/mpv-player/mpv/issues/9232#issuecomment-926220843), that would already be helpful.

the most likely explanation ist, that your xcode/command line tool installation is broken and you don#t have a swift compiler and/or library installed.

**Comment by Dudemanguy** [comment]
Appears to be a user build error. Closing since it's old.
