### ISSUE TITLE
Enable native-keyrepeat by default

### ISSUE THREAD

**Issue by bno1** [mpv-player/mpv#9301]
I think native-keyrepeat should be enabled by default. I noticed that sometimes when I press the arrow key to seek it jumps 10 seconds instead of 5. The delay between detecting the press and repeating it seems very short, at least on my system. From the config it's not clear what the default delay is:

```
--native-keyrepeat
    Use system settings for keyrepeat delay and rate, instead of --input-ar-delay and --input-ar-rate. (Whether this applies depends on the VO backend and how it handles keyboard input. Does not apply to terminal input.)
--input-ar-delay
    Delay in milliseconds before we start to autorepeat a key (0 to disable).
```

I enabled native-keyrepeat and the problem is fixed. The delay is now similar to what I see in other desktop applications, and I think mpv should use the system-wide delay by default.

### Important Information

- mpv version: 0.33.1
- Platform and Version: Arch Linux
- Source of the mpv binary: Arch package repository

**Comment by Dudemanguy** [comment]
This just seems like strictly a preference thing to me that probably varies wildly depending on your OS, etc. I don't see a strong reason to change the default (just keep on using `--native-keyrepeat`).
