### ISSUE TITLE
mpv compiled with --disable-gl will occasionally crash on window resize, also blacks appear gray

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#9305]
### Important Information

- mpv 0.33.0-363-gf386fd79b2 (Latest build from master branch)
- Windows 10 Pro | 10.0.19043 N/A Build 19043

### Reproduction steps

Build from source with config --disable-gl
Play a file.
Resize the MPV window like mad for a few seconds.
Observe crash.
Also observe the 100% black intro in the sample file is slightly grey.

Demonstration video:
https://0x0.st/-GVo.mkv

### Log file

[out.log](https://github.com/mpv-player/mpv/files/7348592/out.log)

### Sample files

https://0x0.st/-GWP.mkv

**Comment by CounterPillow** [comment]
Regardless of the issue, you probably don't want to be using vo_direct3d, on account of it being a low quality compatibility VO. Fix your build to build with vo_gpu using the d3d11 or Vulkan API instead.

**Comment by Dudemanguy** [comment]
If you were using `vo_direct3d` then the crashes should have been fixed by b7bf5e619fc94ebea6dac6fff4336561fb221fbc. If this is still a problem on git master, please open a new issue.
