### ISSUE TITLE
How to play dolby vision in SDR display?

### ISSUE THREAD

**Issue by xeleven11** [mpv-player/mpv#9308]
- mpv version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
ffmpeg version: 4.3.1-4ubuntu1
- Linux Distribution and Version: Ubuntu 20.10 x64 xfce
- GPU driver and version: Nvidia 470.57.02 X.Org

### Reproduction steps

Play any file specified like below.
Format profile : Main 10@L5@Main
HDR format : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 10 bits

### Expected behavior
I want to play dolby vision videos in non-HDR display with colors close to original.
### Actual behavior
Everything is green and purple in black & white colors. My display is 6bit+FRC SDR 250cd display. Dolby vision colorspace is IPT and I cannot find any matching in mpv options. I am currently using hardware decoding and when I play dolby vision file pixel format is p010, primaries and colormatrix bt.709, gamma bt.1886

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by hooke007** [comment]
No way and dup

**Comment by ValZapod** [comment]
I just found out that DV metadata also is being applied in profile 8 in those apps! See https://drive.google.com/file/d/1-8C0ZYnIhEqOVJQ532hIJobP5XR6A7gj/view?usp=sharing

Just install two pluginß in Windows store.

**Comment by ValZapod** [comment]
IPTPQc2 can be now played with libplacebo. https://code.videolan.org/videolan/libplacebo/-/merge_requests/207#note_294293

**Comment by mailinglists35** [comment]
> IPTPQc2 can be now played with libplacebo. 

does this mean mpv will be able to play?

**Comment by ValZapod** [comment]
Yes.

**Comment by mailinglists35** [comment]
> IPTPQc2 can be now played with libplacebo. https://code.videolan.org/videolan/libplacebo/-/merge_requests/207#note_294293

I've just got [this response](https://www.paste.sh/Y4vTyKLA#EMxAs_5lMRYtUu_fYWbkEVZB) from people in #videolan on libera chat, regarding that code merge mentioned

I think some of them are developers or people with intimate knowledge of the project. I have anonymized the nicknames.

There isn't much hope for a soon working code in their project: 

Can we assume it's going to be as difficult for mpv as well?

**Comment by ValZapod** [comment]
> Can we assume it's going to be as difficult for mpv as well?

First code in ffmpeg should be merged that connect rpu to libplacebo.

**Comment by ValZapod** [comment]
MPV got Dolby Vision, besides NLQ and dynamic metadata. So can be closed.

**Comment by Dudemanguy** [comment]
Dolby vision works with gpu-next and an update system nowadays. I confess I have no idea about the hardware requirements, but the feature is there.
