### ISSUE TITLE
[Suggesion] Set af=scaletempo2 by default

### ISSUE THREAD

**Issue by All3xJ** [mpv-player/mpv#9315]
if I open a video with mpv and I increase the speed of the video, the voice of the one who is talking seems "robotic". If I instead set "af=scaletempo2" option in "~/.config/mpv/mpv.conf", and I increase the speed, the voice is good.

### Expected behavior of the wanted feature
mpv should opens by default with af=scaletempo2, if there are not issues with that. it seems better.

**Comment by sfan5** [comment]
duplicate of #8376, this was already done.

**Comment by All3xJ** [comment]
> duplicate of #8376, this was already done.

ok, sorry. Can't believe I didn't realized that. I have also checked for duplicates.....
