### ISSUE TITLE
frame-back-step doesn't work with .ts files

### ISSUE THREAD

**Issue by epistularum** [mpv-player/mpv#9317]
### Important Information

- mpv 1:0.33.1-3
- Arch
- Arch repository (community)
- i3-gaps 4.19.1-1
- nvidia 470.74-5

### Reproduction steps

1. Play .ts file
2. Press "," frame-back-step

### Expected behavior

Goes back one frame, even when pressed multiple times.

### Actual behavior

Doesn't go back one frame or it does work but only for a few key presses and then stops responding to further key presses. Works correctly on non-ts files.

### Log file

https://0x0.st/-kIc.txt

### Sample files

https://0x0.st/-kI1.ts

### Mediainfo

https://0x0.st/-kIQ.txt

**Comment by BikramKumar6928** [comment]
All the configurations are same, except I am on KDE.

I am also facing similar issue. 

I cannot seek back by 3 seconds and when I seek forward, I see that it jumps further.

When I seek by 30 seconds, it jumps, but not to the exact timestamp.

I think it is some issue with precision seeking and keyframes, but I tried it without precision seeking but had the same result.

**Comment by Dudemanguy** [comment]
This is just a limitation of the format. Seeking is never going to work well. See https://github.com/mpv-player/mpv/issues/9639#issuecomment-1001034332.
