### ISSUE TITLE
Add --tone-mapping=aces, bt.2446, heatmap and no

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9320]
ACES provides good contrast and vivid result, been used in video games popularly as hable now. especially this is the default tonemapper of unreal engine.
https://knarkowicz.wordpress.com/2016/01/06/aces-filmic-tone-mapping-curve
https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/PostProcessEffects/ColorGrading/
```glsl
vec3 ACESToneMapping(vec3 color, const float adapted_lum)
{
    const float A = 2.51;
    const float B = 0.03;
    const float C = 2.43;
    const float D = 0.59;
    const float E = 0.14;

    color *= adapted_lum;
    return clamp((color * (A * color + B)) / (color * (C * color + D) + E), 0.0, 1.0);
}
```

BT.2446 provides better result for HLG, that "BT.2390" dim the normal bright areas, "clip" drop all of highlights.
https://trev16.hatenablog.com/entry/2020/08/01/131907 (implementation of PQ)

Heatmap privides result as the some one of this, for tests or balabala...
![image](https://user-images.githubusercontent.com/50797982/144607061-e046c9fb-e966-45df-870f-72f88f901c3d.png)
https://trev16.hatenablog.com/entry/2020/04/26/190416

Last thing, add tone-mapping=no to disable internal tonemapping method, for possible to use custom tonemapper by `--glsl-shader`

**Comment by Natural-Harmonia-Gropius** [comment]
Closed by https://github.com/mpv-player/mpv/commit/a9cb2e2821adb40e7548e8233390e79706104041
Reopen this if necessary.

**Comment by haasn** [comment]
I'll track this [in libplacebo](https://code.videolan.org/videolan/libplacebo/-/issues/180)
