### ISSUE TITLE
GPU Decode and Direct rendering

### ISSUE THREAD

**Issue by ksmuthucv** [mpv-player/mpv#9322]
**MPV Version and Platform**

MPV Version: 0.33
Windows 10
Nvidia GPU: GeForce Drivers 471.68, Version 82.7.7f.0.14
Open GL: 4.6
Vulkan: 1.2.175

**Reproduction steps**
- Not Applicable

**Expected behavior**
Is it possible to configure MPV player, so that the frame is decoded in GPU memory and rendered directly to the screen without copying back the frame/required details to CPU memory? The goal is run 20+ video/ip sources in our lab with as minimal usage of CPU.

**Actual behavior**
- Not Applicable.

Please advice.

**Comment by CounterPillow** [comment]
> Or is there a parameter where the the gpu number (1,2) can passed while using hwdec=auto?

`--cuda-decode-device`, please consult the manual for further info.
