### ISSUE TITLE
Option to disable auto resize

### ISSUE THREAD

**Issue by svefro** [mpv-player/mpv#9325]
I would like the mpv window to never change size unless i do something like maximize or resize manualy.
having the window automaticaly rezise to the opened file is unpredictable behaviour.

i use Uosc to navigate trough folders using a keyboard shortcut and the window changes size on every file load. also it snaps out of the maximised state, to maximize again i have to first turn off maximize and then re-maximize

**Comment by guidocella** [comment]
I think this depends on the window manager since with my script and window manager the window size is kept after resizing it and changing file, but you can try https://github.com/occivink/mpv-image-viewer/blob/master/scripts/freeze-window.lua which seems to set the geometry again on every resize.

**Comment by CounterPillow** [comment]
> i guess you could not figure it out either @CounterPillow ??

The geometry option does set the window to a fixed size for me, even across playlist entries. Is this not what you wanted?

**Comment by svefro** [comment]
> > i guess you could not figure it out either @CounterPillow ??
> 
> The geometry option does set the window to a fixed size for me, even across playlist entries. Is this not what you wanted?

Yes it set's a fixed size but it does not keep the size when changing video files.

**Comment by CounterPillow** [comment]
>  Maybe all the files in your playlist are the same resolution?

Even with files of different resolution in the playlist, mpv does not resize for me when using the geometry option.

Can you post a `--log-file` of you trying this? That way we can perhaps spot what makes it resize.

**Comment by svefro** [comment]
Here it is.
[https://1drv.ms/t/s!AmiOAvwbn4gdkd0xB7XHr6vMPpaBtA?e=ejQoYo]

I started with a clean mpv release from sourceforge/64bit/mpv-x86_64-20211017-git-e13fe12.7z

added portable_config/mpv.conf
added line "geometry=40%x40%"
(i do not have any config in %appdata% since i sync my normal installation and configuration to one-drive and then to 5 different computers around the house, this way i use the same config on all devices)

started mpv by running
"mpv --log-file=C:\Temp\mpv_log.txt V:\ATV"
maximized the window by clicking the maximize button
navigated to to another file using ">" key
resulting in the window resizing.
-closed the window.

mpv still thinks it is maximized after resizing. so if i want it to maximize again i have to click 2 times on the maximize button

**Comment by stax76** [comment]
Since you are on Windows, mpv.net beta would support it.

**Comment by svefro** [comment]
Thank you @Dudemanguy :)

**Comment by Dudemanguy** [comment]
Well it's not merged yet so we should keep this issue open.

**Comment by hooke007** [comment]
I don't know which commit had fixed the issue.
`--geometry` works well now in windows.

**Comment by Dudemanguy** [comment]
This is just missing on mac now. I didn't attempt it because I'm not sure how the swift/cocoa/etc. stuff works. But anyways if someone wants to try it, it might be as simple as modifying this one line.

https://github.com/mpv-player/mpv/blob/c993d5c0ce79ab560e86da8d6d5fe25da35b4c78/video/out/cocoa_common.m#L721

Possibly?
```
diff --git a/video/out/cocoa_common.m b/video/out/cocoa_common.m
index 222dde4520..cbf479e2df 100644
--- a/video/out/cocoa_common.m
+++ b/video/out/cocoa_common.m
@@ -718,7 +718,8 @@ int vo_cocoa_config_window(struct vo *vo)
         uint32_t width = vo->dwidth;
         uint32_t height = vo->dheight;
 
-        bool reset_size = s->old_dwidth != width || s->old_dheight != height;
+        bool reset_size = (s->old_dwidth != width || s->old_dheight != height) &&
+                          opts->auto_window_resize;
         s->old_dwidth  = width;
         s->old_dheight = height;
 
```

**Comment by Akemi** [comment]
that's the old deprecated code.

either here
https://github.com/mpv-player/mpv/blob/master/video/out/cocoa_cb_common.swift#L68-L71

or here
https://github.com/mpv-player/mpv/blob/master/video/out/cocoa_cb_common.swift#L85-L101

**Comment by Dudemanguy** [comment]
Hah, good thing I didn't attempt it.

**Comment by hooke007** [comment]
@Akemi It's a WIN issue, why it is cloesd by a mac's solution? https://github.com/mpv-player/mpv/issues/9325#issuecomment-947355887
