### ISSUE TITLE
Media buttons not working when mpv isn't focused

### ISSUE THREAD

**Issue by BeauTaapken** [mpv-player/mpv#9336]
### Important Information

Provide following Information:
- mpv version: 0.33.0-376-ge13fe1299d
- Windows Version: 20H2
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20211017-git-e13fe12.7z

### Reproduction steps

1: Start mpv in any way you want(exe or terminal).
2: Focus on another window like a browser or game.
3: try to use media buttons.

### Expected behavior

The player receives the media button input

### Actual behavior

The player doesn't receive the media button input

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/7390885/output.txt).

**Comment by BhaturaGuy** [comment]
> > Global hotkeys are generally not supported in mpv I think
> 
> Global hotkeys in general are not supported, but global media keys _should_ work on windows and osx, and are supposedly enabled by default. See https://mpv.io/manual/master/#options-input-media-keys
> 
> I tested it on osx and it works. On windows it should work but I don't have a KB with media keys to test.


Yes they _do_ work but if and only if mpv is focused or on top, if it's in background(not on top) or minimized it won't work.

**Comment by stax76** [comment]
AutoHotkey is an essential tool on Windows, for global mpv media keys this will work:

`Media_Play_Pause::ControlSend, ahk_parent, {Space}, ahk_exe mpv.exe`

**Comment by BhaturaGuy** [comment]
> AutoHotkey is an essential tool on Windows, for global mpv media keys the following works:
> 
> `Media_Play_Pause::ControlSend, ahk_parent, {Space}, ahk_exe mpv.exe`

Sure works for play/pause. Forward/Backward, stop media keys won't work.

**Comment by stax76** [comment]
Here are some helpful bookmarks:

https://www.autohotkey.com
https://www.autohotkey.com/docs/Tutorial.htm
https://www.autohotkey.com/docs/Hotkeys.htm
https://www.autohotkey.com/docs/KeyList.htm
https://www.autohotkey.com/docs/commands/ControlSend.htm

**Comment by escapezn** [comment]
mpv 0.34 has the same issue.

**Comment by escapezn** [comment]
I tried the lastest build [here](https://github.com/shinchiro/mpv-winbuild-cmake/releases), but it doesn't seem to work.

**Comment by kasper93** [comment]
It works, but if you have multiple media players open, you have to select the one you want to control in media controls window.

**Comment by escapezn** [comment]
I'm not sure what I missed but the media controls don't show the tracks when mpv is playing
![屏幕截图 2024-07-30 221340](https://github.com/user-attachments/assets/fb9194e1-439a-4690-b517-44f2ff90007a)
![屏幕截图 2024-07-30 221420](https://github.com/user-attachments/assets/387b14dc-0e35-4e8a-80cf-be01b466fa17)

**Comment by kasper93** [comment]
post logs

**Comment by escapezn** [comment]
[mpv.log](https://github.com/user-attachments/files/16429455/mpv.log)

**Comment by zhongfly** [comment]
> I tried the latest build [here](https://github.com/shinchiro/mpv-winbuild-cmake/releases), but it doesn't seem to work.

If you are talking about Media Control, I should tell you that shinchiro's build didn't support it yet.

**Comment by escapezn** [comment]
> > I tried the latest build [here](https://github.com/shinchiro/mpv-winbuild-cmake/releases), but it doesn't seem to work.
> 
> If you are talking about Media Control or System Media Transport Controls (#14338), I should tell you that shinchiro's build didn't support it yet.

Oh it's pity

**Comment by zhongfly** [comment]
> > If you are talking about Media Control or System Media Transport Controls (#14338), I should tell you that shinchiro's build didn't support it yet.
> 
> Oh it's pity

If you want to try Media Control, you can use my builds: https://github.com/zhongfly/mpv-winbuild/releases
And shinchiro's builds will support it after https://github.com/shinchiro/mpv-winbuild-cmake/pull/670 merged (my builds have merged it)

**Comment by escapezn** [comment]
> > > If you are talking about Media Control or System Media Transport Controls (#14338), I should tell you that shinchiro's build didn't support it yet.
> > 
> > 
> > Oh it's pity
> 
> If you want to try Media Control, you can use my builds: https://github.com/zhongfly/mpv-winbuild/releases/latest And shinchiro's builds will support it after [shinchiro/mpv-winbuild-cmake#670](https://github.com/shinchiro/mpv-winbuild-cmake/pull/670) merged (my builds have merged it)

I noticed that there are no thumbnails (album art) on the media controls when playing music, is that expected?

**Comment by kasper93** [comment]
> I noticed that there are no thumbnails (album art) on the media controls when playing music, is that expected? What about https://github.com/mpv-player/mpv/commit/6a43514097b709eb5a70b33f25b3ad3db92e7bac ?

There are multiple factors that may affect if thumbnail is shown or not. Do you have exact example when it fails and should work? I can look, but need steps to reproduce.

**Comment by escapezn** [comment]
> > I noticed that there are no thumbnails (album art) on the media controls when playing music, is that expected? What about [6a43514](https://github.com/mpv-player/mpv/commit/6a43514097b709eb5a70b33f25b3ad3db92e7bac) ?
> 
> There are multiple factors that may affect if thumbnail is shown or not. Do you have exact example when it fails and should work? I can look, but need steps to reproduce.

No matter the albumart is internal or external, there are no thumbnails in media control. This is a sample file
![屏幕截图 2024-08-01 203340](https://github.com/user-attachments/assets/4612859a-c33c-426c-9640-0e1f5bacd89d)
[mp3.zip](https://github.com/user-attachments/files/16456463/mp3.zip)

**Comment by escapezn** [comment]
Interestingly video files are ok, as long as windows explorer can show thumbnails, media controls can. Otherwise it will show the mpv icon. I'm running windows 10 22h2.

**Comment by zhongfly** [comment]
> Interestingly video files are ok, as long as windows explorer can show thumbnails, media controls can. Otherwise it will show the mpv icon. I'm running windows 10 22h2.

work for my windows 10 22h2 19045.4651 (Windows Feature Experience Pack 1000.19060.1000.0)
![image](https://github.com/user-attachments/assets/106cffc5-b7a2-4e46-8c1a-d6a99429271f)

**Comment by kasper93** [comment]
> > No matter the albumart is internal or external, there are no thumbnails in media control. This is a sample file.
> > 
> > I am using @zhongfly's [build](https://github.com/zhongfly/mpv-winbuild/releases/latest) with no config file for test. ![屏幕截图 2024-08-01 203340](https://private-user-images.githubusercontent.com/30799958/354224021-4612859a-c33c-426c-9640-0e1f5bacd89d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTY3ODAsIm5iZiI6MTcyMjUxNjQ4MCwicGF0aCI6Ii8zMDc5OTk1OC8zNTQyMjQwMjEtNDYxMjg1OWEtYzMzYy00MjZjLTk2NDAtMGUxZjViYWNkODlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEyNDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTY0NTk1OGZjNzM4ODNkYjM0ZDczY2UwOTQ4Yjg4ZTY1NmU1NTE2YTI4YTdjZTlhMzYyMTFkOTBlNDRhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kNVQxaHGNWttL4P26m-k2cP0txERfw8kWHRWbd7jVTc) [mp3.zip](https://github.com/user-attachments/files/16456463/mp3.zip)
> 
> work for me,I'm using Windows 11 23H2
> ![image](https://github.com/user-attachments/assets/9f4de4c2-b908-4732-b5a5-b57d1db405ca)
> 

How do you manage to make it show the mpv logo and name it the top left corner? It doesn't work for me. I'm curious what it is based on.

**Comment by zhongfly** [comment]
> How do you manage to make it show the mpv logo and name it the top left corner? It doesn't work for me. I'm curious what it is based on.

It should be one of those commands: https://github.com/shinchiro/mpv-packaging/blob/master/mpv-root/installer/mpv-install.bat
I found that I was able to show the mpv logo and name after using this script to install mpv

**Comment by kasper93** [comment]
someone™ should port it to mpv. Not by default, but `--install` or `--register` command should be available.
