### ISSUE TITLE
Clever invert of colors in video

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [mpv-player/mpv#9338]
### Expected behavior of the wanted feature

While watching elearning videos, I am able to negate colors in order to ease eyes at nights.
In this manner, white portions of the recorded lecture  become black, and that's ok, but there are portions that were originally black and become white upon invertion, while I want to keep them black.
Is there a filter or some magic ffmpeg command to do that?
I would like to use only mpv since maybe I can hack some ffmpeg commands to do that, but I have to do it custom per video and maybe I have to use disk space and waste CPU time.
the black portion I want to remain black after invertion is total black, since it comes from zoom recorded applications
I have mpv  0.33.0 on ubuntu 20.04.

**Comment by Dudemanguy** [comment]
The GLSL shader seems like a sufficient solution.

**Comment by omaru-ok** [comment]
@haasn & @JohnPlayerSpecial 
i really like that script but instead of using old command in ur `[input.conf](https://github.com/azimut/dotfiles/commit/cf7ba934a2806b81b475c8acf18d669f6cb00be6#diff-3a468cc672b0ae3cee7c650add6fb6c8bddb1dd8d29fb89b16569d13190dc42aR77) as 
```
F1  no-osd change-list glsl-shaders set "~~/shaders/invert.glsl"; show-text "Invert Shader"
```
i rather reccomand you to use 
```
KEY  no-osd cycle-values glsl-shaders "~~/shaders/invert.glsl" "" ; show-text "Invert Shader"
```

**Comment by escape0707** [comment]
Isn't the GLSL shader only do a luma invertion? I thought the OP wants an invertion of luma only when it's not very low.

**Comment by NormTurtle** [comment]
no its based on intensity i guess.

**Comment by escape0707** [comment]
@NormTurtle Could you point to me where I can find the documentation for the data type and the LUMA_texOff function? I can't find the documentation for that function name with Google at all. And I searched it in GLSL specification but no hit.

**Comment by NormTurtle** [comment]
sorry i misunderstood as because how i use them.
my binding
```
o cycle-values vf negate ""
O no-osd cycle-values glsl-shaders "~~/shaders/invert.glsl" ""; show-text "Invert Shader"
```

the code `invert.glsl` does that 
>shader function that takes a texture, calculates its luminance, and returns an inverted version of the texture based on its brightness values.

**Comment by joskezelensky** [comment]
you can also use --vf=negate if you want your colours inverted
