### ISSUE TITLE
Help: mpv-1.dll 

### ISSUE THREAD

**Issue by ksmuthucv** [mpv-player/mpv#9340]
Hello Team,

MPV Version: 0.33.0
OS: Windows 10

Request:
While running the mpv with command say "mpv --d3d11-adapter=help > results.txt" from cmd prompt, it would return list of possible display adapters of the machine and results.txt will have them written. 

Is it possible to achieve the same while using mpv-1.dll i.e. invoke a function with --d3d11-adapter=help and get the adapters in a string? If that would be possible, can you please guide on how to achieve it?

Thank you.

**Comment by stax76** [comment]
https://github.com/smourier/DirectN

**Comment by softworkz** [comment]
> Most mpv CLI options are properties, it's easy to access and change properties with libmpv, only certain CLI functionality cannot be accessed from libmpv because the functionality is not property based

> No, this is not possible, because mpv-1.dll is a library, which can be used from within your own project, but it does not have a CLI interface.

Both statements are incorrect. MPV **does** have a command interface and you can execute commands with `mpv_command()`  and similar functions.

**Comment by softworkz** [comment]
> Is it possible to achieve the same while using mpv-1.dll i.e. invoke a function with --d3d11-adapter=help and get the adapters in a string? If that would be possible, can you please guide on how to achieve it?

Yes, it is possible!

You just need to process event messages of type `MPV_EVENT_LOG_MESSAGE` and record the log message.

Then you can do one of the following:

- call `mpv_set_property()` and set `d3d11-adapter` to 'help'
  or
- call `mpv_command_string()` with the command text `set d3d11-adapter help`

In both cases, you'll get a `-4` error, but the device list will have been printed via event log messages.
