### ISSUE TITLE
mpv crashes while moving forward and backward

### ISSUE THREAD

**Issue by Germano0** [mpv-player/mpv#9345]
### Important Information

Provide following Information:
- mpv version: mpv-0.33.1-4.fc34.x86_64
- Linux Distribution and Version: Fedora 34
- Source of the mpv binary: https://koji.rpmfusion.org/koji/buildinfo?buildID=20248
- Window Manager and version: KDE Plasma 5.22.5
- GPU driver and version: 00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09), drivers in kernel 5.14.9-200.fc34.x86_64

### Reproduction steps
I use command
```
mpv --log-file=output.txt -vo=vaapi -hwdec=vaapi -hwdec-codecs=all 2021_1021_104515_F.MP4
```
and such video file triggers this crash when you move keyboard arrows to go backward or forward

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/7403755/output.txt)
[gdb.txt](https://github.com/mpv-player/mpv/files/7403756/gdb.txt)

### Sample files

Can't provide for privacy reasons

**Comment by Dudemanguy** [comment]
Is this still an issue? I can't reproduce.

**Comment by Dudemanguy** [comment]
Will assume this doesn't happen anymore on git master given some of the recent vaapi fixes (feel free to reopen if it still does).
