### ISSUE TITLE
mpv should be called a media player, not a "movie" player in the man page.

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#935]
Right now it says:

> mpv is a movie player based on MPlayer and mplayer2. It supports a wide variety of video file formats, audio and video codecs, and subtitle types.

Since it perfectly plays pure audio, it's more proper to say:

> mpv is a media player based on MPlayer and mplayer2. It supports a wide variety of video and audio file formats, audio and video codecs , and subtitle types

**Comment by shmerl** [comment]
FYI, the title page on Github still uses the old "movie player" title: https://github.com/mpv-player/mpv

**Comment by wm4** [comment]
Changed.

**Comment by qbb** [comment]
https://github.com/mpv-player/mpv/search?utf8=%E2%9C%93&q=movie
