### ISSUE TITLE
vf=gpu for windows

### ISSUE THREAD

**Issue by feanor3** [mpv-player/mpv#9354]
### mpv version and platform versions
latest version cloned today from github, ubunutu 20.04 on Virtual Box

### Reproduction steps
Installed MXE and compiled mpv as [here](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md) 64 bit

### Expected behavior
I was trying to do the same thing as [this](https://github.com/mpv-player/mpv/issues/7194), which is rendering a video and applying a glsl shader to it using --vf=gpu. Searching online, I found out that this filter was aviable on linux and not on windows: in fact, after installing official mpv.exe from mpv.io, the command mpv --vf=help doesn't list "gpu", while on linux it did. 
So i thought that maybe this [code](https://github.com/mpv-player/mpv/commit/90df6c79c9400d3f1c711ef5696324908a5126ce) wasn't compiled for windows, and so I cross compiled mpv from ubunutu to windows, hoping the problem was that, but it didn't work.
Since in vf_gpu there is 
`#if HAVE_EGL_X11
    &vf_gpu,
#endif`
 and mpv configuration outputs 
```
Checking for Linux's memfd_create()                                       : wayland not found 
Checking for X11                                                          : no ('x11 >= 1.0.0 xscrnsaver >= 1.0.0 xext >= 1.0.0 xinerama >= 1.0.0 xrandr >= 1.2.0' not found) 
Checking for Xv video output                                              : x11 not found 
Checking for OpenGL Cocoa Backend                                         : cocoa not found 
Checking for OpenGL X11/GLX (deprecated/legacy)                           : disabled 
Checking for Raspberry Pi support                                         : disabled 
Checking for EGL 1.4                                                      : no ('egl' not found) 
Checking for OpenGL X11 EGL Backend                                       : x11 not found 
Checking for OpenGL DRM EGL Backend                                       : drm not found 
Checking for OpenGL Wayland Backend                                       : wayland not found 
Checking for OpenGL Win32 Backend                                         : yes 
Checking for OpenGL/DirectX Interop Backend                               : yes 
Checking for OpenGL ANGLE headers                                         : no 
Checking for OpenGL Win32 ANGLE Library                                   : egl-angle not found 
Checking for OpenGL Win32 ANGLE Backend                                   : egl-angle not found 
Checking for VDPAU acceleration                                           : x11 not found 
Checking for VDPAU with OpenGL/X11                                        : vdpau not found 
Checking for VAAPI acceleration                                           : x11 not found 
Checking for VAAPI (X11 support)                                          : vaapi not found 
Checking for VAAPI (Wayland support)                                      : vaapi not found 
Checking for VAAPI (DRM/EGL support)                                      : vaapi not found 
Checking for VAAPI EGL on X11                                             : vaapi-x11 not found 
Checking for VAAPI EGL                                                    : vaapi-x-egl not found 
Checking for CACA                                                         : yes 
```
I think it is related to these missing x11 and opengl (?).
### Actual behavior
Is there a way I can compile mpv so that vf=gpu is aviable on windows?

### Log file
[config.log](https://github.com/mpv-player/mpv/files/7411941/config.log)

**Comment by Dudemanguy** [comment]
The `vf_libplacebo` filter should work and accomplish the same thing so closing? Feel free to complain if I'm wrong.
