### ISSUE TITLE
Protocol mpv://

### ISSUE THREAD

**Issue by greyrat116** [mpv-player/mpv#9364]
### Expected behavior of the wanted feature
Launching the player after the link in the browser

A similar one is implemented in Potplayer (potplayer://). The same request from VLC https://forum.videolan.org/viewtopic.php?f=14&t=157968&p=520097#p520097

**Comment by gunir** [comment]
For people who curious, this is a plugin that allows the use of `mpv://`: https://github.com/FirefoxUniverse/FirefoxTweaksVN/blob/main/mpv/scripts/protocol_hook.lua

You need to install this script to your Userscript Manager (preferbly Violentmoney): https://github.com/FirefoxUniverse/FirefoxTweaksVN/blob/main/userscript/Handlers%20Helper.user.js

And patch your browser `handlers.json` (`about:support` -> Open Profile Folder) using this: https://htmlpreview.github.io/?https://github.com/FirefoxUniverse/FirefoxTweaksVN/blob/main/utility/handlers_patcher.html

If you do everything correctly, congrats, this is how you use it: https://streamable.com/4s1gfi

**Comment by llyyr** [comment]
Or you could set mpv as the default application for .m3u files and use https://github.com/llyyr/play-url
