### ISSUE TITLE
Totally black window on Ubuntu 21.10 Nvidia Proprietary Wayland Gnome

### ISSUE THREAD

**Issue by tearfur** [mpv-player/mpv#9365]
### Important Information

- mpv 0.33.1 (From Ubuntu repo, `sudo apt install mpv`)
- Ubuntu 21.10
- Mutter 40.5
- NVIDIA proprietary 495.29.05 (From NVIDIA repo, `sudo apt install cuda`)
- GTX1080

### Reproduction steps

I just did a fresh install, and I did install a few other things before this, but I hope these steps would still work:
1. Fresh install Ubuntu 21.10. Normal installation (as opposed to Minimal installation) and with 3rd party drivers
2. Install CUDA SDK from NVIDIA repo https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network
3. Run `sudo apt install libnvidia-egl-wayland1`
4. Reboot
5. Comment out `WaylandEnable=false` in `/etc/gdm3/custom.conf`
6. Add `nvidia-drm.modeset=1` to `GRUB_CMDLINE_LINUX_DEFAULT` in `/etc/default/grub`
7. Run `sudo update-grub`
8. Reboot, login to Wayland session, the About page in settings should look something like this, it should show the model of the graphics card instead of `llvmpipe`. Windowing system should show Wayland
![image](https://user-images.githubusercontent.com/46261767/139344674-a0d056a0-e71e-4732-92c7-ce569277b8a0.png)
9. Install mpv and create this `mpv.conf` in `~/.config/mpv`: [mpv.txt](https://github.com/mpv-player/mpv/files/7437700/mpv.txt) (renamed to .txt so that GitHub accepts it)
10. Play any video file (at least every one I tried had this problem)

### Expected behavior

The video plays, on-screen controls appear when hovering the mouse over.

### Actual behavior

A black window with no on-screen controls and only audio playing. Not even GNOME's window bar can be seen. Keyboard controls appears to be still working.

Using `--no-config` still has the issue, but it did remove this line of error in stdout:
```
[vaapi] libva: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
```

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/7437698/log.txt)

**Comment by floatingrain** [comment]
>     3\. `sudo apt install libnvidia-egl-wayland1`

This unexpectedly solved a problem I had with the nvidia driver installation using the ubuntu software and updates app where it was only showing llvmpipe under wayland, after installing this package it finally shows the driver correctly! Where did you see this command line please?

**Comment by hogcryat** [comment]
> 
> 
> > ```
> > 3\. `sudo apt install libnvidia-egl-wayland1`
> > ```
> 
> This unexpectedly solved a problem I had with the nvidia driver installation using the ubuntu software and updates app where it was only showing llvmpipe under wayland, after installing this package it finally shows the driver correctly! Where did you see this command line please?

https://askubuntu.com/q/1369250
