### ISSUE TITLE
Memory Growing

### ISSUE THREAD

**Issue by ksmuthucv** [mpv-player/mpv#9373]
Environment Details:
mpv version: 0.33.0-376
Windows Version: 10
Language: C#

### Reproduction steps
I took the code from below link and wrote a player based on it. This application would launch the 16 instances of the mpv lib while pressing enter and on pressing escape it would dispose them. But when I try to run this scenario multiple times the memory of the application keeps growing. 

[](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/csharp/Form1.cs)

### Expected behavior
Memory of the application to stay close to the start up value.

### Actual behavior
Memory of the application keeps growing.
![image](https://user-images.githubusercontent.com/16358707/139587170-dc2f4b97-754d-40ac-bebb-a4fcb40881da.png)

### Sample files
Please find the attached file containing the code for the application.
[RenderMpv.txt](https://github.com/mpv-player/mpv/files/7448958/RenderMpv.txt)

Please advise.

**Comment by CounterPillow** [comment]
Might be the libass glyph cache (which has bounded growth so it's not really an issue in practice), try with `--no-osc` (the OSC uses libass for rendering)

**Comment by ksmuthucv** [comment]
added below line after initializing mpv handle, could see the memory growth still.
_mpvSetOptionString(_mpvHandle, GetUtf8Bytes("osc"), GetUtf8Bytes("no"));

![image](https://user-images.githubusercontent.com/16358707/139608124-dab21fe1-4401-4d7d-87ba-73067db6aef5.png)

**Comment by Dudemanguy** [comment]
If this is still a problem on 0.36, please open a new issue.
