### ISSUE TITLE
Does sigmoid-upscaling=yes affects cscale options?

### ISSUE THREAD

**Issue by yeezylife** [mpv-player/mpv#9374]
I've read the manual [https://mpv.io/manual/master/#options-sigmoid-upscaling](url) here,it just says "When upscaling, use a sigmoidal color transform to avoid emphasizing ringing artifacts. "

If sigmoid-upscaling=yes affects cscale too,I could use something like cscale=lanczos without worring the ringing artifact.

**Comment by haasn** [comment]
It does not. Sigmoidization is only done after linearization anyway, so doing it directly on cscale wouldn't make much sense.

I'd recommend not worrying about it.
