### ISSUE TITLE
MPV Dynamic Properties on the fly

### ISSUE THREAD

**Issue by vinothbellie** [mpv-player/mpv#9377]
mpv version:0.33.0-376
windows: 10
lang: c#

We could start the mpv player using C# Process instance. We have invoked mpv by passing --input-terminal argument and enabled standard input redirection for the process instance. Now, lets say we have started the mpv player with volume as 50 (i.e. --volume=50). Is it possible to change the volume to 75 on the fly by writing to the standard input i.e. --volume=75?

**Comment by CounterPillow** [comment]
You probably want to use the JSON IPC for this, not input-terminal. https://mpv.io/manual/master/#json-ipc

**Comment by avih** [comment]
Changing mpv properties at runtime is documented. If you think some docs are missing on incorrect on this subject, please request to re-open this issue.

**Comment by garoto** [comment]
`--input-terminal` is known to be not working on Windows when redirecting stdin.
