### ISSUE TITLE
mpv 0.34.0 crashes with shaders

### ISSUE THREAD

**Issue by lavilao** [mpv-player/mpv#9381]
Hi I just updated to 0.34.0 and found a little problem, mpv now crashes with 
```Resuming playback. This behavior can be disabled with --no-resume-playback.
[autoload] Adding y2mate.com - AMDs gift to ALL gamers  FidelityFX Super Resolution_480p.mp4
 (+) Video --vid=1 (*) (h264 854x480 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[vo/gpu/vulkan/libplacebo] Storable format 'bgr565' has no matching GLSL format qualifier but read/write without format is not supported.. disabling
[vo/gpu/vulkan/libplacebo] Storable format 'bgr5a1' has no matching GLSL format qualifier but read/write without format is not supported.. disabling
[auto_profiles] Applying auto profile: 2
fish: Job 1, 'mpv y2mate.com\ -\ AMD\ Fidel...' terminated by signal SIGSEGV (Address boundary error)
```
this did not happened with 0.33.1, here is my config file. I am using garuda linux sway
[ravu-litex2-vk.zip](https://github.com/mpv-player/mpv/files/7462406/ravu-litex2-vk.zip)

**Comment by jeeb** [comment]
try running under `gdb` with `gdb --args mpv --other --player --arguments`.

It will tell you whether it was able to load symbols or not - if you are building yourself it should have symbols, on many distros symbols are packaged in a dbg/debug package. If it's a packaged version, install those debug symbols and re-run.

Then as it crashes, see `thread apply all bt full`, that should dump the backtrace of each thread within mpv.

**Comment by lavilao** [comment]
Just installed gdb and I'm a bit lost, running 
```gdb --args ~/Games/mpv y2mate.com\ -\ AMD\ Fidelity\ Fx\
Super\ Resolution\ for\ all\ gamers\ thoughts\ \ impressions_4
80p.mp4```
outputs 
```
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/luis/Games/mpv...
(gdb)
```
what do I do now?

**Comment by lavilao** [comment]
F, the comment broke!

**Comment by lavilao** [comment]
this is the gbd output
```
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/luis/Games/mpv...
(gdb)
```

**Comment by lavilao** [comment]
and this was the command
```
gdb --args ~/Games/mpv y2mate.com\ -\ AMD\ Fidelity\ Fx\
Super\ Resolution\ for\ all\ gamers\ thoughts\ \ impressions_4
80p.mp4
```

**Comment by jeeb** [comment]
ah, I thought args would run it too :)

You tell gdb you want to `run` or `r` .

**Comment by lavilao** [comment]
I though that but there was a --args option so.. xD

**Comment by lavilao** [comment]
finally, this is the output
```
gdb --args  ~/Games/mpv /run/media/luis/9A8674AC86748A91/lja\(NO\ TOCAR\)/series/new/Arduino\ y\ Raspberry\ Pi\ -\ Hardware\
Libre\ para\ Linux\ y\ Android.mp4
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/luis/Games/mpv...
(gdb) run
Starting program: /home/luis/Games/mpv /run/media/luis/9A8674AC86748A91/lja\(NO\ TOCAR\)/series/new/Arduino\ y\ Raspberry\ Pi\ -\ Hardware\ Libre\ para\ Linux\ y\ Android.mp4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe2e63640 (LWP 21241)]
[New Thread 0x7fffe2662640 (LWP 21242)]
[New Thread 0x7fffe1e61640 (LWP 21243)]
[New Thread 0x7fffe1660640 (LWP 21244)]
[New Thread 0x7fffe0e5f640 (LWP 21245)]
[New Thread 0x7fffd3fff640 (LWP 21246)]
[New Thread 0x7fffd37fe640 (LWP 21247)]
Can't load unknown script: /home/luis/.config/mpv/scripts/scripts.zip
[New Thread 0x7fffd2ffd640 (LWP 21248)]
Can't load unknown script: /home/luis/.config/mpv/scripts/auto-profiles.zip
Can't load unknown script: /home/luis/.config/mpv/scripts/skiptosilence.zip
[New Thread 0x7fffd27fc640 (LWP 21249)]
Resuming playback. This behavior can be disabled with --no-resume-playback.
[New Thread 0x7fffd1ffb640 (LWP 21250)]
[Thread 0x7fffd1ffb640 (LWP 21250) exited]
[New Thread 0x7fffd1ffb640 (LWP 21251)]
[New Thread 0x7fffd10b8640 (LWP 21252)]
 (+) Video --vid=1 (*) (h264 450x360 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[New Thread 0x7fffd08b7640 (LWP 21253)]
[Thread 0x7fffd08b7640 (LWP 21253) exited]
[New Thread 0x7fffd08b7640 (LWP 21254)]
[New Thread 0x7fffb2e6f640 (LWP 21256)]
[New Thread 0x7fffb266e640 (LWP 21258)]
[New Thread 0x7fffb1e6d640 (LWP 21259)]
[New Thread 0x7fffb166c640 (LWP 21260)]
[auto_profiles] Applying auto profile: 2
[Thread 0x7fffb166c640 (LWP 21260) exited]
[Thread 0x7fffb1e6d640 (LWP 21259) exited]
[Thread 0x7fffb266e640 (LWP 21258) exited]

Thread 15 "mpv/vo" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd08b7640 (LWP 21254)]
0x0000555555693284 in set_geometry (wl=wl@entry=0x7fffac001690) at ../video/out/wayland_common.c:1375
1375	../video/out/wayland_common.c: No existe el fichero o el directorio.
```

**Comment by jeeb** [comment]
And now `thread apply all bt full` should give you a crapload of stuff :) . Possibly in bits where you can move to the next one with space or so.

**Comment by lavilao** [comment]
what do I do with all of this stuff?
[gdb log.txt](https://github.com/mpv-player/mpv/files/7464101/gdb.log.txt)

**Comment by Dudemanguy** [comment]
>screenrc = {x0 = 0, y0 = 0, x1 = -796171792, y1 = 32767}

Huh? How can loading shaders affect this variable? Guess I need to look at this later.

**Comment by jeeb** [comment]
@lavilao thanks a lot for that.

Would also be nice to check what  `p *wl` (`p` and `print` let you print out variables' info) outputs since you should still be within the context. And then possibly `p wl->current_output`. Since that is the thing that might be nullptr in that case.

**Comment by Dudemanguy** [comment]
I see the problem. It's not specifically shader-related but I guess it just triggers it for you for some reason. x11 in theory has it too. I'll open up a PR in a bit.

**Comment by lavilao** [comment]
so bad luck me? what a surprise

**Comment by lavilao** [comment]
@jeeb here is the log of p wl-> current
```
p wl->current_output
$2 = (struct vo_wayland_output *) 0x0
```

the other log is down here
[p wl.txt](https://github.com/mpv-player/mpv/files/7464321/p.wl.txt)

**Comment by jeeb** [comment]
Thanks, so it's what I guesstimated. A VO message (one of `geometry|autofit|autofit_(smaller|larger)` which lead to the output size calculation) comes in before you have current output set :) .

**Comment by Dudemanguy** [comment]
@lavilao: If you comment out `autofit` in your config, does the crash stop?

**Comment by lavilao** [comment]
will test now

**Comment by lavilao** [comment]
IT WORKS!! removing autofit fixes the crash, thank you both I would have never fixed on my own.

**Comment by lavilao** [comment]
BTW any of you knows why svp and vaap-copy make appear a black bar on top of videos on wayland?

**Comment by Dudemanguy** [comment]
>IT WORKS!! removing autofit fixes the crash, thank you both I would have never fixed on my own.

Well it's still a bug I need to fix so it's worth leaving it open for now.

**Comment by lavilao** [comment]
![frame corrupted](https://user-images.githubusercontent.com/77688725/139966763-305dd030-fc31-4531-b220-2f10883036d1.png)
like this, I dont know how to describe this on english. Also happens with gpu-api=vulkan, more often on wayland than on x (on x only happens with vulkan+shaders/filters, on wayland happens with that and some times with gpu-api=opengl)

**Comment by Dudemanguy** [comment]
@lavilao: could you test https://github.com/mpv-player/mpv/pull/9382? With autofit and the shaders enabled, that should fix your crash. I couldn't reproduce it myself so I assume it has something to do with loading a lot of shaders at once delaying startup.

**Comment by lavilao** [comment]
how do I test it?

**Comment by Dudemanguy** [comment]
You would need to git clone my fork of the repo, checkout the branch, and then build it.

**Comment by lavilao** [comment]
Done, your fix works, now to recompile my mpv-full package

**Comment by lavilao** [comment]
umm, I just copy the things from pull request to the name of the files...

**Comment by lavilao** [comment]
green is add and red is remove no? just a quick edit to wayland_common.c and x11_common.c on video/out and compile, one thing though I dont have the way to test mpv on x11, I'm using sway but using my non patched mpv inmediately crashes while the patched worked so I would say its a success.

**Comment by Dudemanguy** [comment]
Thanks for testing. I just wanted to make sure that the logic behind the fix was correct before merging. The x11 fix is the same in principle so I'll just merge it now.

**Comment by Dudemanguy** [comment]
P.S. I personally have no idea about the vaapi thing. Feel free to open a new issue for it.
