### ISSUE TITLE
[gpu-next] --tone-mapping={gamma, reinhard} produces black screen

### ISSUE THREAD

**Issue by NSQY** [mpv-player/mpv#9386]
```mpv --version
mpv 0.34.0-9-g9d5d9b2424 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  3 23:42:57 ACDT 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.100
   libswresample   4.0.100
FFmpeg version: N-104460-gbf9950446d
```
Arch
git master via mpv-build
present on vo_placebo branch for as long as I've known about it
Gnome 40
Nvidia proprietary 495.44
Image: https://0x0.st/-n71.webp

### Reproduction steps
mpv -v --no-config --vo=gpu-next --tone-mapping=reinhard hdr_test.mkv --log-file=reinhard.log

### Expected behavior
Similar output to --vo=gpu

### Actual behavior
Black screen, subtitles visible but distorted

### Log file
[reinhard.log](https://github.com/mpv-player/mpv/files/7467866/reinhard.log)
[gamma.log](https://github.com/mpv-player/mpv/files/7467868/gamma.log)

**Comment by quietvoid** [comment]
The fix also corrects the extra clipping I was getting. Thanks.
