### ISSUE TITLE
[gpu-next] --sharpen does not work

### ISSUE THREAD

**Issue by NSQY** [mpv-player/mpv#9387]
```mpv --version
mpv 0.34.0-9-g9d5d9b2424 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  3 23:42:57 ACDT 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.100
   libswresample   4.0.100
FFmpeg version: N-104460-gbf9950446d
```
Arch
git master via mpv-build
present on vo_placebo branch for as long as I've known about it
Gnome 40
Nvidia proprietary 495.44

### Reproduction steps
mpv -v --no-config --vo=gpu-next --sharpen=10 foo.mkv --log-file=sharp.txt

### Expected behavior
For the image to look worse but sharper

### Actual behavior
Nothing changes

### Log file
[sharp.txt](https://github.com/mpv-player/mpv/files/7467918/sharp.txt)

**Comment by haasn** [comment]
This is WONTFIX. The `--sharpen` option for a long time has done nothing useful except pre-load a built-in shader. You can accomplish the exact same by loading this using the `--glsl-shader` option:

```glsl
//!DESC unsharp masking
//!HOOK MAIN
//!BIND HOOKED
#define PARAM 1.0

vec4 hook()
{
    const float st1 = 1.2;
    vec4 p = HOOKED_tex(HOOKED_pos);
    vec4 sum1 = HOOKED_texOff(st1 * vec2(+1, +1))
              + HOOKED_texOff(st1 * vec2(+1, -1))
              + HOOKED_texOff(st1 * vec2(-1, +1))
              + HOOKED_texOff(st1 * vec2(-1, -1));
    const float st2 = 1.5;
    vec4 sum2 = HOOKED_texOff(st2 * vec2(+1,  0))
              + HOOKED_texOff(st2 * vec2( 0, +1))
              + HOOKED_texOff(st2 * vec2(-1,  0))
              + HOOKED_texOff(st2 * vec2( 0, -1));
    vec4 t = p * 0.859375 + sum2 * -0.1171875 + sum1 * -0.09765625;
    return p + t * PARAM;
}
```

Admittedly, this one doesn't let you change the param at runtime, but I plan on extending GLSL shaders to allow runtime changeable parameters, so this will soon be a non-issue. As such, I think we can remove this option, which only really exists to make the video look worse.
