### ISSUE TITLE
[vo=gpu-next] tonemapped screenshots do not correspond to the displayed picture

### ISSUE THREAD

**Issue by quietvoid** [mpv-player/mpv#9388]
### Important Information
```
mpv 0.34.0-9-g9d5d9b2424 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  3 09:43:10 EDT 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4
```
- Arch Linux
- git master
- vo=gpu-next branch
- Sway 1.6.1, wlroots 0.14.1
- GPU: AMD Navi 5500 XT
- Kernel Driver: amdgpu 5.14.15
- OpenGL Driver: Mesa 21.2.4 (OpenGL 4.6)
- libplacebo: v4.157.0.102.g84c6bd4-1

### Reproduction steps

Play video with command line:
`mpv -v --no-config --vo=gpu-next --tone-mapping=mobius video.mkv --log-file=vo-gpu-next.log`
Save a screenshot by pressing `s`

### Expected behavior
The screenshot should be the same as what the window is displaying.

### Actual behavior
The screenshot from mpv is very different.
If it's of any use, changing params like `gamut-clipping` has no effect on the `gpu-next` screenshots.

Player window (fullscreen) screenshots:
vo=gpu: https://0x0.st/-n7v.png
vo=gpu-next: https://0x0.st/-n7w.png

mpv generated screenshots:
vo=gpu: https://0x0.st/-n7y.png
vo=gpu-next: https://0x0.st/-n7t.png

### Log file
[vo-gpu.log](https://github.com/mpv-player/mpv/files/7468092/vo-gpu.log)
[vo-gpu-next.log](https://github.com/mpv-player/mpv/files/7468094/vo-gpu-next.log)

### Sample files

I assume this can be reproduced with any HDR file.

**Comment by haasn** [comment]
Known limitation. VOCTRL_SCREENSHOT is not supported yet. I'll add that soon-ish.

**Comment by quietvoid** [comment]
Oh I missed it in the PR, sorry.
