### ISSUE TITLE
vo_gpu-next: Compatibility with shaders

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9390]
### Important Information

Provide following Information:
- mpv version
a73e5cd
- Windows Version
win11 release
- Source of the mpv binary
built based on shinchiro
- If known which version of mpv introduced the problem

- Possible screenshot or video of visual glitches
![ravu-zoom-r3](https://user-images.githubusercontent.com/41094733/140191871-72fe9e31-4db2-42e1-8e18-d794046a11c0.jpg)

### Reproduction steps

open the video and apply any shader.

### Expected behavior
No error or no crash.

### Actual behavior
ravu-zoom -- error in the console
adaptive-sharpen , SSim -- crash
nnedi3-nns64-win8x4 -- the chroma plane is terrible while luma plane was stretched.

Also, once ravu caused the error firstly (as u can c in the picture), and then any shaders could not be actived at runtime.

### Log file
[ravu-zoom-r3.log](https://github.com/mpv-player/mpv/files/7470623/ravu-zoom-r3.log)
[adaptive-sharpen.log](https://github.com/mpv-player/mpv/files/7470632/adaptive-sharpen.log)

### Sample files
ravu-zoom https://github.com/bjin/mpv-prescalers/blob/master/vulkan/compute/ravu-zoom-r3.hook
nnedi3 https://github.com/bjin/mpv-prescalers/blob/master/compute/nnedi3-nns64-win8x4.hook
adaptive and ssim https://gist.github.com/igv

**Comment by haasn** [comment]
> ravu-zoom -- error in the console

This one is a ravu bug. It uses the (undocumented) function LUT_POS which is not part of the mpv shader API. You can fix it by adding this to the shader:

```glsl
#define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
```

**Comment by haasn** [comment]
> adaptive-sharpen , SSim -- crash

Fixed the crash in haasn/libplacebo@08456a11b306ad

**Comment by haasn** [comment]
> nnedi3-nns64-win8x4 -- the chroma plane is terrible while luma plane was stretched.s

Can you open a new issue for this? (And in future, one issue per different type of bug)

**Comment by hooke007** [comment]
>Can you open a new issue for this? 

Here or libplacebo repo?
