### ISSUE TITLE
Is shader stage diferent when using vo_gpu-next?

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9391]
I noticed that the diff of stats with vo_gpu and vo_gpu-next.

Even prescaler works after the planes merging, is it a bug? Or does it have serious influence on the output?

vo_gpu
![gpu](https://user-images.githubusercontent.com/41094733/140196399-44ea2229-b6b4-4937-8a72-5ee5c9a89eb2.jpg)

vo_gpu-next
![gpu-next](https://user-images.githubusercontent.com/41094733/140196411-acb5544c-e12b-47a3-bde8-10f5143fd425.jpg)

### Log file
N/A

**Comment by haasn** [comment]
While those are different shaders, it still is surprising that `vo_gpu_next` merges the chroma plane but `vo_gpu` does not. Are you sure the input format to both is the same? (Log?)

**Comment by hooke007** [comment]
[gpu.log](https://github.com/mpv-player/mpv/files/7470924/gpu.log)
[gpu-next.log](https://github.com/mpv-player/mpv/files/7470925/gpu-next.log)

AiUpscale_Fast_2x_LineArt.gls [AiUpscale_Fast_2x_LineArt.zip](https://github.com/mpv-player/mpv/files/7470929/AiUpscale_Fast_2x_LineArt.zip)l

**Comment by hooke007** [comment]
Oh I forgot that I set hwdec=d3d11va-copy.
reset to `hwdec=no`
vo_gpu

![Snipaste_2021-11-04_06-08-39](https://user-images.githubusercontent.com/41094733/140200189-b349068e-ed91-4fd8-904e-ec2109032bee.jpg)

**Comment by haasn** [comment]
> Why no combing planes stage in vo_gpu-next? or it just didn't show in the stats?

It's redundant with "color conversion" since the two are basicallyg never done separately. (In libplacebo this is called "color decoding")
