### ISSUE TITLE
vo_gpu-next: subtitles affected by shaders may generate the obvious artifacts

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9398]
### Important Information

Provide following Information:
- mpv version
a73e5cd
- Windows Version
win11 release
- Source of the mpv binary
built based on shinchiro
- If known which version of mpv introduced the problem

- Possible screenshot or video of visual glitches

### Reproduction steps

open the video with external subtitles
apply the shader

### Expected behavior

no artifacts

![Snipaste_2021-11-06_02-20-30](https://user-images.githubusercontent.com/41094733/140560229-38a6d9db-2f59-4a04-9ce9-665c5ff28bf8.jpg)

### Actual behavior

artifacts (Pixel offset?) will appear when apply some shaders such as ravu , fsrcnnx

![Snipaste_2021-11-06_02-21-12](https://user-images.githubusercontent.com/41094733/140560195-0d78364b-b452-44ce-bba9-cf1fd81c22f4.jpg)

### Log file

[gpu-next.log](https://github.com/mpv-player/mpv/files/7488162/gpu-next.log)

### Sample files
N/A

**Comment by haasn** [comment]
Can you test if you get the same issue using `--vo=gpu --blend-subtitles=video`?

**Comment by hooke007** [comment]
Nope.
![Snipaste_2021-11-07_06-43-51](https://user-images.githubusercontent.com/41094733/140625870-3741d4cc-ac30-4064-934f-42a7c5848d08.jpg)
The subtitles became clearer.
