### ISSUE TITLE
vo_gpu-next: memory leak when minimize

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9401]
### Important Information

Provide following Information:
- mpv version
a73e5cd
- Windows Version
win11 release
- Source of the mpv binary
built based on shinchiro
- If known which version of mpv introduced the problem

- Possible screenshot or video of visual glitches

### Reproduction steps

open the video (keep playing) and then minimize the mpv window

### Expected behavior

no memory leak

### Actual behavior
![Snipaste_2021-11-06_19-39-07](https://user-images.githubusercontent.com/41094733/140608312-7500d179-1e46-4eb1-a18b-5dc68aaf9cb5.jpg)

Finally I have to exit mpv.
![Snipaste_2021-11-06_19-41-06](https://user-images.githubusercontent.com/41094733/140608319-937190ef-6f45-4895-b9e3-b8d842518df2.jpg)

### Log file

[gpu-next.log](https://github.com/mpv-player/mpv/files/7490356/gpu-next.log)

### Sample files
N/A

**Comment by yeezylife** [comment]
In my case,not just the memory.CPU,GPU,memory all went to 100%,then everything frozen,had to reboot my pc.
Happened twice with twice minimization.
