### ISSUE TITLE
gpu-next: gamut mapping looks different from vo_gpu/icc-profile in rec2020

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9403]
### Important Information

Provide following Information:
- mpv version 0.35
- Windows Version win11
- Source of the mpv binary https://github.com/zhongfly/mpv-build/releases/tag/2021-11-05

### Reproduction steps
`--vo=gpu`
![image](https://user-images.githubusercontent.com/50797982/140615976-90f11954-12e7-4b16-983e-5c90e35006f3.png)
`--vo=gpu --gamut-clipping=no`
![image](https://user-images.githubusercontent.com/50797982/140615989-d3b3f986-b410-4611-b281-6f8752b30068.png)
`--vo=gpu-next`
![image](https://user-images.githubusercontent.com/50797982/140616014-acc44a9c-ff3f-47a9-b819-71f60dee647a.png)
`--vo=gpu-next --gamut-clipping=no`
![image](https://user-images.githubusercontent.com/50797982/140616001-765e732c-259b-4d58-abb7-64531f47196a.png)
`--vo=gpu-next/gpu --icc-intent=0 --icc-profile=~~/icc/Rec.709.icc`
![image](https://user-images.githubusercontent.com/50797982/140616118-6671ba56-f01d-479b-a671-4b5805761c64.png)

### Expected behavior
output like `--icc-profile=~~/icc/Rec.709.icc`, if that is right.

### Actual behavior
no effect with `--vo=gpu-next --gamut-clipping=yes/no`

### Log file
`--vo=gpu-next --gamut-clipping=no`
[mpv.log](https://github.com/mpv-player/mpv/files/7490828/mpv.log)

### Sample files
https://nyaa.si/view/1430459 00:05:00
[Rec.709.zip](https://github.com/mpv-player/mpv/files/7490829/Rec.709.zip)

**Comment by yeezylife** [comment]
Yeah, `vo=gpu-next` displays diffrent color(with same conf and same frame) from `vo=gpu`..
Makes me curious which one is the correct color...

**Comment by yeezylife** [comment]
`vo=gpu-next` 
![sphinx0 6991556596428412-clamped-gpu-next](https://user-images.githubusercontent.com/30175425/142869911-e5776e72-8a7c-4a74-a572-6f068d288711.png)
`vo=gpu`
![sphinx0 6991556596428412-clamped](https://user-images.githubusercontent.com/30175425/142869982-3eb371f8-bab4-48f8-b219-50eab12b7cf6.png)

`vo=gpu-next` seems generally more greenish than `vo=gpu`. (And I'm using a greyscale image)

**Comment by Natural-Harmonia-Gropius** [comment]
white subtitles have some black points in mode desaturate, @haasn need fix.

auto
![image](https://user-images.githubusercontent.com/50797982/148501117-747efa78-f7d5-45d2-bbb5-05a5ca518117.png)
clip
![image](https://user-images.githubusercontent.com/50797982/148501136-37abbbf0-8f47-474b-92d8-af624fe9fad2.png)
desaturate
![image](https://user-images.githubusercontent.com/50797982/148501197-31da4768-3087-41a3-af04-ece56241869b.png)
lut bt.2407annex2
https://trev16.hatenablog.com/entry/2020/06/07/094646
![image](https://user-images.githubusercontent.com/50797982/148501314-b78ef375-623c-447b-a84d-377b3d3fe00d.png)

**Comment by Natural-Harmonia-Gropius** [comment]
darken results balck frame in 10000nit pq video (e.g. sony camp). other modes works fine.
![image](https://user-images.githubusercontent.com/50797982/148518435-53c57ddc-f44b-4c70-b066-39581748d788.png)
![image](https://user-images.githubusercontent.com/50797982/148518467-a2551ee1-e7c6-49cf-b220-fdd788e47ae9.png)

**Comment by Natural-Harmonia-Gropius** [comment]
I still think make `clip` as default is best. or keep in bound colors, desaturate out bound colors.

**Comment by haasn** [comment]
> darken results black frame in 10000nit pq video (e.g. sony camp). other modes works fine.

Sony camp is a broken file.

**Comment by Natural-Harmonia-Gropius** [comment]
> white subtitles have some black points in mode desaturate
desaturate ![image](https://user-images.githubusercontent.com/50797982/148501197-31da4768-3087-41a3-af04-ece56241869b.png)

https://github.com/haasn/libplacebo/commit/478623de63d46687205c86aa54eb0f4b26f58b1b
not fixed with it.

[ヱヴァンゲリヲン新劇場版：Q.zip](https://github.com/mpv-player/mpv/files/7834241/Q.zip)
ass file, video same as top post

**Comment by haasn** [comment]
Does this fix it?

```diff
diff --git a/src/shaders/colorspace.c b/src/shaders/colorspace.c
index 6f0d767d..df0a551d 100644
--- a/src/shaders/colorspace.c
+++ b/src/shaders/colorspace.c
@@ -1539,7 +1539,7 @@ static void adapt_colors(pl_shader sh,
 
     case PL_GAMUT_DESATURATE:
         GLSL("float cmin = min(min(color.r, color.g), color.b); \n"
-             "float luma = dot(%s, color.rgb);                  \n"
+             "float luma = clamp(dot(%s, color.rgb), 0.0, 1.0); \n"
              "if (cmin < 0.0 - 1e-6)                            \n"
              "    color.rgb = mix(color.rgb, vec3(luma),        \n"
              "                    -cmin / (luma - cmin));       \n"
```

**Comment by Natural-Harmonia-Gropius** [comment]
> Does this fix it?

fixed

**Comment by Natural-Harmonia-Gropius** [comment]
not fixed. and `gamut-mapping-mode=warn` in gpu-next colorized less area.

I can get very similar result by using this shader with a gamut clip lut
```glsl
//!HOOK MAIN
//!BIND HOOKED
//!DESC test

// https://gist.github.com/yohhoy/dafa5a47dade85d8b40625261af3776a
vec3 RGB_to_YCbCr(float R, float G, float B) {
    // BT.709
    const float a = 0.2126;
    const float b = 0.7152;
    const float c = 0.0722;  // a + b + c = 1
    const float d = 1.8556;  // 2 * (a + b)
    const float e = 1.5748;  // 2 * (1 - a)

    const float Y  = a * R + b * G + c * B;
    const float Cb = (B - Y) / d;
    const float Cr = (R - Y) / e;
    return vec3(Y, Cb, Cr);
}

vec3 YCbCr_to_RGB(float Y, float Cb, float Cr) {
    // BT.2020
    const float a = 0.2627;
    const float b = 0.6780;
    const float c = 0.0593;  // a + b + c = 1
    const float d = 1.8814;  // 2 * (a + b)
    const float e = 1.4747;  // 2 * (1 - a)

    const float R = Y + e * Cr;
    const float G = Y - (a * e / b) * Cr - (c * d / b) * Cb;
    const float B = Y + d * Cb;
    return vec3(R, G, B);
}

vec4 p = HOOKED_texOff(vec2(0.0, 0.0));
vec4 hook() {
    p.rgb = RGB_to_YCbCr(p.r, p.g, p.b);
    p.rgb = YCbCr_to_RGB(p.r, p.g, p.b);
    return p;
}
```

```ini
lut=~~/luts/Rec202012-bit_Rec2020-Rec202012-bit_Rec709.cube
lut-type=conversion
```

https://cameramanben.github.io/LUTCalc/LUTCalc/index.html
![image](https://user-images.githubusercontent.com/50797982/150629251-1341fa3f-a760-4232-8ffa-3d7832905064.png)

![image](https://user-images.githubusercontent.com/50797982/150629064-a66d8b28-1768-49f3-ba36-d542b4c44b8e.png)

**Comment by Natural-Harmonia-Gropius** [comment]
@haasn Does this need to be reopened?
samples: https://1drv.ms/u/s!AlXacxDwIFe73vMnUa-4HO4uISfpPg?e=5mqxIg

**Comment by haasn** [comment]
> @haasn Does this need to be reopened?

No. Stop putting 3 different bugs into a single issue. The above commit was a fix for the YCbCr decoding matrix being slightly off (resulting in green tint). The other issue you mentioned (NaN in desaturation mode) was also already fixed.
