### ISSUE TITLE
show DAR (display aspect ratio) for files like mkv that are specified. when pressing the i button.

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#9409]
in some files (I have only encountered mkvs for this) video can have a different DAR from PAR (pixel aspect ration) 
like this :
Pixel aspect ratio                       : 1.333
Display aspect ratio                     : 1.783
for a video file that has
Width                                    : 960 pixels
Height                                   : 718 pixels
but shows as 1280 by 718 so in my 16:9 laptop it covers the whole screen as it scales to 1980x1080 completely.
because if I open it in mkvtoolnix it shows 1280x716 for DAR. this is a metadata added to the video to show it compressed from 4x3 to 16x9.

can this ,1280x716 for DAR, be shown in info when pressing the i button?
right now only the PAR is shown and the scaled resolution.
which shows:
native 960x716
scaled 1920x1077

maybe something like this 
native 960x716
**par 1280x716**
scaled 1920x1077

**Comment by hooke007** [comment]
If no description, dup https://github.com/mpv-player/mpv/issues/9100

**Comment by kasper93** [comment]
Fixed by https://github.com/mpv-player/mpv/pull/14330
