### ISSUE TITLE
Screen getting messed up when using hwdec=vaapi vo=vaapi with Intel HD3000

### ISSUE THREAD

**Issue by spidey** [mpv-player/mpv#941]
When I tried playing some file with hwdec=vaapi and vo=vaapi on my configuration file, the video kind of plays in full screen even though it's not configured to, but very glitchy, messing around with everything in my screen. After a couple seconds, the display goes down and I can only hear the sound of the file playing. If I quit mpv with Enter or Esc or q and change displays to e.g. tty1 and then back to tty7 with X, it comes back normally again.

I'm using Gentoo Linux ~amd64, mpv-0.3.11.

I don't know what kind of logs I could attach here. Should I make a video? I've found out that I can still have vaapi hardware accelerated decoding even when using vo=opengl, and that fixed the problem for me.

Build configuration:
emerge -uav mpv

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U  ] media-video/mpv-0.3.11 [0.3.10] USE="X alsa bluray cdio dvb dvd enca encode iconv jpeg lcms libass lua mpg123 openal opengl postproc pulseaudio quvi shm v4l vaapi vdpau xscreensaver xv -bs2b -doc-pdf -dvdnav -jack -joystick -ladspa -libcaca -libguess -lirc -luajit -oss -portaudio -pvr -radio -samba -sdl (-selinux) -vcd -vf-dlopen -wayland -xinerama" 2,463 kB

Total: 1 package (1 upgrade), Size of downloads: 2,463 kB

I was hoping to find this as a known bug, but I didn't find anything. Hope I can help debugging this. I could build it by hand with -g -ggdb -O0 and try generating a useful callstack, but mpv doesn't crash, it just messes around with my screen even disabling it. It is probably related to Xorg, Intel DRI, DRM and KMS, the whole stack.

Just found out that if I quit the player soon enough, the screen gets messed but not disabled, and a simple repaint (what I did was minimize all windows and restore afterwards, just like Windows' Win+D pressed twice) corrects the screen glitches.

**Comment by mgcrea** [comment]
I'm encountering this issue as well, I get vsync-like tearing issues with mpv using either `vo=vaapi` `vo=vaapi-copy`, on intel nuc based systems, with latest oibaf drivers. It's working flawlessly with vlc.

**Comment by wm4** [comment]
Try ``--vo=xv``. This uses what VLC uses.

**Comment by wm4** [comment]
PS: this means only ``--hwdec=vaapi-copy`` will work, ``--hwdec=vaapi`` will not.

**Comment by mgcrea** [comment]
@wm4 same issue.

**Comment by wm4** [comment]
Does ``--vo=xv:adaptor=1`` help?

**Comment by mgcrea** [comment]
@wm4 It seems to do the trick! Thanks!

**Comment by wm4** [comment]
I guess this means that VLC magically selects the "right" adapter?

But in general, Intel really should get to fixing this. Xv is such an old and bad API and causes tons of other problems.

**Comment by mgcrea** [comment]
Does it mean that this should be the default config for all media ever played on this device?

**Comment by Gusar321** [comment]
@mcgrea: Install and run xvinfo to see what's adaptor 1 and what other adaptors there are. Then check the documentation for the intel X driver, I recall there are some options to switch around adaptors in there.

But rather than using Xv with vaapi-copy, I'd suggest sticking with vaapi for both hwdec and vo. To get rid of tearing, use the TearFree option. Works wonders on Haswell, where I had tearing in windowed mode but not in fullscreen.

Tearing in windowed mode is not really avoidable due to how modern Intel hardware works and how X works, that's why TearFree was implemented.

**Comment by mgcrea** [comment]
@Gusar321, I'm already using `--fullscreen` 

Here is the `xvinfo output`. The Intel NUC model is the DN2820 (celeron based).
Have tested the flag on a recent Nuc i7 (Iris6100) and the video has artefacts.
On a year-old Nuc i5 (HD5000), the video does not start (adaptator not found).

```
$ xvinfo
X-Video Extension version 2.2
screen #0
  Adaptor #0: "Intel(R) Textured Video"
    number of ports: 16
    port base: 71
    operations supported: PutImage 
    supported visuals:
      depth 24, visualID 0x20
    number of attributes: 1
      "XV_SYNC_TO_VBLANK" (range -1 to 1)
              client settable attribute
              client gettable attribute (current value is 1)
    maximum XvImage size: 16384 x 16384
    Number of image formats: 5
      id: 0x32595559 (YUY2)
        guid: 59555932-0000-0010-8000-00aa00389b71
        bits per pixel: 16
        number of planes: 1
        type: YUV (packed)
      id: 0x32315659 (YV12)
        guid: 59563132-0000-0010-8000-00aa00389b71
        bits per pixel: 12
        number of planes: 3
        type: YUV (planar)
      id: 0x30323449 (I420)
        guid: 49343230-0000-0010-8000-00aa00389b71
        bits per pixel: 12
        number of planes: 3
        type: YUV (planar)
      id: 0x59565955 (UYVY)
        guid: 55595659-0000-0010-8000-00aa00389b71
        bits per pixel: 16
        number of planes: 1
        type: YUV (packed)
      id: 0x434d5658 (XVMC)
        guid: 58564d43-0000-0010-8000-00aa00389b71
        bits per pixel: 12
        number of planes: 3
        type: YUV (planar)
  Adaptor #1: "Intel(R) Video Sprite"
    number of ports: 1
    port base: 87
    operations supported: PutImage 
    supported visuals:
      depth 24, visualID 0x20
    number of attributes: 2
      "XV_COLORKEY" (range 0 to 16777215)
              client settable attribute
              client gettable attribute (current value is 66046)
      "XV_ALWAYS_ON_TOP" (range 0 to 1)
              client settable attribute
              client gettable attribute (current value is 0)
    maximum XvImage size: 8192 x 8192
    Number of image formats: 4
      id: 0x32595559 (YUY2)
        guid: 59555932-0000-0010-8000-00aa00389b71
        bits per pixel: 16
        number of planes: 1
        type: YUV (packed)
      id: 0x59565955 (UYVY)
        guid: 55595659-0000-0010-8000-00aa00389b71
        bits per pixel: 16
        number of planes: 1
        type: YUV (packed)
      id: 0x18424752
        guid: 50415353-5448-524f-5547-485247423234
        bits per pixel: 32
        number of planes: 1
        type: RGB (packed)
        depth: 24
        red, green, blue masks: 0xff0000, 0xff00, 0xff
      id: 0x10424752
        guid: 50415353-5448-524f-5547-485247423136
        bits per pixel: 16
        number of planes: 1
        type: RGB (packed)
        depth: 16
        red, green, blue masks: 0xf800, 0x7e0, 0x1f
```

**Comment by Gusar321** [comment]
Adaptor 1 is "Video Sprite". I get artifacts on Haswell with that one too. No artifacts on a Celeron N2806 netbook, but on both machines the video doesn't get scaled. Do you get scaling with the Sprite adaptor? Your i5 only has a "Textured Video" adapter, so of course adaptor=1 won't work there.

Xv is more or less a dead end, it had its use a long time ago when a Video Overlay adaptor was the only way to display video, nowadays there are better methods. Did you try --vo=vaapi with TearFree? Note, TearFree is an option for the X driver - create an /etc/X11/xorg.conf.d/20-intel.conf file to set it.

**Comment by wm4** [comment]
Didn't find anything in VLC's code that would specifically prefer adaptors over others.

>But rather than using Xv with vaapi-copy, I'd suggest sticking with vaapi for both hwdec and vo. To get rid of tearing, use the TearFree option. Works wonders on Haswell, where I had tearing in windowed mode but not in fullscreen.

What about OpenGL?

**Comment by Gusar321** [comment]
> What about OpenGL?
As the turbostat output posted in issue #1765 shows, it has higher resource consumption than vaapi. Those results are for the video in native resolution, the difference is even bigger when scaling to fullscreen. Especially opengl-hq stresses Intel GPUs quite a bit. vaapi:scaling=hq produces a very similar picture, but with noticeably less resources.

Other than that, OpenGL works fine. Though it too might need TearFree to get rid of tearing in windowed mode.

**Comment by kevmitch** [comment]
You might want to check if you are running the SNA acceleration mode of the intel Xorg driver. This causes massive corruption, tearing and all sorts of garbage. Unfortunately this is now the default.

To switch back to the more stable UXA acceleration, I have added to my xorg.conf

```
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod"  "uxa"
EndSection
```

The TearFree option applies only to SNA and is supposed to fix these problems, but I have found that it just makes the corruption of a different quality. If you want to give it a try while keeping sna

```
Section "Device"
   Identifier  "Intel Graphics"
   Driver       "intel"
   Option      "AccelMethod"  "sna"
   Option      "TearFree" "true"
EndSection
```

I've been meaning to send some feedback on this mess to intel for a while now, but it's so bad, I'd be astonished if it isn't a known issue. I just don't understand why this hasn't stayed in git master until the kinks have been ironed out.

**Comment by kevmitch** [comment]
Just to clarify, my above comment regards using --vo=opengl (which is what everyone should really be using).

**Comment by Gusar321** [comment]
@kevmitch: You seem to be the only one with such issues. I haven't seen from anyone such talk about corruption and garbage. Arch has been shipping with SNA as the default for a long time now, and there aren't any bug reports about corruption. I have used SNA for many months on four different generations of Intel GPUs, no corruption anywhere. Just tearing on Baytrail and Haswell, which the TearFree option fixes.

So please do provide feedback to Intel, they don't know about such issues, as no one else is seeing them. On the contrary, Intel's driver is considered a very high quality one.

**Comment by wm4** [comment]
> Just tearing on Baytrail and Haswell, which the TearFree option fixes.

Why is this option not on by default everywhere?

>So please do provide feedback to Intel, they don't know about such issues, as no one else is seeing them. On the contrary, Intel's driver is considered a very high quality one.

Let's just say I can't really share this sentiment.

**Comment by tobiasjakobi** [comment]
Also running here with SNA on a gen7.5 chip (i7-4700HQ) since months without any kind of visual corruptions. In particular I also don't see any tearing issues with vaapi here. If SNA doesn't work for you, but UXA does, then I really suggest to open a bug on FDO. Intel's Chris Wilson is always actively fixing bugs and responding to reports. But as Gusar321 already pointed out: If nobody ever bothers to report a bug, it obviously won't get fixed anytime soon.

**Comment by tobiasjakobi** [comment]
@wm4: Concerning potential negative impacts of TearFree, just see the manpage of the driver. It's accurately described there.

**Comment by Gusar321** [comment]
> Why is this option not on by default everywhere?

It's not needed when a page-flipping compositor is running, though the manpage says TearFree is aware when such a compositor is running.
It's only needed on Sandy Bridge and up, though there could easily be per-gpu defaults.
It used to be an experimental feature, though I think it's fully fleshed out now.

So maybe Chris Wilson simply forgot it might be a good idea to turn it on. Considering he hasn't made a new driver release in six months, managerial stuff doesn't appear to be his strong point.

**Comment by spidey** [comment]
Thank you all for the discussion that this issue has created and all the feedback you've given.

To summarize what has been talked about, I've since the first post been using SNA and TearFree in my xorg.conf file, and --vo=opengl --hwdec=vaapi in .mpv/config. This has worked very well for me. I have an 2nd Gen i3 (Sandy Bridge), with an HD3000 integrated video adapter.

**Comment by laichiaheng** [comment]
vo=opengl with hwdec=vaapi is laggy when playing an AVC 4096X2160 59.94fps video, but vo=vaapi with hwdec=vaapi doesn't happen.
