### ISSUE TITLE
vo_gpu-next: (unknown shader) when using inactive SSimSuperRes or SSimDownscaler 

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#9411]
### Important Information

Provide following Information:
- mpv version 
```
mpv 0.34.0-16-gec16769c2d Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  7 08:41:58 +08 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.101
   libswresample   4.0.100
FFmpeg version: git-2021-11-06-1728127e
```
- Windows Version - Windows 10 21H1 Build 19043.1288
- Source of the mpv binary - Shinchiro Build mpv-x86_64-20211107-git-ec16769

### Reproduction steps

`mpv --no-config --glsl-shader=~~/portable_config/Shaders/SSimSuperRes.glsl --vo=gpu-next  <video_file>`

### Expected behavior

Shader name in Frame Timings, and ideally not present when it shouldn't be in the rendering process

(Watching 1080p content on 1080p window size or less should not activate SSimSuperRes) 

### Actual behavior

![image](https://user-images.githubusercontent.com/22327220/140637485-91bbe344-7e8e-4c05-8d2a-8814a7b9806c.png)

`(Unknown Shader)` in frame timings for 1080p or less window size, when it shouldn't be active for a 1080p video.

### Log file

[mpvlog.txt](https://github.com/mpv-player/mpv/files/7491939/mpvlog.txt)

### Sample files

[SSimSuperRes.glsl.txt](https://github.com/mpv-player/mpv/files/7491940/SSimSuperRes.glsl.txt)

**Comment by haasn** [comment]
[Known bug](https://code.videolan.org/videolan/libplacebo/-/issues/166), closing in favor of that issue.
