### ISSUE TITLE
How to toggle the printing of "demuxer-cache-duration" ?

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#9418]
How to toggle the printing of "demuxer-cache-duration" ?

I tried this in my `input.conf` : 
`C cycle demuxer-cache-duration`

but when pressing `C` mpv prints `Failed to set property 'demuxer-cache-duration'` on the OSD.

I'd like to succeed to toggle the printing of "demuxer-cache-duration".
### Log file

[mpv-toggle-demuxer-cache-duration.txt](https://github.com/mpv-player/mpv/files/7493059/mpv-toggle-demuxer-cache-duration.txt)

**Comment by guidocella** [comment]
Cycle is for setting values. Use `show-text ${demuxer-cache-duration}`'.

**Comment by sebma** [comment]
I want the `demuxer-cache-duration` to be shown in the OSD until I press `C` again. Does the `show-text` do that ?

**Comment by guidocella** [comment]
`C no-osd cycle-values osd-msg1 $${demuxer-cache-duration} ""`

**Comment by sebma** [comment]
> `C no-osd cycle-values osd-msg1 $${demuxer-cache-duration} ""`

Just tried it. Unfortunately, it does not work.

**Comment by sebma** [comment]
@guidocella My bad. It does work, I had to switch to OSD level 3 to be able to see it.

It seems the `no-osd` is not mandatory.

Thank for your help.
