### ISSUE TITLE
Multiple marked seek and a keybind to cycle through all the marked seek

### ISSUE THREAD

**Issue by Ceynou** [mpv-player/mpv#9422]
### Expected behavior of the wanted feature
Use a keybind to mark current position, usable multiple times.
Ex: 134s, 788s, 1498s
Use another keybind to cycle(change position?) through all the saved/marked positions. 

If I understand correctly the keybind Shift+Ctrl+BACKSPACE indeed marks the seek but you can only mark one seek(?).

#### Comment
I barely know any coding nor understand correctly the terms and stuff, and I don't have the patience to learn sadly.
So I tried these scripts [mpv-bookmark-lua-script](https://github.com/nimatrueway/mpv-bookmark-lua-script) and [mpv-bookmarker](https://github.com/NurioHin/mpv-bookmarker), which in my opinion aren't smart or I don't know what was the goal of the authors.
-Main issue is that the first one use keybinds as slots for the bookmarks
-The second one(probably fixed in a pull request, didn't test) is that it displays every bookmark, even the ones that are not from the video you're watching.

If I could make a complete script(forked from this [mpv-bookmark-lua-script](https://github.com/nimatrueway/mpv-bookmark-lua-script)) there would the possibility to 

- bookmarks current time - X second with a keybind, X set in a config file where there would be other options
  - maybe instead of current time it could be previous subtitles line.
  - maybe save it to the watch_later file(somehow)
- either cycle through all the bookmarks with one keybind or previous and next bookmark keybinds 

I didn't throughly check how mpv parse the watch_later file, if we could add content after the first line like a table(?), that would be nice, and I couldn't understand at all that bit of code, it's converting the name to some kind of hash right?
```
{
    if (mpctx->opts->write_filename_in_watch_later_config) {
        char write_name[1024] = {0};
        for (int n = 0; filename[n] && n < sizeof(write_name) - 1; n++)
            write_name[n] = (unsigned char)filename[n] < 32 ? '_' : filename[n];
        fprintf(file, "# %s\n", write_name);
    }
}
```

**Comment by Dudemanguy** [comment]
This is really a job for a lua script. Basically you would need a function that saves the `timepos` everytime you hit a key and another function that seeks/cycles to each marked time that you saved with the previous function.
