### ISSUE TITLE
vo=gpu-next: add option *scale-antialiasing

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#9423]
### Expected behavior of the wanted feature
>High-quality, optimized upscaling and downscaling including support for polar filters ("Jinc"), anti-aliasing, anti-ringing and gamma correct scaling

I noticed that the [libplacebo](https://github.com/haasn/libplacebo) description supports antialiasing and antiringing. mpv does not seem to have the antialiasing option.
Is it possible to add *scale antialiasing options for `vo_gpu-next` in the future?
Or `vo_gpu-next` has  realized this function based on libplacebo？
### Alternative behavior of the wanted feature
//
### Log file
//

**Comment by haasn** [comment]
It's called `--correct-downscaling`.

**Comment by dyphire** [comment]
I see,thanks

**Comment by Obegg** [comment]
> It's called `--correct-downscaling`.

What about antialiasing when upscaling? I'm using ```vo=gpu-next``` and want antialiasing when upscaling.

**Comment by haasn** [comment]
What do you mean by "antialiasing when upscaling"?

**Comment by Obegg** [comment]
> What do you mean by "antialiasing when upscaling"?

When you watch 1080p video on 4k display, the lines are not straight, especially text

**Comment by haasn** [comment]
Try `--scale=ewa_lanczos`?

**Comment by Obegg** [comment]
> Try `--scale=ewa_lanczos`?

I was already using it and still need antialiasing to fix the edges of lines such as text,
besides - there is no option to select the multiplier of antialiasing (x2, x4, x8)
example from google:
![image](https://user-images.githubusercontent.com/13978119/150018980-878067e7-0f8a-4240-abad-c2da0d73d9df.png)

**Comment by Hrxn** [comment]
The multiplier? How would multi-sampling anti-aliasing even work on a video?!

You should probably try a *fancy* modern scaler like FSRCNNX or RAVU, I think. Maybe there is even a newer, even fancier one, not sure I'm not closely following that space...

**Comment by haasn** [comment]
>  besides - there is no option to select the multiplier of antialiasing (x2, x4, x8)

All of those anti-aliasing techniques rely on having access to information we don't get. Video files use a fixed (rectangular) sampling pattern. I second the recommendation to look into FSRCNNX.
