### ISSUE TITLE
zimg: chroma shifted / unstable autocovert

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9424]
### Important Information

Provide following Information:
- mpv version 0.35
- Windows Version win11
- Source of the mpv binary https://github.com/zhongfly/mpv-build/releases/tag/2021-11-06

### Reproduction steps
In my case, problem is caused by [autocrop.lua](https://github.com/mpv-player/mpv/raw/master/TOOLS/lua/autocrop.lua), Can reproduce it with press _shift+c_.
I tired remove video-sync=display-resample from mpv.conf, autoconvert work fine when filter removed.

- `vf-add=cropdetect`
- autoconvert to yuv420p16, merging planes appear with chroma shift
- `vf-remove=cropdetect` after 1 seconds
- autoconvert to worng result

### Expected behavior
![image](https://user-images.githubusercontent.com/50797982/140695379-3af49107-2581-4954-8a67-08041e85b0dc.png)
![image](https://user-images.githubusercontent.com/50797982/141642535-634f6134-f39d-4475-afb9-e2a8d00a02fa.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/50797982/140695732-516473ba-8328-4325-a086-88a5a3853509.png)
![image](https://user-images.githubusercontent.com/50797982/141642543-2cdca86a-2913-4da4-81f5-730e97065fb8.png)

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/7494764/mpv.log)

### Sample files
//

**Comment by Natural-Harmonia-Gropius** [comment]
and vapoursynth fillter would exacerbate this problem

**Comment by haasn** [comment]
I suspect this is related to the same thing as #9425. It's very hard to tell from your logs what's happening when - can you reproduce it in a more consistent way without things randomly changing constantly in the middle of playback?

**Comment by Natural-Harmonia-Gropius** [comment]
both issues of the vf, [#9425](https://github.com/mpv-player/mpv/issues/9425) closed.
in my case, problem is caused by [autocrop.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua), can reproduce it with press _shift+c_.
I tired remove `video-sync=display-resample` from mpv.conf, chroma shift will only happens when `vf=cropdetect` appended and autoconvert work fine when remove it.

more detailed steps
1. `vf-add=cropdetect`
2. merging planes appear with chroma shift
3. 1 seconds wait (behavior of autocrop.lua)
4. if `video-sync=display-resample`
    high probability merging planes still here
    else
    merging planes gone
4. `vf-remove=cropdetect`
5. if `video-sync=display-resample`
    very high probability autoconvert rgb48, ayuv64 or something like this.
    else
    autoconvert yuv420p

**Comment by Natural-Harmonia-Gropius** [comment]
#8636

**Comment by Natural-Harmonia-Gropius** [comment]
https://github.com/mpv-player/mpv/issues/8636

**Comment by haasn** [comment]
There's still probably some bug here if it results in broken output. Can you reproduce these issues with `vo_gpu`?

**Comment by Natural-Harmonia-Gropius** [comment]
no chroma shift when merging planes appear in ​`vo_gpu`
vapoursynth fillter always cause chroma shift both ​`vo_gpu` and `vo_gpu-next`

**Comment by haasn** [comment]
So `vo_gpu` and `vo_gpu_next` now behave identically?

**Comment by Natural-Harmonia-Gropius** [comment]
`vo_gpu` works fine with non-vapoursynth fillter, `vo_gpu_next` not

**Comment by Natural-Harmonia-Gropius** [comment]
More precisely, filters that change the pixelformat can cause this problem

**Comment by dyphire** [comment]
> in my case, problem is caused by autocrop.lua, can reproduce it with press shift+c.

About autocrop.lua, you can try this script: [dynamic-crop.lua](https://github.com/Ashyni/mpv-scripts/blob/master/dynamic-crop.lua)

It works better. Of course, it also has some issues

**Comment by haasn** [comment]
> More precisely, filters that change the pixelformat can cause this problem

So, what's a simple way of reproducing this?

**Comment by Natural-Harmonia-Gropius** [comment]
> So, what's a simple way of reproducing this?

`mpv --video-sync=display-resample`
play `HDR video`, I can reproduce this on [[VCB-Studio] Tenki no Ko [Ma10p_2160p_HDR][x265_flac].mkv](https://share.dmhy.org/topics/view/547514_VCB-Studio_Tenki_no_Ko_10-bit_1080p_2160p_HEVC_BDRip_MOVIE_Fin.html)
use [autocrop.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua)
press `shift+c` multiple times
see `Frame Timing` page, merging planes appear with chroma shift
see `terminal`, autocovert to rgb48 or ayuv64 appear with worng color.

**Comment by Natural-Harmonia-Gropius** [comment]
https://github.com/mpv-player/mpv/issues/9435#issuecomment-965688584
look at the glass, these screenshot has chroma shifted.

**Comment by Natural-Harmonia-Gropius** [comment]
Output always chroma shifted now. use [this release of mpv](https://github.com/zhongfly/mpv-winbuild/releases/tag/2021-12-02) .
![image](https://user-images.githubusercontent.com/50797982/144594197-af291d12-dbd3-41d0-815a-c6f7347f9346.png)

**Comment by haasn** [comment]
I also found that you can work-around it by using `--sws-allow-zimg=no`

**Comment by haasn** [comment]
Confirming that we set the correct metadata for the zimg call. To me all signs indicate that this is a zimg bug.

**Comment by Natural-Harmonia-Gropius** [comment]
> what's happening is that the yuv420p10 -> yuv420p auto-conversion offsets the chroma for some strange reason. (It doesn't even need to do any scaling, so I'm not sure what's going on there...)

I got it, thanks for delving into this issue.

**Comment by ValZapod** [comment]
For a very long time zimg wrapper in ffmpeg was broken in chroma sample location. https://github.com/FFmpeg/FFmpeg/commit/27c0dd55609daf440a7744e96ac20c119bbeb80f

 Also, it turns out that ffmpeg cannot see sample location of input, for full range and limited hevc it assumes left, always! Wow.

You should force it with 
ffmpeg.exe -i cosmos.mkv -vf 'scale=in_h_chr_pos=0:in_v_chr_pos=128' -pix_fmt rgb24 qnfvarejwnfe3.rgb for left
ffmpeg.exe -i cosmos.mkv -vf 'scale=in_h_chr_pos=0:in_v_chr_pos=0' -pix_fmt rgb24 qnfvarejwnfe3.rgb for top-left

WTF.

**Comment by haasn** [comment]
I pushed something that should hopefully fix the "unstable" part of your original issue (and this affecting gpu-next). Might be a good idea to open a new issue for the zimg bug specifically.
