### ISSUE TITLE
[vo=gpu-next] playback convert to rgb48 randomly by autoconvert

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9425]
### Important Information

Provide following Information:
- mpv version 0.35
- Windows Version win11
- Source of the mpv binary https://github.com/zhongfly/mpv-build/releases/tag/2021-11-06

### Reproduction steps
it's not always happen.
when sense become white i can see `[autoconvert] Converting p010 -> rgb48` in terminal.

### Expected behavior
`[autoconvert] Converting p010 -> yuv420p`
![image](https://user-images.githubusercontent.com/50797982/140697012-f23352ae-6885-4506-bbd6-051491ac2e11.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/50797982/140696943-0b25777a-ae53-46d2-a0b4-a44ccf52e842.png)

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/7494792/mpv.log)

### Sample files
//

**Comment by ValZapod** [comment]
> p010

Does it even make sence to use rgb48 for p010? p016 I would understand...

**Comment by Natural-Harmonia-Gropius** [comment]
yes，and sometimes ayuv48
