### ISSUE TITLE
videos with some specific frame rates flicker with tscale=box --vo=gpu-next

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#9427]
E.g. this sample from the Kodi wiki exhibits black flicker:
https://drive.google.com/file/d/0BwxFVkl63-lEUGZnR1JHUUU0WEk/view?resourcekey=0-YrNv_pEiY4Ukaw_X5rckRw

It seems to be specific to --tscale=box, e.g. linear doesn't trigger it. Other mpv settings don't seem to matter.

Used mpv-x86_64-20211107-git-ec16769 build by shinchiro.

Log:
[output.txt](https://github.com/mpv-player/mpv/files/7498657/output.txt)

**Comment by haasn** [comment]
I think the correct solution here is disabling the use of `tscale=box` for interpolation (or hard-coding it as being equal to `--interpolation=no`).

`box` is sort of special because it's the only filter window that only spans a single sample, which breaks some of the assumptions in the code. I don't see why you would use it as an interpolation kernel anyways - it's just nearest neighbour which is the same as what you get with interpolation disabled.

Thoughts?

**Comment by aufkrawall** [comment]
Indeed with gpu-next, box looks like no interpolation at all.
However, with --vo=gpu, it looks smooth. I've been using it as follows with gpu:

tscale=box
tscale-window=sphinx
tscale-radius=1.0
tscale-clamp=0.0

I admit that I didn't check how each parameter turn out or if they make that much sense at all. It was posted in the lengthy dicussion which parameters for interpolation would be "best". I found this to look smoother then linear, while being less blurry than any cubic kernel. I'd really like to preserve that result with gpu-next.

**Comment by hooke007** [comment]
For gpu-next:

tscale=sphinx
tscale-clamp=0.0

**Comment by aufkrawall** [comment]
It's really blurry vs. "old tweaked box". I also tried with otherwise the same parameters, but old box result always (I tried multiple times to rule out screen capture in an unfavorable moment for either setting) has far less ghosting and motion blur:
![new](https://user-images.githubusercontent.com/13510490/140796391-05bdc339-1c6a-417c-98d0-88b6ac5a78b3.png)

![old](https://user-images.githubusercontent.com/13510490/140796399-135e391f-32a5-46e1-91b1-6be0747391fa.png)

**Comment by haasn** [comment]
Try something like `--tscale=sphinx --tscale-radius=1.0 --tscale-blur=0.6991556596428412`. (Or maybe the `tscale-radius` option is unnecessary, I'm not quite sure off the top of my head)

At any rate, it should be possible to recreate the exact same filter kernel without the `tscale=box` hack, which was always just an ugly work-around for an mpv shortcoming in my mind.

Alternatively I could reintroduce something that replaces the old `tscale=box`, like perhaps `tscale=flat` that's constant 1 everywhere.

**Comment by haasn** [comment]
> Edit: Btw: Is it technically possible to have a tscale filter for interpolation that also works in gpu-dumb-mode? E.g. something lightweight like linear?

Technically possible. But note that every device that supports vulkan also supports non-dumb mode, so I don't see the reason to enable it.

**Comment by aufkrawall** [comment]
> Technically possible. But note that every device that supports vulkan also supports non-dumb mode, so I don't see the reason to enable it.

I'm not sure if it is actually caused by not being in gpu-dumb-mode anymore or due to the additional load, but when I try to use interpolation with tscale=linear, performance on my weak Gemini Lake Intel GPU totally breaks down (already did so with old --vo=gpu). It is also massively overwhelmed by e.g. bicubic_fast image scaling.

Well, at least video-sync=display-resample already does the trick with some refresh rate switching. Massively underrated feature outside of mpv user base. :)

Btw: I'm stupid: tscale-radius <0.5 is out of range. With the default tscale-radius value of tscale=sphinx, tscale-blur=0.65 looks good to my eyes.

**Comment by haasn** [comment]
(Note that `bicubic_fast` is a lot faster with `--vo=gpu-next` than with `--vo=gpu`, since it only does two passes (one for scaling both chroma planes and RGB conversion, one for main RGB scaling) versus vo_gpu's four (chroma merging, chroma scaling, RGB conversion).)

**Comment by aufkrawall** [comment]
Thanks for sharing that technical background information. With --gpu-api=vulkan in --vo=gpu, this SoC draws a bit more power than with OGL. This GPU is just extra terrible (current Firefox Webrender makes it explode...), I'll report back how it fares with gpu-next. =)

**Comment by hooke007** [comment]
> since it only does two passes (one for scaling both chroma planes and RGB conversion, one for main RGB scaling) versus vo_gpu's four (chroma merging, chroma scaling, RGB conversion, main scaling).

(Maybe it's offtopic, but I suddenly thought of it) gpu-next seems to avoid the issue https://github.com/mpv-player/mpv/issues/5727 in vo_gpu, which would make a little performance waste.

**Comment by haasn** [comment]
> > since it only does two passes (one for scaling both chroma planes and RGB conversion, one for main RGB scaling) versus vo_gpu's four (chroma merging, chroma scaling, RGB conversion, main scaling).
> 
> (Maybe it's offtopic, but I suddenly thought of it) gpu-next seems to avoid the issue #5727 in vo_gpu, which would make a little performance waste.

It does avoid that, yes.

**Comment by haasn** [comment]
Is this still an issue?

**Comment by aufkrawall** [comment]
Can't reproduce this one, so it's probably fixed.
