### ISSUE TITLE
Background is always transparent with vo=gpu-next in Sway and Mutter

### ISSUE THREAD

**Issue by Dudemanguy** [mpv-player/mpv#9432]
### Important Information

- mpv version: c413720
- libplacebo version: haasn/libplacebo@0aaced1
- Window Manager and version: Sway 1.6.1
- GPU driver and version: RX 550 using amdgpu with mesa's radv (21.2.5)

### Reproduction steps

This happens in Sway but not Weston (too lazy to try any other compositor). Just open up any file using gpu-next (`mpv --no-config --vo=gpu-next`).

### Expected behavior

The window has a black background as per the default. Below is with vo=gpu and --gpu-api=vulkan.

![2021-11-10-083618_grim](https://user-images.githubusercontent.com/5105515/141133213-5dd06528-e6f8-4457-977b-78f14cd43495.png)

### Actual behavior

It's actually transparent. Below is with vo=gpu-next.

![2021-11-10-083550_grim](https://user-images.githubusercontent.com/5105515/141133140-3f3a6edd-09f9-4928-9d88-2af4f76f7f9f.png)

### Log file

[vo=gpu](https://0x0.st/-50L.log)
[vo=gpu-next](https://0x0.st/-509.log)

**Comment by Dudemanguy** [comment]
I stopped being lazy and can confirm that this also happens in GNOME/Mutter so it's not Sway-only.

**Comment by haasn** [comment]
Oh, I see - it's only the *background* that's transparent? Okay this is very surprising. What happens if you set the background color to something else, e.g. red?

**Comment by Dudemanguy** [comment]
Alright so this gets weird. Some colors (like red: `#ff0000`) do work. Others (like this blue: `#0080ff`) have transparency (see below picture). And of course, some other ones like black and such have no affect at all (just totally transparent).

![2021-11-10-140929_grim](https://user-images.githubusercontent.com/5105515/141186336-5b6defff-95ab-44a1-b632-0292d2dd4a8c.png)

**Comment by haasn** [comment]
@Dudemanguy can you please test with this diff applied?

```diff
diff --git a/src/renderer.c b/src/renderer.c
index 3e4dbc5..fe2f472 100644
--- a/src/renderer.c
+++ b/src/renderer.c
@@ -3029,6 +3029,8 @@ void pl_frame_clear_rgba(pl_gpu gpu, const struct pl_frame *frame,
                 clear[c] = mult * encoded[plane->component_mapping[c]];
         }
 
+        PL_WARN(gpu, "clearing plane %d with values %f %f %f %f",
+                p, clear[0], clear[1], clear[2], clear[3]);
         pl_tex_clear(gpu, plane->texture, clear);
     }
 }
```

**Comment by Dudemanguy** [comment]
With the default background (aka black):
`[vo/gpu-next/vulkan/libplacebo] clearing plane 0 with values 0.000000 0.000000 0.000000 0.000000`

With #ff0000:
`[vo/gpu-next/vulkan/libplacebo] clearing plane 0 with values 1.000000 0.000000 0.000000 1.000000`

With #0080ff:
`[vo/gpu-next/vulkan/libplacebo] clearing plane 0 with values 0.000000 0.501961 1.000000 0.000000`

With #000010:
`[vo/gpu-next/vulkan/libplacebo] clearing plane 0 with values 0.000000 0.000000 0.062745 0.000000`
