### ISSUE TITLE
vo_gpu-next: Worse HDR -> SDR conversion compared to vo_gpu

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#9435]
### Important Information

Provide following Information:
- mpv version 
```
mpv 0.34.0-16-gec16769c2d Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  7 08:41:58 +08 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.101
   libswresample   4.0.100
FFmpeg version: git-2021-11-06-1728127e
```
- Windows Version - Windows 10 21H1 Build 19043.1288
- Source of the mpv binary - Shinchiro build `mpv-x86_64-20211107-git-ec16769`

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

`mpv --no-config`
![image](https://user-images.githubusercontent.com/22327220/141179694-9f14b39f-fe9d-4a00-87e3-a6d1bbde908c.png)

`mpv --no-config --vo=gpu-next`
![image](https://user-images.githubusercontent.com/22327220/141180133-9c5fae35-a7f3-4b4e-9f9b-b785265432d0.png)

Pics taken using Windows' OS level screenshot feature on a SDR display

### Expected behavior

Equivalent (or somehow better?) HDR -> SDR conversion compared to `vo=gpu`

### Actual behavior

`vo=gpu-next` has more contrast and/or saturation, especially the blue spectacles seem to have clipped

### Log file

With `vo=gpu-next`
[mpv.txt](https://github.com/mpv-player/mpv/files/7515433/mpv.txt)

With no config at all:
[mpv-no-config.txt](https://github.com/mpv-player/mpv/files/7515440/mpv-no-config.txt)

### Sample files

File used: https://www.demolandia.net/downloads.html?id=654828652
Timestamp: 00:00:51.952

**Comment by Silver-Fullbuster** [comment]
With `--target-trc=gamma2.2 --vo=gpu-next`
![image](https://user-images.githubusercontent.com/22327220/141182691-f84d8bdd-27fe-4fda-b3fd-c3b57dc0af91.png)

Colors seem improved and comparable to `no-config`

With `--hdr-compute-peak=no`
![image](https://user-images.githubusercontent.com/22327220/141183064-511460aa-9914-4359-92c2-99831199e503.png)

Still not correct

**Comment by Doofussy2** [comment]
Try adding `gamut-clipping=no`

**Comment by Silver-Fullbuster** [comment]
Updated to latest shinchiro build (`mpv-x86_64-20211114-git-c478a1e`)

`mpv --no-config --vo=gpu-next --gamut-clipping=no`

![image](https://user-images.githubusercontent.com/22327220/141683756-f4b480a6-5747-45d8-98c2-2ea5695cc939.png)

Log File

[mpv.txt](https://github.com/mpv-player/mpv/files/7533834/mpv.txt)

**Comment by epicfilmmaker93** [comment]
Could you please try it with tone-mapping=reinhard? BT.2390 has some problems in mpv (see #7984), and probably its version in libplacebo isn't perfect as well

**Comment by Silver-Fullbuster** [comment]
`mpv --no-config --vo=gpu-next --tone-mapping=reinhard` 
![image](https://user-images.githubusercontent.com/22327220/141686392-587d78a5-596a-40b2-ae24-b207fa9d4be2.png)

Log file 

[mpv.txt](https://github.com/mpv-player/mpv/files/7533980/mpv.txt)

**Comment by ValZapod** [comment]
> and probably its version in libplacebo isn't perfect as well

No, that part is already fixed.

**Comment by epicfilmmaker93** [comment]
Ok, I'm sorry then

**Comment by Silver-Fullbuster** [comment]
Tried `mpv-x86_64-20220109-git-777628e` with `mpv --no-config --vo=gpu-next --gpu-api=vulkan --log-file=D:\mpv.txt`

Complete black screen when playing the file.

Log File: 
[mpv.txt](https://github.com/mpv-player/mpv/files/7835639/mpv.txt)

**Comment by haasn** [comment]
> Complete black screen when playing the file.

Broken file

**Comment by Silver-Fullbuster** [comment]
https://www.demolandia.net/downloads.html?id=654828652

Just to confirm, this file is broken?

**Comment by Natural-Harmonia-Gropius** [comment]
you need to add `gamut-mapping-mode=clip` into your config.

**Comment by haasn** [comment]
> Just to confirm, this file is broken?

```
Mastering display color primaries        : R: x=1.000000 y=1.000000, G: x=1.000000 y=1.000000, B: x=1.000000 y=1.000000, White point: x=1.000000 y=1.000000
Mastering display luminance              : min: 0.1000 cd/m2, max: 0.5000 cd/m2
```

Yes.

**Comment by haasn** [comment]
HDR->SDR tone-mapping has changed a lot. Re-open if you're still unhappy with the results.

**Comment by damian101** [comment]
Issue still exists, vo=gpu tonemapping is accurate, while vo=gpu-next tonemapping is very much not so, regardless of the tonemapping function used.
