### ISSUE TITLE
vo_gpu-next: seeking behind in HDR videos produces a corrupted/unprocessed frame

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#9436]
### Important Information

Provide following Information:
- mpv version 
```
mpv 0.34.0-16-gec16769c2d Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  7 08:41:58 +08 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.101
   libswresample   4.0.100
FFmpeg version: git-2021-11-06-1728127e
```
- Windows Version - Windows 10 21H1 Build 19043.1288
- Source of the mpv binary - Shinchiro build `mpv-x86_64-20211107-git-ec16769`

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

`mpv --no-config --vo=gpu-next`
![image](https://user-images.githubusercontent.com/22327220/141181702-87542a27-3cfa-4ee8-a2b9-4dddcfb996d2.png)

1. Play an HDR video on SDR display (no idea how it behaves on HDR displays)
2. Pause the video at some point
3. Seek a few frame behind (I used the default keybind `,`)

### Expected behavior

Correct rendering of the previous frame

### Actual behavior

`vo=gpu-next` shows a very weird/corrupted frame
However, if the display updates (like on mouse hover activating osc), the frame gets properly rendered

### Log file

[mpv.txt](https://github.com/mpv-player/mpv/files/7515499/mpv.txt)

### Sample files

File used: https://www.demolandia.net/downloads.html?id=654828652

**Comment by Silver-Fullbuster** [comment]
Using `hdr-compute-peak=np` doesn't reproduce this
Using `target-trc=gamma2.2` produces a black image instead

**Comment by haasn** [comment]
Seems like this happens as a result of peak detection not being delayed. Still looking into why, but that does mean you can work around it by specifying `--allow-delayed-peak-detect=no`.
