### ISSUE TITLE
Current-window-scale behavior is strange when hidpi-window-scale is on

### ISSUE THREAD

**Issue by bepvte** [mpv-player/mpv#9437]
### Important Information

Provide following Information:
- mpv version `mpv 0.34.0`
- Windows Version `Windows 10 [10.0.19043 Build 19043]`
- Source of the mpv binary *Chocolatey*
- If known which version of mpv introduced the problem
I'm almost certain its related to #9104
- Possible screenshot or video of visual glitches
[vid of problem](https://user-images.githubusercontent.com/8226605/141200957-1fa81d8f-9227-4f8e-97f3-1022132bf2c5.mp4)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.
**Done**
Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

1.  Open a video with mpv at a high dpi scale on windows. For me, I had to do 200%.
2. Try and resize the video with alt + 1 or alt + 0
3. Try again with `--no-hidpi-window-scale``, and problem doesn't occur

### Expected behavior
Video resizes and reaches scale 1 somehow
### Actual behavior
Video resizing becomes almost useless and acts confusingly, never producing a window that matches the videos size.
### Log file
[log file](https://github.com/mpv-player/mpv/files/7516255/out.txt)
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by avih** [comment]
>     3\. Try again with `--no-hidpi-window-scale``, and problem doesn't occur

What _IS_ the problem which doesn't occur?

**Comment by hooke007** [comment]
I think he mean, 200%dpi system scale should not affect window scale.

set current-window-scale 1.0 should always make video looks as the size as original.

**Comment by bepvte** [comment]
Trying to set a 720p video to 1x scale on a hidpi monitor makes it fill the whole screen, making the "current-window-scale" feature somewhat useless the way its implemented right now. Its hard to see use cases where this behavior is expected and useful to anyone right now, but I might be misunderstanding something. Maybe current-window-scale should get special behavior for hidpi, or the no-hidpi-window-scale flag should be the default? I don't fully understand the design of the feature and stuff, so I might be wrong and confused here, but right now it's very confusing.

> I think he mean, 200%dpi system scale should not affect window scale.
> 
> set current-window-scale 1.0 should always make video looks as the size as original.

Yeah, that would make most sense to me

**Comment by avih** [comment]
Well, with 200% DPI, the text is twice bigger in pixels than on a 100% DPI monitor, and mpv does the same with the video.

If you don't like this behaviot then just disable it?

**Comment by hooke007** [comment]
> For example, --window-scale=0.5 would show the window at half the video size.

Maybe the example in the doc didn't account dpi and make it a little deceptive?

**Comment by avih** [comment]
> > For example, --window-scale=0.5 would show the window at half the video size.
> 
> Maybe the example in the doc didn't account dpi and make it a little deceptive?

Who are you quoting, who are you replying to, and what do you mean? that some example at the docs is incorrect?

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-window-scale

I think that is why he think `Current-window-scale=1` didn't reach his goal.
Apparently window-scale now will consider the dpi. dpi=200% lead that --window-scale=0.5 would show the window at same size of the video instead of `half`.

**Comment by avih** [comment]
@hooke007 let's give @bepvte a chance to explain it best. Because I don't really understand what the issue is, and I don't want you or me to guess.

**Comment by bepvte** [comment]
Hooke explained it correctly. Setting the window scale on hidpi machines to "1x" should make the window 1x size, not attempt to make it 2x. Otherwise the option is confusing.

**Comment by avih** [comment]
But this is what it does:
>  `--hidpi-window-scale` ... On regular HiDPI resolutions the window opens with double the size but appears as having the same size as on non-HiDPI resolutions

When you set higher-than-100% DPI scale you tell the OS that you want to make things bigger on screen. All the windows titlebar and decorations become bigger, text become bigger, buttons and other widgets become bigger, etc - and so does the mpv window.

And if you want to make everything bigger (by setting high DPI at the OS), but keep the mpv windows exactly 1:1 in pixel size without scaling it like everything else on screen - then simply disable this option.

Personally I don't see the issue here.
