### ISSUE TITLE
Chrome OS Linux Container does not support certain Wayland features

### ISSUE THREAD

**Issue by richard-gravy** [mpv-player/mpv#9446]
Hello

mpv version "c478a1e" (git master, self-compiled)
Linux version: `Linux penguin 5.4.139-16311-g330b3df0010b #1 SMP PREEMPT Tue Oct 26 21:17:14 PDT 2021 aarch64 GNU/Linux`, based on Debian buster, running as "Linux" container under Chrome OS version 94.0.4606.114
Device: Lenovo Chromebook Duet (aarch64)

The [Chrome OS Linux container](https://support.google.com/chromebook/answer/9145439?hl=en) indicates that it supports Wayland applications, though it does not support all expected Wayland protocols.

I have searched around and people have been able to recompile sommelier, the offending Chrome OS service, to provide xdg_wm_base support.  However, this would require switching into developer mode, which disables all security elements of the device.  I would like to avoid doing that.

sommelier advertises the "wl_compositor", "wl_shm", "wl_drm", "wl_subcompsitor", "wl_output", "wl_data_device_manager", "wl_seat", "gtk_shell1" and "wl_shell" stable protocols.

Additionally, it advertises the "zwp_pointer_constraints_v1", "zwp_relative_pointer_manager_v1", "zwp_text_input_manager_v1" and "zxdg_shell_v6" unstable protocols.

Is it possible to use an alternative protocol, like zxdg_shell_v6, to achieve similar results?
Log: [20211114-stdout.txt](https://github.com/mpv-player/mpv/files/7533918/20211114-stdout.txt)

**Comment by Dudemanguy** [comment]
zxdg_shell_v6 is pretty old. mpv dropped support for it a long time ago. Desktop wayland has used xdg_shell for years now as the defacto standard. Chrome OS should really update their container thing.

**Comment by richard-gravy** [comment]
nvm, managed to find #6577 and can implement that as a workaround.
