### ISSUE TITLE
How to make profile to search for two different filenames?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9448]
Hi,

I'm trying to make profile that search for two different file names.
Example first file name is Crunchyroll second file name is CR.

This what I try to do but didn't work. Could someone help please?

```
[Crunchyroll]
profile-cond=string.match(get("filename", ""), "CR")~=nil
profile-cond=string.match(get("filename", ""), "Crunchyroll")~=nil
pause
fs
deband=yes
deband-iterations=3
deband-threshold=40
deband-range=20
deband-grain=0
glsl-shader="~~/noise_static_chroma.hook"
glsl-shader="~~/noise_static_luma.hook"
scale=spline36
cscale=spline36
dscale=mitchell
dither-depth=auto
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
```

**Comment by guidocella** [comment]
`profile-cond=get("filename", ""):match("CR") ~= nil or get("filename", ""):match("Crunchyroll") ~= nil`

**Comment by erickyun** [comment]
> `profile-cond=get("filename", ""):match("CR") ~= nil or get("filename", ""):match("Crunchyroll") ~= nil`

Thank you very much. :)
