### ISSUE TITLE
linux static builds

### ISSUE THREAD

**Issue by Abu-Abdullah** [mpv-player/mpv#945]
Can we have the option to have static build on Linux.
there is an example for mplayer on:
https://code.google.com/p/mplayer-subjunk-builds/downloads/detail?name=MPlayerMEncoder-SB50-Linux.zip&can=1&q=

even if we loose few features, i believe it is very useful to have this.

**Comment by Sami32** [comment]
@lachs0r Where could i find a Linux static build ?
As i wasn't able to make it myself, so i'll much appreciate your help to get a working one.
I wasn't smart to found a link to your MEncoder build script either :-(

**Comment by lachs0r** [comment]
No such thing exists and I’ve changed my opinion since then. Either get your distro to package mpv, or use [mpv-build](https://github.com/mpv-player/mpv-build).
