### ISSUE TITLE
vo_gpu-next: some module of anime4k make mpv freezing

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#9455]
### Important Information

Provide following Information:
- mpv version
git 3bfc37d
- Windows Version
win11 first release
- Source of the mpv binary
built by shinchiro's toolchain
- If known which version of mpv introduced the problem
N/A
- Possible screenshot or video of visual glitches
N/A

### Reproduction steps

run mpv and play the hdr video (sdr display)
apply the shader anime4k

### Expected behavior
shaders would work

### Actual behavior
some kind of shaders would hang the mpv.
And finally I have to kill the instance by the task manager.

### Log file
[gpu-next1.log](https://github.com/mpv-player/mpv/files/7541871/gpu-next1.log)

### Sample files

I do not test all the a4k modules. I found [Anime4K_3DGraphics_AA_Upscale_x2_US](https://github.com/bloc97/Anime4K/blob/master/glsl/Upscale/Anime4K_3DGraphics_AA_Upscale_x2_US.glsl) and [Anime4K_Restore_CNN_Soft_M](https://github.com/bloc97/Anime4K/blob/master/glsl/Restore/Anime4K_Restore_CNN_Soft_M.glsl)
 would make mpv lose response.

**Comment by haasn** [comment]
Can you produce another log with `--msg-level=vo/gpu-next=trace`?

**Comment by hooke007** [comment]
[gpu-next.log](https://github.com/mpv-player/mpv/files/7542046/gpu-next.log)

**Comment by haasn** [comment]
I don't see anything wrong on our end. All of the dependencies are correct. The GPU just seems to deadlock and stop processing commands for no apparent reason.

Might need to take this one up with nvidia. But, just to be sure, does `--swapchain-depth=8` help at all?

**Comment by hooke007** [comment]
Recently I updated many things including nvidia drive, system patch, mpv.
Cannot reproduce the issue now, so close it.
