### ISSUE TITLE
Strange error messages while playing a video

### ISSUE THREAD

**Issue by mdziczkowski** [mpv-player/mpv#9458]
### Important Information
- mpv version: 0.27.0-394-g871a8a316a
- Linux Distribution and Version: Debian 10
- Window Manager and version: Openbox
- GPU driver and version: GPU card specific

### Reproduction steps

Open a video in mpv thru command line to see oputput

### Expected behavior

Normal video playback

### Actual behavior

mpv display strange video related error like messages in the terminal

### Log file

> Xlib: sequence lost (0x10044 > 0x46) in reply type 0x0!
>
>[vo/gpu/opengl] Suspected software renderer or indirect context.
> libEGL warning: DRI2: failed to authenticate
> [vo/gpu/opengl] Suspected software renderer or indirect context.
> Xlib: sequence lost (0x10044 > 0x46) in reply type 0x0!
> [vo/gpu/opengl] Suspected software renderer or indirect context.
> Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
> [vo/vdpau] Error when calling vdp_device_create_x11: 1
> [vo/xv] No Xvideo support found.
> libva info: VA-API version 0.39.4
> libva info: va_getDriverName() returns -1
> libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
> [vaapi] Failed to initialize VAAPI: unknown libva error
> [vo/x11] Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcing the x11 VO.

### Sample files

any video, aspecially openend from an URL

**Comment by CounterPillow** [comment]
Your graphics drivers are completely broken and you don't have 3d acceleration.

Also

> mpv version: 0.27.0-394-g871a8a316a

We do not support old versions of mpv.
