### ISSUE TITLE
Missing unlocking here in the method dvb_ope

### ISSUE THREAD

**Issue by ryancaicse** [mpv-player/mpv#9459]
It seems the lock release is missing before **Line 1048**. Should it be a bug?
https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/stream/stream_dvb.c#L1024-L1049

**Comment by olifre** [comment]
Yes, this seems like a bug, I'll fix it with a PR shortly. 
The issue is usually not triggered in real life, since configuration will either be invalid at start or be valid — it should however be possible to trigger a deadlock by using a playlist with valid and invalid stream URLs.
