### ISSUE TITLE
Is there any way to use input.conf to activate some auto-profiles?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#9461]
I would like to enable or disable audio filter by pressing my keyboard, is there any way to do it?
This is my auto-profile:
```
[Multi-Channel]
profile-cond= audio_params["channel-count"] > 2
af=sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz4.sofa:interpolate=true:radius=5 #For the headphone
[Dual-Channel]
profile-cond= audio_params["channel-count"] <= 2
af-clr
```
If I can activate it by pressing keyboard, I don't need to comment out them if I'm using a speaker.

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by hooke007** [comment]
If you want to manually activate some profiles or options, why use conditions to judge?
Why not just use `<key> set af sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz4.sofa:interpolate=true:radius=5`

**Comment by laichiaheng** [comment]
@hooke007 How about the af-clr?

**Comment by hooke007** [comment]
`<key> vf clr ""`

**Comment by laichiaheng** [comment]
@hooke007 I thought it were `<key> set af clr`

**Comment by hooke007** [comment]
You can try first.
And I think toggle would be better.
`<key> af toggle sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz4.sofa:interpolate=true:radius=5`

**Comment by laichiaheng** [comment]
@hooke007 Cool, thanks.
This one simple line solved my problem.
