### ISSUE TITLE
MPV no longer runs with `hwdec=auto` after OS update

### ISSUE THREAD

**Issue by David-Else** [mpv-player/mpv#9465]
### Important Information

Provide following Information:
- mpv version 0.32
- Linux Distribution and Version Rocky Linux 8.5
- Source of the mpv binary RPM Fusion
- Window Manager and version Gnome Version 3.32.2
- GPU driver and version:

Radeon RX550/550 Series (POLARIS12, DRM 3.40.0, 4.18.0-348.2.1.el8_5.x86_64, LLVM 12.0.1)
Mesa 21.1.5

### Expected behavior

Video plays with GPU acceleration using these settings (as before update):

```
  profile=gpu-hq
  hwdec=auto
  fullscreen=yes
```

### Actual behavior

```
mpv ./x.mkv 
 (+) Video --vid=1 (*) (hevc 1456x1080 23.976fps)
 (+) Audio --aid=1 --alang=ita (*) 'AC3 5.1 ITA' (ac3 6ch 48000Hz)
     Audio --aid=2 --alang=eng 'AC3 2.0 ENG' (ac3 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=ita (*) (f) 'Forced ITA' (hdmv_pgs_subtitle)
     Subs  --sid=2 --slang=ita 'ITA Completi' (hdmv_pgs_subtitle)
File tags:
 Title: x
[vo/gpu/wayland] GNOME's wayland compositor is known to have many serious issues with mpv. Switch to GNOME's xorg session for the best experience.
wl_drm@22: error 0: authenticate failed
VA error: wayland: Wayland roundtrip error: Protocol error (errno 71)
Cannot load libcuda.so.1
[ffmpeg] AVHWDeviceContext: Cannot load libcuda.so.1
[ffmpeg] AVHWDeviceContext: Could not dynamically load CUDA
[vo/gpu/wayland] Error occurred on the display fd, closing
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[ffmpeg/video] hevc_v4l2m2m: Could not find a valid device
[ffmpeg/video] hevc_v4l2m2m: can't configure decoder
Could not open codec.

Exiting... (Quit)
```
I am NOT running Wayland or Nvidia. I have an AMD card and run Xorg. If I remove the `hwdec=auto` the file plays but with no GPU acceleration.

Rocky 8.4 > 8.5 updated Mesa from 20.3.3 to 21.1.5. I don't know if that is involved.

How can I get GPU acceleration back? Thanks.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/7553370/log.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Same with all video files.

**Comment by CounterPillow** [comment]
Please provide a log file that shows the problem in action, using --log-file.

In your case: `mpv --log-file=mpv_sucks.log x.mkv`, then provide us with `mpv_sucks.log`.

**Comment by David-Else** [comment]
@CounterPillow Thanks for looking into this! Here is the log as requested: [mpv_sucks.log](https://github.com/mpv-player/mpv/files/7553525/mpv_sucks.log)

**Comment by CounterPillow** [comment]
It looks like you accidentally are using wayland now (maybe the default session changed?). Also:

```
[   0.199][d][vo/gpu/vaapi-egl/vaapi] libva: VA-API version 1.5.0
[   0.199][d][vo/gpu/vaapi-egl/vaapi] libva: va_getDriverName() returns 0
[   0.199][d][vo/gpu/vaapi-egl/vaapi] libva: Trying to open /usr/lib64/dri/emgd_drv_video.so
[   0.199][d][vo/gpu/vaapi-egl/vaapi] libva: va_openDriver() returns -1
```
the name of the .so here looks odd. For me on a `Picasso` amd APU, I'm using `/usr/lib/dri/radeonsi_drv_video.so`. According to some research, `emgd_drv_video.so` appears to be the intel vaapi implementation.

Please report this to your distribution, as it appears to be their packaging bug.

**Comment by David-Else** [comment]
@CounterPillow You were right about wayland! It is some stupid bug in Rocky, I had to select Wayland, and THEN log out and select Xorg for Xorg to actually run... urrghh!

After going back to Xorg it now works again :) I have attached the new log, do you think there is still an error to report with their packaging? 
[mpv_sucks1.log](https://github.com/mpv-player/mpv/files/7553683/mpv_sucks1.log)

Thanks for your help!

**Comment by CounterPillow** [comment]
```
[   0.164][d][vo/gpu/vaapi-egl/vaapi] libva: VA-API version 1.5.0
[   0.164][d][vo/gpu/vaapi-egl/vaapi] libva: va_getDriverName() returns 0
[   0.164][d][vo/gpu/vaapi-egl/vaapi] libva: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
[   0.164][d][vo/gpu/vaapi-egl/vaapi] libva: va_openDriver() returns -1
```
Looks fine now.
