### ISSUE TITLE
Meson + Static Mingw64: Catastrophic Linking Failure

### ISSUE THREAD

**Issue by rorgoroth** [mpv-player/mpv#9466]
### mpv version and platform versions
3d9c0eae9e4d42494b9435ad3cf5c31217e262ad

### Reproduction steps

It's a build system based on shinchiro/mpv-winbuild-cmake - I haven't tested it on that but there is nothing changed that I imagine causes this, and waf works fine still.

### Expected behavior
It links

### Actual behavior
It doesn't links 

### Log file
mpv-configure-out.log: https://0x0.st/-RyY.log
mpv-build-err.log: https://0x0.st/-RyE.log
mpv-build-out.log: https://0x0.st/-Ry6.log

Any help appreciated, thanks!

**Comment by Dudemanguy** [comment]
If you are trying to use something like `PKG_CONFIG="pkg-config --static"`, it's not going to work (meson ignores this). One ugly way around this is to use `c_link_args` in the cross file and give it something like: `['-Wl,-Bstatic', 'paths/to/needed/lib.a_files', '-Wl,-Bdynamic']`. There may be a better/smarter way to do this. Static linking is far from my forte.

**Comment by rorgoroth** [comment]
>One ugly way around this is to use `c_link_args` in the cross file and give it something like: `['-Wl,-Bstatic', 'paths/to/needed/lib.a_files', '-Wl,-Bdynamic']` (if the build is completely static, you wouldn't need the `-Wl,-Bydnamic` bit I think). There may be a better/smarter way to do this. Static linking is far from my forte.

I spent a few hours reading up on this, trying a few things and it could be because I'm lazy/stupid but it was far too much effort for little to no progress.

> If you are trying to use something like `PKG_CONFIG="pkg-config --static"`, it's not going to work (meson ignores this). 

Thanks, this set me on the right path and I managed to produce a working mpv.exe (with .com built in - not ideal but w/e) using meson+ninja.

The trick is patching meson to respect pkg-config --static.
I managed to find this: [meson/pull/6629](https://github.com/mesonbuild/meson/pull/6629)
Which lead me to patches for buildroot project: https://github.com/woodsts/buildroot/tree/master/package/meson

And with the crossfile:
```
[binaries]
c = '/mingw64/bin/x86_64-w64-mingw32-gcc'
cpp = '/mingw64/bin/x86_64-w64-mingw32-c++'
ar = '/mingw64/bin/x86_64-w64-mingw32-ar'
strip = '/mingw64/bin/x86_64-w64-mingw32-strip'
windres = '/mingw64/bin/x86_64-w64-mingw32-windres'
pkgconfig = '/mingw64/bin/x86_64-w64-mingw32-pkg-config'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64-w64-mingw32'
endian = 'little'

[built-in options]
c_link_args = ['-static']
cpp_link_args = ['-static']

[properties]
pkg_config_static = 'true'
```

It went successful.
I've learnt that the meson probably wont fix this themselves any time soon, problem has been going for years. Having to patch meson itself is ridiculous so hopefully waf stays around for some time.

Thanks for your time.

**Comment by Dudemanguy** [comment]
Yeah unless there's a better user interface for static linking, I don't think waf can be removed. Regardless, waf wasn't going to go anywhere anytime soon. Another thing you could do instead of patching meson is to just patch the `meson.build` in mpv. If you give all the dependency objects the `static: true` keyword in there, it should work. Anyways, I'll close this for now.
