### ISSUE TITLE
Videos from YouTube take an excruciatingly long time to load.

### ISSUE THREAD

**Issue by SkMyPP** [mpv-player/mpv#9468]
It takes an extremely long time to load videos from YouTube (via youtube-dl) on mpv.
I tried playing videos with mpv from every other video hosting site that I could think of; all of them loaded fine. 

Don't know if this is a youtube-dl issue, an mpv issue or whatever (could be YouTube throttling speeds since the same thing happens when playing a video from any Invidious instance) but since I can't find anyone else having this problem I might as well put this here.

Using version 0.33.1 of mpv with version 2021.06.06 of youtube-dl downloaded from the official Manjaro (version 21.1.6) repositories.

**Comment by LaserEyess** [comment]
I can reproduce this with `mpv --no-config $random_youtube_video`, but I can also reproduce it with `yt-dlp $some_youtube_video` so unless you have a specific reason to think this is an mpv issue you should report it to youtube-dl.

**Comment by SkMyPP** [comment]
> so unless you have a specific reason to think this is an mpv issue you should report it to youtube-dl.

Well seeing as how I use mpv to play the video I figured it could be a problem with that instead of youtube-dl, since downloading videos with it is way faster than streaming them with mpv.

I also tried playing videos with the method you mentioned, they still take way too long to load.

**Comment by Doofussy2** [comment]
I have problems with this, also. Very slow loading. I can download the videos very quickly, directly with yt-dlp. But the same video played in mpv, is unwatchable, due to repeated buffering.

[log.txt](https://github.com/mpv-player/mpv/files/7560149/log.txt)

**Comment by LaserEyess** [comment]
> I also tried playing videos with the method you mentioned, they still take way too long to load.

Do you mean you tried `youtube-dl $random_youtube_video` and it worked? or do you mean you forced ipv4? Either way, if you want help with this issue you need to do two things

1. Fill out the issue template that you purposefully ignored. It is very helpful to people trying to reproduce your issues and at the very least without a log file it's impossible to know where the issue is happening.
2. Try to see using youtube-dl directly reproduces this issue, if it does, then there is likely nothing mpv can do about it.

**Comment by SkMyPP** [comment]
> Do you mean you tried `youtube-dl $random_youtube_video` and it worked? or do you mean you forced ipv4?
The latter.

I mean, there really isn't much to it. Just try playing a video from YouTube with mpv, that's literally the only way to reproduce the issue. And using youtube-dl directly didn't reproduce the issue, which is why I opened the issue here and not on the yt-dl repo.

**Comment by LaserEyess** [comment]
It doesn't matter if there isn't much to it, no one can help you without filling out the issue template.

**Comment by SkMyPP** [comment]
I don't know what more you want from me. Steps to reproduce, OS, mpv & youtube-dl version are all there. That seems to me as all the info that's needed.

**Comment by LaserEyess** [comment]
You did not actually confirm steps to reproduce, e.g. does it happen with `--no-config`. Also there's no log file, so it is impossible to help you. Anyway, because you didn't follow the issue template and this Werks On My Machine™ I can't really help you anymore, good luck.

**Comment by SkMyPP** [comment]
> You did not actually confirm steps to reproduce, e.g. does it happen with `--no-config`.

`mpv https://www.youtube.com/watch?v=OLpeX4RRo28`

Technically I used ff2mpv, but the result is exactly the same no matter what you use to watch YouTube videos on mpv.

**Comment by Doofussy2** [comment]
I just drag 'n' drop the URL on the mpv window. It used to work perfectly. This is a fairly recent change. I'll have pull down some of shinchiro's builds and try to figure out when it broke.

**Comment by SkMyPP** [comment]
> I just drag 'n' drop the URL on the mpv window.

Already tried this as well, videos still take ages to load. In any case this very well might be an issue on youtube-dl's part, so I'll try opening an issue there.

And stop getting apoplectic about not using an needlessly convoluted issue template. The issue is "youtube videos take too long to load when playing them on mpv", the steps to reproduce are "watch any youtube video on mpv". That's literally it. No need to fill out a CV for something so simple lmao.

**Comment by garoto** [comment]
> And stop getting apoplectic about not using an needlessly convoluted issue template. 

lol, you're dumb by dismissing the ammount of useful information a simple `log-file` can generate. Anyways, enjoy your "slow" mpv+youtube-dl experince.
