### ISSUE TITLE
--keep-open doesn't work with looping

### ISSUE THREAD

**Issue by groszdaniel** [mpv-player/mpv#9470]
### Important Information

mpv 0.33.1+git.20210630T163736.f2afae55e9 or 0.34.0-UNKNOWN (69f21d5)
openSUSE Tumbleweed 20211116
Source of the mpv binary: Main Repository (OSS) or git
kwin_x11 5.23.2
xf86-video-intel 2.99.917.916_g31486f40-2.3

### Reproduction steps

mpv --keep-open=always --loop-playlist=2 test.mkv test2.mkv
mpv --keep-open=always --loop-file=2 test.mkv test2.mkv

### Expected behavior

Playback stops at the end of every playback of every file, until the user either switches to the next file with the playlist_next input command, or disables the keep-open option. (At least with --loop-playlist. With --loop-file, the current behavior may be intended.)

### Actual behavior

With --loop-playlist, playback changes to the next file immediately when a file ends, as if --keep-open weren't specified, except during the last loop.

With --loop-file, at the end of a file, loopback jumps immediately to the beginning of that file, until the specified number of loops have been performed.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/7563435/log.txt)

**Comment by thebombzen** [comment]
I can reproduce this, I'll take a look.

**Comment by thebombzen** [comment]
It's not possible to make `--keep-open=always` work with `--loop-file` since the only way to break out of `--keep-open=always` is to explicitly seek or explicitly change files. `loop-file` is implemented as a seek to 0, so the only "compatible" way is for `--keep-open=always` to cause `--loop-file` to be ignored entirely. This is not ideal. 

That being said, not working with `--keep-playlist` is just a bug.

**Comment by groszdaniel** [comment]
> It's not possible to make `--keep-open=always` work with `--loop-file` since the only way to break out of `--keep-open=always` is to explicitly seek or explicitly change files. `loop-file` is implemented as a seek to 0, so the only "compatible" way is for `--keep-open=always` to cause `--loop-file` to be ignored entirely. This is not ideal.

Another way to break out of `--keep-open=always` is to turn off the keep-open option with a shortcut (if you've configured one), or through IPC. But I'm not sure which behavior makes more sense.

**Comment by thebombzen** [comment]
Turning it off isn't breaking out of it, in the same way. But during testing I "fixed" the keep-open and loop-file incompat and found that it didn't make any difference whether loop-file was on or not, which was not the goal.
