### ISSUE TITLE
How is MPV compared to other software (PAID)?

### ISSUE THREAD

**Issue by ObsessedHacker** [mpv-player/mpv#9474]
I've been using MPV for a while now, mainly for YouTube with "SponsorBlock" script and for BDMV playback.
There are some paid software like "CyberLink PowerDVD", so I wonder what the differences are and if it's worth it to pay for it for my use cases.
Both offer support for MKV, M2TS, AVC, HEVC, 4K, HDR and etc... so why choose one over the other?
Forgot to mention but CyberLink PowerDVD has a certified BluRay award.

**Comment by avih** [comment]
We don't conduct comparisons to other players.

Feel free to try and/or read the documentation of each program and draw your own comparisons/conclusions.

**Comment by wm4** [comment]
mpv has won a certified autism award, but even then it's clearly an inferior product...
