### ISSUE TITLE
gpu-next support in libmpv

### ISSUE THREAD

**Issue by nehalem501** [mpv-player/mpv#9475]
Hello,
Is it possible to use the new gpu-next video backend with libmpv?
Reading the docs suggests it's not possible as libmpv is OpenGL only and gpu-next works only using Vulkan.

**Comment by stax76** [comment]
It depends on how you use libmpv, the render API is OpenGL, but you can use libmpv without render API, you can use [wid](https://mpv.io/manual/master/#options-wid) instead, that is what mpv.net does.

**Comment by Dudemanguy** [comment]
Old one, but `gpu-next` supports opengl (as of #9486), so you can use the render API with it if you wish. Other ways of libmpv work as well in the same way as they do with `gpu`, so I will close this one.
