### ISSUE TITLE
Why does mpv's yt-dl_hook fail while yt-dlp succeeds? 

### ISSUE THREAD

**Issue by owbosh** [mpv-player/mpv#9477]
I've only ran into this issue on nicovideo.jp so far. The strange thing is that yt-dlp can successfully download videos from nicovideo, while mpv's hook (which is also using yt-dlp) cannot. Tried it with the --no-config option to make sure my configuration wasn't messing with anything, same result. Here's my terminal input + the error message:
`mpv "https://www.nicovideo.jp/watch/sm35840680"`
`[ytdl_hook] Ignoring potentially unsafe url: 'niconico_dmc:sm35840680/archive_h264_360p/archive_aac_64kbps'
Failed to recognize file format.`
It looks like the hook is trying to use the URL 'niconico_dmc:sm35840680/archive_h264_360p/archive_aac_64kbps', but this isn't the URL I gave it. Again, yt-dlp can download "https://www.nicovideo.jp/watch/sm35840680" just fine, so what's going on here?

**Comment by sfan5** [comment]
mpv calls `yt-dlp -J` to retrieve information about the video and then handles the downloading on its own.
In the JSON output the `niconico_dmc:` URL you quoted is returned to mpv but a HTTP(S) URL would be needed for this to work.
yt-dlp will have an internal handler to make downloading work but this is of no use to mpv.
