### ISSUE TITLE
meson: please lower the requirements on version number

### ISSUE THREAD

**Issue by CdeMills** [mpv-player/mpv#9481]
### Important Information

Provide following Information:
- mpv version: git - e095bdb
- Linux Distribution and Version CentOS8 Stream
- If known which version of mpv introduced the problem: ??
- Window Manager and version gnome 3.32

### Reproduction steps
The Meson build system
Version: 0.55.3
Source dir: /home/padupuis/01-Applications/05-Development/mpv
Build dir: /home/padupuis/01-Applications/05-Development/mpv/build
Build type: native build

meson.build:1:0: ERROR: Meson version is 0.55.3 but project requires >=0.60.0
FYI: meson-0.60.0 is to be found only in Fedora Rawhide. Could you go back on Meson to 0.55.3, the one in CentOS8 Stream ?

Regards

Pascal

**Comment by Dudemanguy** [comment]
This can't be done. The meson build is very new and requires some newer meson features (particularly the iconv check) hence why the version requirement is at 60. One could in theory add a bunch of legacy/fallback code to handle older versions but that defeats one of the entire reasons of going to meson in the first place. The waf build exists and will be around for quite a while, so you will have to stick with that for now until your distro updates.

**Comment by haasn** [comment]
> This can't be done. The meson build is very new and requires some newer meson features (particularly the iconv check) hence why the version requirement is at 60. One could in theory add a bunch of legacy/fallback code to handle older versions but that defeats one of the entire reasons of going to meson in the first place. The waf build exists and will be around for quite a while, so you will have to stick with that for now until your distro updates.

I don't follow. What exactly is meson 0.60 doing that makes `dependency('iconv')` somehow different in a way that can't be replicated on e.g. 0.59 (the latest version available in openSuSE)?

**Comment by Dudemanguy** [comment]
>What exactly is meson 0.60 doing that makes dependency('iconv') somehow different in a way that can't be replicated on e.g. 0.59 (the latest version available in openSuSE)?

It actually working. The system method for iconv wasn't implemented until 0.60. The other part is that multiple arguments in dependency checks (like in rpi) wasn't supported until 0.60 as well.

**Comment by haasn** [comment]
Am I correct in assuming these are basically all work-arounds for broken libraries that don't have .pc entries in the correct locations?

**Comment by Dudemanguy** [comment]
It depends. In iconv's case, it doesn't have a .pc on most systems since it is usually a part of the libc. In waf, this check is done via a custom fragment.

**Comment by eli-schwartz** [comment]
Currently:

```meson
iconv = dependency('iconv', required: get_option('iconv'))
if iconv.found()
    ...
endif
```

Backwards compat with old meson:
```meson
iconv_dep = dependency('', required: false)
iconv_found = false
if not get_option('iconv').disabled()
    iconv_found =  cc.has_function('iconv_open')
    if not iconv_found
        iconv_dep = cc.find_library('iconv', has_headers: 'iconv.h', required: get_option('iconv'))
        iconv_found = iconv_dep.found()
    endif
endif

if iconv_found
    ...
endif
```

You can theoretically do this, it's just pain... that is why I added it to meson in 0.60 as a simple one-liner dependency. Though detecting a broken (mismatched libc iconv_open and GNU `iconv.h`) version of iconv is still something I need to implement in meson. That makes the has_function checks a bit more painful. ;)
