### ISSUE TITLE
What's wrong with OpenAL AO?

### ISSUE THREAD

**Issue by etircopyh** [mpv-player/mpv#9483]
mpv's manual says that [OpenAL backend is broken and does not work](https://mpv.io/manual/stable/#audio-output-drivers-openal).

Also OpenAL is disabled on build both for waf and meson. So I'm curios what's broken and why, because it seems to work for me just fine.

**Comment by etircopyh** [comment]
Also, [openal-direct-channels](https://mpv.io/manual/stable/#audio-output-drivers-openal-direct-channels) doesn't seem to have a whole lot of sense to be disabled by default, eh?

**Comment by Dudemanguy** [comment]
The manual entry originated from the old audio rewrite commit (https://github.com/mpv-player/mpv/commit/d27ad9654218463694093697e3d09f8983b4ccf3). However, it seems it was later fixed for the audio API (https://github.com/mpv-player/mpv/commit/0ac724f0025d48e1372ac82c62d504aaadf19735) so probably the manual entry is wrong. I think it was always disabled by default in the build but I'm not 100% sure on that.

**Comment by etircopyh** [comment]
> I think it was always disabled by default in the build but I'm not 100% sure on that.

Yeah, git blame appears to confirm that.

**Comment by Dudemanguy** [comment]
Updated the docs. Thanks for mentioning this.
