### ISSUE TITLE
vo=gpu-next playback results in VK_ERROR_OUT_OF_HOST_MEMORY

### ISSUE THREAD

**Issue by quietvoid** [mpv-player/mpv#9484]
### Important Information

Provide following Information:
- mpv version:
```
mpv 0.34.0-63-ge095bdb5f5 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Fri Nov 19 05:15:16 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```

- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: mpv-git PKGBUILD
- Window Manager and version: Sway 1.6.1, wlroots 0.14.1
- GPU: AMD Navi 5500 XT
- Kernel Driver: amdgpu 5.13.13
- OpenGL Driver: Mesa 21.2.5 (OpenGL 4.6)
- libplacebo version: v4.157.0.157.g0bfc00b-1

### Reproduction steps

- Play a stream through mpv using streamlink (in my case 1080p60), with config `--no-config --vo=gpu-next`
- Wait for a couple minutes, or switch between workspaces.
- Eventually the rendering freezes and mpv can't be closed manually.

To reproduce quicker, leaving the window in a background workspace for 30-45s seems to make it crash as well.

### Expected behavior
Smooth playback.

### Actual behavior
System crash (on latest kernel).

On kernel 5.13.13, amdgpu reports out of memory.
On 5.14 and later, amdgpu crashes with page faults and the GPU is reset.

On 5.13.13:
```
kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* amdgpu_vm_validate_pt_bos() failed.
kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Not enough memory for command submission!
```

The kernel errors seem to be printed a couple seconds before the libplacebo errors.

### Log file

Log with `--no-config --vo=gpu-next --gpu-debug --log-file=mpv.log --msg-level=vo/gpu-next=trace`
Log with 3 errors: https://0x0.st/-R5h.log

Same CLI but `<haasn> quietvoid: it might be more manageable if you just place #define PL_TRACE PL_WARN at the top of libplacebo/src/utils/frame_queue.c`
Smaller (hopefully useful log): https://0x0.st/-RRr.log, another just in case: https://0x0.st/-RRs.log

**Comment by quietvoid** [comment]
I tried setting `--vd-lavc-dr=no` and there was no crash for 10 mins, so maybe this fixes it.
Removed it and got a crash within 5min.

**Comment by LaserEyess** [comment]
Just a hunch, but can you reproduce this under Xorg?

**Comment by haasn** [comment]
Does this fix it?

```diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index 8a5f078939..1a02f27699 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -627,12 +627,6 @@ static void draw_frame(struct vo *vo, struct vo_frame *frame)
         p->last_id = id;
     }
 
-    // Doesn't draw anything. Only checks for visibility.
-    struct ra_swapchain *sw = p->ra_ctx->swapchain;
-    bool should_draw = sw->fns->start_frame(sw, NULL);
-    if (!should_draw)
-        return;
-
     if (p->target_hint && frame->current) {
         struct pl_swapchain_colors hint = get_csp_hint(vo, frame->current);
         pl_swapchain_colorspace_hint(p->sw, &hint);
@@ -641,7 +635,9 @@ static void draw_frame(struct vo *vo, struct vo_frame *frame)
     }
 
     struct pl_swapchain_frame swframe;
-    if (!pl_swapchain_start_frame(p->sw, &swframe)) {
+    struct ra_swapchain *sw = p->ra_ctx->swapchain;
+    bool should_draw = sw->fns->start_frame(sw, NULL); // for wayland logic
+    if (!should_draw || !pl_swapchain_start_frame(p->sw, &swframe)) {
         // Advance the queue state to the current PTS to discard unused frames
         pl_queue_update(p->queue, NULL, &(struct pl_queue_params) {
             .pts = frame->current->pts + frame->vsync_offset,
```

**Comment by quietvoid** [comment]
@haasn Yes, it does.
There are still a lot of discarded frames but they aren't allocated anymore, it seems.
