### ISSUE TITLE
auto-profile coredump in Plasma5

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#9492]
### Important Information

Provide following Information:
- mpv version: mpv 0.34.0-dirty
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: AUR
- If known which version of mpv introduced the problem: I don't know
- Window Manager and version: Kwin 5.23.3-1
- GPU driver and version: Mesa Gallium driver 21.2.5 for AMD Radeon RX 580 Series (POLARIS10, DRM 3.42.0, 5.15.2-zen1-1-zen, LLVM 13.0.0)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1.Play videos with auto-profiles.
2. Maybe crash or not.

### Expected behavior
No core dump
### Actual behavior
core dump, and a lot, but not everytime
### Log file

[easy_core_dump.txt](https://github.com/mpv-player/mpv/files/7574484/easy_core_dump.txt)

### Sample files

Every files.

**Comment by Dudemanguy** [comment]
What auto-profile are you using exactly to produce this crash?
