### ISSUE TITLE
Player crashes after rewinding forward (smk - Smacker videos)

### ISSUE THREAD

**Issue by necros2k7** [mpv-player/mpv#9494]
### Important Information

Provide following Information:
- mpv version mpv-x86_64-20211114-git-c478a1e.7z
- Windows Version 11
- Source of the mpv binary https://sourceforge.net/projects/mpv-player-windows/files/64bit/

### Reproduction steps
open sample file and seek to random time

### Expected behavior
seek time with smk files

### Actual behavior
crash after seeking

P.S. Not sure if it`s mpv problem not ffmpg

### Log file
[   2.005][v][lavf] execute seek (to 16.627586 flags 32)
[   2.005][e][ffmpeg/demuxer] smk: Random seeks are not supported (can only seek to start).
[   2.005][v][file] stream level seek from 983040 to 151552
[   2.005][v][cplayer] hr-seek, skipping to 16.627586
[   2.005][e][ffmpeg/demuxer] smk: Invalid audio part size
[   2.005][e][ffmpeg/demuxer] smk: Random seeks are not supported (can only seek to start).
[   2.005][e][ffmpeg/demuxer] smk: Invalid audio part size
[   2.005][v][lavf] Seek failed (Operation not permitted)
[   2.005][v][lavf] seek done
[   2.005][e][ffmpeg/demuxer] smk: Invalid audio part size
[   2.006][w][lavf] error reading packet: Invalid data found when processing input.

### Sample files

https://file.io/uiVPbtaJ9reQ

**Comment by Dudemanguy** [comment]
Probably an ffmpeg thing.
