### ISSUE TITLE
No config file exists but different behavior with --no-config

### ISSUE THREAD

**Issue by elfehr** [mpv-player/mpv#9495]
### Important Information

- mpv version: 0.34.0, but I remember the same behavior since I first installed mpv months ago
- Linux Distribution and Version: ManjaroLinux 21.2.0
- Source of the mpv binary: [Archlinux community repo](https://archlinux.org/packages/community/x86_64/mpv/)
- Window Manager and version: sway version 1.6.1

### Reproduction steps

I was trying to debug why mpv quits when disconnecting bluetooth headphones (and after way too long, found it was solved by setting `stop-playback-on-init-failure=no`, or at least I though because it worked yesterday but not today anymore). With `mpv --no-config`, mpv doesn't quit, so I tried to find the responsible setting.
I didn't have `stop-playback-on-init-failure=yes` or anything that seems remotely related in my config, but to be sure I deleted the whole file. Still, running only `mpv`, it is still quitting when turning off my headphones.

The following files/folders don't exist:
- ~/.mpv/
- $XDG_CONFIG_HOME/mpv/mpv.conf (just deleted it)
- $XDG_CONFIG_HOME/mpv/scripts/ (also deleted it, to be sure)
- $XDG_CONFIG_HOME/mpv/config
- $XDG_CONFIG_HOME/mpv/input.conf
- /usr/local/etc/mpv/
- /etc/mpv/mpv.conf (which is where the config is supposed to go, but as  [the package listing](https://archlinux.org/packages/community/x86_64/mpv/) shows no system-wide config file is installed by default)
- /etc/mpv/config

The only files are
- /etc/mpv/encoding-profiles.conf
- /etc/mpv/scripts/mpris.so

`mpv --input-test --force-window --idle` doesn't see any key pressed when turning off the headphones, and I looked with `wev` if any XF86AudioStop key event was happening, but there is none, so it doesn't seem that my headphone are asking mpv to quit.

### Expected behavior

`mpv --no-config` and `mpv` behave the same when no config file exists in any of the possible locations according to the documentation (and I also didn't see any config file read according to the logs).

### Actual behavior

With `mpv` and no config file, mpv quits when turning off bluetooth headphones. With `mpv --no-config`, it switches to the laptop speakers and continue playing.

### Log file

`mpv`: https://0x0.st/-7ox.txt
 `mpv --no-config`: https://0x0.st/-7Hr.txt

**Comment by sfan5** [comment]
`--no-config` does more than disable mpv.conf. It disables anything that could exist in any of the mpv config directories, this includes `scripts`, `script-opts` and `watch_later` files.
You already listed /etc/mpv/scripts/mpris.so. This is a third-party plugin and exactly what you should investigate.
