### ISSUE TITLE
play youtube video using "send to mpv player" is stuttering every 1 second

### ISSUE THREAD

**Issue by andrew-ysk** [mpv-player/mpv#9498]
While playing youtube video using "send to mpv player" from firefox , the mpv video quality stuttering every 1 second, totally not watchable. 
After around several minutes, mpv cached the whole video file, hence able to play without stuttering.

### Important Information

Provide following Information:
- mpv version
mpv 0.33.1-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4

- Linux Distribution and Version
uname -r
5.10.68-1-MANJARO

- Source of the mpv binary
from manjaro community repository

- If known which version of mpv introduced the problem
FFmpeg version: n4.4

- Window Manager and version
 inxi -G
Graphics:
  Device-1: Intel 82Q35 Express Integrated Graphics driver: i915 
  v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: loaded: intel 
  unloaded: modesetting resolution: 1280x1024~60Hz 
  OpenGL: renderer: Mesa DRI Intel Q35 v: 1.4 Mesa 21.2.2 
sddm.service - Simple Desktop Display Manager

- GPU driver and version
Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02)

- Possible screenshot or video of visual glitches
The issue is cache is low, it runs out of cache, hence stuck to cache up.. and the cycle repeats. 
I keep pressing "i" to see the cache runs out and cache up while the video is playing.. 

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases
I have just install mpv yesterday, so it shld be up to date.

**Comment by sfan5** [comment]
https://github.com/mpv-player/mpv/issues/9493#issuecomment-974736729
