### ISSUE TITLE
vo=gpu-next + scale=ewa_lanczossharp

### ISSUE THREAD

**Issue by ObsessedHacker** [mpv-player/mpv#9502]
MPV [manual](https://mpv.io/manual/master/) [recommends scale=ewa_lanczossharp](https://mpv.io/manual/master/#options-ewa-lanczossharp)
But the new `vo=gpu-next `doesn't have `scale=ewa_lanczossharp`
What should be recommended now?

**Comment by haasn** [comment]
`scale=ewa_lanczos`.
