### ISSUE TITLE
If I close stats.lua, there are Vsync-Jitter, mistimed, delayed.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#9504]
It only happens in Gnome Wayland.
I know MPV has announced that it does not officially support Gnome desktop anymore, but I still hope somebody can solve this issue.
If I open stats.lua, the vsync jitter will drop to 0 few seconds later, the frame mistimed and delayed will stop rising. If I close stats.lua again, the vsync jitter and frame mistimed and delayed will rise quickly, and I can see slightly stutter appears in the video.
### Important Information

Provide following Information:
- mpv version: mpv 0.34.0-73-g2b2442ee67-dirty
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: mpv-build-git from AUR
- If known which version of mpv introduced the problem: I don't know.
- Window Manager and version: Mutter41.1-1
- GPU driver and version: Mesa Gallium driver 21.2.5 for AMD Radeon RX 580 Series (POLARIS10, DRM 3.42.0, 5.15.3-zen1-1-zen, LLVM 13.0.0)
- Possible screenshot or video of visual glitches
![2021-11-22 22-34-15 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/142880687-d2ef38c2-7831-4da3-9023-0dbe9d9f70d3.png)
### Reproduction steps

mpv --log-file=delayed_without_stats_lua.txt --fs --no-config --video-sync=display-resample 'video' 

### Expected behavior
No stutter, no vsync jitter, no frame mistimed, no frame delayed.
### Actual behavior
They all happened.
### Log file
[delayed_without_stats_lua.txt](https://github.com/mpv-player/mpv/files/7581949/delayed_without_stats_lua.txt)
### Sample files
Every video.

**Comment by Dudemanguy** [comment]
Hmm, I can reproduce this. It happens on weston too actually. I wonder if I have to start calling `wl_display_roundtrip` unconditionally again. I'd really prefer not to (this used to work).

**Comment by laichiaheng** [comment]
> Hmm, I can reproduce this. It happens on weston too actually. I wonder if I have to start calling `wl_display_roundtrip` unconditionally again. I'd really prefer not to (this used to work).

Does Plasma Wayland do things differently than Gnome and Weston? I don't see it happens in Plasma Wayland.

**Comment by Dudemanguy** [comment]
>Does Plasma Wayland do things differently than Gnome and Weston?

Yeah. Well strictly speaking mpv does something differently. Since it doesn't have presentation time, `wl_display_roundtrip` is called on every frame which is semi-blocking.

**Comment by laichiaheng** [comment]
> > Does Plasma Wayland do things differently than Gnome and Weston?
> 
> Yeah. Well strictly speaking mpv does something differently. Since it doesn't have presentation time, `wl_display_roundtrip` is called on every frame which is semi-blocking.

Is it possible for users to enable the `wl_display_roundtrip`?

**Comment by Dudemanguy** [comment]
No it's in the code. I need to investigate more on what's really happening here. Gnome is still mistimed even when using that function.

**Comment by laichiaheng** [comment]
@Dudemanguy The video looks smooth now, thanks.
