### ISSUE TITLE
Not playing mp4/mkv video files when adding those two lines in mpv.conf file

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#9508]
I can't play mp4/mkv files when I add those 2 lines of code in my mpv.conf file.
And I don't have any ideas how to resolve this and unfortunately, even I tried to learn about it from the doc of mpv.

```
demuxer-lavf-format=hls
stream-lavf-o-append="protocol_whitelist=file,http,https,tcp,tls,crypto,hls,applehttp"
```
- mpv version 2021-10-10 modified
- Windows Version 21H2
- Source of the mpv binary 2021-10-10 modified

**Comment by CounterPillow** [comment]
where is your log file?

**Comment by thebombzen** [comment]
Don't put nonsensical options in your config file and then file a bug report when it doesn't work.

**Comment by Max-Enrik** [comment]
This is what inside of mpv.conf file.
```
demuxer-lavf-format=hls
log-file=~~desktop/log.txt
```
Just needed to play mp4 files inside of video files folder.
When I drag and drop the folder over mpv player, mpv player just close.

And a log file.
[mpv_log.txt](https://github.com/mpv-player/mpv/files/7591440/mpv_log.txt)

**Comment by thebombzen** [comment]
`demuxer-lavf-format=hls`

don't tell mpv to use the HLS demuxer for every file and then wonder why it can't play files

**Comment by Max-Enrik** [comment]
I think I have to use profile for it.
```
[but don't have any ideas what to write here]
demuxer-lavf-format=hls
demuxer-max-bytes=2GiB
demuxer-readahead-secs=45
```
Look like I won't make this work without help.

**Comment by Max-Enrik** [comment]
I can't find a solution, and look like I won't get a help?

**Comment by qmega** [comment]
I don't think anyone knows what you're actually trying to do with those config directives. I would assume you want that profile applied only for certain files or URLs, so you probably want a [conditional auto profile, documented in the manual here](https://mpv.io/manual/master/#conditional-auto-profiles).

If you need more help than that, you'll have to describe more clearly what you're trying to do. It would probably also be better received as a fresh issue.

**Comment by Max-Enrik** [comment]
I tested the below code for mp4, and it worked well.
```
[extension.mp4]
profile-restore=copy
hue=-50
```

And I tried the below code for m3u8.
```
[extension.m3u8]
demuxer-lavf-format=hls
```

Maybe that is a simple thing for most people. But I am struggling with code. Spend over 3 hours making those five lines of code. Fortunately, three of them worked for mp4, and the last two lines of code did not work for m3u8 files/URLs.
