### ISSUE TITLE
mpv connects to wrong display when running simultaneous X and Wayland session

### ISSUE THREAD

**Issue by alerikaisattera** [mpv-player/mpv#9513]
### Important Information

Provide following Information:
- mpv 1:0.34.0
- Manjaro
- From Manjaro repository
- KWin 5.23.3
- AMDGPU

### Reproduction steps

Run an X session on display 1 (KDE Plasma, but may be present on others)
Run a Wayland session on display 2 (Weston, but may be present on others)
Open a video with mpv in X session on display 1

### Expected behavior

mpv connects to X server on display 1

### Actual behavior

mpv connects to Wayland compositor on display 2

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/7600445/output.txt)

The issue will be closed for ignoring the issue template.

**Comment by Dudemanguy** [comment]
Wayland is before xorg in the autoprobe so if you have an active wayland and xorg session at the same time, the wayland connection is found first and picked. You would have to use `--gpu-context` in your case to launch it on xorg.

**Comment by evelikov** [comment]
AFAICT nearly every toolkit/app out there does the same - try wayland, fallback to xorg. There is no standard (or at least common) way to force one or the other, so I'm not sure this can be "fixed" in mpv.

**Comment by Dudemanguy** [comment]
Going to go ahead and close this since it's not really actionable.
