### ISSUE TITLE
[vo=gpu-next] Video hangs after seek then mpv crashes after CTRL-C

### ISSUE THREAD

**Issue by syncrond** [mpv-player/mpv#9526]
### Important Information

The problem with the hanging video occurs only with the given file (still looking for other problematic files) and when using gpu-next. This hang leads to the follow up bug that mpv segfaults.
With `vo=gpu` it seeks without any issues.

Provide following Information:
- mpv && ffmpeg
```
mpv 0.34.0-86-g059bd3dcaa Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Fri Nov 26 17:51:44 CET 2021
FFmpeg library versions:
   libavutil       57.9.101
   libavcodec      59.13.101
   libavformat     59.9.102
   libswscale      6.1.100
   libavfilter     8.17.100
   libswresample   4.0.100
FFmpeg version: N-104658-g27c9300027
```
- System
```
Ubuntu 20.04.3 LTS Kernel 5.11.0-41-generic
```
running X11

- GPU driver and version
```
GPU id : 0 (Intel(R) Iris(R) Plus Graphics 640 (Kaby Lake GT3e) (KBL GT3))
```
vainfo:
```
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.3.5 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```
vulkaninfo:
```
VkPhysicalDeviceDriverProperties:
---------------------------------
	driverID           = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
	driverName         = Intel open-source Mesa driver
	driverInfo         = Mesa 22.0.0-devel (git-add883b 2021-11-26 focal-oibaf-ppa)
	conformanceVersion = 1.2.0.0
```
### Reproduction steps
Play the given video file with:

`mpv --no-config --vo=gpu-next --gpu-api=vulkan --gpu-debug=yes --v --msg-level=vo/gpu-next=trace test.mkv`

Seek in the video and you see the errors and the video hangs

### Expected behavior

Seeks without any issues. Like with `vo=gpu`

### Actual behavior

Video hangs after seek with device lost errors:

```
vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:481)
```

### Log file

https://0x0.st/-7w0.txt

gdb backtrace of the segmentation fault:

https://0x0.st/-7wU.txt

### Sample files

https://0x0.st/-7wI.mkv

**Comment by haasn** [comment]
Can't reproduce. Works for me on RADV.

Can anybody else with an intel GPU try this?

**Comment by syncrond** [comment]
Thanks for looking into it.
With your assert applied, the assert always triggers in case I seek in the given video:
```
[cplayer] EOF code: 5  
mpv: ../video/out/vo_gpu_next.c:168: free_dr_buf: Assertion `memcmp(dr->sentinel, dr_magic, sizeof(dr_magic)) == 0' failed.
Aborted
```

There was this message in the original logs, dunno if it's a bad thing:
```
[vo/gpu-next/vulkan/libplacebo] Imported host pointer is not page-aligned. This should normally be fine on most platforms, but may cause issues in some rare circumstances.
[vo/gpu-next/vulkan/libplacebo] Rounding imported host pointer 0x7fb73b733400 + 0 -> 1536000 to nearest page boundaries: 0x7fb73b733000 + 1024 -> 1540096
```


Then I did some more testing:
- I tried wayland as compositor -> same issue
- I added `MESA_VK_ABORT_ON_DEVICE_LOSS=true` to the env and indeed it immediately aborts after seeking
- I reencoded the file with ffmpeg and video codec x265 -> same issue
- I reencoded the file with ffmpeg and video codec x264 -> no issue

So I'm off for the weekend but if I can help by testing more, I can do that next week.

**Comment by syncrond** [comment]
Thanks for looking into it.
With your assert applied, the assert always triggers in case I seek in the given video:
```
[cplayer] EOF code: 5  
mpv: ../video/out/vo_gpu_next.c:168: free_dr_buf: Assertion `memcmp(dr->sentinel, dr_magic, sizeof(dr_magic)) == 0' failed.
Aborted
```

There was this message in the original logs, dunno if it's a bad thing:
```
[vo/gpu-next/vulkan/libplacebo] Imported host pointer is not page-aligned. This should normally be fine on most platforms, but may cause issues in some rare circumstances.
[vo/gpu-next/vulkan/libplacebo] Rounding imported host pointer 0x7fb73b733400 + 0 -> 1536000 to nearest page boundaries: 0x7fb73b733000 + 1024 -> 1540096
```


Then I did some more testing:
- I tried wayland as compositor -> same issue
- I added `MESA_VK_ABORT_ON_DEVICE_LOSS=true` to the env and indeed it immediately aborts after seeking
- I reencoded the file with ffmpeg and video codec x265 -> same issue
- I reencoded the file with ffmpeg and video codec x264 -> no issue

So I'm off for the weekend but if I can help by testing more, I can do that next week.

**Comment by haasn** [comment]
In either case, I assume the `free_dr_buf` error is a result of the mapped buffer suddenly becoming undefined data, which itself seems to be a result of the driver somehow crashing / device loss. (Though, incidentally, we could definitely do a better job of detecting device loss and failing gracefully in that case rather than trying to free buffers that now no longer exist...)

I'm no sure what causes it, but here are some things you should definitely try: (alongside the usual flags)

- Try `--vo=gpu --gpu-api=vulkan`
- Try `--vo=gpu-next --vd-lavc-dr=no`

**Comment by syncrond** [comment]
I tried the things you suggested, both options help:

- with `--vo=gpu --gpu-api=vulkan`:
issue is gone

- with `--vo=gpu-next --gpu-api=vulkan --vd-lavc-dr=no`:
issue is gone

Btw. I have to set `--gpu-api=vulkan` otherwise mpv errors and exits without playing at all. Even `--gpu-api=auto` isn't working:
`mpv -v --no-config --vd-lavc-dr=no --vo=gpu-next --log-file=test.txt test.mkv`
Error:
```
[vo/gpu-next] libplacebo was built without OpenGL support.
[cplayer] Error opening/initializing the selected video_out (--vo) device.
```
logfile: https://0x0.st/-hTW.txt

**Comment by haasn** [comment]
What about `--vo=gpu-next --gpu-api=vulkan --vulkan-async-transfer=no`?

**Comment by syncrond** [comment]
With `--vo=gpu-next --gpu-api=vulkan --vulkan-async-transfer=no` it hangs after seek and the assertion triggers.

**Comment by haasn** [comment]
Can you try with this patch? (And no special settings)
It will leak memory like crazy, so ideally test on a small file and seek as soon as possible.

```diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index 0d505f7913..a4701f8d99 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -164,10 +164,6 @@ static pl_buf get_dr_buf(struct mp_image *mpi)
 
 static void free_dr_buf(void *opaque, uint8_t *data)
 {
-    struct dr_buf *dr = opaque;
-    assert(memcmp(dr->sentinel, dr_magic, sizeof(dr_magic)) == 0);
-    // Can't use `&dr->buf` because it gets freed during `pl_buf_destroy`
-    pl_buf_destroy(dr->gpu, &(pl_buf) { dr->buf });
 }
 
 static struct mp_image *get_image(struct vo *vo, int imgfmt, int w, int h,
@@ -192,14 +188,9 @@ static struct mp_image *get_image(struct vo *vo, int imgfmt, int w, int h,
         return NULL;
 
     // Store the DR header at the end of the allocation
-    struct dr_buf *dr = dr_header(buf->data, buf->params.size);
-    memcpy(dr->sentinel, dr_magic, sizeof(dr_magic));
-    dr->gpu = gpu;
-    dr->buf = buf;
-
     struct mp_image *mpi = mp_image_from_buffer(imgfmt, w, h, stride_align,
                                                 buf->data, buf->params.size,
-                                                dr, free_dr_buf);
+                                                NULL, free_dr_buf);
     if (!mpi) {
         pl_buf_destroy(gpu, &buf);
         return NULL;
```

**Comment by syncrond** [comment]
hmm, now with the patch applied I don't see the first frame, just a black mpv window and mpv hangs.
log: https://0x0.st/-hA2.txt
Happens with all videos I give mpv not just the broken test video.

**Comment by syncrond** [comment]
I had a test (without your patch) with an updated kernel. I installed 5.15. (Instead of using 5.11 which comes with Ubuntu 20.04.3 LTS)
Result is, the video doesn't hang anymore when seeking but when I quit mpv after seeking in the video the assert is always triggered. If I don't seek the assert just play it the assert doesn't trigger.

**Comment by syncrond** [comment]
Sorry but it's the same as with the other patch, mpv doesn't show a frame and immediately hangs with any video.
log: https://0x0.st/-haY.txt

**Comment by haasn** [comment]
Okay that really shouldn't be happening. Report to driver devs I guess?

**Comment by lavilao** [comment]
see if this helps  ```export ANV_QUEUE_THREAD_DISABLE=1```

**Comment by syncrond** [comment]
OK I had some time to test again and I realized your last patch only hangs with kernel 5.11 but not with 5.15. With 5.15 it works!
So I think using a bleeding edge mesa 22.0 with a stock Ubuntu 20.04.3 linux 5.11 kernel is not a good idea and leads to weird errors.
I think I won't follow that error.

That leaves the bug that the assertion is triggered when quitting after seeking (which works) while using an updated 5.15 kernel (without the patch):

```
[cplayer] EOF code: 5  
mpv: ../video/out/vo_gpu_next.c:168: free_dr_buf: Assertion `memcmp(dr->sentinel, dr_magic, sizeof(dr_magic)) == 0' failed.
Aborted
```

It works (no assertion is triggered) when using @haasn 's last patch.

Logfile with your patch applied: https://0x0.st/-hnT.txt
It also prints to the console:
```
!!! libplacebo: leaked 9217536 bytes of vulkan memory
!!! slab total size: 9225216 bytes, heap: 0, flags: 0xF
!!! libplacebo: leaked 18435072 bytes of vulkan memory
!!! slab total size: 18450432 bytes, heap: 0, flags: 0xF
!!! libplacebo: leaked 18435072 bytes of vulkan memory
!!! slab total size: 36900864 bytes, heap: 0, flags: 0xF
```

But I guess this is what you expected.

@haasn should I change the issue title and description or open a new one for following the assert issue with kernel 5.15?
Or just follow on in the issue?
Or do you still think I should report it to mesa?

@lavilao thanks but unfortunately `export ANV_QUEUE_THREAD_DISABLE=1` doesn't help.

**Comment by lavilao** [comment]
@syncrond sorry I could not help, btw small question. How did you do for the vo=gpu-next to work? did you download the binary from somewhere or you compile it yourself? I am currently using mpv-full-0.34 from aur and gpu-next is not present, I am having to use the windows version to try it through wine... that feels bad.

**Comment by haasn** [comment]
Wild stab in the dark, does this help at all?

```diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index d6e9cffd1f..9a58c4bcef 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -183,7 +183,7 @@ static struct mp_image *get_image(struct vo *vo, int imgfmt, int w, int h,
         return NULL;
 
     pl_buf buf = pl_buf_create(gpu, &(struct pl_buf_params) {
-        .size = size + stride_align + sizeof(struct dr_buf) + dr_align,
+        .size = size + stride_align + sizeof(struct dr_buf) + dr_align + 4096,
         .memory_type = PL_BUF_MEM_HOST,
         .host_mapped = true,
     });
```

**Comment by syncrond** [comment]
@haasn No, same behaviour.

@lavilao I compile mpv (using [mpv-build](https://github.com/mpv-player/mpv-build.git))

**Comment by lavilao** [comment]
@syncrond thanks for the info

**Comment by gunnarmarten** [comment]
Just for the record commit 7f67a553 fixed the issue for me as does the current HEAD.
Back then I couldn't find a better sample so its good someone found a reproducible sample for the issue and it could be fixed.
Thank you!
