### ISSUE TITLE
[MacOS] After video finishes, music.app gets launched and autoplay the first thing it can.

### ISSUE THREAD

**Issue by choule99** [mpv-player/mpv#9527]
### Important Information

Provide following Information:
- mpv version: **0.34.0**
- macOS Version: **12.0.1**
- Source of the mpv binary or bundle: **Homebrew**
- If known which version of mpv introduced the problem: **Started on macOS Monterrey, MPV 0.32.0, originally installed by IINA, but then upgraded to the latest MPV using homebrew**
- Possible screenshot or video of visual glitches: **None**

### Reproduction steps
- In a terminal: `brew install mpv`
- In a terminal: `mpv file.mp4 --no-config`
- Watch it until the end
- Wait a few seconds, the `Music.app` launch, and start playing whatever is in the current playlist

### Expected behavior
`Music.app` does not launch

### Actual behavior
`Music.app` launch, and start playing stuff randomly.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/7610799/output.txt)

### Sample files
Any video will do.

**Comment by Akemi** [comment]
are you sure you are not using any other software that could influence this?

if i would take a guess the most likely reason is the media player support. which was introduced in 0.31 (https://github.com/mpv-player/mpv/commit/a32db637b5c66c0304147caadf02d7b28083bcee#diff-2e3df7e674a9f01c88300fcdfeb709bfd1f190a8ce5ba04e249bf49b2fd2ec8d). is 0.32 the earliest version you could reproduce it with, or did you not try 0.31? please try it with vanilla mpv and not the one in iina. if it's media player support related then this is deactivated in iina anyway and it's using its own media player support, which could also cause the problem.

if you can build it yourself try with --disable-macos-media-player on configure.

it could also be related to the playback state https://github.com/mpv-player/mpv/commit/695d850412144629827bdea146e6bf4bbeba39ed#diff-2e3df7e674a9f01c88300fcdfeb709bfd1f190a8ce5ba04e249bf49b2fd2ec8d.

**Comment by choule99** [comment]
I already have installed mpv directly through homebrew, version 0.34 and have the same issue. 
 
Something in mpv is instructing macos to playback, if there is a safari opened on YouTube, after mpn finish playing, it will autoplay whatever video is paused on YouTube

**Comment by Akemi** [comment]
> I already have installed mpv directly through homebrew, version 0.34 and have the same issue.

no one said you didn't with 0.34 but you wrote, before you edited your initial post, "Started on macOS Monterrey 12.0.0, using MPV 0.32.0, as packaged by IINA". so please try the earlier versions with vanilla mpv and not through iina.

> Something in mpv is instructing macos to playback, if there is a safari opened on YouTube, after mpn finish playing, it will autoplay whatever video is paused on YouTube

yes, you described your issue already. no, mpv does not instruct anything else to start playing directly. in theory it could >restart< something else that was playing while taking priority (restoring the previous state), but that is entirely in the hands of the OS. since it started with 12.0 it's more likely that Apple changed the API behaviour (which would be a dick move) or there is a bug in 12.0.1.

**Comment by choule99** [comment]
Sorry my original bug report misled you. Which is why I edited in the 1st place, better clarity. Sorry if that offended you in any way), I only tried to supply relevant information as _requested_ by the template. 

Here is my viewpoint:
- The problem started when using IINA on macos Monterrey 12.0.1, which uses mpv `0.32.x` (At least as of this writing.) 
- But as stated in the original bug report, I also installed mpv `0.34.0` through `homebrew`, to see if that was an isssue fixed in newer version of mpv. 
- As of this writing, the problem can be witnessed using mpv `0.34.0`, without any wrapper, through the command-line interface, without any other software involved.

Finally, I do not _care_ if the bug is a change in mpv or a change in the macos api, I am only interested in a solution. Realistically, even if _Apple_ changed the API, and it is a _dick-move_, it is still a bug, we won't be able to force Apple to fix it unless it is a generalized problem with media playing on the platform.

However, I have tried another media player (i.e.: VLC), and it does not have this behavior, which leads me to conclude that it is a problem specific to mpv.

Back to my original thinking in filling the bug-report, there is an issue with the mpv-macos integration layer, which may originate from a change in macos monterrey. It is most probably Apple's fault, but it is a bug I believe that should/could be fixed in mpv.

I am sorry Apple changed the API under your collective feet, but we've got to roll with the punches, and fix it. 

I will checkout the code, try to make sense of it (even though this is far away from my area of expertise in terms of coding)

But if people with the proper technical knowledge, and with the knowledge of mpv inner workings were looking at it, I believe how chances of success would much higher.

Thank you!

**Comment by Akemi** [comment]
if you want to move forward please don't repeat yourself. i don't want to read a wall of text. i just want you to do what i asked you to do and if you can't just say so. i didn't ask you to check out the code.

i told you the facts. i don't care if you care about them or not.

VLC uses a different old deprecated api. if that is the reason of the problem, then it doesn't matter if VLC works.

i am the one who wrote that code and i am willing to look into it, but you have to at least do what i told you to make my work a bit easier.

**Comment by choule99** [comment]
Please do.

I believe I have given enough information already.

**Comment by CounterPillow** [comment]
@choule99 you want the bug fixed (if it is a bug in mpv in the first place), it's only reasonable that you are the one who provides all the information to the person who is willing to spend their free time for you by investigating it, namely the information they ask for, not whatever information is convenient for you to provide. By not doing this, you're actively shooting yourself in the foot.

**Comment by choule99** [comment]
@CounterPillow Sorry, but I filled the template to the best of my abilities. Sorry it's not up to snuff.

**Comment by choule99** [comment]
> if you want to move forward please don't repeat yourself. i don't want to read a wall of text. i just want you to do what i asked you to do and if you can't just say so

Just trying to give you all the information I can possibly can. Sorry for the inconvenience.

> i didn't ask you to check out the code.

To _build_ mpv, I kinda have to checkout the code, especially to try ` --disable-macos-media-player `.

> i told you the facts or my viewpoint. 

And I told you mine. 

> i don't care if you care about them or not.

Was that really necessary? Why the hostility here?

> VLC uses a different old deprecated api. if that is the reason of the problem, then it doesn't matter if VLC works.

Just trying to give you more insights into the troubleshooting I did.

> are you sure you are not using any other software that could influence this?

As stated, using `mpv` directly from the command-line, like instructed in the template (`--no-config`) 

> if you can build it yourself try with --disable-macos-media-player on configure.

Built it with `--disable-macos-media-player`, and the problem went away.


**Conclusion:**
There is a bug on mpv media-player integration on macos monterrey 12.0.1

**Comment by Akemi** [comment]
> To _build_ mpv, I kinda have to checkout the code, especially to try `--disable-macos-media-player`.

no. you 'just' have to pass the argument to configure. 

> And I told you mine.
> Was that really necessary? Why the hostility here?

you told me you don't care. so i gave that right back to you. was your hostility really necessary in the first place then?

> Built it with `--disable-macos-media-player`, and the problem went away.
> **Conclusion:** There is a bug on mpv media-player integration on macos monterrey 12.0.1

we could have established that much earlier if you hadn't ignored my requests and questions. that's not the right conclusion. like i said before it can be an OS bug, an API behaviour change, still some other software interfering with it or lastly a misuse of the API.

i am done with charade. comments closed.
