### ISSUE TITLE
doesn't see the audio track

### ISSUE THREAD

**Issue by WqR128** [mpv-player/mpv#9533]
### Important Information

- mpv 0.34.0-31-gc478a1efba (by shinchiro)
- Windows Version 19042.1348
- Source of the mpv binary https://sourceforge.net/projects/mpv-player-windows/files

![изображение](https://user-images.githubusercontent.com/20769035/143734738-d8ff49d4-3d20-4a41-987b-7b93f2a56115.png)

#### ffmpeg.exe -i

> Input #0, matroska,webm, from '[AniStar.org] Detective Conan - 1027 [720p].mkv':
>   Metadata:
>     encoder         : libebml v1.4.2 + libmatroska v1.6.4
>     creation_time   : 2021-11-20T14:07:00.000000Z
>   Duration: 00:24:52.86, start: 0.000000, bitrate: 2275 kb/s
>     Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
>     Metadata:
>       BPS             : 2080655
>       DURATION        : 00:24:52.825000000
>       NUMBER_OF_FRAMES: 35792
>       NUMBER_OF_BYTES : 388256842
>       _STATISTICS_WRITING_APP: mkvmerge v60.0.0 ('Are We Copies?') 64-bit
>       _STATISTICS_WRITING_DATE_UTC: 2021-11-20 14:07:00
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:1(eng): Audio: mp1, 48000 Hz, stereo, s16p, 192 kb/s (default)
>     Metadata:
>       BPS             : 192000
>       DURATION        : 00:24:52.856000000
>       NUMBER_OF_FRAMES: 186607
>       NUMBER_OF_BYTES : 35828544
>       _STATISTICS_WRITING_APP: mkvmerge v60.0.0 ('Are We Copies?') 64-bit
>       _STATISTICS_WRITING_DATE_UTC: 2021-11-20 14:07:00
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

### Expected behavior
normal video playback with sound

### Actual behavior
the sound does not play

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/7613041/output.txt)
### Sample files

[video file](https://drive.google.com/file/d/1or7kFdVaAykjYx56ffvAFzmtgext_Ogv/view?usp=sharing)

**Comment by garoto** [comment]
Workaround is to force ffmpeg's matroska demuxer for this file only:

`mpv --demuxer=lavf "[AniStar.org] Detective Conan - 1027 [720p].mkv"`

**Comment by WqR128** [comment]
The workaround works fine

**Comment by garoto** [comment]
On related news, how can MP1 be a format that dummy ruskies accept as valid, lol.
