### ISSUE TITLE
[vo=gpu-next] Error opening/initializing the selected video_out (--vo) device.

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9534]
### Important Information

Provide following Information:
- mpv version [0.34.0-89-gf08db00d26](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20211128-git-f08db00.7z/download)
- Windows Version 10 Pro 21H1 19043.1348
- Source of the mpv binary [sourceforge shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/)
- If known which version of mpv introduced the problem: Yes - [0.34.0-89-gf08db00d26](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20211128-git-f08db00.7z/download)
last version was OK: [ 0.34.0-31-gc478a1efba](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20211114-git-c478a1e.7z/download)

### Reproduction steps
`mpv --no-config --vo=gpu-next`

### Expected behavior
MPV will open

### Actual behavior
MPV crash

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/7613366/log.txt)

**Comment by ObsessedHacker** [comment]
By what I can tell from the log - apparently `gpu-context=auto` (default) is trying to use `gpu-context=d3d11` which results in a crash.
My guess it's because `vo=gpu-next` doesn't support `gpu-context=d3d11` yet? I'm not sure.

Anyway, temporary fix is `gpu-context=winvk`

**Comment by haasn** [comment]
Ideal fix would be to support d3d11 contexts, cc @rossy @JEEB

**Comment by hooke007** [comment]
My local cache told me the last safe commit is 2b2442e.
It may be introduced by the commit about implement OpenGL context support

**Comment by yeezylife** [comment]
In my opinion,d3d11 is still the best choice for windows user,hope it get implemented soon.

**Comment by sfan5** [comment]
> My local cache told me the last safe commit is [2b2442e](https://github.com/mpv-player/mpv/commit/2b2442ee67913221e5c87cbc06010671e1b41c15). It may be introduced by the commit about implement OpenGL context support

Before the OpenGL commit, vo_gpu_next always forced Vulkan regardless of what `gpu-api` or `gpu-context` were set tho.
It now honors those settings and absence of d3d11 support isn't really a bug.

**Comment by Hrxn** [comment]
> In my opinion,d3d11 is still the best choice for windows user,really hope it could get implemented soon.

Why? If there's anything wrong with `gpu-context=winvk`, the proper course of action would be to fix this, I think..

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/8902 someone think vulkan under win is not as stable as dx.

**Comment by Hrxn** [comment]
Hence "ought to be fixed" 😅

**Comment by ValZapod** [comment]
> someone think vulkan under win is not as stable as dx.

Well, fir me 2080 ti vulkan + nvdec eas so much better than anything else. Buf i tuned vulkan with zero copy and other stuff. I nowadays watch only Dolby Vision and mostly on c9.

**Comment by Obegg** [comment]
Fixed, closing now.

**Comment by brian6932** [comment]
This seems to be back?
