### ISSUE TITLE
gpu-api=vulkan+SSimDownscaler makes some video blurier

### ISSUE THREAD

**Issue by yeezylife** [mpv-player/mpv#9543]
### Important Information

Provide following Information:
- mpv version:Pulled from master Github branch(with igv's latest SSimDownscaler)
- Platform and Version:win11
- Source of the mpv binary:shinchirol's toolchain

### Reproduction steps
`no-config`
`vo=gpu-next`
`gpu-api=vulkan`
`gpu-context=winvk`
`glsl-shaders="~~/shaders/SSimDownscaler.glsl"`
`dscale=spline16`
`--log-file=gpu-next.log`

### Expected behavior
The results would be roughly the same(with vo=gpu and vo=gpu-next).

### Actual behavior
The dark lines in the anime become thicker(also blurer) and you can see "gliches" around the edge.

### Sample files
vo=gpu  SSIMdownscaler  dscale=spline16
![vo=gpu-ssimdownscaler-dscale=spline16](https://user-images.githubusercontent.com/30175425/144046977-7cf2d832-4685-4e94-a95a-8e9305efd3db.png)

vo=gpu-next  SSIMdownscaler  dscale=spline16
![GPU-NEXT-SSIMdownscaler-dscale=spline16](https://user-images.githubusercontent.com/30175425/144046929-6e6024ec-cd91-4542-9823-02396917b599.png)

vo=gpu-next  With No Shader  dscale=spline16
![GPU-NEXT-NoShader-Dscale=spline16](https://user-images.githubusercontent.com/30175425/144046871-4971bb24-42a6-4580-a6e6-5e221173b208.png)

As you can see in the third screenshot,when I removed SSIMdownscaler,just use dscale=spline16 and `vo=gpu-next` ,the thicker dark lines and "gliches" are gone. 

### Log file
[gpu-next.log](https://github.com/mpv-player/mpv/files/7626475/gpu-next.log)

**Comment by hooke007** [comment]
some shaders works differently after one commit of libplacebo.
https://github.com/mpv-player/mpv/issues/9505#issuecomment-980427736
You could check if it only happens at paused stat or try the earily version I mentioned.

**Comment by yeezylife** [comment]
> some shaders works differently after one commit of libplacebo.  You could check if it only happens at paused stat or try the earily version I mentioned.

I've read this already,so I've tested taking screenshot while playing,Same results with vo=gpu-next SSIMdownscaler dscale=spline16.

**Comment by yeezylife** [comment]
Tested a earilier version from 10 days ago,same problem.

**Comment by haasn** [comment]
Hi, I can't reproduce this on my end - I get the same results from your command line whether from `--vo=gpu` or `--vo=gpu-next`, paused or unpaused. Can you try giving me the exact source file so I can see which screenshot it matches up to?

**Comment by yeezylife** [comment]
I tested again, this only happens with this exact file.
I can't reproduce with other file but only with this one it's 100％.
I'm uploading this file to google drive then sending to your email...
Screenshot time (Tengen Toppa Gurren Lagann E23) 00:14:13

**Comment by yeezylife** [comment]
https://drive.google.com/file/d/153cBV_gDhaTL15L7hi7Qm3aDoZskOgF9/view?usp=sharing

**Comment by Natural-Harmonia-Gropius** [comment]
use `scale=gaussian` with ssimd shader for a still image that pixelformat is `grey` will be visibly blurred.

> Ringing artifacts not perceivable with gamma light. And, after the latest update, SSimDownscaler blurs them instead of over-sharpening.

maybe its the issue of ssimd since this. I will do more tests in weekend.

**Comment by yeezylife** [comment]
> maybe its the issue of ssimd since this. I will do more tests in weekend.

But it works fine with vo=gpu.(Of cause now I know the problem only happens when using vo=gpu-next+SSIMdownscaler with this perticular file)

**Comment by Natural-Harmonia-Gropius** [comment]
I think it's a issue of ssimd.

use `scale=gaussian glsl-shader=~~/shaders/SSimDownscaler.glsl`,  the result mostly blurred and some parts being sharper, same results with gpu or gpu-next. not that visible but this happens to all kind of images, some sharp area becomes blurry.
![image](https://user-images.githubusercontent.com/50797982/144585648-4e9b67c7-0549-4984-a9c8-064764530c19.png)
source image
![2](https://user-images.githubusercontent.com/50797982/144585509-d3b5e621-6e2d-46b5-b0dd-5d2867c1ce7a.jpg)

**Comment by igv** [comment]
Still can't reproduce with any image/video/vo.
Try this patch:
```
@@ -150,7 +150,7 @@
 
     float Sl = Luma(max(avg[1] - avg[0] * avg[0], 0.)) + sigma_nsq;
     float Sh = Luma(max(avg[2] - avg[0] * avg[0], 0.)) + sigma_nsq;
-    return vec4(avg[0], sqrt(Sh / Sl));
+    return vec4(avg[0], 1.0 / (1.0 + sqrt(Sh / Sl)));
 }
 
 //!HOOK POSTKERNEL
@@ -182,7 +182,8 @@
         float w = Kernel(rel);
 
         vec4 MR = MR_tex(pos);
-        avg += w * mat3x3(MR.a*MR.rgb, MR.rgb, MR.aaa);
+        vec3 R = vec3(1.0 / MR.a - 1.0);
+        avg += w * mat3x3(R*MR.rgb, MR.rgb, R);
         W += w;
     }
     avg /= W;
```

**Comment by Natural-Harmonia-Gropius** [comment]
still blurry
![image](https://user-images.githubusercontent.com/50797982/144595729-bbd79908-3633-4c05-8c34-9ea6a052f26d.png)
![image](https://user-images.githubusercontent.com/50797982/144595743-1a2a1607-eceb-4277-823b-bd7d8887fff7.png)

**Comment by yeezylife** [comment]
> Still can't reproduce with any image/video/vo. Try this patch:
Even with that file I upload? I can 100％ly reproduce with that file(using my testing command line). Weird...

**Comment by Natural-Harmonia-Gropius** [comment]
Strangely, I got sharper image from `gpu-api=d3d11` and blurry from `gpu-api=vulkan`. and change gpu-api in terminal did nothing, only change from mpv.conf works.

and some errors shown when toggle ssimd with `gpu-api=d3d11`.
![image](https://user-images.githubusercontent.com/50797982/144596920-f63e6aed-12ca-4f81-b6a6-b4211440629a.png)

**Comment by yeezylife** [comment]
Hi igv, I tested your patch and it worked!!!  Same results here!!!

**Comment by hooke007** [comment]
Eh it is quite strange. Even no patch I cannot reproduce the blur.

**Comment by yeezylife** [comment]
I'm literaly testing right now,you can see no patched SSIMD still blurrier.
![blur ones](https://user-images.githubusercontent.com/30175425/144598793-ba2f7d5a-8bc8-4e73-9f2e-f6e20e23e2f7.jpg)

**Comment by igv** [comment]
@yeezylife 
> I tested your patch and it worked!!! Same results here!!!
 
That means out-of-range values aren't supported by your GPU drivers. You may also have issues with HDR because of that.

@Natural-Harmonia-Gropius, I didn't test vulkan, only opengl (currently on Intel iGPU, Mesa 21.3)

**Comment by yeezylife** [comment]
No patched blurrier one.
![44444444](https://user-images.githubusercontent.com/30175425/144599669-2463defa-c293-4e7c-baa0-fe3b29b1014e.png)

> That means out-of-range values aren't supported by your GPU drivers. You may also have issues with HDR because of that.

But with vo=gpu that's OK, maybe because gpu-next uses vulkan.
I'm using latest win11 with a GTX2060...

**Comment by yeezylife** [comment]
And I can only reproduce this with this particular video,If it's a driver problem shouldn't I be able to  reproduce this with every video?

**Comment by hooke007** [comment]
@igv I tested three recent versions of ssimd
--vo=gpu-next --gpu-api=vulkan
device: rtx 2070s

Oct 9, 2021 sharp-----------------------------Nov 20, 2021 blur-----------------------------Dec 3, 2021 blur
<img src="https://user-images.githubusercontent.com/41094733/144601288-3e0ec29d-39b3-4fab-b562-922145392fe5.jpg" width="240"> <img src="https://user-images.githubusercontent.com/41094733/144601302-12624f62-fd98-41c0-8dcd-02daf23c6934.jpg" width="240"> <img src="https://user-images.githubusercontent.com/41094733/144601305-391be1f8-f9e7-4f2c-b535-61cc15cb0174.jpg" width="240">

**Comment by yeezylife** [comment]
I get it now,like igv said! Out-of-range values bugged by my GPU drivers.But only with vulkan,and only reproducable with certain videos.
This should be a vulkan on windows driver problem, not a vo=gpu-next problem!

**Comment by igv** [comment]
@hooke007 and I still can't reproduce with any version of ssimd even under vulkan...
It must be Windows+vulkan (+some GPUs) issue only.

**Comment by yeezylife** [comment]
And certain videos!  I even tested similar Images. Dark lines on  a blue background.
Same results with this one.

vo=gpu  (using d3d11)
![gpu2](https://user-images.githubusercontent.com/30175425/144604077-de1fa016-18f0-4a59-887e-c1640d1a91f1.jpg)
vo=gpu-next (using vulkan)
![gpu-next2](https://user-images.githubusercontent.com/30175425/144604116-39795fb6-8e4f-405b-8355-d4d0d843f8d9.jpg)

And some other videos,most can't reproduce.

**Comment by Natural-Harmonia-Gropius** [comment]
> @hooke007 and I still can't reproduce with any version of ssimd even under vulkan... It must be Windows+vulkan (+some GPUs) issue only. @Natural-Harmonia-Gropius do you also use nVidia GPU?

yes rtx3080 with driver version 496.98

**Comment by yeezylife** [comment]
Would this patch works for futrue version of SSimDownscaler? I mean you just revised SSimDownscaler 1 hour ago...

**Comment by yeezylife** [comment]
And does SSIMsuperres and Krig uses "out-of-range values"? If so...I guess I'll just say goodbye to vulkan..

**Comment by igv** [comment]
> And does SSIMSuperres and Krig uses "out-of-range values"? If so...I guess I'll just say goodbye to vulkan...

No, but...

> @igv I tested three recent versions of ssimd --vo=gpu-next --gpu-api=vulkan device: rtx 2070s
> 
> Oct 9, 2021 sharp-----------------------------Nov 20, 2021 blur-----------------------------Dec 3, 2021 blur 

... if this is true, then it means the issue appeared when I removed clamps from inputs, in that case you may have any kind of weirdness with almost any shader...

**Comment by yeezylife** [comment]
> ... if this is true, then it means the issue appeared when I removed clamps from inputs, in that case you may have any kind of weirdness with almost any shader...

What?! I thought changing to gpu-api=d3d11 solves everything...

**Comment by igv** [comment]
...under vulkan+nVidia...

**Comment by yeezylife** [comment]
> @igv I tested three recent versions of ssimd --vo=gpu-next --gpu-api=vulkan device: rtx 2070s
> 
> Oct 9, 2021 sharp-----------------------------Nov 20, 2021 blur-----------------------------Dec 3, 2021 blur

Reproduced this by the way.Oct 9, 2021 version of SSIMD stays sharp with vulkan.

**Comment by yeezylife** [comment]
> > @igv I tested three recent versions of ssimd --vo=gpu-next --gpu-api=vulkan device: rtx 2070s
> > Oct 9, 2021 sharp-----------------------------Nov 20, 2021 blur-----------------------------Dec 3, 2021 blur
> 
> ... if this is true, then it means the issue appeared when I removed clamps from inputs, in that case you may have any kind of weirdness with almost any shader...

But I tested Krig and Superres with vulkan/d3d11 and get identical results.
Well it's a strange problem anyway...

**Comment by igv** [comment]
I fixed this. Turned out there is something wrong with pow instruction (if first parameter isn't clamped/absed) under vulkan + Nvidia.

**Comment by yeezylife** [comment]
igv actually fixed a bug he can't even reproduce,and he answers my questions every time,igv is the best!

**Comment by yeezylife** [comment]
d3d11
![gpu-d3d11](https://user-images.githubusercontent.com/30175425/147638984-34e43986-bec3-4537-849c-d4d82039d507.png)
vulkan
![gpu-next-vulkan](https://user-images.githubusercontent.com/30175425/147639027-5c08bbbb-3a57-43d6-80b0-700b1a84bddc.png)
d3d11
![gpu (2)](https://user-images.githubusercontent.com/30175425/147639100-81486d44-f1d5-4b84-8b1f-52953d8102c7.png)
vulkan
![gpui-next (2)](https://user-images.githubusercontent.com/30175425/147639127-faf02e63-0ff7-4135-af08-1b87cd0d1f2a.png)

Done some testing,now SSIMD gives identical results (under windows+nvidia+vulkan)for dark lines and grains.All fixed!Thanks again!
