### ISSUE TITLE
How to use referer?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9545]
This does work but

`
yt-dlp --no-config --referer "https://gogoplay1.com/download?id=MTc1MTg2&typesub=Gogoanime-SUB&title=Platinum+End+Episode+8" "https://cdn21.anicdn.stream/user1342/445046b34d6a7224930d7bf02980382f/EP.8.v0.1080p.mp4?token=kcU_RQoWr8bchwHuTf9gPA&expires=1638463975&id=175186" -F                                            
[generic] EP.8.v0.1080p: Requesting header
[info] Available formats for EP.8.v0.1080p:             
ID  EXT RESOLUTION │ PROTO │ VCODEC  ACODEC             ──────────────────────────────────
mp4 mp4 unknown    │ https │ unknown unknown
`

in mpv.conf this doesn't work? 

`
ytdl-raw-options="[referer]=https://gogoplay1.com/download?id=MTc1MTg2&typesub=Gogoanime-SUB&title=Platinum+End+Episode+8"
`

player closes when I paste the link?

**Comment by guidocella** [comment]
youtube-dl isn't used to play regular mp4 URLs. Use `mpv --referrer='https://gogoplay1.com/download?id=MTc1MTg2&typesub=Gogoanime-SUB&title=Platinum+End+Episode+8' 'https://cdn21.anicdn.stream/user1342/445046b34d6a7224930d7bf02980382f/EP.8.v0.1080p.mp4?token=kcU_RQoWr8bchwHuTf9gPA&expires=1638463975&id=175186'`

**Comment by erickyun** [comment]
> youtube-dl isn't used to play regular mp4 URLs. Use `mpv --referrer='https://gogoplay1.com/download?id=MTc1MTg2&typesub=Gogoanime-SUB&title=Platinum+End+Episode+8' 'https://cdn21.anicdn.stream/user1342/445046b34d6a7224930d7bf02980382f/EP.8.v0.1080p.mp4?token=kcU_RQoWr8bchwHuTf9gPA&expires=1638463975&id=175186'`

Thank you it worked in my pc but how can I use referer in mpv.conf?
I'm trying to use --referer in mpv android?

```
mpv --referrer="https://gogoplay1.com/download?id=MTc1MTg2&typesub=Gogoanime-SUB&title=Platinum+End+Episode+8" "https://cdn21.anicdn.stream/user1342/445046b34d6a7224930d7bf02980382f/EP.8.v0.1080p.mp4?token=kcU_RQoWr8bchwHuTf9gPA&expires=1638463975&id=175186"
```
