### ISSUE TITLE
reverse colors

### ISSUE THREAD

**Issue by schachmat** [mpv-player/mpv#955]
I would like to watch lecture recordings with inverted colors since
- my screen burns in bright colors
- the contrast between video (bright white) and terminal (dark) is quite annoying

So far I did not find an mpv option that allows me to watch videos with reverse colors.

**Comment by japrogramer** [comment]
hey guys, this is better
```
$mpv --vf=sub,lavfi="negate" $(xclip -o | awk "{print $1}")
```

**Comment by PhilipKigo** [comment]
To negate colors for better visibility use the flag vf-lavfi=[negate]
To negate all videos edit  .config/mpv/mpv.conf using a text editor like nano/vim/kwrite/gedit and paste that flag. 
To negate one video on the commandline use mpv --vf-lavfi=[negate] <videofile>

**Comment by egils-consulting** [comment]
help to search engines: how to invert colors in mpv
mpv --vf-lavfi=[negate] <videofile>

**Comment by arbitrary-dev** [comment]
Also, to toggle with `I` key in the player itself:
```
$ cat .config/mpv/input.conf
I cycle-values vf "sub,lavfi=negate" ""
```

**Comment by egils-consulting** [comment]
@arbitrary-dev Could you add that to the bottom of the FAQ?

**Comment by Akemi** [comment]
that's nothing for the FAQ.
