### ISSUE TITLE
Videos lagging hard on mpv

### ISSUE THREAD

**Issue by vinraghav** [mpv-player/mpv#9560]
I'm trying to play two videos first one is 1080p@144 fps and second is 4k@60 fps. They both are lagging hard. Both the videos play smoothly on my phone which has lower end hardware compared to my PC which has a graphics card. This is by no means a hardware issue because I can play 4k60 HDR videos on YouTube on browser without any lagging using the same PC.

OS: Ubuntu 20.04 
Specs: i5 8365u, RX 6800, 12 GB ram

**Comment by CounterPillow** [comment]
Press ctrl+h

**Comment by Dudemanguy** [comment]
Likely just need to enable hardware decoding.
