### ISSUE TITLE
Linking errors during mpv build on Fedora 35

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#9563]
### mpv version and platform versions

Latest ffmpeg and mpv git versions as of creation of this issue.
OS: Fedora 35 KDE Spin

### Reproduction steps

1. Install dependencies of ffmpeg and mpv through package manager.
2. Build ffmpeg with shared library.
3. Build mpv with shared library.

### Expected behavior

Build goes without issue.

### Actual behavior

Linking error with some libraries, particularly asound and lcms2, even though both are installed and available through the package manager.

### Log file

waf configure: https://0x0.st/-hDA.txt
waf: https://0x0.st/-hDm.txt

**Comment by kkanungo17** [comment]
Okay so it was my distro screwing up, for whatever reason only 32-bit versions of the dependency libraries were installed. Had to manually install the 64-bit versions too.

**Comment by jeeb** [comment]
Yea, the asound errors in there with linking were weird, which made me think there was an architecture mismatch somewhere between the compiler/linker/library:
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/11/../../../libasound.so when searching for -lasound
/usr/bin/ld: skipping incompatible /lib/libasound.so when searching for -lasound
/usr/bin/ld: skipping incompatible /usr/lib/libasound.so when searching for -lasound
/usr/bin/ld: cannot find -lasound
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/11/../../../libasound.so when searching for -lasound
/usr/bin/ld: skipping incompatible /lib/libasound.so when searching for -lasound
/usr/bin/ld: skipping incompatible /usr/lib/libasound.so when searching for -lasound
collect2: error: ld returned 1 exit status
```

Glad you got that figured out.
