### ISSUE TITLE
Tone Mapping: Handling of wrong values (false colors)

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9564]
There are some movies which contain illegal YCbCr values. The tone mapping of MPV shows completely wrong colors in this case. Other renderers like madVR or 3D LUT from DisplayCAL don't. Here is an example:

"Mad Max: Fury Road", time code: 00:10:43.

madVR:
![image](https://user-images.githubusercontent.com/95616074/144840685-ab055a81-e7a6-4993-b6bb-f37eae6888b3.png)

MPV (BT.2390):
![image](https://user-images.githubusercontent.com/95616074/144840713-4beed54c-f1c2-447b-b8e7-f411ddf87a27.png)

I could not find any parameter that solves this problem. Is it possible to handle wrong values in a tolerant way?

PS: the green spear in "Batman vs. Superman" has equal problems.

**Comment by FoLLgoTT** [comment]
Shall I provide anything for analyzing?

The problem is obvious with default settings.

**Comment by haasn** [comment]
A sample would be useful.

**Comment by haasn** [comment]
Ah, yes, the infamous sample where the problem is that, essentially, this is the color the sample is actually stored with. An easy work-around here is `--tone-mapping-desaturate=1 --tone-mapping-desaturate-exponent=0`, which is probably what madVR is doing under the hood as well. YMMV.

FWIW I'm in the process of completely redesigning the way tone mapping works in libplacebo (and thus `--vo=gpu-next`), so expect this stuff to change soon-ish anyway.

That said, what do you mean by "illegal YCbCr values"?

**Comment by FoLLgoTT** [comment]
Thank you I will try it. I read from madshi somewhere that these parts of the picture contains illegal YCbCr values that cannot be converted correctly to RGB (e.g. a color with 10,000 Nits). But I didn't analyzed them in detail.

Good news about yout redesign. I could provide more scenes which are problematic in the current implementation. I noticed while comparing to madVR that the brightnes doesn't stay that constant. There are some scenes which should be very bright, but look rather dull. And other scenes which have blown out highlights.

Just tell me if I can support you with testing and samples. :-)

At the current state MPV is very interesting for people who want to switch to Linux or who wants to have an alternative to madVR. If the last drawbacks would be improved that would help much for MPV's popularity.

**Comment by NSQY** [comment]
Mad Max is a notoriously difficult sample which we have covered here in the past, Vincent has some measurements: https://youtu.be/cMaG21W_sr4?t=278

**Comment by quietvoid** [comment]
State of things: https://slow.pics/c/7qTUgWNc

I can't personally reproduce the super blue highlight at all like the issue screenshots.

**Comment by haasn** [comment]
The new default curve should handle files like this a lot better.
