### ISSUE TITLE
[vo=gpu-next] --target-peak is ignored

### ISSUE THREAD

**Issue by epicfilmmaker93** [mpv-player/mpv#9566]
### Important Information

Tested on Windows and Linux, Reinhard and BT.2390, latest mpv built from git, latest libplacebo built from git

### Reproduction steps

Add --target-peak to mpv.conf when --vo=gpu-next is used

### Expected behavior

--target-peak modifies the image

### Actual behavior

Nothing happens

### Sample files

https://www.youtube.com/watch?v=LXb3EKWsInQ

**Comment by haasn** [comment]
Hi, sorry for the delay, I only just remembered what's going on. `--target-peak` no longer does anything for SDR curves in libplacebo, a deliberate design decision. (For SDR, 1.0 is defined to be the target peak, so to adjust the brightness of the display you should be adjusting the brightness controls on your display)

This functionality is still available (as the orthogonal `target-scale` setting), but I forgot to add an option for it. Will fix. (That said, I will also completely overhaul HDR tone mapping in libplacebo very soon, so I'll defer this until that's done, in case it's no longer needed)

**Comment by epicfilmmaker93** [comment]
Sorry, maybe I'm confusing something, but I was talking about HDR videos

**Comment by haasn** [comment]
I think this should be fixed with the new tone mapping stuff? `target-peak` now behaves more like it used to, iirc
