### ISSUE TITLE
MPV spawns pulseaudio with --ao=alsa

### ISSUE THREAD

**Issue by mrnoname1000** [mpv-player/mpv#9567]
### Important Information

Provide following Information:
- mpv version: 0.34.0
- Linux Distribution and Version: Gentoo ~amd64
- Source of the mpv binary: Built by Portage
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: i3 4.20.1
- GPU driver and version: mesa 21.3.1 (radeonsi)
- Possible screenshot or video of visual glitches

### Reproduction steps

Install pulseadio, play a file with audio with `mpv --no-config --ao=alsa`.

### Expected behavior
mpv successfully plays the audio using alsa.

### Actual behavior
mpv spawns pulseaudio before trying alsa, causing the audio device to be busy and disabling audio. Pulseaudio later exits (because it isn't being used?), allowing mpv to begin audio playback if manually switched.

### Log file

[mpv --log-file](https://github.com/mpv-player/mpv/files/7663331/mpv.log)
[strace --follow-forks -e execve](https://github.com/mpv-player/mpv/files/7663328/strace.log)

**Comment by jeeb** [comment]
All of the pulse related calls should be within `ao_pulse` and if you look at spawning such a process the mpv code base is not doing that at all. So if something is causing this, it is because something that is actually being called by mpv causes pulse to be kicked, which then in turn causes it to start up.

I would check the output of
```
mpv -audio-device=help
```
that should output the available audio devices for the various AO APIs, which might or might not shed some extra info on the state of affairs.

**Comment by mrnoname1000** [comment]
I just tested it in void linux and it doesn't try to spawn pulseaudio or the gsettings-* commands. Not sure what's different in gentoo, but I do remember pulseaudio was being spawned before I even built mpv with pulseaudio support.
Here's the output of `mpv -audio-device=help`:
```
List of detected audio devices:
  'auto' (Autoselect device)
  'pulse/alsa_output.pci-0000_06_00.6.analog-stereo' (Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo)
  'alsa' (Default (alsa))
  'alsa/lavrate' (Rate Converter Plugin Using Libav/FFmpeg Library)
  'alsa/upmix' (Plugin for channel upmix (4,6,8))
  'alsa/vdownmix' (Plugin for channel downmix (stereo) with a simple spacialization)
  'alsa/hdmi:CARD=Generic,DEV=0' (HD-Audio Generic, HDMI 0/HDMI Audio Output)
  'alsa/hdmi:CARD=Generic,DEV=1' (HD-Audio Generic, HDMI 1/HDMI Audio Output)
  'alsa/hdmi:CARD=Generic,DEV=2' (HD-Audio Generic, HDMI 2/HDMI Audio Output)
  'alsa/usbstream:CARD=Generic' (HD-Audio Generic/USB Stream Output)
  'alsa/sysdefault:CARD=Generic_1' (HD-Audio Generic, ALC257 Analog/Default Audio Device)
  'alsa/front:CARD=Generic_1,DEV=0' (HD-Audio Generic, ALC257 Analog/Front output / input)
  'alsa/surround21:CARD=Generic_1,DEV=0' (HD-Audio Generic, ALC257 Analog/2.1 Surround output to Front and Subwoofer speakers)
  'alsa/surround40:CARD=Generic_1,DEV=0' (HD-Audio Generic, ALC257 Analog/4.0 Surround output to Front and Rear speakers)
  'alsa/surround41:CARD=Generic_1,DEV=0' (HD-Audio Generic, ALC257 Analog/4.1 Surround output to Front, Rear and Subwoofer speakers)
  'alsa/surround50:CARD=Generic_1,DEV=0' (HD-Audio Generic, ALC257 Analog/5.0 Surround output to Front, Center and Rear speakers)
  'alsa/surround51:CARD=Generic_1,DEV=0' (HD-Audio Generic, ALC257 Analog/5.1 Surround output to Front, Center, Rear and Subwoofer speakers)
  'alsa/surround71:CARD=Generic_1,DEV=0' (HD-Audio Generic, ALC257 Analog/7.1 Surround output to Front, Center, Side, Rear and Woofer speakers)
  'alsa/usbstream:CARD=Generic_1' (HD-Audio Generic/USB Stream Output)
  'sdl' (Default (sdl))

**Comment by mrnoname1000** [comment]
I got a backtrace of the pulseaudio spawn and it's buried in a bunch of alsa-lib calls. I also found adding `autospawn = no` to pulseaudio's client.conf fixes the problem. Still not sure why pulseaudio's being spawned to begin with though, and only in Gentoo.

[backtrace.txt](https://github.com/mpv-player/mpv/files/7709322/backtrace.txt)

**Comment by t-8ch** [comment]
Do you have a file `/etc/alsa/conf.d/99-pulseaudio-default.conf`?
Pulseaudio registers itself as default alsa device.

**Comment by mrnoname1000** [comment]
I do but it ends with `.example` and I override default in my asound.conf anyway

**Comment by t-8ch** [comment]
Does the same happen when using `aplay`? If so this is not specific to mpv.
To me the backtrace strongly indicates that alsa-libs is doing this on its own.

**Comment by Dudemanguy** [comment]
I don't believe this is an mpv issue, so I will close it.
