### ISSUE TITLE
Screenshot is blurry

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#9568]
I am using these settings.
```
screenshot-format=png
screenshot-png-compression=0
```

### Important Information
Provide the following information:
- mpv version - 0.34
- Windows Version - 21H1
- Possible screenshot or video of visual glitches - Sorry it's a private video.

### Expected behavior
I'd like the screenshot that would be more clear not blurry.

### Actual behavior
With that settings, the screenshot is much blurry.

### Log file
[mpv_log.txt](https://github.com/mpv-player/mpv/files/7663681/mpv_log.txt)

### Sample files
It is a private video. (Unfortunately, I am not able to upload it here.)

**Comment by avih** [comment]
> Screenshot is blurry

No, it's not.
