### ISSUE TITLE
Does Libmpv respect user-defined bindings: ~/.config/mpv/input.conf  ?

### ISSUE THREAD

**Issue by hanguofu** [mpv-player/mpv#9571]
### Important Information

Provide following Information:
- mpv version : 0.32.0-2ubuntu2
- Linux Distribution and Version :  Ubuntu 21.04  , kernel 5.11
- Source of the mpv binary :  Ubuntu  official repository
- If known which version of mpv introduced the problem :  N/A
- Window Manager and version:  N/A
- GPU driver and version:  N/A
- Possible screenshot or video of visual glitches:  N/A

### Reproduction steps

Define User key binding file :   ~/.config/mpv/input.conf  as follows  :

ENTER cycle pause
HOMEPAGE quit

Develop a simple libmpv as : https://github.com/mpv-player/mpv-examples/blob/master/libmpv/streamcb/simple-streamcb.c
build it and run. During the movie , press key  ENTER  and HOMEPAGE  one by one.

### Expected behavior
Both keys should work :   ENTER should cause mpv pause  and HOMEPAGE should make mpv quit

### Actual behavior
Nothing happen.

### Log file

[  22.172][v][cplayer] first video frame after restart shown
[  22.174][v][cplayer] audio sync: sync_to_video=1, offset=-0.089952
[  22.175][v][cplayer] starting audio playback
[  22.175][v][cplayer] playback restart complete @ 0.133467
[  24.730][w][input] No key binding found for key 'HOMEPAGE'.
[  29.083][d][cplayer] Run command: playlist-next, flags=73, args=["weak"]
[  35.028][w][input] No key binding found for key 'HOMEPAGE'.
[  35.939][e][lavf] Edit lists are not correctly supported (FFmpeg issue).
[  35.940][v][stream_callback] stream level seek from 4022096 to 1996435
[  37.099][w][cplayer] Invalid video timestamp: 15.081733 -> 15.081733
[  37.309][w][cplayer] Invalid video timestamp: 15.215200 -> 15.215200
[  40.051][d][cplayer] Run command: playlist-next, flags=73, args=["weak"]
[  50.962][v][stream_callback] stream level seek from 6593943 to 4264602
[  65.894][v][stream_callback] stream level seek from 7967699 to 6686181
[  95.963][v][stream_callback] stream level seek from 11145600 to 9122939

### Sample files
Not important. You can use any video clips to test this case.

**Comment by stax76** [comment]
You can set `config` to yes.

https://mpv.io/manual/master/#options-no-config

https://github.com/mpv-player/mpv/blob/master/libmpv/client.h#L436

https://github.com/stax76/mpv.net/blob/master/src/Misc/CorePlayer.cs#L134

**Comment by hanguofu** [comment]
stax76 's suggestion does work. Thankyou very much and sorry for the delayed comment :)
