### ISSUE TITLE
MacBook Media keys?

### ISSUE THREAD

**Issue by 097115** [mpv-player/mpv#9575]
Is it possible to make mpv to work with MacBook's media keys? If not natively then may be some kind of third-party software exists?

Thanks.

**Comment by Akemi** [comment]
the media keys work in mpv. if not you should open an issue.

**Comment by samcarter** [comment]
@097115  Did you try to install from https://github.com/jnozsc/mpv-nightly-build or homebrew? With these two versions the media key work for me with Big Sur 11.6 

(they did not work for me with when installing from https://laboratory.stolendata.net/~djinn/mpv_osx/ )

**Comment by 097115** [comment]
@samcarter Thanks!
