### ISSUE TITLE
What is the license for the umpv script?

### ISSUE THREAD

**Issue by Anskrevy** [mpv-player/mpv#9576]
I'd like to fork the umpv script but it doesn't specify any license in the file.

**Comment by rubyFeedback** [comment]
The best would be if mpv could use and offer the same, unified licence for all files.
That would make it easier for people "downstream" in similar situations.

**Comment by avih** [comment]
mpv as a whole is LGPL, so except where noted otherwise (e.g. a file which carries a different license), all files are LGPL.

**Comment by CounterPillow** [comment]
> The best would be if mpv could use and offer the same, unified licence for all files. That would make it easier for people "downstream" in similar situations.

Let us know once you managed to contact the literally dead authors of some of the GPL code to ask them for relicensing.
