### ISSUE TITLE
vo=gpu-next not working with ewa_lanczos in cscale

### ISSUE THREAD

**Issue by lavilao** [mpv-player/mpv#9581]
### Important Information

Provide following Information:
- mpv version : lastest mpv & libplacebo from master
- Linux Distribution and Version: manjaro gnome
- Source of the mpv binary: self compiled
- If known which version of mpv introduced the problem
- Window Manager and version
- GPU driver and version: Mesa 21.2.5
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

with lastest mpv & libplacebo from master gpu-next is not working with ewa_lanczos, with gpu-api=opengl it throws this error ```[vo/gpu-next] Tried calling `pl_swapchain_resize` with unknown size! This is forbidden for OpenGL. The first call to `pl_swapchain_resize` must include the width and height of the swapchain, because there's no way to figure this out from within the API.``` and then crashes with ```i965: Failed to submit batchbuffer: Input/output errorche: 960s/139MB``` or stays on a black screen with audio still playing, with gpu-api=vulkan  ``` [vo/gpu-next/vulkan/libplacebo] vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:481)
[vo/gpu-next/vulkan/libplacebo] Failed holding swapchain image for presentation
[vo/gpu-next] Failed presenting frame!```
 and after that is a black screen, lanczos and spline36 works ok

### Expected behavior
mpv runs fine with polar (ewa_lanczos) scaler
### Actual behavior
crashes or black screen and the gpu hangs (desktop freeze for a couple of seconds)
### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files
[opengl.txt](https://github.com/mpv-player/mpv/files/7689791/opengl.txt)
[vulkan.txt](https://github.com/mpv-player/mpv/files/7689792/vulkan.txt)

**Comment by lavilao** [comment]
machine properties
[machine.txt](https://github.com/mpv-player/mpv/files/7689805/machine.txt)

**Comment by haasn** [comment]
Is this still an issue? I'm assuming it's caused by upstream (due to the GPU errors being logged) either way, but I might as well ask.

**Comment by Dudemanguy** [comment]
Going to assume this is solved (i.e. works on my machine).

**Comment by lavilao** [comment]
Scale=ewa_lanczos does work, the issue seems to be cscale=ewa_lanczos (at that time they were the same) whenever I use cscale=ewa_lanczos the vídeo just loops in the 1st second or goes directly black.

**Comment by Dudemanguy** [comment]
Could you post some new logs?

**Comment by lavilao** [comment]
```mpv -no-config -vo=gpu-next -v -v -gpu-api=vulkan -cscale=ewa_lanczos -log-file=mpv-logs.txt```
[mpv-logs.txt](https://github.com/mpv-player/mpv/files/10375974/mpv-logs.txt)

**Comment by haasn** [comment]
I don't see anything wrong or suspicious in that log

**Comment by lavilao** [comment]
if it helps here is a picture, the audio kept going but the video was on a loop and when hover over the bottom the interface broke
![Screenshot_20230111_222259](https://user-images.githubusercontent.com/77688725/211968800-0fd42b53-0e05-42a6-8faa-1216740e8155.png)

**Comment by llyyr** [comment]
Is this still an issue?

**Comment by lavilao** [comment]
I just tested it on my current setup (chromebook / crostini) and it seems to be fixed
