### ISSUE TITLE
Black screen, flickering, persistent Latte-dock issues with fullscreen mpv

### ISSUE THREAD

**Issue by smsteward** [mpv-player/mpv#9582]
### Important Information

I have a dual monitor setup and have noticed an issue with the latest mpv. When playing an mpv video on either monitor and making said video fullscreen, the bottom ~15% of the other monitor (the one without the mpv window) is covered in a black bar for a few seconds, then that entire monitor flickers once. I utilize Latte-dock, and whilst the mpv video is playing fullscreen, the dock on the second monitor has an ugly black border around it, and the dock animations (bouncing, zooming, etc) and any KDE screen-edge controls (like Show All Windows) are completely disabled until the mpv window is no longer fullscreen, at which point the second monitor goes black and flickers for a second or two before going back to normal and re-enabling all animations and window flair.

I am not utilizing any custom profiles as far as I know. This happens when I simply call `mpv <URL>` to watch a video for which I have the link, but also happens when using the ani-cli script which calls mpv in the background. It happens when the active mpv window is active on either monitor, causing whichever monitor is secondary to have the issues.

I've attached a screenshot that shows the latte-dock problem, and can provide a video upon request.

Here is my system info:
- mpv version : 0.34.0
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch Linux community repository
- If known which version of mpv introduced the problem: 0.34.0 (current)
- Window Manager and version: KWin using KDE Plasma version 5.23.4, KDE Frameworks version 5.88.0, Qt version 5.15.2
- GPU driver and version: NVIDIA 2070 Super, driver 495.44-15 (from Arch Linux extra repository)
- Possible screenshot or video of visual glitches: 
![mpv_glitch](https://user-images.githubusercontent.com/94140636/145582899-7932f574-bc1a-4195-bd00-602b830c1904.jpg)

### Reproduction steps

Issue IS reproducible with `--no-config` option.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

- Open a terminal window and call stock mpv with any url (no profiles, custom scripts, etc): `mpv <URL>`
- Upon loading, in the mpv GUI, click the fullscreen option

### Expected behavior
- mpv should make the video fullscreen without affecting the secondary

### Actual behavior
- the mpv window goes fullscreen, but the secondary monitor freezes momentarily, the bottom ~15% of the screen is fulled with a black bar which then disappears when the window flickers, but latte-dock retains the black border around it, and all window and dock animations are completely disabled on the secondary monitor until the mpv window is no longer fullscreen

### Log file

[mpv_log.txt](https://github.com/mpv-player/mpv/files/7693172/mpv_log.txt)

The issue will be closed for ignoring the issue template.

**Comment by qmega** [comment]
Sounds like the result of KWin's compositing being disabled, which mpv requests in fullscreen by default. Normally kwin takes the content of all windows on the screen and renders them again with its effects applied. When compositing is disabled, each window draws directly to the screen and kwin can't apply its effects (including alpha transparency).

If you don't want mpv to disable compositing, you can add `x11-bypass-compositor=no` to your config file. The downside of this is potentially reduced performance (possible lag, stuttering, or dropped frames, especially if your machine is weak) or broken display sync leading to tearing, etc., depending on your system. You may not notice a difference at all, and some people even have better experiences with compositing enabled. You will have to determine for yourself whether leaving the compositor on is worthwhile or not.

Another option would be to try something like kwin-lowlatency and trying to unredirect the mpv's fullscreen window without disabling compositing for other windows. That might give you the best of both worlds, or it might not work at all. I haven't tried it and can't provide any more information about it.

**Comment by psifidotos** [comment]
you can forbid to KWin to disable your compositing from : plasma systemsettings -> Display And Monitor->Compositor-> [disable] Allow applications to block compositing

**Comment by smsteward** [comment]
Thank you both very much for your assistance! It was in fact a matter of mpv disabling the compositor. All is fixed on my end, and I have no other issues so far. Thanks again!

**Comment by Hamza-Aziane** [comment]
@qmega Thanks man. This issue was driving me nuts
