### ISSUE TITLE
Geometry and Autofit-larger not working

### ISSUE THREAD

**Issue by Anonymous78910** [mpv-player/mpv#9583]
- mpv version 0.32.0
- Linux Distribution and Version Debian 11
- Source of the mpv binary apt install
- Window Manager and version i3wm 4.20.1

Hey while using mpv I tried to set its position at bottom left of my screen. Initially there was no config file so I had to take the sample from here. setting geometry and autofit-larger isnt working whatever value I am giving. I am confident that its reading the config file cause changing fs value to yes worked without any issue. Can you please help?

**Comment by CounterPillow** [comment]
> mpv version 0.32.0

report to your distro, we don't provide support for out of date versions

**Comment by Anonymous78910** [comment]
ok i will try the new version

**Comment by CounterPillow** [comment]
Please include a `--log-file` if you do end up trying it with an up to date version

**Comment by Anonymous78910** [comment]
Dont know if I should post it here but while trying to build on debian. It gave an error in the wal configure.py
File "~/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/./Configure.py", line 6, in <module>
>  from waflib import ConfigSet,Utils,Options,Logs,Context,Build,Errors
> ModuleNotFoundError: No module named 'waflib'

Any idea why this is happening
