### ISSUE TITLE
Is there a keybind to go to the next (or last) playlist?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#9584]
I'm referring to *the entire playlist*, not to the next/last playlist entry which are browsed with the  `<>` characters.

 For instance I often load Youtube channels or playlists only to watch the newly released videos — the entire playlists can of course consist of hundreds or thousands of entries and it'd be convenient not having to always quit mpv, instead loading in as many `https://www.youtube.com/playlist?list=*` links at once as your heart desires.

**Comment by guidocella** [comment]
There are no default keybindings to skip to the first or to the last playlist entry, but you can define them in  `~/.config/mpv/input.conf`:
```
g      playlist-play-index 0
G      set playlist-pos-1 ${playlist-count}
```
