### ISSUE TITLE
How do I clear(reset) lavfi-complex?

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#9588]
I tried passing "", but then audio disappears.
`F5 cycle-values lavfi-complex '[aid1] silenceremove=1:0:-45dB:0:any:-1:0:-45dB:0:any:rms:0.3 [ao]' ""`

**Comment by guidocella** [comment]
You don't need lavfi-complex if you're not mixing multiple tracks. Use `F5 af toggle silenceremove=1:0:-45dB:0:any:-1:0:-45dB:0:any:rms:0.3`
