### ISSUE TITLE
Fails silently with deprecated legacy option syntax "--title mytitle"

### ISSUE THREAD

**Issue by Vrihub** [mpv-player/mpv#9590]
### Important Information

Provide following Information:
- mpv version: 0.32
- Linux Distribution and Version: debian 11

### Reproduction steps

Run `mpv --title mytitle video.mp4` using the deprecated legacy option syntax, without the `=` sign, instead of the correct `--title=mytitle`

### Expected behavior

mpv should warn the user about the wrong option syntax

### Actual behavior

mpv fails silently: no playback, no error messages, even with increased verbosity level `-vvv`.

### Log file

NA

### Sample files

NA

**Comment by CounterPillow** [comment]
```
$ mpv --title mytitle Video/turtle.mp4 
Error parsing commandline option title: option requires parameter
Make sure you're using e.g. '--title=value' instead of '--title value'.
Exiting... (Fatal error)
```

Stop reporting issues for your ancient Debian version.

**Comment by Vrihub** [comment]
Oops, I was actually using `--no-terminal`, sorry for the noise.
