### ISSUE TITLE
mpv-build not activating HDR

### ISSUE THREAD

**Issue by luizzod** [mpv-player/mpv#9592]
### Important Information

Provide following Information:
- 0.34.0
- Windows 11 Pro 21H2
- mpv-build
- Monitor Acer Predator X27

- Possible screenshot or video of visual glitches:
![Screenshot 2021-12-12 134544](https://user-images.githubusercontent.com/21387611/145733504-acdd5854-69d7-4d87-8f62-e9f62eceb759.png)

### Reproduction steps
Downloaded from git the mpv-build. Compiled using MWing64. Configured with waf. I use the exe from the MWing64 bin. Windows display settings is set to Auto HDR on. 
I run mpv from mwing64 with no-config or by dragging and dropping to the mpv.exe any video with HDR but it doesn't play with HDR. I play the same video on PowerDVD 20 and this one does activate the HDR.  The screenshot shows PowerDVD on the left and mpv on the right. I also tried this with the sourceforge exe and that one does activate HDR. Is this a problem when compiling mpv? 

### Expected behavior
Play any video file with HDR and show whites very bright for example (first thing I notice with HDR) and the nvidia message should display with HDR. My monitor has 1100 peak nits so when HDR is on it's much brighter however this doesn't happen with this version of mpv. 

### Actual behavior
No HDR. Video plays as if in SDR. Nvidia message is SDR.

### Log file
[amonghdr.log](https://github.com/mpv-player/mpv/files/7700089/amonghdr.log)

**Comment by hooke007** [comment]
no `--d3d11-output-csp=pq` option could be found... but your build doesn't support d3d11 backend.

**Comment by hooke007** [comment]
no libplacebo in this build, neither.

**Comment by luizzod** [comment]
> You could try `vo=gpu-next`, it works for me.

Actually it disabled hdr for me with the precompiled mpv binary and it didnt activate it on the mpv-build.


> no libplacebo in this build, neither.
I assume I should just use the precompiled binary then since that one works.

**Comment by Dudemanguy** [comment]
As noted, it was just a build issue.
