### ISSUE TITLE
Video and audio lag when using v4l2 with audio file

### ISSUE THREAD

**Issue by s0301132** [mpv-player/mpv#9595]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.34.0-100-g0e76372e86 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Mon Dec 13 01:57:44 HKT 2021
FFmpeg library versions:
   libavutil       57.11.100
   libavcodec      59.14.100
   libavformat     59.10.100
   libswscale      6.1.101
   libavfilter     8.20.100
   libswresample   4.0.100
FFmpeg version: N-104861-g7fe5c7f02d

```
- Linux Distribution and Version
```
Ubuntu 18.04.6 LTS aarch64
NVIDIA Jetson Xavier NX Develo
4.9.253-tegra
```

### Reproduction steps and actual behavior
According to this page [v4l Input](https://github.com/mpv-player/mpv/wiki/Video4Linux2-Input) I want to stream video from video capture card `dev/video0`, if only using `v4l2` it can play smoothly.
`mpv av://v4l2:/dev/video0 --profile=low-latency`

But after adding audio file both video and audio are laggy with lots of drop frame.
```
mpv av://v4l2:/dev/video0 --audio-file=av://pulse:alsa_input.usb-AVerMedia_Live_Gamer_Ultra-Video_5310975600762-02.analog-stereo --demuxer-lavf-o=timestamps=abs
```

Terminal output.
```
Audio device underrun detected.
AV: 455390:42:46 / 455390:42:46 (100%) A-V:  0.000 ct:  0.673 Dropped: 41
Audio device underrun detected.
AV: 455390:42:47 / 455390:42:48 (100%) A-V:  0.000 ct:  0.673 Dropped: 41
Audio device underrun detected.
AV: 455390:42:49 / 455390:42:50 (100%) A-V:  0.000 ct:  0.673 Dropped: 41
Audio device underrun detected.
AV: 455390:42:51 / 455390:42:52 (100%) A-V:  0.000 ct:  0.673 Dropped: 41
Audio device underrun detected.
AV: 455390:42:53 / 455390:42:54 (100%) A-V:  0.000 ct:  0.673 Dropped: 41
Audio device underrun detected.

```

### Expected behavior
Both video and audio play smoothly

**Comment by s0301132** [comment]
I follow [#8367](https://github.com/mpv-player/mpv/issues/8367#issuecomment-741724885) and config my `PulseAudio` now both video and audio can play smoothly. However it only works on system wise setting `/etc/pulse` but not user config `/.config/pulse`

**Comment by Dudemanguy** [comment]
Original reporter said he solved it (might be still an mpv bug somewhere but we'll close this for now).
