### ISSUE TITLE
mp.find_config_file to search mpv directory as well

### ISSUE THREAD

**Issue by bitingsock** [mpv-player/mpv#9598]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

mp.find_config_file would find, for example because users are often directed to put it there, yt-dlp next to the mpv executable instead of it having to be in the config folder. This would aid many scripts in finding it.

### Alternative behavior of the wanted feature

add another argument to mp.find_config_file() for directories to include.

**Comment by avih** [comment]
> add another argument to mp.find_config_file() for folders to include.

`mp.find_config_file` looks for files at the config dir[s]. If you want to lookup files at other dirs, use `utils.readdir`.

**Comment by sfan5** [comment]
Note that ` ~~exe_dir/` exists for this purpose, you can use it with e.g. `mp.utils.get_user_path`.
https://mpv.io/manual/master/#paths

**Comment by bitingsock** [comment]
Has there been any discussion about exposing the ytdl_path found by ytld_hook? This would be a preferable solution in this case.

**Comment by avih** [comment]
> Has there been any discussion about exposing the ytdl_path found by ytld_hook?

mpv doesn't look for and doesn't know where ytdl is. The OS finds it at PATH, unless you configured a custom ytdl path yourself.
