### ISSUE TITLE
mpv window resized in Plasma Wayland when other application gets launched

### ISSUE THREAD

**Issue by goduck777** [mpv-player/mpv#9599]
With the latest version (0.34), mpv window will get resized in Plasma Wayland when launching any new KDE application (like kwrite, or KDE System Setting). I traced it to the commit cd7a7a1de8d8bffa05170befef25b251711c994a, which force window resize when an output event happens. However, it seems that in KDE plasma this event will be triggered when launching any other new KDE application.

I hope this commit can be reverted, or at least the resizing part in output_handle_done()

### Important Information

Provide following Information:
- mpv version:  0.34
- Linux Distribution and Version: Gentoo Linux kernel 5.14.18
- Source of the mpv binary: compiled from github tarball
- If known which version of mpv introduced the problem: 0.34
- Window Manager and version: KDE Plasma Wayland 5.23.4

### Reproduction steps

1. Launch mpv
2. Resize window
3. Click Plasma Kickoff menu, launch any KDE application

### Expected behavior

mpv window should be untouched

### Actual behavior

mpv window get resized to its original size

**Comment by Dudemanguy** [comment]
The `wl->window_size = wl->vdparams;` part is suspicious and I still need to fix some resizing behavior (it's kind of related to this), but plasma should not be sending output events just because you open up some other application. That's just wrong.

**Comment by goduck777** [comment]
I also reported a bug to KDE.

https://bugs.kde.org/show_bug.cgi?id=446452

**Comment by Dudemanguy** [comment]
Shouldn't happen anymore but the KDE behavior is still a bug imo.

**Comment by goduck777** [comment]
Thank you! I actually checked the master version of KDE Plasma yesterday, and found that the issue does not show up with mpv 0.34.0, so I guess it is fixed on the KDE side, though I didn't hear anything back from the their developers.
