### ISSUE TITLE
new mbp14 play hdr video

### ISSUE THREAD

**Issue by zwb124** [mpv-player/mpv#9608]
How to configure the new mbp14 to better play hdr video, the current configuration always feels that the picture is dark, infuse or nplayer the picture is very good, who knows how to configure, thank you very much!

**Comment by Akemi** [comment]
play with the various tone mapping settings. otherwise wait till https://github.com/mpv-player/mpv/pull/8485 is merged.

for hdr stuff i usually play around with those settings, but there are a few more.
```
#HDR
#target-peak=120
tone-mapping=reinhard
tone-mapping-param=0.60
tone-mapping-desaturate=0.6
```
