### ISSUE TITLE
MPV not respecting Subtitle "default" value

### ISSUE THREAD

**Issue by MartinHotmann** [mpv-player/mpv#9610]
### mpv version and platform versions

I installed MPV through Chocolatey and am currently using version: 2021.11.01 (v0.34.0)

### Reproduction steps

Open MKVToolNix and set one: video, audio & subtitle as default:
![image](https://user-images.githubusercontent.com/17692860/146656699-06aa0dc5-b32d-4698-a34c-851c4c22942a.png)
Process the Video and play it with MPV

### Expected behavior

The selected: Video, Audio & Subtitle should be activated by default

### Actual behavior

Video: "default" value respected
Audio: "default" value respected
Subtitle: **"default" value NOT respected**
![image](https://user-images.githubusercontent.com/17692860/146656754-92ad9800-7388-4267-a25e-f7afff65103a.png)
(subtitle with ID `#1` is not activated by default, even if the default value is set)

### Log file

As this happens everywhere (linux and windows tested) I assume this is a general error. A log should not be required for this. I also remember when MPV actually respected the default value/tag for subtitles some time ago.

Thanks in advance!

**Comment by Doofussy2** [comment]
Most likely this, again. https://github.com/mpv-player/mpv/issues/9419

**Comment by BhaturaGuy** [comment]
It's not that "default" is not respect but the "forced" tag actually. Default subs without forced tag will play normally without any slang in conf.

**Comment by MartinHotmann** [comment]
> Most likely this, again. #9419

Thanks, did not noticed it may is related to SRT only. I will check if it also happens for:
- PGS
- VVT
- VOB


> It's not that "default" is not respect but the "forced" tag actually.

I think that you did not understand what the "Forced" tag is for. https://en.wikipedia.org/wiki/Subtitles#Categories

Forced = if a russian mafiabos speaks in the movie in russian they sometimes do not translate this in the audio, for not losing the flare of the russian cursing. So this will be included in the Forced Subtitle for all languages beside russia.
Forced should not have any effect on how, or if a subtitle will be displayed.
But the default value should always be activated as default.
If multiple default values within subtitles are activated take the one with the smallest ID. (the first)

**Comment by Doofussy2** [comment]
> > Most likely this, again. #9419
> 
> Thanks, did not noticed it may is related to SRT only. I will check if it also happens for:
> 
> * PGS
> * VVT
> * VOB

It isn't SRT, exclusively. If you follow the link I posted and read through, you'll have a better understanding.

**Comment by Dudemanguy** [comment]
Duplicate as noted.
