### ISSUE TITLE
Is this the proper way to stop stream recording via IPC?

### ISSUE THREAD

**Issue by silvioprog** [mpv-player/mpv#9611]
Hi.

Supposing this stream playing:

```bash
mpv http://s1.myradiostream.com:12508/listen.mp3 --input-ipc-server=/tmp/mpvsocket
```

and this record starting via IPC:

```bash
echo '{ "command": ["set_property_string", "stream-record", "/home/user/record.mp3"] }' | socat - /tmp/mpvsocket
{"request_id":0,"error":"success"}
```

is this below the correct way to stop the recording?

```bash
echo '{ "command": ["set_property_string", "stream-record", ""] }' | socat - /tmp/mpvsocket
{"request_id":0,"error":"success"}
```

cheers

**Comment by EzeKees** [comment]
I do not think so. What you could do is stop the playback (that would stop the recording).

**Comment by Hrxn** [comment]
FWIW, I can't test this now, but stopping might indeed work, so you could try to send this command:

`echo '{ "command": ["stop"] }' | socat - /tmp/mpvsocket`

**Comment by garoto** [comment]
`echo {"command": ["set_property", "stream-record", ""]} > \\.\pipe\mpv-socket` works for me on Windows.
