### ISSUE TITLE
mpv blocks signals in processes executed with 'subprocess' command

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#9613]
### Important Information

```
mpv 0.34.0 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```
Using mpv on arch linux from distribution repositories. The issue is reproducible on both wayland and X11.
The issue was first reported on foot's [issue tracker](https://codeberg.org/dnkl/foot/issues/853) as I thought it was causing the issue.

### Reproduction steps

Run `mpv --no-config --idle --script=test.lua`
where test.lua contains the following:
```lua
mp.command_native({ name = "subprocess", playback_only = false, detach = true, args = {"foot", "-e", "sleep", '1' }})
```
`foot` can be replaced with other terminal emulators such as `xterm`, `alacritty`, `gnome-terminal`...

### Expected behavior

The terminal window appears and closes down 1 second after, when the `sleep` process is over.

### Actual behavior

The terminal emulator does not close down since it does not receive the SIGCHLD signal. It appears that all signals of the subprocess started by mpv are blocked.
Craig Barnes on the foot issue tracker mentioned that this is caused by [these lines](https://github.com/mpv-player/mpv/blob/fd63bf398af14c95ee7df18815dc3c9d1b4d9b49/osdep/subprocess-posix.c#L76-L77), added in 5309497727debfe1b268f915c5a41bdbe93ad9de

### Log file

https://0x0.st/-CS3.json

**Comment by sfan5** [comment]
I didn't find anything about the signal mask (only signal handlers) in execve(3) but confirmed experimentally that the signal mask indeed carries to the child.

Please test this fix: https://github.com/sfan5/mpv/commit/50af0618c394ebd3f74fe0202d5f8d0aa8b3bdc2

**Comment by occivink** [comment]
The patch indeed fixes the issue, and I can observe that the SigBlk mask of the child process is all-0.

**Comment by craigbarnes** [comment]
> I didn't find anything about the signal mask (only signal handlers) in execve(3) but confirmed experimentally that the signal mask indeed carries to the child.

The [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html) has a useful list of process attributes that get inherited across `exec`.

FWIW, while I was testing this I also noticed that mpv seems to ignore `SIGTTIN` and `SIGTTOU` and doesn't reset them to `SIG_DFL` when spawning child processes.

The POSIX exec spec also states the following:

> ... it is best not to block **or ignore** signals across execs without explicit reason to do so, and especially not to block signals across execs of arbitrary (not closely cooperating) programs.

**Comment by craigbarnes** [comment]
> ... I also noticed that mpv seems to ignore `SIGTTIN` and `SIGTTOU` ...

Ah, never mind - I just noticed you fixed both issues in the same commit.
