### ISSUE TITLE
Provide a property that reports the mastering display metadata used by current video track

### ISSUE THREAD

**Issue by CarterLi** [mpv-player/mpv#9620]
We have [video-params/primaries](https://mpv.io/manual/master/#command-interface-video-params/primaries) to test if the video source is HDR compatible. However it always reports bt.2020 despite the video suggests `Display P3` in mastering display metadata.

It seems that video creators will only set `Display P3` in mastering display metadata as [suggested by Apple](https://help.apple.com/finalcutpro/mac/10.4.6/en.lproj/ver504d31dd2.html), while Color primaries is always set as `BT.2020`. Without a new property we can't know if the video suggests using `Display P3` or not.

```
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0000 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 400 cd/m2
Codec configuration box                  : hvcC
```

### Expected behavior of the wanted feature

Provide a new property `video-params/mastering-display-metadata` that reports the mastering display metadata used by current video track, or null if unavailable.

eg:

```json
{
  "display_primaries": {
    "G": [Gx, Gy],
    "B": [Bx, By],
    "R": [Rx, Ry],
    "WP": [WPx, WPy],
  },
  "luminance": [Lmin, Lmax]
}
```

### Alternative behavior of the wanted feature

N/A

### Log file

N/A

**Comment by ValZapod** [comment]
> bt.2020 despite the video suggests `Display P3` in mastering display metadata.

It does not suggest it, the video is 2020. False. Mastering metadata is what displag you were mastering on was, it does not mean there cannot be outside display p3 data. As an example see Spiderman: Into the spider-verse Blu-ray.

**Comment by CarterLi** [comment]
> Mastering metadata is what display you were mastering on was

Since the video was mastered on Display P3, it should be watched on Display P3 for best results, shouldn't it?

What's more, [`Mastering display luminance` does suggest maximum luminance that the display should support. If not, a tone mapping algorithm must be enabled to display the brightness correctly](https://github.com/iina-plus/iina/issues/8#issuecomment-999385742)

**Comment by ValZapod** [comment]
> mastered on Display P3

Display P3 uses sRGB transfer. Also no, it was mastered on 2020, it just so happened the display only supports part of 2020 and that is what written in mdcv.

> support. If not, a tone mapping algorithm must be enabled to display the brightness correctly

I am sorry what?? No, it is always enabled, that is the whole point of HDR. And no only CLL meta is used for this.

**Comment by CarterLi** [comment]
> I am sorry what?? No, it is always enabled, that is the whole point of HDR. And no only CLL meta is used for this.

I'm sorry I'm confused. If the video suggest max luminance 1000nits and my display support max luminance 1600nits ( eg. Apple XDR Display ), should I enable tone mapping algorithm for that?

**Comment by ValZapod** [comment]
> luminance 1000nits and my display support max luminance 1600nits ( eg. Apple XDR Display ), should I enable tone mapping algorithm for that?

You should look into what actually is in content (for only black picture there is obviously 0.0001 nits max) and then tone map per BT.2390 and later standards, yes.

**Comment by CarterLi** [comment]
> You should look into what actually is in content (for only black picture there is obviously 0.0001 nits max) and then tone map per BT.2390 and later standards, yes. But if there is 1000 nits only, then tonemapping is not needed, of course some complex stuff still happens, PQ should be decoded, but whatever. Also tonemapping should work since it is LCD, so black point is far from 0.0001 nits.

I agree. So in this case, what value should I specify for [--target-peak](https://mpv.io/manual/stable/#options-target-peak), since I can only specify one value instead of two (min and max)

**Comment by Natural-Harmonia-Gropius** [comment]
> Display P3 uses sRGB transfer.

Mastering display color primaries is color **primaries only**, doesn't matter what transfer function it is.
not color **space** display p3 display

**Comment by haasn** [comment]
> I'm sorry I'm confused. If the video suggest max luminance 1000nits and my display support max luminance 1600nits ( eg. Apple XDR Display ), should I enable tone mapping algorithm for that?

No. In this case, mpv will also not enable tone-mapping either. We only tone-map if the source mastering luminance exceeds the display capabilities.

**Comment by CarterLi** [comment]
> No. In this case, mpv will also not enable tone-mapping either. We only tone-map if the source mastering luminance exceeds the display capabilities.

Again according to the [issue](https://github.com/iina-plus/iina/issues/8#issuecomment-995276685), tone mapping didn't seem to work without manually enabling.

https://user-images.githubusercontent.com/662304/146276378-e7a3777a-4edd-4261-b8b8-04717c202c43.mov

**Comment by haasn** [comment]
> Provide a new property video-params/mastering-display-metadata that reports the mastering display metadata used by current video track, or null if unavailable.

In practice the first step will be to extend mpv to even include mastering metadata as part of video colorimetry. (And ideally, also allow overriding it using `vf_format`).

Right now mpv core ignores it. (`vo_gpu_next` looks it up from the ffmpeg side data, but this is not an optimal solution and also ignores e.g. mkv metadata)

**Comment by ValZapod** [comment]
> Mastering display color primaries is color **primaries only**, doesn't matter what transfer function it is.

No Display P3 is name of Apple's creation. The name of the primaries is P3-D65. So display-p3 is P3-D65 + sRGB transfer. That is what all SDR photos of iPhone use. Okay?

**Comment by garoto** [comment]
@ValZapod Are the rumours true that a TV set manufactured by a huuge korean conglomerate is your mostly valuable possession currently?

**Comment by ValZapod** [comment]
> conglomerate is your mostly valuable possession currently?

No, 2080 Ti is. C9 I bought with a big 40% off.

**Comment by ValZapod** [comment]
> mostly valuable possession currently?

Do you wanna read what 2080 Ti (as my most valuable possession) can achieve? I wrote a giant article about it. It includes using ray tracing cores not for raytracing (maps algorithms of Google Earth and Google Moon and general math operations for CUDA), using h264 nvdec decoder for general math operations, using tensor cores to achieve best score in computer chess and fold any protein for a couple of hours using Alphafold 2 open NN weights, hacking nvenc to support more than 2 encoder sessions, hacking driver for use of NVFbc locked for Quadro and of course VRR of HDMI 2.1 in HDMI 2.0b using "optional channels" and using 30 bit color in Photoshop which was also recently added from Quadro. Oh and also mining and of course VFR video using VRR. Oh, and also CUDA cores can compute models of black holes in real time and do GMP level general & infinite precision arithmetic in wolfram mathematica.

> Also tonemapping should work since it is LCD, so black point is far from 0.0001 nits.

BTW, the reference for this is both bt.1886 and bt.2390 that describe how black point affect SDR and HDR EOTFs. Yes, only on OLED BT.1886 is actually 2,4 gamma though it depends luminance too.

Anyway, here is actual P3-D65 primaries sample used in Netflix that they published as open content with permissive license! Just FYI. 

**
Format                      : JPEG 2000
Format profile              : IMFS4k@ML6SL3
Frame rate                  : 24.000 FPS
Color space                 : RGB
Bit depth                   : 12 bits
Title                       : PHDR Image Track
Color range                 : Full
Color primaries             : Display P3
Transfer characteristics    : PQ
Mastering display color pri : Display P3
Mastering display luminance : min: 0.0001 cd/m2, max: 1000 cd/m2**

https://trac.ffmpeg.org/ticket/9145

Lets -c copy that to mkv (mp4 somehow does not work and rename it to mp4 to attach it to our crazy github that does not support mkv, faker, Chrome also removed support for mkv yet mkv renamed to mp4 still works, lame, I was against that idea, but alas)

https://user-images.githubusercontent.com/31514790/151315094-4bb11c09-03b9-46b3-b7d0-84dcb58aa231.mp4
