### ISSUE TITLE
Option to disable deletion of watch_later files upon resume playback for non-playlist users[0.34.0]

### ISSUE THREAD

**Issue by 01yakiek** [mpv-player/mpv#9623]
The only reason I could think of the purpose of deletion watch_later files upon resume playback is the playlist, so that it won't resume if the playlist is looped or replayed. But for us that don't use the playlist, this causes two annoying problems that I experienced.

1. Such as sometimes failure of playback especially online streams as the resume gets deleted without even able to play, as documented in this [pull#7367](https://github.com/mpv-player/mpv/pull/7367). In that thread OP said it's fixed, but it is not. The resume file still gets deleted instantaneously.

2. --save-position-on-quit still fails to resume sometimes regardless even on offline videos for some unknown reason. This happens randomly whenever I close with the X button, it's annoying. I don't know if this is related to the cause of deletion of the watch_later files upon playback, so I'll mention this just in case. I couldn't test this properly as when I try to reproduce it, it doesn't.

By adding the option to disable the deletion, we can control it for various use-cases, which eliminates these problems.

Thank you.

Additional info:
- OS: Windows 10
- Tested MPV version: 0.34.0
- Launched via: Command-line

Edit: Apologies if I didn't follow the template, I clicked "New Issue" and then I signed in, then it entirely skipped selecting issue template for me. I didn't realize there are issue templates.

**Comment by Dudemanguy** [comment]
`watch_later` was originally designed to be a quick way to resume playback from a particular file. i.e. you quit a file for whatever reason and then pick up back from where you left off later. In most cases, you would want the watch_later to be deleted since presumably you would either watch the file to the end or quit again later (and perhaps write new watch_later data). That said, an option to just not automatically delete the watch_later file sounds reasonable.

>--save-position-on-quit still fails to resume sometimes regardless even on offline videos for some unknown reason.

This should definitely not happen though.

**Comment by 01yakiek** [comment]
watch_later data can be overwritten if it exists. So deleting it at playback serves no further purpose than preventing resuming upon playlist loop or such.

I'm too inept to contribute to the mpv codebase as how huge and chaotic it is.

Meantime I doubt the devs will give two cents about this issue. Without hesitation I've quickly devised with an alternative implementation of watch_later2 via lua. You would want to disable the original with --no-resume.

First get a lua hash function from somewhere, such as [SHA1](https://help.interfaceware.com/kb/1318) and wire it up in mpv through separate launch options that don't use playlist.

I placed the sha1 code in the same lua so it doesn't need to load too many lua files at once. Then add the rest at the bottom. This is what I use, so if you use a different hash function, you might have to edit the sha1.hex( ) into your own. Also modify watch_later2_dir to your custom watch_later directory.

```
-- insert hash code here
-- end of hash code

local watch_later2_dir = data\\watch_later2\\" -- point this to your custom watch_later directory

function save_playback_function( )
    local a = mp.get_property( "path" )
    local b = mp.get_property_native( "time-pos" )
    if a ~= "" and a ~= nil and b ~= nil then
        local file = io.open( watch_later2_dir .. sha1.hex( a ), "w" )
        if file ~= nil then
            file:write( math.floor( b ) )
            file:close( )
        end
    end
end

function load_playback_function( )
    local a = mp.get_property( "path" )
    if a ~= "" and a ~= nil then
        local file = io.open( watch_later2_dir .. sha1.hex( a ), "r" )
        if file ~= nil then 
            local b = file:read( )
            if b ~= "" and b ~= nil then
                mp.command( "seek " .. b .. " absolute" )
            end
            file:close( )
        end
    end
    mp.osd_message( "Loaded watch_later2" )
end

mp.add_hook( "on_unload", 50, save_playback_function )
mp.register_event( "shutdown" , save_playback_function )
mp.register_event( "file-loaded" , load_playback_function )

mp.add_key_binding( "", "write-watch-later-config-custom", save_playback_function )
mp.add_key_binding( "", "load-watch-later-config-custom", save_playback_function )
```

The lua code above creates two functions; save_playback_function and load_playback_function, which are then fed into callback events on_unload, shutdown, and file-loaded. Also there is no native way to check if file exists in lua.

Upon on_unload or shutdown event, save_playback_function executes, converting current file path into hash, opens and overwrites existing hash file, then saves a math.floored time-pos.
As for the file-loaded, it is the same, but instead opens to read the time-pos, then seek towards that position. This is only possible once the video is successfully loaded and playback begun.

The two extra script-keybinding write/load-watch-later-config-custom can be wired up in input.conf for other functions.

For example in input.conf
```
Ctrl+s script-binding write-watch-later-config-custom ; show-text "Saved watch_later2"
Ctrl+l script-binding load-watch-later-config-custom ; show-text "Loaded watch_later2"
f5 loadfile "${=path}" ; show-text "Refreshing..."
```

Mpv stupidly have no stop function as far as I could tell. The f5 keybinding works for video streams that have stopped buffering and pressing it  causes on_load to fire to save time-pos. Then loadfile the same path, and finally it will fire file-loaded which loads the time-pos.

Thank you.

**Comment by garoto** [comment]
> codebase as how huge and chaotic it is [...]

mpv has a super-organized dir structure and strict commit rules, wtf are you talking about.

**Comment by 01yakiek** [comment]
> > codebase as how huge and chaotic it is [...]
> 
> mpv has a super-organized dir structure and strict commit rules, wtf are you talking about.

Please don't go around and misquote someone.
I wrote _"**I'm too inept to contribute** to the mpv codebase as how huge and chaotic it is."_
How did you miss that? Don't answer.
Here, lemme rephrase.

I'm too much of a complete waste of oxygen brainless imbecile in a useless bag of rotted fleshy daft cunt to comprehend how to contribute to the mpv codebase, let alone no matter the state of "super-organized dir structure and strict commit rules", all we I see are huge and chaotic codes.

If it's so super-organized, then add this feature for my smooth brain.

Thank you.

**Comment by garoto** [comment]
It's organized in the sense that one can grep the ouput of a `git --log` command and _generally_ find what they are looking for,  or, at the very least, a very close approximation.
