### ISSUE TITLE
How to work out amplification level for --volume-max?

### ISSUE THREAD

**Issue by T-10001** [mpv-player/mpv#9626]
The manual says for --volume-max "Set the maximum amplification level in percent (default: 130). A value of 130 will allow you to adjust the volume up to about double the normal level.".

How to work out the amplification level? If it is percent why is 130 double?

**Comment by haasn** [comment]
https://github.com/mpv-player/mpv/blob/master/player/audio.c#L168

The gain is equal to the volume taken to the third power. 1.3^3 = 2.197.

**Comment by Dudemanguy** [comment]
The question was answered.
