### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jvschiavo** [mpv-player/mpv#9628]
.

**Comment by jvschiavo** [comment]
Help, I created this issue by accident. Can someone help me to delete it? ;-;

**Comment by jvschiavo** [comment]
@Dudemanguy Sorry to disturb you, but I created this issue by accident, could you please delete it for me?

**Comment by Akemi** [comment]
we can't delete opened issues, we can only close them.

**Comment by jvschiavo** [comment]
> we can't delete issues, we can only close them.

There is really no way to do it? T.T

**Comment by CounterPillow** [comment]
No, your embarrassing mistake is preserved forever.

I have hired a stonecutter to reproduce it onto a stone tablet so it can be preserved in the library of Alexandria for thousands of years to come.

**Comment by jvschiavo** [comment]
> No, your embarrassing mistake is preserved forever.
> 
> I have hired a stonecutter to reproduce it onto a stone tablet so it can be preserved in the library of Alexandria for thousands of years to come.

Man, I fucked up really hard right now. I managed to post my password here because of some fucking stupid design UIs, I'm running to change this password on a lot of websites right now... It would really help me if I this could be deleted. I feel so fucking stupid right now...

**Comment by CounterPillow** [comment]
"jvsm11" wasn't a very good password to begin with.

**Comment by jvschiavo** [comment]
> "jvsm11" wasn't a very good password to begin with.

I'm a particular kind of dumb...

**Comment by adisib** [comment]
I'm pretty sure Github staff can delete issues. After changing your passwords I would open up a support ticket ( https://support.github.com/request ) and tell them it is a security issue.

**Comment by jvschiavo** [comment]
> I'm pretty sure Github staff can delete issues. After changing your passwords I would open up a support ticket ( https://support.github.com/request ) and tell them it is a security issue.

Thank you very much! :pray: I'm gonna do that as soon as I change all my passwords.
