### ISSUE TITLE
mpv freezes up completly at random

### ISSUE THREAD

**Issue by D0nnieD4rk0** [mpv-player/mpv#9629]
been using a thing called ani-cli that streams anime from gogoanime.vc and every now and then it causes mpv to completely stop responding and a kill command is necessary to even close the window.
its probably a streaming bug and it happens about 1 or 2 times a day

using latest version on arch linux with vulkan gpu driver

**Comment by ChrolloRifat** [comment]
It's not a streaming bug...It freezes for me too... completely freezes my whole system for a while until I kill it....even the kill comand takes ages to apply...so I'm using celluloid for the time being...

**Comment by CounterPillow** [comment]
im calling the ceo of mpv this is unacceptable!!! left a bad yelp review!!!
