### ISSUE TITLE
add alt-enter command to go backward in the playlist

### ISSUE THREAD

**Issue by alexherbo2** [mpv-player/mpv#963]
with `alt` as alternate behaviour to `enter` to go forward in the playlist

**Comment by rrooij** [comment]
This issue should be closed in my opinion. Users can define their custom key bindings in input.conf. Discussing the default key bindings can be done in: https://github.com/mpv-player/mpv/issues/973

**Comment by wm4** [comment]
Yes, discussion should continue in that issue.
