### ISSUE TITLE
"seek_v_exact" and "seek_h_exact" to "true" by default

### ISSUE THREAD

**Issue by l4kr** [mpv-player/mpv#9632]
Hi, I've spent a few minutes figuring out why sometimes I seek 5 seconds, sometimes 10 seconds, sometimes 7 seconds... when it should always be 5 seconds. Turns out it's because by default, the app relies on keyframes.

I think most people would expect a consistent behavior in this regard because every player I know seeks exactly the seconds it should. My suggestion would be to change "seek_v_exact" and "seek_h_exact" to "true" by default to avoid confusion I just had.

**Comment by sfan5** [comment]
"seek_[hv]_exact" appear to be settings specific to jellyfin-mpv-shim. Did you mean to open an issue on [their repository](https://github.com/jellyfin/jellyfin-mpv-shim)?

**Comment by l4kr** [comment]
I am very sorry, yes, this is the wrong repository, closing this.
