### ISSUE TITLE
How to render HDR video content on the iOS platform via Metal?

### ISSUE THREAD

**Issue by MenThu** [mpv-player/mpv#9633]
I am trying to use mpv to play HDR video on iOS platform

When `hwdec-image-format` is specified as  `nv12`, pixel-format is `kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange`
, the video frame is different from AVPlayer, the exposure is too high to make some details unclear

When not specified, pixel-format is `kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange`, then mapper_init of hwdec_ios.m exits with an error message: `Unsupported texture format`, and the screen turns blue

I watched several issues
[8468](https://github.com/mpv-player/mpv/issues/8468)
[8467](https://github.com/mpv-player/mpv/issues/8467)
[7846](https://github.com/mpv-player/mpv/issues/7846)

The conclusion is: there is no suitable format of texutre on ios, so the effect of rendering with OpenGL ES is not perfect

But I also saw that @tmm1 was trying to use metal to render HDR content, but it didn’t work, but it was in January. 
I don’t know if there is any breakthrough now.

It seems that Apple only provides AVFoundation to play HDR videos

Has anyone found a way to bypass this problem or successfully rendered it with Metal?

Mother tongue is Chinese, use google to translate text, if some words or semantics are wrong, please point them out, thank you

**Comment by alexiscn** [comment]
1.  [Create CVPixelBufferRef from OpenGL](https://gist.github.com/caojianhua/8494bb3077228ee01fda)
2. [Create OpenGL and Metal InteropTexture](https://developer.apple.com/documentation/metal/metal_sample_code_library/mixing_metal_and_opengl_rendering_in_a_view)
3. Draw metal texture using `CAMetalLayer`

The real implementation is much more complex than above steps.

**Comment by Dudemanguy** [comment]
mpv doesn't support metal at all (likely won't ever), so all I can say is, "good luck".
