### ISSUE TITLE
long path > short path

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#9634]
The below line of code works perfectly.
`watch-later-directory=Z:\Users\Max\AppData\Roaming\mpv\_Z\watch_later`

It has a long path. Is there a short version of it?

_PC, Windows_

**Comment by CounterPillow** [comment]
`~~/home` instead of `Z:\Users\Max\AppData\Roaming\mpv\`

I will not respond to your 5 follow-up tech support questions that are sure to follow.

**Comment by Max-Enrik** [comment]
Thank you so much for the answer.

_That is is my fault that I didn't look for 'Path'._
