### ISSUE TITLE
ability to trim black bars from build in console

### ISSUE THREAD

**Issue by nanderer** [mpv-player/mpv#9635]
Hi,

i dont like black bars in window mode, like when viewing a cinematric movie that has been encoded like SD DVD 16:9 resolution. But i would need to restart and do complicated stuff, so it would be nice if there would be a command in the build in console, accessable using the ` key left next to 1 to do so, i tried 

````
973770973770
[input] Command 'geometry=20:9' not found.
[input] Command was defined at console.
(Paused) AV: 01:14:26 / 02:00:08 (61%) A-V:  0.000 Cache: 763s/150MB
[input] Command set: required argument value not set.
[input] Command was defined at console.
```

thanks for any help in advance

**Comment by hooke007** [comment]
console is not a conf file
so input command instead of options
`set geometry 20:9`

**Comment by Dudemanguy** [comment]
If I understood you correctly, what you want is the `--panscan` option (`w` and `W` by default).
