### ISSUE TITLE
[Question] How to make mpv read "sub-ass-styles=" from portable_config?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9640]
Hi,

I did ask similar question here #9352 

so in place of specifiying the whole path like this
`
sub-ass-styles="C:\Users\Ayd1n\mpv-build\portable_config\template-ass\[Kaizoku] Demon Slayer.ass"
`

I want to know How can I make this work?
`
sub-ass-styles="~~/template-ass/[Kaizoku] Demon Slayer.ass"
`

**Comment by hooke007** [comment]
escape the blank first.

**Comment by hooke007** [comment]
Doesn't work? It couldn't be possible.
```lua
mp.set_property('sub-ass-styles' , mp.command_native({'expand-path', '~~/this is sub.ass'}))
```

**Comment by Dudemanguy** [comment]
Late here but does `~~/` not expand to the `portable_config` directory on windows? That sounds like a bug if it really doesn't. There's also `~~home/` you could try.
