### ISSUE TITLE
MPV window focuses itself even if launched minimized

### ISSUE THREAD

**Issue by SunSerega** [mpv-player/mpv#9641]
### Important Information

- mpv version: mpv-x86_64-20211219-git-fd63bf3
- Windows Version: Version	10.0.19043 Build 19043
- Source of the mpv binary: Initially downloaded from [here](https://sourceforge.net/projects/mpv-player-windows/files/64bit/), but since then - updated many times using `updater.bat`, including just now.

### Reproduction steps

Demonstration: https://youtu.be/uYuur0ksfmk
In this video, I used my program (which acts as a weighted playlist of music) to start MPV.
Arguments were `mpv.exe "FileName" --window-minimized=yes --volume=40`.

First I pressed Win+Up, Win+Down. MPV window reacted to that, proving that it got focused, normalizing, and then minimizing again.
Then I repeated this key combination, but this time RM.exe reacted, so windows returned focus to it after MPV got manually minimized.

I also tried making my own small WinForms and WPF programs (though both in .Net, not C++) and launching them from the folder and from another program, but couldn't reproduce it.
So I think this can't be a windows bug - only MPV has this weird behavior.

> Try to reproduce your issue with --no-config first.

The result is the same.

### Expected behavior

I expect MPV to not steal focus if it was launched in minimized state.

### Actual behavior

Windows shouldn't allow minimized windows to have a focus in the first place, but it seems like here MPV does something to break this rule.

### Log file

Made with args: `mpv.exe "FileName" --no-config --window-minimized=yes --log-file="C:\Users\***\Desktop\MPV log.txt" --volume=40`:
[MPV log.txt](https://github.com/mpv-player/mpv/files/7776840/MPV.log.txt)

### Sample files

Which music files are used is irrelevant, but the program I used for reproduction [can be found here](https://github.com/SunSerega/RM).

**Comment by maaldheefee** [comment]
https://github.com/tomasklaen/uosc/issues/296

**Comment by SunSerega** [comment]
Are you sure? The behavior here happens on window creation, but what you linked seemingly happens when the existing window minimizes.

**Comment by maaldheefee** [comment]
Not sure is it's related to this issue. But yes.

Type `set window-minimized yes` in the console. `Esc` to exit the console. Then check. For example pressing `q` quits mpv.

**Comment by SexySteak** [comment]
I also encountered this issue. I started mpv through the command line and set "window-minimized" in the "mpv.conf" beforehand. mpv correctly started minimized, but it still took focus.
