### ISSUE TITLE
show osd-bar

### ISSUE THREAD

**Issue by yassin-l** [mpv-player/mpv#9643]
i changed the key o to do following:
```bash
o show-text '➤ ${time-pos} / ${time-remaining}'
```
but i wanna show osd-bar as well,so i add the osd-bar like this:
```bash 
o osd-bar show-text '➤ ${time-pos} / ${time-remaining}'
``` 
but it didn't work
NOTE:i know osd-bar it's prefix if u cloud explain more how i can use it.

**Comment by avih** [comment]
> if u cloud explain more how i can use it.

It's documented: https://mpv.io/manual/master/#command-interface-osd-bar :

> osd-bar
>    If possible, show a bar with this command. Seek commands will show the progress bar, property changing commands may show the newly set value.

It shows the seek bar for the `seek` command, and can show a bar for some properties (brightness, etc).

There's no bar for the `show-text` command.

**Comment by yassin-l** [comment]
> > if u cloud explain more how i can use it.
> 
> It's documented: https://mpv.io/manual/master/#command-interface-osd-bar :
> 
> > osd-bar
> >    If possible, show a bar with this command. Seek commands will show the progress bar, property changing commands may show the newly set value.
> 
> It shows the seek bar for the `seek` command, and can show a bar for some properties (brightness, etc).
> 
> There's no bar for the `show-text` command.

so there's no way to show osd-bar

**Comment by avih** [comment]
> I wanna show remaining time and osd-bar like the progress bar command?

You can't with the `show-text` command.

**Comment by bitraid** [comment]
> I wanna show remaining time and osd-bar like the progress bar command?

Add this to your `mpv.conf`:
`osd-status-msg='➤ ${time-pos} / ${time-remaining}'`
