### ISSUE TITLE
MPV: graphic artifacts in .m2ts files (in copies of blu-ray discs)

### ISSUE THREAD

**Issue by Niotferdi** [mpv-player/mpv#9645]
### Important Information

- mpv version
`mpv 0.34.0 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  7 20:16:38 +08 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.101
   libswresample   4.0.100
FFmpeg version: git-2021-11-06-1728127e`
- Windows Version
21H1 19043.928
- Source of the mpv binary
Windows builds by shinchiro (releases and git) https://sourceforge.net/projects/mpv-player-windows/files/release/
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches
Glitches appear too quickly, I cannot capture them in the screenshot.

### Reproduction steps

Open video file with m2ts extension copied from blu-ray disc. Regardless of the parameters used (with my custom config or --no-config), the result will be the same. Perhaps the strength of graphic glitches and the frequency of their occurrence will be different, but they will still be.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
The video file plays without any visible glitches just like any other file.

### Actual behavior
Glitches appear in the video file with frequent seek. They appear as either a solid gray tone, a solid gray tone with a small horizontal bar of noise (or a few bars), or a wall of color distortion and noise, rich and beautiful glitches. Glitches block the picture completely, or leave parts of the picture visible. Disappear after a split second.
It appears differently in different video files. In one full-hd-movie they did not appear at all, in another full-hd movie they rarely appear, only a few times at the beginning of the file, and after a certain number of searches (closer to the middle and end of the file) they disappear. In a 4k movie, they appeared literally at every second seek, and disappeared gradually within a second or half a second.
If you convert m2ts file to mkv without re-encoding, then this problem disappears.

### Log file

https://pastebin.com/CT9UMAFq

**Comment by aufkrawall** [comment]
Afaik m2ts wasn't meant to be parsed directly so seeking is ultra fugly with it in lots of programs.

**Comment by LaserEyess** [comment]
https://github.com/mpv-player/mpv/issues/9639#issuecomment-1001034332

You should not expect seeking to work well on transport stream containers. Remux it to mkv and it should work as expected.

**Comment by ValZapod** [comment]
This is a known bug in ffmpeg. In partiuclar when in hevc there are 4 tiles.

> Remux it to mkv and it should work as expected.

You mean to mp4. MKV does not support good enough precision. But yes, that does work.

**Comment by ValZapod** [comment]
BTW, also see https://patchwork.ffmpeg.org/project/ffmpeg/patch/20190831101039.2179-2-fumoboy007@me.com/

**Comment by Dudemanguy** [comment]
As noted previously, this is just how TS works. Not anything we can really do about it.
