### ISSUE TITLE
How to unload a script while running?

### ISSUE THREAD

**Issue by escapezn** [mpv-player/mpv#9648]
I have a script for one-time use and load it in console as needed, but once loaded it keeps on all along this session, I have to restart mpv to resume normal playback.

So is there any way to unload certain script without quitting mpv?

**Comment by avih** [comment]
> So is there any way to unload certain script without quitting mpv?

In a js script you can call `exit()`, and in lua the script never exits, but if it only does one thing, then it shouldn't matter anyway. The resources which an idle script consumes are almost negligible.

**Comment by avih** [comment]
> and in lua the script never exits

Actually that's not true. You can set `mp.keep_running = false` and then the script will exit/unload.
