### ISSUE TITLE
wine getting some errors..

### ISSUE THREAD

**Issue by QinnStar** [mpv-player/mpv#9649]
when i run an exe file using wine "wine ./file.exe"

i get this errors :-

MESA-INTEL: warning: Bay Trail Vulkan support is incomplete
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:gdiplus:GdipGetLineSpacing ignoring style
0024:fixme:gdiplus:GdipGetLineSpacing ignoring style

can anyone help with it?please

**Comment by CounterPillow** [comment]
This is the mpv bug tracker
