### ISSUE TITLE
ADD ability to set --title update interval/frequency

### ISSUE THREAD

**Issue by allanlaal** [mpv-player/mpv#9650]
> --title=<string>
> There is a danger of this causing significant CPU usage, depending on the properties used. Changing the window title is often a slow operation, and if the title changes every frame, playback can be ruined.

### Expected behavior of the wanted feature

setting `--title-update-interval-frames` or `--title-update-interval-sec`  or such would update (and thus parse) the Window Title only after that set interval

fixes CPU usage. Needing to update the title every frame (current  default) seems to be an edge case - most of the time the Window Title  is quite static (as in default)

### Alternative behavior of the wanted feature

none

### Log file

not applicable, but I can share by awesome title here :D

`title='${?seeking==yes:⏩}${!seeking==yes:▶}${?seeking==yes:${?paused-for-cache==yes:🕙${cache-buffering-state}% }}${!playlist-count==1: [${playlist-pos-1}}${?chapter:${!$chapter-list/count==1::${=chapter}}}${!playlist-count==1:/${playlist-count}]} ${?demuxer-via-network==yes:${media-title}${metadata/by-key/creation_time:}}${!demuxer-via-network==yes:${filename/no-ext}}${?height: ${height}p}${?estimated-vf-fps:@${estimated-vf-fps}}${?demuxer-via-network==yes: [${demuxer-cache-duration}s@${cache-speed}]}'
`

**Comment by avih** [comment]
No. The title is updated whenever it needs to.

If you want to throttle it, then write a script which expands your string periodically and set the title to the resulting string.

**Comment by allanlaal** [comment]
> No. The title is updated whenever it needs to.

there are properties that have frame or millisecond accurate values, which will force the title to update each frame

**Comment by allanlaal** [comment]
> If you want to throttle it, then write a script which expands your string periodically and set the title to the resulting string.

I think throttling the title update should be a core mpv feature, like with other such intervals/frequencies currently already in the config :)

**Comment by avih** [comment]
For future reference, this script can be used for that:
```lua
-- File: title.lua
-- Throttle title updates to 1s intervals by default
-- Interval can also be set with e.g. --script-opts-add=title-interval=5
-- The title can be set normally via mpv.conf or changed at runtime

local opts = { interval = 1 }  -- in seconds
local title, expanded

local function update()
    if not title then return end
    expanded = mp.command_native({"expand-text", title})
    expanded = expanded:gsub("%$", "$$")  -- escape $, if any
    mp.set_property("title", expanded)
end

mp.observe_property("title", "string", function(_, v)
    if v == expanded then return end  -- our own (title not set by the user)
    title = v
    update()
end)

local timer
local function set_timer()
    if opts.interval <= 0 then
        mp.msg.error("timer interval must be greater than 0 (" .. opts.interval .. ")")
        opts.interval = 1
    end
    if timer then timer:kill() end
    timer = mp.add_periodic_timer(opts.interval, update)
    update()
end

require("mp.options").read_options(opts, nil, set_timer)
set_timer()
```
