### ISSUE TITLE
General question about HTTP network stream implementation

### ISSUE THREAD

**Issue by bartfer** [mpv-player/mpv#9651]
Hi,

This is a rather general question:
I have setup a MusicPlayerDaemon httpd audio stream and using mpv to listen to it I only get a few seconds delay compared to other softwares like VLC for example. Other softwares not only have much bigger delays but will lose connection somehow and accumulate more and more delay over time (when stream is paused for example).
Could anyone please explain how mpv is implementing http network playback? I'd love to understand what is the reason it gives better results and maybe if it is possible to even shorten this delay somehow (but maybe that is up to the source (MPD), I don't know).

Would appreciate any info regarding this (some links somewhere or exact code etc).

Thanks!

**Comment by Dudemanguy** [comment]
This is a bad answer since I do not know the details, but mpv generally uses ffmpeg for network streams. Most of the related code to this is in [stream_lavf.c](https://github.com/mpv-player/mpv/blob/master/stream/stream_lavf.c).
