### ISSUE TITLE
Exclude unwanted files in folders

### ISSUE THREAD

**Issue by escapezn** [mpv-player/mpv#9652]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
When loading a folder or directory mpv would recursively add all files in it and it's subdirectories. Sometimes this behavior makes playlist a mess, for example a folder of music with album photos and lyrics.

It would be nice if mpv could offer an option to exclude such unrelated files by extension.

**Comment by guidocella** [comment]
You can use this script: https://github.com/mpv-player/mpv/issues/2595#issuecomment-808723731

**Comment by escapezn** [comment]
> You can use this script: [#2595 (comment)](https://github.com/mpv-player/mpv/issues/2595#issuecomment-808723731)

Thanks for your hint. Looks there have been a few similar requests. Scripts are helpful, but still waiting for a native implement in mpv.

**Comment by LaserEyess** [comment]
You won't get a native implementation, even now the feature you're using is implemented as a script, [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua). You can set it to ignore extensions by type, such as ignore non-music files. 

Your next best option, assuming you don't want a userscript, is to make the playlist yourself with another tool and then play that in mpv.

**Comment by escapezn** [comment]
> You won't get a native implementation, even now the feature you're using is implemented as a script, [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua). You can set it to ignore extensions by type, such as ignore non-music files.
> 
> Your next best option, assuming you don't want a userscript, is to make the playlist yourself with another tool and then play that in mpv.

Loading folder is not implemented by autoload.lua, but the extentions filter feature does meet my demand when loading files in a mixed folder, not loading folder directly.
I currently managed to deal with it by adding . prior to non-media filenames, so that mpv would not add these files to playlist.

**Comment by shmup** [comment]
Even trying the script, I'm still seeing:

```
[file] This is a directory - adding to playlist.

Playing: ./Industrial-Oldschool/Cabaret Voltaire - 2 X 45/00 - Cabaret Voltaire - 1982 - 2 X 45.sfv
Failed to recognize file format.
```

And I've added `$HOME/.config/mpv/scripts/blacklist.lua` where I've tried both:

```
mp.observe_property('playlist-count', 'number', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        for _, extension in pairs({'svf', 'cue', 'txt', 'jpg'}) do
            if playlist[i].filename:match('%.' .. extension .. '$') then
                mp.commandv('playlist-remove', i-1)
            end
        end
    end
end)
```

And [the suggested](https://github.com/mpv-player/mpv/issues/2595#issuecomment-1091152137) "faster version":

```
local blacklist = {'svf', 'cue', 'txt', 'jpg', 'jpeg', 'gif', 'png', 'log', 'm3u8'}

local temp = {}
for _, ext in pairs(blacklist) do
    temp[ext] = true
end
blacklist = temp

-- Observing playlist instead of playlist-count would call this 3 times
-- unnecessarily on each playlist-entry change, though it would be more correct
-- since it would exclude blacklisted files in single-file directory/playlists,
-- which don't change playlist-count, and files added by calling loadfile with
-- a blacklisted file.
mp.observe_property('playlist-count', 'native', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if blacklist[playlist[i].filename:match('%.(%w+)$')]
           and playlist[i].filename ~= 'playlist.m3u8'
           and playlist[i].filename:match('/playlist.m3u8$') == nil then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

So I'm wondering: _what am I doing wrong here?_
