### ISSUE TITLE
Is it possible to save screenshots with the media-title with spaces and special characters replaced by the underscore character ?

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#9653]
Hi,
I have this option in my `mpv.conf` : 
`screenshot-template="%{media-title}-%n"`

But I'd like the screenshot to be saved inside a filename with spaces and special characters replaced by underscores (`_`).

Is this possible ?

**Comment by Dudemanguy** [comment]
Not with just the `--screenshot-template` option. It would possible to do in a script though.

**Comment by sebma** [comment]
@Dudemanguy I've never written a mpv script, how do I do that ?

**Comment by Dudemanguy** [comment]
You can look at some existing examples on the [User Scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) page for reference. Essentially what you would need to do is create a function that takes the `media-title`, formats it to your liking to some string, and then execute a screenshot using the string you created as the screenshot-template.

**Comment by sebma** [comment]
@Dudemanguy Thanks for your help :+1: 

Just one more little detail that bothers me : what is the function to `execute a screenshot`, is it the [`mp.commandv("screenshot-to-file",...`](https://github.com/Thann/mpv-abs-screenshot/blob/master/abs-screenshot.lua#L33) function ?

**Comment by Dudemanguy** [comment]
You could use `screenshot` or `screenshot-to-file` depending on how you want to implement this. The difference is that `screenshot-to-file` takes a specific, exact path for your screenshot. In your question you indicated that you wanted to use the `%n` formatter. If you use `screenshot-to-file`, it would ignore the `screenshot-template` and said formatters wouldn't work. In other words, you would need to come up with a way to calculate that `%n` value yourself.

The other way to do this would be to just use the `screenshot` command. All you need to do is first set the `screenshot-template` to the string you want with the wanted formatting codes. Then just execute the `screenshot` command.

**Comment by sebma** [comment]
@Dudemanguy Thanks a lot :+1:
