### ISSUE TITLE
Interpolation Double FPS (estimated)

### ISSUE THREAD

**Issue by ModernLobby** [mpv-player/mpv#9662]
Hey, 

So i have a bit of a problem since returning on W10.

I got a config with interpolation : 
"interpolation
video-sync=display-resample"

For example in win11 with G-SYNC result was (Fullscreen and Windowed): 
Display FPS : 164.917   Estimated : 164.917          Windowed
Display FPS : 164.917   Estimated : 164.917          Fullscreen

Now i got back on win10 with G-SYNC (Fullscreen and Windowed): 
Display FPS : 164.917   Estimated : 164.917          [Windowed](https://i.imgur.com/QJMGjx3.png)
Display FPS : 164.917   Estimated : 328.729          [Fullscreen](https://i.imgur.com/wF7muVP.png)

If needed i will post my mpv.conf 

Thanks in advance

**Comment by Tsubajashi** [comment]
Do you have FastSync enabled in your vsync settings of your nvidia control panel?

**Comment by ModernLobby** [comment]
Only G-Sync at 165hz for both monitor.

**Comment by CounterPillow** [comment]
Don't use both display-resample and g-sync. display-resample assumes the monitor refresh rate won't try to match the application's presentation rate.

**Comment by ModernLobby** [comment]
Alright thanks you for the solution it's working now

**Comment by CrendKing** [comment]
If you have [NVIDIA Profile Inspector](https://github.com/Orbmu2k/nvidiaProfileInspector), you will find that NVIDIA has a profile specifically for [MPC-HC](https://github.com/clsid2/mpc-hc). This profile basically set "GSYNC - Application State" to "Force Off". If you disable this profile and try playing in MPC-HC or [MPC-BE](https://sourceforge.net/projects/mpcbe/) with G-Sync, you will notice they have exactly the same problem. So NVIDIA may know G-SYNC not compatible with some video players, but they only did profile for MPC-HC (maybe due to higher user count or legacy reason?)

So you could just add mpv.exe to that profile to solve the problem. Or you could disable `display-resample`.

**Comment by Dudemanguy** [comment]
Problem was fixed as noted by the OP.

**Comment by adavier** [comment]
I found this while searching for a solution to the same issue. Specifically, display-resamaple resulted in 2x fps and I couldn't use audio as this would bring my monitor down to 24hz (even when mpv is just in focus, not full screen, despite GSYNC set to only full screen) casuing flicker and high input lag.

The solution I found is rather odd:

- Go to Manage 3d Settings, select mpv.
- Set Monitor Technology to "Fixed Refresh"
- First time I opened mpv the screen went entirely black and stopped working. On future times it worked but would cause the screen to say "DP 1 detected" every time mpv lost/gained focus.
- Restart (Maybe?)
- Set Monitor Technology back to Use Global Setting (GSync)
- Now mpv will not trigger gsync. (dispaly-resample will work @144, or audio will work at 24 without setting the montior to 24.

Why this works, I have no idea.
I found it accidently after mpv started exhibiting this behaviour after I reset the drivers, I must have done this accidently before.

**Comment by Hrxn** [comment]
Either turn off G-Sync (globally or for mpv), or disable `display-resample`. Never both together.
It's already mentioned in this thread. And elsewhere, here..

**Comment by adavier** [comment]
> Either turn off G-Sync (globally or for mpv), or disable `display-resample`. Never both together. It's already mentioned in this thread. And elsewhere, here..

Yes, but for the benefit of those of us who want to play games without toggling gsync each time, this is a work around to the issue. so for anyone else who arrives here by google, this could be a viable alternative.

I apologise for trying to be useful...




Also, as I stated turning off display-resample just causes the monitor to drop to 24hz, causing a uncomfortable strobing effect (and while yes, this is the monitors first) I doubt Dell would ever bother to do anything. And this doesn't seem like it should be an issue with Gsync set to Fullscreen only, but it is.
