### ISSUE TITLE
Play gzipped files

### ISSUE THREAD

**Issue by necros2k7** [mpv-player/mpv#9665]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
play gzipped files
### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by CounterPillow** [comment]
`zcat file | mpv -`

**Comment by necros2k7** [comment]
Windows build

**Comment by CounterPillow** [comment]
use better OS or less shitty files.

There is no point to gzipping media files. They are already compressed. gzip is not a multimedia container. It will not allow for proper seeking. If you, for some reason, want to compress things with zlib, then use MKV with zlib compression mode.
