### ISSUE TITLE
Could I make autoload.lua only work on a hotkey?

### ISSUE THREAD

**Issue by Kayizoku** [mpv-player/mpv#9668]
As I noted, I simply want to autoload.lua to kick if I press a certain hotkey. There are times I would like to refrain from loading an entire folder of files, so I would appreciate a solution if possible.

**Comment by escapezn** [comment]
You may edit autoload.lua like this, simply change f6 to other key you feel convenient.

-- mp.register_event("start-file", find_and_add_entries)
mp.add_key_binding("f6", "find_and_add_entries", find_and_add_entries)

**Comment by Kayizoku** [comment]
> You may edit autoload.lua like this, simply change f6 to other key you feel convenient.
> 
> ```
> -- mp.register_event("start-file", find_and_add_entries)
> mp.add_key_binding("f6", "find_and_add_entries", find_and_add_entries)
> ```

This works wonderfully, but I noticed that once I have activated the hotkey. It won't work on the same instance of MPV anymore. Is there some way I can prevent this, by it only affecting the current instance and I were to overwrite to a different path. I don't want the files to be loaded anymore till I press the hotkey.

**Comment by escapezn** [comment]
In my environment the keybind is always available even if playlist was replaced by files somewhere else, for the same instance of mpv. Not clear about what situation you encountered, maybe conflicted with other scripts?

**Comment by Kayizoku** [comment]
> In my environment the keybind is always available even if playlist was replaced by files somewhere else, for the same instance of mpv. Not clear about what situation you encountered, maybe conflicted with other scripts?

Sorry, I think I didn't do a good job of clarifying myself. What I meant was that MPV will after you've pressed Autoload hotkey keep on autoloading all other files you insert into the MPV or change to a different folder. Untill you exit out, or open a new instance, then all the files won't be loaded till I press the hotkey. Hopefully, that makes more sense

**Comment by escapezn** [comment]
That's strange. I noticed autoload.lua just be executed for once after pressing the key. As long as other files to be loaded there is only a single item in playlist, if I want to load all files in the folder I have to press the kotkey again.

**Comment by escapezn** [comment]
Did you commented `mp.register_event("start-file", find_and_add_entries)` out?

**Comment by Kayizoku** [comment]
> Did you comment `mp.register_event("start-file", find_and_add_entries)` out?

Yes, I did that. Otherwise, it would just load all the files the second I open MPV, which would defeat the purpose of a hotkey

**Comment by escapezn** [comment]
OK sure. Sorry I have no idea about your problem...

**Comment by Kayizoku** [comment]
> Reference in n

It's completely fine. I was able to at least make Autoload react when I wanted, that's plenty for now. Thank you
