### ISSUE TITLE
seeking youtube problem

### ISSUE THREAD

**Issue by Littlemac123** [mpv-player/mpv#9669]
every damn time i run the command "mpv https://youtu.be/jIku1jBMDjI"

it wont let me seek to a spot in the video that i want to go to it fails,

**Comment by CounterPillow** [comment]
Works for me.

You should have filled out the issue template if you wanted actual help.

**Comment by Dudemanguy** [comment]
Issue template ignored + there's probably not an actual bug (i.e. works on my machine) so closing.
