### ISSUE TITLE
Mpv yt-dlp issue (also vp9)

### ISSUE THREAD

**Issue by Animationss** [mpv-player/mpv#9672]
### Important Information

Provide following Information:
0.32.0
Pop os 
- Source of the mpv binary ?
0.30.0 or 0.31.0
- Window Manager and version ?
- GPU driver and version ?
- Possible screenshot or video of visual glitches
![unknown](https://cdn.discordapp.com/attachments/807247901981016094/927919389045583902/unknown.png)
![unknown](https://cdn.discordapp.com/attachments/807247901981016094/927919921738940436/unknown.png)
(I fixed the typo)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

This issue is Reproducible even without doing all these steps it will happen whenever i try to play a video with mpv 

### Expected behavior
![yt-dlp-7-FSMdotCOM-768x429](https://user-images.githubusercontent.com/89710296/148070877-be9c0042-d6b3-4dea-a9ef-9238d25c5ed3.png)

plays video smoothly with yt-dlp

### Actual behavior

Very laggy and studdery
Freezes every 3 ish secs 

### Log file

https://pastebin.com/raw/EhJ9DLSJ

(dont know how to use 0x0.st)

**Comment by LaserEyess** [comment]
Your mpv is unsupported, you have to talk to popOS about this, unless you can reproduce with the latest stable or git master. Your issue doesn't seem related to yt-dlp, you have broken drivers it seems, or your GPU doesn't support vp9. Impossible to say since you didn't fill out the issue template. Furthermore you log file is wrong, it shows nothing of your issue.

**Comment by Animationss** [comment]
Welp thats strange cause stream link gui works fine with mpv but 1080p 1440p and 4k on yt wont ? 
And I started to compile mpv myself and im running into a few issues with ffmpeg, Maybe after I figure that out 
ill work cause I don't think my drivers r broke cause games work just fine but I could always be wrong.


(ffmpeg problom) 
![image](https://user-images.githubusercontent.com/89710296/148123341-d4c1703e-b9c8-43b7-8c38-6c06b86921b1.png)

**Comment by garoto** [comment]
Your mpv binary needs to be built from master after "Oct 27, 2020" for "script-opts=ytdl_hook-ytdl_path=yt-dlp" to work.

**Comment by Dudemanguy** [comment]
As noted, your mpv is too old for the `script-opts=ytdl_hook-ytdl_path=yt-dlp` to work. `yt-dlp` has also been preferred since 0.34 so your best bet is to simply update.
