### ISSUE TITLE
`mpv: symbol lookup error: mpv: undefined symbol: wl_proxy_marshal_flags` error on startup

### ISSUE THREAD

**Issue by Seme4eg** [mpv-player/mpv#9676]
- mpv version: 1:0.34.0-4
- Linux Distribution and Version: Manjaro Linux 21.2.0
- Source of the mpv binary: official repositories (community)
- Window Manager and version: gnome

### Reproduction steps

installed with 'sudo pacman -S mpv', installed all deps, tried to run, got just this error, no error trace, just the string from the name of the issue.

### Log file

Can't generate one, even with --log-file=mpvlog.txt.

**Comment by sfan5** [comment]
Your package maintainers forgot to recompile the package. Ask them.
