### ISSUE TITLE
gpu-next: lut based tone-mapping looks different from glsl based one.

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9678]
the new one looks slightly dimmed, and drop color in very low nit.
sample: https://www.youtube.com/watch?v=C4lM87MD9FQ

```ini
hdr-compute-peak=no
tone-mapping=bt.2390
tone-mapping-desaturate=0
gamut-clipping=no
```
![glsl](https://user-images.githubusercontent.com/50797982/148506084-0c3fd024-528a-43a6-84a8-8d2df2338e85.png)

```ini
hdr-compute-peak=no
tone-mapping=bt.2390
tone-mapping-crosstalk=0
gamut-mapping-mode=clip
```
![lut](https://user-images.githubusercontent.com/50797982/148506296-f42d166b-e99b-4d66-abc3-77013c44e073.png)

```ini
hdr-compute-peak=no
tone-mapping=bt.2390
tone-mapping-mode=rgb
tone-mapping-crosstalk=0
gamut-mapping-mode=clip
```
![lut](https://user-images.githubusercontent.com/50797982/148506110-a0ec6d39-6bad-46e2-a71b-50fd5edcb20e.png)

**Comment by Natural-Harmonia-Gropius** [comment]
`lut-type=native/normalized` also clips out the very dark areas.

**Comment by Natural-Harmonia-Gropius** [comment]
maybe move color coversation to fully lut based can solove this, and make it more robust.
https://github.com/mpv-player/mpv/issues/9403#issuecomment-1007240716 https://github.com/mpv-player/mpv/issues/9435#issuecomment-1008348237

**Comment by haasn** [comment]
> maybe move color coversation to fully lut based can solove this, and make it more robust.

Have you tried `--lut=<file> --lut-type=conversion`?

**Comment by Natural-Harmonia-Gropius** [comment]
> Have you tried `--lut=<file> --lut-type=conversion`?

this worked fine.
give me 2 minutesvto take a screenshots.

**Comment by Natural-Harmonia-Gropius** [comment]
```
vo=gpu-next
gpu-api=vulkan

hdr-compute-peak=no
tone-mapping=linear
tone-mapping-mode=rgb
tone-mapping-crosstalk=0
gamut-mapping-mode=clip
```
lut [keep.zip](https://github.com/mpv-player/mpv/files/7837171/keep.zip)

`lut-type=native`
![image](https://user-images.githubusercontent.com/50797982/148727075-d1d43cd5-51a5-4477-a69f-4feea4b641f0.png)
`lut-type=normalized`
![image](https://user-images.githubusercontent.com/50797982/148727093-a11b1d66-5fdd-4de5-ae63-6119eff4c9dd.png)
`lut-type=normalized`
![image](https://user-images.githubusercontent.com/50797982/148727111-988b6476-dba8-4171-a378-c72150368e09.png)

**Comment by Natural-Harmonia-Gropius** [comment]
seems only happens with `normalized`, I add these into conf to match input.
```
target-prim=bt.2020
target-trc=pq
target-peak=1000
```
native
![image](https://user-images.githubusercontent.com/50797982/148730024-6c584158-6fd7-489a-baad-b33c70548683.png)
normalized
![image](https://user-images.githubusercontent.com/50797982/148730052-062c5dac-4c35-4d76-a0e5-1539a51ce83e.png)
conversion
![image](https://user-images.githubusercontent.com/50797982/148730245-00b764b8-66ac-4585-b8ff-67d7aeaa70b0.png)

**Comment by haasn** [comment]
Is this still the case on libplacebo master? Also, can you try testing with `target-prim=bt.2020`?

**Comment by Natural-Harmonia-Gropius** [comment]
> Is this still the case on libplacebo master? Also, can you try testing with `target-prim=bt.2020`?

yes


```ini
hdr-compute-peak=no
tone-mapping=bt.2390
tone-mapping-mode=rgb
tone-mapping-crosstalk=0
gamut-mapping-mode=clip
```

`target-prim=bt.2020`
`hsl(0deg 0% 0%)` in both 0 and 16.
![image](https://user-images.githubusercontent.com/50797982/149138254-828a61b2-c0f9-4748-8374-b069b7319dc6.png)

`target-prim=bt.2020 target-trc=pq target-peak=999`
`hsl(0deg 0% 2%)` in 0, `hsl(0deg 0% 75%)` in 1024.
![image](https://user-images.githubusercontent.com/50797982/149138285-c6478103-6b42-47a4-9c1c-89cc0f5fcff5.png)

`target-prim=bt.2020 target-trc=pq target-peak=1000`
match the input, everythings fine.
![image](https://user-images.githubusercontent.com/50797982/149138337-fe5d4cb3-be95-4913-9edf-53dc4d6e4947.png)

`target-prim=bt.709 target-trc=pq target-peak=1000`
`hsl(0deg 0% 1%)` in 0, `hsl(120deg 14% 1%)` in 16, `hsl(0deg 0% 75%)` in 1024
![TestPattern_ ST2084-BT2020-D65-00_00_01 418-0001](https://user-images.githubusercontent.com/50797982/149139321-b18b5d65-fd9f-4fac-82e2-d88c83d7954a.png)

**Comment by Natural-Harmonia-Gropius** [comment]
icc profile could make 16 visible again. but also boost brightness in dark area.
https://github.com/mpv-player/mpv/files/7490829/Rec.709.zip
![image](https://user-images.githubusercontent.com/50797982/150672702-81cd1b13-d33f-47df-9df9-0f18df03b45e.png)

**Comment by Natural-Harmonia-Gropius** [comment]
fixed by https://github.com/haasn/libplacebo/commit/0d7b97d660cc693c3cf5adfeb91e54f20e1e4c10
