### ISSUE TITLE
gpu-next: failed initializing GPU context

### ISSUE THREAD

**Issue by Robot-DaneelOlivaw** [mpv-player/mpv#9680]
### Important Information

Provide following Information:
- mpv version
https://github.com/mpv-player/mpv/commit/d09c73c7b2b0135cb24ab2173b3c4ee1c55840b0
- macOS version
macOS 12.1 (intel)
- Vulkan version
1.2.198.1
- libplacebo version
v4.157.0-230-gb260440 (API v192)
- Source of the mpv binary or bundle
Self compiled
- If known which version of mpv introduced the problem
Not able to make it work since the introduction of gpu-next

### Reproduction steps
```
mpv ~/Movies/jellyfish-3-mbps-hd-hevc-10bit.mkv --no-config --vo=gpu-next --gpu-api=vulkan --gpu-context=displayvk --log-file=~/Library/Logs/mpv/mpv.log
```

### Expected behavior
Play the video normally.

### Actual behavior
Unable to play video with an error: `[vo/gpu-next] Failed initializing any suitable GPU context!`

### Log file
https://0x0.st/ozku.log

**Comment by Akemi** [comment]
because there is no gpu-next macos backend. it's not expect to work let the auto selection do its work.

**Comment by Robot-DaneelOlivaw** [comment]
Thank you for pointing that out. :) Didn't know that it's not supported.
