### ISSUE TITLE
PPA repository ?

### ISSUE THREAD

**Issue by Animationss** [mpv-player/mpv#9681]
Is there a ppa repository I can use to download the latest version of mpv because Ive been having problems trying to install mpv by compiling or mpv builder ill help a bunch.

**Comment by LaserEyess** [comment]
https://mpv.io/installation/

**Comment by mailinglists35** [comment]
https://launchpad.net/~savoury1/+archive/ubuntu/mpv

**Comment by winstonma** [comment]
Please check **option 2** of [How to Install Latest MPV video player 0.35 in Debian 11, Ubuntu 22.04 | 20.04](https://fostips.com/install-mpv-media-player-debian/) to get apt working

**Comment by SuzukiHonoka** [comment]
> https://launchpad.net/~savoury1/+archive/ubuntu/mpv
> 
> also don't forget the alternate graphic drivers https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

Thanks, this is most useful!

**Comment by SuzukiHonoka** [comment]
> https://mpv.io/installation/

It only support amd64 in apt repo.
