### ISSUE TITLE
Can libmpv convert timestamp to byte offset?

### ISSUE THREAD

**Issue by Kelvin-Ng** [mpv-player/mpv#9684]
### Expected behavior of the wanted feature
Have an API so that given a segment of video file, tell me the corresponding byte offset according to the starting timestamp built in the video format.

### Alternative behavior of the wanted feature
Have an API so that given a timestamp, tell me the corresponding byte offset. (I will try to figure out the starting timestamp of the segment myself).

I am using this together with the stream API. I know you can kind of achieve that by seeking and then get the byte argument from the read callback, but that interferes with the normal playing.

If necessarily, you can assume that the video format is "streaming-friendly". In particular, they will be in the Media Source Extensions Byte Stream Format.

**Comment by avih** [comment]
libmpv is a player, not media file analyzer. Use some other tool to convert a timestamp to byte offset in a file (also, there might be more than one, e.g. the video and audio packet, depending on muxing)..
