### ISSUE TITLE
Upgrade from 0.32 to 0.33  I have lost my TV chanell 

### ISSUE THREAD

**Issue by Froas** [mpv-player/mpv#9685]
### Important Information

Provide following Information:
- mpv version - 0.33
- Linux Distribution and Version - ubuntu 20.04
- Source of the mpv binary - lp_ppa_mc3man_mpv_tests-focal-main
- If known which version of mpv introduced the problem - 0.33
- Window Manager and version GNOME Shell x11
- GPU driver and version nvidia-driver 460
- Possible screenshot or video of visual glitches

Hello everyone. It is my first issue ticket, sorry if make a mistake. I try to describe my problem step by step. After I had been installed mpv 0.32 I noticed 4-5 mpv's icons app with some Japanese TV name. When I opened it, It was starting to stream Japanese TV. I really don't know how they had been installed, but it was really useful for my learning Japanese. Yesterday I updated my mpv from 0.32 to 0.33 and I have lost all my tv streaming  channel. I have to return it back, but I don't know how.  Can you help me? 

P.S. Channels have same mpv icons, but their name were corresponding tv channel. When I open the TV channel, there is a link in the title of mpv.  Unfortunate I don't have any screenshot or logfile :( 

P.S.S. I have tried to downgrade mpv 0.32 and the channel hasn't appearance

**Comment by ChrisK2** [comment]
Hi,

The mpv team does not ship any shortcuts to any streams with mpv. The only explanation for you getting those shortcuts in the first place is a mistake by the person making that mpv binary. I guess they accidentally bundled them with the PPA or something. The mpv team is not involved in the creation of that PPA, so we can't help you at all. But maybe the maintainer of that PPA [mc3man](https://launchpad.net/~mc3man) can help you with getting those shortcuts back.
