### ISSUE TITLE
Use libmpv to play frames without demuxing?

### ISSUE THREAD

**Issue by Kelvin-Ng** [mpv-player/mpv#9689]
### Expected behavior of the wanted feature
I already have a list of coded frames demuxed from a container. I want to be able to directly play these frames, effectively skipping the demuxer of mpv. I can't find existing API that can achieve that.

I have looked into the source code of mpv. It seems that I can potentially achieve that by implementing my own `struct demuxer_desc`, and feed my frames using the stream API. In the `demuxer_desc`, the `seek` function will call `stream_seek()`, abusing the `pos` parameter as `pts`. The `read_packet()` function will call `stream_read()` and ultimately the user-provided read callback, which will provide the frame corresponding to the `pos` (which is now abused as `pts`). Then, the `read_packet()` function will wrap the data as a `demux_packet`. Inside the `demux_packet`, the `pos` will be again abused and have the same value as `pts`.

When passing `pts` as `pos`, they are multiplied by 1e9 to convert to integer.

Is there a better/easier/cleaner solution than that? If not, do you think the above proposal will work out? (Like I won't fall into some trap and break the whole system?)

Thank you!

**Comment by avih** [comment]
In your copy of (lib)mpv you can do anything (subject to the license terms), but we won't add it to the official API, because libmpv is a playback control API - not media construction.

**Comment by Kelvin-Ng** [comment]
@avih I think I have a convincing reason for this feature. Would you please reconsider after seeing my reason?

I am not using the feature for media construction. I use it for playing media in adaptive bitrate. Using WebM as an example. The video source has multiple WebM files for different bitrates of the same video. The video source will push WebM clusters of different bitrates (from different WebM containers) to the player according to the current connection speed. So, the stream API that is based on byte offsets will not work because the clusters are from different files and don't have a consistent byte offset. So, I decide to parse and demux the WebM clusters to get the individual frames, sort them in the timestamp order, and feed to libmpv in some way.

Is there an existing API that can help me play adaptive bitrate streams like this? If not, do you think this is a convincing reason for adding the proposed feature? Thank you.
