### ISSUE TITLE
mpv shouldn't complain about missing libcuda.so.1

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#9691]
* mpv version: 0.34.1
* Linux Distribution: Debian testing.
*  Source of the mpv binary: Debian testing repo.
* Window Manager and version: KDE Plasma 5.23.5
* GPU driver and version: AMD, Mesa 21.3.3

Every time I run mpv it complains about missing libcuda.so.1:

```
Cannot load libcuda.so.1
```

This looks like noise, especially since CUDA is Nvidia only. Can you please remove this error message when it's not relevant?

**Comment by CounterPillow** [comment]
Doesn't happen for me, post a full log file like the issue template asks you to.

**Comment by sfan5** [comment]
This log message is generated by ffnvcodec, which is used by ffmpeg (*not* mpv) for CUDA integration.
I doubt we can do anything about this.
<pre>
ffnvcodec-headers-git.git/src/nv-codec-headers/include/ffnvcodec/dynlink_loader.h
85:            FFNV_LOG_FUNC(logctx, "Cannot load %s\n", path);   \
95:            FFNV_LOG_FUNC(logctx, "Cannot load %s\n", symbol);   \
105:            FFNV_DEBUG_LOG_FUNC(logctx, "Cannot load optional %s\n", symbol); \
</pre>

**Comment by shmerl** [comment]
@sfan5: Does ffmpeg automatically load it regardless of whether CUDA is available or not? Should I file a bug for ffmpeg about it?

**Comment by 42147** [comment]
I have this fix from way back on my mpv.conf:

> # Default (auto) results in "cannot load libcuda.so.1"
> gpu-hwdec-interop=vaapi-egl

**Comment by shmerl** [comment]
I'm actually already using vaapi like this:

```
hwdec=vaapi
gpu-context=x11egl
```

So it's kind of strange it even tries to use ffnvcodec and CUDA.

**Comment by shmerl** [comment]
Since that option limits what backends are probed, does it mean mpv **can** decide that after all? I.e. then it doesn't make sense to probe ffnvcodec on AMD, no?

**Comment by laichiaheng** [comment]
Same here, I build mpv-build-git from AUR.

**Comment by sfan5** [comment]
>does it mean mpv **can** decide that after all? I.e. then it doesn't make sense to probe ffnvcodec on AMD, no?

Few things are _actually_ impossible but merely not feasible, this is one of them. Nobody wants to write the possibly OS-specific code to detect the vendor and handle possible edge cases (for example it is perfectly okay to decode on an NVIDIA gpu and render on an AMD gpu, if you have both in the same machine).
This is much better fixed if ffmpeg hooks up ffnvcodec to the normal log callbacks.

**Comment by shmerl** [comment]
I can open a bug for ffmpeg, if you help with suggesting how to phrase it.

**Comment by skrat** [comment]
@42147 thanks for this, this helped removed the huge delay I had when starting mpv, ie.

```
[   0.828][d][vo/gpu/vaapi-egl]  p010
[   0.828][d][vo/gpu/vaapi-egl]  argb
[   0.828][d][vo/gpu/vaapi-egl]  abgr
[   0.828][d][vo/gpu/vaapi-egl]  rgb30
[   0.828][v][vo/gpu/vaapi-egl] Done probing surface formats.
[   0.828][v][vo/gpu] Loading hwdec driver 'cuda-nvdec'
[  10.687][v][vo/gpu/cuda-nvdec] cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[  10.688][v][vo/gpu] Loading failed.
[  10.688][v][vo/gpu] Loading hwdec driver 'drmprime-drm'
[  10.688][v][vo/gpu/drmprime-drm] Failed to retrieve DRM fd from native display.
[  10.688][v][vo/gpu] Loading failed.
[  10.688][v][vd] Trying hardware decoding via h264-vaapi.
[  10.689][v][vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[  10.689][v][vf] User filter list:
```

And just FIY, I already had hwdec=vaapi in the conf. file. So I dunno why is it trying to open those other drivers. I also tried setting `LIBVA_DRIVER_NAME=iHD` to no help.

**Comment by ValZapod** [comment]
Csn it be that ffmpeg got vaapi / nvdec interconnect somehow? Like it DID with qsvdec.
