### ISSUE TITLE
Get native screen resolution in shaders?

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9692]
Is there a way to get the output screen resolution in a GLSL shader?

target_size seems to be not that what I'm looking for. For explanation: I wrote a shader to correct the geometric distortion of a curved screen ("warping"). And if the picture is scaled additionally the curvature must be applied to the whole screen resolution (e.g. 3820x2160) and not to the down-scaled part of the source picture.

**Comment by haasn** [comment]
There's not really any good way to access arbitrary properties from shaders currently, apart from a few hard-coded built-in properties that have a cost associated with them.

I expect it to be unlikely for something like this to be added any time soon, at least not in the current form of the shader subsystem. (I plan on reworking the way that is handled in `vo_gpu_next`, so expect changes sometime down the line)

**Comment by FoLLgoTT** [comment]
Ok, thank you. It is not a big deal at the moment, because I laways use the same screen resolution. I leave it hard coded in the shader.
