### ISSUE TITLE
mpv prevent  Xscreensaver to run

### ISSUE THREAD

**Issue by bluebyt65** [mpv-player/mpv#9693]
mpv prevent Xscreensaver to run, I have the option "no-stop-screensaver" in the config file.

Version mpv-1:0.34.1 (I downgraded to version mpv-1:0.34.0 the bug is not present) 

Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.13-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 6 × Intel® Core™ i5-9600K CPU @ 3.70GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630

mpv.conf
no-stop-screensaver
hr-seek=always
force-window=yes
autofit-larger=30%x30%
loop-playlist
vo=gpu
save-position-on-quit

When the option "no-stop-screensaver" is in mpv.conf the screensaver should run, that was happened in the previous version mpv-1:0.34.0

Here the log file
[output.txt](https://github.com/mpv-player/mpv/files/7835363/output.txt)

**Comment by LaserEyess** [comment]
Please fill out the issue template properly. There's no log file, and most importantly: what do you WANT to happen with those options?

**Comment by Dudemanguy** [comment]
xscreensaver doesn't work on wayland (obviously). According to your log, the idle inhibitor isn't enabled which means the screensaver should be still enabled (which I gather is what you want).

**Comment by bluebyt65** [comment]
I re-installed the latest version and now its working, I will close this issue.
How do we know the idle inhibitor isn't enabled in the log file?

**Comment by LaserEyess** [comment]
You would see lines like this if it was active:
```
[   0.138][v][vo/gpu/wayland] Enabling idle inhibitor
[   0.614][v][vo/gpu/wayland] Disabling the idle inhibitor
```

**Comment by Dudemanguy** [comment]
Enabling the idle inhibitor is normally logged as `Enabling idle inhibitor` when using wayland. Since that line wasn't in your log file, I must not be enabled.
