### ISSUE TITLE
Specify key to action?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9698]
I'm using an air mouse which looks like this:
![image](https://user-images.githubusercontent.com/13978119/148999090-d5c6ce89-3191-4d8c-8f4e-a3d489c4b775.png)

And I want to set a key (since it's not a keyboard) that will do ALT+TAB,
for example:
```DEL     ALT+TAB```

Something like that is possible to do with mpv?

**Comment by CounterPillow** [comment]
Why not just bind DEL to the action you want to perform?

If you want it to actually register as an alt+tab event in your OS, then no, mpv cannot do this as it is not a device driver or input remapper.

**Comment by Obegg** [comment]
> Why not just bind DEL to the action you want to perform?
>
The action I want to perform is `ALT+TAB`, which is switching between windows.


> If you want it to actually register as an alt+tab event in your OS, then no, mpv cannot do this as it is not a device driver or input remapper.
>
Got it, thank you!
