### ISSUE TITLE
[cplayer] Option --gamut-clipping was removed

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9700]
I'm using ```--gamut-clipping=no``` and I get this error:
```[cplayer] Option --gamut-clipping was removed: Replaced by --gamut-mapping-mode-desaturate```

How can replicate my previous setting ```--gamut-clipping=no``` to the new setting ```--gamut-mapping-mode-desaturate```?

**Comment by hooke007** [comment]
`gamut-mapping-mode=clip`

**Comment by Obegg** [comment]
> `gamut-mapping-mode=clip`

It would be nice if there was some [documentation](https://mpv.io/manual/master/) on it, because I couldn't find any information about it.
But `gamut-mapping-mode=clip` would mean the same as `gamut-clipping=yes`.
The result I want is `gamut-clipping=no`.

**Comment by hooke007** [comment]
> It would be nice if there was some documentation on it

https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst#gpu-renderer-options
