### ISSUE TITLE
MPV hangs and crashes while switching to fullscreen

### ISSUE THREAD

**Issue by Shytindo** [mpv-player/mpv#9704]
New to MPV and I use the default set up, everything was working well until I switched to fullscreen.
Video will hang and eventually MPV will crash after long hang. This only happens in MPV.

Important Information

    mpv version: mpv-x86_64-20220109-git-777628e
    Platform and Version: Windows 8
    Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/

Reproduction steps

    start mpv
    enable fullscreen

Expected behavior

enable fullscreen with no hang and crash

Actual behavior

mpv hangs and has to be force-closed

**Comment by aufkrawall** [comment]
Log? If this is with AMD Windows Vulkan driver: No dice, eternal driver bug.

**Comment by Jules-A** [comment]
> 

Except that was partially fixed, if content is supplied it won't occur, it only happens when you open MPV without any content now.

**Comment by ValZapod** [comment]
That happens to me sometimes when it is out of memory.
