### ISSUE TITLE
Raising of levels near black possible?

### ISSUE THREAD

**Issue by mr-berndt** [mpv-player/mpv#9705]
Is there a way to scale the video output to match the black levels to that of the display device?

MadVR has this feature, which is very handy: You can set the value for video level 16 to be scaled to 18 for example. That compensates for displays that cannot do true black (so most of them, especially projectors, though). This helps quite a lot of shadow-detail to be visible again.

In the end the entire range has to be scaled accordingly, to fit into the new given range, e.g. 18 to 235 or 4 to 255.

**Comment by haasn** [comment]
mpv should already do this automatically (especially with `--vo=gpu-next`), I'm not sure what more you want/need exactly

**Comment by mr-berndt** [comment]
I am afraid you understood me wrong and refer to tv-levels vs. full levels (16-235 / 0-255). That is not what I meant. These are working fine.

I'll try to explain again. For the further examples let's assume tv-levels, where 16 is black.

What I meant is that my projector and many displays are not capable of showing differences in a test pattern with steps near black, like 20,19,18,17,16. On my projector everything below 19 is just black, so all details in that range is simply lost. MadVR lets one give a value, lets say 19 to be the new reference black and then scales all the video levels accordingly into this new window from 19 to 235. So 16 is lifted to 19, 17 to ~20 and so on.

Another way to maybe explain it would be in Nits: Let's say the darkest a projector can to is 10 Nits, then content which should have 2 Nits would be lost in the blac-floor, just as content with 9 Nits would be. Practically everything below 10 Nits would be lost. If the player would know this threshold an scale the two Nits to around 12,  it would be displayed just the correct 2 Nits above my black-floor. 

This feature really helps getting quite a bit more shadow-detail out the image. Just coming from MadVR this is the only thing left that I am missing. For all the rest mpv is equal or better in my opinion. :)

mpv cannot do this automatically because it cannot know the capability of my display device to display near-black.

**Comment by Natural-Harmonia-Gropius** [comment]
sounds like things about gamma-factor

**Comment by mr-berndt** [comment]
Just installed madVR in a VM and made a screenshot. Maybe this explains it better:

![madVR_levels](https://user-images.githubusercontent.com/11179748/149312924-7033534d-6b4e-4a96-a785-bbafd9e33ba9.PNG)

**Comment by haasn** [comment]
Seems like a weird hack. Yeah, I'd probably just use a shader like that.

Better would be to calibrate your projector properly. Or use an ICC profile.

**Comment by mr-berndt** [comment]
It is not a matter of a wrong Gamma, it is just what projectors are not capable off. Especially JVC have their problems with near-black. There is simly no way to compensate for that within the projector itself. The only option is to do that externally. Since this is a very common problem, madVR at one point came up with controls for that, which I think is a very nice idea in general.

The projector is calibrated with ICC-Profiles, part loaded in the OS and part in mpv, so just the way it is supposed to be. Interestingly the ICC-profiles do not take care of the near-black issue, I would acutally expect that. Up until recently I used 3D-LUT correction, which did take care of the issue.

Thanks anyway for the shader, I will try this later and I guess it should solve the problem at least for me.

**Comment by lextra2** [comment]
Sounds like you wanna clip some highlights/shadows to compensate for the bad contrast ratio of your projector?

https://ffmpeg.org/ffmpeg-filters.html#colorlevels
or
https://ffmpeg.org/ffmpeg-filters.html#pp

probably works. Or the shader posted above.

**Comment by mr-berndt** [comment]
Actually it is a JVC X7500, in other words: Very hard to beat contrast. What is does though, is clips near-black a little.

Anyway, thx for all the hints, raising black level worked but did more harm to the shadow-detail than good. A simple test with a gamma eq showed, that this would be indeed a better way to go but after all my ICC profiles should take care of it and so I will see what I can optimize there.

**Comment by lextra2** [comment]
Why would you try to adjust this in software? Just adjust "Dark Level" under "Gamma" inside your projector settings. All of these solutions cause clipping anyways.

**Comment by mr-berndt** [comment]
Older JVC models used to have a good black point correction, the setting you mentioned tends to hurt shadow-detail, from what I see. It quickly gets milky.

All in all the issue is super-small, because my projector-setup is very good as it is. Just always looking for improvements. ;)

**Comment by ValZapod** [comment]
> That compensates for displays that cannot do true black (so most of them

I use LG C9 with old before v4.80 firmware that can and does do the perfect black in all SDR and HDR modes. So, yeah.
