### ISSUE TITLE
Doesn't autoplay when opening a file from the finder if already open

### ISSUE THREAD

**Issue by ghazel** [mpv-player/mpv#9707]
### Important Information

Provide following Information:
- mpv version 
0.34.1
- macOS Version
12.1
- Source of the mpv binary or bundle
Homebrew
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Open a video from Finder (should auto-play)
Hit pause
Open another video from Finder

### Expected behavior

Autoplay

### Actual behavior

Opens video stopped at the beginning

Related: https://github.com/mpv-player/mpv/issues/4866

**Comment by dyphire** [comment]
You can try set `reset-on-next-file=pause`

**Comment by Akemi** [comment]
that's intended behaviour. see @dyphire reply.

**Comment by ghazel** [comment]
Why is this intended behavior? It is not the way other video players work, and it was not expected.

**Comment by Akemi** [comment]
the intended behaviour is just not the same behaviour you expect. mpv won't reset any options or settings without you explicitly telling mpv to do so and you can change that behaviour.

**Comment by ghazel** [comment]
It certainly does reset options and settings, in the sense that it completely replaces the file being viewed. I don't know why settings from the previous viewer would apply -- killing and restarting mpv when a new file is opened would behave as expected.

**Comment by dyphire** [comment]
> It certainly does reset options and settings, in the sense that it completely replaces the file being viewed, and changes window size and location accordingly. I don't know why settings from the previous viewer would apply -- killing and restarting mpv when a new file is opened would behave as expected.

https://mpv.io/manual/master/#options-reset-on-next-file
You should see the options in the reference manual. It explains very clearly.
