### ISSUE TITLE
Problem displaying a star symbol from subtitles

### ISSUE THREAD

**Issue by UndeadKitten** [mpv-player/mpv#9708]
MPV example:
![MPV Symbol Test](https://user-images.githubusercontent.com/30302861/149396994-dc6ad83b-70f9-475f-b834-9d9d657ec75d.png)

MPC-BE example:
![MPC-BE Symbol Test](https://user-images.githubusercontent.com/30302861/149397021-f07e4491-25e0-44df-ab91-110e51544b20.png)

Video file used:
https://drive.google.com/file/d/13c3yNJMTAge4qxBbrX4pEKzVxLaYztwA/view?usp=sharing

**Comment by Tsubajashi** [comment]
What mpv Version did you use, on what operating System? That's not really enough Info to go with.

**Comment by UndeadKitten** [comment]
> What mpv Version did you use, on what operating System? That's not really enough Info to go with.

I'm on Windows 10 and I used the latest version on SourceForge at the time (mpv-x86_64-20220109-git-777628e), issue persists on the current latest version of SourceForge (mpv-x86_64-20220116-git-1ba0547). I left the settings unchanged on both mpv and MPC-BE.

**Comment by jimmy-1000** [comment]
Interesting, VLC has the same problem, MPC-HC not.
I'm Windows 7 64bits SP1

**Comment by Dudemanguy** [comment]
This worked for me.

![Sayonara Zetsubou Sensei - S01E01-00 10 36 235-00 10 50 21900:00:08](https://user-images.githubusercontent.com/5105515/211375655-09ecefbf-2711-412f-9250-ac9d6ad2ffff.jpg)

Possibly something to do with missing fonts and/or your OS settings. Shouldn't be an mpv issue an any case (this would be libass).
