### ISSUE TITLE
Cant disable fullscreen mode when video resolution==screen resolution

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#971]
Hi!
I have 1920x1080 monitor, and when i watch FullHD videos - program automaticly opens fullscreen window (without pressing "F" and CLI options), and i cant leave fullscreen mode.
This bug didnt appear when i watch other res videos - it opens normal window and  switching between fullscreen/window mode is perfect.

This bug was reproduced on Linux mint 14, Linux mint 17, FreeBSD 10

If some evidence is needed - i can capture screen => upload screencast into youtube and show u this bug

Regards, Xdevelnet

**Comment by hashn0n** [comment]
I have the same problem on Gentoo on my notebook:
ASUS UX52V:
Intel(R) Core(TM) i5-3317U
NVIDIA GeForce GT 645M
x11-drivers/nvidia-drivers-396.54

I use Compiz Reloaded v0.8.14
mpv -v ./VID_20180930_114533633.mp4 &>./VID_20180930_114533633.log
https://pastebin.com/VjL6f1zy
