### ISSUE TITLE
Feedback request for Contrast Adaptive Sharpening shader port

### ISSUE THREAD

**Issue by agyild** [mpv-player/mpv#9711]
I have [ported](https://gist.github.com/agyild/bbb4e58298b2f86aa24da3032a0d2ee6) AMD's [Contrast Adaptive Sharpening](https://gpuopen.com/fidelityfx-cas/) shader to mpv along with ReShade's modifications. However, since this is my first shader port, I would appreciate some feedback from more experienced mpv shader developers before possibly including it in the wiki.

**Comment by haasn** [comment]
Hi, I added `HOOKED_gather` etc. functions to mpv master, which you can conditionally depend on (`#ifdef HOOKED_gather`):

```glsl
#ifdef HOOKED_gather
	vec4 red_efhi = HOOKED_gather(HOOKED_pos + 0.5 * HOOKED_pt, 0);

	vec3 e = vec3( red_efhi.w, red_efhi.w, red_efhi.w);
	vec3 f = vec3( red_efhi.z, red_efhi.z, red_efhi.z);
	vec3 h = vec3( red_efhi.x, red_efhi.x, red_efhi.x);
	vec3 i = vec3( red_efhi.y, red_efhi.y, red_efhi.y);

	vec4 green_efhi = HOOKED_gather(HOOKED_pos + 0.5 * HOOKED_pt, 1);

	e.g = green_efhi.w;
	f.g = green_efhi.z;
	h.g = green_efhi.x;
	i.g = green_efhi.y;

	vec4 blue_efhi = HOOKED_gather(HOOKED_pos + 0.5 * HOOKED_pt, 2);

	e.b = blue_efhi.w;
	f.b = blue_efhi.z;
	h.b = blue_efhi.x;
	i.b = blue_efhi.y;

#else
	vec3 e = ori.rgb;
	vec3 f = HOOKED_texOff(vec2(1.0, 0.0)).rgb;

	vec3 h = HOOKED_texOff(vec2(0.0, -1.0)).rgb;
	vec3 i = HOOKED_texOff(vec2(1.0, -1.0)).rgb;

#endif
```

**Comment by agyild** [comment]
> Hi, I added `HOOKED_gather` etc. functions to mpv master, which you can conditionally depend on (`#ifdef HOOKED_gather`):
> 
> ```glsl
> #ifdef HOOKED_gather
> 	vec4 red_efhi = HOOKED_gather(HOOKED_pos + 0.5 * HOOKED_pt, 0);
> 
> 	vec3 e = vec3( red_efhi.w, red_efhi.w, red_efhi.w);
> 	vec3 f = vec3( red_efhi.z, red_efhi.z, red_efhi.z);
> 	vec3 h = vec3( red_efhi.x, red_efhi.x, red_efhi.x);
> 	vec3 i = vec3( red_efhi.y, red_efhi.y, red_efhi.y);
> 
> 	vec4 green_efhi = HOOKED_gather(HOOKED_pos + 0.5 * HOOKED_pt, 1);
> 
> 	e.g = green_efhi.w;
> 	f.g = green_efhi.z;
> 	h.g = green_efhi.x;
> 	i.g = green_efhi.y;
> 
> 	vec4 blue_efhi = HOOKED_gather(HOOKED_pos + 0.5 * HOOKED_pt, 2);
> 
> 	e.b = blue_efhi.w;
> 	f.b = blue_efhi.z;
> 	h.b = blue_efhi.x;
> 	i.b = blue_efhi.y;
> 
> #else
> 	vec3 e = ori.rgb;
> 	vec3 f = HOOKED_texOff(vec2(1.0, 0.0)).rgb;
> 
> 	vec3 h = HOOKED_texOff(vec2(0.0, -1.0)).rgb;
> 	vec3 i = HOOKED_texOff(vec2(1.0, -1.0)).rgb;
> 
> #endif
> ```

Did you test it? Does it work on your end? On `mpv 0.34.0-127-g777628e761` on Windows, I get the following errors when I force it to use that branch:

> ```
> [vo/gpu/d3d11] input:58: error: 'HOOKED_gather' : no matching overloaded function found
> [vo/gpu/d3d11] input:58: error: '=' :  cannot convert from ' const float' to ' temp highp 4-component vector of float'
>```

**Comment by haasn** [comment]
I tested that it compiles, not that the output is correct. It's possible that the channel order is different between HLSL and GLSL gather functions, which would require changing the indices.

**Comment by agyild** [comment]
> I tested that it compiles, not that the output is correct. It's possible that the channel order is different between HLSL and GLSL gather functions, which would require changing the indices.

I have modified the code to take into account gather operations and texture coordinates. I think it should work properly, assuming `i` refers to x-coordinates and `j` refers to y-coordinates in the reference [documentation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/textureGatherOffset.xhtml).

**Comment by agyild** [comment]
@haasn Do you know which colorspace is used during the processing of mpv pixel shaders? Apparently CAS should be working in linear colorspace and I would like to know if there is a way to request linear colorspace from the shader code.
