### ISSUE TITLE
support for Lua 5.4

### ISSUE THREAD

**Issue by jonassmedegaard** [mpv-player/mpv#9712]
It [seems](https://github.com/mpv-player/mpv/blob/master/meson.build#L702) only Lua 5.1 and 5.2 are supported.  Both of those (and Lua 5.3 as well) are [has likely reached end-of-life](https://www.lua.org/versions.html).

Seems sensible to add support for linking with Lua 6.4 as well.

**Comment by LaserEyess** [comment]
Propbably a lot of the same arguments in #5205 are going to be re-hashed. If 5.4 doesn't have backwards compatibility with 5.1/5.2 it won't happen, thousands of user scripts would break.

**Comment by CounterPillow** [comment]
but number higher?????

**Comment by avih** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#Why_does_mpv_not_support_Lua_53_or_newer

**Comment by rubyFeedback** [comment]
I just ran into the same issue. I understand avih's pointer to the FAQ, but this is not applicable to every user. For instance I do not need support for older lua versions. Perhaps if the above reasoning is applied for longer, a configure switch could be added to meson to allow users to build with newer lua support. That way we can use that option, others can default to the older lua, and everyone is happy by being able to configure it to their liking. Right now I have lua 5.4.x installed and mpv keeps on whining on the commandline for every .mp3 file I play how support for lua 5.4.x is not there ... which is just plain annoying to read.

> thousands of user scripts would break

So, you cite one use case. I do not disagree that it is one valid use case.

How is the use case of people NOT having old lua scripts not valid, though? With the same reasoning we could use perl 4 or ruby 1.8.x or python 2.
