### ISSUE TITLE
Stop playlist when reaching the last file of a playlist?

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#9713]
Currently, I am using `p cycle-values loop-playlist force no` to loop a playlist. And this works perfectly. But I need the loop that wouldn't back the 1st file after reaching the end of a playlist.

I have already tried to find an answer to my question.

In mode `loop-playlist force` is it possible to avoid jumping back to the 1st file when it has reached the end of a playlist?

**Comment by Hrxn** [comment]
Don't use any `loop` options, just a normal playlist and the `--keep-open` option?

Not sure if I understand you correctly, but this sounds like what you are describing to me, more or less..

**Comment by Max-Enrik** [comment]
Thank you for your very valuable answer.
