### ISSUE TITLE
How to automatically pause at a specific time?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9716]
hi,

I want to know how I can make a video pause automatically at a specific time
Currently I'm doing this with `end=` 
but with this command the video stops 
I want to know how I can pause the video?
if someone could help me I would appreciated it. 

```
[ProfileName]
profile-cond=string.match(get("filename", ""), "NameOfVideo")~=nil
end=00:23:16
```

**Comment by guidocella** [comment]
Also use `--keep-open`.

**Comment by avih** [comment]
mpv doesn't have an option to pause at a specific time. You can use what you already did, or write a lua/js script which observes the timestamp and pauses once it's reached/ellapses.
