### ISSUE TITLE
[gpu-next] 60fps video + OSD = display sync audio drift

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9718]
### Important Information

Provide following Information:
- mpv version ```mpv 0.34.0-142-g1ba0547bfb```
- Windows Version ```Windows 10 Pro x64 21H2 19044.1466```
- Source of the mpv binary [sourceforge - shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/)
- If known which version of mpv introduced the problem: No
- Possible screenshot or video of visual glitches: Screenshot doesn't capture the issue

### Reproduction steps

```--no-config``` doesn't reproduce the issue, I'm sorry I'm unable to further test the issue, but it's probably my config's fault, so here it is:
[config.txt](https://github.com/mpv-player/mpv/files/7879731/config.txt)

### Expected behavior
Playback without issues

### Actual behavior
Playback with issues
Any OSD (stats or menu) is causing issues with playback

Without OSD = Playback without issues
With OSD = Playback with issues

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/7879816/log.txt)
Issue starts from this line (2330):
```[  18.401][d][cplayer] Run command: script-binding, flags=73, args=[name="stats/display-stats-toggle"]```

### Sample files
https://www.youtube.com/watch?v=VnLdOcDNTe0

**Comment by Obegg** [comment]
Did some testing and found out it also happens on videos that are 1080p 60fps ([example](https://www.youtube.com/watch?v=pfbAirb7Gds)).
So the problem is not the resolution, the problem seems to be with 60fps.
```vo=gpu-next``` + ```OCD``` + ```60fps video``` = display sync audio drift.

**Comment by hooke007** [comment]
looks like the performances i mentioned. https://github.com/mpv-player/mpv/issues/9551
Rendering osd make the case worse.

**Comment by Obegg** [comment]
I believe this issue has been fixed for `hwdec=d3d11va`, but not for vulkan (without hwdec) on Windows.

**Comment by Obegg** [comment]
I just realized that my issue is a duplicate of this https://github.com/mpv-player/mpv/issues/10716 ,so I'll close mine
