### ISSUE TITLE
Player freezes when unpausing with gpu-next + vulkan-queue-count=2 + display-resample

### ISSUE THREAD

**Issue by adisib** [mpv-player/mpv#9722]
### Important Information

Provide following Information:
- mpv version : 0.34.0-142-g1ba0547bfb
- Windows Version : Windows 10 Pro 21H1
- Source of the mpv binary : Self built with shinchiro win build
- If known which version of mpv introduced the problem : unknown
- Possible screenshot or video of visual glitches : NA

AMD RX 6800XT on latest driver 22.1.1

### Reproduction steps

Play any video using all of the following options:
--vo=gpu-next --gpu-api=vulkan --vulkan-queue-count=2 --video-sync=display-resample

Then when unpausing the video, the player can freeze and become unrecoverable. For the example I just mashed my spacebar a couple of times and it immediately showed up. If I remove any of the options this doesn't happen, so thinking it might not be a driver issue and maybe some sort of deadlock in libplacebo if it only happens with gpu-next and display resample.

### Expected behavior

Video pauses/unpauses.

### Actual behavior

Video player freezes. All I see is the last played frame, but it seems that audio can still play for a bit until I move my mouse. I cannot quit the player by pressing "q" and have to force kill the player with Ctrl+C in terminal. No special error messages in the terminal, and the player stops consuming resources.

### Log file

[mpvlog.txt](https://github.com/mpv-player/mpv/files/7885059/mpvlog.txt)

**Comment by haasn** [comment]
Can't reproduce either with mesa nor AMDVLK. However, this error seems likely relevant:

```
[   0.338][e][vo/gpu-next/vulkan/libplacebo] Failed presenting to queue 00000212b740a488: VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT
```

This looks like a driver bug. We don't enable the relevant extension, so those errors should never be returned by the driver. Also, the spec says that even when presentation fails with this error, the semaphore is still counted as signalled for the purposes of advancing queue dependencies. So it shouldn't deadlock.

But you could try running with `--gpu-debug` just in case. (Make sure you have vulkan debug layers installed)

**Comment by adisib** [comment]
That error happens when going into fullscreen but is unrelated to this issue. I should not have run with the fullscreen option when making the log, sorry. The freezing issue occurs when unpausing whether the player is in fullscreen or not.

**Comment by snylonue** [comment]
mpv version: `mpv 0.34.0-142-g1ba0547bfb`
Such freezing seems to happen with a GTX 1050 from time to time with config below
```
vo=gpu-next
gpu-api=vulkan
video-sync=display-resample
vulkan-queue-count=4
vulkan-async-transfer=yes
vulkan-async-compute=yes
```
Unfortunately the log was not kept due to the uncertainty of occurrence.
BTW I also suffered from freezing when switch to fullscreen at random.

**Comment by hooke007** [comment]
> The freezing issue occurs when unpausing whether the player is in fullscreen or not.

no fix yet.
https://github.com/mpv-player/mpv/issues/8008

**Comment by dyphire** [comment]
It also happens with a GTX 1060 when switch to fullscreen. mpv version: `mpv 0.34.0-142-g1ba0547bfb`
```
vo=gpu-next
gpu-api=vulkan
ontop
```
The freezing issue not happen when `ontop=no`

[log.txt](https://github.com/mpv-player/mpv/files/7892027/log.txt)

**Comment by snylonue** [comment]
> 

The freezing happened again
1. pause the video
2. minimize the window for a while
3. switch to fullscreen and unpause

the log seems to contain some error messages like ```[  46.425][e][vo/gpu-next/vulkan/libplacebo] Requested PTS 112.295647 is lower than the oldest frame PTS 112.445999. This is not supported, PTS must be monotonically increasing! Please use `pl_queue_reset` to reset the frame queue on discontinuous PTS jumps.```

[mpv.log](https://github.com/mpv-player/mpv/files/7914010/mpv.log)

**Comment by haasn** [comment]
> mpv version: `mpv 0.34.0-142-g1ba0547bfb` Such freezing seems to happen with a GTX 1050 from time to time with config below
> 
> ```
> vo=gpu-next
> gpu-api=vulkan
> video-sync=display-resample
> vulkan-queue-count=4
> vulkan-async-transfer=yes
> vulkan-async-compute=yes
> ```
> 
> ~Unfortunately the log was not kept due to the uncertainty of occurrence. BTW I also suffered from freezing when switch to fullscreen at random.~ update: the log is uploaded below

I've been using these settings for months now and still never been able to reproduce this issue. I can't realistically debug it without seeing it live, I think.

**Comment by Dudemanguy** [comment]
Does anybody still have this issue? I presume it's windows only.

**Comment by adisib** [comment]
I do not experience this issue anymore
