### ISSUE TITLE
deband grain has input video resolution size

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#9725]
### Important Information
- mpv version: mpv 0.34.1-dirty
- Linux Distribution and Version: Archlinux/rolling
- Source of the mpv binary: Archlinux package
- Window Manager and version: kwin_x11 5.22.5
- GPU driver and version: nvidia-495.46
- Possible screenshot or video of visual glitches:
![image](https://user-images.githubusercontent.com/1230726/150095576-b66a8aa3-b6f0-42f5-b62b-5524ebb55d4a.png)

### Reproduction steps
Try to play a video which is lower than resolution of your screen with debanding active:
```mpv https://0x0.st/ooiM.png --image-display-duration=inf --deband --deband-grain=4096 --fs```

See how dither behaves better:
```mpv https://0x0.st/ooiM.png --image-display-duration=inf --dither-depth=2 --fs```

OFC playing screen resolution videos (or prescaling to screen size) works ok with debanding:
```mpv https://0x0.st/ooiM.png --image-display-duration=inf --vf=scale=1920:-1 --deband --deband-grain=4096 --fs```

### Expected behavior
Debanding grain should have screen pixel size.

### Actual behavior
Debanding grain has input video pixel size.

### Log file
https://0x0.st/ooiB.txt

### Sample files
256x122 BW gradient: https://0x0.st/ooiM.png

**Comment by haasn** [comment]
This is expected and by design. If you would prefer to have grain at screen resolution, I would recommend disabling `--deband-grain` and using a shader like [this one](https://raw.githubusercontent.com/haasn/gentoo-conf/xor/home/nand/.mpv/shaders/filmgrain-smooth.glsl). (Change `LUMA` to `SCALED`)

**Comment by kokoko3k** [comment]
Ok thanks.
