### ISSUE TITLE
[vo=gpu-next] Video output gpu-next not found, error opening/initializing the selected video_out (--vo) device

### ISSUE THREAD

**Issue by Gigas002** [mpv-player/mpv#9726]
### Important Information

mpv version:

```text
mpv 0.34.0-147-g1ab3f56df0 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Wed Jan 19 02:21:44 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```

linux destribution and version:

```text
Operating System: Manjaro Linux
Kernel: Linux 5.16.1-1-MANJARO
Architecture: x86-64
```

source of mpv binary: mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

window manager: `x11, KDE Plasma 5.23.5`

GPU driver: proprietary nvidia driver 495.46

### Reproduction steps

Run video with `mpv --no-config --vo=gpu-next` arguments

Probably related to #9534 ? But since this one's linux issue I thought I should create a new one.
Tried setting `--gpu-context=x11vk` but nothing changed. BTW, using `--gpu-context=x11` results in error:

```text
Error parsing option gpu-context (option parameter could not be parsed)
Setting commandline option --gpu-context=x11 failed.
```

is it deprecated?

### Expected behavior

Video starts

### Actual behavior

```text
[vo] Video output gpu-next not found!
Error opening/initializing the selected video_out (--vo) device.
```

### Log file

Log: https://pastebin.com/raw/Xx511w2Z

**Comment by Dudemanguy** [comment]
Your build doesn't have libplacebo-v4 support (i.e. your libplacebo version is too old). You can just grab libplacebo-git from AUR and rebuild mpv to make it easy.

**Comment by hooke007** [comment]
Well, its short deps list has answered of this issue.
