### ISSUE TITLE
Poor experience running youtube

### ISSUE THREAD

**Issue by touhamii** [mpv-player/mpv#9728]
Hi mpv community , 
im trying to fix this old pc for someone : pentium 4 3.2ghz + nvidia 7200 gs , i installed antiX 17.5_64bit on it (based on debian 9) and it has mpv 0.23, legacy 304.xxx drivers are installed on my 4.9.0-294 antix kernel
when i run videos on the HDD it's way better exprience than runnin the same video on youtube with mpv or with browsers 
im trying to have the best experience as possible running youtube, downloading every single video i want to watch is not an option

**Comment by touhamii** [comment]
https://i.imgur.com/SvYvqOI.jpg
can those redlines be the probleme why it runs youtube videos on mpv slowly and poorly ?

**Comment by garoto** [comment]
Try these in your `mpv.conf`:

```
gpu-dumb-mode=yes
ytdl-format=best
```

**Comment by touhamii** [comment]
ytdl-format=best ? bro i have a bad gpu im not sure if goin with best is good here but i will try 
thank u

**Comment by garoto** [comment]
> i tried those 2 on /etc/mpv/encoding-profiles.conf and seems that nothing changed same probleme

oh boy...no... pls no.

**Comment by touhamii** [comment]
xD what did i do

**Comment by garoto** [comment]
(I'm biting)

> ytdl-format=best ? bro i have a bad gpu [...]

Hugger, believe me, ` ytdl-format=best ` is the way to go and it doesn't mean what you think it does.

> i tried those 2 on /etc/mpv/encoding-profiles.conf and seems that nothing changed same probleme

Look up the manual where `mpv.conf` should be located in your setup, because `/etc/mpv/encoding-profiles.conf` is not it.

**Comment by touhamii** [comment]
well , not sure where to find it i will try tomorrow , time to sleep thank u

**Comment by Obegg** [comment]
> mpv 0.23
>
The latest is 0.34, try updating.

Also, try to use [yt-dlp](https://github.com/yt-dlp/yt-dlp) it's better than yt-dl.

Anyway, seems like everything is outdated on this machine.

**Comment by touhamii** [comment]
isnt 0.23 the last version on debian 9 64bit ? can i install 0.34 without breaking anything ?

**Comment by Obegg** [comment]
> isnt 0.23 the last version on debian 9 64bit ? can i install 0.34 without breaking anything ?

I have no idea, I'm using WIndows.

**Comment by haasn** [comment]
You are trying to play a 4K video on an ancient machine. That this does not work smoothly should not surprise you.

Use a lower resolution, as e.g. @garoto recommended.

**Comment by touhamii** [comment]
my pc name is (khtal)
i created mpv.conf file on /home/khtal/.config/mpv/mpv.confg
i saved 
gpu-dumb-mode=yes
ytdl-format=best
nothing changed
