### ISSUE TITLE
How to record stream without playing them in GUI?

### ISSUE THREAD

**Issue by snowman** [mpv-player/mpv#9731]
```bash
# shows GUI window
$ mpv --stream-record=output.flv URL

# do NOT shows GUI window, but the output file ONLY has audio, NO video
$ mpv --stream-record=output.flv --vid=no URL
```

**Comment by Dudemanguy** [comment]
This not actually possible. `--stream-record` by capturing what mpv is actually decoding. If you turn off the video (i.e. have no window), well you aren't decoding video so there will be no video in the output.

**Comment by vizionere** [comment]
For people that found this page via a search engine:

     mpv --vo=null --ao=null --stream-record=output.flv URL

**Comment by guidocella** [comment]
`--stream-dump=<destination-filename>`
