### ISSUE TITLE
config help - profile for videos of 60fps

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9736]
I use this shader:
```glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"```
And when I watch 60fps video ([example](https://www.youtube.com/watch?v=pfbAirb7Gds))
I have dropped frames.
But if I don't use this shader - I don't have dropped frames.

I want that if I watch videos of 60fps it will disable the shader (and will enable the shader if the video is not 60fps).
Can someone help me with that?

**Comment by dyphire** [comment]
only 60fps？’
Plese try this：
```
[fps-fix]
profile-cond=p["container-fps"]>59
profile-restore=copy
glsl-shaders-remove="~~/FSRCNNX_x2_16-0-4-1.glsl"
```
You can also try hardware decoding with 60fps videos. It works for me.

**Comment by Obegg** [comment]
> Only 60fps？’
> 
Yes, only 60fps, because my hardware couldn't handle it with this shader.

> Plese try this：
> ```
> [fps-fix]
> profile-cond=p["container-fps"]>59
> profile-restore=copy
>glsl-shaders-remove="~~/FSRCNNX_x2_16-0-4-1.glsl"
> ```
Thank you for your response.
I modified it a bit (because it didn't use shader when it wasn't 60fps) so this is the end result:
```
[23fps - Use FSRCNNX]
profile-cond=p["container-fps"]<49
glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"

[60fps - Remove FSRCNNX]
profile-cond=p["container-fps"]>49
glsl-shaders-remove="~~/FSRCNNX_x2_16-0-4-1.glsl"
```
If there's an easier solution to this without adding another profile let me know (I'm not good with profiles),
```profile-restore=copy``` didn't seem to apply the shader when not using 60fps video so this is why I modified it.

> You can also try hardware decoding for 60fps videos. It works for me. 
>

I use ```vo=gpu-next``` and it doesn't support ```hwdec```.
