### ISSUE TITLE
Boss key (with extended scope of use)

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#9738]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

There seem to be some scripts, but none I could find support macOS or do as fully expected.

https://duckduckgo.com/?t=ffab&q=mpv+boss+key&ia=web

### Expected behavior of the wanted feature

Keystroke to instantly mute audio and blacken video, as a toggle (the classic "Boss Key") or for a preset time.

Mute audio is already in place ("m"), but there seems to be no corresponding key for video. There is "Cmd + H", but this gets panicky having to combine it with "m" on a moment's notice. I'm looking for a single, instant key.

Relevant use cases:

- Skip ad breaks in live broadcasts (typically 2-3 minutes)
- Skip "This program is sponsored by X, Y and Z" (typically 15 seconds)

https://www.quora.com/How-long-is-the-average-commercial-break-on-television?share=1

Side note: This feature could also be relevant for avoiding particularly disgusting scenes (or cringe-y moments) in otherwise edible movies, but maybe the good old fast forward is more applicable here. One could even consider an "almost" mute/blacken audio/video feature, similar to covering your eyes and peeking out between the fingers.

If someone has a script that could be easily extended to support the requested features, please share, as I do have a programming background, and managed to wrestle together at least a small plug-in already.

**Comment by avih** [comment]
You can add to `input.conf`:
`ctrl+b set pause yes; set window-minimized yes`

**Comment by forthrin** [comment]
Wow! That was quick. Thanks for the pointers. Sounds like this is easy. But I assume if I want the video/audio to turn automatically back on after a certain time, `input.conf` won't cut it and I have to write a plug-in to use a timer. Correct?
