### ISSUE TITLE
Need help porting AMD's CAS shader with scaling to mpv

### ISSUE THREAD

**Issue by agyild** [mpv-player/mpv#9743]
[Here](https://github.com/GPUOpen-Effects/FidelityFX-CAS/blob/c7cfb610ade910172ab2e001fe1bd43742d43017/ffx-cas/ffx_cas.h#L539) is the original source code. And [here](https://gist.github.com/agyild/131809aeb3108fbd6e0f8959c415b105) is my current WIP port. Currently it is broken, and all it does is creating scanline-like artifacts with no visible sharpening at all, and I don't know why. Feel free to take a crack at it.

**Comment by epicfilmmaker93** [comment]
Related? https://gist.github.com/igv/8a77e4eb8276753b54bb94c1c50c317e#gistcomment-3551269

**Comment by agyild** [comment]
> Related? https://gist.github.com/igv/8a77e4eb8276753b54bb94c1c50c317e#gistcomment-3551269

Thanks. However, this is the non-scaled version of CAS which I have already [ported](https://gist.github.com/agyild/bbb4e58298b2f86aa24da3032a0d2ee6) with additional fixes and optimizations, and it works fine. The issue is about the scaled version of CAS.

**Comment by igv** [comment]
I've already told you, that mpv uses upper left origin coordinate system, but haven't checked what coordinates you use for this shader. Using original coordinates fixes scanline artifacts, but it still blurry.

**Comment by agyild** [comment]
> I've already told you, that mpv uses upper left origin coordinate system, but haven't checked what coordinates you use for this shader. Using original coordinates fixes scanline artifacts, but it still blurry.

@haasn Can you confirm this? I assumed mpv uses GLSL format (which means initial coordinates should be GL in coordinate space) for the shader code and then _transcompiles_ into appropriate output. ReShade has a similar mechanism where the shader code is inputted in HLSL format and according to HLSL rules and then transcompiled into appropriate format.

**Comment by haasn** [comment]
@igv is correct, mpv uses upper-left origin. GLSL specifies no coordinate system or convention. I agree that it should be documented better, though. It just never occurred to me to assume otherwise, since top-left origin is the convention throughout all of multimedia.

**Comment by agyild** [comment]
I have solved the problem. Apparently during porting I accidentally skipped a tiny portion of the code that was available in a remote section. CAS with scaling gives great results in mpv, and I will release it soon. I am currently trying to find a solution to the linear colorspace problem.

**Comment by BenjaminWegener** [comment]
> I have solved the problem. Apparently during porting I accidentally skipped a tiny portion of the code that was available in a remote section. CAS with scaling gives great results in mpv, and I will release it soon. I am currently trying to find a solution to the linear colorspace problem.

@agyild can you tell when you are planning to release your implementation? Thanks!

**Comment by agyild** [comment]
> @agyild can you tell when you are planning to release your implementation? Thanks!

It is already [available](https://gist.github.com/agyild/bbb4e58298b2f86aa24da3032a0d2ee6) on my Gist repository.

**Comment by BenjaminWegener** [comment]
FIY: ported to webgl https://github.com/BenjaminWegener/AMD-fidelityFX-CAS-webGL
