### ISSUE TITLE
gpu-next: shader misbehavior with subtitles

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9744]
### Important Information
- mpv version ```mpv 0.34.0-142-g1ba0547bfb```
- Windows Version ```Windows 10 Pro x64 21H2 19044.1466```
- Source of the mpv binary ```sourceforge - shinchiro```

### Actual behavior
```vo=gpu-next``` without shader:
(No issues, just blurry)
![gpu-next  No Shader](https://user-images.githubusercontent.com/13978119/150664636-ffacca6f-a6f4-4df4-bcd9-991f6db7ef82.jpg)

```vo-gpu-next``` with ```glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"```:
(Strange lines at the end and at the bottom of the sentence, and blurry)
![gpu-next  FSRCNNX_x2_16-0-4-1](https://user-images.githubusercontent.com/13978119/150664654-938d87b2-2871-493f-92d0-bb0bc425771f.jpg)

```vo=gpu``` with ```glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"```
(Best, without issues and sharper)
![gpu  FSRCNNX_x2_16-0-4-1](https://user-images.githubusercontent.com/13978119/150664672-670c5484-8d62-4cea-98fb-156f04ae0d18.jpg)

### Sample files
Shader - [FSRCNNX_x2_16-0-4-1.glsl](https://github.com/igv/FSRCNN-TensorFlow/releases)
Video - [One Piece — 1007](https://subsplease.org/shows/one-piece/)

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/9398
