### ISSUE TITLE
Correct configuration for SPDIF audio pass through?

### ISSUE THREAD

**Issue by Utini2000** [mpv-player/mpv#9746]
Good morning everyone,

I believe  I have a bit of a "tricky" setup and wonder how to set it up best with mpv:

```
HTPC -> HDMI -> TV -> SPDIF -> DAC -> AMP - Stereo Speaker
HTPC = Arch Linux with pipwire
TV = LG CX55OLED
DAC = Sony SDP-EP90ES
AMP = Sony TA-F690ES
Stereo Speaker = 2x Magnat Zero 8
```

When playing content directly from my TV (e.g. via UPNP) the DAC does all the "magic" as it should.
Meaning it can convert all kind of input formats (5.1, HD-DTS, Atmos, Dolby,....) to create the best possible sound on my stereo speaker setup.
However, when playing anything from my HTPC with mpv, then the DAC doesn't seem to process the sound with all features anymore.
E.g. Dolby Surround, Dolby Digital, Dolby ProLogic and also the "L.F.E" feature to not work anymore. 
Since the connection to the DAC is always the same (SPID/F), the only thing that changes (and breaks) is my HTPC. 

So I enabled "pass through" in pavucontrol (=Archlinux audio settings) for everything (PCM, AC3, EAC, MPEG, DTS, DTS-HD) and then added the following to mpv.conf: 
audio-spdif=ac3,dts,dts-hd,eac3,truehd

When I then open a video file, the playback gets really choppy and doesn't produce any sound at all. At the same time, VLC will suddenly process some files (but not all) correctly due to the changes I made in pavucontrol.

Again, when playing the file directly on my TV with the built-in UPNP Player, everything works fine and the DAC detects the amount of input signals (e.g. 5.1, DolbyPro,...) and converts/processes them correctly.

In case it is relevant, here are the configurations of my TV and DAC.
TV:
```
- All sound effects deactivated (EQ, Dolby Atmos, AI-Ton,...)
- Output: Optical Out
- Signal: Passthrough
- DTV Automatic (AC4 -> HE-AAC -> Dolby Digital Plus -> Dolby Digital -> MPEG)
```

DAC:
```
- Master Volume: -20 dB
- Front SP: Large
- Center SP: No
- Rear SP: No
- Rear SP: Side (obsolete anyway)
- Sub Woofer: No
- Front Speaker Distance: 2,5m
- Center Speaker Distance: 2,5m (obsolete anyway)
- Rear Speaker Distance: 2,5m (obsolete anyway)
- Surround Mode: Virtual Enhanced Surround A 
- Reak Speaker level: 0dB
- Centre Speaker level: 0dB
- Sub Woofer level: 0dB
- Surround Effect: 75%
- LFE Mix: 0dB
- Dynamic range compression ratio: On / STD
- Tone Control: Off
- Bass, Treble: 0dB
- Equalizer: Off
- Decode Mode: Auto
- Front speaker roll of frequency: > 120 Hz 
- Cenrte speaker roll of frequency: > 120 Hz 
- Rear speaker roll of frequency: > 120 Hz 
```

I would appreciate any help :S Thanks in advance!

**Comment by ValZapod** [comment]
Optical output in LG CX and later firmware of LG C9 do not support DTS passthrough BTW. C9 is a bug.

**Comment by Utini2000** [comment]
> Optical output in LG CX and later firmware of LG C9 do not support DTS passthrough BTW. C9 is a bug.

Hmm I haven't noticed that problem yet. Actually I have the BX which is basically the CX with another color.
My DAC always seems to recognize the correct signals (to the extend that it supports) and processes them fine.

**Comment by ValZapod** [comment]
But CX does  ot support DTS at all in any form.

**Comment by Utini2000** [comment]
You are right. It is: AC4, AC3 (Dolby Digital), EAC3, HE-AAC, AAC, MP2, MP3, PCM, WMA, apt-X
So how come I can play files with DTS audio then? :D

**Comment by Utini2000** [comment]
I just double checked. The Model I have is:  LG OLED55CX8LB

Again, all the audio thats into the TV (HTPC, XBOX, DLNA/UPNP, Satelite,...) gets "passed through" via optical SPID/F to my DAC.
So far everything plays fine.. DTS, 5.1, AC3,... 
Well, except the issue I described in OP.

**Comment by jackieyiwu** [comment]
audio-spdif=ac3，dts，dts-hd，eac3，truehd  配置进mpv.conf文件里吗，控制台好像没有关联指令。
