### ISSUE TITLE
[vo=gpu-next] Add configuration options for inverse-tone-mapping

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#9747]
After testing inverse-tone-mapping I should say it makes the shadows too dark and the image has too much contrast. It is possible to use gamma and contrast controls to fix that but it would probably be better if configuration options for inverse-tone-mapping existed, like "upconvert-highlights-only" and maybe "upconvert-sdr-only" when using a very bright display and only 1000 nit video

**Comment by ValZapod** [comment]
> too dark and the image has too much contrast

Are you sure OS does not do inverse tonemapping too?? 😜
