### ISSUE TITLE
[Feature Request] Option to disable idle logo and message

### ISSUE THREAD

**Issue by Eisa01** [mpv-player/mpv#9751]
Going through the documentation, I could not find a way to disable the idle logo and message.
Things I want to disable:
```
[LOGO]
"drop files or urls to play here"
```
The only way I could disable it is by modifying the osc.lua, perhaps I am missing something.

For me it is currently needed so I could utilize the idle state with lua scripts for mpv.

**Comment by avih** [comment]
You can just disable the OSC when you want it cleared, and re-enable it once you're done.
