### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#9753]
Hi.

I've been getting this distracting pop-up all the time, where I have to press cancel, exit, and re-enter full screen to fix it. If I don't exit and re-enter full screen the cursor autohide doesn't work.

[Here](https://ibb.co/NymdnT9) you can see a screenshot of it.

**Comment by LaserEyess** [comment]
Please do not ignore the issue template, also that has nothing to do with mpv.

**Comment by Dudemanguy** [comment]
mpv does not have any search popup, so there's nothing we can do for you.

**Comment by al3xtjames** [comment]
This looks like the pop-up from [Hachidori](https://malupdaterosx.moe/hachidori/). In any case, it's not from mpv.
