### ISSUE TITLE
SDR .PNG in 30 bit mode (alà Photoshop) using windowed OpenGL 10 bit Geforce

### ISSUE THREAD

**Issue by ValZapod** [mpv-player/mpv#9754]
When I select 4K 24/1.001 fps 12 bit RGB SDR mode (just for your comfort due to not everyone having 2.1 HDMI GPU i will not just use 120/1.001 fps) in Photoshop I can use 30 bit renderer option to render 30 bit image using windowed OpenGL API that was activated not so recently in Geforce GPUs (no need for Quadro no longer).

It is very very subtle but I am sure it works and it is not dither.
I use this image:
![gradient_3840-2160_0-100](https://user-images.githubusercontent.com/31514790/140886684-46920dc7-1f61-4434-b9bd-5b2e95ad7593.png)

How to replicate this behaviour in mpv (ideally also using OpenGL, but Vulkan and Directx approaches even if in fullscreen only are also allowed, ideally SDR, but HDR scRGB approach like in Chrome is okay)?

Issue in YUView: https://github.com/IENT/YUView/issues/443#issuecomment-1019510583 they propose using this code https://github.com/IENT/YUView/pull/282

There were some related issues for 10 bit YCbCr, but they do not work, or I could not made them work (they did assume SDR too though). Again. This is SDR, NOT HDR.

**Comment by haasn** [comment]
Missing log?

**Comment by ValZapod** [comment]
What log? This is a question.

**Comment by haasn** [comment]
Well if this is a question, not a bug report, then the answer is 'yes'.

**Comment by ValZapod** [comment]
> then the answer is 'yes'.

How? SDR 10 bit OpenGL?

**Comment by ValZapod** [comment]
Okay, so does this work? mpv.com --log-file=hndcwhe.txt --gpu-context=winvk --vo=gpu-next gradient_3840-2160_0-100.png
[hndcwhe.txt](https://github.com/mpv-player/mpv/files/7926501/hndcwhe.txt)

```
[   0.489][v][vo/gpu-next/vulkan/libplacebo] Available surface configurations:
[   0.489][v][vo/gpu-next/vulkan/libplacebo]     0: VK_FORMAT_B8G8R8A8_UNORM                 VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[   0.489][v][vo/gpu-next/vulkan/libplacebo]     1: VK_FORMAT_B8G8R8A8_SRGB                  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[   0.489][v][vo/gpu-next/vulkan/libplacebo]     2: VK_FORMAT_R16G16B16A16_SFLOAT            VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
[   0.489][v][vo/gpu-next/vulkan/libplacebo]     3: VK_FORMAT_A2B10G10R10_UNORM_PACK32       VK_COLOR_SPACE_HDR10_ST2084_EXT
[   0.489][v][vo/gpu-next/vulkan/libplacebo]     4: VK_FORMAT_A2B10G10R10_UNORM_PACK32       VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[   0.489][v][vo/gpu-next/vulkan/libplacebo] Picked surface configuration 4: VK_FORMAT_A2B10G10R10_UNORM_PACK32 + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR

```

How can one force openGL?

**Comment by haasn** [comment]
Ah, I see the issue - yes, that's a limitation of the `--vo=gpu` <-> vulkan wrapper, not of the vulkan swapchain (which is, as the log points out, correctly configured into 10-bit mode). You can override this color depth auto-detection by using `--dither-depth=10` explicitly. It should also already be working with `--vo=gpu-next` out of the box.

For OpenGL, it should already be automatic.

**Comment by ValZapod** [comment]
> It should also already be working with `--vo=gpu-next` out of the box.

This thing from above is with gpu-next. Can you tell from the log? Does nvidia driver tell you?

dither-depth set to 10 is not a good idea, since nvidia applies its own dither, no? In 8 bit mode and in limited rgb it is always on. There is a way to turn it off... But it is a new hack in registry.

Also what is the connection between dither and actual 10 bit output? Also 12 bit? How to do it?

>OpenGL, it should already be automatic.

Yeah, what is the command line? That is what I want.

**Comment by ValZapod** [comment]
Okay, I did a printscreen and then checked it with paint it does have artifacts while the mpv does not. So it does work. Nice. dither-depth=no I suppose will turn it off...

**Comment by ValZapod** [comment]
FYI, here is all that crazy rabbit whole for nvidia dither. https://github.com/ledoge/novideo_srgb/issues/6#issuecomment-997306157

**Comment by ValZapod** [comment]
I was RIGHT! This dither is indeed nvidia's! 

>printscreen and then checked it with paint it does have banding on the 10 bit section while the mpv screen does not

This does work even with 8 bit HDR (thus dither on), so it appears 10 bit does not work with  vulkan?

**Comment by ValZapod** [comment]
https://github.com/mpv-player/mpv/issues/4874 that does not work. OpenGL does not work at all, be it angle or whatever.
