### ISSUE TITLE
sync audio with video

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9756]
My setup is Windows PC > AV > TV,
And sometimes I feel like to audio and the video are not in sync,
I did enable "Auto Delay" on my AV receiver (which uses the HDMI to send the sound at the same time as the video).
And on mpv I use:
```
vo=gpu-next
video-sync=display-resample
audio-pitch-correction=yes
```
So what else can I do in order to make sure the video and audio are synced?

**Comment by CounterPillow** [comment]
You can manually adjust AV sync by Ctrl+ and Ctrl-

**Comment by Obegg** [comment]
> You can manually adjust AV sync by Ctrl+ and Ctrl-

I am aware of this, and also my AV does support manual delay.
The reason I don't use it manually is that it might not be the correct delay, only appear to be so.
That's why I want it to be automatic.
So is there any option with MPV, maybe I missed a command, that will sync audio to video?

**Comment by CounterPillow** [comment]
Audio and video are synchronised by default. If your audio output chain induces some delay, it cannot be detected by mpv, and hence will need to be accounted for manually.
