### ISSUE TITLE
I implemented a BT.2446A shader, but the results are very different from the mpv, why?

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9758]
**there some things worng with nvidia+vulkan+pow, results here are not reliable.**

mpv's bt2446a produces very dim results, while mine so bright that even the sdr area, why?
I think I followed [R-REP-BT.2446-1](https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-BT.2446-1-2021-PDF-E.pdf)
change `Lsdr` doesn't work.

mpv 2446a / my 2446a / mpv clip
<img src="https://user-images.githubusercontent.com/50797982/150815810-5dd4773e-db89-4fbd-8514-39a9d4765e5c.png" alt="" width="33.333%"><img src="https://user-images.githubusercontent.com/50797982/150815656-50130828-c554-468d-a857-3ab71b82adba.png" alt="" width="33.333%"><img src="https://user-images.githubusercontent.com/50797982/150815774-d8e9fbaf-3612-4585-8cf3-af37269530a0.png" alt="" width="33.333%">

```ini
glsl-shader=~~/shaders-toys/HardClip/Black.glsl
glsl-shader=~~/shaders-toys/PQ_to_Y.glsl
glsl-shader=~~/shaders-toys/Y_to_CV.glsl
glsl-shader=~~/shaders-toys/Tonemapper/BT2446A.glsl
glsl-shader=~~/shaders-toys/CV_to_BT1886.glsl
lut=~~/luts/Rec202012-bit_Rec2020-Rec202012-bit_Rec709.cube
lut-type=conversion
```

[BT2446A.glsl](https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/main/shaders-toys/Tonemapper/BT2446A.glsl) 
[other shaders](https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/main/shaders-toys)
[lut.zip](https://github.com/mpv-player/mpv/files/7926776/lut.zip)

test in javascript [input, output r, g, b]
![image](https://user-images.githubusercontent.com/50797982/150815301-b8c3e02c-fdd5-487c-84c9-a43d2d57a1b7.png)

**Comment by ValZapod** [comment]
It assumes BT.1886? https://code.videolan.org/videolan/libplacebo/-/issues/154

**Comment by ValZapod** [comment]
> I did the linear to bt1886 [CV_to_BT1886.glsl](https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/main/shaders-toys/CV_to_BT1886.glsl)

But it already does it.

**Comment by Natural-Harmonia-Gropius** [comment]
> But it already does it.

it doesn't
![image](https://user-images.githubusercontent.com/50797982/150826672-7e8597bc-6194-4b08-9543-98349ebec5da.png)
![image](https://user-images.githubusercontent.com/50797982/150826768-7af23a47-c893-4f32-bfa5-ca5de230b6ca.png)
![image](https://user-images.githubusercontent.com/50797982/150826284-4a11d212-6305-4f3f-84d8-7bb797f39a2a.png)

**Comment by aufkrawall** [comment]
> mpv's bt2446a produces very dim results

Yes, it does that without ICC profile and no other custom settings defined, whereas with ICC profile it seems a bit too bright.

**Comment by Natural-Harmonia-Gropius** [comment]
i just show that output rgb' not rgb^bt1886
