### ISSUE TITLE
script=***.lua command doesn't work for Conditional auto profiles?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#9759]
Hi,

I have lua script named sub-priority.lua  
I want to use this lua script for only a specific video file

So I did set up auto profile but it doesn't work?
The script does work fine when I place it in Script folder or with cmd mpv video.mkv --script=***.lua 

but
İt seems with Conditional auto profiles script=path\to\sub-priority.lua doesn't work?  

İf I write it 
not as a profile command 
but as an seperate mpv.conf command it works but  
when I use it for auto profiles it doesn't work

script-opts= works  for auto profiles
but `script=` doesn't work for auto profiles?

    [web dl profile name]
    profile-cond=get("filename", ""):match("Example name") ~= nil
    script="C:\Users\Ayd1n\mpv-build\portable_config\shaders\Scripts-external\sub-priority.lua"

[Log.txt](https://pastebin.com/raw/TyaBHh8U)

**Comment by guidocella** [comment]
Use single quotes so the backslashes aren't interpreted as the start of an escape sequence:
`script='C:\Users\Ayd1n\mpv-build\portable_config\shaders\Scripts external\sub-priority.lua'`

**Comment by erickyun** [comment]
> Use single quotes so the backslashes aren't interpreted as the start of an escape sequence: `script='C:\Users\Ayd1n\mpv-build\portable_config\shaders\Scripts external\sub-priority.lua'`

did just try 
it doesn't work

**Comment by avih** [comment]
I'm not 100% sure how profiles are loaded, but the `--script` startup option translates to command and not a property, so there's no option-property bridge for it (i.e. setting a property `script` to some path does not load a script)

At runtime a script can be loaded using the command `load-script path/to/script.lua` (and there's no way to unload it from outside the script) https://mpv.io/manual/master/#command-interface-load-script

So I don't think a profile can load/unload a script.

I think your best option is to "activate" the script only when your specific condition is true (e.g. a specific video or whatever).

**Comment by guidocella** [comment]
As a workaround you can call load-script in the profile condition:
```
[web dl profile name]
profile-cond=get("filename", ""):match("Example name") ~= nil and mp.commandv('load-script', 'C:\Users\Ayd1n\mpv-build\portable_config\shaders\Scripts-external\sub-priority.lua')
```

**Comment by erickyun** [comment]
> As a workaround you can call load-script in the profile condition:
> 
> ```
> [web dl profile name]
> profile-cond=get("filename", ""):match("Example name") ~= nil and mp.commandv('load-script', 'C:\Users\Ayd1n\mpv-build\portable_config\shaders\Scripts-external\sub-priority.lua')
> ```
 
I am getting this error?
![image](https://user-images.githubusercontent.com/71968711/150840580-a6901e45-c349-491d-bec2-a5b51caa9637.png)

**Comment by guidocella** [comment]
The string should be escaped again because it's evaluated as Lua source code, just use forward slashes which do work on Windows. Also beware that if you use this workaround and play multiple videos matching the condition instead of just one, the script will be loaded multiple times.

**Comment by erickyun** [comment]
> As a workaround you can call load-script in the profile condition:
> 
> ```
> [web dl profile name]
> profile-cond=get("filename", ""):match("Example name") ~= nil and mp.commandv('load-script', 'C:\Users\Ayd1n\mpv-build\portable_config\shaders\Scripts-external\sub-priority.lua')
> ```

`and mp.commandv('load-script', 'C:/Users/Ayd1n/mpv-build/portable_config/shaders/Scripts-external/sub-priority.lua')`
Thank you very much this worked for me 👍  :)))

**Comment by guidocella** [comment]
Those aren't conditional profiles and are deprecated. You can use
```
[network]
profile-cond=demuxer_via_network and ...
```
But if you load a script in this profile condition you will load it multiple times for every entry played via network in a playlist.
