### ISSUE TITLE
Dynamic `sub-file-paths` ?

### ISSUE THREAD

**Issue by LazyGeniusMan** [mpv-player/mpv#9767]
How to set `sub-file-paths` dynamically based on video file name without the file format?

I have this folder stucture
```
│   video-1.mp4
│   video-2.mp4
│   video-3.mp4
│
└───Subs
    ├───video-1
    │       Bahasa.srt
    │       English.srt
    │
    ├───video-2
    │       Bahasa.srt
    │       English.srt
    │
    └───video-3
            Bahasa.srt
            English.srt
```

I tried to set `sub-file-paths=Subs/{$filename}`, but it's not detecting

### Log file

https://0x0.st/oo5A.txt

**Comment by guidocella** [comment]
Use this script:
```lua
mp.add_hook('on_load', 10, function ()
    mp.set_property('sub-file-paths', 'Subs/' .. mp.get_property('filename/no-ext'))
end)
```
You will also need ` --sub-auto=all`.

**Comment by LazyGeniusMan** [comment]
> Use this script:

thanks it's working, what is I want `Subs` to be anything ? maybe sometimes the folder is not `Subs`, I have to add them manually or there is a better and cleaner way ?

**Comment by Hrxn** [comment]
The clean way is definitely having consistently named folders...

**Comment by LazyGeniusMan** [comment]
> The clean way is definitely having consistently named folders...

Haha yeaa, I need to make myself more consistent. sometimes I name the folder `Sub` or `Substitle` or even the language like `ENG`, `IDN` etc

Anyway, I will just mark this as solved, let me know if there is a way to make it load `**/filename/`

**Comment by dyphire** [comment]
See https://github.com/mpv-player/mpv/issues/9783#event-5968885036

You can also try this script: [fuzzydir.lua](https://github.com/dyphire/mpv-config/blob/master/scripts/fuzzydir.lua)
And edit your mpv.conf:
```
audio-file-paths=audio;audios;**
sub-file-paths=sub;subs;subtitles;**
```
Also can modify `fuzzydir.conf` to your liking

**Comment by LazyGeniusMan** [comment]
> You can also try this script: [fuzzydir.lua](https://github.com/dyphire/mpv-config/blob/master/scripts/fuzzydir.lua)

I tried it, it's listed all subs in Subs dir instead (if I play video-1 it will also have video-2 and video-3 subtitle)

**Comment by dyphire** [comment]
> I tried it, it's listed all subs in Subs dir instead (if I play video-1 it will also have video-2 and video-3 subtitle)

Because you use `sub-auto=all`, this is expected behavior for mpv.

**Comment by XCongoAlpha** [comment]
After adding the script by @guidocella, `sub-file-paths=Subs;sub;subtitles;subs` in `mpv.conf` no longer works.
Is there any way to add the extra folders in this script?

**Comment by LazyGeniusMan** [comment]
> you should use `sub-auto=fuzzy` with:

Ah so I need to rename the sub ? I'll stick to guidocella script then.



> Is there any way to add the extra folders in this script?

@XCongoAlpha Yea me too, then I add the sub dir in `mpv.conf` on that script too. I put the sub dir in array like this:
```lua
mp.add_hook('on_load', 10, function ()
    sub_paths = {}
    sub_paths[#sub_paths+1]='Subs/' .. mp.get_property('filename/no-ext')
    sub_paths[#sub_paths+1]='Subs'
    mp.set_property_native('sub-file-paths', sub_paths)
end)
```
Maybe there is a better way. Add more sub dir by duplicate row 4 and change the value

**Comment by XCongoAlpha** [comment]
> Add more sub dir by adding more string in row 2

I'm a noob in this but how do I add more folders in there? for example: `subtitles` folder
``` lua
sub_paths = {'Subs', 'subtitles'}
```
Is it like this?

**Comment by XCongoAlpha** [comment]
@LazyGeniusMan thanks man it works

**Comment by dyphire** [comment]
> Ah so I need to rename the sub ? I'll stick to guidocella script then.

If you insist. Because of its low applicability for `sub-auto=all`, the script of fuzzydir.lua will not adapt it. For example, it does not work properly under the following conditions. When use your modified script with `sub-auto=all`, play video-1.mp4 will also have all anyname*.srt and don‘t have video-1.srt.
```
│   video-1.mp4
│   video-2.mp4
│   video-3.mp4
│   video-1.srt
└───Subs
    │      anyname*.srt
    │      anyname*.srt
    │      anyname*.srt
    ├───video-1
    │       Bahasa.srt
    │       English.srt
    │
    ├───video-2
    │       Bahasa.srt
    │       English.srt
    │
    └───video-3
            Bahasa.srt
            English.srt
```
But for your first request, the script by guidocella is great. Forget about another script of fuzzydir.lua

**Comment by mixslad** [comment]
yo can help me with subtitle pathing, i dont understand the above posts.

**Comment by D33M0N** [comment]
> yo can help me with subtitle pathing, i dont understand the above posts.

+1.
Please can someone explain how this function should work and where should I copy it to work as intended?

**Comment by guidocella** [comment]
You should place Lua scripts in `~/.config/mpv/scripts` with a `.lua` extension.

**Comment by D33M0N** [comment]
did that. doesn't do anything...

**Comment by guidocella** [comment]
You also need `sub-auto=all` in `mpv.conf`.

**Comment by D33M0N** [comment]
There is still this problem, that the subtitles will not load always. It's like gamble and you have to restart the player several times before it detects and loads the subtitles in the Subs folder. Any clue how to fix this?

**Comment by kaoneko** [comment]
I ran into OP's problem today too. I adjusted @guidocella's script so it doesn't overwrite the sub-file-paths option given in mpv.conf or on the command line:
> ```lua
>sub_paths = mp.get_property_native('sub-file-paths')
>mp.add_hook('on_load', 10, function ()
>	sub_paths[#sub_paths+1]='Subs/' .. mp.get_property('filename/no-ext')
>	mp.set_property_native('sub-file-paths', sub_paths)
>	sub_paths[#sub_paths]=nil
>end)
> ```
Works wonderful! Thanks you guys.

**Comment by Obegg** [comment]
Random question which I genuinely want to know the answer to:
Why not use [fuzzydir.lua](https://github.com/sibwaf/mpv-scripts/blob/master/fuzzydir.lua)?

**Comment by kaoneko** [comment]
Consider this common layout:
```
Big.Buck.Bunny.1080p.S01E01.WEBRip.x265.mp4
Big.Buck.Bunny.1080p.S01E02.WEBRip.x265.mp4
etc.
Subs
├── Big.Buck.Bunny.1080p.S01E01.WEBRip.x265
│   ├── 10_Finnish.srt
│   ├── 11_French.srt
│   ├── 12_French.srt
│   ├── 13_Hungarian.srt
│   ├── 14_Italian.srt
│   ├── 15_Japanese.srt
│   ├── 16_Korean.srt
│   ├── 17_Dutch.srt
│   ├── 18_nor.srt
│   ├── 19_Polish.srt
│   ├── 20_Portuguese.srt
│   ├── 21_Portuguese.srt
│   ├── 22_Romanian.srt
│   ├── 23_slo.srt
│   ├── 24_Swedish.srt
│   ├── 25_Turkish.srt
│   ├── 26_Chinese.srt
│   ├── 27_Chinese.srt
│   ├── 28_Chinese.srt
│   ├── 2_English.srt
│   ├── 3_English.srt
│   ├── 4_Czech.srt
│   ├── 5_Danish.srt
│   ├── 6_German.srt
│   ├── 7_Greek.srt
│   ├── 8_Spanish.srt
│   └── 9_Spanish.srt
├── Big.Buck.Bunny.1080p.S01E02.WEBRip.x265
│   ├── 10_Finnish.srt
│   ├── 11_French.srt
│   ├── 12_French.srt
│   ├── 13_Hungarian.srt
│   └── etc.
etc.
```
The subtitle file names don't contain the video file name, so you need to use `sub-auto=all` for them to load. How would you use fuzzydir.lua to only load the 27 subtitles belonging to the episode you're playing?

If you just load all subtitle files with `sub-file-paths = **` mpv will always select the first subtitle in the list matching your preferred languages, i.e. episode one's subtitle, no matter which episode you play, and you have to manually select the correct subtitle file from a list of possibly hundreds of nondescript file names.

**Comment by eggegg963** [comment]
My subs are also under sub folders like this:

```
2_Arabic.srt
3_Chinese.srt
4_Chinese.srt
5_English.srt
6_Indonesian.srt
7_Japanese.srt
8_Korean.srt
9_Korean.srt
10_may.srt
11_Thai.srt
12_Vietnamese.srt
```

But it always plays the '10_' subtitles, in this case the Malaysian subtitles. I have `slang=english,eng,en` but it doesn't work,
Can anyone help me please. I'm using the script from @kaoneko.

**Comment by kaoneko** [comment]
I think this has nothing to do with this issue or the script. Often video files don't contain the language information in their subtitle tracks, so there's nothing MPV can do to find the English subtitle track. When you press F9 you see the list of subtitles, they should include the language in parentheses like so: `(1) 'English' (eng)`

Looking at several videos from different series, it seems to me that external subtitles don't have this information. Best you can do is put an mpv.conf file in the directory that contains the videos with the line `sid=20` where you replace 20 with the subtitle track number for English. Or write/find a script that looks for the word English in the subtitle file name. Good luck!

**Comment by cronyakatsuki** [comment]
> Random question which I genuinely want to know the answer to: Why not use [fuzzydir.lua](https://github.com/sibwaf/mpv-scripts/blob/master/fuzzydir.lua)?

Cause it load all the subtitles, which in my case is over 200+ for a 8 episode TV show.

It becomes a pain in the ass to find the subtitle for a specific episode.

**Comment by usegv** [comment]
To load subtitles with one of these two directories structure

1.
```
.
├── video1.mkv
├── video2.mkv
└── Subs
    ├── video1
    │   ├── 2_English.srt
    │   ├── 3_English.srt
    │   ├── 4_Czech.srt
    │   ├── 5_Danish.srt
    │   ├── 6_German.srt
    │   │ ...
    │
    └── video2
        ├── 2_English.srt
        ├── 3_English.srt
        ├── 4_Czech.srt
        ├── 5_Danish.srt
        ├── 6_German.srt
        │ ...
```
2.
```
.
├── video.mkv
└── Subs
    ├── 2_English.srt
    ├── 3_English.srt
    ├── 4_Czech.srt
    ├── 5_Danish.srt
    ├── 6_German.srt
    │ ...
```

I use this script.

```lua
local msg = require 'mp.msg'
local utils = require 'mp.utils'

local sub_dir = 'Subs'
local sub_lang = 'English'

function find_and_add()
    local path = mp.get_property('path', '')
    local dir, fn = utils.split_path(path)
    local sd = utils.join_path(dir, sub_dir)

    local list = utils.readdir(sd, 'files')
    if #list == 0 then
        local fn_no_ext = mp.get_property('filename/no-ext')
        sd = utils.join_path(sd, fn_no_ext)
        list = utils.readdir(sd, 'files')
        if #list == 0 then
            return
        end
    end

    table.sort(list)
    for i = 1,#list do
        local sub = string.match(list[i], '^(.+' .. sub_lang .. '.+)$')
        if sub then
            mp.commandv('sub-add', utils.join_path(sd, sub), 'select')
        end
    end
end

mp.register_event('file-loaded', find_and_add)
```

This script will load subtitle files which name contains "English". Adjust the `sub_dir` value to change the main subtitle directory and `sub_lang` to change the language.

**Comment by NickLion** [comment]
So, I've written my js script for this (before I've read @usegv answer), based on @guidocella code:

```js
mp.add_hook('on_load', 10, function () {
    dir = 'Subs/' + mp.get_property('filename/no-ext');
    subs = mp.utils.readdir(dir, 'files');
    files = subs.sort(function (a, b) {
                    if (a.match(/^\d/) && b.match(/^\d/)) {
                        a = parseInt(a);
                        b = parseInt(b);
                    }
                    return a < b ? -1 : a > b ? 1 : 0;
                })
                .filter(function (s) { return s.match(/eng|ukr/i); })
                .map(function (s) { return dir + '/' + s; })
                .join(':');
    print(files);
    mp.set_property('sub-files', files);
});
```

And have this in configuration to support Subs folder:
```
sub-auto=fuzzy
sub-file-paths=Subs:subs:Eng:eng:Ukr:ukr
```

Just change regexp `/eng/ukr/` for your preferred languages. Or remove `filter` to load all subtitles in the folder.

**Comment by fuantaji** [comment]
@usegv has a script that should work fine for Windows and Linux I presume, but on Mac there is the ever present .DS_Store in Subs, so the script does not descent into Subs/<filename> folder.

Thus a rough updated version that would check for subs in <folder with filename>/, Subs/ and Subs/<folder with filename>.

```
local msg = require 'mp.msg'
local utils = require 'mp.utils'

local add_dir_subs = true
local add_dir_name = true
local add_dir_subs_name = true

local sub_lngs = { 'English', 'Russian' }

function find_and_add2()
    local sub_dirs = {}
    local path = mp.get_property('path', '')
    local dir, fn = utils.split_path(path)
    local fn_no_ext = mp.get_property('filename/no-ext')

    if add_dir_subs then
        local sd = utils.join_path(dir, 'Subs')
        table.insert(sub_dirs, sd)
        print('added', sd)

        if add_dir_subs_name then
            local nd = utils.join_path(sd, fn_no_ext)
            table.insert(sub_dirs, nd)
            print('added', nd)
        end
    end

    if add_dir_name then
        local nd = utils.join_path(dir, fn_no_ext)
        table.insert(sub_dirs, nd)
        print('added', nd)
    end    

    for i = 1,#sub_dirs do
        local list = utils.readdir(sub_dirs[i], 'files')
        if list then

            for j = 1,#list do
                for k = 1,#sub_lngs do
                    local sub = string.match(list[j], '^(.+' .. sub_lngs[k] .. '.+)$')
                    if sub then
                        mp.commandv('sub-add', utils.join_path(sub_dirs[i], sub), 'select')
                    end
                end
            end
        end
    end
end

mp.register_event('file-loaded', find_and_add2)

```

**Comment by kaoneko** [comment]
@Exagone313 Neat! I love how the solutions in this issue keep getting better, notwithstanding the fact that it has been marked as _Closed_ for a long time haha.

We can use `mp.set_property('sid', [id])` to select a subtitle track from the script, so if we can figure out the subtitle id...

Btw, I noticed that using `mp.register_event('file-loaded', find_and_add)` spams the terminal with a lot of extra lines for each added subtitle; using `mp.add_hook('on_load', 10, find_and_add)` instead gives a much cleaner output.

**Comment by kaoneko** [comment]
@Exagone313 Not sure what you were trying to do here, but if you actually leave out these lines:
```lua
local selected = false
```
and
```lua
if not selected then
	flags = 'select'
	selected = true
end
```
mpv will respect the slang= and sid= settings made elsewhere (mpv.conf, command line) just fine; i.e. it will auto-select your preferred language (thanks to your code setting the language for each subtitle!) and will also respect a local mpv.conf file setting the sid to a specific number for a series that has e.g. multiple English subtitles and you always want to use the one that's not SDH (Subtitles for the Deaf and Hard-of-hearing).

**Comment by kaoneko** [comment]
I'm studying this script again after getting better at writing LUA scripts, and re-reading this thread I realized removing those lines only worked because I had replaced `mp.register_event('file-loaded', find_and_add)` with `mp.add_hook('on_load', 10, find_and_add)`. So now I understand why they were there too.

The `file-loaded` event _“happens after a file was loaded and begins playback”_. The `on_load` hook is _“called when a file is to be opened, before anything is actually done”_. That explains the difference in console output and auto selection of a subtitle.

Since use of the `on_load` hook is discouraged (_“Basically, nobody should use this API.”_) I went looking for an _event_ that happens before a file is loaded and found the `start-file` event which _“happens right before a new file is loaded”_.

Conclusion: replacing `mp.register_event('file-loaded', find_and_add)` with `mp.register_event('start-file', find_and_add)` and removing the lines discussed in my previous comment results in the script not overriding subtitle selection options like `sid` specified elsewhere while also auto-selecting the first track in the final subtitle track list that matches your `slang` settings.

@usegv @Exagone313 after studying the script and fully understanding it now, I would just like to say: **marvelous script!**

**Comment by N1ck01** [comment]
Sorry for posting in a closed thread but it relates to a script posted here.

> This script will load subtitle files which name contains "English". Adjust the `sub_dir` value to change the main subtitle directory and `sub_lang` to change the language.
https://github.com/mpv-player/mpv/issues/9767#issuecomment-1437767199

Some auto load subtitle scripts have one good feature over others but none have them all in one and I'm hoping someone would be willing to help with that.
Would anyone knowledgeable and helpful enough please be able to get usegv's script to work with multiple sub_dir values (ex: "Subs;Subtitles;srt;ass") by either reading "--sub-file-paths" values from mpv.conf or just from within the script like how multiple languages can be set in two scripts based on usegv's?

There are posts that reference multiple sub_dir values.

The following script can supposedly add more sub_dir values right into the script but I don't know what to change/add...and the script also isn't as featured as usegv's with a language preference.
> Add more sub dir by adding more string in row 2. Maybe there is a better way.
https://github.com/mpv-player/mpv/issues/9767#issuecomment-1024831645

//

The following script supposedly reads the "--sub-file-paths" values from mpv.conf but that feature didn't work. The script only looks to a "Subs" folder no matter what the "--sub-file-paths" option has set.
> I adjusted [@guidocella](https://github.com/guidocella)'s and [@LazyGeniusMan](https://github.com/LazyGeniusMan)'s script so it doesn't overwrite the sub-file-paths option given in mpv.conf or on the command line:
https://github.com/mpv-player/mpv/issues/9767#issuecomment-1289901645

//

The following is a post from another thread but again I don't know what to change/add...and the script also isn't as featured as usegv's with a language preference.
> Just set `sub-file-paths` to whatever you want.
https://github.com/mpv-player/mpv/issues/12464#issuecomment-1731376771

//

Then there's this following post from another thread of a js script that actually does work in reading the "--sub-file-paths" values from mpv.conf but it has a big issue where it keeps previous loaded subs saved and keeps including and adding them up...and it also doesn't have a language preference. But apparently the saved subs issue can be resolved based on a reply if one is knowledgeable.
> This is my final script, that expands on the existing `sub-file-paths` configuration:
https://github.com/mpv-player/mpv/issues/9952#issuecomment-1059961050

Since I don't have the know-how I think usegv's script currently works best and hopefully maybe someone can make this improvement to it. Thanks to anyone who would be willing to try to do it.

**Comment by kaoneko** [comment]
This should do what you want:

```lua
local utils = require "mp.utils"
local langs = {"English", "French", "Spanish"}
local subsdirs = {"Subs", "Subtitles", "srt", "ass"}

function load_subs()
    local subs = {}
    local basedir = utils.split_path(mp.get_property("path"))
    local filename_noext = mp.get_property("filename/no-ext")
    function add_subs_from_dir(path)
        local files = utils.readdir(path, "files")
        if files then
            for _,file in pairs(files) do
                subs[#subs+1] = path.."/"..file
            end
        end
    end
    for _,subsdir in pairs(subsdirs) do
        add_subs_from_dir(basedir.."/"..subsdir)
        add_subs_from_dir(basedir.."/"..subsdir.."/"..filename_noext)
    end
    if #subs == 0 then return end
    table.sort(subs)
    for _,lang in pairs(langs) do
        for _,sub in pairs(subs) do
            if string.match(sub:lower(), lang:lower()) then
                local _,filename = utils.split_path(sub)
                mp.commandv("sub-add", sub, "auto", filename, lang:lower():sub(1,3))
            end
        end
    end
end

mp.register_event("start-file", load_subs)
``` 
You would use this for the same use-cases as usegv's script, but I used my own script as a starting point to write this.

**Comment by kaoneko** [comment]
You're welcome!

**Comment by steinuil** [comment]
I got the itch to write my own version of this script so here you go:

https://kirarin.hootr.club/git/steinuil/flakes/src/branch/master/packages/mpv-loadsubs/loadsubs.lua

Here's the feature list:

- *Actually* uses the paths from `sub-file-paths` to search subs.
- Uses the `sub-auto-exts` option (which has some good defaults) to detect which files are subtitles.
- Works in both of these cases:

```
├─ Big.Buck.Bunny.S01E01.VeryLegalRip.x265-ZIPBG.mkv
├─ Big.Buck.Bunny.S01E02.VeryLegalRip.x265-ZIPBG.mkv
└─ Subs
   ├─ Big.Buck.Bunny.S01E01.VeryLegalRip.x265-ZIPBG
   │  ├─ 2_English.srt
   │  ├─ 3_English.srt
   │  └─ 4_Arabic.srt
   └─ Big.Buck.Bunny.S01E02.VeryLegalRip.x265-ZIPBG
      ├─ 2_English.srt
      ├─ 3_English.srt
      └─ 4_Arabic.srt
```
```
├─ Big.Buck.Bunny.VeryLegalRip.x265-ZIPBG.mkv
└─ Subs
   ├─ 2_English.srt
   ├─ 3_English.srt
   └─ 4_Arabic.srt
```

- Ignores this case to avoid loading subs that don't match the file:
```
├─ Big.Buck.Bunny.S01E01.VeryLegalRip.x265-ZIPBG.mkv
├─ Big.Buck.Bunny.S01E02.VeryLegalRip.x265-ZIPBG.mkv
└─ Subs
   ├─ Big.Buck.Bunny.S01E01.VeryLegalRip.x265-ZIPBG.en.srt
   └─ Big.Buck.Bunny.S01E02.VeryLegalRip.x265-ZIPBG.en.srt
```

- It does not filter the subs it loads based on language but you can override the `should_load` function with your own logic. For example:
```lua
local langs = {"english", "french", "spanish"}

local function should_load(directory, sub_file)
  for i, lang in ipairs(langs) do
    if sub_file:lower():match(lang) then
      return true
    end
  end
  return false
end
```

Or this version, which loads subs based on the `slang` option from `mpv.conf`:

```lua
local language_code_map = {
  en = 'English',
  it = 'Italian',
  fr = 'French',
  es = 'Spanish',
  -- add more...
}

local function should_load(directory, sub_file)
  local sub_languages = mp.get_property_native('slang')

  for i, lang in ipairs(sub_languages) do
    local lang_name = language_code_map[lang]
    if lang_name and sub_file:lower():match(lang_name:lower()) then
      return true
    end
  end

  return false
end
```

**Comment by mrfragger** [comment]
I have mine like
someaudio.opus
anotheraudiofile.opus

and each one has a subdirectory with all the subs in it
someaudio_vtt
anotheraudiofile_vtt

This script loads them all from their respective subdir.
o    script-binding uosc/subtitles  #! [Subtitles] > Select/Load Subtitles
d-x      script-binding uosc/load-subtitles  #! [Subtitles] > Load Subtitles
d-t  script-binding load-subs-subdir #! [Subtitles] > Load Subtitles in filename_vtt subdir
Meta+o      script-binding swap_subtitles  #! [Subtitles] > Swap dual subtitles position

```
local utils = require "mp.utils"

function load_subs()
    mp.msg.info("Attempting to load custom subtitles...")
    local subs = {}
    local path = mp.get_property("path")
    if not path then
        mp.msg.warn("No file loaded. Cannot load subtitles.")
        return
    end

    local basedir, filename = utils.split_path(path)
    local filename_noext = mp.get_property("filename/no-ext")

    if not filename_noext then
        mp.msg.warn("Could not get filename without extension. Cannot load subtitles.")
        return
    end

    local filename_noext_vtt = filename_noext .. "_vtt"

    local filename_noext_underscore = filename_noext:gsub("[ %-]", "_") 
    local filename_noext_underscore_vtt = filename_noext_underscore .. "_vtt"

    local dirs_to_search = {
        utils.join_path(basedir, filename_noext_vtt),            
    }

    local function add_subs_from_dir(dir_path)
        mp.msg.verbose("Searching directory: " .. dir_path)
        local files = utils.readdir(dir_path, "files")
        if files then
            for _, file in pairs(files) do
                local lower_file = file:lower()
                if lower_file:match("%.srt$") or
                   lower_file:match("%.ass$") or
                   lower_file:match("%.ssa$") or
                   lower_file:match("%.vtt$") or
                   lower_file:match("%.sub$") or 
                   lower_file:match("%.idx$")
                then
                    subs[#subs + 1] = utils.join_path(dir_path, file)
                    mp.msg.verbose("Found potential sub: " .. subs[#subs])
                end
            end
        else
            mp.msg.verbose("Directory does not exist or is not readable: " .. dir_path)
        end
    end

    for _, dir_path in pairs(dirs_to_search) do
        add_subs_from_dir(dir_path)
    end

    if #subs == 0 then
        mp.msg.info("No potential subtitles found in scanned directories.")
        return
    end

    table.sort(subs)

    local subtitles_added_count = 0

    for _, sub_path in pairs(subs) do
        local _, filename_only = utils.split_path(sub_path)
        mp.commandv("sub-add", sub_path, "auto", filename_only)
        subtitles_added_count = subtitles_added_count + 1
        mp.msg.verbose("Added sub: " .. sub_path)
    end

    if subtitles_added_count > 0 then
        mp.msg.info("Finished adding " .. subtitles_added_count .. " custom subtitles.")
        mp.osd_message("Finished adding " .. subtitles_added_count .. " custom subtitles.")

    else
        mp.msg.info("No custom subtitles found to add.")
    end

end 

mp.add_key_binding(nil, "load-subs-subdir", load_subs)
```
