### ISSUE TITLE
"video-codec-id" property

### ISSUE THREAD

**Issue by riverscn** [mpv-player/mpv#9768]
"video-codec" property only shows something like "hevc" "h264" etc.

if there is "video-codec-id" property which shows the [raw id of video codec](https://mp4ra.org/#/codecs) will be helpful for conditional auto profiles.

**Comment by kasper93** [comment]
`video-format` exists and `hevc` / `h264` are standard names, you can find mapping to raw id here if you need it https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/codec_desc.c
