### ISSUE TITLE
vf-remove in profile of conf is executed automatically

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#9769]
- mpv version https://github.com/mpv-player/mpv/commit/8087e3371f8ffbdc8ddcbc0445392b0480ef02a4
- Platform and Version win11 22000
- Source of the mpv binary shinchiro

### Reproduction steps

add follows into mpv.conf
```ini
[svpflow-inverse]
vf-remove=@interp
hr-seek-framedrop
osd-msg1="hello"
```

### Expected behavior
vf-remove doesn't auto execute as osd-msg.

### Actual behavior
no osd-msg, but warning for vf-remove
![image](https://user-images.githubusercontent.com/50797982/151175709-b2d278e8-f63d-4b02-a9c5-08d086d290e4.png)

**Comment by guidocella** [comment]
It should be `osd-msg1="hello"` without spaces.

**Comment by Natural-Harmonia-Gropius** [comment]
> without spaces.
yes, but same behavior.
