### ISSUE TITLE
Loading a profile automatically based on video info

### ISSUE THREAD

**Issue by Soukyuu** [mpv-player/mpv#977]
I saw mpv supports profiles, but they have to be manually loaded by the user from what I see. Would it be possible to add further configurations options allowing setting conditions to load a profile automatically depending on video 
- resolution
- fps
- bit depth
- ...

Use case would be for example to use a different scaling algorithm based on video resolution or fps, to either improve video quality or save some resources in case of  a weaker gpu.

**Comment by Shudouken** [comment]
You could write a lua script that runs before loading the video file and calls mediainfo on it, then parses parameters like fps, resolution and so on and changes the options. Would only work on linux though I guess, not sure if os x or windows have mediainfo. Also wouldn't work with youtube links etc. unless you download the file first.

**Comment by Argon-** [comment]
Well, that's basically what wm4 said.
While this works in theory, it would result in lua scripts being used as config files and I guess we can agree on this being not the way things were supposed to be.

Imo the ability to change or activate `--profile`s with LUA scripts would be better.

**Comment by Paviluf** [comment]
I am really interested in profile autoloading to adjust settings according to the video.
Is it possible to autoload a profile with a lua script ?
If yes, can someone give an exemple to write that script please ?

Thank you

**Comment by wm4** [comment]
> Is it possible to autoload a profile with a lua script ?

Not yet. But on the other hand, this wouldn't do more than setting options and properties, which you can do with Lua anyway. (Though it'd force you to have your own profile files and parsing.)

Personally, I'd like to wait until I unify options and properties, so the users don't have to figure out what's the difference between them.

**Comment by Soukyuu** [comment]
I'm currently tinkering with a lua script (first time writing one, really) and I got so far that I can parse file properties. Is triggering  the lua function with `mp.register_event("start-file", profile_select)` already too late to change vo options? Can you please share some more info on that undocumented `vo_cmdline` command?

**Comment by wm4** [comment]
> Is triggering the lua function with mp.register_event("start-file", profile_select) already too late to change vo options? 

No, but it may be too late at this point (because event delivery is asynchronous). You can work this around by  using a hook (like the ytdl script). Also, if the VO is already created (e.g. because this is the second file being played), changing the options will currently do nothing.

What I plan is:
- make options settable at runtime, in a way that they are actually applied even to VOs
- make profiles settable at runtime
- make profiles and their contents accessible to Lua

But it could take weeks until I get there. (There are other things to do too.)

**Comment by Argon-** [comment]
Is using a hook more reliable/earlier than just "letting the script run (once)" when loaded? That's what I'm currently doing and it's fast enough to change the VO, unless you use `force-window=immediate`.

**Comment by Soukyuu** [comment]
So it will at least work for single files for now. Good to know. 

@Argon- : do you mind sharing the script you are using?

**Comment by Argon-** [comment]
[This one](https://github.com/Argon-/mpv-config/blob/master/scripts/auto-options.lua). I'm basically using it only for VO options, although it can set other options as well (e.g. like `hwdec` in l.149). Not particularly nice, but it's only supposed to be "bridge technology" until I can use this script to set profiles (then I'm going to define them in mpv.conf and set them with this script).

**Comment by wm4** [comment]
>Is using a hook more reliable/earlier than just "letting the script run (once)" when loaded? 

They're different use-cases. A hook is called per-file, and before the file is actually loaded.

>That's what I'm currently doing and it's fast enough to change the VO, unless you use force-window=immediate.

If it's convenient, scripts could be loaded before the VO is created the first time.

**Comment by Argon-** [comment]
It certainly would be convenient for this purpose, however, not sure about the implications for other things. Maybe a special "before anything actually happens/is configured/set" hook?

**Comment by wm4** [comment]
Changed the point at which scripts are loaded.

**Comment by Argon-** [comment]
Ok, great, thanks.

**Comment by wm4** [comment]
Since this isn't progressing at all, I added a way to export profiles (see above).

I imagine this could be used to attempt to apply profiles at runtime, by setting each profile item as property, and if that not works, via the ``options/`` property.

I might even try to implement this in mpv/C, but there's a lot of crap to deal with since options and properties are still inconsistent at times (also, updating VO options).

**Comment by lachs0r** [comment]
https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua

I consider this solved with that script.

**Comment by Soukyuu** [comment]
Thank you. The script could use some (more) examples, though, like how to load a profile based on a name pattern or resolution (this used to work with the script posted by Argon above). Or is there some extended documentation somewhere?

For example, I just tried it with 
```
cond:string.find(mp.get_property_osd("filename"), 'mypattern')
```
and the script errored that condition did not return a boolean.

**Comment by Soukyuu** [comment]
Actually, all of the useful properties (filename, path, width, height) listed in the manual seem to be `nil` when the condition is evaluated. So my condition obviously also evaluates to 'nil`

The script is completely useless like this, unless I'm doing it wrong, which is highly possible.

**Comment by lachs0r** [comment]
You’re doing it wrong.
cond:string.find(get("filename", ""), "mypattern") ~= nil

**Comment by Soukyuu** [comment]
Ok, that seems to be working, thanks. Is there more documentation for this, though?

**Comment by Argon-** [comment]
> Actually, all of the useful properties (filename, path, width, height) listed in the manual seem to be nil when the condition is evaluated. So my condition obviously also evaluates to 'nil`

No. Well, yes, at the very start but conditions get re-evaluated when the properties of this condition change. So yeah, first evaluation will probably yield unwanted results as many properties are nil but once their values change the appropriate conditions get re-evaluated.
