### ISSUE TITLE
Single touch input does not function after 0.34.0 release

### ISSUE THREAD

**Issue by bfvogel** [mpv-player/mpv#9770]
Looking at this commit:
https://git.srsfckn.biz/mpv/commit/?h=release/0.34&id=8300830951e2b0b90b22fc7d33b7556ed05e139c

Touch input is now recognized separately from mouse input. as expected but an single touch event in the mpv window only shows the OSD.  OSD cannot be interacted with via touch events at all.  Double touch events with one finger are registered as a mouse double click.  Multiple finger are not recognized.

**Comment by Dudemanguy** [comment]
Touching the OSC definitely works though (just tested it). Just touch it again while it's visible.

**Comment by bfvogel** [comment]
##Downgraded to 0.33.1
## Same input test as previous post.  Single tap, Single Tap,  Double Tap
`[touchscreen_seek] Loaded touchscreen-seek Lua flavor 
[touchscreen_seek_pause] Loaded touchscreen-seek-pause Lua flavor 
[simple_mpv_webui] v3.0.0
[simple_mpv_webui] [::]:8080
[simple_mpv_webui] 192.168.114.22:8080 
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, timescale not set
 (+) Video --vid=1 (*) (h264 3840x1606 23.976fps)
     Video --vid=2 [P] (mjpeg)
     Audio --aid=1 --alang=eng (aac 2ch 48000Hz)
 (+) Audio --aid=2 --alang=eng (*) (ac3 6ch 48000Hz)
 (+) Subs  --sid=1 --slang=pol (*) (mov_text)
     Subs  --sid=2 --slang=eng (mov_text)
File tags:
 Date: 2008-06-22
 Description: After 700 years of doing what he was built for, he'll discover what he was meant for.
 Genre: Animation
 Title: WALL·E
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).
[vo/gpu/vaapi-egl] failed to retrieve libavutil frame constraints
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz 5.1(side) 6ch float
VO: [gpu] 3840x1606 vaapi[nv12]
AV: 00:00:00 / 01:38:12 (0%) A-V:  0.000
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
AV: 00:00:03 / 01:38:12 (0%) A-V:  0.000
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT is bound to:
[input] 1.  'ignore' in <builtin>:1 (default)
[input] 2.  'script-binding touchscreen-seek-pause' in /home/bvogel/.config/mpv/input.conf:31
[input] 3.  'script-binding osc/__keybinding5' in section {input} in <api>:1
[input] 4.  'script-binding osc/__keybinding11' in section {window-controls} in <api>:1
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
AV: 00:00:05 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT is bound to:
[input] 1.  'ignore' in <builtin>:1 (default)
[input] 2.  'script-binding touchscreen-seek-pause' in /home/bvogel/.config/mpv/input.conf:31
[input] 3.  'script-binding osc/__keybinding5' in section {input} in <api>:1
[input] 4.  'script-binding osc/__keybinding11' in section {window-controls} in <api>:1
AV: 00:00:06 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT is bound to:
[input] 1.  'ignore' in <builtin>:1 (default)
[input] 2.  'script-binding touchscreen-seek-pause' in /home/bvogel/.config/mpv/input.conf:31
[input] 3.  'script-binding osc/__keybinding5' in section {input} in <api>:1
[input] 4.  'script-binding osc/__keybinding11' in section {window-controls} in <api>:1
AV: 00:00:07 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT is bound to:
[input] 1.  'ignore' in <builtin>:1 (default)
[input] 2.  'script-binding touchscreen-seek-pause' in /home/bvogel/.config/mpv/input.conf:31
[input] 3.  'script-binding osc/__keybinding5' in section {input} in <api>:1
[input] 4.  'script-binding osc/__keybinding11' in section {window-controls} in <api>:1
[input] Key MBTN_LEFT_DBL is bound to:
[input] 1.  'cycle fullscreen' in <builtin>:1 (default)
[input] 2.  'script-binding touchscreen-seek' in /home/bvogel/.config/mpv/input.conf:30
[input] 3.  'ignore' in section {input} in <api>:7
AV: 00:00:11 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] CLOSE_WIN was received. This pseudo key can be remapped too,
[input] but --input-test will always quit when receiving it.

Exiting... (Quit)
[input] Key MOUSE_LEAVE is bound to:
[input] (nothing)
`

**Comment by Dudemanguy** [comment]
I can't say. The code didn't actually change much. You can clearly see that it still explicitly sends a click `mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);`. As long as your stylus thing is registered as a touch event (which I assume it would be), it should send clicks.

**Comment by bfvogel** [comment]
# Different device (Surface 3) same behavior
[bvogel@Notebook ~]$ mpv WALL·E\ \(2008\).mp4 --input-test
 (+) Video --vid=1 (*) (h264 3840x1606 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 8ch 48000Hz)
 (+) Subs  --sid=1 --slang=pol (*) (mov_text)
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz 7.1 8ch float
VO: [gpu] 3840x1606 vaapi[nv12]
AV: 00:00:00 / 01:38:12 (0%) A-V:  0.000
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
AV: 00:00:01 / 01:38:12 (0%) A-V:  0.000
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT is bound to:
[input] 1.  'ignore' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding5' in section {input} in <api>:1
[input] 3.  'script-binding osc/__keybinding11' in section {window-controls} in <api>:1
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
AV: 00:00:03 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
AV: 00:00:05 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
AV: 00:00:05 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT_DBL is bound to:
[input] 1.  'cycle fullscreen' in <builtin>:1 (default)
[input] 2.  'ignore' in section {input} in <api>:7
AV: 00:00:07 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
AV: 00:00:07 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
AV: 00:00:10 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] CLOSE_WIN was received. This pseudo key can be remapped too,
[input] but --input-test will always quit when receiving it.
AV: 00:00:10 / 01:38:12 (0%) A-V:  0.000 Dropped: 1

Exiting... (Quit)
[input] Key MOUSE_LEAVE is bound to:
[input] (nothing)


If someone can point me at the issue template I will happily refile as I can recrete this across to devices with differing hardware only.  

I just noticed that while OSD interaction has no action if I click in the seek bar it will show / update the "timestamp overlay" (the one that displays within the seek bar) popup to where I touch but does not seek to that timestamp.

**Comment by Dudemanguy** [comment]
When you create an issue, it should have auto generated a template.

**Comment by bfvogel** [comment]
Closing and opening new issue with proper template
#9771

**Comment by Dudemanguy** [comment]
Thanks.
