### ISSUE TITLE
Single touch input not working after 0.34.0 release 

### ISSUE THREAD

**Issue by bfvogel** [mpv-player/mpv#9771]
### Important Information

Provide following Information:
- mpv version
 0.34
- Linux Distribution and Version
Fedora release 35 (Thirty Five)
- Source of the mpv binary
rpmfusion-free
- If known which version of mpv introduced the problem
0.34.0
- Window Manager and version
Gnome (mutter-41.3-1.fc35.x86_64)
- GPU driver and version
Intel
#8934 [bvogel@Notebook ~]$ vainfo
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_12
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD

### Reproduction steps
Play movie with mpv
Tap (finger) on touchscreen to sow OSD
Tap (finger) on OSD object #No interaction occurs even though event is registered 
Close mpv with mouse or keyboard commands as OSD is unusable via touch input
### Expected behavior
Touch taps / moves would be handled as a separate event with actionable bindings
### Actual behavior
Single touch input while registered as a MBTN_LEFT does not interact with OSD or remapped commands.  Mouse click work as expected.  Double touch input registers as MBTN_LEFT_DBLand works as expected.
### Log file
https://0x0.st/oHrB.txt

###input-test
[bvogel@Notebook ~]$ mpv WALL·E\ \(2008\).mp4 --input-test
 (+) Video --vid=1 (*) (h264 3840x1606 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 8ch 48000Hz)
 (+) Subs  --sid=1 --slang=pol (*) (mov_text)
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz 7.1 8ch float
VO: [gpu] 3840x1606 vaapi[nv12]
AV: 00:00:00 / 01:38:12 (0%) A-V:  0.000
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
AV: 00:00:03 / 01:38:12 (0%) A-V:  0.000
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT is bound to:
[input] 1.  'ignore' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding5' in section {input} in <api>:1
[input] 3.  'script-binding osc/__keybinding11' in section {window-controls} in <api>:1
[input] Key MOUSE_LEAVE is bound to:
[input] 1.  'script-binding osc/__keybinding2' in section {showhide} in <api>:2
[input] 2.  'script-binding osc/__keybinding4' in section {showhide_wc} in <api>:2
AV: 00:00:04 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
AV: 00:00:05 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
AV: 00:00:05 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_MOVE is bound to:
[input] 1.  'script-binding osc/__keybinding1' in section {showhide} in <api>:1
[input] 2.  'script-binding osc/__keybinding3' in section {showhide_wc} in <api>:1
[input] Key MBTN_LEFT_DBL is bound to:
[input] 1.  'cycle fullscreen' in <builtin>:1 (default)
[input] 2.  'ignore' in section {input} in <api>:7
AV: 00:00:08 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
AV: 00:00:08 / 01:38:12 (0%) A-V:  0.000 Dropped: 1
[input] CLOSE_WIN was received. This pseudo key can be remapped too,
[input] but --input-test will always quit when receiving it.

Exiting... (Quit)
[input] Key MOUSE_LEAVE is bound to:
[input] (nothing)

**Comment by Dudemanguy** [comment]
Just to be absolutely clear, if you revert 8300830951e2b0b90b22fc7d33b7556ed05e139c on master does it work normally again?

**Comment by bfvogel** [comment]
I've only been downgrading the binary release to 0.33.1 to revert.  The behavior describe in [8300830](https://github.com/mpv-player/mpv/commit/8300830951e2b0b90b22fc7d33b7556ed05e139c) is the only single touch behavior present.

I'll setup a build environment within fc35 and see iff pulling the individual change resolves.

**Comment by bfvogel** [comment]
> Just to be absolutely clear, if you revert [8300830](https://github.com/mpv-player/mpv/commit/8300830951e2b0b90b22fc7d33b7556ed05e139c) on master does it work normally again?

**Confirmed** an individual revert of 8300830 from master resolves the issue.

**Comment by Dudemanguy** [comment]
Wonderful, that makes zero sense. I'll try to think of something.

**Comment by Dudemanguy** [comment]
Does this really dumb patch make any difference?

```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index 1f176aaad3..bcb7fe437f 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -285,18 +285,18 @@ static void touch_handle_down(void *data, struct wl_touch *wl_touch,
 {
     struct vo_wayland_state *wl = data;
 
-    wl->mouse_x = wl_fixed_to_int(x_w) * wl->scaling;
-    wl->mouse_y = wl_fixed_to_int(y_w) * wl->scaling;
-
-    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
-    mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);
-
     enum xdg_toplevel_resize_edge edge;
     if (check_for_resize(wl, x_w, y_w, wl->opts->edge_pixels_touch, &edge)) {
         xdg_toplevel_resize(wl->xdg_toplevel, wl->seat, serial, edge);
     } else {
         xdg_toplevel_move(wl->xdg_toplevel, wl->seat, serial);
     }
+
+    wl->mouse_x = wl_fixed_to_int(x_w) * wl->scaling;
+    wl->mouse_y = wl_fixed_to_int(y_w) * wl->scaling;
+
+    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
+    mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);
 }
 
 static void touch_handle_up(void *data, struct wl_touch *wl_touch,
````

**Comment by bfvogel** [comment]
With that patch things function exactly as they did prior to 8300830.  All functionality added in 8300830 IE resize of window and move window does not function.

**Comment by Dudemanguy** [comment]
Oh wait so previously you could click but not drag/resize the window? And now you can drag/resize the window but not click?

**Comment by Dudemanguy** [comment]
@bfvogel: Okay hopefully this does the trick. I tested this out on my pinephone and it works OK. I don't really understand why the resize/move stuff has to happen first in your case, but if it works I'll just commit it.

```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index 1f176aaad3..1ecdd35e64 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -284,19 +284,20 @@ static void touch_handle_down(void *data, struct wl_touch *wl_touch,
                               int32_t id, wl_fixed_t x_w, wl_fixed_t y_w)
 {
     struct vo_wayland_state *wl = data;
-
     wl->mouse_x = wl_fixed_to_int(x_w) * wl->scaling;
     wl->mouse_y = wl_fixed_to_int(y_w) * wl->scaling;
 
-    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
-    mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);
-
     enum xdg_toplevel_resize_edge edge;
-    if (check_for_resize(wl, x_w, y_w, wl->opts->edge_pixels_touch, &edge)) {
-        xdg_toplevel_resize(wl->xdg_toplevel, wl->seat, serial, edge);
-    } else {
-        xdg_toplevel_move(wl->xdg_toplevel, wl->seat, serial);
+    if (!mp_input_test_dragging(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y)) {
+        if (check_for_resize(wl, x_w, y_w, wl->opts->edge_pixels_touch, &edge)) {
+            xdg_toplevel_resize(wl->xdg_toplevel, wl->seat, serial, edge);
+        } else  {
+            xdg_toplevel_move(wl->xdg_toplevel, wl->seat, serial);
+        }
     }
+
+    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
+    mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);
 }
 
 static void touch_handle_up(void *data, struct wl_touch *wl_touch,
```

**Comment by bfvogel** [comment]
This patch works to process the OSD actions but has no windows move / resize functionality.  I'm fine with that as double taping to go fullscreen would be the only thing I would ever do via touch.  Mouse movements allow me to resize so I say it is good.

**Comment by Dudemanguy** [comment]
Well I don't want to break windows moving/resizing. That's supposed to work. I'll go back to the first patch I suppose. I think that one worked (need to test it locally again).

**Comment by bfvogel** [comment]
Circling back to this issue as I rebuilt my daily driver r2in 1 laptop for Fedora 36 and was reminded that this issue exists.  My guess is that this is something upstream in Gnome's multitouch handling as trying both of the historical patches in this thread against master currently do not resolve the issue in my fresh install.  I'm happy to aid in diagnostic if anyone has the cycles.

**Comment by christoph-heinrich** [comment]
I've ran into this problem when testing https://github.com/christoph-heinrich/pointer_event/blob/master/pointer_event.lua.
The problem with touch input is that the `mbtn_left` down event gets sent first, followed by the position update.

I was observing the `mouse-pos` property instead of binding to `mouse_move` like osc.lua does because of [the problems this causes](https://github.com/tomasklaen/uosc/issues/295) (which btw are also present in osc.lua as pointed out in https://github.com/tomasklaen/uosc/issues/295), but it must be the same problem here.

osc.lua only binds to `mbtn_left` when the cursor is over an element, this leads to two scenarios when touching an element.
1. The last known position to osc is not over an element, therefore it's not bound to `mbtn_left` and all it sees is that the position got updated.
2. The last known position to osc is over an element, so it's already bound to `mbtn_left`, however when touching it still hasn't received a new position when the down event happens and so it registers the touch in the wrong position.

**Comment by Dudemanguy** [comment]
Does simply swapping the order work?
```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index e4a590704b..a410d71d81 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -303,8 +303,8 @@ static void touch_handle_down(void *data, struct wl_touch *wl_touch,
     wl->mouse_x = wl_fixed_to_int(x_w) * wl->scaling;
     wl->mouse_y = wl_fixed_to_int(y_w) * wl->scaling;
 
-    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
     mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);
+    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
 
     enum xdg_toplevel_resize_edge edge;
     if (check_for_resize(wl, x_w, y_w, wl->opts->edge_pixels_touch, &edge)) {
```

Not sure if that's actually related to this particular issue because it's always been `set_mouse_pos` before `put_key`.

**Comment by christoph-heinrich** [comment]
I've now tested it and added an output for `mouse_move` and without swapping those lines around, `mouse_move` does trigger before `mbtn_left`, so this is is not the issue here. With the patch applied, unsurprisingly, the order is swapped around.

It is however still the case that the lua script misses the down event when the last known position before the touch is not on top of an element, because by the time the script gets to bind `mbtn_left` the event has already happened. To really solve this we would need a way of constantly listening to mouse button activity without blocking other scripts from doing the same. This can already be done for the mouse position with the `mouse-pos` property, so maybe properties for mouse button state would be a good idea?

While testing this I did notice something else. When I left click on the floating window I get the down event and then immediately after the up event and so far I assumed that is because of window dragging. However when I touch the window I only get the down event despite window dragging activating and the up event happens when I let go again. This is also the behavior on windows when clicking with a mouse. But on kde plasma on wayland clicking with the mouse behaves differently for some reason.

Getting the up event immediately after down has one advantage though. By measuring the time between events it enables the detection of window dragging, which is otherwise not possible afaik.

**Comment by Dudemanguy** [comment]
The wayland code does actually explicitly send a "mouse up" after a click. There was a bug related to this a long time ago I don't exactly remember. I don't think your issue is related to the OP's problem though (in fact, I was never able to reproduce OP's thing).

**Comment by bfvogel** [comment]
Now my absence is the drag.  I can confirm that Dudemanguy's path from Jan27 on a fully patched fedora 37 build fixes my touch input issue and retains the resize behavior.

**Comment by Dudemanguy** [comment]
Just to be clear, is that mpv 0.35 or still 0.34.1?

**Comment by bfvogel** [comment]
> @bfvogel: Okay hopefully this patch does the trick (unapply/remove the old one if it's still there). I tested this out on my pinephone and it works OK. I don't really understand why the resize/move stuff has to happen first in your case, but if it works I'll just commit it.
> 
> ```
> diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
> index 1f176aaad3..1ecdd35e64 100644
> --- a/video/out/wayland_common.c
> +++ b/video/out/wayland_common.c
> @@ -284,19 +284,20 @@ static void touch_handle_down(void *data, struct wl_touch *wl_touch,
>                                int32_t id, wl_fixed_t x_w, wl_fixed_t y_w)
>  {
>      struct vo_wayland_state *wl = data;
> -
>      wl->mouse_x = wl_fixed_to_int(x_w) * wl->scaling;
>      wl->mouse_y = wl_fixed_to_int(y_w) * wl->scaling;
>  
> -    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
> -    mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);
> -
>      enum xdg_toplevel_resize_edge edge;
> -    if (check_for_resize(wl, x_w, y_w, wl->opts->edge_pixels_touch, &edge)) {
> -        xdg_toplevel_resize(wl->xdg_toplevel, wl->seat, serial, edge);
> -    } else {
> -        xdg_toplevel_move(wl->xdg_toplevel, wl->seat, serial);
> +    if (!mp_input_test_dragging(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y)) {
> +        if (check_for_resize(wl, x_w, y_w, wl->opts->edge_pixels_touch, &edge)) {
> +            xdg_toplevel_resize(wl->xdg_toplevel, wl->seat, serial, edge);
> +        } else  {
> +            xdg_toplevel_move(wl->xdg_toplevel, wl->seat, serial);
> +        }
>      }
> +
> +    mp_input_set_mouse_pos(wl->vo->input_ctx, wl->mouse_x, wl->mouse_y);
> +    mp_input_put_key(wl->vo->input_ctx, MP_MBTN_LEFT | MP_KEY_STATE_DOWN);
>  }
>  
>  static void touch_handle_up(void *data, struct wl_touch *wl_touch,
> ```

Pulled the latest master today and built and the issue still existed.

Applied quoted above and rebuilt he issue is gone.

**Comment by Dudemanguy** [comment]
Thanks! I'll find some time tomorrow to double check my devices (I actually have a drawing tablet now yay) and see if anything weird happens. If it looks good then I'll go ahead and commit it finally.
