### ISSUE TITLE
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device and other errors on fresh install

### ISSUE THREAD

**Issue by cachho** [mpv-player/mpv#9773]
### Important Information

Provide following Information:
- mpv version: 0.34.0-158-g8087e3371f 
- Linux Distribution and Version: Ubuntu 20.04.3 LTS x86_64
- Source of the mpv binary: https://github.com/mpv-player/mpv-build.git
- If known which version of mpv introduced the problem: this is the first version I'm using
- Window Manager and version: awesome v4.3
- GPU driver and version: lshw -c video 
- Device is a 2015 MacBook Pro

### Reproduction steps
mpv -v --no-config --log-file=mpv-log.txt ~/Downloads/640.mp4 

### Expected behavior
Play the video

### Actual behavior
 (+) Video --vid=1 (*) (h264 640x360 24.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu] Failed to commit ModeSetting atomic request (-13)
[vo/gpu/opengl] Failed to set CRTC for connector 77: Permission denied
Error opening/initializing the selected video_out (--vo) device.
Video: no video

### Log file

Link: https://0x0.st/oHsI.txt

[   0.004][v][cplayer] mpv 0.34.0-158-g8087e3371f Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Thu Jan 27 00:32:39 CET 2022
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       57.19.100
[   0.004][v][cplayer]    libavcodec      59.20.100
[   0.004][v][cplayer]    libavformat     59.17.101
[   0.004][v][cplayer]    libswscale      6.5.100
[   0.004][v][cplayer]    libavfilter     8.26.101
[   0.004][v][cplayer]    libswresample   4.4.100
[   0.004][v][cplayer] FFmpeg version: N-105374-gb2421c4f26
[   0.004][v][cplayer] 
[   0.004][v][cplayer] Configuration: ./waf configure
[   0.004][v][cplayer] List of enabled features: alsa asm build-date cplayer cplugins debug-build drm egl egl-drm egl-helpers ffmpeg gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jpeg lcms2 libass libavdevice libdl libm librt linux-fstatfs linux-input-event-codes memfd_create optimize posix posix-or-mingw pthreads pulse stdatomic vaapi vaapi-drm vaapi-egl vaapi-wayland vector vt.h wayland wayland-protocols zlib
[   0.004][v][cplayer] Command line options: '-v' '--no-config' '--log-file=mpv-log.txt' '/home/carl/Downloads/640.mp4'
[   0.004][v][cplayer] mpv 0.34.0-158-g8087e3371f Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Thu Jan 27 00:32:39 CET 2022
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       57.19.100
[   0.004][v][cplayer]    libavcodec      59.20.100
[   0.004][v][cplayer]    libavformat     59.17.101
[   0.004][v][cplayer]    libswscale      6.5.100
[   0.004][v][cplayer]    libavfilter     8.26.101
[   0.004][v][cplayer]    libswresample   4.4.100
[   0.004][v][cplayer] FFmpeg version: N-105374-gb2421c4f26
[   0.004][v][cplayer] 
[   0.004][v][cplayer] Configuration: ./waf configure
[   0.004][v][cplayer] List of enabled features: alsa asm build-date cplayer cplugins debug-build drm egl egl-drm egl-helpers ffmpeg gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jpeg lcms2 libass libavdevice libdl libm librt linux-fstatfs linux-input-event-codes memfd_create optimize posix posix-or-mingw pthreads pulse stdatomic vaapi vaapi-drm vaapi-egl vaapi-wayland vector vt.h wayland wayland-protocols zlib
[   0.004][d][global] config path: '' -> '-'
[   0.004][d][global] user path: '~~home/' -> ''
[   0.004][d][global] user path: '~~old_home/' -> ''
[   0.004][v][cplayer] Setting option 'v' = '' (flags = 8)
[   0.004][v][cplayer] Setting option 'config' = 'no' (flags = 8)
[   0.004][v][cplayer] Setting option 'log-file' = 'mpv-log.txt' (flags = 8)
[   0.006][d][global] user path: 'mpv-log.txt' -> 'mpv-log.txt'
[   0.006][d][global] config path: 'watch_later' -> '-'
[   0.006][d][global] config path: 'watch_later' -> '-'
[   0.006][v][file] Opening /home/carl/Downloads/640.mp4
[   0.006][d][file] resize stream to 131072 bytes, drop 0 bytes
[   0.006][d][file] Stream opened successfully.
[   0.006][v][demux] Trying demuxers for level=normal.
[   0.006][d][demux] Trying demuxer: disc (force-level: normal)
[   0.006][d][demux] Trying demuxer: edl (force-level: normal)
[   0.006][d][demux] Trying demuxer: cue (force-level: normal)
[   0.006][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.006][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.006][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.006][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.012][v][lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[   0.013][v][demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[   0.013][v][cplayer] Opening done: /home/carl/Downloads/640.mp4
[   0.014][v][find_files] Loading external files in /home/carl/Downloads/
[   0.014][d][find_files] Potential external file: "hws_logo_zoom.png"  Priority: 0
[   0.014][d][find_files] Potential external file: "citygobuy_logo.jpg"  Priority: 0
[   0.014][d][find_files] Potential external file: "hws_banner_LQ.png"  Priority: 0
[   0.014][d][find_files] Potential external file: "CityGoBuy_logo.png"  Priority: 0
[   0.014][d][find_files] Potential external file: "IMG_6923.JPG"  Priority: 0
[   0.014][d][find_files] Potential external file: "IMG_6922.JPG"  Priority: 0
[   0.014][v][lavf] select track 0
[   0.014][v][lavf] select track 1
[   0.014][i][cplayer]  (+) Video --vid=1 (*) (h264 640x360 24.000fps)
[   0.014][i][cplayer]  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[   0.014][v][vo/gpu] Probing for best GPU context.
[   0.014][v][vo/gpu/opengl] Initializing GPU context 'wayland'
[   0.014][v][vo/gpu/opengl] Initializing GPU context 'drm'
[   0.014][e][vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[   0.014][w][vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[   0.014][v][vo/gpu/opengl] Initializing KMS
[   0.014][v][vo/gpu/opengl] Picked DRM card 0, primary node /dev/dri/card0 as the default.
[   0.015][v][vo/gpu/opengl] Driver: i915 1.6.0 (20201103)
[   0.016][v][vo/gpu/opengl/kms] Connector 77 currently connected to encoder 76
[   0.016][v][vo/gpu/opengl/kms] Selected Encoder 76 with CRTC 45
[   0.016][v][vo/gpu/opengl/kms] Selected mode: 2560x1600 (2560x1600@59.97Hz)
[   0.016][v][vo/gpu/opengl] DRM Atomic support found
[   0.017][v][vo/gpu/opengl/kms] Using primary plane 31 as draw plane
[   0.017][v][vo/gpu/opengl/kms] Using overlay plane 35 as drmprime plane
[   0.017][v][vo/gpu] GBM_FORMAT_ARGB8888 not supported by draw plane: Falling back to GBM_FORMAT_XRGB8888.
[   0.017][v][vo/gpu] Supported modifier: 0x100000000000001
[   0.017][v][vo/gpu] Supported modifier: 0x0
[   0.017][v][vo/gpu] Creating GBM device
[   0.043][v][vo/gpu] Initializing GBM surface (2560 x 1600)
[   0.043][v][vo/gpu/opengl] Initializing EGL
[   0.045][v][vo/gpu/opengl] EGL_VERSION=1.5
[   0.045][v][vo/gpu/opengl] EGL_VENDOR=Mesa Project
[   0.045][v][vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[   0.045][v][vo/gpu/opengl] Trying to create Desktop OpenGL context.
[   0.045][v][vo/gpu/opengl] Attempting to find EGLConfig matching GBM_FORMAT_XRGB8888
[   0.045][v][vo/gpu/opengl] Found matching EGLConfig for GBM_FORMAT_XRGB8888
[   0.045][d][vo/gpu/opengl] Chosen EGLConfig:
[   0.045][d][vo/gpu/opengl]   EGL_CONFIG_ID=0x31
[   0.045][d][vo/gpu/opengl]   EGL_RED_SIZE=0x8
[   0.045][d][vo/gpu/opengl]   EGL_GREEN_SIZE=0x8
[   0.045][d][vo/gpu/opengl]   EGL_BLUE_SIZE=0x8
[   0.045][d][vo/gpu/opengl]   EGL_ALPHA_SIZE=0x0
[   0.045][d][vo/gpu/opengl]   EGL_COLOR_BUFFER_TYPE=0x308e
[   0.045][d][vo/gpu/opengl]   EGL_CONFIG_CAVEAT=0x3038
[   0.045][d][vo/gpu/opengl]   EGL_CONFORMANT=0x4d
[   0.045][d][vo/gpu/opengl]   EGL_NATIVE_VISUAL_ID=0x34325258
[   0.047][v][vo/gpu/opengl] Initializing EGL surface
[   0.053][v][vo/gpu] GL_VERSION='4.6 (Core Profile) Mesa 21.0.3'
[   0.053][v][vo/gpu] Detected desktop OpenGL 4.6.
[   0.053][v][vo/gpu] GL_VENDOR='Intel'
[   0.053][v][vo/gpu] GL_RENDERER='Mesa Intel(R) Iris(R) Graphics 6100 (BDW GT3)'
[   0.053][v][vo/gpu] GL_SHADING_LANGUAGE_VERSION='4.60'
[   0.053][d][vo/gpu] Combined OpenGL extensions string:
[   0.053][d][vo/gpu] EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display  GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_gpu_shader_int64 GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_texture_float GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_demote_to_helper_invocation GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_multimode_draw_arrays GL_INTEL_blackhole_render GL_INTEL_performance_query GL_INTEL_shader_integer_functions2 GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_framebuffer_flip_y GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NV_compute_shader_derivatives GL_NV_conditional_render GL_NV_copy_image GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_OES_EGL_image GL_S3_s3tc
[   0.053][v][vo/gpu] Loaded extension GL_KHR_debug.
[   0.054][v][vo/gpu/opengl] Preparing framebuffer
[   0.054][v][vo/gpu/opengl] GBM surface using modifier 0x100000000000001
[   0.054][e][vo/gpu] Failed to commit ModeSetting atomic request (-13)
[   0.054][e][vo/gpu/opengl] Failed to set CRTC for connector 77: Permission denied
[   0.054][f][cplayer] Error opening/initializing the selected video_out (--vo) device.
[   0.054][v][lavf] deselect track 0
[   0.054][i][cplayer] Video: no video
[   0.054][v][ad] Codec list:
[   0.054][v][ad]     aac - AAC (Advanced Audio Coding)
[   0.054][v][ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[   0.054][v][ad] Opening decoder aac
[   0.054][v][ad] Requesting 1 threads for decoding.
[   0.056][v][ad] Selected codec: aac (AAC (Advanced Audio Coding))
[   0.056][v][af] User filter list:
[   0.056][v][af]   (empty)
[   0.056][v][cplayer] Starting playback...
[   0.056][v][cplayer] EOF code: 6  
[   0.056][d][ad] Uninit decoder.
[   0.056][d][cplayer] Terminating demuxers...
[   0.056][d][cplayer] Done terminating demuxers.
[   0.056][v][cplayer] finished playback, something happened (reason 4)
[   0.056][i][cplayer] 
[   0.056][i][cplayer] Exiting... (Errors when loading file)

**Comment by M1ndo** [comment]
I can confirm, i'm having the same issue.
here's the full log file: https://0x0.st/oHdK.txt

**Comment by marlencrabapple** [comment]
Also dealing with this after my last system update

`mpv -v --no-config --log-file=mpv-log insta.webm`:
https://0x0.st/oQOr.txt

`glxinfo -B`:
https://0x0.st/oQOs.txt

**Comment by Dudemanguy** [comment]
OP's build is actually just missing X11 support which is why that message appears. Some other logs in this issue also indicate missing X11 support. Normally, I would say you guys are missing libxpresent, but the older messages in this thread were from before that was a requirement and @marlencrabapple appears to be using 0.34 (before that was required as well). In any case, the solution is to build mpv with x11 support so I'll close this.

**Comment by qmega** [comment]
FWIW, if you aren't sure what you need to install, adding build flag `-Dx11=enabled` (meson) or `--enable-x11` (waf) will give you a build failure and some more information when you're missing a dependency.

**Comment by mlindner** [comment]
I'm also having this issue on Arch Linux. I have x11 headers installed but it doesn't seem to work regardless.

**Comment by mlindner** [comment]
Fixed by installing "libxpresent" package on Arch Linux.

**Comment by ryusko2** [comment]
I have built with X11 support, installed `libxpresent`, and I still get this error :(

`mpv 0.34.0-UNKNOWN

    d3d11     : NO
    gpu-next  : YES
    javascript: YES
    libmpv    : YES
    lua       : YES
    opengl    : YES
    vulkan    : YES
    wayland   : YES
    x11       : YES

  User defined options
    buildtype : plain
    prefix    : /usr
    sysconfdir: /etc
    wrap_mode : nodownload
    dvbin     : enabled
    libmpv    : true
    libplacebo: enabled
    lua       : luajit
    wayland   : enabled
    x11       : enabled`

**Comment by oskarvid** [comment]
I had the same issue so I installed `libxpresent` and recompiled and now it works, I'm running Ubuntu 20.04.

**Comment by cachho** [comment]
> I have built with X11 support, installed `libxpresent`, and I still get this error :(
> 
> ```
> 
>     d3d11     : NO
>     gpu-next  : YES
>     javascript: YES
>     libmpv    : YES
>     lua       : YES
>     opengl    : YES
>     vulkan    : YES
>     wayland   : YES
>     x11       : YES
> 
>   User defined options
>     buildtype : plain
>     prefix    : /usr
>     sysconfdir: /etc
>     wrap_mode : nodownload
>     dvbin     : enabled
>     libmpv    : true
>     libplacebo: enabled
>     lua       : luajit
>     wayland   : enabled
>     x11       : enabled
> ```

how do you get this overview?

**Comment by CounterPillow** [comment]
> how do you get this overview?

That's meson's output after configuring the build.

**Comment by stax76** [comment]
On Ubuntu, I don't understand why `sudo apt install libxpresent-dev` is needed? Isn't already `sudo apt build-dep mpv` supposed to install that?

**Comment by CounterPillow** [comment]
> On Ubuntu, I don't understand why `sudo apt install libxpresent-dev` is needed? Isn't already `sudo apt build-dep mpv` supposed to install that?

libxpresent-dev is a new dependency in 0.35. The mpv version which build-dep pulls the build-deps from is that from the Ubuntu repositories, which for you likely still is 0.34.

**Comment by stax76** [comment]
That explains it, thanks.

**Comment by rubyFeedback** [comment]
I had the same problem but twiddling with libxpresent or passing
-Dx11=enabled did not help.

I think my issue had to do with something related to nvidia. mpv was working
fine until I recompiled it (from default manjaro), so I messed up something.
Not sure how to resolve this but I mention it in case someone else finds the
same error message (the part from vo/gpu is the same).


[vo/gpu/drm] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/drm] Failed to create DRM atomic context, no DRM Atomic support
[vo/gpu/libplacebo] EnumeratePhysicalDevices(inst, &num, NULL): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/context.c:984)
[vo/gpu/libplacebo] Found no suitable device, giving up.
[vo/gpu/libplacebo] Failed initializing vulkan device
[vo/gpu/libplacebo] EnumeratePhysicalDevices(inst, &num, NULL): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/context.c:984)
[vo/gpu-next/drm] Can't handle VT release - signal already used
[vo/gpu-next/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu-next/drm] Failed to create DRM atomic context, no DRM Atomic support
[vo/gpu-next/libplacebo] EnumeratePhysicalDevices(inst, &num, NULL): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/context.c:984)
[vo/gpu-next/libplacebo] Found no suitable device, giving up.
[vo/gpu-next/libplacebo] Failed initializing vulkan device
[vo/gpu-next/libplacebo] EnumeratePhysicalDevices(inst, &num, NULL): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/context.c:984)
[vo/vdpau] Warning: this compatibility VO is low quality and may have issues with OSD, scaling, screenshots and more.
[vo/vdpau] vo=gpu is the preferred choice in any case and includes VDPAU support via hwdec=vdpau or vdpau-copy.

**Comment by CounterPillow** [comment]
@rubyFeedback congratulations, you completely broke your graphics stack
