### ISSUE TITLE
How to allow only certain file format in the playlist ?

### ISSUE THREAD

**Issue by LazyGeniusMan** [mpv-player/mpv#9775]
My folder structure is like this:
```
│   log.txt
│
├───folder 1
│   │   video-1.mp4
│   │   video-2.mp4
│   │   video-3.mp4
│   │
│   └───Subs
│       ├───video-1
│       │       Bahasa.srt
│       │       English.srt
│       │
│       ├───video-2
│       │       Bahasa.srt
│       │       English.srt
│       │
│       └───video-3
│               Bahasa.srt
│               English.srt
│
└───folder 2
    │   video-1.mp4
    │   video-2.mp4
    │   video-3.mp4
    │
    └───Subs
        ├───video-1
        │       Bahasa.srt
        │       English.srt
        │
        ├───video-2
        │       Bahasa.srt
        │       English.srt
        │
        └───video-3
                Bahasa.srt
                English.srt

```
Is there a way to make playlist only load certain file type (e.g. video only like `mp4`, `mkv`, etc). Currently if I drag the folder or do `mpv .` in that dir, I have this playlist:
![image](https://user-images.githubusercontent.com/58850480/151269270-1ab58b1a-2c59-4dce-a0d3-23b27d800ec0.png)

as you can see the subtitle and even `log.txt` is loaded in playlist, I prefer only the video file is loaded.

I tried to use `playlistmanager.lua` like in this issue https://github.com/mpv-player/mpv/issues/8363#issuecomment-739112451 (using video format instead of video) but looks like it's not working for my case (the screenshot is after I add that script)

### Log file
https://0x0.st/oHsl.txt

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/2595

**Comment by LazyGeniusMan** [comment]
> dup #2595

AIght thanks it's miliar to my case, but instead of delete the file from list that match the array, I want to remove the one that not match the array.

I tried to modified that script into this but MPV won't even load ._.
```lua
ALLOWED_EXTENSIONS = {"mkv", "avi", "mp4", "ogv", "webm", "rmvb", "flv", "wmv", "mpeg", "mpg", "m4v", "3gp" , "m2ts"}

mp.observe_property('playlist-count', 'number', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        for _, extension in pairs(ALLOWED_EXTENSIONS) do
            if playlist[i].filename:match('%.' .. extension .. '$') == nil then
                mp.commandv('playlist-remove', i-1)
            end
        end
    end
end)
```
could someone help me ? I dont have much experience with LUA

**Comment by guidocella** [comment]
```lua
ALLOWED_EXTENSIONS = {'mkv', 'avi', 'mp4', 'ogv', 'webm', 'rmvb', 'flv', 'wmv', 'mpeg', 'mpg', 'm4v', '3gp' , 'm2ts'}

mp.observe_property('playlist-count', 'number', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        local allowed = false
        for _, extension in pairs(ALLOWED_EXTENSIONS) do
            if playlist[i].filename:match('%.' .. extension .. '$') then
                allowed = true
                break
            end
        end
        if not allowed then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

**Comment by occivink** [comment]
I have a [script](https://github.com/occivink/mpv-scripts/blob/master/scripts/blacklist-extensions.lua) that does essentially what @guidocella posted, with some more configurability (whitelist/blacklist)

**Comment by LazyGeniusMan** [comment]
@guidocella it's still not working, it has same log with my modified script (https://0x0.st/oHzc.txt)

@occivink Thanks it's working, it was not working before because I didn't notice that `script-opts` is using underscore but `scripts` using hyphen haha
