### ISSUE TITLE
[Question] How to show MPV's builtin STATS programingly

### ISSUE THREAD

**Issue by CarterLi** [mpv-player/mpv#9776]
IINA uses libmpv as its backend and we want to toggle showing [mpv statistics](https://mpv.io/manual/master/#stats). I can't find any options / commands to do it except [--load-stats-overlay](https://mpv.io/manual/master/#options-load-stats-overlay) which doesn't seem to be useful

**Comment by CarterLi** [comment]
Ref: https://github.com/iina-plus/iina/issues/29

Can I send keyboard events to libmpv?

**Comment by avih** [comment]
> Can I send keyboard events to libmpv?

iiana can, I don't know whether it allows users to send them to mpv.

As for `stats.lua`, it can also be activated using `script-message`. See the "Different key bindings" section at the stats docs, though again, I don't know if iiana has a way to allow users to send script-messages to mpv.

**Comment by CarterLi** [comment]
I'm one of a developer of IINA and I'm searching for method to communicate with libmpv using various options / commands. Sorry for confusion.

> > Can I send keyboard events to libmpv?
> 
> iiana can, I don't know whether it allows users to send them to mpv.

I mean if I can forward keyboard events to libmpv somehow.

> 
> As for `stats.lua`, it can also be activated using `script-message`. See the "Different key bindings" section at the stats docs, though again, I don't know if iiana has a way to allow users to send script-messages to mpv.

IINA don't uses MPV's native window but IINA creates its own, so MPV won't receive users keyboard events directly. We have to forward these keyboard events to libmpv using libmpv's API somehow.

As for `script-message`, I still don't know how to use it. Any examples?

**Comment by avih** [comment]
The simplest way for both would be with to send a `keypress KEY` and/or `script-message MESSAGE ARG...` commands to mpv.

There are other ways. `client.h` is documented quite well.

**Comment by avih** [comment]
> As for `stats.lua`, it can also be activated using `script-message`. See the "Different key bindings" section at the stats docs

Sorry, `script-binding`, not `script-message`. E.g. `script-binding stats/display-stats-toggle` (as seen at that docs section).
