### ISSUE TITLE
MPD playback failed when baseurl is relative address

### ISSUE THREAD

**Issue by rolandjon** [mpv-player/mpv#9778]
### Important Information

Provide following Information:
- mpv version
git master
- Linux Distribution and Version
ubuntu 20.04
- Source of the mpv binary
git master
- If known which version of mpv introduced the problem
none
- Window Manager and version
gnome
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
try those streams:
https://testassets.dashif.org/#testvector/details/5aafc9bda5eeda55aa662dc0

mpv https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/ThreePeriods/ThreePeriod_OnDemand_presentationDur.mpd
---
[   0.012][v][ffmpeg] Opening https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd
[   0.012][t][ffmpeg] https: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[   0.025][t][ffmpeg] tcp: Original list of addresses:
[   0.025][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   0.025][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   0.025][t][ffmpeg] tcp: Interleaved list of addresses:
[   0.025][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   0.025][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   0.025][d][ffmpeg] tcp: Starting connection attempt to 23.215.177.211 port 443
[   0.029][d][ffmpeg] tcp: Successfully connected to 23.215.177.211 port 443
[   0.388][t][ffmpeg] https: request: GET /dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd HTTP/1.1
[   0.388][t][ffmpeg] User-Agent: libmpv
[   0.388][t][ffmpeg] Accept: */*
[   0.388][t][ffmpeg] Range: bytes=0-
[   0.388][t][ffmpeg] Connection: close
[   0.388][t][ffmpeg] Host: dash.akamaized.net
[   0.388][t][ffmpeg] Icy-MetaData: 1
[   0.388][t][ffmpeg] 
[   0.388][t][ffmpeg] 
[   0.442][t][ffmpeg] https: header='HTTP/1.1 200 OK'
[   0.442][t][ffmpeg] https: http_code=200
[   0.442][t][ffmpeg] https: header='ETag: "b97e4f97517eb328009ff70eab6312c2:1534859164"'
[   0.442][t][ffmpeg] https: header='Last-Modified: Tue, 21 Aug 2018 13:46:04 GMT'
[   0.442][t][ffmpeg] https: header='Server: AkamaiNetStorage'
[   0.442][t][ffmpeg] https: header='Cache-Control: max-age=23001486'
[   0.442][t][ffmpeg] https: header='Date: Thu, 27 Jan 2022 06:52:09 GMT'
[   0.442][t][ffmpeg] https: header='Alt-Svc: h3-Q050=":443"; ma=93600,quic=":443"; ma=93600; v="46,43"'
[   0.442][t][ffmpeg] https: header='Content-Length: 4425'
[   0.442][t][ffmpeg] https: header='Connection: close'
[   0.442][t][ffmpeg] https: header='Akamai-Mon-Iucid-Del: 941106'
[   0.442][t][ffmpeg] https: header='Content-Type: application/dash+xml'
[   0.442][t][ffmpeg] https: header='Timing-Allow-Origin: *'
[   0.443][t][ffmpeg] https: header='Access-Control-Max-Age: 86400'
[   0.443][t][ffmpeg] https: header='Access-Control-Allow-Credentials: true'
[   0.443][t][ffmpeg] https: header='Access-Control-Expose-Headers: Server,range,Date,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC,Content-Length,Content-Range,Geo-Info,Quic-Version'
[   0.443][t][ffmpeg] https: header='Access-Control-Allow-Headers: origin,range,hdntl,hdnts,accept-encoding,referer,CMCD-Request,CMCD-Object,CMCD-Status,CMCD-Session'
[   0.443][t][ffmpeg] https: header='Access-Control-Allow-Methods: GET,POST,OPTIONS'
[   0.443][t][ffmpeg] https: header='Access-Control-Allow-Origin: *'
[   0.443][t][ffmpeg] https: header=''
[   0.443][d][ffmpeg] resize stream to 131072 bytes, drop 0 bytes
[   0.443][v][ffmpeg] Mime-type: 'application/dash+xml'
[   0.443][d][ffmpeg] Stream opened successfully.
[   0.443][v][demux] Trying demuxers for level=normal.
[   0.443][d][demux] Trying demuxer: disc (force-level: normal)
[   0.443][t][ffmpeg] seek request from 0 to 0
[   0.443][d][demux] Trying demuxer: edl (force-level: normal)
[   0.443][t][ffmpeg] seek request from 0 to 0
[   0.443][d][demux] Trying demuxer: cue (force-level: normal)
[   0.443][t][ffmpeg] seek request from 0 to 0
[   0.443][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.443][t][ffmpeg] seek request from 0 to 0
[   0.443][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.443][t][ffmpeg] seek request from 0 to 0
[   0.443][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.443][t][ffmpeg] seek request from 0 to 0
[   0.443][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.443][t][ffmpeg] seek request from 3 to 0
[   0.455][t][ffmpeg] Probing dash score:100 size:2048
[   0.456][v][lavf] Found 'dash' at score=100 size=2048.
[   0.458][t][lavf] Skipping nested option: 'user_agent'
[   0.458][t][lavf] Skipping nested option: 'tls_verify'
[   0.458][t][lavf] Skipping nested option: 'icy'
[   0.458][t][lavf] Skipping nested option: 'timeout'
[   0.458][t][ffmpeg/demuxer] dash: Opening 'https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd' for reading
[   0.458][t][ffmpeg] https: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[   0.464][t][ffmpeg] tcp: Original list of addresses:
[   0.464][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   0.464][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   0.464][t][ffmpeg] tcp: Interleaved list of addresses:
[   0.464][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   0.464][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   0.464][d][ffmpeg] tcp: Starting connection attempt to 23.215.177.211 port 443
[   0.477][d][ffmpeg] tcp: Successfully connected to 23.215.177.211 port 443
[   0.698][t][ffmpeg] https: request: GET /dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd HTTP/1.1
[   0.698][t][ffmpeg] User-Agent: libmpv
[   0.698][t][ffmpeg] Accept: */*
[   0.698][t][ffmpeg] Range: bytes=0-
[   0.698][t][ffmpeg] Connection: close
[   0.698][t][ffmpeg] Host: dash.akamaized.net
[   0.698][t][ffmpeg] Icy-MetaData: 1
[   0.698][t][ffmpeg] 
[   0.698][t][ffmpeg] 
[   0.888][t][ffmpeg] https: header='HTTP/1.1 200 OK'
[   0.888][t][ffmpeg] https: http_code=200
[   0.888][t][ffmpeg] https: header='ETag: "b97e4f97517eb328009ff70eab6312c2:1534859164"'
[   0.888][t][ffmpeg] https: header='Last-Modified: Tue, 21 Aug 2018 13:46:04 GMT'
[   0.888][t][ffmpeg] https: header='Server: AkamaiNetStorage'
[   0.888][t][ffmpeg] https: header='Cache-Control: max-age=23001486'
[   0.888][t][ffmpeg] https: header='Date: Thu, 27 Jan 2022 06:52:09 GMT'
[   0.888][t][ffmpeg] https: header='Alt-Svc: h3-Q050=":443"; ma=93600,quic=":443"; ma=93600; v="46,43"'
[   0.888][t][ffmpeg] https: header='Content-Length: 4425'
[   0.888][t][ffmpeg] https: header='Connection: close'
[   0.888][t][ffmpeg] https: header='Akamai-Mon-Iucid-Del: 941106'
[   0.888][t][ffmpeg] https: header='Content-Type: application/dash+xml'
[   0.888][t][ffmpeg] https: header='Timing-Allow-Origin: *'
[   0.888][t][ffmpeg] https: header='Access-Control-Max-Age: 86400'
[   0.888][t][ffmpeg] https: header='Access-Control-Allow-Credentials: true'
[   0.888][t][ffmpeg] https: header='Access-Control-Expose-Headers: Server,range,Date,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC,Content-Length,Content-Range,Geo-Info,Quic-Version'
[   0.888][t][ffmpeg] https: header='Access-Control-Allow-Headers: origin,range,hdntl,hdnts,accept-encoding,referer,CMCD-Request,CMCD-Object,CMCD-Status,CMCD-Session'
[   0.888][t][ffmpeg] https: header='Access-Control-Allow-Methods: GET,POST,OPTIONS'
[   0.888][t][ffmpeg] https: header='Access-Control-Allow-Origin: *'
[   0.889][t][ffmpeg] https: header=''
[   0.889][t][ffmpeg/demuxer] dash: c->min_buffer_time = [1]
[   0.889][t][ffmpeg/demuxer] dash: c->media_presentation_duration = [594]
[   0.890][d][ffmpeg/demuxer] dash: DASH request for url 'https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/BBB_1080_1M_video_init.mp4', offset 0
[   0.890][t][ffmpeg] https: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[   0.936][t][ffmpeg] tcp: Original list of addresses:
[   0.936][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   0.936][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   0.936][t][ffmpeg] tcp: Interleaved list of addresses:
[   0.936][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   0.936][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   0.936][d][ffmpeg] tcp: Starting connection attempt to 23.215.177.211 port 443
[   0.939][d][ffmpeg] tcp: Successfully connected to 23.215.177.211 port 443
[   1.541][t][ffmpeg] https: request: GET /dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/BBB_1080_1M_video_init.mp4 HTTP/1.1
[   1.542][t][ffmpeg] User-Agent: libmpv
[   1.542][t][ffmpeg] Accept: */*
[   1.542][t][ffmpeg] Range: bytes=0-
[   1.542][t][ffmpeg] Connection: close
[   1.542][t][ffmpeg] Host: dash.akamaized.net
[   1.542][t][ffmpeg] Icy-MetaData: 1
[   1.542][t][ffmpeg] 
[   1.542][t][ffmpeg] 
[   3.713][t][ffmpeg] https: header='HTTP/1.1 404 Not Found'
[   3.713][t][ffmpeg] https: http_code=404
[   3.713][w][ffmpeg] https: HTTP error 404 Not Found
[   3.715][w][ffmpeg/demuxer] dash: Failed to open fragment of playlist
[   3.717][e][ffmpeg/demuxer] dash: Error when loading first fragment of playlist
[   3.717][d][ffmpeg] AVIOContext: Statistics: 4425 bytes read, 0 seeks
[   3.719][e][lavf] avformat_open_input() failed
[   3.719][w][lavf] Leaking 1 nested connections (FFmpeg bug).
[   3.719][d][demux] Trying demuxer: mf (force-level: normal)
[   3.719][t][ffmpeg] seek request from 0 to 0
[   3.720][d][demux] Trying demuxer: playlist (force-level: normal)
[   3.720][t][ffmpeg] seek request from 0 to 0
[   3.722][d][demux] Trying demuxer: null (force-level: normal)
[   3.722][t][ffmpeg] seek request from 0 to 0
[   3.722][v][demux] Trying demuxers for level=unsafe.
[   3.722][d][demux] Trying demuxer: disc (force-level: unsafe)
[   3.722][t][ffmpeg] seek request from 0 to 0
[   3.722][d][demux] Trying demuxer: edl (force-level: unsafe)
[   3.722][t][ffmpeg] seek request from 0 to 0
[   3.722][d][demux] Trying demuxer: cue (force-level: unsafe)
[   3.722][t][ffmpeg] seek request from 0 to 0
[   3.722][d][demux] Trying demuxer: rawaudio (force-level: unsafe)
[   3.722][t][ffmpeg] seek request from 0 to 0
[   3.722][d][demux] Trying demuxer: rawvideo (force-level: unsafe)
[   3.722][t][ffmpeg] seek request from 0 to 0
[   3.722][d][demux] Trying demuxer: mkv (force-level: unsafe)
[   3.722][t][ffmpeg] seek request from 0 to 0
[   3.722][d][demux] Trying demuxer: lavf (force-level: unsafe)
[   3.722][t][ffmpeg] seek request from 3 to 0
[   3.732][t][ffmpeg] Probing dash score:100 size:2048
[   3.733][v][lavf] Found 'dash' at score=100 size=2048.
[   3.733][t][lavf] Skipping nested option: 'user_agent'
[   3.733][t][lavf] Skipping nested option: 'tls_verify'
[   3.733][t][lavf] Skipping nested option: 'icy'
[   3.733][t][lavf] Skipping nested option: 'timeout'
[   3.733][t][ffmpeg/demuxer] dash: Opening 'https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd' for reading
[   3.733][t][ffmpeg] https: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[   3.748][t][ffmpeg] tcp: Original list of addresses:
[   3.748][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   3.748][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   3.748][t][ffmpeg] tcp: Interleaved list of addresses:
[   3.748][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   3.748][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   3.748][d][ffmpeg] tcp: Starting connection attempt to 23.215.177.211 port 443
[   3.783][d][ffmpeg] tcp: Successfully connected to 23.215.177.211 port 443
[   4.044][t][ffmpeg] https: request: GET /dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd HTTP/1.1
[   4.044][t][ffmpeg] User-Agent: libmpv
[   4.044][t][ffmpeg] Accept: */*
[   4.044][t][ffmpeg] Range: bytes=0-
[   4.044][t][ffmpeg] Connection: close
[   4.044][t][ffmpeg] Host: dash.akamaized.net
[   4.044][t][ffmpeg] Icy-MetaData: 1
[   4.044][t][ffmpeg] 
[   4.044][t][ffmpeg] 
[   4.101][t][ffmpeg] https: header='HTTP/1.1 200 OK'
[   4.101][t][ffmpeg] https: http_code=200
[   4.101][t][ffmpeg] https: header='ETag: "b97e4f97517eb328009ff70eab6312c2:1534859164"'
[   4.101][t][ffmpeg] https: header='Last-Modified: Tue, 21 Aug 2018 13:46:04 GMT'
[   4.101][t][ffmpeg] https: header='Server: AkamaiNetStorage'
[   4.101][t][ffmpeg] https: header='Cache-Control: max-age=23001483'
[   4.101][t][ffmpeg] https: header='Date: Thu, 27 Jan 2022 06:52:12 GMT'
[   4.101][t][ffmpeg] https: header='Alt-Svc: h3-Q050=":443"; ma=93600,quic=":443"; ma=93600; v="46,43"'
[   4.101][t][ffmpeg] https: header='Content-Length: 4425'
[   4.101][t][ffmpeg] https: header='Connection: close'
[   4.101][t][ffmpeg] https: header='Akamai-Mon-Iucid-Del: 941106'
[   4.101][t][ffmpeg] https: header='Content-Type: application/dash+xml'
[   4.101][t][ffmpeg] https: header='Timing-Allow-Origin: *'
[   4.101][t][ffmpeg] https: header='Access-Control-Max-Age: 86400'
[   4.101][t][ffmpeg] https: header='Access-Control-Allow-Credentials: true'
[   4.101][t][ffmpeg] https: header='Access-Control-Expose-Headers: Server,range,Date,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC,Content-Length,Content-Range,Geo-Info,Quic-Version'
[   4.101][t][ffmpeg] https: header='Access-Control-Allow-Headers: origin,range,hdntl,hdnts,accept-encoding,referer,CMCD-Request,CMCD-Object,CMCD-Status,CMCD-Session'
[   4.101][t][ffmpeg] https: header='Access-Control-Allow-Methods: GET,POST,OPTIONS'
[   4.101][t][ffmpeg] https: header='Access-Control-Allow-Origin: *'
[   4.101][t][ffmpeg] https: header=''
[   4.101][t][ffmpeg/demuxer] dash: c->min_buffer_time = [1]
[   4.102][t][ffmpeg/demuxer] dash: c->media_presentation_duration = [594]
[   4.102][d][ffmpeg/demuxer] dash: DASH request for url 'https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/BBB_1080_1M_video_init.mp4', offset 0
[   4.102][t][ffmpeg] https: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[   4.128][t][ffmpeg] tcp: Original list of addresses:
[   4.128][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   4.128][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   4.128][t][ffmpeg] tcp: Interleaved list of addresses:
[   4.128][t][ffmpeg] tcp: Address 23.215.177.211 port 443
[   4.128][t][ffmpeg] tcp: Address 23.215.177.200 port 443
[   4.128][d][ffmpeg] tcp: Starting connection attempt to 23.215.177.211 port 443
[   4.140][d][ffmpeg] tcp: Successfully connected to 23.215.177.211 port 443
[   4.397][t][ffmpeg] https: request: GET /dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/BBB_1080_1M_video_init.mp4 HTTP/1.1
[   4.397][t][ffmpeg] User-Agent: libmpv
[   4.397][t][ffmpeg] Accept: */*
[   4.397][t][ffmpeg] Range: bytes=0-
[   4.397][t][ffmpeg] Connection: close
[   4.397][t][ffmpeg] Host: dash.akamaized.net
[   4.397][t][ffmpeg] Icy-MetaData: 1
[   4.397][t][ffmpeg] 
[   4.397][t][ffmpeg] 
[   6.170][t][ffmpeg] https: header='HTTP/1.1 404 Not Found'
[   6.170][t][ffmpeg] https: http_code=404
[   6.170][w][ffmpeg] https: HTTP error 404 Not Found
[   6.173][w][ffmpeg/demuxer] dash: Failed to open fragment of playlist
[   6.173][e][ffmpeg/demuxer] dash: Error when loading first fragment of playlist
[   6.173][d][ffmpeg] AVIOContext: Statistics: 4425 bytes read, 0 seeks
[   6.176][e][lavf] avformat_open_input() failed
[   6.176][w][lavf] Leaking 1 nested connections (FFmpeg bug).
[   6.176][d][demux] Trying demuxer: mf (force-level: unsafe)
[   6.176][t][ffmpeg] seek request from 0 to 0
[   6.176][d][demux] Trying demuxer: playlist (force-level: unsafe)
[   6.176][t][ffmpeg] seek request from 0 to 0
[   6.177][d][demux] Trying demuxer: null (force-level: unsafe)
[   6.177][t][ffmpeg] seek request from 0 to 0
[   6.177][d][ffmpeg] AVIOContext: Statistics: 4425 bytes read, 0 seeks
[   6.179][v][cplayer] Opening failed or was aborted: https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd
[   6.180][v][cplayer] finished playback, unrecognized file format (reason 4)
[   6.180][e][cplayer] Failed to recognize file format.
[   6.180][i][cplayer] 
[   6.180][i][cplayer] Exiting... (Errors when loading file)
---

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior

I compared GStreamer and other players that can play those stream,the correct request address should be:
https://dash.akamaized.net/dash264/TestCasesHD/1a/qualcomm/1/BBB_1080_1M_video_init.mp4,
But mpv is  https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/BBB_1080_1M_video_init.mp4

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files
https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd
mpd file(note that its baseurl is a relative address:../../1a/qualcomm/1/):
----
<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H9M54.00S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
 </ProgramInformation>
 <BaseURL>../../1a/qualcomm/1/</BaseURL>
 <Period id="1" duration="PT0H4M57.00S">
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="24" par="16:9" subsegmentStartsWithSAP="1">
   <Representation id="1" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="1630280">
    <BaseURL>BBB_1080_1M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487"  presentationTimeOffset="0"/>
   </Representation>
   <Representation id="2" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="2607826">
    <BaseURL>BBB_1080_2M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487"  presentationTimeOffset="0"/>
   </Representation>
   <Representation id="3" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="4229100">
    <BaseURL>BBB_1080_4M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487"  presentationTimeOffset="0"/>
   </Representation>
   <Representation id="4" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="7941284">
    <BaseURL>BBB_1080_8M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487"  presentationTimeOffset="0"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="5" mimeType="audio/mp4" codecs="mp4a.40.29" audioSamplingRate="48000" startWithSAP="1" bandwidth="33206">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>BBB_HD_32k_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="820-4487"  presentationTimeOffset="0"/>
   </Representation>
  </AdaptationSet>
 </Period>
  <Period id="2" duration="PT0H4M57.00S">
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="24" par="16:9" subsegmentStartsWithSAP="1">
   <Representation id="1" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="1630280">
    <BaseURL>BBB_1080_1M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487"  presentationTimeOffset="297"/>
   </Representation>
   <Representation id="2" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="2607826">
    <BaseURL>BBB_1080_2M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487" presentationTimeOffset="297"/>
   </Representation>
   <Representation id="3" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="4229100">
    <BaseURL>BBB_1080_4M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487" presentationTimeOffset="297"/>
   </Representation>
   <Representation id="4" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="7941284">
    <BaseURL>BBB_1080_8M_video_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="892-4487" presentationTimeOffset="297"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="5" mimeType="audio/mp4" codecs="mp4a.40.29" audioSamplingRate="48000" startWithSAP="1" bandwidth="33206">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>BBB_HD_32k_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="820-4487"  presentationTimeOffset="297"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

----

**Comment by rolandjon** [comment]
I think this should be a problem with ffmpeg upstream, so I have created a similar ticket here(https://trac.ffmpeg.org/ticket/9615#ticket)

**Comment by sfan5** [comment]
This is indeed not mpv's business.

**Comment by g2p** [comment]
The trac is offline, and I don't know if this is tracked anywhere, but this is still an issue.

Illustrated with local Steam recordings, this works:

    mpv ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/*/gamerecordings/clips/clip_*_*_*/video/fg_*_*_*/session.mpd

So does this:

    cd ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/*/gamerecordings/clips/clip_*_*_*/video/fg_*_*_*
    mpv session.mpd

But this doesn't:

    cd
    mpv .var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/*/gamerecordings/clips/clip_*_*_*/video/fg_*_*_*/session.mpd

As it looks for segments under the home directory rather than in the session.mpd directory.
ffplay has the same issue, whereas VLC works fine.  In gstreamer land, there is an [mpd-baseurl](https://gstreamer.freedesktop.org/documentation/dash/dashsink.html?gi-language=c#dashsink:mpd-baseurl) property on dashsink elements, I don't know if something like this is lacking in the ffmpeg API.
