### ISSUE TITLE
TOOLS/lua/autoload.lua: add 'm2ts' to EXTENSIONS_VIDEO

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9779]
I tried to do a pull request but apparently, I need to follow a readme file, and if I mess it up it's impossible to edit the pull request or squash them together since I have no idea how to do it, I tried to google it and it's overcomplicated, I use GitHub.com (website).
(If someone can send me a guide for newbies I will thank you)
So I'm gonna keep it simple.

https://github.com/mpv-player/mpv/blob/8087e3371f8ffbdc8ddcbc0445392b0480ef02a4/TOOLS/lua/autoload.lua#L52

Add 
```
, 'm2ts'
```

**Comment by Natural-Harmonia-Gropius** [comment]
```
git rebase -i HEAD~<number of commit>
git push origin <branch name> --force
```

**Comment by Obegg** [comment]
> ```
> git rebase -i HEAD~<number of commit>
> git push origin <branch name> --force
> ```

What are those? Where do I type them? What about editing a commit on a pull request?

**Comment by Natural-Harmonia-Gropius** [comment]
> What are those?

command

> Where do I type them?

terminal

> What about editing a commit on a pull request?

git rebase will show a guide

**Comment by Obegg** [comment]
Yeah, so I googled it, and apparently, I need to download something called "Git", and... I have no idea what now...
How do I get to my pull request? How can I change my commits?
Send me a guide, step by step.

**Comment by Obegg** [comment]
Anyway... too complicated for me, I'll just keep this issue open till someone will add this

**Comment by Hrxn** [comment]
Yeah, this doesn't work like that. What you can do on the website itself is *very* limited. You can make changes to any file (implicitly forking it), and then create a PR, but even simple rebasing is too much.

But there are many git clients, many graphical ones, and there even is an official GUI git client:
https://desktop.github.com/

**Comment by Obegg** [comment]
> Yeah, this doesn't work like that. What you can do on the website itself is _very_ limited. You can make changes to any file (implicitly forking it), and then create a PR, but even simple rebasing is too much.
> 
> But there are many git clients, many graphical ones, and there even is an official GUI git client: https://desktop.github.com/

I did try GitHub Desktop and even that doesn't have "squash" or "edit commit"... 
All these complications for a single line, lol, what a joke...
I'll just keep this issue open till someone that knows what he's doing will add it...
