### ISSUE TITLE
[vo=gpu-next] --tone-mapping-mode=hybrid near black behaviour

### ISSUE THREAD

**Issue by NSQY** [mpv-player/mpv#9781]
- mpv https://github.com/mpv-player/mpv/commit/8087e3371f8ffbdc8ddcbc0445392b0480ef02a4
- libplacebo https://github.com/haasn/libplacebo/commit/1062725fea934a5883fbfcaa62e3c38bd7a12c86
- Arch linux
- Nvidia proprietary 510.39.01
```
mpv 0.34.0-158-g8087e3371f Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Thu Jan 27 23:15:00 ACDT 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```

### Reproduction steps
Tonemap HDR file to SDR/709
`mpv foo --vo=gpu-next --tone-mapping=bt.2390 --tone-mapping-mode=hybrid --gamut-mapping-mode=clip`

### Expected behavior
Similar shadow/black levels to --tone-mapping-mode rgb

### Actual behavior
Elevated near or at black levels with perceptually strong chrominance

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/7950882/mpv.log)

### Sample files
Please see https://slow.pics/c/U01RjDNo

From LG 'Colors' demo
https://0x0.st/ooOY.mkv
https://0x0.st/oHop.mkv

**Comment by Natural-Harmonia-Gropius** [comment]
especially the red
![image](https://user-images.githubusercontent.com/50797982/151375094-efa3dace-2250-4d13-b8e8-35cbd798831e.png)
![image](https://user-images.githubusercontent.com/50797982/151375513-91624e20-f50c-429f-b81b-9743c2b807b2.png)

**Comment by haasn** [comment]
> especially the red ![image](https://user-images.githubusercontent.com/50797982/151375094-efa3dace-2250-4d13-b8e8-35cbd798831e.png) ![image](https://user-images.githubusercontent.com/50797982/151375513-91624e20-f50c-429f-b81b-9743c2b807b2.png)

What file is this screenshot from?

**Comment by Natural-Harmonia-Gropius** [comment]
> What file is this screenshot from?

https://b23.tv/QDN3u6T, but need some trick  to unlock dolby vision. Also available in https://youtu.be/TZR1P4ClZLY but hlg only.

I will upload it later.

**Comment by haasn** [comment]
For testing, 1-frame clips are very helpful:

```ffmpeg -ss MM:SS -i FILE -vframes 1 -c copy -an clip.mkv```

**Comment by haasn** [comment]
See https://code.videolan.org/videolan/libplacebo/-/merge_requests/226

**Comment by Natural-Harmonia-Gropius** [comment]
[o.zip](https://github.com/mpv-player/mpv/files/7960227/o.zip)

**Comment by Natural-Harmonia-Gropius** [comment]
https://user-images.githubusercontent.com/50797982/151584713-2a208636-5e60-414e-811c-efe27008d1b6.mp4

**Comment by quietvoid** [comment]
The saturation issue in that video is caused by the tone mapping increasing saturation in SDR parts of the image. Or pixels with luma that doesn't exceed the target peak.

It's not really clear what saturation is correct because there doesn't seem to be a useful reference to compare against.
For what it's worth, madVR maps in RGB for pixels with original luma that already fits within the target peak.

**Comment by Natural-Harmonia-Gropius** [comment]
maybe bug in `sh_luma_coeffs(sh, pl_raw_primaries_get(src->primaries)))`, only rgb mode not over-saturated.
`float L = dot(p.rgb, vec3(0.2627, 0.6780, 0.0593))` with my shaders works fine.
![image](https://user-images.githubusercontent.com/50797982/151586632-7ee6a372-6b0c-4632-b5b4-65b376118408.png)

**Comment by NSQY** [comment]
> See https://code.videolan.org/videolan/libplacebo/-/merge_requests/226

Looking much better https://slow.pics/c/szP2v2S5
