### ISSUE TITLE
"target-lut" doesn't work in profiles

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9782]
### Important Information

mpv-x86_64-20220116-git-1ba0547.7z
Windows 10

### Reproduction steps
Configure a cube 3d lut with target_lut= in a profile. It will not be applied. It is only applied in the global section of mpv-conf.

### Expected behavior
target-lut should be changed with profile activation.

### Actual behavior
target-lut is not changed with profile activation.

### Sample files
Config: [test_lut.zip](https://github.com/mpv-player/mpv/files/7956287/test_lut.zip)
3D LUT: [BT.2020 BT.709 (Gamma 2.2).zip](https://github.com/mpv-player/mpv/files/7956256/BT.2020.BT.709.Gamma.2.2.zip)

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/7956280/log.txt)

**Comment by FoLLgoTT** [comment]
Added more information and sample files.

**Comment by ValZapod** [comment]
> It is only applied in the global section of mpv-conf.

This is just cosmetic issue, right?

**Comment by FoLLgoTT** [comment]
> This is just cosmetic issue, right?

Not really. If you want to use two LUTs (e.g. for BT.709 and BT.2020) then you cannot use it in profiles. Without profiles I always have to use a LUT for the largest color space (e.g. BT.2020) and waste precision (?) for smaller color spaces (e.g. BT.709).

**Comment by Dudemanguy** [comment]
This was fixed by 85e84f6d9202c8f24def535a6aa78994c0223298.

**Comment by mrfragger** [comment]
> This was fixed by [85e84f6](https://github.com/mpv-player/mpv/commit/85e84f6d9202c8f24def535a6aa78994c0223298).

I have 500+ LUTs that I flip through and just tried latest build but still must use workaround.  I can say that if you apply a LUT to a image or a paused video you must do cycle video; cycle video ...that I was doing but annoying for online videos as it rebuffers video and interrupts it.  But since yesterday just use frame-back-step;frame-step and it works just great..sometimes if video is playing it'll pause it but no big deal as you can flip through your LUTs quickly with images, paused videos or playing videos.  

I should mention obviously need in mpv.config 
`vo=gpu-next `

but still I'd say most of the 500 Luts wouldn't work.  The key is putting 
`image-lut-type=normalized `

and all 500+ LUTs work.

example config

```
input.conf
`Ctrl+Meta+1 frame-back-step;frame-step;script-message cycle-profiles  'abigailgonzalez blade runner'  'abigailgonzalez blue house'  'abigailgonzalez blue ice'  'abigailgonzalez caribe'  'abigailgonzalez cinema 02'  'abigailgonzalez cinema 03'  'abigailgonzalez cinema 04'  'abigailgonzalez cinema 05'  'abigailgonzalez cinema noir'  'abigailgonzalez cinema'  'abigailgonzalez cinematic for flog'  'abigailgonzalez day 4nite'  'abigailgonzalez eterna for flog'  'abigailgonzalez filmic'  'abigailgonzalez fuji hdr'  'abigailgonzalez goldengate'  'abigailgonzalez matrix'  'abigailgonzalez monochrome 01'  'abigailgonzalez monochrome 02'  'abigailgonzalez monochrome 02'  'abigailgonzalez science fiction' 'LUT none' #! [Video/Image] > [LUTs 1] > Abigail Gonzalez`
```

mpv.conf
```
[LUT none]
image-lut=''
#LUT Lookup Tables video/images GMIC

[abigailgonzalez blade runner]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez blade runner.cube' 
[abigailgonzalez blue house]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez blue house.cube' 
[abigailgonzalez blue ice]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez blue ice.cube' 
[abigailgonzalez caribe]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez caribe.cube' 
[abigailgonzalez cinema 02]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez cinema 02.cube' 
[abigailgonzalez cinema 03]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez cinema 03.cube' 
[abigailgonzalez cinema 04]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez cinema 04.cube' 
[abigailgonzalez cinema 05]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez cinema 05.cube' 
[abigailgonzalez cinema noir]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez cinema noir.cube' 
[abigailgonzalez cinema]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez cinema.cube' 
[abigailgonzalez cinematic for flog]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez cinematic for flog.cube' 
[abigailgonzalez day 4nite]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez day 4nite.cube' 
[abigailgonzalez eterna for flog]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez eterna for flog.cube' 
[abigailgonzalez filmic]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez filmic.cube' 
[abigailgonzalez fuji hdr]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez fuji hdr.cube' 
[abigailgonzalez goldengate]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez goldengate.cube' 
[abigailgonzalez matrix]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez matrix.cube' 
[abigailgonzalez monochrome 01]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez monochrome 01.cube' 
[abigailgonzalez monochrome 02]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez monochrome 02.cube' 
[abigailgonzalez monochrome 02]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez old west.cube' 
[abigailgonzalez science fiction]
image-lut='~/.config/mpv/lut/abigailgonzalez/abigailgonzalez science fiction.cube'
```

**Comment by Dudemanguy** [comment]
`image-lut` isn't `target-lut`

**Comment by mrfragger** [comment]
> `image-lut` isn't `target-lut`

changed all to target-lut and no longer need frame-step stuff nor image-lut-type=normalized obviously.  Man I feel like a fool...thanks for pointing that out Dudemanguy.  0.39 works just fine
