### ISSUE TITLE
[sub-file-paths] all folders?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9783]
I want mpv to get all subs from all folders, is it possible?

**Comment by dyphire** [comment]
You can use this lua: [fuzzydir.lua](https://github.com/dyphire/mpv-config/blob/master/scripts/fuzzydir.lua)
And edit your mpv.conf:
```
audio-file-paths=audio;audios;**
sub-file-paths=sub;subs;subtitles;**
```
Also can modify `fuzzydir.conf` to your liking
