### ISSUE TITLE
gpu-next: screenshots don't work with shader in POSTKERNEL/SCALED

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9786]
### Important Information

mpv-x86_64-20220116-git-1ba0547.7z
Windows 10

### Reproduction steps

mpv "movie.mkv" --no-config --vo=gpu-next --gpu-api=vulkan --glsl-shaders=test.glsl

Note: it works when the hook is POSTKERNEL for example.

### Expected behavior
Screenshot contains the picture after shaders.

### Actual behavior
Screenshot is black:

![mpv-shot0001](https://user-images.githubusercontent.com/95616074/151497579-7e3f24b9-8347-41ab-9ee9-d917657d02d7.jpg)

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/7956242/log.txt)

### Sample files

Simple shader that does nothing:

`//!DESC Cropping
//!HOOK SCALED   
//!BIND HOOKED
//!WIDTH OUTPUT.w
//!HEIGHT OUTPUT.h

vec4 hook() 
{
	return vec4(HOOKED_tex(HOOKED_pos).rgb, 0.0);
}`

**Comment by Natural-Harmonia-Gropius** [comment]
no, it set alpha to 0.
how about change 0.0 to 1.0?

**Comment by FoLLgoTT** [comment]
Thank you! That works.

I just understand why this was never a problem with "gpu". I close this issue.
