### ISSUE TITLE
gpu-next: tone mapping produces darker image

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9787]
### Important Information

mpv-x86_64-20220116-git-1ba0547.7z
Windows 10

### Reproduction steps
It seems that "gpu-next" don't use the full 8 bit for output with default tone mapping. The image is overall darker than with "gpu".

Please compare the image with these parameters:

mpv "hdr_movie.mkv" --no-config --vo=gpu-next --gpu-api=vulkan
mpv "hdr_movie.mkv" --no-config --vo=gpu --gpu-api=d3d11

gpu:
![gpu](https://user-images.githubusercontent.com/95616074/151499708-0fd12e74-6c71-41da-820c-6b59c616df1e.jpg)

gpu-next:
![gpu-next](https://user-images.githubusercontent.com/95616074/151499720-c12bef98-5daf-4356-919b-8f26ec90c07b.jpg)

### Expected behavior
Same brightness as "gpu".

### Actual behavior
It is darker.

### Log file
[log_gpu.txt](https://github.com/mpv-player/mpv/files/7956338/log_d3d11.txt)
[log_gpu-next.txt](https://github.com/mpv-player/mpv/files/7956339/log_gpu-next.txt)

**Comment by NSQY** [comment]
This is probably due to `--gamut-mapping-mode=darken`.

Have you tried `--gamut-mapping-mode=clip` ?

**Comment by FoLLgoTT** [comment]
You are right, thanks! 

Maybe "darken" can be tweaked a bit to give more contrast and use more of the 8 bit output range? Otherwise we waste contrast. Even if I reduce target nits values near white (-> 255) don't occur in the image. It seems that there is some kind of border (around RGB 200) which is not exceeded. "clip" and madVR go closer to full white in those scenes.

**Comment by FoLLgoTT** [comment]
Another observation: when using "target-lut" the "gamut-mapping-mode" seems to have no affect. It is always as bright as "clip".

**Comment by FoLLgoTT** [comment]
Another bug: d3d11va-copy produces a darker image with gpu-next and HDR content even if target-trc=gamma2.2 is specified.

Shall I open a new issue for that?

**Comment by haasn** [comment]
> Another bug: d3d11va-copy produces a darker image with gpu-next and HDR content even if target-trc=gamma2.2 is specified.
> 
> Shall I open a new issue for that?

Probably a good idea. Sounds like some metadata isn't being properly forwarded by that decoder path.

**Comment by haasn** [comment]
> Another observation: when using "target-lut" the "gamut-mapping-mode" seems to have no effect. It is always as bright as "clip".

Known issue. I'm planning on rewriting the majority of the color management code in libplacebo sometime in the future to address many of these issues (this also affects LUTs generated by ICC profiles).

**Comment by haasn** [comment]
ICC / gamut mapping / etc. have been rewritten since then, and also `darken` is no longer the default. The original issue should be resolved as a result.
