### ISSUE TITLE
--tone-mapping-param behaviour with BT.2390 is not documented

### ISSUE THREAD

**Issue by NSQY** [mpv-player/mpv#9788]
https://slow.pics/c/GYyOCVUH
It does _something_, but there is no explanation at https://mpv.io/manual/master/#options-tone-mapping-param

Setting --tone-mapping-param=2.0 can reduce perceived clipping when using BT.2390.

**Comment by pillepalle1234** [comment]
Can confirm, great find!

clip
https://ibb.co/x3cm76P

clip + tone-mapping-param=2.0
https://ibb.co/Pt6h5fg

**Comment by haasn** [comment]
Yeah, sorry, the mpv man page is still written for `--vo=gpu`, not `--vo=gpu-next`. You can find the full documentation of the `gpu-next` tone mapping curves [here](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/include/libplacebo/tone_mapping.h#L119).

Should be fixed though.

**Comment by ValZapod** [comment]
>Note that this defaults to 1.0, rather than the value of 0.5 from the ITU-R spec.

**Comment by pillepalle1234** [comment]
A simple question: When choosing Tone-mapping=auto does that mean that each scene could be using another algorithm or is it chosen per movie?

**Comment by haasn** [comment]
> A simple question: When choosing Tone-mapping=auto does that mean that each scene could be using another algorithm or is it chosen per file/movie?

It is chosen based on static metadata (HDR10). Since that's usually the same for the entire stream, it would be constant per file. The only exception would be if you somehow have a file that has different HDR10 metadata per frame, but I've never seen such a file.

**Comment by ValZapod** [comment]
> metadata per frame, but I've never seen such a file.

Per scene. Here is such a file as per segment of Blu-ray. https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/uploads/16c628c535865d7282a48317064345a2/out.mp4

> . (And it wouldn't make much sense either)

It makes perfect sense, moroever that is what apple does hwne they send hdr10 stream from dolby vision profile 5 source.

**Comment by pillepalle1234** [comment]
> > Note that this defaults to 1.0, rather than the value of 0.5 from the ITU-R spec.

After experimenting i think it should default to 2.0 since even 1.0 leads to highlights bleeding out as we see in the screenshots above.

**Comment by ValZapod** [comment]
> apple does when they send hdr10 stream from dolby vision profile 5 source.

Oh, I somehow forgot to mention that their PER FRAME derivation of static metadata from dolby vision introduced in v4 DV 3 part dynamic curve is not necessarily a good thing, on avsforum people were talking about how it causes some strange brightness jumps even on 0 frame latency lg c9 and later.

**Comment by haasn** [comment]
> Per scene. Here is such a file as per segment of Blu-ray. https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/uploads/16c628c535865d7282a48317064345a2/out.mp4

That file has the same metadata on every frame.

**Comment by Hrxn** [comment]
Quelle surprise

**Comment by ValZapod** [comment]
> > Per scene. Here is such a file as per segment of Blu-ray. https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/uploads/16c628c535865d7282a48317064345a2/out.mp4
> 
> That file has the same metadata on every frame.

No, it does not. Maybe you **used not ffprobe** to probe:

Change is as follows on frame pkt_pos=7258705:
side_data_type=Content light level metadata
max_content=284
max_average=145
to
side_data_type=Content light level metadata
max_content=378
max_average=277
Use ffprobe -show_frames -select_streams v out.mp4
Also see my issue https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/875
