### ISSUE TITLE
--ao=dsound without --autosync=4 causing video to stutter

### ISSUE THREAD

**Issue by Cyberbeing** [mpv-player/mpv#98]
I've been doing some testing on couple Windows 7 x64 computers (nvidia & ati gpu), and notice that the opengl and direct3d_shaders output drivers stutter frequently with autosync=0, the default value. In both cases using a low value of autosync=4 along with --mc=0 resolved the issue.

Has anybody else noticed this?

Would there be any merit for mpv to enable ---autosync=4 and --mc=0 by default?

**Comment by wm4** [comment]
Does it happen with ``--ao=null``? What does the status line say, does it say something about ``ct:``?

**Comment by wm4** [comment]
Try how large you can make the value passed to ``--mc`` until the stutter happens (values between 0 and 0.1 would make sense).

With ``--mc=0`` you'll eventually get desync. I tried with some mkv, and after about 7 mins, the desync was already 20ms (the player still thinks A-V sync is 0.0 aka ok, because ``--mc`` compensates for the difference between timestamps that builds up for whatever reason).

The change applied without ``--mc`` option is very small (e.g. about 0.000036 per frame in my case), so I'm wondering how the hell it would cause stutter. Try the following patch and paste what it outputs (try with ``null``, ``dsound``, and ``wasapi`` AOs): http://sprunge.us/EAMA (it won't change behavior, just adds debug output)

Also, try the following patch: http://sprunge.us/MANS (it also doesn't change behavior). Play a few seconds of video with ``--dump-stats=out.txt``, and paste the resulting ``out.txt`` file somewhere. Run it once with default options, and once with options that appear to remove the stutter.

**Comment by Cyberbeing** [comment]
As mentioned in https://github.com/mpv-player/mpv/issues/98#issuecomment-18467037 the issue does not occur with ``--ao=null`` . I've not seen ``ct:`` in the status line, but I was unsure of exactly what settings and playback duration what you wanted me to test when looking for it.

After further testing (lachs0r's 2015-01-29 Win32 build), I'm unsure how much ``--mc`` is involved with the stuttering. 

Occasionally I'll see stuttering with ``--ao=dsound`` or ``--ao=wasapi`` depending on the exact moment I begin playback or enter fullscreen, no matter what ``--mc`` value is set. So at least with current builds, I'm now unconvinced if ``--mc=0`` makes any difference, since my results have been inconsistent over multiple runs.

``--ao=dsound`` I'll always see constant stuttering unless I set --autosync=4

``--ao=wasapi`` seems decent using defaults. 

wasapi wasn't implemented when I originally opened this issue, so it's possible that this Issue may only  affect ``--ao=dsound``. I'll need to do more testing, as I've always had ``--ao=dsound`` set in my config file.

I'm also noticing that overriding ``display-fps`` with my refresh rate value causes ``--ao=dsound`` to stutter more, but not ``--ao=wasapi``. Use of wasapi over dsound doesn't resolve the stuttering with smoothmotion though, which once again seems to confirm that the stuttering seen in Issue #1505 is an OpenGL issue.

I'll see if I can try your patches this weekend, assuming I don't have any trouble updating my cross-compile VM to mpv's new waf build system. Last time I built mpv myself was over 6 months ago.

**Comment by lachs0r** [comment]
> I'll see if I can try your patches this weekend, assuming I don't have any
> trouble updating my cross-compile VM to mpv's new waf build system. Last
> time I built mpv myself was over 6 months ago.

You can use this: https://github.com/lachs0r/mingw-w64-cmake

Notice the prebuilt VM image that has all the build dependencies preinstalled.

With that, you can get binaries with the same configuration as those on my 
site. If you want to apply patches, either add a patch step to mpv.cmake
(see the other files for examples) or cd into
<build>/packages/mpv-prefix/src/mpv and do it there after you’ve successfully 
built mpv using the environment (do that if you need many rebuilds as the 
CMake build system updates all dependencies every time). You can just run 
./waf there as usual; mpv.exe will be in the build/ subdirectory. Just take 
care not to reconfigure waf without passing the right flags.

**Comment by Cyberbeing** [comment]
> You can use this: https://github.com/lachs0r/mingw-w64-cmake

Thanks, I'll look into that later. A little bit eariler, I already ended up using rossy's MSYS2 guide from https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2 which seemed to go smoothly for compiling a quick mpv build on Windows.

**Comment by Cyberbeing** [comment]
patch1 console logs:
[dsound (stuttering)] (http://pastebin.com/DDRjvbuQ) | [dsound --autosync=4 (smooth)] (http://pastebin.com/qrXTvnST) | [wasapi (smooth)] (http://pastebin.com/BisSx3aT) | [null (very smooth)] (http://pastebin.com/Phy9P7Av)

**Comment by Cyberbeing** [comment]
patch2 dump-stats logs:
https://www.mediafire.com/?2r64ara13o5d7q8

**Comment by wm4** [comment]
>patch1 console logs:

Looks to me like ``--mc=0`` really shouldn't have any effect. The deviation added by this code is not larger than 1ms in any case.

>patch2 dump-stats logs:

Maybe the coarse playback position reporting of dsound is really a problem, wasapi on the other hand looks pretty much perfect.

Can you try running with: ``--ao=null:outburst=512:broken-delay``. Just to see whether you experience stuttering with it or not. (I don't want any logs.) Maybe increase the outburst parameter a bit.

**Comment by Cyberbeing** [comment]
``--ao=null:outburst=512:broken-delay`` stutters badly

**Comment by wm4** [comment]
So, is ao_null or --no-audio in any way smoother than ao_wasapi? (With no additional options.)

**Comment by Cyberbeing** [comment]
> Occasionally I'll see stuttering with --ao=dsound or --ao=wasapi depending on the exact moment I begin playback or enter fullscreen

Only this, which I've now been able to confirm also occurs occasionally with ``--ao=null`` or ``--no-audio``, suggesting it's a completely unrelated OpenGL renderer problem. I'll open a new issue for that.

The apparent 'broken-delay' delay stuttering (the problem I originally opened this issue for) I believe only affects ``--ao=dsound``, which ``--autosync=4`` functions as a partial-workaround.

**Comment by wm4** [comment]
I don't think we'll ever bother to fix ao_dsound. It's more likely that we'll just remove it.
