### ISSUE TITLE
Srt subtitle with GNU locale naming convention

### ISSUE THREAD

**Issue by doraeric** [mpv-player/mpv#9801]
### Expected behavior of the wanted feature

Mpv can auto load subtitles with filenames containing language code according to [GNU locale names](https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html), such as `video.en_US.srt`

### Alternative behavior of the wanted feature

Currently, mpv would auto load subtitles with names like `video.en.srt`, `video.chi.srt`. However, the original naming convention is hard to tell the difference between Chinese (simplify), Chinese (traditional) and Chinese (Hong Kong), which are all Chinese but used by different people.

I think GNU locale names are much more mature, and some websites also suggest following this rule, like [facebook](https://www.facebook.com/help/1528795707381162).

**Comment by CounterPillow** [comment]
The more sensible solution, in my eyes, would be to stop trying to assign meaning to file names and instead package your subtitles into a container format that allows you to specify metadata like this. I'm pretty sure Matroska can be used as a standalone subtitle container.

**Comment by dyphire** [comment]
https://github.com/mpv-player/mpv/pull/8865. Is this PR what you want？

You can also try this lua: [sub-select.lua](https://github.com/CogentRedTester/mpv-sub-select)
This is my profile for reference: [sub-select.json](https://github.com/dyphire/mpv-config/blob/master/script-opts/sub-select.json)

**Comment by doraeric** [comment]
@CounterPillow
Yes, packing subtitles into mkv would be a solution.
It's more like a personal preference to manage subtitles in separate text files. Sometimes I have multiple versions of videos and subtitles. Managing in separate files makes it easier to compare them using tools like `diff` if I want, also easier to share these subtitles among videos.

**Comment by doraeric** [comment]
@dyphire
I tried that PR locally, but it seems not doing what I want.
I also tried the lua script, but it's not loading srt files whose filenames contain the string in whitelist.

However, I think maybe I can write a script to load subtitles using glob like `filename.*.srt`.
Thanks for your information. Still hope this feature can be implemented in mpv.

**Comment by 1sixth** [comment]
Have you tried `--sub-auto=fuzzy`? It load all subs containing the media filename.[^1]

[^1]: https://mpv.io/manual/stable/#options-sub-auto

**Comment by occivink** [comment]
>It's more like a personal preference to manage subtitles in separate text files.

You can also package the subtitles as standalone `.mks` files. The biggest disadvantage is that it's not as easy to open the file to modify the actual text.

**Comment by doraeric** [comment]
@1sixth
Thank you! This is what I need! I didn't notice this option before.
