### ISSUE TITLE
MPV build error using latest FFMPEG libraries

### ISSUE THREAD

**Issue by ConHuevosGuey** [mpv-player/mpv#9803]
### mpv version and platform versions

GIT MASTER

### Reproduction steps

./bootstrap.py
./waf configure --enable-livmpv-shared
./waf

### Expected behavior
Build successfully.
### Actual behavior
Build ends in an error:

> /usr/bin/ld:` filters/f_lavfi.c.29.o: in function `is_usable':

>/root/src/mpv/build/../filters/f_lavfi.c:951: undefined reference to `avfilter_filter_pad_count'
>/usr/bin/ld: /root/src/mpv/build/../filters/f_lavfi.c:952: undefined reference to `avfilter_filter_pad_count'
>collect2: error: ld returned 1 exit status

>../video/decode/vd_lavc.c: In function ‘init_avctx’:
>../video/decode/vd_lavc.c:663:9: warning: ‘thread_safe_callbacks’ is deprecated [-Wdeprecated-declarations]
>  663 |         avctx->thread_safe_callbacks = 1;
>      |         ^~~~~
>In file included from ../video/decode/vd_lavc.c:25:
>/usr/local/include/libavcodec/avcodec.h:1479:9: note: declared here
>1479 |     int thread_safe_callbacks;
>      |         ^~~~~~~~~~~~~~~~~~~~~

I'm no programming expert but I believe the cause is MPV cannot build using the latest FFMPEG (clone of https://git.ffmpeg.org/ffmpeg.git) libraries.

### Log file
[wafconfig.log](https://github.com/mpv-player/mpv/files/7974672/wafconfig.log)

**Comment by avih** [comment]
Most probably you have two version of ffmpeg installed: one old which doesn't have `avfilter_filter_pad_count` (this was added nearly 6 months ago here https://github.com/FFmpeg/FFmpeg/commit/7c5f998196d101a661d802aa48dd62dd93d1fb3d ), and one new which does have it but `avfilter_pad_count` is deprecated or missing.

For some reason, mpv detects the new version during compilation - where `avfilter_filter_pad_count` does exist - https://github.com/mpv-player/mpv/commit/ec16769c2d37d74d53192d422d80c8e20a708fb7 but when it links it finds the old version which doesn't have it and errors.

So we'd need more details on your build and link setup, specifically how did you build and placed the new ffmpeg vrsion, and how you configured mpv to use it, but overall it's most probably not mpv's fault.

**Comment by ConHuevosGuey** [comment]
Thank you!  That was indeed the issue.  I'm on Slackware 15 and the Distro comes with ffmpeg 4.4.1.  I recently did a build of the latest FFMPEG and installed and forgot to uninstall the older version.  After removing 4.4.1, rebuilding FFMPEG and then trying to compile MPV, it works correctly.

Thank you again.

**Comment by avih** [comment]
Note that alternativey (if you want to keep the system ffmpeg) you can link statically with a new ffmpeg. That's what mpv-build does https://github.com/mpv-player/mpv-build .

**Comment by ConHuevosGuey** [comment]
> Note that alternativey (if you want to keep the system ffmpeg) you can link mpv statically with a new ffmpeg. That's what mpv-build does https://github.com/mpv-player/mpv-build .

Excellent.  Thank you.
