### ISSUE TITLE
Black crush with BT.2390 and gpu-next

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9805]
### Important Information

BT.2390 with vo=gpu-next is significantly darker and shows less shadow details. BT.2446a doesn't have this problem and BT.2390 + vo=gpu neither. madVR looks ok, too.

Please take a look at the screenshots in a viewer with dark background. Otherwise the differences are not really visible.

**"The Martian" (00:00:15.474)**

vo=gpu, BT.2390:
_mpv "movie.mkv" --vo=gpu -gpu-api=vulkan --no-config --target-peak=100 --tone-mapping=bt.2390_
![gpu_bt 2390_klein](https://user-images.githubusercontent.com/95616074/151932066-69c66df4-bb08-41ac-b304-3af5f7208bd7.jpg)

vo=gpu-next, BT2390:
_mpv "movie.mkv" --vo=gpu-next -gpu-api=vulkan --no-config --target-peak=100 --tone-mapping=bt.2390_
![gpu-next_bt 2390_klein](https://user-images.githubusercontent.com/95616074/151932109-d505e8d7-2381-4676-ac6f-20cdda1a514a.jpg)

vo=gpu-next, BT.2446a:
_mpv "movie.mkv" --vo=gpu-next -gpu-api=vulkan --no-config --target-peak=100 --tone-mapping=bt.2446a_
![gpu-next_bt 2446a_klein](https://user-images.githubusercontent.com/95616074/151932151-255c2555-c8e0-430f-9cf6-a7ff444da9df.jpg)

### Expected behavior
Same shadow detail/brightness as with vo=gpu.

### Actual behavior
Black crush.

### Log file

[gpu.log](https://github.com/mpv-player/mpv/files/7976727/gpu.log)
[gpu-next.log](https://github.com/mpv-player/mpv/files/7976728/gpu-next.log)
[gpu-next+bt.2446a.log](https://github.com/mpv-player/mpv/files/7976729/gpu-next%2Bbt.2446a.log)

**Comment by haasn** [comment]
Try `--tone-mapping=bt.2390 --tone-mapping-param=0.5`?

**Comment by FoLLgoTT** [comment]
> Try `--tone-mapping=bt.2390 --tone-mapping-param=0.5`?

That option makes no difference in dark parts of the picture. Only in very bright parts.

**Comment by haasn** [comment]
Oh, right. In any case, I think this happens because gpu-next actually implements the low-end of the BT.2390 curve, which the mpv implementation just ignores (and effectively does linear-stretching of the black point).

As such, this is ultimately a limitation of the BT.2390 curve. Maybe you could find a different curve that you like more? How about `spline`?

**Comment by Natural-Harmonia-Gropius** [comment]
I think it's the same issue, https://github.com/mpv-player/mpv/issues/9678.
also, you can see the red shadows and deep blue sky over saturated.

**Comment by FoLLgoTT** [comment]
> As such, this is ultimately a limitation of the BT.2390 curve. Maybe you could find a different curve that you like more? How about `spline`?

Spline has the same limitations. Only hable and BT.2446a seems to have the same amount of shadow detail as madVR and tone mapping 3D LUT from DisplayCAL.

Here is how a DisplayCAL 3D LUT (lut-type=conversion) handles it. It was generated with 100 Nits reference white and 10.000 Nits maximum by 3D LUT generator using synthetic ICC profiles.
![displaycal 10 000](https://user-images.githubusercontent.com/95616074/151989578-03f883b7-7e9d-478e-9a7d-a9e17dd063ef.jpg)

**Comment by haasn** [comment]
What if you use a different target curve? (try `gamma2.2`, `bt.1886` and `srgb` in particular)

Or ideally, an ICC profile

**Comment by FoLLgoTT** [comment]
> What if you use a different target curve? (try `gamma2.2`, `bt.1886` and `srgb` in particular)

Perfect! "gamma2.2" solves the problem. Even with target-lut there is no black crush anymore. :-)

_--start=00:00:15.474 --pause --vo=gpu-next -gpu-api=vulkan --no-config --target-peak=100 --tone-mapping=bt.2390 --target-trc=gamma2.2_
![gamma2 2](https://user-images.githubusercontent.com/95616074/151998088-8cc6e38f-fb18-4295-a241-2f36df50f7f8.jpg)

**Comment by haasn** [comment]
Sounds working as intended then. There's no real way for us to know how the target monitor is calibrated, you'll just have to set it appropriately.

**Comment by ValZapod** [comment]
> Perfect! "gamma2.2" solves the problem.

Yeah. Most monitors are like that. Not srgb. You need to specifically calibrate to get stgb piece wise function.

**Comment by FoLLgoTT** [comment]
> Sounds working as intended then. There's no real way for us to know how the target monitor is calibrated, you'll just have to set it appropriately.

But that is a bit strange. The manual states that target-trc=auto assumes gamma2.2 in case of HDR. So gpu-next obviously doesn't behave like that. auto and gamma2.2 should make no difference.

From manual:
_**auto**
Disable any adaptation, except for atypical transfers. Specifically, HDR or linear light source material gets automatically converted to gamma 2.2, while SDR content is not touched. (default)_

PS: my monitor (TV/projector) is properly calibrates to gamma 2.2 via 3D LUT or ICC profile (using profile loader of DisplayCAL).

**Comment by ValZapod** [comment]
BTW, I will just point out that BT.2390 is mostly a DTM, so it creates dynamic metadata out of static, so is for presenting HDR on HDR display without any transforms. Tonemapping PQ to SDR curve is really impossible, even with specific BT.2446 that describes how to "do" it.

**Comment by haasn** [comment]
> So gpu-next obviously doesn't behave like that. auto and gamma2.2 should make no difference.

Indeed, it infers BT.1886 by default. The man page hasn't really been updated for `gpu-next`. I'll probably go through and change all of these references whenever `gpu-next` is ready to become `gpu`. It's not really quite there yet (tm) which is why I haven't bothered.

**Comment by ValZapod** [comment]
> The manual states that target-trc=auto assumes gamma2.2 in case of HDR

>Indeed, it infers BT.1886 by default. 

Those are two different things. If SDR produced from Dolby Vision in gpu-next is in BT.1886 -- and yet swapchain mentions sRGB, but whatever -- then the default for target-trc is also BT.1886. That is just how SDR content in mpv behaves, for srgb srgb is target for bt.1886 bt.1886. For it to work you need to actually select --target=trc=gamma2.2 even on SDR content or switch your display to BT.1886. So many people are doing this wrong (including Chrome, but display can be turned to bt.1886).

While with vo gpu if it produces gamma2.2 then again gamma2.2 is default

>HDR or linear light source material gets automatically converted to gamma 2.

So documentation is wrong: for SDR and SDR produced for HDR is untouched. Again, target-trc should always be used.

**Comment by FoLLgoTT** [comment]
@haasn
There seems to be still an issue near black with HDR. Please take a look at the Mehanik test pattern. 

vo=gpu
![gpu](https://user-images.githubusercontent.com/95616074/156801328-169fd413-a712-4c53-913f-862df8daef1c.jpg)

vo=gpu-next
target-trc=auto
![gpu-next target-trc=auto](https://user-images.githubusercontent.com/95616074/156801393-085fa0a6-540f-4717-8e3a-e2753e6c9579.jpg)

vo=gpu-next
target-trc=gamma2.2
![gpu-next target-trc=gamma2 2](https://user-images.githubusercontent.com/95616074/156801432-5a1a6fdc-f1ef-48e7-8bac-58b7f48f20c2.jpg)


I checked the values with a color picker. With target-trc=auto the black bars up to 68 are RGB(0,0,0). With target-trc=gamma2.2 the bar 66 is still RGB(0,0,0). So there is a black crush which changes with target gamma.

**Comment by haasn** [comment]
@FoLLgoTT log, file?

**Comment by FoLLgoTT** [comment]
Here is the log file. dither-depth=auto makes no diference at all for these bars.

[gpu-next.log](https://github.com/mpv-player/mpv/files/8190719/gpu-next.log)

**Comment by haasn** [comment]
Oh, I see. You're rendering to a 10-bit framebuffer. Are you sure the "numerical black crush" can be verified when you capture the actual 10-bit framebuffer? Downconversion to 8-bit without dithering will lose that. Try taking your screenshots with `--screenshot-format=png`.

> dither-depth=auto makes no diference at all for these bars.

It should when taking 8-bit screenshot (e.g. jpg files)

**Comment by FoLLgoTT** [comment]
> Oh, I see. You're rendering to a 10-bit framebuffer. 

How can I change that? Even dither-depth=8 bit doesn't change anything.

>Are you sure the "numerical black crush" can be verified when you capture the actual 10-bit framebuffer? Downconversion to >8-bit without dithering will lose that. Try taking your screenshots with `--screenshot-format=png`.

Here is the PNG:
![48bit](https://user-images.githubusercontent.com/95616074/156885887-d68a4e1e-3a98-4634-88e6-68ccd307e24e.png)

I stated above that there is no black crush with target-trc=gamma2.2. But then the steps above are too bright. It looks a bit weird and different to vo=gpu, madVR or tone mapping LUT from DisplayCAL. And the saturation is a bit too high with gpu-next. I still think there is something wrong. Or at least different to the other algorithms/renderers/LUT.

**Comment by FoLLgoTT** [comment]
@haasn
Any idea about the black crush?

And about the higher saturation? I can reproduce it with and without 3D LUT. That makes no difference. The saturation is higher with gpu-next even >100 nits. Not only in the black parts.
