### ISSUE TITLE
osc script-opts title option

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#9807]
### Expected behavior of the wanted feature

osc script-opts title option `title="${filename}` shows filename of video file, but shows parts of url of Youtube stream. 

osc script-opts title option `title="${media-title}` shows Youtube video title, but shows video tag for video file. 

### Alternative behavior of the wanted feature

Allow the option to show filename of video file AND show title of stream, not one or the other. I need the latter but lots of videos from the internet have tags modified that don't match their filename. I don't use tags for videos and interact videos only through their filenames.

**Comment by avih** [comment]
> Allow the option to show filename of video file AND show title of stream

`title="${filename} ${media-title}"`

**Comment by guidocella** [comment]
You can use this conditional profie:

```
[local]
profile-cond=demuxer_via_network == false
script-opts-append=osc-title=${filename}
```

**Comment by rieje** [comment]
@guidocella That looks like it works, but I've just encountered a file where it shows the value of "`Movie name`" (in my case the value was "`manifest`") in the osc title as opposed to the filename (that was passed to mpv and is also the value of "`Complete name`" according to `mediainfo`.

I tried to do the inverse of the profile:

    title=${filename}

    [local]
    profile-cond=demuxer_via_network == true
    script-opts-append=osc-title=${media-title}

but playing a Youtube stream shows URL while local file shows the filename as expected.

**Comment by guidocella** [comment]
You may be playing a file on a slow filesystem that mpv mistakes as a network file. Check the output of `show-text ${demuxer-via-network}` in the console that you can open by pressing ` (backtick).

I don't understand and can't reproduce how adding that profile would make youtube streams stop showing `${media-title}` as the OSC title since that is the default.

**Comment by rieje** [comment]
@guidocella I had the profile in osc.conf instead of mpv.conf >.>. Seems to work well, thank you.
