### ISSUE TITLE
add tone-mapping-mode=xyY

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9809]
method from BT2446C
![image](https://user-images.githubusercontent.com/50797982/152159687-6ce49ca0-3f5f-4731-94a0-d1779db70a59.png)

Look at the screenshots below, luma is even more saturated than max in low brightness area, xyY doesn't, and rgb lost saturate in high brightness area, xyY doesn't.
I implemented the code according to the report.
https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/main/shaders-toys/Tonemapper/BT2446C.glsl

xyY / rgb / max / hybrid / luma (hable cruve for all)
<img src="https://user-images.githubusercontent.com/50797982/152158761-1c4da4e1-20a4-4e24-a912-bdebabd5c8b7.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152158738-15b9d3a1-420d-453b-944c-a2422358e724.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152158748-314f929a-f942-4d95-92eb-df79c9e411e5.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152158754-51668f7d-5b4f-4edd-b890-f25028c6ca4d.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152158757-a22de6ec-871a-4c4c-a27c-32cc88568153.png" alt="" width="20%">
<img src="https://user-images.githubusercontent.com/50797982/152162492-bf0d6b34-2fb8-4dbf-b7c4-208dd48b23f9.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152162514-76fc1029-2ef5-4879-898f-afe48777e929.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152162552-e239416e-587b-4dca-8bd9-8fa1f18230d9.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152162577-884e090c-663b-4c91-9c8f-5afee30ad468.png" alt="" width="20%"><img src="https://user-images.githubusercontent.com/50797982/152162749-e58990fe-29ff-46d7-8933-e822c988f97c.png" alt="" width="20%">

Samples
https://user-images.githubusercontent.com/50797982/152163988-dd98b653-352e-42f2-9682-25f8e68d19c8.mp4
https://user-images.githubusercontent.com/50797982/152164029-da9e3f06-3063-4126-92d0-8c2559ec32e5.mp4

Screenshot of sample one from uwp with dovi ext.
![image](https://user-images.githubusercontent.com/50797982/152165924-13ba51aa-817f-452d-b319-48d6b8c65f56.png)

**Comment by haasn** [comment]
The `luma` mode already does tone-mapping in Yxy space.

**Comment by quietvoid** [comment]
From my experimenting it comes from the higher black point.
However RGB is too desaturated in low brightness.

**Comment by Natural-Harmonia-Gropius** [comment]
> Compare with 'clip' tone mapping.

clip luma
![image](https://user-images.githubusercontent.com/50797982/152181596-f3da8f4c-3370-48b7-9a82-2cc8cbe9fadd.png)

clip rgb
![image](https://user-images.githubusercontent.com/50797982/152181541-e48c5c00-f231-4931-a2a0-3116031b70d7.png)

my shaders
![image](https://user-images.githubusercontent.com/50797982/152180793-ce15fe6e-8a02-4f10-9b44-98cbabe451e9.png)
![image](https://user-images.githubusercontent.com/50797982/152184854-7ef7d714-bd29-4974-a45a-3d47366ada3a.png)

without dovi EL + target-trc=hlg
![image](https://user-images.githubusercontent.com/50797982/152185584-97d6ebc6-088b-40bb-9edc-4fc90dd33587.png)

auto luma
![image](https://user-images.githubusercontent.com/50797982/152182258-1bf37517-86ab-499e-8d58-1fbba637d23f.png)

clip luma
![image](https://user-images.githubusercontent.com/50797982/152182724-9626cdb4-056b-4a80-bb7d-8e71eb209b08.png)

target-trc=hlg
![image](https://user-images.githubusercontent.com/50797982/152182468-349a8c1f-c3fd-4164-9686-d198ccd9abc4.png)

https://user-images.githubusercontent.com/50797982/152182953-4197ccd7-498e-419f-b929-ca84d2ca2f67.mp4
