### ISSUE TITLE
Is tone-mapping-mode luma made from ITU-R BT.2446a?

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#9810]
> Luminance-based method from ITU-R BT.2446a

https://mpv.io/manual/master/#options-tone-mapping-mode says that.

But it looks like bt.2446a in the report is handle luminance entirely in YCbCr, without using CIE XYZ.
https://github.com/haasn/libplacebo/blob/9a102248f2beb88654952400fa2add39e86734c0/src/shaders/colorspace.c#L1427-L1459
![image](https://user-images.githubusercontent.com/50797982/152166798-2fcca279-578b-4c7f-93a2-81cf59b73ae3.png)

**Comment by quietvoid** [comment]
Yes, both luma and hybrid share most of the same code path as of https://github.com/haasn/libplacebo/commit/9a102248f2beb88654952400fa2add39e86734c0.

**Comment by Natural-Harmonia-Gropius** [comment]
I'm a little unclear in my expression, why libplacebo process in `XYZ.y`?
https://github.com/haasn/libplacebo/blob/9a102248f2beb88654952400fa2add39e86734c0/src/shaders/colorspace.c#L1447

it looks bad in my code.
![image](https://user-images.githubusercontent.com/50797982/152169004-c052ea97-b78c-46bd-a6e5-ee8d8dc8a26f.png)
![image](https://user-images.githubusercontent.com/50797982/152169054-05824430-cdfc-4c9f-b495-e9249240d35d.png)

**Comment by haasn** [comment]
> I'm a little unclear in my expression, why libplacebo process in XYZ.y?

CIE XYZ's Y and YCbCr's Y are identical, and the other color channels are linearly related.
