### ISSUE TITLE
MPV shows blank screen / lags / crashes on Fedora 35 with Wayland and Nvidia

### ISSUE THREAD

**Issue by Parent5446** [mpv-player/mpv#9816]
### Important Information

Provide following Information:
- mpv version: **0.34.1**
- Linux Distribution and Version: **Fedora Workstation 35**
- Source of the mpv binary: **rpmfusion-free**
- If known which version of mpv introduced the problem
- Window Manager and version: **Wayland / GNOME 42**
- GPU driver and version: **Nvidia 495.46** 
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

1. Play a video.

### Expected behavior

The video shows on-screen and has smooth playback.

### Actual behavior

With default settings, sometimes only a black screen is rendered, and other times a segmentation fault occurs and MPV crashes.

Setting `--gpu-api=vulkan --gpu-context=wayland` causes video to actually show up, but it is extraordinarily laggy and unwatchable (frames are dropping constantly). Additionally, if `--gpu-context=wayland` is omitted, a blank *blue* screen is shown instead.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

Default (`--no-config`)
[mpv.log](https://github.com/mpv-player/mpv/files/7991179/mpv.log)
[stderr.log](https://github.com/mpv-player/mpv/files/7991180/stderr.log)

With `gpu-api=vulkan gpu-context=wayland`:
[mpv.log](https://github.com/mpv-player/mpv/files/7991170/mpv.log)
[stderr.log](https://github.com/mpv-player/mpv/files/7991172/stderr.log)

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

https://0x0.st/oHlY.mkv

**Comment by Dudemanguy** [comment]
Please try the master branch. There were some commits directly related to this (nvidia stuff).

**Comment by Parent5446** [comment]
Got it. I'll try grabbing and compiling tomorrow when I have some time.

**Comment by Parent5446** [comment]
OK built on master and it does show video now. There's a weird behavior where the cursor no longer displays when MPV is in full-screen, but I can deal with that.
