### ISSUE TITLE
Is it possible to process the OSD by shaders?

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9820]
I wrote a warping shader for my curved screen. It works fine, but the OSD is not processed. Is there a way to do it? Like embedding subtitles to the picture?

**Comment by ValZapod** [comment]
> for my curved screen

You are supposed to watch and preserve the geometry. Curved screens happen due to form of our eyes. After some time with curved screen it is harder to look into noncurved screens.

**Comment by FoLLgoTT** [comment]
> You are supposed to watch and preserve the geometry. Curved screens happen due to form of our eyes. After some time with curved screen it is harder to look into noncurved screens.

No that is not the problem [my shader](https://github.com/FoLLgoTT/Warping) is intended for. I talk abour projection screens. The problem is not geometric distortion from our yes, but from the projector which has a lens not calculated for curved screens. And more important to compensate an asymmetrical vertical placement of the projector which creates an asymmetric barrel and bow distortion.

**Comment by haasn** [comment]
The short answer is that this is not currently possible.

The long answer is that if you just need this for personal use you could easily accomplish it by modifying like two lines of code.
