### ISSUE TITLE
Add preprocessor macros to detect renderer version at compile-time for shaders

### ISSUE THREAD

**Issue by agyild** [mpv-player/mpv#9822]
If we had a way to detect current renderer version (e.g., DX10+ or OGL4+) at compile-time, optionally we could compile the shader with a more performance-saving algorithms that is only supported by the more recent versions of renderers (e.g., `textureGather()`), and fallback to more performance-heavy, default ones if the former are not supported. Current limitations require either to add an user controlled variable to enable such optional routines, or create multiple versions of the same shader targeted for different versions of renderers, which makes it harder to maintain code and harder for user to configure the shader.

**Comment by haasn** [comment]
You can test for the presence of the `TEXTURE_gather` macro already. Did you need anything else?

**Comment by agyild** [comment]
> You can test for the presence of the `TEXTURE_gather` macro already. Did you need anything else?

I thought it would just test if the current mpv has the macro defined, rather than the current renderer supports it.

> I suppose we could maybe make the GLSL version available as a macro (which it, surprisingly, apparently isn't). Edit: Nvm, that exists as `__VERSION__` already in base GLSL.

Good to know. I will let you know if it works as expected. Thanks.
