### ISSUE TITLE
[question] Is it possible to override a subtitle track's filename?

### ISSUE THREAD

**Issue by Pato05** [mpv-player/mpv#9825]
I wonder if it is possible (via command-line args) to specify a (text) track's name, without it falling back to the file name, this would be particularly useful, for example, for remote tracks, that usually have the `{language_code}.extension` format, and replace it by something more human-friendly.

I am using the `--sub-file` option to specify subtitle files for my video, and repeating it for as many subtitle tracks I need (those subtitles are remote files, not local, so I do not have control over the filename).

I already searched this question up, but it doesn't seem to have been already answered and/or there is an open or closed issue or pull request talking about this.

Thank you!

**Comment by guidocella** [comment]
Use `--force-media-title=<string>`

**Comment by Pato05** [comment]
> Use `--force-media-title=<string>`

This seems to override the video's filename, not the subtitle's

**Comment by avih** [comment]
> I wonder if it is possible (via command-line args) to specify a (text) track's name

Which track? audio? video? sub?

Also, there's no such thing as track "name".

Please be very specific in what you're trying to achieve, because your question is completely incoherent and impossible to answer. The edits don't help either.

**Comment by Pato05** [comment]
> Which track? audio? video? sub?
>
> Also, there's no such thing as track "name".

I would like to modify the subtitle track's filename, which defaults to the file's name; I would like to override it, pretty much how the `-force-media-title` flag does for the video's filename.

**Comment by avih** [comment]
> I would like to modify the subtitle track's filename, which defaults to the file's name; I would like to override it, pretty much how the `-force-media-title` flag does for the video's filename.

The media-title is only used for display purposes.

> I am using the `--sub-file` option to specify subtitle files for my video

That's the only way to choose a local sub file which is not the same as the file name.

> his would be particularly useful, for example, for remote tracks, that usually have the {language_code}.extension format

And for remote files that's the only way, because even if it was following some naming convention, mpv doesn't enumerate the files on a remote (http[s]) server.

**Comment by Pato05** [comment]
> The media-title is only used for display purposes.

Yeah, I'm trying to achieve this, except for subtitle tracks

> And for remote files that's the only way, because even if it was following some naming convention, mpv doesn't enumerate the files on a remote http[s] server.

I know it is the only way, I know mpv cannot enumerate files from an http server like it can from a local directory; I just asked for a way to specify a different name, rather than the default one, for **display purposes**, to be able to distinguish between tracks that have the same filename, but they're a different version from each other.

**Comment by avih** [comment]
> > The media-title is only used for display purposes.
> 
> Yeah, I'm trying to achieve this, except for subtitle tracks

Can't be done, unless the sub track itself contains this meta info.

**Comment by Pato05** [comment]
> Can't be done, unless the sub track itself contains this meta info.

got it, thanks

**Comment by guidocella** [comment]
`track-list/N/title` should be writable in order to achieve this, but since it isn't, you could use a script that calls dmenu with custom titles for subs and lets you select a subtitle:

```lua
mp.add_key_binding('Alt+j', function ()
    local subs = ''
    for _, track in pairs(mp.get_property_native('track-list')) do
        if track.type == 'sub' then
            local title
            if track['external-filename'] == 'https://example.com/en.vtt' then
                title = 'English (x fps)'
            else
                title = track.title
            end
            subs = subs .. track.id .. ' ' .. title .. '\n'
        end
    end

    if subs == '' then
        return
    end

    local file = io.open('/tmp/subs', 'w')
    file:write(subs)
    file:close()

    local r = mp.command_native({
        name = 'subprocess',
        capture_stdout = true,
        args = {'sh', '-c', 'dmenu < /tmp/subs'},
    })
    if r.status == 0 then
        mp.set_property('sid', r.stdout:match('%d+'))
    end
end)
```
