### ISSUE TITLE
Honour X11 _ICC_PROFILE atom

### ISSUE THREAD

**Issue by juw** [mpv-player/mpv#983]
Hi,

when using OpenGL as output driver, one can automatically use the right ICC profile via "icc-profile-auto" on OS X. It would be nice, if that option could be extended, so that it automatically selects the current display ICC profile specified in the X11 _ICC_PROFILE atom, which would make it useful on Linux systems, too.

Cheer.

**Comment by wm4** [comment]
Actually, this was implemented.
