### ISSUE TITLE
Subtitle with wrong ass style 

### ISSUE THREAD

**Issue by Mikasa-san** [mpv-player/mpv#9832]
### Important Information

Provide following Information:
- mpv version mpv-0.34.1
- macOS Version 12.2 and the Issue was in big sur also
- Device Mac Mini M1.
- Source of the mpv binary or bundle https://laboratory.stolendata.net/~djinn/mpv_osx/
- The Issue from versions 0.33.0 and above
- Possible screenshot or video of visual glitches
<img width="1749" alt="Screen Shot 2022-02-06 at 12 13 48 AM" src="https://user-images.githubusercontent.com/54586069/152657465-485558d5-720c-4f21-9e94-f74fdc33f872.png">

If you want I can also upload for you the file which has the ass file .

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

**Comment by Akemi** [comment]
the issue template told you what you have to provide. though you it's probably a libass problem so you should report that to them.
