### ISSUE TITLE
Test twitch url with log but without opening the stream

### ISSUE THREAD

**Issue by jppaled** [mpv-player/mpv#9834]
Hello !

I need to test if a stream via a twitch url is online or not.

I use this command: `mpv --msg-level=all=error https://twitch.tv/exemplechannel`

if the stream is offline, it show me error and does not open the stream (yes it's logic because it's offiline)
`[ytdl_hook] ERROR: exemplechannel is offline `

But I can't find a combination of options that display nothing in the terminal if the stream is online **WITHOUT** open the stream.

I have also tried with `--quiet` and `--really-quiet` options

It's like i'm trying to find a command that only "test" the url

Can someone help me please ?

I use mpv `0.32.0`

Thanks

**Comment by garoto** [comment]
Wrong tool for the job, but here's something my puny brain came up with:

> mpv https://www.twitch.tv/marzzzzy --end=0.1 --vo=null --keep-open=no & echo !errorlevel!
or if on *nix:
> mpv https://www.twitch.tv/marzzzzy --end=0.1 --vo=null --keep-open=no ; echo $?

Act on the exit code of the program.

**Comment by jppaled** [comment]
@garoto 
it's works like a charm thank you !

here is the usage if anyone is interested

```
if $(mpv https://www.twitch.tv/$1 --end=0.1 --vo=null --keep-open=no | grep -q 'offline\|not exist'); then
    echo "$1 is not online or does not exist"
else
    # start the stream
fi
```

**Comment by guidocella** [comment]
`yt-dlp -sq https://twitch.tv/exemplechannel`

**Comment by jppaled** [comment]
@guidocella It works great, but i would like to only use mpv or a basic command-line tool

**Comment by guidocella** [comment]
mpv can only play twitch URLs through youtube-dl, how is using mpv more basic than using youtube-dl directly?

**Comment by jppaled** [comment]
`youtube-dl` and `yt-dlp` are two diffenrent package no ?

**Comment by guidocella** [comment]
Yes, but either one works.

**Comment by jppaled** [comment]
Ah ok ! It works really great, I gain 1,5s on my script thanks @guidocella

**Comment by garoto** [comment]
Can the resident italian-shitter be made into a mpv member for a change? It's about time people, c'mon.
