### ISSUE TITLE
Pipewire stream stays active after video ends

### ISSUE THREAD

**Issue by gbpi** [mpv-player/mpv#9835]
### Important Information
When the video ends naturally my easyeffects CPU usage stays high like it is still playing. I can see the 'wires' still connected in helvum.

![ss_20220205234308](https://user-images.githubusercontent.com/11637237/152668071-0100ab90-6144-460c-bea0-c75ffaf4e7ed.png)

If I pause the video, or just back up after it ends, it works as expected, the 'wires' in helvum disappear and easyeffects CPU usage is normal for idle. 

![ss_20220205234343](https://user-images.githubusercontent.com/11637237/152668074-828073b5-2582-44a4-8993-96001119ba8f.png)

Pulse through pipewire-pulse works as expected.

Provide following Information:
- mpv version: mpv 0.34.0-184-g7849a36beb
- Linux Distribution and Version: Arch
- Source of the mpv binary: AUR mpv-git

### Reproduction steps
Has to be native pipewire which was recently added.

Not sure the best way to show this other than helvum, maybe someone who knows more about pipewire could help.

**Comment by t-8ch** [comment]
I assume you are using the configuration `keep-open`, correct?
Then after the file is played the playback is paused.

Pipewire uses the pull-based audio API of mpv, which pulse uses the push-based one.
For pull-based AOs mpv does not notify the AO that it should pause but instead sends silence data.
Therefore the links in helvum stay solid and easyeffects is still processing that (silence) data.

To fix this we have to either change the mpv core to also call the `set_paused` function for pull-based AOs or convert the pipewire AO to a push-based one.

I'll let the AO maintainers weigh in.

**Comment by t-8ch** [comment]
Ignore the bits about the pull-based AO not calling `set_paused()`.
Instead pull-based AOs will be `reset()`. However the logic in `audio/out/buffer.c` does not call reset when the stream has finished playing as happens with `--keep-open`.

The following patch forces a reset even if the stream has finished playing, could you test it?

```
diff --git a/audio/out/buffer.c b/audio/out/buffer.c
index 2a69596597..75edab3215 100644
--- a/audio/out/buffer.c
+++ b/audio/out/buffer.c
@@ -386,6 +386,8 @@ void ao_set_paused(struct ao *ao, bool paused)
             p->streaming = true;
         }
         wakeup = true;
+    } else if (!p->paused && paused && !ao->driver->write) {
+        do_reset = true;
     }
     p->paused = paused;
```

**Comment by gbpi** [comment]
Thanks, that works perfectly.

My laptop is old and I use autogain in easyeffects, so CPU usage is pretty high when it is doing anything.

**Comment by t-8ch** [comment]
@philipl Do you think this is the correct fix for the issue?

**Comment by philipl** [comment]
I'm not sure. This isn't an area I'm familiar with. I need to find someone else to weigh in. But instinctively it seems like a reasonable approach.

**Comment by philipl** [comment]
@jeeb Any thoughts?

**Comment by t-8ch** [comment]
This needs to be reopened as the original fix got reverted.

**Comment by philipl** [comment]
I thought we fixed it a different way. Is it still broken?

**Comment by t-8ch** [comment]
This issue got fixed as a drive-by.
The other issue got fixed properly but the new fix didn't work for this issue.
