### ISSUE TITLE
d3d11va does not forward HDR metadata to VO

### ISSUE THREAD

**Issue by FoLLgoTT** [mpv-player/mpv#9836]
### Important Information

With gpu-next and hwdec=d3d11va-copy or dxva2-copy the image is significantly darker on HDR content.

Software decoding:
![software_decoding_klein](https://user-images.githubusercontent.com/95616074/152671980-45511e53-5c7a-4fda-a3c6-b8c1945f371b.jpg)

Hardware decoding:
![d3d11va-copy_klein](https://user-images.githubusercontent.com/95616074/152671985-d9d47ab1-875f-4dff-a97f-b02d6e879211.jpg)

### Expected behavior
Same brightness.

### Actual behavior
Image is darker.

### Log file
[softwaredecoding.txt](https://github.com/mpv-player/mpv/files/8009684/softwaredecoding.txt)
[d3d11va-copy.txt](https://github.com/mpv-player/mpv/files/8009685/d3d11va-copy.txt)

**Comment by haasn** [comment]
Doesn't seem like there's an obvious issue in the metadata:

```
[vf] [out] 3840x2160 yuv420p10 bt.2020-ncl/bt.2020/pq/limited/display SP=4.926108 CL=uhd
[vf] [out] 3840x2160 p010 bt.2020-ncl/bt.2020/pq/limited/display SP=4.926108 CL=uhd
```

It could be the mastering colorspace primaries. Just to confirm, does `--gamut-mode=clip` make the difference go away?

**Comment by FoLLgoTT** [comment]
> It could be the mastering colorspace primaries. Just to confirm, does `--gamut-mode=clip` make the difference go away?

Yes, with clip the problem completely goes away.

**Comment by haasn** [comment]
Old issue, and no longer as pressing since `--gamut-mode=clip` is now the default behavior, but the likely culprit here is that `d3d11va` hwdec does not forward all HDR mastering metadata, by the sound of it.

**Comment by kasper93** [comment]
@FoLLgoTT Could you test with the latest version? There were fixes recently in this area and to my knowledge all metadata is passed correctly now with `-copy` hwdec.

**Comment by FoLLgoTT** [comment]
@kasper93
I don't seen any difference anymore. Thank you! :-)

**Comment by Dudemanguy** [comment]
Seems like this was fixed? Closing.
