### ISSUE TITLE
gpu-next: 60 fps video with interpolation breaks apart

### ISSUE THREAD

**Issue by Gigas002** [mpv-player/mpv#9837]
### Important Information
mpv version:

```
mpv 0.34.0-184-g7849a36beb Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 06 08:55:33 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```

linux destribution and version:
```
Operating System: Manjaro Linux
Kernel: Linux 5.16.6-1-MANJARO
Architecture: x86-64
```

source of mpv binary: mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

window manager: `x11, KDE Plasma 5.23.5`

GPU driver: proprietary nvidia driver 510.47.03

### Reproduction steps

```
mpv --no-config --profile=gpu-hq --gpu-api=vulkan --vo=gpu-next --video-sync=display-resample --interpolation=yes "https://www.youtube.com/watch?v=mSKOqTkRhR4"
```

### Expected behavior

Video plays without problems

### Actual behavior

Video tears apart. This issue doesn't occur without `--vo=gpu-next` and also doesn't occur with `--vo=gpu-next --vulkan-queue-count=1 --swapchain-depth=1`. Probably related to #8360?

### Log file

[log.zip](https://github.com/mpv-player/mpv/files/8010008/log.zip)

### Sample files

[video.zip](https://github.com/mpv-player/mpv/files/8010009/video.zip)

**Comment by ValZapod** [comment]
That video is 60.000 fps, not 60/1.001 so that may be the reason.

**Comment by aufkrawall** [comment]
display-resample Vulkan is broken with Nvidia Xorg, don't use: https://github.com/mpv-player/mpv/issues/6172

**Comment by haasn** [comment]
Does this still happen? And can you *observe* the tearing in a screenshot / screen capture, or is it only visible on the monitor during playback?

**Comment by Gigas002** [comment]
Doesn't seem to happen anymore
