### ISSUE TITLE
High GPU usage and low CPU usage

### ISSUE THREAD

**Issue by NeilTohno** [mpv-player/mpv#9838]
```
[HD_ani] 
profile-desc=cond:(p["video-params/w"]>955)
profile=high_q
glsl-shaders-clr
#glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
glsl-shaders-append="~~/shaders/FSRCNN_x2_r2_16-0-2.glsl"
#glsl-shaders-append="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
linear-downscaling=no
```

I test 1080p video file with mpv, the GPU is at 90 to 95 percent usage, and CPU is at 10 percent usage.

The GPU fan make loud noise.

Thanks.

### Important Information

- mpv version
mpv-x86_64-20220116-git-1ba0547
- Windows Version
win10 21H2 64bit
2950x cpu , vega 64

###
I found no error in mpv's log file.
I will upload a screenshot next time, 
thanks.

**Comment by Cloud11665** [comment]
you use shaders that run on the gpu.

**Comment by lavilao** [comment]
use the x2_8 version, the quality between x2_8 and x2_16 is negible the impact in performance though is not. Also as @Cloud11665 said you are running shaders that run on the gpu so the gpu get more use than the cpu.
