### ISSUE TITLE
When playing with ass sub which uses a non-exists font, can not fall back to system default.

### ISSUE THREAD

**Issue by Tsukimeizi** [mpv-player/mpv#984]
System: OS X 10.10

$ mpv The.Strain.S01E01.720p.HDTV.X264-DIMENSION.mkv 
Playing: The.Strain.S01E01.720p.HDTV.X264-DIMENSION.mkv
[stream] Video (+) --vid=1 (h264)
[stream] Audio (+) --aid=1 (*) (ac3)
[stream] Subs  (+) --sid=1 'The.Strain.S01E01.720p.HDTV.X264-DIMENSION.简体&英文.ass' (ass) (external)
[vo/opengl-hq] Opening ICC profile '/Library/ColorSync/Profiles/Displays/Color LCD-C6076DC3-B2A7-E5A5-3A31-D9E7427CFF58.icc'
Trying to use hardware decoding.
AO: [coreaudio] 48000Hz stereo 2ch float
AV: 00:00:00 / 01:09:55 (0%) A-V:  0.000
VO: [opengl-hq] 1280x720 => 1280x720 vda
AV: 00:00:00 / 01:09:55 (0%) A-V:  0.000
Neither PlayResX nor PlayResY defined. Assuming 384x288
AV: 00:00:00 / 01:09:55 (0%) A-V:  0.001
[osd/libass] fontselect: Using fallback font family: (sans-serif, 400, 0) -> /Library/Fonts/Arial.ttf, -1, ArialMT
AV: 00:00:04 / 01:09:55 (0%) A-V:  0.002
fontselect: Using fallback font family: (TestFont, 400, 0) -> /Library/Fonts/Arial.ttf, -1, ArialMT
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V:  0.005
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V:  0.005
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V:  0.002
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V: -0.001
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V:  0.002
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V: -0.001
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V:  0.002
Error opening font: '/Library/Fonts/Arial.ttf', 1
AV: 00:00:04 / 01:09:55 (0%) A-V:  0.007
...

The ass file "The.Strain.S01E01.720p.HDTV.X264-DIMENSION.简体&英文.ass" has a default style with TestFont which in fact does not exists in the system.

Then mpv can not show ass sub.

The ass file:

[Script Info]
; Script generated by Aegisub r6195M (development version, SAPikachu - 2.1.9 branch)
; http://www.aegisub.org/
Title:YYeTs
Original Script:YYeTs
Synch Point:1
ScriptType: v4.00+
Collisions:Normal
Video File: EG.avs
Video Aspect Ratio: 0
Video Zoom: 4
Video Position: 2874

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,TestFont,20,&H00FFFFFF,&HF0000000,&H00000000,&H32000000,0,0,0,0,100,100,0,0,1,2,1,2,5,5,2,134

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:04.17,0:00:07.15,_Default,NTP,0000,0000,0000,,诗人曾言\N{\fn微软雅黑}{\fs14}Hunger, a poet once said,
Dialogue: 0,0:00:07.29,0:00:09.84,_Default,NTP,0000,0000,0000,,饥渴是我们所知最重要之事\N{\fn微软雅黑}{\fs14}is the most important thing we know,
Dialogue: 0,0:00:09.84,0:00:11.84,*Default,NTP,0000,0000,0000,,也是我们所学之初\N{\fn微软>雅黑}{\fs14}the first lesson we learn.
...

**Comment by twlz0ne** [comment]
```sh
echo 'sub-text-font="STHeiti"' >> ~/.config/mpv/mpv.conf
```

Work fine on my mac
