### ISSUE TITLE
mpv_get_property returns filter params in unordered map breaking remove

### ISSUE THREAD

**Issue by low-batt** [mpv-player/mpv#9841]
### Important Information

Provide following Information:
- mpv version: 0.34.1
- macOS Version: 12.1
- Source of the mpv binary or bundle: Local build
- If known which version of mpv introduced the problem: Unknown
- Possible screenshot or video of visual glitches: Not that kind of problem

### Reproduction steps
Add an audio filter and then use the `mpv_get_property` client API call to obtain the audio filters.

### Expected behavior
The filter returned by `mpv_get_property` is useable in the `af` `remove` command.

### Actual behavior
The `af` and `vf` `remove` and `toggle` commands when matching filters compare _argument order_.  That requirement conflicts with the node structure returned by `mpv_get_property` for filters which uses a `MPV_FORMAT_NODE_MAP` to hold the filter arguments. The documentation for `MPV_FORMAT_NODE_MAP` in  [client.h](https://github.com/mpv-player/mpv/blob/c72b897e9cb60a3dd4a4fd35442ba21ea7ef6163/libmpv/client.h#L815) within the `mpv_node_list` structure explicitly documents that _keys are in random order_.

Is the documentation wrong for `MPV_FORMAT_NODE_MAP`? Can clients depend upon the order of keys in a map returned for a filter? If not, isn't it inappropriate for `mpv_get_property` to be returning filter arguments in an unordered map given the requirements of the `remove` and `toggle` commands?

This conflict is the root cause of IINA issue https://github.com/iina/iina/issues/3620. When IINA is parsing the `mpv_node` returned by `mpv_get_property` into Swift objects it uses a [Swift Dictionary](https://developer.apple.com/documentation/swift/dictionary) for  `MPV_FORMAT_NODE_MAP`. The order of key-value pairs in a Swift Dictionary is unpredictable. Based on the documentation of  `MPV_FORMAT_NODE_MAP` that is a correct representation. However if the documentation for `MPV_FORMAT_NODE_MAP` is wrong about the order of keys and the map returned by `mpv_get_property` can be relied upon to match the order of arguments in a filter then IINA needs to be changed to parse a `MPV_FORMAT_NODE_MAP` into a [Swift OrderedDictionary](https://github.com/apple/swift-collections/blob/main/Documentation/OrderedDictionary.md).

A quick test indicated  `mpv_get_property` is returning the filter argument key-value pairs in the map in the correct order. In a test changing IINA to preserve that order using an `OrderedDictionary` resolved the problem reported in IINA issue https://github.com/iina/iina/issues/3620. However given the clear documentation that the keys in a `MPV_FORMAT_NODE_MAP` are in random order I would expect developers to question such an IINA "fix".

Thoughts? How should library clients deal with the ordering of filter arguments?

The concerning comment regarding `MPV_FORMAT_NODE_MAP` keys being in random order from [client.h](https://github.com/mpv-player/mpv/blob/c72b897e9cb60a3dd4a4fd35442ba21ea7ef6163/libmpv/client.h#L815):
```c
/**
 * MPV_FORMAT_NODE_ARRAY:
 *  unused (typically NULL), access is not allowed
 *
 * MPV_FORMAT_NODE_MAP:
 *  keys[N] refers to key of the Nth key/value pair. If num > 0, keys[0] to
 *  keys[num-1] (inclusive) are valid. Otherwise, this can be NULL.
 *  The keys are in random order. The only guarantee is that keys[N] belongs
 *  to the value values[N]. NULL keys are not allowed.
 */
```

Text from the [mpv manual](https://mpv.io/manual/stable/#video-filters) indicating the order of filter arguments matters:
```text
--vf-remove=filter
    Deletes the filter from the list. The filter can be either given the way it was added (filter name and its
	full argument list), or by label (prefixed with @). Matching of filters works as follows: if either of the
	compared filters has a label set, only the labels are compared. If none of the filters have a label, the
	filter name, arguments, and argument order are compared. (Passing multiple filters is currently still
	possible, but deprecated.)
```

The `af` / `vf` property definition from the [mpv manual](https://mpv.io/manual/stable/#video-filters) showing filter params as being returned in a `MPV_FORMAT_NODE_MAP`:
```text
 af, vf (RW)

    See --vf/--af and the vf/af command.

    When querying the property with the client API using MPV_FORMAT_NODE, or with
	Lua mp.get_property_native, this will return a mpv_node with the following contents:

    MPV_FORMAT_NODE_ARRAY
        MPV_FORMAT_NODE_MAP (for each filter entry)
            "name"      MPV_FORMAT_STRING
            "label"     MPV_FORMAT_STRING [optional]
            "enabled"   MPV_FORMAT_FLAG [optional]
            "params"    MPV_FORMAT_NODE_MAP [optional]
                "key"   MPV_FORMAT_STRING
                "value" MPV_FORMAT_STRING

    It's also possible to write the property using this format.
```

### Log file

This clip from the mpv log file merely confirms the behavior discussed above. In it you can see that IINA is not passing the filter arguments to the remove command in the same order that was used when adding the filters due to the reordering occuring when parsing the `MPV_FORMAT_NODE_MAP`:

<details>
<summary>mpv Log</summary>

```text
[  19.802][d][cplayer] Run command: af, flags=64, args=[operation="add", value="scaletempo=stride=8:overlap=1:search=10:scale=%3%0.4:speed=pitch"]
[  19.803][v][user_filter_wrapper] Setting option 'stride' = '8' (flags = 0)
[  19.803][v][user_filter_wrapper] Setting option 'overlap' = '1' (flags = 0)
[  19.803][v][user_filter_wrapper] Setting option 'search' = '10' (flags = 0)
[  19.803][v][user_filter_wrapper] Setting option 'scale' = '0.4' (flags = 0)
[  19.803][v][user_filter_wrapper] Setting option 'speed' = 'pitch' (flags = 0)
[  19.803][v][af] User filter list:
[  19.803][v][af]   scaletempo (scaletempo.00)
[  21.059][d][cplayer] Run command: af, flags=64, args=[operation="add", value="scaletempo=stride=8:overlap=1:search=10:scale=2:speed=pitch"]
[  21.059][v][user_filter_wrapper] Setting option 'stride' = '8' (flags = 0)
[  21.059][v][user_filter_wrapper] Setting option 'overlap' = '1' (flags = 0)
[  21.059][v][user_filter_wrapper] Setting option 'search' = '10' (flags = 0)
[  21.059][v][user_filter_wrapper] Setting option 'scale' = '2' (flags = 0)
[  21.059][v][user_filter_wrapper] Setting option 'speed' = 'pitch' (flags = 0)
[  21.059][v][af] User filter list:
[  21.059][v][af]   scaletempo (scaletempo.00)
[  21.059][v][af]   scaletempo (scaletempo.01)
[  29.122][d][cplayer] Run command: af, flags=64, args=[operation="remove", value="scaletempo=overlap=1:scale=%3%0.4:stride=8:speed=pitch:search=10"]
[  29.122][v][af] User filter list:
[  29.123][v][af]   scaletempo (scaletempo.00)
[  29.123][v][af]   scaletempo (scaletempo.01)
[  32.286][d][cplayer] Run command: af, flags=64, args=[operation="remove", value="scaletempo=overlap=1:scale=2:stride=8:speed=pitch:search=10"]
[  32.286][v][af] User filter list:
[  32.286][v][af]   scaletempo (scaletempo.00)
[  32.286][v][af]   scaletempo (scaletempo.01)
```
</details>

### Sample files
Should not be needed. Any file with audio should suffice.

**Comment by avih** [comment]
Can you give a concrete example of a sequence which:
1. adds a filter with more than one param (which command you use, which exact arguments and types).
2. the resulting structure (e.g. as a JSON string) when you read the property.
3. how you call af "remove" and with which exact argument (JSON/string/whatever). Are you constructing a string? how? show us the string.

Also it's documented that the filters can have an arbitrary `@name:` label, which should make it to target specific filters, e.g. for removal.

**Comment by low-batt** [comment]
The issue being reported here is that according to the mpv documentation mpv can't be relied upon to work properly in this case. The issue comes down to this one line in  [client.h](https://github.com/mpv-player/mpv/blob/c72b897e9cb60a3dd4a4fd35442ba21ea7ef6163/libmpv/client.h#L815):
```text
*  The keys are in random order. The only guarantee is that keys[N] belongs
```

I can show the examples requested, however they show mpv working. The examples work because contrary to the above statement the keys are not returned by mpv in random order. The order matches the order of filter arguments in the filter. But the above documentation implies that is just luck.

The runtime problem occurs because IINA obeys that line from the mpv documentation. IINA stores `MPV_FORMAT_NODE_MAP` key-value pairs in a Swift collection with unpredictable ordering. So when IINA forms a string from its collection the filter arguments are in random order, just like mpv documentation says you should expect from `MPV_FORMAT_NODE_MAP`.

I can fix IINA by mapping  `MPV_FORMAT_NODE_MAP` to an ordered collection. But developers reviewing such a change would point out it is wrong as the mpv documentation clearly says `MPV_FORMAT_NODE_MAP` are not ordered so we should not be assuming it is ordered.

If you do want runtime examples I'm happy to supply them. But they show mpv working because contrary to the documented behavior the keys in the `MPV_FORMAT_NODE_MAP` are ordered.

So can clients rely upon the order of keys in a `MPV_FORMAT_NODE_MAP`? Is the mpv documentation incorrect?

**Comment by low-batt** [comment]
The clip from the mpv log above shows the runtime failure. Here IINA is adding one of the filters:
```text
[  21.059][d][cplayer] Run command: af, flags=64, args=[operation="add", value="scaletempo=stride=8:overlap=1:search=10:scale=2:speed=pitch"]
```

Here it tries to remove the filter and remove does not find the filter because the order of arguments does not match:
```text
[  32.286][d][cplayer] Run command: af, flags=64, args=[operation="remove", value="scaletempo=overlap=1:scale=2:stride=8:speed=pitch:search=10"]
[  32.286][v][af] User filter list:
[  32.286][v][af]   scaletempo (scaletempo.00)
[  32.286][v][af]   scaletempo (scaletempo.01)
```

The order of filter arguments changed because IINA obtained the filter list using `mpv_get_property` and IINA's general `mpv_node` parser treated the `MPV_FORMAT_NODE_MAP` as having random keys as per mpv documentation.

This can all be blamed on IINA as long as that one line of mpv documentation about keys in a `MPV_FORMAT_NODE_MAP` being in random order is wrong. With that very clear statement about keys being in random order I am reluctant to change IINA to blatantly ignore the mpv documentation and assume a `MPV_FORMAT_NODE_MAP` is ordered.

**Comment by avih** [comment]
>  can fix IINA by mapping MPV_FORMAT_NODE_MAP to an ordered collection

You can do whatever you want, but if it's logically a map then you can't rely on it appearing at the same order later at an MPV_FORMAT_NODE value.

> The order matches the order of filter arguments in the filter. But the above documentation implies that is just luck.

Technically it's not purely luck, but I assume that _logically_ it is a map, because the same parameter name can appear at most once, and the order doesn't affect the behavior of the filter. These are guesses - I'm not familiar with the filters code nor its representation.

So assuming that the af "params" it is logically a map, you only want the order so that you can target/identify a specific filter, e.g. for removal.

However, even if it was ordered, it's guaranteed to not be enough in general, because you can have two identical filters (same name/params/order/etc), and the filter data alone is simply not enough to identify one of them uniquely.

Which is why you can add an arbitrary and unique `@name` label to every filter, and later use this label to target a specific filter unambiguously.

It's also documented that you can remove a filter by index ("del"), even if it's deprecated. That would also allow to target the exact filter you need.

Another option which I know works (at least when I tried - I don't know enough to say whether it's fficially supported or not), is to read the "af" property as MPV_FORMAT_NODE, "edit" it (remove items, etc), and set it back using MPV_FORMAT_NODE.

You're getting stuck on the fact that the params order is sufficient in your use case to identify a filter uniquely, and forget that it's not sufficient in general, which is why you shouldn't rely on it to identify a filter.

The best way to ID a filter which I can tell is to use a label.

**Comment by avih** [comment]
Consider this (silly) sequence of commands:
```
af add lavfi=loudnorm
af add lavfi=[bass=g=10]
af add lavfi=loudnorm
af add lavfi=[bass=g=10]
```

the two "loudnorm" filters are without params - so a params order will not help identify one of them uniquely, and both the "bass" filters have one (same) param, so the order will not help here either.

You simply cannot rely on the params order in general to identify a specific filter. Even if you read them as MPV_FORMAT_NODE they will be identical. The only thing to identify one or the other in these pairs is their position at the filter chain.

Or a label, like so:
```
af add @ln1:lavfi=loudnorm
af add @bass1:lavfi=[bass=g=10]
af add @ln2:lavfi=loudnorm
af add @bass1:lavfi=[bass=g=10]
```

And then you can remove a specific filter by lagel, e.g. `af remove @bass2`.

**Comment by low-batt** [comment]
Thanks! That answer is very helpful. This issue is all about my confusion over why `mpv_get_property` would use an unordered container to return filter arguments if argument order is important, which the documentation of the remove command indicates is considered. With the tests I ran always returning key-value pairs in order I was beginning to question the definition of `MPV_FORMAT_NODE_MAP` as being unordered.

I really appreciate you taking the time to explain the filter behavior and confirm `MPV_FORMAT_NODE_MAP` must not be considered ordered.

**Comment by avih** [comment]
> This issue is all about my confusion over why `mpv_get_property` would use an unordered container to return filter arguments if argument order is important, which the documentation of the remove command indicates is considered

The documentation doesn't say that mpv can show you in which order the arguments were given (though it probably can if you read it as a string). It only says that if you use the same order then it will match.

You can keep a record of how you added the filter so that you can use it again later.

But this will not solve your IIANA issue where two identical filters are added and you want to remove a specific one of them.

**Comment by low-batt** [comment]
Yes, the documentation is silent on how the proper way to obtain filter arguments in order, hence my request for clarification.

By the way, I am not a member of the IINA development team. I am an IINA user that has been investigating IINA issues and posting proposed solutions to help out the busy development team. Thus my dumb newbie questions.

I've not had a chance yet to go back and investigate a proper way to fix the IINA defect. IINA does not restrict use of mpv features, so it does not force you to set filters only through it. You can set `input-ipc-server` in IINA's advanced settings and then establish filters "behind IINA's back" by sending commands directly to mpv. IINA's filter window must then display them and allow you to delete them. Changing IINA to remember the string used to add a filter would not cover such cases.

IINA knows the position within the list of filters of the filter to be deleted. Since mpv allows you to write a value for the `af` and `vf` properties I'm thinking IINA could get the property value, remove the filter to be deleted from the array based on index, and then write the property value. Maybe something like that.

I know I'm repeating myself, but this newbie really appreciates you taking the time to redirect me from the wrong path I was heading down. Thank you again.
