### ISSUE TITLE
gpu-next: `--sharpen` is not supported (has no effect)

### ISSUE THREAD

**Issue by MoSal** [mpv-player/mpv#9845]
### Important Information

Provide following Information:
- mpv version

| repo | commit |
|:----:|:----:|
| mpv | 0197729949491a65c4c10dba673dbb9c8af04c67 | 
| libplacebo | aff39f522760376c7b532cde6a68560e5e987ff1 |

### Reproduction steps

`--sharpen=<non-zero value>`

**Comment by hooke007** [comment]
> (Only for --vo=gpu)

It's clear in the doc.

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/commit/a73e5cdbed417c554244dda403412d57cba12e8d

**Comment by hooke007** [comment]
It is also clear that hassn won't implement it which was mentioned in the commit message.

**Comment by MoSal** [comment]
Fair enough.

I would close this myself, but since the parameter is still not adjustable at run-time if a shader is used, this is not really a solved issue.

**Comment by NSQY** [comment]
https://github.com/mpv-player/mpv/issues/9387

**Comment by haasn** [comment]
I still plan on adding runtime adjustable arbitrary parameters to `vo_gpu_next` shaders, which will solve this permanently.

**Comment by MoSal** [comment]
Got it.

Closing.
