### ISSUE TITLE
How can I make files that are logged not be duplicated?

### ISSUE THREAD

**Issue by Kayizoku** [mpv-player/mpv#9847]
I am using a script and was wondering how to not add duplicates to log files if the file already exists. I wish it to be overwritten or added to the same element that already exists in the log. Basically, if it finds that the log entry matches, the latest entry due for logging, it should not be duplicated.

This is the code: 
https://github.com/hakonw/mpvtimelogger/blob/master/timelogger.lua

**Comment by Kayizoku** [comment]
> I don't understand how this question is related to mpv.
> 
> Is there some info which mpv has but you don't know how to get?

I see, my bad. I thought I could ask questions as long as it's linked to MPV.  In that case, I do have another question and that's how to calculate the total duration of an entire playlist? Is there any API endpoint or easy way to do it?

**Comment by avih** [comment]
> how to calculate the total duration of an entire playlist? Is there any API endpoint or easy way to do it?

There's no such API, and mpv doesn't know it either. The most it knows is the length of the currently playing playlist entry - and even that is not always known (e.g. a live stream which can keep going forever).

**Comment by avih** [comment]
> I see, my bad. I thought I could ask questions as long as it's linked to MPV in some ways

I think you could look for some help in lua programming forums. You can also try some lua IRC channels, or the mpv IRC channel, but as far as I can tell your problem a general programming/filesystem question and not related to mpv. Maybe someone could help if they understood exactly what the problem is (I didn't understand).
