### ISSUE TITLE
Lose focus frequently in fullscreen mode

### ISSUE THREAD

**Issue by NeilTohno** [mpv-player/mpv#9852]
Recently, I open video files with mpv player and press "f" key to enable full-screen mode, after sometime, the program (mpv player) lose focus, I can't use shortcut keys until I click it with mouse.

I found no error in mpv's log file.
Thanks.

### Important Information
mpv version
mpv-x86_64-20220206-git-0197729
Source of the mpv binary: Windows builds by shinchiro (releases and git) | https://sourceforge.net/projects/mpv-player-windows/files

Windows Version
win10 21H2 64bit
2950x cpu , vega 64

**Comment by avih** [comment]
mpv doesn't have code which can result in loss of focus, and it doesn't on its own run other applications which can steal the focus, so losing focus is not something which mpv does.

Even if it had code which can lose focus, you didn't provide enough info to analyze the issue (do feel free to add it, maybe someone could identify something relevant):
- What's "frequently" and "after some time"? 1 second? a minute? an hour? a month?
- Does it only happen in fullscreen?
- Did you try with `--no-config` like the issue template suggest?
- A log is missing, and typically it's critical to analyze issues, even if it doesn't contain any error.

**Comment by NeilTohno** [comment]
Thanks.

> * What's "frequently" and "after som.e time"? 1 second? a minute? an hour? a month?

I was edited the issue, "frequently" means many times I launch the mpv player.

> * Does it only happen in fullscreen?

Yes, only happen in fullscreen.

> * Does it only happen with mpv?

I don't known, but I test many program (Games and Video player) , I don't found same problem.

> * Did you try with `--no-config` like the issue template suggest?

--no-config ?
I never use mpv player with such parameter, I will test that parameter later.

> * A full log (with the issue happening) is missing, and typically it's critical to analyze issues, even if it doesn't contain any error.

I will upload next time.

**Comment by avih** [comment]
Do try what I wrote about trying an older mpv version which didn't have this issue in the past.

**Comment by NeilTohno** [comment]
> Do try what I wrote about trying an older mpv version which didn't have this issue in the past.

Because I need time to test those old version.

**Comment by NeilTohno** [comment]
> mpv doesn't have code which can result in loss of focus, and it doesn't on its own run other applications which can steal the focus, so losing focus is not something which mpv does.


Sorry, I don't found the regular pattern.

[mpv.log](https://github.com/mpv-player/mpv/files/8031867/mpv.zip)


[portable_config.zip](https://github.com/mpv-player/mpv/files/8031869/portable_config.zip)

I will use the parameter "d3d11-exclusive-fs=yes" instead of "d3d11-flip=yes" ,
Thanks.
