### ISSUE TITLE
[BUG] Flicker screen happen when enter and exit exclusive full-screen mode

### ISSUE THREAD

**Issue by NeilTohno** [mpv-player/mpv#9853]
**I found no error in mpv's log file.**
Thanks.

### Important Information
mpv version
mpv-x86_64-20220206-git-0197729
Source of the mpv binary: Windows builds by shinchiro (releases and git) | https://sourceforge.net/projects/mpv-player-windows/files

Windows Version
win10 21H2 64bit
2950x cpu , vega 64
Acer VG271U P monitor  2k 144Hz

### Reproduction steps

I test mpv with --no-config, get the same issue.

[MPV.exe --d3d11-exclusive-fs=yes --no-config "Y:\TT3\T1.mp4"]
[mpv1.zip](https://github.com/mpv-player/mpv/files/8032352/mpv1.zip)

### Frequency
Always. I test old version, I found same issue.

### 
I  took a video with smartphone.
In this video, I press "f" key to enter exclusive full-screen mode, success, and I press "f" key again to exit exclusive full-screen mode, failed, and flicker screen happens.
[V_20220209_192048_ES6.zip](https://github.com/mpv-player/mpv/files/8032269/V_20220209_192048_ES6.zip)

**Comment by ValZapod** [comment]
> --d3d11-exclusive-fs=yes

That will only work if you wull disable fullscreen optimisation on mpv executable in windows. Otherwise that makes no effect as you can see from mpv -v debug

You also need to see black screen for a moment.

**Comment by NeilTohno** [comment]
> That will only work if you will disable fullscreen optimisation on mpv executable in windows. Otherwise that makes no effect as you can see from mpv -v debug

I know "disable fullscreen optimisation", I do disable fullscreen optimisation  for every DirectX program.


> There is no bug.
> 
> Also on LG C9 that becasue of edid selects 120 fps 4:2:0 resolution which does not work on lg c9 in hdmi 2.0b, a bug of EDID and or LG C9 chipset. A known bug...

My computer is connected to monitor through a DisplayPort 1.4 Cable.

**Comment by ValZapod** [comment]
> for every DirectX program.

Even for mpv?

**Comment by NeilTohno** [comment]
> > for every DirectX program.
> 
> Even for mpv?

Yes.
I don't know what to say,  after I read those news that "Fullscreen optimisation" could causes problems in some games, I decided not to never use this feature.

https://www.reddit.com/r/Amd/comments/issh9o/enabling_disable_fullscreen_optimizations_fixed/
https://mspoweruser.com/tip-fullscreen-optimizations-might-hurting-game-performance-windows-10/

**Comment by ValZapod** [comment]
Disabling game bar doesn't disable full screen opt. systemwide, just checked. What is that even. You need to disable it per exe and it only works since quite new version of windows 10.

**Comment by ValZapod** [comment]
So did you try to disable it in mpv.exe properties?

**Comment by NeilTohno** [comment]
> Even for mpv?

I did it before you speak that. 
 (｀・ω・´)

**Comment by ValZapod** [comment]
Behavòur must change between the two. Whay do you observe?

**Comment by garoto** [comment]
Switching player mode between --fullscreen on and off is jarring for the longest time on my Win 8.1. `--gpu-api` never really mattered, it is less jarring with `d3d11`.

**Comment by ValZapod** [comment]
> Switching player --fullscreen mode on and off is jarring

We are not talking about this. We are talking about exclusive fullscreen. That will only work if you disable new fullscreen mode.

**Comment by NeilTohno** [comment]
> You need to disable it per exe and it only works since quite new version of windows 10. 

I did it.
If you must kown.

[![sZHtf.th.png](https://imglink.win/image/2022/04/16/sZHtf.th.png)](https://imglink.org/image/sZHtf)

**Comment by ValZapod** [comment]
So how does it change the behaviour?

**Comment by NeilTohno** [comment]
> So how does it change the behaviour?

Nothing happened, the problem remains unsolved.

**Comment by kasper93** [comment]
> This happens to all programs on Windows which enter exclusive fullscreen mode. There is nothing can be done from mpv side. Just don't use exclusive fullscreen.

Correct.
