### ISSUE TITLE
how can i see the info of a file after i added subtitles.

### ISSUE THREAD

**Issue by bladem2003** [mpv-player/mpv#9854]
how can i see the info of a file after i added subtitles.
I want what is displayed at startup in the terminal. 

 (+) Video --vid=1 (mpeg2video 720x576 25.000fps)
 (+) Audio --aid=1 --alang=nl (ac3 6ch 48000Hz)
     Audio --aid=2 --alang=de (ac3 6ch 48000Hz)
     Audio --aid=3 --alang=en (ac3 6ch 48000Hz)
     Subs  --sid=1 --slang=en (dvd_subtitle)
     Subs  --sid=2 --slang=de (dvd_subtitle)
     Subs  --sid=3 --slang=nl (dvd_subtitle)
     Subs  --sid=4 --slang=de (dvd_subtitle)

**Comment by szero** [comment]
check out `ffprobe` program, it gives you information about different streams in a video file
