### ISSUE TITLE
Window transparency is limited to 4 discrete values on wayland

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#9862]
### Important Information
```
mpv 0.34.0-198-gbc9805c71a Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sat Feb 12 10:01:11 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```
local build from master on arch linux, using an intel GPU with mesa.
The same issue can be reproduced on wlroots-compositors (wayfire, sway), weston and kwin (as confirmed by @Counterpillow).

Not reproducible on X11 according to @guidocella 

### Reproduction steps

run `mpv --no-config --vo=gpu --idle --force-window --alpha=yes`. Using the console, change the value from 0/0.0 to 0/1.0 in increments of 0.1 for the alpha.

### Expected behavior

The transparency of the window varies gradually from transparent to opaque, by increments of 10%.

### Actual behavior

Only 4 distinct alpha levels can be observed, with the first being fully transparent and the last fully opaque, the transition values being around 0.17/0.5/0.83.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/8053253/log.txt)

edit: this is also probably the cause of the behavior observed here https://github.com/mpv-player/mpv/pull/9621#issuecomment-998081600

**Comment by Dudemanguy** [comment]
Same thing happens here on amdgpu. On X11, this doesn't work at all for me (i.e. it's always completely opaque). I think that mesa bug is still open on x11 so that's probably it in that case.

**Comment by guidocella** [comment]
On X11 background transparency with mesa depends on https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9989, but with Nvidia proprietary drivers it already works and you can see the opacity change for each 0.1 step.

**Comment by occivink** [comment]
This diff 'fixes' the issue, but I don't know about the implications of this change
```diff
diff --git a/video/out/opengl/egl_helpers.c b/video/out/opengl/egl_helpers.c
index b3e11c6f43..3bf6239e41 100644
--- a/video/out/opengl/egl_helpers.c
+++ b/video/out/opengl/egl_helpers.c
@@ -132,7 +132,7 @@ static bool create_context(struct ra_ctx *ctx, EGLDisplay display,
         EGL_RED_SIZE, 8,
         EGL_GREEN_SIZE, 8,
         EGL_BLUE_SIZE, 8,
-        EGL_ALPHA_SIZE, ctx->opts.want_alpha ? 1 : 0,
+        EGL_ALPHA_SIZE, ctx->opts.want_alpha ? 8 : 0,
         EGL_RENDERABLE_TYPE, rend,
         EGL_NONE
     };
```

**Comment by guidocella** [comment]
alpha behaves the same on X11 + Nvidia with that diff for what it's worth.
