### ISSUE TITLE
Segfault on undefined pixdesc name

### ISSUE THREAD

**Issue by jas-per** [mpv-player/mpv#9865]
### Important Information

Provide following Information:
- mpv git
- raspbian 64 bullseye
- self compiled mpv
- mpv 0.32 last version without this issue
- Sway 1.5
- RPI4 / V3D / Mesa 20.3.5
- using drm instead of wayland worked fine on the same system

### Reproduction steps

`mpv --vo=gpu --gpu-context=wayland video.mp4`

### Expected behavior

mpv starts and plays the video

### Actual behavior

Segfault

### Log file

[mpv.log](https://0x0.st/oX76.log)

[backtrace.txt](https://0x0.st/oX7E.log)

**Comment by jeeb** [comment]
```
0x000000555564002c in mp_imgfmt_get_desc_from_pixdesc (out=0x7fd37fc930, mpfmt=1253) at ../video/img_format.c:431
431	../video/img_format.c: No such file or directory.
#0  0x000000555564002c in mp_imgfmt_get_desc_from_pixdesc (out=0x7fd37fc930, mpfmt=1253) at ../video/img_format.c:431
        fmt = AV_PIX_FMT_SAND64_16
        pd = 0x7ff7a13f78
        desc = 
          {id = 1253, flags = 0, num_planes = 0 '\000', chroma_xs = 0 '\000', chroma_ys = 0 '\000', align_x = 0 '\000', align_y = 0 '\000', bpp = "\000\000\000", xs = "\000\000\000", ys = "\000\000\000", comps = {{plane = 0 '\000', offset = 0 '\000', size = 0 '\000', pad = 0 '\000'}, {plane = 0 '\000', offset = 0 '\000', size = 0 '\000', pad = 0 '\000'}, {plane = 0 '\000', offset = 0 '\000', size = 0 '\000', pad = 0 '\000'}, {plane = 0 '\000', offset = 0 '\000', size = 0 '\000', pad = 0 '\000'}}, endian_shift = 0 '\000'}
        is_ne = <optimized out>
        need_endian = <optimized out>
        desc = 
          {id = <optimized out>, flags = <optimized out>, num_planes = <optimized out>, chroma_xs = <optimized out>, chroma_ys = <optimized out>, align_x = <optimized out>, align_y = <optimized out>, bpp = {<optimized out>, <optimized out>, <optimized out>, <optimized out>}, xs = {<optimized out>, <optimized out>, <optimized out>, <optimized out>}, ys = {<optimized out>, <optimized out>, <optimized out>, <optimized out>}, comps = {{plane = <optimized out>, offset = <optimized out>, size = <optimized out>, pad = <optimized out>}, {plane = <optimized out>, offset = <optimized out>, size = <optimized out>, pad = <optimized out>}, {plane = <optimized out>, offset = <optimized out>, size = <optimized out>, pad = <optimized out>}, {plane = <optimized out>, offset = <optimized out>, size = <optimized out>, pad = <optimized out>}}, endian_shift = <optimized out>}
        is_ba = <optimized out>
```

So we have `AV_PIX_FMT_SAND64_16` which seems to be a valid pix_fmt for whatever FFmpeg headers those are, but it also is not a thing in upstream FFmpeg master. Thus, I can only expect that it was patched in.

And then I will just expect that whomever patched that FFmpeg did not add that pixel format to the list in `libavutil/pixdesc.c`. If you just add a descriptor there for the pixel format, it should fix the issue. My understanding is that each pix_fmt should have a valid descriptor but I'll still check it. At least in master FFmpeg, that is the case.

Hilariously enough, there is a test in FFmpeg in `libavutil/tests/pixdesc.c` checking things but it would only log those as "unused values", not fail. There are also FATE tests for these descriptors, but not sure if that patched FFmpeg would fail them. I would kind of hope it would :P .

**Comment by jas-per** [comment]
ok suspected something like that - you mentioned the patched ffmpeg as the culprit so I tried hwdec=v4l2m2m instead of the proprietary hwdec=mmal and this kinda works

the problem here is that v4l2m2m drops frames on high bitrates so mmal is still needed for the time being. since v4l2m2m is the future I doubt that the patched ffmpeg will get any fixes at all - no working hw-acceleration for rpi4 until v4l2m2m will be up to the task I guess

its a bit of a shame, because rpi foundation already fucked up getting the only working hw-accel besides the dreadful omxplayer out to the people on older raspberries - mpv used to work beautifully with lots of rpi specific code but the rpi guys failed for years to compile this support into mpv on their distro. no specific code needed for rpi4 output this time around but this little bug will stop people from using mpv again

anyways will try to get that forked ffmpeg fixed, thanks for having a closer look @jeeb

**Comment by cyph84** [comment]
@jas-per FWIW, the "official" video player is VLC. It gets all the love for hwaccel'ed video decode and output. VLC's mmal_xsplitter is even has decent integration into the windowing system.

Problem with v4l2m2m is the video output portion is not hwaccel'ed and will unfortunately stutter on higher-res videos.
