### ISSUE TITLE
How to encode textures in shaders?

### ISSUE THREAD

**Issue by agyild** [mpv-player/mpv#9866]
The manual states that:

> Following the metadata is a string of bytes in hexadecimal notation that define the raw texture data, corresponding to the format specified by FORMAT, on a single line with no extra whitespace.

However, I would appreciate a more detailed instruction. Is it a .dds texture file in hex (if so, can we also use something more accessible such as .png)? Is it color values in serialized hexadecimal form? How does the texture format affect it? What is it exactly?

Let's take this simple, stupid LUT for instance:

```glsl
vec4(1.0, 1.0, 1.0, 1.0), vec4(0.0, 0.0, 0.0, 1.0), vec4(1.0, 1.0, 1.0, 1.0)
vec4(1.0, 0.0, 0.0, 1.0), vec4(0.0, 1.0, 0.0, 1.0), vec4(0.0, 0.0, 1.0, 1.0)
vec4(0.0, 0.0, 0.0, 1.0), vec4(1.0, 1.0, 1.0, 1.0), vec4(0.0, 0.0, 0.0, 1.0)
```

How would I encode it as a texture?

**Comment by haasn** [comment]
It is the raw texture data, in the encoding appropriate to the texture format. See [here](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#formats-definition) for a basic explanation of the memory layout and [here](https://www.khronos.org/registry/DataFormat/specs/1.3/dataformat.1.3.html#_bit_pattern_interpretation_and_emphasis_samples_emphasis) for a deep dive.
