### ISSUE TITLE
packing the appimage format file #942

### ISSUE THREAD

**Issue by newyorkthink** [mpv-player/mpv#9867]
can your packing the appimage file.
i don't like to sudo apt-get install it

i like use appimage, it is simple to one click.

![image](https://user-images.githubusercontent.com/87791643/153734274-313b0ec1-7e30-488d-81fa-faf929305e2a.png)

**Comment by CounterPillow** [comment]
No, we've already discussed this and the solution is to use flatpak instead.

**Comment by newyorkthink** [comment]
> No, we've already discussed this and the solution is to use flatpak instead.

no one use flatpak, it is obsolete may.

**Comment by newyorkthink** [comment]
> No, we've already discussed this and the solution is to use flatpak instead.

you answer, i think will use vlc player instead mpv player.

**Comment by CounterPillow** [comment]
ok bye

**Comment by newyorkthink** [comment]
> ok bye

:) bye
