### ISSUE TITLE
Let screensaver run (or screen off) if media file has video disabled with --player-operation-mode=pseudo-gui

### ISSUE THREAD

**Issue by Totorrr** [mpv-player/mpv#9869]
### Important Information

Provide following Information:
- mpv version 0.34.0
- Linux Debian 10.11 (with backports)
- Source of the mpv binary (Debian re-packaging with github sources)
- If known which version of mpv introduced the problem : no
- Window Manager and version : cinnamon 3.8
- GPU driver and version : N/A
- Possible screenshot or video of visual glitches : N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Run `mpv --player-operation-mode=pseudo-gui video-file.mp4`

Then, disable the video using the `_` key from keyboard. 

Then wait for screensaver to kick in, or for screen to turn off (you can use `xset dpms force off` on a console to speed things up)

### Expected behavior

The screen saver (or screen turning off) would kick in an stay as is, for as long as the user doesn't use the computer. 

### Actual behavior

After a few seconds, the screen turns on again. `mpv` is keeping the screen on forcefully. 

### Log file

(maybe later, but may not be needed, as it is easily reproductible)

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

(not needed)

**Comment by Totorrr** [comment]
@avih Thanks for answering. 

While reading you, I understand you prefer not to change the behaviour because it is subjective, and there is an easy way to make it work as I prefer using the short lua script. You also think a reason for the current behaviour may be that the OSC could be used from the window. I realise I did no share my motivations, to give you some meaning behind what I'm asking. 

I also think there is a power/battery saving opportunity with allowing screen saving in the case where there is a window without a video. And the behaviour I suggest, set as a default, could save non-negligible energy (when spread over several devices), without needing customisation of `mpv` using the lua script (people could still use, conversely, a script to keep the screen on). This energy saving would allow or more battery autonomy on portable devices, and globally, less energy waste I believe (which, given the ecological context, would be desirable). 

How do you consider my request now, with this new meaning?

Thanks,

PS: I did specifically open a graphical window with `--player-operation-mode=pseudo-gui` in the description to allow easy reproduction of the behaviour, but mostly, my desktop environment is doing this by default when I start a audio/video file from the file browser (in order to avoid a no window & no control situation, like when playing an audio file). This is a pretty common use case & useful behaviour IMHO.

**Comment by avih** [comment]
I'm sure you have a valid reason, I just said it's subjective.

Also, think about it this way: if we change it to behave like you want, then no script would be able to make it behave like the current default, while with the current default a 3 LOC script can do what you prefer. Think of it as a configuration value, it might make you feel better about it.

**Comment by Totorrr** [comment]
> I just said it's subjective.

Sure, for everyone even, right? ;)

> if we change it to behave like you want, then no mpv script would be able to make it behave like the current default

Well, I did not know this. Thanks. :ok_hand: 

> Also, personally I do prefer the current behavior, because I'm using HDMI audio, and if the screen idles then it also kills the audio, so when I have an mpv window open _and_ it plays - I don't want screen idle to kick in.

Well, now, this use case makes much sense for me. Surely I get why you would prefer the current behaviour. Let's keep it like this then, and for those of us who have the other preference (and are looking at github issues ;)) we have the 3 lines script you shared. 

Cheers
