### ISSUE TITLE
mpv does not prevent blank screen while watching a video

### ISSUE THREAD

**Issue by All3xJ** [mpv-player/mpv#9871]
### Important Information

Provide following Information:
```
- $ mpv --version
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```
- Linux Distribution and Version: ArchLinux. Gnome 41.3

### Expected behavior
It should inhibit blank screen if watching a video

### Actual behavior
Screen blank

**Comment by Dudemanguy** [comment]
There is no bug here. mpv uses idle-inhibit to prevent screen blanking. Gnome still does not support this, so there is nothing we can do.

**Comment by All3xJ** [comment]
If you have this problem, to fix you have to: https://wiki.archlinux.org/title/Mpv#GNOME_Blank_screen_(Wayland)
