### ISSUE TITLE
LD_PRELOAD crashes mpv because of compatibility issue.

### ISSUE THREAD

**Issue by Zesko** [mpv-player/mpv#9875]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1
```

- Linux Distribution and Version 
```
Manjaro the latest version (based on Arch Linux)
Kernel: 5.16.7-1-MANJARO x86_64 
```

- GPU driver and version
```
It does not matter with this issue. But only the environment variable is the issue.
```

### Reproduction steps

1. Install Vivaldi the latest version in Arch based distro, e.g. Manjaro
2. Make mpv or smplayer as default player without any custom config of mpv.
3. Download any video mp4. e.g https://help.vivaldi.com/wp-content/uploads/2017/12/vivaldi_success.mp4
4. Open this video mp4 in the Download panel of Vivaldi, but mpv does not start.
5. Let you test to run `LD_PRELOAD=/opt/vivaldi/lib/libffmpeg.so mpv --no-config ~/Downloads/vivaldi_success.mp4`
```
libavutil: 56.70.100 -> 57.7.100 # Error, because both versions are not compatible
fish: Job 1, 'LD_PRELOAD=/opt/vivaldi/lib/lib…' terminated by signal SIGABRT (Abort)
```
6. Run it without LD_PRELOAD, mpv works fine.

I know so far the issue is related to LD_PRELOAD of Vivaldi that crashes mpv when opening mp4 in its own Download panel.

Vivaldi forum: https://forum.vivaldi.net/topic/66195/video-file-cannot-be-opened-in-vivaldi-downloads-by-clicking-mp4/46

There are possible ways to fix:
- Is there way to disable LD_PRELOAD for mpv? Or can mpv ignore LD_PRELOAD? 
- How can I define ffmpeg path for mpv for `alias mpv='mpv --loadffmpeg xxx '` that will overwrite or ignore LD_PRELOAD ?

Thanks!

**Comment by avih** [comment]
> * Is there way to disable LD_PRELOAD for mpv? Or can mpv ignore LD_PRELOAD?
> * How can I define ffmpeg path for mpv for `alias mpv='mpv --loadffmpeg xxx '` that will overwrite or ignore LD_PRELOAD ?

Not an mpv issue, and mpv doesn't support these things.

If you want to avoid depending on a shared lib, link mpv statically with whatever you want.

If you get this or similar issues with the default packages from your package manager, then you should report it to them.

If you mess with custom LD_PRELOAD and other shenanigans, then it's likely that even them will refuse to support you.

You're pretty much on your own with such things.

**Comment by avih** [comment]
> * Is there way to disable LD_PRELOAD for mpv? Or can mpv ignore LD_PRELOAD?

mpv doesn't care about it. The system loader does.

If you run the `sh` command `unset -v LD_PRELOAD` right before you run mpv then I presume it will be ignored. But again, this can really result in a mess, and you're pretty much on your own.

**Comment by Zesko** [comment]
> If you mess with custom LD_PRELOAD and other shenanigans
> If you run the sh command unset -v LD_PRELOAD right before you run mpv then I presume it will be ignored. But again, this can really result in a mess, and you're pretty much on your own.

No, I did not define LD_PRELOAD. There is no LD_PRELOAD in my own by default after Linux installation. But only Vivaldi calls mpv with its own LD_PRELOAD with mpv, not me. That means Vivaldi breaks mpv.

**Comment by Zesko** [comment]
Yes, I know `LD_PRELOAD="" mpv ... ` works, but I set alias `alias mpv='LD_PRELOAD="" mpv' ` in /etc/profile.d/00-alias.sh, then reboot.
Nevertheless, no luck. Vivaldi ignores this alias and calls mpv with its own LD_PRELOAD in vivaldi's environment variables.

**Comment by Zesko** [comment]
> Not an mpv issue, and mpv doesn't support these things.

But there is one thing I don't understand, why can LD_PRELOAD strongly influence mpv that crashes, that means mpv uses this LD_PRELOAD in backend too?

**Comment by avih** [comment]
> That means Vivaldi breaks mpv.

This is between Vivaldi and your OS. mpv is not part of it, even if it's affected by such things.

> `alias mpv='LD_PRELOAD="" mpv'` ... Vivaldi ignores this alias...

You don't need the double quotes, and I presume that vivaldy runs mpv directly and without applying aliases.

Again, this is outside the scope of mpv, but what you should do is saving this script someplace, e.g. as `mpv-no-ld`:
```sh
#!/bin/sh

LD_PRELOAD= mpv "$@"
```

Then `chmod +x path/to/mpv-no-ld`, and then somehow make Vivaldi execute this script as the default player instead of mpv directly.

**Comment by avih** [comment]
> why can LD_PRELOAD strongly influence mpv that crashes

I don't know, you didn't provide any log or terminal output.

> that means mpv uses this LD_PRELOAD in backend too?

No. It's a system thing. If you change `$PATH` then it affects where a program is loaded from. It doesn't mean that this program uses `$PATH` - the system does. Same goes with `LD_PRELOAD` - the system loader uses it, and when mpv loads a library then the system loader decides where to look for it.

**Comment by Zesko** [comment]
> Vivaldi execute this script as the default player instead of mpv directly.

I do not know how can Vivaldi execute this script when clicking mp4 in its own Download panel (GUI of Vivaldi).

I checked `mplayer` that has the same issue with LD_PRELOAD.
I checked `mpv` and `vivaldi` in new Ubuntu in VM, new Manjaro in other VM too.
Both have the same issue.

**Comment by avih** [comment]
This is as far as my help goes. For further help you should try Manjaro or Vivaldi help at their forums/IRC/whatever.

You can refer them to this issue if you want.

**Comment by Zesko** [comment]
Okay, I believe that UNIX system uses LD_PRELOAD as standard environment variable for all. That means all Linux distros and Mac OS too.

>  For further help you should try Manjaro or Vivaldi help at their forums/IRC/whatever.
Yes, I reported the issue of Vivaldi only. Vivaldi should not use this environment variable.

**Comment by Zesko** [comment]
Here: https://forum.vivaldi.net/topic/66195/video-file-cannot-be-opened-in-vivaldi-downloads-by-clicking-mp4/54

**Comment by Zesko** [comment]
I do not think Vivaldi want to fix it.

Theoretically, you can add a new option `--ignore-ld` that will set `LD_PRELOAD=""` in the first initialization of `mpv`. I mean that is new feature, not bug.

**Comment by avih** [comment]
> Theoretically, you can add a new option `--ignore-ld` that will set `LD_PRELOAD=""`

Not going to happen. The script I posted earlier should do that for you if you insist. But I can't help you in configuring Vivaldi or your system to execute this script instead of mpv itself as a default media handler.

**Comment by Zesko** [comment]
I did a trick.

1. Change the name of `mpv` as the binary file: `sudo mv /usr/bin/mpv /usr/bin/real_mpv`
2. Created a new script for  `mpv` in the same directory `/usr/bin/mpv`
```
#!/usr/bin/env bash 

unset -v LD_PRELOAD 
/usr/bin/real_mpv "$@"
```
3. `sudo chmod +x /usr/bin/mpv`
4.  Done. 

`mpv` works fine with Vivaldi.

**Comment by guidocella** [comment]
If you place the script in `~/.local/bin/mpv` or `/usr/local/bin/mpv` it won't be overwritten by updates.

**Comment by Zesko** [comment]
Nevertheless, there is the third party media player e.g SMPlayer using mpv from `/usr/bin/mpv`, it can not start with Vivaldi, but only `mpv`works fine.
