### ISSUE TITLE
Make a script that will suggest on which monitor to play video file.

### ISSUE THREAD

**Issue by IlyaIndigo** [mpv-player/mpv#9876]
I want to write a bash script which will 
1 Check which connected monitors are in the system.
2 If there is more than one, then output their list (e.g. via kdialog) and after selection run the video file on the selected monitor.
 
Problems.
1 mpv offers 2 options to control the output to the monitor "--screen=" and "--screen-name=".
But I can't use "--screen-name=" no matter how correct the xrandr name I would pass, the video always opens on the default screen ignoring this option.
Only the "--screen=" option works.

2 "xrandr --prop" does not show the screen number for the "--screen=" option and they are not listed in ascending order from 0.
[xrandr-prop.txt](https://github.com/mpv-player/mpv/files/8081622/xrandr-prop.txt)
Here is a script that displays the name of the monitor linked to the output but I don't know what screen number they are under.
```
#!/bin/bash
while read -r output hex conn; do
    [[ -z "$conn" ]] && conn=${output%%-*}
    echo "# $output $conn   $(xxd -r -p <<< "$hex")"
done < <(xrandr --prop | awk '
    !/^[ \t]/ {
        if (output && hex) print output, hex, conn
        output=$1
        hex=""
    }
    /ConnectorType:/ {conn=$2}
    /[:.]/ && h {
        sub(/.*000000fc00/, "", hex)
        hex = substr(hex, 0, 26) "0a"
        sub(/0a.*/, "", hex)
        h=0
    }
    h {sub(/[ \t]+/, ""); hex = hex $0}
    /EDID.*:/ {h=1}
    END {if (output && hex) print output, hex, conn}
    ' | sort
)
```
```
# DisplayPort-0 DisplayPort   DELL U2312HM
# DVI-0 DVI   VA249
# HDMI-0 HDMI   Panasonic-TV
```
How do I solve this problem?
Ideally I would be fine with the "--screen-name=" option if it would work.
```
openSUSE Tumbleweed | Xorg | KDE4
mpv 0.34.1+git.20220203T182214.5d31c7310c Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Feb  5 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1
```

**Comment by Dudemanguy** [comment]
`--screen-name` is supposed to work. If it doesn't, it sounds more like you should be opening up a bug report.

**Comment by IlyaIndigo** [comment]
> `--screen-name` is supposed to work. If it doesn't, it sounds more like you should be opening up a bug report.

You have my [xrandr-prop.txt](https://github.com/mpv-player/mpv/files/8081622/xrandr-prop.txt)
Please write a command to playback on the monitor using the correct option name "--screen-name=" for the monitor "DisplayPort-0 DisplayPort DELL U2312HM".

If the result is the same I will open the report.

**Comment by Dudemanguy** [comment]
`mpv --no-config --screen-name=DisplayPort-0 video.mkv` in theory. If the specified screen name can't be found, mpv will print a warning.

**Comment by IlyaIndigo** [comment]
> `mpv --no-config --screen-name=DisplayPort-0 video.mkv` in theory. If the specified screen name can't be found, mpv will print a warning.

/usr/bin/mpv --no-config --fs --screen-name=DisplayPort-0 video.mp4
It opened on the default monitor
```
 (+) Video --vid=1 (*) (h264 1280x720 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
AO: [alsa] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
(Paused) AV: 00:00:05 / 00:15:58 (1%) A-V:  0.000
[input] No key binding found for key 'MBTN_RIGHT_DBL'.
(Paused) AV: 00:00:06 / 00:15:58 (1%) A-V:  0.000
[input] No key binding found for key 'MBTN_RIGHT_DBL'.
(Paused) AV: 00:00:07 / 00:15:58 (1%) A-V:  0.000
[input] No key binding found for key 'MBTN_RIGHT_DBL'.
AV: 00:00:13 / 00:15:58 (1%) A-V:  0.000

Exiting... (Quit)
```.
/usr/bin/mpv --no-config --fs --screen=1 video.mp4
Opened on the desired monitor.

Should I write a separate issue or can this issue be redone in the report?

**Comment by Dudemanguy** [comment]
Just one thing real quick, does it work correctly if you remove `--fs` from the command you're passing there?

**Comment by IlyaIndigo** [comment]
Well.
