### ISSUE TITLE
SRT subtitles not displaying with sub-font-provider=none

### ISSUE THREAD

**Issue by andiandi13** [mpv-player/mpv#9878]
### Important Information

- mpv-x86_64-20220213-git-bc9805c
- Windows 7 x64

When I set sub-font-provider on none, SRT subtitles don't show at all, while ASS are working.

My mpv.conf looks like this if this can help :

![mpvconf](https://user-images.githubusercontent.com/19387072/154329000-48794874-13bc-40bf-876a-48816cbd909f.png)

**Comment by avih** [comment]
It's documented very clearly - it will only use embedded fonts, or configured fonts:
> The none font provider effectively disables system fonts. It will still attempt to use embedded fonts (unless --embeddedfonts=no is set; this is the same behavior as with all other font providers), subfont.ttf if provided, and fonts in the fonts sub-directory if provided.

https://mpv.io/manual/master/#options-sub-font-provider

**Comment by andiandi13** [comment]
> It's documented very clearly - it will only use embedded fonts, or configured fonts:
> 
> > The none font provider effectively disables system fonts. It will still attempt to use embedded fonts (unless --embeddedfonts=no is set; this is the same behavior as with all other font providers), subfont.ttf if provided, and fonts in the fonts sub-directory if provided.
> 
> https://mpv.io/manual/master/#options-sub-font-provider

I read this part, but it doesn't mention SRT subtitles.

But I get it now that you mention it, since SRT subs are displayed through system fonts, it doesn't display anything...
Alright but does it make any sense since SRT subtitles doesn't rely on any particular font ? Woudn't it be legitimate to set an exception for SRT subtitles - or at least - an additional option ? 

I mean, it's not like SRT subs could work with embedded fonts.

**Comment by avih** [comment]
> I mean, it's not like SRT subs could work with embedded fonts.

but it can with your own font, which is what you should have if you disable system fonts...

**Comment by andiandi13** [comment]
> 

Yes that's what I thought, but why MPV doesn't use any of the multiple embedded ttf/otf to display SRT ? Am I missing an option ?

**Comment by avih** [comment]
> Am I missing an option ?

No. It's exactly what you said - srt doesn't use embedded fonts, and combined with the fact that you disbabled system fonts - you need to provide your own font so that srt could display anything.

**Comment by andiandi13** [comment]
> you need to provide your own font so that srt could display anything.

That's my point, how does my SRT subs doesn't use any of these embedded font ?

![2022-02-16 20_17_29-Propriétés](https://user-images.githubusercontent.com/19387072/154339286-272e4224-ecb0-4e0d-9701-4f3c4b3de860.png)

**Comment by avih** [comment]
Just stop. Either don't disable the system fonts, or configure your own fonts instead of the system fonts.

Don't waste our time anymore.

**Comment by avih** [comment]
> I don't know what providing my own font is

It's at the docs I quoted earlier:

> subfont.ttf if provided, and fonts in the fonts sub-directory if provided.

**Comment by andiandi13** [comment]
Ah that's it. The doc talk about libass so I thought it was just an ass option.
Thanks for your help.
