### ISSUE TITLE
How to specify language of a subtitle file loaded in mpv with "--sub-file" command line option?

### ISSUE THREAD

**Issue by fboumol** [mpv-player/mpv#9882]
Let us assume one wants to play a video file using two subtitle files available through http(s). This can be easily done using something like

```
 mpv --sub-file="${urlsub1}" --sub-file="${urlsub2}" "${file}"
```
Is there some way to specify in the command line the languages of each one these files. I am assuming the case that one does not admin the http server (so renaming to ending with "en.srt", etc is not possible).

For the sake of the discussion let us assume the case where "urlsub1" is in english and "urlsub2" is in spanish.

**Comment by dyphire** [comment]
dup https://github.com/mpv-player/mpv/issues/9825

**Comment by fboumol** [comment]
Sorry for not being precise enough to show why this is not a dup.

Another issue is than what I am looking for, if possible, is a command line (choosing the right arguments) such that:
 - when in the configuration file of mpv it appears `slang=eng,en` then the player automatically chooses urlsub1,
 - when in the configuration file of mpv it appears `slang=spa,es` then the player automatically chooses urlsub2,
 - etc

This is the sense I had in mind for specifying the language.

Is this possible?

**Comment by dyphire** [comment]
> Can't be done, unless the sub track itself contains this meta info.

**Comment by dyphire** [comment]
> What do you mean?

https://github.com/mpv-player/mpv/issues/9825#issuecomment-1029810844

It just means that mpv cannot specify metainfo. `slang` is a track metainfo, so  this demand cannot be realized at present.
