### ISSUE TITLE
mpv can't reproduce YouTube video anymore.

### ISSUE THREAD

**Issue by donchiadev** [mpv-player/mpv#9887]
### Brief Introduction

mpv actually doesn't reproduce any video provided with url anymore, so it's not something related specifically to YouTube.

### Important Information

- mpv version: 0.34.0-198-gbc9805c71a
- Windows Version: Windows 11 Home (Build: 22000.493)
- Source of the mpv binary: [Link](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220213-git-bc9805c.7z/download).

### Reproduction Steps

- Move the folder within the 7zip file (provided by the link above) in a folder at the same level of "Program Files" (like a new folder called "Portable Programs").
- Add mpv bin directory folder to PATH.
- Launch the following command from PowerShell: `mpv [ANY_YOUTUBE_VIDEO]` .

### Expected Behavior

mpv should reproduce the video given in the command.

### Actual Behavior

The following error: `[ytdl_hook] youtube-dl failed: unexpected error occurred`

### Log File

[Log](https://github.com/mpv-player/mpv/files/8101627/log.txt)

### Additional Information

Python Version: 3.10.2
yt-dlp: 2022.02.04

I'm using yt-dlp instead of youtube-dl. From what i understand, seems that mpv recognize yt-dlp as a tool to use in its process (see the log file). I also tried to go back to youtube-dl but doesn't make any difference, same result as reported up here.

**Comment by avih** [comment]
Your test setup adds a lot of variables, and it's really impossible to tell which one causes this.

> From what i understand, seems that mpv recognize yt-dlp

Correct.

However, mpv didn't have any recent changes in how it launches youtube-dl (or yt-dlp). So i'm guessing it's either related to file permission issues, or maybe windows defender or some other anti-virus blocks execution of yt-dlp.

> Move the folder within the 7zip file (provided by the link above) in a folder at the same level of "Program Files" (like a new folder called "Portable Programs").

Try first without moving it anywhere (e.g. it in a dir without potential permission issues).

mpv doesn't modify or change PATH, so another option is that you didn't set PATH correctly, and/or yt-dlp does not execute correctly for some reason which is unrelated to mpv.

You mentioned python version, which suggests you don't use the standard windows yt-dlp binary, so you should try the official binary too. There were some known recent issues that yt-dlp fails to launch from python env.

Overall though, unless you can demonstrate that it's actually mpv's fault, it's 99.99% unrelated to mpv.

**Comment by avih** [comment]
See also this https://github.com/mpv-player/mpv/issues/9846

Seems to me a similar issue to yours (TL:DR: seem to be a pip 22 issue. try downgrading pip to 21).

**Comment by donchiadev** [comment]
> You mentioned python version, which suggests you don't use the standard windows yt-dlp binary, so you should try the official binary too. There were some known recent issues that yt-dlp fails to launch from python env.

Using yt-dlp binary instead the python module solved my problem. I put the binary inside a folder within my profile directory and added the said folder to PATH. Thanks alot for your help @avih and sorry to had doubt about the mpv functionality, i searched a little bit before open this issue and wasn't able to pinpoint the exact problem.
