### ISSUE TITLE
Wrong scaled resolution on macOS

### ISSUE THREAD

**Issue by fluxth** [mpv-player/mpv#9890]
### Important Information

Provide following Information:
- mpv version: `0.34.1`
- macOS Version: `12.2`
- Source of the mpv binary or bundle: `Homebrew`

### Reproduction steps

Go to System Preferences > Display > Resolution, and then change from "Default for Display" to "Scaled" and select any option but the default one.

My setup has a 3840x2160 display. By default, macOS will use 2.0x scaling to make my scaled resolution looks like 1920x1080.
I want more space, so I set the scaling to 1.5x which makes my scaled resolution looks like 2560x1440.

Note that this issue doesn't appear if your macOS scaling preference is set to the default.

1. Launch mpv with any video (in this example: a 1920x1080 video), with `--no-hidpi-window-scale` flag. It will start windowed.
2. Use `I` shortcut to bring up the info OSD and observe the `Scaled Resolution` item.
3. Try to resize the player window and observe the `Scaled Resolution` item.
4. Switch to fullscreen and observe the `Scaled Resolution` item.

### Expected behavior

- When launched in windowed mode, `Scaled Resolution` should be `1920x1080`.
- When trying to resize the window, `Scaled Resolution` should never exceed `3840x2160` which is the screen's native resolution.
- When switched to fullscreen mode, `Scaled Resolution` should be `3840x2160`.

### Actual behavior

- When launched in windowed mode, `Scaled Resolution` reports `1920x1080`. (correct)
- When trying to resize the window, `Scaled Resolution` reports `3840x2160` before the window fills up the entire screen. (wrong)
- When switched to fullscreen mode, `Scaled Resolution` reports `5120x2880`. (wrong)

![Screen Shot 2022-02-20 at 1 39 45 AM](https://user-images.githubusercontent.com/9163891/154814593-061893fb-3639-4a5d-98fd-fa1a67b75863.jpg)

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/8102905/mpv.log) (Launched and toggled fullscreen)

**Comment by Akemi** [comment]
if you have a resolution that "looks like 2560x1440" macOS uses a virtual desktop with a resolution of 5120x2880. which is the max resolution mpv need to scale to. if you don't scale to that resolution you can never go to full screen. 3840x2160 can only be done with black borders.

your expectations are wrong and that's not how macOS's DPI scaling works internally.
