### ISSUE TITLE
tex_offset is not available in consequent shader passes

### ISSUE THREAD

**Issue by agyild** [mpv-player/mpv#9892]
This is something I have noticed while trying to implement a pan & scan fix for [FSR](https://gist.github.com/agyild/82219c545228d70c5604f865ce0b0ce5) which is made of two passes. I assume once consumed in the first pass, `tex_offset` gets a reset, because adding it to texture position in the second pass doesn't do anything at all. The current version of the shader includes the fix, and you can test it for yourself. If this is a bug, consider this a bug report. If not, please consider adding a `PASSTHROUGH` option to `//!OFFSET` so it doesn't get reset after the first pass.

**Comment by igv** [comment]
`tex_offset` is always used together with `input_size` (size of a cropped (or moved) texture where `tex_offset` is offset of the crop).
RCAS pass doesn't need it since `EASUTEX` is already cropped.
It still won't work, because if you crop `LUMA` you also need to crop `CHROMA`.

**Comment by agyild** [comment]
@igv I have also noticed that pan-and-scan behavior of FSR/CAS are not the same as normal scalers, instead of focusing on the center they focus on upper or lower side of a vertical video for instance. And if I remove the RCAS pass, EASU pass with pan-and-scan fix works perfectly. So in the first pass the CHROMA channel is cropped perfectly, and it is only the second pass that is problematic.

How do your shaders tackle those issues (i.e., CHROMA misscaling and pan-and-scan focus)?

**Comment by igv** [comment]
> So in the first pass the CHROMA channel is cropped perfectly, and it is only the second pass that is problematic.

RCAS pass has nothing to do with pan-and-scan. Chroma is still misaligned without it.

> How do your shaders tackle those issues (i.e., CHROMA misscaling and pan-and-scan focus)?

I don't crop luma, it's not supported by mpv.

Just revert back to RGB, it's only ~20% slower. For better quality use proper RGB to luma conversion (instead of "Simplest approximate luma possible").

**Comment by agyild** [comment]
> > So in the first pass the CHROMA channel is cropped perfectly, and it is only the second pass that is problematic.
> 
> RCAS pass has nothing to do with pan-and-scan. Chroma is still misaligned without it.
> 
> > How do your shaders tackle those issues (i.e., CHROMA misscaling and pan-and-scan focus)?
> 
> I don't crop luma, it's not supported by mpv.
> 
> Just revert back to RGB, it's only ~20% slower. For better quality use proper RGB to luma conversion (instead of "Simplest approximate luma possible").

It still won't work. It fixes the chroma misaligning problem, but when pan-and-scanning the texture gets stretched and/or zooms-in to a non-center area (if a second pass after EASU is available) instead of zooming-in.

**Comment by igv** [comment]
Works perfect (Alt + LEFT/RIGHT/+/-) if aspect ration of a frame is the same as the player/monitor. You doing something wrong if it doesn't.
The only problem is when AR doesn't match, then texture gets stretched. Looks like mpv bug.

**Comment by agyild** [comment]
> Works perfect (Alt + LEFT/RIGHT/+/-) if aspect ration of a frame is the same as the player/monitor. You doing something wrong if it doesn't. The only problem is when AR doesn't match, then texture gets stretched. Looks like mpv bug.

I tried it in a vertical video on a 16:9 monitor (i.e., aspect ratio doesn't match), it focuses on the center but the video gets stretched vertically on both sides. Is that what you mean? You are sure that's a bug and not a miscalculation or because of the elliptical shape of the kernel?

@haasn If that's a bug, can you please investigate?

**Comment by igv** [comment]
My guess - this is because you scaling to OUTPUT size, which is just the size of the player (or screen if mpv is maximized)

**Comment by agyild** [comment]
> My guess - this is because you scaling to OUTPUT size, which is just the size of the player (or screen if mpv is maximized)

Yeah, I also have guessed that and tried changing `OUTPUT` to `MAIN`. The result is the same. Is there like a `OUTPUT_CROPPED` or something like that?

**Comment by igv** [comment]
All you need to do is replace `input_size` with `HOOKED_size`. Don't need to crop manually. And it works with luma version. Even if you scale directly to `OUTPUT`, mpv's built-in scaler kicks-in when you zooming.

**Comment by igv** [comment]
Only I'm not sure this shader works correctly now that I zoomed-in - it looks kinda ugly.

**Comment by agyild** [comment]
> All you need to do is replace `input_size` with `HOOKED_size`. Don't need to crop manually. And it works with luma version. Even if you scale directly to `OUTPUT`, mpv's built-in scaler kicks-in when you zooming.

Do you mean like this?

```glsl
	// Get position of 'f'.
	vec2 pp = HOOKED_pos * input_size - vec2(0.5) + tex_offset;
	vec2 fp = floor(pp);
	pp -= fp;
```

In this case it just stretches from one side, causing the edge pixels to repeat.

**Comment by igv** [comment]
Without `tex_offset`. As I already said `tex_offset` should be used only together with input_size.

**Comment by agyild** [comment]
> Only I'm not sure this shader works correctly now that I zoomed-in - it looks kinda ugly.

How do you mean?

Obviously the shader does not fully enlarge the texture; mpv takes the enlarged texture by the shader and zooms it in by using the selected scalers. Is this what you have meant by kinda ugly?

**Comment by igv** [comment]
This ugly.
![mpv-shot0001](https://user-images.githubusercontent.com/16772957/154924567-e0770e54-7c11-44f7-8bcf-a8046bfcfadd.png)

**Comment by igv** [comment]
CAS-scaled looks... interesting.
![cas](https://user-images.githubusercontent.com/16772957/154926876-e166a930-2e14-42ef-aa09-28853be9f280.png)

**Comment by agyild** [comment]
I don't know. It just seems to like the kernel shapes. FSR is elliptical, CAS is a box filter. How should it look instead?

**Comment by igv** [comment]
> How should it look instead?

On [this](madshi.net/small.png) test pattern NVScaler would be perfect without ringing.
![nvscaler](https://user-images.githubusercontent.com/16772957/154928636-8cbe7a3f-3c62-4a67-b906-cf01cf51fb4c.png)

**Comment by agyild** [comment]
NVScaler is already prone to ringing due to its very aggressive edge sharpening even when you use the built-in version in the driver. So I would say it is expected behavior. But if you are thinking that I have missed something when porting, I would love to hear it.

As for the difference between using `input_size` and `HOOKED_size`, the results are exactly the same for me when used on the test pattern. So looks like they are both ugly, when you zoom in like crazy.

**Comment by igv** [comment]
Zoom level (or input_size / HOOKED_size) has nothing to do with it.

**Comment by igv** [comment]
Also, your issue, in my opinion, has been properly fixed, you can close it.

**Comment by igv** [comment]
When upscaling only by a factor of 2 it doesn't look that ugly.
![fsr2](https://user-images.githubusercontent.com/16772957/154969921-3b5638cb-fe99-43da-b35f-043492865113.png)

Use this to limit scaling factor to 2x:
```
//!WIDTH OUTPUT.w OUTPUT.w LUMA.w 2 * < * LUMA.w 2 * OUTPUT.w LUMA.w 2 * > * + OUTPUT.w OUTPUT.w LUMA.w 2 * = * +
//!HEIGHT OUTPUT.h OUTPUT.h LUMA.h 2 * < * LUMA.h 2 * OUTPUT.h LUMA.h 2 * > * + OUTPUT.h OUTPUT.h LUMA.h 2 * = * +
```
With
`//!WHEN OUTPUT.w OUTPUT.h * LUMA.w LUMA.h * / 1.0 >`

**Comment by agyild** [comment]
Can you pseudocode what it does? I hate reading reverse expressions. Is it like integer scaling where it only scales by the factor of 2x, or it scales anything upscaled (including values between 1x to 4x) but only up to 4x area scaling, so the internal scalers takes care of the rest after 4x?

**Comment by igv** [comment]
it scales anything up to 4x area scaling, so the internal scalers takes care of the rest after 4x, instead of your old approach
pseudo code: `WIDTH = if LUMA.w * 2 > OUTPUT.w then OUTPUT.w else LUMA.w * 2`

**Comment by agyild** [comment]
@igv While testing it with `gpu-next`, I have noticed that `WIDTH` and `HEIGHT` cause errors with it. Any idea why?

**Comment by igv** [comment]
It doesn't like '='
@haasn

**Comment by igv** [comment]
Meanwhile try this instead:
```
//!WIDTH OUTPUT.w OUTPUT.w LUMA.w 2 * < * LUMA.w 2 * 1 OUTPUT.w LUMA.w 2 * < - * +
//!HEIGHT OUTPUT.h OUTPUT.h LUMA.h 2 * < * LUMA.h 2 * 1 OUTPUT.h LUMA.h 2 * < - * +
```

**Comment by agyild** [comment]
> Meanwhile try this instead:
> 
> ```
> //!WIDTH OUTPUT.w OUTPUT.w LUMA.w 2 * < * LUMA.w 2 * 1 OUTPUT.w LUMA.w 2 * < - * +
> //!HEIGHT OUTPUT.h OUTPUT.h LUMA.h 2 * < * LUMA.h 2 * 1 OUTPUT.h LUMA.h 2 * < - * +
> ```

The same.

```
[vo/gpu-next] Variable 'EASUTEX' not found in RPN expression!
[vo/gpu-next] Failed executing hook, disabling
```

For some reason it doesn't execute the first pass with the new directives.

**Comment by igv** [comment]
Works for me (just compiled everything).

**Comment by igv** [comment]
> [vo/gpu-next] Variable 'EASUTEX' not found in RPN expression!
[vo/gpu-next] Failed executing hook, disabling

This is only if you enable the shader before upscaling.

**Comment by agyild** [comment]
> > [vo/gpu-next] Variable 'EASUTEX' not found in RPN expression!
> > [vo/gpu-next] Failed executing hook, disabling
> 
> This is only if you enable the shader before upscaling. It's a different bug.

How do you enable it after upscaling?

**Comment by igv** [comment]
With a key bind.

**Comment by haasn** [comment]
> It doesn't like '=' @haasn

Should be fixed. These were added in mpv after the code was forked to libplacebo.

What's the other bug you were talking about? Also note that the entire shader system is in dire need of a redesign, see [this issue](https://code.videolan.org/videolan/libplacebo/-/issues/174) if you want to contribute to the discussion.

**Comment by igv** [comment]
> What's the other bug you were talking about?

If (temporary) texture is unavailable for binding that shader is disabled forever (until mpv restart).

> Also note that the entire shader system is in dire need of a redesign, see [this issue](https://code.videolan.org/videolan/libplacebo/-/issues/174) if you want to contribute to the discussion.

Right now my only wish is that current shaders wouldn't need much work to port to the new system.
