### ISSUE TITLE
Weird behaviour on tct output

### ISSUE THREAD

**Issue by H4ck3r404** [mpv-player/mpv#9894]
Yesterday i had this weird issue when trying to play something with tct output. No matter the video it always shown weird white horizontal stripes. It seems that they are negating colour somehow as pitch black shows as white and the other way around. 
Hardware: Poco 3x pro
Software: Mpv on termux build

If this issue does not apply to this repo please let me know where to move it.

Here's some pictures:

![Screenshot_2022-02-21-01-38-06-336_com.termux.jpg](https://user-images.githubusercontent.com/53434628/154924700-9af1876f-a4fb-4f34-b3fd-6f8820aafc8a.jpg)
![Screenshot_2022-02-21-01-51-49-652_com.termux.jpg](https://user-images.githubusercontent.com/53434628/154924745-acea43f5-70b8-46af-af09-8b4af0045f73.jpg)

**Comment by avih** [comment]
You didn't provide a log so it's impossible to tell what's going on.

Most likely one or more of the following:
- TCT is unable to determine the terminal width and/or height, or the terminal doesn't handle correctly newline at the exact terminal width. Try setting explicit (smaller) size with `--vo-tct-width` and `--vo-tct-height`.
- The terminal is unable to process true color the way TCT outputs it. Try `--vo-tct-256=yes`.
- The font doesn't have half-block unicode characters, and/or the terminal doesn't process UTF-8 correctly. Try a different font or `--vo-tct-algo=plain`.

**Comment by H4ck3r404** [comment]
Nevermind - dark mode rom issue.
