### ISSUE TITLE
Mpv Doesn't Suspend Screensaver/Sleep on Windows 11 on ARM

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#9895]
### Important Information

Provide following Information:
- Latest (just intalled)
- Windows 11 on ARM Build Number 22000.318

### Reproduction steps

Play a video.

### Expected behavior

Mpv suspends sleep while playing and the screen doesn't fade or go black.

### Actual behavior

It does not suspend it and I have to move the cursor every so often.

**Comment by CounterPillow** [comment]
The issue template would've told you how to generate the log file. "the build is probably for x86" does not answer where you got your mpv from.

**Comment by Hrxn** [comment]
You cannot seriously expect a binary build for x86 to work on an ARM system, do you?

I think this issue should be closed, seems like a waste of time.

**Comment by george-emerald** [comment]
I got it from mpv.io. The shinchiro builds.

**Comment by george-emerald** [comment]
Nobody seems interested in this, plus I don't use this anymore. So I'm closing it.
