### ISSUE TITLE
How to scale the video information / toggle stats (OSD) text size?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#9898]
https://mpv.io/manual/stable/#configurable-options

>i | Show stats for a fixed duration
>I | Toggle stats (shown until toggled again)

I have set `osd-scale=0.25` but the video stats doesn't seem to scale? Is this by design?

3840 × 2160 screenshot (native, fullscreen):

![Screenshot from 2022-02-22 14-15-47](https://user-images.githubusercontent.com/14923168/155130568-52232418-ae80-4a18-a9cd-e6870ff6c07d.png)

**Comment by avih** [comment]
https://mpv.io/manual/stable/#stats-font-size

**Comment by 07416** [comment]
for the record (on Linux):

    nano ~/.config/mpv/script-opts/stats.conf

edit in (replace with the preferred value):

    font_size=3
