### ISSUE TITLE
brighter Hable-like tonemapping without peak detection for lowend devices

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#9900]
My current approach to watch HDR video on a lowend Gemini Lake device with strictly enforced 6W TDP is

```
tone-mapping=reinhard
tone-mapping-param=0.8
tone-mapping-max-boost=10
hdr-compute-peak=no
```

`hdr-compute-peak=yes` is not an option, as it completely overburdens this GPU and its power envelope.

Why I'm not entirely happy with that config: Saturated colors look oversaturated and very dark scenes are still a bit hard to watch (especially at very low display brightness). There is `target-peak`. However, low values also make bright parts very glaring.

This is why it'd be really great if there was tonemapping with Hable-like desaturated colors, but much brighter darker parts without making bright parts glaring. Ideally also in `vo=gpu`, as `gpu-next` is not usable with that device until there is hardware decoding support.

**Comment by Doofussy2** [comment]
Does `--tone-mapping-mode=desaturate` make a difference?

https://mpv.io/manual/master/#options-gamut-mapping-mode

**Comment by Doofussy2** [comment]
I actually made an error, it should be `--gamut-mapping-mode`. But I imagine you saw my error.

**Comment by aufkrawall** [comment]
Perhaps. ;)

Anyway, new `spline` tone mapping of `gpu-next` seems to be exactly what I want, it's very bright with `tone-mapping-param=1` and colors look far more balanced than `reinhard`. Though it seems to be a tiny bit more taxing on the GPU, which makes life a tiny bit too hard for my Gemini Lake craptop. Probably will be downscaling videos via re-encode for now, unless some magic performance optimization pops up. Also looks like `nearest` scaling doesn't decrease power consumption vs. `bilinear`.

**Comment by haasn** [comment]
> Though it seems to be a tiny bit more taxing on the GPU, which makes life a tiny bit too hard for my Gemini Lake craptop.

That's an unfortunate consequence of the switch to LUT-based tone mapping. Is it still too taxing with `--hdr-compute-peak=no`? If so, I could try and re-add a pure GLSL fallback for the most common and easiest-to-implement tone mappers (e.g. spline).

Alternatively, we could try a different LUT method. Can you share a log? I want to confirm what it's picking for you.

> Also looks like nearest scaling doesn't decrease power consumption vs. bilinear.

You need to combine these with `--no-correct-downscaling` when downscaling to make it actually used fixed function sampling.

**Comment by aufkrawall** [comment]
Thanks!
Funny: With `nearest` allowed via `no-correct-downscaling`, GPU power consumption is actually much higher than with `bilinear`. Really wouldn't have expected that, unless mpv takes some clever shortcuts with bilinear.

Yes, I had `hdr-compute-peak=no` set. The larger the mpv window size is, the more load is put on the GPU. So ~700p windowed works, whereas 1080p fullscreen doesn't anymore.

Here is a log file:
[spline.txt](https://github.com/mpv-player/mpv/files/8187368/spline.txt)

Config used:

```
vo=gpu-next
gpu-api=opengl
gpu-context=wayland
hwdec=vaapi
hwdec-codecs=all
dither-depth=8
temporal-dither
video-sync=display-resample
icc-profile=".../profile.icm"
tone-mapping=spline
tone-mapping-param=1
```

With Vulkan, SoC power consumption is already close to the 6W limit also without HDR video, which is why I set it to OGL.

**Comment by aufkrawall** [comment]
Yeah, I forgot to set `hdr-compute-peak=no`. It is much better with it set to `no`. `Spline` doesn't actually consume power power than `reinhard` when both used in `vo=gpu-next`.

However, `vo=gpu-next` consumes a bit more power than `vo=gpu` with

```
tone-mapping=reinhard
tone-mapping-param=0.8
hdr-compute-peak=no
```
. It's ~4W vs. ~4.3W with half screen video size and probably a bit more in fullscreen. So any tiny bit of more optimization in `gpu-next` for such lowend GPUs would be highly appreciated. :)

**Comment by aufkrawall** [comment]
A log file with `hdr-compute-peak=no`:
[spline.txt](https://github.com/mpv-player/mpv/files/8193389/spline.txt)

It's still too much load on the GPU to watch 4k video without stutter on this device, which worked with `vo=gpu` and `tone-mapping=reinhard` (+ `hdr-compute-peak=no`). Fortunately, the 1080p transcode workaround does the trick. `spline` is really a great improvement for typical real world content.

**Comment by haasn** [comment]
@aufkrawall can you try if this patch makes things faster or slower?

```diff
diff --git a/src/shaders/colorspace.c b/src/shaders/colorspace.c
index 11197cb7..3fab1a9e 100644
--- a/src/shaders/colorspace.c
+++ b/src/shaders/colorspace.c
@@ -1319,7 +1319,7 @@ static void tone_map(pl_shader sh,
 
         lut = sh_lut(sh, sh_lut_params(
             .object = &obj->lut,
-            .method = SH_LUT_AUTO,
+            .method = SH_LUT_LITERAL,
             .type = PL_VAR_FLOAT,
             .width = lut_params.lut_size,
             .height = dynamic_peak ? lut_params.lut_size : 0,
```

**Comment by aufkrawall** [comment]
Power consumption did not change by the patch.

**Comment by flipflop133** [comment]
Thanks @aufkrawall, after testing everything to get a brighter HDR rendering, your config is just the best with `vo=gpu-next`, while with `vo=gpu` the best was using `tone-mapping-max-boost`.
With `vo=gpu-next`, everything I tried gave bad results (mostly too bright regions), the best results were by using this:
```
tone-mapping = bt.2390
target-peak = 80
```
but your config is far better, brighter while conserving the colors!

**Comment by Dudemanguy** [comment]
Was this solved? Not entirely sure about all this HDR stuff.

**Comment by aufkrawall** [comment]
Imho we can close this. Peak detect apparently is also a challenge for much bigger Intel Gen 9 GPUs than found in Gemini Lake. I guess one can be glad that it can even handle vo=gpu(-next) at all.
