### ISSUE TITLE
No video on macOS, instead `[osx/cocoacb] Unexpected nil value in Control Callback` error

### ISSUE THREAD

**Issue by globau** [mpv-player/mpv#9902]
### Important Information

Provide following Information:
- mpv version

mpv 0.34.0-204-g37927b65f7

- macOS Version

Monterey 12.2.1

- Source of the mpv binary or bundle

Self built from 37927b65f719aac817717c88c10b05ca7246248a with the following config options:
```
/usr/local/bin/python3 waf configure \
    --prefix=/usr/local \
    --disable-macos-touchbar \
    --enable-javascript \
    --enable-libmpv-shared \
    --enable-lua \
    --lua=luajit \
    --enable-libarchive \
    --enable-uchardet \
    --confdir=/usr/local/etc/mpv \
    --datadir=/usr/local/share/mpv \
    --mandir=/usr/local/share/man \
    --docdir=/usr/local/share/doc/mpv
```

- If known which version of mpv introduced the problem

Was not introduced by a change in mpv; an older version started throwing errors so I upgraded to latest to test.

### Reproduction steps

Viewing any video, with or without `--no-config`.

### Expected behavior

Video and audio plays

### Actual behavior

Only audio plays.  Terminal shows a large amount of `[osx/cocoacb] Unexpected nil value in Control Callback` errors.

Problem continues after upgrading mpv and rebooting.

Happens with all video files.  I confirmed the videos work correctly in other players.

### Log file

https://gist.github.com/globau/931f3ff935ca7771d4fc65f497685076

**Comment by globau** [comment]
Hrm, just tested it on a different macOS system, also 12.2.1 with the same mpv build options.  No problems there.  Sadly I have no idea how to start to diagnose what's busted on my main macOS device.

Feel free to close this issue as "works for me" if appropriate.

**Comment by globau** [comment]
After messing about in the guts of mpv for a while it suddenly started working, and continues to work after reverting all my diagnostic changes.
I don't know what happened, but it's working now and clearly something local to my system.
Sorry about the noise.

**Comment by avih** [comment]
> it suddenly started working

For future reference, the osx build sometimes needs `./waf clean` bfore `./waf configure && ./waf build`.

I had the same spam/warning as OP, and doing clean before configure fixed it for me.
