### ISSUE TITLE
While playing an ISO image played and remaining times are shown wrong

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#9904]
### Important Information

Provide following Information:
- mpv version: 0.34.0
- OS: FreeBSD 13
- Source of the mpv binary: port
- Window Manager and version: XFCE4

### Reproduction steps

Download and play [this ISO image](https://people.freebsd.org/~yuri/testcase-mpv-fails-to-show-time.iso).

It plays but the remaining time is shown as 4 minutes for a long time. In the end it shows played time as 4 minutes for a long time.

**Comment by thebombzen** [comment]
The sample you provided is corrupt. Please provide screenshots of the issue by pushing `Ctrl+s` while the OSC is open.

**Comment by yurivict** [comment]
I checked, the ISO file is valid:
MD5 (testcase-mpv-fails-to-show-time.iso) = b1ba0ee41ac2ee6194e40f7294e1030e
SIZE = 4688615424

**Comment by yurivict** [comment]
![mpv-shot0001](https://user-images.githubusercontent.com/271906/156265549-eb42c8ab-a777-4ea9-863c-07cb4af03a80.jpg)

**Comment by thebombzen** [comment]
You will need to provide a sample that is not corrupt.

**Comment by yurivict** [comment]
Sorry, indeed the original URL has a problem.

Here is a replacement [url](http://distcache.us-east.FreeBSD.org/local-distfiles/yuri/testcase-mpv-fails-to-show-time.iso).
