### ISSUE TITLE
How to upscale video pixel-perfectly?

### ISSUE THREAD

**Issue by Layerex** [mpv-player/mpv#9905]
There seems to be no option to disable antialiasing when scaling. Is there some hack to do so?

**Comment by avih** [comment]
`--scale=nearest` will be pixel-perfect, but note that unless the new size is an exact multiple of the original size then the scaled pixels would be of slightly different sizes.

To avoid this "different pixels size" issue at the cost of some "anti aliasing", use `--scale=oversample`.
