### ISSUE TITLE
Video output x11 not found problem!

### ISSUE THREAD

**Issue by Shiro350** [mpv-player/mpv#9906]
### Important Information

Provide following Information:
mpv-x86_64-20220213-git-bc9805c - mpv version
- Windows 10 - windows version

I try to use vo=x11 but get error
(mpv.exe --vo=x11 --log-file=logs.log test.mp4)
[   0.030][e][vo] Video output x11 not found!
How to fix it?

[logs.log](https://github.com/mpv-player/mpv/files/8127409/logs.log)

**Comment by avih** [comment]
>  How to fix it?

Use Linux or other Platform which supports x11.

Your mpv does not have x11 support, and I don't think anyone ever tried to enable x11 support in mpv for windows.
