### ISSUE TITLE
osc (overlay) does not respond to mouse actions transmitted by the command 

### ISSUE THREAD

**Issue by Shiro350** [mpv-player/mpv#9910]
I am trying to send mouse events to mpv via commands, but the overlay control (osc) simply does not work in this way, I cannot control the osc. Rewind the video or turn down the volume via osc for example. Only keybinds works (for example, pause the video if it is written in input.conf)

Provide following Information:
- mpv version:mpv-devx86_64-20210515
- os:Windows 10

My code on python:
```
#!/usr/bin/env python3

import time
import os
os.add_dll_directory(os.getcwd())
import mpv
import sys
from PySide6.QtWidgets import *
from PySide6.QtCore import *
if getattr(sys, 'frozen', False):
    # If the application is run as a bundle, the PyInstaller bootloader
    # extends the sys module by a flag frozen=True and sets the app
    # path into variable _MEIPASS'.
    application_path = sys._MEIPASS
else:
    application_path = os.path.dirname(os.path.abspath(__file__))
MpvKeys = {
    Qt.Key.Key_Backspace:   'BS',
    Qt.Key.Key_PageUp:      'PGUP',
    Qt.Key.Key_PageDown:    'PGDWN',
    Qt.Key.Key_Home:        'HOME',
    Qt.Key.Key_End:         'END',
    Qt.Key.Key_Left:        'LEFT',
    Qt.Key.Key_Up:          'UP',
    Qt.Key.Key_Right:       'RIGHT',
    Qt.Key.Key_Down:        'DOWN',

    # ...
}




mpvfolderpath = f"{application_path}/mpv.net/portable_config/"
class Test(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setMouseTracking(True)

        self.container = QWidget(self)
        self.setCentralWidget(self.container)
        self.container.setAttribute(Qt.WA_DontCreateNativeAncestors)
        self.container.setAttribute(Qt.WA_NativeWindow)
        self.container.setMouseTracking(True)
        self.player = mpv.MPV(wid=str(int(self.container.winId())),
                              vo="gpu",
                              input_conf=f"{mpvfolderpath}input.conf",
                              terminal=True,
                              input_terminal=True,
                              osc=True)
        self.player.play('test.mp4')

    def keyPressEvent(self, event):
        # look up for the key in our mapping, otherwise use the event's text
        key = MpvKeys.get(event.key(), event.text())
        self.player.keypress(key)

    def mouseMoveEvent(self, event):
        self.player.command('mouse', int(event.position().x()), int(event.position().y()))

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.player.command('mouse', int(event.position().x()), int(event.position().y()), 2)
        else:
            super().mousePressEvent(event)



app = QApplication(sys.argv)

import locale
locale.setlocale(locale.LC_NUMERIC, 'C')
win = Test()
win.show()
sys.exit(app.exec_())
```
All you need to understand here is that when you click the mouse button, I send a command mouse x, y, button

**Comment by avih** [comment]
We don't maintain the python bindings, so we don't know which commands are sent to mpv, and you didn't provide a log either.

> Only keybinds works (for example, pause the video if it is written in input.conf)

That's not interpreted by the OSC. it's interpreted by mpv, and would work even if you disable the OSC.

> I cannot control the osc. Rewind the video or turn down the volume via osc for example

Again, we don't know which commands you execute and their timing so we can't know what's going on.

But if I had to guess, you either use the mouse command to execute the click, or use the mouse command to set the position and then immediately invoke the click command or key up/down commands for the button.

In general, the OSC is not meant for programatic control except as documented (e.g. for `osc-visibility`). The OSC is a complex and delicate code, and highly timing sensitive.

Specifically, the OSC doesn't capture mouse clicks by default, but if the mouse pointer moves such that it's over the "GUI" area, then it enables capturing also mouse clicks etc.

So if the click arrives before the OSC gets a chance to enable capturing mouse clicks, then it won't capture the click, which I guess is what happens in your case.

**Comment by trin94** [comment]
Try those commands:

```python
    def move_mouse(self, x: int, y: int):
        self._mpv.command("mouse", x, y)

    def open(self, url: str):
        self._mpv.command("loadfile", url, "replace")

    def press_mouse_left(self):
        self._mpv.command("keydown", "MOUSE_BTN0")

    def press_mouse_middle(self):
        self._mpv.command("keypress", "MOUSE_BTN1")

    def release_mouse_left(self):
        self._mpv.command("keyup", "MOUSE_BTN0")

    def scroll_up(self):
        self._mpv.command("keypress", f"MOUSE_BTN3")

    def scroll_down(self):
        self._mpv.command("keypress", f"MOUSE_BTN4")
```

**Comment by Shiro350** [comment]
> Try those commands:
> 
> ```python
>     def move_mouse(self, x: int, y: int):
>         self._mpv.command("mouse", x, y)
> 
>     def open(self, url: str):
>         self._mpv.command("loadfile", url, "replace")
> 
>     def press_mouse_left(self):
>         self._mpv.command("keydown", "MOUSE_BTN0")
> 
>     def press_mouse_middle(self):
>         self._mpv.command("keypress", "MOUSE_BTN1")
> 
>     def release_mouse_left(self):
>         self._mpv.command("keyup", "MOUSE_BTN0")
> 
>     def scroll_up(self):
>         self._mpv.command("keypress", f"MOUSE_BTN3")
> 
>     def scroll_down(self):
>         self._mpv.command("keypress", f"MOUSE_BTN4")
> ```
Thanks, it's really works, i close issue.

**Comment by martinrotter** [comment]
this saved my day, thankx
