### ISSUE TITLE
MPV can only play video at 100x speed. How to adjust 200X speed and 300X speed?

### ISSUE THREAD

**Issue by jiutian321** [mpv-player/mpv#9916]
### Important Information

Provide following Information:
- mpv version   mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects

- Linux Distribution and Version    统信uos家庭版21.1.1

**Comment by LaserEyess** [comment]
Your mpv is way too out of date, you have to update. Also, when you update, be sure to fill out the issue template which you ignored.

**Comment by snylonue** [comment]
The limit is defined here
https://github.com/mpv-player/mpv/blob/b1fb4b783bd604ffb763e88a7cee2ad9d9c2c209/options/options.c#L555

**Comment by jiutian321** [comment]
> 限制在这里定义
> 
> https://github.com/mpv-player/mpv/blob/b1fb4b783bd604ffb763e88a7cee2ad9d9c2c209/options/options.c#L555

Command side installation, did not find this file, do not know how to modify where

thank you

**Comment by jiutian321** [comment]
> 

Do you have software sources?apt update ，apt install mpv，Not knowing how to update.thank you
