### ISSUE TITLE
"PreviewImage" in jpg tags makes mpv misbehave

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#9920]
### Important Information

```
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```
Also reproducible on mpv master with the same ffmpeg version. 
The system in question is arch linux. Can be reproduced on both x11 and wayland. 

I am pretty sure that a (recent) update to ffmpeg started causing this, as I have been using mpv previously without any problem. I can try to confirm this if necessary.

### Reproduction steps

Open a jpg image with embedded "PreviewImage" with `mpv --no-config image.jpg`. 
The options `--loop-file=inf` and `--image-display-duration=inf` highlight different "broken" behavior

### Expected behavior

No flags: the image is displayed for 1 second, then mpv closes
--loop-file=inf: the image is displayed until mpv is closed
--image-display-duration=inf: the image is displayed until mpv is closed

### Actual behavior

No flags: the image is not displayed, mpv closes almost right away
--loop-file=inf: the mpv window flashes, the command line output constantly switch between `VO: [gpu] 6000x4000 yuvj422p` and `VO: [gpu] 1616x1080 yuvj422p`
--image-display-duration=inf: the image is not displayed, mpv closes almost right away

### Log file

Log file with `mpv --no-config image.jpg` [log0.txt](https://github.com/mpv-player/mpv/files/8146634/log0.txt)
Log file with `mpv --no-config --image-display-duration=inf image.jpg` [log1.txt](https://github.com/mpv-player/mpv/files/8146621/log1.txt)
Log file with `mpv --no-config --loop-file=inf image.jpg` [log2.txt](https://github.com/mpv-player/mpv/files/8146622/log2.txt)

### Sample files

The important part of this file is the "Preview Image". If this tag is removed, everything works fine again.

I tried generating a sample file using exiftool, but apparently the "Preview Image" tag is not well supported.

![DSC00978](https://user-images.githubusercontent.com/5473453/155843661-3f5081da-3c0c-446e-abb2-cae4d59d51da.JPG)

**Comment by occivink** [comment]
Are you suggesting that ffmpeg does not provide sufficient information, such that mpv 'thinks' that it's actually two frames of a video? Should I report this to the ffmpeg issue tracker?

**Comment by jeeb** [comment]
@occivink yea, the functionality has been based for things such as JPEG streams from HTTP servers etc. So as it reads one JPEG image and the decoder only reads what it requires, the parser starts looking for the next start point of a JPEG image. Which then is found within the metadata. I haven't looked at the code but my guesstimate is that's how it goes.

The reason why this doesn't happen when you just read it through the image2 reader is (by my guesstimate) just because it doesn't attempt to read more data after an image has been read from the file.

**Comment by quietvoid** [comment]
I stumbled on a sample that also reproduces this issue with image duration.
In my case `exiftool` also says:
```
Number Of Images                : 2
MP Image Flags                  : Dependent child image
MP Image Format                 : JPEG
MP Image Type                   : Large Thumbnail (full HD equivalent)
MP Image Length                 : 576755
MP Image Start                  : 3974420
...
Thumbnail Image                 : (Binary data 8936 bytes, use -b option to extract)
Preview Image                   : (Binary data 576755 bytes, use -b option to extract)
```
