### ISSUE TITLE
Disable video decoding when the player is minimized

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#9921]
It's quite a simple feature request: detect when the mpv window is minimized and temporarily stop video decoder/rendererer in this case until the window is restored.

**Comment by Dudemanguy** [comment]
Video decoding and video rendering are two radically different things. In the decoding case, this obviously cannot be stopped. The video is still playing. If you want to stop decoding, then just pause the video. The rendering case is a little more complicated. The wayland backend has a bunch of code to not render when it is hidden (and I kind of wish I didn't do all that but w/e). I'm honestly not sure about other platforms, but it's probable they handle this at the driver level already (i.e. not rendering if the window isn't visible). In any case, I don't think this is an optimization we should be doing in general so I will close this.

**Comment by Dudemanguy** [comment]
You can't stop decoding if the video is still playing. The visibility of the window doesn't matter.

**Comment by birdie-github** [comment]
Maybe I'm not expressing myself properly.

I mean leaving only audio stream playing, while temporarily ignoring video stream. That's what I'm talking about.

**Comment by Dudemanguy** [comment]
You can do this already with a script. Observe the `window-minimized` property and if the window is minimized, set `vid` to no.
