### ISSUE TITLE
Sourceforge -- which version?

### ISSUE THREAD

**Issue by markfilipak-windows** [mpv-player/mpv#9926]
https://sourceforge.net/projects/mpv-player-windows/files/latest/download?utm_campaign=updater&utm_medium=email&utm_source=subscribers

Released /64bit/mpv-x86_64-20220227-git-b1fb4b7.7z -- 9 hours ago
Released /32bit/mpv-i686-20220227-git-b1fb4b7.7z -- 9 hours ago
Released /libmpv/mpv-dev-x86_64-20220227-git-b1fb4b7.7z -- 9 hours ago
Released /libmpv/mpv-dev-i686-20220227-git-b1fb4b7.7z -- 9 hours ago

Why 4 versions? What are the differences? Explanation, please.

Regards,
Mark Filipak.

**Comment by rubyFeedback** [comment]
This is indeed a bit confusing. I'd recommend to just focus on a stable version for sourceforge and get rid of these weird git-tags; and for development builds to perhaps use a separate link. Stable should be the default.

I'd count these only as 2 versions, though, since one is for 64 bit and the other for 32 bit if I understood the names correctly so.

**Comment by zhongfly** [comment]
This includes 2 architectures: 32-bit (i686) and 64-bit (x86_64), and is also divided into executables (exe) and libmpv (for integrated use by other programs)
For most users, you only need to choose between mpv-x86_64 or mpv-i686 to download according to your computer architecture.

In addition, the release version does not mean stable, I always recommend to follow the latest version of git, if there is a bug, and then fall back to the previous version.

**Comment by markfilipak-windows** [comment]
@rubyFeedback
@zhongfly

Sorry, I don't understand either of your posts. I received a notice of a new version from Sourceforge. I know what "stable version" means, and I'm not keen on development builds, but I don't know how to differentiate a development build from a stable version. Further, I'm not familiar with what "i686" means. Further, does "Stable should be the default" mean that what Sourceforge offers is Stable? Further, I don't understand how "The goal of releases is to provide Linux distributions with something to package" applies to a Windows application. Further, while I know what a "master branch" is, how does that apply? -- I'm not compiling. Furthermore, how is git involved? (I avoid everything with 'git' in its name.)

**Comment by zhongfly** [comment]
Well, to put it simply, you download `/64bit/mpv-x86_64-20220227-git-b1fb4b7.7z` or `/32bit/mpv-i686-20220227-git-b1fb4b7.7z`, whichever works, just use that

**Comment by markfilipak-windows** [comment]
I give up.

**Comment by markfilipak-windows** [comment]
Launch d:\D\Setup\Video\players\MPV\mpv-x86_64-20220227-git-b1fb4b7\updater.bat

"Running script with administrator privileges
"Checking Windows PowerShell version -- 5
"Fetching RSS feed for mpv
"Unable to connect to the remote server

"Waiting for 1 seconds, press a key to continue ..."

Windows is not connected to the Internet. How do I proceed?

**Comment by markfilipak-windows** [comment]
I closed all running applications and submitted this:
d:\D\Setup\Video\players\MPV\mpv-x86_64-20220227-git-b1fb4b7\installer\mpv-install.bat
to the Windows 'Run' dialog. Then I double-clicked a '.mkv' to test it.

Filetype '.mkv' should solely launch this:
c:\CMD & tiny apps\MPV\mpv.exe
But now it launches this:
d:\D\Setup\Video\players\MPV\mpv-x86_64-20220227-git-b1fb4b7\mpv.exe

The only way I know of that would cause that is file associations in the Windows Registry, so I looked there.

The so-called mpv-install.bat is **not an installer**! It has made a mess of the Registry that will take me several hours to fix.

I would have appreciated a warning that MPV is a portable app and that 'mpv-install.bat' should be run solely from it's final destination, not from the download directory.

**Comment by Hrxn** [comment]
You don't need to use `mpv-install.bat` at all.. simply run the mpv binary files.

**Comment by markfilipak-windows** [comment]
On 2022-02-28 14:23, HRXN wrote:
> You don't need to use |mpv-install.bat| at all.. simply run the mpv binary files.

If I don't need to run mpv-install.bat, then why is it there?

**Comment by dexeonify** [comment]
> If I don't need to run mpv-install.bat, then why is it there?

`mpv-install.bat` is a script to register the default file associations, so your video files will automatically open in mpv.

> It has made a mess of the Registry that will take me several hours to fix.

There's a helpful `mpv-uninstall.bat` included that will undo whatever `mpv-install.bat` did. Don't try to "fix" the registry and make things worse.

**Comment by avih** [comment]
> Sourceforge -- which version?

If your system is 64 bits then this (try it out if you don't know, if your system doesn't support it then it won't run):
> Released /64bit/mpv-x86_64-20220227-git-b1fb4b7.7z -- 9 hours ago

And if not then this
> Released /32bit/mpv-i686-20220227-git-b1fb4b7.7z -- 9 hours ago

> If I don't need to run mpv-install.bat, then why is it there?

The mpv team does not provide executable binaries and does not maintain the binaries on sourceforge.

They're maintained by a 3rd paty project, here https://github.com/shinchiro/mpv-winbuild-cmake/

Please ask any further related questions there.

**Comment by ValZapod** [comment]
> and I'm not keen on development builds

We do not have that. Stable too. It is always master that is stable, just like ffmpeg.
