### ISSUE TITLE
Frametime higher than ideal but still no framedrop

### ISSUE THREAD

**Issue by Shashank066** [mpv-player/mpv#9929]
Provide following Information:
- mpv version mpv : 0.34.0-142-g1ba0547bfb
- Windows Version :  Windows 11 Pro - 21H2
- Source of the mpv binary : Windows builds by shinchiro 

### Expected behavior
Running a 23.976 fps video on 23.976 hz display. The average frame time is around 45 ms.
1000/23.976 = 41.7 ms
Should be frame drops since 45ms is more than 41.7ms.

### Actual behavior
0 frame drops.

### Log file
N/A

![Stats](https://user-images.githubusercontent.com/8770783/155998020-7b46e855-0e17-4c65-a850-d98f58d68db4.jpg)

**Comment by ValZapod** [comment]
> Should be frame drops since 45ms is more than 41.7ms.

One problem: there is no drops. MPV displays both decoding and presentation drops. So... How fast can you actually decode this video? There is -f null - command for this in ffmpeg use -hwaccel. Also you do understand that only LG C9 (and later models) has something like 5 ms on 120 hz? And it has 11 ms input lag on 60 fps, even more on 24/1.001 fps. And anyway I suppose that info is reported by gpu from libplacebo which is rather buggy at least for mp4 (it somehow corrupts vync stuff).

**Comment by Shashank066** [comment]
> One problem: there is no drops. MPV displays both decoding and presentation drops together, just like chrome, while firefox displays only decoding drops. So... How fast can you actually decode this video? There is -f null - command for this in ffmpeg use -hwaccel. 

I am running this in MPV with hwdec = no as I have enough CPU power but limited igpu performance. igpu is getting maxed at 100%. 

> Also you do understand that only LG C9 (and later models) has something like 5 ms on 120 hz? And it has 11 ms input lag on 60 fps, even more on 24/1.001 fps. 

Why would 5ms on 120hz be an issue, since I am running it at 23.976hz with 23.976fps? The display I am running is LG CX. 11ms input also shouldn't be an issue, since it's just a small latency on every frame.

>And anyway I suppose that info is reported by gpu from libplacebo which is rather buggy at least for mkv (it somehow corrupts vsync stuff).

Thanks for the help. Yes those are mkv files. I had scaled back the shaders settings a bit down to bring frame timing closer to 25ms.

**Comment by ValZapod** [comment]
> Why would 5ms on 120hz be an issue, since I am running it at 23.976hz with 23.976fps?

The less the fps the more is input lag. This is just physics...

>I had scaled back the shaders settings a bit down to bring frame timing closer to 25ms.

Oh, would be interesting to see what did you do ;)

**Comment by Shashank066** [comment]
I misunderstood input lag for frame timings previously. The input lag I haven't found that much of a issue for playing video content. Input lag for mouse while launching video files certainly isn't fun. By making the display frequency same as video fps i.e. 23.976, I avoid frame redraw performance hit by mpv and motion interpolation also works better that way with LG CX.

Couldn't find how to use qsvdec with mpv, only a few posts about ffmpeg. hwdec = yes causes frame drops on output and also high frame timings around 55ms. Running a 12700k with igpu uhd 770. Also, mpv documentation mentions:
>"Hardware decoding is not enabled by default, because it is typically an additional source of errors. It is worth using only if your CPU is too slow to decode a specific video."

So, I avoid it at the moment.

Can't remember pinpoint settings, but it was probably the heavy custom shaders leftover in MPV config from when I was using Nvidia 3090. Could be disabling any of these:
```

glsl-shader = E:/Softwares/Video Player\mpv/shaders/KrigBilateral.glsl
glsl-shader = E:/Softwares/Video Player\mpv/shaders/SSimDownscaler.glsl
glsl-shader = E:/Softwares/Video Player\mpv/shaders/SSimSuperRes.glsl
glsl-shader = E:/Softwares/Video Player\mpv/shaders/ravu-zoom-r4.hook

deband = yes

High anime4k shaders.
```

Now able to manage these with 35ms frame times:

```
scale = lanczos
cscale = lanczos
dscale = lanczos

glsl-shader = E:/Softwares/Video Player\mpv/shaders/KrigBilateral.glsl
glsl-shader = E:/Softwares/Video Player\mpv/shaders/Anime4K_Upscale_DTD_x2.glsl
```

**Comment by ValZapod** [comment]
Mpv uses zscale by default, lanczos with 3 taps. You can for example use lanczos with 2 taps, that will be faster.

**Comment by Obegg** [comment]
Off-topic but if you change the screen settings on windows from 60hz to 23.967hz, doesn't it automatically change the value of color format and bit depth to a lower setting?

**Comment by ValZapod** [comment]
> screen settings on windows from 60hz to 23.967hz, doesn't it automatically change the value of color format and bit depth to a lower setting?

The opposite if you do not have 3090 nvidia card and hdmi 2.1.

**Comment by Shashank066** [comment]
> Off-topic but if you change the screen settings on windows from 60hz to 23.967hz, doesn't it automatically change the value of color format and bit depth to a lower setting?

It depends. When connected to a pc monitor the colors and bit depth are fine when switching to any resolution. When connected to a TV even with hdmi 2.1, I have seen windows not switching to 10 bit RGB or YUV 444 on both Nvidia and Intel. Had to create a custom resolution in Nvidia control panel or in cru to make it work.
