### ISSUE TITLE
How do I tell mpv to put volume change messages in terminal to be silent?

### ISSUE THREAD

**Issue by lierante** [mpv-player/mpv#9931]
### Important Information
<pre>
- mpv version 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
- Void Linux
</pre>
I would like to keep the position of the time counter to not move at all and I really need help figuring out how to put the volume adjust messages in the terminal on quiet mode. It would also be very helpful if anyone could tell how to put a specific mpv message in the terminal to silence itself because only a few things like the statusline is shown in the mpv manual.

![img](https://user-images.githubusercontent.com/58134273/156135382-75335cb2-2cff-448f-9b5c-50e543447f28.gif)

This is what command --quiet does as there is no specific option I can find to disable the volume messages in the terminal, instead the time counter of the song is being shut off.

![ffm_2022-03-01_16:30:12](https://user-images.githubusercontent.com/58134273/156136312-f204a31d-723d-4dbd-bae8-8ab157222c8e.gif)

**Comment by avih** [comment]
Just rebind the keys to not produce osd message, at input.conf:
```
0 no-osd add volume 2
9 no-osd add volume -2
```

See https://mpv.io/manual/master/#input-command-prefixes

**Comment by lierante** [comment]
> Just rebind the keys to not produce osd message, at input.conf:
> 
> ```
> 0 no-osd add volume 2
> 9 no-osd add volume -2
> ```
> 
> See https://mpv.io/manual/master/#input-command-prefixes

I only know a little about configurations, this is definitely the solution. Thank you!
