### ISSUE TITLE
MPV can only play video at 100x speed. How to adjust 200X speed and 300X speed?

### ISSUE THREAD

**Issue by jiutian321** [mpv-player/mpv#9932]
Do not know how to break 100 times speed, how to modify,？MPV has been updated and upgraded

### Important Information

Provide following Information:
- mpv version  mpv 0.34.0-208-gb1fb4b783b Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Tue Mar  1 17:23:18 CST 2022

- 
![image](https://user-images.githubusercontent.com/97730241/156143376-071d315c-ab4d-4257-8e84-0c3d24ba0e83.png)
uos 21.1.1
- mpv
mpv 0.34.0-208-gb1fb4b783b Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Tue Mar  1 17:23:18 CST 2022
FFmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
FFmpeg version: 4.1.8-1+dde

[mpv/options/options.c](https://github.com/mpv-player/mpv/blob/b1fb4b783bd604ffb763e88a7cee2ad9d9c2c209/options/options.c#L555)

Line 555 in [b1fb4b7](https://github.com/mpv-player/mpv/commit/b1fb4b783bd604ffb763e88a7cee2ad9d9c2c209)

 {"speed", OPT_DOUBLE(playback_speed), M_RANGE(0.01, 100.0)},

**Comment by avih** [comment]
> How to adjust 200X speed and 300X speed?

You can't.

The limit is 100 because the developers don't think it's useful or practical to play ay higher speeds.

> {"speed", OPT_DOUBLE(playback_speed), M_RANGE(0.01, 100.0)},

You can edit the source code and change the limit and then compile mpv, but we can't guarantee which things could break if you modify the source code.

**Comment by jiutian321** [comment]
> > 如何调整200X速度和300X速度？
> 
> 你不能。
> 
> 限制为 100，因为开发人员认为以更高的速度玩游戏没有用或实用。
> 
> > {“速度”，OPT_DOUBLE（播放速度），M_RANGE（0.01，100.0）}，
> 
> 如果您知道如何编译 mpv，那么您可以编辑源代码并更改限制，然后重新编译 mpv，但我们无法保证如果您修改源代码会破坏哪

OK  谢谢
