### ISSUE TITLE
WebVTT doesn't unescape HTML tags

### ISSUE THREAD

**Issue by rany2** [mpv-player/mpv#9934]
### Important Information

Provide following Information:
- mpv version: 0.34.1-dirty
- Platform and Version: Arch
- Source of the mpv binary: Arch repos

### Reproduction steps

1. Use WebVTT subtitle with escaped tags (`&lt;` -> `<`, etc`) 
2. `mpv` does not decode them and shows them as is

### Expected behavior

mpv should decode html tags

### Actual behavior

mpv does not decode the html tags

### Sample files

mp3: http://0x0.st/oPoX.mp3
webvtt: http://0x0.st/oPoH.txt

**Comment by dyphire** [comment]
this is an FFmpeg issue, open feature requests in ffmpeg's bug tracker to request those WebVTT features.
refer https://github.com/mpv-player/mpv/issues/7214
