### ISSUE TITLE
SRT subtitles to be covered by a blank bottom black edge when video-sync is configured

### ISSUE THREAD

**Issue by kingwwh** [mpv-player/mpv#9937]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20220227-git-b1fb4b7
- Windows Version: Windows 11

### Reproduction steps

Enabling the "video-sync = display-resample" configuration will cause the SRT subtitles to be covered by a blank black edge when moving down.It's normal without any configuration.
![screenshot](https://user-images.githubusercontent.com/100736205/156354850-949fbd0e-7f5a-49f7-b1ed-ab2bbdd981f9.png)
### Expected behavior
Fix bug

### Actual behavior
Fix bug

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by kingwwh** [comment]
<img width="249" alt="conf" src="https://user-images.githubusercontent.com/100736205/156355235-31756e7d-a5cf-4667-a8a1-4a073c5ce7a8.png">
Configuration above

**Comment by zhongfly** [comment]
> Configuration above

upload configuration or paste will be better than a picture

**Comment by kingwwh** [comment]
priority=high
priority:ignored-issue-template
input-ipc-server=mpvpipe

ontop
save-position-on-quit
keep-open=yes
msg-level=all=debug
no-border
#fs
autofit-larger=100%x95%
cursor-autohide-fs-only
cursor-autohide=1000
no-input-default-bindings

profile=gpu-hq
vo=gpu-next
gpu-context=d3d11
hwdec=d3d11va-copy
hwdec-codecs=all
deband=no
video-sync=display-resample
video-sync-max-video-change=5

**Comment by kingwwh** [comment]
Remove the configuration in the red box, the subtitle is completely displayed, but the video is torn
![shot2](https://user-images.githubusercontent.com/100736205/156358193-3d412a6d-6e74-4c70-96a9-b1c7839da9e9.jpg)

**Comment by 1Naim** [comment]
Can reproduce with the video from issue #9928. For some reason, commenting out video-sync makes subtitles visible in the black bars (it's not supposed to, right?)

**Comment by hooke007** [comment]
It cannot be rendered in the blackbar https://github.com/mpv-player/mpv/pull/9870#issuecomment-1046040009

**Comment by 1Naim** [comment]
![image](http://midi.moe/f/npftu.png)
This screenshot apparently says otherwise (screenshot taken with sharex because it'll show the subtitles regardless if the screenshot was taken with mpv)

[Log file for what it's worth](http://0x0.st/oPNE.txt)

**Comment by kingwwh** [comment]
Set vo=gpu makes subtitles visible in the black bars，vo=gpu-next is invisible; But vo=gpu-next support Dolby vision, yet vo=gpu the color of dovi video will occur deviation

**Comment by kingwwh** [comment]
So these are contradictory.
