### ISSUE TITLE
mpv: symbol lookup error: mpv: undefined symbol: wl_proxy_marshal_flags

### ISSUE THREAD

**Issue by 0xj0hn** [mpv-player/mpv#9941]
I've encountered to this problem
Actually, when i want to run mpv, it says "mpv: symbol lookup error: mpv: undefined symbol: wl_proxy_marshal_flags."
i don't know why it occurs
- mpv version: 0.34.1
- Arch Linux (kernel: 5.15.6-arch2-1)
- i installed mpv using pacman
- i3wm : v4.20.1
- GPU driver and version
- screenshot:
![2022-03-03_10-49](https://user-images.githubusercontent.com/50566073/156515677-061534c0-3c9a-4026-9bf4-82d02fe20ba2.png)

**Comment by Dudemanguy** [comment]
This isn't an mpv issue but rather an issue with configuration on your machine. I highly doubt arch packaged this incorrectly so I am going to assume the wayland client library is outdated on your machine.
