### ISSUE TITLE
Why is "video-sync=audio" the default?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9942]
`video-sync=audio` (default):
Play a video file that is 23.978fps on a 60Hz screen, it will skip frames

`video-sync=display-resample`:
Play a video file that is 23.978fps on a 60Hz screen, it will **NOT** skip frames

It makes me wonder why it's the default...
It means that every user has to have this line (`video-sync=display-resample`) on `mpv.conf` , which adds bloat to the config.

Now I wonder if there are more options that should not be the default....

**Comment by avih** [comment]
> It makes me wonder why it's the default...

Because it's simpler. mpv doesn't need to know/guess the display refresh rate. Whenever it's time to display a new frame - simply display it.

**Comment by haasn** [comment]
It's less surprising and less prone to breakage, and most users do not even care about the duplicated frames / are used to it.

**Comment by Obegg** [comment]
> > It makes me wonder why it's the default...
> 
> Because it's simpler. mpv doesn't need to know/guess the display refresh rate. Whenever it's time to display a new frame - simply display it.

I completely understand it, but the only issue with it is the playback of videos with 23.978fps, it skips frames.
Or am I missing something here? Does it only skip frames on my PC? Is it not normal behavior? Is there a solution to the skipped frames?

**Comment by avih** [comment]
> the only issue with it is the playback of videos with 23.978fps, it skips frames.

It shouldn't skip frames. If it does for you, please file a proper bug report with logs. Otherwise we can't tell why it skips frames for you.

**Comment by Obegg** [comment]
> > the only issue with it is the playback of videos with 23.978fps, it skips frames.
> 
> It shouldn't skip frames. If it does for you, please file a proper bug report with logs. Otherwise we can't tell why it skips frames for you.

Ok, I will, but I'm afraid that the log file doesn't show dropped/skipped frames, how can I ensure they are logged?
(what do I add to `mpv.conf`?

**Comment by Obegg** [comment]
> > What do I add to mpv.conf?
> 
> Preferably you run `mpv --no-config --log-file=whatever.log <more-options-if-needed> file/to/play` so that it doesn't depend on mpv.conf at all, but where the problem does happen.

I just run `mpv --no-config --video-sync=audio --log-file=gpu-next.log --vo=gpu-next --fs --fs-screen=1 D:\TEST.mkv`,
But there is nothing inside the log file that indicates a problem, here's an example:
```
[   1.464][v][ao/wasapi] Changed property: {1155845d-d38c-419c-a121-8191b686d02c},0
[  59.240][d][cplayer] Run command: set, flags=73, args=[name="fullscreen", value="no"]
```
There is 57 seconds where nothing is logged but there are still skipped frames.

**Comment by avih** [comment]
Don't waste our time. File a proper bug report.

**Comment by ValZapod** [comment]
> Play a video file that is 23.978fps on a 60Hz screen, it will skip frames

Is you screen 60 fps or 60/1.001 fps? Because if the first there is no way to present 23.976 (actually 24/1.001) on integr 60.000 fps.

**Comment by Obegg** [comment]
> > Play a video file that is 23.978fps on a 60Hz screen, it will skip frames
> 
> Is your screen 60 fps or 60/1.001 fps? Because if the first there is no way to present 23.976 (actually 24/1.001) on integer 60.000 fps. Also, there is no way to present on less than the amount of video fps.

I am aware of that fact, but, they said
> It shouldn't skip frames. If it does for you, please file a proper bug report with logs. Otherwise we can't tell why it skips frames for you.
>
So I guess something is wrong with mpv or my pc.

**Comment by haasn** [comment]
> I am aware of that fact, but, they said

What @avih said is wrong.

**Comment by Obegg** [comment]
So, the issue I had no longer exists since I use this:
https://github.com/CogentRedTester/mpv-changerefresh
It changes the refresh rate of my screen (windows) to match the video.
I don't see how it has downsides, so if I'm wrong and I should not be using it - tell me.

**Comment by ValZapod** [comment]
That is your code @haasn that does not turn on interpolotation in the case I mentioned above, and there is no way to fix it due to a bug in mkv container that somehow corrupts vsync timings.

> refresh rate of my screen (windows) to match the video.

It is all good! MPC also has such functinality.

**Comment by haasn** [comment]
>  I don't see how it has downsides, so if I'm wrong and I should not be using it - tell me.

If it has no downsides for you, keep using it. I would not like my monitor to randomly change fps just because I'm watching a lowres video. It's also not cross platform :)

**Comment by ValZapod** [comment]
> I would not like my monitor to randomly change fps just because I'm watching a lowres video

What resolution has to do with fps? After all there are only 2 movies on Blu-ray that are 60/1.001 fps. Everything else is either 24/1.001 or 24. Ome rare ones are 25.
