### ISSUE TITLE
Make --no-border behave normally like --border does

### ISSUE THREAD

**Issue by iiiGerardoiii** [mpv-player/mpv#9943]
### Important Information
- mpv version: 0.34.0
- Windows Version: 10
- Possible screenshot or video of visual glitches: https://a.pomf.cat/fygqrz.mp4

### Description
I've searched for `--no-border` issues and didn't find anything related to what I'm looking for. Feel free to delet this if it was already talked about and I missed it.

I like mpv with `no-border` on because it looks cleaner/simpler and because I like to put the video on the right half of my ultrawide moniter and a titlebar would waste a good portion of the video size. With `--no-border` the video can be as big as possible without being maximized. **But `--no-border` behaves quite weird, at least on Windows.**

Certain features don't work, or work incorrectly when using `--no-border` on Windows 10, I'll name a few:
- Pressing Win+RIGHT or Win+LEFT doesn't do anything, it should snap the window to the left or right portion of the screen.
- Dragging the video to the left/right edge of the screen won't snap it either.
- Win+UP doesn't maximize the video (pressing 🗖 on the OSC makes it go fullscreen though).
- The window doesn't resize properly when resized through PowerToys' FancyZones. It moves it to its correct position, but doesn't resize it.

All the examples mentioned above work correctly when using `--border=yes`, it even adds letterboxing/pillarboxing when the window ends up having different proportions.

I've recorded a short video showing what I described:
https://a.pomf.cat/fygqrz.mp4

It would be nice to have the `--no-border` behave exactly as if it was a normal window, but with the borders and titlebar invisible of course. Is such thing possible?

**Comment by avih** [comment]
mpv doesn't handle any of mentioned key presses and doesn't do the snapping itself. Windows does. But apparently Windows doesn't do that for windows without border.

> FancyZones is a window manager utility for arranging and snapping windows into efficient layouts ...

I haven't tried it, but I guess it's similar here, Windows probably doesn't apply snapping behavior to windows without borders.

**Comment by satvikpendem** [comment]
Did you find any solution to this @iiiGerardoiii? I just ran into the same issue

**Comment by kasper93** [comment]
> Did you find any solution to this [@iiiGerardoiii](https://github.com/iiiGerardoiii)? I just ran into the same issue

`--no-title-bar --border`

**Comment by iiiGerardoiii** [comment]
what the fuck @kasper93 how long has this `title-bar` option been on mpv? it just works thank you.

>Did you find any solution to this @iiiGerardoiii? I just ran into the same issue

Yes @satvikpendem I just found out about now, just use `--title-bar=no` (@kasper93 wrote it incorrectly)

**Comment by satvikpendem** [comment]
Actually Windows 11 with `--no-border` works fine with PowerToys' FancyZones, it might just be an issue on Windows 10.

**Comment by timespacedecay** [comment]
> Actually Windows 11 with `--no-border` works fine with PowerToys' FancyZones, it might just be an issue on Windows 10.

Hm, not working for me on Windows 11.  Can only get proper resizing with FancyZones when using bordered mode.

Edit: Did not work with the unofficial Windows Store version of mpv, which apparently is version 0.36.0.  Used `winget install "mpv (shinchiro build)"` to install 0.41.0 and it works now.
