### ISSUE TITLE
After compiling, it can be opened and used successfully. The shortcut icon in the start menu has picture color, but the shortcut image is not displayed when you right-click to choose the opening mode. The shortcut can be used, which is white

### ISSUE THREAD

**Issue by jiutian321** [mpv-player/mpv#9944]
### Important Information

Provide following Information:
- mpv version mpv 0.34.0-208-gb1fb4b783b-dirty Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects

- Linux Distribution and Version  uos21.2    https://www.chinauos.com/resource/download-home

![Uploading image.png…]()

After compiling, it can be opened and used successfully. The shortcut icon in the start menu has picture color, but the shortcut image is not displayed when you right-click to choose the opening mode. The shortcut can be used, which is white

![Uploading image.png…]()

**Comment by avih** [comment]
Please follow the issue template:
- Log.
- Exact steps to reproduce the issue so that a developer can follow them and actually see the issue.
- What you expect to happen.
- What happens instead.

**Comment by avih** [comment]
> Please follow the issue template:

If you intend to do that, please do that in a new issue. Thanks.
