### ISSUE TITLE
Half floating-point data type support status for shaders

### ISSUE THREAD

**Issue by agyild** [mpv-player/mpv#9945]
As the title suggests I would like to learn the current support available for `float16_t` and related data types for shaders in mpv.

**Comment by haasn** [comment]
There's no support currently. What do you need them for?

**Comment by agyild** [comment]
I was looking for various ways into optimizing FSR, and apparently packed half float versions are faster with new hardware. It is not something that is absolutely needed, but I was curious if they were available so I could give them a try to see how they work.

**Comment by haasn** [comment]
I can try adding support for it, I suppose. It might actually speed up some of our internal shaders, too. We use a lot of 16-bit float precision stuff already (e.g. FBO textures).

**Comment by agyild** [comment]
If it is something that can benefit mpv in general, why not? I guess all the shaders would benefit from it. But I suppose it only benefits newer hardware, and you have to fallback to float32 when it is not supported. At least that's what I gather from AMD documentation.

**Comment by haasn** [comment]
So I gave an implementation a quick try but the major issue is that GLSL cannot auto-lift `float` to float16_t`. This is a huge pain, requiring manual casts literally everywhere.

I have a hard time seeing anybody using it without at least some set of helper macros or something to facilitate this casting.

**Comment by haasn** [comment]
Also, I'm not sure how we can sample from textures directly in float16 format. There's [an extension](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_16bit_storage.txt) to load them to/from storage buffers, but that one doesn't cover storage images.. which would be our main use case.

I'm also not sure if this extension technically allows you to put 16-bit floats into shared memory either, which would be the other huge benefit of using 16-bit floats.
