### ISSUE TITLE
How to get image ( jpeg/png ) file resolution ( specifically, height ) BEFORE loading the file?

### ISSUE THREAD

**Issue by subluminal-byte** [mpv-player/mpv#9946]
I'm on Debian 11, using mpv 0.32.

I've been experimenting with using mpv as an image viewer. Works great.

https://github.com/occivink/mpv-image-viewer

That helped to get started. Great repo.

I want to load profiles depending on image height. I've doing this successfully for video files using this lua script.

`local utils = require 'mp.utils'

local profile = {
	ud = "UD",
    fhd = "FHD",
    hd = "HD",
	sd = "SD"
}

local function set_profile()
	if  mp.get_property_number("height") >= 1440 then
        mp.commandv("apply-profile", profile.ud)
    elseif  mp.get_property_number("height") >= 1080 and mp.get_property_number("height") < 1440 then
		mp.commandv("apply-profile", profile.fhd)
    elseif  mp.get_property_number("height") >= 720 and mp.get_property_number("height") < 1080 then
		mp.commandv("apply-profile", profile.hd)
    else
		mp.commandv("apply-profile", profile.sd)
	end
end

mp.register_event("file-loaded", set_profile)
`

It works great for videos but not for images. Probably because image file has 1 frame.
The error log says the script is trying to compare with nil value.

Also worth mentioning, status-line lua script by occivink, shows dheight AFTER loading the file.

How do I load the dheight info BEFORE loading the file and hence apply conditional profiles??

Any help would be much appreciated. Thank you for creating, developing and maintaining what I consider the best video ( and occasionally image ) player/viewer in any platform.

Cheers !

**Comment by guidocella** [comment]
```lua
mp.add_hook('on_preloaded', 50, function ()
    mp.get_property_native('track-list/0/demux-h')
end)
```

Or just observe height, this fires later but is more accurate:
```lua
mp.observe_property('height', 'native', function (_, value)

end)
```

**Comment by subluminal-byte** [comment]
Thanks @guidocella . Used observe_property. Works perfectly.
