### ISSUE TITLE
Segmentation fault with --hwdec=auto-safe

### ISSUE THREAD

**Issue by txgk** [mpv-player/mpv#9947]
When `hwdec` is set to `auto-safe` and hardware decoding isn't supported mpv just crashes. It took some time for me to find out that problem is in `hwdec` option in config. Yeah, I know that man page explicitly says that setting `hwdec` in config for regular use is discouraged, but should it really be that edgy? It is `auto-safe` after all.

By the way, thank you for the best media player in the world!

### Important Information

* `mpv --version`

```
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1
```

* Linux distribution

Alpine Linux Edge

* Source of the mpv binary

https://pkgs.alpinelinux.org/package/edge/community/x86_64/mpv

* `icewm --version`

```
IceWM 2.9.6, Copyright 1997-2012 Marko Macek, 2001 Mathias Hasselmann.
```

* `glxinfo | grep Device`

```
    Device: Mesa Intel(R) HD Graphics 500 (APL 2) (0x5a85)
```

### Reproduction steps

1. Get a video encoded with codec that does not have support for hardware decoding
2. Play it with `mpv --no-config --hwdec=auto-safe --log-file=mpv-log.txt video-file.mp4`

### Expected behavior

Mpv prints out a message with info about inability to use hardware decoding and exits

### Actual behavior

Mpv segfaults

### Log file

[mpv-log.txt](https://github.com/mpv-player/mpv/files/8191125/mpv-log.txt)

**Comment by sfan5** [comment]
A gdb backtrace would be useful here. The log file suggests that the crash could be inside the iHD vaapi driver.

**Comment by txgk** [comment]
Here it is: [gdb-output.txt](https://github.com/mpv-player/mpv/files/8191175/gdb-output.txt)

**Comment by philipl** [comment]
While `iHD` does technically support Apollo Lake, that hardware is old enough that it's not terribly well supported. I'd recommend trying the i965 va driver instead.

**Comment by txgk** [comment]
Setting `LIBVA_DRIVER_NAME` environment variable to `i965` saved the day... I didn't know my machine is so old it requires to fiddle with the environment :<
