### ISSUE TITLE
gpu-next: Assertion triggered when gpu-api=vulkan

### ISSUE THREAD

**Issue by MoSal** [mpv-player/mpv#9949]
### Important Information

Provide following Information:
- mpv version

| repo | commit |
|:----:|:----:|
| mpv | 1c49d5735dc5231b9bebcdcab5b182a7e62771d4 | 
| libplacebo | b840fbdc38fa0d1704e6e171c6428689637d4853 |

### Reproduction steps

    mpv --no-config --vo=gpu-next --gpu-api=vulkan https://archive.org/download/unsorted_files/test.ts

Assertion triggered:
https://github.com/mpv-player/mpv/blob/1c49d5735dc5231b9bebcdcab5b182a7e62771d4/video/out/vo_gpu_next.c#L187

**Comment by haasn** [comment]
Thanks, I can reproduce it. Will investigate $tomorrow.
