### ISSUE TITLE
MPV Doesn't Play Files

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#9950]
### Important Information

Provide following Information:
- mpv version:0.34.1
- macOS Version:12.2.1
- Source of the mpv binary or bundle:mpv.io

### Reproduction steps

Just try to play something.

### Expected behavior

Playing the video.

### Actual behavior

The video and audio stutter and just go nuts for no reason.

### Log file

I didn't get how to do that.

I tried deleting my config and the issue is still there.

**Comment by Akemi** [comment]
with that little information and without a log there is no way we can help you. sry.
