### ISSUE TITLE
Is there a way to completely turn off/on the OSC with a toggle/keybind

### ISSUE THREAD

**Issue by gamintoad** [mpv-player/mpv#9951]
im new to MPV and was wondering if i can turn off the OSC with a button then when i need it again ill turn it back on, any ideas?

**Comment by dexeonify** [comment]
The <kbd>DEL</kbd> key cycles between OSC visibility. See: https://mpv.io/manual/master/#keyboard-control

If you want to cycle only between `auto` and `never`, have a look at #8658 or this [user script](https://www.reddit.com/r/mpv/comments/ib0bo9/option_to_toggle_bottom_seekbar_in_osd/g1v12ku/).

**Comment by gamintoad** [comment]
> The DEL key cycles between OSC visibility. See: https://mpv.io/manual/master/#keyboard-control
> 
> If you want to cycle between `auto` and `never`, have a look at #8658 or this [user script](https://www.reddit.com/r/mpv/comments/ib0bo9/option_to_toggle_bottom_seekbar_in_osd/g1v12ku/).



> The DEL key cycles between OSC visibility. See: https://mpv.io/manual/master/#keyboard-control
> 
> If you want to cycle between `auto` and `never`, have a look at #8658 or this [user script](https://www.reddit.com/r/mpv/comments/ib0bo9/option_to_toggle_bottom_seekbar_in_osd/g1v12ku/).

I'm trying to make it so the OSC appears when I press a button but when I press it again it shouldn't appear no matter what, I'm not sure if this is the solution Because I don't get how to do it specifically

**Comment by dexeonify** [comment]
Yes, that's what I was talking about. Have you look at the reddit thread? It does exactly what you want and provided all the steps. 

> I'm trying to make it so the OSC appears when I press a button but when I press it again it shouldn't appear no matter what

What you are looking for is to cycle the OSC visibility between `always` and `never`. Change 'auto' to 'never' in the script.
```lua
    ...
    mp.commandv('script-message', 'osc-visibility',
        osc_always_on and 'always' or 'auto'
    )
    ...
```
Then, place the script file inside your scripts folder and assign a keybind in `input.conf` (also explained in the reddit comment). If you don't know where's the script folder, see https://mpv.io/manual/master/#files-on-windows.

**Comment by gamintoad** [comment]
> Yes, that's what I was talking about. Have you look at the reddit thread? It does exactly what you want and provided all the steps.
> 
> > I'm trying to make it so the OSC appears when I press a button but when I press it again it shouldn't appear no matter what
> 
> What you are looking for is to cycle the OSC visibility between `always` and `never`. Change 'auto' to 'never' in the script.
> 
> ```lua
>     ...
>     mp.commandv('script-message', 'osc-visibility',
>         osc_always_on and 'always' or 'auto'
>     )
>     ...
> ```
> 
> Then, place the script file inside your scripts folder and assign a keybind in `input.conf` (also explained in the reddit comment). If you don't know where's the script folder, see https://mpv.io/manual/master/#files-on-windows.

sorry ! i did look but i didn't understand it, but now it makes sense im stupid , it works now though ! thanks I appreciate it
