### ISSUE TITLE
How to get subtitles to load from a folder with the same name as the video file?

### ISSUE THREAD

**Issue by sharunkumar** [mpv-player/mpv#9952]
I have these two configurations in my mpv.conf:

```conf
sub-file-paths=Subs;subs
sub-auto=all
```

and this is the folder structure of my  show:
```
My.Awesome.Show
|   My.Awesome.Show.S01E01.mp4
|   My.Awesome.Show.S01E02.mp4
|   ...
|   
\---Subs
    +---My.Awesome.Show.S01E01
    |       2_English.srt
    |       3_English.srt
    |       4_Spanish.srt
    |       5_Portuguese.srt
    |       
    +---My.Awesome.Show.S01E02
    |       2_English.srt
    |       3_English.srt
    |       4_Spanish.srt
    |       5_Portuguese.srt
    |       
    +   ...
```

MPV doesn't seem to load the subtitles from these directories automatically unless I cherry pick the ones I want and rename it in the top level directory `Subs`, like so:

```
My.Awesome.Show
|   My.Awesome.Show.S01E01.mp4
|   My.Awesome.Show.S01E02.mp4
|   ...
|   
\---Subs
    |   My.Awesome.Show.S01E01.srt
    |   My.Awesome.Show.S01E02.srt
    |   ...
```

are there any additional configurations that need to be added in order to get the subtitles to load from folders that share the same name as the video file?

**Comment by guidocella** [comment]
See https://github.com/mpv-player/mpv/issues/9767#issuecomment-1022207724

**Comment by sharunkumar** [comment]
Thanks for the comment, but from my understanding, this process adds the folders with the current file name to `sub-file-paths` property. which still requires renaming the srt files to have the file name in order to fuzzy match the subtitles? is there a function to add each srt file manually via the script? [ I am trying to use JS btw ]

**Comment by guidocella** [comment]
> requires renaming the srt files to have the file name in order to fuzzy match the subtitles

`sub-auto=all` loads all subtitles in `sub-file-paths` regardless of their filenames.

**Comment by sharunkumar** [comment]
I am using this script, but it doesn't seem to be working:

```js
function subsFolders() {
    paths = mp.get_property("sub-file-paths").split(",");
    filename = mp.get_property("filename/no-ext");

    added_paths = paths.map(path => `${path}/${filename}/*.srt`);

    mp.set_property("sub-file-paths", [...paths, ...added_paths].join(","));

    mp.osd_message(mp.get_property("sub-file-paths"))

}

mp.add_hook('on_load', 10, subsFolders);```

note: actual script is transpiled into ECMA5 when saving to scripts directory. 

I am able to get the sub paths (folders) properly in the console logs, but it doesn't seem to be loading them 🤔

**Comment by sharunkumar** [comment]
So I think I found out my mistake, when setting the `sub-file-paths`, I should give the delimiter as `;` (windows). I was assuming that since `,` is the delimiter when getting it, that I'd have to use the same while setting.

This is my final script, that expands on the existing `sub-file-paths` configuration:

```js
"use strict";

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2[i] = arr[i]; return arr2; } else { return Array.from(arr); } }

function loadSubs() {
    var paths = mp.get_property("sub-file-paths").split(",");
    var filename = mp.get_property("filename/no-ext");

    var added_paths = paths.map(function (path) {
        return path + "/" + filename;
    });

    mp.set_property("sub-file-paths", [].concat(_toConsumableArray(paths), _toConsumableArray(added_paths)).join(";"));

    mp.msg.info(mp.get_property("sub-file-paths"))
}

mp.add_hook('on_load', 10, loadSubs);
```

**Comment by guidocella** [comment]
You can use arrays directly without string conversion with `mp.get_property_native` and `mp.set_property_native`.

**Comment by mixslad** [comment]
> I have these two configurations in my mpv.conf:
> 
> ```
> sub-file-paths=Subs;subs
> sub-auto=all
> ```
> 
> and this is the folder structure of my show:
> 
> ```
> My.Awesome.Show
> |   My.Awesome.Show.S01E01.mp4
> |   My.Awesome.Show.S01E02.mp4
> |   ...
> |   
> \---Subs
>     +---My.Awesome.Show.S01E01
>     |       2_English.srt
>     |       3_English.srt
>     |       4_Spanish.srt
>     |       5_Portuguese.srt
>     |       
>     +---My.Awesome.Show.S01E02
>     |       2_English.srt
>     |       3_English.srt
>     |       4_Spanish.srt
>     |       5_Portuguese.srt
>     |       
>     +   ...
> ```
> 
> MPV doesn't seem to load the subtitles from these directories automatically unless I cherry pick the ones I want and rename it in the top level directory `Subs`, like so:
> 
> ```
> My.Awesome.Show
> |   My.Awesome.Show.S01E01.mp4
> |   My.Awesome.Show.S01E02.mp4
> |   ...
> |   
> \---Subs
>     |   My.Awesome.Show.S01E01.srt
>     |   My.Awesome.Show.S01E02.srt
>     |   ...
> ```
> 
> are there any additional configurations that need to be added in order to get the subtitles to load from folders that share the same name as the video file?

i have the same problem when watching tv shows. i am using fuzzydir, do i need to edit this script? 

my mpv.conf while using fuzzydir

sub-auto=all
sub-file-paths=**

**Comment by mixslad** [comment]
> I am not familiar with fuzzydir, the script I posted should work without it. it basically takes each path from `sub-file-paths` and appends the file name on to it. it that works with fuzzydir configuration, then there's no need to edit

lets say i remove the fuzzydir script, should i make a new script base of yours? 
cus i can still autload the subs without fuzzydir scripts with this mpv.conf

sub-file-paths=Subs;subs
sub-auto=all

**Comment by mixslad** [comment]
sub-auto=all
sub-file-paths=Subs

this is my current mpv.conf with out the fuzzydir. can you point me which script should i copy and whats the name of the script should i name it.

**Comment by sharunkumar** [comment]
> sub-auto=all
> sub-file-paths=Subs

This is the same configuration that I have. and you can use the script mentioned here: https://github.com/mpv-player/mpv/issues/9952#issuecomment-1059961050

**Comment by mixslad** [comment]
> > sub-auto=all
> > sub-file-paths=Subs
> 
> This is the same configuration that I have. and you can use the script mentioned here: [#9952 (comment)](https://github.com/mpv-player/mpv/issues/9952#issuecomment-1059961050)

i did create a script name sub-file-paths.lua but it doesnt work tho for tv shows with two subsdirectory.

**Comment by sharunkumar** [comment]
its JavaScript so you have to name it with `.js` extension

**Comment by mixslad** [comment]
> its JavaScript so you have to name it with `.js` extension

do i need another folder for this specific file?

**Comment by sharunkumar** [comment]
I just put it in the scripts folder

**Comment by mixslad** [comment]
> I just put it in the scripts folder

it works now. but is there a way that can only load english.srt file?

**Comment by mixslad** [comment]
> I am not sure of that. I am fairly new to this scripting and I only learned about adding the directories here 😅

lol same here but thanks anyway for the response.

**Comment by guidocella** [comment]
> is there a way that can only load english.srt file?

Use `slang=en,eng` or whatever is the language code of your subtitles, you can check it with F9.

**Comment by sharunkumar** [comment]
@guidocella hey, so doing this method has a sort of a bug

when I am in a folder with all the video files and launch mpv with `mpv .` command, it loads the subs as expected,

but when the second video starts playing, the subs folder list doesn't refresh, and so both the first and second video's subtitles get loaded for the second video, and it keeps adding up the more videos I move forward

what would you suggest to add to my script in this case?

**Comment by guidocella** [comment]
That's because your script appends to `sub-file-paths` on each file played, so mpv searches in all the directories of the previous filenames. If you use my script from https://github.com/mpv-player/mpv/issues/9767#issuecomment-1022207724, it doesn't have this issue because it onlys sets `sub-file-paths` to `'Subs/' .. mp.get_property('filename/no-ext')` for each file.

**Comment by sharunkumar** [comment]
Yes I had written the script the way I did to extend the functionality of the `sub-file-paths` configuration. I had assumed that the configuration would reload before each file played, but it doesn't seem like that's the case now. Is there a way to force the configuration to reset before I append the paths?

**Comment by guidocella** [comment]
Just save the initial value in a variable.
