### ISSUE TITLE
Pass multiple 'referrer' links in mpv.conf

### ISSUE THREAD

**Issue by krahjndzfix** [mpv-player/mpv#9958]
I haven't found a way, it only executes the last referrer link. Is there a way?

**Comment by krahjndzfix** [comment]
> Use the `--http-header-fields` option perhaps:
> 
> `mpv --http-header-fields-add="Referer: http://localhost,Referer: http://example.com" <URL>`

I have a playlist (+playlistmanager.lua) and I need to pass multiple referrers, cannot do it with mpv.conf and can't do it in .m3u file with something like #EXTVLCOPT. `http-header-fields` has the same behaviour as `referrer` in this matter.

**Comment by THEGOLDENPRO** [comment]
Did you find a fix to this, I noticed you closed this.
