### ISSUE TITLE
CPU usage higher than mplayer2

### ISSUE THREAD

**Issue by naoliv** [mpv-player/mpv#996]
With a simple "mplayer2 file.mp3" versus "mpv file.mp3", I see mplayer2 using 3.3~3.8% while with mpv I see 2 threads: one using 5.2~5.7% and another using 1.9%

$ mpv --version     
mpv 0.4.2 (C) 2000-2014 mpv/MPlayer/mplayer2 projects
 built on 2014-07-26T10:31:23
libav library versions:
   libavutil       53.3.0
   libavcodec      55.34.1
   libavformat     55.12.0
   libswscale      2.1.2
   libavfilter     4.2.0
   libavresample   1.1.0

**Comment by wm4** [comment]
Never found out the reason. Maybe it's because the mpv playloop does a bit too much each iteration.
