### ISSUE TITLE
Display sizes and screenshots are screwy.

### ISSUE THREAD

**Issue by markfilipak-windows** [mpv-player/mpv#9960]
### Important Information

Provide following Information:
- mpv version
mpv 0.34.0-221-g1c49d5735d Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects built on Sun Mar  6 22:44:00 +08 2022
FFmpeg library versions:
   libavutil       57.22.100
   libavcodec      59.22.100
   libavformat     59.17.103
   libswscale      6.5.100
   libavfilter     8.27.100
   libswresample   4.4.100
FFmpeg version: git-2022-03-06-10c2ef1c

- Platform and Version
Windows 10-1809
- Source of the mpv binary
Sourceforge

### Actual behavior

'mpv %1' display is 1800x1350, should be 640x480. Screenshot is 720x540, should be 640x480.

'mpv --video-aspect-method=bitstream %1' -- display is 1800x1350, should be 640x480. Screenshot is 720x540, should be 720x480 (I think).

'mpv --video-aspect-method=container %1' -- display is 1800x1350, should be 640x480. Screenshot is 720x540, should be 640x480 (I think).

'mpv --video-aspect=0 %1' -- display is 1800x1200, should be 720x480. Screenshot is 720x480 (okay, I think).

Note: If it seems I'm unsure, it's because I'm unsure, and the documentation doesn't help. But it seems that all this behavior changed about 1/2 year ago. It used to make sense, but now appears to make (almost) no sense.

### Sample files

The sample is the 7.441 second, 640x480, 20th CENTURY FOX HOME ENTERTAINMENT logo splash video.

**Comment by markfilipak-windows** [comment]
TheAMM wrote: "You can't just create a "this file plays back weird" issue and omit the log file and the sample"
Sorry. There are 4 cases, so I could make 4 log files. Which log file would you like? They don't contain anything informative. MPV behavior changed a while back, but it's not generating any errors.
What is the expected behavior of the commands? I don't know. For example, the display of a 4:3 DVD video is 1800x1350. Why? A screenshot is 720x540 instead of 640x480. Why?
If you play a 4:3 DVD video, what do you see?
Yes, I know the aspects are 4:3, but the sizes aren't right. That matters.
TheAMM wrote: "...IRC after UTC midnight..." The Internet is world wide. Are all MPV users and developers who might be listening only in Europe? Sorry. I'm not familiar with IRC.

**Comment by philipl** [comment]
mpv has always scaled non-square pixel content up as that preserves detail better than scaling down; and DVD video is always non square (NTSC is 720x480 and PAL is 720x576). So 4:3 resolution DVD content will be scaled up to 720x540 rather than down to 640x480. Similarly, widescreen PAL content will be scaled to 1024x576 rather than down to 720x405). And so on.

**Comment by markfilipak-windows** [comment]
> mpv has always scaled non-square pixel content up as that preserves detail better than scaling down;

Sure, if that's what a user wants. But it (e.g. 720x540) is the default. How can I defeat the default?

How about 16:9 DVD? If MPV does the same thing, then the result will be 720x405! Do you mean that MPV will throw away 75 lines?

> and DVD video is always non square (NTSC is 720x480 and PAL is 720x576). So 4:3 resolution DVD content will be scaled up to 720x540 rather than down to 640x480. Similarly, widescreen PAL content will be scaled to 1024x576 rather than down to 720x405). And so on.

So MPV interpolates additional lines for SAR < 1, or additional dots/line for SAR > 1, eh? That's fine when a user chooses full screen, but what about when a user wants to confirm what is actual?

How can I defeat that behavior and get true results? I've tried everything I could find.

Thank you.

**Comment by philipl** [comment]
What's your definition of true results? The only unscaled version you can have is going to be distorted by the non square pixels. You can get that, if you want by setting the `--video-aspect-override`. If you set that to `1.5`, then 720x480 DVD content will render at 720x480. Anything else involves a scaling operation.

**Comment by philipl** [comment]
NTSC DVD will be scaled to 848x480.

**Comment by markfilipak-windows** [comment]
> What's your definition of true results? The only unscaled version you can have is going to be distorted by the non square pixels. You can get that, if you want by setting the `--video-aspect-override`. If you set that to `1.5`, then 720x480 DVD content will render at 720x480. Anything else involves a scaling operation.

True results: Showing what's stored in the video. I can demonstrate/measure SAR via 'mpv --video-aspect=0 %1' and I can demostrate/measure DARx1.125 via 'mpv --video-aspect-method=container %1', then show how PAR bridges between the two, but DARx1.125 complicates that showing.

> NTSC widescreen DVD will be scaled to 848x480.

Huh? Not 853x480?

**Comment by markfilipak-windows** [comment]
THE question: Is there an MPV setting/argument that will display 4:3 ersatz-NTSC as 640x480?

**Comment by philipl** [comment]
Sorry, I meant 854x480 (maybe it's 853, can't remember).

What's stored in the video is 720x480. If you want anything else, you are making some sort of scaling operation so you are no longer looking at what was stored.

Anyway, I do agree that it's somewhat surprising how hard it is to get it to display at a specific size but you can use `--window-scale=0.889` to 'undo' the scale up. Internally, the scaling path will scale directly from the original to the output and not do a scale up followed by a scale down.

**Comment by markfilipak-windows** [comment]
Do you see the inconsistency I see?
```
COMMAND                                            SCREENSHOT
'mpv --video-aspect-method=container 640x480.VOB'   720x540 <= should be 640x480 [note 1]
'mpv --video-aspect=0 640x480.VOB'                  720x480 (confirmed)
'mpv --video-aspect-method=container 768x576.VOB'   768x576 <= [note 2]
'mpv --video-aspect=0 768x576.VOB'                  720x540 <= [note 3]
'mpv --video-aspect-method=container 853x480.VOB'   853x480 (confirmed)
'mpv --video-aspect=0 640x480.VOB'                  720x480 (confirmed)
'mpv --video-aspect-method=container 1024x576.VOB' 1024x576 (confirmed)
'mpv --video-aspect=0 1024x576.VOB'                 720x576 (confirmed)

```
[note 1] The "intended" display has 480 lines, not 540 lines -- "intended" is from MPEG2-PS specification.
[note 2] I don't have a 4:3 ersatz-PAL source video to test, so the 768x576 screenshot is my presumption.
[note 3] I don't have a 4:3 ersatz-PAL source video to test, so the 720x540 screenshot is my presumption.

**Comment by philipl** [comment]
mpv prioritizes retaining information, and that means it scales up when normalising non-square pixels. The screenshot you get from mpv is a reflection of the playback state. if you want fine-tuned control over frame captures of DVD video where you have specific requirements that are independent of playback behaviour, then mpv is the wrong tool for the job.

**Comment by markfilipak-windows** [comment]
So much for feedback from users, eh?

**Comment by Hrxn** [comment]
Providing a sample *might* help, bud..

**Comment by markfilipak-windows** [comment]
> Providing a sample _might_ help, bud..

Okay, but first, may I recap what I've learned so far?
I'm using 2 MPV arguments: 1, To produce a screenshot having DAR proportions, and 2, To produce a screenshot having SAR proportions.
My sources are 4 DVD samples: 16:9 ersatz-PAL, 4:3 ersatz-PAL, 16:9 ersatz-NTSC, and 4:3 ersatz-NTSC.
That's 8 total screenshots.
The only case that produces surprising results is 4:3 ersatz-NTSC DAR.
Instead of being 640x480, it's 720x540 -- DAR is 4:3 (correct), but the dimensions: 720x540, are wrong.
All I ask is for an MPV argument that I can pass on to users that does produce 640x480 without having to know in advance that the video is 4:3 ersatz-NTSC (which users will not know because it what they will be trying to ascertain).

May I suggest this: 'mpv --dar' to play a video at whatever the real DAR is, and 'mpv --sar' to play a video at whatever the real SAR is? Of course, any other argument(s) that produce the expected results is fine, but regarding 4:3 ersatz-NTSC DAR, I haven't discovered such argument(s).

Regarding your request for a sample, here is the 720x540 screenshot.

![MPV = 720x540 '20th CENTURY FOX'](https://user-images.githubusercontent.com/45295408/157511842-1060bc32-9b98-4abe-aee3-b9c16b0d2525.png)

**Comment by markfilipak-windows** [comment]
May I comment further?

Complicating all of this is that users may not have their TVs set up properly. For examples, I still see many people who have their TVs set up to show 'fat faces' -- that is, they are filling a 16:9 TV with a 4:3 image. When I ask them why, they say they want to see the whole picture. When I fix their TV so that it doesn't 'fat face', they say it doesn't look right -- They have become so used to 'fat face' that anything else doesn't look right. Now, you might think that such people don't really give a s**t and won't be extracting video or transcoding video but, believe it or don't, they do give a s**t about that! Many people have simply given up trying to understand video and have quit trying.

**Comment by ValZapod** [comment]
Jpeg can also have nonsqure pixels (pixel aspect ratio not 1), but that is not supported by anything except maybe ffmpeg. See http://frs.badcoffee.info/PAR_AcidTest/

So your image view may be just buggy.
