### ISSUE TITLE
Runtime directory not set in environment

### ISSUE THREAD

**Issue by Breach344** [mpv-player/mpv#9961]
### Important Information

Provide following Information:
- mpv 0.34.1
- Kali Linux / Release 2022.1

### Reproduction steps

1. Run `mpv https://www.youtube.com/watch?v=dQw4w9WgXcQ`

### Expected behavior
Loads video and plays
### Actual behavior
Returns an error:
 (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: Rick Astley
 Channel_URL: https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw
error: XDG_RUNTIME_DIR not set in the environment.
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Listing DRM devices with drmGetDevices failed! (No such file or directory)
[vo/gpu/opengl] Failed to find a usable DRM primary node!
[vo/gpu/opengl] Failed to create KMS.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
[vo/sdl] SDL_Init failed
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)

### Log file

https://drive.google.com/file/d/1H2nUVKioWwKC3BjyAIGwsBkbIZNOVAoB/view?usp=sharing

### Exactly what I've been typing

https://docs.google.com/document/d/13TD4EcuLcI2B_j27cquQrjyBPnYMTXgfGfMe1iI6Bug/edit?usp=sharing

### Additional Info

Im not sure if this is the issue or the path to fixing it but when I I tried `echo $DISPLAY` it returned nothing. It was just blank.  Next I used `export DISPLAY=MYIPADDRESS:0.0` and tried `echo $DISPLAY` which returned what I set it to. After doing that and running `mpv https://www.youtube.com/watch?v=dQw4w9WgXcQ` it returns:
 (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: Rick Astley
 Channel_URL: https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw
error: XDG_RUNTIME_DIR not set in the environment.
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Listing DRM devices with drmGetDevices failed! (No such file or directory)
[vo/gpu/opengl] Failed to find a usable DRM primary node!
[vo/gpu/opengl] Failed to create KMS.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
[vo/sdl] SDL_Init failed
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)

So looks to be no difference. I have no idea what I'm doing.

**Comment by Dudemanguy** [comment]
XDG_RUNTIME_DIR is normally created by logind/elogind. For mpv, I wouldn't think this matters for trying to run on drm (which is what you appear to be doing), but admittedly, I didn't try it. Also, that is not a complete log file. Please use `--log-file`.

**Comment by Breach344** [comment]
> XDG_RUNTIME_DIR is normally created by logind/elogind. For mpv, I wouldn't think this matters for trying to run on drm (which is what you appear to be doing), but admittedly, I didn't try it. Also, that is not a complete log file. Please use `--log-file`.

I tried using the `'-v -v` and `--log-file=output.txt` the issue template says to use but it returns:
-bash: MYCOMMAND: command not found

for both. I really dont know much about operating systems and command terminals so if I'm not typing the correct things please let me know. I can use `cd /var/log` then `ls` to comb through some different logs if any of them are helpful. I have gone back and did everything again along with things like `cd /var/log/` to update my log file with any potentially useful information.

**Comment by Dudemanguy** [comment]
I have no idea what you're typing but try:

`mpv --log-file=output.txt https://www.youtube.com/watch?v=dQw4w9WgXcQ`

**Comment by Breach344** [comment]
> I have no idea what you're typing but try:
> 
> `mpv --log-file=output.txt https://www.youtube.com/watch?v=dQw4w9WgXcQ`

Thank you. I have copy and pasted your command but get the exact same result returned.

https://docs.google.com/document/d/1jPnejTYlJKdWv-KIohgx7KOqfaFZdmee3DubVd2LBXA/edit?usp=sharing

**Comment by Dudemanguy** [comment]
Please share the actual log file (`output.txt`).

**Comment by Breach344** [comment]
> Please share the actual log file (`output.txt`).

My apologies. Here we go.

https://drive.google.com/file/d/1H2nUVKioWwKC3BjyAIGwsBkbIZNOVAoB/view?usp=sharing

**Comment by Dudemanguy** [comment]
Just for clarity, are you trying to run mpv on a tty?

**Comment by Breach344** [comment]
> Just for clarity, are you trying to run mpv on a tty?

No. All I want to be able to do is just open up my laptop, open Kali Linux, type in `mpv WHATIWANTTOWATCH` and have it open up the mpv tab and play the video. Thank you for your continued assistance.

**Comment by Dudemanguy** [comment]
Oh okay so that means you're failing to make both a wayland and xorg connection. Since `XDG_RUNTIME_DIR` is not properly configured on your machine for some reason, I could imagine that being a problem on wayland (not being able to find the wayland socket which is typically in that directory). For xorg, I wouldn't think this should matter so you *should* have at least spawned an xorg window but maybe whatever configuration you're using is wayland only and doesn't use xwayland. Who knows.

Anyways, the tl;dr on this is basically that your environment is really funky and not configured correctly so this is not an mpv issue. I would suggest fixing the `XDG_RUNTIME_DIR` issue. That environment variable is normally set by systemd or elogind.
