### ISSUE TITLE
Q: Possible for script to update value in GLSL?

### ISSUE THREAD

**Issue by polarathene** [mpv-player/mpv#9967]
### Current question - Update shader parameter values via scripts?

It seems like presently it's not possible to pass custom data to a shader? I have seen scripts have access to data like [mouse position](https://github.com/dfaker/VR-reversal/blob/de5ba0fc41ef9475189cc0a1064c5f2c90b88c87/360plugin.lua#L256) but that is not possible for a shader to use? (relatively new to shaders)

Related to that lua script (_which uses ffmpeg to process frames_), there was a [shader attempt a while back](https://github.com/mpv-player/mpv/issues/2280)(un360) but they seemed to have had difficulty getting that mouse data for camera control with the shader which should be more efficient than processing via CPU with ffmpeg. I guess not much has improved on that front yet, or is dynamically updating parameter values during runtime not practical for shaders?

Just curious if this is a general issue with shaders or just the current shader support/handling with MPV?

I don't think I saw anything that would allow to interact with a shader beyond add/remove it (_which I guess works if you modify the shader file before re-adding it, but I imagine that would have poor playback performance_).

---

### Original Query - Source/List and definition of `HOOKED_` vars (Resolved)

I've looked through various issues, search engine results, github wiki, official docs and have had trouble finding much information on getting started with shaders and MPV.

Some resources of interest (for others that end up here):

- https://github.com/mpv-player/mpv/issues/9915
- https://github.com/mpv-player/mpv/issues/9692
- https://github.com/mpv-player/mpv/wiki/Video-output---shader-stage-diagram
- https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders

[hyperview](https://gist.github.com/bjin/399cb23818ad210941725ef768893499) shader uses `HOOKED_pos` (_and `_size` + `_tex` variants among other variables_), [un360](https://gist.github.com/tesu/196db5421559de3e9555d4f9da9d847d) shader like others I viewed also use these. I have looked at the [official docs](https://mpv.io/manual/stable/#options-glsl-shader) for the `--glsl-shader` option and see mention of `HOOKED` ~~but not these~~  (**EDIT:** they are covered, but referenced as `NAME_pos` instead, while it's more common to see actual scripts with `HOOKED_pos`, below that is then listing all other variables I came across, all clear now :+1: )

<details>
<summary>Quoted snippets from docs on glsl shader</summary>

> _The special name HOOKED can be used to refer to the texture that triggered this pass._

> _references to sizes of existing texture (such as MAIN.width or CHROMA.height), OUTPUT, or NATIVE_CROPPED (size of an input texture cropped after pan-and-scan, video-align-x/y, video-pan-x/y, etc. and possibly prescaled). By default, these are set to HOOKED.w and HOOKED.h, espectively._

> _To help translate texture coordinates in the absence of vertices, mpv provides a special function NAME_map(id) to map from the texel space of the output image to the texture coordinates for all bound textures. In particular, NAME_pos is equivalent to NAME_map(gl_GlobalInvocationID), although using this only really makes sense if (tw,th) == (bw,bh)._

> _Each bound mpv texture (via BIND) will make available the following definitions to that shader pass, where NAME is the name of the bound texture_

> _This is a list of the legal hook points_

</details>

So the docs do cover this, it just wasn't as easily picked up on first glance over. I was not having much luck looking for any guides with small examples explaining such. Probably because this is a rather niche topic with MPV?

It might be helpful to make a mention of these variables in the Github Wiki, or pointing to that specific part of the docs?

**Comment by butterw** [comment]
With --vo=gpu-next it is possible to pass parameters to a libplacebo shader using the PARAM bloc. The parameter will need to be int or float. 

http://libplacebo.org/custom-shaders/#tunable-parameters

In the following example the parameter is time_s (TYPE DYNAMIC float):
input.conf: F5 set glsl-shader-opts time_s="${=playback-time}"

**Comment by Dudemanguy** [comment]
Question was answered.
