### ISSUE TITLE
MPV angle context renders blue screen.

### ISSUE THREAD

**Issue by ZhenFTW** [mpv-player/mpv#9968]
### Important Information
Provide following Information:
Hi, I've been wanting to make libmpv work on my program with angle context so I can get the directx backing texture of mpv. So, I looked into the mpv-examples and port the sdl opengl code to work with angle but once I managed to make everything done, I found out that the mpv video renders in blue screen. So I tried to make it work on mpv default program using the command of mpv video.mp4 --vo=gpu --gpu-context=angle but still renders the same.

I think it has something to do with this issue.
[vo/gpu/opengl] fragment shader compile log (status=0):
[vo/gpu/opengl] ERROR: 0:4: 'image2D' : Illegal use of reserved word
[vo/gpu/opengl] ERROR: 0:4: 'image2D' : syntax error

Provide following Information:
- mpv version: mpv 0.34.0-116-gd92cf77be5(latest shinchiro build)
- Windows Version: Windows 11
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/latest/download
- Possible screenshot or video of visual glitches

By running: mpv video.mp4 --vo=gpu -gpu-context=angle --log-file=log.txt
![image](https://user-images.githubusercontent.com/17694257/157577121-bbabab33-a49d-4b81-ad6f-ffbae61595f5.png)

By using libmpv with angle on my sdl program:
![image](https://user-images.githubusercontent.com/17694257/157577217-f5033e65-637a-4ba8-b98b-cea7befb6348.png)

### Reproduction steps
I tried running with --no-config still runs the same.

### Expected behavior
Run video normally without rendering issue.

### Actual behavior
Video renders blue screen. It's only audio that works.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/8219842/log.txt)

**Comment by haasn** [comment]
Known issue fixed by 57bc5ba6d6579d5f1e6897f6915a3a940b84bb73
