### ISSUE TITLE
gpu-next tinting with a gray-scale image (lowers PSNR)

### ISSUE THREAD

**Issue by CrHasher** [mpv-player/mpv#9969]
### Important Information

Provide following Information:
- mpv-x86_64-20220306-git-1c49d57
- Windows 11
- [Source of the mpv binary](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220306-git-1c49d57.7z/download)

### Reproduction steps
Config for mpv stable:
```
deband=no
no-hidpi-window-scale
window-scale=2.0
pause=yes
no-scaler-resizes-only
```

Config for mpv gpu-next:
```
vo=gpu-next
deband=no
no-hidpi-window-scale
window-scale=2.0
pause=yes
no-scaler-resizes-only
```

Python script to calculate PSNR with ReadMe:
[_PyPSNR.zip](https://github.com/mpv-player/mpv/files/8222419/_PyPSNR.zip)

- Unzip attached zip in any location
- Start the stable mpv and take screenshot
- Start the new mpv with gpu-next take screenshot
- Put screenshots in "images" folder where you extracted PyPSNR
- Run python script: `CalculatePSNR.py images`

### Expected behavior

- PSNR close to stable default video driver in mpv windows version 0.34.0
- Most importantly there is a slight color tinting in the gpu-next version that makes the processed image by mpv `vo=gpu-next` look different than the reference one.

### Actual behavior

Different PSNR because of tinting with gpu-next

### Log file

Log stable:
[log.txt](https://github.com/mpv-player/mpv/files/8222470/log.txt)
Log gpu-next:
[log.txt](https://github.com/mpv-player/mpv/files/8222472/log.txt)

### Sample files

In the zip.

**Comment by CrHasher** [comment]
I can confirm it's fixed. For some reason PSNR is still lower for gpu-next, but not in a noticeable way.

**Comment by ValZapod** [comment]
> but not in a noticeable way.

That is still bad, we should be bit perfect. Is it possible that gpu was worse? Anyway, it looks like this "0.5" issue comes from H.273.

**Comment by haasn** [comment]
> It could be anything really...

It's impossible to say without noticing a concrete trend. There are many underlying architectural differences, different choices of FBO format, and so on. You're also using multiple features which could interfere with debugging this (judging by your log, at least), such as custom user shaders.

Ideally you would test with `--gpu-dumb-mode=yes` and `--scale=bilinear` for both.

**Comment by CrHasher** [comment]
Please send me a config file you think would be ok for testing this and I will test it.
