### ISSUE TITLE
zsh.pl [possibly] generating incorrect completion definitions for some commands

### ISSUE THREAD

**Issue by Pyrohh** [mpv-player/mpv#997]
`--fullscreen` for example, is completed to `--fullscreen=`, which isn't necessarily wrong as you can specify yes or no, but is a bit odd. The man page mentions it without the `=` as one would expect for a boolean argument. This is the case for most (all?) other boolean commands.

**Comment by qmega** [comment]
Bump. I'd really like to implement `--no-whatever` and completion for Choices values, and lose the `=` on Flags/Prints. Are we still planning to have some separate output to list possible values, or can we just parse what's there? If necessary, I'm willing to take responsibility for updating the script if `--list-options` changes.

**Comment by wm4** [comment]
Although I'd like to improve the ``--list-options`` output at some point, I currently have no concrete plans for this. So go ahead if you're fine with the idea that the output might change in incompatible ways at some point in the future.
