### ISSUE TITLE
meson: mpv_stream_cb_add_ro not exported

### ISSUE THREAD

**Issue by jas-per** [mpv-player/mpv#9971]
### mpv version and platform versions

git master on linux arm32

### Reproduction steps

use meson to build libmpv

### Expected behavior

https://github.com/jaseg/python-mpv as a libmpv-wrapper should find all exports, simple test:

`strings /usr/lib/arm-linux-gnueabihf/libmpv.so.2.0.0 | grep -i mpv_stream` should find the export name

this works with the other exports using meson and also for mpv_stream_cb_add_ro when using waf to build

### Actual behavior

`strings /usr/lib/arm-linux-gnueabihf/libmpv.so.2.0.0 | grep -i mpv_stream` finds nothing

when using python-mpv to wrap libmpv for python I get

`AttributeError: /lib/arm-linux-gnueabihf/libmpv.so.2: undefined symbol: mpv_stream_cb_add_ro`

@Dudemanguy you manually added MPV_EXPORTs in https://github.com/mpv-player/mpv/commit/20c4036daa680ebf9d379c9a7566bcf3ae12d405 - is `mpv_stream_cb_add_ro` maybe missing because its not defined in /libmpv/client.h but /libmpv/stream_cb.h? it is present in /libmpv/mpv.def ..

**Comment by Dudemanguy** [comment]
Oops, I forgot this API even existed. Give me a second.

**Comment by jas-per** [comment]
libmpv is working fine on rpi3/arm32hf with vo rpi and mmal hwdec now. thanks a lot for the meson build!
