### ISSUE TITLE
Videos from vk.com not playing, but downloads via yt-dlp.

### ISSUE THREAD

**Issue by IlyaIndigo** [mpv-player/mpv#9972]
Today I found out that I can't play vk.com videos via mpv/yt-dlp, even though they were playing yesterday.
It would seem that the problem should be found in yt-dlp, but yt-dlp downloads videos from the same URL just fine.

### Reproduction steps

/usr/bin/mpv --no-config https://vk.com/video406756414_456240853

[ffmpeg] https: HTTP error 400 Bad Request
Failed to open https://vkvd111.mycdn.me/expires/1647290800422/srcIp/178.219.171.159/pr/40/srcAg/CHROME/ms/185.226.53.155/type/2/sig/Llt0TRAfz-E/ct/8/urls/185.226.52.162/clientType/13/zs/21/id/2090981460542/video/.
Exiting... (Errors when loading file)

/usr/bin/yt-dlp https://vk.com/video406756414_456240853

[vk] 406756414_456240853: Downloading JSON metadata
[vk] 406756414_456240853: Downloading m3u8 information
[info] 406756414_456240853: Downloading 1 format(s): hls-1260
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 51
[download] Destination: Огуречная лошадка. 1985 г. [406756414_456240853].mp4
[download] 100% of 75.60MiB in 00:26
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Огуречная лошадка. 1985 г. [406756414_456240853].mp4"

### Expected behavior
Play video in mpv and download via yt-dlp.

### Actual behavior
[ffmpeg] https: HTTP error 400 Bad Request in mpv, but downloaded via yt-dlp.

### Important Information

mpv 0.34.1+git.20220203T182214.5d31c7310c Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Feb  5 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1

yt-dlp 2022.03.08.1

openSUSE Tumbleweed x86_64

**Comment by CounterPillow** [comment]
Seems to be a regression in yt-dlp. I tried it, it worked through mpv, was about to reply with "werks4me", but then decided to do my due diligence and upgraded from 2022.02.04 to 2022.03.08, at which point it stopped working in mpv but still works downloading straight with yt-dlp.

**Comment by hooke007** [comment]
Some other websites also suffer yt-dlp's recent changes. In my case, I have to roll back to the previous release https://github.com/yt-dlp/yt-dlp/releases/tag/2022.01.21 or even youtube-dl.

**Comment by zhongfly** [comment]
Through the daily build of https://github.com/ytdl-patched/yt-dlp, I tested and found that the last version of yt-dlp that can play vk video on mpv is https://github.com/ytdl-patched /yt-dlp/releases/tag/2022.03.04.40298.

**Comment by zhongfly** [comment]
I found out that the reason is that there is an error in http_headers in the json returned by yt-dlp.
User-Agent needs to be set to load the video of vk. However, the case error in the information returned by yt-dlp becomes User-agent. In the code world, case is sensitive, ytdl_hook.lua does not find User-Agent , so no User-Agent is set.
```json
    "http_headers": {
        "User-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-encoding": "gzip, deflate, br",
        "Accept-language": "en-us,en;q=0.5",
        "Sec-fetch-mode": "navigate"
    }
```

**Comment by thebombzen** [comment]
That said, HTTP Headers are case-insensitive, so perhaps ytdl_hook.lua could lowercase things first, although unsure how difficult that would be with Lua.

**Comment by Dudemanguy** [comment]
Allegedly has been fixed.
