### ISSUE TITLE
ytdl_hook.lua should set http headers from yt-dlp when format_info is "youtube-dl (separate)"

### ISSUE THREAD

**Issue by zhongfly** [mpv-player/mpv#9978]
### Expected behavior of the wanted feature
When the online video is divided into video stream and audio stream and needs to be loaded separately, ytdl_hook.lua uses the http headers provided by yt-dlp.
When there are multiple http headers, the http headers of the video stream file are used first (I think the http headers required by the video stream and the audio stream are the same in general)

### Alternative behavior of the wanted feature
ytdl_hook.lua use the `.http_headers`.
after https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua#L579 ,add `set_http_headers(json.http_headers)`

### Why
When the online video is divided into video stream and audio stream and needs to be loaded separately, ytdl_hook.lua will not use the http headers provided by yt-dlp. However, some sites needs mpv set special http headers to download their video, so the problems mentioned above will cause mpv to not be able to play this kind of video.

A practical example where this feature is needed is https://github.com/mpv-player/mpv/issues/9973 .The lack of this function makes mpv unable to play bilibili website videos with yt-dlp.
This will also fix the issue in https://github.com/mpv-player/mpv/issues/8786.

**Comment by escape0707** [comment]
Besides downloading the video in advance, is there another workaround for now?

**Comment by zhongfly** [comment]
> Besides downloading the video in advance, is there another workaround for now?
> 
> This is getting more annoying as Firefox currently can't handle hardware acceleration correctly.

I made a small modification to the script for this, and so far it does solve the problem I'm talking about, but I don't know if it will create new problems.
https://gist.github.com/zhongfly/e95fa433ca912380f9f61e0910146d7e#file-ytdl_hook_plus-lua

**Comment by escape0707** [comment]
> I made a small modification to the script for this

Do you mind publishing this as a fork of the MPV repo? That way people can easily compare the changes, and you can also send a PR later.

**Comment by zhongfly** [comment]
I thought of 2 simple modification methods (one of which is mentioned in the issue, and the other is in the script I modified), but I feel that these two solutions are not elegant, and I have not tested whether they are applicable to youtube-dl(I only use yt-dlp), or other sites with similar problems apply.
I don't mind using my ideas if anyone is willing to create a PR

**Comment by escape0707** [comment]
> > I made a small modification to the script for this
> 
> Do you mind publishing this as a fork of the MPV repo? That way people can easily compare the changes, and you can also send a PR later.

XDDD 我的意思是，能不能不发成 gist 而是 fork 一下 mpv 这个 repo 并且把修改 commit 到您的 fork 里。这样方便后来人查看您具体的修改内容，以及从您的 repo 发起 PR。

**Comment by zhongfly** [comment]
You can directly follow the method I proposed in the issue: 
create a new line after https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua#L579 , the new line contents :`set_http_headers(json.http_headers)`

**Comment by escape0707** [comment]
I'll try it now, thank you!

> https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua#L579

BTW, just a reminder.If quoting code and line number in this way, when new commit on master branch changed the quoted file, the line number will be incorrect.

**Comment by GalaxySnail** [comment]
The url is:
https://github.com/mpv-player/mpv/blob/ebaf6a6cfa24a78d9041389974568b9db7df6a71/player/lua/ytdl_hook.lua#L579

> You can directly follow the method I proposed in the issue: create a new line after https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua#L579 , the new line contents :`set_http_headers(json.http_headers)`

It's not the latest, it was modified in line 406-408 of <https://gist.github.com/zhongfly/e95fa433ca912380f9f61e0910146d7e/0f46340621415ae93a91a7f3eb60d013c5bdf542#file-ytdl_hook_plus-lua>.

By the way, I can't find `ytdl_hook.lua` in my mpv installation, is it compiled as bytecode in the mpv executable? That means users can't modify it easily, and must compile mpv by themselves. In my opinion, a PR will be helpful for more users.

**Comment by zhongfly** [comment]
> It's not the latest, it was modified in line 406-408 of https://gist.github.com/zhongfly/e95fa433ca912380f9f61e0910146d7e/0f46340621415ae93a91a7f3eb60d013c5bdf542#file-ytdl_hook_plus-lua.

As I said before, I offer 2 ways to modify it, but I can't guarantee if there are any side effects.


> By the way, I can't find `ytdl_hook.lua` in my mpv installation, is it compiled as bytecode in the mpv executable? That means users can't modify it easily, and must compile mpv by themselves. In my opinion, a PR will be helpful for more users.

`ytdl_hook.lua` is built into mpv. But you don't need to compile mpv if you want to fix the problem by modifying it.
Just put your modified `ytdl_hook.lua` (I recommend renaming it to something else) into the `scripts` folder, then set `ytdl=no` in mpv.conf to disable the built-in `ytdl_hook.lua`

**Comment by GalaxySnail** [comment]
> `ytdl_hook.lua` is built into mpv. But you don't need to compile mpv if you want to fix the problem. Just put your modified `ytdl_hook.lua` (I recommend renaming it to something else) into the `scripts` folder, then set `ytdl=no` in mpv.conf to disable the built-in `ytdl_hook.lua`

Thanks for explanitaon!

**Comment by Dudemanguy** [comment]
Should be fixed by 10416.
