### ISSUE TITLE
mpv settings and viscosity (OpenVPN) interfere with each other

### ISSUE THREAD

**Issue by therealmarv** [mpv-player/mpv#9981]
### Important Information

Provide following Information:
- mpv version: 0.34.1
- macOS Version: 12.2.1 (21D62)
- Source of the mpv binary or bundle: Homebrew
- If known which version of mpv introduced the problem: all versions

### Reproduction steps

- Install (trial works) [viscosity](https://www.sparklabs.com/viscosity/) which is a paid OpenVPN client for macOS
- Viscosity does not need to run
- Open mpv and go to "mpv -> Preferences..." menu item.

### Expected behavior

mpv preferences open

### Actual behavior

Viscosity thinks I want to import and open a new OpenVPN configuration
<img width="260" alt="image" src="https://user-images.githubusercontent.com/1050582/158171141-b7dcf25a-df05-452a-918b-d68fccbc21ed.png">

Here the configs imported after pressing four times mpv->Preferences... Viscosity thinks I've imported four new mpv named OpenVPN configs (of course they don't work).
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1050582/158171349-b32d112e-7bbe-4a8c-b866-e8397f246366.png">

**Comment by Akemi** [comment]
mpv's Preferences opens the default config file (mpv.conf) with the default app for that extension. you associated .conf files with viscosity, hence why it opens and imports it.
