### ISSUE TITLE
Q: Dolby Vision to SDR

### ISSUE THREAD

**Issue by regystro** [mpv-player/mpv#9982]
Hi.

Since last git builds support `--vo=gpu-next` for Dolby Vision reshaping, which by the way works great, I was wondering if it could be possible to dump that tone-mapped displayed version to a file.

With `mpv --vo=gpu-next P5_DVtest.mkv --o=SDR.mkv` all you get is the version before tone-mapping applied.

P5_DVtest.mkv is a Profile 5 DV sample (no HDR10 fallback).

Greetings.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/8252952/output.txt)

**Comment by haasn** [comment]
Hi. You should probably use the `vf_libplacebo` FFmpeg filter for this.

Pending documentation (tm). I'll put it on my TODO list.

**Comment by regystro** [comment]
Thank you @haasn! Inspired by your answer and https://github.com/mpv-player/mpv/issues/9589, I came up with this command line that works:

`ffmpeg -y -i P5_DVtest.mkv -init_hw_device vulkan -vf format=yuv420p,hwupload,libplacebo,hwdownload,format=yuv420p -vcodec h264_nvenc SDR.mkv`

Awesome :)

**Comment by haasn** [comment]
Great :) (You probably want to use `yuv420p10`, not `yuv420p`, since this is a 10-bit file)

**Comment by regystro** [comment]
> Great :) (You probably want to use `yuv420p10`, not `yuv420p`, since this is a 10-bit file)

Thanks for the tip! Will do when using software encoding. Unfortunately right now dealing with an old _not-10bit-encoding-capable-GPU_, and need speed over quality ;)

**Comment by haasn** [comment]
> Unfortunately right now dealing with an old not-10bit-encoding-capable-GPU, and need speed over quality ;)

What you are doing right now is software converting from 10-bit to 8-bit. If you want speed, you should do the conversion on GPU. I propose:

```
-vf hwupload,libplacebo=format=yuv420p,hwdownload,format=yuv420p
```

(This has the added bonus of working on all input files)

**Comment by regystro** [comment]
Thank you so much to both of you. Those suggestions worked like a charm and transcoding speed increased from 1.52x to 1.94x which is a huge improvement.

**Comment by ValZapod** [comment]
Ffmpeg also requires you to tag the 8 bit ycbcr correctlyfor it to be hdr. PQ at the very least + bt.2020 ncl and bt.2020 primaries.

**Comment by regystro** [comment]
I've got a question about the outcoming SDR mkv file regarding mediainfo data:
```
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 3 s 24 ms
Bit rate mode                            : Variable
Maximum bit rate                         : 120 Mb/s
Width                                    : 1920 pixels
Height                                   : 1080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Original frame rate                      : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Writing library                          : Lavc59.18.100 h264_nvenc
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```

- I've managed to change all color specs to bt709, but cannot remove the **HDR format: Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU** data. I thought `apply_dolbyvision=0` would do the trick but it didn't, and Plex complains about unsupported color space :( This is my try:

`hwupload,libplacebo=w=-2:h=1080:colorspace=bt709:color_primaries=bt709:color_trc=bt709:range=limited:apply_dolbyvision=0:format=yuv420p,hwupload=derive_device=cuda`

Any ideas?

**Comment by ValZapod** [comment]
> Any ideas?

Just -c copy without -strict unofficial.

**Comment by haasn** [comment]
Oh, it's possible that the metadata it's seeing is the dolby vision configuration record, not the actual RPU record?

**Comment by regystro** [comment]
> > but what I meant was to map from
> 
> That is too hard to do. You need zscale for this, etc.

Already accomplished with libplacebo. See https://github.com/mpv-player/mpv/issues/9982#issuecomment-1067977248.

This is my current command:
`ffmpeg -y -i P5_DVtest.mkv -map_metadata -1 -init_hw_device vulkan -vf hwupload,libplacebo=w=-2:h=1080:colorspace=bt709:color_primaries=bt709:color_trc=bt709:range=limited:format=yuv420p,hwupload=derive_device=cuda -c:v h264_nvenc -c:a aac SDR.mkv`

> You want the _opposite_, I think. `apply_dolbyvision=1` _should_ strip it from the output frames.

Same result :(

> Oh, it's possible that the metadata it's seeing is the dolby vision configuration record, not the actual RPU record?

Sorry, I don't know how to check. Here you are the sample once tone-mapped (no audio): https://0x0.st/oZ7N.mkv

**Comment by regystro** [comment]
> Just -c copy without -strict unofficial.

Didn't work, but maybe I'm missing something:

1. Download the sample from my previous post
2. `ffmpeg -i oZ7N.mkv -c copy out1.mkv`
3. `ffmpeg -i oZ7N.mkv -c copy -strict unofficial out2.mkv` (just in case)

Result: both mediainfo still show "**HDR format: Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU**"

**Comment by ValZapod** [comment]
> Didn't work, but maybe I'm missing something:

To mp4

https://user-images.githubusercontent.com/31514790/158623612-a9cbf2cb-efec-4c6c-b2fa-3eda01f8c40b.mp4

.

**Comment by regystro** [comment]
> To mp4 works, then you can just -c copy back to mkv.

All right. Or I could just transcode to mp4 in the first place, which also strips all DoVi record, and saves some steps. I was wondering if there could be a way to do it when transcoding to mkv.

**Comment by haasn** [comment]
> Sorry, I don't know how to check. Here you'll find the sample once tone-mapped (no audio): https://0x0.st/oZ7N.mkv

I had a look at it. Yeah, the dovi metadata is intact in the stream metadata:

```
Input #0, matroska,webm, from '/mem/oZ7N.mkv':
  Metadata:
    ENCODER         : Lavf59.16.100
  Duration: 00:00:10.01, start: 0.000000, bitrate: 1730 kb/s
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 2160x1080 [SAR 1:1 DAR 2:1], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc59.18.100 h264_nvenc
      DURATION        : 00:00:10.010000000
    Side data:
      DOVI configuration record: version: 1.0, profile: 5, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0
```

Apparently there's no way to suppress writing this configuration record at the moment. I'll look into it (tm)

**Comment by acedogblast** [comment]
@haasn Sorry if this is not directly releated to this issue but I have also been trying to get Dolby Vision HDR to SDR tone-mapping to work on FFmpeg that is built with libplacebo and vulkan enabled. I keep getting this error `[AVHWFramesContext @ 0x55c084bdcb40] There are no supported modifiers for the given sw_format`
`[Parsed_hwupload_0 @ 0x55c084bd5f40] Failed to configure output pad on Parsed_hwupload_0`
My ffmpeg command look like this `$FFMPEG -i "$INPUT" -map 0:v:0 -init_hw_device vulkan=gpu:0.0 -vf "hwupload,libplacebo=tonemapping=bt.2446a:colorspace=bt709:color_primaries=bt709:color_trc=bt709:range=limited:format=nv12,hwdownload,format=yuv420p" -c:v libx265 -crf 20 -preset:v slow -pix_fmt yuv420p10le "test.mkv"`

**Comment by haasn** [comment]
@acedogblast file an FFmpeg issue, this is an error coming from the ffmpeg vulkan code

cc @cyanreg

**Comment by Brainiarc7** [comment]
I have the same issue as @acedogblast , which I reported on ffmpeg trac as https://trac.ffmpeg.org/ticket/10046

**Comment by rom4ster** [comment]
Hello I tried all of this stuff, waited for a long time, AND IT DID NOT RESOLVE my green video issue. Can you guys give any reason why?
