### ISSUE TITLE
CFLAG/LDFLAGS

### ISSUE THREAD

**Issue by Alex313031** [mpv-player/mpv#9985]
Hi, I'm using waf to build on Debian 11. I can use meson if that will help with my question.

Question is, how do I set cflags and ldflags for optimizing, like how one might do in a makefile.

For example, I would like to set -O3 -s -march=haswell -mtune=haswell as cflags and -Wl,-O3 -march=haswell as ldflags to get as highly optimized a binary as possbile.
If it matters I'm also building with ./waf configure --enable-libmpv-shared so idk if building libmpv.so would take anything different.

On the other hand, I dont use waf or meson (only gcc and clang) and so maybe none of these apply anyway and there are other ways of making a binary optimized for your own machine.

**Comment by LaserEyess** [comment]
`CFLAGS` and `LDFLAGS` are set on your env, that works on any build system. A build system is not a compiler, mpv is compiled with gcc and clang so your options will work, though `-O3` probably will not do anything that helps mpv's performance.

**Comment by lavilao** [comment]
with waf is as simple as ```export CFLAGS="-march=native -O3 -pipe -fgraphite-identity -floop-strip-mine -floop-nest-optimize -fno-semantic-interposition -fipa-pta -flto -fdevirtualize-at-ltrans -flto-partition=one"```, you can after verify it on the build log

**Comment by Hello71** [comment]
`-mtune=haswell` also doesn't do anything if `-march=haswell` is specified, `-s` doesn't make the binary any faster, `-Wl,-O3` is exactly the same as `-Wl,-O` which also doesn't make the binary any faster, and "I'm also building with ./waf" contradicts "I dont use waf".

**Comment by Dudemanguy** [comment]
I think this has been sufficiently answered. meson also has the ` c_args` and `c_link_args` options if you don't want to use environment variables.
