### ISSUE TITLE
Video length displayed is incorrect for sped up videos.

### ISSUE THREAD

**Issue by Tagvi** [mpv-player/mpv#9993]
### Important Information
Version: 1:0.34.1-4
Arch Linux
MPV installed from Pacman

### Reproduction steps
Play a video like this:
mpv --speed=`anything` `video`

### Expected behavior
At the bottom of the window there is a timeline which displays time left, etc. There is a little component which displays time left, for example -00:05:00. When I click that component, it then displays video length, which should be shown at the sped up value. FE 12 min video at 2x speed should be 00:06:00.
### Actual behavior
Video length is shown at 1x speed, while time left is at correct speed.
### Log file
https://0x0.st/oNBZ.txt

**Comment by ValZapod** [comment]
> displays time left, for

It does not. It displays the timestamps (be it PTS + DTS for mp4 or durations for mkv or timing sei for Annex B streams or editlists in mp4).

**Comment by Tagvi** [comment]
Haha, I don't understand a single thing. Should I close this?

**Comment by ValZapod** [comment]
Okay, imagine you speed up video 100 times. What that would mean for 60 seconds video?

**Comment by Tagvi** [comment]
600 ms 🤔

**Comment by Hrxn** [comment]
A video file, with the property: length = 60s, wouldn't that still have property: length = 60s, regardless of playback speed? 😕

**Comment by ValZapod** [comment]
> 600 ms 🤔

That will be horribel UI... besides what if we have nanosecond duration? We do not have picoseconds to show x100...

**Comment by Tagvi** [comment]
Well, looks like what I said was either dumb or only makes sense to me, and I don't really care about this that much, so I will just close it.

**Comment by oltodosel** [comment]
You may use [the script](https://github.com/oltodosel/mpv-scripts#speed_osd3lua) that does that.
Does not work with OSC though, only OSD.
