### ISSUE TITLE
Nvidia Shield(andorid OS) can't see any media files after possible Android update/permission change policy associated with the update. 

### ISSUE THREAD

**Issue by miogpsrocks** [mpv-player/mpv#9995]
### Important Information

**Nvidia Shield(andorid OS) can't see any media files after possible Android update/permission change
VLC has the same issue. Looked up and had to manually in the APP settings tell VLC to ALLOW access to media Always" then it started working for VLC. 

However with MPV which is my normal go to video player, it did not have the option in the settings to " ALLOW ACCESS TO MEDIA ALWAYS" instead " only when using the app" however that did not work and the MPV player still can't see any media files. 

I have been using MPV for a long time without issue before this. The problem I think started with some kind of update to android or maybe the firmware in Nvidia Shield device.** 

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by philipl** [comment]
You need to file this issue against https://github.com/mpv-android/mpv-android/

**Comment by miogpsrocks** [comment]
Where exactly? The Android area you linked has no option to submit a trouble ticket .

**Comment by philipl** [comment]
Umm. It's just a normal github project. https://github.com/mpv-android/mpv-android/issues/new/choose
