### ISSUE TITLE
Best User Shaders?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#9996]
https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders
We have many user shaders, some are bad and some are good.
As a noob user - I don't understand all the details and I would like to get the BEST (recommended) one to use.
So far I only used [FSRCNN](https://github.com/igv/FSRCNN-TensorFlow/releases), the only reason is because of "research" like this: https://artoriuz.github.io/blog/mpv_upscaling.html which is full of test results and recommendations, but since it doesn't update that often, and we have new user shaders, I am now conflicted which one is better.

**Comment by Akemi** [comment]
we do not recommend any user shaders. test them and see for yourself, since everyone has different preferences.
