### ISSUE TITLE
Nvidia shield has an update and now MPV can't see any video files. 

### ISSUE THREAD

**Issue by miogpsrocks** [mpv-player/mpv#9998]
### Important Information

Nvidia shield has an update and now MPV can't see any video files. 
If you're not using git master or the latest release, update.

I mean all the file directly show up as empty. 

I had same issue with VLC but was able to resolve in the permissions. I don't get the same option with MPV. 

Also, why is there no trouble ticket option for the android area? 

I had to switch back to VLC cause of this issue and  spend all night trying to find some contact email 

Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by philipl** [comment]
As discussed in your previous issue, if you have an android specific problem, it needs to be filed in the mpv -android project, at the link I provided you previously.

https://github.com/mpv-android/mpv-android/issues/new/choose

**Comment by miogpsrocks** [comment]
> As discussed in your previous issue, if you have an android specific problem, it needs to be filed in the mpv -android project, at the link I provided you previously.
> 
> https://github.com/mpv-android/mpv-android/issues/new/choose

As previously discussed, the ANDROID area does not have a place to submit trouble tickets.  So tell me how to submit a ticket for the android or I will submit my ticket with a 1-star negative review on the google play store.

**Comment by CounterPillow** [comment]
We're shuddering in fear of your 1-star negative review.

**Comment by ValZapod** [comment]
> the ANDROID area does not have a place to submit trouble tickets.

But it does. Anyway just do not use google play, compile yourself.

**Comment by miogpsrocks** [comment]
Why don’t you get your shit together?

You software can’t even recognize a media file when it’s a media player. How stupid is that?

Sent from Mail for Windows

**Comment by ValZapod** [comment]
> you get your shit together?

It is not our shit, it is a separte project. We do care about android.
